Repository microsoftgraph/microsoft-graph-docs, pull requests merged in 2018-12, with the labels that each got.

#3552 DirectoryServices: Fix beta device doc bugs
  api-reference/beta/api/device-list-memberof.md
Labels: area: azure/AAD

#3391 update signin api
  api-reference/beta/resources/signin.md
Labels: area: azure/AAD

#3535 DirectoryService: Add v1.0 docs for device memberOf
  api-reference/v1.0/api/device-list-memberof.md
  api-reference/v1.0/resources/device.md
  concepts/changelog.md
Labels: area: azure/AAD

#3624 [Do not merge] - For review: adding landing page mockup for review
  concepts/images/index/angular.svg
  concepts/images/index/i_api-reference.svg
  concepts/images/index/i_api.svg
  concepts/images/index/i_blog.svg
  concepts/images/index/i_code-edit.svg
  concepts/images/index/i_get-started.svg
  concepts/images/index/i_investigate.svg
  concepts/images/index/i_library.svg
  concepts/images/index/i_overview.svg
  concepts/images/index/i_video.svg
  concepts/images/index/logo_NET.svg
  concepts/images/index/logo_nodejs.svg
  concepts/images/index/logo_php.svg
  concepts/images/index/logo_python.svg
  concepts/images/index/logo_react.svg
  concepts/images/index/logo_ruby.svg
  concepts/images/index/logo_windows.svg
  concepts/images/index/whatsnew-video.PNG
  concepts/index-existing.md
  concepts/index.yml
Labels: do not merge

#3618 Clarified get scenarios from create. Refactored repeated content.
  api-reference/beta/resources/message.md
  api-reference/v1.0/resources/message.md
  concepts/outlook-create-send-messages.md
  concepts/toc.yml
Labels: ready to merge

#3410 Move dataPolicyOperation to v1.0
  api-reference/beta/resources/users.md
  api-reference/v1.0/api/datapolicyoperation-get.md
  api-reference/v1.0/api/user-exportpersonaldata.md
  api-reference/v1.0/resources/datapolicyoperation.md
  concepts/changelog.md
Labels: ready to merge

#3626 Org contacts update for Beta
  api-reference/beta/api/orgcontact-get.md
  api-reference/beta/api/orgcontact-list.md
  api-reference/beta/resources/orgcontact.md
  api-reference/beta/resources/physicalofficeaddress.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: area: azure/AAD, ready to merge

#3643 Attempting to add dataPolicyOperation to beta and v1.0 menus.
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
Labels: ready to merge

#3578 Update Permissions for user-exportPersonalData and dataPolicyOperation-get
  api-reference/beta/api/datapolicyoperation-get.md
  api-reference/beta/api/user-exportpersonaldata.md
Labels: area: azure/AAD

#3679 Added note about sharing permissions not supporting subscribing.
  concepts/outlook-get-shared-contacts-folders.md
  concepts/outlook-get-shared-events-calendars.md
  concepts/outlook-share-messages-folders.md
Labels: do not merge

#3703 Removed redundant optional query parameters section.
  api-reference/beta/api/outlookcategory-delete.md
  api-reference/beta/api/outlookcategory-update.md
  api-reference/v1.0/api/outlookcategory-delete.md
  api-reference/v1.0/api/outlookcategory-update.md
Labels: do not merge
