Repository microsoftgraph/microsoft-graph-docs, pull requests merged in 2019-06, with the labels that each got.

#4732 AppAccessPolicy
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
  concepts/auth-limit-mailbox-access.md
  concepts/toc.yml
Labels: ready to merge

#3940 Followed sites docs
  api-reference/beta/api/site-follow.md
  api-reference/beta/api/site-get.md
  api-reference/beta/api/site-unfollow.md
  api-reference/beta/resources/site.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: changes requested, ready to merge

#4658 Documentation for Urgent Message and HostedContent support
  api-reference/beta/api/channel-post-messages.md
  api-reference/beta/api/chat-list-members.md
  api-reference/beta/api/chat-post-messages.md
  api-reference/beta/api/chatmessage-get.md
  api-reference/beta/api/chatmessage-list-hostedcontents.md
  api-reference/beta/api/chatmessage-list-replies.md
  api-reference/beta/api/chatmessage-post-replies.md
  api-reference/beta/api/chatmessagehostedcontent-get.md
  api-reference/beta/api/user-list-chats.md
  api-reference/beta/resources/channel.md
  api-reference/beta/resources/chatmessage.md
  api-reference/beta/resources/chatmessagehostedcontent.md
  api-reference/beta/resources/chatmessagereaction.md
  api-reference/beta/resources/conversationmember.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/team.md
  api-reference/beta/resources/teams-api-overview.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: changes requested, ready to merge

#4747 Gitissue4686
  api-reference/v1.0/api/user-list.md
Labels: ready to merge

#4755 Add revoke sign-in sessions docs to v1.0
  api-reference/v1.0/api/user-revokesigninsessions.md
  api-reference/v1.0/resources/user.md
  concepts/changelog.md
Labels: area: azure/AAD, ready to merge

#4688 EducationRosting API Updates
  api-reference/beta/api/educationassignment-delete.md
  api-reference/beta/api/educationcategory-delete.md
  api-reference/beta/api/educationcategory-get.md
  api-reference/beta/api/educationclass-delete-teachers.md
  api-reference/beta/api/educationclass-delta.md
  api-reference/beta/api/educationclass-list-assignments.md
  api-reference/beta/api/educationclass-list-categories.md
  api-reference/beta/api/educationschool-delete-users.md
  api-reference/beta/api/educationschool-delta.md
  api-reference/beta/api/educationschool-post-users.md
  api-reference/beta/api/educationsubmission-list-resources.md
  api-reference/beta/api/educationsubmission-recall.md
  api-reference/beta/api/educationuser-delta.md
  api-reference/beta/resources/educationclass.md
  api-reference/beta/resources/educationcourse.md
  api-reference/beta/resources/educationidentitydomain.md
  api-reference/beta/resources/educationidentitymatchingoptions.md
  api-reference/beta/resources/educationonpremisesinfo.md
  api-reference/beta/resources/educationschool.md
  api-reference/beta/resources/educationstudent.md
  api-reference/beta/resources/educationsynchronizationlicenseassignment.md
  api-reference/beta/resources/educationuser.md
  api-reference/beta/resources/enums.md
  api-reference/beta/toc.yml
  api-reference/v1.0/resources/educationuser.md
  api-reference/v1.0/resources/enums.md
  concepts/changelog.md
  concepts/delta-query-overview.md
Labels: area: edu, changes requested, ready to merge

#4628 added azure ATP note
  api-reference/beta/resources/security-api-overview.md
  api-reference/v1.0/resources/security-api-overview.md
Labels: area: Security, ready to merge

#4603 Fixing permissions for group directory operations
  api-reference/beta/api/group-delete.md
  api-reference/beta/api/group-delta.md
  api-reference/beta/api/group-get.md
  api-reference/beta/api/group-list-grouplifecyclepolicies.md
  api-reference/beta/api/group-list.md
  api-reference/beta/api/group-post-groups.md
  api-reference/beta/api/group-update.md
  api-reference/v1.0/api/group-delete.md
  api-reference/v1.0/api/group-delta.md
  api-reference/v1.0/api/group-get.md
  api-reference/v1.0/api/group-list-grouplifecyclepolicies.md
  api-reference/v1.0/api/group-list.md
  api-reference/v1.0/api/group-post-groups.md
  api-reference/v1.0/api/group-update.md
Labels: area: groups, ready to merge, review requested

#4391 Team discovery settings
  api-reference/beta/api/team-get.md
  api-reference/beta/api/team-post.md
  api-reference/beta/api/team-put-teams.md
  api-reference/beta/api/team-update.md
  api-reference/beta/resources/team.md
  api-reference/beta/resources/teamdiscoverysettings.md
  concepts/changelog.md
Labels: area: teams, ready to merge

#3899 Clarified response HTTP 202 for external partner.
  api-reference/beta/api/user-get.md
  api-reference/v1.0/api/user-get.md
Labels: do not merge

#4774 fix for git issue 4705
  api-reference/beta/api/user-post-users.md
  api-reference/beta/resources/invitation.md
  api-reference/v1.0/api/user-post-users.md
  api-reference/v1.0/resources/invitation.md
Labels: ready to merge

#4783 Fixes to user profile
  api-reference/beta/api/user-post-users.md
  api-reference/beta/api/user-revokesigninsessions.md
  api-reference/beta/api/user-update.md
  api-reference/beta/resources/user.md
  api-reference/v1.0/api/user-post-users.md
  api-reference/v1.0/api/user-update.md
  api-reference/v1.0/resources/user.md
  concepts/permissions-reference.md
Labels: area: azure/AAD, ready to merge

#4828 Update chatmessagereaction.md for emojis
  api-reference/beta/resources/chatmessagereaction.md
Labels: ready to merge

#4836 Add note that Teams SendMessage APIs are not for migration
  api-reference/beta/api/channel-post-messagereply.md
  api-reference/beta/api/channel-post-messages.md
Labels: ready to merge

#4777 Revert "Revert "Add revoke sign-in sessions docs to v1.0""
  api-reference/v1.0/api/user-revokesigninsessions.md
  api-reference/v1.0/resources/user.md
  concepts/changelog.md
  concepts/migrate-azure-ad-graph-method-differences.md
Labels: area: azure/AAD, ready to merge

#4833 Search folder changelog, application access policy links.
  concepts/auth/auth-concepts.md
  concepts/changelog.md
  concepts/permissions-reference.md
Labels: do not merge

#4420 Teams hosted images
  api-reference/beta/api/chatmessagehostedimage-get.md
  api-reference/beta/api/chatmessagehostedimage-getbytes.md
  api-reference/beta/api/chatmessagehostedimage-list-hostedimages.md
  api-reference/beta/resources/chatmessage.md
  api-reference/beta/resources/chatmessagehostedimage.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: area: teams, ready to merge

#4860 [Intune] Added Accessing the Graph API for Intune
  api-reference/beta/resources/privilegedidentitymanagement-root.md
  api-reference/v1.0/resources/intune-graph-overview.md
Labels: area: intune, ready to merge

#4884 [Intune] Updated Accessing the Graph API for Intune
  api-reference/v1.0/resources/intune-graph-overview.md
Labels: area: intune, ready to merge

#4719 Adding applicationtemplate resource and the methods
  api-reference/beta/api/applicationtemplate-get.md
  api-reference/beta/api/applicationtemplate-instantiate.md
  api-reference/beta/api/applicationtemplate-list.md
  api-reference/beta/resources/applicationserviceprincipal.md
  api-reference/beta/resources/applicationtemplate.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: area: app model, area: azure/AAD, ready to merge

#4892 [Intune] Added Accessing the Graph API for Intune 2
  api-reference/v1.0/resources/intune-graph-overview.md
Labels: area: intune, ready to merge

#4885 Adding embeded videos
  concepts/data-connect-overview.md
  concepts/deployments.md
  concepts/dynamics-business-central-concept-overview.md
  concepts/education-concept-overview.md
  concepts/excel-concept-overview.md
  concepts/extensibility-overview.md
  concepts/integrate-with-onenote.md
  concepts/intune-concept-overview.md
  concepts/json-batching.md
  concepts/notifications-concept-overview.md
  concepts/onedrive-concept-overview.md
  concepts/paging.md
  concepts/permissions-reference.md
  concepts/query-parameters.md
  concepts/reportroot-concept-overview.md
  concepts/security-concept-overview.md
  concepts/throttling.md
  concepts/webhooks.md
Labels: ready to merge

#4523 Adding Microsoft Graph Toolkit Docs
  concepts/toc.yml
  concepts/toolkit/components/agenda.md
  concepts/toolkit/components/images/mgt-agenda.PNG
  concepts/toolkit/components/images/mgt-people.png
  concepts/toolkit/components/login.md
  concepts/toolkit/components/people.md
  concepts/toolkit/components/person.md
  concepts/toolkit/components/tasks.md
  concepts/toolkit/overview.md
  concepts/toolkit/providers.md
  concepts/toolkit/providers/custom.md
  concepts/toolkit/providers/msal.md
  concepts/toolkit/providers/sharepoint.md
  concepts/toolkit/providers/teams.md
  concepts/toolkit/style.md
  concepts/toolkit/templates.md
Labels: do not merge

#4912 fix for git issue 4900
  api-reference/beta/api/identityriskevent-list.md
Labels: ready to merge

#4837 fix for git issue 4786
  api-reference/beta/api/group-get.md
  api-reference/beta/api/group-list.md
  api-reference/beta/api/group-post-groups.md
  api-reference/beta/resources/group.md
  api-reference/v1.0/api/group-get.md
  api-reference/v1.0/api/group-list.md
  api-reference/v1.0/api/group-post-groups.md
  api-reference/v1.0/resources/group.md
Labels: ready to merge

#4830 Adding postman page
  concepts/toc.yml
  concepts/use-postman.md
Labels: ready to merge

#4871 added a note to specify OData is only available on GET requests
  concepts/query-parameters.md
Labels: changes requested, review requested

#4838 fix for git issue 4771
  api-reference/beta/api/group-delete-members.md
  api-reference/v1.0/api/group-delete-members.md
Labels: ready to merge

#4699 Added scenario table to choose auth provider page
  concepts/sdks/choose-authentication-providers.md
Labels: ready to merge

#4937 Adding roles for Channel get messages in application context
  api-reference/beta/api/channel-get-message.md
  api-reference/beta/api/channel-get-messagereply.md
Labels: ready to merge

#4874 Add riskdetections api
  api-reference/beta/api/riskdetection-get.md
  api-reference/beta/api/riskdetection-list.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/riskdetection.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: changes requested, ready to merge

#4891 clarify user and group permissions
  api-reference/beta/api/directoryobject-checkmembergroups.md
  api-reference/beta/api/directoryobject-getmembergroups.md
  api-reference/beta/api/group-checkmembergroups.md
  api-reference/beta/api/user-checkmembergroups.md
  api-reference/beta/api/user-getmembergroups.md
  api-reference/v1.0/api/directoryobject-checkmembergroups.md
  api-reference/v1.0/api/directoryobject-getmembergroups.md
  api-reference/v1.0/api/group-checkmembergroups.md
  api-reference/v1.0/api/user-checkmembergroups.md
  api-reference/v1.0/api/user-getmembergroups.md
Labels: area: groups, ready to merge

#4953 Cleaned up social intel node.
  api-reference/beta/resources/social-overview.md
  api-reference/beta/toc.yml
  concepts/overview-major-services.md
  concepts/social-intel-concept-overview.md
  concepts/toc.yml
Labels: resolved: awaiting prod deployment
