Repository microsoftgraph/microsoft-graph-docs, pull requests merged in 2019-01, with the labels that each got.

#3704 Made function parameters section heading and table headers consistent, following template spec.
  api-reference/beta/api/driveitem-delta.md
  api-reference/beta/api/driveitem-search.md
  api-reference/beta/api/itemactivity-getbyinterval.md
  api-reference/beta/api/outlookuser-supportedtimezones.md
  api-reference/beta/api/user-reminderview.md
  api-reference/v1.0/api/driveitem-delta.md
  api-reference/v1.0/api/driveitem-search.md
  api-reference/v1.0/api/user-reminderview.md
Labels: do not merge

#3688 Clarified some message properties are updateable.
  api-reference/beta/api/message-update.md
  api-reference/beta/resources/message.md
  api-reference/v1.0/api/message-update.md
  api-reference/v1.0/resources/message.md
Labels: do not merge

#3712 Update group-list-transitivemembers.md
  api-reference/beta/api/group-list-transitivemembers.md
Labels: area: azure/AAD, ready to merge

#3698 Update organization for issue 3654 and other fixes
  api-reference/beta/api/organization-get.md
  api-reference/beta/api/organization-update.md
  api-reference/beta/resources/organization.md
  api-reference/v1.0/api/organization-get.md
  api-reference/v1.0/api/organization-update.md
  api-reference/v1.0/resources/organization.md
Labels: ready to merge

#3694 Update Reponse details for exportpersonaldata for v1.0
  api-reference/v1.0/api/user-exportpersonaldata.md
Labels: ready to merge

#3695 Update reponse details for exportpersonaldata for beta
  api-reference/beta/api/user-exportpersonaldata.md
Labels: ready to merge

#3763 Example request typo
  api-reference/beta/api/user-post-users.md
Labels: ready to merge

#3795 Update group.md
  api-reference/beta/resources/group.md
Labels: ready to merge

#3797 Update changelog.md
  concepts/changelog.md
Labels: ready to merge

#3803 Added Send Outlook message from another user topic
  concepts/images/outlook-sent-on-behalf.png
  concepts/outlook-mail-concept-overview.md
  concepts/outlook-send-mail-from-other-user.md
  concepts/toc.yml
Labels: ready to merge

#3811 (Ready to merge) Document configuring Word/Excel/PowerPoint/PDF tabs in Teams
  concepts/teams-configuring-builtin-tabs.md
Labels: ready to merge

#3818 [Ready to merge] Update device-list-transitivememberof.md - fixes #3817
  api-reference/beta/api/device-list-transitivememberof.md
Labels: area: azure/AAD

#3707 Updates to National Cloud Landing Page
  concepts/deployments.md
  concepts/images/Checkmark success.png
Labels: ready to merge

#3824 Group creation members example
  api-reference/beta/api/group-post-groups.md
  api-reference/v1.0/api/group-post-groups.md
Labels: area: azure/AAD

#3842 Removing extraneous line feeds
  concepts/changelog.md
Labels: ready to merge

#3851 Update passwordprofile in v1.0
  api-reference/v1.0/resources/passwordprofile.md
  concepts/changelog.md
Labels: area: azure/AAD

#3849 Update group-post-groups.md
  api-reference/v1.0/api/group-post-groups.md
Labels: area: azure/AAD, ready to merge

#3757 Add office365 active and inactive properties in reports graph api getoffice365servicesusercounts
  api-reference/beta/api/reportroot-getoffice365servicesusercounts.md
  api-reference/beta/resources/office365servicesusercounts.md
  concepts/changelog.md
  concepts/deployments.md
Labels: do not merge

#3827 Update sortOrderIndex value in JSON representation
  api-reference/beta/api/teamstab-add.md
  api-reference/beta/api/teamstab-get.md
  api-reference/beta/api/teamstab-list.md
  api-reference/beta/api/teamstab-update.md
  api-reference/beta/resources/teamstab.md
  api-reference/v1.0/api/teamstab-add.md
  api-reference/v1.0/api/teamstab-get.md
  api-reference/v1.0/api/teamstab-list.md
  api-reference/v1.0/api/teamstab-update.md
  api-reference/v1.0/resources/teamstab.md
Labels: review requested

#3819 Updates to Team Templates Documentation
  api-reference/beta/api/team-post.md
  api-reference/beta/resources/team.md
  api-reference/beta/resources/teamspecialization.md
  concepts/changelog.md
Labels: changes requested

#3868 Update user docs with createdDateTime
  api-reference/beta/resources/user.md
  concepts/changelog.md
Labels: area: azure/AAD, ready to merge

#3547 Ready to merge: GBL graph promotion from beta to v1.0
  api-reference/v1.0/api/group-get.md
  api-reference/v1.0/api/group-list.md
  api-reference/v1.0/resources/group.md
  api-reference/v1.0/resources/groups-overview.md
  api-reference/v1.0/resources/licenseassignmentstate.md
  api-reference/v1.0/resources/user.md
  concepts/changelog.md
Labels: changes requested, ready to merge

#3741 Adding User properties and enabling transitive Member search in v1.0
  concepts/changelog.md
Labels: ready to merge

#3888 Adding User properties and Transitive search to v1.0
  api-reference/v1.0/api/device-list-transitivememberof.md
  api-reference/v1.0/api/group-list-transitivememberof.md
  api-reference/v1.0/api/group-list-transitivemembers.md
  api-reference/v1.0/api/user-list-transitivememberof.md
  api-reference/v1.0/resources/device.md
  api-reference/v1.0/resources/group.md
  api-reference/v1.0/resources/user.md
Labels: ready to merge
