Repository microsoftgraph/microsoft-graph-docs, pull requests merged in 2019-09, with the labels that each got.

#5599 Update broken link
  api-reference/v1.0/resources/teams-api-overview.md
  concepts/teams-concept-overview.md
Labels: external

#5577 Update tablecolumn.md
  api-reference/beta/resources/workbooktablecolumn.md
  api-reference/v1.0/api/table-list-columns.md
  api-reference/v1.0/api/table-post-columns.md
  api-reference/v1.0/api/tablecolumn-get.md
  api-reference/v1.0/api/tablecolumn-list.md
  api-reference/v1.0/api/tablecolumn-update.md
  api-reference/v1.0/api/tablecolumncollection-add.md
  api-reference/v1.0/api/tablecolumncollection-itemat.md
  api-reference/v1.0/resources/table.md
  api-reference/v1.0/resources/workbooktablecolumn.md
Labels: changes requested

#5439 PhoebeYuan reply comment update
  api-reference/beta/api/workbook-list-comments.md
  api-reference/beta/api/workbookcomment-get.md
  api-reference/beta/api/workbookcomment-list-replies.md
  api-reference/beta/api/workbookcomment-post-replies.md
  api-reference/beta/api/workbookcommentreply-get.md
  api-reference/beta/resources/workbookcomment.md
  api-reference/beta/resources/workbookcommentreply.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/workbook-list-comments.md
  api-reference/v1.0/api/workbookcomment-get.md
  api-reference/v1.0/api/workbookcomment-list-replies.md
  api-reference/v1.0/api/workbookcomment-post-replies.md
  api-reference/v1.0/api/workbookcommentreply-get.md
  api-reference/v1.0/resources/workbookcomment.md
  api-reference/v1.0/resources/workbookcommentreply.md
  api-reference/v1.0/toc.yml
Labels: ready to merge

#4850 Add {tenant} Replacement Token to Token URL
  concepts/auth-v2-user.md
Labels: ready to merge

#5634 Added scenarios attributes.
  concepts/azuread-identity-access-management-concept-overview.md
  concepts/azuread-users-concept-overview.md
  concepts/booking-concept-overview.md
  concepts/cross-device-concept-overview.md
  concepts/data-connect-concept-overview.md
  concepts/data-connect-overview.md
  concepts/education-concept-overview.md
  concepts/excel-concept-overview.md
  concepts/integrate-with-onenote.md
  concepts/notifications-concept-overview.md
  concepts/office365-groups-concept-overview.md
  concepts/onedrive-concept-overview.md
  concepts/outlook-calendar-concept-overview.md
  concepts/outlook-contacts-concept-overview.md
  concepts/outlook-mail-concept-overview.md
  concepts/overview-major-services.md
  concepts/overview.md
  concepts/paging.md
  concepts/permissions-reference.md
  concepts/query-parameters.md
  concepts/reportroot-concept-overview.md
  concepts/sdks/sdks-overview.md
  concepts/security-concept-overview.md
  concepts/sharepoint-concept-overview.md
  concepts/social-intel-concept-overview.md
  concepts/teams-concept-overview.md
  concepts/toolkit/overview.md
  concepts/traverse-the-graph.md
  concepts/use-the-api.md
Labels: ready to merge

#5276 Paywu/2743 updates and changelog
  api-reference/beta/api/application-post-calls.md
  api-reference/beta/api/application-post-onlinemeetings.md
  api-reference/beta/api/audioroutinggroup-delete.md
  api-reference/beta/api/audioroutinggroup-get.md
  api-reference/beta/api/audioroutinggroup-update.md
  api-reference/beta/api/call-answer.md
  api-reference/beta/api/call-cancelmediaprocessing.md
  api-reference/beta/api/call-changescreensharingrole.md
  api-reference/beta/api/call-delete.md
  api-reference/beta/api/call-get.md
  api-reference/beta/api/call-list-audioroutinggroups.md
  api-reference/beta/api/call-list-participants.md
  api-reference/beta/api/call-mute.md
  api-reference/beta/api/call-post-audioroutinggroups.md
  api-reference/beta/api/call-record.md
  api-reference/beta/api/call-redirect.md
  api-reference/beta/api/call-reject.md
  api-reference/beta/api/call-subscribetotone.md
  api-reference/beta/api/call-transfer.md
  api-reference/beta/api/call-unmute.md
  api-reference/beta/api/call-updatemetadata.md
  api-reference/beta/api/onlinemeeting-get.md
  api-reference/beta/api/participant-configuremixer.md
  api-reference/beta/api/participant-get.md
  api-reference/beta/api/participant-invite.md
  api-reference/beta/api/participant-mute.md
  api-reference/beta/api/participant-muteall.md
  api-reference/beta/includes/snippets/javascript/create-call-from-application-javascript-snippets.md
  api-reference/beta/resources/call.md
  api-reference/beta/resources/callmediastate.md
  api-reference/beta/resources/inviteparticipantsoperation.md
  api-reference/beta/resources/meetingparticipants.md
  api-reference/beta/resources/onlinemeeting.md
  concepts/changelog.md
Labels: beta, changes requested, ready to merge

#5283 Docs update for new mailboxsettings properties
  api-reference/beta/api/user-get-mailboxsettings.md
  api-reference/beta/api/user-update-mailboxsettings.md
  api-reference/beta/resources/mailboxsettings.md
  api-reference/beta/resources/workinghours.md
  api-reference/v1.0/resources/mailboxsettings.md
  api-reference/v1.0/resources/workinghours.md
  concepts/changelog.md
Labels: changes requested, review requested

#5453 updating toolkit docs with people picker component
  concepts/toc.yml
  concepts/toolkit/components/images/mgt-people-picker-image.png
  concepts/toolkit/components/people-picker.md
Labels: ready to merge

#5649 Added first item for September in what's new.
  concepts/changelog.md
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: do not merge

#5353 Update chat-list.md
  api-reference/beta/api/chat-list.md
Labels: external, ready to merge

#5410 Proactive messaging how-to doc
  concepts/teams-proactive-messaging.md
  concepts/toc.yml
Labels: area: teams, ready to merge

#5495 checkmemberobjects apis
  api-reference/beta/api/device-checkmemberobjects.md
  api-reference/beta/api/group-checkmemberobjects.md
  api-reference/beta/api/serviceprincipal-checkmemberobjects.md
  api-reference/beta/api/user-checkmemberobjects.md
  api-reference/beta/resources/device.md
  api-reference/beta/resources/group.md
  api-reference/beta/resources/serviceprincipal.md
  api-reference/beta/resources/user.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: awaiting internal response, ready to merge

#5688 Correcting example
  api-reference/beta/api/educationsynchronizationprofile-post.md
Labels: area: edu, bug: documentation, ready to merge

#5687 Added Outlook-related resource throttling information
  concepts/throttling.md
Labels: ready to merge

#5618 Make getting raw contents of file and item attachments, and MIME content of a message available in v1.
  api-reference/beta/api/attachment-get.md
  api-reference/beta/api/message-get.md
  api-reference/beta/resources/attachment.md
  api-reference/beta/resources/fileattachment.md
  api-reference/beta/resources/itemattachment.md
  api-reference/beta/resources/mail-api-overview.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/attachment-get.md
  api-reference/v1.0/api/message-get.md
  api-reference/v1.0/resources/attachment.md
  api-reference/v1.0/resources/fileattachment.md
  api-reference/v1.0/resources/itemattachment.md
  api-reference/v1.0/resources/mail-api-overview.md
  api-reference/v1.0/toc.yml
  concepts/changelog.md
  concepts/outlook-get-mime-message.md
  concepts/toc.yml
Labels: do not merge

#5165 Update new quarantine reasons
  api-reference/beta/resources/synchronization-quarantine.md
Labels: ready to merge

#5663 Add changelog for synchronizationQuarantine reason
  concepts/changelog.md
Labels: ready to merge

#5698 Update teams-protected-apis.md
  concepts/teams-protected-apis.md
Labels: ready to merge

#5693 Deprecate /teams/id/apps
  api-reference/beta/resources/team.md
Labels: ready to merge

#5633 Policy permission updates
  api-reference/beta/api/policy-get.md
  api-reference/beta/api/policy-list-appliesto.md
  api-reference/beta/api/policy-list-assigned.md
  api-reference/beta/api/policy-list.md
  api-reference/beta/resources/workbookcomment.md
  api-reference/beta/resources/workbookcommentreply.md
  concepts/permissions-reference.md
Labels: area: azure/AAD, ready to merge

#4128 Team.primarychannel
  api-reference/beta/resources/team.md
  concepts/changelog.md
Labels: area: teams, ready to merge

#5646 Added Preeti's changes
  api-reference/beta/resources/security-api-overview.md
  api-reference/beta/resources/security-error-codes.md
  api-reference/v1.0/resources/security-api-overview.md
Labels: ready to merge

#5703 Resolving minor doc issues reported by customers
  concepts/webhooks.md
Labels: area: webhooks, ready to merge

#5717 fix for git issue 4146
  api-reference/beta/api/governancerolesetting-update.md
Labels: ready to merge

#5726 Translate Exchange id changelog
  concepts/changelog.md
Labels: ready to merge

#5746 Fix application permissions for chat messages
  api-reference/beta/api/chatmessage-list.md
Labels: ready to merge

#5731 tagged for custom reports
  concepts/auth-cloudsolutionprovider.md
  concepts/auth-register-app-v2.md
  concepts/auth-v2-service.md
  concepts/auth-v2-user.md
  concepts/auth/auth-concepts.md
  concepts/auth/index.yml
  concepts/best-practices-concept.md
  concepts/delta-query-events.md
  concepts/delta-query-groups.md
  concepts/delta-query-messages.md
  concepts/delta-query-overview.md
  concepts/delta-query-users.md
  concepts/extensibility-open-users.md
  concepts/extensibility-overview.md
  concepts/extensibility-schema-groups.md
  concepts/json-batching.md
  concepts/paging.md
  concepts/permissions-reference.md
  concepts/query-parameters.md
  concepts/throttling.md
  concepts/traverse-the-graph.md
  concepts/use-the-api.md
  concepts/webhooks-outlook-authz.md
  concepts/webhooks.md
Labels: ready to merge

#5744 Added new tutorials
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
  concepts/toc.yml
  concepts/tutorials.md
Labels: ready to merge

#5655 Add synchronizationJobSettings in MsGraph docs
  api-reference/beta/api/synchronization-synchronizationjob-get.md
  api-reference/beta/resources/synchronization-synchronizationjob.md
Labels: ready to merge

#5656 Add synchronizationJobSettings to Identity synchronizationJob resource
  concepts/changelog.md
Labels: ready to merge

#5766 Removing routes that don't exist
  api-reference/beta/api/chatmessage-list-replies.md
  api-reference/beta/api/chatmessage-post-replies.md
Labels: area: teams, ready to merge

#5762 sharepoint list sites: fixed Odata query string parameters
  api-reference/beta/api/site-list.md
Labels: ready to merge

#5763 sharepoitn site search: fix odata query parameter
  api-reference/beta/api/site-search.md
Labels: ready to merge

#5773 Intune app only auth perms doc update
  api-reference/v1.0/resources/intune-graph-overview.md
  concepts/changelog.md
  concepts/permissions-reference.md
Labels: ready to merge

#5539 Update teamMemberSettings resource to include allowCreatePrivateChannels
  api-reference/beta/resources/teammembersettings.md
  concepts/changelog.md
Labels: area: teams, ready to merge

#5686 intune 1909 v1
  api-reference/v1.0/api/intune-apps-ioslobapp-create.md
  api-reference/v1.0/api/intune-apps-ioslobapp-delete.md
  api-reference/v1.0/api/intune-apps-ioslobapp-get.md
  api-reference/v1.0/api/intune-apps-ioslobapp-list.md
  api-reference/v1.0/api/intune-apps-ioslobapp-update.md
  api-reference/v1.0/api/intune-apps-iosstoreapp-create.md
  api-reference/v1.0/api/intune-apps-iosstoreapp-delete.md
  api-reference/v1.0/api/intune-apps-iosstoreapp-get.md
  api-reference/v1.0/api/intune-apps-iosstoreapp-list.md
  api-reference/v1.0/api/intune-apps-iosstoreapp-update.md
  api-reference/v1.0/api/intune-apps-managedioslobapp-create.md
  api-reference/v1.0/api/intune-apps-managedioslobapp-delete.md
  api-reference/v1.0/api/intune-apps-managedioslobapp-get.md
  api-reference/v1.0/api/intune-apps-managedioslobapp-list.md
  api-reference/v1.0/api/intune-apps-managedioslobapp-update.md
  api-reference/v1.0/api/intune-apps-managediosstoreapp-create.md
  api-reference/v1.0/api/intune-apps-managediosstoreapp-delete.md
  api-reference/v1.0/api/intune-apps-managediosstoreapp-get.md
  api-reference/v1.0/api/intune-apps-managediosstoreapp-list.md
  api-reference/v1.0/api/intune-apps-managediosstoreapp-update.md
  api-reference/v1.0/resources/intune-apps-ioslobapp.md
  api-reference/v1.0/resources/intune-apps-iosminimumoperatingsystem.md
  api-reference/v1.0/resources/intune-apps-iosstoreapp.md
  api-reference/v1.0/resources/intune-apps-managedioslobapp.md
  api-reference/v1.0/resources/intune-apps-managediosstoreapp.md
  concepts/changelog.md
Labels: ready to merge

#5645 User identities
  api-reference/beta/api/user-list.md
  api-reference/beta/api/user-post-users.md
  api-reference/beta/api/user-update.md
  api-reference/beta/resources/objectidentity.md
  api-reference/beta/resources/user.md
  api-reference/beta/resources/users.md
  concepts/changelog.md
  concepts/migrate-azure-ad-graph-property-differences.md
Labels: area: azure/AAD, ready to merge

#5813 Adding two new MS Learn modules
  concepts/tutorials.md
Labels: ready to merge

#5802 Update group-list-members.md
  api-reference/v1.0/api/group-list-members.md
Labels: ready to merge

#5654 Update private channel docs
  api-reference/beta/api/channel-list.md
  api-reference/beta/api/channel-patch.md
  api-reference/beta/api/channel-post.md
  api-reference/beta/toc.yml
Labels: area: teams, ready to merge

#5786 fix for git issue 5440
  api-reference/beta/api/user-get.md
Labels: ready to merge

#5818 Added What's new, translateExchangeIds in TOC.
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
  concepts/whats-new-overview.md
Labels: do not merge

#5765 Resolving customer issues
  concepts/delta-query-overview.md
Labels: ready to merge

#5839 Adding gif as supported file type.
  concepts/docfx.json
Labels: ready to merge

#5841 Added Note per #5828.
  api-reference/beta/resources/teams-api-overview.md
Labels: area: teams, ready to merge

#5804 hosted content
  api-reference/beta/api/chatmessage-list-chatmessagehostedcontents.md
  api-reference/beta/api/chatmessagehostedcontent-get.md
  api-reference/beta/api/chatmessagehostedimage-get.md
  api-reference/beta/api/chatmessagehostedimage-getbytes.md
  api-reference/beta/api/chatmessagehostedimage-list-hostedimages.md
  api-reference/beta/resources/chatmessage.md
  api-reference/beta/resources/chatmessagehostedcontent.md
  api-reference/beta/resources/chatmessagehostedimage.md
  api-reference/beta/toc.yml
Labels: area: teams, ready to merge

#5390 Add docs for restore, orientation, sha256, deferCommit, and pendingOperations
  api-reference/beta/api/driveitem-createuploadsession.md
  api-reference/beta/api/driveitem-get.md
  api-reference/beta/api/driveitem-list-thumbnails.md
  api-reference/beta/api/driveitem-restore.md
  api-reference/beta/resources/driveitem.md
  api-reference/beta/resources/driveitemuploadableproperties.md
  api-reference/beta/resources/geocoordinates.md
  api-reference/beta/resources/hashes.md
  api-reference/beta/resources/pendingcontentupdate.md
  api-reference/beta/resources/pendingoperations.md
  api-reference/beta/resources/photo.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: ready to merge
