Repository microsoftgraph/microsoft-graph-docs, pull requests merged in 2019-11, with the labels that each got.

#5044 Initial commit for Information Protection documentation
  api-reference/beta/api/informationprotectionlabel-evaluateapplication.md
  api-reference/beta/api/informationprotectionlabel-evaluateclassificationresults.md
  api-reference/beta/api/informationprotectionlabel-evaluateremoval.md
  api-reference/beta/api/informationprotectionlabel-extractlabel.md
  api-reference/beta/api/informationprotectionlabel-get.md
  api-reference/beta/api/informationprotectionpolicy-list-labels.md
  api-reference/beta/resources/addcontentfooteraction.md
  api-reference/beta/resources/addcontentheaderaction.md
  api-reference/beta/resources/addwatermarkaction.md
  api-reference/beta/resources/applylabelaction.md
  api-reference/beta/resources/classificationresult.md
  api-reference/beta/resources/contentinfo.md
  api-reference/beta/resources/customaction.md
  api-reference/beta/resources/downgradejustification.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/informationprotectionaction.md
  api-reference/beta/resources/informationprotectioncontentlabel.md
  api-reference/beta/resources/informationprotectionlabel.md
  api-reference/beta/resources/justifyaction.md
  api-reference/beta/resources/labeldetails.md
  api-reference/beta/resources/labelingoptions.md
  api-reference/beta/resources/metadataaction.md
  api-reference/beta/resources/protectadhocaction.md
  api-reference/beta/resources/protectbytemplateaction.md
  api-reference/beta/resources/protectdonotforwardaction.md
  api-reference/beta/resources/recommendlabelaction.md
  api-reference/beta/resources/removecontentfooteraction.md
  api-reference/beta/resources/removecontentheaderaction.md
  api-reference/beta/resources/removeprotectionaction.md
  api-reference/beta/resources/removewatermarkaction.md
  api-reference/beta/toc.yml
  concepts/changelog.md
  concepts/information-protection-overview.md
  concepts/toc.yml
Labels: content review, ready to merge

#6027 SET Place API
  api-reference/beta/api/place-update.md
  api-reference/beta/resources/place.md
  api-reference/beta/resources/room.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: content review

#6176 Add changelog and update to Major services topic for Profile.
  concepts/changelog.md
  concepts/overview-major-services.md
Labels: ready to merge

#6180 Origin/sochowdh Calendar API documentation changes
  api-reference/beta/api/calendar-post-events.md
  api-reference/beta/api/user-post-events.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: do not merge

#6185 Update application.md
  api-reference/v1.0/resources/application.md
Labels: ready to merge

#6159 Added details of new application and service principal permissions
  concepts/changelog.md
  concepts/permissions-reference.md
Labels: area: app model, ready to merge

#6195 Updates to broken links in the concepts doc
  concepts/information-protection-overview.md
Labels: ready to merge

#6200 Updated Online Meeting Beta Permissions and other Details
  api-reference/beta/api/application-post-onlinemeetings.md
  api-reference/beta/api/onlinemeeting-get.md
  api-reference/beta/resources/audioconferencing.md
  api-reference/beta/resources/onlinemeeting.md
Labels: ready to merge

#6198 Adding documentation for Class Settings to expose settings specific to Team's of type Class
  api-reference/beta/resources/team.md
  api-reference/beta/resources/teamclasssettings.md
  concepts/changelog.md
Labels: area: teams, ready to merge

#6212 Update to password credential
  api-reference/beta/resources/passwordcredential.md
  api-reference/v1.0/resources/passwordcredential.md
Labels: ready to merge

#6280 Make even clearer IDs change on sending draft.
  api-reference/beta/resources/mail-api-overview.md
  api-reference/v1.0/resources/mail-api-overview.md
Labels: do not merge

#6278 Update on Message Search (Personal Accounts, and attachements)
  concepts/search-concept-messages.md
Labels: content review, ready to merge

#5511 new groups permissions scopes
  api-reference/beta/api/directoryobject-checkmembergroups.md
  api-reference/beta/api/directoryobject-getmembergroups.md
  api-reference/beta/api/group-checkmembergroups.md
  api-reference/beta/api/group-delete-members.md
  api-reference/beta/api/group-getmembergroups.md
  api-reference/beta/api/group-list-memberof.md
  api-reference/beta/api/group-post-groups.md
  api-reference/beta/api/group-post-members.md
  api-reference/beta/api/user-checkmembergroups.md
  api-reference/beta/api/user-getmembergroups.md
  api-reference/v1.0/api/directoryobject-checkmembergroups.md
  api-reference/v1.0/api/directoryobject-getmembergroups.md
  api-reference/v1.0/api/group-checkmembergroups.md
  api-reference/v1.0/api/group-delete-members.md
  api-reference/v1.0/api/group-getmembergroups.md
  api-reference/v1.0/api/group-list-memberof.md
  api-reference/v1.0/api/group-post-groups.md
  api-reference/v1.0/api/group-post-members.md
  api-reference/v1.0/api/user-checkmembergroups.md
  api-reference/v1.0/api/user-getmembergroups.md
  concepts/changelog.md
  concepts/permissions-reference.md
Labels: ready to merge

#6312 Update steps to assign roles in Azure portal.
  concepts/security-authorization.md
Labels: do not merge

#6318 Add creationType documentation
  api-reference/beta/resources/user.md
  api-reference/v1.0/resources/user.md
  concepts/changelog.md
Labels: area: azure/AAD, ready to merge

#5750 added PasswordSSO docs
  api-reference/beta/api/serviceprincipal-createpasswordsinglesignoncredentials.md
  api-reference/beta/api/serviceprincipal-deletepasswordsinglesignoncredentials.md
  api-reference/beta/api/serviceprincipal-getpasswordsinglesignoncredentials.md
  api-reference/beta/api/serviceprincipal-updatepasswordsinglesignoncredentials.md
  api-reference/beta/resources/credential.md
  api-reference/beta/resources/passwordsinglesignoncredentialset.md
  api-reference/beta/resources/serviceprincipal.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: area: azure/AAD, ready to merge

#6307 Update identityprotection root
  api-reference/beta/resources/identityprotection-root.md
Labels: content review, ready to merge

#6313 Migration and B2C identities fixes
  api-reference/beta/api/user-post-users.md
  api-reference/beta/resources/objectidentity.md
  api-reference/beta/resources/user.md
  api-reference/v1.0/resources/user.md
  concepts/extensibility-overview.md
  concepts/migrate-azure-ad-graph-feature-differences.md
  concepts/migrate-azure-ad-graph-method-differences.md
  concepts/migrate-azure-ad-graph-property-differences.md
  concepts/migrate-azure-ad-graph-resource-differences.md
Labels: area: app model, area: azure/AAD, content review, ready to merge

#6308 Adding Mail.ReadBasic to v1.0
  api-reference/beta/api/subscription-delete.md
  api-reference/beta/api/subscription-get.md
  api-reference/beta/api/subscription-post-subscriptions.md
  api-reference/beta/api/subscription-update.md
  api-reference/v1.0/api/mailfolder-delta.md
  api-reference/v1.0/api/mailfolder-get.md
  api-reference/v1.0/api/mailfolder-list-childfolders.md
  api-reference/v1.0/api/mailfolder-list-messages.md
  api-reference/v1.0/api/message-delta.md
  api-reference/v1.0/api/message-get.md
  api-reference/v1.0/api/subscription-delete.md
  api-reference/v1.0/api/subscription-get.md
  api-reference/v1.0/api/subscription-post-subscriptions.md
  api-reference/v1.0/api/subscription-update.md
  api-reference/v1.0/api/user-list-mailfolders.md
  api-reference/v1.0/api/user-list-messages.md
  concepts/changelog.md
  concepts/permissions-reference.md
Labels: changes requested, ready to merge

#6336 update access reviews businessflowtemplates
  api-reference/beta/api/accessreview-list.md
  api-reference/beta/api/businessflowtemplate-list.md
  api-reference/beta/includes/snippets/csharp/get-accessreviews-csharp-snippets.md
  api-reference/beta/includes/snippets/javascript/get-accessreviews-javascript-snippets.md
  api-reference/beta/includes/snippets/objc/get-accessreviews-objc-snippets.md
  api-reference/beta/resources/accessreview.md
  api-reference/beta/resources/businessflowtemplate.md
Labels: ready to merge

#6327 bug fix for incorrect response in example
  api-reference/beta/api/user-post-users.md
Labels: area: azure/AAD, area: users, ready to merge

#6309 Adding app-only permissions to read CA and named location policies
  api-reference/beta/api/conditionalaccesspolicy-get.md
  api-reference/beta/api/conditionalaccessroot-list-namedlocations.md
  api-reference/beta/api/conditionalaccessroot-list-policies.md
  api-reference/beta/api/countrynamedlocation-get.md
  api-reference/beta/api/ipnamedlocation-get.md
  api-reference/beta/api/namedlocation-get.md
  concepts/changelog.md
Labels: content review, ready to merge

#6331 Added callout about signup requirement for Search API
  api-reference/beta/api/connectionoperation-get.md
  api-reference/beta/api/external-post-connections.md
  api-reference/beta/api/externalconnection-delete.md
  api-reference/beta/api/externalconnection-get.md
  api-reference/beta/api/externalconnection-list.md
  api-reference/beta/api/externalconnection-post-schema.md
  api-reference/beta/api/externalconnection-put-items.md
  api-reference/beta/api/externalconnection-update.md
  api-reference/beta/api/externalitem-delete.md
  api-reference/beta/api/externalitem-update.md
  api-reference/beta/api/schema-get.md
  api-reference/beta/api/search-get.md
  api-reference/beta/api/search-query.md
  api-reference/beta/resources/acl.md
  api-reference/beta/resources/configuration.md
  api-reference/beta/resources/connectionoperation.md
  api-reference/beta/resources/errordetail.md
  api-reference/beta/resources/externalconnection.md
  api-reference/beta/resources/externalfile.md
  api-reference/beta/resources/externalitem.md
  api-reference/beta/resources/indexing-api-overview.md
  api-reference/beta/resources/innererrordetail.md
  api-reference/beta/resources/property.md
  api-reference/beta/resources/schema.md
  api-reference/beta/resources/search-api-overview.md
  api-reference/beta/resources/search.md
  api-reference/beta/resources/searchhit.md
  api-reference/beta/resources/searchhitscontainer.md
  api-reference/beta/resources/searchquery.md
  api-reference/beta/resources/searchquerystring.md
  api-reference/beta/resources/searchrequest.md
  api-reference/beta/resources/searchresponse.md
  api-reference/beta/resources/searchresult.md
  api-reference/includes/search-api-preview-signup.md
  concepts/search-concept-custom-types.md
  concepts/search-concept-events.md
  concepts/search-concept-files.md
  concepts/search-concept-messages.md
  concepts/search-concept-overview.md
  concepts/search-index-manage-connections.md
  concepts/search-index-manage-items.md
  includes/search-api-preview-signup.md
Labels: ready to merge

#6126 Improved (code) sample
  api-reference/beta/resources/intune-deviceconfig-windows10networkproxyserver.md
  api-reference/v1.0/resources/educationuser.md
  api-reference/v1.0/resources/intune-deviceconfig-windows10networkproxyserver.md
  concepts/delta-query-overview.md
Labels: ready to merge

#6258 Remove file and add redirect.
  .openpublishing.redirection.json
  concepts/associate-account.md
Labels: ready to merge

#6332 Paywu/update call answer permissions
  api-reference/beta/api/call-answer.md
Labels: ready to merge

#6357 fix for git issue 5922
  api-reference/beta/api/subscribedsku-list.md
Labels: ready to merge

#6358 More specific on permission scope
  concepts/permissions-reference.md
Labels: ready to merge

#6323 Concept topic about online meetings in Outlook.
  api-reference/beta/resources/event.md
  concepts/outlook-calendar-concept-overview.md
  concepts/outlook-calendar-online-meetings.md
  concepts/toc.yml
Labels: do not merge

#6371 checkobjects v1
  api-reference/v1.0/api/device-checkmemberobjects.md
  api-reference/v1.0/api/group-checkmemberobjects.md
  api-reference/v1.0/api/user-checkmemberobjects.md
  api-reference/v1.0/resources/device.md
  api-reference/v1.0/resources/group.md
  api-reference/v1.0/resources/user.md
  api-reference/v1.0/toc.yml
  concepts/changelog.md
Labels: ready to merge

#6368 Updated the Calling Permission Notes and Online Meeting Permissions
  concepts/permissions-reference.md
Labels: awaiting internal response, ready to merge

#6394 Add new driveItem get route
  api-reference/beta/api/driveitem-get.md
  api-reference/beta/resources/channel.md
  concepts/changelog.md
Labels: area: teams, ready to merge

#6062 Communications Recording APIs
  api-reference/beta/api/application-post-calls.md
  api-reference/beta/api/call-answer.md
  api-reference/beta/api/call-get.md
  api-reference/beta/api/call-record.md
  api-reference/beta/api/call-subscribetotone.md
  api-reference/beta/api/call-updatemetadata.md
  api-reference/beta/api/call-updaterecordingstatus.md
  api-reference/beta/api/participant-configuremixer.md
  api-reference/beta/api/participant-muteall.md
  api-reference/beta/includes/snippets/csharp/create-call-from-application-csharp-snippets.md
  api-reference/beta/includes/snippets/javascript/create-call-from-application-javascript-snippets.md
  api-reference/beta/resources/call.md
  api-reference/beta/resources/incomingcontext.md
  api-reference/beta/resources/invitationparticipantinfo.md
  api-reference/beta/resources/participantinfo.md
  api-reference/beta/resources/recordinginfo.md
  api-reference/beta/resources/updaterecordingstatusoperation.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: ready to merge

#5780 Update Request header specification
  api-reference/v1.0/api/groupsetting-update.md
Labels: external, ready to merge, review requested

#6430 Update permissions required for CA APIs
  api-reference/beta/api/conditionalaccesspolicy-delete.md
  api-reference/beta/api/conditionalaccesspolicy-update.md
  api-reference/beta/api/conditionalaccessroot-post-namedlocations.md
  api-reference/beta/api/conditionalaccessroot-post-policies.md
  api-reference/beta/api/countrynamedlocation-delete.md
  api-reference/beta/api/countrynamedlocation-update.md
  api-reference/beta/api/ipnamedlocation-delete.md
  api-reference/beta/api/ipnamedlocation-update.md
  api-reference/beta/api/namedlocation-delete.md
  concepts/changelog.md
  concepts/known-issues.md
Labels: ready to merge

#6398 Add reportOnly mode as a state to conditional access policies
  api-reference/beta/resources/conditionalaccesspolicy.md
  concepts/changelog.md
Labels: ready to merge

#6263 Made conversationIndex available in v1 as well.
  api-reference/beta/resources/eventmessage.md
  api-reference/beta/resources/message.md
  api-reference/v1.0/api/attachment-get.md
  api-reference/v1.0/api/eventmessage-get.md
  api-reference/v1.0/api/user-post-messages.md
  api-reference/v1.0/resources/eventmessage.md
  api-reference/v1.0/resources/message.md
  concepts/changelog.md
Labels: do not merge
