Repository microsoftgraph/microsoft-graph-docs, pull requests merged in 2019-12, with the labels that each got.

#6310 fix for git issue 3880
  api-reference/beta/resources/group.md
  api-reference/v1.0/resources/group.md
Labels: ready to merge

#6425 Microsoft-graph-toolkit v1.1 documentation update
  concepts/toc.yml
  concepts/toolkit/components/agenda.md
  concepts/toolkit/components/get.md
  concepts/toolkit/components/login.md
  concepts/toolkit/components/people-picker.md
  concepts/toolkit/components/people.md
  concepts/toolkit/components/person-card.md
  concepts/toolkit/components/person.md
  concepts/toolkit/components/tasks.md
  concepts/toolkit/images/chromeIcon.png
  concepts/toolkit/images/edgeIcon.png
  concepts/toolkit/images/firefoxIcon.png
  concepts/toolkit/images/internetExplorerIcon.png
  concepts/toolkit/images/operaIcon.png
  concepts/toolkit/images/safariIcon.png
  concepts/toolkit/images/samsungInternetIcon.png
  concepts/toolkit/overview.md
  concepts/toolkit/providers/msal.md
  concepts/toolkit/providers/proxy.md
  concepts/toolkit/providers/sharepoint.md
  concepts/toolkit/providers/teams.md
  concepts/toolkit/templates.md
Labels: internal

#6464 Bug fixes to filesFolder docs
  api-reference/beta/api/driveitem-get.md
  api-reference/beta/resources/channel.md
Labels: area: teams, ready to merge

#6396 clean up of user toc
  api-reference/beta/resources/user.md
  api-reference/beta/toc.yml
  api-reference/v1.0/resources/user.md
  api-reference/v1.0/toc.yml
Labels: ready to merge

#6475 Snippets update
  api-reference/beta/api/call-updaterecordingstatus.md
  api-reference/beta/includes/snippets/csharp/call-updaterecordingstatus-csharp-snippets.md
  api-reference/beta/includes/snippets/csharp/create-call-app-hosted-media-csharp-snippets.md
  api-reference/beta/includes/snippets/csharp/create-call-service-hosted-media-csharp-snippets.md
  api-reference/beta/includes/snippets/javascript/call-updatemetadata-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/call-updaterecordingstatus-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/create-call-app-hosted-media-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/create-call-service-hosted-media-javascript-snippets.md
  api-reference/beta/includes/snippets/objc/call-updaterecordingstatus-objc-snippets.md
Labels: ready to merge

#6346 fix for git issue 5883
  api-reference/beta/resources/invitation.md
  api-reference/v1.0/resources/invitation.md
Labels: ready to merge

#6454 beta replaced with v1.0;
  concepts/teams-configuring-builtin-tabs.md
Labels: area: teams, external, ready to merge

#6467 Create presence-get.md
  api-reference/beta/api/cloudcommunications-getpresencesbyuserid.md
  api-reference/beta/api/presence-get.md
  api-reference/beta/resources/communications-api-overview.md
  api-reference/beta/resources/presence.md
  api-reference/beta/toc.yml
  concepts/permissions-reference.md
Labels: ready to merge

#6488 Correct invalid microsoft.graph.conflictBehavior values
  api-reference/beta/api/driveitem-createuploadsession.md
Labels: area: onedrive, bug: documentation, ready to merge

#6341 Added error codes/description to document
  api-reference/beta/api/notifications-post.md
  api-reference/beta/api/user-post-notifications.md
Labels: ready to merge

#5294 Change notifications for Teams messages, including message properties (preview)
  api-reference/beta/api/subscription-post-subscriptions.md
  api-reference/beta/resources/chatmessage.md
  api-reference/beta/resources/subscription.md
  api-reference/beta/resources/webhooks.md
  concepts/changelog.md
  concepts/toc.yml
  concepts/webhooks-outlook-authz.md
  concepts/webhooks-with-resource-data.md
  concepts/webhooks.md
Labels: area: webhooks, ready to merge

#6359 Places API updates.md
  api-reference/beta/api/place-update.md
  concepts/permissions-reference.md
Labels: ready to merge

#6504 fix for git issue 6455
  api-reference/beta/api/intune-deviceconfig-ioscompliancepolicy-create.md
  api-reference/v1.0/api/intune-deviceconfig-ioscompliancepolicy-create.md
Labels: ready to merge

#5995 Shifts API documentation and Changelog for Swap requests, WFI, TimeoffRequests,Open…
  api-reference/beta/api/openshift-delete.md
  api-reference/beta/api/openshift-get.md
  api-reference/beta/api/openshift-update.md
  api-reference/beta/api/openshiftchangerequest-approve.md
  api-reference/beta/api/openshiftchangerequest-decline.md
  api-reference/beta/api/openshiftchangerequest-delete.md
  api-reference/beta/api/openshiftchangerequest-get.md
  api-reference/beta/api/openshiftchangerequest-update.md
  api-reference/beta/api/schedule-get.md
  api-reference/beta/api/swapshiftschangerequest-delete.md
  api-reference/beta/api/swapshiftschangerequest-get.md
  api-reference/beta/api/swapshiftschangerequest-update.md
  api-reference/beta/api/team-put-schedule.md
  api-reference/beta/api/timeoff-put.md
  api-reference/beta/api/timeoffrequest-approve.md
  api-reference/beta/api/timeoffrequest-decline.md
  api-reference/beta/api/timeoffrequest-delete.md
  api-reference/beta/api/timeoffrequest-get.md
  api-reference/beta/api/timeoffrequest-update.md
  api-reference/beta/api/workforceintegration-delete.md
  api-reference/beta/api/workforceintegration-get.md
  api-reference/beta/api/workforceintegration-list.md
  api-reference/beta/api/workforceintegration-post.md
  api-reference/beta/api/workforceintegration-update.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/openshift.md
  api-reference/beta/resources/openshiftchangerequest.md
  api-reference/beta/resources/openshiftitem.md
  api-reference/beta/resources/schedule.md
  api-reference/beta/resources/swapshiftschangerequest.md
  api-reference/beta/resources/timeoffrequest.md
  api-reference/beta/resources/workforceintegration.md
  api-reference/beta/resources/workforceintegrationencryption.md
  concepts/changelog.md
Labels: ready to merge

#6474 Update driveitem.md
  api-reference/beta/resources/driveitem.md
  api-reference/v1.0/resources/driveitem.md
Labels: ready to merge

#6507 Fix url
  concepts/changelog.md
Labels: area: teams, ready to merge

#6525 Update search-concept-overview.md
  concepts/search-concept-overview.md
Labels: ready to merge

#6469 Microsoft Graph Toolkit 1.1 docs
  concepts/changelog.md
  concepts/toc.yml
  concepts/toolkit/components/agenda.md
  concepts/toolkit/components/get.md
  concepts/toolkit/components/images/selected-people.png
  concepts/toolkit/components/login.md
  concepts/toolkit/components/people-picker.md
  concepts/toolkit/components/people.md
  concepts/toolkit/components/person-card.md
  concepts/toolkit/components/person.md
  concepts/toolkit/components/tasks.md
  concepts/toolkit/images/chromeIcon.png
  concepts/toolkit/images/edgeIcon.png
  concepts/toolkit/images/firefoxIcon.png
  concepts/toolkit/images/internetExplorerIcon.png
  concepts/toolkit/images/operaIcon.png
  concepts/toolkit/images/safariIcon.png
  concepts/toolkit/images/samsungInternetIcon.png
  concepts/toolkit/overview.md
  concepts/toolkit/providers.md
  concepts/toolkit/providers/msal.md
  concepts/toolkit/providers/proxy.md
  concepts/toolkit/providers/sharepoint.md
  concepts/toolkit/providers/teams.md
  concepts/toolkit/templates.md
Labels: ready to merge

#6246 Added property allowCreatePrivateChannels
  api-reference/v1.0/resources/teammembersettings.md
Labels: external, ready to merge, review requested

#6549 minor doc change to keep consistent with V1 doc
  api-reference/beta/api/call-answer.md
  api-reference/beta/resources/call.md
  api-reference/beta/resources/commsnotification.md
Labels: ready to merge

#6520 Correct example
  api-reference/beta/api/conversationmember-add.md
Labels: external, ready to merge

#6527 identityriskevents deprecation updates
  api-reference/beta/api/anonymousipriskevent-get.md
  api-reference/beta/api/anonymousipriskevent-list.md
  api-reference/beta/api/identityriskevent-get.md
  api-reference/beta/api/impossibletravelriskevent-get.md
  api-reference/beta/api/impossibletravelriskevent-list.md
  api-reference/beta/api/leakedcredentialsriskevent-get.md
  api-reference/beta/api/leakedcredentialsriskevent-list.md
  api-reference/beta/api/malwareriskevent-get.md
  api-reference/beta/api/malwareriskevent-list.md
  api-reference/beta/api/suspiciousipriskevent-get.md
  api-reference/beta/api/suspiciousipriskevent-list.md
  api-reference/beta/api/unfamiliarlocationriskevent-get.md
  api-reference/beta/api/unfamiliarlocationriskevent-list.md
  api-reference/beta/resources/anonymousipriskevent.md
  api-reference/beta/resources/identityriskevent.md
  api-reference/beta/resources/impossibletravelriskevent.md
  api-reference/beta/resources/leakedcredentialsriskevent.md
  api-reference/beta/resources/malwareriskevent.md
  api-reference/beta/resources/suspiciousipriskevent.md
  api-reference/beta/resources/unfamiliarlocationriskevent.md
Labels: ready to merge

#6550 Added Shifts APIs to TOC; minor fixes.
  api-reference/beta/api/timeoffrequest-get.md
  api-reference/beta/api/timeoffrequest-update.md
  api-reference/beta/api/workforceintegration-get.md
  api-reference/beta/resources/openshift.md
  api-reference/beta/resources/timeoff.md
  api-reference/beta/resources/timeoffreason.md
  api-reference/beta/resources/workforceintegration.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: ready to merge

#6072 Added application permissions
  api-reference/beta/api/chatmessage-list.md
Labels: external, ready to merge, review requested

#6556 Updated table of contents in beta with 'Delete channel' and its reference md file.
  api-reference/beta/toc.yml
Labels: area: teams, ready to merge

#6547 Update sharepoint.md
  api-reference/v1.0/resources/sharepoint.md
Labels: external

#6458 Onboard threat assessment APIs
  api-reference/beta/api/informationprotection-list-threatassessmentrequests.md
  api-reference/beta/api/informationprotection-post-threatassessmentrequests.md
  api-reference/beta/api/threatassessmentrequest-get.md
  api-reference/beta/resources/emailfileassessmentrequest.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/fileassessmentrequest.md
  api-reference/beta/resources/mailassessmentrequest.md
  api-reference/beta/resources/threatassessment-api-overview.md
  api-reference/beta/resources/threatassessmentrequest.md
  api-reference/beta/resources/threatassessmentresult.md
  api-reference/beta/resources/urlassessmentrequest.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: ready to merge

#6433 Edits to search topics.
  api-reference/beta/api/connectionoperation-get.md
  api-reference/beta/api/external-post-connections.md
  api-reference/beta/api/externalconnection-delete.md
  api-reference/beta/api/externalconnection-get.md
  api-reference/beta/api/externalconnection-list.md
  api-reference/beta/api/externalconnection-post-schema.md
  api-reference/beta/api/externalconnection-put-items.md
  api-reference/beta/api/externalconnection-update.md
  api-reference/beta/api/externalitem-update.md
  api-reference/beta/api/schema-get.md
  api-reference/beta/api/search-query.md
  api-reference/beta/resources/externalconnection.md
  api-reference/beta/resources/externalitem.md
  api-reference/beta/resources/indexing-api-overview.md
  api-reference/beta/resources/schema.md
  api-reference/beta/resources/search-api-overview.md
  concepts/search-concept-custom-types.md
  concepts/search-concept-events.md
  concepts/search-concept-files.md
  concepts/search-concept-messages.md
  concepts/search-concept-overview.md
Labels: ready to merge

#6571 fix for workitem 594009
  api-reference/beta/api/subscription-post-subscriptions.md
  api-reference/v1.0/api/subscription-post-subscriptions.md
Labels: ready to merge

#6584 Remove notes on access token format
  concepts/auth/auth-concepts.md
Labels: ready to merge

#6567 Update channel-post-messages.md
  api-reference/beta/api/channel-post-messages.md
Labels: ready to merge

#6588 Changed property type enums for Indexing API schema
  api-reference/beta/resources/property.md
Labels: ready to merge

#6570 Initial Learn/Concept Pages
  concepts/cloud-communications-limits.md
  concepts/cloud-communications-phone-number.md
  concepts/images/communications-app-tenant.PNG
  concepts/toc.yml
Labels: content review, ready to merge

#6601 Update to appRoleAssignments and appRoleAssignedTo on servicePrincipals
  api-reference/beta/api/approleassignment-delete.md
  api-reference/beta/api/approleassignment-get.md
  api-reference/beta/resources/approleassignment.md
  api-reference/beta/resources/serviceprincipal.md
  concepts/changelog.md
Labels: ready to merge

#6604 Updating postman url references
  concepts/use-postman.md
Labels: ready to merge

#6602 Remove unsupported paths from documentation
  concepts/webhooks-with-resource-data.md
Labels: area: teams, ready to merge

#6605 deprecation disclaimer
  api-reference/beta/api/identityriskevent-list.md
Labels: ready to merge

#6573 Application permissions for Shifts Graph APIs
  api-reference/beta/api/schedule-get.md
  api-reference/beta/api/schedule-list-schedulinggroups.md
  api-reference/beta/api/schedule-list-shifts.md
  api-reference/beta/api/schedule-list-timeoffreasons.md
  api-reference/beta/api/schedule-post-schedulinggroups.md
  api-reference/beta/api/schedule-post-shifts.md
  api-reference/beta/api/schedule-post-timeoffreasons.md
  api-reference/beta/api/schedule-post-timesoff.md
  api-reference/beta/api/schedule-share.md
  api-reference/beta/api/schedulinggroup-delete.md
  api-reference/beta/api/schedulinggroup-get.md
  api-reference/beta/api/schedulinggroup-put.md
  api-reference/beta/api/shift-delete.md
  api-reference/beta/api/shift-get.md
  api-reference/beta/api/shift-put.md
  api-reference/beta/api/swapshiftschangerequest-delete.md
  api-reference/beta/api/swapshiftschangerequest-update.md
  api-reference/beta/api/team-put-schedule.md
  api-reference/beta/api/timeoff-delete.md
  api-reference/beta/api/timeoff-get.md
  api-reference/beta/api/timeoff-put.md
  api-reference/beta/api/timeoffreason-delete.md
  api-reference/beta/api/timeoffreason-get.md
  api-reference/beta/api/timeoffreason-put.md
  api-reference/beta/api/timeoffrequest-approve.md
  api-reference/beta/api/timeoffrequest-decline.md
  api-reference/beta/api/timeoffrequest-delete.md
  api-reference/beta/api/timeoffrequest-get.md
  api-reference/beta/api/timeoffrequest-update.md
  concepts/changelog.md
  concepts/permissions-reference.md
Labels: ready to merge

#6568 Update directoryaudit-list.md
  api-reference/v1.0/api/directoryaudit-list.md
Labels: ready to merge

#6603 Gitissue6585
  api-reference/beta/api/directory-deleteditems-user-owned.md
  api-reference/beta/resources/directory.md
  api-reference/v1.0/api/directory-deleteditems-user-owned.md
  api-reference/v1.0/resources/directory.md
Labels: ready to merge

#6539 Update sitepage-create.md
  api-reference/beta/api/sitepage-create.md
Labels: external, ready to merge

#6616 Removed mention of presence (beta only) in v1.0
  api-reference/v1.0/resources/communications-api-overview.md
Labels: ready to merge

#6617 Update permissions-reference.md
  concepts/permissions-reference.md
Labels: external, ready to merge

#6619 Added entry for Presence permissions and fixed links.
  concepts/changelog.md
  concepts/data-connect-concept-overview.md
Labels: ready to merge

#6614 Updated overview page
  concepts/cloud-communications-concept-overview.md
  concepts/images/communications-ivr-transfer.png
  concepts/images/communications-ivr.PNG
  concepts/toc.yml
Labels: ready to merge

#5960 Fix wrong examples about credentialUserRegistrationDetails
  api-reference/beta/api/reportroot-list-credentialuserregistrationdetails.md
Labels: external, ready to merge, review requested

#6620 changed from 2 min to 1 min - recordResponse
  api-reference/v1.0/api/call-record.md
Labels: ready to merge

#6622 Added back missing parentheses
  concepts/cloud-communications-concept-overview.md
Labels: ready to merge

#6624 Add Christmas disclaimer to protected APIs
  concepts/teams-protected-apis.md
Labels: area: teams, ready to merge

#6639 list msgs clarifications
  api-reference/beta/api/channel-list-messages.md
  api-reference/beta/api/chatmessage-delta.md
Labels: area: teams, ready to merge

#6625 Update subscription-post-subscriptions.md
  api-reference/beta/api/subscription-post-subscriptions.md
Labels: area: teams, ready to merge

#6646 Adding documentation for Class Settings to expose settings specific to Team's of type Class.
  api-reference/v1.0/resources/team.md
  api-reference/v1.0/resources/teamclasssettings.md
  concepts/changelog.md
Labels: area: teams, ready to merge

#6652 updated typos in cloud communications limits
  concepts/cloud-communications-limits.md
Labels: ready to merge

#6566 updated PR for entitlement management add accessPackageResourceRequest
  api-reference/beta/api/accesspackage-post-accesspackageresourcerolescopes.md
  api-reference/beta/api/accesspackageassignment-list.md
  api-reference/beta/api/accesspackageassignmentresourcerole-get.md
  api-reference/beta/api/accesspackageassignmentresourcerole-list.md
  api-reference/beta/api/accesspackagecatalog-list-accesspackageresourceroles.md
  api-reference/beta/api/accesspackageresourcerequest-list.md
  api-reference/beta/api/accesspackageresourcerequest-post.md
  api-reference/beta/resources/accesspackage.md
  api-reference/beta/resources/accesspackagecatalog.md
  api-reference/beta/resources/accesspackageresource.md
  api-reference/beta/resources/accesspackageresourcerequest.md
  api-reference/beta/resources/accesspackageresourcerole.md
  api-reference/beta/resources/accesspackageresourcerolescope.md
  api-reference/beta/resources/accesspackageresourcescope.md
  api-reference/beta/resources/entitlementmanagement-root.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: area: azure/AAD, ready to merge

#6399 Titus/recordresponserename
  api-reference/beta/api/application-post-onlinemeetings.md
  api-reference/beta/api/call-cancelmediaprocessing.md
  api-reference/beta/api/call-playprompt.md
  api-reference/beta/api/call-record.md
  api-reference/beta/api/call-subscribetotone.md
  api-reference/beta/api/onlinemeeting-get.md
  api-reference/beta/resources/call.md
  api-reference/beta/resources/calls-api-ivr-overview.md
  api-reference/beta/resources/onlinemeeting.md
  api-reference/beta/resources/resultinfo.md
  concepts/changelog.md
Labels: ready to merge

#6634 (New) Learn and Concept Pages Update for Cloud Communications
  concepts/cloud-communications-calls.md
  concepts/cloud-communications-concept-overview.md
  concepts/cloud-communications-get-started.md
  concepts/cloud-communications-media.md
  concepts/cloud-communications-online-meetings.md
  concepts/images/communications-group-call.PNG
  concepts/images/communications-local-media.PNG
  concepts/images/communications-p2p-call.PNG
  concepts/images/communications-remote-media.PNG
  concepts/toc.yml
Labels: content review, ready to merge

#6660 Fixed availabilityViewInterval minimum value as 5.
  api-reference/beta/api/calendar-getschedule.md
  api-reference/v1.0/api/calendar-getschedule.md
Labels: do not merge

#6655 Added REST example to get MIME content.
  api-reference/beta/api/message-get.md
  api-reference/v1.0/api/message-get.md
  concepts/outlook-get-mime-message.md
Labels: do not merge

#6666 Remove validation warning.
  api-reference/beta/includes/snippets/snippets-sdk-documentation-link.md
  api-reference/v1.0/includes/snippets/snippets-sdk-documentation-link.md
Labels: ready to merge

#6335 Removed properties from OnlineMeetings (Beta)
  api-reference/beta/resources/onlinemeeting.md
Labels: ready to merge

#6659 Adding the DELETE Online Meetings API for beta & v1.0
  api-reference/beta/api/application-post-onlinemeetings.md
  api-reference/beta/api/onlinemeeting-delete.md
  api-reference/beta/api/onlinemeeting-get.md
  api-reference/beta/includes/snippets/snippets-sdk-documentation-link.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/application-post-onlinemeetings.md
  api-reference/v1.0/api/onlinemeeting-delete.md
  api-reference/v1.0/api/onlinemeeting-get.md
  api-reference/v1.0/includes/snippets/snippets-sdk-documentation-link.md
  api-reference/v1.0/resources/onlinemeeting.md
  api-reference/v1.0/toc.yml
  concepts/changelog.md
Labels: ready to merge

#6658 update beta docs
  api-reference/beta/api/application-post-calls.md
  api-reference/beta/api/call-answer.md
  api-reference/beta/api/call-reject.md
  api-reference/beta/api/participant-mute.md
  api-reference/beta/resources/call.md
  api-reference/beta/resources/chatInfo.md
  api-reference/beta/resources/invitationparticipantinfo.md
  api-reference/beta/resources/mediaconfig.md
  api-reference/beta/resources/mediaprompt.md
  api-reference/beta/resources/mediastream.md
  api-reference/beta/resources/participant.md
  api-reference/beta/resources/recordoperation.md
  api-reference/beta/resources/servicehostedmediaconfig.md
Labels: ready to merge
