Repository microsoftgraph/microsoft-graph-docs, pull requests merged in 2019-02, with the labels that each got.

#3905 Updating links for program, per issue #3729
  api-reference/beta/toc.yml
Labels: ready to merge

#3845 Add internalId to Team
  api-reference/beta/resources/team.md
  api-reference/v1.0/resources/team.md
  concepts/changelog.md
Labels: ready to merge

#3922 Included doc'd nav properties & non-default props in optionalProperties, for API Doctor.
  api-reference/beta/resources/group.md
  api-reference/v1.0/resources/group.md
Labels: do not merge

#3929 [ready to merge] Update user resource to remove companyName read-only
  api-reference/beta/resources/user.md
  api-reference/v1.0/resources/user.md
  concepts/changelog.md
Labels: area: azure/AAD

#3910 Fixed some CATS report errors.
  api-reference/beta/api/driveitem-post-children.md
  api-reference/beta/api/teamstab-update.md
  api-reference/docfx.json
  api-reference/v1.0/api/driveitem-post-children.md
  concepts/activity-feed-concept-overview.md
  concepts/auth-overview.md
  concepts/auth-register-app-v2.md
  concepts/auth-v2-service.md
  concepts/auth-v2-user.md
  concepts/docfx.json
  concepts/long-running-actions-overview.md
  concepts/onenote-branding.md
  concepts/outlook-see-messages-you-care-for-first.md
  concepts/permissions-reference.md
  concepts/teams-concept-overview.md
Labels: review requested

#3886 Added displayname values.
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
  concepts/toc.yml
Labels: review requested

#3807 Update to Examples section to match current guidance
  api-reference/beta/api/alert-update.md
  api-reference/beta/api/call-list-participants.md
  api-reference/beta/api/governanceroleassignmentrequest-post.md
  api-reference/beta/api/mailfolder-get.md
  api-reference/beta/api/mailfolder-list-childfolders.md
  api-reference/beta/api/outlooktask-get.md
  api-reference/beta/api/outlooktaskfolder-list-tasks.md
  api-reference/beta/api/outlookuser-list-tasks.md
  api-reference/beta/api/projectrome-put-activity.md
  api-reference/beta/api/teamsapp-list.md
  api-reference/v1.0/api/alert-update.md
  api-reference/v1.0/api/projectrome-put-activity.md
  api-reference/v1.0/api/teamsapp-list.md
Labels: do not merge

#3969 planner; removed planid from task update
  api-reference/beta/api/plannertask-update.md
  api-reference/v1.0/api/plannertask-update.md
Labels: review requested

#3826 Adding new getNotebookFromWebUrl documentation
  api-reference/beta/api/notebook-getnotebookfromweburl.md
  api-reference/beta/resources/notebook.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/notebook-getnotebookfromweburl.md
  api-reference/v1.0/resources/notebook.md
  concepts/changelog.md
Labels: ready to merge

#3973 Correction for Webhooks
  concepts/deployments.md
Labels: ready to merge

#3978 Update registrykeystate.md
  api-reference/beta/resources/registrykeystate.md
Labels: ready to merge

#3951 Updated findMeetingTimes in the beta version.
  api-reference/beta/api/user-findmeetingtimes.md
  api-reference/beta/resources/attendeeavailability.md
  api-reference/beta/resources/attendeeavailabilitydatamodel.md
  api-reference/beta/resources/attendeedatamodel.md
  api-reference/beta/resources/calendar.md
  api-reference/beta/resources/datetimetimezone.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/findmeetingtimesresponse.md
  api-reference/beta/resources/findmeetingtimestimeconstraints.md
  api-reference/beta/resources/locationconstraintitem.md
  api-reference/beta/resources/locationconstraints.md
  api-reference/beta/resources/locationdatamodel.md
  api-reference/beta/resources/meetingtimecandidate.md
  api-reference/beta/resources/meetingtimecandidatesresult.md
  api-reference/beta/resources/meetingtimeslotdatamodel.md
  api-reference/beta/resources/meetingtimesuggestion.md
  api-reference/beta/resources/postaladdress.md
  api-reference/beta/resources/searchwindowtimeslot.md
  api-reference/beta/resources/timeconstraint.md
  api-reference/beta/resources/user.md
  concepts/changelog.md
Labels: do not merge

#3921 Application permissions for installedApps
  api-reference/beta/api/teamsappinstallation-add.md
  api-reference/beta/api/teamsappinstallation-delete.md
  api-reference/beta/api/teamsappinstallation-list.md
  api-reference/beta/api/teamsappinstallation-upgrade.md
  api-reference/beta/resources/teamsappinstallation.md
  concepts/changelog.md
  concepts/known-issues.md
Labels: ready to merge

#3989 Update registrykeystate.md
  api-reference/v1.0/resources/registrykeystate.md
Labels: ready to merge

#3656 Work-in-progress: Clarifying perms for subscriptions.
  api-reference/beta/api/conversation-list-threads.md
  api-reference/beta/api/conversation-post-threads.md
  api-reference/beta/api/subscription-delete.md
  api-reference/beta/api/subscription-get.md
  api-reference/beta/api/subscription-post-subscriptions.md
  api-reference/beta/api/subscription-update.md
  api-reference/beta/resources/subscription.md
  api-reference/beta/resources/webhooks.md
  api-reference/v1.0/api/conversation-list-threads.md
  api-reference/v1.0/api/conversation-post-threads.md
  api-reference/v1.0/api/subscription-delete.md
  api-reference/v1.0/api/subscription-get.md
  api-reference/v1.0/api/subscription-post-subscriptions.md
  api-reference/v1.0/api/subscription-update.md
  api-reference/v1.0/resources/subscription.md
  api-reference/v1.0/resources/webhooks.md
  concepts/webhooks.md
Labels: do not merge

#3912 Added Directory.Read.All, Directory.ReadWrite.All
  api-reference/v1.0/api/group-get.md
Labels: ready to merge

#3993 Add docs for v1.0
  api-reference/v1.0/api/directoryobject-getbyids.md
  api-reference/v1.0/resources/directoryobjectpartnerreference.md
  api-reference/v1.0/resources/organization.md
  concepts/changelog.md
Labels: area: azure/AAD, ready to merge

#4041 Adding info about soft deletes, per issue #3167
  api-reference/beta/api/group-delete.md
  api-reference/beta/api/user-delete.md
  api-reference/v1.0/api/group-delete.md
  api-reference/v1.0/api/user-delete.md
Labels: area: azure/AAD, ready to merge, review requested

#4012 Update domain password policy in beta
  api-reference/beta/resources/domain.md
  concepts/changelog.md
Labels: area: azure/AAD, ready to merge

#4070 Fixed typo and added REST examples to reduce customer confusion.
  api-reference/beta/api/calendar-post-events.md
  api-reference/beta/resources/eventmessage.md
  api-reference/beta/resources/eventmessagerequest.md
  api-reference/v1.0/api/calendar-post-events.md
  api-reference/v1.0/resources/eventmessage.md
Labels: ready to merge

#4016 Changelog update for targetResource changes.
  api-reference/beta/resources/targetresource.md
  api-reference/beta/resources/targetresourcedevice.md
  api-reference/beta/resources/targetresourcedirectory.md
  api-reference/beta/resources/targetresourcegroup.md
  api-reference/beta/resources/targetresourceother.md
  api-reference/beta/resources/targetresourcepolicy.md
  api-reference/beta/resources/targetresourcerole.md
  api-reference/beta/resources/targetresourceserviceprincipal.md
  api-reference/beta/resources/targetresourceuser.md
  concepts/changelog.md
Labels: area: azure/AAD, ready to merge
