Repository microsoftgraph/microsoft-graph-docs, pull requests merged in 2019-04, with the labels that each got.

#4295 Provided real examples to get event instances.
  api-reference/beta/api/event-list-instances.md
  api-reference/v1.0/api/event-list-instances.md
Labels: ready to merge

#4323 New in v1: application permissions for Teams app installations, channel props
  api-reference/beta/resources/channel.md
  api-reference/v1.0/api/teamsappinstallation-add.md
  api-reference/v1.0/api/teamsappinstallation-delete.md
  api-reference/v1.0/api/teamsappinstallation-list.md
  api-reference/v1.0/api/teamsappinstallation-upgrade.md
  api-reference/v1.0/resources/channel.md
  api-reference/v1.0/resources/teamsappinstallation.md
  concepts/changelog.md
Labels: area: teams, ready to merge

#4324 Content improvements to the Channel page
  api-reference/beta/resources/channel.md
  api-reference/v1.0/resources/channel.md
Labels: area: teams, ready to merge

#4325 Update chatMessage documentation to match code
  api-reference/beta/resources/chatmessage.md
  api-reference/beta/resources/chatmessageattachment.md
  api-reference/beta/resources/chatmessagemention.md
  api-reference/beta/resources/chatmessagereaction.md
  concepts/changelog.md
Labels: area: teams, ready to merge

#4245 Graph US Gov endpoints old v/s new updates
  concepts/deployments.md
Labels: changes requested, do not merge

#4360 Add a link to the Teams card reference
  api-reference/beta/api/channel-post-chatmessage.md
Labels: ready to merge

#4268 Update people-example.md
  concepts/people-example.md
Labels: changes requested, ready to merge

#4374 Add "/me/memberOf" endpointl Similar style to user-list-joinedteams.md
  api-reference/beta/api/user-list-memberof.md
  api-reference/v1.0/api/user-list-memberof.md
Labels: do not merge, review requested

#4393 @mentions fixes
  api-reference/beta/api/channel-get-message.md
  api-reference/beta/api/channel-get-messagereply.md
  api-reference/beta/api/channel-list-messagereplies.md
  api-reference/beta/api/channel-list-messages.md
  api-reference/beta/resources/chatmessagemention.md
Labels: area: teams, ready to merge

#4396 eketo - adding docs for revoke sign-in sessions rename
  api-reference/beta/api/user-revokesigninsessions.md
  api-reference/beta/resources/user.md
  concepts/changelog.md
Labels: area: azure/AAD, ready to merge

#3909 Update site-search.md
  api-reference/beta/api/site-search.md
  api-reference/v1.0/api/site-search.md
Labels: review requested

#4418 Explain how channel and team @mentions are represented.
  api-reference/beta/resources/chatmessagemention.md
  api-reference/v1.0/api/teamstab-update.md
Labels: area: teams, ready to merge

#4405 Fixes
  api-reference/beta/resources/chatmessagemention.md
  api-reference/beta/resources/team.md
Labels: area: teams, ready to merge

#4106 Adding the Beta API docs for Trust Framework Policies
  api-reference/beta/api/trustframework-list-trustframeworkpolicies.md
  api-reference/beta/api/trustframework-post-trustframeworkpolicy.md
  api-reference/beta/api/trustframework-put-trustframeworkpolicy.md
  api-reference/beta/api/trustframeworkpolicy-delete.md
  api-reference/beta/api/trustframeworkpolicy-get.md
  api-reference/beta/resources/trustframeworkpolicy.md
  api-reference/beta/toc.yml
  concepts/changelog.md
  concepts/permissions-reference.md
Labels: area: azure/AAD, ready to merge

#4427 $top support for teams messages
  api-reference/beta/api/channel-list-messagereplies.md
  api-reference/beta/api/channel-list-messages.md
Labels: area: teams, ready to merge

#4375 Moved overview below Explore.
  api-reference/docfx.json
  concepts/docfx.json
  concepts/toc.yml
Labels: do not merge

#4378 Kept major services a parent node, shows too many overviews.
  concepts/toc.yml
Labels: do not merge

#4398 Fixed JSON mitigate API Doctor errors, + examples.
  api-reference/beta/api/channel-get-message.md
  api-reference/beta/api/channel-get-messagereply.md
  api-reference/beta/api/channel-list-messagereplies.md
  api-reference/beta/api/channel-list-messages.md
  api-reference/beta/resources/chatmessage.md
  api-reference/beta/resources/chatmessagemention.md
  api-reference/beta/resources/identityset.md
  api-reference/beta/resources/team.md
  api-reference/v1.0/resources/team.md
Labels: do not merge

#4432 removed delegated permissions
  api-reference/beta/api/securityaction-cancelsecurityaction.md
  api-reference/beta/api/securityaction-get.md
  api-reference/beta/api/securityactions-list.md
  api-reference/beta/api/securityactions-post.md
  api-reference/beta/resources/security-api-overview.md
  api-reference/beta/resources/securityaction.md
Labels: area: Security, ready to merge

#4309 Added descriptions and syntax for $value.
  api-reference/beta/api/attachment-get.md
  api-reference/v1.0/api/attachment-get.md
Labels: do not merge

#3564 [Do not merge]: Updated content for getting MIME content of a message.
  api-reference/beta/api/message-get.md
  api-reference/beta/resources/mail-api-overview.md
  concepts/changelog.md
  concepts/outlook-create-send-messages.md
  concepts/outlook-get-mime-message.md
  concepts/outlook-mail-concept-overview.md
  concepts/toc.yml
Labels: do not merge

#4193 Update/application signin summary II
  api-reference/beta/api/applicationsignindetailedsummary-get.md
  api-reference/beta/api/applicationsigninsummary-get.md
  api-reference/beta/resources/applicationsignindetailedsummary.md
  api-reference/beta/resources/applicationsigninsummary.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: area: azure/AAD, ready to merge

#4308 Exchange notifications with subscription removed signals
  api-reference/beta/resources/subscription.md
  concepts/changelog.md
  concepts/toc.yml
  concepts/webhooks-outlook-authz.md
Labels: ready to merge

#4132 service principals can read access reviews
  api-reference/beta/api/accessreview-create.md
  api-reference/beta/api/accessreview-delete.md
  api-reference/beta/api/accessreview-get.md
  api-reference/beta/api/accessreview-listdecisions.md
  api-reference/beta/api/accessreview-listmydecisions.md
  api-reference/beta/api/accessreview-listreviewers.md
  api-reference/beta/api/accessreview-stop.md
  api-reference/beta/api/businessflowtemplate-list.md
  api-reference/beta/api/program-create.md
  api-reference/beta/api/program-delete.md
  api-reference/beta/api/program-list.md
  api-reference/beta/api/program-listcontrols.md
  api-reference/beta/api/program-update.md
  api-reference/beta/api/programcontrol-create.md
  api-reference/beta/api/programcontrol-delete.md
  api-reference/beta/api/programcontrol-list.md
  api-reference/beta/api/programcontroltype-list.md
  api-reference/beta/resources/accessreview.md
  api-reference/beta/resources/accessreviews-root.md
  api-reference/beta/resources/program.md
  api-reference/beta/resources/programcontrol.md
  api-reference/beta/resources/useridentity.md
  concepts/changelog.md
  concepts/permissions-reference.md
Labels: ready to merge

#4235 GET /me/chats
  api-reference/beta/api/channel-get-messagereply.md
  api-reference/beta/api/channel-list-messages.md
  api-reference/beta/api/chat-get-message.md
  api-reference/beta/api/chat-get.md
  api-reference/beta/api/chat-list-messages.md
  api-reference/beta/api/chat-list.md
  api-reference/beta/resources/chat.md
  api-reference/beta/resources/chatmessage.md
  api-reference/beta/toc.yml
  concepts/changelog.md
  concepts/permissions-reference.md
Labels: area: teams, ready to merge

#4470 Fixed namespace of openTypeExtension & notifications TOC.
  api-reference/beta/api/opentypeextension-post-opentypeextension.md
  api-reference/v1.0/api/opentypeextension-post-opentypeextension.md
  concepts/toc.yml
Labels: do not merge

#4482 added delete instructions for Azmon
  concepts/security-splunk-siemintegration.md
Labels: area: Security, ready to merge

#4402 Add a url of getting my manager
  api-reference/beta/api/user-list-manager.md
  api-reference/v1.0/api/user-list-manager.md
Labels: ready to merge

#4403 Add the url of getting my direct reports
  api-reference/beta/api/user-list-directreports.md
  api-reference/v1.0/api/user-list-directreports.md
Labels: ready to merge

#3903 Added SDK conceptual docs
  concepts/sdks/choose-authentication-providers.md
  concepts/sdks/create-client.md
  concepts/sdks/sdk-installation.md
  concepts/sdks/sdks-overview.md
  concepts/toc.yml
Labels: ready to merge
