Repository microsoftgraph/microsoft-graph-docs, pull requests merged in 2019-10, with the labels that each got.

#5856 fix for git issue 5422 - beta
  api-reference/beta/api/group-list-members.md
Labels: ready to merge

#5771 v1 doc updates for the following API's
  api-reference/beta/api/message-reply.md
  api-reference/beta/api/user-get-mailboxsettings.md
  api-reference/v1.0/api/message-reply.md
  api-reference/v1.0/api/user-get-mailboxsettings.md
  api-reference/v1.0/api/user-update-mailboxsettings.md
  api-reference/v1.0/overview.md
  api-reference/v1.0/resources/workinghours.md
  concepts/changelog.md
Labels: do not merge, review requested

#4389 Add scheduled state to status property values
  api-reference/beta/resources/educationassignment.md
Labels: ready to merge

#5789 Add new reviewed properties to EduAssignments docs
  api-reference/beta/api/educationassignment-get.md
  api-reference/beta/api/educationassignment-update.md
  api-reference/beta/api/educationclass-list-assignments.md
  api-reference/beta/api/educationclass-post-assignments.md
  api-reference/beta/api/educationuser-list-assignments.md
  api-reference/beta/resources/educationassignment.md
  api-reference/beta/resources/educationmakecoderesource.md
  concepts/changelog.md
Labels: area: edu, ready to merge

#5863 2 new props for group exposure in Outlook.
  api-reference/beta/resources/group.md
  concepts/changelog.md
Labels: do not merge

#5884 Typo "**@odata.nextLink**"→"**\@odata.nextLink**"
  api-reference/v1.0/api/driveitem-delta.md
Labels: external

#5694 Team photo
  api-reference/beta/api/team-get-photo.md
  api-reference/beta/api/team-update-photo.md
  api-reference/beta/resources/team.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: area: teams, content review, ready to merge

#5894 Added date and time formats, updated what's new.
  api-reference/v1.0/resources/mailboxsettings.md
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: do not merge

#5913 Update the protected API list
  api-reference/beta/api/chatmessage-delta.md
  api-reference/beta/api/chatmessage-list-chatmessagehostedcontents.md
  api-reference/beta/api/chatmessagehostedcontent-get.md
  api-reference/beta/api/conversationmember-get.md
  api-reference/beta/api/conversationmember-list.md
  concepts/teams-protected-apis.md
Labels: area: teams, ready to merge

#5879 Added missing relatedContacts property
  api-reference/beta/api/educationuser-delete.md
  api-reference/beta/api/educationuser-get-user.md
  api-reference/beta/api/educationuser-get.md
  api-reference/beta/api/educationuser-list-assignments.md
  api-reference/beta/api/educationuser-list-classes.md
  api-reference/beta/api/educationuser-list-schools.md
  api-reference/beta/api/educationuser-post-rubrics.md
  api-reference/beta/api/educationuser-update.md
  api-reference/beta/resources/educationuser.md
  api-reference/beta/resources/relatedcontact.md
Labels: area: edu, ready to merge

#5920 Updated Comms API page
  api-reference/beta/resources/calls-api-overview.md
  api-reference/beta/resources/communications-api-overview.md
  api-reference/beta/resources/teams-api-overview.md
  api-reference/beta/toc.yml
Labels: ready to merge

#5902 Nivogt/people picker updates
  concepts/toolkit/components/images/selected-people.png
  concepts/toolkit/components/people-picker.md
Labels: do not merge, internal

#5272 GBL Write API documentation
  api-reference/beta/api/group-assignlicense.md
  api-reference/beta/api/user-assignlicense.md
  api-reference/beta/api/user-reprocesslicenseassignment.md
  api-reference/beta/resources/group.md
  api-reference/beta/resources/user.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: area: azure/AAD, ready to merge

#5956 fix for git issue 5952
  api-reference/beta/api/organization-get.md
  api-reference/beta/resources/organization.md
  api-reference/v1.0/resources/organization.md
Labels: ready to merge

#5953 Fixing app permissions for chats
  api-reference/beta/api/chat-get.md
  api-reference/beta/api/chat-list.md
Labels: area: teams, ready to merge

#5935 Fixes to user identities
  api-reference/beta/api/user-post-users.md
  api-reference/beta/resources/objectidentity.md
  api-reference/beta/resources/user.md
Labels: area: azure/AAD, area: users, ready to merge

#5936 update api overview
  api-reference/beta/resources/search-api-overview.md
Labels: internal

#5940 add l3 section
  api-reference/beta/api/search-query.md
Labels: internal

#5941 init search message page
  concepts/search-concept-messages.md
Labels: internal

#5942 Update search-concept-events.md
  concepts/search-concept-events.md
Labels: internal

#5943 Update search-concept-files.md
  concepts/search-concept-files.md
Labels: internal

#5963 Headers are both required
  api-reference/v1.0/api/plannertaskdetails-update.md
Labels: ready to merge

#5890 AAD: Add mdmAppId and securityIdenitifier to beta and v1.0 (properties are showing up in both now)
  api-reference/beta/resources/device.md
  api-reference/beta/resources/group.md
  api-reference/v1.0/resources/device.md
  api-reference/v1.0/resources/group.md
  concepts/changelog.md
Labels: ready to merge

#5967 Update v1.0 docs for certificate based auth configuration
  api-reference/v1.0/api/certificatebasedauthconfiguration-delete.md
  api-reference/v1.0/api/certificatebasedauthconfiguration-get.md
  api-reference/v1.0/api/certificatebasedauthconfiguration-list.md
  api-reference/v1.0/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration.md
  api-reference/v1.0/resources/certificateauthority.md
  api-reference/v1.0/resources/certificatebasedauthconfiguration.md
  api-reference/v1.0/resources/organization.md
  api-reference/v1.0/toc.yml
  concepts/changelog.md
  concepts/migrate-azure-ad-graph-property-differences.md
  concepts/migrate-azure-ad-graph-resource-differences.md
Labels: ready to merge

#5973 Announcing reading images with application permissions
  concepts/changelog.md
Labels: area: teams, ready to merge

#5986 Updating toolkit import statement for sp webparts
  concepts/toolkit/providers/sharepoint.md
Labels: ready to merge

#5985 Corrections to edu scopes and school properties
  api-reference/beta/api/educationclass-list-schools.md
  api-reference/beta/api/educationroot-list-schools.md
  api-reference/beta/api/educationroot-post-schools.md
  api-reference/beta/api/educationschool-update.md
  api-reference/beta/api/educationuser-list-schools.md
  api-reference/beta/includes/snippets/csharp/create-educationschool-from-educationroot-csharp-snippets.md
  api-reference/beta/includes/snippets/javascript/create-educationschool-from-educationroot-javascript-snippets.md
  api-reference/beta/includes/snippets/objc/create-educationschool-from-educationroot-objc-snippets.md
  api-reference/beta/resources/educationschool.md
  api-reference/v1.0/api/educationclass-list-schools.md
  api-reference/v1.0/api/educationroot-list-schools.md
  api-reference/v1.0/api/educationroot-post-schools.md
  api-reference/v1.0/api/educationschool-update.md
  api-reference/v1.0/api/educationuser-list-schools.md
  api-reference/v1.0/includes/snippets/csharp/create-educationschool-from-educationroot-csharp-snippets.md
  api-reference/v1.0/includes/snippets/java/create-educationschool-from-educationroot-java-snippets.md
  api-reference/v1.0/includes/snippets/javascript/create-educationschool-from-educationroot-javascript-snippets.md
  api-reference/v1.0/includes/snippets/objc/create-educationschool-from-educationroot-objc-snippets.md
  api-reference/v1.0/resources/educationschool.md
  concepts/permissions-reference.md
Labels: area: edu, ready to merge

#5989 fix whitespace issue
  api-reference/beta/api/search-query.md
Labels: internal

#5988 fix relative path
  api-reference/beta/resources/search.md
Labels: internal

#5987 fix relative path
  api-reference/beta/api/search-query.md
Labels: internal

#5538 Add device properties for cloud print service
  api-reference/beta/resources/device.md
  concepts/changelog.md
Labels: area: azure/AAD, content review, ready to merge

#6010 resolve bookmark
  api-reference/beta/resources/search-api-overview.md
Labels: internal

#6025 Fix team photo permissions
  api-reference/beta/api/team-get-photo.md
Labels: area: teams, ready to merge

#6017 Add description and note for Group.Selected permission
  concepts/permissions-reference.md
Labels: area: azure/AAD, area: groups, ready to merge

#6005 Adding lastPasswordChangeDateTime
  api-reference/v1.0/resources/user.md
  concepts/changelog.md
Labels: area: azure/AAD, area: users, ready to merge

#5354 New calendar API to support proposing alternate meeting times.
  api-reference/beta/api/event-decline.md
  api-reference/beta/api/event-get.md
  api-reference/beta/api/event-tentativelyaccept.md
  api-reference/beta/api/eventmessage-get.md
  api-reference/beta/api/user-list-events.md
  api-reference/beta/api/user-post-events.md
  api-reference/beta/resources/attendee.md
  api-reference/beta/resources/event.md
  api-reference/beta/resources/eventmessage.md
  api-reference/beta/resources/eventmessagerequest.md
  api-reference/beta/resources/eventmessageresponse.md
  api-reference/beta/resources/message.md
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
  concepts/changelog.md
  concepts/outlook-calendar-concept-overview.md
  concepts/outlook-calendar-meeting-proposals.md
  concepts/toc.yml
Labels: do not merge

#5805 Docs for new API supporting large file attachments for messages.
  api-reference/beta/api/attachment-createuploadsession.md
  api-reference/beta/api/message-post-attachments.md
  api-reference/beta/resources/attachment.md
  api-reference/beta/resources/attachmentitem.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/uploadsession.md
  api-reference/beta/toc.yml
  concepts/changelog.md
  concepts/outlook-large-attachments.md
  concepts/toc.yml
Labels: do not merge

#5510 Calendar url fix
  api-reference/v1.0/api/attachment-get.md
Labels: review requested

#5826 Add conditional access documentation
  api-reference/beta/api/conditionalaccesspolicy-delete.md
  api-reference/beta/api/conditionalaccesspolicy-get.md
  api-reference/beta/api/conditionalaccesspolicy-update.md
  api-reference/beta/api/conditionalaccessroot-list-policies.md
  api-reference/beta/api/conditionalaccessroot-post-policies.md
  api-reference/beta/resources/applicationenforcedrestrictionssessioncontrol.md
  api-reference/beta/resources/cloudappsecuritysessioncontrol.md
  api-reference/beta/resources/conditionalaccessapplications.md
  api-reference/beta/resources/conditionalaccessconditionset.md
  api-reference/beta/resources/conditionalaccessdevicestates.md
  api-reference/beta/resources/conditionalaccessgrantcontrols.md
  api-reference/beta/resources/conditionalaccesslocations.md
  api-reference/beta/resources/conditionalaccessplatforms.md
  api-reference/beta/resources/conditionalaccesspolicy.md
  api-reference/beta/resources/conditionalaccesssessioncontrol.md
  api-reference/beta/resources/conditionalaccesssessioncontrols.md
  api-reference/beta/resources/conditionalaccessusers.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/persistentbrowsersessioncontrol.md
  api-reference/beta/resources/signinfrequencysessioncontrol.md
  api-reference/beta/toc.yml
  concepts/changelog.md
  concepts/known-issues.md
  concepts/permissions-reference.md
Labels: area: azure/AAD, ready to merge

#5842 Add named locations API documentation
  api-reference/beta/api/conditionalaccessroot-list-namedlocations.md
  api-reference/beta/api/conditionalaccessroot-post-namedlocations.md
  api-reference/beta/api/countrynamedlocation-delete.md
  api-reference/beta/api/countrynamedlocation-get.md
  api-reference/beta/api/countrynamedlocation-update.md
  api-reference/beta/api/ipnamedlocation-delete.md
  api-reference/beta/api/ipnamedlocation-get.md
  api-reference/beta/api/ipnamedlocation-update.md
  api-reference/beta/api/namedlocation-delete.md
  api-reference/beta/api/namedlocation-get.md
  api-reference/beta/resources/countrynamedlocation.md
  api-reference/beta/resources/ipnamedlocation.md
  api-reference/beta/resources/iprange.md
  api-reference/beta/resources/ipv4cidrrange.md
  api-reference/beta/resources/ipv6cidrrange.md
  api-reference/beta/resources/namedlocation.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: changes requested, content review, ready to merge

#5653 Initial draft of SDK create requests
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
  concepts/sdks/choose-authentication-providers.md
  concepts/sdks/create-requests.md
  concepts/sdks/includes/snippets/csharp/create-requests-create.md
  concepts/sdks/includes/snippets/csharp/create-requests-delete.md
  concepts/sdks/includes/snippets/csharp/create-requests-expand.md
  concepts/sdks/includes/snippets/csharp/create-requests-headers.md
  concepts/sdks/includes/snippets/csharp/create-requests-index.md
  concepts/sdks/includes/snippets/csharp/create-requests-list.md
  concepts/sdks/includes/snippets/csharp/create-requests-queryparams.md
  concepts/sdks/includes/snippets/csharp/create-requests-read.md
  concepts/sdks/includes/snippets/csharp/create-requests-select.md
  concepts/sdks/includes/snippets/csharp/create-requests-update.md
  concepts/sdks/includes/snippets/typescript/create-requests-create.md
  concepts/sdks/includes/snippets/typescript/create-requests-delete.md
  concepts/sdks/includes/snippets/typescript/create-requests-expand.md
  concepts/sdks/includes/snippets/typescript/create-requests-headers.md
  concepts/sdks/includes/snippets/typescript/create-requests-index.md
  concepts/sdks/includes/snippets/typescript/create-requests-list.md
  concepts/sdks/includes/snippets/typescript/create-requests-queryparams.md
  concepts/sdks/includes/snippets/typescript/create-requests-read.md
  concepts/sdks/includes/snippets/typescript/create-requests-select.md
  concepts/sdks/includes/snippets/typescript/create-requests-update.md
  concepts/toc.yml
Labels: ready to merge

#6075 Remove duplicate Conditional Access heading from toc.yml
  api-reference/beta/toc.yml
Labels: ready to merge

#6056 removed Directory.Read.All from the list of perms for List domainNameReferences
  api-reference/beta/api/domain-list-domainnamereferences.md
  api-reference/v1.0/api/domain-list-domainnamereferences.md
  concepts/permissions-reference.md
Labels: area: azure/AAD

#5990 Remove deprecated props from educationSubmission
  .openpublishing.redirection.json
  api-reference/beta/api/educationassignment-list-submissions.md
  api-reference/beta/api/educationsubmission-get.md
  api-reference/beta/api/educationsubmission-release.md
  api-reference/beta/api/educationsubmission-update.md
  api-reference/beta/resources/educationsubmission.md
  api-reference/beta/toc.yml
  concepts/changelog.md
  concepts/education-concept-overview.md
Labels: area: edu, ready to merge

#5689 Nvalluri keysets
  api-reference/beta/api/identityprovider-delete.md
  api-reference/beta/api/identityprovider-get.md
  api-reference/beta/api/identityprovider-list.md
  api-reference/beta/api/identityprovider-post-identityproviders.md
  api-reference/beta/api/identityprovider-update.md
  api-reference/beta/api/identityuserflow-delete.md
  api-reference/beta/api/identityuserflow-get.md
  api-reference/beta/api/identityuserflow-list.md
  api-reference/beta/api/identityuserflow-post-userflows.md
  api-reference/beta/api/trustframework-list-keysets.md
  api-reference/beta/api/trustframework-list-trustframeworkpolicies.md
  api-reference/beta/api/trustframework-post-keysets.md
  api-reference/beta/api/trustframework-post-trustframeworkpolicy.md
  api-reference/beta/api/trustframework-put-trustframeworkpolicy.md
  api-reference/beta/api/trustframeworkkeyset-delete.md
  api-reference/beta/api/trustframeworkkeyset-generatekey.md
  api-reference/beta/api/trustframeworkkeyset-get.md
  api-reference/beta/api/trustframeworkkeyset-getactivekey.md
  api-reference/beta/api/trustframeworkkeyset-update.md
  api-reference/beta/api/trustframeworkkeyset-uploadcertificate.md
  api-reference/beta/api/trustframeworkkeyset-uploadpkcs12.md
  api-reference/beta/api/trustframeworkkeyset-uploadsecret.md
  api-reference/beta/api/trustframeworkpolicy-delete.md
  api-reference/beta/api/trustframeworkpolicy-get.md
  api-reference/beta/resources/identityuserflow.md
  api-reference/beta/resources/trustframeworkkey.md
  api-reference/beta/resources/trustframeworkkeyset.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: area: azure/AAD, ready to merge

#6107 Add model/manufacturer v1.0 docs
  api-reference/v1.0/resources/device.md
  concepts/changelog.md
Labels: area: azure/AAD, ready to merge

#6109 add documentation for mgt-tasks groupId parameter
  concepts/toolkit/components/tasks.md
Labels: internal, review requested

#6123 Updating the documentation to reflect the correct filtering parameters
  api-reference/beta/api/chatmessage-delta.md
Labels: area: teams, ready to merge

#6080 Removed Palo Alto Networks from version v.1 Alerts
  api-reference/v1.0/resources/security-api-overview.md
Labels: ready to merge

#6078 Removed Palo Alto Networks from Alerts version Beta
  api-reference/beta/resources/security-api-overview.md
Labels: ready to merge

#6052 Added additional possible value for targetProduct
  api-reference/beta/resources/tiindicator.md
Labels: ready to merge

#6046 Ignite 2019 GN Updates - Round 1
  api-reference/beta/api/notifications-post.md
  api-reference/beta/api/user-post-notifications.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/fallbackpolicy.md
  api-reference/beta/resources/fallbackpolicyproperties.md
  api-reference/beta/resources/notifications-api-overview.md
  api-reference/beta/resources/payloadtypes.md
  api-reference/beta/resources/projectrome-notification.md
  api-reference/beta/resources/targetpolicyendpoints.md
  api-reference/beta/resources/visualproperties.md
  api-reference/beta/toc.yml
  concepts/changelog.md
  concepts/images/notifications-api-permissions-list.png
  concepts/images/notifications-integration-e2e-overview.png
  concepts/notifications-concept-overview.md
  concepts/notifications-integrating-app-server.md
  concepts/notifications-integration-app-registration.md
  concepts/notifications-integration-cross-device-experiences-onboarding.md
  concepts/notifications-integration-e2e-overview.md
Labels: ready to merge

#5914 Group onpremise properties
  api-reference/beta/resources/group.md
  api-reference/v1.0/resources/group.md
  concepts/changelog.md
  concepts/migrate-azure-ad-graph-property-differences.md
Labels: area: azure/AAD, ready to merge

#5991 sign-in updates
  api-reference/beta/api/signin-get.md
  api-reference/beta/api/signin-list.md
  api-reference/beta/api/user-list.md
  api-reference/beta/resources/authenticationdetail.md
  api-reference/beta/resources/keyvalue.md
  api-reference/beta/resources/networkLocationDetail.md
  api-reference/beta/resources/signin.md
  api-reference/beta/resources/signinactivity.md
  api-reference/beta/resources/user.md
  concepts/changelog.md
Labels: ready to merge

#5546 add entitlementmanagement-root.md to left nav
  api-reference/beta/api/accesspackage-delete.md
  api-reference/beta/api/accesspackage-get.md
  api-reference/beta/api/accesspackage-list-accesspackageresourcerolescopes.md
  api-reference/beta/api/accesspackage-list.md
  api-reference/beta/api/accesspackage-post.md
  api-reference/beta/api/accesspackageassignment-list.md
  api-reference/beta/api/accesspackageassignmentpolicy-delete.md
  api-reference/beta/api/accesspackageassignmentpolicy-get.md
  api-reference/beta/api/accesspackageassignmentpolicy-list.md
  api-reference/beta/api/accesspackageassignmentpolicy-post.md
  api-reference/beta/api/accesspackageassignmentrequest-get.md
  api-reference/beta/api/accesspackageassignmentrequest-list.md
  api-reference/beta/api/accesspackageassignmentrequest-post.md
  api-reference/beta/api/accesspackageassignmentresourcerole-list.md
  api-reference/beta/api/accesspackagecatalog-delete.md
  api-reference/beta/api/accesspackagecatalog-get.md
  api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md
  api-reference/beta/api/accesspackagecatalog-list.md
  api-reference/beta/api/accesspackagecatalog-post.md
  api-reference/beta/resources/accesspackage.md
  api-reference/beta/resources/accesspackageassignment.md
  api-reference/beta/resources/accesspackageassignmentpolicy.md
  api-reference/beta/resources/accesspackageassignmentrequest.md
  api-reference/beta/resources/accesspackageassignmentresourcerole.md
  api-reference/beta/resources/accesspackagecatalog.md
  api-reference/beta/resources/accesspackageresource.md
  api-reference/beta/resources/accesspackageresourcerole.md
  api-reference/beta/resources/accesspackageresourcerolescope.md
  api-reference/beta/resources/accesspackageresourcescope.md
  api-reference/beta/resources/accesspackagesubject.md
  api-reference/beta/resources/entitlementmanagement-root.md
  api-reference/beta/toc.yml
  concepts/permissions-reference.md
Labels: area: azure/AAD, ready to merge

#6155 Update for entitlement management and fix tables.
  concepts/changelog.md
Labels: ready to merge

#6156 Update to App API v1.0 changes
  api-reference/v1.0/resources/application.md
  concepts/changelog.md
Labels: ready to merge
