Repository microsoftgraph/microsoft-graph-docs, pull requests merged in 2019-07, with the labels that each got.

#4903 Added mailfolder, delta support to Mail.ReadBasic
  api-reference/beta/api/mailfolder-delta.md
  api-reference/beta/api/mailfolder-get.md
  api-reference/beta/api/mailfolder-list-childfolders.md
  api-reference/beta/api/mailfolder-list-messages.md
  api-reference/beta/api/message-delta.md
  api-reference/beta/api/user-list-mailfolders.md
  concepts/changelog.md
Labels: ready to merge

#4976 Fixed a mistake in the initial PR that had additional filters (Ready …
  api-reference/beta/api/provisioningobjectsummary-list.md
Labels: ready to merge

#4899 Reorganized what's new.
  concepts/toc.yml
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: do not merge

#4795 Appmethodsusageapi2
  api-reference/beta/api/applicationsigninsummary-get.md
  api-reference/beta/api/reportroot-getcredentialusagesummary.md
  api-reference/beta/api/reportroot-getcredentialuserregistrationcount.md
  api-reference/beta/api/reportroot-list-credentialuserregistrationdetails.md
  api-reference/beta/api/reportroot-list-usercredentialusagedetails.md
  api-reference/beta/resources/authenticationmethods-usage-insights-overview.md
  api-reference/beta/resources/credentialusagesummary.md
  api-reference/beta/resources/credentialuserregistrationcount.md
  api-reference/beta/resources/credentialuserregistrationdetails.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/usercredentialusagedetails.md
  api-reference/beta/resources/userregistrationcount.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: ready to merge

#4952 Intune 1906 beta grouppolicy
  api-reference/beta/api/intune-grouppolicy-grouppolicydefinitionfile-get.md
  api-reference/beta/api/intune-grouppolicy-grouppolicydefinitionfile-update.md
  api-reference/beta/api/intune-grouppolicy-grouppolicypresentationlistbox-create.md
  api-reference/beta/api/intune-grouppolicy-grouppolicypresentationlistbox-delete.md
  api-reference/beta/api/intune-grouppolicy-grouppolicypresentationlistbox-get.md
  api-reference/beta/api/intune-grouppolicy-grouppolicypresentationlistbox-list.md
  api-reference/beta/api/intune-grouppolicy-grouppolicypresentationlistbox-update.md
  api-reference/beta/resources/intune-grouppolicy-grouppolicydefinitionfile.md
  api-reference/beta/resources/intune-grouppolicy-grouppolicypresentationlistbox.md
  concepts/changelog.md
Labels: area: intune, ready to merge

#5043 Fixing video link
  concepts/security-concept-overview.md
Labels: ready to merge

#5009 Fix Wrong Parameter on One Note Tab Configuration
  concepts/teams-configuring-builtin-tabs.md
Labels: ready to merge

#4965 Update profilephoto-get.md
  api-reference/v1.0/api/profilephoto-get.md
Labels: changes requested

#5051 Tighten preamble, better correlate w/ changelog.
  concepts/changelog.md
  concepts/whats-new-overview.md
Labels: do not merge

#5075 fix for git issue 4221
  api-reference/beta/api/directoryaudit-list.md
Labels: ready to merge

#5074 fix for git issue 4260
  api-reference/beta/resources/organization.md
  api-reference/v1.0/resources/organization.md
Labels: ready to merge

#5072 added author metadata to synchronization
  api-reference/beta/api/synchronization-synchronizationjob-delete.md
  api-reference/beta/api/synchronization-synchronizationjob-get.md
  api-reference/beta/api/synchronization-synchronizationjob-list.md
  api-reference/beta/api/synchronization-synchronizationjob-pause.md
  api-reference/beta/api/synchronization-synchronizationjob-post.md
  api-reference/beta/api/synchronization-synchronizationjob-restart.md
  api-reference/beta/api/synchronization-synchronizationjob-start.md
  api-reference/beta/api/synchronization-synchronizationjob-validatecredentials.md
  api-reference/beta/api/synchronization-synchronizationschema-delete.md
  api-reference/beta/api/synchronization-synchronizationschema-filteroperators.md
  api-reference/beta/api/synchronization-synchronizationschema-functions.md
  api-reference/beta/api/synchronization-synchronizationschema-get.md
  api-reference/beta/api/synchronization-synchronizationschema-parseexpression.md
  api-reference/beta/api/synchronization-synchronizationschema-update.md
  api-reference/beta/api/synchronization-synchronizationtemplate-get.md
  api-reference/beta/api/synchronization-synchronizationtemplate-list.md
  api-reference/beta/api/synchronization-synchronizationtemplate-post.md
  api-reference/beta/api/synchronization-synchronizationtemplate-update.md
  api-reference/beta/resources/synchronization-attributedefinition.md
  api-reference/beta/resources/synchronization-attributemapping.md
  api-reference/beta/resources/synchronization-attributemappingfunctionschema.md
  api-reference/beta/resources/synchronization-attributemappingparameterschema.md
  api-reference/beta/resources/synchronization-attributemappingsource.md
  api-reference/beta/resources/synchronization-configure-with-custom-target-attributes.md
  api-reference/beta/resources/synchronization-configure-with-directory-extension-attributes.md
  api-reference/beta/resources/synchronization-directorydefinition.md
  api-reference/beta/resources/synchronization-expressioninputobject.md
  api-reference/beta/resources/synchronization-filter.md
  api-reference/beta/resources/synchronization-filterclause.md
  api-reference/beta/resources/synchronization-filtergroup.md
  api-reference/beta/resources/synchronization-filteroperand.md
  api-reference/beta/resources/synchronization-filteroperatorschema.md
  api-reference/beta/resources/synchronization-metadataentry.md
  api-reference/beta/resources/synchronization-objectdefinition.md
  api-reference/beta/resources/synchronization-objectmapping.md
  api-reference/beta/resources/synchronization-overview.md
  api-reference/beta/resources/synchronization-parseexpressionresponse.md
  api-reference/beta/resources/synchronization-quarantine.md
  api-reference/beta/resources/synchronization-referencedobject.md
  api-reference/beta/resources/synchronization-secretkeystringvaluepair.md
  api-reference/beta/resources/synchronization-stringkeyattributemappingsourcevaluepair.md
  api-reference/beta/resources/synchronization-stringkeylongvaluepair.md
  api-reference/beta/resources/synchronization-stringkeyobjectvaluepair.md
  api-reference/beta/resources/synchronization-stringkeystringvaluepair.md
  api-reference/beta/resources/synchronization-synchronizationerror.md
  api-reference/beta/resources/synchronization-synchronizationjob.md
  api-reference/beta/resources/synchronization-synchronizationjobrestartcriteria.md
  api-reference/beta/resources/synchronization-synchronizationprogress.md
  api-reference/beta/resources/synchronization-synchronizationrule.md
  api-reference/beta/resources/synchronization-synchronizationschedule.md
  api-reference/beta/resources/synchronization-synchronizationschema.md
  api-reference/beta/resources/synchronization-synchronizationstatus.md
  api-reference/beta/resources/synchronization-synchronizationtaskexecution.md
  api-reference/beta/resources/synchronization-synchronizationtemplate.md
Labels: ready to merge

#5042 Adding Organization.Read.All and Organization.ReadWrite.All permissions
  api-reference/beta/api/organization-get.md
  api-reference/beta/api/organization-update.md
  api-reference/beta/api/subscribedsku-get.md
  api-reference/beta/api/subscribedsku-list.md
  api-reference/beta/resources/subscribedsku.md
  api-reference/v1.0/api/organization-get.md
  api-reference/v1.0/api/organization-update.md
  api-reference/v1.0/api/subscribedsku-get.md
  api-reference/v1.0/api/subscribedsku-list.md
  api-reference/v1.0/resources/subscribedsku.md
  concepts/changelog.md
  concepts/permissions-reference.md
Labels: area: azure/AAD, ready to merge

#5081 fix for git issue 4915
  api-reference/beta/api/directory-deleteditems-restore.md
  api-reference/v1.0/api/directory-deleteditems-restore.md
Labels: ready to merge

#4684 Updated concepts/sdks/choose-authentication-provider
  concepts/sdks/choose-authentication-providers.md
Labels: do not merge, review requested

#5113 Clarify chatMessage.lastModifiedDateTime
  api-reference/beta/resources/chatmessage.md
Labels: ready to merge

#5104 corrected link
  api-reference/beta/resources/authenticationmethods-usage-insights-overview.md
Labels: ready to merge

#5114 Add documentation for expiratinDateTime and password
  api-reference/beta/api/driveitem-createlink.md
  concepts/changelog.md
Labels: ready to merge

#5132 typo fix
  api-reference/v1.0/api/alert-list.md
Labels: area: Security, ready to merge

#5128 fix for git issue 4226
  api-reference/beta/api/governanceresource-register.md
Labels: ready to merge

#5139 Make consistent H3 section titles.
  concepts/changelog.md
Labels: do not merge

#5112 Update MSAL Auth Provider Examples For .NET SDK
  concepts/sdks/choose-authentication-providers.md
  concepts/sdks/create-client.md
Labels: ready to merge

#4249 Application permissions support for reading channel messages
  api-reference/beta/api/channel-get-message.md
  api-reference/beta/api/channel-get-messagereply.md
  api-reference/beta/api/channel-list-messagereplies.md
  api-reference/beta/api/channel-list-messages.md
  api-reference/beta/api/chat-get-message.md
  api-reference/beta/api/chat-list-members.md
  api-reference/beta/api/chatmessage-get.md
  api-reference/beta/api/chatmessage-list-replies.md
  api-reference/beta/api/chatmessage-list.md
  api-reference/beta/resources/chat.md
  api-reference/beta/resources/chatmessage.md
  api-reference/beta/toc.yml
  concepts/changelog.md
  concepts/teams-protected-apis.md
  concepts/toc.yml
Labels: area: teams, ready to merge

#5102 Mail-Enabled security groups
  api-reference/v1.0/api/group-post-members.md
Labels: review requested

#5088 fix: Unordered list formatting
  api-reference/beta/api/programcontrol-create.md
  api-reference/beta/resources/calendar.md
  api-reference/beta/resources/event.md
  api-reference/beta/resources/licenseAssignmentState.md
  api-reference/beta/resources/plannerplancontext.md
  api-reference/beta/resources/schemaextension.md
  api-reference/v1.0/resources/calendar.md
  api-reference/v1.0/resources/event.md
  api-reference/v1.0/resources/licenseassignmentstate.md
  api-reference/v1.0/resources/schemaextension.md
  concepts/auth-register-app-v2.md
  concepts/best-practices-concept.md
  concepts/call-api.md
  concepts/education-concept-overview.md
  concepts/migrate-azure-ad-graph-planning-checklist.md
  concepts/notifications-integration-app-registration.md
  concepts/onenote-update-page.md
  concepts/open-onenote-client.md
  concepts/outlook-get-free-busy-schedule.md
  concepts/security-qradar-siemintegration.md
  concepts/security-splunk-siemintegration.md
  concepts/toolkit/providers.md
  concepts/versioning-and-support.md
  concepts/webhooks-outlook-authz.md
Labels: changes requested

#5068 Updates to appRole field descriptions
  api-reference/beta/resources/approle.md
Labels: area: app model

#5146 expose more properties in reports api
  api-reference/beta/api/reportroot-getmailboxusagedetail.md
  api-reference/beta/api/reportroot-getoffice365groupsactivitydetail.md
  api-reference/beta/resources/mailboxusagedetail.md
  api-reference/beta/resources/office365groupsactivitydetail.md
  concepts/changelog.md
Labels: ready to merge

#5170 fix for workitem 627679
  api-reference/beta/resources/group.md
  api-reference/beta/toc.yml
  api-reference/v1.0/resources/group.md
  api-reference/v1.0/toc.yml
Labels: ready to merge

#5171 Time zone support when creating/updating events.
  api-reference/beta/api/event-update.md
  api-reference/beta/api/user-post-events.md
  api-reference/beta/resources/datetimetimezone.md
  api-reference/beta/resources/event.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/event-update.md
  api-reference/v1.0/api/user-post-events.md
  api-reference/v1.0/resources/datetimetimezone.md
  api-reference/v1.0/resources/event.md
  api-reference/v1.0/toc.yml
Labels: do not merge

#5032 add validateProperties
  api-reference/beta/toc.yml
  api-reference/v1.0/api/directoryobject-validateproperties.md
  api-reference/v1.0/api/group-validateproperties.md
  api-reference/v1.0/includes/snippets/csharp/directoryobject-validateproperties-csharp-snippets.md
  api-reference/v1.0/includes/snippets/csharp/group-validateproperties-csharp-snippets.md
  api-reference/v1.0/includes/snippets/javascript/directoryobject-validateproperties-javascript-snippets.md
  api-reference/v1.0/includes/snippets/javascript/group-validateproperties-javascript-snippets.md
  api-reference/v1.0/includes/snippets/objc/directoryobject-validateproperties-objc-snippets.md
  api-reference/v1.0/includes/snippets/objc/group-validateproperties-objc-snippets.md
  api-reference/v1.0/resources/directoryobject.md
  api-reference/v1.0/resources/group.md
  api-reference/v1.0/toc.yml
  concepts/changelog.md
Labels: ready to merge

#5192 Documented bug applying $select on 2 event properties.
  api-reference/beta/api/calendar-list-calendarview.md
  api-reference/beta/api/group-list-calendarview.md
  api-reference/beta/api/user-list-calendarview.md
  api-reference/v1.0/api/calendar-list-calendarview.md
  api-reference/v1.0/api/group-list-calendarview.md
  api-reference/v1.0/api/user-list-calendarview.md
Labels: do not merge

#4485 Added new On-premises Publishing Profile API docs
  api-reference/beta/api/onpremisesagent-delete-agentgroups.md
  api-reference/beta/api/onpremisesagent-get.md
  api-reference/beta/api/onpremisesagent-list.md
  api-reference/beta/api/onpremisesagent-post-agentgroups.md
  api-reference/beta/api/onpremisesagentgroup-delete.md
  api-reference/beta/api/onpremisesagentgroup-get.md
  api-reference/beta/api/onpremisesagentgroup-list.md
  api-reference/beta/api/onpremisesagentgroup-post.md
  api-reference/beta/api/onpremisesagentgroup-update.md
  api-reference/beta/api/onpremisespublishingprofile-get.md
  api-reference/beta/api/onpremisespublishingprofile-update.md
  api-reference/beta/api/publishedresource-delete-agentgroups.md
  api-reference/beta/api/publishedresource-delete.md
  api-reference/beta/api/publishedresource-get.md
  api-reference/beta/api/publishedresource-list.md
  api-reference/beta/api/publishedresource-post-agentgroups.md
  api-reference/beta/api/publishedresource-post.md
  api-reference/beta/api/publishedresource-update.md
  api-reference/beta/resources/hybridagentupdaterconfiguration.md
  api-reference/beta/resources/onpremisesagent.md
  api-reference/beta/resources/onpremisesagentgroup.md
  api-reference/beta/resources/onpremisespublishing.md
  api-reference/beta/resources/onpremisespublishingprofile-root.md
  api-reference/beta/resources/onpremisespublishingprofile.md
  api-reference/beta/resources/publishedresource.md
  api-reference/beta/resources/updatewindow.md
  api-reference/beta/toc.yml
  concepts/permissions-reference.md
Labels: area: azure/AAD, ready to merge

#5211 Update group.md
  api-reference/beta/resources/group.md
Labels: awaiting internal response

#5195 Mute is not in the table of contents
  api-reference/beta/toc.yml
Labels: review requested

#3846 Update Taxonomy support in Get List API
  api-reference/beta/api/list-get.md
Labels: changes requested

#4681 Places API
  api-reference/beta/api/place-get.md
  api-reference/beta/api/place-list.md
  api-reference/beta/resources/place.md
  api-reference/beta/resources/room.md
  api-reference/beta/resources/roomlist.md
  api-reference/beta/toc.yml
  concepts/changelog.md
  concepts/outlook-calendar-concept-overview.md
  concepts/permissions-reference.md
  concepts/places-concept-overview.md
Labels: changes requested, do not merge

#4120 Images only accept data-url or binary part
  concepts/onenote-update-page.md
Labels: review requested

#5048 Update the document to not include the ConnectorDataStore into the Reset Scope example.
  api-reference/beta/api/synchronization-synchronizationjob-restart.md
  api-reference/beta/includes/snippets/csharp/synchronizationjob-restart-csharp-snippets.md
  api-reference/beta/includes/snippets/java/synchronizationjob-restart-java-snippets.md
  api-reference/beta/includes/snippets/javascript/synchronizationjob-restart-javascript-snippets.md
  api-reference/beta/includes/snippets/objc/synchronizationjob-restart-objc-snippets.md
Labels: ready to merge

#4503 Add three new properties to the directory definition
  api-reference/beta/api/directorydefinition-discover.md
  api-reference/beta/resources/synchronization-directorydefinition.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: area: azure/AAD, ready to merge

#5251 Gitissue4794
  api-reference/beta/api/application-post-owners.md
Labels: ready to merge

#4867 att targetResource must be targetResources to work
  api-reference/v1.0/api/directoryaudit-list.md
Labels: ready to merge, review requested

#5250 Added Mail.ReadBasic.All
  api-reference/beta/api/mailfolder-delta.md
  api-reference/beta/api/mailfolder-get.md
  api-reference/beta/api/mailfolder-list-childfolders.md
  api-reference/beta/api/mailfolder-list-messages.md
  api-reference/beta/api/message-delta.md
  api-reference/beta/api/message-get.md
  api-reference/beta/api/user-list-mailfolders.md
  api-reference/beta/api/user-list-messages.md
  concepts/changelog.md
  concepts/permissions-reference.md
Labels: ready to merge

#5271 Tried enabling API Doctor properly.
  api-reference/beta/api/teamsappinstallation-add.md
  api-reference/beta/api/teamsappinstallation-delete.md
  api-reference/beta/api/teamsappinstallation-list.md
  api-reference/beta/api/teamsappinstallation-upgrade.md
  api-reference/beta/api/user-add-teamsappinstallation.md
  api-reference/beta/api/user-delete-teamsappinstallation.md
  api-reference/beta/api/user-list-teamsappinstallation.md
  api-reference/beta/api/user-upgrade-teamsappinstallation.md
  api-reference/beta/resources/teamsappinstallation.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/teamsappinstallation-add.md
  api-reference/v1.0/api/teamsappinstallation-delete.md
  api-reference/v1.0/api/teamsappinstallation-list.md
  api-reference/v1.0/api/teamsappinstallation-upgrade.md
  api-reference/v1.0/resources/teamsappinstallation.md
  api-reference/v1.0/toc.yml
  concepts/changelog.md
Labels: do not merge

#5286 Updated author and ms.prod
  api-reference/beta/api/application-post-applications.md
  api-reference/beta/api/application-post-owners.md
Labels: ready to merge

#4851 added post unfollow
  api-reference/beta/api/driveitem-unfollow.md
Labels: review requested

#5268 AdministrativeUnit.*.All and RoleManagement.*.Directory
  api-reference/beta/api/administrativeunit-delete-members.md
  api-reference/beta/api/administrativeunit-delete-scopedrolemembers.md
  api-reference/beta/api/administrativeunit-delete.md
  api-reference/beta/api/administrativeunit-get-members.md
  api-reference/beta/api/administrativeunit-get-scopedrolemembers.md
  api-reference/beta/api/administrativeunit-get.md
  api-reference/beta/api/administrativeunit-list-members.md
  api-reference/beta/api/administrativeunit-list-scopedrolemembers.md
  api-reference/beta/api/administrativeunit-list.md
  api-reference/beta/api/administrativeunit-post-administrativeunits.md
  api-reference/beta/api/administrativeunit-post-members.md
  api-reference/beta/api/administrativeunit-post-scopedrolemembers.md
  api-reference/beta/api/administrativeunit-update.md
  api-reference/v1.0/api/directoryrole-delete-member.md
  api-reference/v1.0/api/directoryrole-post-members.md
  concepts/changelog.md
  concepts/permissions-reference.md
Labels: changes requested, do not merge

#4204 [Do not merge] Docs for Bundles
  api-reference/beta/api/bundle-additem.md
  api-reference/beta/api/bundle-delete.md
  api-reference/beta/api/bundle-get.md
  api-reference/beta/api/bundle-list.md
  api-reference/beta/api/bundle-removeitem.md
  api-reference/beta/api/bundle-update.md
  api-reference/beta/api/drive-post-bundles.md
  api-reference/beta/api/permission-grant.md
  api-reference/beta/resources/album.md
  api-reference/beta/resources/bundle.md
  api-reference/beta/resources/drive.md
  api-reference/beta/resources/permission.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: ready to merge

#5289 Adding loop support to playprompt operation. Adding media file details.
  api-reference/beta/api/call-playprompt.md
  api-reference/beta/resources/mediainfo.md
  api-reference/beta/resources/mediaprompt.md
Labels: ready to merge

#5307 fix joinedTeams doc
  api-reference/beta/api/user-list-joinedteams.md
Labels: ready to merge

#5308 Fix permissions for scoped role member APIs
  api-reference/beta/api/administrativeunit-delete-scopedrolemembers.md
  api-reference/beta/api/administrativeunit-get-members.md
  api-reference/beta/api/administrativeunit-get-scopedrolemembers.md
  api-reference/beta/api/administrativeunit-get.md
  api-reference/beta/api/administrativeunit-list-members.md
  api-reference/beta/api/administrativeunit-list-scopedrolemembers.md
  api-reference/beta/api/administrativeunit-list.md
  api-reference/beta/api/administrativeunit-post-scopedrolemembers.md
  api-reference/beta/api/directoryrole-delete-member.md
  api-reference/beta/api/directoryrole-delta.md
  api-reference/beta/api/directoryrole-get.md
  api-reference/beta/api/directoryrole-list-members.md
  api-reference/beta/api/directoryrole-list-scopedadministrators.md
  api-reference/beta/api/directoryrole-list.md
  api-reference/beta/api/directoryrole-post-directoryroles.md
  api-reference/beta/api/directoryrole-post-members.md
  api-reference/beta/api/directoryroletemplate-get.md
  api-reference/beta/api/directoryroletemplate-list.md
  api-reference/v1.0/api/directoryrole-delta.md
  api-reference/v1.0/api/directoryrole-get.md
  api-reference/v1.0/api/directoryrole-list-members.md
  api-reference/v1.0/api/directoryrole-list.md
  api-reference/v1.0/api/directoryrole-post-directoryroles.md
  api-reference/v1.0/api/directoryroletemplate-get.md
  api-reference/v1.0/api/directoryroletemplate-list.md
Labels: ready to merge

#4780 Doc beta for lastPasswordChangeDateTime
  api-reference/beta/resources/user.md
  concepts/changelog.md
Labels: area: azure/AAD, ready to merge

#5316 add AccessReview.ReadWrite.Membership as an app permission
  api-reference/beta/api/accessreview-addreviewer.md
  api-reference/beta/api/accessreview-apply.md
  api-reference/beta/api/accessreview-create.md
  api-reference/beta/api/accessreview-delete.md
  api-reference/beta/api/accessreview-get.md
  api-reference/beta/api/accessreview-listdecisions.md
  api-reference/beta/api/accessreview-listreviewers.md
  api-reference/beta/api/accessreview-removereviewer.md
  api-reference/beta/api/accessreview-reset.md
  api-reference/beta/api/accessreview-sendreminder.md
  api-reference/beta/api/accessreview-stop.md
  api-reference/beta/api/accessreview-update.md
  api-reference/beta/api/businessflowtemplate-list.md
  concepts/changelog.md
  concepts/permissions-reference.md
Labels: area: azure/AAD, ready to merge

#5332 Documented some Teams permissions that have slipped through the cracks
  concepts/permissions-reference.md
Labels: ready to merge

#5329 Improve the description of Group.Read/ReadWrite.All by copying language from the consent dialog.
  concepts/permissions-reference.md
Labels: ready to merge
