Repository microsoftgraph/microsoft-graph-docs, pull requests merged in 2019-05, with the labels that each got.

#4443 Data connect doc changes v1
  concepts/data-connect-concept-overview.md
  concepts/data-connect-datasets.md
  concepts/data-connect-filtering.md
  concepts/data-connect-get-started.md
  concepts/data-connect-overview.md
  concepts/data-connect-pam.md
  concepts/data-connect-policies.md
  concepts/data-connect-tips.md
  concepts/deployments.md
  concepts/images/data-connect-keyvault-access.png
  concepts/images/data-connect-keyvault-create.png
  concepts/images/data-connect-tips.png
  concepts/overview.md
Labels: do not merge

#4463 Auth content revisions
  concepts/associate-account.md
  concepts/auth-overview.md
  concepts/auth-register-app-v2.md
  concepts/auth-v2-service.md
  concepts/auth-v2-user.md
  concepts/auth/.DS_Store
  concepts/auth/auth-concepts.md
  concepts/auth/index.yml
  concepts/azuread-identity-access-management-concept-overview.md
  concepts/breadcrumb/toc.yml
  concepts/deployments.md
  concepts/dynamics-business-central-concept-overview.md
  concepts/images/appreg-video.png
  concepts/images/auth-v2/new-app-overview-page-expanded.png
  concepts/images/auth-v2/new-app-registration-expanded.png
  concepts/images/auth-v2/v2-application-permissions.png
  concepts/images/index/logo_reactnative.svg
  concepts/images/v2-application-permissions.png
  concepts/overview.md
  concepts/toc.yml
  concepts/traverse-the-graph.md
  concepts/users-you-can-reach.md
Labels: changes requested, do not merge

#4149 publishing secure score api to graph v1.0
  api-reference/v1.0/api/securescore-get.md
  api-reference/v1.0/api/securescorecontrolprofile-get.md
  api-reference/v1.0/api/securescorecontrolprofile-update.md
  api-reference/v1.0/api/security-list-securescorecontrolprofiles.md
  api-reference/v1.0/api/security-list-securescores.md
  api-reference/v1.0/resources/averagecomparativescore.md
  api-reference/v1.0/resources/certificationcontrol.md
  api-reference/v1.0/resources/complianceinformation.md
  api-reference/v1.0/resources/controlscore.md
  api-reference/v1.0/resources/securescore.md
  api-reference/v1.0/resources/securescorecontrolprofile.md
  api-reference/v1.0/resources/securescorecontrolstateupdate.md
  api-reference/v1.0/resources/security-api-overview.md
  api-reference/v1.0/toc.yml
  concepts/changelog.md
  concepts/security-authorization.md
Labels: ready to merge

#4377 Adds risk history details + new reference topic
  api-reference/beta/api/riskyuser-list-history.md
  api-reference/beta/api/riskyuserhistoryitem-get.md
  api-reference/beta/api/riskyusers-confirmcompromised.md
  api-reference/beta/api/riskyusers-dismiss.md
  api-reference/beta/resources/riskyuser.md
  api-reference/beta/resources/riskyuserhistoryitem.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: ready to merge

#4404 AAD Graph to Microsoft Graph migration guidance (draft)
  concepts/migrate-azure-ad-graph-app-registration.md
  concepts/migrate-azure-ad-graph-audit-api-use.md
  concepts/migrate-azure-ad-graph-authentication-library.md
  concepts/migrate-azure-ad-graph-client-libraries.md
  concepts/migrate-azure-ad-graph-deploy-test-extend.md
  concepts/migrate-azure-ad-graph-feature-differences.md
  concepts/migrate-azure-ad-graph-method-differences.md
  concepts/migrate-azure-ad-graph-overview.md
  concepts/migrate-azure-ad-graph-planning-checklist.md
  concepts/migrate-azure-ad-graph-property-differences.md
  concepts/migrate-azure-ad-graph-request-differences.md
  concepts/migrate-azure-ad-graph-resource-differences.md
  concepts/toc.yml
Labels: area: azure/AAD, ready to merge

#4526 Expanding the role of Graph in M365.
  concepts/images/microsoft-graph-dataconnect-connectors-800.png
  concepts/overview.md
Labels: resolved: awaiting prod deployment

#4543 Add link
  api-reference/beta/api/channel-list.md
Labels: ready to merge

#3736 Update quick-start-faq.md
  concepts/quick-start-faq.md
Labels: do not merge

#4493 ItemAnalytics and ItemActivities docs moved from beta to v1.0
  api-reference/v1.0/api/itemactivitystat-getactivitybyinterval.md
  api-reference/v1.0/api/itemanalytics-get.md
  api-reference/v1.0/api/listitem-get.md
  api-reference/v1.0/api/listitem-update.md
  api-reference/v1.0/resources/accessaction.md
  api-reference/v1.0/resources/commentaction.md
  api-reference/v1.0/resources/createaction.md
  api-reference/v1.0/resources/deleteaction.md
  api-reference/v1.0/resources/driveitem.md
  api-reference/v1.0/resources/editaction.md
  api-reference/v1.0/resources/incompletedata.md
  api-reference/v1.0/resources/itemactionset.md
  api-reference/v1.0/resources/itemactionstat.md
  api-reference/v1.0/resources/itemactivity.md
  api-reference/v1.0/resources/itemactivitystat.md
  api-reference/v1.0/resources/itemactivitytimeset.md
  api-reference/v1.0/resources/itemanalytics.md
  api-reference/v1.0/resources/listitem.md
  api-reference/v1.0/resources/mentionaction.md
  api-reference/v1.0/resources/moveaction.md
  api-reference/v1.0/resources/renameaction.md
  api-reference/v1.0/resources/restoreaction.md
  api-reference/v1.0/resources/shareaction.md
  api-reference/v1.0/resources/site.md
  api-reference/v1.0/resources/versionaction.md
  api-reference/v1.0/toc.yml
  concepts/changelog.md
Labels: ready to merge

#4047 [ready-to-merge] Updating **securityEnabled** and **mailEnabled** properties.
  api-reference/beta/api/group-post-groups.md
  api-reference/beta/api/group-update.md
  api-reference/beta/resources/group.md
  api-reference/v1.0/api/group-post-groups.md
  api-reference/v1.0/api/group-update.md
  api-reference/v1.0/resources/group.md
Labels: area: azure/AAD, ready to merge

#4592 Add version info to outboundConnectionsRequired and outboundConnectio…
  api-reference/beta/resources/intune-deviceconfig-windowsfirewallnetworkprofile.md
Labels: ready to merge

#4593 Add info about Windows OS version for outboundConnectionsBlocked v1.01
  api-reference/v1.0/resources/intune-deviceconfig-windowsfirewallnetworkprofile.md
Labels: ready to merge

#4536 Notifications doc restructure and new content
  api-reference/beta/api/notifications-post.md
  api-reference/beta/resources/notifications-api-overview.md
  api-reference/beta/resources/project-rome-overview.md
  api-reference/beta/resources/projectrome-notification.md
  api-reference/beta/toc.yml
  concepts/cross-device-concept-overview.md
  concepts/images/notifications-api-permissions-list.png
  concepts/images/notifications-api-permissions-list_old.png
  concepts/images/notifications-api-permissions.png
  concepts/images/notifications-app-overview.png
  concepts/images/notifications-app-secrets.png
  concepts/images/notifications-crossdevice-azureportal-clientid.png
  concepts/images/notifications-crossdevice-domain-verify.png
  concepts/images/notifications-crossdevice-new-configure.png
  concepts/images/notifications-crossdevice-platform-appids.png
  concepts/images/notifications-crossdevice-push-cred.png
  concepts/images/notifications-crossdevice-supported-platforms.png
  concepts/images/notifications-flow-overview.png
  concepts/images/notifications-integration-e2e-overview.png
  concepts/images/notifications-new-notification-android.png
  concepts/images/notifications-new-notification-ios.png
  concepts/images/notifications-new-notification-windows.png
  concepts/images/notifications-notification-update-android.png
  concepts/images/notifications-notification-update-ios.png
  concepts/images/notifications-notification-update-windows.png
  concepts/images/notifications-nuget-1-manage.png
  concepts/images/notifications-nuget-2-find.png
  concepts/images/notifications-nuget-3-install.png
  concepts/images/notifications-register-app.png
  concepts/images/notifications-search-app-registrations.png
  concepts/notifications-concept-overview.md
  concepts/notifications-integrating-app-server.md
  concepts/notifications-integrating-with-android.md
  concepts/notifications-integrating-with-ios.md
  concepts/notifications-integrating-with-windows.md
  concepts/notifications-integration-app-registration.md
  concepts/notifications-integration-cross-device-experiences-onboarding.md
  concepts/notifications-integration-e2e-overview.md
  concepts/overview-major-services.md
  concepts/toc.yml
Labels: ready to merge

#4490 added assignedlabels property to beta
  api-reference/beta/resources/assignedlabel.md
  api-reference/beta/resources/group.md
  concepts/changelog.md
Labels: area: groups, changes requested, ready to merge

#4343 Fix calendargroup-post-calendars.md
  api-reference/v1.0/api/calendargroup-post-calendars.md
Labels: do not merge, review requested

#4491 Docs & Changelog for chat membership
  api-reference/beta/api/chatmembership-get.md
  api-reference/beta/api/chatmembership-list.md
  api-reference/beta/resources/conversationmember.md
  concepts/changelog.md
Labels: do not merge

#4641 Adding Chat.ReadWrite
  concepts/permissions-reference.md
Labels: ready to merge

#4625 Added Message deeplink/weburl for Channel messages
  api-reference/beta/api/channel-get-message.md
  api-reference/beta/api/channel-get-messagereply.md
  api-reference/beta/api/channel-list-messagereplies.md
  api-reference/beta/api/channel-list-messages.md
  api-reference/beta/resources/chatmessage.md
  concepts/changelog.md
Labels: ready to merge

#4635 Add owner principal name in onedriveusage and sharepointusage report API
  api-reference/beta/api/reportroot-getonedriveusageaccountdetail.md
  api-reference/beta/api/reportroot-getsharepointsiteusagedetail.md
  api-reference/beta/resources/onedriveusageaccountdetail.md
  api-reference/beta/resources/sharepointsiteusagedetail.md
  concepts/changelog.md
Labels: ready to merge

#4643 chat membership APIs
  api-reference/beta/api/conversationmember-get.md
  api-reference/beta/api/conversationmember-list.md
  api-reference/beta/resources/aaduserconversationmember.md
  api-reference/beta/resources/chat.md
  api-reference/beta/resources/conversationmember.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: area: teams, ready to merge

#4657 [Azure AD] [PIM] Separated into Azure AD and Azure resources
  api-reference/beta/api/governanceresource-get.md
  api-reference/beta/api/governanceresource-list.md
  api-reference/beta/api/governanceresource-register.md
  api-reference/beta/api/governanceroleassignment-export.md
  api-reference/beta/api/governanceroleassignment-get.md
  api-reference/beta/api/governanceroleassignment-list.md
  api-reference/beta/api/governanceroleassignmentrequest-cancel.md
  api-reference/beta/api/governanceroleassignmentrequest-get.md
  api-reference/beta/api/governanceroleassignmentrequest-list.md
  api-reference/beta/api/governanceroleassignmentrequest-post.md
  api-reference/beta/api/governanceroleassignmentrequest-update.md
  api-reference/beta/api/governanceroledefinition-get.md
  api-reference/beta/api/governanceroledefinition-list.md
  api-reference/beta/api/governancerolesetting-get.md
  api-reference/beta/api/governancerolesetting-list.md
  api-reference/beta/api/governancerolesetting-update.md
  api-reference/beta/resources/governanceroledefinition.md
  api-reference/beta/resources/privilegedidentitymanagement-directory.md
  api-reference/beta/resources/privilegedidentitymanagement-resources.md
  api-reference/beta/resources/privilegedidentitymanagement-root.md
  api-reference/beta/toc.yml
Labels: area: azure/AAD, ready to merge

#4675 Adding federated users notice and revoking sign in sessions
  api-reference/beta/api/user-post-users.md
  api-reference/beta/api/user-revokesigninsessions.md
  api-reference/beta/resources/user.md
  api-reference/v1.0/api/user-post-users.md
Labels: ready to merge

#4708 Update data-connect-get-started.md
  concepts/data-connect-get-started.md
Labels: ready to merge

#4710 Remove uppercase letters from all urls.
  api-reference/beta/api/application-update.md
  api-reference/beta/api/call-playprompt.md
  api-reference/beta/api/privilegedroleassignmentrequest-cancel.md
  api-reference/beta/api/riskyusers-get.md
  api-reference/beta/api/riskyusers-list.md
  api-reference/beta/api/tiindicator-update.md
  api-reference/beta/api/trustframeworkpolicy-get.md
  api-reference/beta/resources/educationcategory.md
  api-reference/beta/resources/educationclass.md
  api-reference/beta/resources/playpromptoperation.md
  api-reference/beta/resources/riskyuser.md
  api-reference/beta/resources/timeoff.md
  api-reference/v1.0/api/identityprovider-get.md
  api-reference/v1.0/api/identityprovider-list.md
  api-reference/v1.0/api/identityprovider-post-identityproviders.md
  api-reference/v1.0/resources/auditlogroot.md
  api-reference/v1.0/resources/itemactivity.md
  api-reference/v1.0/resources/securescorecontrolprofile.md
Labels: ready to merge

#4655 Update "Create team" examples to include teamify support
  api-reference/beta/api/team-post.md
  api-reference/beta/api/team-put-teams.md
Labels: ready to merge
