Repository microsoftgraph/microsoft-graph-docs, pull requests merged in 2019-08, with the labels that each got.

#5319 Corrections, edits to Record, Play API's
  api-reference/beta/api/call-playprompt.md
  api-reference/beta/api/call-record.md
  api-reference/beta/resources/recordoperation.md
Labels: ready to merge

#4619 Initial version of documentation for feature rollout policy.
  api-reference/beta/api/directory-list-featurerolloutpolicies.md
  api-reference/beta/api/directory-post-featurerolloutpolicies.md
  api-reference/beta/api/featurerolloutpolicy-delete-appliesto.md
  api-reference/beta/api/featurerolloutpolicy-delete.md
  api-reference/beta/api/featurerolloutpolicy-get.md
  api-reference/beta/api/featurerolloutpolicy-post-appliesto.md
  api-reference/beta/api/featurerolloutpolicy-update.md
  api-reference/beta/resources/directory.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/featurerolloutpolicy.md
  api-reference/beta/toc.yml
  concepts/changelog.md
  concepts/permissions-reference.md
Labels: area: azure/AAD, beta, ready to merge

#5345 Snippets Updates
  api-reference/beta/api/directory-list-featurerolloutpolicies.md
  api-reference/beta/api/directory-post-featurerolloutpolicies.md
  api-reference/beta/api/featurerolloutpolicy-delete-appliesto.md
  api-reference/beta/api/featurerolloutpolicy-get.md
  api-reference/beta/api/featurerolloutpolicy-post-appliesto.md
  api-reference/beta/includes/snippets/csharp/create-bookingappointment-from-bookingbusiness-csharp-snippets.md
  api-reference/beta/includes/snippets/csharp/create-directoryobject-from-featurerolloutpolicy-csharp-snippets.md
  api-reference/beta/includes/snippets/csharp/create-featurerolloutpolicy-from-directory-csharp-snippets.md
  api-reference/beta/includes/snippets/csharp/create-tiindicator-from-security-csharp-snippets.md
  api-reference/beta/includes/snippets/csharp/delete-directoryobject-from-featurerolloutpolicy-csharp-snippets.md
  api-reference/beta/includes/snippets/csharp/get-featurerolloutpolicies-csharp-snippets.md
  api-reference/beta/includes/snippets/csharp/get-featurerolloutpolicy-csharp-snippets.md
  api-reference/beta/includes/snippets/csharp/tiindicator-submittiindicators-csharp-snippets.md
  api-reference/beta/includes/snippets/csharp/update-bookingappointment-csharp-snippets.md
  api-reference/beta/includes/snippets/java/create-bookingappointment-from-bookingbusiness-java-snippets.md
  api-reference/beta/includes/snippets/java/create-directoryobject-from-featurerolloutpolicy-java-snippets.md
  api-reference/beta/includes/snippets/java/create-featurerolloutpolicy-from-directory-java-snippets.md
  api-reference/beta/includes/snippets/java/create-tiindicator-from-security-java-snippets.md
  api-reference/beta/includes/snippets/java/delete-directoryobject-from-featurerolloutpolicy-java-snippets.md
  api-reference/beta/includes/snippets/java/get-featurerolloutpolicies-java-snippets.md
  api-reference/beta/includes/snippets/java/get-featurerolloutpolicy-java-snippets.md
  api-reference/beta/includes/snippets/java/tiindicator-submittiindicators-java-snippets.md
  api-reference/beta/includes/snippets/java/update-bookingappointment-java-snippets.md
  api-reference/beta/includes/snippets/javascript/call-playprompt-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/call-record-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/create-directoryobject-from-featurerolloutpolicy-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/create-featurerolloutpolicy-from-directory-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/delete-directoryobject-from-featurerolloutpolicy-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/get-featurerolloutpolicies-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/get-featurerolloutpolicy-javascript-snippets.md
  api-reference/beta/includes/snippets/objc/create-bookingappointment-from-bookingbusiness-objc-snippets.md
  api-reference/beta/includes/snippets/objc/create-directoryobject-from-featurerolloutpolicy-objc-snippets.md
  api-reference/beta/includes/snippets/objc/create-featurerolloutpolicy-from-directory-objc-snippets.md
  api-reference/beta/includes/snippets/objc/create-tiindicator-from-security-objc-snippets.md
  api-reference/beta/includes/snippets/objc/delete-directoryobject-from-featurerolloutpolicy-objc-snippets.md
  api-reference/beta/includes/snippets/objc/get-featurerolloutpolicies-objc-snippets.md
  api-reference/beta/includes/snippets/objc/get-featurerolloutpolicy-objc-snippets.md
  api-reference/beta/includes/snippets/objc/tiindicator-submittiindicators-objc-snippets.md
  api-reference/beta/includes/snippets/objc/update-bookingappointment-objc-snippets.md
Labels: ready to merge

#5328 add accessreview.readwrite.membership as a delegated permission
  api-reference/beta/api/accessreview-addreviewer.md
  api-reference/beta/api/accessreview-apply.md
  api-reference/beta/api/accessreview-create.md
  api-reference/beta/api/accessreview-delete.md
  api-reference/beta/api/accessreview-get.md
  api-reference/beta/api/accessreview-listdecisions.md
  api-reference/beta/api/accessreview-listmydecisions.md
  api-reference/beta/api/accessreview-listreviewers.md
  api-reference/beta/api/accessreview-removereviewer.md
  api-reference/beta/api/accessreview-reset.md
  api-reference/beta/api/accessreview-sendreminder.md
  api-reference/beta/api/accessreview-stop.md
  api-reference/beta/api/accessreview-update.md
  api-reference/beta/api/businessflowtemplate-list.md
  api-reference/beta/resources/accessreviews-root.md
  concepts/permissions-reference.md
Labels: area: azure/AAD, ready to merge

#4863 Rossten/outcomes2 - outcomes, rubrics, and makecode resources
  api-reference/beta/api/educationassignment-delete-rubric.md
  api-reference/beta/api/educationassignment-get-rubric.md
  api-reference/beta/api/educationassignment-put-rubric.md
  api-reference/beta/api/educationoutcome-update.md
  api-reference/beta/api/educationrubric-delete.md
  api-reference/beta/api/educationrubric-get.md
  api-reference/beta/api/educationrubric-update.md
  api-reference/beta/api/educationsubmission-list-outcomes.md
  api-reference/beta/api/educationuser-list-rubrics.md
  api-reference/beta/api/educationuser-post-rubrics.md
  api-reference/beta/resources/educationassignment.md
  api-reference/beta/resources/educationassignmentpointsgrade.md
  api-reference/beta/resources/educationassignmentpointsgradetype.md
  api-reference/beta/resources/educationfeedbackoutcome.md
  api-reference/beta/resources/educationmakecoderesource.md
  api-reference/beta/resources/educationoutcome.md
  api-reference/beta/resources/educationpointsoutcome.md
  api-reference/beta/resources/educationrubric.md
  api-reference/beta/resources/educationrubricoutcome.md
  api-reference/beta/resources/educationsubmission.md
  api-reference/beta/resources/rubriccriterion.md
  api-reference/beta/resources/rubriclevel.md
  api-reference/beta/resources/rubricquality.md
  api-reference/beta/resources/rubricqualityfeedbackmodel.md
  api-reference/beta/resources/rubricqualityselectedcolumnmodel.md
  api-reference/beta/toc.yml
  concepts/changelog.md
  concepts/education-rubric-overview.md
Labels: ready to merge

#5331 Update the Calendar docs to mention that they work with Group.Read.All.
  api-reference/beta/api/calendar-get.md
Labels: review requested

#5361 Fix for #5359
  api-reference/beta/api/user-revokesigninsessions.md
  api-reference/v1.0/api/user-revokesigninsessions.md
  concepts/known-issues.md
Labels: ready to merge

#5385 Fixed busted links in revokeSignInSessions
  api-reference/beta/api/user-revokesigninsessions.md
  api-reference/v1.0/api/user-revokesigninsessions.md
Labels: ready to merge

#5327 fix for git issue 5282
  api-reference/beta/api/user-update.md
  api-reference/v1.0/api/user-update.md
Labels: ready to merge

#5419 Clarify timelines for protected APIs
  concepts/teams-protected-apis.md
Labels: area: teams, ready to merge

#5427 fix for git issue 4997
  api-reference/beta/resources/signin.md
Labels: ready to merge

#5429 heading correction for user-update
  api-reference/v1.0/api/user-update.md
Labels: ready to merge

#5433 Clarify long-running operation
  api-reference/beta/api/team-clone.md
Labels: area: teams, ready to merge

#5392 expose more properties in Reports Graph API v1.0
  api-reference/beta/api/reportroot-getoffice365servicesusercounts.md
  api-reference/v1.0/api/reportroot-getmailboxusagedetail.md
  api-reference/v1.0/api/reportroot-getoffice365groupsactivitydetail.md
  api-reference/v1.0/api/reportroot-getoffice365servicesusercounts.md
  api-reference/v1.0/api/reportroot-getonedriveusageaccountdetail.md
  api-reference/v1.0/api/reportroot-getsharepointsiteusagedetail.md
  concepts/changelog.md
Labels: ready to merge

#5399 Incorrect C# Syntax In Code Block
  concepts/migrate-azure-ad-graph-client-libraries.md
Labels: ready to merge

#5219 Updating subscribetotone documentation to align with the code.
  api-reference/beta/api/call-subscribetotone.md
Labels: ready to merge

#5086 fix: MD037/no-space-in-emphasis
  api-reference/beta/api/intune-cirrus-officeclientconfigurationassignment-delete.md
  api-reference/beta/api/intune-cirrus-officeclientconfigurationassignment-get.md
  api-reference/beta/api/intune-cirrus-officeclientconfigurationassignment-list.md
  api-reference/beta/api/intune-cirrus-officeclientconfigurationassignment-update.md
Labels: awaiting internal response, ready to merge

#5336 role management APIs
  api-reference/beta/api/rbacapplication-list-roleassignments.md
  api-reference/beta/api/rbacapplication-list-roledefinitions.md
  api-reference/beta/api/rbacapplication-post-roleassignments.md
  api-reference/beta/api/rbacapplication-post-roledefinitions.md
  api-reference/beta/api/unifiedroleassignment-delete.md
  api-reference/beta/api/unifiedroleassignment-get.md
  api-reference/beta/api/unifiedroledefinition-delete.md
  api-reference/beta/api/unifiedroledefinition-get.md
  api-reference/beta/api/unifiedroledefinition-update.md
  api-reference/beta/resources/rbacapplication.md
  api-reference/beta/resources/rolemanagement.md
  api-reference/beta/resources/unifiedroleassignment.md
  api-reference/beta/resources/unifiedroledefinition.md
  api-reference/beta/resources/unifiedrolepermission.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: do not merge

#5457 Added August items to date. Fixed header.
  concepts/changelog.md
  concepts/whats-new-overview.md
Labels: do not merge

#5461 Updated migration topic
  api-reference/beta/api/user-post-manager.md
  api-reference/beta/resources/directoryrole.md
  api-reference/beta/resources/directoryroletemplate.md
  api-reference/beta/resources/invitation.md
  api-reference/v1.0/api/user-post-manager.md
  api-reference/v1.0/api/user-revokesigninsessions.md
  api-reference/v1.0/resources/directoryrole.md
  api-reference/v1.0/resources/directoryroletemplate.md
  concepts/migrate-azure-ad-graph-property-differences.md
Labels: ready to merge

#4992 Origin/madehmer analytics api
  api-reference/beta/api/activitystatistics-get.md
  api-reference/beta/api/activitystatistics-list.md
  api-reference/beta/api/useranalytics-get-settings.md
  api-reference/beta/resources/activitystatistics.md
  api-reference/beta/resources/callactivitystatistics.md
  api-reference/beta/resources/chatactivitystatistics.md
  api-reference/beta/resources/emailactivitystatistics.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/focusactivitystatistics.md
  api-reference/beta/resources/meetingactivitystatistics.md
  api-reference/beta/resources/settings.md
  api-reference/beta/resources/social-overview.md
  api-reference/beta/resources/user.md
  api-reference/beta/resources/useranalytics.md
  api-reference/beta/toc.yml
  concepts/changelog.md
  concepts/overview-major-services.md
  concepts/permissions-reference.md
  concepts/social-intel-concept-overview.md
Labels: ready to merge

#5352 add accessreview-list.md
  api-reference/beta/api/accessreview-get.md
  api-reference/beta/api/accessreview-list.md
  api-reference/beta/resources/accessreview.md
  api-reference/beta/resources/accessreviews-root.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: area: azure/AAD

#5278 Adding doc page to post chat messages
  api-reference/beta/api/chat-post-messages.md
  api-reference/beta/resources/chatmessage.md
Labels: area: teams, ready to merge

#5490 Sync'd what's new with changelog.
  api-reference/beta/toc.yml
  concepts/changelog.md
  concepts/toc.yml
  concepts/whats-new-overview.md
Labels: do not merge

#5273 private channel support
  api-reference/beta/api/channel-get.md
  api-reference/beta/api/channel-list.md
  api-reference/beta/api/channel-post.md
  api-reference/beta/api/conversationmember-add.md
  api-reference/beta/api/conversationmember-delete.md
  api-reference/beta/api/conversationmember-get.md
  api-reference/beta/api/conversationmember-list.md
  api-reference/beta/api/conversationmember-update.md
  api-reference/beta/resources/aaduserconversationmember.md
  api-reference/beta/resources/channel.md
  api-reference/beta/resources/conversationmember.md
  api-reference/beta/resources/enums.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: area: teams, ready to merge

#5470 add channel-patch to toc
  api-reference/beta/api/channel-patch.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/channel-patch.md
  api-reference/v1.0/toc.yml
Labels: area: teams, ready to merge

#5471 fix example URL in channel-delete
  api-reference/v1.0/api/channel-delete.md
  api-reference/v1.0/api/channel-patch.md
  api-reference/v1.0/toc.yml
Labels: area: teams, ready to merge

#5497 groups table update
  api-reference/v1.0/resources/groups-overview.md
Labels: ready to merge

#5499 fix for git issue 5401
  api-reference/beta/resources/domain.md
  api-reference/v1.0/resources/domain.md
Labels: ready to merge

#5500 fix for git issue 5138
  api-reference/beta/api/privilegedrolesettings-update.md
Labels: ready to merge

#5214 Added Grade property to Education Class
  api-reference/beta/resources/educationclass.md
  concepts/changelog.md
Labels: area: edu, ready to merge

#5560 Org contact permission
  api-reference/beta/api/orgcontact-get.md
  api-reference/beta/api/orgcontact-list.md
  concepts/changelog.md
  concepts/permissions-reference.md
Labels: area: azure/AAD, ready to merge

#5550 Add new priority property to existing Planner task entity
  api-reference/beta/api/plannertask-update.md
  api-reference/beta/resources/plannertask.md
  concepts/changelog.md
Labels: area:planner, ready to merge

#4228 Add documentation for delta sync api
  api-reference/beta/api/chatmessage-delta.md
  api-reference/beta/resources/channel.md
  api-reference/beta/resources/chatmessage.md
  api-reference/beta/toc.yml
  concepts/changelog.md
  concepts/delta-query-overview.md
Labels: area: teams, ready to merge

#5563 fix for git issue 5402
  api-reference/beta/resources/group.md
  api-reference/v1.0/resources/group.md
Labels: ready to merge

#5549 fix for git issue 5305
  api-reference/beta/api/group-list-owners.md
Labels: ready to merge
