Repository microsoftgraph/microsoft-graph-docs, pull requests merged in 2019-03, with the labels that each got.

#4030 Update changelog for planner api
  concepts/changelog.md
Labels: ready to merge

#4056 Edwardkoval rsa 2019 update
  api-reference/beta/api/alert-get.md
  api-reference/beta/api/alert-updatealerts.md
  api-reference/beta/api/securityaction-cancelsecurityaction.md
  api-reference/beta/api/securityaction-get.md
  api-reference/beta/api/securityactions-list.md
  api-reference/beta/api/securityactions-post.md
  api-reference/beta/api/tiindicator-delete.md
  api-reference/beta/api/tiindicator-deletetiindicators.md
  api-reference/beta/api/tiindicator-deletetiindicatorsbyexternalid.md
  api-reference/beta/api/tiindicator-get.md
  api-reference/beta/api/tiindicator-submittiindicators.md
  api-reference/beta/api/tiindicator-update.md
  api-reference/beta/api/tiindicator-updatetiindicators.md
  api-reference/beta/api/tiindicators-list.md
  api-reference/beta/api/tiindicators-post.md
  api-reference/beta/resources/alert.md
  api-reference/beta/resources/alerthistorystate.md
  api-reference/beta/resources/keyvaluepair.md
  api-reference/beta/resources/security-api-overview.md
  api-reference/beta/resources/securityaction.md
  api-reference/beta/resources/securityactionstate.md
  api-reference/beta/resources/securityvendorinformation.md
  api-reference/beta/resources/tiindicator.md
  api-reference/beta/toc.yml
  api-reference/v1.0/resources/security-api-overview.md
  concepts/changelog.md
  concepts/permissions-reference.md
  concepts/security-concept-overview.md
Labels: area: Security, beta, do not merge, needs more info

#4072 Document device compliance and domain password policy
  api-reference/beta/resources/device.md
  api-reference/beta/resources/user.md
  api-reference/v1.0/resources/device.md
  api-reference/v1.0/resources/domain.md
  api-reference/v1.0/resources/user.md
  concepts/changelog.md
Labels: ready to merge

#4091 odata fixes
  api-reference/beta/api/team-post.md
  api-reference/beta/api/teamsappinstallation-add.md
  api-reference/beta/api/teamsappinstallation-delete.md
  api-reference/beta/api/teamsappinstallation-upgrade.md
  api-reference/beta/resources/team.md
  concepts/known-issues.md
Labels: ready to merge

#4054 Removing app crud caveats
  api-reference/beta/api/teamsappinstallation-add.md
  api-reference/beta/api/teamsappinstallation-delete.md
  api-reference/beta/api/teamsappinstallation-upgrade.md
  concepts/known-issues.md
Labels: do not merge

#4095 Edits after RSA
  api-reference/beta/api/securityaction-get.md
  api-reference/beta/api/securityactions-list.md
  api-reference/beta/api/securityactions-post.md
  api-reference/beta/api/tiindicator-update.md
  api-reference/beta/api/tiindicators-post.md
  api-reference/beta/resources/alerthistorystate.md
  api-reference/beta/resources/security-api-overview.md
  api-reference/beta/resources/securityaction.md
  api-reference/beta/resources/tiindicator.md
  concepts/security-authorization.md
Labels: area: Security, ready to merge

#4166 Intune 1903 beta remove enum property for GroupPolicy
  api-reference/beta/api/intune-grouppolicy-grouppolicydefinition-update.md
  api-reference/beta/resources/intune-grouppolicy-grouppolicydefinition.md
  api-reference/beta/resources/intune-grouppolicy-grouppolicydefinitionclasstype.md
Labels: area: intune, ready to merge

#4167 update provider name
  api-reference/beta/resources/security-api-overview.md
  api-reference/v1.0/resources/security-api-overview.md
Labels: area: Security, ready to merge

#4136 CelesteDG landingpage
  concepts/docfx.json
  concepts/images/index/angular.svg
  concepts/images/index/angular_solidBlack.svg
  concepts/images/index/flow.png
  concepts/images/index/flow.svg.png
  concepts/images/index/i_api-reference.svg
  concepts/images/index/i_api.svg
  concepts/images/index/i_backlog.svg
  concepts/images/index/i_blog.svg
  concepts/images/index/i_code-edit.svg
  concepts/images/index/i_get-started.svg
  concepts/images/index/i_investigate.svg
  concepts/images/index/i_library.svg
  concepts/images/index/i_overview.svg
  concepts/images/index/i_queries.svg
  concepts/images/index/i_video.svg
  concepts/images/index/logo_NET.svg
  concepts/images/index/logo_android.svg
  concepts/images/index/logo_ios.svg
  concepts/images/index/logo_java.svg
  concepts/images/index/logo_js.svg
  concepts/images/index/logo_nodejs.svg
  concepts/images/index/logo_php.svg
  concepts/images/index/logo_python.svg
  concepts/images/index/logo_react.svg
  concepts/images/index/logo_ruby.svg
  concepts/images/index/logo_windows.svg
  concepts/images/index/logo_xamarin.svg
  concepts/images/index/whatsnew-video.PNG
  concepts/index.md
  concepts/index.yml
  concepts/toc.experimental.yml
  concepts/toc.yml
Labels: ready to merge

#4124 Add Microsoft Teams Shifts APIs to Beta
  api-reference/beta/api/schedule-get.md
  api-reference/beta/api/schedule-list-schedulinggroups.md
  api-reference/beta/api/schedule-list-shifts.md
  api-reference/beta/api/schedule-list-timeoffreasons.md
  api-reference/beta/api/schedule-list-timesoff.md
  api-reference/beta/api/schedule-post-schedulinggroups.md
  api-reference/beta/api/schedule-post-shifts.md
  api-reference/beta/api/schedule-post-timeoffreasons.md
  api-reference/beta/api/schedule-post-timesoff.md
  api-reference/beta/api/schedule-share.md
  api-reference/beta/api/schedulinggroup-delete.md
  api-reference/beta/api/schedulinggroup-get.md
  api-reference/beta/api/schedulinggroup-put.md
  api-reference/beta/api/shift-delete.md
  api-reference/beta/api/shift-get.md
  api-reference/beta/api/shift-put.md
  api-reference/beta/api/team-put-schedule.md
  api-reference/beta/api/timeoff-delete.md
  api-reference/beta/api/timeoff-get.md
  api-reference/beta/api/timeoff-put.md
  api-reference/beta/api/timeoffreason-delete.md
  api-reference/beta/api/timeoffreason-get.md
  api-reference/beta/api/timeoffreason-put.md
  api-reference/beta/resources/schedule.md
  api-reference/beta/resources/schedulinggroup.md
  api-reference/beta/resources/shift.md
  api-reference/beta/resources/shiftactivity.md
  api-reference/beta/resources/shiftitem.md
  api-reference/beta/resources/timeoff.md
  api-reference/beta/resources/timeoffitem.md
  api-reference/beta/resources/timeoffreason.md
  concepts/changelog.md
Labels: do not merge

#4177 Update logo_ios.svg
  concepts/images/index/logo_ios.svg
Labels: ready to merge

#4023 Changes to invites
  api-reference/beta/api/driveitem-invite.md
  concepts/changelog.md
Labels: ready to merge

#4199 update siem providers
  concepts/security-siemintegration.md
Labels: area: Security, ready to merge

#4208 Update channel-post-messagereply.md
  api-reference/beta/api/channel-post-messagereply.md
Labels: review requested

#4152 Proposal to add new field in schema-config. Treat errors in specified workloads as warnings
  api-reference/beta/config/schema-config.json
Labels: ready to merge

#4158 [Ready to merge] Promote 'socketio' from beta to v1.0
  api-reference/beta/resources/driveitem.md
  api-reference/v1.0/api/driveItem-subscriptions-socketio.md
  api-reference/v1.0/resources/driveitem.md
  concepts/changelog.md
Labels: ready to merge

#4133 Edu Assignments: Categories, form resources, and assigntTo for individual assignments
  api-reference/beta/api/educationassignment-add-categories.md
  api-reference/beta/api/educationassignment-list-categories.md
  api-reference/beta/api/educationassignment-remove-category.md
  api-reference/beta/api/educationcategory-delete.md
  api-reference/beta/api/educationcategory-get.md
  api-reference/beta/api/educationclass-list-categories.md
  api-reference/beta/api/educationclass-post-category.md
  api-reference/beta/resources/educationassignment.md
  api-reference/beta/resources/educationassignmentindividualrecipient.md
  api-reference/beta/resources/educationcategory.md
  api-reference/beta/resources/educationclass.md
  api-reference/beta/resources/educationformresource.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: changes requested, ready to merge

#4053 Remove deleted property from chatMessage
  api-reference/beta/resources/chatmessage.md
  concepts/changelog.md
Labels: ready to merge

#4118 improved the create chat message sample by adding mentions
  api-reference/beta/api/channel-post-chatmessage.md
Labels: ready to merge

#4039 1. unify letter case.
  api-reference/beta/resources/team.md
  api-reference/v1.0/resources/team.md
Labels: ready to merge

#4280 formatting fix
  concepts/security-partner-overview.md
Labels: area: Security, ready to merge

#4285 Updated 1.0 doc with Shifts resources
  api-reference/v1.0/resources/teams-api-overview.md
Labels: ready to merge

#4229 Update teams overview with Shifts resources
  api-reference/beta/resources/teams-api-overview.md
Labels: ready to merge
