Repository microsoftgraph/microsoft-graph-docs, pull requests merged in 2020-11, with the labels that each got.

#10500 Update drive.md
  api-reference/v1.0/resources/drive.md
Labels: external

#10499 Update whats-new-overview.md
  concepts/whats-new-overview.md
Labels: external

#10434 [MVP3]2020-Microsoft-Search-API-Refiner-Update
  api-reference/beta/resources/search-api-overview.md
  concepts/search-concept-custom-types.md
Labels: internal, ready to merge

#10509 Revert "[MVP3]2020-Microsoft-Search-API-Refiner-Update"
  api-reference/beta/resources/search-api-overview.md
  concepts/search-concept-custom-types.md
Labels: internal

#10508 Fix print links in graph documentation - 2
  api-reference/beta/api/print-list-connectors.md
  api-reference/beta/api/printconnector-get.md
  api-reference/beta/api/printer-delete-allowedgroup.md
  api-reference/beta/api/printer-delete-alloweduser.md
  api-reference/beta/api/printer-list-allowedgroups.md
  api-reference/beta/api/printer-list-allowedusers.md
  api-reference/beta/api/printer-post-allowedgroups.md
  api-reference/beta/api/printer-post-allowedusers.md
  api-reference/beta/api/printer-restorefactorydefaults.md
  api-reference/beta/api/printjob-get.md
  api-reference/beta/api/printusagesummarybyprinter-get.md
  api-reference/beta/api/printusagesummarybyuser-get.md
  api-reference/beta/api/reportroot-list-dailyprintusagesummariesbyprinter.md
  api-reference/beta/api/reportroot-list-dailyprintusagesummariesbyuser.md
  api-reference/beta/api/reportroot-list-monthlyprintusagesummariesbyprinter.md
  api-reference/beta/api/reportroot-list-monthlyprintusagesummariesbyuser.md
  api-reference/beta/api/reports-getgrouparchivedprintjobs.md
  api-reference/beta/api/reports-getprinterarchivedprintjobs.md
  api-reference/beta/api/reports-getuserarchivedprintjobs.md
  api-reference/beta/resources/printdocument.md
  api-reference/beta/resources/printer.md
  api-reference/beta/resources/printershare.md
  api-reference/beta/resources/printjobconfiguration.md
  api-reference/beta/toc.yml
  concepts/changelog.md
  concepts/universal-print-concept-overview.md
Labels: area: universal print, internal, ready to merge

#10494 Pimupdate1
  api-reference/beta/resources/privilegedidentitymanagement-directory.md
  api-reference/beta/resources/privilegedidentitymanagement-root.md
Labels: area: azure/AAD, internal, ready to merge

#9715 Fix camel casing in docs for correct code generation in SDK
  api-reference/v1.0/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration.md
  api-reference/v1.0/api/driveitem-unfollow.md
  api-reference/v1.0/api/endpoint-get.md
  api-reference/v1.0/api/eventmessage-post-attachments.md
  api-reference/v1.0/api/group-list-endpoints.md
  api-reference/v1.0/api/place-update.md
  api-reference/v1.0/api/serviceprincipal-addkey.md
  api-reference/v1.0/api/serviceprincipal-delete-owners.md
  api-reference/v1.0/api/serviceprincipal-list.md
  api-reference/v1.0/api/serviceprincipal-post-serviceprincipals.md
  api-reference/v1.0/api/serviceprincipal-removekey.md
  api-reference/v1.0/api/table-headerrowrange.md
  api-reference/v1.0/api/table-totalrowrange.md
  api-reference/v1.0/api/tablecolumn-headerrowrange.md
  api-reference/v1.0/api/tablecolumn-range.md
  api-reference/v1.0/api/tablecolumn-totalrowrange.md
Labels: ready to merge

#10522 Create Microsoft.PrintService.json changelog for October 2020 changes
  changelog/Microsoft.PrintService.json
Labels: area: universal print, internal, ready to merge

#10523 Snippets Update
  api-reference/v1.0/api/table-headerrowrange.md
  api-reference/v1.0/api/table-totalrowrange.md
  api-reference/v1.0/api/tablecolumn-headerrowrange.md
  api-reference/v1.0/api/tablecolumn-range.md
  api-reference/v1.0/api/tablecolumn-totalrowrange.md
  api-reference/v1.0/includes/snippets/csharp/create-certificatebasedauthconfiguration-from-certificatebasedauthconfiguration-csharp-snippets.md
  api-reference/v1.0/includes/snippets/csharp/create-item-attachment-from-eventmessage-csharp-snippets.md
  api-reference/v1.0/includes/snippets/csharp/create-serviceprincipal-from-serviceprincipals-csharp-snippets.md
  api-reference/v1.0/includes/snippets/csharp/list-serviceprincipal-csharp-snippets.md
  api-reference/v1.0/includes/snippets/csharp/serviceprincipal-addkey-csharp-snippets.md
  api-reference/v1.0/includes/snippets/csharp/serviceprincipal-delete-owners-csharp-snippets.md
  api-reference/v1.0/includes/snippets/csharp/serviceprincipal-removekey-csharp-snippets.md
  api-reference/v1.0/includes/snippets/csharp/table-headerrowrange-csharp-snippets.md
  api-reference/v1.0/includes/snippets/csharp/table-totalrowrange-csharp-snippets.md
  api-reference/v1.0/includes/snippets/csharp/tablecolumn-headerrowrange-csharp-snippets.md
  api-reference/v1.0/includes/snippets/csharp/tablecolumn-range-csharp-snippets.md
  api-reference/v1.0/includes/snippets/csharp/tablecolumn-totalrowrange-csharp-snippets.md
  api-reference/v1.0/includes/snippets/csharp/unfollow-item-csharp-snippets.md
  api-reference/v1.0/includes/snippets/csharp/update-roomlist-csharp-snippets.md
  api-reference/v1.0/includes/snippets/java/create-certificatebasedauthconfiguration-from-certificatebasedauthconfiguration-java-snippets.md
  api-reference/v1.0/includes/snippets/java/create-item-attachment-from-eventmessage-java-snippets.md
  api-reference/v1.0/includes/snippets/java/create-serviceprincipal-from-serviceprincipals-java-snippets.md
  api-reference/v1.0/includes/snippets/java/list-serviceprincipal-java-snippets.md
  api-reference/v1.0/includes/snippets/java/serviceprincipal-addkey-java-snippets.md
  api-reference/v1.0/includes/snippets/java/serviceprincipal-delete-owners-java-snippets.md
  api-reference/v1.0/includes/snippets/java/serviceprincipal-removekey-java-snippets.md
  api-reference/v1.0/includes/snippets/java/table-headerrowrange-java-snippets.md
  api-reference/v1.0/includes/snippets/java/table-totalrowrange-java-snippets.md
  api-reference/v1.0/includes/snippets/java/tablecolumn-headerrowrange-java-snippets.md
  api-reference/v1.0/includes/snippets/java/tablecolumn-range-java-snippets.md
  api-reference/v1.0/includes/snippets/java/tablecolumn-totalrowrange-java-snippets.md
  api-reference/v1.0/includes/snippets/java/unfollow-item-java-snippets.md
  api-reference/v1.0/includes/snippets/java/update-roomlist-java-snippets.md
  api-reference/v1.0/includes/snippets/javascript/create-certificatebasedauthconfiguration-from-certificatebasedauthconfiguration-javascript-snippets.md
  api-reference/v1.0/includes/snippets/javascript/create-item-attachment-from-eventmessage-javascript-snippets.md
  api-reference/v1.0/includes/snippets/javascript/create-serviceprincipal-from-serviceprincipals-javascript-snippets.md
  api-reference/v1.0/includes/snippets/javascript/list-serviceprincipal-javascript-snippets.md
  api-reference/v1.0/includes/snippets/javascript/serviceprincipal-addkey-javascript-snippets.md
  api-reference/v1.0/includes/snippets/javascript/serviceprincipal-delete-owners-javascript-snippets.md
  api-reference/v1.0/includes/snippets/javascript/serviceprincipal-removekey-javascript-snippets.md
  api-reference/v1.0/includes/snippets/javascript/table-headerrowrange-javascript-snippets.md
  api-reference/v1.0/includes/snippets/javascript/table-totalrowrange-javascript-snippets.md
  api-reference/v1.0/includes/snippets/javascript/tablecolumn-headerrowrange-javascript-snippets.md
  api-reference/v1.0/includes/snippets/javascript/tablecolumn-range-javascript-snippets.md
  api-reference/v1.0/includes/snippets/javascript/tablecolumn-totalrowrange-javascript-snippets.md
  api-reference/v1.0/includes/snippets/javascript/unfollow-item-javascript-snippets.md
  api-reference/v1.0/includes/snippets/javascript/update-roomlist-javascript-snippets.md
  api-reference/v1.0/includes/snippets/objc/create-certificatebasedauthconfiguration-from-certificatebasedauthconfiguration-objc-snippets.md
  api-reference/v1.0/includes/snippets/objc/create-item-attachment-from-eventmessage-objc-snippets.md
  api-reference/v1.0/includes/snippets/objc/create-serviceprincipal-from-serviceprincipals-objc-snippets.md
  api-reference/v1.0/includes/snippets/objc/list-serviceprincipal-objc-snippets.md
  api-reference/v1.0/includes/snippets/objc/serviceprincipal-addkey-objc-snippets.md
  api-reference/v1.0/includes/snippets/objc/serviceprincipal-delete-owners-objc-snippets.md
  api-reference/v1.0/includes/snippets/objc/serviceprincipal-removekey-objc-snippets.md
  api-reference/v1.0/includes/snippets/objc/table-headerrowrange-objc-snippets.md
  api-reference/v1.0/includes/snippets/objc/table-totalrowrange-objc-snippets.md
  api-reference/v1.0/includes/snippets/objc/tablecolumn-headerrowrange-objc-snippets.md
  api-reference/v1.0/includes/snippets/objc/tablecolumn-range-objc-snippets.md
  api-reference/v1.0/includes/snippets/objc/tablecolumn-totalrowrange-objc-snippets.md
  api-reference/v1.0/includes/snippets/objc/unfollow-item-objc-snippets.md
Labels: ready to merge

#10520 Add note on filtering on the `identities` property in Beta docs from 1.0 docs
  api-reference/beta/resources/objectidentity.md
Labels: external

#10517 Update schedulinggroup-put.md
  api-reference/v1.0/api/schedulinggroup-put.md
Labels: external

#10506 Fix for GitHub Issue #5121
  api-reference/beta/api/conversationthread-list-posts.md
  api-reference/v1.0/api/conversationthread-list-posts.md
Labels: internal

#10513 MVP3-MicrosoftSearch-Update refiner for connector
  api-reference/beta/resources/search-api-overview.md
  concepts/search-concept-custom-types.md
Labels: internal, ready to merge

#10530 Adds the preferred-timezone property to mgt-agenda
  concepts/toolkit/components/agenda.md
Labels: internal

#10532 Update webhooks-lifecycle.md
  concepts/webhooks-lifecycle.md
Labels: external

#10529 Update
  api-reference/v1.0/resources/user.md
Labels: external

#10535 Fixes to the changelog JSON files.
  changelog/Microsoft.DirectoryServices.json
  changelog/Microsoft.FileServices.json
  changelog/Microsoft.Intune.json
  changelog/Microsoft.PrintService.json
  changelog/Microsoft.Skype.Calling.json
  changelog/Microsoft.SubscriptionServices.json
  changelog/Microsoft.Teams.Core.json
Labels: internal

#10537 Update webhooks.md
  concepts/webhooks.md
Labels: external

#10538 Merge to publish.
  api-reference/beta/api/application-update.md
  api-reference/beta/api/emailauthenticationmethod-delete.md
  api-reference/beta/api/group-post-groups.md
  api-reference/beta/api/serviceprincipal-update.md
  api-reference/beta/resources/authenticationmethods-overview.md
  api-reference/beta/resources/authenticationmethodspolicies-overview.md
  api-reference/beta/resources/authorizationpolicy.md
  api-reference/beta/resources/b2cidentityuserflow.md
  api-reference/beta/resources/delegatedpermissionclassification.md
  api-reference/beta/resources/group.md
  api-reference/beta/resources/homerealmdiscoverypolicy.md
  api-reference/beta/resources/onpremisespublishing.md
  api-reference/beta/resources/onpremisespublishingprofile-root.md
  api-reference/beta/resources/onpremisespublishingprofile.md
  api-reference/beta/resources/search-api-overview.md
  api-reference/beta/resources/security-api-overview.md
  api-reference/beta/resources/serviceprincipal.md
  api-reference/v1.0/api/group-assignlicense.md
  api-reference/v1.0/api/serviceprincipal-update.md
  api-reference/v1.0/resources/homerealmdiscoverypolicy.md
  api-reference/v1.0/resources/security-api-overview.md
  api-reference/v1.0/resources/serviceprincipal.md
  api-reference/v1.0/resources/user.md
  api-reference/v1.0/resources/verifiedpublisher.md
  changelog/Microsoft.DirectoryServices.json
  changelog/Microsoft.FileServices.json
  changelog/Microsoft.Intune.json
  changelog/Microsoft.PrintService.json
  changelog/Microsoft.Skype.Calling.json
  changelog/Microsoft.SubscriptionServices.json
  changelog/Microsoft.Teams.Core.json
  concepts/application-proxy-configure-api.md
  concepts/changelog-archive.md
  concepts/permissions-reference.md
  concepts/search-concept-custom-types.md
  concepts/security-concept-overview.md
  concepts/security-integration.md
  concepts/security-partner-overview.md
  concepts/sharepoint-concept-overview.md
  concepts/webhooks-lifecycle.md
  concepts/webhooks.md
Labels: internal

#10477 Add print task definition resource to graph webhook docs
  api-reference/beta/api/subscription-delete.md
  api-reference/beta/api/subscription-get.md
  api-reference/beta/api/subscription-post-subscriptions.md
  api-reference/beta/api/subscription-update.md
  api-reference/beta/resources/subscription.md
  api-reference/beta/resources/webhooks.md
  changelog/Microsoft.SubscriptionServices.json
  concepts/changelog.md
  concepts/webhooks.md
Labels: area: universal print, area: webhooks, content review, internal, ready to merge

#10555 Correction: channel-post-messages.md to channel-post-message.md
  api-reference/v1.0/api/channel-post-message.md
  api-reference/v1.0/resources/channel.md
  api-reference/v1.0/resources/chatmessage.md
  api-reference/v1.0/resources/teams-api-overview.md
Labels: internal, ready to merge

#10554 Update throttling.md
  concepts/throttling.md
Labels: external

#10550 Update team.md
  api-reference/beta/resources/team.md
Labels: external

#10549 Update chatmessage.md
  api-reference/v1.0/resources/chatmessage.md
Labels: external

#10541 - updates java batch to use latest methods
  concepts/sdks/batch-requests.md
Labels: area: batch requests, area: sample code, internal, ready to merge

#10557 Updated the date for the Nov entry.
  changelog/Microsoft.Teams.Core.json
Labels: internal

#10559 Make "See also" display on right side TOC.
  api-reference/beta/api/event-delta.md
  api-reference/v1.0/api/event-delta.md
Labels: internal

#10558 Camel case fixes for compilable snippets
  api-reference/beta/api/administrativeunit-delta.md
  api-reference/beta/api/directoryrole-delete-member.md
  api-reference/beta/api/informationprotectionlabel-evaluateapplication.md
  api-reference/beta/api/informationprotectionlabel-evaluateclassificationresults.md
  api-reference/beta/api/informationprotectionlabel-evaluateremoval.md
  api-reference/beta/api/informationprotectionlabel-extractlabel.md
  api-reference/beta/api/oauth2permissiongrant-delta.md
  api-reference/beta/api/place-update.md
  api-reference/v1.0/api/oauth2permissiongrant-delta.md
Labels: internal

#10560 Merge to publish.
  api-reference/beta/api/administrativeunit-delta.md
  api-reference/beta/api/directoryrole-delete-member.md
  api-reference/beta/api/event-delta.md
  api-reference/beta/api/informationprotectionlabel-evaluateapplication.md
  api-reference/beta/api/informationprotectionlabel-evaluateclassificationresults.md
  api-reference/beta/api/informationprotectionlabel-evaluateremoval.md
  api-reference/beta/api/informationprotectionlabel-extractlabel.md
  api-reference/beta/api/oauth2permissiongrant-delta.md
  api-reference/beta/api/place-update.md
  api-reference/beta/api/subscription-delete.md
  api-reference/beta/api/subscription-get.md
  api-reference/beta/api/subscription-post-subscriptions.md
  api-reference/beta/api/subscription-update.md
  api-reference/beta/resources/subscription.md
  api-reference/beta/resources/team.md
  api-reference/beta/resources/webhooks.md
  api-reference/v1.0/api/channel-post-message.md
  api-reference/v1.0/api/event-delta.md
  api-reference/v1.0/api/oauth2permissiongrant-delta.md
  api-reference/v1.0/resources/channel.md
  api-reference/v1.0/resources/chatmessage.md
  api-reference/v1.0/resources/teams-api-overview.md
  changelog/Microsoft.SubscriptionServices.json
  changelog/Microsoft.Teams.Core.json
  concepts/changelog.md
  concepts/sdks/batch-requests.md
  concepts/throttling.md
  concepts/webhooks.md
Labels: internal

#10392 [MGT][Person] Added docs for line3-property
  concepts/toolkit/components/person.md
Labels: do not merge, internal

#10562 Updates for byte order mark.
  concepts/application-saml-sso-configure-api.md
Labels: internal, ready to merge

#10567 Update teams-configuring-builtin-tabs.md
  concepts/teams-configuring-builtin-tabs.md
Labels: external

#10573 Merge to publish.
  concepts/application-saml-sso-configure-api.md
  concepts/teams-configuring-builtin-tabs.md
Labels: do not merge, internal

#10576 Unify perspective, apply Microsoft voice.
  concepts/search-concept-overview.md
Labels: internal

#10577 Adding details on some missing properties
  concepts/toolkit/components/people-picker.md
Labels: external, ready to merge

#10424 Updates MGT React getting started
  concepts/toc.yml
  concepts/toolkit/get-started/add-aad-app-registration.md
  concepts/toolkit/get-started/build-a-microsoft-teams-tab.md
  concepts/toolkit/get-started/overview.md
  concepts/toolkit/get-started/use-toolkit-with-react.md
  concepts/toolkit/images/mgt-finished-app.png
  concepts/toolkit/images/mgt-react-userinfo.png
  concepts/toolkit/includes/aad-app-registration-spa.md
Labels: ready to merge

#10606 Added what's new from the last week.
  concepts/changelog.md
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: internal

#10607 Publish what's new gathered from the last week.
  concepts/changelog.md
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: internal

#10598 [MGT] Added docs for useContactApis
  concepts/toolkit/components/person-card.md
  concepts/toolkit/components/person.md
Labels: do not merge, internal

#10625 Update chat-post-message.md
  api-reference/beta/api/chat-post-message.md
Labels: external

#10609 Updating printer with application permissions and json payload
  api-reference/beta/api/printer-post-tasktriggers.md
  api-reference/beta/api/printer-update.md
  api-reference/beta/resources/printer.md
  concepts/universal-print-concept-overview.md
Labels: area: universal print, internal, ready to merge

#10619 Global admin callers are no longer needed, that line is outdated
  api-reference/beta/api/teamsapp-publish.md
Labels: external

#10628 Removed file and added redirect.
  .openpublishing.redirection.json
  api-reference/beta/api/user-list-workingwith.md
Labels: internal

#10605 Update homerealmdiscoverypolicy.md
  api-reference/beta/resources/homerealmdiscoverypolicy.md
Labels: external

#10604 Update homerealmdiscoverypolicy.md
  api-reference/v1.0/resources/homerealmdiscoverypolicy.md
Labels: external

#10596 Updated permissions-reference for ToU
  concepts/permissions-reference.md
Labels: external

#10630 Revert "Updated permissions-reference for ToU"
  concepts/permissions-reference.md
Labels: internal

#10374 Jingha add cloud pc permissions
  concepts/permissions-reference.md
Labels: internal, ready to merge

#10631 Merge to publish.
  .openpublishing.redirection.json
  api-reference/beta/api/chat-post-message.md
  api-reference/beta/api/printer-post-tasktriggers.md
  api-reference/beta/api/printer-update.md
  api-reference/beta/api/teamsapp-publish.md
  api-reference/beta/api/user-list-workingwith.md
  api-reference/beta/includes/snippets/csharp/create-printer-csharp-snippets.md
  api-reference/beta/includes/snippets/csharp/synchronizationschema-parseexpression-csharp-snippets.md
  api-reference/beta/includes/snippets/csharp/tablerowcollection-add-csharp-snippets.md
  api-reference/beta/resources/homerealmdiscoverypolicy.md
  api-reference/beta/resources/printer.md
  api-reference/v1.0/resources/homerealmdiscoverypolicy.md
  concepts/permissions-reference.md
  concepts/universal-print-concept-overview.md
Labels: internal

#10643 Fix example body for synchronizationJob: provisionOnDemand
  api-reference/beta/api/synchronization-synchronizationjob-provision-on-demand.md
Labels: external

#10639 Update chatmessage-delta.md
  api-reference/v1.0/api/chatmessage-delta.md
Labels: external

#10620 add delivering as an assignmentState in accesspackageassignment
  api-reference/beta/resources/accesspackageassignment.md
Labels: area: azure/AAD, internal, ready to merge

#10627 Include "preserve-view" parameter in links.
  concepts/changelog.md
Labels: do not merge, internal

#10646 Fix changelog - deleted 2 rows, updated 1 row.
  concepts/changelog.md
Labels: internal

#10344 Mentioning change notification in messaging docs
  api-reference/beta/api/channel-list-messagereplies.md
  api-reference/beta/api/channel-list-messages.md
  api-reference/beta/api/chat-list-message.md
  api-reference/beta/api/subscription-post-subscriptions.md
  api-reference/beta/resources/chatmessage.md
  concepts/teams-changenotifications-chatmessage.md
  concepts/teams-concept-overview.md
  concepts/toc.yml
  concepts/webhooks-with-resource-data.md
Labels: area: teams, area: webhooks, do not merge, internal

#9935 Access review v2 api
  api-reference/beta/api/accessreviewinstance-acceptrecommendations.md
  api-reference/beta/api/accessreviewinstance-applydecisions.md
  api-reference/beta/api/accessreviewinstance-get.md
  api-reference/beta/api/accessreviewinstance-list.md
  api-reference/beta/api/accessreviewinstance-pendingaccessreviewinstances.md
  api-reference/beta/api/accessreviewinstance-sendreminder.md
  api-reference/beta/api/accessreviewinstance-stop.md
  api-reference/beta/api/accessreviewinstancedecisionitem-list.md
  api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md
  api-reference/beta/api/accessreviewinstancedecisionitem-update.md
  api-reference/beta/api/accessreviewscheduledefinition-create.md
  api-reference/beta/api/accessreviewscheduledefinition-delete.md
  api-reference/beta/api/accessreviewscheduledefinition-get.md
  api-reference/beta/api/accessreviewscheduledefinition-list.md
  api-reference/beta/api/accessreviewscheduledefinition-update.md
  api-reference/beta/resources/accessreviewapplyaction.md
  api-reference/beta/resources/accessreviewinstance.md
  api-reference/beta/resources/accessreviewinstancedecisionitem.md
  api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md
  api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md
  api-reference/beta/resources/accessreviewinstancedecisionitemusertarget.md
  api-reference/beta/resources/accessreviewreviewerscope.md
  api-reference/beta/resources/accessreviews-root.md
  api-reference/beta/resources/accessreviewscheduledefinition.md
  api-reference/beta/resources/accessreviewschedulesettings.md
  api-reference/beta/resources/accessreviewscope.md
  api-reference/beta/resources/accessreviewsv2-root.md
  api-reference/beta/resources/user.md
  api-reference/beta/toc.yml
  changelog/Microsoft.DirectoryServices.json
  concepts/changelog.md
Labels: area: azure/AAD, changes requested, ready to merge

#10647 Fix formatting.
  concepts/changelog.md
Labels: do not merge, internal

#10648 Merge to publish.
  api-reference/beta/api/accessreviewinstance-acceptrecommendations.md
  api-reference/beta/api/accessreviewinstance-applydecisions.md
  api-reference/beta/api/accessreviewinstance-get.md
  api-reference/beta/api/accessreviewinstance-list.md
  api-reference/beta/api/accessreviewinstance-pendingaccessreviewinstances.md
  api-reference/beta/api/accessreviewinstance-sendreminder.md
  api-reference/beta/api/accessreviewinstance-stop.md
  api-reference/beta/api/accessreviewinstancedecisionitem-list.md
  api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md
  api-reference/beta/api/accessreviewinstancedecisionitem-update.md
  api-reference/beta/api/accessreviewscheduledefinition-create.md
  api-reference/beta/api/accessreviewscheduledefinition-delete.md
  api-reference/beta/api/accessreviewscheduledefinition-get.md
  api-reference/beta/api/accessreviewscheduledefinition-list.md
  api-reference/beta/api/accessreviewscheduledefinition-update.md
  api-reference/beta/api/channel-list-messagereplies.md
  api-reference/beta/api/channel-list-messages.md
  api-reference/beta/api/chat-list-message.md
  api-reference/beta/api/subscription-post-subscriptions.md
  api-reference/beta/api/synchronization-synchronizationjob-provision-on-demand.md
  api-reference/beta/resources/accesspackageassignment.md
  api-reference/beta/resources/accessreviewapplyaction.md
  api-reference/beta/resources/accessreviewinstance.md
  api-reference/beta/resources/accessreviewinstancedecisionitem.md
  api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md
  api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md
  api-reference/beta/resources/accessreviewinstancedecisionitemusertarget.md
  api-reference/beta/resources/accessreviewreviewerscope.md
  api-reference/beta/resources/accessreviews-root.md
  api-reference/beta/resources/accessreviewscheduledefinition.md
  api-reference/beta/resources/accessreviewschedulesettings.md
  api-reference/beta/resources/accessreviewscope.md
  api-reference/beta/resources/accessreviewsv2-root.md
  api-reference/beta/resources/chatmessage.md
  api-reference/beta/resources/user.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/chatmessage-delta.md
  changelog/Microsoft.DirectoryServices.json
  concepts/changelog.md
  concepts/teams-changenotifications-chatmessage.md
  concepts/teams-concept-overview.md
  concepts/toc.yml
  concepts/webhooks-with-resource-data.md
Labels: internal

#10658 Update date attribute.
  changelog/Microsoft.DirectoryServices.json
Labels: internal

#8012 Organizational Branding API docs
  api-reference/beta/api/organizationalbrandingproperties-create.md
  api-reference/beta/api/organizationalbrandingproperties-delete.md
  api-reference/beta/api/organizationalbrandingproperties-get.md
  api-reference/beta/api/organizationalbrandingproperties-update.md
  api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md
  api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md
  api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md
  api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md
  api-reference/beta/resources/azure-ad-overview.md
  api-reference/beta/resources/organization.md
  api-reference/beta/resources/organizationalbrandingproperties.md
  api-reference/beta/toc.yml
  changelog/Microsoft.DirectoryServices.json
  concepts/changelog.md
Labels: area: azure/AAD, changelog, changes requested, ready to merge

#10663 fix for git issue 8581
  api-reference/v1.0/resources/user.md
Labels: area: azure/AAD, internal, ready to merge

#10649 Update chatmessage-delta.md
  api-reference/beta/api/chatmessage-delta.md
Labels: external

#10666 Updating per-tenant throttling in Azure AD
  concepts/throttling.md
Labels: external

#10661 fix for git issue 10493
  api-reference/beta/api/user-list.md
  api-reference/v1.0/api/user-list.md
Labels: area: azure/AAD, internal, ready to merge

#10664 Adding new topic to TOC
  api-reference/beta/toc.yml
Labels: content review, internal

#10662 Update toc.yml
  api-reference/v1.0/toc.yml
Labels: external

#10595 Create spaapplication.md
  api-reference/beta/api/application-update.md
  api-reference/beta/resources/application.md
  api-reference/beta/resources/spaapplication.md
  changelog/Microsoft.DirectoryServices.json
  concepts/changelog.md
Labels: internal, ready to merge

#10668 Fixed order of H3s.
  concepts/changelog.md
Labels: internal

#10669 Merge to publish.
  api-reference/beta/api/application-update.md
  api-reference/beta/api/chatmessage-delta.md
  api-reference/beta/api/organizationalbrandingproperties-create.md
  api-reference/beta/api/organizationalbrandingproperties-delete.md
  api-reference/beta/api/organizationalbrandingproperties-get.md
  api-reference/beta/api/organizationalbrandingproperties-update.md
  api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md
  api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md
  api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md
  api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md
  api-reference/beta/api/user-list.md
  api-reference/beta/resources/application.md
  api-reference/beta/resources/azure-ad-overview.md
  api-reference/beta/resources/organization.md
  api-reference/beta/resources/organizationalbrandingproperties.md
  api-reference/beta/resources/spaapplication.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/user-list.md
  api-reference/v1.0/resources/user.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.DirectoryServices.json
  concepts/changelog.md
  concepts/throttling.md
Labels: internal

#10677 Mezzo not supported in SDK. Removed examples.
  api-reference/beta/api/application-list.md
  api-reference/beta/api/device-list-memberof.md
  api-reference/beta/api/device-list-transitivememberof.md
  api-reference/beta/api/device-list.md
  api-reference/beta/api/group-list-memberof.md
  api-reference/beta/api/group-list-members.md
  api-reference/beta/api/group-list-transitivememberof.md
  api-reference/beta/api/group-list-transitivemembers.md
  api-reference/beta/api/group-list.md
  api-reference/beta/api/orgcontact-list.md
  api-reference/beta/api/serviceprincipal-list-memberof.md
  api-reference/beta/api/serviceprincipal-list-transitivememberof.md
  api-reference/beta/api/serviceprincipal-list.md
  api-reference/beta/api/user-list-memberof.md
  api-reference/beta/api/user-list-transitivememberof.md
  api-reference/beta/api/user-list.md
  api-reference/v1.0/api/application-list.md
  api-reference/v1.0/api/device-list-memberof.md
  api-reference/v1.0/api/device-list-transitivememberof.md
  api-reference/v1.0/api/device-list.md
  api-reference/v1.0/api/group-list-memberof.md
  api-reference/v1.0/api/group-list-members.md
  api-reference/v1.0/api/group-list-transitivememberof.md
  api-reference/v1.0/api/group-list-transitivemembers.md
  api-reference/v1.0/api/group-list.md
  api-reference/v1.0/api/orgcontact-list.md
  api-reference/v1.0/api/serviceprincipal-list-memberof.md
  api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md
  api-reference/v1.0/api/serviceprincipal-list.md
  api-reference/v1.0/api/user-list-memberof.md
  api-reference/v1.0/api/user-list-transitivememberof.md
  api-reference/v1.0/api/user-list.md
Labels: area: azure/AAD, internal, ready to merge

#10675 Update drive.md
  api-reference/v1.0/resources/drive.md
Labels: external

#10674 Update drive.md
  api-reference/beta/resources/drive.md
Labels: external

#10659 Labeling new access review api documentation as Preview
  api-reference/beta/resources/accessreviews-root.md
  api-reference/beta/resources/accessreviewsv2-root.md
  api-reference/beta/toc.yml
Labels: area: azure/AAD, ready to merge

#10683 Fix camel casing in beta APIs
  api-reference/beta/api/serviceprincipal-addkey.md
  api-reference/beta/api/serviceprincipal-delete-owners.md
  api-reference/beta/api/serviceprincipal-list.md
  api-reference/beta/api/serviceprincipal-post-serviceprincipals.md
Labels: internal, ready to merge

#10682 Merge to publish.
  api-reference/beta/api/application-list.md
  api-reference/beta/api/device-list-memberof.md
  api-reference/beta/api/device-list-transitivememberof.md
  api-reference/beta/api/device-list.md
  api-reference/beta/api/group-list-memberof.md
  api-reference/beta/api/group-list-members.md
  api-reference/beta/api/group-list-transitivememberof.md
  api-reference/beta/api/group-list-transitivemembers.md
  api-reference/beta/api/group-list.md
  api-reference/beta/api/orgcontact-list.md
  api-reference/beta/api/serviceprincipal-addkey.md
  api-reference/beta/api/serviceprincipal-delete-owners.md
  api-reference/beta/api/serviceprincipal-list-memberof.md
  api-reference/beta/api/serviceprincipal-list-transitivememberof.md
  api-reference/beta/api/serviceprincipal-list.md
  api-reference/beta/api/serviceprincipal-post-serviceprincipals.md
  api-reference/beta/api/user-list-memberof.md
  api-reference/beta/api/user-list-transitivememberof.md
  api-reference/beta/api/user-list.md
  api-reference/beta/resources/accessreviews-root.md
  api-reference/beta/resources/accessreviewsv2-root.md
  api-reference/beta/resources/drive.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/application-list.md
  api-reference/v1.0/api/device-list-memberof.md
  api-reference/v1.0/api/device-list-transitivememberof.md
  api-reference/v1.0/api/device-list.md
  api-reference/v1.0/api/group-list-memberof.md
  api-reference/v1.0/api/group-list-members.md
  api-reference/v1.0/api/group-list-transitivememberof.md
  api-reference/v1.0/api/group-list-transitivemembers.md
  api-reference/v1.0/api/group-list.md
  api-reference/v1.0/api/orgcontact-list.md
  api-reference/v1.0/api/serviceprincipal-list-memberof.md
  api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md
  api-reference/v1.0/api/serviceprincipal-list.md
  api-reference/v1.0/api/user-list-memberof.md
  api-reference/v1.0/api/user-list-transitivememberof.md
  api-reference/v1.0/api/user-list.md
  api-reference/v1.0/resources/drive.md
Labels: do not merge, internal

#10572 Adding the transitive-search documentation
  concepts/toolkit/components/people-picker.md
Labels: do not merge, internal

#10528 added transitive managers operation
  api-reference/beta/api/user-list-manager.md
  api-reference/v1.0/api/user-list-manager.md
Labels: internal, ready to merge

#10699 corrected beta toc
  api-reference/beta/toc.yml
Labels: area: azure/AAD, internal, ready to merge

#10697 Fix typo in note at top of page
  api-reference/beta/resources/accessreviews-root.md
Labels: external

#10691 Update user-list-memberof.md
  api-reference/v1.0/api/user-list-memberof.md
Labels: external

#10690 Update user-list-memberof.md
  api-reference/beta/api/user-list-memberof.md
Labels: external

#10689 Clarifying what exactly 'key' needs
  api-reference/v1.0/resources/keycredential.md
Labels: external

#10688 Clarifying 'iss' claim is the AAD ObjectId
  concepts/application-rollkey-prooftoken.md
Labels: external

#10645 update mgt provider docs
  concepts/toolkit/providers.md
  concepts/toolkit/providers/custom.md
  concepts/toolkit/providers/msal.md
  concepts/toolkit/providers/sharepoint.md
  concepts/toolkit/providers/teams.md
Labels: ready to merge

#10579 AndresC---Auth-MEthods-Policies-permissions-update
  api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md
  api-reference/beta/api/fido2authenticationmethodconfiguration-get.md
  api-reference/beta/api/fido2authenticationmethodconfiguration-update.md
  api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md
  api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md
  api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md
Labels: internal, ready to merge

#10704 Merge to publish.
  api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md
  api-reference/beta/api/fido2authenticationmethodconfiguration-get.md
  api-reference/beta/api/fido2authenticationmethodconfiguration-update.md
  api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md
  api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md
  api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md
  api-reference/beta/api/user-list-manager.md
  api-reference/beta/api/user-list-memberof.md
  api-reference/beta/resources/accessreviews-root.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/user-list-manager.md
  api-reference/v1.0/api/user-list-memberof.md
  api-reference/v1.0/resources/keycredential.md
  concepts/application-rollkey-prooftoken.md
  concepts/teams-configuring-builtin-tabs.md
  concepts/toolkit/providers.md
  concepts/toolkit/providers/custom.md
  concepts/toolkit/providers/msal.md
  concepts/toolkit/providers/sharepoint.md
  concepts/toolkit/providers/teams.md
Labels: internal

#10711 Adding documentation for the new caching capability of mgt-get
  concepts/toolkit/components/get.md
Labels: external

#10717 added missing ms.custom tag for the Azure CLI
  concepts/change-notifications-delivery.md
Labels: external

#10709 Updated StackOverflow link
  api-reference/beta/overview.md
Labels: external

#10708 Update directoryaudit.md
  api-reference/v1.0/resources/directoryaudit.md
Labels: external

#10707 Update directoryaudit.md
  api-reference/beta/resources/directoryaudit.md
Labels: external

#10703 adding correct level specifications
  api-reference/beta/api/user-list-manager.md
  api-reference/v1.0/api/user-list-manager.md
Labels: internal, ready to merge

#10680 Push meeting options to v1
  api-reference/v1.0/api/onlinemeeting-get.md
  api-reference/v1.0/resources/lobbyBypassSettings.md
  api-reference/v1.0/resources/meetingparticipantinfo.md
  api-reference/v1.0/resources/onlinemeeting.md
  changelog/Microsoft.Skype.Calling.json
  concepts/changelog.md
Labels: internal, ready to merge

#10719 Add registerdevice user action
  api-reference/beta/resources/conditionalaccessapplications.md
Labels: content review, internal

#10732 added preserve-view=true
  concepts/changelog.md
Labels: area: azure/AAD, internal, ready to merge

#10731 fix for git issue 9649
  api-reference/beta/api/user-list.md
  api-reference/v1.0/api/user-list.md
Labels: area: azure/AAD, internal, ready to merge

#10724 Removed Global Reader
  api-reference/beta/api/emailauthenticationmethod-delete.md
  api-reference/beta/api/emailauthenticationmethod-post.md
  api-reference/beta/api/emailauthenticationmethod-update.md
  api-reference/beta/api/fido2authenticationmethod-delete.md
  api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-delete.md
Labels: internal, ready to merge

#10725 Update assignedlabel.md
  api-reference/beta/resources/assignedlabel.md
Labels: external

#10692 Update profile-get.md
  api-reference/beta/api/profile-get.md
Labels: internal, ready to merge

#10653 Various fixes (deployments, orgcontacts...)
  .gitignore
  api-reference/beta/api/orgcontact-delta.md
  api-reference/beta/api/orgcontact-get.md
  api-reference/beta/api/orgcontact-list.md
  api-reference/beta/api/orgcontact-update.md
  api-reference/beta/api/schemaextension-update.md
  api-reference/beta/api/user-revokesigninsessions.md
  api-reference/beta/resources/orgcontact.md
  api-reference/beta/resources/schemaextension.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/schemaextension-update.md
  api-reference/v1.0/api/user-revokesigninsessions.md
  api-reference/v1.0/resources/schemaextension.md
  concepts/add-properties-profilecard.md
  concepts/deployments.md
  concepts/known-issues.md
  concepts/migrate-azure-ad-graph-planning-checklist.md
Labels: area: azure/AAD, internal, ready to merge, resolved: awaiting validation

#10738 Merge to publish.
  .gitignore
  api-reference/beta/api/emailauthenticationmethod-delete.md
  api-reference/beta/api/emailauthenticationmethod-post.md
  api-reference/beta/api/emailauthenticationmethod-update.md
  api-reference/beta/api/fido2authenticationmethod-delete.md
  api-reference/beta/api/orgcontact-delta.md
  api-reference/beta/api/orgcontact-get.md
  api-reference/beta/api/orgcontact-list.md
  api-reference/beta/api/orgcontact-update.md
  api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-delete.md
  api-reference/beta/api/profile-get.md
  api-reference/beta/api/schemaextension-update.md
  api-reference/beta/api/user-list.md
  api-reference/beta/api/user-revokesigninsessions.md
  api-reference/beta/resources/assignedlabel.md
  api-reference/beta/resources/orgcontact.md
  api-reference/beta/resources/schemaextension.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/schemaextension-update.md
  api-reference/v1.0/api/user-list.md
  api-reference/v1.0/api/user-revokesigninsessions.md
  api-reference/v1.0/resources/schemaextension.md
  concepts/add-properties-profilecard.md
  concepts/changelog.md
  concepts/deployments.md
  concepts/known-issues.md
  concepts/migrate-azure-ad-graph-planning-checklist.md
Labels: internal

#10750 fix for git issue 9457
  api-reference/beta/api/user-list.md
  api-reference/v1.0/api/user-list.md
Labels: area: azure/AAD, internal, ready to merge

#10746 Update educationschool.md
  api-reference/v1.0/resources/educationschool.md
Labels: external

#10736 Change example 2 to show creation of security group (instead of M365 group)
  api-reference/beta/api/group-delta.md
  api-reference/beta/api/group-get.md
  api-reference/beta/api/group-list.md
  api-reference/beta/api/group-post-groups.md
  api-reference/v1.0/api/group-delta.md
  api-reference/v1.0/api/group-get.md
  api-reference/v1.0/api/group-list.md
  api-reference/v1.0/api/group-post-groups.md
Labels: internal, ready to merge

#10753 Merge to publish.
  api-reference/beta/api/group-delta.md
  api-reference/beta/api/group-get.md
  api-reference/beta/api/group-list.md
  api-reference/beta/api/group-post-groups.md
  api-reference/beta/api/user-list.md
  api-reference/v1.0/api/group-delta.md
  api-reference/v1.0/api/group-get.md
  api-reference/v1.0/api/group-list.md
  api-reference/v1.0/api/group-post-groups.md
  api-reference/v1.0/api/user-list.md
  api-reference/v1.0/resources/educationschool.md
Labels: do not merge, internal

#10758 Added v1.0 docs for permissionGrantPolicy and delegatedPermissionClassification
  api-reference/v1.0/api/permissiongrantpolicy-delete-excludes.md
  api-reference/v1.0/api/permissiongrantpolicy-delete-includes.md
  api-reference/v1.0/api/permissiongrantpolicy-delete.md
  api-reference/v1.0/api/permissiongrantpolicy-get.md
  api-reference/v1.0/api/permissiongrantpolicy-list-excludes.md
  api-reference/v1.0/api/permissiongrantpolicy-list-includes.md
  api-reference/v1.0/api/permissiongrantpolicy-list.md
  api-reference/v1.0/api/permissiongrantpolicy-post-excludes.md
  api-reference/v1.0/api/permissiongrantpolicy-post-includes.md
  api-reference/v1.0/api/permissiongrantpolicy-post-permissiongrantpolicies.md
  api-reference/v1.0/api/permissiongrantpolicy-update.md
  api-reference/v1.0/api/serviceprincipal-delete-delegatedpermissionclassifications.md
  api-reference/v1.0/api/serviceprincipal-list-delegatedpermissionclassifications.md
  api-reference/v1.0/api/serviceprincipal-post-delegatedpermissionclassifications.md
  api-reference/v1.0/resources/delegatedpermissionclassification.md
  api-reference/v1.0/resources/enums.md
  api-reference/v1.0/resources/permissiongrantconditionset.md
  api-reference/v1.0/resources/permissiongrantpolicy.md
  api-reference/v1.0/resources/serviceprincipal.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.DirectoryServices.json
  concepts/changelog.md
Labels: internal, ready to merge

#10737 Update schedulinggroup-put.md
  api-reference/v1.0/api/schedulinggroup-put.md
Labels: internal, ready to merge

#10734 Adding description for signInAudience for B2C.
  api-reference/v1.0/resources/application.md
Labels: area: azure/AAD, internal, ready to merge

#9661 directoryRoles work with role templateId
  api-reference/v1.0/api/directoryrole-delete-member.md
  api-reference/v1.0/api/directoryrole-get.md
  api-reference/v1.0/api/directoryrole-list-members.md
  api-reference/v1.0/api/directoryrole-post-members.md
Labels: ready to merge

#10721 Documentation of Activity Feed Notification APIs
  api-reference/beta/api/chat-sendactivitynotification.md
  api-reference/beta/api/team-sendactivitynotification.md
  api-reference/beta/api/userteamwork-sendactivitynotification.md
  api-reference/beta/resources/aadusernotificationrecipient.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/teams-api-overview.md
  api-reference/beta/resources/teamworkactivitytopic.md
  api-reference/beta/resources/teamworknotificationrecipient.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Teams.Core.json
  concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png
  concepts/images/teams-activityfeednotifications/examplefeednotification.png
  concepts/images/teams-activityfeednotifications/notificationsettings.png
  concepts/images/teams-activityfeednotifications/notificationtemplate.png
  concepts/teams-send-activityfeednotifications.md
  concepts/toc.yml
Labels: internal, ready to merge

#10412 Add CloudPC documentation-jiajyang
  api-reference/beta/api/cloudpc-get.md
  api-reference/beta/api/cloudpc-reprovision.md
  api-reference/beta/api/cloudpcdeviceimage-delete.md
  api-reference/beta/api/cloudpcdeviceimage-get.md
  api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md
  api-reference/beta/api/cloudpconpremisesconnection-delete.md
  api-reference/beta/api/cloudpconpremisesconnection-get.md
  api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md
  api-reference/beta/api/cloudpconpremisesconnection-update.md
  api-reference/beta/api/cloudpcprovisioningpolicy-assign.md
  api-reference/beta/api/cloudpcprovisioningpolicy-delete.md
  api-reference/beta/api/cloudpcprovisioningpolicy-get.md
  api-reference/beta/api/cloudpcprovisioningpolicy-update.md
  api-reference/beta/api/virtualendpoint-geteffectivepermissions.md
  api-reference/beta/api/virtualendpoint-list-cloudpcs.md
  api-reference/beta/api/virtualendpoint-list-deviceimages.md
  api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md
  api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md
  api-reference/beta/api/virtualendpoint-post-deviceimages.md
  api-reference/beta/api/virtualendpoint-post-onpremisesconnections.md
  api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md
  api-reference/beta/resources/cloudpc.md
  api-reference/beta/resources/cloudpcStatusDetails.md
  api-reference/beta/resources/cloudpcdeviceimage.md
  api-reference/beta/resources/cloudpcmanagementassignmenttarget.md
  api-reference/beta/resources/cloudpcmanagementgroupassignmenttarget.md
  api-reference/beta/resources/cloudpconpremisesconnection.md
  api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
  api-reference/beta/resources/cloudpconpremisesconnectionstatusdetails.md
  api-reference/beta/resources/cloudpcprovisioningpolicy.md
  api-reference/beta/resources/cloudpcprovisioningpolicyassignment.md
  api-reference/beta/resources/cloudpcsourcedeviceimage.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/virtualendpoint.md
  api-reference/beta/toc.yml
  changelog/Microsoft.CloudManagedDesktop.json
  concepts/changelog.md
Labels: content review, internal

#10769 Publish debut PR for cloud PC API.
  api-reference/beta/api/cloudpc-get.md
  api-reference/beta/api/cloudpc-reprovision.md
  api-reference/beta/api/cloudpcdeviceimage-delete.md
  api-reference/beta/api/cloudpcdeviceimage-get.md
  api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md
  api-reference/beta/api/cloudpconpremisesconnection-delete.md
  api-reference/beta/api/cloudpconpremisesconnection-get.md
  api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md
  api-reference/beta/api/cloudpconpremisesconnection-update.md
  api-reference/beta/api/cloudpcprovisioningpolicy-assign.md
  api-reference/beta/api/cloudpcprovisioningpolicy-delete.md
  api-reference/beta/api/cloudpcprovisioningpolicy-get.md
  api-reference/beta/api/cloudpcprovisioningpolicy-update.md
  api-reference/beta/api/virtualendpoint-geteffectivepermissions.md
  api-reference/beta/api/virtualendpoint-list-cloudpcs.md
  api-reference/beta/api/virtualendpoint-list-deviceimages.md
  api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md
  api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md
  api-reference/beta/api/virtualendpoint-post-deviceimages.md
  api-reference/beta/api/virtualendpoint-post-onpremisesconnections.md
  api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md
  api-reference/beta/resources/cloudpc.md
  api-reference/beta/resources/cloudpcStatusDetails.md
  api-reference/beta/resources/cloudpcdeviceimage.md
  api-reference/beta/resources/cloudpcmanagementassignmenttarget.md
  api-reference/beta/resources/cloudpcmanagementgroupassignmenttarget.md
  api-reference/beta/resources/cloudpconpremisesconnection.md
  api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
  api-reference/beta/resources/cloudpconpremisesconnectionstatusdetails.md
  api-reference/beta/resources/cloudpcprovisioningpolicy.md
  api-reference/beta/resources/cloudpcprovisioningpolicyassignment.md
  api-reference/beta/resources/cloudpcsourcedeviceimage.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/virtualendpoint.md
  api-reference/beta/toc.yml
  changelog/Microsoft.CloudManagedDesktop.json
  concepts/changelog.md
Labels: internal

#10783 Corrects broken link
  concepts/webhooks-with-resource-data.md
Labels: external

#10786 Corrects spelling
  concepts/change-notifications-delivery.md
Labels: external

#10787 Update whats-new-overview.md
  concepts/whats-new-overview.md
Labels: external

#10848 Typo "Jupyter notebook"→"Jupyter Notebook"
  api-reference/v1.0/resources/security-api-overview.md
Labels: external
