Repository microsoftgraph/microsoft-graph-docs, pull requests merged in 2020-06, with the labels that each got.

#8150 Added new properties for person component
  concepts/toolkit/components/person.md
Labels: internal

#7810 Create authorizationpolicy.md
  api-reference/beta/api/authorizationpolicy-get.md
  api-reference/beta/api/authorizationpolicy-update.md
  api-reference/beta/resources/authorizationpolicy.md
  api-reference/beta/resources/policy-overview.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: area: azure/AAD, ready to merge

#8476 version-independent doc
  api-reference/beta/resources/teams-api-overview.md
  api-reference/v1.0/resources/teams-api-overview.md
Labels: area: teams, ready to merge

#8487 - fixes #8454: adds missing available resources for group subscriptions
  api-reference/beta/resources/webhooks.md
  api-reference/v1.0/resources/webhooks.md
Labels: area: webhooks, ready to merge

#8495 Fix RSC permissions in v1.0 and beta
  api-reference/beta/api/conversationmember-get.md
  api-reference/beta/api/team-archive.md
  api-reference/beta/api/team-get-photo.md
  api-reference/beta/api/team-get.md
  api-reference/beta/api/team-unarchive.md
  api-reference/beta/api/team-update-photo.md
  api-reference/beta/api/team-update.md
  api-reference/v1.0/api/team-archive.md
  api-reference/v1.0/api/team-unarchive.md
  api-reference/v1.0/api/team-update.md
  api-reference/v1.0/api/teamsappinstallation-list.md
  api-reference/v1.0/api/teamstab-add.md
Labels: area: teams, ready to merge

#8496 Changes in RSC permissions -V1.0 & beta
  api-reference/beta/api/channel-delete.md
  api-reference/beta/api/channel-get-message.md
  api-reference/beta/api/channel-get-messagereply.md
  api-reference/beta/api/channel-get.md
  api-reference/beta/api/channel-list-messagereplies.md
  api-reference/beta/api/channel-list-messages.md
  api-reference/beta/api/channel-list.md
  api-reference/beta/api/channel-patch.md
  api-reference/beta/api/channel-post.md
  api-reference/beta/api/chatmessage-delta.md
  api-reference/beta/api/chatmessage-list-chatmessagehostedcontents.md
  api-reference/beta/api/chatmessagehostedcontent-get.md
  api-reference/beta/api/conversationmember-add.md
  api-reference/beta/api/conversationmember-delete.md
  api-reference/beta/api/conversationmember-update.md
  api-reference/beta/api/teamstab-add.md
  api-reference/beta/api/teamstab-delete.md
  api-reference/beta/api/teamstab-get.md
  api-reference/beta/api/teamstab-list.md
  api-reference/beta/api/teamstab-update.md
  api-reference/v1.0/api/channel-patch.md
  api-reference/v1.0/api/teamstab-delete.md
  api-reference/v1.0/api/teamstab-get.md
  api-reference/v1.0/api/teamstab-list.md
  api-reference/v1.0/api/teamstab-update.md
Labels: area: teams, ready to merge

#8500 Fix broken link
  api-reference/beta/api/chatmessage-delta.md
Labels: ready to merge

#8529 Updated template names
  concepts/toolkit/components/agenda.md
Labels: internal

#8484 Update group.md
  api-reference/v1.0/resources/group.md
Labels: ready to merge

#8485 Update changelog.md
  concepts/changelog.md
Labels: ready to merge

#8509 Update Search API doc based on enum change
  api-reference/beta/api/search-query.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/searchrequest.md
  concepts/search-concept-custom-types.md
  concepts/search-concept-events.md
  concepts/search-concept-files.md
  concepts/search-concept-messages.md
Labels: ready to merge

#8533 Added documentation for TemplateHelper globalContext and setBindingSyntax
  concepts/toolkit/templates.md
Labels: internal

#8527 Added the /communications/presences path
  api-reference/beta/api/presence-get.md
  concepts/changelog.md
Labels: ready to merge

#7839 App Proxy APIs with updates related to HIS APIs for BETA
  api-reference/beta/api/application-update.md
  api-reference/beta/api/connector-get.md
  api-reference/beta/api/connector-list-memberof.md
  api-reference/beta/api/connector-list.md
  api-reference/beta/api/connector-post-memberof.md
  api-reference/beta/api/connectorgroup-delete.md
  api-reference/beta/api/connectorgroup-get.md
  api-reference/beta/api/connectorgroup-list-applications.md
  api-reference/beta/api/connectorgroup-list-members.md
  api-reference/beta/api/connectorgroup-list.md
  api-reference/beta/api/connectorgroup-post-applications.md
  api-reference/beta/api/connectorgroup-post-connectorgroups.md
  api-reference/beta/api/connectorgroup-post-members.md
  api-reference/beta/api/connectorgroup-update.md
  api-reference/beta/api/onpremisesagentgroup-get.md
  api-reference/beta/resources/application.md
  api-reference/beta/resources/connector.md
  api-reference/beta/resources/connectorgroup.md
  api-reference/beta/resources/kerberossignonsettings.md
  api-reference/beta/resources/onpremisesagent.md
  api-reference/beta/resources/onpremisesagentgroup.md
  api-reference/beta/resources/onpremisespublishing.md
  api-reference/beta/resources/onpremisespublishingprofile-root.md
  api-reference/beta/resources/onpremisespublishingprofile.md
  api-reference/beta/resources/onpremisespublishingsinglesignon.md
  api-reference/beta/resources/publishedresource.md
  api-reference/beta/resources/verifiedcustomdomaincertificatesmetadata.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: area: azure/AAD, content review, ready to merge

#8560 Repair mistake in Beta TOC
  api-reference/beta/toc.yml
Labels: ready to merge

#8241 Update $filter vendor keyword - beta
  api-reference/beta/api/alert-list.md
Labels: ready to merge

#8107 Accept-Language Header for Online Meetings (v1)
  api-reference/v1.0/api/application-post-onlinemeetings.md
  api-reference/v1.0/api/onlinemeeting-get.md
  api-reference/v1.0/resources/onlinemeeting.md
  concepts/changelog.md
Labels: ready to merge

#8242 Update $filter keyword for vendor name - v1.0
  api-reference/v1.0/api/alert-list.md
Labels: ready to merge

#8173 Lipar exidapidocs
  api-reference/beta/api/authenticationflowspolicy-get.md
  api-reference/beta/api/authenticationflowspolicy-update.md
  api-reference/beta/resources/authenticationflowspolicy.md
  api-reference/beta/resources/selfservicesignupauthenticationflowconfiguration.md
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
  concepts/changelog.md
Labels: changes requested, content review, ready to merge

#8580 updating people-picker custom properties
  concepts/toolkit/components/people-picker.md
Labels: internal

#8582 Quick start FAQ update
  concepts/quick-start-faq.md
Labels: ready to merge

#8587 Recreated the changes that were in PR 8509
  api-reference/beta/api/search-query.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/searchrequest.md
  concepts/search-concept-custom-types.md
  concepts/search-concept-events.md
  concepts/search-concept-files.md
  concepts/search-concept-messages.md
Labels: ready to merge

#8592 updating mgt-people-picker enums with lowercase
  concepts/toolkit/components/people-picker.md
Labels: internal

#8583 correct filter table formatting
  concepts/query-parameters.md
Labels: ready to merge

#8577 Update group.md
  api-reference/beta/resources/group.md
Labels: ready to merge

#8578 Update group.md
  api-reference/v1.0/resources/group.md
Labels: ready to merge

#8503 Added new permissions related to teams
  concepts/permissions-reference.md
Labels: area: teams, ready to merge

#8558 Update eventmessage-post-attachments.md
  api-reference/v1.0/api/eventmessage-post-attachments.md
Labels: ready to merge

#8601 Fix casing for resourceAccess type values
  api-reference/beta/resources/resourceaccess.md
  api-reference/v1.0/resources/resourceaccess.md
Labels: area: app model, ready to merge

#8605 author change
  api-reference/beta/api/conditionalaccessroot-list-namedlocations.md
Labels: ready to merge

#8584 Service principal migration guide updates for resources and properties
  concepts/migrate-azure-ad-graph-property-differences.md
  concepts/migrate-azure-ad-graph-resource-differences.md
Labels: area: app model, content review, ready to merge

#8573 - fixes #8571: add clarity about initial delta sync
  concepts/delta-query-overview.md
Labels: area: delta query, ready to merge

#8516 add properties to alert resource
  api-reference/beta/api/alert-get.md
  api-reference/beta/resources/alert.md
  api-reference/beta/resources/networkconnection.md
  api-reference/beta/resources/securityresource.md
  api-reference/v1.0/api/alert-get.md
  api-reference/v1.0/resources/alert.md
  api-reference/v1.0/resources/networkconnection.md
  api-reference/v1.0/resources/securityresource.md
  concepts/changelog.md
Labels: ready to merge

#8507 Add new permissions to permissions-reference.md
  concepts/permissions-reference.md
Labels: area: teams, ready to merge

#8643 Replacement for TeamsApp.*.All permissions
  concepts/permissions-reference.md
Labels: area: teams, ready to merge

#8625 Updated the new permissions(Teamwork) in changelog
  concepts/changelog.md
Labels: area: teams, ready to merge

#8591 Microsoft Graph Toolkit 1.3 Update
  concepts/toolkit/components/agenda.md
  concepts/toolkit/components/login.md
  concepts/toolkit/components/people-picker.md
  concepts/toolkit/components/people.md
  concepts/toolkit/components/person.md
  concepts/toolkit/providers/msal.md
  concepts/toolkit/templates.md
Labels: ready to merge

#8606 Corrected application permission for App Proxy APIs
  api-reference/beta/api/connector-get.md
  api-reference/beta/api/connector-list-memberof.md
  api-reference/beta/api/connector-list.md
  api-reference/beta/api/connector-post-memberof.md
  api-reference/beta/api/connectorgroup-delete.md
  api-reference/beta/api/connectorgroup-get.md
  api-reference/beta/api/connectorgroup-list-applications.md
  api-reference/beta/api/connectorgroup-list-members.md
  api-reference/beta/api/connectorgroup-list.md
  api-reference/beta/api/connectorgroup-post-applications.md
  api-reference/beta/api/connectorgroup-post-members.md
  api-reference/beta/api/connectorgroup-update.md
  api-reference/beta/resources/onpremisespublishing.md
Labels: area: azure/AAD, ready to merge

#8630 - fixes #8305: adds delta token duration for education objects
  concepts/delta-query-overview.md
Labels: area: delta query, ready to merge

#8633 - adds the subscription entity to the list of resources that return r…
  concepts/throttling.md
Labels: area: throttling, area: webhooks, ready to merge

#8622 Update known-issues.md
  concepts/known-issues.md
Labels: ready to merge

#8623 Change to add S to the end of the V1.0 query
  api-reference/v1.0/api/groupsetting-post-groupsettings.md
Labels: ready to merge

#8530 Fix datatype for Calendar Event categories field
  api-reference/beta/api/event-update.md
  api-reference/v1.0/api/event-update.md
Labels: ready to merge

#8620 Weekly updates.
  api-reference/beta/resources/changenotification.md
  api-reference/beta/resources/changenotificationcollection.md
  api-reference/beta/toc.yml
  concepts/changelog.md
  concepts/choose-online-meeting-api.md
  concepts/webhooks.md
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: do not merge

#8618 Migration docs - fixed formatting and some changes
  concepts/migrate-azure-ad-graph-method-differences.md
  concepts/migrate-azure-ad-graph-property-differences.md
  concepts/migrate-azure-ad-graph-resource-differences.md
Labels: area: azure/AAD, ready to merge

#8142 get followed sites by target user
  api-reference/v1.0/api/sites-list-followed.md
Labels: external, ready to merge

#8510 - adds syncStateNotFound error to error list
  concepts/errors.md
Labels: area: delta query, ready to merge

#8713 Fixing bug in upload of files > 2GB in Java sample
  concepts/sdks/large-file-upload.md
Labels: ready to merge

#8716 Corrected error in request URL
  api-reference/beta/api/serviceprincipal-delete-homerealmdiscoverypolicies.md
Labels: external, ready to merge

#8595 Updating documentation to indicate app-only support
  api-reference/beta/api/conversation-list-threads.md
  api-reference/beta/api/conversationthread-get.md
  api-reference/beta/api/group-get-conversation.md
  api-reference/beta/api/group-get-thread.md
  api-reference/beta/api/group-list-conversations.md
  api-reference/beta/api/group-list-threads.md
  api-reference/v1.0/api/conversation-list-threads.md
  api-reference/v1.0/api/conversationthread-get.md
  api-reference/v1.0/api/group-get-conversation.md
  api-reference/v1.0/api/group-get-thread.md
  api-reference/v1.0/api/group-list-conversations.md
  api-reference/v1.0/api/group-list-threads.md
  concepts/changelog.md
  concepts/known-issues.md
Labels: ready to merge

#7493 Settings regional and language settings
  api-reference/beta/api/regionalandlanguagesettings-get.md
  api-reference/beta/api/regionalandlanguagesettings-update.md
  api-reference/beta/resources/regionalandlanguagesettings.md
  api-reference/beta/resources/regionalformatoverrides.md
  api-reference/beta/resources/user.md
  api-reference/beta/resources/usersettings.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: ready to merge

#8732 Fix examples of AU scoped assignment
  api-reference/beta/api/rbacapplication-post-roleassignments.md
Labels: ready to merge

#8721 intune 2006 v1
  api-reference/v1.0/api/intune-onboarding-compliancemanagementpartner-create.md
  api-reference/v1.0/api/intune-onboarding-compliancemanagementpartner-delete.md
  api-reference/v1.0/api/intune-onboarding-compliancemanagementpartner-get.md
  api-reference/v1.0/api/intune-onboarding-compliancemanagementpartner-list.md
  api-reference/v1.0/api/intune-onboarding-compliancemanagementpartner-update.md
  api-reference/v1.0/resources/intune-onboarding-compliancemanagementpartner.md
  api-reference/v1.0/resources/intune-onboarding-compliancemanagementpartnerassignment.md
  api-reference/v1.0/resources/intune-shared-devicemanagement.md
  concepts/changelog.md
Labels: ready to merge

#8738 Add chatMessage syntax to subscription
  api-reference/beta/api/subscription-post-subscriptions.md
Labels: area: teams, ready to merge

#8694 Update doc to include $select as supported query option
  api-reference/beta/api/user-list-licensedetails.md
  api-reference/v1.0/api/user-list-licensedetails.md
Labels: ready to merge

#8742 Update appliedconditionalaccesspolicy.md
  api-reference/v1.0/resources/appliedconditionalaccesspolicy.md
Labels: ready to merge

#8068 Removes isGuest property
  api-reference/beta/api/riskyuser-list-history.md
  api-reference/beta/api/riskyusers-get.md
  api-reference/beta/api/riskyusers-list.md
  api-reference/beta/resources/riskyuser.md
  concepts/changelog.md
Labels: area: azure/AAD, ready to merge

#8448 API Pages changes in V1.0 & beta
  api-reference/beta/api/channel-get-filesfolder.md
  api-reference/beta/api/team-get-primarychannel.md
  api-reference/beta/resources/channel.md
  api-reference/beta/resources/team.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/channel-get-filesfolder.md
  api-reference/v1.0/api/team-get-primarychannel.md
  api-reference/v1.0/resources/channel.md
  api-reference/v1.0/resources/team.md
  api-reference/v1.0/toc.yml
  concepts/changelog.md
Labels: area: teams, ready to merge

#8753 Update excel-write-to-workbook.md
  concepts/excel-write-to-workbook.md
Labels: ready to merge

#8763 Update chatmessagehostedcontent.md
  api-reference/beta/resources/chatmessagehostedcontent.md
Labels: area: teams, ready to merge

#8761 Updated DataSync Documentation
  api-reference/beta/api/regionalandlanguagesettings-get.md
  api-reference/beta/api/regionalandlanguagesettings-update.md
  api-reference/beta/resources/educationonerosterapidataprovider.md
  api-reference/beta/resources/educationpowerschooldataprovider.md
  api-reference/beta/resources/educationsynchronizationcustomization.md
  api-reference/beta/resources/educationsynchronizationcustomizations.md
  api-reference/beta/resources/educationsynchronizationdataprovider.md
  api-reference/beta/resources/educationsynchronizationprofile.md
Labels: area: edu, bug: documentation, ready to merge

#8762 Fix chat message attachment
  api-reference/beta/resources/chatmessageattachment.md
Labels: area: teams, ready to merge

#8629 Add description for userPurpose property of mailboxsettings
  api-reference/beta/api/user-get-mailboxsettings.md
  api-reference/beta/resources/mailboxsettings.md
  api-reference/beta/resources/userpurpose.md
  concepts/changelog.md
Labels: ready to merge

#8801 What's new, and some topic fixes for clarity.
  api-reference/beta/api/channel-get-filesfolder.md
  api-reference/beta/api/team-get-primarychannel.md
  api-reference/beta/resources/user.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/channel-get-filesfolder.md
  api-reference/v1.0/api/team-get-primarychannel.md
  concepts/changelog.md
  concepts/whats-new-overview.md
Labels: do not merge

#8803 Update chatmessage-delta.md
  api-reference/beta/api/chatmessage-delta.md
Labels: ready to merge

#8784 Table fixes
  api-reference/beta/api/application-update.md
  api-reference/beta/api/oauth2permissiongrant-list.md
  api-reference/beta/api/reports-getgrouparchivedprintjobs.md
  api-reference/beta/api/reports-getprinterarchivedprintjobs.md
  api-reference/beta/api/reports-getuserarchivedprintjobs.md
  api-reference/beta/api/shift-get.md
  api-reference/beta/resources/application.md
  api-reference/beta/resources/authenticationdetail.md
  api-reference/beta/resources/conversationthread.md
  api-reference/beta/resources/directoryaudit.md
  api-reference/beta/resources/educationsynchronizationdataprovider.md
  api-reference/beta/resources/featurerolloutpolicy.md
  api-reference/beta/resources/governanceroledefinition.md
  api-reference/beta/resources/group.md
  api-reference/beta/resources/personOrGroupColumn.md
  api-reference/beta/resources/planner-overview.md
  api-reference/beta/resources/regionalandlanguagesettings.md
  api-reference/beta/resources/synchronization-attributemappingsource.md
  api-reference/beta/resources/synchronization-synchronizationschema.md
  api-reference/beta/resources/tiindicator.md
  api-reference/beta/resources/user.md
  api-reference/beta/resources/useraccountinformation.md
  api-reference/beta/resources/useridentity.md
  api-reference/v1.0/api/application-update.md
  api-reference/v1.0/api/oauth2permissiongrant-list.md
  api-reference/v1.0/api/schedule-get.md
  api-reference/v1.0/api/shift-get.md
  api-reference/v1.0/api/swapshiftschangerequest-decline.md
  api-reference/v1.0/api/workbook-closesession.md
  api-reference/v1.0/resources/alert.md
  api-reference/v1.0/resources/conversationthread.md
  api-reference/v1.0/resources/directoryaudit.md
  api-reference/v1.0/resources/group.md
  api-reference/v1.0/resources/orgcontact.md
  api-reference/v1.0/resources/personorgroupcolumn.md
  api-reference/v1.0/resources/user.md
  concepts/auth-v2-user.md
  concepts/changelog.md
  concepts/delta-query-overview.md
  concepts/education-rubric-overview.md
  concepts/migrate-azure-ad-graph-feature-differences.md
  concepts/migrate-azure-ad-graph-property-differences.md
  concepts/migrate-azure-ad-graph-request-differences.md
  concepts/onenote-note-tags.md
  concepts/permissions-reference.md
  concepts/reportroot-concept-overview.md
  concepts/toolkit/providers/msal.md
  concepts/toolkit/templates.md
Labels: ready to merge

#8743 Combine docs for delta on events & on calendarview
  api-reference/beta/api/event-delta.md
  concepts/changelog.md
  concepts/delta-query-events.md
Labels: do not merge

#8617 Adding policy relationships to service principals
  api-reference/beta/toc.yml
  api-reference/v1.0/api/claimsmappingpolicy-delete.md
  api-reference/v1.0/api/claimsmappingpolicy-get.md
  api-reference/v1.0/api/claimsmappingpolicy-list-appliesto.md
  api-reference/v1.0/api/claimsmappingpolicy-list.md
  api-reference/v1.0/api/claimsmappingpolicy-post-claimsmappingpolicies.md
  api-reference/v1.0/api/claimsmappingpolicy-update.md
  api-reference/v1.0/api/serviceprincipal-delete-claimsmappingpolicies.md
  api-reference/v1.0/api/serviceprincipal-delete-homerealmdiscoverypolicies.md
  api-reference/v1.0/api/serviceprincipal-list-claimsmappingpolicies.md
  api-reference/v1.0/api/serviceprincipal-list-homerealmdiscoverypolicies.md
  api-reference/v1.0/api/serviceprincipal-post-claimsmappingpolicies.md
  api-reference/v1.0/api/serviceprincipal-post-homerealmdiscoverypolicies.md
  api-reference/v1.0/resources/application.md
  api-reference/v1.0/resources/claimsmappingpolicy.md
  api-reference/v1.0/resources/policy-overview.md
  api-reference/v1.0/resources/serviceprincipal.md
  api-reference/v1.0/toc.yml
  concepts/changelog.md
  concepts/migrate-azure-ad-graph-feature-differences.md
  concepts/migrate-azure-ad-graph-request-differences.md
  concepts/migrate-azure-ad-graph-resource-differences.md
Labels: area: azure/AAD, content review, ready to merge

#6244 allowCreatePrivateChannels added to the request
  api-reference/v1.0/api/team-put-teams.md
Labels: external, ready to merge

#6898 Update team-get.md
  api-reference/v1.0/api/team-get.md
Labels: external, ready to merge

#8788 Update deployments.md
  concepts/deployments.md
Labels: content review, ready to merge

#8767 Fix typo about accessreview.md
  api-reference/beta/resources/accessreview.md
Labels: ready to merge

#8770 Update security-authorization.md
  concepts/security-authorization.md
Labels: ready to merge

#8778 Adding author to the deployments.md doc
  concepts/deployments.md
Labels: area: national clouds, ready to merge

#8807 Update team-get-primarychannel.md
  api-reference/beta/api/team-get-primarychannel.md
Labels: ready to merge

#8805 Update team-get-primarychannel.md
  api-reference/v1.0/api/team-get-primarychannel.md
Labels: ready to merge

#8665 Bug fixes for open and schema extensions
  api-reference/beta/api/opentypeextension-delete.md
  api-reference/beta/api/opentypeextension-get.md
  api-reference/beta/api/opentypeextension-post-opentypeextension.md
  api-reference/beta/api/opentypeextension-update.md
  api-reference/beta/api/schemaextension-delete.md
  api-reference/beta/api/schemaextension-get.md
  api-reference/beta/api/schemaextension-list.md
  api-reference/beta/api/schemaextension-post-schemaextensions.md
  api-reference/beta/api/schemaextension-update.md
  api-reference/beta/resources/onpremisesextensionattributes.md
  api-reference/beta/resources/opentypeextension.md
  api-reference/beta/resources/schemaextension.md
  api-reference/beta/resources/user.md
  api-reference/v1.0/api/opentypeextension-delete.md
  api-reference/v1.0/api/opentypeextension-get.md
  api-reference/v1.0/api/opentypeextension-post-opentypeextension.md
  api-reference/v1.0/api/opentypeextension-update.md
  api-reference/v1.0/api/schemaextension-delete.md
  api-reference/v1.0/api/schemaextension-get.md
  api-reference/v1.0/api/schemaextension-list.md
  api-reference/v1.0/api/schemaextension-post-schemaextensions.md
  api-reference/v1.0/api/schemaextension-update.md
  api-reference/v1.0/resources/onpremisesextensionattributes.md
  api-reference/v1.0/resources/opentypeextension.md
  api-reference/v1.0/resources/schemaextension.md
  api-reference/v1.0/resources/user.md
  concepts/extensibility-overview.md
Labels: area: schema extensions, content review, ready to merge

#8834 update Azure AD migration docs with the latest info
  concepts/migrate-azure-ad-graph-method-differences.md
  concepts/migrate-azure-ad-graph-property-differences.md
  concepts/migrate-azure-ad-graph-resource-differences.md
Labels: area: azure/AAD, content review, ready to merge

#8701 New /identityProtection segment in beta
  api-reference/beta/api/riskdetection-get.md
  api-reference/beta/api/riskdetection-list.md
  api-reference/beta/api/riskyuser-list-history.md
  api-reference/beta/api/riskyuserhistoryitem-get.md
  api-reference/beta/api/riskyusers-confirmcompromised.md
  api-reference/beta/api/riskyusers-dismiss.md
  api-reference/beta/api/riskyusers-get.md
  api-reference/beta/api/riskyusers-list.md
Labels: area: azure/AAD, ready to merge

#8756 - adds notifications dropping policies for webhooks
  concepts/webhooks.md
Labels: area: webhooks, ready to merge

#8765 alphabetize
  concepts/permissions-reference.md
Labels: area: teams, ready to merge

#8783 - fixes #8777: updates outlook service limits for v1.0
  concepts/throttling.md
Labels: area: outlook, area: outlook events, area: throttling, ready to merge

#8808 - updates the tutorial link to the latest tutorial
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
  concepts/delta-query-overview.md
  concepts/toc.yml
  concepts/tutorials.yml
  concepts/webhooks.md
Labels: area: webhooks, ready to merge

#8684 Appproxy updates v2
  api-reference/beta/api/connectorgroup-post-applications.md
  api-reference/beta/api/connectorgroup-post-members.md
  api-reference/beta/api/connectorgroup-post.md
  api-reference/beta/resources/connectorgroup.md
  api-reference/beta/resources/kerberossignonsettings.md
  api-reference/beta/resources/onpremisespublishingsinglesignon.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: area: azure/AAD, ready to merge

#8821 Update channel-patch.md
  api-reference/beta/api/channel-patch.md
Labels: ready to merge

#8822 Update channel-patch.md
  api-reference/v1.0/api/channel-patch.md
Labels: ready to merge

#8835 Fixing wrongly tagged /chats permissions
  api-reference/beta/api/chat-get.md
  api-reference/beta/api/chat-list.md
  api-reference/beta/resources/chat.md
Labels: ready to merge

#8838 Add custom css property to people picker
  concepts/toolkit/components/people-picker.md
Labels: ready to merge

#8664 FileServicesDocs-Update-v1.0
  api-reference/beta/api/sites-list-followed.md
  api-reference/beta/resources/site.md
  api-reference/v1.0/api/driveitem-createuploadsession.md
  api-reference/v1.0/api/driveitem-get.md
  api-reference/v1.0/api/driveitem-list-thumbnails.md
  api-reference/v1.0/api/driveitem-restore.md
  api-reference/v1.0/api/sites-list-followed.md
  api-reference/v1.0/resources/columndefinition.md
  api-reference/v1.0/resources/contentTypeInfo.md
  api-reference/v1.0/resources/driveitem.md
  api-reference/v1.0/resources/driveitemuploadableproperties.md
  api-reference/v1.0/resources/geolocationcolumn.md
  api-reference/v1.0/resources/hashes.md
  api-reference/v1.0/resources/pendingcontentupdate.md
  api-reference/v1.0/resources/pendingoperations.md
  api-reference/v1.0/resources/photo.md
  api-reference/v1.0/resources/quota.md
  api-reference/v1.0/resources/storageplaninformation.md
  api-reference/v1.0/toc.yml
  concepts/changelog.md
Labels: ready to merge

#8836 Snippets Update
  api-reference/beta/api/schemaextension-post-schemaextensions.md
  api-reference/beta/includes/snippets/csharp/create-schemaextension-from-schemaextensions-3-csharp-snippets.md
  api-reference/beta/includes/snippets/csharp/event-accept-csharp-snippets.md
  api-reference/beta/includes/snippets/csharp/get-riskdetection-csharp-snippets.md
  api-reference/beta/includes/snippets/csharp/update-profilephoto-csharp-snippets.md
  api-reference/beta/includes/snippets/csharp/upload-via-put-id-csharp-snippets.md
  api-reference/beta/includes/snippets/java/create-schemaextension-from-schemaextensions-3-java-snippets.md
  api-reference/beta/includes/snippets/javascript/create-schemaextension-from-schemaextensions-3-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/get-riskdetection-javascript-snippets.md
  api-reference/beta/includes/snippets/objc/create-schemaextension-from-schemaextensions-3-objc-snippets.md
  api-reference/beta/includes/snippets/objc/get-riskdetection-objc-snippets.md
  api-reference/v1.0/api/schemaextension-post-schemaextensions.md
  api-reference/v1.0/includes/snippets/csharp/create-schemaextension-from-schemaextensions-3-csharp-snippets.md
  api-reference/v1.0/includes/snippets/csharp/event-accept-csharp-snippets.md
  api-reference/v1.0/includes/snippets/csharp/event-decline-csharp-snippets.md
  api-reference/v1.0/includes/snippets/csharp/event-tentativelyaccept-csharp-snippets.md
  api-reference/v1.0/includes/snippets/csharp/update-profilephoto-csharp-snippets.md
  api-reference/v1.0/includes/snippets/csharp/upload-via-put-id-csharp-snippets.md
  api-reference/v1.0/includes/snippets/java/create-schemaextension-from-schemaextensions-3-java-snippets.md
  api-reference/v1.0/includes/snippets/java/event-accept-java-snippets.md
  api-reference/v1.0/includes/snippets/java/event-decline-java-snippets.md
  api-reference/v1.0/includes/snippets/java/event-tentativelyaccept-java-snippets.md
  api-reference/v1.0/includes/snippets/javascript/create-schemaextension-from-schemaextensions-3-javascript-snippets.md
  api-reference/v1.0/includes/snippets/objc/create-schemaextension-from-schemaextensions-3-objc-snippets.md
  includes/snippets/csharp/event-reply-tentativelyaccept-csharp-snippets.md
  includes/snippets/java/event-reply-tentativelyaccept-java-snippets.md
Labels: ready to merge

#8858 Update schemaextension-update.md
  api-reference/beta/api/schemaextension-update.md
Labels: ready to merge

#8857 Update schemaextension-update.md
  api-reference/v1.0/api/schemaextension-update.md
Labels: ready to merge

#8867 Using "authority" in MGT TeamsProvider
  concepts/toolkit/providers/teams.md
Labels: internal

#8847 Update channel-patch.md
  api-reference/beta/api/channel-patch.md
Labels: ready to merge

#8846 Update channel-patch.md
  api-reference/v1.0/api/channel-patch.md
Labels: ready to merge

#8816 update docs for identity protection v1.0
  api-reference/v1.0/api/riskdetection-get.md
  api-reference/v1.0/api/riskdetection-list.md
  api-reference/v1.0/api/riskyuser-confirmcompromised.md
  api-reference/v1.0/api/riskyuser-dismiss.md
  api-reference/v1.0/api/riskyuser-get-riskyuserhistoryitem.md
  api-reference/v1.0/api/riskyuser-get.md
  api-reference/v1.0/api/riskyuser-list-history.md
  api-reference/v1.0/api/riskyuser-list.md
  api-reference/v1.0/resources/enums.md
  api-reference/v1.0/resources/identityprotectionroot.md
  api-reference/v1.0/resources/riskdetection.md
  api-reference/v1.0/resources/riskuseractivity.md
  api-reference/v1.0/resources/riskyuser.md
  api-reference/v1.0/resources/riskyuserhistoryitem.md
  api-reference/v1.0/toc.yml
  concepts/changelog.md
Labels: changes requested, ready to merge

#8824 Update group.md
  api-reference/beta/resources/group.md
Labels: ready to merge

#8785 feature/auto throttling documentation
  concepts/throttling.md
  includes/throttling-cpim.md
  includes/throttling-education-rostering-apis.md
  includes/throttling-excel.md
  includes/throttling-intune-applications.md
  includes/throttling-intune-books.md
  includes/throttling-intune-company-terms.md
  includes/throttling-intune-device-configuration.md
  includes/throttling-intune-device-enrollment.md
  includes/throttling-intune-devices.md
  includes/throttling-intune-enrollment.md
  includes/throttling-intune-managed-applications.md
  includes/throttling-intune-notifications.md
  includes/throttling-intune-rbac.md
  includes/throttling-intune-remote-assistance.md
  includes/throttling-intune-reporting.md
  includes/throttling-intune-tem.md
  includes/throttling-intune-troubleshooting.md
  includes/throttling-intune-wip.md
  includes/throttling-skype-calling.md
  includes/throttling-subscription-services.md
Labels: area: throttling, ready to merge

#8328 Document spsite type
  api-reference/v1.0/resources/insights-resourcevisualization.md
Labels: external, ready to merge

#8878 - auto generated update for throttling documentation
  concepts/throttling.md
  includes/throttling-Identity-and-access-audit-logs.md
Labels: area: throttling, ready to merge

#8682 Education Rostering Changes
  api-reference/beta/api/educationclass-delta.md
  api-reference/beta/api/educationschool-delta.md
  api-reference/beta/api/educationuser-delta.md
  api-reference/beta/api/educationuser-get-user.md
  api-reference/beta/api/educationuser-get.md
  api-reference/beta/api/educationuser-list-classes.md
  api-reference/beta/api/educationuser-list-schools.md
  api-reference/beta/api/educationuser-update.md
  api-reference/beta/resources/education-overview.md
  api-reference/beta/resources/educationclass.md
  api-reference/beta/resources/educationorganization.md
  api-reference/beta/resources/educationschool.md
  api-reference/beta/resources/educationstudent.md
  api-reference/beta/resources/educationteacher.md
  api-reference/beta/resources/educationuser.md
  api-reference/beta/resources/enums.md
  api-reference/v1.0/resources/education-overview.md
  api-reference/v1.0/resources/educationuser.md
  api-reference/v1.0/resources/relatedcontact.md
  concepts/changelog.md
Labels: area: edu, ready to merge

#8875 Update teamstab.md
  api-reference/v1.0/resources/teamstab.md
Labels: ready to merge

#8874 Update teamstab.md
  api-reference/beta/resources/teamstab.md
Labels: ready to merge

#8744 Bulk add members
  api-reference/beta/api/group-delete-members.md
  api-reference/beta/api/group-delete.md
  api-reference/beta/api/group-post-groups.md
  api-reference/beta/api/group-post-members.md
  api-reference/v1.0/api/group-delete-members.md
  api-reference/v1.0/api/group-delete.md
  api-reference/v1.0/api/group-post-groups.md
  api-reference/v1.0/api/group-post-members.md
  concepts/teams-create-group-and-team.md
Labels: area: teams, do not merge

#8676 HTML chat message
  api-reference/beta/resources/chatmessage.md
  concepts/chatmessage-html.md
Labels: area: teams, do not merge

#8370 Permissions column added for Teamwork API resources
  api-reference/beta/resources/channel.md
  api-reference/beta/resources/chatmessage.md
  api-reference/beta/resources/teamsapp.md
  api-reference/beta/resources/teamstab.md
Labels: do not merge

#8886 [Universal Print] Fixing changelog typo
  concepts/changelog.md
Labels: content review, ready to merge

#8898 - fixes #8895: clarifies terminology for limits
  concepts/webhooks.md
Labels: area: webhooks, ready to merge

#8909 Microsoft Graph Toolkit 1.3.1 Update
  concepts/toolkit/components/person.md
  concepts/toolkit/providers/teams.md
Labels: content review

#8810 Fix rbacApplication & rbacApplicationMultiple
  api-reference/beta/api/unifiedroleassignmentmultiple-list.md
  api-reference/beta/resources/rbacapplication.md
  api-reference/beta/resources/rbacapplicationmultiple.md
Labels: ready to merge

#8865 - adds invitation manager service limits
  concepts/throttling.md
Labels: area: azure/AAD, area: throttling, ready to merge

#8899 - updates delta token duration to 7 days for identity and education o…
  concepts/delta-query-overview.md
Labels: area: delta query, ready to merge

#8907 - auto generated update for throttling documentation
  includes/throttling-cpim.md
  includes/throttling-education-rostering-apis.md
  includes/throttling-excel.md
  includes/throttling-intune-applications.md
  includes/throttling-intune-books.md
  includes/throttling-intune-company-terms.md
  includes/throttling-intune-device-configuration.md
  includes/throttling-intune-device-enrollment.md
  includes/throttling-intune-devices.md
  includes/throttling-intune-enrollment.md
  includes/throttling-intune-managed-applications.md
  includes/throttling-intune-notifications.md
  includes/throttling-intune-rbac.md
  includes/throttling-intune-remote-assistance.md
  includes/throttling-intune-reporting.md
  includes/throttling-intune-tem.md
  includes/throttling-intune-troubleshooting.md
  includes/throttling-intune-wip.md
  includes/throttling-skype-calling.md
  includes/throttling-subscription-services.md
Labels: content review, ready to merge

#8809 Add example to unifiedRoleAssignment
  api-reference/beta/api/rbacapplication-list-roleassignments.md
Labels: ready to merge

#8920 create user update
  api-reference/beta/api/user-post-users.md
  api-reference/v1.0/api/user-post-users.md
Labels: ready to merge

#8916 Correct invalid prototypes in Education Delta documentation
  api-reference/beta/api/educationclass-delta.md
  api-reference/beta/api/educationschool-delta.md
  api-reference/beta/api/educationuser-delta.md
Labels: area: edu, bug: documentation, ready to merge

#8921 Policy cleanup
  api-reference/beta/resources/claimsmappingpolicy.md
  api-reference/beta/resources/homerealmdiscoverypolicy.md
  api-reference/beta/resources/tokenlifetimepolicy.md
  api-reference/beta/toc.yml
Labels: ready to merge

#8884 mgt: SPFx section to get started
  concepts/toolkit/get-started.md
  concepts/toolkit/providers/sharepoint.md
Labels: ready to merge
