Repository microsoftgraph/microsoft-graph-docs, pull requests merged in 2020-05, with the labels that each got.

#8010 Add rbacApplicationMultiple to roleManagement
  api-reference/beta/resources/rolemanagement.md
Labels: ready to merge

#7980 Update group.md
  api-reference/beta/resources/group.md
Labels: ready to merge

#8018 Update changelog.md
  concepts/changelog.md
Labels: ready to merge

#7640 Update place-get.md
  api-reference/beta/api/place-get.md
  api-reference/beta/api/place-list.md
  concepts/changelog.md
Labels: changes requested

#8032 Added markdown for 'important' and 'note' blocks to be consistent with MS docs
  concepts/deployments.md
Labels: ready to merge

#8011 toolkit userDetails property email update
  concepts/toolkit/components/login.md
  concepts/toolkit/components/person.md
Labels: ready to merge

#6980 Graph SDK Conceptual docs
  concepts/sdks/batch-requests.md
  concepts/sdks/customize-client.md
  concepts/sdks/large-file-upload.md
  concepts/sdks/paging.md
  concepts/toc.yml
Labels: ready to merge

#8072 Update group-delta.md
  api-reference/v1.0/api/group-delta.md
Labels: ready to merge

#8073 Update team-post.md
  api-reference/beta/api/team-post.md
Labels: ready to merge

#8108 Fix bad hyperlink
  concepts/changelog.md
Labels: area: teams, ready to merge

#7787 Clarify JSON of the profile resource, & need to use respective GET to get individual descriptive properties of user.
  api-reference/beta/api/profile-get.md
  api-reference/beta/resources/profile.md
Labels: do not merge

#8112 Adding new clientAppTypes to Conditional Access API
  api-reference/beta/api/conditionalaccesspolicy-get.md
  api-reference/beta/api/conditionalaccessroot-list-policies.md
  api-reference/beta/api/conditionalaccessroot-post-policies.md
  api-reference/beta/resources/conditionalaccessconditionset.md
  concepts/changelog.md
Labels: ready to merge

#8095 Added docs for fetch-image
  concepts/toolkit/components/person.md
Labels: internal

#7923 Added docs for new type and group-type attributes for People Picker
  concepts/toolkit/components/people-picker.md
Labels: internal

#8102 Update permissions-reference.md
  concepts/permissions-reference.md
Labels: external, ready to merge

#8113 Intune 2005 v1
  api-reference/v1.0/api/intune-mam-androidmanagedappprotection-create.md
  api-reference/v1.0/api/intune-mam-androidmanagedappprotection-get.md
  api-reference/v1.0/api/intune-mam-androidmanagedappprotection-list.md
  api-reference/v1.0/api/intune-mam-androidmanagedappprotection-update.md
  api-reference/v1.0/api/intune-mam-defaultmanagedappprotection-create.md
  api-reference/v1.0/api/intune-mam-defaultmanagedappprotection-get.md
  api-reference/v1.0/api/intune-mam-defaultmanagedappprotection-list.md
  api-reference/v1.0/api/intune-mam-defaultmanagedappprotection-update.md
  api-reference/v1.0/api/intune-mam-iosmanagedappprotection-create.md
  api-reference/v1.0/api/intune-mam-iosmanagedappprotection-get.md
  api-reference/v1.0/api/intune-mam-iosmanagedappprotection-list.md
  api-reference/v1.0/api/intune-mam-iosmanagedappprotection-update.md
  api-reference/v1.0/api/intune-mam-managedappprotection-get.md
  api-reference/v1.0/api/intune-mam-managedappprotection-list.md
  api-reference/v1.0/api/intune-mam-targetedmanagedappprotection-get.md
  api-reference/v1.0/api/intune-mam-targetedmanagedappprotection-list.md
  api-reference/v1.0/resources/intune-mam-androidmanagedappprotection.md
  api-reference/v1.0/resources/intune-mam-defaultmanagedappprotection.md
  api-reference/v1.0/resources/intune-mam-iosmanagedappprotection.md
  api-reference/v1.0/resources/intune-mam-managedappprotection.md
  api-reference/v1.0/resources/intune-mam-managedbrowsertype.md
  api-reference/v1.0/resources/intune-mam-targetedmanagedappprotection.md
  concepts/changelog.md
Labels: ready to merge

#8086 Added templates documentation for login component
  concepts/toolkit/components/login.md
Labels: internal

#7993 - adds link to ODSP best practices to avoid throttling
  concepts/throttling.md
Labels: content review, review requested

#8022 [Universal Print] Printer & PrinterShare updates for Build
  api-reference/beta/api/print-list-shares.md
  api-reference/beta/api/print-post-shares.md
  api-reference/beta/api/printer-get.md
  api-reference/beta/api/printershare-delete-allowedgroup.md
  api-reference/beta/api/printershare-delete.md
  api-reference/beta/api/printershare-get.md
  api-reference/beta/api/printershare-list-allowedgroups.md
  api-reference/beta/api/printershare-list-allowedusers.md
  api-reference/beta/api/printershare-post-allowedgroups.md
  api-reference/beta/api/printershare-post-allowedusers.md
  api-reference/beta/api/printershare-update.md
  api-reference/beta/resources/print.md
  api-reference/beta/resources/printer.md
  api-reference/beta/resources/printershare.md
  api-reference/beta/toc.yml
  concepts/changelog.md
  concepts/universal-print-concept-overview.md
Labels: Build20, ready to merge

#7230 update permissions-reference.md
  concepts/permissions-reference.md
Labels: ready to merge

#8066 update changelog, add new riskeventtype
  concepts/changelog.md
Labels: area: azure/AAD, ready to merge

#8171 - fixes #8170: adds a mention for IPs in use for change notifications
  concepts/webhooks.md
Labels: ready to merge

#8064 Update group-post-members.md
  api-reference/v1.0/api/group-post-members.md
Labels: area: groups, ready to merge

#8152 added facebook as another B2B scenario
  api-reference/v1.0/resources/identityprovider.md
  concepts/changelog.md
Labels: ready to merge

#8166 Update group.md
  api-reference/beta/resources/group.md
Labels: ready to merge

#8172 Fix camelCase in sample
  api-reference/beta/api/tokenissuancepolicy-get.md
Labels: ready to merge

#8198 Added new SDK docs to the reference TOCs
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
Labels: ready to merge

#8195 Add another example to get-roleAssignmentMultiple
  api-reference/beta/api/unifiedroleassignmentmultiple-get.md
Labels: ready to merge

#8194 Update serviceprincipal-list-transitivememberof.md
  api-reference/beta/api/serviceprincipal-list-transitivememberof.md
Labels: ready to merge

#5484 Change description for the navigation properties (shared, used, trending)
  api-reference/beta/resources/insights-usagedetails.md
  api-reference/beta/resources/insights-used.md
  api-reference/beta/resources/officegraphinsights.md
  api-reference/v1.0/resources/insights-usagedetails.md
  api-reference/v1.0/resources/insights-used.md
  api-reference/v1.0/resources/officegraphinsights.md
Labels: ready to merge

#8221 Added a link to the support page.
  concepts/known-issues.md
Labels: ready to merge

#8154 update example
  api-reference/beta/api/riskdetection-list.md
Labels: area: azure/AAD, ready to merge

#8023 [Universal Print] Adding $orderby support to Printer and PrintJob lists
  api-reference/beta/api/print-list-printers.md
  api-reference/beta/api/printer-list-jobs.md
  api-reference/beta/resources/printerlocation.md
Labels: ready to merge

#7967 Added a query option to insights/used API description.
  api-reference/beta/api/insights-list-used.md
  api-reference/v1.0/api/insights-list-used.md
Labels: ready to merge

#6026 new evaluate dynamic group membership
  api-reference/beta/api/group-evaluatedynamicmembership.md
  api-reference/beta/resources/evaluatedynamicmembershipresult.md
  api-reference/beta/resources/expressionevaluationdetails.md
  api-reference/beta/resources/group.md
  api-reference/beta/resources/propertytoevaluate.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: ready to merge

#8093 Update patch alerts - v1.0
  api-reference/v1.0/resources/security-api-overview.md
Labels: ready to merge

#8094 Update patch alerts - beta version
  api-reference/beta/resources/security-api-overview.md
Labels: ready to merge

#8141 Updates to some Microsoft Bookings API scope names
  concepts/permissions-reference.md
Labels: ready to merge

#8197 Adding auth methods API tutorial
  concepts/authenticationmethods-get-started.md
  concepts/toc.yml
Labels: area: authentication methods, area: azure/AAD, ready to merge

#8240 Add limit of 100 indicators for bulk Post
  api-reference/beta/resources/tiindicator.md
Labels: ready to merge

#8160 Compare ways to create or join an online meeting.
  concepts/choose-online-meeting-api.md
  concepts/cloud-communications-online-meetings.md
  concepts/outlook-calendar-online-meetings.md
  concepts/toc.yml
Labels: do not merge

#8252 Incorporated some more feedback for cloud com API.
  concepts/choose-online-meeting-api.md
Labels: do not merge

#8248 Updates to what's new in May.
  api-reference/beta/toc.yml
  api-reference/v1.0/resources/teams-api-overview.md
  concepts/changelog.md
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: do not merge

#8258 Removed comma
  api-reference/beta/api/application-post-calls.md
  api-reference/v1.0/api/application-post-calls.md
Labels: ready to merge

#8256 Updated deprecation message for online meetings
  api-reference/beta/api/application-post-onlinemeetings.md
  concepts/permissions-reference.md
Labels: ready to merge

#8257 Updated incorrect property name
  concepts/cloud-communications-online-meetings.md
Labels: ready to merge

#8255 add rsc to permissions reference
  concepts/permissions-reference.md
Labels: ready to merge

#7509 Mezzo3
  api-reference/beta/api/application-list.md
  api-reference/beta/api/device-list-memberof.md
  api-reference/beta/api/device-list-transitivememberof.md
  api-reference/beta/api/device-list.md
  api-reference/beta/api/group-list-memberof.md
  api-reference/beta/api/group-list-members.md
  api-reference/beta/api/group-list-transitivememberof.md
  api-reference/beta/api/group-list-transitivemembers.md
  api-reference/beta/api/group-list.md
  api-reference/beta/api/orgcontact-list.md
  api-reference/beta/api/serviceprincipal-list-memberof.md
  api-reference/beta/api/serviceprincipal-list-transitivememberof.md
  api-reference/beta/api/serviceprincipal-list.md
  api-reference/beta/api/user-list-memberof.md
  api-reference/beta/api/user-list-transitivememberof.md
  api-reference/beta/api/user-list.md
  concepts/changelog.md
  concepts/query-parameters.md
Labels: area: azure/AAD, area: query, ready to merge

#8076 Update property types to match referenced resource types
  api-reference/beta/resources/educationonerosterapidataprovider.md
  api-reference/beta/resources/educationsynchronizationprofile.md
  api-reference/beta/resources/eventmessage.md
  api-reference/beta/resources/eventmessageresponse.md
  api-reference/beta/resources/fallbackpolicy.md
  api-reference/beta/resources/file.md
  api-reference/beta/resources/onenoteidentityset.md
  api-reference/beta/resources/projectrome-notification.md
  api-reference/beta/resources/riskdetection.md
Labels: content review

#8019 Adding V1 files for Places API
  api-reference/beta/api/place-list.md
  api-reference/beta/resources/place.md
  api-reference/v1.0/api/place-get.md
  api-reference/v1.0/api/place-list.md
  api-reference/v1.0/api/place-update.md
  api-reference/v1.0/resources/place.md
  api-reference/v1.0/resources/room.md
  api-reference/v1.0/resources/roomlist.md
  api-reference/v1.0/toc.yml
  concepts/changelog.md
  concepts/places-concept-overview.md
Labels: Build20, ready to merge

#8282 Fix toc.yml for Record Response (beta and v1)
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
Labels: ready to merge

#8288 Updated overview and major services for Build.
  concepts/images/microsoft-graph-dataconnect-connectors-rebrand-800.png
  concepts/office365-groups-concept-overview.md
  concepts/overview-major-services.md
  concepts/overview.md
Labels: ready to merge

#8301 Fix missing teams snippets
  api-reference/beta/api/team-archive.md
  api-reference/beta/api/team-clone.md
  api-reference/beta/api/team-get.md
  api-reference/beta/api/team-post.md
  api-reference/beta/api/team-unarchive.md
  api-reference/v1.0/api/team-archive.md
  api-reference/v1.0/api/team-clone.md
  api-reference/v1.0/api/team-get.md
  api-reference/v1.0/api/team-unarchive.md
Labels: do not merge

#8274 address accessreview.md missing enum value
  api-reference/beta/resources/accessreview.md
Labels: area: azure/AAD, ready to merge

#8276 Update group-list-members.md
  api-reference/v1.0/api/group-list-members.md
Labels: ready to merge

#8308 Remove "private preview" from permissions that are no longer in priva…
  concepts/permissions-reference.md
Labels: area: teams, ready to merge

#8277 Update group-list-owners.md
  api-reference/v1.0/api/group-list-owners.md
Labels: ready to merge

#8369 Extracted details for group creation options.
  api-reference/beta/resources/group.md
  concepts/group-set-options.md
Labels: do not merge

#8364 Some more clarifications.
  concepts/choose-online-meeting-api.md
Labels: do not merge

#8377 Added ASP.NET Core tutorial
  concepts/toc.yml
  concepts/tutorials.yml
Labels: ready to merge

#8362 Fixed beta TOC for Information Protection
  api-reference/beta/toc.yml
Labels: ready to merge

#8234 - fixes #8231 - aligns terminology to clearly differenciate between notifications and change notifications
  api-reference/beta/api/subscription-delete.md
  api-reference/beta/api/subscription-get.md
  api-reference/beta/api/subscription-post-subscriptions.md
  api-reference/beta/api/subscription-update.md
  api-reference/beta/resources/subscription.md
  api-reference/v1.0/api/subscription-delete.md
  api-reference/v1.0/api/subscription-get.md
  api-reference/v1.0/api/subscription-post-subscriptions.md
  api-reference/v1.0/api/subscription-update.md
  api-reference/v1.0/resources/subscription.md
  concepts/webhooks-outlook-authz.md
  concepts/webhooks-with-resource-data.md
  concepts/webhooks.md
Labels: ready to merge

#8348 Removing permissions that we don't actually support
  api-reference/beta/api/channel-post-messagereply.md
  api-reference/beta/api/channel-post-messages.md
  api-reference/beta/api/chat-post-messages.md
  api-reference/beta/api/teamsapp-delete.md
  api-reference/beta/api/teamsapp-list.md
  api-reference/beta/api/teamsapp-publish.md
  api-reference/beta/api/teamsapp-update.md
  api-reference/v1.0/api/channel-post-messagereply.md
  api-reference/v1.0/api/channel-post-messages.md
  api-reference/v1.0/api/teamsapp-delete.md
  api-reference/v1.0/api/teamsapp-list.md
  api-reference/v1.0/api/teamsapp-publish.md
  api-reference/v1.0/api/teamsapp-update.md
Labels: area: teams, ready to merge

#8163 Update permissions-reference.md
  concepts/permissions-reference.md
Labels: ready to merge

#8307 - adds missing entities for delta token duration directory entities
  concepts/delta-query-overview.md
Labels: ready to merge

#8319 Small update to required permissions for reading app role assignments
  api-reference/beta/api/serviceprincipal-list-approleassignedto.md
  api-reference/beta/api/serviceprincipal-list-approleassignments.md
  api-reference/v1.0/api/serviceprincipal-list-approleassignedto.md
  api-reference/v1.0/api/serviceprincipal-list-approleassignments.md
Labels: area: app model, ready to merge

#8352 introduce delegated EntitlementManagement.Read.All perm
  api-reference/beta/api/accesspackage-get.md
  api-reference/beta/api/accesspackage-list-accesspackageresourcerolescopes.md
  api-reference/beta/api/accesspackage-list.md
  api-reference/beta/api/accesspackageassignment-list.md
  api-reference/beta/api/accesspackageassignmentpolicy-get.md
  api-reference/beta/api/accesspackageassignmentpolicy-list.md
  api-reference/beta/api/accesspackageassignmentrequest-get.md
  api-reference/beta/api/accesspackageassignmentrequest-list.md
  api-reference/beta/api/accesspackageassignmentresourcerole-get.md
  api-reference/beta/api/accesspackageassignmentresourcerole-list.md
  api-reference/beta/api/accesspackagecatalog-get.md
  api-reference/beta/api/accesspackagecatalog-list-accesspackageresourceroles.md
  api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md
  api-reference/beta/api/accesspackagecatalog-list.md
  api-reference/beta/api/accesspackageresourcerequest-list.md
  concepts/changelog.md
  concepts/permissions-reference.md
Labels: area: azure/AAD, ready to merge

#8383 Removed deprecated message
  api-reference/beta/api/application-post-onlinemeetings.md
Labels: ready to merge

#8384 Fixed typo in bookingstaffmember.md
  api-reference/beta/resources/bookingstaffmember.md
Labels: external, ready to merge

#8376 Update group-removefavorite.md
  api-reference/v1.0/api/group-removefavorite.md
Labels: ready to merge

#8357 Update openshift-update.md
  api-reference/v1.0/api/openshift-update.md
Labels: ready to merge

#8356 Update user-findmeetingtimes.md
  api-reference/v1.0/api/user-findmeetingtimes.md
Labels: ready to merge

#8344 update sample request url with correct date format
  api-reference/v1.0/api/itemactivitystat-getactivitybyinterval.md
Labels: ready to merge

#8313 update built-in tabs doc
  concepts/teams-configuring-builtin-tabs.md
Labels: ready to merge

#8327 Update group-list-members.md
  api-reference/beta/api/group-list-members.md
Labels: ready to merge

#8340 Removed "status" from example response.
  api-reference/v1.0/api/educationroot-post-schools.md
Labels: ready to merge

#8299 Temporarily removed some code sample links
  concepts/education-concept-overview.md
Labels: ready to merge

#8387 Fix chat-list permissions
  api-reference/beta/api/chat-list.md
Labels: area: teams, ready to merge

#8158 Update search-concept-files.md
  concepts/search-concept-files.md
Labels: ready to merge

#8069 Document enums for the callRecords subnamespace
  api-reference/beta/resources/callrecords-callrecord.md
  api-reference/beta/resources/callrecords-clientuseragent.md
  api-reference/beta/resources/callrecords-failureinfo.md
  api-reference/beta/resources/callrecords-mediastream.md
  api-reference/beta/resources/callrecords-networkinfo.md
  api-reference/beta/resources/callrecords-serviceuseragent.md
  api-reference/beta/resources/callrecords-session.md
  api-reference/beta/resources/callrecords-userfeedback.md
  api-reference/beta/resources/enums-callrecords.md
Labels: area: teams, changes requested, ready to merge

#8232 - fixes #8149: adds link to error response
  api-reference/beta/api/subscription-delete.md
  api-reference/beta/api/subscription-post-subscriptions.md
  api-reference/beta/api/subscription-update.md
  api-reference/v1.0/api/subscription-delete.md
  api-reference/v1.0/api/subscription-post-subscriptions.md
  api-reference/v1.0/api/subscription-update.md
Labels: ready to merge

#8405 Links to admin docs to set up Outlook with Teams.
  concepts/choose-online-meeting-api.md
  concepts/outlook-calendar-online-meetings.md
Labels: ready to merge

#8378 Mmast msft patch 3
  api-reference/beta/api/educationroot-post-classes.md
  api-reference/v1.0/api/educationroot-post-classes.md
Labels: ready to merge

#8432 Snippets Update
  api-reference/v1.0/includes/snippets/csharp/create-educationschool-from-educationroot-csharp-snippets.md
  api-reference/v1.0/includes/snippets/csharp/update-openshift-csharp-snippets.md
  api-reference/v1.0/includes/snippets/csharp/user-findmeetingtimes-csharp-snippets.md
  api-reference/v1.0/includes/snippets/java/create-educationschool-from-educationroot-java-snippets.md
  api-reference/v1.0/includes/snippets/java/update-openshift-java-snippets.md
  api-reference/v1.0/includes/snippets/java/user-findmeetingtimes-java-snippets.md
  api-reference/v1.0/includes/snippets/javascript/create-educationschool-from-educationroot-javascript-snippets.md
  api-reference/v1.0/includes/snippets/javascript/update-openshift-javascript-snippets.md
  api-reference/v1.0/includes/snippets/javascript/user-findmeetingtimes-javascript-snippets.md
  api-reference/v1.0/includes/snippets/objc/create-educationschool-from-educationroot-objc-snippets.md
  api-reference/v1.0/includes/snippets/objc/update-openshift-objc-snippets.md
  api-reference/v1.0/includes/snippets/objc/user-findmeetingtimes-objc-snippets.md
Labels: ready to merge

#8427 Update teamsappinstallation-add.md
  api-reference/v1.0/api/teamsappinstallation-add.md
Labels: ready to merge

#7300 clarify accessPackageSubject
  api-reference/beta/api/accesspackageassignment-list.md
  api-reference/beta/api/accesspackageassignmentpolicy-list.md
  api-reference/beta/api/accesspackageassignmentrequest-get.md
  api-reference/beta/api/accesspackageassignmentrequest-list.md
  api-reference/beta/api/accesspackageassignmentrequest-post.md
  api-reference/beta/api/accesspackageassignmentresourcerole-list.md
  api-reference/beta/resources/accesspackageassignmentresourcerole.md
  api-reference/beta/resources/entitlementmanagement-root.md
Labels: area: azure/AAD, ready to merge

#8008 Update callrecords-failureinfo.md
  api-reference/beta/resources/callrecords-failureinfo.md
Labels: area: teams, ready to merge

#8425 Update administrativeunit-delta.md
  api-reference/beta/api/administrativeunit-delta.md
Labels: ready to merge

#8423 Update worksheet-range.md
  api-reference/beta/api/worksheet-range.md
Labels: ready to merge

#8424 Update synchronization-synchronizationtemplate-update.md
  api-reference/beta/api/synchronization-synchronizationtemplate-update.md
Labels: ready to merge

#8109 Added permission references for Authentication Flows policies
  concepts/permissions-reference.md
Labels: area: azure/AAD, ready to merge

#8449 Add a paragraph to call records permission
  concepts/permissions-reference.md
Labels: area: teams, ready to merge

#8447 Update group-update.md
  api-reference/beta/api/group-update.md
Labels: ready to merge

#8455 Add notice of terms of use violation
  api-reference/beta/api/channel-post-messagereply.md
  api-reference/beta/api/channel-post-messages.md
Labels: area: teams, ready to merge

#8461 - updates documentation to list properties that cannot be updated in …
  api-reference/beta/api/user-update.md
  api-reference/v1.0/api/user-update.md
Labels: area: sharepoint, ready to merge

#8467 Re-document some things we undocumented recently
  concepts/teams-configuring-builtin-tabs.md
Labels: area: teams, ready to merge

#8413 Update group-set-options.md documentation
  concepts/group-set-options.md
Labels: ready to merge

#8317 Updating user resource to add 2 new properties
  api-reference/v1.0/resources/user.md
Labels: area: users, ready to merge

#8316 Updated changlog to add new user properties in May 2020
  concepts/changelog.md
Labels: ready to merge

#8478 - updates owner of the page for better triage
  concepts/query-parameters.md
Labels: ready to merge

#8394 - adds id and sequence number to change notification
  api-reference/beta/resources/changenotification.md
  api-reference/beta/resources/changenotificationcollection.md
  api-reference/beta/resources/changenotificationencryptedcontent.md
  api-reference/beta/resources/resourcedata.md
  concepts/changelog.md
  concepts/webhooks-outlook-authz.md
  concepts/webhooks-with-resource-data.md
  concepts/webhooks.md
Labels: area: webhooks, ready to merge

#8483 Removed self perms from auth method change APIs
  api-reference/beta/api/authentication-post-phonemethods.md
  api-reference/beta/api/passwordauthenticationmethod-resetpassword.md
  api-reference/beta/api/phoneauthenticationmethod-delete.md
  api-reference/beta/api/phoneauthenticationmethod-update.md
Labels: ready to merge

#8486 - adds support for graph webhooks in us gov national deployment
  concepts/changelog.md
  concepts/deployments.md
Labels: area: webhooks, ready to merge
