Repository microsoftgraph/microsoft-graph-docs, pull requests merged in 2020-07, with the labels that each got.

#8722 [Universal Print] Adding support for printer registration
  api-reference/beta/api/printer-create.md
  api-reference/beta/api/printoperation-get.md
  api-reference/beta/resources/print.md
  api-reference/beta/resources/printcertificatesigningrequest.md
  api-reference/beta/resources/printer.md
  api-reference/beta/resources/printercreateoperation.md
  api-reference/beta/resources/printoperation.md
  api-reference/beta/resources/printoperationstatus.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: content review, ready to merge

#8925 [Universal Print] Add support for listing print jobs using application permissions
  api-reference/beta/api/printer-list-jobs.md
Labels: content review, ready to merge

#8797 Clarify how to retrieve a call record id
  api-reference/beta/api/callrecords-callrecord-get.md
  api-reference/v1.0/api/callrecords-callrecord-get.md
Labels: area: teams, ready to merge

#8799 Create synchronization-synchronizationjob-provision-on-demand.md
  api-reference/beta/api/synchronization-synchronizationjob-provision-on-demand.md
  api-reference/beta/resources/synchronization-synchronizationjob.md
  api-reference/beta/resources/synchronization-synchronizationjobapplicationparameters.md
  api-reference/beta/resources/synchronization-synchronizationjobsubject.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: ready to merge

#8927 [Universal Print] Adding support for $expand=documents on Get printJob
  api-reference/beta/api/printer-list-jobs.md
  api-reference/beta/api/printjob-get.md
  concepts/changelog.md
Labels: ready to merge

#8939 typo fix
  api-reference/v1.0/resources/identityprotectionroot.md
Labels: ready to merge

#8924 Update mgt-person css property name
  concepts/toolkit/components/person.md
Labels: ready to merge

#8905 Update externalconnection-post-schema.md
  api-reference/beta/api/externalconnection-post-schema.md
Labels: ready to merge

#8922 [Universal Print] Adding support for updating printer attributes using IPP
  api-reference/beta/api/printer-update.md
  concepts/changelog.md
Labels: changelog, ready to merge

#8855 Updating printers using application permissions with application/ipp
  api-reference/beta/api/printer-update.md
Labels: awaiting internal response, do not merge

#8959 Update security-integration.md
  concepts/security-integration.md
Labels: ready to merge

#8757 - adds additional headers support for OSDP delta
  api-reference/v1.0/api/driveitem-delta.md
Labels: area: delta query, area: onedrive, ready to merge

#8862 - adds o365 reports service limits
  concepts/throttling.md
Labels: area: office reports, area: throttling, ready to merge

#8950 - fixes #8443: fixes the unit of the upload limit
  concepts/throttling.md
Labels: area: outlook, area: throttling, ready to merge

#8952 - removes changenotification sequencenumber that was introduced by error
  api-reference/beta/resources/changenotification.md
  api-reference/v1.0/resources/changenotification.md
  concepts/changelog.md
  concepts/webhooks.md
Labels: area: webhooks, bug: documentation, ready to merge

#8956 Restructure API TOCs
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
Labels: ready to merge

#8957 Mandatory displayName in Intune role assignments
  api-reference/beta/api/unifiedroleassignmentmultiple-post.md
  api-reference/beta/resources/unifiedroleassignmentmultiple.md
Labels: ready to merge

#8955 [Universal Print] Adding new permissions to the permissions reference and changelog
  concepts/changelog.md
  concepts/permissions-reference.md
Labels: area: permissions, changelog, content review, ready to merge

#8866 - adds insights service limits
  concepts/throttling.md
Labels: area: insights, area: throttling, ready to merge

#8960 added note to signinactivity
  api-reference/beta/resources/signinactivity.md
Labels: ready to merge

#8961 Update profile photo fixes for beta
  api-reference/beta/api/profilephoto-get.md
  api-reference/beta/api/profilephoto-update.md
Labels: area: profilePhoto, content review, ready to merge

#8367 Add profileCardProperties content
  api-reference/beta/api/organizationsettings-get.md
  api-reference/beta/api/organizationsettings-list-profilecardproperties.md
  api-reference/beta/api/organizationsettings-post-profilecardproperties.md
  api-reference/beta/api/profilecardproperty-delete.md
  api-reference/beta/api/profilecardproperty-get.md
  api-reference/beta/api/profilecardproperty-update.md
  api-reference/beta/resources/displaynamelocalization.md
  api-reference/beta/resources/organization.md
  api-reference/beta/resources/organizationsettings.md
  api-reference/beta/resources/profile.md
  api-reference/beta/resources/profilecardannotation.md
  api-reference/beta/resources/profilecardproperty.md
  api-reference/beta/resources/social-overview.md
  api-reference/beta/toc.yml
  concepts/changelog.md
  concepts/overview-major-services.md
  concepts/social-intel-concept-overview.md
Labels: changelog, changes requested

#8887 Team membership APIs
  api-reference/beta/api/conversationmember-add.md
  api-reference/beta/api/conversationmember-get.md
  api-reference/beta/api/conversationmember-update.md
  api-reference/beta/api/team-delete-members.md
  api-reference/beta/api/team-list-members.md
  api-reference/beta/api/team-post-members.md
  api-reference/beta/resources/aaduserconversationmember.md
  api-reference/beta/resources/conversationmember.md
  api-reference/beta/resources/team.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: area: teams, changelog, ready to merge

#8971 Update team.md
  api-reference/v1.0/resources/team.md
Labels: ready to merge

#8748 Presence Subscriptions (Preview)
  api-reference/beta/resources/presence.md
  api-reference/beta/resources/webhooks.md
  concepts/changelog.md
  concepts/webhooks.md
Labels: area: webhooks, ready to merge

#8850 Adding note for non-gallery creation
  api-reference/beta/api/applicationtemplate-instantiate.md
Labels: ready to merge

#8908 - adds clarification for the term tenant
  concepts/throttling.md
Labels: area: throttling, ready to merge

#8954 - adds teams shift throttling limits
  concepts/throttling.md
Labels: area: teams, area: throttling, ready to merge

#8958 - adds throttling limits for cloud communications APIs
  concepts/cloud-communications-concept-overview.md
  concepts/cloud-communications-limits.md
  concepts/throttling.md
  concepts/toc.yml
Labels: area: throttling, ready to merge

#7556 Ponincev working
  .gitignore
  concepts/add-properties-profilecard.md
  concepts/toc.yml
Labels: ready to merge

#8968 Removed old policy topics from beta and added redirects
  .openpublishing.redirection.json
  api-reference/beta/api/application-delete-tokenissuancepolicies.md
  api-reference/beta/api/application-list-tokenissuancepolicies.md
  api-reference/beta/api/application-post-tokenissuancepolicies.md
  api-reference/beta/api/policy-assign.md
  api-reference/beta/api/policy-delete.md
  api-reference/beta/api/policy-get.md
  api-reference/beta/api/policy-list-appliesto.md
  api-reference/beta/api/policy-list-assigned.md
  api-reference/beta/api/policy-list.md
  api-reference/beta/api/policy-post.md
  api-reference/beta/api/policy-update.md
  api-reference/beta/resources/application.md
  api-reference/beta/resources/azure-ad-overview.md
  api-reference/beta/resources/policy.md
  api-reference/beta/resources/serviceprincipal.md
  api-reference/beta/toc.yml
  api-reference/v1.0/resources/application.md
  api-reference/v1.0/resources/serviceprincipal.md
  api-reference/v1.0/toc.yml
Labels: area: azure/AAD, ready to merge

#8994 Added more links to profile card concept topic.
  api-reference/beta/api/organizationsettings-post-profilecardproperties.md
  concepts/social-intel-concept-overview.md
Labels: ready to merge

#8981 [Universal Print] Improving consistency of evolvable enum documentation
  api-reference/beta/resources/printercapabilities.md
  api-reference/beta/resources/printerdefaults.md
  api-reference/beta/resources/printerdocumentconfiguration.md
Labels: area: universal print, ready to merge

#8978 Document restriction on channel.isFavoriteByDefault
  api-reference/beta/resources/channel.md
Labels: area: teams, ready to merge

#8734 new app proxy tutorial
  concepts/application-proxy-configure-api.md
  concepts/applications-concept-overview.md
  concepts/toc.yml
Labels: ready to merge

#8980 [Universal Print] Clarify that capabilities are not returned by GET /print/shares
  api-reference/beta/api/print-list-shares.md
Labels: area: universal print, ready to merge

#8970 Update team.md
  api-reference/beta/resources/team.md
Labels: ready to merge

#9029 Update conversationmember-update.md
  api-reference/beta/api/conversationmember-update.md
Labels: ready to merge

#9027 Update team-delete-members.md
  api-reference/beta/api/team-delete-members.md
Labels: ready to merge

#8991 Replace placeholder query term in examples
  api-reference/beta/api/driveitem-search.md
  api-reference/v1.0/api/driveitem-search.md
Labels: area: onedrive, awaiting internal response, ready to merge

#8880 - adds conditional access and identity protection service limits
  concepts/throttling.md
Labels: area: identity protection, area: throttling, ready to merge

#8883 [Universal Print] Adding support for task definitions and triggers
  api-reference/beta/api/print-delete-taskdefinition.md
  api-reference/beta/api/print-list-taskdefinitions.md
  api-reference/beta/api/print-post-taskdefinitions.md
  api-reference/beta/api/print-update-taskdefinition.md
  api-reference/beta/api/printer-delete-tasktrigger.md
  api-reference/beta/api/printer-list-tasktriggers.md
  api-reference/beta/api/printer-post-tasktriggers.md
  api-reference/beta/api/printjob-get.md
  api-reference/beta/api/printjob-redirect.md
  api-reference/beta/api/printtask-get.md
  api-reference/beta/api/printtaskdefinition-get.md
  api-reference/beta/api/printtaskdefinition-list-tasks.md
  api-reference/beta/api/printtaskdefinition-update-task.md
  api-reference/beta/api/printtasktrigger-get.md
  api-reference/beta/resources/print.md
  api-reference/beta/resources/printer.md
  api-reference/beta/resources/printjob.md
  api-reference/beta/resources/printtask.md
  api-reference/beta/resources/printtaskdefinition.md
  api-reference/beta/resources/printtaskstatus.md
  api-reference/beta/resources/printtasktrigger.md
  api-reference/beta/toc.yml
  concepts/changelog.md
  concepts/universal-print-concept-overview.md
Labels: area: universal print, changelog, changelog required, content review, ready to merge

#9038 Fix incorrect paths in recently released profileCardProperties docs
  api-reference/beta/api/organizationsettings-list-profilecardproperties.md
  api-reference/beta/api/organizationsettings-post-profilecardproperties.md
  api-reference/beta/api/profilecardproperty-delete.md
  api-reference/beta/api/profilecardproperty-get.md
  api-reference/beta/api/profilecardproperty-update.md
Labels: content review, ready to merge

#9026 Update team-post-members.md
  api-reference/beta/api/team-post-members.md
Labels: ready to merge

#9036 Update webhooks.md
  concepts/webhooks.md
Labels: ready to merge

#8997 - adds teams subscriptions limits
  concepts/webhooks.md
Labels: area: teams, area: webhooks, ready to merge

#7956 Adding userRisk condition and passwordChange control.
  api-reference/beta/resources/conditionalaccessconditionset.md
  api-reference/beta/resources/conditionalaccessgrantcontrols.md
  concepts/changelog.md
Labels: area: azure/AAD, area: identity protection, changelog, ready to merge

#9051 Update changelog.md
  concepts/changelog.md
Labels: ready to merge

#8996 Added EmailAsAlternateId feature to rollout policy.
  api-reference/beta/resources/featurerolloutpolicy.md
Labels: ready to merge

#9013 - auto generated update for throttling documentation
  concepts/throttling.md
Labels: area: throttling, ready to merge

#9067 Update team-delete-members.md
  api-reference/beta/api/team-delete-members.md
Labels: ready to merge

#9018 Fix Documentation Bugs
  concepts/changelog.md
Labels: ready to merge

#9057 Update team-list-members.md
  api-reference/beta/api/team-list-members.md
Labels: ready to merge

#9101 Sample update for Connectors search
  concepts/search-concept-custom-types.md
Labels: ready to merge

#9088 Update dynamics-account-get.md
  api-reference/beta/api/dynamics-account-get.md
Labels: ready to merge

#9087 Update dynamics-account.md
  api-reference/beta/resources/dynamics-account.md
Labels: ready to merge

#9077 - auto generated update for throttling documentation
  includes/throttling-education-rostering-apis.md
Labels: area: throttling, ready to merge

#9020 Add changelog in Json format
  changelog/Manual.NonWorkloadChanges.json
  changelog/Microsoft.AAD.Reporting.json
  changelog/Microsoft.Analytics.json
  changelog/Microsoft.DirectoryServices.json
  changelog/Microsoft.EducationAssignment.json
  changelog/Microsoft.Exchange.json
  changelog/Microsoft.FileServices.json
  changelog/Microsoft.Intune.json
  changelog/Microsoft.NAV.json
  changelog/Microsoft.Office.Tasks.json
  changelog/Microsoft.OneNote.json
  changelog/Microsoft.Search.json
  changelog/Microsoft.SharePoint.json
  changelog/Microsoft.Skype.Calling.json
  changelog/Microsoft.SubscriptionServices.json
  changelog/Microsoft.Teams.Core.json
  changelog/Microsoft.ThreatAssessment.json
  changelog/changelog.json
Labels: ready to merge

#9058 Update team-post-members.md
  api-reference/beta/api/team-post-members.md
Labels: ready to merge

#9059 Update team-delete-members.md
  api-reference/beta/api/team-delete-members.md
Labels: ready to merge

#9072 Update printconnector.md
  api-reference/beta/resources/printconnector.md
Labels: ready to merge

#9060 Doc updates for GA of schema extensions in US Gov cloud
  concepts/changelog.md
  concepts/deployments.md
  concepts/whats-new-overview.md
Labels: ready to merge

#9041 Yuayuan long running operation update
  api-reference/beta/api/workbook-createsession.md
  api-reference/beta/api/workbookoperation-get.md
  api-reference/beta/resources/workbook.md
  api-reference/beta/resources/workbookoperation.md
  api-reference/beta/resources/workbookoperationerror.md
  concepts/changelog.md
Labels: area: excel, beta, ready to merge

#8863 - adds information protection throttling
  concepts/throttling.md
Labels: area: identity protection, area: throttling, ready to merge

#9042 bugfix/delta-event-missing-token
  concepts/delta-query-events.md
Labels: area: delta query, area: outlook events, ready to merge

#9062 - adds project rome throttling limits
  concepts/throttling.md
Labels: area: rome, area: throttling, ready to merge

#9113 - adds open and schema extensions service limits
  concepts/throttling.md
Labels: area: open extensions, area: schema extensions, area: throttling, ready to merge

#9120 Add a pointer to tutorial on how to use APIs
  api-reference/beta/resources/onpremisespublishing.md
  api-reference/beta/resources/onpremisespublishingprofile-root.md
Labels: area: azure/AAD, ready to merge

#9159 - adds worklows so conflicting PRs are tagged automatically
  .github/label-commenter-config.yml
  .github/workflows/conflicting-pr-comment.yml
  .github/workflows/conflicting-pr-label.yml
Labels: ready to merge

#9049 - adds onenote throttling service limits
  concepts/throttling.md
Labels: area: onenote, area: throttling, ready to merge

#9117 - adds missing entry to list for change notifications
  concepts/webhooks.md
Labels: area: webhooks, ready to merge

#9118 - adds security detections and incidents service limits
  concepts/throttling.md
Labels: area: Security, area: azure/AAD, area: throttling, ready to merge

#9158 - auto generated update for throttling documentation
  includes/throttling-excel.md
Labels: area: throttling, ready to merge

#9114 - adds global service limits
  concepts/throttling.md
Labels: area: throttling, ready to merge

#9023 added new mezzo features info
  concepts/query-parameters.md
Labels: ready to merge

#9160 Added additional permissions for default templates
  concepts/toolkit/components/agenda.md
  concepts/toolkit/components/people.md
Labels: ready to merge

#9152 Added additional botData information that was missing before
  api-reference/beta/api/call-answer.md
  api-reference/beta/api/call-updaterecordingstatus.md
  api-reference/v1.0/api/call-answer.md
  api-reference/v1.0/api/call-updaterecordingstatus.md
Labels: ready to merge

#9148 Patch meeting API beta
  api-reference/beta/api/onlinemeeting-update.md
  api-reference/beta/resources/onlinemeeting.md
  concepts/changelog.md
Labels: ready to merge

#9166 added patch/update meeting in table of contents
  api-reference/beta/toc.yml
Labels: ready to merge

#9164 groupupdate2
  api-reference/beta/resources/group.md
  api-reference/beta/resources/user.md
  api-reference/v1.0/resources/assignedlabel.md
  api-reference/v1.0/resources/group.md
  concepts/changelog.md
Labels: area: azure/AAD, ready to merge

#9103 [CallRecords] Remove invalid sdk samples
  api-reference/beta/api/callrecords-callrecord-get.md
  api-reference/beta/api/callrecords-session-list.md
  api-reference/v1.0/api/callrecords-callrecord-get.md
  api-reference/v1.0/api/callrecords-session-list.md
Labels: content review, ready to merge

#9163 Update call.md
  api-reference/v1.0/resources/call.md
Labels: ready to merge

#9169 What's new update, and a few corrections.
  api-reference/beta/resources/profilecardproperty.md
  concepts/add-properties-profilecard.md
  concepts/changelog.md
  concepts/whats-new-overview.md
Labels: do not merge

#9065 Add ID
  api-reference/beta/resources/synchronization-synchronizationschema.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: area: azure/AAD, ready to merge

#9054 Add acquireAccessToken
  api-reference/beta/api/synchronization-synchronization-acquireaccesstoken.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: area: azure/AAD, content review, ready to merge

#9190 Update team-delete-members.md
  api-reference/beta/api/team-delete-members.md
Labels: ready to merge

#8812 query assignments for a particular policy
  api-reference/beta/api/accesspackageassignment-list.md
Labels: area: azure/AAD, ready to merge

#9161 - adds PXS service limits
  concepts/throttling.md
Labels: area: identity protection, area: throttling, ready to merge

#8976 Adding TeamsAppInstallation.Read*ForTeam
  api-reference/beta/api/teamsappinstallation-add.md
  api-reference/beta/api/teamsappinstallation-delete.md
  api-reference/beta/api/teamsappinstallation-list.md
  api-reference/beta/api/teamsappinstallation-upgrade.md
  api-reference/beta/api/user-add-teamsappinstallation.md
  api-reference/beta/api/user-delete-teamsappinstallation.md
  api-reference/beta/api/user-list-teamsappinstallation.md
  api-reference/beta/api/user-upgrade-teamsappinstallation.md
  api-reference/v1.0/api/teamsappinstallation-add.md
  api-reference/v1.0/api/teamsappinstallation-delete.md
  api-reference/v1.0/api/teamsappinstallation-list.md
  api-reference/v1.0/api/teamsappinstallation-upgrade.md
  concepts/changelog.md
  concepts/permissions-reference.md
Labels: area: teams, ready to merge

#9154 Update delta-query-overview.md
  concepts/delta-query-overview.md
Labels: area: delta query, area: outlook, area: outlook events, ready to merge

#9144 Create workbook-error-codes.md
  concepts/toc.yml
  concepts/workbook-error-codes.md
Labels: area: excel, content review, ready to merge

#9187 get available extension props to v1 (mark 2)
  api-reference/v1.0/api/directoryobject-getavailableextensionproperties.md
  api-reference/v1.0/resources/application.md
  api-reference/v1.0/resources/directoryobject.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.DirectoryServices.json
  concepts/changelog.md
  concepts/migrate-azure-ad-graph-feature-differences.md
  concepts/migrate-azure-ad-graph-method-differences.md
Labels: area: app model, area: azure/AAD, ready to merge

#8699 add entitlement management settings singleton
  api-reference/beta/api/entitlementmanagementsettings-get.md
  api-reference/beta/api/entitlementmanagementsettings-update.md
  api-reference/beta/resources/entitlementmanagement-root.md
  api-reference/beta/resources/entitlementmanagementsettings.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: area: azure/AAD, changelog, ready to merge

#8218 Create V1 documentation for CA APis
  api-reference/v1.0/api/conditionalaccesspolicy-delete.md
  api-reference/v1.0/api/conditionalaccesspolicy-get.md
  api-reference/v1.0/api/conditionalaccesspolicy-update.md
  api-reference/v1.0/api/conditionalaccessroot-list-policies.md
  api-reference/v1.0/api/conditionalaccessroot-post-policies.md
  api-reference/v1.0/resources/applicationenforcedrestrictionssessioncontrol.md
  api-reference/v1.0/resources/cloudappsecuritysessioncontrol.md
  api-reference/v1.0/resources/conditionalaccessapplications.md
  api-reference/v1.0/resources/conditionalaccessconditionset.md
  api-reference/v1.0/resources/conditionalaccessgrantcontrols.md
  api-reference/v1.0/resources/conditionalaccesslocations.md
  api-reference/v1.0/resources/conditionalaccessplatforms.md
  api-reference/v1.0/resources/conditionalaccesspolicy.md
  api-reference/v1.0/resources/conditionalaccesssessioncontrol.md
  api-reference/v1.0/resources/conditionalaccesssessioncontrols.md
  api-reference/v1.0/resources/conditionalaccessusers.md
  api-reference/v1.0/resources/persistentbrowsersessioncontrol.md
  api-reference/v1.0/resources/signinfrequencysessioncontrol.md
  api-reference/v1.0/toc.yml
  concepts/changelog.md
Labels: area: azure/AAD, changelog, ready to merge

#9015 Update HTTP syntax to reflect available URLs
  api-reference/beta/api/informationprotectionpolicy-list-labels.md
Labels: ready to merge

#9017 Add Information protection policy permissions
  concepts/permissions-reference.md
Labels: ready to merge

#8851 Update synchronization-attributedefinition.md
  api-reference/beta/resources/synchronization-attributedefinition.md
  concepts/changelog.md
Labels: conflicting

#9221 Clarify lastUpdatedDateTime
  api-reference/beta/resources/chat.md
Labels: area: teams, ready to merge

#9183 - adds trigger on push to master
  .github/workflows/conflicting-pr-label.yml
Labels: ready to merge

#7487 - fixes behavior description for lifecycle notifications
  concepts/webhooks-outlook-authz.md
Labels: area: webhooks, ready to merge

#8338 - removes preview tag from service principal delta
  api-reference/v1.0/resources/serviceprincipal.md
  api-reference/v1.0/toc.yml
  concepts/changelog.md
  concepts/delta-query-overview.md
Labels: area: delta query, changelog, ready to merge

#9184 - adds missing service limits information for ODSP and planner
  concepts/throttling.md
Labels: area: onedrive, area: planner, area: sharepoint, area: throttling, ready to merge

#9228 Fix documentation bugs
  api-reference/beta/api/workbook-list-comments.md
  api-reference/v1.0/api/workbook-list-comments.md
  concepts/workbook-error-codes.md
Labels: area: excel, ready to merge

#9229 - fixes sample to match scenario
  api-reference/beta/api/subscription-post-subscriptions.md
  api-reference/v1.0/api/subscription-post-subscriptions.md
Labels: area: webhooks, ready to merge

#9238 mgt-people-picker defaultSelectedUserIds prop
  concepts/toolkit/components/people-picker.md
Labels: ready to merge

#9239 Add new css property to mgt-person
  concepts/toolkit/components/person.md
Labels: internal

#9176 Long running operation -async createsession update for 1.0
  api-reference/v1.0/api/workbook-createsession.md
  api-reference/v1.0/api/workbookoperation-get.md
  api-reference/v1.0/resources/workbook.md
  api-reference/v1.0/resources/workbookoperation.md
  api-reference/v1.0/resources/workbookoperationerror.md
  concepts/changelog.md
Labels: area: excel, ready to merge

#8831 Elmakhmu/add item insight privacy topics
  api-reference/beta/api/insights-list-trending.md
  api-reference/beta/api/insights-list-used.md
  api-reference/beta/api/iteminsightssettings-get.md
  api-reference/beta/api/iteminsightssettings-update.md
  api-reference/beta/api/organizationsettings-get.md
  api-reference/beta/resources/insights-resourcereference.md
  api-reference/beta/resources/insights-resourcevisualization.md
  api-reference/beta/resources/iteminsights.md
  api-reference/beta/resources/iteminsightssettings.md
  api-reference/beta/resources/officegraphinsights.md
  api-reference/beta/resources/organizationsettings.md
  api-reference/beta/resources/social-overview.md
  api-reference/beta/resources/user.md
  api-reference/beta/toc.yml
  concepts/changelog.md
  concepts/insights-customize-item-insights-privacy.md
  concepts/social-intel-concept-overview.md
  concepts/toc.yml
Labels: changelog, changelog required, content review, ready to merge

#8339 Feature/oauth2 permission grant delta v1
  api-reference/v1.0/api/oauth2permissiongrant-delta.md
  api-reference/v1.0/resources/oauth2permissiongrant.md
  api-reference/v1.0/toc.yml
  concepts/changelog.md
  concepts/delta-query-overview.md
Labels: area: delta query, changelog, ready to merge

#9258 Rolled up what's new this week.
  concepts/changelog.md
  concepts/versioning-and-support.md
  concepts/whats-new-overview.md
Labels: do not merge

#8852 Added expirationDate to educationSynchronizationProfile
  api-reference/beta/api/educationsynchronizationerrors-get.md
  api-reference/beta/api/educationsynchronizationprofilestatus-get.md
  api-reference/beta/resources/educationcsvdataprovider.md
  api-reference/beta/resources/educationfilesynchronizationverificationmessage.md
  api-reference/beta/resources/educationidentitycreationconfiguration.md
  api-reference/beta/resources/educationidentitydomain.md
  api-reference/beta/resources/educationidentitymatchingconfiguration.md
  api-reference/beta/resources/educationidentitymatchingoptions.md
  api-reference/beta/resources/educationidentitysynchronizationconfiguration.md
  api-reference/beta/resources/educationsynchronizationconnectionsettings.md
  api-reference/beta/resources/educationsynchronizationdataprovider.md
  api-reference/beta/resources/educationsynchronizationerror.md
  api-reference/beta/resources/educationsynchronizationlicenseassignment.md
  api-reference/beta/resources/educationsynchronizationoauth1connectionsettings.md
  api-reference/beta/resources/educationsynchronizationoauth2clientcredentialsconnectionsettings.md
  api-reference/beta/resources/educationsynchronizationprofile.md
  api-reference/beta/resources/educationsynchronizationprofilestatus.md
  concepts/changelog.md
Labels: area: edu, changelog, ready to merge

#9074 Update user.md
  api-reference/beta/resources/user.md
Labels: area: azure/AAD, area: users, ready to merge

#9291 Updated POST online meeting docs
  api-reference/beta/api/application-post-onlinemeetings.md
Labels: content review, do not merge

#9131 Adding PSTN and Direct Routing call log documentation
  api-reference/beta/api/callrecords-callrecord-getdirectroutingcalls.md
  api-reference/beta/api/callrecords-callrecord-getpstncalls.md
  api-reference/beta/resources/callrecords-api-overview.md
  api-reference/beta/resources/callrecords-callrecord.md
  api-reference/beta/resources/callrecords-directroutinglogrow.md
  api-reference/beta/resources/callrecords-pstncalllogrow.md
  api-reference/beta/toc.yml
  concepts/changelog.md
  concepts/cloud-communications-callrecords.md
  concepts/permissions-reference.md
Labels: ready to merge

#8917 Education: New externalSourceDetail Property
  api-reference/beta/resources/educationclass.md
  api-reference/beta/resources/educationschool.md
  api-reference/beta/resources/educationuser.md
  changelog/changelog.json
  concepts/changelog.md
Labels: area: edu, changelog, changes requested, ready to merge

#8638 introduce connected org API
  api-reference/beta/api/connectedorganization-delete.md
  api-reference/beta/api/connectedorganization-get.md
  api-reference/beta/api/connectedorganization-list.md
  api-reference/beta/api/connectedorganization-post.md
  api-reference/beta/api/connectedorganization-update.md
  api-reference/beta/resources/azureactivedirectorytenant.md
  api-reference/beta/resources/connectedorganization.md
  api-reference/beta/resources/connectedorganizationmembers.md
  api-reference/beta/resources/domainidentitysource.md
  api-reference/beta/resources/entitlementmanagement-root.md
  api-reference/beta/resources/externaldomainfederation.md
  api-reference/beta/resources/identitysource.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: area: azure/AAD, changelog, ready to merge

#8786 eDiscovery Graph API docs - phase 1
  api-reference/beta/api/ediscoverycase-delete.md
  api-reference/beta/api/ediscoverycase-get.md
  api-reference/beta/api/ediscoverycase-list.md
  api-reference/beta/api/ediscoverycase-post.md
  api-reference/beta/api/ediscoverycase-update.md
  api-reference/beta/api/reviewset-get.md
  api-reference/beta/api/reviewset-list.md
  api-reference/beta/api/reviewset-post.md
  api-reference/beta/api/reviewsetquery-delete.md
  api-reference/beta/api/reviewsetquery-get.md
  api-reference/beta/api/reviewsetquery-list.md
  api-reference/beta/api/reviewsetquery-post.md
  api-reference/beta/api/reviewsetquery-update.md
  api-reference/beta/resources/complianceapioverview.md
  api-reference/beta/resources/ediscoveryapioverview.md
  api-reference/beta/resources/ediscoverycase.md
  api-reference/beta/resources/reviewset.md
  api-reference/beta/resources/reviewsetquery.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: awaiting internal response, changelog, ready to merge

#9289 Added remark to include items from external tenants
  api-reference/beta/api/drive-sharedwithme.md
  api-reference/v1.0/api/drive-sharedwithme.md
Labels: ready to merge

#9290 - adds token validation before running step
  .github/label-commenter-config.yml
  .github/workflows/conflicting-pr-comment.yml
  .github/workflows/conflicting-pr-label.yml
Labels: do not merge

#9302 - worksaround publishing issue for workflow
  .github/workflows/conflicting-pr-label.yml
Labels: ready to merge

#9305 - removes clean comment to avoid spam
  .github/workflows/conflicting-pr-label.yml
Labels: ready to merge

#9301 Removed s from mis-spelled word
  api-reference/beta/api/drive-sharedwithme.md
  api-reference/v1.0/api/drive-sharedwithme.md
Labels: ready to merge

#9310 Generalized note about $filter support for Directory Objects
  concepts/query-parameters.md
Labels: ready to merge

#9292 toc restructure 2
  api-reference/beta/resources/azure-ad-auditlog-overview.md
  api-reference/beta/resources/report-identity-access.md
  api-reference/beta/resources/security-api-overview.md
  api-reference/beta/toc.yml
  api-reference/v1.0/resources/azure-ad-auditlog-overview.md
  api-reference/v1.0/resources/security-api-overview.md
  api-reference/v1.0/toc.yml
  concepts/reportroot-concept-overview.md
Labels: area: azure/AAD, ready to merge

#8943 Delegated webhooks
  api-reference/beta/api/subscription-post-subscriptions.md
  concepts/changelog.md
Labels: area: teams, ready to merge

#9010 bugfix/presence-webhook-miss
  api-reference/beta/api/subscription-delete.md
  api-reference/beta/api/subscription-get.md
  api-reference/beta/api/subscription-post-subscriptions.md
  api-reference/beta/api/subscription-update.md
  api-reference/beta/resources/subscription.md
  concepts/webhooks-with-resource-data.md
  concepts/webhooks.md
Labels: area: cloud communications, area: webhooks, ready to merge

#9002 TaxonomyAPIs new branch(07-08)
  api-reference/beta/api/termstore-group-delete.md
  api-reference/beta/api/termstore-group-list-sets.md
  api-reference/beta/api/termstore-group-post.md
  api-reference/beta/api/termstore-list-groups.md
  api-reference/beta/api/termstore-relation-post.md
  api-reference/beta/api/termstore-set-delete.md
  api-reference/beta/api/termstore-set-get.md
  api-reference/beta/api/termstore-set-post.md
  api-reference/beta/api/termstore-set-update.md
  api-reference/beta/api/termstore-store-get-group.md
  api-reference/beta/api/termstore-store-get.md
  api-reference/beta/api/termstore-store-update.md
  api-reference/beta/api/termstore-term-delete.md
  api-reference/beta/api/termstore-term-get.md
  api-reference/beta/api/termstore-term-list-children.md
  api-reference/beta/api/termstore-term-list-relations.md
  api-reference/beta/api/termstore-term-post.md
  api-reference/beta/api/termstore-term-update.md
  api-reference/beta/resources/enums-termstore.md
  api-reference/beta/resources/termstore-group.md
  api-reference/beta/resources/termstore-localizeddescription.md
  api-reference/beta/resources/termstore-localizedlabel.md
  api-reference/beta/resources/termstore-localizedname.md
  api-reference/beta/resources/termstore-relation.md
  api-reference/beta/resources/termstore-set.md
  api-reference/beta/resources/termstore-store.md
  api-reference/beta/resources/termstore-term.md
  api-reference/beta/toc.yml
  concepts/changelog.md
  concepts/permissions-reference.md
Labels: ready to merge

#6063 group isAssignableRole property
  api-reference/beta/api/group-get.md
  api-reference/beta/api/group-getmemberobjects.md
  api-reference/beta/api/group-list.md
  api-reference/beta/api/group-post-groups.md
  api-reference/beta/resources/group.md
  concepts/changelog.md
Labels: area: azure/AAD, ready to merge
