Repository microsoftgraph/microsoft-graph-docs, pull requests merged in 2020-10, with the labels that each got.

#10096 Accessreviewupdate1
  api-reference/beta/resources/accessreview.md
  api-reference/beta/resources/accessreviewrecurrencesettings.md
  api-reference/beta/resources/accessreviewsettings.md
  api-reference/beta/resources/autoreviewsettings.md
  api-reference/beta/resources/programcontrol.md
  api-reference/beta/resources/programresource.md
Labels: area: azure/AAD, internal, ready to merge

#10115 Remove trailing "." from permissions in tables
  api-reference/beta/api/conversationmember-update.md
  api-reference/beta/api/informationprotection-list-threatassessmentrequests.md
  api-reference/beta/api/informationprotection-post-threatassessmentrequests.md
  api-reference/beta/api/place-update.md
  api-reference/beta/api/securescorecontrolprofiles-list.md
  api-reference/beta/api/securescorecontrolprofiles-update.md
  api-reference/beta/api/securescores-list.md
  api-reference/beta/api/threatassessmentrequest-get.md
  api-reference/beta/api/trustframeworkkeyset-getactivekey.md
  api-reference/v1.0/api/group-checkmembergroups.md
  api-reference/v1.0/api/informationprotection-list-threatassessmentrequests.md
  api-reference/v1.0/api/informationprotection-post-threatassessmentrequests.md
  api-reference/v1.0/api/place-update.md
  api-reference/v1.0/api/securescorecontrolprofile-update.md
  api-reference/v1.0/api/security-list-securescorecontrolprofiles.md
  api-reference/v1.0/api/security-list-securescores.md
  api-reference/v1.0/api/threatassessmentrequest-get.md
Labels: internal, ready to merge

#10116 Fix casing of @odata.nextLink in callRecord docs
  api-reference/beta/api/callrecords-callrecord-get.md
  api-reference/beta/api/callrecords-session-list.md
  api-reference/v1.0/api/callrecords-callrecord-get.md
  api-reference/v1.0/api/callrecords-session-list.md
Labels: area: cloud communications, internal, ready to merge

#10119 fix for git issue 9966
  api-reference/v1.0/resources/group.md
  concepts/changelog.md
Labels: area: azure/AAD, internal, ready to merge

#10120 Adding staggering information for parity with V1
  api-reference/beta/api/team-post-members.md
Labels: content review, external, ready to merge

#10123 included both http requests
  api-reference/beta/api/conversationmember-update.md
Labels: content review, external, ready to merge

#10124 including both potential HTTP requests
  api-reference/beta/api/team-delete-members.md
Labels: content review, external, ready to merge

#10125 Including both HTTP Requests
  api-reference/v1.0/api/team-delete-members.md
Labels: content review, external, ready to merge

#10126 Including both HTTP requests
  api-reference/beta/api/team-post-members.md
Labels: content review, external, ready to merge

#10127 Including both HTTP Requests
  api-reference/v1.0/api/team-post-members.md
Labels: content review, external, ready to merge

#10128 Include both http requests
  api-reference/beta/api/team-list-members.md
Labels: content review, external, ready to merge

#10129 Including both http requests
  api-reference/v1.0/api/team-list-members.md
Labels: content review, external, ready to merge

#10110 Update todotasklist-delta.md
  api-reference/beta/api/todotasklist-delta.md
Labels: external

#10111 Update plannerexternalreferences.md
  api-reference/beta/resources/plannerexternalreferences.md
Labels: external

#10112 Update plannerexternalreferences.md
  api-reference/v1.0/resources/plannerexternalreferences.md
Labels: external

#10131 Merge to publish.
  api-reference/beta/api/callrecords-callrecord-get.md
  api-reference/beta/api/callrecords-session-list.md
  api-reference/beta/api/conversationmember-update.md
  api-reference/beta/api/informationprotection-list-threatassessmentrequests.md
  api-reference/beta/api/informationprotection-post-threatassessmentrequests.md
  api-reference/beta/api/place-update.md
  api-reference/beta/api/securescorecontrolprofiles-list.md
  api-reference/beta/api/securescorecontrolprofiles-update.md
  api-reference/beta/api/securescores-list.md
  api-reference/beta/api/team-delete-members.md
  api-reference/beta/api/team-list-members.md
  api-reference/beta/api/team-post-members.md
  api-reference/beta/api/threatassessmentrequest-get.md
  api-reference/beta/api/todotasklist-delta.md
  api-reference/beta/api/trustframeworkkeyset-getactivekey.md
  api-reference/beta/resources/accessreview.md
  api-reference/beta/resources/accessreviewrecurrencesettings.md
  api-reference/beta/resources/accessreviewsettings.md
  api-reference/beta/resources/autoreviewsettings.md
  api-reference/beta/resources/plannerexternalreferences.md
  api-reference/beta/resources/programcontrol.md
  api-reference/beta/resources/programresource.md
  api-reference/v1.0/api/callrecords-callrecord-get.md
  api-reference/v1.0/api/callrecords-session-list.md
  api-reference/v1.0/api/group-checkmembergroups.md
  api-reference/v1.0/api/informationprotection-list-threatassessmentrequests.md
  api-reference/v1.0/api/informationprotection-post-threatassessmentrequests.md
  api-reference/v1.0/api/place-update.md
  api-reference/v1.0/api/securescorecontrolprofile-update.md
  api-reference/v1.0/api/security-list-securescorecontrolprofiles.md
  api-reference/v1.0/api/security-list-securescores.md
  api-reference/v1.0/api/team-delete-members.md
  api-reference/v1.0/api/team-list-members.md
  api-reference/v1.0/api/team-post-members.md
  api-reference/v1.0/api/threatassessmentrequest-get.md
  api-reference/v1.0/resources/group.md
  api-reference/v1.0/resources/plannerexternalreferences.md
  concepts/changelog.md
Labels: internal

#10144 Fix typo `acquistion`
  concepts/migrate-azure-ad-graph-authentication-library.md
Labels: external

#10143 Clarify use of 'Application' allowedMemberType value
  api-reference/beta/resources/approle.md
  api-reference/v1.0/resources/approle.md
Labels: internal, ready to merge

#10141 Remove duplicate channel permissions
  concepts/permissions-reference.md
Labels: internal, ready to merge

#10139 Update todotasklist-list-tasks.md
  api-reference/beta/api/todotasklist-list-tasks.md
Labels: external

#10140 Add notes on directory roles granted for some app-only permissions
  concepts/permissions-reference.md
Labels: internal, ready to merge

#10130 fix for git issue 9798
  api-reference/beta/api/group-delete-members.md
  api-reference/v1.0/api/group-delete-members.md
Labels: area: azure/AAD, internal, ready to merge

#10146 Merge to publish.
  api-reference/beta/api/group-delete-members.md
  api-reference/beta/api/todotasklist-list-tasks.md
  api-reference/beta/resources/approle.md
  api-reference/v1.0/api/group-delete-members.md
  api-reference/v1.0/resources/approle.md
  concepts/migrate-azure-ad-graph-authentication-library.md
  concepts/permissions-reference.md
Labels: internal

#10106 Update to v1.0 because some API already have v1.0
  concepts/application-saml-sso-configure-api.md
Labels: area: azure/AAD, external, ready to merge, review requested

#9911 Rajeshwari 1149658gaprivatechannelapi
  api-reference/v1.0/api/channel-delete.md
  api-reference/v1.0/api/channel-get.md
  api-reference/v1.0/api/channel-list.md
  api-reference/v1.0/api/channel-patch.md
  api-reference/v1.0/api/channel-post-messagereply.md
  api-reference/v1.0/api/channel-post-messages.md
  api-reference/v1.0/api/channel-post.md
  api-reference/v1.0/resources/channel.md
Labels: internal, ready to merge

#10172 Update todotask-delta.md
  api-reference/beta/api/todotask-delta.md
Labels: external

#10171 Add missing permission reference for Policy.ReadWrite.Authorization
  concepts/permissions-reference.md
Labels: internal, ready to merge

#10155 Fixing inaccuracy that customer was confused by
  concepts/whats-new-overview.md
Labels: area: teams, internal, ready to merge

#10156 Updated $filter general explanation
  concepts/query-parameters.md
Labels: internal, ready to merge

#10147 Update todotasklist-post-tasks.md
  api-reference/beta/api/todotasklist-post-tasks.md
Labels: external

#10148 Update todotask-update.md
  api-reference/beta/api/todotask-update.md
Labels: external

#10135 Fix Wrong Input Example when the Claim Configuration
  concepts/application-saml-sso-configure-api.md
Labels: external

#10186 fix for git issue 9503
  api-reference/beta/api/group-list.md
Labels: area: azure/AAD, internal, ready to merge

#10160 Added allowInvitesFrom to authorizationPolicy
  api-reference/beta/resources/authorizationpolicy.md
  concepts/changelog.md
Labels: area: azure/AAD, internal, ready to merge

#10049 Removed concept topic from reference TOC and added as a See also.
  api-reference/beta/resources/team.md
  api-reference/beta/toc.yml
  api-reference/v1.0/resources/team.md
  api-reference/v1.0/toc.yml
Labels: internal, ready to merge

#9874 Updated from beta to v1.0
  api-reference/v1.0/api/team-post.md
Labels: internal, ready to merge

#10163 Fix tags for some titles
  concepts/sdks/choose-authentication-providers.md
Labels: external

#10188 Merge to publish.
  api-reference/beta/api/group-list.md
  api-reference/beta/api/todotask-delta.md
  api-reference/beta/api/todotask-update.md
  api-reference/beta/api/todotasklist-post-tasks.md
  api-reference/beta/resources/authorizationpolicy.md
  api-reference/beta/resources/team.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/channel-delete.md
  api-reference/v1.0/api/channel-get.md
  api-reference/v1.0/api/channel-list.md
  api-reference/v1.0/api/channel-patch.md
  api-reference/v1.0/api/channel-post-messagereply.md
  api-reference/v1.0/api/channel-post-messages.md
  api-reference/v1.0/api/channel-post.md
  api-reference/v1.0/api/team-post.md
  api-reference/v1.0/resources/channel.md
  api-reference/v1.0/resources/team.md
  api-reference/v1.0/toc.yml
  concepts/application-saml-sso-configure-api.md
  concepts/changelog.md
  concepts/permissions-reference.md
  concepts/query-parameters.md
  concepts/sdks/choose-authentication-providers.md
  concepts/whats-new-overview.md
Labels: internal

#10189 Update linkedresource-update.md
  api-reference/beta/api/linkedresource-update.md
Labels: external

#10196 fix for git issue 8987
  api-reference/beta/api/group-post-groups.md
  api-reference/beta/resources/group.md
  api-reference/v1.0/api/group-post-groups.md
  api-reference/v1.0/resources/group.md
Labels: area: azure/AAD, internal, ready to merge

#10200 fix for git issue 8636
  api-reference/beta/api/group-post-owners.md
  api-reference/v1.0/api/group-post-owners.md
Labels: area: azure/AAD, internal, ready to merge

#10198 fix for git issue 8637
  api-reference/beta/api/group-post-members.md
  api-reference/v1.0/api/group-post-members.md
Labels: area: azure/AAD, internal, ready to merge

#10187 fix for git issue 9451
  api-reference/v1.0/api/groupsetting-post-groupsettings.md
Labels: area: azure/AAD, internal, ready to merge

#10153 Update listitem-get.md
  api-reference/v1.0/api/listitem-get.md
Labels: external, ready to merge

#10149 Update listitem-get.md
  api-reference/beta/api/listitem-get.md
Labels: external, ready to merge

#10078 Included staggering information for perf
  api-reference/beta/api/team-post-members.md
  api-reference/v1.0/api/team-post-members.md
Labels: external, ready to merge

#9994 2020-Microsoft-Search-API-Update
  api-reference/beta/resources/search-api-overview.md
  api-reference/beta/resources/searchbucket.md
  api-reference/beta/resources/searchrequest.md
  concepts/search-concept-aggregation.md
  concepts/search-concept-custom-types.md
  concepts/search-concept-files.md
  concepts/search-concept-overview.md
Labels: internal, ready to merge

#10218 fix for git issue 8265
  api-reference/beta/api/group-post-conversations.md
  api-reference/v1.0/api/group-post-conversations.md
Labels: area: azure/AAD, internal, ready to merge

#10213 Fix typos in permissions names for the setDeviceName action
  api-reference/beta/api/intune-devices-manageddevice-setdevicename.md
Labels: external

#10209 Update search-api-overview.md
  api-reference/beta/resources/search-api-overview.md
Labels: external

#10212 Add preserve-view=true to versioned links in changelog
  concepts/changelog.md
Labels: content review, internal

#10222 Revert "Add preserve-view=true to versioned links in changelog"
  concepts/changelog.md
Labels: internal

#10223 Merge to publish.
  api-reference/beta/api/group-post-conversations.md
  api-reference/beta/api/intune-devices-manageddevice-setdevicename.md
  api-reference/beta/resources/search-api-overview.md
  api-reference/v1.0/api/group-post-conversations.md
Labels: internal

#10225 Fix link validation errors.
  api-reference/beta/config/link-validation-config.json
  api-reference/v1.0/config/link-validation-config.json
Labels: internal

#10226 Fix link validation errors.
  api-reference/beta/config/link-validation-config.json
  api-reference/v1.0/config/link-validation-config.json
Labels: internal

#10237 Updates definition.
  concepts/application-saml-sso-configure-api.md
Labels: internal

#10229 Update indexing-api-overview.md
  api-reference/beta/resources/indexing-api-overview.md
Labels: external

#10228 Update search-query.md
  api-reference/beta/api/search-query.md
Labels: external

#10211 Adds missing docs for permissionGrantPolicyIdsAssignedToDefaultUserRole
  api-reference/beta/api/authorizationpolicy-get.md
  api-reference/beta/api/authorizationpolicy-update.md
  api-reference/beta/resources/authorizationpolicy.md
  changelog/Microsoft.DirectoryServices.json
  concepts/changelog.md
Labels: internal, ready to merge

#10239 Move 'Role Management' under 'Directory Management'
  api-reference/beta/toc.yml
Labels: external

#10219 fix for git issue 6879
  api-reference/beta/resources/group.md
  api-reference/beta/toc.yml
  api-reference/v1.0/resources/group.md
  api-reference/v1.0/toc.yml
Labels: area: azure/AAD, internal, ready to merge

#9033 B2C authentication methods policy
  api-reference/beta/api/b2cauthenticationmethodspolicy-get.md
  api-reference/beta/api/b2cauthenticationmethodspolicy-update.md
  api-reference/beta/resources/b2cauthenticationmethodspolicy.md
  api-reference/beta/toc.yml
  changelog/Microsoft.DirectoryServices.json
  concepts/changelog.md
  concepts/permissions-reference.md
Labels: ready to merge

#9937 User flow doc file name and resource name fixes
  api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md
  api-reference/beta/api/b2cidentityuserflow-delete.md
  api-reference/beta/api/b2cidentityuserflow-get.md
  api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md
  api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md
  api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md
  api-reference/beta/api/b2xidentityuserflow-delete.md
  api-reference/beta/api/b2xidentityuserflow-get.md
  api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md
  api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md
  api-reference/beta/api/identitycontainer-list-b2cuserflows.md
  api-reference/beta/api/identitycontainer-list-b2xuserflows.md
  api-reference/beta/api/identitycontainer-post-b2cuserflows.md
  api-reference/beta/api/identitycontainer-post-b2xuserflows.md
  api-reference/beta/resources/b2cidentityuserflow.md
  api-reference/beta/resources/b2xidentityuserflow.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: ready to merge

#9870 Authentication Methods API pwdless refresh doc updates
  api-reference/beta/api/authentication-list-methods.md
  api-reference/beta/api/authentication-list-passwordmethods.md
  api-reference/beta/api/authentication-list-phonemethods.md
  api-reference/beta/api/authentication-post-phonemethods.md
  api-reference/beta/api/authenticationmethod-get.md
  api-reference/beta/api/authenticationoperation-get.md
  api-reference/beta/api/emailauthenticationmethod-delete.md
  api-reference/beta/api/emailauthenticationmethod-get.md
  api-reference/beta/api/emailauthenticationmethod-list.md
  api-reference/beta/api/emailauthenticationmethod-post.md
  api-reference/beta/api/emailauthenticationmethod-update.md
  api-reference/beta/api/fido2authenticationmethod-delete.md
  api-reference/beta/api/fido2authenticationmethod-get.md
  api-reference/beta/api/fido2authenticationmethod-list.md
  api-reference/beta/api/passwordauthenticationmethod-get.md
  api-reference/beta/api/passwordauthenticationmethod-resetpassword.md
  api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-delete.md
  api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-get.md
  api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-list.md
  api-reference/beta/api/phoneauthenticationmethod-delete.md
  api-reference/beta/api/phoneauthenticationmethod-disablesmssignin.md
  api-reference/beta/api/phoneauthenticationmethod-enablesmssignin.md
  api-reference/beta/api/phoneauthenticationmethod-get.md
  api-reference/beta/api/phoneauthenticationmethod-update.md
  api-reference/beta/includes/snippets/javascript/get-operation-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/passwordauthenticationmethod-resetpassword-adminprovided-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/passwordauthenticationmethod-resetpassword-systemgenerated-javascript-snippets.md
  api-reference/beta/includes/snippets/objc/get-operation-objc-snippets.md
  api-reference/beta/includes/snippets/objc/passwordauthenticationmethod-resetpassword-adminprovided-objc-snippets.md
  api-reference/beta/includes/snippets/objc/passwordauthenticationmethod-resetpassword-systemgenerated-objc-snippets.md
  api-reference/beta/resources/authenticationmethods-overview.md
  api-reference/beta/resources/emailauthenticationmethod.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/fido2authenticationmethod.md
  api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethod.md
  api-reference/beta/toc.yml
  changelog/Microsoft.DirectoryServices.json
  concepts/changelog.md
Labels: area: azure/AAD, internal, ready to merge

#9924 Authentication Methods Policies API doc updates
  api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md
  api-reference/beta/api/fido2authenticationmethodconfiguration-get.md
  api-reference/beta/api/fido2authenticationmethodconfiguration-update.md
  api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md
  api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md
  api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md
  api-reference/beta/resources/authenticationmethodconfiguration.md
  api-reference/beta/resources/authenticationmethodspolicies-overview.md
  api-reference/beta/resources/authenticationmethodtarget.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/fido2authenticationmethodconfiguration.md
  api-reference/beta/resources/fido2keyrestrictions.md
  api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md
  api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md
  api-reference/beta/toc.yml
  changelog/Microsoft.DirectoryServices.json
  concepts/changelog.md
  concepts/permissions-reference.md
Labels: area: azure/AAD, internal, ready to merge

#10249 Update group-delete-members.md (Issue 10247)
  api-reference/v1.0/api/group-delete-members.md
Labels: external

#10244 Update permissions-reference.md
  concepts/permissions-reference.md
  concepts/search-concept-files.md
Labels: internal, ready to merge

#10253 Merge to publish.
  api-reference/beta/api/authentication-list-methods.md
  api-reference/beta/api/authentication-list-passwordmethods.md
  api-reference/beta/api/authentication-list-phonemethods.md
  api-reference/beta/api/authentication-post-phonemethods.md
  api-reference/beta/api/authenticationmethod-get.md
  api-reference/beta/api/authenticationoperation-get.md
  api-reference/beta/api/emailauthenticationmethod-delete.md
  api-reference/beta/api/emailauthenticationmethod-get.md
  api-reference/beta/api/emailauthenticationmethod-list.md
  api-reference/beta/api/emailauthenticationmethod-post.md
  api-reference/beta/api/emailauthenticationmethod-update.md
  api-reference/beta/api/fido2authenticationmethod-delete.md
  api-reference/beta/api/fido2authenticationmethod-get.md
  api-reference/beta/api/fido2authenticationmethod-list.md
  api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md
  api-reference/beta/api/fido2authenticationmethodconfiguration-get.md
  api-reference/beta/api/fido2authenticationmethodconfiguration-update.md
  api-reference/beta/api/passwordauthenticationmethod-get.md
  api-reference/beta/api/passwordauthenticationmethod-resetpassword.md
  api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-delete.md
  api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-get.md
  api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-list.md
  api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md
  api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md
  api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md
  api-reference/beta/api/phoneauthenticationmethod-delete.md
  api-reference/beta/api/phoneauthenticationmethod-disablesmssignin.md
  api-reference/beta/api/phoneauthenticationmethod-enablesmssignin.md
  api-reference/beta/api/phoneauthenticationmethod-get.md
  api-reference/beta/api/phoneauthenticationmethod-update.md
  api-reference/beta/includes/snippets/javascript/get-operation-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/passwordauthenticationmethod-resetpassword-adminprovided-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/passwordauthenticationmethod-resetpassword-systemgenerated-javascript-snippets.md
  api-reference/beta/includes/snippets/objc/get-operation-objc-snippets.md
  api-reference/beta/includes/snippets/objc/passwordauthenticationmethod-resetpassword-adminprovided-objc-snippets.md
  api-reference/beta/includes/snippets/objc/passwordauthenticationmethod-resetpassword-systemgenerated-objc-snippets.md
  api-reference/beta/resources/authenticationmethodconfiguration.md
  api-reference/beta/resources/authenticationmethods-overview.md
  api-reference/beta/resources/authenticationmethodspolicies-overview.md
  api-reference/beta/resources/authenticationmethodtarget.md
  api-reference/beta/resources/emailauthenticationmethod.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/fido2authenticationmethod.md
  api-reference/beta/resources/fido2authenticationmethodconfiguration.md
  api-reference/beta/resources/fido2keyrestrictions.md
  api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethod.md
  api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md
  api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/group-delete-members.md
  changelog/Microsoft.DirectoryServices.json
  concepts/changelog.md
  concepts/permissions-reference.md
  concepts/search-concept-files.md
Labels: internal

#10269 PersonalMicrosoftAccount for signinaudience
  api-reference/beta/resources/application.md
  api-reference/v1.0/resources/application.md
Labels: internal, ready to merge

#10257 Fix typo
  api-reference/beta/api/unifiedroleassignmentmultiple-get.md
Labels: external

#10260 Update team-post.md
  api-reference/beta/api/team-post.md
Labels: external

#10262 Update team-post.md
  api-reference/v1.0/api/team-post.md
Labels: external

#10263 Update team-post.md
  api-reference/beta/api/team-post.md
Labels: external

#10270 fix for git issue 9654
  api-reference/beta/api/subscription-delete.md
  api-reference/v1.0/api/subscription-delete.md
Labels: area: azure/AAD, internal, ready to merge

#10275 Added archive file.
  concepts/changelog-archive.md
Labels: internal

#10183 Add docs for delegatedPermissionClassifications and permissionGrantPolicies
  api-reference/beta/api/permissiongrantpolicy-delete-excludes.md
  api-reference/beta/api/permissiongrantpolicy-delete-includes.md
  api-reference/beta/api/permissiongrantpolicy-delete.md
  api-reference/beta/api/permissiongrantpolicy-get.md
  api-reference/beta/api/permissiongrantpolicy-list-excludes.md
  api-reference/beta/api/permissiongrantpolicy-list-includes.md
  api-reference/beta/api/permissiongrantpolicy-list.md
  api-reference/beta/api/permissiongrantpolicy-post-excludes.md
  api-reference/beta/api/permissiongrantpolicy-post-includes.md
  api-reference/beta/api/permissiongrantpolicy-post-permissiongrantpolicies.md
  api-reference/beta/api/permissiongrantpolicy-update.md
  api-reference/beta/api/serviceprincipal-delete-delegatedpermissionclassifications.md
  api-reference/beta/api/serviceprincipal-list-delegatedpermissionclassifications.md
  api-reference/beta/api/serviceprincipal-post-delegatedpermissionclassifications.md
  api-reference/beta/resources/delegatedpermissionclassification.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/permissiongrantconditionset.md
  api-reference/beta/resources/permissiongrantpolicy.md
  api-reference/beta/resources/serviceprincipal.md
  api-reference/beta/toc.yml
  changelog/Microsoft.DirectoryServices.json
  concepts/changelog.md
  concepts/permissions-reference.md
Labels: internal, ready to merge

#10282 Add missing delegatedPermissionClassifications navigation
  api-reference/beta/resources/serviceprincipal.md
Labels: internal, ready to merge

#10168 Update document for GET online meeting by Join URL
  api-reference/beta/api/onlinemeeting-get.md
Labels: internal, ready to merge

#10278 Update fido2authenticationmethodconfiguration-get.md
  api-reference/beta/api/fido2authenticationmethodconfiguration-get.md
Labels: external

#10291 Summarized what's new in the last two weeks.
  changelog/Microsoft.DirectoryServices.json
  concepts/changelog.md
  concepts/permissions-reference.md
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: do not merge, internal

#10296 Refresh the what's new topic.
  changelog/Microsoft.DirectoryServices.json
  concepts/changelog.md
  concepts/permissions-reference.md
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: do not merge, internal

#10292 Update workbook-error-handling.md
  concepts/workbook-error-handling.md
Labels: internal, ready to merge

#10294 Auto-update throttling documentation
  concepts/throttling.md
  includes/throttling-Identity-and-access-audit-logs.md
Labels: area: throttling, internal, ready to merge

#9827 Adding verifiedPublisher to Application and ServicePrincipal
  api-reference/beta/api/application-setverifiedpublisher.md
  api-reference/beta/api/application-unsetverifiedpublisher.md
  api-reference/beta/resources/application.md
  api-reference/beta/resources/serviceprincipal.md
  api-reference/beta/resources/verifiedpublisher.md
  api-reference/v1.0/api/application-setverifiedpublisher.md
  api-reference/v1.0/api/application-unsetverifiedpublisher.md
  api-reference/v1.0/resources/application.md
  api-reference/v1.0/resources/serviceprincipal.md
  api-reference/v1.0/resources/verifiedpublisher.md
  concepts/changelog.md
Labels: area: azure/AAD, ready to merge

#10301 Merge to publish.
  api-reference/beta/api/application-setverifiedpublisher.md
  api-reference/beta/api/application-unsetverifiedpublisher.md
  api-reference/beta/resources/application.md
  api-reference/beta/resources/serviceprincipal.md
  api-reference/beta/resources/verifiedpublisher.md
  api-reference/v1.0/api/application-setverifiedpublisher.md
  api-reference/v1.0/api/application-unsetverifiedpublisher.md
  api-reference/v1.0/resources/application.md
  api-reference/v1.0/resources/serviceprincipal.md
  api-reference/v1.0/resources/verifiedpublisher.md
  concepts/changelog.md
  concepts/throttling.md
  concepts/workbook-error-handling.md
  includes/throttling-Identity-and-access-audit-logs.md
Labels: internal

#10298 Update call.md
  api-reference/v1.0/resources/call.md
Labels: external

#9940 Add Team.Create to supported permissions
  api-reference/beta/api/team-post.md
  api-reference/v1.0/api/team-post.md
  concepts/permissions-reference.md
Labels: area: teams, changes requested, ready to merge

#10305 Update ediscoveryapioverview.md
  api-reference/beta/resources/ediscoveryapioverview.md
Labels: external

#10306 Took down documents for GetMeetingByJoinWebUrl
  api-reference/beta/api/onlinemeeting-get.md
Labels: internal, ready to merge

#10307 Merge to publish.
  api-reference/beta/api/onlinemeeting-get.md
  api-reference/beta/api/team-post.md
  api-reference/beta/resources/ediscoveryapioverview.md
  api-reference/v1.0/api/team-post.md
  api-reference/v1.0/resources/call.md
  concepts/permissions-reference.md
Labels: internal

#10273 Fixed issues in TOC.
  api-reference/beta/toc.yml
Labels: awaiting internal response, internal

#10323 Update attachment.md
  api-reference/beta/resources/attachment.md
Labels: external

#10322 Update attachment.md
  api-reference/v1.0/resources/attachment.md
Labels: external

#9997 RevokeGrants
  api-reference/beta/api/permission-revokegrants.md
  api-reference/beta/resources/driveitem.md
  api-reference/beta/resources/permission.md
  api-reference/beta/toc.yml
  changelog/Microsoft.FileServices.json
  concepts/changelog.md
Labels: ready to merge

#9857 Updated Prefer header delimeter
  api-reference/beta/api/driveitem-delta.md
  api-reference/v1.0/api/driveitem-delta.md
Labels: changes requested, internal, ready to merge

#10325 Update application.md to add missing property to table
  api-reference/beta/resources/application.md
Labels: external

#10297 Updated example URL
  api-reference/beta/api/invitation-post.md
  api-reference/v1.0/api/invitation-post.md
Labels: internal

#10319 Update Directory Audit $filter Example to Reflect Valid Attribute
  api-reference/beta/api/directoryaudit-list.md
  api-reference/v1.0/api/directoryaudit-list.md
Labels: external

#10343 correcting typo "whether"
  api-reference/beta/resources/riskyuser.md
Labels: external

#10337 Update b2cauthenticationmethodspolicy.md
  api-reference/beta/resources/b2cauthenticationmethodspolicy.md
Labels: external

#10341 Update documentation owner for callrecord apis
  api-reference/beta/api/callrecords-callrecord-get.md
  api-reference/beta/api/callrecords-callrecord-getdirectroutingcalls.md
  api-reference/beta/api/callrecords-callrecord-getpstncalls.md
  api-reference/beta/api/callrecords-session-list.md
  api-reference/beta/resources/callrecords-api-overview.md
  api-reference/beta/resources/callrecords-callrecord.md
  api-reference/beta/resources/callrecords-clientuseragent.md
  api-reference/beta/resources/callrecords-deviceinfo.md
  api-reference/beta/resources/callrecords-directroutinglogrow.md
  api-reference/beta/resources/callrecords-endpoint.md
  api-reference/beta/resources/callrecords-failureinfo.md
  api-reference/beta/resources/callrecords-feedbacktokenset.md
  api-reference/beta/resources/callrecords-media.md
  api-reference/beta/resources/callrecords-mediastream.md
  api-reference/beta/resources/callrecords-networkinfo.md
  api-reference/beta/resources/callrecords-participantendpoint.md
  api-reference/beta/resources/callrecords-pstncalllogrow.md
  api-reference/beta/resources/callrecords-segment.md
  api-reference/beta/resources/callrecords-serviceendpoint.md
  api-reference/beta/resources/callrecords-serviceuseragent.md
  api-reference/beta/resources/callrecords-session.md
  api-reference/beta/resources/callrecords-useragent.md
  api-reference/beta/resources/callrecords-userfeedback.md
  api-reference/v1.0/resources/callrecords-api-overview.md
  api-reference/v1.0/resources/callrecords-callrecord.md
  api-reference/v1.0/resources/callrecords-clientuseragent.md
  api-reference/v1.0/resources/callrecords-deviceinfo.md
  api-reference/v1.0/resources/callrecords-endpoint.md
  api-reference/v1.0/resources/callrecords-failureinfo.md
  api-reference/v1.0/resources/callrecords-feedbacktokenset.md
  api-reference/v1.0/resources/callrecords-media.md
  api-reference/v1.0/resources/callrecords-mediastream.md
  api-reference/v1.0/resources/callrecords-networkinfo.md
  api-reference/v1.0/resources/callrecords-participantendpoint.md
  api-reference/v1.0/resources/callrecords-segment.md
  api-reference/v1.0/resources/callrecords-serviceendpoint.md
  api-reference/v1.0/resources/callrecords-serviceuseragent.md
  api-reference/v1.0/resources/callrecords-useragent.md
  api-reference/v1.0/resources/callrecords-userfeedback.md
  concepts/cloud-communications-callrecords.md
Labels: area: cloud communications, internal, ready to merge

#10342 Add a Github Action to create PRs for generated snippets
  .github/workflows/snippet-generation-pr.yml
Labels: internal, ready to merge

#10264 Update intune-graph-overview.md
  api-reference/beta/resources/intune-graph-overview.md
Labels: internal, ready to merge

#10347 Merge to publish.
  .github/workflows/snippet-generation-pr.yml
  api-reference/beta/api/callrecords-callrecord-get.md
  api-reference/beta/api/callrecords-callrecord-getdirectroutingcalls.md
  api-reference/beta/api/callrecords-callrecord-getpstncalls.md
  api-reference/beta/api/callrecords-session-list.md
  api-reference/beta/api/directoryaudit-list.md
  api-reference/beta/resources/b2cauthenticationmethodspolicy.md
  api-reference/beta/resources/callrecords-api-overview.md
  api-reference/beta/resources/callrecords-callrecord.md
  api-reference/beta/resources/callrecords-clientuseragent.md
  api-reference/beta/resources/callrecords-deviceinfo.md
  api-reference/beta/resources/callrecords-directroutinglogrow.md
  api-reference/beta/resources/callrecords-endpoint.md
  api-reference/beta/resources/callrecords-failureinfo.md
  api-reference/beta/resources/callrecords-feedbacktokenset.md
  api-reference/beta/resources/callrecords-media.md
  api-reference/beta/resources/callrecords-mediastream.md
  api-reference/beta/resources/callrecords-networkinfo.md
  api-reference/beta/resources/callrecords-participantendpoint.md
  api-reference/beta/resources/callrecords-pstncalllogrow.md
  api-reference/beta/resources/callrecords-segment.md
  api-reference/beta/resources/callrecords-serviceendpoint.md
  api-reference/beta/resources/callrecords-serviceuseragent.md
  api-reference/beta/resources/callrecords-session.md
  api-reference/beta/resources/callrecords-useragent.md
  api-reference/beta/resources/callrecords-userfeedback.md
  api-reference/beta/resources/intune-graph-overview.md
  api-reference/beta/resources/riskyuser.md
  api-reference/v1.0/api/directoryaudit-list.md
  api-reference/v1.0/resources/callrecords-api-overview.md
  api-reference/v1.0/resources/callrecords-callrecord.md
  api-reference/v1.0/resources/callrecords-clientuseragent.md
  api-reference/v1.0/resources/callrecords-deviceinfo.md
  api-reference/v1.0/resources/callrecords-endpoint.md
  api-reference/v1.0/resources/callrecords-failureinfo.md
  api-reference/v1.0/resources/callrecords-feedbacktokenset.md
  api-reference/v1.0/resources/callrecords-media.md
  api-reference/v1.0/resources/callrecords-mediastream.md
  api-reference/v1.0/resources/callrecords-networkinfo.md
  api-reference/v1.0/resources/callrecords-participantendpoint.md
  api-reference/v1.0/resources/callrecords-segment.md
  api-reference/v1.0/resources/callrecords-serviceendpoint.md
  api-reference/v1.0/resources/callrecords-serviceuseragent.md
  api-reference/v1.0/resources/callrecords-useragent.md
  api-reference/v1.0/resources/callrecords-userfeedback.md
  concepts/cloud-communications-callrecords.md
Labels: internal

#10349 Update teamstab.md
  api-reference/beta/resources/teamstab.md
Labels: external

#10362 fix for sit issue 6347
  api-reference/beta/resources/groups-overview.md
  api-reference/v1.0/resources/groups-overview.md
Labels: area: azure/AAD, internal, ready to merge

#10360 Added Blazor and Bot Framework tutorials
  concepts/toc.yml
  concepts/tutorials.yml
Labels: internal, ready to merge

#10357 fix: Invalid trailing comma in JSON
  api-reference/beta/resources/printdocument.md
Labels: external

#10351 [MVP3] 2020-Microsoft-Search-API-Update
  concepts/search-concept-files.md
Labels: internal, ready to merge

#10277 Backfilled documentation for meeting role
  api-reference/beta/api/application-post-onlinemeetings.md
  api-reference/beta/api/onlinemeeting-createorget.md
  api-reference/beta/api/onlinemeeting-get.md
  api-reference/beta/api/onlinemeeting-update.md
  api-reference/beta/resources/meetingparticipantinfo.md
  api-reference/beta/resources/onlinemeeting.md
  concepts/changelog.md
Labels: content review, internal, ready to merge

#10271 added priveleged access permissions
  api-reference/beta/api/governanceresource-get.md
  api-reference/beta/api/governanceresource-list.md
  api-reference/beta/api/governanceresource-register.md
  api-reference/beta/api/governanceroleassignment-export.md
  api-reference/beta/api/governanceroleassignment-get.md
  api-reference/beta/api/governanceroleassignment-list.md
  api-reference/beta/api/governanceroleassignmentrequest-cancel.md
  api-reference/beta/api/governanceroleassignmentrequest-get.md
  api-reference/beta/api/governanceroleassignmentrequest-list.md
  api-reference/beta/api/governanceroleassignmentrequest-post.md
  api-reference/beta/api/governanceroleassignmentrequest-update.md
  api-reference/beta/api/governanceroledefinition-get.md
  api-reference/beta/api/governanceroledefinition-list.md
  api-reference/beta/api/governancerolesetting-get.md
  api-reference/beta/api/governancerolesetting-list.md
  api-reference/beta/api/governancerolesetting-update.md
  concepts/permissions-reference.md
Labels: area: azure/AAD, internal, ready to merge

#9981 Added LCM user properties (v1.0 endpoint)
  api-reference/v1.0/resources/employeeorgdata.md
  api-reference/v1.0/resources/user.md
  concepts/changelog.md
Labels: area: azure/AAD, area: users, ready to merge

#9790 Added LCM user properties (beta endpoint)
  api-reference/beta/resources/employeeorgdata.md
  api-reference/beta/resources/user.md
Labels: area: azure/AAD, area: users, beta, ready to merge

#9967 Add AltID Login to HRD policy
  api-reference/beta/resources/homerealmdiscoverypolicy.md
  api-reference/v1.0/resources/homerealmdiscoverypolicy.md
  changelog/Manual.NonWorkloadChanges.json
  changelog/Microsoft.DirectoryServices.json
  concepts/changelog.md
Labels: changes requested, ready to merge

#9810 Conversationmember resource
  api-reference/beta/toc.yml
  api-reference/v1.0/api/conversationmember-add.md
  api-reference/v1.0/api/conversationmember-delete.md
  api-reference/v1.0/api/conversationmember-get.md
  api-reference/v1.0/api/conversationmember-list.md
  api-reference/v1.0/api/conversationmember-update.md
  api-reference/v1.0/resources/aaduserconversationmember.md
  api-reference/v1.0/resources/conversationmember.md
  api-reference/v1.0/toc.yml
  concepts/changelog.md
Labels: internal, ready to merge

#10377 fix for git issue 9273
  api-reference/beta/api/group-post-owners.md
  api-reference/v1.0/api/group-post-owners.md
Labels: area: azure/AAD, internal, ready to merge

#10376 Gitissue6481
  api-reference/beta/api/group-list-owners.md
  api-reference/v1.0/api/group-list-owners.md
Labels: area: azure/AAD, internal, ready to merge

#10366 Update opentypeextension.md
  api-reference/beta/resources/opentypeextension.md
Labels: external

#10365 Update opentypeextension.md
  api-reference/v1.0/resources/opentypeextension.md
Labels: external

#10336 Update intune-companyterms-termsandconditions-list.md
  api-reference/v1.0/api/intune-companyterms-termsandconditions-list.md
Labels: external

#10372 Convert changelog.md file to json files.
  changelog/Manual.NonWorkloadChanges.json
  changelog/Microsoft.AAD.Reporting.json
  changelog/Microsoft.Analytics.json
  changelog/Microsoft.DirectoryServices.json
  changelog/Microsoft.EducationAssignment.json
  changelog/Microsoft.Excel.json
  changelog/Microsoft.Exchange.json
  changelog/Microsoft.FileServices.json
  changelog/Microsoft.Intune.json
  changelog/Microsoft.NAV.json
  changelog/Microsoft.Office.Tasks.json
  changelog/Microsoft.OneNote.json
  changelog/Microsoft.Search.json
  changelog/Microsoft.SharePoint.json
  changelog/Microsoft.Skype.Calling.json
  changelog/Microsoft.SubscriptionServices.json
  changelog/Microsoft.Teams.Core.json
  changelog/Microsoft.ThreatAssessment.json
Labels: changes requested, external

#10387 Adds quotes and corrects return code.
  concepts/application-provisioning-configure-api.md
Labels: internal, ready to merge

#10383 Update device.md
  api-reference/v1.0/resources/device.md
Labels: external

#10384 Update device.md
  api-reference/beta/resources/device.md
Labels: external

#9748 User flow attributes doc creation
  api-reference/beta/api/identityuserflowattribute-delete.md
  api-reference/beta/api/identityuserflowattribute-get.md
  api-reference/beta/api/identityuserflowattribute-list.md
  api-reference/beta/api/identityuserflowattribute-post.md
  api-reference/beta/api/identityuserflowattribute-update.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/identityuserflowattribute.md
  api-reference/beta/toc.yml
  changelog/Microsoft.DirectoryServices.json
  concepts/changelog.md
  concepts/permissions-reference.md
Labels: changes requested, ready to merge

#8965 feature/lifecycle-notifications-v1
  api-reference/beta/api/subscription-get.md
  api-reference/beta/api/subscription-list.md
  api-reference/beta/api/subscription-update.md
  api-reference/beta/resources/subscription.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/subscription-get.md
  api-reference/v1.0/api/subscription-list.md
  api-reference/v1.0/api/subscription-update.md
  api-reference/v1.0/resources/changenotification.md
  api-reference/v1.0/resources/subscription.md
  api-reference/v1.0/toc.yml
  concepts/changelog.md
  concepts/toc.yml
  concepts/webhooks-lifecycle.md
  concepts/webhooks.md
  concepts/whats-new-earlier.md
Labels: area: webhooks, ready to merge

#10393 Get onlinemeeting by joinurl
  api-reference/beta/api/onlinemeeting-get.md
  concepts/changelog.md
Labels: content review, internal, ready to merge

#10394 Push meeting option documents to v1.0
  api-reference/v1.0/api/onlinemeeting-get.md
  api-reference/v1.0/resources/lobbyBypassSettings.md
  api-reference/v1.0/resources/meetingparticipantinfo.md
  api-reference/v1.0/resources/onlinemeeting.md
  concepts/changelog.md
Labels: do not merge, internal

#10382 Update teamsapp-publish.md
  api-reference/beta/api/teamsapp-publish.md
Labels: external

#10395 Merge to publish.
  api-reference/beta/api/identityuserflowattribute-delete.md
  api-reference/beta/api/identityuserflowattribute-get.md
  api-reference/beta/api/identityuserflowattribute-list.md
  api-reference/beta/api/identityuserflowattribute-post.md
  api-reference/beta/api/identityuserflowattribute-update.md
  api-reference/beta/api/onlinemeeting-get.md
  api-reference/beta/api/subscription-get.md
  api-reference/beta/api/subscription-list.md
  api-reference/beta/api/subscription-update.md
  api-reference/beta/api/teamsapp-publish.md
  api-reference/beta/resources/device.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/identityuserflowattribute.md
  api-reference/beta/resources/subscription.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/onlinemeeting-get.md
  api-reference/v1.0/api/subscription-get.md
  api-reference/v1.0/api/subscription-list.md
  api-reference/v1.0/api/subscription-update.md
  api-reference/v1.0/resources/changenotification.md
  api-reference/v1.0/resources/device.md
  api-reference/v1.0/resources/lobbyBypassSettings.md
  api-reference/v1.0/resources/meetingparticipantinfo.md
  api-reference/v1.0/resources/onlinemeeting.md
  api-reference/v1.0/resources/subscription.md
  api-reference/v1.0/toc.yml
  changelog/Manual.NonWorkloadChanges.json
  changelog/Microsoft.AAD.Reporting.json
  changelog/Microsoft.Analytics.json
  changelog/Microsoft.DirectoryServices.json
  changelog/Microsoft.EducationAssignment.json
  changelog/Microsoft.Excel.json
  changelog/Microsoft.Exchange.json
  changelog/Microsoft.FileServices.json
  changelog/Microsoft.Intune.json
  changelog/Microsoft.NAV.json
  changelog/Microsoft.Office.Tasks.json
  changelog/Microsoft.OneNote.json
  changelog/Microsoft.Search.json
  changelog/Microsoft.SharePoint.json
  changelog/Microsoft.Skype.Calling.json
  changelog/Microsoft.SubscriptionServices.json
  changelog/Microsoft.Teams.Core.json
  changelog/Microsoft.ThreatAssessment.json
  concepts/application-provisioning-configure-api.md
  concepts/changelog.md
  concepts/permissions-reference.md
  concepts/toc.yml
  concepts/webhooks-lifecycle.md
  concepts/webhooks.md
  concepts/whats-new-earlier.md
Labels: internal

#10405 Revert "Push meeting option documents to v1.0"
  api-reference/v1.0/api/onlinemeeting-get.md
  api-reference/v1.0/resources/lobbyBypassSettings.md
  api-reference/v1.0/resources/meetingparticipantinfo.md
  api-reference/v1.0/resources/onlinemeeting.md
  concepts/changelog.md
Labels: content review, internal, ready to merge

#10404 Fix typo in file title for "File resource type"
  api-reference/v1.0/resources/file.md
Labels: external

#10398 Update aaduserconversationmember.md
  api-reference/v1.0/resources/aaduserconversationmember.md
Labels: external

#10397 Update aaduserconversationmember.md
  api-reference/beta/resources/aaduserconversationmember.md
Labels: external

#10406 Merge to publish.
  api-reference/beta/resources/aaduserconversationmember.md
  api-reference/v1.0/api/onlinemeeting-get.md
  api-reference/v1.0/resources/aaduserconversationmember.md
  api-reference/v1.0/resources/file.md
  api-reference/v1.0/resources/lobbyBypassSettings.md
  api-reference/v1.0/resources/meetingparticipantinfo.md
  api-reference/v1.0/resources/onlinemeeting.md
  concepts/changelog.md
Labels: internal

#10409 Fixed webLink description. Updated OWA branding.
  api-reference/beta/resources/eventmessage.md
  api-reference/beta/resources/eventmessagerequest.md
  api-reference/beta/resources/eventmessageresponse.md
  api-reference/beta/resources/message.md
  api-reference/v1.0/resources/eventmessage.md
  api-reference/v1.0/resources/eventmessagerequest.md
  api-reference/v1.0/resources/eventmessageresponse.md
  api-reference/v1.0/resources/message.md
  concepts/known-issues.md
Labels: internal

#10410 Merge to publish.
  api-reference/beta/resources/eventmessage.md
  api-reference/beta/resources/eventmessagerequest.md
  api-reference/beta/resources/eventmessageresponse.md
  api-reference/beta/resources/message.md
  api-reference/v1.0/resources/eventmessage.md
  api-reference/v1.0/resources/eventmessagerequest.md
  api-reference/v1.0/resources/eventmessageresponse.md
  api-reference/v1.0/resources/message.md
  concepts/known-issues.md
Labels: internal

#10411 Changed getSchedule owner to tariq-sharif.
  api-reference/beta/api/calendar-getschedule.md
  api-reference/v1.0/api/calendar-getschedule.md
  concepts/outlook-get-free-busy-schedule.md
Labels: do not merge, internal

#10420 Adding type to mgt-get
  concepts/toolkit/components/get.md
Labels: external

#10408 Add PHP beta example
  concepts/sdks/use-beta.md
Labels: internal, ready to merge

#10018 Small bug fixing in Permissions section
  api-reference/beta/api/iteminsightssettings-get.md
Labels: do not merge, internal

#10020 Small bug fixing in Permissions section
  api-reference/beta/api/iteminsightssettings-update.md
Labels: do not merge, internal

#10429 Update authorizationpolicy-update.md
  api-reference/beta/api/authorizationpolicy-update.md
Labels: external

#10413 Fix typo "use" -> "user"
  api-reference/v1.0/api/profilephoto-get.md
Labels: external

#10399 bugfix/lifecycle-notifications-adjustments
  concepts/changelog.md
  concepts/webhooks-lifecycle.md
Labels: area: webhooks, internal, ready to merge

#10433 Merge to publish.
  api-reference/beta/api/authorizationpolicy-update.md
  api-reference/beta/api/calendar-getschedule.md
  api-reference/beta/api/iteminsightssettings-get.md
  api-reference/beta/api/iteminsightssettings-update.md
  api-reference/v1.0/api/calendar-getschedule.md
  api-reference/v1.0/api/profilephoto-get.md
  concepts/changelog.md
  concepts/outlook-get-free-busy-schedule.md
  concepts/sdks/use-beta.md
  concepts/webhooks-lifecycle.md
Labels: internal

#10431 Address iframe issue for webLink and eventWebLink properties of event and reminder.
  api-reference/beta/resources/event.md
  api-reference/beta/resources/reminder.md
  api-reference/v1.0/resources/event.md
  api-reference/v1.0/resources/reminder.md
Labels: do not merge, internal

#10097 update import messages API
  api-reference/beta/api/accessreview-apply.md
  api-reference/beta/api/channel-completemigration.md
  api-reference/beta/api/channel-post-message.md
  api-reference/beta/api/channel-post-messagereply.md
  api-reference/beta/api/channel-post.md
  api-reference/beta/api/team-completemigration.md
  api-reference/beta/api/team-post.md
  api-reference/beta/resources/channel.md
  api-reference/beta/resources/team.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Teams.Core.json
  concepts/changelog.md
  concepts/permissions-reference.md
Labels: internal, ready to merge

#10445 fix for git issue 9869
  api-reference/beta/api/group-list-members.md
  api-reference/v1.0/api/group-list-members.md
Labels: area: azure/AAD, internal, ready to merge

#10443 Update subscription-post-subscriptions.md
  api-reference/beta/api/subscription-post-subscriptions.md
  api-reference/v1.0/api/subscription-post-subscriptions.md
Labels: internal, ready to merge
