Repository microsoftgraph/microsoft-graph-docs, pull requests merged in 2020-04, with the labels that each got.

#7529 Add network name in yammergroupactivitydetail API
  api-reference/beta/api/reportroot-getyammergroupsactivitydetail.md
  api-reference/beta/resources/yammergroupsactivitydetail.md
  concepts/changelog.md
Labels: ready to merge

#5388 Update instance annotation
  api-reference/beta/api/drive-post-bundles.md
Labels: awaiting internal response

#7573 Application owner change
  api-reference/beta/api/application-add-password.md
  api-reference/beta/api/application-addpassword.md
  api-reference/beta/api/application-delete-extensionproperty.md
  api-reference/beta/api/application-delete-owners.md
  api-reference/beta/api/application-delete-tokenlifetimepolicies.md
  api-reference/beta/api/application-delete.md
  api-reference/beta/api/application-delta.md
  api-reference/beta/api/application-get.md
  api-reference/beta/api/application-list-extensionproperty.md
  api-reference/beta/api/application-list-owners.md
  api-reference/beta/api/application-list-tokenlifetimepolicies.md
  api-reference/beta/api/application-list.md
  api-reference/beta/api/application-post-applications.md
  api-reference/beta/api/application-post-extensionproperty.md
  api-reference/beta/api/application-post-owners.md
  api-reference/beta/api/application-post-tokenlifetimepolicies.md
  api-reference/beta/api/application-removepassword.md
  api-reference/beta/api/application-update.md
  api-reference/beta/api/applicationsignindetailedsummary-get.md
  api-reference/beta/api/applicationsigninsummary-get.md
  api-reference/beta/resources/application.md
  api-reference/v1.0/api/application-addpassword.md
  api-reference/v1.0/api/application-delete-extensionproperty.md
  api-reference/v1.0/api/application-delete-owners.md
  api-reference/v1.0/api/application-delete.md
  api-reference/v1.0/api/application-get.md
  api-reference/v1.0/api/application-list-extensionproperty.md
  api-reference/v1.0/api/application-list-owners.md
  api-reference/v1.0/api/application-list.md
  api-reference/v1.0/api/application-post-applications.md
  api-reference/v1.0/api/application-post-extensionproperty.md
  api-reference/v1.0/api/application-post-owners.md
  api-reference/v1.0/api/application-removepassword.md
  api-reference/v1.0/api/application-update.md
  api-reference/v1.0/resources/application.md
Labels: ready to merge

#6718 Fixes to workbook paths and permissions
  api-reference/beta/api/nameditem-add.md
  api-reference/beta/api/nameditem-addformulalocal.md
  api-reference/beta/api/worksheet-list-names.md
  api-reference/v1.0/api/nameditem-add.md
  api-reference/v1.0/api/nameditem-addformulalocal.md
  api-reference/v1.0/api/worksheet-list-names.md
Labels: ready to merge

#7366 Adding docs for list webhooks in v1.0.
  api-reference/beta/api/subscriptions-socketio.md
  api-reference/beta/resources/driveitem.md
  api-reference/beta/resources/list.md
  api-reference/v1.0/api/subscription-delete.md
  api-reference/v1.0/api/subscription-get.md
  api-reference/v1.0/api/subscription-post-subscriptions.md
  api-reference/v1.0/api/subscription-update.md
  api-reference/v1.0/api/subscriptions-socketio.md
  api-reference/v1.0/resources/driveitem.md
  api-reference/v1.0/resources/list.md
  api-reference/v1.0/resources/subscription.md
  api-reference/v1.0/resources/webhooks.md
  concepts/changelog.md
Labels: ready to merge

#7365 Adding docs for Grant permissions v1.0.
  api-reference/beta/resources/permission.md
  api-reference/v1.0/api/permission-grant.md
  api-reference/v1.0/resources/permission.md
  api-reference/v1.0/toc.yml
  concepts/changelog.md
Labels: ready to merge

#7363 Adding docs for Followed v1.0.
  api-reference/beta/resources/driveitem.md
  api-reference/v1.0/api/drive-list-following.md
  api-reference/v1.0/api/driveitem-follow.md
  api-reference/v1.0/api/driveitem-unfollow.md
  api-reference/v1.0/resources/drive.md
  api-reference/v1.0/resources/driveitem.md
  api-reference/v1.0/toc.yml
  concepts/changelog.md
Labels: ready to merge

#7576 Making supported permissions more explicit
  api-reference/beta/resources/chat.md
Labels: area: teams, ready to merge

#7588 App role assignment owner change
  api-reference/beta/api/approleassignment-update.md
Labels: ready to merge

#7586 Access reviews owner change
  api-reference/beta/api/accessreview-addreviewer.md
  api-reference/beta/api/accessreview-apply.md
  api-reference/beta/api/accessreview-create.md
  api-reference/beta/api/accessreview-delete.md
  api-reference/beta/api/accessreview-get.md
  api-reference/beta/api/accessreview-listdecisions.md
  api-reference/beta/api/accessreview-listmydecisions.md
  api-reference/beta/api/accessreview-listreviewers.md
  api-reference/beta/api/accessreview-removereviewer.md
  api-reference/beta/api/accessreview-reset.md
  api-reference/beta/api/accessreview-sendreminder.md
  api-reference/beta/api/accessreview-stop.md
  api-reference/beta/api/accessreview-update.md
  api-reference/beta/api/businessflowtemplate-list.md
  api-reference/beta/api/program-create.md
  api-reference/beta/api/program-delete.md
  api-reference/beta/api/program-list.md
  api-reference/beta/api/program-listcontrols.md
  api-reference/beta/api/program-update.md
  api-reference/beta/api/programcontrol-create.md
  api-reference/beta/api/programcontrol-delete.md
  api-reference/beta/api/programcontrol-list.md
  api-reference/beta/api/programcontroltype-list.md
  api-reference/beta/resources/accessreview.md
  api-reference/beta/resources/businessflowtemplate.md
  api-reference/beta/resources/program.md
  api-reference/beta/resources/programcontrol.md
  api-reference/beta/resources/programcontroltype.md
Labels: ready to merge

#7590 Data policy operation owner change
  api-reference/beta/api/datapolicyoperation-get.md
  api-reference/beta/resources/datapolicyoperation.md
  api-reference/v1.0/api/datapolicyoperation-get.md
  api-reference/v1.0/resources/datapolicyoperation.md
Labels: ready to merge

#7607 Update tutorials landing page to card format
  concepts/tutorials.md
  concepts/tutorials.yml
Labels: ready to merge

#7608 Update per PR 5868.
  api-reference/beta/resources/usersettings.md
  api-reference/v1.0/resources/usersettings.md
Labels: ready to merge

#7595 Clarified actions of deleting an event that's a meeting organized by the specified user.
  api-reference/beta/api/event-delete.md
  api-reference/v1.0/api/event-delete.md
Labels: do not merge

#7526 Updated TOC in beta and content
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
  concepts/toc.yml
Labels: ready to merge

#7617 Extended deprecation timeline
  api-reference/beta/api/application-post-onlinemeetings.md
Labels: ready to merge

#6287 Update group-post-groups.md
  api-reference/v1.0/api/group-post-groups.md
Labels: external, ready to merge

#6696 Fix List method wording
  api-reference/v1.0/resources/intune-companyterms-termsandconditions.md
Labels: external, ready to merge

#6286 Update group-post-groups.md
  api-reference/beta/api/group-post-groups.md
Labels: external, ready to merge

#6775 Update group-post-groups.md
  api-reference/beta/api/group-post-groups.md
  api-reference/v1.0/api/group-post-groups.md
Labels: external, ready to merge

#7043 Corrected some inconsistencies
  api-reference/beta/api/application-delete-owners.md
Labels: external, ready to merge

#7611 mgt-person-card updated css custom properties
  concepts/toolkit/components/person-card.md
Labels: ready to merge

#7585 Updating the Teams how to doc
  concepts/images/teams-roster-sync.png
  concepts/teams-create-group-and-team.md
Labels: ready to merge

#7610 Add additional properties in person card component.
  concepts/toolkit/components/person-card.md
Labels: ready to merge

#7540 Update permissions-reference.md
  concepts/permissions-reference.md
Labels: ready to merge

#7581 Added information about using immutable ID when sending mail
  concepts/outlook-immutable-id.md
Labels: ready to merge

#7327 Rbacroles1
  api-reference/beta/api/rbacapplication-list-roleassignments.md
  api-reference/beta/api/rbacapplication-list-roledefinitions.md
  api-reference/beta/api/rbacapplication-post-roleassignments.md
  api-reference/beta/api/rbacapplication-post-roledefinitions.md
  api-reference/beta/api/unifiedroleassignment-get.md
  api-reference/beta/api/unifiedroleassignmentmultiple-delete.md
  api-reference/beta/api/unifiedroleassignmentmultiple-get.md
  api-reference/beta/api/unifiedroleassignmentmultiple-list.md
  api-reference/beta/api/unifiedroleassignmentmultiple-post.md
  api-reference/beta/api/unifiedroleassignmentmultiple-update.md
  api-reference/beta/api/unifiedroledefinition-get.md
  api-reference/beta/api/unifiedroledefinition-update.md
  api-reference/beta/resources/appscope.md
  api-reference/beta/resources/rbacapplicationmultiple.md
  api-reference/beta/resources/unifiedroleassignment.md
  api-reference/beta/resources/unifiedroleassignmentmultiple.md
  api-reference/beta/resources/unifiedroledefinition.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: ready to merge

#7656 Directory role owner change
  api-reference/beta/api/directoryrole-delete-member.md
  api-reference/beta/api/directoryrole-delta.md
  api-reference/beta/api/directoryrole-get.md
  api-reference/beta/api/directoryrole-list-members.md
  api-reference/beta/api/directoryrole-list-scopedadministrators.md
  api-reference/beta/api/directoryrole-list.md
  api-reference/beta/api/directoryrole-post-directoryroles.md
  api-reference/beta/api/directoryrole-post-members.md
  api-reference/beta/api/directoryroletemplate-get.md
  api-reference/beta/api/directoryroletemplate-list.md
  api-reference/beta/resources/directoryrole.md
  api-reference/beta/resources/directoryroletemplate.md
  api-reference/v1.0/api/directoryrole-delete-member.md
  api-reference/v1.0/api/directoryrole-delta.md
  api-reference/v1.0/api/directoryrole-get.md
  api-reference/v1.0/api/directoryrole-list-members.md
  api-reference/v1.0/api/directoryrole-list.md
  api-reference/v1.0/api/directoryrole-post-directoryroles.md
  api-reference/v1.0/api/directoryrole-post-members.md
  api-reference/v1.0/api/directoryroletemplate-get.md
  api-reference/v1.0/api/directoryroletemplate-list.md
  api-reference/v1.0/resources/directoryrole.md
  api-reference/v1.0/resources/directoryroletemplate.md
Labels: ready to merge

#7657 Directory setting owner change
  api-reference/beta/api/directorysetting-delete.md
  api-reference/beta/api/directorysetting-get.md
  api-reference/beta/api/directorysetting-list.md
  api-reference/beta/api/directorysetting-post-settings.md
  api-reference/beta/api/directorysetting-update.md
  api-reference/beta/api/directorysettingtemplate-get.md
  api-reference/beta/api/directorysettingtemplate-list.md
  api-reference/beta/resources/directorysetting.md
  api-reference/beta/resources/directorysettingtemplate.md
Labels: ready to merge

#7661 Identity protection owner change
  api-reference/beta/api/anonymousipriskevent-get.md
  api-reference/beta/api/anonymousipriskevent-list.md
  api-reference/beta/api/identityriskevent-get.md
  api-reference/beta/api/identityriskevent-list.md
  api-reference/beta/api/impossibletravelriskevent-get.md
  api-reference/beta/api/impossibletravelriskevent-list.md
  api-reference/beta/api/leakedcredentialsriskevent-get.md
  api-reference/beta/api/leakedcredentialsriskevent-list.md
  api-reference/beta/api/malwareriskevent-get.md
  api-reference/beta/api/malwareriskevent-list.md
  api-reference/beta/api/riskdetection-get.md
  api-reference/beta/api/riskdetection-list.md
  api-reference/beta/api/suspiciousipriskevent-get.md
  api-reference/beta/api/suspiciousipriskevent-list.md
  api-reference/beta/api/unfamiliarlocationriskevent-get.md
  api-reference/beta/api/unfamiliarlocationriskevent-list.md
  api-reference/beta/resources/identityprotection-root.md
  api-reference/beta/resources/identityriskevent.md
  api-reference/beta/resources/riskdetection.md
  api-reference/beta/resources/riskuseractivity.md
Labels: ready to merge

#7660 Feature rollout policy owner change
  api-reference/beta/api/directory-post-featurerolloutpolicies.md
  api-reference/beta/api/featurerolloutpolicy-delete-appliesto.md
  api-reference/beta/api/featurerolloutpolicy-delete.md
  api-reference/beta/api/featurerolloutpolicy-get.md
  api-reference/beta/api/featurerolloutpolicy-post-appliesto.md
  api-reference/beta/api/featurerolloutpolicy-update.md
  api-reference/beta/resources/featurerolloutpolicy.md
Labels: ready to merge

#7662 Fix the Property and Complex Type name so that the documents link works properly
  concepts/changelog.md
Labels: ready to merge

#7658 Domain owner change
  api-reference/beta/api/domain-delete.md
  api-reference/beta/api/domain-forcedelete.md
  api-reference/beta/api/domain-get.md
  api-reference/beta/api/domain-list-domainnamereferences.md
  api-reference/beta/api/domain-list-serviceconfigurationrecords.md
  api-reference/beta/api/domain-list-verificationdnsrecords.md
  api-reference/beta/api/domain-list.md
  api-reference/beta/api/domain-post-domains.md
  api-reference/beta/api/domain-update.md
  api-reference/beta/api/domain-verify.md
  api-reference/beta/resources/domain.md
  api-reference/beta/resources/domaindnscnamerecord.md
  api-reference/beta/resources/domaindnsmxrecord.md
  api-reference/beta/resources/domaindnsrecord.md
  api-reference/beta/resources/domaindnssrvrecord.md
  api-reference/beta/resources/domaindnstxtrecord.md
  api-reference/beta/resources/domaindnsunavailablerecord.md
  api-reference/beta/resources/domainstate.md
  api-reference/v1.0/api/domain-delete.md
  api-reference/v1.0/api/domain-forcedelete.md
  api-reference/v1.0/api/domain-get.md
  api-reference/v1.0/api/domain-list-domainnamereferences.md
  api-reference/v1.0/api/domain-list-serviceconfigurationrecords.md
  api-reference/v1.0/api/domain-list-verificationdnsrecords.md
  api-reference/v1.0/api/domain-list.md
  api-reference/v1.0/api/domain-post-domains.md
  api-reference/v1.0/api/domain-update.md
  api-reference/v1.0/api/domain-verify.md
  api-reference/v1.0/resources/domain.md
  api-reference/v1.0/resources/domaindnscnamerecord.md
  api-reference/v1.0/resources/domaindnsmxrecord.md
  api-reference/v1.0/resources/domaindnsrecord.md
  api-reference/v1.0/resources/domaindnssrvrecord.md
  api-reference/v1.0/resources/domaindnstxtrecord.md
  api-reference/v1.0/resources/domaindnsunavailablerecord.md
  api-reference/v1.0/resources/domainstate.md
Labels: ready to merge

#7655 Directory owner change
  api-reference/beta/api/directory-deleteditems-delete.md
  api-reference/beta/api/directory-deleteditems-get.md
  api-reference/beta/api/directory-deleteditems-list.md
  api-reference/beta/api/directory-deleteditems-restore.md
  api-reference/beta/api/directory-deleteditems-user-owned.md
  api-reference/beta/api/directory-list-featurerolloutpolicies.md
  api-reference/beta/api/directoryobject-checkmembergroups.md
  api-reference/beta/api/directoryobject-delete.md
  api-reference/beta/api/directoryobject-delta.md
  api-reference/beta/api/directoryobject-get.md
  api-reference/beta/api/directoryobject-getbyids.md
  api-reference/beta/api/directoryobject-getmembergroups.md
  api-reference/beta/api/directoryobject-getmemberobjects.md
  api-reference/beta/api/directoryobject-validateproperties.md
  api-reference/beta/resources/directory.md
  api-reference/beta/resources/directoryobject.md
  api-reference/v1.0/api/directory-deleteditems-delete.md
  api-reference/v1.0/api/directory-deleteditems-get.md
  api-reference/v1.0/api/directory-deleteditems-list.md
  api-reference/v1.0/api/directory-deleteditems-restore.md
  api-reference/v1.0/api/directory-deleteditems-user-owned.md
  api-reference/v1.0/api/directoryobject-checkmembergroups.md
  api-reference/v1.0/api/directoryobject-delete.md
  api-reference/v1.0/api/directoryobject-get.md
  api-reference/v1.0/api/directoryobject-getbyids.md
  api-reference/v1.0/api/directoryobject-getmembergroups.md
  api-reference/v1.0/api/directoryobject-getmemberobjects.md
  api-reference/v1.0/api/directoryobject-validateproperties.md
  api-reference/v1.0/resources/directory.md
  api-reference/v1.0/resources/directoryobject.md
Labels: ready to merge

#7645 [mgt] Adding new component "teams-channel-picker" to overview section
  concepts/toolkit/overview.md
Labels: ready to merge

#7654 Organization owner change
  api-reference/beta/api/certificatebasedauthconfiguration-delete.md
  api-reference/beta/api/certificatebasedauthconfiguration-get.md
  api-reference/beta/api/certificatebasedauthconfiguration-list.md
  api-reference/beta/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration.md
  api-reference/beta/api/organization-get.md
  api-reference/beta/api/organization-list.md
  api-reference/beta/api/organization-update.md
  api-reference/beta/resources/certificatebasedauthconfiguration.md
  api-reference/beta/resources/organization.md
  api-reference/v1.0/api/certificatebasedauthconfiguration-delete.md
  api-reference/v1.0/api/certificatebasedauthconfiguration-get.md
  api-reference/v1.0/api/certificatebasedauthconfiguration-list.md
  api-reference/v1.0/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration.md
  api-reference/v1.0/api/organization-get.md
  api-reference/v1.0/api/organization-list.md
  api-reference/v1.0/api/organization-update.md
  api-reference/v1.0/resources/certificatebasedauthconfiguration.md
  api-reference/v1.0/resources/organization.md
Labels: ready to merge

#7639 Auditlogs directory owner change
  api-reference/beta/api/directoryaudit-get.md
  api-reference/beta/api/directoryaudit-list.md
  api-reference/beta/resources/directoryaudit.md
  api-reference/v1.0/api/directoryaudit-get.md
  api-reference/v1.0/api/directoryaudit-list.md
  api-reference/v1.0/resources/directoryaudit.md
Labels: ready to merge

#7682 On-premises publishing owner change
  api-reference/beta/api/onpremisesagent-delete-agentgroups.md
  api-reference/beta/api/onpremisesagent-get.md
  api-reference/beta/api/onpremisesagent-list.md
  api-reference/beta/api/onpremisesagent-post-agentgroups.md
  api-reference/beta/api/onpremisesagentgroup-delete.md
  api-reference/beta/api/onpremisesagentgroup-get.md
  api-reference/beta/api/onpremisesagentgroup-list.md
  api-reference/beta/api/onpremisesagentgroup-post.md
  api-reference/beta/api/onpremisesagentgroup-update.md
  api-reference/beta/api/onpremisespublishingprofile-get.md
  api-reference/beta/api/onpremisespublishingprofile-update.md
  api-reference/beta/api/publishedresource-delete-agentgroups.md
  api-reference/beta/api/publishedresource-delete.md
  api-reference/beta/api/publishedresource-get.md
  api-reference/beta/api/publishedresource-list.md
  api-reference/beta/api/publishedresource-post-agentgroups.md
  api-reference/beta/api/publishedresource-post.md
  api-reference/beta/api/publishedresource-update.md
  api-reference/beta/resources/onpremisesagent.md
  api-reference/beta/resources/onpremisesagentgroup.md
  api-reference/beta/resources/onpremisesextensionattributes.md
  api-reference/beta/resources/onpremisesprovisioningerror.md
  api-reference/beta/resources/onpremisespublishing.md
  api-reference/beta/resources/onpremisespublishingprofile-root.md
  api-reference/beta/resources/onpremisespublishingprofile.md
  api-reference/beta/resources/publishedresource.md
Labels: ready to merge

#7679 Fix links
  concepts/tutorials.yml
Labels: ready to merge

#7678 Oauth2permissiongrant owner change
  api-reference/beta/api/oauth2permissiongrant-delete.md
  api-reference/beta/api/oauth2permissiongrant-get.md
  api-reference/beta/api/oauth2permissiongrant-list.md
  api-reference/beta/api/oauth2permissiongrant-update.md
  api-reference/beta/resources/oauth2permission.md
  api-reference/beta/resources/oauth2permissiongrant.md
Labels: ready to merge

#7677 Invitation owner change
  api-reference/beta/api/invitation-post.md
  api-reference/beta/resources/invitation.md
  api-reference/beta/resources/invitedusermessageinfo.md
  api-reference/v1.0/api/invitation-post.md
  api-reference/v1.0/resources/invitation.md
  api-reference/v1.0/resources/invitedusermessageinfo.md
Labels: ready to merge

#7676 - removes certificate thumbprint from sample response for rich notifi…
  concepts/webhooks-with-resource-data.md
Labels: ready to merge

#7674 Identity provider owner change
  api-reference/beta/api/identityprovider-delete.md
  api-reference/beta/api/identityprovider-get.md
  api-reference/beta/api/identityprovider-list.md
  api-reference/beta/api/identityprovider-post-identityproviders.md
  api-reference/beta/api/identityprovider-update.md
  api-reference/beta/resources/identityprovider.md
  api-reference/v1.0/api/identityprovider-delete.md
  api-reference/v1.0/api/identityprovider-get.md
  api-reference/v1.0/api/identityprovider-list.md
  api-reference/v1.0/api/identityprovider-post-identityproviders.md
  api-reference/v1.0/api/identityprovider-update.md
  api-reference/v1.0/resources/identityprovider.md
Labels: ready to merge

#7672 - updates links to webhooks samples
  concepts/webhooks.md
Labels: ready to merge

#7670 - adds a mention that the known issue also impacts groups
  concepts/known-issues.md
  concepts/webhooks.md
Labels: ready to merge

#7669 - adds missing chat message entity from teams to overview
  concepts/webhooks.md
Labels: ready to merge

#7696 Update group-post-groups.md
  api-reference/beta/api/group-post-groups.md
Labels: ready to merge

#7694 Update group-post-groups.md
  api-reference/v1.0/api/group-post-groups.md
Labels: ready to merge

#7693 Policy owner change
  api-reference/beta/api/activitybasedtimeoutpolicy-delete.md
  api-reference/beta/api/activitybasedtimeoutpolicy-get.md
  api-reference/beta/api/activitybasedtimeoutpolicy-list.md
  api-reference/beta/api/activitybasedtimeoutpolicy-post-activitybasedtimeoutpolicies.md
  api-reference/beta/api/activitybasedtimeoutpolicy-update.md
  api-reference/beta/api/claimsmappingpolicy-delete.md
  api-reference/beta/api/claimsmappingpolicy-get.md
  api-reference/beta/api/claimsmappingpolicy-list-appliesto.md
  api-reference/beta/api/claimsmappingpolicy-list.md
  api-reference/beta/api/claimsmappingpolicy-post-claimsmappingpolicies.md
  api-reference/beta/api/claimsmappingpolicy-update.md
  api-reference/beta/api/homerealmdiscoverypolicy-delete.md
  api-reference/beta/api/homerealmdiscoverypolicy-get.md
  api-reference/beta/api/homerealmdiscoverypolicy-list-appliesto.md
  api-reference/beta/api/homerealmdiscoverypolicy-list.md
  api-reference/beta/api/homerealmdiscoverypolicy-post-homerealmdiscoverypolicies.md
  api-reference/beta/api/homerealmdiscoverypolicy-update.md
  api-reference/beta/api/identitysecuritydefaultsenforcementpolicy-get.md
  api-reference/beta/api/identitysecuritydefaultsenforcementpolicy-update.md
  api-reference/beta/api/tokenissuancepolicy-delete.md
  api-reference/beta/api/tokenissuancepolicy-get.md
  api-reference/beta/api/tokenissuancepolicy-list-appliesto.md
  api-reference/beta/api/tokenissuancepolicy-list.md
  api-reference/beta/api/tokenissuancepolicy-post-tokenissuancepolicy.md
  api-reference/beta/api/tokenissuancepolicy-update.md
  api-reference/beta/api/tokenlifetimepolicy-delete.md
  api-reference/beta/api/tokenlifetimepolicy-get.md
  api-reference/beta/api/tokenlifetimepolicy-list-appliesto.md
  api-reference/beta/api/tokenlifetimepolicy-list.md
  api-reference/beta/api/tokenlifetimepolicy-post-tokenlifetimepolicies.md
  api-reference/beta/api/tokenlifetimepolicy-update.md
  api-reference/beta/resources/activitybasedtimeoutpolicy.md
  api-reference/beta/resources/claimsmappingpolicy.md
  api-reference/beta/resources/homerealmdiscoverypolicy.md
  api-reference/beta/resources/identitysecuritydefaultsenforcementpolicy.md
  api-reference/beta/resources/policy-overview.md
  api-reference/beta/resources/tokenissuancepolicy.md
  api-reference/beta/resources/tokenlifetimepolicy.md
Labels: ready to merge

#7689 Fix .NET core link
  concepts/tutorials.yml
Labels: ready to merge

#7704 Trust framework owner change
  api-reference/beta/api/identityuserflow-delete.md
  api-reference/beta/api/identityuserflow-get.md
  api-reference/beta/api/identityuserflow-list.md
  api-reference/beta/api/identityuserflow-post-userflows.md
  api-reference/beta/api/trustframework-list-keysets.md
  api-reference/beta/api/trustframework-list-trustframeworkpolicies.md
  api-reference/beta/api/trustframework-post-keysets.md
  api-reference/beta/api/trustframework-post-trustframeworkpolicy.md
  api-reference/beta/api/trustframework-put-trustframeworkpolicy.md
  api-reference/beta/api/trustframeworkkeyset-delete.md
  api-reference/beta/api/trustframeworkkeyset-generatekey.md
  api-reference/beta/api/trustframeworkkeyset-get.md
  api-reference/beta/api/trustframeworkkeyset-getactivekey.md
  api-reference/beta/api/trustframeworkkeyset-update.md
  api-reference/beta/api/trustframeworkkeyset-uploadcertificate.md
  api-reference/beta/api/trustframeworkkeyset-uploadpkcs12.md
  api-reference/beta/api/trustframeworkkeyset-uploadsecret.md
  api-reference/beta/api/trustframeworkpolicy-delete.md
  api-reference/beta/api/trustframeworkpolicy-get.md
  api-reference/beta/resources/identityuserflow.md
  api-reference/beta/resources/trustframeworkkeyset.md
  api-reference/beta/resources/trustframeworkpolicy.md
Labels: ready to merge

#7703 Agreements owner change
  api-reference/beta/api/agreement-delete.md
  api-reference/beta/api/agreement-get.md
  api-reference/beta/api/agreement-list.md
  api-reference/beta/api/agreement-post-agreements.md
  api-reference/beta/api/agreement-update.md
  api-reference/beta/resources/agreement.md
Labels: ready to merge

#7701 Synchronization owner change
  api-reference/beta/resources/synchronization-attributedefinition.md
  api-reference/beta/resources/synchronization-attributemapping.md
  api-reference/beta/resources/synchronization-attributemappingfunctionschema.md
  api-reference/beta/resources/synchronization-attributemappingparameterschema.md
  api-reference/beta/resources/synchronization-attributemappingsource.md
  api-reference/beta/resources/synchronization-configure-with-custom-target-attributes.md
  api-reference/beta/resources/synchronization-configure-with-directory-extension-attributes.md
  api-reference/beta/resources/synchronization-directorydefinition.md
  api-reference/beta/resources/synchronization-expressioninputobject.md
  api-reference/beta/resources/synchronization-filter.md
  api-reference/beta/resources/synchronization-filterclause.md
  api-reference/beta/resources/synchronization-filtergroup.md
  api-reference/beta/resources/synchronization-filteroperand.md
  api-reference/beta/resources/synchronization-filteroperatorschema.md
  api-reference/beta/resources/synchronization-metadataentry.md
  api-reference/beta/resources/synchronization-objectdefinition.md
  api-reference/beta/resources/synchronization-objectmapping.md
  api-reference/beta/resources/synchronization-overview.md
  api-reference/beta/resources/synchronization-parseexpressionresponse.md
  api-reference/beta/resources/synchronization-quarantine.md
  api-reference/beta/resources/synchronization-referencedobject.md
  api-reference/beta/resources/synchronization-secretkeystringvaluepair.md
  api-reference/beta/resources/synchronization-stringkeyattributemappingsourcevaluepair.md
  api-reference/beta/resources/synchronization-stringkeylongvaluepair.md
  api-reference/beta/resources/synchronization-stringkeyobjectvaluepair.md
  api-reference/beta/resources/synchronization-stringkeystringvaluepair.md
  api-reference/beta/resources/synchronization-synchronizationerror.md
  api-reference/beta/resources/synchronization-synchronizationjob.md
  api-reference/beta/resources/synchronization-synchronizationjobrestartcriteria.md
  api-reference/beta/resources/synchronization-synchronizationprogress.md
  api-reference/beta/resources/synchronization-synchronizationrule.md
  api-reference/beta/resources/synchronization-synchronizationschedule.md
  api-reference/beta/resources/synchronization-synchronizationschema.md
  api-reference/beta/resources/synchronization-synchronizationstatus.md
  api-reference/beta/resources/synchronization-synchronizationtaskexecution.md
  api-reference/beta/resources/synchronization-synchronizationtemplate.md
Labels: ready to merge

#7700 Service principal owner change
  api-reference/beta/api/serviceprincipal-addpassword.md
  api-reference/beta/api/serviceprincipal-checkmembergroups.md
  api-reference/beta/api/serviceprincipal-checkmemberobjects.md
  api-reference/beta/api/serviceprincipal-createpasswordsinglesignoncredentials.md
  api-reference/beta/api/serviceprincipal-delete-claimsmappingpolicies.md
  api-reference/beta/api/serviceprincipal-delete-homerealmdiscoverypolicies.md
  api-reference/beta/api/serviceprincipal-delete.md
  api-reference/beta/api/serviceprincipal-deletepasswordsinglesignoncredentials.md
  api-reference/beta/api/serviceprincipal-delta.md
  api-reference/beta/api/serviceprincipal-get.md
  api-reference/beta/api/serviceprincipal-getmembergroups.md
  api-reference/beta/api/serviceprincipal-getmemberobjects.md
  api-reference/beta/api/serviceprincipal-getpasswordsinglesignoncredentials.md
  api-reference/beta/api/serviceprincipal-list-approleassignments.md
  api-reference/beta/api/serviceprincipal-list-claimsmappingpolicies.md
  api-reference/beta/api/serviceprincipal-list-createdobjects.md
  api-reference/beta/api/serviceprincipal-list-homerealmdiscoverypolicies.md
  api-reference/beta/api/serviceprincipal-list-memberof.md
  api-reference/beta/api/serviceprincipal-list-oauth2permissiongrants.md
  api-reference/beta/api/serviceprincipal-list-ownedobjects.md
  api-reference/beta/api/serviceprincipal-list-owners.md
  api-reference/beta/api/serviceprincipal-list-transitivememberof.md
  api-reference/beta/api/serviceprincipal-list.md
  api-reference/beta/api/serviceprincipal-post-approleassignments.md
  api-reference/beta/api/serviceprincipal-post-claimsmappingpolicies.md
  api-reference/beta/api/serviceprincipal-post-homerealmdiscoverypolicies.md
  api-reference/beta/api/serviceprincipal-post-owners.md
  api-reference/beta/api/serviceprincipal-removepassword.md
  api-reference/beta/api/serviceprincipal-update.md
  api-reference/beta/api/serviceprincipal-updatepasswordsinglesignoncredentials.md
  api-reference/beta/resources/serviceprincipal.md
Labels: ready to merge

#7698 Role management owner change
  api-reference/beta/api/rbacapplication-list-roleassignments.md
  api-reference/beta/api/rbacapplication-list-roledefinitions.md
  api-reference/beta/api/rbacapplication-post-roleassignments.md
  api-reference/beta/api/rbacapplication-post-roledefinitions.md
  api-reference/beta/api/unifiedroleassignment-delete.md
  api-reference/beta/api/unifiedroleassignment-get.md
  api-reference/beta/api/unifiedroleassignmentmultiple-delete.md
  api-reference/beta/api/unifiedroleassignmentmultiple-get.md
  api-reference/beta/api/unifiedroleassignmentmultiple-list.md
  api-reference/beta/api/unifiedroleassignmentmultiple-post.md
  api-reference/beta/api/unifiedroleassignmentmultiple-update.md
  api-reference/beta/api/unifiedroledefinition-delete.md
  api-reference/beta/api/unifiedroledefinition-get.md
  api-reference/beta/api/unifiedroledefinition-update.md
  api-reference/beta/resources/rolemanagement.md
  api-reference/beta/resources/unifiedroleassignment.md
  api-reference/beta/resources/unifiedroleassignmentmultiple.md
  api-reference/beta/resources/unifiedroledefinition.md
Labels: ready to merge

#7697 PIM owner change
  api-reference/beta/api/governanceresource-get.md
  api-reference/beta/api/governanceresource-list.md
  api-reference/beta/api/governanceresource-register.md
  api-reference/beta/api/governanceroleassignment-export.md
  api-reference/beta/api/governanceroleassignment-get.md
  api-reference/beta/api/governanceroleassignment-list.md
  api-reference/beta/api/governanceroleassignmentrequest-cancel.md
  api-reference/beta/api/governanceroleassignmentrequest-get.md
  api-reference/beta/api/governanceroleassignmentrequest-list.md
  api-reference/beta/api/governanceroleassignmentrequest-post.md
  api-reference/beta/api/governanceroleassignmentrequest-update.md
  api-reference/beta/api/governanceroledefinition-get.md
  api-reference/beta/api/governanceroledefinition-list.md
  api-reference/beta/api/governancerolesetting-get.md
  api-reference/beta/api/governancerolesetting-list.md
  api-reference/beta/api/governancerolesetting-update.md
  api-reference/beta/api/privilegedapproval-get.md
  api-reference/beta/api/privilegedapproval-list.md
  api-reference/beta/api/privilegedapproval-myrequests.md
  api-reference/beta/api/privilegedapproval-post-privilegedapproval.md
  api-reference/beta/api/privilegedapproval-update.md
  api-reference/beta/api/privilegedoperationevent-list.md
  api-reference/beta/api/privilegedrole-get.md
  api-reference/beta/api/privilegedrole-list-assignments.md
  api-reference/beta/api/privilegedrole-list.md
  api-reference/beta/api/privilegedrole-selfactivate.md
  api-reference/beta/api/privilegedrole-selfdeactivate.md
  api-reference/beta/api/privilegedroleassignment-delete.md
  api-reference/beta/api/privilegedroleassignment-get.md
  api-reference/beta/api/privilegedroleassignment-list.md
  api-reference/beta/api/privilegedroleassignment-makeeligible.md
  api-reference/beta/api/privilegedroleassignment-makepermanent.md
  api-reference/beta/api/privilegedroleassignment-my.md
  api-reference/beta/api/privilegedroleassignment-post-privilegedroleassignments.md
  api-reference/beta/api/privilegedroleassignmentrequest-cancel.md
  api-reference/beta/api/privilegedroleassignmentrequest-list.md
  api-reference/beta/api/privilegedroleassignmentrequest-my.md
  api-reference/beta/api/privilegedroleassignmentrequest-post.md
  api-reference/beta/api/privilegedrolesettings-get.md
  api-reference/beta/api/privilegedrolesettings-update.md
  api-reference/beta/api/privilegedrolesummary-get.md
  api-reference/beta/resources/governanceresource.md
  api-reference/beta/resources/governanceroleassignment.md
  api-reference/beta/resources/governanceroleassignmentrequest.md
  api-reference/beta/resources/governanceroledefinition.md
  api-reference/beta/resources/governancerolesetting.md
  api-reference/beta/resources/privilegedapproval.md
  api-reference/beta/resources/privilegedidentitymanagement-directory.md
  api-reference/beta/resources/privilegedidentitymanagement-resources.md
  api-reference/beta/resources/privilegedidentitymanagement-root.md
  api-reference/beta/resources/privilegedoperationevent.md
  api-reference/beta/resources/privilegedrole.md
  api-reference/beta/resources/privilegedroleassignment.md
  api-reference/beta/resources/privilegedroleassignmentrequest.md
Labels: ready to merge

#7186 Adding Phase-I Calendar Properties to Graph v1.
  api-reference/v1.0/api/calendar-get.md
  api-reference/v1.0/api/calendar-post-events.md
  api-reference/v1.0/api/calendar-update.md
  api-reference/v1.0/api/calendarpermission-delete.md
  api-reference/v1.0/api/calendarpermission-get.md
  api-reference/v1.0/api/calendarpermission-update.md
  api-reference/v1.0/api/event-update.md
  api-reference/v1.0/api/user-get-mailboxsettings.md
  api-reference/v1.0/api/user-list-calendars.md
  api-reference/v1.0/api/user-post-calendars.md
  api-reference/v1.0/api/user-post-events.md
  api-reference/v1.0/api/user-update-mailboxsettings.md
  api-reference/v1.0/resources/calendar.md
  api-reference/v1.0/resources/calendarpermission.md
  api-reference/v1.0/resources/enums.md
  api-reference/v1.0/resources/event.md
  api-reference/v1.0/resources/mailboxsettings.md
  api-reference/v1.0/resources/onlinemeetinginfo.md
  api-reference/v1.0/toc.yml
  concepts/changelog.md
Labels: ready to merge

#7616 Adding identity and access policy objects to v1
  api-reference/beta/resources/aaduserconversationmember.md
  api-reference/beta/resources/accessaction.md
  api-reference/beta/resources/accesspackage.md
  api-reference/v1.0/api/activitybasedtimeoutpolicy-delete.md
  api-reference/v1.0/api/activitybasedtimeoutpolicy-get.md
  api-reference/v1.0/api/activitybasedtimeoutpolicy-list.md
  api-reference/v1.0/api/activitybasedtimeoutpolicy-post-activitybasedtimeoutpolicies.md
  api-reference/v1.0/api/activitybasedtimeoutpolicy-update.md
  api-reference/v1.0/api/application-delete-tokenissuancepolicies.md
  api-reference/v1.0/api/application-delete-tokenlifetimepolicies.md
  api-reference/v1.0/api/application-list-tokenissuancepolicies.md
  api-reference/v1.0/api/application-list-tokenlifetimepolicies.md
  api-reference/v1.0/api/application-post-tokenissuancepolicies.md
  api-reference/v1.0/api/application-post-tokenlifetimepolicies.md
  api-reference/v1.0/api/domain-forcedelete.md
  api-reference/v1.0/api/group-renew.md
  api-reference/v1.0/api/homerealmdiscoverypolicy-delete.md
  api-reference/v1.0/api/homerealmdiscoverypolicy-get.md
  api-reference/v1.0/api/homerealmdiscoverypolicy-list-appliesto.md
  api-reference/v1.0/api/homerealmdiscoverypolicy-list.md
  api-reference/v1.0/api/homerealmdiscoverypolicy-post-homerealmdiscoverypolicies.md
  api-reference/v1.0/api/homerealmdiscoverypolicy-update.md
  api-reference/v1.0/api/organization-list.md
  api-reference/v1.0/api/securescorecontrolprofile-get.md
  api-reference/v1.0/api/subscription-post-subscriptions.md
  api-reference/v1.0/api/tokenissuancepolicy-delete.md
  api-reference/v1.0/api/tokenissuancepolicy-get.md
  api-reference/v1.0/api/tokenissuancepolicy-list-appliesto.md
  api-reference/v1.0/api/tokenissuancepolicy-list.md
  api-reference/v1.0/api/tokenissuancepolicy-post-tokenissuancepolicy.md
  api-reference/v1.0/api/tokenissuancepolicy-update.md
  api-reference/v1.0/api/tokenlifetimepolicy-delete.md
  api-reference/v1.0/api/tokenlifetimepolicy-get.md
  api-reference/v1.0/api/tokenlifetimepolicy-list-appliesto.md
  api-reference/v1.0/api/tokenlifetimepolicy-list.md
  api-reference/v1.0/api/tokenlifetimepolicy-post-tokenlifetimepolicies.md
  api-reference/v1.0/api/tokenlifetimepolicy-update.md
  api-reference/v1.0/resources/activitybasedtimeoutpolicy.md
  api-reference/v1.0/resources/application.md
  api-reference/v1.0/resources/homerealmdiscoverypolicy.md
  api-reference/v1.0/resources/policy-overview.md
  api-reference/v1.0/resources/policybase.md
  api-reference/v1.0/resources/stspolicy.md
  api-reference/v1.0/resources/tokenissuancepolicy.md
  api-reference/v1.0/resources/tokenlifetimepolicy.md
  api-reference/v1.0/resources/urlassessmentrequest.md
  api-reference/v1.0/toc.yml
  concepts/changelog.md
Labels: area: azure/AAD, changes requested, ready to merge

#7692 - adds documentation for the administrative unit delta beta support
  api-reference/beta/api/administrativeunit-delta.md
  api-reference/beta/resources/administrativeunit.md
  api-reference/beta/toc.yml
  concepts/changelog.md
  concepts/delta-query-overview.md
Labels: ready to merge

#7728 Updated get list to include get list by title
  api-reference/beta/api/list-get.md
  api-reference/v1.0/api/list-get.md
Labels: ready to merge

#7730 Add MeetingCreated and MeetingInteracted properties to Reports API
  api-reference/beta/api/reportroot-getemailactivitycounts.md
  api-reference/beta/api/reportroot-getemailactivityusercounts.md
  api-reference/beta/api/reportroot-getemailactivityuserdetail.md
  concepts/changelog.md
Labels: ready to merge

#7740 Update people-picker to add selectionChanged event
  concepts/toolkit/components/people-picker.md
Labels: ready to merge

#7748 Added "Derived types" section
  api-reference/beta/resources/teleconferencedevicemediaquality.md
  api-reference/beta/resources/teleconferencedevicevideoquality.md
  api-reference/v1.0/resources/teleconferencedevicemediaquality.md
  api-reference/v1.0/resources/teleconferencedevicevideoquality.md
Labels: ready to merge

#7549 New riskeventtype field
  api-reference/beta/resources/riskdetection.md
  api-reference/beta/resources/riskuseractivity.md
Labels: ready to merge

#6524 new article for auth error resolution
  concepts/resolve-auth-errors.md
  concepts/toc.yml
Labels: ready to merge

#6924 revised API overview
  concepts/images/graph-explorer.PNG
  concepts/use-the-api.md
Labels: ready to merge

#7293 Clarify TiIndicator required & editable properties for each targetProduct
  api-reference/beta/resources/tiindicator.md
Labels: ready to merge

#7729 Update mgt-people new attribute.
  concepts/toolkit/components/people.md
Labels: do not merge

#7759 Update subscription-post-subscriptions.md
  api-reference/beta/api/subscription-post-subscriptions.md
  api-reference/v1.0/api/subscription-post-subscriptions.md
Labels: ready to merge

#7753 Update known-issues.md
  concepts/known-issues.md
Labels: ready to merge

#7691 - adds documentation for oAuth2 permission grant support
  api-reference/beta/api/oauth2permissiongrant-delta.md
  api-reference/beta/resources/oauth2permissiongrant.md
  api-reference/beta/toc.yml
  concepts/changelog.md
  concepts/delta-query-overview.md
Labels: ready to merge

#7780 Auditlog owner correction
  api-reference/beta/api/directoryaudit-get.md
  api-reference/beta/api/directoryaudit-list.md
  api-reference/beta/resources/directoryaudit.md
  api-reference/v1.0/api/directoryaudit-get.md
  api-reference/v1.0/api/directoryaudit-list.md
  api-reference/v1.0/resources/directoryaudit.md
Labels: ready to merge

#7785 Patch for an error in Public doc.
  api-reference/v1.0/resources/recordinginfo.md
Labels: review requested

#7783 - updates page owner
  concepts/query-parameters.md
Labels: ready to merge

#7781 - adds precision for duplicated notifications scenario
  concepts/known-issues.md
Labels: ready to merge

#7755 Updated Bookings verbiage content and removed small business refernecs
  concepts/booking-concept-overview.md
Labels: ready to merge

#4906 RelyingPartySummary API
  api-reference/beta/api/relyingpartydetailedsummary-list.md
  api-reference/beta/resources/relyingpartydetailedsummary.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: ready to merge

#7754 Updated verbiage for Bookings
  concepts/overview-major-services.md
Labels: ready to merge

#7690 adds documentation for application delta v1.0
  api-reference/beta/toc.yml
  api-reference/v1.0/api/application-delta.md
  api-reference/v1.0/resources/application.md
  api-reference/v1.0/toc.yml
  concepts/changelog.md
  concepts/delta-query-overview.md
Labels: ready to merge

#7560 Auth method docs
  api-reference/beta/api/authentication-list-methods.md
  api-reference/beta/api/authentication-list-passwordmethods.md
  api-reference/beta/api/authentication-list-phonemethods.md
  api-reference/beta/api/authentication-post-phonemethods.md
  api-reference/beta/api/authenticationmethod-get.md
  api-reference/beta/api/authenticationoperation-get.md
  api-reference/beta/api/passwordauthenticationmethod-get.md
  api-reference/beta/api/passwordauthenticationmethod-resetpassword.md
  api-reference/beta/api/phoneauthenticationmethod-delete.md
  api-reference/beta/api/phoneauthenticationmethod-disablesmssignin.md
  api-reference/beta/api/phoneauthenticationmethod-enablesmssignin.md
  api-reference/beta/api/phoneauthenticationmethod-get.md
  api-reference/beta/api/phoneauthenticationmethod-update.md
  api-reference/beta/resources/authenticationmethod.md
  api-reference/beta/resources/authenticationmethods-overview.md
  api-reference/beta/resources/passwordauthenticationmethod.md
  api-reference/beta/resources/phoneauthenticationmethod.md
  api-reference/beta/toc.yml
  concepts/changelog.md
  concepts/permissions-reference.md
Labels: area: authentication methods, ready to merge

#7417 Update group.md
  api-reference/beta/resources/group.md
Labels: ready to merge

#7418 Update changelog.md
  concepts/changelog.md
Labels: ready to merge

#7714 Update throttling.md
  concepts/throttling.md
Labels: ready to merge

#7565 Adding devices to ConditionalAccessConditionSet
  api-reference/beta/api/conditionalaccesspolicy-get.md
  api-reference/beta/api/conditionalaccessroot-list-policies.md
  api-reference/beta/api/conditionalaccessroot-post-policies.md
  api-reference/beta/resources/conditionalaccessconditionset.md
  api-reference/beta/resources/conditionalaccessdevices.md
  concepts/changelog.md
Labels: ready to merge

#7853 Replaced links to ASP.NET tutorial with Learn module link
  concepts/quick-start-faq.md
  concepts/toc.yml
  concepts/tutorials.yml
Labels: ready to merge

#7809 Update schema for content property in externalItem
  api-reference/beta/api/externalconnection-put-items.md
  api-reference/beta/api/externalitem-update.md
  api-reference/beta/resources/externalitem.md
  api-reference/beta/resources/externalitemcontent.md
Labels: ready to merge

#7850 Update serviceprincipal-update.md
  api-reference/beta/api/serviceprincipal-update.md
Labels: ready to merge

#7895 role assigment permission correction
  api-reference/beta/api/rbacapplication-post-roleassignments.md
  api-reference/beta/api/rbacapplication-post-roledefinitions.md
  api-reference/beta/api/unifiedroleassignment-delete.md
  api-reference/beta/api/unifiedroleassignmentmultiple-delete.md
  api-reference/beta/api/unifiedroleassignmentmultiple-post.md
  api-reference/beta/api/unifiedroledefinition-delete.md
  api-reference/beta/api/unifiedroledefinition-update.md
  api-reference/beta/toc.yml
Labels: ready to merge

#7899 Update MGT MsalProvider link to MSAL.js documentation
  concepts/toolkit/providers/msal.md
Labels: content review, ready to merge

#7898 Add example of authority with single-tenant apps
  concepts/toolkit/providers/msal.md
Labels: ready to merge

#7888 Add alternative API with application permissions
  api-reference/beta/api/application-post-onlinemeetings.md
Labels: ready to merge

#7887 allowNewTimeProposals not supported on v1.0
  api-reference/v1.0/api/user-post-events.md
Labels: ready to merge

#7880 Update stspolicy.md
  api-reference/v1.0/resources/stspolicy.md
Labels: ready to merge

#7886 Added missing option to fetch drive item
  api-reference/v1.0/api/driveitem-get.md
Labels: ready to merge

#7805 Adding allowedUsers and allowedGroups documentation for printerShare
  api-reference/beta/api/printershare-delete-allowedgroup.md
  api-reference/beta/api/printershare-delete-alloweduser.md
  api-reference/beta/api/printershare-list-allowedgroups.md
  api-reference/beta/api/printershare-list-allowedusers.md
  api-reference/beta/api/printershare-post-allowedgroups.md
  api-reference/beta/api/printershare-post-allowedusers.md
  api-reference/beta/resources/printershare.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: changes requested, ready to merge

#7917 fix for git issue 7282
  api-reference/v1.0/resources/objectidentity.md
Labels: ready to merge

#7918 - adds javascript sample for rich notifications decryption and valida…
  concepts/webhooks-with-resource-data.md
Labels: ready to merge

#7920 toolkit personImage prop
  concepts/toolkit/components/login.md
  concepts/toolkit/components/person.md
Labels: ready to merge

#7924 Universal Print - Adding missing "Optional query parameters" sections
  api-reference/beta/api/print-list-connectors.md
  api-reference/beta/api/print-list-printers.md
  api-reference/beta/api/print-list-printershares.md
  api-reference/beta/api/printer-list-allowedgroups.md
  api-reference/beta/api/printer-list-allowedusers.md
  api-reference/beta/api/printer-list-connectors.md
  api-reference/beta/api/printer-list-jobs.md
  api-reference/beta/api/printjob-get.md
  api-reference/beta/api/printusagesummarybyprinter-get.md
  api-reference/beta/api/printusagesummarybyuser-get.md
Labels: ready to merge

#7953 doc bug (directoryProvisioning -> provisioning)
  api-reference/beta/resources/azure-ad-auditlog-overview.md
Labels: ready to merge

#7954 [Universal Print] Adding printIdentity and printUserIdentity references
  api-reference/beta/api/printer-list-allowedgroups.md
  api-reference/beta/api/printer-list-allowedusers.md
  api-reference/beta/api/printershare-list-allowedgroups.md
  api-reference/beta/api/printershare-list-allowedusers.md
  api-reference/beta/resources/printer.md
  api-reference/beta/resources/printershare.md
  api-reference/beta/resources/printidentity.md
  api-reference/beta/resources/printuseridentity.md
  concepts/changelog.md
Labels: ready to merge

#7942 faq: Fix linking
  concepts/quick-start-faq.md
Labels: ready to merge

#7941 Update planner-post-tasks.md
  api-reference/beta/api/planner-post-tasks.md
Labels: ready to merge

#7940 Update planner-post-tasks.md
  api-reference/v1.0/api/planner-post-tasks.md
Labels: ready to merge

#7939 CELA Name and Number Changes
  api-reference/beta/api/onlinemeeting-createorget.md
  api-reference/beta/api/onlinemeeting-get.md
  api-reference/v1.0/api/onlinemeeting-get.md
Labels: ready to merge

#7873 - adds throttling information for subscriptions operations
  concepts/throttling.md
Labels: ready to merge

#7963 Changed online meeting to outlook event
  api-reference/beta/api/application-post-onlinemeetings.md
Labels: ready to merge

#7969 Snippets Update
  api-reference/beta/includes/snippets/csharp/create-conditionalaccesspolicy-from-conditionalaccessroot-csharp-snippets.md
  api-reference/beta/includes/snippets/csharp/create-externalitem-from-connections-csharp-snippets.md
  api-reference/beta/includes/snippets/javascript/create-conditionalaccesspolicy-from-conditionalaccessroot-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/create-externalitem-from-connections-javascript-snippets.md
  api-reference/beta/includes/snippets/objc/create-conditionalaccesspolicy-from-conditionalaccessroot-objc-snippets.md
  api-reference/beta/includes/snippets/objc/create-externalitem-from-connections-objc-snippets.md
  api-reference/v1.0/includes/snippets/csharp/create-event-from-user-with-online-meeting-csharp-snippets.md
  api-reference/v1.0/includes/snippets/java/create-event-from-user-with-online-meeting-java-snippets.md
  api-reference/v1.0/includes/snippets/javascript/create-event-from-user-with-online-meeting-javascript-snippets.md
  api-reference/v1.0/includes/snippets/javascript/create-plannertask-from-planner-javascript-snippets.md
  api-reference/v1.0/includes/snippets/objc/create-event-from-user-with-online-meeting-objc-snippets.md
Labels: ready to merge

#7975 Add delay guidance for adding members
  concepts/teams-create-group-and-team.md
Labels: ready to merge

#7857 Update attributes to add presence badge.
  concepts/toolkit/components/people.md
  concepts/toolkit/components/person.md
Labels: do not merge, internal

#7574 Item analytics activities
  api-reference/beta/api/sites-list-followed.md
  api-reference/beta/resources/site.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/driveitem-createlink.md
  api-reference/v1.0/api/driveitem-invite.md
  api-reference/v1.0/api/sites-list-followed.md
  api-reference/v1.0/resources/permission.md
  api-reference/v1.0/resources/shareddriveitem.md
  api-reference/v1.0/resources/sharepointids.md
  api-reference/v1.0/resources/sharinglink.md
  api-reference/v1.0/resources/site.md
  api-reference/v1.0/resources/sitecollection.md
  api-reference/v1.0/toc.yml
  concepts/changelog.md
Labels: changes requested, ready to merge

#7988 Update group-post-threads.md
  api-reference/v1.0/api/group-post-threads.md
Labels: ready to merge

#8009 Fix the permissions of UnifiedRoleAssignmentMultiple
  api-reference/beta/api/unifiedroleassignmentmultiple-delete.md
  api-reference/beta/api/unifiedroleassignmentmultiple-get.md
  api-reference/beta/api/unifiedroleassignmentmultiple-list.md
  api-reference/beta/api/unifiedroleassignmentmultiple-post.md
  api-reference/beta/api/unifiedroleassignmentmultiple-update.md
Labels: ready to merge
