Repository microsoftgraph/microsoft-graph-docs, pull requests merged in 2020-02, with the labels that each got.

#6689 Describe API for sharing or delegating calendars.
  api-reference/beta/api/calendarpermission-update.md
  api-reference/beta/api/event-accept.md
  api-reference/beta/api/event-decline.md
  api-reference/beta/resources/calendar.md
  api-reference/beta/resources/calendarpermission.md
  api-reference/beta/resources/event.md
  api-reference/beta/resources/eventmessage.md
  api-reference/beta/resources/eventmessagerequest.md
  api-reference/beta/resources/eventmessageresponse.md
  api-reference/beta/resources/mailboxsettings.md
  api-reference/beta/resources/message.md
  api-reference/v1.0/api/event-accept.md
  api-reference/v1.0/api/event-decline.md
  api-reference/v1.0/api/event-tentativelyaccept.md
  api-reference/v1.0/resources/event.md
  api-reference/v1.0/resources/eventmessage.md
  api-reference/v1.0/resources/message.md
  concepts/outlook-create-event-in-shared-delegated-calendar.md
  concepts/outlook-get-shared-events-calendars.md
  concepts/outlook-share-or-delegate-calendar.md
  concepts/toc.yml
Labels: do not merge

#6985 - fixes wrong odata query parameter for membership
  api-reference/beta/api/group-delta.md
  api-reference/v1.0/api/group-delta.md
Labels: content review, ready to merge

#6993 subscription update
  api-reference/beta/api/subscription-get.md
  api-reference/beta/api/subscription-list.md
  api-reference/beta/api/subscription-post-subscriptions.md
  api-reference/beta/api/subscription-update.md
  api-reference/beta/resources/subscription.md
  api-reference/v1.0/api/subscription-get.md
  api-reference/v1.0/api/subscription-list.md
  api-reference/v1.0/api/subscription-post-subscriptions.md
  api-reference/v1.0/api/subscription-update.md
  api-reference/v1.0/resources/subscription.md
  concepts/changelog.md
Labels: ready to merge

#6997 update note for recurring reviews
  api-reference/beta/api/accessreview-list.md
Labels: area: azure/AAD

#7001 Note support for primary mailbox vs archive.
  api-reference/beta/resources/mail-api-overview.md
  api-reference/includes/outlook-mailbox-type-support.md
  api-reference/v1.0/resources/mail-api-overview.md
  concepts/outlook-calendar-concept-overview.md
  concepts/outlook-contacts-concept-overview.md
  concepts/outlook-mail-concept-overview.md
  includes/outlook-mailbox-type-support.md
Labels: do not merge

#7016 Updated spacing to fix table issue
  api-reference/beta/resources/call.md
Labels: ready to merge

#7012 - fixes #4807: documents that client state is not returned
  api-reference/beta/api/subscription-list.md
  api-reference/v1.0/api/subscription-list.md
Labels: content review, ready to merge

#7021 Update what's new.
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: do not merge

#7013 Define new hide-options attribute in mgt-tasks
  concepts/toolkit/components/tasks.md
Labels: internal

#6844 GBL graph v1.0 API changes
  api-reference/v1.0/api/group-assignlicense.md
  api-reference/v1.0/api/user-assignlicense.md
  api-reference/v1.0/api/user-reprocesslicenseassignment.md
  api-reference/v1.0/resources/group.md
  api-reference/v1.0/resources/user.md
  api-reference/v1.0/toc.yml
  concepts/changelog.md
Labels: ready to merge

#7032 Addressed questions about latestSupportedTlsVersion property.
  api-reference/beta/resources/subscription.md
  api-reference/v1.0/resources/subscription.md
Labels: resolved: awaiting prod deployment

#7056 Fixed a typo in graph toolkit templating docs
  concepts/toolkit/templates.md
Labels: ready to merge

#7053 Snippets update
  api-reference/beta/includes/snippets/csharp/create-subscription-from-subscriptions-csharp-snippets.md
  api-reference/beta/includes/snippets/javascript/create-subscription-from-subscriptions-javascript-snippets.md
  api-reference/beta/includes/snippets/objc/create-subscription-from-subscriptions-objc-snippets.md
  api-reference/v1.0/api/group-assignlicense.md
  api-reference/v1.0/api/user-reprocesslicenseassignment.md
  api-reference/v1.0/includes/snippets/csharp/create-subscription-from-subscriptions-csharp-snippets.md
  api-reference/v1.0/includes/snippets/csharp/group-assignlicense-csharp-snippets.md
  api-reference/v1.0/includes/snippets/csharp/group-removelicense-csharp-snippets.md
  api-reference/v1.0/includes/snippets/csharp/user-reprocesslicenseassignment-csharp-snippets.md
  api-reference/v1.0/includes/snippets/java/create-subscription-from-subscriptions-java-snippets.md
  api-reference/v1.0/includes/snippets/java/group-assignlicense-java-snippets.md
  api-reference/v1.0/includes/snippets/java/group-removelicense-java-snippets.md
  api-reference/v1.0/includes/snippets/java/user-reprocesslicenseassignment-java-snippets.md
  api-reference/v1.0/includes/snippets/javascript/create-subscription-from-subscriptions-javascript-snippets.md
  api-reference/v1.0/includes/snippets/javascript/group-assignlicense-javascript-snippets.md
  api-reference/v1.0/includes/snippets/javascript/group-removelicense-javascript-snippets.md
  api-reference/v1.0/includes/snippets/javascript/user-reprocesslicenseassignment-javascript-snippets.md
  api-reference/v1.0/includes/snippets/objc/create-subscription-from-subscriptions-objc-snippets.md
  api-reference/v1.0/includes/snippets/objc/group-assignlicense-objc-snippets.md
  api-reference/v1.0/includes/snippets/objc/group-removelicense-objc-snippets.md
  api-reference/v1.0/includes/snippets/objc/user-reprocesslicenseassignment-objc-snippets.md
Labels: ready to merge

#6992 Update outlook-large-attachments.md
  concepts/outlook-large-attachments.md
Labels: ready to merge

#7072 illustrate how to use AdminRemove for removing assignments
  api-reference/beta/api/accesspackageassignment-list.md
  api-reference/beta/api/accesspackageassignmentrequest-list.md
  api-reference/beta/api/accesspackageassignmentrequest-post.md
  api-reference/beta/resources/accesspackageassignment.md
  api-reference/beta/resources/accesspackageassignmentrequest.md
Labels: area: azure/AAD, ready to merge

#5448 issues - 2028 - top parameter values added
  concepts/query-parameters.md
Labels: area: azure/AAD, content review, external, ready to merge

#7095 Updated per PR #2937.
  concepts/delta-query-users.md
Labels: ready to merge

#7109 Update openshiftchangerequest-approve.md
  api-reference/beta/api/openshiftchangerequest-approve.md
Labels: external

#7084 Update permissions-reference.md
  concepts/permissions-reference.md
Labels: area: teams, ready to merge

#7017 Origin/madehmer analytics feb
  api-reference/beta/api/activitystatistics-get.md
  api-reference/beta/api/activitystatistics-list.md
  api-reference/beta/resources/activitystatistics.md
  api-reference/beta/toc.yml
  concepts/permissions-reference.md
Labels: ready to merge

#6140 Change notifications capabilities
  api-reference/beta/resources/subscription.md
  api-reference/beta/resources/webhooks.md
  api-reference/v1.0/resources/subscription.md
  api-reference/v1.0/resources/webhooks.md
Labels: area: webhooks, content review, ready to merge

#7049 Alezhan onenote postpages
  api-reference/beta/api/onenote-post-pages.md
  api-reference/v1.0/api/onenote-post-pages.md
  concepts/onenote-create-page.md
Labels: ready to merge

#7150 - partial #6471: adds the delta query mark for Chinese Cloud
  concepts/deployments.md
Labels: ready to merge

#7139 add description for teamsapp permission
  concepts/permissions-reference.md
Labels: area: teams, ready to merge

#7127 Add Splunk Cloud blog post
  concepts/security-integration.md
Labels: ready to merge

#7126 Add link to github samples
  concepts/security-concept-overview.md
Labels: ready to merge

#7082 Add required fields to CreateTiIndicator method
  api-reference/beta/api/tiindicators-post.md
Labels: ready to merge

#7085 Add required fields to SubmitMultipleTiIndicators
  api-reference/beta/api/tiindicator-submittiindicators.md
Labels: ready to merge

#7091 Add required fields for UpdateTiIndicator
  api-reference/beta/api/tiindicator-update.md
Labels: ready to merge

#7092 Add required fields to Update Multiple TiIndicators
  api-reference/beta/api/tiindicator-updatetiindicators.md
Labels: ready to merge

#7102 updating request endpoints for Openshiftchangerequest approve and decline
  api-reference/beta/api/openshiftchangerequest-approve.md
  api-reference/beta/api/openshiftchangerequest-decline.md
Labels: ready to merge

#7153 Fix broken links in changelog
  concepts/changelog.md
Labels: ready to merge

#7141 Re-voiced and added missing descriptions for some resources, and re-formatted table.
  api-reference/beta/resources/subscription.md
  api-reference/beta/resources/webhooks.md
  api-reference/v1.0/resources/subscription.md
  api-reference/v1.0/resources/webhooks.md
Labels: ready to merge

#7044 Fixing doc issues for large attachments
  api-reference/beta/api/attachment-createuploadsession.md
  api-reference/beta/api/event-post-attachments.md
  api-reference/beta/api/message-post-attachments.md
  api-reference/v1.0/api/event-post-attachments.md
  api-reference/v1.0/api/message-post-attachments.md
  concepts/outlook-large-attachments.md
Labels: review requested

#7161 adds token validation example for rich notifications
  concepts/webhooks-with-resource-data.md
Labels: area: webhooks, ready to merge

#6860 Update calendar-get.md
  api-reference/beta/api/calendar-post-events.md
  api-reference/beta/api/event-update.md
  api-reference/beta/api/user-post-events.md
  api-reference/beta/resources/event.md
Labels: ready to merge

#7034 Add RecordingInfo.Initiator Property and onlineMeeting.externalId property in Beta
  api-reference/beta/resources/recordinginfo.md
  concepts/changelog.md
Labels: ready to merge

#7162 Update activitystatistics.md
  api-reference/beta/resources/activitystatistics.md
Labels: review requested

#7191 Add error to job - in progress
  api-reference/beta/api/synchronization-synchronizationjob-get.md
  api-reference/beta/resources/synchronization-quarantine.md
  concepts/changelog.md
Labels: ready to merge

#6995 Added user authentication method permissions
  concepts/permissions-reference.md
Labels: ready to merge

#7184 Update teams-concept-overview.md
  concepts/teams-concept-overview.md
Labels: external, ready to merge

#7179 update permissions-reference.md
  concepts/permissions-reference.md
Labels: ready to merge

#7197 Add ThreatIndicators.Read.All to the permissions
  concepts/permissions-reference.md
Labels: ready to merge

#6967 Teams webhooks
  api-reference/beta/api/subscription-post-subscriptions.md
  concepts/changelog.md
  concepts/teams-protected-apis.md
Labels: area: teams, ready to merge

#7222 fix for git issue 6545
  api-reference/beta/api/accessreview-create.md
Labels: ready to merge

#7217 - adds information about non support for expand in users delta queries
  concepts/delta-query-overview.md
Labels: ready to merge

#7215 fix bad merge
  concepts/changelog.md
Labels: ready to merge

#4454 webhooksonlists
  api-reference/beta/api/subscription-delete.md
  api-reference/beta/api/subscription-get.md
  api-reference/beta/api/subscription-post-subscriptions.md
  api-reference/beta/api/subscription-update.md
  api-reference/beta/resources/list.md
  api-reference/beta/resources/subscription.md
  api-reference/beta/resources/webhooks.md
  concepts/changelog.md
Labels: area: azure/AAD, ready to merge

#6881 introduce requestor, approval and assignment review settings to policy
  api-reference/beta/api/accesspackage-list.md
  api-reference/beta/api/accesspackageassignmentpolicy-get.md
  api-reference/beta/api/accesspackageassignmentpolicy-list.md
  api-reference/beta/api/accesspackageassignmentpolicy-post.md
  api-reference/beta/api/accesspackagecatalog-list.md
  api-reference/beta/resources/accesspackageassignmentpolicy.md
  api-reference/beta/resources/accesspackageassignmentrequest.md
  api-reference/beta/resources/approvalsettings.md
  api-reference/beta/resources/approvalstage.md
  api-reference/beta/resources/assignmentreviewsettings.md
  api-reference/beta/resources/connectedorganizationmembers.md
  api-reference/beta/resources/entitlementmanagement-root.md
  api-reference/beta/resources/externalsponsors.md
  api-reference/beta/resources/groupmembers.md
  api-reference/beta/resources/internalsponsors.md
  api-reference/beta/resources/requestormanager.md
  api-reference/beta/resources/requestorsettings.md
  api-reference/beta/resources/singleuser.md
  api-reference/beta/resources/userset.md
  concepts/changelog.md
Labels: area: azure/AAD, ready to merge

#7178 Add toc/changelog for policies changes
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: area: azure/AAD, ready to merge

#6692 Added 2 new props for group exposure in Outlook
  api-reference/v1.0/resources/group.md
  concepts/changelog.md
Labels: ready to merge

#6873 add servicePrincipal to logs
  api-reference/beta/api/provisioningobjectsummary-list.md
  api-reference/beta/resources/provisioningobjectsummary.md
  api-reference/beta/resources/provisioningserviceprincipal.md
  concepts/changelog.md
Labels: ready to merge

#7055 Teams Graph Throttling limits
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
  concepts/throttling-limits-current .md
Labels: do not merge

#7181 update permissions-reference.md
  concepts/permissions-reference.md
Labels: changes requested, ready to merge

#7209 New hub page for Graph doc set
  concepts/index.yml
Labels: ready to merge
