Repository microsoftgraph/microsoft-graph-docs, pull requests merged in 2020-01, with the labels that each got.

#6697 Corrected spelling of "videio"
  api-reference/v1.0/resources/onlinemeeting.md
Labels: ready to merge

#6642 Deleted note : Sending messages with attachments and images is not supported on Line no 46.
  api-reference/beta/api/channel-post-messages.md
Labels: area: teams, ready to merge

#6717 Update integrate-with-onenote.md
  concepts/integrate-with-onenote.md
Labels: external, ready to merge

#6726 fix for git issue 6545
  api-reference/beta/api/accessreview-create.md
Labels: ready to merge

#6734 Added note that identifiers are case-sensitive
  concepts/outlook-immutable-id.md
Labels: ready to merge

#6738 Examples to attach file or item to an Outlook task. Not reference attachment.
  api-reference/beta/api/outlooktask-post-attachments.md
  api-reference/beta/resources/attachment.md
  api-reference/beta/resources/referenceattachment.md
Labels: do not merge

#6744 Update search-concept-overview.md
  concepts/search-concept-overview.md
Labels: content review, ready to merge

#6752 Update Comments section for Update Alert v1.0
  api-reference/v1.0/api/alert-update.md
Labels: ready to merge

#6751 Update comments section Update Alert beta
  api-reference/beta/api/alert-update.md
Labels: ready to merge

#6735 Change to Graph Security API
  concepts/changelog.md
Labels: ready to merge

#6773 Microsoft-graph-toolkit "people-picker" permissions update
  concepts/toolkit/components/people-picker.md
Labels: content review

#6771 user default properties
  api-reference/beta/api/user-get.md
  api-reference/beta/api/user-list.md
  api-reference/beta/api/user-post-users.md
  api-reference/beta/resources/user.md
Labels: ready to merge

#6755 Added information about timezones in startDateTime and endDateTime
  api-reference/beta/api/calendar-list-calendarview.md
  api-reference/beta/api/group-list-calendarview.md
  api-reference/beta/api/user-list-calendarview.md
  api-reference/v1.0/api/calendar-list-calendarview.md
  api-reference/v1.0/api/group-list-calendarview.md
  api-reference/v1.0/api/user-list-calendarview.md
Labels: ready to merge

#6629 add suggestion for paging access review results
  api-reference/beta/api/accessreview-get.md
  api-reference/beta/api/accessreview-list.md
  api-reference/beta/resources/accessreview.md
Labels: area: azure/AAD

#6797 Added Dec. and Jan. what's new items.
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
  concepts/changelog.md
  concepts/toc.yml
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: do not merge

#6795 Update http url for workbook comment APIs
  api-reference/beta/api/workbookcomment-get.md
  api-reference/beta/api/workbookcomment-list-replies.md
  api-reference/beta/api/workbookcomment-post-replies.md
  api-reference/beta/api/workbookcommentreply-get.md
  api-reference/v1.0/api/workbookcomment-get.md
  api-reference/v1.0/api/workbookcomment-list-replies.md
  api-reference/v1.0/api/workbookcomment-post-replies.md
  api-reference/v1.0/api/workbookcommentreply-get.md
Labels: ready to merge

#6809 Online Meeting Deprecated Permissions
  api-reference/beta/api/application-post-onlinemeetings.md
  concepts/permissions-reference.md
Labels: content review, ready to merge

#6548 Add details + changelog on new optional request header.
  api-reference/beta/api/informationprotectionlabel-evaluateapplication.md
  api-reference/beta/api/informationprotectionlabel-evaluateclassificationresults.md
  api-reference/beta/api/informationprotectionlabel-evaluateremoval.md
  api-reference/beta/api/informationprotectionlabel-extractlabel.md
  api-reference/beta/api/informationprotectionlabel-get.md
  api-reference/beta/api/informationprotectionpolicy-list-labels.md
  concepts/changelog.md
Labels: ready to merge

#6838 link fixes
  api-reference/beta/api/subscription-post-subscriptions.md
  concepts/changelog.md
Labels: area: teams, ready to merge

#6836 Corrected description of the id property
  api-reference/beta/resources/calendar.md
  api-reference/v1.0/resources/calendar.md
Labels: ready to merge

#6715 userIdentities to v1.0
  api-reference/beta/api/user-list.md
  api-reference/beta/api/user-post-users.md
  api-reference/v1.0/api/user-list.md
  api-reference/v1.0/api/user-post-users.md
  api-reference/v1.0/resources/objectidentity.md
  api-reference/v1.0/resources/user.md
  concepts/changelog.md
  concepts/migrate-azure-ad-graph-property-differences.md
Labels: content review, ready to merge

#6277 Policy update to beta (breaking change)
  api-reference/beta/api/activitybasedtimeoutpolicy-delete.md
  api-reference/beta/api/activitybasedtimeoutpolicy-get.md
  api-reference/beta/api/activitybasedtimeoutpolicy-list.md
  api-reference/beta/api/activitybasedtimeoutpolicy-post-activitybasedtimeoutpolicies.md
  api-reference/beta/api/activitybasedtimeoutpolicy-update.md
  api-reference/beta/api/application-delete-tokenlifetimepolicies.md
  api-reference/beta/api/application-list-tokenlifetimepolicies.md
  api-reference/beta/api/application-list.md
  api-reference/beta/api/application-post-tokenlifetimepolicies.md
  api-reference/beta/api/claimsmappingpolicy-delete.md
  api-reference/beta/api/claimsmappingpolicy-get.md
  api-reference/beta/api/claimsmappingpolicy-list-appliesto.md
  api-reference/beta/api/claimsmappingpolicy-list.md
  api-reference/beta/api/claimsmappingpolicy-post-claimsmappingpolicies.md
  api-reference/beta/api/claimsmappingpolicy-update.md
  api-reference/beta/api/homerealmdiscoverypolicy-delete.md
  api-reference/beta/api/homerealmdiscoverypolicy-get.md
  api-reference/beta/api/homerealmdiscoverypolicy-list-appliesto.md
  api-reference/beta/api/homerealmdiscoverypolicy-list.md
  api-reference/beta/api/homerealmdiscoverypolicy-post-homerealmdiscoverypolicies.md
  api-reference/beta/api/homerealmdiscoverypolicy-update.md
  api-reference/beta/api/serviceprincipal-delete-claimsmappingpolicies.md
  api-reference/beta/api/serviceprincipal-delete-homerealmdiscoverypolicies.md
  api-reference/beta/api/serviceprincipal-list-claimsmappingpolicies.md
  api-reference/beta/api/serviceprincipal-list-homerealmdiscoverypolicies.md
  api-reference/beta/api/serviceprincipal-post-claimsmappingpolicies.md
  api-reference/beta/api/serviceprincipal-post-homerealmdiscoverypolicies.md
  api-reference/beta/api/tokenlifetimepolicy-delete.md
  api-reference/beta/api/tokenlifetimepolicy-get.md
  api-reference/beta/api/tokenlifetimepolicy-list-appliesto.md
  api-reference/beta/api/tokenlifetimepolicy-list.md
  api-reference/beta/api/tokenlifetimepolicy-post-tokenlifetimepolicies.md
  api-reference/beta/api/tokenlifetimepolicy-update.md
  api-reference/beta/resources/activitybasedtimeoutpolicy.md
  api-reference/beta/resources/application.md
  api-reference/beta/resources/claimsmappingpolicy.md
  api-reference/beta/resources/homerealmdiscoverypolicy.md
  api-reference/beta/resources/policy-overview.md
  api-reference/beta/resources/policybase.md
  api-reference/beta/resources/serviceprincipal.md
  api-reference/beta/resources/stspolicy.md
  api-reference/beta/resources/tokenlifetimepolicy.md
  api-reference/beta/toc.yml
  concepts/changelog.md
  concepts/migrate-azure-ad-graph-client-libraries.md
  concepts/migrate-azure-ad-graph-overview.md
  concepts/migrate-azure-ad-graph-property-differences.md
  concepts/migrate-azure-ad-graph-resource-differences.md
Labels: area: azure/AAD, content review, ready to merge

#5626 added documentation for $ref and $value capabilities
  concepts/query-parameters.md
Labels: area: azure/AAD, ready to merge

#6878 clarify values of reviewResult, appliedBy and reviewedBy
  api-reference/beta/resources/accessreviewdecision.md
Labels: area: azure/AAD, ready to merge

#6730 Graph Documentation TOC changes: Bug fix for #742736, #742763, #742770, #742819, #742829, #742853, #742888 in Azure Portal
  api-reference/beta/resources/channel.md
  api-reference/beta/resources/group.md
  api-reference/beta/resources/team.md
  api-reference/beta/resources/teamsappinstallation.md
  api-reference/beta/resources/teamstab.md
  api-reference/beta/toc.yml
Labels: area: teams, ready to merge

#6933 Bug fix in teamsapp-list.md
  api-reference/beta/api/teamsapp-list.md
Labels: area: teams, ready to merge

#6931 Fix typo: "for on" --> "on"
  api-reference/beta/api/driveitem-list-permissions.md
  api-reference/v1.0/api/driveitem-list-permissions.md
Labels: ready to merge

#6963 - fixes #6403: aligns tokens presented in the sample with the sequence
  concepts/delta-query-users.md
Labels: ready to merge

#6961 - partial #2962: adds token validity limitation documentation for AAD objects
  concepts/delta-query-overview.md
Labels: ready to merge

#6960 - fixes #6471: adds documentation regarding availability of delta queries in national clouds
  concepts/delta-query-overview.md
Labels: ready to merge

#6958 - fixes #6913: adds indications about the delta query FQN
  concepts/delta-query-overview.md
Labels: ready to merge

#6956 Added sample request to send mail with file attachment
  api-reference/beta/api/user-sendmail.md
  api-reference/v1.0/api/user-sendmail.md
Labels: ready to merge

#6957 - fixes #6785: adds an indication that entities can be duplicated in a delta query response
  concepts/delta-query-overview.md
Labels: ready to merge

#6903 fixes #5784 adds v1 lifecycle event information
  concepts/webhooks-outlook-authz.md
  concepts/webhooks.md
Labels: ready to merge

#6942 - fixes #6609 indicates that delta on users is not supported for personal accounts
  api-reference/beta/api/user-delta.md
  api-reference/v1.0/api/user-delta.md
Labels: ready to merge

#6902 fixes: #3055 adds tenant id in the properties
  concepts/webhooks.md
Labels: ready to merge

#6941 Removed wellKnownName from example responses in v1 docs
  api-reference/v1.0/api/mailfolder-get.md
  api-reference/v1.0/api/mailsearchfolder-post.md
  api-reference/v1.0/api/mailsearchfolder-update.md
  api-reference/v1.0/api/user-list-mailfolders.md
Labels: ready to merge

#6895 Added primaryChannel navigation property in Team resource type doc in v1.0.
  api-reference/v1.0/resources/team.md
  concepts/changelog.md
Labels: area: teams, ready to merge

#6962 - fixes #6376: adds a note regarding possible delays before DQ reflects changes
  concepts/delta-query-overview.md
Labels: content review, ready to merge

#6954 - fixes #6951: provides guidance for retry handling
  concepts/throttling.md
Labels: ready to merge
