Repository microsoftgraph/microsoft-graph-docs, pull requests merged in 2020-08, with the labels that each got.

#9342 Update group-post-groups.md
  api-reference/beta/api/group-post-groups.md
Labels: ready to merge

#9350 new app management article
  concepts/application-saml-sso-configure-api.md
  concepts/toc.yml
Labels: area: azure/AAD, ready to merge

#9354 Added details for new events in MgtTasks
  concepts/toolkit/components/tasks.md
Labels: internal

#9316 - adds a note for the query string parameters capability
  concepts/webhooks.md
Labels: area: webhooks, ready to merge

#9365 bugfix/comment-onetask-nospam
  .github/label-commenter-config.yml
  .github/workflows/conflicting-pr-comment.yml
  .github/workflows/conflicting-pr-label.yml
Labels: ready to merge

#9368 - moves resources under their service limits for clarity
  concepts/throttling.md
Labels: area: throttling, ready to merge

#9403 Renamed changelog areas to match taxonomy
  concepts/changelog.md
Labels: changelog, content review, ready to merge

#9376 better hyperlink
  api-reference/beta/resources/teams-api-overview.md
Labels: area: teams, ready to merge

#9385 Update unifiedroledefinition-get.md
  api-reference/beta/api/unifiedroledefinition-get.md
Labels: ready to merge

#8904 - adds support for delta query in us gov
  concepts/changelog.md
  concepts/deployments.md
Labels: area: delta query, area: national clouds, changelog, ready to merge

#9363 - adds outlooks subscription maximum number
  concepts/webhooks.md
Labels: area: outlook, area: outlook events, area: webhooks, ready to merge

#9235 - adds change notifications latency information
  concepts/webhooks.md
Labels: area: webhooks, ready to merge

#9387 Document subscription limits for callRecords
  concepts/webhooks.md
Labels: area: cloud communications, area: teams, area: webhooks, ready to merge

#9406 - adds extension error code
  concepts/errors.md
Labels: area: outlook, area: outlook events, area: webhooks, ready to merge

#7462 adds change notifications delivery alternative
  api-reference/beta/toc.yml
  concepts/change-notifications-delivery.md
  concepts/changelog.md
  concepts/images/change-notifications/accesspolicieslist.png
  concepts/images/change-notifications/accesspolicyadd.png
  concepts/images/change-notifications/dnsname.png
  concepts/images/change-notifications/eventhubadditionpanel.png
  concepts/images/change-notifications/eventhubs.png
  concepts/images/change-notifications/eventhubsaddition.png
  concepts/images/change-notifications/eventhubscreated.png
  concepts/images/change-notifications/eventhubscreation.png
  concepts/images/change-notifications/keyvault.png
  concepts/images/change-notifications/keyvaultcreated.png
  concepts/images/change-notifications/keyvaultcreation.png
  concepts/images/change-notifications/policyaddition.png
  concepts/images/change-notifications/policycs.png
  concepts/images/change-notifications/policypanel.png
  concepts/images/change-notifications/secretscreation.png
  concepts/images/change-notifications/secretslistpage.png
  concepts/toc.yml
Labels: area: webhooks, changelog, changes requested, ready to merge

#9416 - updates author from baywet to davidmu1
  api-reference/beta/api/subscription-delete.md
  api-reference/beta/api/subscription-get.md
  api-reference/beta/api/subscription-list.md
  api-reference/beta/api/subscription-post-subscriptions.md
  api-reference/beta/api/subscription-update.md
  api-reference/beta/resources/changenotification.md
  api-reference/beta/resources/changenotificationcollection.md
  api-reference/beta/resources/changenotificationencryptedcontent.md
  api-reference/beta/resources/resourcedata.md
  api-reference/beta/resources/subscription.md
  api-reference/beta/resources/webhooks.md
  api-reference/v1.0/api/subscription-delete.md
  api-reference/v1.0/api/subscription-get.md
  api-reference/v1.0/api/subscription-list.md
  api-reference/v1.0/api/subscription-post-subscriptions.md
  api-reference/v1.0/api/subscription-update.md
  api-reference/v1.0/resources/changenotification.md
  api-reference/v1.0/resources/changenotificationcollection.md
  api-reference/v1.0/resources/resourcedata.md
  api-reference/v1.0/resources/subscription.md
  api-reference/v1.0/resources/webhooks.md
  concepts/delta-query-events.md
  concepts/delta-query-groups.md
  concepts/delta-query-messages.md
  concepts/delta-query-overview.md
  concepts/delta-query-users.md
  concepts/json-batching.md
  concepts/paging.md
  concepts/throttling.md
  concepts/webhooks-outlook-authz.md
  concepts/webhooks-with-resource-data.md
  concepts/webhooks.md
  includes/throttling-Identity-and-access-audit-logs.md
  includes/throttling-cpim.md
  includes/throttling-education-rostering-apis.md
  includes/throttling-excel.md
  includes/throttling-intune-applications.md
  includes/throttling-intune-books.md
  includes/throttling-intune-company-terms.md
  includes/throttling-intune-device-configuration.md
  includes/throttling-intune-device-enrollment.md
  includes/throttling-intune-devices.md
  includes/throttling-intune-enrollment.md
  includes/throttling-intune-managed-applications.md
  includes/throttling-intune-notifications.md
  includes/throttling-intune-rbac.md
  includes/throttling-intune-remote-assistance.md
  includes/throttling-intune-reporting.md
  includes/throttling-intune-tem.md
  includes/throttling-intune-troubleshooting.md
  includes/throttling-intune-wip.md
  includes/throttling-skype-calling.md
  includes/throttling-subscription-services.md
Labels: area: delta query, area: throttling, area: webhooks, ready to merge

#9422 Appprov1
  concepts/application-provisioning-configure-api.md
  concepts/images/application-provisioning-configure-api/wd_export_02.png
  concepts/toc.yml
Labels: area: azure/AAD, ready to merge

#8451 - adds throttling documentation for directory entities
  concepts/throttling.md
Labels: area: azure/AAD, area: throttling, ready to merge

#7461 - adds subscription includeProperties removal to changelog
  concepts/changelog.md
Labels: area: webhooks, ready to merge

#9227 Create workbook-best-practice.md
  concepts/toc.yml
  concepts/workbook-best-practice.md
Labels: area: excel, content review, ready to merge

#9431 Removing a permission that doesn't exist
  concepts/permissions-reference.md
Labels: area: teams, ready to merge

#9427 Updating incorrectly tagged permissions
  concepts/permissions-reference.md
Labels: ready to merge

#9389 Changes to Synchronization API Overview
  api-reference/beta/resources/synchronization-overview.md
Labels: ready to merge

#9434 Update workbook-best-practice.md
  concepts/workbook-best-practice.md
Labels: area: excel, ready to merge

#9200 Add new Microsoft 365 usage report: Microsoft 365 Apps usage
  api-reference/beta/api/reportroot-getm365appplatformusercounts.md
  api-reference/beta/api/reportroot-getm365appusercounts.md
  api-reference/beta/api/reportroot-getm365appuserdetail.md
  api-reference/beta/resources/intune-shared-report.md
  api-reference/beta/resources/microsoft-365-apps-usage-report.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: ready to merge

#9444 Update workbook-best-practice.md
  concepts/workbook-best-practice.md
Labels: area: excel, ready to merge

#9458 Fixed broken link per #9453
  concepts/toolkit/providers/custom.md
Labels: ready to merge

#9455 Removed 'Auditlogs' permissions from List users topic in beta docs
  api-reference/beta/api/user-list.md
Labels: area: azure/AAD, content review, ready to merge

#9459 Update changelog
  changelog/Manual.NonWorkloadChanges.json
  changelog/Microsoft.AAD.Reporting.json
  changelog/Microsoft.Analytics.json
  changelog/Microsoft.DirectoryServices.json
  changelog/Microsoft.EducationAssignment.json
  changelog/Microsoft.Excel.json
  changelog/Microsoft.Exchange.json
  changelog/Microsoft.FileServices.json
  changelog/Microsoft.Intune.json
  changelog/Microsoft.NAV.json
  changelog/Microsoft.Office.Tasks.json
  changelog/Microsoft.OneNote.json
  changelog/Microsoft.Search.json
  changelog/Microsoft.SharePoint.json
  changelog/Microsoft.Skype.Calling.json
  changelog/Microsoft.SubscriptionServices.json
  changelog/Microsoft.Teams.Core.json
  changelog/Microsoft.ThreatAssessment.json
  changelog/changelog.json
Labels: ready to merge

#8534 Update licensing terms
  api-reference/beta/api/subscription-post-subscriptions.md
  concepts/teams-licenses.md
  concepts/toc.yml
Labels: area: teams, ready to merge

#9473 Update workbook-error-codes.md
  concepts/workbook-error-codes.md
Labels: area: excel, ready to merge

#9466 Adding sample for sending cards with inline images
  api-reference/beta/api/chatmessage-post.md
Labels: area: teams, ready to merge

#9474 Snippets Update
  api-reference/beta/api/reportroot-getm365appplatformusercounts.md
  api-reference/beta/api/reportroot-getm365appusercounts.md
  api-reference/beta/api/reportroot-getm365appuserdetail.md
  api-reference/beta/includes/snippets/csharp/create-chatmessage-from-channel-csharp-snippets.md
  api-reference/beta/includes/snippets/csharp/reportroot-getm365appplatformusercounts-csv-csharp-snippets.md
  api-reference/beta/includes/snippets/csharp/reportroot-getm365appplatformusercounts-json-csharp-snippets.md
  api-reference/beta/includes/snippets/csharp/reportroot-getm365appusercoundetail-csharp-snippets.md
  api-reference/beta/includes/snippets/csharp/reportroot-getm365appusercountdetail-csharp-snippets.md
  api-reference/beta/includes/snippets/csharp/reportroot-getm365appusercounts-csv-csharp-snippets.md
  api-reference/beta/includes/snippets/csharp/reportroot-getm365appusercounts-json-csharp-snippets.md
  api-reference/beta/includes/snippets/javascript/reportroot-getm365appplatformusercounts-csv-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/reportroot-getm365appplatformusercounts-json-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/reportroot-getm365appusercoundetail-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/reportroot-getm365appusercountdetail-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/reportroot-getm365appusercounts-csv-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/reportroot-getm365appusercounts-json-javascript-snippets.md
  api-reference/beta/includes/snippets/objc/reportroot-getm365appplatformusercounts-csv-objc-snippets.md
  api-reference/beta/includes/snippets/objc/reportroot-getm365appplatformusercounts-json-objc-snippets.md
  api-reference/beta/includes/snippets/objc/reportroot-getm365appusercoundetail-objc-snippets.md
  api-reference/beta/includes/snippets/objc/reportroot-getm365appusercountdetail-objc-snippets.md
  api-reference/beta/includes/snippets/objc/reportroot-getm365appusercounts-csv-objc-snippets.md
  api-reference/beta/includes/snippets/objc/reportroot-getm365appusercounts-json-objc-snippets.md
  concepts/application-proxy-configure-api.md
  concepts/application-saml-sso-configure-api.md
Labels: ready to merge

#8853 Adding passwordsinglesignonsettings to servicePrincipal
  api-reference/beta/resources/passwordsinglesignonfield.md
  api-reference/beta/resources/passwordsinglesignonsettings.md
  api-reference/beta/resources/serviceprincipal.md
  concepts/changelog.md
Labels: changelog, changelog required

#9467 update roles on permission object in v1.0 and beta
  api-reference/beta/resources/permission.md
  api-reference/v1.0/resources/permission.md
Labels: ready to merge

#9393 Create workbook-error-handling.md
  concepts/toc.yml
  concepts/workbook-error-handling.md
Labels: area: excel, ready to merge

#9504 update changelog.json file
  changelog/changelog.json
Labels: conflicting

#9485 Adding allowAllUsers documentation
  api-reference/beta/resources/printershare.md
  concepts/changelog.md
Labels: area: universal print, changelog, ready to merge

#9520 Ramjsing/fix chat permissions
  api-reference/beta/api/conversationmember-get.md
  api-reference/beta/api/conversationmember-list.md
Labels: ready to merge

#9517 author alias correction
  api-reference/beta/api/signin-get.md
  api-reference/beta/api/signin-list.md
  api-reference/beta/resources/applicationsigninsummary.md
  api-reference/beta/resources/authenticationdetail.md
  api-reference/beta/resources/authenticationmethods-usage-insights-overview.md
  api-reference/beta/resources/azure-ad-auditlog-overview.md
  api-reference/beta/resources/report-identity-access.md
  api-reference/beta/resources/signin.md
  api-reference/v1.0/api/signin-get.md
  api-reference/v1.0/api/signin-list.md
  api-reference/v1.0/resources/azure-ad-auditlog-overview.md
  api-reference/v1.0/resources/signin.md
Labels: area: azure/AAD, ready to merge

#9519 Removes spacing.
  concepts/application-saml-sso-configure-api.md
Labels: area: azure/AAD, ready to merge

#9486 Adding Universal Print permissions
  api-reference/beta/api/print-get-settings.md
  api-reference/beta/api/print-list-connectors.md
  api-reference/beta/api/print-list-printers.md
  api-reference/beta/api/print-list-services.md
  api-reference/beta/api/print-list-shares.md
  api-reference/beta/api/print-post-shares.md
  api-reference/beta/api/print-update-settings.md
  api-reference/beta/api/printconnector-delete.md
  api-reference/beta/api/printconnector-get.md
  api-reference/beta/api/printconnector-update.md
  api-reference/beta/api/printdocument-uploaddata.md
  api-reference/beta/api/printer-create.md
  api-reference/beta/api/printer-delete-allowedgroup.md
  api-reference/beta/api/printer-delete-alloweduser.md
  api-reference/beta/api/printer-delete.md
  api-reference/beta/api/printer-get.md
  api-reference/beta/api/printer-getcapabilities.md
  api-reference/beta/api/printer-list-allowedgroups.md
  api-reference/beta/api/printer-list-allowedusers.md
  api-reference/beta/api/printer-list-connectors.md
  api-reference/beta/api/printer-list-jobs.md
  api-reference/beta/api/printer-list-tasktriggers.md
  api-reference/beta/api/printer-post-allowedgroups.md
  api-reference/beta/api/printer-post-allowedusers.md
  api-reference/beta/api/printer-post-jobs.md
  api-reference/beta/api/printer-post-tasktriggers.md
  api-reference/beta/api/printer-resetdefaults.md
  api-reference/beta/api/printer-update.md
  api-reference/beta/api/printershare-delete-allowedgroup.md
  api-reference/beta/api/printershare-delete-alloweduser.md
  api-reference/beta/api/printershare-delete.md
  api-reference/beta/api/printershare-get.md
  api-reference/beta/api/printershare-list-allowedgroups.md
  api-reference/beta/api/printershare-list-allowedusers.md
  api-reference/beta/api/printershare-post-allowedgroups.md
  api-reference/beta/api/printershare-post-allowedusers.md
  api-reference/beta/api/printershare-update.md
  api-reference/beta/api/printjob-cancelprintjob.md
  api-reference/beta/api/printjob-get.md
  api-reference/beta/api/printjob-startprintjob.md
  api-reference/beta/api/printoperation-get.md
  api-reference/beta/api/printservice-get.md
  api-reference/beta/api/printservice-list-endpoints.md
  api-reference/beta/api/printserviceendpoint-get.md
  api-reference/beta/api/printusagesummarybyprinter-get.md
  api-reference/beta/api/printusagesummarybyuser-get.md
  concepts/changelog.md
  concepts/permissions-reference.md
Labels: area: universal print, changelog, ready to merge

#9447 Add accessPackageAssignmentRequest requestState
  api-reference/beta/resources/accesspackageassignmentrequest.md
Labels: area: azure/AAD

#9119 add entitlement management update APIs
  api-reference/beta/api/accesspackage-update.md
  api-reference/beta/api/accesspackageassignmentpolicy-update.md
  api-reference/beta/api/accesspackagecatalog-update.md
  api-reference/beta/resources/accesspackage.md
  api-reference/beta/resources/accesspackageassignmentpolicy.md
  api-reference/beta/resources/accesspackagecatalog.md
  api-reference/beta/resources/entitlementmanagement-root.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: area: azure/AAD, changelog, ready to merge

#9352 add connected org internal and external sponsors
  api-reference/beta/api/connectedorganization-delete-externalsponsors.md
  api-reference/beta/api/connectedorganization-delete-internalsponsors.md
  api-reference/beta/api/connectedorganization-list-externalsponsors.md
  api-reference/beta/api/connectedorganization-list-internalsponsors.md
  api-reference/beta/api/connectedorganization-post-externalsponsors.md
  api-reference/beta/api/connectedorganization-post-internalsponsors.md
  api-reference/beta/resources/connectedorganization.md
  api-reference/beta/resources/entitlementmanagement-root.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: area: azure/AAD, changelog, ready to merge

#9516 add isMembershipLimitedToOwnersBeta
  api-reference/beta/api/team-get.md
  api-reference/beta/api/team-update.md
  api-reference/beta/resources/team.md
  concepts/changelog.md
Labels: ready to merge

#7947 Calendar - Client side expansion of events
  api-reference/beta/api/event-get.md
  api-reference/beta/resources/event.md
  concepts/changelog.md
Labels: changelog, ready to merge

#9537 Remove permissions that are no longer supported
  api-reference/beta/api/user-add-teamsappinstallation.md
  api-reference/beta/api/user-delete-teamsappinstallation.md
  api-reference/beta/api/user-list-teamsappinstallation.md
  api-reference/beta/api/user-upgrade-teamsappinstallation.md
Labels: area: teams, ready to merge

#9541 feature/auto throttling documentation
  includes/throttling-subscription-services.md
Labels: area: throttling, ready to merge

#9374 final app staging api
  api-reference/beta/api/teamsapp-delete.md
  api-reference/beta/api/teamsapp-list.md
  api-reference/beta/api/teamsapp-publish.md
  api-reference/beta/api/teamsapp-update.md
  api-reference/beta/resources/teamsapp.md
  api-reference/beta/resources/teamsappdefinition.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/teamsapp-delete.md
  api-reference/v1.0/api/teamsapp-list.md
  api-reference/v1.0/api/teamsapp-publish.md
  api-reference/v1.0/api/teamsapp-update.md
  api-reference/v1.0/resources/teamsapp.md
  api-reference/v1.0/resources/teamsappdefinition.md
  api-reference/v1.0/toc.yml
  concepts/changelog.md
  concepts/permissions-reference.md
Labels: area: teams, changes requested, ready to merge

#9567 Added Azure Functions tutorial to TOC and landing page
  concepts/toc.yml
  concepts/tutorials.yml
Labels: ready to merge

#9560 - fixes #4694: documents batching in combinatino with throttling
  concepts/throttling.md
Labels: area: batch requests, area: throttling, ready to merge

#9558 - documents token latest support for ODSP delta
  concepts/delta-query-overview.md
Labels: area: delta query, area: onedrive, ready to merge

#9559 - fixes: #3877 adds a throttling response sample
  concepts/throttling.md
Labels: area: throttling, ready to merge

#9568 Added clarity for the app submission status
  api-reference/beta/api/teamsapp-list.md
  api-reference/v1.0/api/teamsapp-list.md
Labels: ready to merge

#9424 Adding documentation for MGT caching
  concepts/toc.yml
  concepts/toolkit/cache.md
  concepts/toolkit/images/indexedDBpanel.png
Labels: internal

#9584 Fix ref links in the conceptual TOC
  concepts/toc.yml
Labels: ready to merge

#9550 Update directoryrole-post-members.md
  api-reference/beta/api/directoryrole-post-members.md
Labels: ready to merge

#9625 - auto generated update for throttling documentation
  includes/throttling-skype-calling.md
Labels: area: throttling, ready to merge

#9616 Updated AAD Graph migration docs
  concepts/migrate-azure-ad-graph-app-registration.md
  concepts/migrate-azure-ad-graph-audit-api-use.md
  concepts/migrate-azure-ad-graph-authentication-library.md
  concepts/migrate-azure-ad-graph-client-libraries.md
  concepts/migrate-azure-ad-graph-deploy-test-extend.md
  concepts/migrate-azure-ad-graph-feature-differences.md
  concepts/migrate-azure-ad-graph-method-differences.md
  concepts/migrate-azure-ad-graph-overview.md
  concepts/migrate-azure-ad-graph-planning-checklist.md
  concepts/migrate-azure-ad-graph-property-differences.md
  concepts/migrate-azure-ad-graph-request-differences.md
  concepts/migrate-azure-ad-graph-resource-differences.md
  concepts/toc.yml
  concepts/whats-new-earlier.md
Labels: area: azure/AAD, content review, ready to merge

#9619 Update workbook-error-handling.md
  concepts/workbook-error-handling.md
Labels: area: excel, ready to merge

#9623 - minor adjustements for change notifications AEH delivery mode
  concepts/change-notifications-delivery.md
Labels: area: webhooks, ready to merge

#9645 Fix HTTP sample query "Projec}" to "Project"
  api-reference/beta/api/driveitem-search.md
Labels: ready to merge

#9667 Remove broken hyperlink
  concepts/onenote-error-codes.md
Labels: ready to merge

#9657 Update accessreview-create.md
  api-reference/beta/api/accessreview-create.md
Labels: area: azure/AAD, ready to merge

#9622 Updated descriptions of ids
  api-reference/beta/resources/directoryobject.md
  api-reference/beta/resources/user.md
  api-reference/v1.0/resources/directoryobject.md
  api-reference/v1.0/resources/user.md
Labels: area: azure/AAD, ready to merge

#9673 Grammatical correction to gender neutral pronoun
  api-reference/beta/resources/invitation.md
  api-reference/v1.0/resources/invitation.md
Labels: ready to merge

#9390 Add inheritsPermissionsFrom to unifiedroledefinition
  api-reference/beta/api/rbacapplication-list-roledefinitions.md
  api-reference/beta/api/rbacapplication-post-roledefinitions.md
  api-reference/beta/api/unifiedroledefinition-get.md
  api-reference/beta/api/unifiedroledefinition-update.md
  api-reference/beta/resources/unifiedroledefinition.md
  concepts/changelog.md
Labels: ready to merge

#9697 Fixing typo in teams.md
  concepts/toolkit/providers/teams.md
Labels: ready to merge

#9695 Fixing typos in permission scopes in people.md
  concepts/toolkit/components/people.md
Labels: ready to merge

#9553 mgt people-picker missing props
  concepts/toolkit/components/people-picker.md
Labels: internal

#9635 Update excel-manage-sessions.md
  concepts/excel-manage-sessions.md
Labels: area: excel, ready to merge

#9611 Added guidance on using beta with SDKs
  api-reference/beta/includes/snippets/snippets-sdk-documentation-link.md
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
  concepts/sdks/use-beta.md
  concepts/toc.yml
Labels: ready to merge

#9375 Update transcription interface related document in beta and v1
  api-reference/beta/api/application-post-calls.md
  api-reference/beta/api/call-get.md
  api-reference/beta/resources/call.md
  api-reference/beta/resources/calltranscriptioninfo.md
  api-reference/v1.0/api/application-post-calls.md
  api-reference/v1.0/api/call-get.md
  api-reference/v1.0/resources/call.md
  api-reference/v1.0/resources/calltranscriptioninfo.md
  concepts/changelog.md
Labels: ready to merge

#9704 Update permissions-reference.md
  concepts/permissions-reference.md
Labels: ready to merge

#9675 Add `connectedOrganizationState` enum/property
  api-reference/beta/api/connectedorganization-post.md
  api-reference/beta/api/connectedorganization-update.md
  api-reference/beta/resources/connectedorganization.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/requestorsettings.md
  concepts/changelog.md
Labels: area: azure/AAD, ready to merge

#9676 Add new attributes to authorizationpolicy
  api-reference/beta/api/authorizationpolicy-get.md
  api-reference/beta/api/authorizationpolicy-update.md
  api-reference/beta/resources/authorizationpolicy.md
  api-reference/beta/resources/defaultuserrolepermissions.md
  concepts/changelog.md
Labels: changes requested, ready to merge

#9672 Updated cache docs for presence and groups caching
  concepts/toolkit/cache.md
Labels: internal
