Repository microsoftgraph/microsoft-graph-docs, pull requests merged in 2020-12, with the labels that each got.

#10867 changed author to besiler
  api-reference/beta/api/relyingpartydetailedsummary-list.md
  api-reference/beta/api/reportroot-getcredentialusagesummary.md
  api-reference/beta/api/reportroot-getcredentialuserregistrationcount.md
  api-reference/beta/api/reportroot-list-credentialuserregistrationdetails.md
  api-reference/beta/api/reportroot-list-usercredentialusagedetails.md
  api-reference/beta/api/signin-get.md
  api-reference/beta/api/signin-list.md
  api-reference/beta/resources/applicationsigninsummary.md
  api-reference/beta/resources/authenticationdetail.md
  api-reference/beta/resources/authenticationmethods-usage-insights-overview.md
  api-reference/beta/resources/azure-ad-auditlog-overview.md
  api-reference/beta/resources/credentialusagesummary.md
  api-reference/beta/resources/credentialuserregistrationcount.md
  api-reference/beta/resources/credentialuserregistrationdetails.md
  api-reference/beta/resources/detailsinfo.md
  api-reference/beta/resources/keyvalue.md
  api-reference/beta/resources/mfadetail.md
  api-reference/beta/resources/networkLocationDetail.md
  api-reference/beta/resources/relyingpartydetailedsummary.md
  api-reference/beta/resources/report-identity-access.md
  api-reference/beta/resources/signin.md
  api-reference/beta/resources/signinactivity.md
  api-reference/beta/resources/usercredentialusagedetails.md
  api-reference/beta/resources/userregistrationcount.md
  api-reference/v1.0/api/signin-get.md
  api-reference/v1.0/api/signin-list.md
  api-reference/v1.0/resources/azure-ad-auditlog-overview.md
  api-reference/v1.0/resources/signin.md
Labels: area: azure/AAD, internal, ready to merge

#10864 Update insights-customize-item-insights-privacy.md
  concepts/insights-customize-item-insights-privacy.md
Labels: internal, ready to merge

#10869 Swap values 2 and 128
  api-reference/beta/resources/intune-deviceconfig-advancedbitlockerstate.md
Labels: external

#10858 Update activity-feed-api-overview.md
  api-reference/beta/resources/activity-feed-api-overview.md
Labels: external

#10857 Update activity-feed-api-overview.md
  api-reference/v1.0/resources/activity-feed-api-overview.md
Labels: external

#10863 Update iteminsightssettings.md
  api-reference/beta/resources/iteminsightssettings.md
Labels: internal, ready to merge

#10853 Quick SharePoint edit
  api-reference/v1.0/resources/search-api-overview.md
Labels: do not merge, internal

#10852 Format updates
  concepts/search-concept-files.md
Labels: do not merge, internal

#10834 Add listId in listItem
  concepts/search-concept-files.md
  concepts/search-concept-sort.md
Labels: internal, ready to merge

#10838 Fix sample: Create Team with application permissions (example 2)
  api-reference/beta/api/team-post.md
  api-reference/beta/includes/snippets/csharp/create-team-post-minimal-csharp-snippets.md
  api-reference/beta/includes/snippets/javascript/create-team-post-minimal-javascript-snippets.md
  api-reference/v1.0/api/team-post.md
  api-reference/v1.0/includes/snippets/csharp/create-team-post-minimal-csharp-snippets.md
  api-reference/v1.0/includes/snippets/javascript/create-team-post-minimal-javascript-snippets.md
Labels: external

#10836 Update printsettings.md
  api-reference/beta/resources/printsettings.md
Labels: external

#10822 Update webhooks.md
  concepts/webhooks.md
Labels: external

#10815 Update statusbase.md
  api-reference/beta/resources/statusbase.md
Labels: external

#10826 Update cloud-communications-media.md
  concepts/cloud-communications-media.md
Labels: external

#10814 Update provisioningstep.md
  api-reference/beta/resources/provisioningstep.md
Labels: external

#10739 Light up PSTN outgoing P2P call in Graph Beta
  api-reference/beta/api/application-post-calls.md
Labels: external, ready to merge

#10842 Fix #10622 - Correct Azure AD Audit logs in MS Graph v1.0
  api-reference/v1.0/resources/azure-ad-auditlog-overview.md
Labels: area: azure/AAD, docs, fixed, internal, ready to merge

#10846 Add placeholder values to User example calls
  api-reference/beta/api/user-delta.md
  api-reference/beta/api/user-get.md
  api-reference/beta/api/user-update.md
  api-reference/v1.0/api/user-delta.md
  api-reference/v1.0/api/user-get.md
  api-reference/v1.0/api/user-update.md
Labels: area: users, docs, internal, ready to merge

#10866 Add reference to 1.0 and Preview in search concepts
  concepts/search-concept-overview.md
Labels: internal, ready to merge

#10844 Add placeholder values to Example 1 of Create User
  api-reference/beta/api/user-post-users.md
  api-reference/v1.0/api/user-post-users.md
Labels: area: users, docs, internal, ready to merge

#10809 Provision on demand rule ID
  api-reference/beta/resources/synchronization-synchronizationjobapplicationparameters.md
Labels: area: azure/AAD, content review, ready to merge

#10813 Fixing broken link
  api-reference/beta/resources/synchronization-configure-with-directory-extension-attributes.md
Labels: area: azure/AAD, content review, internal, ready to merge

#10312 Yw/participant info with platform
  api-reference/beta/api/participant-get.md
  api-reference/beta/resources/participantinfo.md
  changelog/Microsoft.Skype.Calling.json
  concepts/changelog.md
Labels: internal, ready to merge

#10430 Update throttling.md
  concepts/throttling.md
Labels: area: edu, area: throttling, internal, ready to merge

#10569 Mgt/localization + right-to-left
  concepts/toc.yml
  concepts/toolkit/customize-components/localization.md
  concepts/toolkit/customize-components/right-to-left.md
  concepts/toolkit/images/rightToLeft.png
Labels: do not merge, internal

#10898 Enable API Doctor for 3 enum-looking property types.
  api-reference/beta/resources/user.md
  api-reference/v1.0/resources/user.md
Labels: internal

#10896 Remove repeated "teams" url segment
  api-reference/beta/api/channel-delete-members.md
Labels: internal, ready to merge

#10368 1242148-docs ga proactive messaging and installed apps
  api-reference/beta/api/team-get-installedapps.md
  api-reference/beta/api/userscopeteamsappinstallation-get-chat.md
  api-reference/beta/api/userteamwork-add-installedapps.md
  api-reference/beta/api/userteamwork-delete-installedapps.md
  api-reference/beta/api/userteamwork-get-installedapps.md
  api-reference/beta/api/userteamwork-list-installedapps.md
  api-reference/beta/api/userteamwork-upgrade-installedapps.md
  api-reference/beta/resources/chat.md
  api-reference/beta/resources/teamsappinstallation.md
  api-reference/beta/resources/user.md
  api-reference/beta/resources/userscopeteamsappinstallation.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/team-get-installedapps.md
  api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md
  api-reference/v1.0/api/userteamwork-add-installedapps.md
  api-reference/v1.0/api/userteamwork-delete-installedapps.md
  api-reference/v1.0/api/userteamwork-get-installedapps.md
  api-reference/v1.0/api/userteamwork-list-installedapps.md
  api-reference/v1.0/api/userteamwork-upgrade-installedapps.md
  api-reference/v1.0/resources/chat.md
  api-reference/v1.0/resources/teamsappinstallation.md
  api-reference/v1.0/resources/user.md
  api-reference/v1.0/resources/userscopeteamsappinstallation.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.Teams.Core.json
  concepts/changelog.md
Labels: internal, ready to merge

#10893 Modify description of the status property to reflect complex structure
  api-reference/beta/resources/signin.md
  api-reference/beta/resources/signinstatus.md
  api-reference/v1.0/resources/signin.md
  api-reference/v1.0/resources/signinstatus.md
Labels: area: azure/AAD, content review, do not merge, docs

#10895 Update tutorial-riskdetection-api.md
  concepts/tutorial-riskdetection-api.md
Labels: external, ready to merge

#10892 Adding an example for admin approval/rejection
  api-reference/beta/api/teamsapp-publish.md
Labels: external

#10885 Clarify datetime properties of message resource
  api-reference/beta/api/user-post-mailfolders.md
  api-reference/beta/resources/message.md
  api-reference/v1.0/api/user-post-mailfolders.md
  api-reference/v1.0/resources/message.md
Labels: docs, internal, ready to merge

#10889 Update in Limitation for search refiners
  concepts/search-concept-aggregation.md
Labels: internal

#10882 Update application-saml-sso-configure-api.md
  concepts/application-saml-sso-configure-api.md
Labels: external

#10802 add description for CR timeout behavior
  api-reference/beta/api/call-answer.md
  api-reference/v1.0/api/call-answer.md
Labels: internal, ready to merge

#10805 Added details about possible value of capabilityStatus property
  api-reference/beta/resources/assignedplan.md
  api-reference/v1.0/resources/assignedplan.md
Labels: internal, ready to merge

#10883 Added note that date range cannot exceed 90 days
  api-reference/beta/api/callrecords-callrecord-getpstncalls.md
Labels: external, ready to merge

#10879 Add preview boilerplate
  api-reference/beta/api/cloudpc-get.md
  api-reference/beta/api/cloudpc-reprovision.md
  api-reference/beta/api/cloudpcdeviceimage-delete.md
  api-reference/beta/api/cloudpcdeviceimage-get.md
  api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md
  api-reference/beta/api/cloudpconpremisesconnection-delete.md
  api-reference/beta/api/cloudpconpremisesconnection-get.md
  api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md
  api-reference/beta/api/cloudpconpremisesconnection-update.md
  api-reference/beta/api/cloudpcprovisioningpolicy-assign.md
  api-reference/beta/api/cloudpcprovisioningpolicy-delete.md
  api-reference/beta/api/cloudpcprovisioningpolicy-get.md
  api-reference/beta/api/cloudpcprovisioningpolicy-update.md
  api-reference/beta/api/virtualendpoint-geteffectivepermissions.md
  api-reference/beta/api/virtualendpoint-list-cloudpcs.md
  api-reference/beta/api/virtualendpoint-list-deviceimages.md
  api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md
  api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md
  api-reference/beta/api/virtualendpoint-post-deviceimages.md
  api-reference/beta/api/virtualendpoint-post-onpremisesconnections.md
  api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md
  api-reference/beta/resources/cloudpc.md
  api-reference/beta/resources/cloudpcStatusDetails.md
  api-reference/beta/resources/cloudpcdeviceimage.md
  api-reference/beta/resources/cloudpcmanagementassignmenttarget.md
  api-reference/beta/resources/cloudpcmanagementgroupassignmenttarget.md
  api-reference/beta/resources/cloudpconpremisesconnection.md
  api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
  api-reference/beta/resources/cloudpconpremisesconnectionstatusdetails.md
  api-reference/beta/resources/cloudpcprovisioningpolicy.md
  api-reference/beta/resources/cloudpcprovisioningpolicyassignment.md
  api-reference/beta/resources/cloudpcsourcedeviceimage.md
  api-reference/beta/resources/virtualendpoint.md
  api-reference/includes/cloudpc-api-preview.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: internal, ready to merge

#10900 Removed unnecessary trailing bracket.
  api-reference/beta/resources/user.md
  api-reference/v1.0/resources/user.md
Labels: internal

#10804 [MGT] Removed deprecated properties
  concepts/toolkit/components/agenda.md
  concepts/toolkit/components/person-card.md
  concepts/toolkit/customize-components/style.md
Labels: do not merge, internal

#10897 [mgt] Adding docs for person-card v2, mgt-react, and packages
  concepts/toc.yml
  concepts/toolkit/components/agenda.md
  concepts/toolkit/components/get.md
  concepts/toolkit/components/login.md
  concepts/toolkit/components/people-picker.md
  concepts/toolkit/components/people.md
  concepts/toolkit/components/person-card.md
  concepts/toolkit/components/person.md
  concepts/toolkit/components/tasks.md
  concepts/toolkit/components/teams-channel-picker.md
  concepts/toolkit/customize-components/templates.md
  concepts/toolkit/get-started/add-aad-app-registration.md
  concepts/toolkit/get-started/build-a-web-app.md
  concepts/toolkit/get-started/mgt-react.md
  concepts/toolkit/get-started/overview.md
  concepts/toolkit/get-started/use-toolkit-with-angular.md
  concepts/toolkit/get-started/use-toolkit-with-react.md
  concepts/toolkit/overview.md
  concepts/toolkit/providers/providers.md
Labels: do not merge, internal

#10902 Add theme docs to style component section
  concepts/toolkit/components/agenda.md
  concepts/toolkit/components/login.md
  concepts/toolkit/components/people-picker.md
  concepts/toolkit/components/people.md
  concepts/toolkit/components/teams-channel-picker.md
  concepts/toolkit/customize-components/style.md
Labels: do not merge, internal

#10912 Snippets update
  api-reference/beta/includes/snippets/csharp/delete-channel-member-csharp-snippets.md
  api-reference/beta/includes/snippets/java/delete-channel-member-java-snippets.md
  api-reference/beta/includes/snippets/javascript/delete-channel-member-javascript-snippets.md
  api-reference/beta/includes/snippets/objc/delete-channel-member-objc-snippets.md
Labels: internal, ready to merge

#10917 Fixed changelog table position
  concepts/changelog.md
Labels: bug: documentation, internal, ready to merge

#10916 Correcting the example for approving a staged app
  api-reference/beta/api/teamsapp-publish.md
Labels: external

#10908 Update teams-send-activityfeednotifications.md
  concepts/teams-send-activityfeednotifications.md
Labels: external

#10905 Fixed errant *
  api-reference/beta/api/callrecords-callrecord-getpstncalls.md
Labels: external

#10881 Rsamai/graphconnectors Broken links fix
  concepts/search-index-manage-connections.md
  concepts/search-index-manage-items.md
  concepts/search-index-manage-schema.md
Labels: internal

#7173 IMAP, POP, SMTP permissions
  concepts/permissions-reference.md
Labels: ready to merge

#10923 Merge to publish.
  api-reference/beta/api/callrecords-callrecord-getpstncalls.md
  api-reference/beta/api/teamsapp-publish.md
  api-reference/beta/includes/snippets/csharp/delete-channel-member-csharp-snippets.md
  api-reference/beta/includes/snippets/java/delete-channel-member-java-snippets.md
  api-reference/beta/includes/snippets/javascript/delete-channel-member-javascript-snippets.md
  api-reference/beta/includes/snippets/objc/delete-channel-member-objc-snippets.md
  concepts/changelog.md
  concepts/permissions-reference.md
  concepts/search-index-manage-connections.md
  concepts/search-index-manage-items.md
  concepts/search-index-manage-schema.md
  concepts/teams-send-activityfeednotifications.md
Labels: internal

#10903 Add todo docs
  concepts/toc.yml
  concepts/toolkit/components/todo.md
  concepts/toolkit/overview.md
Labels: do not merge, internal

#10933 1797650: Remove '?view=azure-cli-latest' link syntax
  concepts/change-notifications-delivery.md
Labels: external

#10926 Update teams-send-activityfeednotifications.md
  concepts/teams-send-activityfeednotifications.md
Labels: external

#10909 - adds missing auth library installation steps
  concepts/sdks/choose-authentication-providers.md
  concepts/sdks/create-client.md
  concepts/sdks/sdk-installation.md
Labels: bug: sample, internal, ready to merge

#10788 2020 11 23 sadharne requestor manager level
  api-reference/beta/resources/requestormanager.md
  changelog/Microsoft.DirectoryServices.json
  concepts/changelog.md
Labels: area: azure/AAD, internal, ready to merge

#10772 Add presence to Graph v1.0
  api-reference/v1.0/api/cloudcommunications-getpresencesbyuserid.md
  api-reference/v1.0/api/presence-get.md
  api-reference/v1.0/resources/communications-api-overview.md
  api-reference/v1.0/resources/presence.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.Skype.Calling.json
  concepts/changelog.md
  concepts/throttling.md
Labels: changes requested, internal, ready to merge

#10934 Fixed links.
  concepts/changelog.md
Labels: internal

#10667 User flow attribute assignments documentation creation
  api-reference/beta/api/b2cidentityuserflow-list-userattributeassignments.md
  api-reference/beta/api/b2cidentityuserflow-post-userattributeassignments.md
  api-reference/beta/api/b2xidentityuserflow-list-userattributeassignments.md
  api-reference/beta/api/b2xidentityuserflow-post-userattributeassignments.md
  api-reference/beta/api/identitycontainer-post-b2cuserflows.md
  api-reference/beta/api/identityuserflowattributeassignment-delete.md
  api-reference/beta/api/identityuserflowattributeassignment-get.md
  api-reference/beta/api/identityuserflowattributeassignment-getorder.md
  api-reference/beta/api/identityuserflowattributeassignment-setorder.md
  api-reference/beta/api/identityuserflowattributeassignment-update.md
  api-reference/beta/resources/assignmentorder.md
  api-reference/beta/resources/b2cidentityuserflow.md
  api-reference/beta/resources/b2xidentityuserflow.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/identityuserflowattributeassignment.md
  api-reference/beta/resources/userattributevaluesitem.md
  api-reference/beta/toc.yml
  changelog/Microsoft.DirectoryServices.json
  concepts/changelog.md
  concepts/permissions-reference.md
Labels: ready to merge

#10938 Remove accidental .orig file
  concepts/changelog.md.orig
Labels: internal, ready to merge

#10937 Merge to publish.
  api-reference/beta/api/b2cidentityuserflow-list-userattributeassignments.md
  api-reference/beta/api/b2cidentityuserflow-post-userattributeassignments.md
  api-reference/beta/api/b2xidentityuserflow-list-userattributeassignments.md
  api-reference/beta/api/b2xidentityuserflow-post-userattributeassignments.md
  api-reference/beta/api/identitycontainer-post-b2cuserflows.md
  api-reference/beta/api/identityuserflowattributeassignment-delete.md
  api-reference/beta/api/identityuserflowattributeassignment-get.md
  api-reference/beta/api/identityuserflowattributeassignment-getorder.md
  api-reference/beta/api/identityuserflowattributeassignment-setorder.md
  api-reference/beta/api/identityuserflowattributeassignment-update.md
  api-reference/beta/resources/assignmentorder.md
  api-reference/beta/resources/b2cidentityuserflow.md
  api-reference/beta/resources/b2xidentityuserflow.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/identityuserflowattributeassignment.md
  api-reference/beta/resources/requestormanager.md
  api-reference/beta/resources/userattributevaluesitem.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/authorizationpolicy-get.md
  api-reference/v1.0/api/authorizationpolicy-update.md
  api-reference/v1.0/api/cloudcommunications-getpresencesbyuserid.md
  api-reference/v1.0/api/presence-get.md
  api-reference/v1.0/resources/authorizationpolicy.md
  api-reference/v1.0/resources/communications-api-overview.md
  api-reference/v1.0/resources/defaultuserrolepermissions.md
  api-reference/v1.0/resources/presence.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.DirectoryServices.json
  changelog/Microsoft.Skype.Calling.json
  concepts/change-notifications-delivery.md
  concepts/changelog.md
  concepts/permissions-reference.md
  concepts/sdks/choose-authentication-providers.md
  concepts/sdks/create-client.md
  concepts/sdks/sdk-installation.md
  concepts/teams-send-activityfeednotifications.md
  concepts/throttling.md
Labels: internal

#10939 Updated what's new and fixed some links.
  concepts/changelog.md
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: internal

#10941 Fixed link.
  concepts/whats-new-overview.md
Labels: internal

#10942 Publish updates to what's new.
  concepts/changelog.md
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: internal

#10583 Onboarding to webhooks for To Do apis
  api-reference/beta/api/subscription-delete.md
  api-reference/beta/api/subscription-get.md
  api-reference/beta/api/subscription-post-subscriptions.md
  api-reference/beta/api/subscription-update.md
  api-reference/beta/resources/subscription.md
  api-reference/beta/resources/todotask.md
  api-reference/beta/resources/webhooks.md
  changelog/Microsoft.SubscriptionServices.json
  changelog/Microsoft.Todo.json
  concepts/changelog.md
  concepts/webhooks.md
Labels: ready to merge

#10948 Add SharepointIds For File
  concepts/search-concept-files.md
  concepts/search-concept-sort.md
Labels: internal, ready to merge

#10956 Fixing typo
  api-reference/v1.0/resources/relatedcontact.md
Labels: external, ready to merge

#10935 Add reference to AAD data retention policies
  api-reference/beta/resources/azure-ad-auditlog-overview.md
  api-reference/v1.0/resources/azure-ad-auditlog-overview.md
Labels: area: azure/AAD, area: reports, internal, ready to merge

#10571 2020 10 26 mahage e discovery - Custodian
  api-reference/beta/api/custodian-activate.md
  api-reference/beta/api/custodian-get.md
  api-reference/beta/api/custodian-list-sitesources.md
  api-reference/beta/api/custodian-list-unifiedgroupsources.md
  api-reference/beta/api/custodian-list-usersources.md
  api-reference/beta/api/custodian-post-sitesources.md
  api-reference/beta/api/custodian-post-unifiedgroupsources.md
  api-reference/beta/api/custodian-post-usersources.md
  api-reference/beta/api/custodian-release.md
  api-reference/beta/api/custodian-update.md
  api-reference/beta/api/ediscoverycase-close.md
  api-reference/beta/api/ediscoverycase-list-custodians.md
  api-reference/beta/api/ediscoverycase-post-custodians.md
  api-reference/beta/api/ediscoverycase-reopen.md
  api-reference/beta/api/sitesource-delete.md
  api-reference/beta/api/sitesource-get.md
  api-reference/beta/api/unifiedgroupsource-delete.md
  api-reference/beta/api/unifiedgroupsource-get.md
  api-reference/beta/api/usersource-delete.md
  api-reference/beta/api/usersource-get.md
  api-reference/beta/resources/custodian.md
  api-reference/beta/resources/datasource.md
  api-reference/beta/resources/ediscoverycase.md
  api-reference/beta/resources/reviewset.md
  api-reference/beta/resources/reviewsetquery.md
  api-reference/beta/resources/sitesource.md
  api-reference/beta/resources/unifiedgroupsource.md
  api-reference/beta/resources/usersource.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Compliance.Ediscovery.json
  concepts/changelog.md
  concepts/compliance-concept-overview.md
  concepts/toc.yml
Labels: content review, internal

#10174 Created chat-get-allmessages-1212884
  api-reference/beta/api/channels-getallmessages.md
  api-reference/beta/api/chats-getallmessages.md
  api-reference/beta/resources/channel.md
  api-reference/beta/resources/chat.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Teams.Core.json
  concepts/changelog.md
  concepts/whats-new-overview.md
Labels: internal, ready to merge

#10951 Update userscopeteamsappinstallation-get-chat.md
  api-reference/beta/api/userscopeteamsappinstallation-get-chat.md
Labels: external

#10962 Merge to publish.
  api-reference/beta/api/channels-getallmessages.md
  api-reference/beta/api/chats-getallmessages.md
  api-reference/beta/api/custodian-activate.md
  api-reference/beta/api/custodian-get.md
  api-reference/beta/api/custodian-list-sitesources.md
  api-reference/beta/api/custodian-list-unifiedgroupsources.md
  api-reference/beta/api/custodian-list-usersources.md
  api-reference/beta/api/custodian-post-sitesources.md
  api-reference/beta/api/custodian-post-unifiedgroupsources.md
  api-reference/beta/api/custodian-post-usersources.md
  api-reference/beta/api/custodian-release.md
  api-reference/beta/api/custodian-update.md
  api-reference/beta/api/ediscoverycase-close.md
  api-reference/beta/api/ediscoverycase-list-custodians.md
  api-reference/beta/api/ediscoverycase-post-custodians.md
  api-reference/beta/api/ediscoverycase-reopen.md
  api-reference/beta/api/sitesource-delete.md
  api-reference/beta/api/sitesource-get.md
  api-reference/beta/api/subscription-delete.md
  api-reference/beta/api/subscription-get.md
  api-reference/beta/api/subscription-post-subscriptions.md
  api-reference/beta/api/subscription-update.md
  api-reference/beta/api/unifiedgroupsource-delete.md
  api-reference/beta/api/unifiedgroupsource-get.md
  api-reference/beta/api/userscopeteamsappinstallation-get-chat.md
  api-reference/beta/api/usersource-delete.md
  api-reference/beta/api/usersource-get.md
  api-reference/beta/resources/azure-ad-auditlog-overview.md
  api-reference/beta/resources/channel.md
  api-reference/beta/resources/chat.md
  api-reference/beta/resources/custodian.md
  api-reference/beta/resources/datasource.md
  api-reference/beta/resources/ediscoverycase.md
  api-reference/beta/resources/reviewset.md
  api-reference/beta/resources/reviewsetquery.md
  api-reference/beta/resources/sitesource.md
  api-reference/beta/resources/subscription.md
  api-reference/beta/resources/todotask.md
  api-reference/beta/resources/unifiedgroupsource.md
  api-reference/beta/resources/usersource.md
  api-reference/beta/resources/webhooks.md
  api-reference/beta/toc.yml
  api-reference/v1.0/resources/azure-ad-auditlog-overview.md
  api-reference/v1.0/resources/relatedcontact.md
  changelog/Microsoft.Compliance.Ediscovery.json
  changelog/Microsoft.SubscriptionServices.json
  changelog/Microsoft.Teams.Core.json
  changelog/Microsoft.Todo.json
  concepts/changelog.md
  concepts/compliance-concept-overview.md
  concepts/search-concept-files.md
  concepts/search-concept-sort.md
  concepts/toc.yml
  concepts/webhooks.md
  concepts/whats-new-overview.md
Labels: internal

#10976 Added subservice value.
  changelog/Microsoft.Compliance.Ediscovery.json
Labels: internal

#10975 Update presence.md
  api-reference/beta/resources/presence.md
Labels: external

#10974 Update presence.md
  api-reference/v1.0/resources/presence.md
Labels: external

#10985 Update agreement.md
  api-reference/beta/resources/agreement.md
Labels: external

#10789 Add abort job action, redirect configuration and HasPhysicalDevice properties
  api-reference/beta/api/printjob-abort.md
  api-reference/beta/api/printjob-cancel.md
  api-reference/beta/api/printjob-redirect.md
  api-reference/beta/resources/printer.md
  changelog/Microsoft.PrintService.json
  concepts/changelog.md
Labels: area: universal print, internal, ready to merge

#10599 Add email OTP to auth methods policy config
  api-reference/beta/api/emailauthenticationmethodconfiguration-delete.md
  api-reference/beta/api/emailauthenticationmethodconfiguration-get.md
  api-reference/beta/api/emailauthenticationmethodconfiguration-update.md
  api-reference/beta/resources/emailauthenticationmethodconfiguration.md
  api-reference/beta/resources/enums.md
  api-reference/beta/toc.yml
  changelog/Microsoft.DirectoryServices.json
  concepts/changelog.md
Labels: internal, ready to merge

#10729 Update enum types in printerProcessingStateDetail
  api-reference/beta/resources/printerstatus.md
  changelog/Microsoft.PrintService.json
  concepts/changelog.md
Labels: area: universal print, ready to merge

#10991 Update compliance-concept-overview.md
  concepts/compliance-concept-overview.md
Labels: external, ready to merge

#10997 Merge to publish.
  api-reference/beta/api/emailauthenticationmethodconfiguration-delete.md
  api-reference/beta/api/emailauthenticationmethodconfiguration-get.md
  api-reference/beta/api/emailauthenticationmethodconfiguration-update.md
  api-reference/beta/api/printjob-abort.md
  api-reference/beta/api/printjob-cancel.md
  api-reference/beta/api/printjob-redirect.md
  api-reference/beta/resources/agreement.md
  api-reference/beta/resources/emailauthenticationmethodconfiguration.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/printer.md
  api-reference/beta/resources/printerstatus.md
  api-reference/beta/toc.yml
  changelog/Microsoft.DirectoryServices.json
  changelog/Microsoft.PrintService.json
  concepts/changelog.md
  concepts/compliance-concept-overview.md
Labels: internal

#10986 Teams: Team Membership API - Bulk and filtering
  api-reference/beta/api/chat-delete-installedapps.md
  api-reference/beta/api/chat-delete-tabs.md
  api-reference/beta/api/chat-list-installedapps.md
  api-reference/beta/api/chat-list-tabs.md
  api-reference/beta/api/chat-patch-tabs.md
  api-reference/beta/api/chat-post-installedapps.md
  api-reference/beta/api/chat-post-tabs.md
  api-reference/beta/api/chat-teamsappinstallation-upgrade.md
  api-reference/beta/api/conversationmembers-add.md
  api-reference/beta/api/team-list-members.md
  api-reference/beta/api/team-post-members.md
  api-reference/beta/resources/aaduserconversationmemberresult.md
  api-reference/beta/resources/actionresultpart.md
  api-reference/beta/resources/channel.md
  api-reference/beta/resources/chat.md
  api-reference/beta/resources/conversationmember.md
  api-reference/beta/resources/publicerror.md
  api-reference/beta/resources/publicerrordetail.md
  api-reference/beta/resources/publicinnererror.md
  api-reference/beta/resources/team.md
  api-reference/beta/resources/teamsappinstallation.md
  api-reference/beta/resources/teamstab.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/team-list-members.md
  api-reference/v1.0/api/team-post-members.md
  api-reference/v1.0/resources/channel.md
  api-reference/v1.0/resources/team.md
  api-reference/v1.0/resources/teamsappinstallation.md
  api-reference/v1.0/resources/teamstab.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.Teams.Core.json
  concepts/changelog.md
  concepts/known-issues.md
Labels: internal, ready to merge

#10999 Update agreementfile.md
  api-reference/beta/resources/agreementfile.md
Labels: external

#10930 MGT 2.0 Release Docs Update
  concepts/toc.yml
  concepts/toolkit/components/agenda.md
  concepts/toolkit/components/get.md
  concepts/toolkit/components/login.md
  concepts/toolkit/components/people-picker.md
  concepts/toolkit/components/people.md
  concepts/toolkit/components/person-card.md
  concepts/toolkit/components/person.md
  concepts/toolkit/components/tasks.md
  concepts/toolkit/components/teams-channel-picker.md
  concepts/toolkit/components/todo.md
  concepts/toolkit/customize-components/cache.md
  concepts/toolkit/customize-components/localization.md
  concepts/toolkit/customize-components/right-to-left.md
  concepts/toolkit/customize-components/style.md
  concepts/toolkit/customize-components/templates.md
  concepts/toolkit/get-started/add-aad-app-registration.md
  concepts/toolkit/get-started/build-a-microsoft-teams-tab.md
  concepts/toolkit/get-started/build-a-sharepoint-web-part.md
  concepts/toolkit/get-started/build-a-web-app.md
  concepts/toolkit/get-started/mgt-react.md
  concepts/toolkit/get-started/overview.md
  concepts/toolkit/get-started/use-toolkit-with-angular.md
  concepts/toolkit/get-started/use-toolkit-with-react.md
  concepts/toolkit/images/indexedDBpanel.png
  concepts/toolkit/images/rightToLeft.png
  concepts/toolkit/overview.md
  concepts/toolkit/providers/msal.md
  concepts/toolkit/providers/providers.md
  concepts/toolkit/providers/proxy.md
  concepts/toolkit/providers/sharepoint.md
  concepts/toolkit/providers/teams.md
  concepts/toolkit/style.md
Labels: internal, ready to merge

#10817 Update type of allowedUsers and allowedGroups API
  api-reference/beta/api/printershare-list-allowedgroups.md
  api-reference/beta/api/printershare-list-allowedusers.md
  api-reference/beta/resources/printershare.md
  changelog/Microsoft.PrintService.json
  concepts/changelog.md
Labels: area: universal print, internal, ready to merge

#10590 Remove RPO caveat
  concepts/known-issues.md
Labels: internal, ready to merge

#11015 Added Office and Teams tutorials
  concepts/toc.yml
  concepts/tutorials.yml
Labels: internal, ready to merge

#11005 Update agreementfilelocalization.md
  api-reference/beta/resources/agreementfilelocalization.md
Labels: external

#10984 [MGT] Updated teams provider docs, react starter, and fixed few script links
  concepts/toolkit/get-started/build-a-web-app.md
  concepts/toolkit/get-started/overview.md
  concepts/toolkit/get-started/use-toolkit-with-react.md
  concepts/toolkit/providers/teams.md
Labels: ready to merge

#10915 tutorial - identify and remediate risk
  concepts/images/tutorial-riskdetection-api/accept-permissions.png
  concepts/images/tutorial-riskdetection-api/conditionalaccess-policy.png
  concepts/images/tutorial-riskdetection-api/permissions-consent.png
  concepts/images/tutorial-riskdetection-api/set-permissions.png
  concepts/toc.yml
  concepts/tutorial-riskdetection-api.md
Labels: area: azure/AAD, internal, ready to merge

#10943 Change floorNumber to floor and roomNumber to roomName
  api-reference/beta/resources/printerlocation.md
  changelog/Microsoft.PrintService.json
  concepts/changelog.md
Labels: area: universal print, internal, ready to merge

#11000 Link legal age group Enums to age properties
  api-reference/beta/resources/user.md
  api-reference/v1.0/resources/user.md
Labels: area: users, internal, ready to merge

#11006 Updated toc to remove entries not needed in the main Table of Content
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
Labels: internal, ready to merge

#11023 Merge to publish.
  api-reference/beta/resources/agreementfilelocalization.md
  api-reference/beta/resources/printerlocation.md
  api-reference/beta/resources/user.md
  api-reference/beta/toc.yml
  api-reference/v1.0/resources/user.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.PrintService.json
  concepts/changelog.md
  concepts/images/tutorial-riskdetection-api/accept-permissions.png
  concepts/images/tutorial-riskdetection-api/conditionalaccess-policy.png
  concepts/images/tutorial-riskdetection-api/permissions-consent.png
  concepts/images/tutorial-riskdetection-api/set-permissions.png
  concepts/toc.yml
  concepts/toolkit/get-started/build-a-web-app.md
  concepts/toolkit/get-started/overview.md
  concepts/toolkit/get-started/use-toolkit-with-react.md
  concepts/toolkit/providers/teams.md
  concepts/tutorial-riskdetection-api.md
  concepts/tutorials.yml
Labels: internal

#11031 Update presence.md
  api-reference/beta/resources/presence.md
Labels: external

#11030 Update presence.md
  api-reference/v1.0/resources/presence.md
Labels: external

#11029 Fix link
  concepts/teams-concept-overview.md
Labels: external

#10994 Add 2 new, optional properties to educationAssignment Object
  api-reference/beta/api/educationassignment-get.md
  api-reference/beta/api/educationassignment-update.md
  api-reference/beta/api/educationclass-list-assignments.md
  api-reference/beta/api/educationclass-post-assignments.md
  api-reference/beta/resources/educationassignment.md
  api-reference/beta/resources/educationassignmentrecipient.md
  api-reference/beta/resources/enums.md
  changelog/Microsoft.EducationAssignment.json
  concepts/changelog.md
Labels: external

#11036 Merge to publish.
  api-reference/beta/api/educationassignment-get.md
  api-reference/beta/api/educationassignment-update.md
  api-reference/beta/api/educationclass-list-assignments.md
  api-reference/beta/api/educationclass-post-assignments.md
  api-reference/beta/resources/educationassignment.md
  api-reference/beta/resources/educationassignmentrecipient.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/presence.md
  api-reference/v1.0/resources/presence.md
  changelog/Microsoft.EducationAssignment.json
  concepts/changelog.md
  concepts/teams-concept-overview.md
Labels: internal

#11040 Corrected Typo
  api-reference/v1.0/resources/user.md
Labels: external

#11042 Teams Graph: Change names in examples.
  api-reference/beta/api/channel-list-members.md
  api-reference/v1.0/api/channel-list-members.md
Labels: internal, ready to merge

#11033 Updating docs to add example for atmention filtering
  api-reference/beta/api/chat-post-message.md
  api-reference/v1.0/toc.yml
  concepts/teams-changenotifications-chatmessage.md
Labels: internal, ready to merge

#11056 Typo on Access Review docs
  api-reference/beta/api/accessreviewscheduledefinition-create.md
  api-reference/beta/resources/accessreviewsv2-root.md
Labels: do not merge, internal

#11050 Update migrate-azure-ad-graph-property-differences.md
  concepts/migrate-azure-ad-graph-property-differences.md
Labels: external

#11046 Update usersource.md
  api-reference/beta/resources/usersource.md
Labels: external

#11038 Update userscopeteamsappinstallation-get-chat.md
  api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md
Labels: external

#11017 add update print job configuration page
  api-reference/beta/api/printjob-update-configuration.md
  api-reference/beta/toc.yml
  changelog/Microsoft.PrintService.json
  concepts/changelog.md
Labels: area: universal print, internal, ready to merge

#10918 User flow language customization documentation
  api-reference/beta/api/b2cidentityuserflow-get.md
  api-reference/beta/api/b2cidentityuserflow-list-languages.md
  api-reference/beta/api/b2cidentityuserflow-put-languages.md
  api-reference/beta/api/b2cidentityuserflow-update.md
  api-reference/beta/api/b2xidentityuserflow-list-languages.md
  api-reference/beta/api/identitycontainer-list-b2cuserflows.md
  api-reference/beta/api/identitycontainer-post-b2cuserflows.md
  api-reference/beta/api/userflowlanguageconfiguration-delete.md
  api-reference/beta/api/userflowlanguageconfiguration-get.md
  api-reference/beta/api/userflowlanguageconfiguration-list-defaultpages.md
  api-reference/beta/api/userflowlanguageconfiguration-list-overridespages.md
  api-reference/beta/api/userflowlanguagepage-delete.md
  api-reference/beta/api/userflowlanguagepage-get.md
  api-reference/beta/api/userflowlanguagepage-put.md
  api-reference/beta/resources/b2cidentityuserflow.md
  api-reference/beta/resources/b2xidentityuserflow.md
  api-reference/beta/resources/userflowlanguageconfiguration.md
  api-reference/beta/resources/userflowlanguagepage.md
  api-reference/beta/toc.yml
  changelog/Microsoft.DirectoryServices.json
  concepts/changelog.md
Labels: area: azure/AAD, ready to merge

#10954 chat member CRUD doc update
  api-reference/beta/api/chat-get-members.md
  api-reference/beta/api/chat-list-members.md
  api-reference/beta/api/chat-post-members.md
  api-reference/beta/api/conversationmember-add.md
  api-reference/beta/api/conversationmember-delete.md
  api-reference/beta/resources/aaduserconversationmember.md
  api-reference/beta/resources/chat.md
  api-reference/beta/resources/conversationmember.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Teams.Core.json
  concepts/changelog.md
  concepts/known-issues.md
Labels: changes requested, internal, ready to merge

#10871 Update cloudPCStatus enum members
  api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md
  api-reference/beta/resources/cloudpc.md
  api-reference/beta/resources/enums.md
  changelog/Microsoft.CloudManagedDesktop.json
  concepts/changelog.md
Labels: internal, ready to merge

#10955 chat CRUD doc update
  api-reference/beta/api/chat-get.md
  api-reference/beta/api/chat-list.md
  api-reference/beta/api/chat-patch.md
  api-reference/beta/api/chat-post.md
  api-reference/beta/api/user-list-chats.md
  api-reference/beta/resources/chat.md
  api-reference/beta/resources/chatmessage.md
  api-reference/beta/resources/enums.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Teams.Core.json
  concepts/changelog.md
Labels: changes requested, internal, ready to merge

#11026 Teams: Added teamworkBot and associated APIs and examples.
  api-reference/beta/api/appcatalogs-list-teamsapps.md
  api-reference/beta/api/chat-list-installedapps.md
  api-reference/beta/api/team-list-installedapps.md
  api-reference/beta/api/team-list-members.md
  api-reference/beta/api/teamworkbot-get.md
  api-reference/beta/api/userteamwork-list-installedapps.md
  api-reference/beta/resources/teamsapp.md
  api-reference/beta/resources/teamsappdefinition.md
  api-reference/beta/resources/teamworkbot.md
  api-reference/v1.0/resources/teamsapp.md
  changelog/Microsoft.Teams.Core.json
  concepts/changelog.md
Labels: changes requested, internal, ready to merge

#10978 update channel moderation doc
  api-reference/beta/api/channel-get.md
  api-reference/beta/api/channel-patch.md
  api-reference/beta/api/channel-post.md
  api-reference/beta/resources/channel.md
  api-reference/beta/resources/channelmoderationsettings.md
  api-reference/beta/resources/enums.md
  changelog/Microsoft.Teams.Core.json
  concepts/changelog.md
Labels: content review, internal, ready to merge

#11064 Update virtualendpoint-geteffectivepermissions.md
  api-reference/beta/api/virtualendpoint-geteffectivepermissions.md
Labels: external

#11063 Update reviewsetquery-post.md
  api-reference/beta/api/reviewsetquery-post.md
Labels: external

#11069 Added remove chat member method.
  api-reference/beta/api/chat-delete-members.md
  api-reference/beta/resources/aaduserconversationmember.md
  api-reference/beta/resources/channel.md
  api-reference/beta/resources/chat.md
  api-reference/beta/resources/conversationmember.md
  api-reference/beta/resources/team.md
  api-reference/beta/toc.yml
  api-reference/v1.0/resources/aaduserconversationmember.md
  api-reference/v1.0/resources/channel.md
  api-reference/v1.0/resources/conversationmember.md
  api-reference/v1.0/resources/team.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.Teams.Core.json
  concepts/changelog.md
  concepts/known-issues.md
Labels: internal, ready to merge

#11074 Document siteId and make clarifications.
  api-reference/beta/resources/driveitem.md
  api-reference/beta/resources/itemreference.md
  api-reference/beta/resources/listitem.md
  api-reference/v1.0/resources/driveitem.md
  api-reference/v1.0/resources/itemreference.md
  api-reference/v1.0/resources/listitem.md
Labels: internal

#11076 Merge to publish.
  api-reference/beta/api/chat-delete-members.md
  api-reference/beta/api/reviewsetquery-post.md
  api-reference/beta/api/virtualendpoint-geteffectivepermissions.md
  api-reference/beta/resources/aaduserconversationmember.md
  api-reference/beta/resources/channel.md
  api-reference/beta/resources/chat.md
  api-reference/beta/resources/conversationmember.md
  api-reference/beta/resources/driveitem.md
  api-reference/beta/resources/itemreference.md
  api-reference/beta/resources/listitem.md
  api-reference/beta/resources/team.md
  api-reference/beta/toc.yml
  api-reference/v1.0/resources/aaduserconversationmember.md
  api-reference/v1.0/resources/channel.md
  api-reference/v1.0/resources/conversationmember.md
  api-reference/v1.0/resources/driveitem.md
  api-reference/v1.0/resources/itemreference.md
  api-reference/v1.0/resources/listitem.md
  api-reference/v1.0/resources/team.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.Teams.Core.json
  concepts/changelog.md
  concepts/known-issues.md
Labels: internal

#9727 Added Documentation for hideAttendees in Beta
  api-reference/beta/api/calendar-post-events.md
  api-reference/beta/api/event-get.md
  api-reference/beta/api/event-update.md
  api-reference/beta/api/user-post-events.md
  api-reference/beta/resources/event.md
  changelog/Microsoft.Exchange.json
  concepts/changelog.md
Labels: ready to merge

#11059 Deleted file.
  .github/workflows/changelog-validation.yml
  changelog/changelog.json
Labels: internal, ready to merge

#11043 Light up outbound PSTN call samples for invite, transfer and forward APIs
  api-reference/beta/api/application-post-calls.md
  api-reference/beta/api/call-redirect.md
  api-reference/beta/api/call-transfer.md
  api-reference/beta/api/participant-invite.md
Labels: internal, ready to merge

#10693 Added documentation for hide attendees property in v1.0
  api-reference/v1.0/api/calendar-post-events.md
  api-reference/v1.0/api/event-get.md
  api-reference/v1.0/api/event-update.md
  api-reference/v1.0/api/user-post-events.md
  api-reference/v1.0/resources/event.md
  changelog/Microsoft.Exchange.json
  concepts/changelog.md
Labels: content review

#11083 [MGT] Fixed typos in provider docs
  concepts/toolkit/providers/providers.md
Labels: ready to merge

#11078 Remove unwanted new line from requests in affected files
  api-reference/beta/api/calendargroup-post-calendars.md
  api-reference/beta/api/connector-post-memberof.md
  api-reference/beta/api/connectorgroup-post-applications.md
  api-reference/beta/api/featurerolloutpolicy-update.md
  api-reference/beta/api/identityuserflowattributeassignment-setorder.md
  api-reference/beta/api/permission-revokegrants.md
  api-reference/beta/api/synchronization-synchronizationjob-provision-on-demand.md
  api-reference/beta/api/userteamwork-sendactivitynotification.md
  api-reference/v1.0/api/calendargroup-post-calendars.md
  api-reference/v1.0/api/directoryobject-getavailableextensionproperties.md
  api-reference/v1.0/api/riskyuser-confirmcompromised.md
  api-reference/v1.0/api/riskyuser-dismiss.md
Labels: internal, ready to merge

#10992 recreating changes on new branch
  api-reference/beta/api/accesspackageassignmentpolicy-post.md
  api-reference/beta/api/accesspackageassignmentpolicy-update.md
  api-reference/beta/api/accesspackageassignmentrequest-post.md
  api-reference/beta/resources/accesspackageanswer.md
  api-reference/beta/resources/accesspackageanswerchoice.md
  api-reference/beta/resources/accesspackageanswerstring.md
  api-reference/beta/resources/accesspackageassignmentpolicy.md
  api-reference/beta/resources/accesspackageassignmentrequest.md
  api-reference/beta/resources/accesspackagelocalizedcontent.md
  api-reference/beta/resources/accesspackagelocalizedtext.md
  api-reference/beta/resources/accesspackagemultiplechoicequestion.md
  api-reference/beta/resources/accesspackagequestion.md
  api-reference/beta/resources/accesspackagetextinputquestion.md
  api-reference/beta/resources/entitlementmanagement-root.md
  changelog/Microsoft.DirectoryServices.json
  concepts/changelog.md
Labels: area: azure/AAD, internal, ready to merge

#10924 API Connectors B2C/External Identities
  api-reference/beta/api/b2cidentityuserflow-get-apiconnectorconfiguration.md
  api-reference/beta/api/b2cidentityuserflow-put-apiconnectorconfiguration.md
  api-reference/beta/api/b2xidentityuserflow-get-apiconnectorconfiguration.md
  api-reference/beta/api/b2xidentityuserflow-put-apiconnectorconfiguration.md
  api-reference/beta/api/identityapiconnector-create.md
  api-reference/beta/api/identityapiconnector-delete.md
  api-reference/beta/api/identityapiconnector-get.md
  api-reference/beta/api/identityapiconnector-list.md
  api-reference/beta/api/identityapiconnector-update.md
  api-reference/beta/api/identitycontainer-post-b2cuserflows.md
  api-reference/beta/api/identitycontainer-post-b2xuserflows.md
  api-reference/beta/resources/apiauthenticationconfigurationbase.md
  api-reference/beta/resources/b2cidentityuserflow.md
  api-reference/beta/resources/b2xidentityuserflow.md
  api-reference/beta/resources/basicauthentication.md
  api-reference/beta/resources/identityapiconnector.md
  api-reference/beta/resources/userflowapiconnectorconfiguration.md
  api-reference/beta/toc.yml
  changelog/Microsoft.DirectoryServices.json
  concepts/changelog.md
Labels: internal, ready to merge

#10224 Authentication events policy docs for user flow invocation
  api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md
  api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md
  api-reference/beta/api/authenticationlistener-delete.md
  api-reference/beta/api/authenticationlistener-get.md
  api-reference/beta/api/authenticationlistener-put.md
  api-reference/beta/api/authenticationlistener-update.md
  api-reference/beta/resources/authenticationeventspolicy.md
  api-reference/beta/resources/authenticationlistener.md
  api-reference/beta/resources/authenticationsourcefilter.md
  api-reference/beta/resources/invokeuserflowlistener.md
  api-reference/beta/toc.yml
  changelog/Microsoft.DirectoryServices.json
  concepts/changelog.md
Labels: ready to merge

#9852 added two event methods to v1.0
  api-reference/beta/resources/event.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/event-cancel.md
  api-reference/v1.0/api/event-forward.md
  api-reference/v1.0/resources/event.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.Exchange.json
  concepts/changelog.md
Labels: ready to merge

#11085 Publish updates to v1 of calendar API.
  api-reference/beta/resources/event.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/calendar-get.md
  api-reference/v1.0/api/calendar-post-events.md
  api-reference/v1.0/api/calendar-update.md
  api-reference/v1.0/api/event-cancel.md
  api-reference/v1.0/api/event-delta.md
  api-reference/v1.0/api/event-forward.md
  api-reference/v1.0/api/group-get-event.md
  api-reference/v1.0/api/group-post-events.md
  api-reference/v1.0/api/user-list-calendars.md
  api-reference/v1.0/api/user-post-calendars.md
  api-reference/v1.0/api/user-post-events.md
  api-reference/v1.0/resources/calendar.md
  api-reference/v1.0/resources/event.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.Exchange.json
  concepts/changelog.md
Labels: internal

#11087 Added what's new for the last 2 weeks.
  api-reference/beta/toc.yml
  concepts/changelog.md
  concepts/toc.yml
  concepts/whats-new-overview.md
Labels: internal

#11088 Publish majority of what's new from the last 2 weeks.
  api-reference/beta/toc.yml
  concepts/changelog.md
  concepts/toc.yml
  concepts/whats-new-overview.md
Labels: internal

#11091 Added what's new with Teams.
  concepts/changelog.md
  concepts/whats-new-overview.md
Labels: internal

#11092 Publish what's new in the Teams API.
  concepts/changelog.md
  concepts/whats-new-overview.md
Labels: do not merge, internal

#11098 Fix outdated links.
  api-reference/beta/api/channel-patch.md
  api-reference/beta/resources/channelmoderationsettings.md
  api-reference/beta/resources/chat.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Teams.Core.json
  concepts/changelog.md
Labels: internal, ready to merge
