Repository microsoftgraph/microsoft-graph-docs, pull requests merged in 2020-09, with the labels that each got.

#9678 update entitlementmanagement documentation for useradd and resource roles
  api-reference/beta/api/accesspackageassignmentrequest-post.md
  api-reference/beta/resources/accesspackageassignment.md
  api-reference/beta/resources/accesspackageassignmentrequest.md
  api-reference/beta/resources/accesspackageassignmentresourcerole.md
  api-reference/beta/resources/accesspackageresource.md
  api-reference/beta/resources/accesspackageresourcerole.md
Labels: area: azure/AAD, ready to merge

#9240 Userflow document creation
  api-reference/beta/api/b2cuserflow-post-b2cuserflows.md
  api-reference/beta/api/b2cuserflows-delete-identityprovider.md
  api-reference/beta/api/b2cuserflows-delete.md
  api-reference/beta/api/b2cuserflows-get.md
  api-reference/beta/api/b2cuserflows-list-identityproviders.md
  api-reference/beta/api/b2cuserflows-list.md
  api-reference/beta/api/b2cuserflows-update-identityprovider.md
  api-reference/beta/api/b2xuserflow-post-b2xuserflows.md
  api-reference/beta/api/b2xuserflows-delete-identityprovider.md
  api-reference/beta/api/b2xuserflows-delete.md
  api-reference/beta/api/b2xuserflows-get.md
  api-reference/beta/api/b2xuserflows-list-identityproviders.md
  api-reference/beta/api/b2xuserflows-list.md
  api-reference/beta/api/b2xuserflows-update-identityprovider.md
  api-reference/beta/api/identityprovider-get.md
  api-reference/beta/api/identityprovider-list.md
  api-reference/beta/api/identityprovider-post-identityproviders.md
  api-reference/beta/resources/b2cuserflows.md
  api-reference/beta/resources/b2xuserflows.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/identityprovider.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: ready to merge

#9721 fix for git issue 8581
  api-reference/v1.0/resources/user.md
  concepts/changelog.md
Labels: area: azure/AAD, ready to merge

#9717 [Universal Print] Adding clarifications around print job redirection
  api-reference/beta/api/printjob-redirect.md
  concepts/universal-print-concept-overview.md
Labels: area: universal print, ready to merge

#9719 fix for git issue 9084
  api-reference/beta/api/user-get.md
  api-reference/v1.0/api/user-get.md
Labels: area: azure/AAD, ready to merge

#9742 fix for git issue 7979
  api-reference/beta/resources/user.md
  api-reference/v1.0/resources/user.md
Labels: area: azure/AAD, ready to merge

#9653 Updating mail property of user as writable.
  api-reference/beta/api/user-update.md
  api-reference/beta/resources/user.md
  api-reference/v1.0/api/user-update.md
  api-reference/v1.0/resources/user.md
  concepts/changelog.md
Labels: ready to merge

#8918 Tutorial: Create an access package
  concepts/images/tutorial-access-package-api/consent-for-organization.png
  concepts/images/tutorial-access-package-api/set-permissions.png
  concepts/images/tutorial-access-package-api/set-user-permission.png
  concepts/toc.yml
  concepts/tutorial-access-package-api.md
Labels: area: azure/AAD, ready to merge

#9760 fix for git issue 9629
  api-reference/beta/api/serviceprincipal-post-claimsmappingpolicies.md
Labels: area: azure/AAD, ready to merge

#9761 fix for git issue 9510
  api-reference/beta/api/application-addpassword.md
  api-reference/v1.0/api/application-addpassword.md
Labels: area: azure/AAD, ready to merge

#9762 fix for git issue 9097
  .openpublishing.redirection.json
  api-reference/beta/api/application-add-password.md
Labels: area: azure/AAD, ready to merge

#9772 Update team-get-photo.md
  api-reference/beta/api/team-get-photo.md
Labels: area: teams, ready to merge

#9763 Change title of page from "Delete Member" to "Remove Member"
  api-reference/beta/api/team-delete-members.md
Labels: ready to merge

#9683 Fixing update photo documentation for Team
  api-reference/beta/api/profilephoto-update.md
  api-reference/beta/api/team-update-photo.md
  api-reference/beta/resources/team.md
  api-reference/beta/toc.yml
Labels: ready to merge

#9786 fix for git issue 9696
  api-reference/v1.0/api/group-post-members.md
Labels: area: azure/AAD, ready to merge

#9784 Tutorials update
  concepts/toc.yml
  concepts/tutorials.yml
Labels: ready to merge

#9789 fix for git issue9531
  api-reference/beta/api/group-post-members.md
  api-reference/v1.0/api/group-post-members.md
Labels: area: azure/AAD, ready to merge

#9791 Documenting new query parameter support for List printJobs
  api-reference/beta/api/printer-list-jobs.md
  concepts/changelog.md
Labels: area: universal print, changelog, ready to merge

#9580 add import messages APIs
  api-reference/beta/api/channel-post.md
  api-reference/beta/api/team-post.md
  api-reference/beta/resources/channel.md
  api-reference/beta/resources/team.md
  concepts/changelog.md
  concepts/permissions-reference.md
Labels: ready to merge

#9831 added redirect
  .openpublishing.redirection.json
Labels: area: azure/AAD, ready to merge

#9515 introduce schedule to entitlement management access package assignment
  api-reference/beta/resources/accesspackageassignment.md
  api-reference/beta/resources/accesspackageassignmentrequest.md
  api-reference/beta/resources/expirationpattern.md
  api-reference/beta/resources/requestschedule.md
  concepts/changelog.md
Labels: area: azure/AAD, changelog, ready to merge

#9630 [OnlineMeetings] meeting options beta doc updates
  api-reference/beta/api/onlinemeeting-get.md
  api-reference/beta/resources/lobbyBypassSettings.md
  api-reference/beta/resources/onlinemeeting.md
  concepts/changelog.md
Labels: ready to merge

#9769 Update entitlement management to add link to first tutorial
  api-reference/beta/resources/entitlementmanagement-root.md
Labels: area: azure/AAD, ready to merge

#9848 Merge to publish.
  api-reference/beta/api/channel-post-message.md
  api-reference/beta/api/onlinemeeting-get.md
  api-reference/beta/resources/entitlementmanagement-root.md
  api-reference/beta/resources/lobbyBypassSettings.md
  api-reference/beta/resources/onlinemeeting.md
  concepts/changelog.md
Labels: external

#9501 Explicit `userAgentApplication` passed to mgt
  concepts/toolkit/providers/msal.md
Labels: do not merge, internal

#9861 Update externalconnection-post-schema.md
  api-reference/beta/api/externalconnection-post-schema.md
Labels: external

#9871 link fix
  concepts/teams-protected-apis.md
Labels: area: teams, internal, ready to merge

#9867 Update externalitem-update.md
  api-reference/beta/api/externalitem-update.md
Labels: external

#9865 Update externalconnection-put-items.md
  api-reference/beta/api/externalconnection-put-items.md
Labels: external

#9864 Update externalitem-get.md
  api-reference/beta/api/externalitem-get.md
Labels: external

#9847 Explaining $search behavior better for AAD Objects
  concepts/query-parameters.md
Labels: ready to merge

#9859 Remove references to CallRecords.Read.PstnCalls permission
  api-reference/beta/api/callrecords-callrecord-getdirectroutingcalls.md
  api-reference/beta/api/callrecords-callrecord-getpstncalls.md
  concepts/permissions-reference.md
Labels: area: cloud communications, internal, ready to merge

#9849 Patch cancel media processing v1 documents
  api-reference/v1.0/resources/call.md
  api-reference/v1.0/resources/calls-api-ivr-overview.md
Labels: internal, ready to merge

#9855 Update teamstabconfiguration.md
  api-reference/v1.0/resources/teamstabconfiguration.md
Labels: do not merge, internal

#9854 Update teamstabconfiguration.md
  api-reference/beta/resources/teamstabconfiguration.md
Labels: do not merge, internal

#9872 Merge to publish.
  .github/workflows/changelog-validation.yml
  api-reference/beta/api/callrecords-callrecord-getdirectroutingcalls.md
  api-reference/beta/api/callrecords-callrecord-getpstncalls.md
  api-reference/beta/api/externalconnection-post-schema.md
  api-reference/beta/api/externalconnection-put-items.md
  api-reference/beta/api/externalitem-get.md
  api-reference/beta/api/externalitem-update.md
  api-reference/beta/resources/teamstabconfiguration.md
  api-reference/v1.0/resources/call.md
  api-reference/v1.0/resources/calls-api-ivr-overview.md
  api-reference/v1.0/resources/teamstabconfiguration.md
  changelog/Changelog.Schema.json
  changelog/Manual.NonWorkloadChanges.json
  changelog/Microsoft.AAD.Reporting.json
  changelog/Microsoft.Analytics.json
  changelog/Microsoft.DirectoryServices.json
  changelog/Microsoft.EducationAssignment.json
  changelog/Microsoft.Excel.json
  changelog/Microsoft.Exchange.json
  changelog/Microsoft.FileServices.json
  changelog/Microsoft.Intune.json
  changelog/Microsoft.NAV.json
  changelog/Microsoft.Office.Tasks.json
  changelog/Microsoft.OneNote.json
  changelog/Microsoft.Search.json
  changelog/Microsoft.SharePoint.json
  changelog/Microsoft.Skype.Calling.json
  changelog/Microsoft.SubscriptionServices.json
  changelog/Microsoft.Teams.Core.json
  changelog/Microsoft.ThreatAssessment.json
  changelog/changelog.json
  concepts/permissions-reference.md
  concepts/query-parameters.md
  concepts/teams-protected-apis.md
  concepts/throttling.md
Labels: external

#9880 Added what's new in the recent weeks.
  concepts/changelog.md
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: external

#9881 Publish updates to what's new.
  concepts/changelog.md
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: external

#9873 Update workbook-best-practice.md
  concepts/workbook-best-practice.md
Labels: area: excel, internal, ready to merge

#9897 Update whats-new-overview.md
  concepts/whats-new-overview.md
Labels: do not merge, internal

#9879 Indefinite article grammar correction
  api-reference/v1.0/resources/file.md
Labels: external

#9901 Update createOrGet examples
  api-reference/beta/api/onlinemeeting-createorget.md
  api-reference/v1.0/api/onlinemeeting-createorget.md
Labels: internal, ready to merge

#9902 Merge to publish.
  api-reference/beta/api/onlinemeeting-createorget.md
  api-reference/v1.0/api/onlinemeeting-createorget.md
  api-reference/v1.0/resources/file.md
  concepts/whats-new-overview.md
  concepts/workbook-best-practice.md
Labels: internal

#9917 fix v1 permissions for listing channels
  api-reference/v1.0/api/channel-list.md
Labels: area: teams, external, ready to merge

#9922 Update driveitem-preview.md
  api-reference/beta/api/driveitem-preview.md
  api-reference/v1.0/api/driveitem-preview.md
Labels: ready to merge

#9927 Update teams-list-all-teams.md
  concepts/teams-list-all-teams.md
Labels: external

#9726 Updated documents for policy-based app token APIs
  api-reference/beta/api/application-post-onlinemeetings.md
  api-reference/beta/api/onlinemeeting-createorget.md
  api-reference/beta/api/onlinemeeting-delete.md
  api-reference/beta/api/onlinemeeting-get.md
  api-reference/beta/api/onlinemeeting-update.md
  concepts/changelog.md
  concepts/cloud-communication-online-meeting-application-access-policy.md
  concepts/permissions-reference.md
  concepts/toc.yml
Labels: ready to merge

#9766 "requires review" is only in beta at the moment
  api-reference/v1.0/api/teamsapp-publish.md
Labels: external, ready to merge, review requested

#9767 "requires review" is only in beta at the moment
  api-reference/v1.0/api/teamsapp-list.md
Labels: external, ready to merge, review requested

#9572 [Permissions] Adding our ShortNotes scopes to list of permissions
  concepts/permissions-reference.md
Labels: ready to merge

#9768 "requires review" is only in beta at the moment
  api-reference/v1.0/api/teamsapp-update.md
Labels: external, ready to merge, review requested

#9947 Fixed doc links
  api-reference/beta/api/application-post-onlinemeetings.md
  api-reference/beta/api/onlinemeeting-createorget.md
  api-reference/beta/api/onlinemeeting-delete.md
  api-reference/beta/api/onlinemeeting-get.md
  api-reference/beta/api/onlinemeeting-update.md
Labels: internal, ready to merge

#9858 Updated the JSON example to include the criteria
  api-reference/beta/resources/synchronization-synchronizationjobrestartcriteria.md
Labels: area: azure/AAD, external, ready to merge

#9680 Admin units API from beta to v1
  api-reference/v1.0/api/administrativeunit-delete-members.md
  api-reference/v1.0/api/administrativeunit-delete-scopedrolemembers.md
  api-reference/v1.0/api/administrativeunit-delete.md
  api-reference/v1.0/api/administrativeunit-get-members.md
  api-reference/v1.0/api/administrativeunit-get-scopedrolemembers.md
  api-reference/v1.0/api/administrativeunit-get.md
  api-reference/v1.0/api/administrativeunit-list-members.md
  api-reference/v1.0/api/administrativeunit-list-scopedrolemembers.md
  api-reference/v1.0/api/administrativeunit-list.md
  api-reference/v1.0/api/administrativeunit-post-administrativeunits.md
  api-reference/v1.0/api/administrativeunit-post-members.md
  api-reference/v1.0/api/administrativeunit-post-scopedrolemembers.md
  api-reference/v1.0/api/administrativeunit-update.md
  api-reference/v1.0/resources/administrativeunit.md
  api-reference/v1.0/resources/scopedrolemembership.md
  api-reference/v1.0/toc.yml
  concepts/changelog.md
Labels: area: azure/AAD, ready to merge

#9943 Update chatmessagehostedcontent.md
  api-reference/beta/resources/chatmessagehostedcontent.md
Labels: external

#9946 Updating webhook resources for Teams in v1
  api-reference/v1.0/resources/webhooks.md
Labels: changes requested, internal, ready to merge

#9545 Revamp MGT get started documentation
  concepts/index.yml
  concepts/toc.yml
  concepts/toolkit/get-started.md
  concepts/toolkit/get-started/build-a-microsoft-teams-tab.md
  concepts/toolkit/get-started/build-a-sharepoint-web-part.md
  concepts/toolkit/get-started/build-a-web-app.md
  concepts/toolkit/get-started/overview.md
  concepts/toolkit/get-started/use-toolkit-with-angular.md
  concepts/toolkit/get-started/use-toolkit-with-react.md
  concepts/toolkit/overview.md
  concepts/toolkit/providers/sharepoint.md
Labels: ready to merge

#9679 Add Continuous Access evaluation policy
  api-reference/beta/api/continuousaccessevaluationpolicy-get.md
  api-reference/beta/api/continuousaccessevaluationpolicy-update.md
  api-reference/beta/resources/continuousaccessevaluationpolicy.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: area: azure/AAD, ready to merge

#9309 New BitLocker recovery key API documentation
  api-reference/beta/api/bitlocker-list-recoverykeys.md
  api-reference/beta/api/bitlockerrecoverykey-get.md
  api-reference/beta/resources/bitlocker.md
  api-reference/beta/resources/bitlockerrecoverykey.md
  api-reference/beta/resources/enums.md
  api-reference/beta/toc.yml
  changelog/Microsoft.BitLocker.json
  concepts/changelog.md
  concepts/permissions-reference.md
Labels: ready to merge

#9962 Tutorialcorrection1
  concepts/tutorial-access-package-api.md
Labels: area: azure/AAD, internal, ready to merge

#3839 PATCH chatMessage (was Jiawwu dlp 20190122)
  api-reference/beta/api/chatmessage-update.md
  api-reference/beta/resources/chatmessage.md
  api-reference/beta/resources/chatmessagepolicyviolation.md
  api-reference/beta/resources/chatmessagepolicyviolationpolicytip.md
  api-reference/beta/resources/enums.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: area: teams, ready to merge

#9959 Update conditionalaccessroot-post-policies.md
  api-reference/v1.0/api/conditionalaccessroot-post-policies.md
Labels: external

#9958 Update conditionalaccessroot-post-policies.md
  api-reference/beta/api/conditionalaccessroot-post-policies.md
Labels: external

#9956 Update accesspackageassignment.md
  api-reference/beta/resources/accesspackageassignment.md
Labels: external

#9795 Update workbook-error-codes.md
  concepts/workbook-error-codes.md
  concepts/workbook-error-handling.md
Labels: ready to merge

#9916 Adding note for analytics API valid date time
  api-reference/v1.0/api/itemactivitystat-getactivitybyinterval.md
Labels: external

#9963 Graph API beta - trust framework - keyset - get active key request method from POST to GET
  api-reference/beta/api/trustframeworkkeyset-getactivekey.md
  api-reference/beta/includes/snippets/csharp/trustframeworkkeyset-getactivekey-csharp-snippets.md
  api-reference/beta/includes/snippets/javascript/trustframeworkkeyset-getactivekey-javascript-snippets.md
  api-reference/beta/includes/snippets/objc/trustframeworkkeyset-getactivekey-objc-snippets.md
Labels: external

#9975 Update channel-get-filesfolder.md
  api-reference/v1.0/api/channel-get-filesfolder.md
Labels: external

#9976 Update channel-get-filesfolder.md
  api-reference/beta/api/channel-get-filesfolder.md
Labels: external

#9910 Remove Participant API document for beta and V1.0
  api-reference/beta/api/participant-delete.md
  api-reference/beta/resources/participant.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/participant-delete.md
  api-reference/v1.0/resources/participant.md
  api-reference/v1.0/toc.yml
  concepts/changelog.md
Labels: internal, ready to merge

#9984 Merge to publish.
  api-reference/beta/api/channel-get-filesfolder.md
  api-reference/beta/api/participant-delete.md
  api-reference/beta/resources/participant.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/channel-get-filesfolder.md
  api-reference/v1.0/api/participant-delete.md
  api-reference/v1.0/resources/participant.md
  api-reference/v1.0/toc.yml
  concepts/changelog.md
Labels: internal

#9990 Fix JSON sample for HTTP request
  api-reference/beta/api/profile-post-positions.md
Labels: internal, ready to merge

#9989 Update known-issues.md
  concepts/known-issues.md
Labels: external

#9982 Add PowerShell SDK docs
  concepts/powershell/RegisterAppOnly.ps1
  concepts/powershell/app-only.md
  concepts/powershell/get-started.md
  concepts/powershell/images/aad-application-id.png
  concepts/powershell/images/aad-portal-app-registrations.png
  concepts/powershell/images/configured-permissions.png
  concepts/powershell/images/register-app.png
  concepts/powershell/installation.md
  concepts/powershell/navigating.md
  concepts/sdks/create-requests.md
  concepts/sdks/includes/snippets/csharp/create-requests-create.md
  concepts/sdks/includes/snippets/csharp/create-requests-delete.md
  concepts/sdks/includes/snippets/csharp/create-requests-expand.md
  concepts/sdks/includes/snippets/csharp/create-requests-headers.md
  concepts/sdks/includes/snippets/csharp/create-requests-index.md
  concepts/sdks/includes/snippets/csharp/create-requests-list.md
  concepts/sdks/includes/snippets/csharp/create-requests-queryparams.md
  concepts/sdks/includes/snippets/csharp/create-requests-read.md
  concepts/sdks/includes/snippets/csharp/create-requests-select.md
  concepts/sdks/includes/snippets/csharp/create-requests-update.md
  concepts/sdks/includes/snippets/powershell/create-requests-create.md
  concepts/sdks/includes/snippets/powershell/create-requests-delete.md
  concepts/sdks/includes/snippets/powershell/create-requests-expand.md
  concepts/sdks/includes/snippets/powershell/create-requests-headers.md
  concepts/sdks/includes/snippets/powershell/create-requests-index.md
  concepts/sdks/includes/snippets/powershell/create-requests-list.md
  concepts/sdks/includes/snippets/powershell/create-requests-queryparams.md
  concepts/sdks/includes/snippets/powershell/create-requests-read.md
  concepts/sdks/includes/snippets/powershell/create-requests-select.md
  concepts/sdks/includes/snippets/powershell/create-requests-update.md
  concepts/sdks/includes/snippets/typescript/create-requests-create.md
  concepts/sdks/includes/snippets/typescript/create-requests-delete.md
  concepts/sdks/includes/snippets/typescript/create-requests-expand.md
  concepts/sdks/includes/snippets/typescript/create-requests-headers.md
  concepts/sdks/includes/snippets/typescript/create-requests-index.md
  concepts/sdks/includes/snippets/typescript/create-requests-list.md
  concepts/sdks/includes/snippets/typescript/create-requests-queryparams.md
  concepts/sdks/includes/snippets/typescript/create-requests-read.md
  concepts/sdks/includes/snippets/typescript/create-requests-select.md
  concepts/sdks/includes/snippets/typescript/create-requests-update.md
  concepts/sdks/sdk-installation.md
  concepts/toc.yml
Labels: internal, ready to merge

#9991 Removed roster sync flow
  concepts/teams-create-group-and-team.md
Labels: internal, ready to merge

#9085 MSA developer support to call app API
  api-reference/beta/api/application-addpassword.md
  api-reference/beta/api/application-delete-extensionproperty.md
  api-reference/beta/api/application-delete.md
  api-reference/beta/api/application-get.md
  api-reference/beta/api/application-list-extensionproperty.md
  api-reference/beta/api/application-list.md
  api-reference/beta/api/application-post-applications.md
  api-reference/beta/api/application-post-extensionproperty.md
  api-reference/beta/api/application-removepassword.md
  api-reference/beta/api/application-update.md
  api-reference/beta/resources/application.md
  api-reference/v1.0/resources/application.md
Labels: area: azure/AAD, changes requested, ready to merge

#9921 Ignite/graphconnectors
  concepts/images/search-index-manage-connections-admin-view.png
  concepts/images/search-index-manage-connections-admin-view.svg
  concepts/images/search-index-manage-connections-connector-structure.png
  concepts/images/search-index-manage-items-1.png
  concepts/images/search-index-manage-items-2.png
  concepts/images/search-index-manage-items-3.svg
  concepts/images/search-index-manage-items-acl.png
  concepts/images/search-index-manage-items-schema-1.svg
  concepts/images/search-index-manage-items-schema-2.svg
  concepts/images/search-index-manage-items-schema-3.svg
  concepts/images/search-index-manage-items-schema-6.svg
  concepts/images/search-index-manage-schema-4.svg
  concepts/images/search-index-manage-schema-5.svg
  concepts/images/search-index-manage-schema-6.svg
  concepts/search-index-manage-connections.md
  concepts/search-index-manage-items.md
  concepts/search-index-manage-schema.md
  concepts/toc.yml
Labels: Ignite20, internal, ready to merge

#9970 Add Indexing Group Sync APIs
  api-reference/beta/api/externalconnection-post-groups.md
  api-reference/beta/api/externalconnection-put-items.md
  api-reference/beta/api/externalgroup-delete.md
  api-reference/beta/api/externalgroup-post-members.md
  api-reference/beta/api/externalgroupmember-delete.md
  api-reference/beta/api/externalitem-get.md
  api-reference/beta/api/externalitem-update.md
  api-reference/beta/resources/acl.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/externalconnection.md
  api-reference/beta/resources/externalgroup.md
  api-reference/beta/resources/externalgroupmember.md
  api-reference/beta/resources/externalitem.md
  api-reference/beta/resources/schema.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: Ignite20, internal, ready to merge

#9949 add new and update property in chatMessage resource (1196639)
  api-reference/beta/api/channel-get-filesfolder.md
  api-reference/beta/api/channel-get-message.md
  api-reference/beta/api/channel-get-messagereply.md
  api-reference/beta/api/channel-list-messagereplies.md
  api-reference/beta/api/channel-list-messages.md
  api-reference/beta/api/channel-post-message.md
  api-reference/beta/api/channel-post-messagereply.md
  api-reference/beta/api/chat-get-message.md
  api-reference/beta/api/chat-list-message.md
  api-reference/beta/api/chatmessage-post.md
  api-reference/beta/resources/chatmessage.md
  api-reference/v1.0/api/channel-post-messagereply.md
  api-reference/v1.0/api/channel-post-messages.md
  api-reference/v1.0/resources/chatmessage.md
  concepts/changelog.md
Labels: internal, ready to merge

#9693 Documentation of transactionid property in v1
  api-reference/v1.0/api/calendar-post-events.md
  api-reference/v1.0/api/event-delta.md
  api-reference/v1.0/api/user-post-events.md
  api-reference/v1.0/resources/event.md
  concepts/changelog.md
Labels: ready to merge

#9995 Add Toolkit to TOCs.
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
Labels: internal

#9996 Added what's new in the past week.
  concepts/whats-new-overview.md
Labels: internal

#10006 Remove extra space
  api-reference/v1.0/api/subscription-post-subscriptions.md
Labels: area: teams, internal, ready to merge

#9920 Update security-api-overview.md
  api-reference/beta/resources/security-api-overview.md
Labels: area: Security, internal, ready to merge

#9919 Update security-api-overview.md
  api-reference/v1.0/resources/security-api-overview.md
Labels: area: Security, internal, ready to merge

#10012 Update teams-protected-apis.md
  concepts/teams-protected-apis.md
Labels: area: teams, internal, ready to merge

#10011 Make the description accurate
  api-reference/beta/api/participant-delete.md
  api-reference/v1.0/api/participant-delete.md
Labels: content review, external, ready to merge

#9985 Promote chatmessage patch to v1
  api-reference/v1.0/api/chatmessage-update.md
  api-reference/v1.0/resources/chatmessage.md
  api-reference/v1.0/resources/chatmessagepolicyviolation.md
  api-reference/v1.0/resources/chatmessagepolicyviolationpolicytip.md
  api-reference/v1.0/resources/enums.md
  api-reference/v1.0/toc.yml
  concepts/changelog.md
Labels: internal, ready to merge

#10002 Update serviceprincipal-post-approleassignments.md
  api-reference/beta/api/serviceprincipal-post-approleassignments.md
Labels: external

#10001 Update serviceprincipal-post-approleassignments.md
  api-reference/v1.0/api/serviceprincipal-post-approleassignments.md
Labels: external

#9999 Update chat.md
  api-reference/beta/resources/chat.md
Labels: external

#10029 Update termstore-store-get-group.md
  api-reference/beta/api/termstore-store-get-group.md
Labels: external

#10028 Update termstore-group-post.md
  api-reference/beta/api/termstore-group-post.md
Labels: external

#10027 Update termstore-group.md
  api-reference/beta/resources/termstore-group.md
Labels: external

#10026 Update termstore-store.md
  api-reference/beta/resources/termstore-store.md
Labels: external

#10021 Update intune-devices-manageddevice-rebootnow.md
  api-reference/v1.0/api/intune-devices-manageddevice-rebootnow.md
Labels: external

#10019 Update intune-devices-manageddevice-rebootnow.md
  api-reference/beta/api/intune-devices-manageddevice-rebootnow.md
Labels: external

#9617 Updated iCalUId documentation in v1
  api-reference/v1.0/resources/event.md
Labels: ready to merge

#10034 Merge to publish.
  api-reference/beta/api/intune-devices-manageddevice-rebootnow.md
  api-reference/beta/api/termstore-group-post.md
  api-reference/beta/api/termstore-store-get-group.md
  api-reference/beta/resources/termstore-group.md
  api-reference/beta/resources/termstore-store.md
  api-reference/v1.0/api/intune-devices-manageddevice-rebootnow.md
  api-reference/v1.0/resources/event.md
Labels: internal

#10035 Update termstore-term.md
  api-reference/beta/resources/termstore-term.md
Labels: external

#9909 Rodriguezd 1149676 ga membership api
  api-reference/v1.0/api/team-delete-members.md
  api-reference/v1.0/api/team-list-members.md
  api-reference/v1.0/api/team-post-members.md
  api-reference/v1.0/resources/team.md
  api-reference/v1.0/toc.yml
  concepts/changelog.md
Labels: changes requested, content review, internal, ready to merge

#9793 Adding printDocument: $value method
  api-reference/beta/api/printdocument-get-file.md
  api-reference/beta/api/printer-update.md
  api-reference/beta/resources/printdocument.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: area: universal print, ready to merge

#10042 Added sentence about v1.0 version.
  api-reference/includes/beta-disclaimer.md
Labels: internal, ready to merge

#10048 Merge to publish.
  api-reference/beta/api/printdocument-get-file.md
  api-reference/beta/api/printer-update.md
  api-reference/beta/resources/printdocument.md
  api-reference/beta/resources/termstore-term.md
  api-reference/beta/toc.yml
  api-reference/includes/beta-disclaimer.md
  api-reference/v1.0/api/team-delete-members.md
  api-reference/v1.0/api/team-list-members.md
  api-reference/v1.0/api/team-post-members.md
  api-reference/v1.0/resources/team.md
  api-reference/v1.0/toc.yml
  concepts/changelog.md
Labels: internal

#10052 additional generic java samples
  concepts/sdks/create-requests.md
  concepts/sdks/includes/snippets/java/create-requests-create.md
  concepts/sdks/includes/snippets/java/create-requests-delete.md
  concepts/sdks/includes/snippets/java/create-requests-expand.md
  concepts/sdks/includes/snippets/java/create-requests-headers.md
  concepts/sdks/includes/snippets/java/create-requests-index.md
  concepts/sdks/includes/snippets/java/create-requests-list.md
  concepts/sdks/includes/snippets/java/create-requests-queryparams.md
  concepts/sdks/includes/snippets/java/create-requests-read.md
  concepts/sdks/includes/snippets/java/create-requests-select.md
  concepts/sdks/includes/snippets/java/create-requests-update.md
  concepts/sdks/paging.md
  concepts/sdks/sdk-installation.md
  concepts/sdks/use-beta.md
Labels: area: sample code, internal, ready to merge

#10051 Update termstore-relation-post.md
  api-reference/beta/api/termstore-relation-post.md
Labels: external

#10050 Update termstore-relation.md
  api-reference/beta/resources/termstore-relation.md
Labels: external

#10066 Updated topic with what's released this week.
  concepts/whats-new-overview.md
Labels: internal

#10072 Update todo-post-lists.md
  api-reference/beta/api/todo-post-lists.md
Labels: external

#10043 - adds a sample for java client customization
  concepts/sdks/customize-client.md
Labels: bug: sample, internal, ready to merge

#10067 Update cloud-communication-online-meeting-application-access-policy.md
  concepts/cloud-communication-online-meeting-application-access-policy.md
Labels: internal

#10083 Merge to publish.
  api-reference/beta/api/todo-post-lists.md
  concepts/cloud-communication-online-meeting-application-access-policy.md
  concepts/sdks/customize-client.md
Labels: do not merge, internal

#7201 DirectorySizeQuota documentation
  api-reference/beta/resources/directorysizequota.md
  api-reference/beta/resources/organization.md
  concepts/changelog.md
Labels: changelog, ready to merge

#10094 Fix table formatting
  api-reference/v1.0/resources/subscription.md
Labels: internal

#10087 Update todotasklist-get.md
  api-reference/beta/api/todotasklist-get.md
Labels: external

#7292 UserShiftPreferences app permissions in Beta
  api-reference/beta/api/offershiftrequest-approve.md
  api-reference/beta/api/offershiftrequest-decline.md
  api-reference/beta/api/offershiftrequest-get.md
  api-reference/beta/api/offershiftrequest-list.md
  api-reference/beta/api/offershiftrequest-post.md
  api-reference/beta/api/schedule-get.md
  api-reference/beta/api/schedule-list-schedulinggroups.md
  api-reference/beta/api/schedule-list-shifts.md
  api-reference/beta/api/schedule-post-schedulinggroups.md
  api-reference/beta/api/schedule-post-shifts.md
  api-reference/beta/api/schedule-share.md
  api-reference/beta/api/schedulinggroup-delete.md
  api-reference/beta/api/schedulinggroup-get.md
  api-reference/beta/api/schedulinggroup-put.md
  api-reference/beta/api/shift-delete.md
  api-reference/beta/api/shift-get.md
  api-reference/beta/api/shift-put.md
  api-reference/beta/api/team-put-schedule.md
  api-reference/v1.0/api/offershiftrequest-approve.md
  api-reference/v1.0/api/offershiftrequest-decline.md
  api-reference/v1.0/api/offershiftrequest-get.md
  api-reference/v1.0/api/offershiftrequest-list.md
  api-reference/v1.0/api/offershiftrequest-post.md
  api-reference/v1.0/api/openshift-get.md
  api-reference/v1.0/api/schedule-get.md
  api-reference/v1.0/api/schedule-list-schedulinggroups.md
  api-reference/v1.0/api/schedule-post-schedulinggroups.md
  api-reference/v1.0/api/schedule-post-shifts.md
  api-reference/v1.0/api/schedule-share.md
  api-reference/v1.0/api/schedulinggroup-delete.md
  api-reference/v1.0/api/schedulinggroup-get.md
  api-reference/v1.0/api/schedulinggroup-put.md
  api-reference/v1.0/api/shift-delete.md
  api-reference/v1.0/api/shift-get.md
  api-reference/v1.0/api/shift-put.md
  api-reference/v1.0/api/team-put-schedule.md
  concepts/permissions-reference.md
Labels: changelog, changelog required, changes requested, ready to merge

#10099 Fix API Doctor link error.
  api-reference/beta/config/link-validation-config.json
  api-reference/v1.0/config/link-validation-config.json
Labels: do not merge, internal

#9601 Add RoleManagement.Read.All permission
  concepts/permissions-reference.md
Labels: ready to merge

#10088 Update todotasklist-update.md
  api-reference/beta/api/todotasklist-update.md
Labels: external

#9941 update documentation for ToDo
  api-reference/beta/api/todotask-post-linkedresources.md
  api-reference/beta/api/todotasklist-post-tasks.md
  api-reference/beta/resources/linkedresource.md
  api-reference/beta/resources/todotasklist.md
  concepts/images/todo-api-entities.png
  concepts/images/todo-linkedresource-taskdetail.PNG
  concepts/images/todo-linkedresource.PNG
  concepts/images/todo-windows-app.png
Labels: area: todo, internal, ready to merge

#10102 Updated to validate link.
  api-reference/beta/config/link-validation-config.json
  api-reference/v1.0/config/link-validation-config.json
Labels: internal
