Repository microsoftgraph/microsoft-graph-docs, pull requests merged in 2020-03, with the labels that each got.

#7242 Typo "**@api.diagnostics**"→"**\@api.diagnostics**"
  concepts/onenote-create-page.md
Labels: external

#7244 Update intune-devices-adminconsentstate.md
  api-reference/beta/resources/intune-devices-adminconsentstate.md
Labels: external

#7249 - delta link : documented the edge case of empty nextlink value
  concepts/delta-query-groups.md
  concepts/delta-query-users.md
Labels: area: delta query, ready to merge

#7221 fix for git issue 6798
  api-reference/beta/resources/subscribedsku.md
  api-reference/v1.0/resources/subscribedsku.md
Labels: ready to merge

#7251 Fix preview permissions.
  concepts/permissions-reference.md
Labels: ready to merge

#6855 Added reference documentation for CallRecords APIs
  api-reference/beta/api/callrecords-callrecord-get.md
  api-reference/beta/api/subscription-delete.md
  api-reference/beta/api/subscription-get.md
  api-reference/beta/api/subscription-post-subscriptions.md
  api-reference/beta/api/subscription-update.md
  api-reference/beta/resources/callrecords-api-overview.md
  api-reference/beta/resources/callrecords-callrecord.md
  api-reference/beta/resources/callrecords-clientuseragent.md
  api-reference/beta/resources/callrecords-deviceinfo.md
  api-reference/beta/resources/callrecords-endpoint.md
  api-reference/beta/resources/callrecords-failureinfo.md
  api-reference/beta/resources/callrecords-feedbacktokenset.md
  api-reference/beta/resources/callrecords-media.md
  api-reference/beta/resources/callrecords-mediastream.md
  api-reference/beta/resources/callrecords-networkinfo.md
  api-reference/beta/resources/callrecords-participantendpoint.md
  api-reference/beta/resources/callrecords-segment.md
  api-reference/beta/resources/callrecords-serviceendpoint.md
  api-reference/beta/resources/callrecords-serviceuseragent.md
  api-reference/beta/resources/callrecords-session.md
  api-reference/beta/resources/callrecords-useragent.md
  api-reference/beta/resources/callrecords-userfeedback.md
  api-reference/beta/resources/communications-api-overview.md
  api-reference/beta/resources/subscription.md
  api-reference/beta/resources/webhooks.md
  api-reference/beta/toc.yml
  concepts/changelog.md
  concepts/cloud-communications-callrecords.md
  concepts/images/callrecords-structure.png
  concepts/permissions-reference.md
  concepts/toc.yml
  concepts/webhooks.md
Labels: area: teams, area: webhooks, ready to merge

#7265 Make known an issue re failure in attaching large files to message in shared or delegated mailbox.
  api-reference/beta/api/attachment-createuploadsession.md
  concepts/known-issues.md
  concepts/outlook-large-attachments.md
Labels: do not merge

#7268 fix for git issue 6976
  api-reference/beta/api/administrativeunit-post-members.md
Labels: ready to merge

#7266 fix for git issue 6909
  api-reference/beta/resources/user.md
  api-reference/v1.0/resources/user.md
Labels: ready to merge

#7263 ChannelMessage.Read.All
  api-reference/beta/api/channel-get-message.md
  api-reference/beta/api/channel-get-messagereply.md
  api-reference/beta/api/channel-list-messagereplies.md
  api-reference/beta/api/channel-list-messages.md
  api-reference/beta/api/chatmessage-delta.md
  api-reference/beta/resources/chatmessage.md
Labels: area: teams, ready to merge

#7275 Add missing links for create rubrics and category
  api-reference/beta/resources/educationcategory.md
  api-reference/beta/resources/educationrubric.md
  api-reference/beta/toc.yml
Labels: area: edu, ready to merge

#7233 add example of accesspackageassignmentpolicy POST request and remove obsolete field isDenyPolicy
  api-reference/beta/api/accesspackageassignmentpolicy-get.md
  api-reference/beta/api/accesspackageassignmentpolicy-list.md
  api-reference/beta/api/accesspackageassignmentpolicy-post.md
  api-reference/beta/resources/accesspackageassignmentpolicy.md
  api-reference/beta/toc.yml
Labels: area: azure/AAD, ready to merge

#7274 Correct method used to get Education Assignment Resource Url
  api-reference/beta/api/educationassignment-getresourcesfolderurl.md
Labels: external, ready to merge

#7273 Correct HTTP Request for deleting assignment resource
  api-reference/beta/api/educationassignmentresource-delete.md
Labels: external, ready to merge

#7279 Nkramer channel message read all
  api-reference/beta/api/chatmessage-list-chatmessagehostedcontents.md
  concepts/changelog.md
Labels: area: teams, ready to merge

#7305 Changed targets to invitationParticipantInfo
  api-reference/beta/api/application-post-calls.md
Labels: ready to merge

#7225 Policy.ReadWrite.ApplicationConfiguration docs
  api-reference/beta/api/activitybasedtimeoutpolicy-get.md
  api-reference/beta/api/activitybasedtimeoutpolicy-list.md
  api-reference/beta/api/application-delete-tokenlifetimepolicies.md
  api-reference/beta/api/application-list-tokenlifetimepolicies.md
  api-reference/beta/api/application-post-tokenlifetimepolicies.md
  api-reference/beta/api/claimsmappingpolicy-get.md
  api-reference/beta/api/claimsmappingpolicy-list-appliesto.md
  api-reference/beta/api/claimsmappingpolicy-list.md
  api-reference/beta/api/homerealmdiscoverypolicy-get.md
  api-reference/beta/api/homerealmdiscoverypolicy-list-appliesto.md
  api-reference/beta/api/homerealmdiscoverypolicy-list.md
  api-reference/beta/api/serviceprincipal-delete-claimsmappingpolicies.md
  api-reference/beta/api/serviceprincipal-delete-homerealmdiscoverypolicies.md
  api-reference/beta/api/serviceprincipal-list-claimsmappingpolicies.md
  api-reference/beta/api/serviceprincipal-list-homerealmdiscoverypolicies.md
  api-reference/beta/api/serviceprincipal-post-claimsmappingpolicies.md
  api-reference/beta/api/serviceprincipal-post-homerealmdiscoverypolicies.md
  api-reference/beta/api/tokenlifetimepolicy-get.md
  api-reference/beta/api/tokenlifetimepolicy-list-appliesto.md
  api-reference/beta/api/tokenlifetimepolicy-list.md
  concepts/changelog.md
  concepts/permissions-reference.md
Labels: area: azure/AAD, ready to merge

#7216 Adding files for tokenIssuancePolicy
  api-reference/beta/api/tokenissuancepolicy-delete.md
  api-reference/beta/api/tokenissuancepolicy-get.md
  api-reference/beta/api/tokenissuancepolicy-list-appliesto.md
  api-reference/beta/api/tokenissuancepolicy-list.md
  api-reference/beta/api/tokenissuancepolicy-post-tokenissuancepolicy.md
  api-reference/beta/api/tokenissuancepolicy-update.md
  api-reference/beta/resources/policy-overview.md
  api-reference/beta/resources/tokenissuancepolicy.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: area: azure/AAD, ready to merge

#7298 Update team-archive.md
  api-reference/v1.0/api/team-archive.md
Labels: ready to merge

#7294 Added docs for extending mgt-login
  concepts/toolkit/components/login.md
Labels: internal

#7106 Onboard threat assessment APIs to v1.0
  api-reference/v1.0/api/informationprotection-list-threatassessmentrequests.md
  api-reference/v1.0/api/informationprotection-post-threatassessmentrequests.md
  api-reference/v1.0/api/threatassessmentrequest-get.md
  api-reference/v1.0/resources/emailFileAssessmentRequest.md
  api-reference/v1.0/resources/enums.md
  api-reference/v1.0/resources/fileassessmentrequest.md
  api-reference/v1.0/resources/mailassessmentrequest.md
  api-reference/v1.0/resources/threatassessment-api-overview.md
  api-reference/v1.0/resources/threatassessmentrequest.md
  api-reference/v1.0/resources/threatassessmentresult.md
  api-reference/v1.0/resources/urlassessmentrequest.md
  api-reference/v1.0/toc.yml
  concepts/changelog.md
Labels: ready to merge

#7332 Restructured render methods in mgt-people
  concepts/toolkit/components/people.md
Labels: internal

#7341 Change subscription: adds the content type header for validation request
  concepts/webhooks.md
Labels: ready to merge

#7257 Add Teams admin roles access to O365 usage reports API
  concepts/changelog.md
  concepts/reportroot-authorization.md
Labels: ready to merge

#7369 - adds java samples for rich notifications payload signature verification and decryption
  concepts/webhooks-with-resource-data.md
Labels: ready to merge

#6880 revamp overview docs
  concepts/toc.yml
  concepts/toolkit/components/agenda.md
  concepts/toolkit/components/get.md
  concepts/toolkit/components/login.md
  concepts/toolkit/components/people-picker.md
  concepts/toolkit/components/people.md
  concepts/toolkit/components/person-card.md
  concepts/toolkit/components/person.md
  concepts/toolkit/components/tasks.md
  concepts/toolkit/get-started.md
  concepts/toolkit/images/internetExplorerIcon.png
  concepts/toolkit/images/mgt_v2.png
  concepts/toolkit/images/microsoftTeamsIcon.png
  concepts/toolkit/images/sharepointIcon.png
  concepts/toolkit/overview.md
Labels: changes requested

#7371 PIM Azure Resources update
  api-reference/beta/api/governanceresource-get.md
  api-reference/beta/api/governanceresource-list.md
  api-reference/beta/api/governanceroleassignment-export.md
  api-reference/beta/api/governanceroleassignment-get.md
  api-reference/beta/api/governanceroleassignment-list.md
  api-reference/beta/api/governanceroleassignmentrequest-cancel.md
  api-reference/beta/api/governanceroleassignmentrequest-get.md
  api-reference/beta/api/governanceroleassignmentrequest-list.md
  api-reference/beta/api/governanceroleassignmentrequest-post.md
  api-reference/beta/api/governanceroleassignmentrequest-update.md
  api-reference/beta/api/governanceroledefinition-get.md
  api-reference/beta/api/governanceroledefinition-list.md
  api-reference/beta/api/governancerolesetting-get.md
  api-reference/beta/api/governancerolesetting-list.md
  concepts/changelog.md
Labels: ready to merge

#7246 Changes in Graph beta for new calendar and event properties
  api-reference/beta/api/calendar-get.md
  api-reference/beta/api/calendar-post-events.md
  api-reference/beta/api/calendargroup-list-calendars.md
  api-reference/beta/api/group-get-event.md
  api-reference/beta/api/group-post-events.md
  api-reference/beta/api/user-list-calendars.md
  api-reference/beta/api/user-post-calendars.md
  api-reference/beta/api/user-post-events.md
  api-reference/beta/resources/calendar.md
  api-reference/beta/resources/event.md
  concepts/changelog.md
Labels: ready to merge

#7385 Update what's new.
  concepts/changelog.md
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: do not merge

#7401 intune v1 updates
  api-reference/v1.0/resources/intune-companyterms-termsandconditionsacceptancestatus.md
  api-reference/v1.0/resources/intune-deviceconfig-iosupdatesinstallstatus.md
  api-reference/v1.0/resources/intune-shared-devicemanagement.md
Labels: ready to merge

#7393 - adds java sample for token validation
  concepts/webhooks-with-resource-data.md
Labels: content review, ready to merge

#7227 User.ManageIdentities.All permissions reference
  api-reference/beta/api/user-update.md
  api-reference/v1.0/api/user-update.md
  concepts/changelog.md
  concepts/permissions-reference.md
Labels: area: azure/AAD, ready to merge

#7193 Added logTeleconferenceDeviceQuality function under Call collection
  api-reference/beta/api/application-post-calls.md
  api-reference/beta/api/call-logteleconferencedevicequality.md
  api-reference/beta/resources/call.md
  api-reference/beta/resources/teleconferencedeviceaudioquality.md
  api-reference/beta/resources/teleconferencedevicemediaquality.md
  api-reference/beta/resources/teleconferencedevicequality.md
  api-reference/beta/resources/teleconferencedevicescreensharingquality.md
  api-reference/beta/resources/teleconferencedevicevideoquality.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: changes requested, ready to merge

#7402 Update protected render methods in mgt-person
  concepts/toolkit/components/person.md
Labels: internal

#7409 Snippets update
  api-reference/v1.0/api/informationprotection-list-threatassessmentrequests.md
  api-reference/v1.0/api/informationprotection-post-threatassessmentrequests.md
  api-reference/v1.0/api/threatassessmentrequest-get.md
  api-reference/v1.0/includes/snippets/csharp/create-emailfileassessmentrequest-from-informationprotection-csharp-snippets.md
  api-reference/v1.0/includes/snippets/csharp/create-fileassessmentrequest-from-informationprotection-csharp-snippets.md
  api-reference/v1.0/includes/snippets/csharp/create-mailassessmentrequest-from-informationprotection-csharp-snippets.md
  api-reference/v1.0/includes/snippets/csharp/create-urlassessmentrequest-from-informationprotection-csharp-snippets.md
  api-reference/v1.0/includes/snippets/csharp/get-emailfileassessmentrequest-csharp-snippets.md
  api-reference/v1.0/includes/snippets/csharp/get-fileassessmentrequest-csharp-snippets.md
  api-reference/v1.0/includes/snippets/csharp/get-mailassessmentrequest-csharp-snippets.md
  api-reference/v1.0/includes/snippets/csharp/get-threatassessmentrequest-expand-results-csharp-snippets.md
  api-reference/v1.0/includes/snippets/csharp/get-threatassessmentrequests-csharp-snippets.md
  api-reference/v1.0/includes/snippets/csharp/get-urlassessmentrequest-csharp-snippets.md
  api-reference/v1.0/includes/snippets/java/create-emailfileassessmentrequest-from-informationprotection-java-snippets.md
  api-reference/v1.0/includes/snippets/java/create-fileassessmentrequest-from-informationprotection-java-snippets.md
  api-reference/v1.0/includes/snippets/java/create-mailassessmentrequest-from-informationprotection-java-snippets.md
  api-reference/v1.0/includes/snippets/java/create-urlassessmentrequest-from-informationprotection-java-snippets.md
  api-reference/v1.0/includes/snippets/java/get-emailfileassessmentrequest-java-snippets.md
  api-reference/v1.0/includes/snippets/java/get-fileassessmentrequest-java-snippets.md
  api-reference/v1.0/includes/snippets/java/get-mailassessmentrequest-java-snippets.md
  api-reference/v1.0/includes/snippets/java/get-threatassessmentrequest-expand-results-java-snippets.md
  api-reference/v1.0/includes/snippets/java/get-threatassessmentrequests-java-snippets.md
  api-reference/v1.0/includes/snippets/java/get-urlassessmentrequest-java-snippets.md
  api-reference/v1.0/includes/snippets/javascript/create-emailfileassessmentrequest-from-informationprotection-javascript-snippets.md
  api-reference/v1.0/includes/snippets/javascript/create-fileassessmentrequest-from-informationprotection-javascript-snippets.md
  api-reference/v1.0/includes/snippets/javascript/create-mailassessmentrequest-from-informationprotection-javascript-snippets.md
  api-reference/v1.0/includes/snippets/javascript/create-urlassessmentrequest-from-informationprotection-javascript-snippets.md
  api-reference/v1.0/includes/snippets/javascript/get-emailfileassessmentrequest-javascript-snippets.md
  api-reference/v1.0/includes/snippets/javascript/get-fileassessmentrequest-javascript-snippets.md
  api-reference/v1.0/includes/snippets/javascript/get-mailassessmentrequest-javascript-snippets.md
  api-reference/v1.0/includes/snippets/javascript/get-threatassessmentrequest-expand-results-javascript-snippets.md
  api-reference/v1.0/includes/snippets/javascript/get-threatassessmentrequests-javascript-snippets.md
  api-reference/v1.0/includes/snippets/javascript/get-urlassessmentrequest-javascript-snippets.md
  api-reference/v1.0/includes/snippets/objc/create-emailfileassessmentrequest-from-informationprotection-objc-snippets.md
  api-reference/v1.0/includes/snippets/objc/create-fileassessmentrequest-from-informationprotection-objc-snippets.md
  api-reference/v1.0/includes/snippets/objc/create-mailassessmentrequest-from-informationprotection-objc-snippets.md
  api-reference/v1.0/includes/snippets/objc/create-urlassessmentrequest-from-informationprotection-objc-snippets.md
  api-reference/v1.0/includes/snippets/objc/get-emailfileassessmentrequest-objc-snippets.md
  api-reference/v1.0/includes/snippets/objc/get-fileassessmentrequest-objc-snippets.md
  api-reference/v1.0/includes/snippets/objc/get-mailassessmentrequest-objc-snippets.md
  api-reference/v1.0/includes/snippets/objc/get-threatassessmentrequest-expand-results-objc-snippets.md
  api-reference/v1.0/includes/snippets/objc/get-threatassessmentrequests-objc-snippets.md
  api-reference/v1.0/includes/snippets/objc/get-urlassessmentrequest-objc-snippets.md
Labels: ready to merge

#7204 signinactivity examples
  api-reference/beta/api/user-list.md
  api-reference/beta/resources/signinactivity.md
  concepts/changelog.md
Labels: ready to merge

#7437 - adds details about users soft deletion and group membership
  concepts/delta-query-groups.md
Labels: ready to merge

#7414 Indexing API updates
  api-reference/beta/api/externalconnection-post-schema.md
  api-reference/beta/api/externalconnection-put-items.md
  api-reference/beta/api/externalitem-delete.md
  api-reference/beta/api/externalitem-update.md
  api-reference/beta/resources/externalfile.md
  api-reference/beta/resources/indexing-api-overview.md
  api-reference/beta/resources/schema.md
  api-reference/beta/toc.yml
  concepts/changelog.md
  concepts/search-concept-files.md
  concepts/search-concept-overview.md
  concepts/search-index-manage-connections.md
  concepts/search-index-manage-items.md
  concepts/throttling.md
Labels: ready to merge

#7207 fix for git issue 6253
  api-reference/v1.0/api/groupsetting-update.md
Labels: ready to merge

#7448 Brought what's new up-to-date for the week.
  concepts/changelog.md
  concepts/whats-new-overview.md
Labels: do not merge

#7384 Add documentation for Azure AD security defaults API
  api-reference/beta/api/identitysecuritydefaultsenforcementpolicy-get.md
  api-reference/beta/api/identitysecuritydefaultsenforcementpolicy-update.md
  api-reference/beta/resources/identitysecuritydefaultsenforcementpolicy.md
  api-reference/beta/resources/policy-overview.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: ready to merge

#7441 Update conditionalaccesspolicy create and update md files
  api-reference/beta/api/conditionalaccesspolicy-update.md
  api-reference/beta/api/conditionalaccessroot-post-policies.md
  concepts/known-issues.md
Labels: ready to merge

#7436 Clarify autoReviewSettings in an access review
  api-reference/beta/resources/accessreview.md
Labels: ready to merge

#7471 Emphasized base64 encoding of contentBytes.
  api-reference/beta/resources/fileattachment.md
  api-reference/v1.0/resources/fileattachment.md
Labels: do not merge

#7439 Restructuring render methods in mgt-people-picker
  concepts/toolkit/components/people-picker.md
  concepts/toolkit/components/person-card.md
Labels: internal

#7455 Added details for customizing mgt-person-card
  concepts/toolkit/components/person-card.md
Labels: internal

#7381 signin updates
  api-reference/beta/api/signin-get.md
  api-reference/beta/api/signin-list.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/signin.md
  api-reference/v1.0/api/signin-get.md
  api-reference/v1.0/api/signin-list.md
  api-reference/v1.0/resources/enums.md
  api-reference/v1.0/resources/signin.md
  concepts/changelog.md
Labels: ready to merge

#7037 Add Compliance Recording document in V1.
  api-reference/v1.0/api/call-updaterecordingstatus.md
  api-reference/v1.0/resources/call.md
  api-reference/v1.0/resources/callroute.md
  api-reference/v1.0/resources/incomingcontext.md
  api-reference/v1.0/resources/participant.md
  api-reference/v1.0/resources/participantinfo.md
  api-reference/v1.0/resources/recordinginfo.md
  api-reference/v1.0/resources/updaterecordingstatusoperation.md
  api-reference/v1.0/toc.yml
  concepts/changelog.md
Labels: ready to merge

#7479 mgt-teams-channel-picker new component
  concepts/toc.yml
  concepts/toolkit/components/images/selected-channel.png
  concepts/toolkit/components/teams-channel-picker.md
Labels: internal

#7492 Limits for Teams (take 2)
  api-reference/beta/resources/team.md
  api-reference/beta/resources/teams-api-overview.md
  concepts/throttling.md
Labels: area: teams, ready to merge

#7302 External ID for Online Meetings (beta)
  api-reference/beta/api/onlinemeeting-createorget.md
  api-reference/beta/resources/onlinemeeting.md
  api-reference/beta/toc.yml
  concepts/changelog.md
Labels: ready to merge

#7513 Updated deprecation note for beta online meeting creation
  api-reference/beta/api/application-post-onlinemeetings.md
Labels: ready to merge

#7451 - adds documentation for delta for org contacts
  api-reference/beta/api/orgcontact-delta.md
  api-reference/beta/resources/orgcontact.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/orgcontact-delta.md
  api-reference/v1.0/resources/orgcontact.md
  api-reference/v1.0/toc.yml
  concepts/changelog.md
  concepts/delta-query-overview.md
Labels: content review, ready to merge

#7397 Accept-Language Header for Online Meetings
  api-reference/beta/api/application-post-onlinemeetings.md
  api-reference/beta/api/onlinemeeting-get.md
  api-reference/beta/resources/onlinemeeting.md
  concepts/changelog.md
Labels: ready to merge

#7502 - adds reference to postman collection for validation
  concepts/images/change-notifications/validation-request-tests-results.png
  concepts/webhooks.md
Labels: content review, ready to merge

#7500 - fixes teams header level to align with outlook
  concepts/throttling.md
Labels: content review, ready to merge

#7514 adding media facets image/video in remoteItem resource.
  api-reference/beta/resources/remoteitem.md
  api-reference/v1.0/resources/remoteitem.md
  concepts/changelog.md
Labels: ready to merge

#7523 Intune beta delta2
  api-reference/beta/api/intune-devices-deviceshellscript-create.md
  api-reference/beta/api/intune-devices-deviceshellscript-get.md
  api-reference/beta/api/intune-devices-deviceshellscript-list.md
  api-reference/beta/api/intune-devices-deviceshellscript-update.md
  api-reference/beta/resources/intune-devices-deviceshellscript.md
  concepts/changelog.md
Labels: ready to merge

#7524 fix for git issue 7518
  api-reference/beta/api/governanceroleassignmentrequest-cancel.md
Labels: ready to merge

#7528 Updated what's new for the week.
  concepts/changelog.md
  concepts/overview-major-services.md
  concepts/universal-print-concept-overview.md
  concepts/whats-new-overview.md
Labels: do not merge

#7466 Remove registeredBy field from Universal Print
  api-reference/beta/api/print-list-connectors.md
  api-reference/beta/api/print-list-printers.md
  api-reference/beta/api/printconnector-get.md
  api-reference/beta/api/printconnector-update.md
  api-reference/beta/api/printer-get.md
  api-reference/beta/api/printer-list-connectors.md
  api-reference/beta/api/printer-update.md
Labels: ready to merge

#6782 Update group-post-groups.md
  api-reference/v1.0/api/group-post-groups.md
Labels: external

#6806 Update group-post-groups.md
  api-reference/beta/api/group-post-groups.md
Labels: external

#6858 Update invitation.md
  api-reference/v1.0/resources/invitation.md
Labels: external

#7169 Updated case for initiatedBy/app/displayName
  api-reference/beta/api/directoryaudit-list.md
  api-reference/v1.0/api/directoryaudit-list.md
Labels: external, review requested

#6824 Update educationclass-update.md
  api-reference/v1.0/api/educationclass-update.md
Labels: external

#7289 Updating all /conditionalAccess/ paths to prefix with /identity/
  api-reference/beta/api/conditionalaccesspolicy-delete.md
  api-reference/beta/api/conditionalaccesspolicy-get.md
  api-reference/beta/api/conditionalaccesspolicy-update.md
  api-reference/beta/api/conditionalaccessroot-list-namedlocations.md
  api-reference/beta/api/conditionalaccessroot-list-policies.md
  api-reference/beta/api/conditionalaccessroot-post-namedlocations.md
  api-reference/beta/api/conditionalaccessroot-post-policies.md
  api-reference/beta/api/countrynamedlocation-delete.md
  api-reference/beta/api/countrynamedlocation-get.md
  api-reference/beta/api/countrynamedlocation-update.md
  api-reference/beta/api/ipnamedlocation-delete.md
  api-reference/beta/api/ipnamedlocation-get.md
  api-reference/beta/api/ipnamedlocation-update.md
  api-reference/beta/api/namedlocation-delete.md
  api-reference/beta/api/namedlocation-get.md
  api-reference/beta/includes/snippets/javascript/create-conditionalaccesspolicy-from-conditionalaccessroot-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/create-namedlocation-from-conditionalaccessroot-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/delete-conditionalaccesspolicy-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/delete-countrynamedlocation-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/delete-ipnamedlocation-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/delete-namedlocation-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/get-conditionalaccesspolicy-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/get-countrynamedlocation-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/get-ipnamedlocation-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/get-namedlocation-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/get-namedlocations-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/get-policies-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/update-conditionalaccesspolicy-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/update-countrynamedlocation-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/update-ipnamedlocation-javascript-snippets.md
  api-reference/beta/includes/snippets/objc/create-conditionalaccesspolicy-from-conditionalaccessroot-objc-snippets.md
  api-reference/beta/includes/snippets/objc/create-namedlocation-from-conditionalaccessroot-objc-snippets.md
  api-reference/beta/includes/snippets/objc/delete-conditionalaccesspolicy-objc-snippets.md
  api-reference/beta/includes/snippets/objc/delete-countrynamedlocation-objc-snippets.md
  api-reference/beta/includes/snippets/objc/delete-ipnamedlocation-objc-snippets.md
  api-reference/beta/includes/snippets/objc/delete-namedlocation-objc-snippets.md
  api-reference/beta/includes/snippets/objc/get-conditionalaccesspolicy-objc-snippets.md
  api-reference/beta/includes/snippets/objc/get-countrynamedlocation-objc-snippets.md
  api-reference/beta/includes/snippets/objc/get-ipnamedlocation-objc-snippets.md
  api-reference/beta/includes/snippets/objc/get-namedlocation-objc-snippets.md
  api-reference/beta/includes/snippets/objc/get-namedlocations-objc-snippets.md
  api-reference/beta/includes/snippets/objc/get-policies-objc-snippets.md
  api-reference/beta/includes/snippets/objc/update-conditionalaccesspolicy-objc-snippets.md
  api-reference/beta/includes/snippets/objc/update-countrynamedlocation-objc-snippets.md
  concepts/changelog.md
  concepts/permissions-reference.md
Labels: ready to merge

#7501 Required Request body for PATCH is incorrect
  api-reference/beta/api/intune-devices-devicehealthscript-update.md
Labels: external

#6825 Update educationclass-update.md
  api-reference/v1.0/api/educationclass-update.md
Labels: external

#7545 updateRecordingStatus - changed namespace and note type
  api-reference/beta/api/call-updaterecordingstatus.md
  api-reference/v1.0/api/call-updaterecordingstatus.md
Labels: ready to merge

#5111 Added new userScopeFilterUri example
  concepts/data-connect-filtering.md
Labels: external, ready to merge, review requested

#4043 due date time needs start date time
  api-reference/beta/resources/followupflag.md
  api-reference/v1.0/resources/followupflag.md
Labels: ready to merge

#4776 Preparing content for introducing patch for MSA.
  api-reference/beta/api/profilephoto-update.md
Labels: do not merge

#7557 Snippets update
  api-reference/beta/api/onlinemeeting-createorget.md
  api-reference/beta/api/orgcontact-delta.md
  api-reference/beta/includes/snippets/csharp/create-or-get-onlinemeeting-csharp-snippets.md
  api-reference/beta/includes/snippets/csharp/orgcontact-delta-csharp-snippets.md
  api-reference/beta/includes/snippets/csharp/orgcontact-delta-minimal-csharp-snippets.md
  api-reference/beta/includes/snippets/csharp/orgcontact-delta-select-csharp-snippets.md
  api-reference/beta/includes/snippets/javascript/create-or-get-onlinemeeting-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/orgcontact-delta-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/orgcontact-delta-minimal-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/orgcontact-delta-select-javascript-snippets.md
  api-reference/beta/includes/snippets/objc/create-or-get-onlinemeeting-objc-snippets.md
  api-reference/beta/includes/snippets/objc/orgcontact-delta-minimal-objc-snippets.md
  api-reference/beta/includes/snippets/objc/orgcontact-delta-objc-snippets.md
  api-reference/beta/includes/snippets/objc/orgcontact-delta-select-objc-snippets.md
  api-reference/v1.0/api/call-updaterecordingstatus.md
  api-reference/v1.0/api/orgcontact-delta.md
  api-reference/v1.0/includes/snippets/csharp/call-updaterecordingstatus-csharp-snippets.md
  api-reference/v1.0/includes/snippets/csharp/orgcontact-delta-csharp-snippets.md
  api-reference/v1.0/includes/snippets/csharp/orgcontact-delta-minimal-csharp-snippets.md
  api-reference/v1.0/includes/snippets/csharp/orgcontact-delta-select-csharp-snippets.md
  api-reference/v1.0/includes/snippets/java/call-updaterecordingstatus-java-snippets.md
  api-reference/v1.0/includes/snippets/java/orgcontact-delta-java-snippets.md
  api-reference/v1.0/includes/snippets/java/orgcontact-delta-minimal-java-snippets.md
  api-reference/v1.0/includes/snippets/java/orgcontact-delta-select-java-snippets.md
  api-reference/v1.0/includes/snippets/javascript/call-updaterecordingstatus-javascript-snippets.md
  api-reference/v1.0/includes/snippets/javascript/orgcontact-delta-javascript-snippets.md
  api-reference/v1.0/includes/snippets/javascript/orgcontact-delta-minimal-javascript-snippets.md
  api-reference/v1.0/includes/snippets/javascript/orgcontact-delta-select-javascript-snippets.md
  api-reference/v1.0/includes/snippets/javascript/update-plannertaskdetails-javascript-snippets.md
  api-reference/v1.0/includes/snippets/objc/call-updaterecordingstatus-objc-snippets.md
  api-reference/v1.0/includes/snippets/objc/orgcontact-delta-minimal-objc-snippets.md
  api-reference/v1.0/includes/snippets/objc/orgcontact-delta-objc-snippets.md
  api-reference/v1.0/includes/snippets/objc/orgcontact-delta-select-objc-snippets.md
Labels: ready to merge

#6340 updating api permissions images
  concepts/images/notifications-api-permissions-list.png
  concepts/images/notifications-api-permissions-list_old2.png
  concepts/images/notifications-api-permissions.png
  concepts/images/notifications-api-permissions_old2.png
Labels: awaiting internal response

#5270 update to clarify that this only works for enterprise users.
  api-reference/beta/api/user-list-licensedetails.md
  api-reference/v1.0/api/user-list-licensedetails.md
Labels: area: azure/AAD, ready to merge

#7558 - adds known issue for duplicate notifications on users
  concepts/known-issues.md
  concepts/webhooks.md
Labels: ready to merge
