Repository microsoftgraph/microsoft-graph-docs, pull requests merged in 2021-12, with the labels that each got.

#15076 Update teams-protected-apis.md
  concepts/teams-protected-apis.md
Labels: external

#15081 Update skype-for-business-organizer-activity-reports.md
  api-reference/beta/resources/skype-for-business-organizer-activity-reports.md
Labels: external

#15082 Update skype-for-business-organizer-activity-reports.md
  api-reference/v1.0/resources/skype-for-business-organizer-activity-reports.md
Labels: external

#15056 Explicit note to include ConsistencyLevel in ex2
  api-reference/beta/api/user-list-manager.md
  api-reference/v1.0/api/user-list-manager.md
Labels: area: azure/AAD, external, ready to merge, content review complete

#15055 Time to take effect can be far > 30 minutes
  concepts/auth-limit-mailbox-access.md
Labels: external, ready to merge, content review complete

#14151 tushar20 adding SharePoint Ids to Permissions
  api-reference/beta/api/driveitem-invite.md
  api-reference/beta/api/driveitem-list-permissions.md
  api-reference/beta/api/permission-get.md
  api-reference/beta/api/permission-update.md
  api-reference/beta/api/site-get-permission.md
  api-reference/beta/api/site-list-permissions.md
  api-reference/beta/api/site-post-permissions.md
  api-reference/beta/api/site-update-permission.md
  api-reference/beta/resources/permission.md
  api-reference/beta/resources/sharepointidentity.md
  api-reference/beta/resources/sharepointidentityset.md
  api-reference/v1.0/api/driveitem-invite.md
  api-reference/v1.0/api/driveitem-list-permissions.md
  api-reference/v1.0/api/permission-get.md
  api-reference/v1.0/api/permission-update.md
  api-reference/v1.0/api/site-get-permission.md
  api-reference/v1.0/api/site-list-permissions.md
  api-reference/v1.0/api/site-post-permissions.md
  api-reference/v1.0/api/site-update-permission.md
  api-reference/v1.0/resources/permission.md
  api-reference/v1.0/resources/sharepointidentity.md
  api-reference/v1.0/resources/sharepointidentityset.md
  changelog/Microsoft.FileServices.json
Labels: ready to merge, internal, content review complete, schema live

#15041 Add migration Q+A for Azure Stack Hub
  concepts/migrate-azure-ad-graph-faq.md
Labels: area: azure/AAD, ready to merge, internal

#15077 Fix incorrect example in user-list.md
  api-reference/v1.0/api/user-list.md
Labels: ready to merge, internal, content review complete

#15078 Fix incorrect example in user-list.md
  api-reference/beta/api/user-list.md
Labels: ready to merge, internal, content review complete

#14835 Added new error types to cloudPcOnPremisesConnectionHealthCheckErrorType
  api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, internal, content review complete

#15079 Add warnings for some permissions that allow granting permissions
  concepts/permissions-reference.md
Labels: ready to merge, internal

#15105 Update educationclass-post-members.md
  api-reference/beta/api/educationclass-post-members.md
Labels: external

#15104 Update educationclass-post-members.md
  api-reference/v1.0/api/educationclass-post-members.md
Labels: external

#14563 [CloudPC]Support AADJ for OPNC
  api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md
  api-reference/beta/resources/cloudpconpremisesconnection.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, internal, content review complete, review feedback addressed

#15080 Update user-list.md
  api-reference/beta/api/user-list.md
  api-reference/v1.0/api/user-list.md
Labels: external, ready to merge, content review complete, area: query parameters

#14137 Adding add token signing certificate content to v1
  api-reference/v1.0/api/serviceprincipal-addtokensigningcertificate.md
  api-reference/v1.0/resources/selfsignedcertificate.md
  api-reference/v1.0/resources/serviceprincipal.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.DirectoryServices.json
Labels: ready to merge, internal, content review complete

#14545 m365certupdates to permissiongrantpolicy
  api-reference/beta/api/permissiongrantpolicy-get.md
  api-reference/beta/api/permissiongrantpolicy-list-excludes.md
  api-reference/beta/api/permissiongrantpolicy-list-includes.md
  api-reference/beta/api/permissiongrantpolicy-list.md
  api-reference/beta/api/permissiongrantpolicy-post-excludes.md
  api-reference/beta/api/permissiongrantpolicy-post-includes.md
  api-reference/beta/resources/permissiongrantconditionset.md
  api-reference/v1.0/api/permissiongrantpolicy-list-excludes.md
  api-reference/v1.0/api/permissiongrantpolicy-post-includes.md
  changelog/Microsoft.DirectoryServices.json
Labels: do not merge, ready to merge, internal, content review complete

#15085 updated mezzo supported properties
  concepts/aad-advanced-queries.md
  includes/filter-directory-objects.md
Labels: area: azure/AAD, ready to merge, internal, content review complete

#15096 Update aad-advanced-queries.md
  concepts/aad-advanced-queries.md
Labels: area: azure/AAD, ready to merge, internal, content review complete

#15083 Add more examples for $search
  concepts/search-query-parameter.md
Labels: area: azure/AAD, ready to merge, internal, content review complete

#14932 Updates to app object around certification property
  api-reference/beta/api/application-get.md
  api-reference/beta/resources/application.md
  api-reference/beta/resources/certification.md
  changelog/Microsoft.DirectoryServices.json
Labels: ready to merge, changes requested

#15117 Update ediscovery-reviewsetquery-update.md
  api-reference/beta/api/ediscovery-reviewsetquery-update.md
Labels: external

#15064 Add Date Range Field In Aggregation Filters
  concepts/search-concept-aggregation.md
Labels: ready to merge, internal, content review complete

#15107 Fix incorrect DateTime in changelog file
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, internal

#15108 Minor doc fixes
  api-reference/beta/api/application-addkey.md
  api-reference/beta/resources/application.md
  api-reference/beta/resources/keycredential.md
  api-reference/v1.0/api/application-addkey.md
  api-reference/v1.0/resources/application.md
  api-reference/v1.0/resources/keycredential.md
Labels: area: azure/AAD, do not merge, ready to merge, internal

#15099 Added explicit list subscription permissions
  api-reference/beta/api/subscription-list.md
  api-reference/v1.0/api/subscription-list.md
Labels: ready to merge

#15131 Update ediscovery-reviewset.md
  api-reference/beta/resources/ediscovery-reviewset.md
Labels: external

#15124 Update presence-setpresence.md
  api-reference/v1.0/api/presence-setpresence.md
Labels: external

#15120 Minor doc fixes
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/user.md
  api-reference/v1.0/resources/user.md
  concepts/permissions-reference.md
Labels: area: azure/AAD, do not merge, ready to merge, internal

#15135 Merge to publish.
  api-reference/beta/api/subscription-list.md
  api-reference/beta/resources/ediscovery-reviewset.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/user.md
  api-reference/v1.0/api/presence-setpresence.md
  api-reference/v1.0/api/subscription-list.md
  api-reference/v1.0/resources/user.md
  concepts/permissions-reference.md
Labels: internal

#15151 Update user-post-contacts.md
  api-reference/beta/api/user-post-contacts.md
Labels: external

#15150 Update user-post-contacts.md
  api-reference/v1.0/api/user-post-contacts.md
Labels: external

#14754 Add tenantOnboardingEligibilityReason enumeration to tenantStatusInformation complex type
  api-reference/beta/resources/enums-managedtenants.md
  api-reference/beta/resources/managedtenants-tenantstatusinformation.md
  changelog/Microsoft.MultiTenantPlatform.json
Labels: external, ready to merge, ready for content review, conflicting, area: multi-tenant management

#15144 Dec6th working with changes from old branch
  .github/workflows/changelog-validation.yml
  .openpublishing.publish.config.json
  api-reference/beta/api/insightssettings-update.md
  api-reference/beta/api/iteminsightssettings-get.md
  api-reference/beta/api/iteminsightssettings-update.md
  api-reference/beta/api/organizationsettings-get.md
  api-reference/beta/api/organizationsettings-list-iteminsights.md
  api-reference/beta/api/organizationsettings-list-peopleinsights.md
  api-reference/beta/api/user-list-people.md
  api-reference/beta/resources/insightssettings.md
  api-reference/beta/resources/iteminsights.md
  api-reference/beta/resources/iteminsightssettings.md
  api-reference/beta/resources/organizationsettings.md
  api-reference/beta/resources/userinsightssettings.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/user-list-people.md
  changelog/Microsoft.OfficeGraph.json
  changelog/Microsoft.People.json
  concepts/insights-customize-item-insights-privacy.md
  concepts/insights-customize-people-insights-privacy.md
  concepts/item-insights-overview.md
  concepts/people-example.md
  concepts/social-intel-concept-overview.md
  concepts/toc.yml
  redirects/.openpublishing.redirection.1221.json
Labels: ready to merge, internal, content review complete

#15025 Working With Changes From Old Branch
  concepts/insights-customize-people-insights-privacy.md
Labels: do not merge, internal, conflicting

#15140 Minor doc fixes
  api-reference/beta/api/directoryaudit-get.md
  api-reference/beta/api/directoryaudit-list.md
  api-reference/beta/api/provisioningobjectsummary-list.md
  api-reference/beta/api/signin-get.md
  api-reference/beta/api/signin-list.md
  api-reference/beta/api/user-list.md
  api-reference/beta/resources/administrativeunit.md
  api-reference/beta/resources/application.md
  api-reference/beta/resources/device.md
  api-reference/beta/resources/group.md
  api-reference/beta/resources/orgcontact.md
  api-reference/beta/resources/serviceprincipal.md
  api-reference/beta/resources/user.md
  api-reference/v1.0/api/directoryaudit-get.md
  api-reference/v1.0/api/directoryaudit-list.md
  api-reference/v1.0/api/provisioningobjectsummary-list.md
  api-reference/v1.0/api/signin-get.md
  api-reference/v1.0/api/signin-list.md
  api-reference/v1.0/resources/administrativeunit.md
  api-reference/v1.0/resources/application.md
  api-reference/v1.0/resources/device.md
  api-reference/v1.0/resources/group.md
  api-reference/v1.0/resources/orgcontact.md
  api-reference/v1.0/resources/serviceprincipal.md
  api-reference/v1.0/resources/user.md
  concepts/known-issues.md
  includes/filter-directory-objects.md
Labels: area: azure/AAD, ready to merge, internal

#14836 Added sourceImageNotGeneralized member to cloudPcDeviceImageStatusDetails
  api-reference/beta/resources/cloudpcdeviceimage.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, internal, content review complete, schema live, review feedback addressed

#14759 Teams - Promote system message events for Messaging APIs to v1.0
  api-reference/beta/resources/chatmessage.md
  api-reference/includes/teams-subscription-notes.md
  api-reference/v1.0/api/channel-list-messages.md
  api-reference/v1.0/api/channel-post-messages.md
  api-reference/v1.0/api/chat-list-messages.md
  api-reference/v1.0/api/chat-post-messages.md
  api-reference/v1.0/api/chatmessage-delta.md
  api-reference/v1.0/api/chatmessage-get.md
  api-reference/v1.0/api/chatmessage-list-replies.md
  api-reference/v1.0/api/chatmessage-post-replies.md
  api-reference/v1.0/api/chatmessage-post.md
  api-reference/v1.0/resources/callendedeventmessagedetail.md
  api-reference/v1.0/resources/callparticipantinfo.md
  api-reference/v1.0/resources/callrecordingeventmessagedetail.md
  api-reference/v1.0/resources/callstartedeventmessagedetail.md
  api-reference/v1.0/resources/calltranscripteventmessagedetail.md
  api-reference/v1.0/resources/channeladdedeventmessagedetail.md
  api-reference/v1.0/resources/channeldeletedeventmessagedetail.md
  api-reference/v1.0/resources/channeldescriptionupdatedeventmessagedetail.md
  api-reference/v1.0/resources/channelrenamedeventmessagedetail.md
  api-reference/v1.0/resources/channelsetasfavoritebydefaulteventmessagedetail.md
  api-reference/v1.0/resources/channelunsetasfavoritebydefaulteventmessagedetail.md
  api-reference/v1.0/resources/chatmessage.md
  api-reference/v1.0/resources/chatrenamedeventmessagedetail.md
  api-reference/v1.0/resources/conversationmemberroleupdatedeventmessagedetail.md
  api-reference/v1.0/resources/enums.md
  api-reference/v1.0/resources/eventmessagedetail.md
  api-reference/v1.0/resources/meetingpolicyupdatedeventmessagedetail.md
  api-reference/v1.0/resources/membersaddedeventmessagedetail.md
  api-reference/v1.0/resources/membersdeletedeventmessagedetail.md
  api-reference/v1.0/resources/membersjoinedeventmessagedetail.md
  api-reference/v1.0/resources/memberslefteventmessagedetail.md
  api-reference/v1.0/resources/tabupdatedeventmessagedetail.md
  api-reference/v1.0/resources/teamarchivedeventmessagedetail.md
  api-reference/v1.0/resources/teamcreatedeventmessagedetail.md
  api-reference/v1.0/resources/teamdescriptionupdatedeventmessagedetail.md
  api-reference/v1.0/resources/teamjoiningdisabledeventmessagedetail.md
  api-reference/v1.0/resources/teamjoiningenabledeventmessagedetail.md
  api-reference/v1.0/resources/teamrenamedeventmessagedetail.md
  api-reference/v1.0/resources/teamsappinstalledeventmessagedetail.md
  api-reference/v1.0/resources/teamsappremovedeventmessagedetail.md
  api-reference/v1.0/resources/teamsappupgradedeventmessagedetail.md
  api-reference/v1.0/resources/teamunarchivedeventmessagedetail.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.Teams.Core.json
  concepts/system-messages.md
Labels: area: teams, ready to merge, internal, content review complete, schema live

#15134 add stub of POST /assignmentrequests to EM
  api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md
  api-reference/v1.0/resources/accesspackageassignmentrequest.md
  api-reference/v1.0/resources/entitlementmanagement-root.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.DirectoryServices.json
Labels: area: azure/AAD, ready to merge, internal, content review complete

#14549 [CloudPC]Added microsoftManagedDesktop property and related complex type to provisionPolicy entity
  api-reference/beta/resources/cloudpcprovisioningpolicy.md
  api-reference/beta/resources/microsoftManagedDesktop.md
  api-reference/beta/toc.yml
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, internal, schema live

#12037 Update Teams Graph API-s doc for UPN Feature
  changelog/Microsoft.Teams.Core.json
Labels: external, do not merge, ready to merge

#15168 Update grouplifecyclepolicy-post-grouplifecyclepolicies.md
  api-reference/v1.0/api/grouplifecyclepolicy-post-grouplifecyclepolicies.md
Labels: external

#15166 Update dynamics-dimension-get.md
  api-reference/beta/api/dynamics-dimension-get.md
Labels: external

#15167 Update grouplifecyclepolicy-post-grouplifecyclepolicies.md
  api-reference/beta/api/grouplifecyclepolicy-post-grouplifecyclepolicies.md
Labels: external

#12749 Adding information regarding # character
  concepts/known-issues.md
Labels: area: azure/AAD, external, ready to merge, content review complete

#12520 Update user.md
  api-reference/beta/resources/user.md
  api-reference/v1.0/resources/user.md
Labels: area: azure/AAD, external, ready to merge, content review complete

#15019 Add documentation for new enum value
  api-reference/beta/resources/callrecords-clientuseragent.md
  api-reference/beta/resources/enums-callrecords.md
  api-reference/v1.0/resources/callrecords-clientuseragent.md
  api-reference/v1.0/resources/enums-callrecords.md
  changelog/Microsoft.IC3.DataPlatform.json
Labels: ready to merge, internal, area: cloud communications, content review complete

#15066 Added the DocumentSharing and Inbox data sets
  concepts/data-connect-datasets.md
Labels: ready to merge, internal, schema live

#15128 EM update $expand in 1.0 to new relationship names
  api-reference/v1.0/api/accesspackageassignmentrequest-filterbycurrentuser.md
  api-reference/v1.0/api/accesspackageassignmentrequest-get.md
  api-reference/v1.0/api/entitlementmanagement-list-accesspackages.md
  api-reference/v1.0/api/entitlementmanagement-list-assignmentrequests.md
  api-reference/v1.0/api/entitlementmanagement-list-assignments.md
Labels: area: azure/AAD, ready to merge, internal, content review complete, area: governance

#15141 Document new workarounds for adding Azure AD Graph permissions
  concepts/images/aadgraph-to-msgraph-migration/AppRegistrationManifest.png
  concepts/images/aadgraph-to-msgraph-migration/AzureADGraphPermissionsAPI.png
  concepts/migrate-azure-ad-graph-configure-permissions.md
Labels: area: azure/AAD, ready to merge, internal

#15156 update to ToC
  api-reference/beta/toc.yml
Labels: ready to merge, internal

#15163 Minor doc fixes
  api-reference/beta/api/group-post-groups.md
  api-reference/beta/api/group-update.md
  api-reference/beta/api/organizationalbranding-list-localizations.md
  api-reference/beta/api/organizationalbranding-post-localizations.md
  api-reference/beta/api/organizationalbranding-update.md
  api-reference/beta/api/organizationalbrandinglocalization-delete.md
  api-reference/beta/api/organizationalbrandinglocalization-update.md
  api-reference/beta/resources/group.md
  api-reference/v1.0/api/group-post-groups.md
  api-reference/v1.0/api/group-update.md
  api-reference/v1.0/api/organizationalbranding-list-localizations.md
  api-reference/v1.0/api/organizationalbranding-post-localizations.md
  api-reference/v1.0/api/organizationalbranding-update.md
  api-reference/v1.0/api/organizationalbrandinglocalization-delete.md
  api-reference/v1.0/api/organizationalbrandinglocalization-update.md
  api-reference/v1.0/resources/group.md
  concepts/migrate-azure-ad-graph-request-differences.md
Labels: area: azure/AAD, ready to merge, internal

#15180 Update broadcastmeetingsettings.md
  api-reference/v1.0/resources/broadcastmeetingsettings.md
Labels: external

#15179 Update broadcastmeetingsettings.md
  api-reference/beta/resources/broadcastmeetingsettings.md
Labels: external

#14840 Add properties and new APIs to cloudPC entity
  api-reference/beta/api/cloudpc-reboot.md
  api-reference/beta/api/cloudpc-rename.md
  api-reference/beta/api/cloudpc-troubleshoot.md
  api-reference/beta/resources/cloudpc.md
  api-reference/beta/resources/cloudpcloginresult.md
  api-reference/beta/resources/cloudpcremoteactionresult.md
  api-reference/beta/toc.yml
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, internal, content review complete

#15155 Add cloud deployments section in reports overview
  api-reference/beta/resources/report.md
  api-reference/v1.0/resources/report.md
  concepts/deployments.md
Labels: ready to merge, internal, content review complete

#15183 Update teams-licenses.md for model B
  concepts/teams-licenses.md
Labels: ready to merge, internal

#14962 Delta query support for Assignments and AssignmentCategories
  api-reference/beta/api/educationassignment-delta.md
  api-reference/beta/api/educationcategory-delta.md
  api-reference/beta/api/educationclass-list-assignments.md
  api-reference/beta/api/educationclass-list-categories.md
  api-reference/beta/resources/educationassignment.md
  api-reference/beta/resources/educationcategory.md
  api-reference/beta/resources/educationclass.md
  api-reference/beta/toc.yml
  changelog/Microsoft.EducationAssignment.json
  concepts/delta-query-overview.md
Labels: ready to merge, internal, schema live

#15174 Fix incorrect Date Time in changelog file
  changelog/Microsoft.Teams.Core.json
Labels: ready to merge, internal

#14865 User preferred presence
  api-reference/beta/api/presence-clearpresence.md
  api-reference/beta/api/presence-clearuserpreferredpresence.md
  api-reference/beta/api/presence-setpresence.md
  api-reference/beta/api/presence-setuserpreferredpresence.md
  api-reference/beta/api/subscription-post-subscriptions.md
  api-reference/beta/resources/presence.md
  api-reference/beta/toc.yml
  api-reference/includes/teams-subscription-notes.md
  api-reference/v1.0/api/subscription-post-subscriptions.md
  changelog/Microsoft.Skype.Calling.json
  concepts/permissions-reference.md
  concepts/webhooks-with-resource-data.md
Labels: do not merge, internal, content review in progress

#15188 Publish doc updates for presence API.
  api-reference/beta/api/presence-clearpresence.md
  api-reference/beta/api/presence-clearuserpreferredpresence.md
  api-reference/beta/api/presence-setpresence.md
  api-reference/beta/api/presence-setuserpreferredpresence.md
  api-reference/beta/api/subscription-post-subscriptions.md
  api-reference/beta/resources/presence.md
  api-reference/beta/toc.yml
  api-reference/includes/teams-subscription-notes.md
  api-reference/v1.0/api/subscription-post-subscriptions.md
  changelog/Microsoft.Skype.Calling.json
  concepts/permissions-reference.md
  concepts/webhooks-with-resource-data.md
Labels: internal

#15195 Update cloudpcloginresult.md
  api-reference/beta/resources/cloudpcloginresult.md
Labels: external

#15194 Update cloudpc-reprovision.md
  api-reference/beta/api/cloudpc-reprovision.md
Labels: external

#14777 Update ediscovery-redundancydetectionsettings.md
  api-reference/beta/resources/ediscovery-legalhold.md
  api-reference/beta/resources/ediscovery-redundancydetectionsettings.md
Labels: external, awaiting internal response

#15190 Minor doc fixes
  api-reference/beta/resources/authenticationmethodsroot.md
  api-reference/beta/resources/permissionscope.md
  api-reference/v1.0/resources/permissionscope.md
Labels: area: azure/AAD, ready to merge, internal

#15162 remove the note about subjectRightsRequest Permission
  api-reference/beta/api/subjectrightsrequest-get.md
  api-reference/beta/api/subjectrightsrequest-getfinalattachment.md
  api-reference/beta/api/subjectrightsrequest-getfinalreport.md
  api-reference/beta/api/subjectrightsrequest-list-notes.md
  api-reference/beta/api/subjectrightsrequest-list.md
  api-reference/beta/api/subjectrightsrequest-post-notes.md
  api-reference/beta/api/subjectrightsrequest-post.md
  api-reference/beta/api/subjectrightsrequest-update.md
  api-reference/v1.0/api/subjectrightsrequest-get.md
  api-reference/v1.0/api/subjectrightsrequest-getfinalattachment.md
  api-reference/v1.0/api/subjectrightsrequest-getfinalreport.md
  api-reference/v1.0/api/subjectrightsrequest-list-notes.md
  api-reference/v1.0/api/subjectrightsrequest-list.md
  api-reference/v1.0/api/subjectrightsrequest-post-notes.md
  api-reference/v1.0/api/subjectrightsrequest-post.md
  api-reference/v1.0/api/subjectrightsrequest-update.md
  concepts/known-issues.md
  concepts/permissions-reference.md
Labels: ready to merge, internal, content review complete

#15154 Fix issue https://github.com/microsoftgraph/microsoft-graph-docs/issues/11995
  concepts/search-concept-files.md
Labels: ready to merge, internal

#15065 GetSubmission and GetSubmissions - Adding Prefer header and expand options in Examples
  api-reference/beta/api/educationassignment-get.md
  api-reference/beta/api/educationassignment-list-submissions.md
  api-reference/beta/api/educationsubmission-get.md
  api-reference/beta/api/educationsubmission-reassign.md
  api-reference/beta/resources/educationsubmission.md
  api-reference/v1.0/api/educationassignment-get.md
  api-reference/v1.0/api/educationsubmission-get.md
Labels: ready to merge, internal, content review complete, schema live

#14391 Update signin.md
  api-reference/beta/resources/signin.md
  api-reference/v1.0/resources/signin.md
Labels: area: azure/AAD, ready to merge, internal, content review complete

#15198 Daily publishing Dec 9th 2021
  api-reference/beta/api/cloudpc-reprovision.md
  api-reference/beta/api/educationassignment-get.md
  api-reference/beta/api/educationassignment-list-submissions.md
  api-reference/beta/api/educationsubmission-get.md
  api-reference/beta/api/educationsubmission-reassign.md
  api-reference/beta/api/subjectrightsrequest-get.md
  api-reference/beta/api/subjectrightsrequest-getfinalattachment.md
  api-reference/beta/api/subjectrightsrequest-getfinalreport.md
  api-reference/beta/api/subjectrightsrequest-list-notes.md
  api-reference/beta/api/subjectrightsrequest-list.md
  api-reference/beta/api/subjectrightsrequest-post-notes.md
  api-reference/beta/api/subjectrightsrequest-post.md
  api-reference/beta/api/subjectrightsrequest-update.md
  api-reference/beta/resources/authenticationmethodsroot.md
  api-reference/beta/resources/cloudpcloginresult.md
  api-reference/beta/resources/ediscovery-legalhold.md
  api-reference/beta/resources/ediscovery-redundancydetectionsettings.md
  api-reference/beta/resources/educationsubmission.md
  api-reference/beta/resources/permissionscope.md
  api-reference/beta/resources/signin.md
  api-reference/v1.0/api/educationassignment-get.md
  api-reference/v1.0/api/educationsubmission-get.md
  api-reference/v1.0/api/subjectrightsrequest-get.md
  api-reference/v1.0/api/subjectrightsrequest-getfinalattachment.md
  api-reference/v1.0/api/subjectrightsrequest-getfinalreport.md
  api-reference/v1.0/api/subjectrightsrequest-list-notes.md
  api-reference/v1.0/api/subjectrightsrequest-list.md
  api-reference/v1.0/api/subjectrightsrequest-post-notes.md
  api-reference/v1.0/api/subjectrightsrequest-post.md
  api-reference/v1.0/api/subjectrightsrequest-update.md
  api-reference/v1.0/resources/permissionscope.md
  api-reference/v1.0/resources/signin.md
  concepts/known-issues.md
  concepts/permissions-reference.md
  concepts/search-concept-files.md
Labels: internal

#14928 Changes to revert occurrenceValues
  api-reference/beta/resources/event.md
  api-reference/v1.0/resources/event.md
  concepts/outlook-calendar-meeting-proposals.md
Labels: do not merge, internal, content review in progress

#15201 Second attempt to create a pull request to merge from main to live, to publish doc fixes for event API.
  api-reference/beta/resources/event.md
  api-reference/v1.0/resources/event.md
  concepts/outlook-calendar-meeting-proposals.md
Labels: do not merge, internal

#15213 Add UnifiedGroupMember.Read.AsGuest
  concepts/permissions-reference.md
Labels: internal

#15206 Bookings Beta changes before v1 release
  api-reference/beta/api/bookingappointment-get.md
  api-reference/beta/api/bookingappointment-update.md
  api-reference/beta/api/bookingbusiness-get.md
  api-reference/beta/api/bookingbusiness-list-appointments.md
  api-reference/beta/api/bookingbusiness-list-calendarview.md
  api-reference/beta/api/bookingbusiness-list-staffmembers.md
  api-reference/beta/api/bookingbusiness-post-appointments.md
  api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md
  api-reference/beta/api/bookingbusiness-post-staffmembers.md
  api-reference/beta/api/bookingservice-update.md
  api-reference/beta/api/bookingstaffmember-get.md
  api-reference/beta/api/bookingstaffmember-update.md
  api-reference/beta/resources/bookingappointment.md
  api-reference/beta/resources/bookingcurrency.md
  api-reference/beta/resources/bookingcustomer.md
  api-reference/beta/resources/bookingcustomerinformation.md
  api-reference/beta/resources/bookingnamedentity.md
  api-reference/beta/resources/bookingperson.md
  api-reference/beta/resources/bookingquestionanswer.md
  api-reference/beta/resources/bookingquestionassignment.md
  api-reference/beta/resources/bookingreminder.md
  api-reference/beta/resources/bookingschedulingpolicy.md
  api-reference/beta/resources/bookingservice.md
  api-reference/beta/resources/bookingstaffmember.md
  api-reference/beta/resources/bookingworkhours.md
  api-reference/beta/resources/bookingworktimeslot.md
  changelog/Microsoft.Bookings.json
Labels: external

#15212 Merge final changes from Bookings beta to v1
  api-reference/v1.0/api/bookingappointment-get.md
  api-reference/v1.0/api/bookingbusiness-list-appointments.md
  api-reference/v1.0/api/bookingbusiness-list-calendarview.md
  api-reference/v1.0/api/bookingbusiness-post-appointments.md
  api-reference/v1.0/api/bookingcustomer-get.md
  api-reference/v1.0/api/bookingcustomer-update.md
  api-reference/v1.0/api/bookingstaffmember-get.md
  api-reference/v1.0/api/bookingstaffmember-update.md
  api-reference/v1.0/resources/bookingcustomerinformation.md
Labels: external, conflicting

#15202 Minor doc fixes
  concepts/migrate-azure-ad-graph-faq.md
Labels: ready to merge, internal

#15173 [CloudPC]Update resize API request body
  api-reference/beta/api/manageddevice-resizecloudpc.md
Labels: ready to merge, internal, content review complete, schema live

#14927 New files for Tasks API - beta
  api-reference/beta/api/basetask-delete.md
  api-reference/beta/api/basetask-delta.md
  api-reference/beta/api/basetask-get.md
  api-reference/beta/api/basetask-list-checklistitems.md
  api-reference/beta/api/basetask-list-linkedresources.md
  api-reference/beta/api/basetask-move.md
  api-reference/beta/api/basetask-post-checklistitems.md
  api-reference/beta/api/basetask-post-linkedresources.md
  api-reference/beta/api/basetask-update.md
  api-reference/beta/api/basetasklist-delta.md
  api-reference/beta/api/basetasklist-get.md
  api-reference/beta/api/basetasklist-list-tasks.md
  api-reference/beta/api/basetasklist-post-tasks.md
  api-reference/beta/api/checklistitem-delete.md
  api-reference/beta/api/checklistitem-get.md
  api-reference/beta/api/checklistitem-update.md
  api-reference/beta/api/linkedresource_v2-delete.md
  api-reference/beta/api/linkedresource_v2-get.md
  api-reference/beta/api/linkedresource_v2-update.md
  api-reference/beta/api/opentypeextension-delete.md
  api-reference/beta/api/opentypeextension-get.md
  api-reference/beta/api/opentypeextension-post-opentypeextension.md
  api-reference/beta/api/opentypeextension-update.md
  api-reference/beta/api/subscription-delete.md
  api-reference/beta/api/subscription-get.md
  api-reference/beta/api/subscription-post-subscriptions.md
  api-reference/beta/api/subscription-update.md
  api-reference/beta/api/tasklist-delete.md
  api-reference/beta/api/tasklist-update.md
  api-reference/beta/api/tasks-list-lists.md
  api-reference/beta/api/tasks-post-lists.md
  api-reference/beta/resources/basetask.md
  api-reference/beta/resources/basetasklist.md
  api-reference/beta/resources/checklistitem.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/linkedresource_v2.md
  api-reference/beta/resources/opentypeextension.md
  api-reference/beta/resources/personaltaskproperties.md
  api-reference/beta/resources/subscription.md
  api-reference/beta/resources/task.md
  api-reference/beta/resources/tasklist.md
  api-reference/beta/resources/tasks-overview.md
  api-reference/beta/resources/tasks.md
  api-reference/beta/resources/webhooks.md
  api-reference/beta/resources/wellknowntasklist.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Tasks.json
  concepts/images/tasks-api-entities.png
Labels: ready to merge, internal, area: todo, content review complete

#15008 Rebrand security products
  api-reference/beta/api/alert-list.md
  api-reference/beta/api/intune-deviceconfig-macosendpointprotectionconfiguration-create.md
  api-reference/beta/api/intune-deviceconfig-macosendpointprotectionconfiguration-update.md
  api-reference/beta/config/link-validation-config.json
  api-reference/beta/resources/intune-apps-macosmdatpapp.md
  api-reference/beta/resources/intune-deviceconfig-macosendpointprotectionconfiguration.md
  api-reference/beta/resources/intune-partnerintegration-deviceappmanagementtaskcategory.md
  api-reference/beta/resources/report-m365defender-reports-overview.md
  api-reference/beta/resources/security-api-overview.md
  api-reference/beta/resources/securityaction.md
  api-reference/beta/resources/tiindicator.md
  api-reference/v1.0/api/alert-list.md
  api-reference/v1.0/resources/security-api-overview.md
  concepts/overview-major-services.md
  concepts/whats-new-earlier.md
Labels: do not merge, ready to merge, internal, content review complete

#15222 Update what's new so far per changelog.
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: do not merge, internal

#15223 Refreshed what's new with a few updates in December.
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: internal

#15233 Missing odata.type for Bookings staff/customer APIs (v1.0)
  api-reference/beta/api/bookingbusiness-list-customers.md
  api-reference/beta/api/bookingbusiness-list-staffmembers.md
  api-reference/beta/api/bookingbusiness-post-customers.md
  api-reference/beta/api/bookingbusiness-post-staffmembers.md
  api-reference/beta/api/bookingcustomer-get.md
  api-reference/beta/api/bookingcustomer-update.md
  api-reference/beta/api/bookingstaffmember-get.md
  api-reference/beta/api/bookingstaffmember-update.md
Labels: external

#15238 Update return status code from 200 - Accepted to 200 - OK when proces…
  concepts/webhooks.md
Labels: external

#15235 fixing minor typos
  api-reference/beta/api/basetasklist-list-tasks.md
  api-reference/beta/api/tasks-list-lists.md
  api-reference/beta/resources/tasks-overview.md
Labels: ready to merge, internal, content review complete

#14728 Adding List Teams API documentation
  api-reference/beta/api/teams-list.md
  api-reference/beta/resources/team.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Teams.Core.json
Labels: ready to merge, internal, content review complete

#15240 Daily publishing Dec 13th 2021
  api-reference/beta/api/basetasklist-list-tasks.md
  api-reference/beta/api/tasks-list-lists.md
  api-reference/beta/api/teams-list.md
  api-reference/beta/resources/tasks-overview.md
  api-reference/beta/resources/team.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Teams.Core.json
  concepts/webhooks.md
Labels: internal

#15244 Fix incorrect Date Time in changelog file
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, internal

#15246 Update teams-list.md
  api-reference/beta/api/teams-list.md
Labels: external

#14926 [CloudPC]Add CloudPC as supported RBAC provider
  api-reference/beta/api/rbacapplication-list-roledefinitions.md
  api-reference/beta/api/rbacapplication-post-roledefinitions.md
  api-reference/beta/api/unifiedroledefinition-delete.md
  api-reference/beta/api/unifiedroledefinition-get.md
  api-reference/beta/api/unifiedroledefinition-update.md
  api-reference/beta/resources/unifiedroledefinition.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, internal, content review complete, schema live

#15251 [Draft] Base type and enum changes for bookingPerson and answerInputType
  api-reference/v1.0/api/bookingappointment-cancel.md
  api-reference/v1.0/api/bookingappointment-update.md
  api-reference/v1.0/api/bookingbusiness-list-calendarview.md
  api-reference/v1.0/api/bookingbusiness-list.md
  api-reference/v1.0/api/bookingbusiness-post-bookingbusinesses.md
  api-reference/v1.0/api/bookingbusiness-publish.md
  api-reference/v1.0/api/bookingcustomer-update.md
Labels: external

#15255 Bookings v1: Typo in bookingCustomerInformation
  api-reference/v1.0/resources/bookingcustomerinformation.md
Labels: external

#15256 Bookings v1: Remove references to bookingNamedEntity
  api-reference/v1.0/resources/bookingcustomquestion.md
Labels: external

#15257 Bookings v1: Adding priceType and additionalInformation
  api-reference/v1.0/api/bookingappointment-update.md
  api-reference/v1.0/api/bookingservice-update.md
  api-reference/v1.0/resources/bookingappointment.md
  api-reference/v1.0/resources/bookingservice.md
  api-reference/v1.0/resources/enums.md
  changelog/Microsoft.Bookings.json
Labels: external

#15263 Publishing the bookings v1 PR
  api-reference/v1.0/api/bookingappointment-cancel.md
  api-reference/v1.0/api/bookingappointment-delete.md
  api-reference/v1.0/api/bookingappointment-get.md
  api-reference/v1.0/api/bookingappointment-update.md
  api-reference/v1.0/api/bookingbusiness-delete.md
  api-reference/v1.0/api/bookingbusiness-get.md
  api-reference/v1.0/api/bookingbusiness-list-appointments.md
  api-reference/v1.0/api/bookingbusiness-list-calendarview.md
  api-reference/v1.0/api/bookingbusiness-list-customers.md
  api-reference/v1.0/api/bookingbusiness-list-customquestions.md
  api-reference/v1.0/api/bookingbusiness-list-services.md
  api-reference/v1.0/api/bookingbusiness-list-staffmembers.md
  api-reference/v1.0/api/bookingbusiness-list.md
  api-reference/v1.0/api/bookingbusiness-post-appointments.md
  api-reference/v1.0/api/bookingbusiness-post-bookingbusinesses.md
  api-reference/v1.0/api/bookingbusiness-post-customers.md
  api-reference/v1.0/api/bookingbusiness-post-customquestions.md
  api-reference/v1.0/api/bookingbusiness-post-services.md
  api-reference/v1.0/api/bookingbusiness-post-staffmembers.md
  api-reference/v1.0/api/bookingbusiness-publish.md
  api-reference/v1.0/api/bookingbusiness-unpublish.md
  api-reference/v1.0/api/bookingbusiness-update.md
  api-reference/v1.0/api/bookingcurrency-get.md
  api-reference/v1.0/api/bookingcurrency-list.md
  api-reference/v1.0/api/bookingcustomer-delete.md
  api-reference/v1.0/api/bookingcustomer-get.md
  api-reference/v1.0/api/bookingcustomer-update.md
  api-reference/v1.0/api/bookingcustomquestion-delete.md
  api-reference/v1.0/api/bookingcustomquestion-get.md
  api-reference/v1.0/api/bookingcustomquestion-update.md
  api-reference/v1.0/api/bookingservice-delete.md
  api-reference/v1.0/api/bookingservice-get.md
  api-reference/v1.0/api/bookingservice-update.md
  api-reference/v1.0/api/bookingstaffmember-delete.md
  api-reference/v1.0/api/bookingstaffmember-get.md
  api-reference/v1.0/api/bookingstaffmember-update.md
  api-reference/v1.0/resources/booking-api-overview.md
  api-reference/v1.0/resources/bookingappointment.md
  api-reference/v1.0/resources/bookingbusiness.md
  api-reference/v1.0/resources/bookingcurrency.md
  api-reference/v1.0/resources/bookingcustomer.md
  api-reference/v1.0/resources/bookingcustomerbase.md
  api-reference/v1.0/resources/bookingcustomerinformation.md
  api-reference/v1.0/resources/bookingcustomerinformationbase.md
  api-reference/v1.0/resources/bookingcustomquestion.md
  api-reference/v1.0/resources/bookingquestionanswer.md
  api-reference/v1.0/resources/bookingquestionassignment.md
  api-reference/v1.0/resources/bookingreminder.md
  api-reference/v1.0/resources/bookingschedulingpolicy.md
  api-reference/v1.0/resources/bookingservice.md
  api-reference/v1.0/resources/bookingstaffmember.md
  api-reference/v1.0/resources/bookingstaffmemberbase.md
  api-reference/v1.0/resources/bookingworkhours.md
  api-reference/v1.0/resources/bookingworktimeslot.md
  api-reference/v1.0/resources/enums.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.Bookings.json
Labels: internal

#15164 Asaniyer bookingsbetaupdate
  api-reference/beta/api/bookingappointment-cancel.md
  api-reference/beta/api/bookingappointment-delete.md
  api-reference/beta/api/bookingappointment-get.md
  api-reference/beta/api/bookingappointment-update.md
  api-reference/beta/api/bookingbusiness-delete.md
  api-reference/beta/api/bookingbusiness-get.md
  api-reference/beta/api/bookingbusiness-list-appointments.md
  api-reference/beta/api/bookingbusiness-list-calendarview.md
  api-reference/beta/api/bookingbusiness-list-customers.md
  api-reference/beta/api/bookingbusiness-list-customquestions.md
  api-reference/beta/api/bookingbusiness-list-services.md
  api-reference/beta/api/bookingbusiness-list-staffmembers.md
  api-reference/beta/api/bookingbusiness-list.md
  api-reference/beta/api/bookingbusiness-post-appointments.md
  api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md
  api-reference/beta/api/bookingbusiness-post-customers.md
  api-reference/beta/api/bookingbusiness-post-customquestions.md
  api-reference/beta/api/bookingbusiness-post-services.md
  api-reference/beta/api/bookingbusiness-post-staffmembers.md
  api-reference/beta/api/bookingbusiness-publish.md
  api-reference/beta/api/bookingbusiness-unpublish.md
  api-reference/beta/api/bookingbusiness-update.md
  api-reference/beta/api/bookingcustomer-delete.md
  api-reference/beta/api/bookingcustomer-get.md
  api-reference/beta/api/bookingcustomer-update.md
  api-reference/beta/api/bookingcustomquestion-delete.md
  api-reference/beta/api/bookingcustomquestion-get.md
  api-reference/beta/api/bookingcustomquestion-update.md
  api-reference/beta/api/bookingservice-delete.md
  api-reference/beta/api/bookingservice-get.md
  api-reference/beta/api/bookingservice-update.md
  api-reference/beta/api/bookingstaffmember-delete.md
  api-reference/beta/api/bookingstaffmember-get.md
  api-reference/beta/api/bookingstaffmember-update.md
  api-reference/beta/resources/bookingappointment.md
  api-reference/beta/resources/bookingbusiness.md
  api-reference/beta/resources/bookingcurrency.md
  api-reference/beta/resources/bookingcustomer.md
  api-reference/beta/resources/bookingcustomerinformation.md
  api-reference/beta/resources/bookingcustomerinformationbase.md
  api-reference/beta/resources/bookingcustomquestion.md
  api-reference/beta/resources/bookingnamedentity.md
  api-reference/beta/resources/bookingperson.md
  api-reference/beta/resources/bookingquestionanswer.md
  api-reference/beta/resources/bookingquestionassignment.md
  api-reference/beta/resources/bookingreminder.md
  api-reference/beta/resources/bookingschedulingpolicy.md
  api-reference/beta/resources/bookingservice.md
  api-reference/beta/resources/bookingstaffmember.md
  api-reference/beta/resources/bookingworkhours.md
  api-reference/beta/resources/enums.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Bookings.json
Labels: area: bookings, do not merge, internal, content review complete

#15265 Merging the bookings beta PR
  api-reference/beta/api/bookingappointment-cancel.md
  api-reference/beta/api/bookingappointment-delete.md
  api-reference/beta/api/bookingappointment-get.md
  api-reference/beta/api/bookingappointment-update.md
  api-reference/beta/api/bookingbusiness-delete.md
  api-reference/beta/api/bookingbusiness-get.md
  api-reference/beta/api/bookingbusiness-list-appointments.md
  api-reference/beta/api/bookingbusiness-list-calendarview.md
  api-reference/beta/api/bookingbusiness-list-customers.md
  api-reference/beta/api/bookingbusiness-list-customquestions.md
  api-reference/beta/api/bookingbusiness-list-services.md
  api-reference/beta/api/bookingbusiness-list-staffmembers.md
  api-reference/beta/api/bookingbusiness-list.md
  api-reference/beta/api/bookingbusiness-post-appointments.md
  api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md
  api-reference/beta/api/bookingbusiness-post-customers.md
  api-reference/beta/api/bookingbusiness-post-customquestions.md
  api-reference/beta/api/bookingbusiness-post-services.md
  api-reference/beta/api/bookingbusiness-post-staffmembers.md
  api-reference/beta/api/bookingbusiness-publish.md
  api-reference/beta/api/bookingbusiness-unpublish.md
  api-reference/beta/api/bookingbusiness-update.md
  api-reference/beta/api/bookingcustomer-delete.md
  api-reference/beta/api/bookingcustomer-get.md
  api-reference/beta/api/bookingcustomer-update.md
  api-reference/beta/api/bookingcustomquestion-delete.md
  api-reference/beta/api/bookingcustomquestion-get.md
  api-reference/beta/api/bookingcustomquestion-update.md
  api-reference/beta/api/bookingservice-delete.md
  api-reference/beta/api/bookingservice-get.md
  api-reference/beta/api/bookingservice-update.md
  api-reference/beta/api/bookingstaffmember-delete.md
  api-reference/beta/api/bookingstaffmember-get.md
  api-reference/beta/api/bookingstaffmember-update.md
  api-reference/beta/resources/bookingappointment.md
  api-reference/beta/resources/bookingbusiness.md
  api-reference/beta/resources/bookingcurrency.md
  api-reference/beta/resources/bookingcustomer.md
  api-reference/beta/resources/bookingcustomerinformation.md
  api-reference/beta/resources/bookingcustomerinformationbase.md
  api-reference/beta/resources/bookingcustomquestion.md
  api-reference/beta/resources/bookingnamedentity.md
  api-reference/beta/resources/bookingperson.md
  api-reference/beta/resources/bookingquestionanswer.md
  api-reference/beta/resources/bookingquestionassignment.md
  api-reference/beta/resources/bookingreminder.md
  api-reference/beta/resources/bookingschedulingpolicy.md
  api-reference/beta/resources/bookingservice.md
  api-reference/beta/resources/bookingstaffmember.md
  api-reference/beta/resources/bookingworkhours.md
  api-reference/beta/resources/enums.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Bookings.json
Labels: internal

#15152 added documentation for live event captions (beta)
  api-reference/beta/resources/broadcastmeetingcaptionsettings.md
  api-reference/beta/resources/broadcastmeetingsettings.md
  changelog/Microsoft.Skype.Calling.json
Labels: ready to merge, internal, content review complete

#15269 Merging this one first to avoid conflicts
  api-reference/beta/resources/broadcastmeetingcaptionsettings.md
  api-reference/beta/resources/broadcastmeetingsettings.md
  changelog/Microsoft.Skype.Calling.json
Labels: internal

#15253 Update dynamics-agedaccountspayable-get.md
  api-reference/beta/api/dynamics-agedaccountspayable-get.md
Labels: external

#15268 Updated link
  concepts/teams-licenses.md
Labels: ready to merge, internal

#15267 Add docs for accessReviewInstance update operation
  api-reference/beta/api/accessreviewinstance-update.md
  api-reference/beta/resources/accessreviewinstance.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/accessreviewinstance-update.md
  api-reference/v1.0/resources/accessreviewinstance.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.IdentityGovernance.AccessReviews.json
Labels: area: azure/AAD, ready to merge, internal, area: governance

#15264 Minor doc fixes
  api-reference/beta/resources/accessreviewschedulesettings.md
  api-reference/beta/resources/patternedrecurrence.md
  api-reference/beta/resources/recurrencepattern.md
  api-reference/v1.0/resources/accessreviewschedulesettings.md
  api-reference/v1.0/resources/patternedrecurrence.md
  api-reference/v1.0/resources/recurrencepattern.md
Labels: area: azure/AAD, ready to merge, internal

#15203 Update description of getSharePointSiteUsageSiteCounts API
  api-reference/beta/api/reportroot-getsharepointsiteusagesitecounts.md
  api-reference/beta/resources/sharepoint-site-usage-reports.md
  api-reference/v1.0/api/reportroot-getsharepointsiteusagesitecounts.md
  api-reference/v1.0/resources/sharepoint-site-usage-reports.md
Labels: ready to merge, internal, content review complete

#15114 GA Deeplink for Chats [do not merge before 12/9]
  api-reference/beta/resources/chat.md
  api-reference/v1.0/resources/chat.md
  changelog/Microsoft.Teams.GraphSvc.json
Labels: ready to merge, internal, content review complete

#15020 fix URL for Posting Assignment Category
  api-reference/v1.0/api/educationclass-post-category.md
Labels: ready to merge, internal, content review complete, schema live

#14963 Add maximum values to permissions reference doc
  concepts/permissions-reference.md
Labels: ready to merge, internal, content review complete

#15281 Update user-list-joinedteams.md
  api-reference/beta/api/user-list-joinedteams.md
Labels: external

#15279 Fix TOC content for beta
  api-reference/beta/toc.yml
Labels: do not merge, ready to merge, internal, content review complete

#15170 added documentation for external registration
  api-reference/beta/api/externalmeetingregistrant-delete.md
  api-reference/beta/api/externalmeetingregistrant-list.md
  api-reference/beta/api/externalmeetingregistrant-post.md
  api-reference/beta/api/externalmeetingregistration-delete.md
  api-reference/beta/api/externalmeetingregistration-get.md
  api-reference/beta/api/externalmeetingregistration-post.md
  api-reference/beta/api/meetingregistration-get.md
  api-reference/beta/api/meetingregistration-list-customquestions.md
  api-reference/beta/api/meetingregistration-post-customquestions.md
  api-reference/beta/api/meetingregistration-post-registrants.md
  api-reference/beta/api/meetingregistration-post.md
  api-reference/beta/resources/externalmeetingregistrant.md
  api-reference/beta/resources/externalmeetingregistration.md
  api-reference/beta/resources/meetingregistrant.md
  api-reference/beta/resources/meetingregistrantbase.md
  api-reference/beta/resources/meetingregistration.md
  api-reference/beta/resources/meetingregistrationbase.md
  api-reference/beta/resources/onlinemeeting.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Skype.Calling.json
Labels: do not merge, ready to merge, internal, content review complete

#14955 Update add-properties-profilecard.md
  concepts/add-properties-profilecard.md
Labels: ready to merge

#15280 Update user-list-joinedteams.md
  api-reference/v1.0/api/user-list-joinedteams.md
Labels: external

#15283 Daily publishing Dec 16th 2021
  api-reference/beta/api/externalmeetingregistrant-delete.md
  api-reference/beta/api/externalmeetingregistrant-list.md
  api-reference/beta/api/externalmeetingregistrant-post.md
  api-reference/beta/api/externalmeetingregistration-delete.md
  api-reference/beta/api/externalmeetingregistration-get.md
  api-reference/beta/api/externalmeetingregistration-post.md
  api-reference/beta/api/meetingregistration-get.md
  api-reference/beta/api/meetingregistration-list-customquestions.md
  api-reference/beta/api/meetingregistration-post-customquestions.md
  api-reference/beta/api/meetingregistration-post-registrants.md
  api-reference/beta/api/meetingregistration-post.md
  api-reference/beta/api/user-list-joinedteams.md
  api-reference/beta/resources/externalmeetingregistrant.md
  api-reference/beta/resources/externalmeetingregistration.md
  api-reference/beta/resources/meetingregistrant.md
  api-reference/beta/resources/meetingregistrantbase.md
  api-reference/beta/resources/meetingregistration.md
  api-reference/beta/resources/meetingregistrationbase.md
  api-reference/beta/resources/onlinemeeting.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/user-list-joinedteams.md
  changelog/Microsoft.Skype.Calling.json
  concepts/add-properties-profilecard.md
Labels: internal

#15272 Remove "preview" for presence subscription
  concepts/presen
Labels: do not merge, ready to merge, internal, content review complete

#15216 Add UnifiedGroupMember.Read.AsGuest
  concepts/permissions-reference.md
Labels: area: azure/AAD, ready to merge, internal, content review complete

#14837 Add properties expirationDate & osStatus to cloudPcDeviceImage
  api-reference/beta/resources/cloudpcdeviceimage.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, internal, content review complete

#15094 v1.0 Doc updates - user assignments, reassign submission and addToCalendar
  api-reference/v1.0/api/educationassignment-update.md
  api-reference/v1.0/api/educationassignmentdefaults-update.md
  api-reference/v1.0/api/educationsubmission-reassign.md
  api-reference/v1.0/api/educationuser-list-assignments.md
  api-reference/v1.0/resources/education-overview.md
  api-reference/v1.0/resources/educationassignment.md
  api-reference/v1.0/resources/educationassignmentdefaults.md
  api-reference/v1.0/resources/educationsubmission.md
  api-reference/v1.0/resources/educationuser.md
  api-reference/v1.0/resources/enums.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.EducationAssignment.json
Labels: do not merge, internal, content review complete, schema live

#15291 Daily publishing Dec 17th 2021
  api-reference/beta/resources/cloudpcdeviceimage.md
  api-reference/v1.0/api/educationassignment-update.md
  api-reference/v1.0/api/educationassignmentdefaults-update.md
  api-reference/v1.0/api/educationsubmission-reassign.md
  api-reference/v1.0/api/educationuser-list-assignments.md
  api-reference/v1.0/resources/education-overview.md
  api-reference/v1.0/resources/educationassignment.md
  api-reference/v1.0/resources/educationassignmentdefaults.md
  api-reference/v1.0/resources/educationsubmission.md
  api-reference/v1.0/resources/educationuser.md
  api-reference/v1.0/resources/enums.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.CloudManagedDesktop.json
  changelog/Microsoft.EducationAssignment.json
  concepts/permissions-reference.md
  concepts/presen
Labels: internal

#15338 Update group-post-groups.md
  api-reference/beta/api/group-post-groups.md
Labels: external

#15331 Update user-list-licensedetails.md
  api-reference/beta/api/user-list-licensedetails.md
Labels: external

#15320 Update team-archive.md
  api-reference/beta/api/team-archive.md
Labels: external

#15330 Update user-list-licensedetails.md
  api-reference/v1.0/api/user-list-licensedetails.md
Labels: external

#15319 Update team-archive.md
  api-reference/v1.0/api/team-archive.md
Labels: external

#15309 Fix broken link in bookings-api-overview.md
  api-reference/v1.0/resources/booking-api-overview.md
Labels: external

#15302 Update educationuser-delete.md
  api-reference/beta/api/educationuser-delete.md
Labels: external

#15301 Update educationuser-delete.md
  api-reference/v1.0/api/educationuser-delete.md
Labels: external

#15297 Broken Change notifications Overview page
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
  concepts/toc.yml
  concepts/webhooks.md
Labels: area: azure/AAD, ready to merge, internal, content review complete

#15289 Clarifying how far back lastsignindatetime goes
  api-reference/beta/resources/signinactivity.md
Labels: area: azure/AAD, ready to merge, internal, content review complete

#15287 fixing broken link to known issue
  api-reference/beta/api/user-list.md
Labels: area: azure/AAD, ready to merge, internal

#15341 Update plannergroup-list-plans.md
  api-reference/beta/api/plannergroup-list-plans.md
Labels: external

#15340 Update plannergroup-list-plans.md
  api-reference/v1.0/api/plannergroup-list-plans.md
Labels: external

#14832 Add deprecation notes
  api-reference/beta/api/user-post-notifications.md
  api-reference/beta/resources/notifications-api-overview.md
  api-reference/beta/resources/projectrome-notification.md
  api-reference/beta/toc.yml
  concepts/notifications-concept-overview.md
  concepts/overview-major-services.md
  concepts/toc.yml
Labels: external, ready to merge

#15313 Calendar issues
  api-reference/beta/api/calendar-list-calendarview.md
  api-reference/v1.0/api/calendar-list-calendarview.md
Labels: do not merge, ready to merge, internal, content review complete

#15321 Doc bugs - Patch and publish Assignment properties
  api-reference/beta/api/educationassignment-publish.md
  api-reference/beta/api/educationassignment-update.md
  api-reference/v1.0/api/educationassignment-publish.md
  api-reference/v1.0/api/educationassignment-update.md
Labels: ready to merge, internal, content review complete, schema live

#15333 Doc bugs - Add link references to educationResource and educationAssignmentRecipient resources
  api-reference/beta/api/educationassignment-list-resources.md
  api-reference/beta/api/educationassignment-publish.md
  api-reference/beta/api/educationassignment-update.md
  api-reference/beta/api/educationassignmentresource-delete.md
  api-reference/beta/api/educationsubmission-list-resources.md
  api-reference/beta/api/educationsubmission-list-submittedresources.md
  api-reference/beta/api/educationsubmission-post-resources.md
  api-reference/beta/api/educationsubmissionresource-delete.md
  api-reference/v1.0/api/educationassignment-list-resources.md
  api-reference/v1.0/api/educationassignment-update.md
  api-reference/v1.0/api/educationassignmentresource-delete.md
  api-reference/v1.0/api/educationsubmission-list-resources.md
  api-reference/v1.0/api/educationsubmission-list-submittedresources.md
  api-reference/v1.0/api/educationsubmission-post-resources.md
  api-reference/v1.0/api/educationsubmissionresource-delete.md
Labels: ready to merge, internal, content review complete, schema live

#15342 Doc bugs - link resource pages for grading assignments
  api-reference/beta/api/educationassignment-update.md
  api-reference/beta/api/educationrubric-update.md
  api-reference/beta/resources/educationassignmentgradetype.md
  api-reference/v1.0/api/educationassignment-update.md
  api-reference/v1.0/api/educationrubric-update.md
  api-reference/v1.0/resources/educationassignmentgradetype.md
Labels: do not merge, ready to merge, internal, content review complete, schema live

#15346 Daily publishing Dec 24th 2021
  api-reference/beta/api/calendar-list-calendarview.md
  api-reference/beta/api/educationassignment-list-resources.md
  api-reference/beta/api/educationassignment-publish.md
  api-reference/beta/api/educationassignment-update.md
  api-reference/beta/api/educationassignmentresource-delete.md
  api-reference/beta/api/educationrubric-update.md
  api-reference/beta/api/educationsubmission-list-resources.md
  api-reference/beta/api/educationsubmission-list-submittedresources.md
  api-reference/beta/api/educationsubmission-post-resources.md
  api-reference/beta/api/educationsubmissionresource-delete.md
  api-reference/beta/api/plannergroup-list-plans.md
  api-reference/beta/api/user-post-notifications.md
  api-reference/beta/resources/educationassignmentgradetype.md
  api-reference/beta/resources/notifications-api-overview.md
  api-reference/beta/resources/projectrome-notification.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/calendar-list-calendarview.md
  api-reference/v1.0/api/educationassignment-list-resources.md
  api-reference/v1.0/api/educationassignment-publish.md
  api-reference/v1.0/api/educationassignment-update.md
  api-reference/v1.0/api/educationassignmentresource-delete.md
  api-reference/v1.0/api/educationrubric-update.md
  api-reference/v1.0/api/educationsubmission-list-resources.md
  api-reference/v1.0/api/educationsubmission-list-submittedresources.md
  api-reference/v1.0/api/educationsubmission-post-resources.md
  api-reference/v1.0/api/educationsubmissionresource-delete.md
  api-reference/v1.0/api/plannergroup-list-plans.md
  api-reference/v1.0/resources/educationassignmentgradetype.md
  concepts/notifications-concept-overview.md
  concepts/overview-major-services.md
  concepts/toc.yml
Labels: internal

#15355 Update assignments-submissions-states-transition.md
  concepts/assignments-submissions-states-transition.md
Labels: external

#15354 Update whats-new-overview.md
  concepts/whats-new-overview.md
Labels: external

#14465 Azure AD sign in logs updates Q1
  api-reference/beta/api/signin-get.md
  api-reference/beta/api/signin-list.md
  api-reference/beta/resources/appidentity.md
  api-reference/beta/resources/appliedconditionalaccesspolicy.md
  api-reference/beta/resources/auditactivityinitiator.md
  api-reference/beta/resources/audituseridentity.md
  api-reference/beta/resources/authenticationstrength.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/riskdetection.md
  api-reference/beta/resources/riskuseractivity.md
  api-reference/beta/resources/signin.md
  changelog/Microsoft.AAD.Reporting.json
  changelog/Microsoft.IdentityProtectionServices.json
Labels: ready to merge, internal, content review complete, schema live

#14437 add docs describing how to address drive items in a drive by path / id
  api-reference/beta/resources/driveitem.md
  api-reference/beta/resources/onedrive.md
  api-reference/v1.0/resources/driveitem.md
  api-reference/v1.0/resources/onedrive.md
  concepts/onedrive-addressing-driveitems.md
  concepts/toc.yml
Labels: ready to merge, internal, content review complete

#15357 Daily publishing Dec 28th 2021
  api-reference/beta/api/signin-get.md
  api-reference/beta/api/signin-list.md
  api-reference/beta/resources/appidentity.md
  api-reference/beta/resources/appliedconditionalaccesspolicy.md
  api-reference/beta/resources/auditactivityinitiator.md
  api-reference/beta/resources/audituseridentity.md
  api-reference/beta/resources/authenticationstrength.md
  api-reference/beta/resources/driveitem.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/onedrive.md
  api-reference/beta/resources/riskdetection.md
  api-reference/beta/resources/riskuseractivity.md
  api-reference/beta/resources/signin.md
  api-reference/v1.0/resources/driveitem.md
  api-reference/v1.0/resources/onedrive.md
  changelog/Microsoft.AAD.Reporting.json
  changelog/Microsoft.IdentityProtectionServices.json
  concepts/assignments-submissions-states-transition.md
  concepts/onedrive-addressing-driveitems.md
  concepts/toc.yml
  concepts/whats-new-overview.md
Labels: internal

#13361 Azure AD Reporting quarterly updates Q4 FY2021
  api-reference/beta/api/signin-get.md
  api-reference/beta/api/signin-list.md
  api-reference/beta/resources/appliedconditionalaccesspolicy.md
  api-reference/beta/resources/authenticationrequirementpolicy.md
  api-reference/beta/resources/conditionalaccessrulesatisfied.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/privatelinkdetails.md
  api-reference/beta/resources/signin.md
  changelog/Microsoft.AAD.Reporting.json
Labels: area: azure/AAD, ready to merge, internal, content review complete, schema live

#15363 Update shift-delete.md
  api-reference/v1.0/api/shift-delete.md
Labels: external

#12457 Committing small Azure AD sign in changes from Q3
  api-reference/beta/api/applicationsignindetailedsummary-get.md
  api-reference/beta/api/reportroot-getazureadapplicationsigninsummary.md
  api-reference/beta/api/reportroot-list-applicationsignindetailedsummary.md
  api-reference/beta/resources/applicationsignindetailedsummary.md
  api-reference/beta/resources/applicationsigninsummary.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/reportroot.md
  api-reference/beta/resources/usercredentialusagedetails.md
  api-reference/beta/toc.yml
  changelog/Microsoft.AAD.Reporting.json
  redirects/.openpublishing.redirection.1221.json
Labels: area: azure/AAD, external, ready to merge, content review complete, schema live

#15364 Update shift-delete.md
  api-reference/beta/api/shift-delete.md
Labels: external

#15365 Specify locale id for org branding is a combo of ISO 639-1 + 3166
  api-reference/beta/api/organizationalbranding-post-localizations.md
  api-reference/beta/resources/organizationalbranding.md
  api-reference/beta/resources/organizationalbrandinglocalization.md
  api-reference/beta/resources/organizationalbrandingproperties.md
  api-reference/v1.0/api/organizationalbranding-post-localizations.md
  api-reference/v1.0/resources/organizationalbranding.md
  api-reference/v1.0/resources/organizationalbrandinglocalization.md
  api-reference/v1.0/resources/organizationalbrandingproperties.md
Labels: area: azure/AAD, ready to merge, internal

#15366 Daily publishing Dec 29th 2021
  api-reference/beta/api/applicationsignindetailedsummary-get.md
  api-reference/beta/api/organizationalbranding-post-localizations.md
  api-reference/beta/api/reportroot-getazureadapplicationsigninsummary.md
  api-reference/beta/api/reportroot-list-applicationsignindetailedsummary.md
  api-reference/beta/api/shift-delete.md
  api-reference/beta/api/signin-get.md
  api-reference/beta/api/signin-list.md
  api-reference/beta/resources/applicationsignindetailedsummary.md
  api-reference/beta/resources/applicationsigninsummary.md
  api-reference/beta/resources/appliedconditionalaccesspolicy.md
  api-reference/beta/resources/authenticationrequirementpolicy.md
  api-reference/beta/resources/conditionalaccessrulesatisfied.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/organizationalbranding.md
  api-reference/beta/resources/organizationalbrandinglocalization.md
  api-reference/beta/resources/organizationalbrandingproperties.md
  api-reference/beta/resources/privatelinkdetails.md
  api-reference/beta/resources/reportroot.md
  api-reference/beta/resources/signin.md
  api-reference/beta/resources/usercredentialusagedetails.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/organizationalbranding-post-localizations.md
  api-reference/v1.0/api/shift-delete.md
  api-reference/v1.0/resources/organizationalbranding.md
  api-reference/v1.0/resources/organizationalbrandinglocalization.md
  api-reference/v1.0/resources/organizationalbrandingproperties.md
  changelog/Microsoft.AAD.Reporting.json
  redirects/.openpublishing.redirection.1221.json
Labels: internal

#15368 Fix changelog date
  changelog/Microsoft.AAD.Reporting.json
Labels: area: azure/AAD, area: reports, ready to merge

#15370 Fixing a date
  changelog/Microsoft.AAD.Reporting.json
Labels: internal

#15372 Minor doc fixes
  api-reference/beta/api/user-post-users.md
  api-reference/beta/api/user-update.md
  api-reference/beta/resources/user.md
  api-reference/v1.0/api/user-post-users.md
  api-reference/v1.0/api/user-update.md
  api-reference/v1.0/resources/user.md
Labels: area: azure/AAD, ready to merge, internal
