Repository microsoftgraph/microsoft-graph-docs, pull requests merged in 2021-06, with the labels that each got.

#12949 Transform URL text to links
  concepts/use-the-api.md
Labels: external

#12942 Update educationsubmission-return.md
  api-reference/beta/api/educationsubmission-return.md
Labels: external

#12871 Remove known issue for Windows updates API
  concepts/known-issues.md
Labels: internal, schema live

#12955 Update chatmessage.md
  api-reference/v1.0/resources/chatmessage.md
Labels: external

#12954 Update team.md
  api-reference/v1.0/resources/team.md
Labels: external

#12729 Scopes for Connect-MgGraph missing ".All"
  concepts/insights-customize-item-insights-privacy.md
Labels: internal, ready to merge

#12936 Connectors quickstart docs updates
  .openpublishing.publish.config.json
  concepts/connecting-external-content-build-quickstart-01-intro.md
  concepts/connecting-external-content-build-quickstart-03-build-app.md
  concepts/connecting-external-content-build-quickstart-04-configure-app.md
  concepts/connecting-external-content-build-quickstart-06-run-app.md
Labels: do not merge, internal

#12956 Merge to publish.
  .openpublishing.publish.config.json
  api-reference/beta/api/educationsubmission-return.md
  api-reference/v1.0/api/emailauthenticationmethodconfiguration-get.md
  api-reference/v1.0/resources/chatmessage.md
  api-reference/v1.0/resources/team.md
  concepts/connecting-external-content-build-quickstart-01-intro.md
  concepts/connecting-external-content-build-quickstart-03-build-app.md
  concepts/connecting-external-content-build-quickstart-04-configure-app.md
  concepts/connecting-external-content-build-quickstart-06-run-app.md
  concepts/insights-customize-item-insights-privacy.md
  concepts/known-issues.md
  concepts/use-the-api.md
Labels: internal

#12957 Fixed broken link
  api-reference/v1.0/api/onlinemeeting-createorget.md
Labels: internal, ready to merge

#12977 Update educationroot-list-schools.md
  api-reference/beta/api/educationroot-list-schools.md
Labels: external

#12974 Fix truncation note
  api-reference/beta/api/adminconsentrequestpolicy-get.md
  api-reference/beta/api/appconsentrequest-filterByCurrentUser.md
  api-reference/beta/api/appconsentrequest-get.md
  api-reference/beta/api/appconsentrequest-list.md
  api-reference/beta/api/userconsentrequest-filterByCurrentUser.md
  api-reference/beta/api/userconsentrequest-get.md
  api-reference/beta/api/userconsentrequest-list.md
Labels: area: azure/AAD, internal, ready to merge

#12978 Update chatmessage.md
  api-reference/beta/resources/chatmessage.md
Labels: external

#12959 Various fixes to access reviews
  api-reference/beta/api/accessreview-addreviewer.md
  api-reference/beta/api/accessreview-create.md
  api-reference/beta/api/accessreview-listdecisions.md
  api-reference/beta/api/accessreview-listmydecisions.md
  api-reference/beta/api/accessreview-listreviewers.md
  api-reference/beta/api/accessreview-removereviewer.md
  api-reference/beta/api/accessreview-reset.md
  api-reference/beta/api/accessreview-sendreminder.md
  api-reference/beta/api/accessreview-stop.md
  api-reference/beta/api/accessreview-update.md
  api-reference/beta/resources/accessreviewrecurrencesettings.md
  api-reference/beta/resources/businessflowtemplate.md
  api-reference/beta/resources/useridentity.md
  concepts/accessreviews-reviewers-concept.md
  concepts/accessreviews-scope-concept.md
  concepts/tutorial-accessreviews-M365group.md
  concepts/tutorial-accessreviews-securitygroup.md
Labels: area: azure/AAD, internal, ready to merge

#12891 Update URI in taughtClasses example
  api-reference/v1.0/api/educationuser-list-taughtclasses.md
Labels: area: edu, internal, ready to merge

#12915 Add Graph Data Connect card to hub
  concepts/index.yml
Labels: internal, ready to merge

#12961 Surface invalidateAllRefreshTokens action on users
  api-reference/beta/resources/user.md
  api-reference/beta/toc.yml
Labels: area: azure/AAD, area: users, internal, ready to merge

#12894 added allowAttendeeToEnableMic and allowAttendeeToEnableCamera
  api-reference/beta/resources/onlinemeeting.md
  changelog/Microsoft.Skype.Calling.json
Labels: internal, ready to merge

#12943 Remove documentation and pointer for assignment resource patch, now t…
  api-reference/beta/api/educationassignmentresource-update.md
  api-reference/beta/resources/educationassignmentresource.md
  api-reference/beta/toc.yml
  changelog/Microsoft.EducationAssignment.json
Labels: internal, ready to merge

#12988 Revert "added allowAttendeeToEnableMic and allowAttendeeToEnableCamera"
  api-reference/beta/resources/onlinemeeting.md
  changelog/Microsoft.Skype.Calling.json
Labels: internal

#12996 Update educationsubmission-get.md
  api-reference/beta/api/educationsubmission-get.md
Labels: external

#12994 fix: removed extra slash from example url
  api-reference/v1.0/api/team-get-members.md
Labels: external

#12983 Correct example, fixes #12821
  api-reference/beta/api/accessreviewscheduledefinition-post.md
Labels: area: azure/AAD, internal, ready to merge

#12857 Documents scopes in Microsoft Graph Toolkit components
  concepts/toolkit/components/agenda.md
  concepts/toolkit/components/file-list.md
  concepts/toolkit/components/get.md
  concepts/toolkit/components/login.md
  concepts/toolkit/components/people-picker.md
  concepts/toolkit/components/people.md
  concepts/toolkit/components/person-card.md
  concepts/toolkit/components/person.md
  concepts/toolkit/components/tasks.md
  concepts/toolkit/components/todo.md
Labels: internal, ready to merge

#12982 Add note on OIDC scopes
  concepts/auth-v2-service.md
  concepts/auth-v2-user.md
Labels: area: authentication, area: azure/AAD, internal, ready to merge

#12794 Added Calendar support for assignment and defaults
  api-reference/beta/api/educationassignment-get.md
  api-reference/beta/api/educationassignment-update.md
  api-reference/beta/api/educationassignmentdefaults-get.md
  api-reference/beta/api/educationassignmentdefaults-update.md
  api-reference/beta/resources/educationassignment.md
  api-reference/beta/resources/educationassignmentdefaults.md
  api-reference/beta/resources/enums.md
  changelog/Microsoft.EducationAssignment.json
  concepts/whats-new-overview.md
Labels: internal, ready to merge

#12870 added External groups doc
  concepts/connecting-external-content-external-groups.md
  concepts/images/connectors-images/bu-teams-D365.png
  concepts/images/connectors-images/roles-salesforce.png
  concepts/toc.yml
Labels: Build21, internal, ready to merge

#12887 Fixed permissions for hybrid identity services APIs
  api-reference/beta/api/onpremisesagent-delete-agentgroups.md
  api-reference/beta/api/onpremisesagent-get.md
  api-reference/beta/api/onpremisesagent-list.md
  api-reference/beta/api/onpremisesagent-post-agentgroups.md
  api-reference/beta/api/onpremisesagentgroup-delete.md
  api-reference/beta/api/onpremisesagentgroup-get.md
  api-reference/beta/api/onpremisesagentgroup-list.md
  api-reference/beta/api/onpremisesagentgroup-post.md
  api-reference/beta/api/onpremisesagentgroup-update.md
  api-reference/beta/api/onpremisespublishingprofile-get.md
  api-reference/beta/api/onpremisespublishingprofile-update.md
Labels: area: azure/AAD

#12791 Updating reporting endpoints
  api-reference/beta/api/printusagebyprinter-get.md
  api-reference/beta/api/printusagebyuser-get.md
  api-reference/beta/api/reportroot-list-dailyprintusagebyprinter.md
  api-reference/beta/api/reportroot-list-dailyprintusagebyuser.md
  api-reference/beta/api/reportroot-list-monthlyprintusagebyprinter.md
  api-reference/beta/api/reportroot-list-monthlyprintusagebyuser.md
  api-reference/beta/api/reports-getgrouparchivedprintjobs.md
  api-reference/beta/api/reports-getprinterarchivedprintjobs.md
  api-reference/beta/api/reports-getuserarchivedprintjobs.md
  api-reference/beta/resources/printusagebyprinter.md
  api-reference/beta/resources/printusagebyuser.md
  api-reference/beta/toc.yml
  changelog/Microsoft.PrintService.json
Labels: area: universal print, internal, ready to merge

#12998 Merge to publish.
  api-reference/beta/api/accessreviewscheduledefinition-post.md
  api-reference/beta/api/educationassignment-get.md
  api-reference/beta/api/educationassignment-update.md
  api-reference/beta/api/educationassignmentdefaults-get.md
  api-reference/beta/api/educationassignmentdefaults-update.md
  api-reference/beta/api/educationsubmission-get.md
  api-reference/beta/api/onpremisesagent-delete-agentgroups.md
  api-reference/beta/api/onpremisesagent-get.md
  api-reference/beta/api/onpremisesagent-list.md
  api-reference/beta/api/onpremisesagent-post-agentgroups.md
  api-reference/beta/api/onpremisesagentgroup-delete.md
  api-reference/beta/api/onpremisesagentgroup-get.md
  api-reference/beta/api/onpremisesagentgroup-list.md
  api-reference/beta/api/onpremisesagentgroup-post.md
  api-reference/beta/api/onpremisesagentgroup-update.md
  api-reference/beta/api/onpremisespublishingprofile-get.md
  api-reference/beta/api/onpremisespublishingprofile-update.md
  api-reference/beta/api/printusagebyprinter-get.md
  api-reference/beta/api/printusagebyuser-get.md
  api-reference/beta/api/reportroot-list-dailyprintusagebyprinter.md
  api-reference/beta/api/reportroot-list-dailyprintusagebyuser.md
  api-reference/beta/api/reportroot-list-monthlyprintusagebyprinter.md
  api-reference/beta/api/reportroot-list-monthlyprintusagebyuser.md
  api-reference/beta/api/reports-getgrouparchivedprintjobs.md
  api-reference/beta/api/reports-getprinterarchivedprintjobs.md
  api-reference/beta/api/reports-getuserarchivedprintjobs.md
  api-reference/beta/resources/educationassignment.md
  api-reference/beta/resources/educationassignmentdefaults.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/onlinemeeting.md
  api-reference/beta/resources/printusagebyprinter.md
  api-reference/beta/resources/printusagebyuser.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/team-get-members.md
  changelog/Microsoft.EducationAssignment.json
  changelog/Microsoft.PrintService.json
  changelog/Microsoft.Skype.Calling.json
  concepts/auth-v2-service.md
  concepts/auth-v2-user.md
  concepts/connecting-external-content-external-groups.md
  concepts/images/connectors-images/bu-teams-D365.png
  concepts/images/connectors-images/roles-salesforce.png
  concepts/toc.yml
  concepts/toolkit/components/agenda.md
  concepts/toolkit/components/file-list.md
  concepts/toolkit/components/get.md
  concepts/toolkit/components/login.md
  concepts/toolkit/components/people-picker.md
  concepts/toolkit/components/people.md
  concepts/toolkit/components/person-card.md
  concepts/toolkit/components/person.md
  concepts/toolkit/components/tasks.md
  concepts/toolkit/components/todo.md
  concepts/whats-new-overview.md
Labels: internal

#12641 Timecard API and Timeoff WFI changes
  api-reference/beta/api/team-put-schedule.md
  api-reference/beta/api/timecard-clockin.md
  api-reference/beta/api/timecard-clockout.md
  api-reference/beta/api/timecard-confirm.md
  api-reference/beta/api/timecard-delete.md
  api-reference/beta/api/timecard-endbreak.md
  api-reference/beta/api/timecard-get.md
  api-reference/beta/api/timecard-list.md
  api-reference/beta/api/timecard-post.md
  api-reference/beta/api/timecard-replace.md
  api-reference/beta/api/timecard-startbreak.md
  api-reference/beta/api/timeoff-delete.md
  api-reference/beta/api/timeoff-get.md
  api-reference/beta/api/timeoff-put.md
  api-reference/beta/api/timeoffreason-delete.md
  api-reference/beta/api/timeoffreason-get.md
  api-reference/beta/api/timeoffreason-put.md
  api-reference/beta/api/workforceintegration-update.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/timecard.md
  api-reference/beta/resources/timecardbreak.md
  api-reference/beta/resources/timecardentry.md
  api-reference/beta/resources/timecardevent.md
  api-reference/beta/resources/timeclocksettings.md
  api-reference/beta/resources/timeoff.md
  api-reference/beta/resources/timeoffitem.md
  api-reference/beta/resources/timeoffreason.md
  api-reference/beta/resources/timeoffrequest.md
  api-reference/beta/resources/workforceintegration.md
  api-reference/beta/toc.yml
  api-reference/v1.0/resources/enums.md
  changelog/Microsoft.Teams.Shifts.json
Labels: Build21, internal, ready to merge, schema live

#12992 Update chatmessage.md
  api-reference/v1.0/resources/chatmessage.md
Labels: external

#13005 Request code snippet generation
  api-reference/beta/api/accessreviewscheduledefinition-list.md
  api-reference/beta/resources/accessreviewinstancedecisionitemresource.md
  concepts/accessreviews-overview.md
  concepts/tutorial-accessreviews-M365group.md
  concepts/tutorial-accessreviews-securitygroup.md
Labels: area: azure/AAD, internal, ready to merge

#13011 Update educationsubmission-unsubmit.md
  api-reference/beta/api/educationsubmission-unsubmit.md
Labels: external

#13023 Update teamworknotificationrecipient.md
  api-reference/beta/resources/teamworknotificationrecipient.md
Labels: external

#13022 Update aadusernotificationrecipient.md
  api-reference/beta/resources/aadusernotificationrecipient.md
Labels: external

#12931 Update tab naming inconsistencies
  concepts/toolkit/get-started/build-a-microsoft-teams-tab.md
  concepts/toolkit/get-started/use-toolkit-with-angular.md
  concepts/toolkit/get-started/use-toolkit-with-react.md
Labels: internal, ready to merge

#12449 Add actions to provision an email for a Teams channel
  api-reference/beta/api/channel-provisionemail.md
  api-reference/beta/api/channel-removeemail.md
  api-reference/beta/resources/channel.md
  api-reference/beta/resources/provisionchannelemailresult.md
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
  changelog/Microsoft.Teams.GraphSvc.json
Labels: content review complete, internal, ready to merge, schema live

#12678 Adding disabledByMicrosoftStatus property for App and SP resources
  api-reference/beta/api/application-get.md
  api-reference/beta/api/serviceprincipal-get.md
  api-reference/beta/resources/application.md
  api-reference/beta/resources/serviceprincipal.md
  api-reference/v1.0/api/application-get.md
  api-reference/v1.0/api/serviceprincipal-get.md
  api-reference/v1.0/resources/application.md
  api-reference/v1.0/resources/serviceprincipal.md
  changelog/Microsoft.DirectoryServices.json
Labels: internal, ready to merge

#13017 Update worksheetprotection-unprotect.md
  api-reference/beta/api/worksheetprotection-unprotect.md
  api-reference/v1.0/api/worksheetprotection-unprotect.md
Labels: area: excel, internal, ready to merge

#13024 Merge to publish.
  api-reference/beta/api/application-get.md
  api-reference/beta/api/channel-provisionemail.md
  api-reference/beta/api/channel-removeemail.md
  api-reference/beta/api/serviceprincipal-get.md
  api-reference/beta/api/worksheetprotection-unprotect.md
  api-reference/beta/resources/aadusernotificationrecipient.md
  api-reference/beta/resources/application.md
  api-reference/beta/resources/channel.md
  api-reference/beta/resources/provisionchannelemailresult.md
  api-reference/beta/resources/serviceprincipal.md
  api-reference/beta/resources/teamworknotificationrecipient.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/application-get.md
  api-reference/v1.0/api/serviceprincipal-get.md
  api-reference/v1.0/api/worksheetprotection-unprotect.md
  api-reference/v1.0/resources/application.md
  api-reference/v1.0/resources/serviceprincipal.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.DirectoryServices.json
  changelog/Microsoft.Teams.GraphSvc.json
  concepts/toolkit/get-started/build-a-microsoft-teams-tab.md
  concepts/toolkit/get-started/use-toolkit-with-angular.md
  concepts/toolkit/get-started/use-toolkit-with-react.md
Labels: do not merge, internal

#13038 Update channel-get-members.md
  api-reference/beta/api/channel-get-members.md
Labels: external

#13034 Update channel-get-members.md
  api-reference/v1.0/api/channel-get-members.md
Labels: external

#13026 Cleanup directoryRole examples
  api-reference/beta/api/directoryrole-delete-member.md
  api-reference/beta/api/directoryrole-get.md
  api-reference/beta/api/directoryrole-list-members.md
  api-reference/beta/api/directoryrole-list.md
  api-reference/beta/api/directoryrole-post-directoryroles.md
  api-reference/beta/api/directoryrole-post-members.md
  api-reference/v1.0/api/directoryrole-delete-member.md
  api-reference/v1.0/api/directoryrole-get.md
  api-reference/v1.0/api/directoryrole-list-members.md
  api-reference/v1.0/api/directoryrole-list.md
  api-reference/v1.0/api/directoryrole-post-directoryroles.md
  api-reference/v1.0/api/directoryrole-post-members.md
Labels: internal, ready to merge

#13013 Update identityprotectionroot.md
  api-reference/v1.0/resources/identityprotectionroot.md
Labels: external

#13040 Merge to publish.
  api-reference/beta/api/channel-get-members.md
  api-reference/beta/api/directoryrole-delete-member.md
  api-reference/beta/api/directoryrole-get.md
  api-reference/beta/api/directoryrole-list-members.md
  api-reference/beta/api/directoryrole-list.md
  api-reference/beta/api/directoryrole-post-directoryroles.md
  api-reference/beta/api/directoryrole-post-members.md
  api-reference/v1.0/api/channel-get-members.md
  api-reference/v1.0/api/directoryrole-delete-member.md
  api-reference/v1.0/api/directoryrole-get.md
  api-reference/v1.0/api/directoryrole-list-members.md
  api-reference/v1.0/api/directoryrole-list.md
  api-reference/v1.0/api/directoryrole-post-directoryroles.md
  api-reference/v1.0/api/directoryrole-post-members.md
  api-reference/v1.0/resources/identityprotectionroot.md
Labels: internal

#12455 Add warning enum to CloudPCOnPremisesConnectionStatus
  api-reference/beta/resources/cloudpconpremisesconnection.md
  api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: content review complete, internal, ready to merge, schema live

#13058 Update workbook.md
  api-reference/beta/resources/workbook.md
Labels: external

#13057 Update persondatasource.md
  api-reference/beta/resources/persondatasource.md
Labels: external

#13042 Fix typo in identity-access-management-concept-overview.md
  concepts/azuread-identity-access-management-concept-overview.md
Labels: external

#12812 access package assignment removal
  api-reference/beta/api/accesspackage-delete.md
  api-reference/beta/api/accesspackageassignmentrequest-post.md
Labels: area: azure/AAD, internal, ready to merge

#13079 Update chat-sendactivitynotification.md
  api-reference/v1.0/api/chat-sendactivitynotification.md
Labels: external

#13077 [Teams] Add chat deep link
  api-reference/beta/api/chat-get.md
  api-reference/beta/api/chat-list.md
  api-reference/beta/api/chat-patch.md
  api-reference/beta/api/chat-post.md
  api-reference/beta/resources/chat.md
  changelog/Microsoft.Teams.Core.json
Labels: internal, ready to merge

#13071 Minor fixes to data & methods article
  concepts/traverse-the-graph.md
Labels: internal, ready to merge

#12695 Add accessReviewNotificationRecipient
  api-reference/beta/api/accessreviewscheduledefinition-post.md
  api-reference/beta/resources/accessReviewnotificationrecipientqueryscope.md
  api-reference/beta/resources/accessreviewnotificationrecipientitem.md
  api-reference/beta/resources/accessreviewnotificationrecipientscope.md
  api-reference/beta/resources/accessreviewscheduledefinition.md
  changelog/Microsoft.IdentityGovernance.AccessReviews.json
Labels: area: azure/AAD, content review complete, ready to merge

#13064 Adding back #12894
  api-reference/beta/api/application-post-onlinemeetings.md
  api-reference/beta/api/onlinemeeting-createorget.md
  api-reference/beta/api/onlinemeeting-delete.md
  api-reference/beta/api/onlinemeeting-get.md
  api-reference/beta/api/onlinemeeting-update.md
  api-reference/beta/resources/attendanceInterval.md
  api-reference/beta/resources/attendanceRecord.md
  api-reference/beta/resources/audioconferencing.md
  api-reference/beta/resources/broadcastmeetingsettings.md
  api-reference/beta/resources/lobbyBypassSettings.md
  api-reference/beta/resources/meetingAttendanceReport.md
  api-reference/beta/resources/meetingparticipants.md
  api-reference/beta/resources/onlinemeeting.md
  api-reference/beta/resources/outofofficesettings.md
  api-reference/v1.0/api/application-post-onlinemeetings.md
  api-reference/v1.0/api/cloudcommunications-getpresencesbyuserid.md
  api-reference/v1.0/api/onlinemeeting-createorget.md
  api-reference/v1.0/api/onlinemeeting-delete.md
  api-reference/v1.0/api/onlinemeeting-get.md
  api-reference/v1.0/api/onlinemeeting-update.md
  api-reference/v1.0/api/presence-get.md
  api-reference/v1.0/resources/lobbyBypassSettings.md
  api-reference/v1.0/resources/onlinemeeting.md
  api-reference/v1.0/resources/presence.md
  changelog/Microsoft.Skype.Calling.json
  concepts/cloud-communication-online-meeting-application-access-policy.md
Labels: internal, ready to merge

#12932 Azure AD entitlement management: update connected organization description
  api-reference/beta/api/connectedorganization-list.md
  api-reference/beta/api/connectedorganization-post.md
  api-reference/beta/resources/azureactivedirectorytenant.md
  api-reference/beta/resources/domainidentitysource.md
Labels: area: azure/AAD, content review complete, internal, ready to merge

#12863 Removed old schema in favor of new tri-state schema
  api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/microsoftauthenticatorauthenticationmethodtarget.md
  changelog/Microsoft.DirectoryServices.json
Labels: internal, ready to merge

#13044 Add an internal server related error type
  api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: internal, ready to merge

#13086 Merge to publish.
  api-reference/beta/api/accessreviewscheduledefinition-post.md
  api-reference/beta/api/application-post-onlinemeetings.md
  api-reference/beta/api/chat-get.md
  api-reference/beta/api/chat-list.md
  api-reference/beta/api/chat-patch.md
  api-reference/beta/api/chat-post.md
  api-reference/beta/api/connectedorganization-list.md
  api-reference/beta/api/connectedorganization-post.md
  api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md
  api-reference/beta/api/onlinemeeting-createorget.md
  api-reference/beta/api/onlinemeeting-delete.md
  api-reference/beta/api/onlinemeeting-get.md
  api-reference/beta/api/onlinemeeting-update.md
  api-reference/beta/resources/accessReviewnotificationrecipientqueryscope.md
  api-reference/beta/resources/accessreviewnotificationrecipientitem.md
  api-reference/beta/resources/accessreviewnotificationrecipientscope.md
  api-reference/beta/resources/accessreviewscheduledefinition.md
  api-reference/beta/resources/attendanceInterval.md
  api-reference/beta/resources/attendanceRecord.md
  api-reference/beta/resources/audioconferencing.md
  api-reference/beta/resources/azureactivedirectorytenant.md
  api-reference/beta/resources/broadcastmeetingsettings.md
  api-reference/beta/resources/chat.md
  api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
  api-reference/beta/resources/domainidentitysource.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/lobbyBypassSettings.md
  api-reference/beta/resources/meetingAttendanceReport.md
  api-reference/beta/resources/meetingparticipants.md
  api-reference/beta/resources/microsoftauthenticatorauthenticationmethodtarget.md
  api-reference/beta/resources/onlinemeeting.md
  api-reference/beta/resources/outofofficesettings.md
  api-reference/v1.0/api/application-post-onlinemeetings.md
  api-reference/v1.0/api/chat-sendactivitynotification.md
  api-reference/v1.0/api/cloudcommunications-getpresencesbyuserid.md
  api-reference/v1.0/api/onlinemeeting-createorget.md
  api-reference/v1.0/api/onlinemeeting-delete.md
  api-reference/v1.0/api/onlinemeeting-get.md
  api-reference/v1.0/api/onlinemeeting-update.md
  api-reference/v1.0/api/presence-get.md
  api-reference/v1.0/resources/lobbyBypassSettings.md
  api-reference/v1.0/resources/onlinemeeting.md
  api-reference/v1.0/resources/presence.md
  api-reference/v1.0/resources/workbook.md
  changelog/Microsoft.CloudManagedDesktop.json
  changelog/Microsoft.DirectoryServices.json
  changelog/Microsoft.IdentityGovernance.AccessReviews.json
  changelog/Microsoft.Skype.Calling.json
  changelog/Microsoft.Teams.Core.json
  concepts/cloud-communication-online-meeting-application-access-policy.md
  concepts/traverse-the-graph.md
Labels: internal

#13090 Minor fix to onPremisesExtensionAttributes
  api-reference/beta/api/user-update.md
  api-reference/beta/resources/onpremisesextensionattributes.md
  api-reference/v1.0/api/user-update.md
  api-reference/v1.0/resources/onpremisesextensionattributes.md
Labels: internal, ready to merge

#13093 Fix #12999 - clarify forceChangePasswordNextSignIn for B2C
  api-reference/beta/api/user-post-users.md
  api-reference/beta/resources/passwordprofile.md
  api-reference/v1.0/api/user-post-users.md
  api-reference/v1.0/resources/passwordprofile.md
Labels: internal, ready to merge

#13078 Document query parameter support on User properties
  api-reference/beta/resources/user.md
  api-reference/v1.0/resources/user.md
Labels: do not merge, internal, ready to merge

#13030 Rename unknownfuturevalue to unknownFutureValue for search API
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/search-api-overview.md
Labels: internal, ready to merge

#12779 Graph client proxy configuration
  concepts/sdks/customize-client.md
Labels: internal, ready to merge

#13036 Adding security webhooks docs
  api-reference/beta/api/subscription-post-subscriptions.md
  api-reference/v1.0/api/subscription-post-subscriptions.md
Labels: internal, ready to merge

#13035 Remove SharePoint/ODB limitation for drive item delta on subfolders.
  api-reference/beta/api/driveitem-delta.md
  api-reference/v1.0/api/driveitem-delta.md
  changelog/Microsoft.FileServices.json
Labels: area: sharepoint, internal

#13033 Update the OneDrive/SharePoint maximum subscription expiration length.
  api-reference/beta/resources/subscription.md
  api-reference/v1.0/resources/subscription.md
  changelog/Microsoft.FileServices.json
Labels: area: onedrive, area: sharepoint, do not merge, internal

#13116 update custom client for .net with proxy
  concepts/sdks/customize-client.md
Labels: area: sample code, internal, ready to merge

#13112 Minor fixes to groups
  api-reference/beta/api/group-post-groups.md
  api-reference/beta/resources/group.md
  api-reference/v1.0/api/group-post-groups.md
Labels: internal, ready to merge

#13107 Updated the subscription expiry from 3 to 29 days
  api-reference/beta/resources/subscription.md
  api-reference/v1.0/resources/subscription.md
Labels: internal, ready to merge

#13094 TOC - Devices and apps should not be expanded by default
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
Labels: bug: documentation, internal, ready to merge

#12469 Added the docs to show how to detect a user's login state in vanilla JS.
  concepts/toolkit/get-started/build-a-web-app.md
Labels: area: toolkit, content review complete, external, ready to merge

#12740 change notification for team and channels crud
  api-reference/beta/api/subscription-delete.md
  api-reference/beta/api/subscription-get.md
  api-reference/beta/api/subscription-post-subscriptions.md
  api-reference/beta/api/subscription-update.md
  api-reference/beta/resources/subscription.md
  api-reference/beta/resources/webhooks.md
  changelog/Microsoft.Teams.Core.json
  concepts/change-notification-in-Microsoft-Teams-overview.md
  concepts/teams-changenotifications-chatmessage.md
  concepts/teams-changenotifications-team-and-channel.md
  concepts/teams-changenotifications-teamMembership.md
  concepts/toc.yml
  concepts/webhooks.md
Labels: content review complete, internal, ready to merge, schema live

#12979 removing get and list members from protected API list
  api-reference/v1.0/api/conversationmember-get.md
  api-reference/v1.0/api/conversationmember-list.md
  concepts/teams-protected-apis.md
Labels: internal, ready to merge

#10286 CreateLink Api
  api-reference/beta/api/driveitem-createlink.md
  api-reference/beta/api/listitem-createlink.md
  api-reference/beta/resources/listitem.md
  api-reference/beta/toc.yml
  changelog/Microsoft.FileServices.json
Labels: content review complete, ready to merge, schema live

#13124 Merge to publish.
  api-reference/beta/api/driveitem-createlink.md
  api-reference/beta/api/group-post-groups.md
  api-reference/beta/api/listitem-createlink.md
  api-reference/beta/api/subscription-delete.md
  api-reference/beta/api/subscription-get.md
  api-reference/beta/api/subscription-post-subscriptions.md
  api-reference/beta/api/subscription-update.md
  api-reference/beta/resources/group.md
  api-reference/beta/resources/listitem.md
  api-reference/beta/resources/subscription.md
  api-reference/beta/resources/webhooks.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/conversationmember-get.md
  api-reference/v1.0/api/conversationmember-list.md
  api-reference/v1.0/api/group-post-groups.md
  api-reference/v1.0/resources/subscription.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.FileServices.json
  changelog/Microsoft.Teams.Core.json
  concepts/change-notification-in-Microsoft-Teams-overview.md
  concepts/sdks/customize-client.md
  concepts/teams-changenotifications-chatmessage.md
  concepts/teams-changenotifications-team-and-channel.md
  concepts/teams-changenotifications-teamMembership.md
  concepts/teams-protected-apis.md
  concepts/toc.yml
  concepts/toolkit/get-started/build-a-web-app.md
  concepts/webhooks.md
Labels: internal

#13140 Create link
  api-reference/beta/api/driveitem-createlink.md
Labels: internal

#13144 Update educationsynchronizationerrors-get.md
  api-reference/beta/api/educationsynchronizationerrors-get.md
Labels: external

#13145 Tenantid is listed twice in user node
  api-reference/beta/api/application-post-calls.md
Labels: external

#13123 Add client init step in JS snippet
  concepts/sdks/create-client.md
Labels: area: sample code, internal, ready to merge

#13125 Adds missing reference to Agenda component. Closes #13121
  concepts/toolkit/get-started/use-toolkit-with-react.md
Labels: area: toolkit, internal, ready to merge

#13043 Update document to use $select for list channels.
  api-reference/beta/api/channel-list.md
Labels: internal, ready to merge, schema live

#13108 [Teams] Add chat rsc to permissions reference
  changelog/Microsoft.Teams.Core.json
  concepts/permissions-reference.md
Labels: internal, ready to merge

#13110 [Teams] Update Teams Graph API's with RSC permissions
  api-reference/beta/api/channel-delete-tabs.md
  api-reference/beta/api/channel-get-filesfolder.md
  api-reference/beta/api/chat-delete-installedapps.md
  api-reference/beta/api/chat-delete-members.md
  api-reference/beta/api/chat-delete-tabs.md
  api-reference/beta/api/chat-get-installedapps.md
  api-reference/beta/api/chat-get-members.md
  api-reference/beta/api/chat-get-tabs.md
  api-reference/beta/api/chat-get.md
  api-reference/beta/api/chat-list-installedapps.md
  api-reference/beta/api/chat-list-members.md
  api-reference/beta/api/chat-list-messages.md
  api-reference/beta/api/chat-list-permissiongrants.md
  api-reference/beta/api/chat-patch-tabs.md
  api-reference/beta/api/chat-patch.md
  api-reference/beta/api/chat-post-installedapps.md
  api-reference/beta/api/chat-post-members.md
  api-reference/beta/api/chat-post-tabs.md
  api-reference/beta/api/chat-teamsappinstallation-upgrade.md
  api-reference/beta/api/chatmessage-get.md
  api-reference/beta/api/chatmessage-list-hostedcontents.md
  api-reference/beta/api/chatmessagehostedcontent-get.md
  api-reference/beta/api/team-get-installedapps.md
  api-reference/beta/api/team-get-photo.md
  api-reference/v1.0/api/channel-delete-tabs.md
  api-reference/v1.0/api/chat-post-members.md
  api-reference/v1.0/api/chatmessage-get.md
  api-reference/v1.0/api/chatmessage-list-hostedcontents.md
  api-reference/v1.0/api/chatmessagehostedcontent-get.md
  api-reference/v1.0/api/team-get-installedapps.md
  changelog/Microsoft.Teams.Core.json
  concepts/permissions-reference.md
Labels: content review complete, internal, ready to merge

#13122 Update chat-list-permissiongrants.md
  api-reference/beta/api/chat-list-permissiongrants.md
Labels: external

#13147 Merge to publish.
  api-reference/beta/api/application-post-calls.md
  api-reference/beta/api/channel-delete-tabs.md
  api-reference/beta/api/channel-get-filesfolder.md
  api-reference/beta/api/channel-list.md
  api-reference/beta/api/chat-delete-installedapps.md
  api-reference/beta/api/chat-delete-members.md
  api-reference/beta/api/chat-delete-tabs.md
  api-reference/beta/api/chat-get-installedapps.md
  api-reference/beta/api/chat-get-members.md
  api-reference/beta/api/chat-get-tabs.md
  api-reference/beta/api/chat-get.md
  api-reference/beta/api/chat-list-installedapps.md
  api-reference/beta/api/chat-list-members.md
  api-reference/beta/api/chat-list-messages.md
  api-reference/beta/api/chat-list-permissiongrants.md
  api-reference/beta/api/chat-patch-tabs.md
  api-reference/beta/api/chat-patch.md
  api-reference/beta/api/chat-post-installedapps.md
  api-reference/beta/api/chat-post-members.md
  api-reference/beta/api/chat-post-tabs.md
  api-reference/beta/api/chat-teamsappinstallation-upgrade.md
  api-reference/beta/api/chatmessage-get.md
  api-reference/beta/api/chatmessage-list-hostedcontents.md
  api-reference/beta/api/chatmessagehostedcontent-get.md
  api-reference/beta/api/driveitem-createlink.md
  api-reference/beta/api/educationsynchronizationerrors-get.md
  api-reference/beta/api/team-get-installedapps.md
  api-reference/beta/api/team-get-photo.md
  api-reference/beta/resources/consentrequests-root.md
  api-reference/v1.0/api/channel-delete-tabs.md
  api-reference/v1.0/api/chat-post-members.md
  api-reference/v1.0/api/chatmessage-get.md
  api-reference/v1.0/api/chatmessage-list-hostedcontents.md
  api-reference/v1.0/api/chatmessagehostedcontent-get.md
  api-reference/v1.0/api/team-get-installedapps.md
  api-reference/v1.0/resources/consentrequests-root.md
  changelog/Microsoft.Teams.Core.json
  concepts/permissions-reference.md
  concepts/sdks/create-client.md
  concepts/toolkit/get-started/use-toolkit-with-react.md
Labels: internal

#12689 Publish teams/{team-id}/permissionGrants
  api-reference/beta/api/chat-list-permissiongrants.md
  api-reference/beta/api/team-list-permissiongrants.md
  api-reference/beta/resources/group.md
  api-reference/beta/resources/resourcespecificpermissiongrant.md
  api-reference/beta/resources/team.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Teams.Core.json
Labels: content review complete, internal, ready to merge

#13165 Remove federated chat caveat
  api-reference/includes/teams-subscription-notes.md
Labels: area: teams, internal, ready to merge

#12725 [CloudPC]Add user setting resource
  api-reference/beta/api/cloudpc-get.md
  api-reference/beta/api/cloudpcdeviceimage-get.md
  api-reference/beta/api/cloudpcusersetting-assign.md
  api-reference/beta/api/cloudpcusersetting-delete.md
  api-reference/beta/api/cloudpcusersetting-get.md
  api-reference/beta/api/cloudpcusersetting-update.md
  api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md
  api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md
  api-reference/beta/api/virtualendpoint-list-usersettings.md
  api-reference/beta/api/virtualendpoint-post-usersettings.md
  api-reference/beta/resources/cloudpcusersetting.md
  api-reference/beta/resources/cloudpcusersettingassignment.md
  api-reference/beta/resources/virtualendpoint.md
  api-reference/beta/toc.yml
  changelog/Microsoft.CloudManagedDesktop.json
Labels: content review complete, internal, ready to merge, schema live

#13150 Update owner of administrativeUnit API
  api-reference/beta/api/administrativeunit-delete-members.md
  api-reference/beta/api/administrativeunit-delete-scopedrolemembers.md
  api-reference/beta/api/administrativeunit-delete.md
  api-reference/beta/api/administrativeunit-delta.md
  api-reference/beta/api/administrativeunit-get-members.md
  api-reference/beta/api/administrativeunit-get-scopedrolemembers.md
  api-reference/beta/api/administrativeunit-get.md
  api-reference/beta/api/administrativeunit-list-members.md
  api-reference/beta/api/administrativeunit-list-scopedrolemembers.md
  api-reference/beta/api/administrativeunit-list.md
  api-reference/beta/api/administrativeunit-post-administrativeunits.md
  api-reference/beta/api/administrativeunit-post-members.md
  api-reference/beta/api/administrativeunit-post-scopedrolemembers.md
  api-reference/beta/api/administrativeunit-update.md
  api-reference/beta/resources/administrativeunit.md
  api-reference/v1.0/api/administrativeunit-delete-members.md
  api-reference/v1.0/api/administrativeunit-delete-scopedrolemembers.md
  api-reference/v1.0/api/administrativeunit-delete.md
  api-reference/v1.0/api/administrativeunit-get-members.md
  api-reference/v1.0/api/administrativeunit-get-scopedrolemembers.md
  api-reference/v1.0/api/administrativeunit-get.md
  api-reference/v1.0/api/administrativeunit-list-members.md
  api-reference/v1.0/api/administrativeunit-list-scopedrolemembers.md
  api-reference/v1.0/api/administrativeunit-list.md
  api-reference/v1.0/api/administrativeunit-post-administrativeunits.md
  api-reference/v1.0/api/administrativeunit-post-members.md
  api-reference/v1.0/api/administrativeunit-post-scopedrolemembers.md
  api-reference/v1.0/api/administrativeunit-update.md
  api-reference/v1.0/resources/administrativeunit.md
Labels: internal, ready to merge

#13156 Fix typo in note on Device.ReadWrite.All
  concepts/permissions-reference.md
Labels: area: azure/AAD, internal, ready to merge

#12796 Add Four Enums to CloudPcOnPremisesConnectionHealthCheckErrorType
  api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: internal, ready to merge, schema live

#13176 Minor fix to scope of principalResourceMembershipsScope
  concepts/accessreviews-scope-concept.md
Labels: internal, ready to merge

#13160 Minor doc updates
  api-reference/beta/api/user-list-memberof.md
  api-reference/beta/api/user-update.md
  api-reference/v1.0/api/user-list-memberof.md
  api-reference/v1.0/api/user-update.md
Labels: internal, ready to merge

#13164 Update education-concept-overview.md
  concepts/education-concept-overview.md
Labels: external, ready to merge

#13178 Merge to publish.
  api-reference/beta/api/user-list-memberof.md
  api-reference/beta/api/user-update.md
  api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
  api-reference/v1.0/api/user-list-memberof.md
  api-reference/v1.0/api/user-update.md
  changelog/Microsoft.CloudManagedDesktop.json
  changelog/Microsoft.Teams.Core.json
  concepts/accessreviews-scope-concept.md
  concepts/education-concept-overview.md
Labels: internal

#13182 Teams: Update permissions for webhooks
  concepts/teams-changenotifications-chatmessage.md
  concepts/teams-changenotifications-team-and-channel.md
  concepts/teams-changenotifications-teamMembership.md
Labels: internal, ready to merge

#13188 Teams: Update permission formatting.
  concepts/permissions-reference.md
Labels: internal, ready to merge

#13189 Merge to publish (OOB).
  concepts/permissions-reference.md
  concepts/teams-changenotifications-chatmessage.md
  concepts/teams-changenotifications-team-and-channel.md
  concepts/teams-changenotifications-teamMembership.md
Labels: internal

#12866 [Teams] Install app during chat creation
  api-reference/beta/api/chat-list-operations.md
  api-reference/beta/api/chat-post.md
  api-reference/beta/api/teamsasyncoperation-get.md
  api-reference/beta/resources/chat.md
  api-reference/beta/resources/resourcespecificpermissiongrant.md
  api-reference/beta/resources/teamsasyncoperation.md
  api-reference/beta/resources/teamsasyncoperationtype.md
  api-reference/beta/toc.yml
  api-reference/v1.0/resources/teamsasyncoperationtype.md
  changelog/Microsoft.Teams.Core.json
Labels: internal, ready to merge

#13181 Adds link to the MGT React code tour
  concepts/toolkit/get-started/use-toolkit-with-react.md
Labels: internal, ready to merge

#13021 Add documenation for instantiating Msal2Provider with exisiting Publi…
  concepts/toolkit/providers/msal2.md
Labels: area: toolkit, external, review requested

#13192 Fix #13183 - Add basic permission + note for limited info
  api-reference/beta/api/user-list-memberof.md
  api-reference/includes/limited-info.md
  api-reference/v1.0/api/user-list-memberof.md
Labels: internal, ready to merge

#13175 Update property descriptions for licenseUnitsDetail resource
  api-reference/beta/resources/licenseunitsdetail.md
  api-reference/beta/resources/passwordprofile.md
  api-reference/beta/resources/subscribedsku.md
  api-reference/v1.0/resources/licenseunitsdetail.md
  api-reference/v1.0/resources/passwordprofile.md
  api-reference/v1.0/resources/subscribedsku.md
Labels: area: azure/AAD, internal, ready to merge

#12832 Document advanced query capabilities on Azure AD objects
  concepts/aad-advanced-queries.md
  concepts/images/advanced-query-parameters/advanced.png
  concepts/images/advanced-query-parameters/default.png
  concepts/known-issues.md
  concepts/paging.md
  concepts/query-parameters.md
  concepts/search-query-parameter.md
  concepts/toc.yml
  concepts/whats-new-earlier.md
  includes/filter-directory-objects.md
Labels: content review complete, internal, ready to merge

#12011 [Azure AD roles] Assign roles to groups GA
  api-reference/v1.0/api/group-get.md
  api-reference/v1.0/api/group-getmemberobjects.md
  api-reference/v1.0/api/group-list.md
  api-reference/v1.0/api/group-post-groups.md
  api-reference/v1.0/resources/group.md
  changelog/Microsoft.DirectoryServices.json
Labels: area: azure/AAD, internal, ready to merge

#13186 User auth page fix
  concepts/auth-v2-user.md
Labels: ready to merge

#13213 [Teams] Replace outdated authors; Add RSC app permissions subheader to permissions reference; fix existing warnings
  api-reference/beta/api/channel-delete-members.md
  api-reference/beta/api/channel-get-members.md
  api-reference/beta/api/channel-list-members.md
  api-reference/beta/api/channel-list.md
  api-reference/beta/api/channel-patch.md
  api-reference/beta/api/channel-post-members.md
  api-reference/beta/api/channel-post.md
  api-reference/beta/api/channel-update-members.md
  api-reference/beta/api/conversationmember-update.md
  api-reference/beta/api/team-delete-installedapps.md
  api-reference/beta/api/team-get-members.md
  api-reference/beta/api/team-get-photo.md
  api-reference/beta/api/team-list-installedapps.md
  api-reference/beta/api/team-post-installedapps.md
  api-reference/beta/api/team-teamsappinstallation-upgrade.md
  api-reference/beta/api/team-update-members.md
  api-reference/beta/api/userteamwork-delete-installedapps.md
  api-reference/beta/api/userteamwork-list-installedapps.md
  api-reference/beta/api/userteamwork-post-installedapps.md
  api-reference/beta/api/userteamwork-teamsappinstallation-upgrade.md
  api-reference/beta/resources/aaduserconversationmember.md
  api-reference/beta/resources/channel.md
  api-reference/beta/resources/conversationmember.md
  api-reference/beta/resources/teamclasssettings.md
  api-reference/beta/resources/teammembersettings.md
  api-reference/beta/resources/teamwork.md
  api-reference/beta/resources/userteamwork.md
  api-reference/v1.0/api/channel-delete-members.md
  api-reference/v1.0/api/channel-get-members.md
  api-reference/v1.0/api/channel-list-members.md
  api-reference/v1.0/api/channel-post-members.md
  api-reference/v1.0/api/channel-update-members.md
  api-reference/v1.0/api/conversationmember-add.md
  api-reference/v1.0/api/conversationmember-delete.md
  api-reference/v1.0/api/conversationmember-get.md
  api-reference/v1.0/api/conversationmember-list.md
  api-reference/v1.0/api/conversationmember-update.md
  api-reference/v1.0/api/team-delete-installedapps.md
  api-reference/v1.0/api/team-get-members.md
  api-reference/v1.0/api/team-list-installedapps.md
  api-reference/v1.0/api/team-post-installedapps.md
  api-reference/v1.0/api/team-teamsappinstallation-upgrade.md
  api-reference/v1.0/api/team-update-members.md
  api-reference/v1.0/api/userteamwork-delete-installedapps.md
  api-reference/v1.0/api/userteamwork-list-installedapps.md
  api-reference/v1.0/api/userteamwork-post-installedapps.md
  api-reference/v1.0/api/userteamwork-teamsappinstallation-upgrade.md
  api-reference/v1.0/resources/aaduserconversationmember.md
  api-reference/v1.0/resources/conversationmember.md
  api-reference/v1.0/resources/teamclasssettings.md
  api-reference/v1.0/resources/userteamwork.md
  concepts/permissions-reference.md
Labels: internal, ready to merge

#13212 Update AR scope exs to use v1.0 instead of beta
  api-reference/beta/api/accessreviewscheduledefinition-list.md
  api-reference/beta/api/accessreviewscheduledefinition-post.md
  api-reference/v1.0/api/accessreviewscheduledefinition-list.md
  api-reference/v1.0/api/accessreviewscheduledefinition-post.md
  concepts/accessreviews-reviewers-concept.md
  concepts/accessreviews-scope-concept.md
Labels: area: azure/AAD, ready to merge

#13216 Update cloudcommunications-getpresencesbyuserid.md
  api-reference/beta/api/cloudcommunications-getpresencesbyuserid.md
Labels: external

#13133 Changes _crop in thumbnails docs to lowercase
  api-reference/v1.0/api/driveitem-list-thumbnails.md
Labels: internal, ready to merge

#13155 Correct required permissions for appRoleAssignedTo
  api-reference/beta/api/serviceprincipal-post-approleassignedto.md
  api-reference/v1.0/api/serviceprincipal-post-approleassignedto.md
Labels: area: azure/AAD, internal, ready to merge

#13205 Fixes typo in use-toolkit-with-react.md
  concepts/toolkit/get-started/use-toolkit-with-react.md
Labels: internal, ready to merge

#11609 [NotificationAPIGuidelines][Create][1529165]
  concepts/activity-feed-notifications-best-practices.md
  concepts/images/activity-feed-notification.png
  concepts/images/best-practices.png
  concepts/images/notification-preview.PNG
  concepts/images/notifications-api-best-practice1.PNG
  concepts/images/notifications-api-best-practice2.png
  concepts/images/notifications-api-best-practice3.PNG
  concepts/teams-send-activityfeednotifications.md
  concepts/toc.yml
Labels: internal, ready to merge

#11071 teamwork Tag changes
  api-reference/beta/api/teamworktag-delete.md
  api-reference/beta/api/teamworktag-get.md
  api-reference/beta/api/teamworktag-list.md
  api-reference/beta/api/teamworktag-post-members.md
  api-reference/beta/api/teamworktag-post.md
  api-reference/beta/api/teamworktag-update.md
  api-reference/beta/api/teamworktagmember-delete.md
  api-reference/beta/api/teamworktagmember-get.md
  api-reference/beta/api/teamworktagmember-list.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/team.md
  api-reference/beta/resources/teams-api-overview.md
  api-reference/beta/resources/teamworktag.md
  api-reference/beta/resources/teamworktagmember.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Teams.Core.json
  concepts/permissions-reference.md
Labels: Build21, content review complete, internal, ready to merge, schema live

#13221 Showcase some partner solutions.
  concepts/overview.md
Labels: internal

#13223 [Doc bug][Updated link: Localized]
  concepts/activity-feed-notifications-best-practices.md
Labels: internal, ready to merge

#13232 Updated link
  concepts/activity-feed-notifications-best-practices.md
Labels: do not merge, internal

#13241 Update delta-query-users.md
  concepts/delta-query-users.md
Labels: external

#13209 Adds documentation for handling MGT events
  concepts/toc.yml
  concepts/toolkit/components/agenda.md
  concepts/toolkit/components/file-list.md
  concepts/toolkit/components/get.md
  concepts/toolkit/components/login.md
  concepts/toolkit/components/people-picker.md
  concepts/toolkit/components/person-card.md
  concepts/toolkit/components/person.md
  concepts/toolkit/components/tasks.md
  concepts/toolkit/components/teams-channel-picker.md
  concepts/toolkit/components/todo.md
  concepts/toolkit/customize-components/events.md
Labels: internal, ready to merge

#13224 Minor fixes to subscription & changeNotification resources
  api-reference/beta/resources/changenotification.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/subscription.md
  api-reference/v1.0/resources/changenotification.md
  api-reference/v1.0/resources/enums.md
  api-reference/v1.0/resources/subscription.md
  changelog/Microsoft.DirectoryServices.json
Labels: area: azure/AAD, area: webhooks, internal, ready to merge

#12384 Update conditionalaccessdevices.md to include device filter property
  api-reference/beta/resources/conditionalaccessdevices.md
  api-reference/beta/resources/conditionalaccessfilter.md
  api-reference/beta/resources/enums.md
  changelog/Microsoft.IdentityProtectionServices.json
Labels: content review complete, internal, ready to merge, schema live

#13227 Fixes the code sample in MGT build web app walkthrough
  concepts/toolkit/get-started/build-a-web-app.md
Labels: internal

#13203 Update string values in API examples
  api-reference/beta/api/cloudpc-get.md
  api-reference/beta/api/virtualendpoint-list-cloudpcs.md
Labels: internal, schema live

#13200 [CloudPC]Fix some errors for usersetting and provisioning policy
  api-reference/beta/api/cloudpcprovisioningpolicy-assign.md
  api-reference/beta/api/cloudpcusersetting-assign.md
  api-reference/beta/resources/cloudpcmanagementassignmenttarget.md
  api-reference/beta/resources/cloudpcprovisioningpolicy.md
  api-reference/beta/resources/cloudpcprovisioningpolicyassignment.md
  api-reference/beta/resources/cloudpcusersetting.md
  api-reference/beta/resources/cloudpcusersettingassignment.md
Labels: internal, schema live

#13242 Merge to publish.
  api-reference/beta/api/cloudpc-get.md
  api-reference/beta/api/cloudpcprovisioningpolicy-assign.md
  api-reference/beta/api/cloudpcusersetting-assign.md
  api-reference/beta/api/virtualendpoint-list-cloudpcs.md
  api-reference/beta/resources/changenotification.md
  api-reference/beta/resources/cloudpcmanagementassignmenttarget.md
  api-reference/beta/resources/cloudpcprovisioningpolicy.md
  api-reference/beta/resources/cloudpcprovisioningpolicyassignment.md
  api-reference/beta/resources/cloudpcusersetting.md
  api-reference/beta/resources/cloudpcusersettingassignment.md
  api-reference/beta/resources/conditionalaccessdevices.md
  api-reference/beta/resources/conditionalaccessfilter.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/subscription.md
  api-reference/v1.0/resources/changenotification.md
  api-reference/v1.0/resources/enums.md
  api-reference/v1.0/resources/subscription.md
  changelog/Microsoft.DirectoryServices.json
  changelog/Microsoft.IdentityProtectionServices.json
  concepts/activity-feed-notifications-best-practices.md
  concepts/delta-query-users.md
  concepts/overview.md
  concepts/toc.yml
  concepts/toolkit/components/agenda.md
  concepts/toolkit/components/file-list.md
  concepts/toolkit/components/get.md
  concepts/toolkit/components/login.md
  concepts/toolkit/components/people-picker.md
  concepts/toolkit/components/person-card.md
  concepts/toolkit/components/person.md
  concepts/toolkit/components/tasks.md
  concepts/toolkit/components/teams-channel-picker.md
  concepts/toolkit/components/todo.md
  concepts/toolkit/customize-components/events.md
  concepts/toolkit/get-started/build-a-web-app.md
Labels: internal

#11518 Update usersettings.md
  api-reference/beta/api/userinsightssettings-get.md
  api-reference/beta/api/userinsightssettings-update.md
  api-reference/beta/api/usersettings-update.md
  api-reference/beta/resources/iteminsightssettings.md
  api-reference/beta/resources/userinsightssettings.md
  api-reference/beta/resources/usersettings.md
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
  changelog/Microsoft.OfficeGraph.json
  concepts/changelog.md
  concepts/images/Recent-files-in-card-based-interfaces.PNG
  concepts/images/Recommended-Office-com.PNG
  concepts/images/disabled-item-insights-in-delve.PNG
  concepts/images/disabled-item-insights-in-office.PNG
  concepts/images/disabled-item-insights-in-persona-card.PNG
  concepts/images/discover-Delve-OutlookMobile.PNG
  concepts/images/item-insights-toggle-in-MyAccount.PNG
  concepts/insights-customize-item-insights-privacy.md
  concepts/item-insights-overview.md
  concepts/social-intel-concept-overview.md
  concepts/toc.yml
Labels: do not merge, internal, schema live

#13256 Updated changelog date for PR 11518.
  changelog/Microsoft.OfficeGraph.json
Labels: internal

#12362 Adding documentation for activateService action on organization
  api-reference/beta/api/organization-activateservice.md
  api-reference/beta/resources/activateservice.md
  api-reference/beta/resources/organization.md
  api-reference/beta/toc.yml
  changelog/Microsoft.DirectoryServices.json
Labels: area: azure/AAD, ready to merge

#13119 The set presence APIs
  api-reference/beta/api/presence-clearpresence.md
  api-reference/beta/api/presence-setpresence.md
  api-reference/beta/resources/presence.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Skype.Calling.json
Labels: content review complete, internal, ready to merge, schema live

#13252 Fixing the HTTP request example
  api-reference/v1.0/api/emailauthenticationmethodconfiguration-update.md
Labels: internal, ready to merge

#13258 Update educationassignment-setupresourcesfolder.md
  api-reference/beta/api/educationassignment-setupresourcesfolder.md
Labels: external

#13257 Update webhooks.md
  api-reference/beta/resources/webhooks.md
Labels: external

#13253 Note: encoding # in UPN for Get user method
  api-reference/beta/api/user-get.md
  api-reference/v1.0/api/user-get.md
Labels: area: azure/AAD, area: users, internal, ready to merge

#13251 Clarify support of $orderBy on deletedDateTime property
  api-reference/beta/api/directory-deleteditems-list.md
  api-reference/v1.0/api/directory-deleteditems-list.md
Labels: internal, ready to merge

#13016 Update installation.md
  concepts/powershell/installation.md
Labels: external, ready to merge

#12386 isBackendCertificateValidationEnabled addition
  api-reference/beta/resources/onpremisespublishing.md
  changelog/Microsoft.DirectoryServices.json
Labels: area: azure/AAD, content review complete, ready to merge

#13263 Fixed broken link in API overview topics to a solutions page in the Microsoft Graph portal.
  api-reference/beta/resources/azure-ad-overview.md
  api-reference/beta/resources/booking-api-overview.md
  api-reference/beta/resources/mail-api-overview.md
  api-reference/beta/resources/report.md
  api-reference/beta/resources/security-api-overview.md
  api-reference/v1.0/resources/azure-ad-overview.md
  api-reference/v1.0/resources/mail-api-overview.md
  api-reference/v1.0/resources/report.md
  api-reference/v1.0/resources/security-api-overview.md
Labels: internal

#13207 Minor fixes to various docs
  api-reference/beta/api/directoryrole-delete-member.md
  api-reference/beta/api/directoryrole-delta.md
  api-reference/beta/api/directoryrole-get.md
  api-reference/beta/api/directoryrole-list-members.md
  api-reference/beta/api/directoryrole-list-scopedmembers.md
  api-reference/beta/api/directoryrole-post-members.md
  api-reference/beta/resources/directoryrole.md
  api-reference/beta/resources/user.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/directoryrole-delete-member.md
  api-reference/v1.0/api/directoryrole-delta.md
  api-reference/v1.0/api/directoryrole-get.md
  api-reference/v1.0/api/directoryrole-list-members.md
  api-reference/v1.0/api/directoryrole-list-scopedmembers.md
  api-reference/v1.0/api/directoryrole-post-members.md
  api-reference/v1.0/resources/directoryrole.md
  api-reference/v1.0/resources/user.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.DirectoryServices.json
  concepts/aad-advanced-queries.md
  concepts/query-parameters.md
Labels: internal, ready to merge

#13273 Merging latest changes in Main to Live
  api-reference/beta/api/directoryrole-delete-member.md
  api-reference/beta/api/directoryrole-delta.md
  api-reference/beta/api/directoryrole-get.md
  api-reference/beta/api/directoryrole-list-members.md
  api-reference/beta/api/directoryrole-list-scopedmembers.md
  api-reference/beta/api/directoryrole-post-members.md
  api-reference/beta/resources/azure-ad-overview.md
  api-reference/beta/resources/booking-api-overview.md
  api-reference/beta/resources/directoryrole.md
  api-reference/beta/resources/mail-api-overview.md
  api-reference/beta/resources/report.md
  api-reference/beta/resources/security-api-overview.md
  api-reference/beta/resources/user.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/directoryrole-delete-member.md
  api-reference/v1.0/api/directoryrole-delta.md
  api-reference/v1.0/api/directoryrole-get.md
  api-reference/v1.0/api/directoryrole-list-members.md
  api-reference/v1.0/api/directoryrole-list-scopedmembers.md
  api-reference/v1.0/api/directoryrole-post-members.md
  api-reference/v1.0/resources/azure-ad-overview.md
  api-reference/v1.0/resources/directoryrole.md
  api-reference/v1.0/resources/mail-api-overview.md
  api-reference/v1.0/resources/report.md
  api-reference/v1.0/resources/security-api-overview.md
  api-reference/v1.0/resources/user.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.DirectoryServices.json
  concepts/aad-advanced-queries.md
  concepts/query-parameters.md
Labels: internal

#13276 Update alerttrigger.md
  api-reference/beta/resources/alerttrigger.md
Labels: external

#13266 Fix #13139 - Member name
  api-reference/beta/resources/changenotification.md
  api-reference/v1.0/resources/changenotification.md
Labels: internal, ready to merge

#13264 Fix #12061 - Add note on effective permissions to call signIn APIs
  api-reference/beta/api/signin-get.md
  api-reference/beta/api/signin-list.md
  api-reference/v1.0/api/signin-get.md
  api-reference/v1.0/api/signin-list.md
Labels: internal, ready to merge

#13262 Fix link #11436
  api-reference/beta/resources/azure-ad-auditlog-overview.md
  api-reference/v1.0/resources/azure-ad-auditlog-overview.md
Labels: internal, ready to merge

#13277 Merge to publish.
  api-reference/beta/api/signin-get.md
  api-reference/beta/api/signin-list.md
  api-reference/beta/resources/alerttrigger.md
  api-reference/beta/resources/azure-ad-auditlog-overview.md
  api-reference/beta/resources/changenotification.md
  api-reference/v1.0/api/signin-get.md
  api-reference/v1.0/api/signin-list.md
  api-reference/v1.0/resources/alerttrigger.md
  api-reference/v1.0/resources/azure-ad-auditlog-overview.md
  api-reference/v1.0/resources/changenotification.md
Labels: internal

#13007 transitive count API
  api-reference/beta/api/orgcontact-get-transitivereports.md
  api-reference/beta/api/user-get-transitivereports.md
  api-reference/beta/resources/orgcontact.md
  api-reference/beta/resources/user.md
  changelog/Microsoft.DirectoryServices.json
Labels: area: azure/AAD, internal, ready to merge

#12099 Add new PIM permissions
  changelog/Microsoft.DirectoryServices.json
  concepts/permissions-reference.md
Labels: area: permissions, internal, ready to merge

#13286 Make one correction for our doc: permissions does not support MSA acc…
  api-reference/beta/api/serviceannouncement-list-healthoverviews.md
  api-reference/beta/api/serviceannouncement-list-issues.md
  api-reference/beta/api/serviceannouncement-list-messages.md
  api-reference/beta/api/servicehealth-get.md
  api-reference/beta/api/servicehealthissue-get.md
  api-reference/beta/api/servicehealthissue-incidentreport.md
  api-reference/beta/api/serviceupdatemessage-archive.md
  api-reference/beta/api/serviceupdatemessage-favorite.md
  api-reference/beta/api/serviceupdatemessage-get.md
  api-reference/beta/api/serviceupdatemessage-markread.md
  api-reference/beta/api/serviceupdatemessage-markunread.md
  api-reference/beta/api/serviceupdatemessage-unarchive.md
  api-reference/beta/api/serviceupdatemessage-unfavorite.md
Labels: content review complete, internal, ready to merge

#13274 Update throttling.md
  concepts/throttling.md
Labels: external

#13283 Remove incorrect statement from permissions API
  api-reference/beta/api/driveitem-list-permissions.md
  api-reference/beta/api/permission-get.md
  api-reference/v1.0/api/driveitem-list-permissions.md
  api-reference/v1.0/api/permission-get.md
Labels: internal
