Repository microsoftgraph/microsoft-graph-docs, pull requests merged in 2021-03, with the labels that each got.

#11014 Rename DeviceStates to Devices
  api-reference/beta/api/conditionalaccesspolicy-get.md
  api-reference/beta/api/conditionalaccessroot-post-policies.md
  api-reference/beta/resources/conditionalaccessdevices.md
  changelog/Microsoft.IdentityProtectionServices.json
  concepts/changelog.md
Labels: internal, ready to merge

#9775 Added documentation for content type apis
  api-reference/beta/api/contenttype-addcopy.md
  api-reference/beta/api/contenttype-associatewithhubsites.md
  api-reference/beta/api/contenttype-copytodefaultcontentlocation.md
  api-reference/beta/api/contenttype-delete-columns.md
  api-reference/beta/api/contenttype-delete.md
  api-reference/beta/api/contenttype-get-columns.md
  api-reference/beta/api/contenttype-get.md
  api-reference/beta/api/contenttype-ispublished.md
  api-reference/beta/api/contenttype-list-columns.md
  api-reference/beta/api/contenttype-list.md
  api-reference/beta/api/contenttype-post-columns.md
  api-reference/beta/api/contenttype-post.md
  api-reference/beta/api/contenttype-publish.md
  api-reference/beta/api/contenttype-unpublish.md
  api-reference/beta/api/contenttype-update-columns.md
  api-reference/beta/api/contenttype-update.md
  api-reference/beta/api/site-getapplicablecontenttypesforlist.md
  api-reference/beta/resources/columndefinition.md
  api-reference/beta/resources/columnvalidation.md
  api-reference/beta/resources/contentType.md
  api-reference/beta/resources/contentapprovalstatuscolumn.md
  api-reference/beta/resources/documentset.md
  api-reference/beta/resources/documentsetcontent.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/hyperlinkorpicturecolumn.md
  api-reference/beta/resources/site.md
  api-reference/beta/resources/termcolumn.md
  api-reference/beta/resources/thumbnailcolumn.md
  api-reference/beta/toc.yml
  changelog/Microsoft.FileServices.json
Labels: ready to merge

#10566 Add documents for participant joining related resources
  api-reference/beta/api/call-answer.md
  api-reference/beta/resources/acceptjoinresponse.md
  api-reference/beta/resources/invitenewbotresponse.md
  api-reference/beta/resources/participantjoiningnotification.md
  api-reference/beta/resources/participantjoiningresponse.md
  api-reference/beta/resources/participantleftnotification.md
  api-reference/beta/resources/rejectjoinresponse.md
  changelog/Microsoft.Skype.Calling.json
  concepts/changelog.md
Labels: internal, ready to merge

#11630 Add filter examples for app role assignments
  api-reference/beta/api/group-list-approleassignments.md
  api-reference/beta/api/group-post-approleassignments.md
  api-reference/beta/api/serviceprincipal-list-approleassignedto.md
  api-reference/beta/api/serviceprincipal-list-approleassignments.md
  api-reference/beta/api/serviceprincipal-post-approleassignedto.md
  api-reference/beta/api/serviceprincipal-post-approleassignments.md
  api-reference/beta/api/user-list-approleassignments.md
  api-reference/beta/api/user-post-approleassignments.md
  api-reference/v1.0/api/group-list-approleassignments.md
  api-reference/v1.0/api/group-post-approleassignments.md
  api-reference/v1.0/api/serviceprincipal-list-approleassignedto.md
  api-reference/v1.0/api/serviceprincipal-list-approleassignments.md
  api-reference/v1.0/api/serviceprincipal-post-approleassignedto.md
  api-reference/v1.0/api/serviceprincipal-post-approleassignments.md
  api-reference/v1.0/api/user-list-approleassignments.md
Labels: internal, ready to merge

#11771 updated intune v1 toc
  api-reference/v1.0/toc.yml
Labels: area: azure/AAD, internal, ready to merge

#11707 TeamGraph: Fix Create Team example.
  api-reference/beta/api/team-post.md
  api-reference/v1.0/api/team-post.md
Labels: internal, ready to merge

#11672 Add lastSeenDateTime property
  api-reference/beta/resources/printer.md
  changelog/Microsoft.PrintService.json
Labels: area: universal print, internal, ready to merge

#11723 Documentation: Removing reference to user/calendarGroup
  api-reference/beta/api/attachment-delete.md
  api-reference/beta/api/calendar-delete.md
  api-reference/beta/api/calendar-get.md
  api-reference/beta/api/calendar-list-calendarview.md
  api-reference/beta/api/calendar-list-events.md
  api-reference/beta/api/calendar-post-events.md
  api-reference/beta/api/calendar-update.md
  api-reference/beta/api/calendargroup-list-calendars.md
  api-reference/beta/api/calendargroup-post-calendars.md
  api-reference/beta/api/event-accept.md
  api-reference/beta/api/event-cancel.md
  api-reference/beta/api/event-decline.md
  api-reference/beta/api/event-delete.md
  api-reference/beta/api/event-delta.md
  api-reference/beta/api/event-dismissreminder.md
  api-reference/beta/api/event-forward.md
  api-reference/beta/api/event-get.md
  api-reference/beta/api/event-list-instances.md
  api-reference/beta/api/event-snoozereminder.md
  api-reference/beta/api/event-tentativelyaccept.md
  api-reference/beta/api/event-update.md
  api-reference/beta/api/organizationalbrandingproperties-get.md
  api-reference/beta/api/organizationalbrandingproperties-update.md
  api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md
  api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md
  api-reference/beta/api/publishedresource-delete-agentgroups.md
  api-reference/beta/api/user-list-calendars.md
  api-reference/beta/api/user-list-calendarview.md
  api-reference/beta/api/user-list-events.md
  api-reference/v1.0/api/attachment-delete.md
  api-reference/v1.0/api/attachment-get.md
  api-reference/v1.0/api/calendar-delete.md
  api-reference/v1.0/api/calendar-get.md
  api-reference/v1.0/api/calendar-list-calendarview.md
  api-reference/v1.0/api/calendar-list-events.md
  api-reference/v1.0/api/calendar-post-events.md
  api-reference/v1.0/api/calendar-update.md
  api-reference/v1.0/api/calendargroup-list-calendars.md
  api-reference/v1.0/api/calendargroup-post-calendars.md
  api-reference/v1.0/api/event-accept.md
  api-reference/v1.0/api/event-cancel.md
  api-reference/v1.0/api/event-decline.md
  api-reference/v1.0/api/event-delete.md
  api-reference/v1.0/api/event-dismissreminder.md
  api-reference/v1.0/api/event-forward.md
  api-reference/v1.0/api/event-get.md
  api-reference/v1.0/api/event-list-attachments.md
  api-reference/v1.0/api/event-list-instances.md
  api-reference/v1.0/api/event-post-attachments.md
  api-reference/v1.0/api/event-snoozereminder.md
  api-reference/v1.0/api/event-tentativelyaccept.md
  api-reference/v1.0/api/event-update.md
  api-reference/v1.0/api/user-list-calendars.md
  api-reference/v1.0/api/user-list-calendarview.md
  api-reference/v1.0/api/user-list-events.md
Labels: internal, ready to merge

#11697 Update dynamics-create-vendor.md
  api-reference/beta/api/dynamics-create-vendor.md
Labels: external

#11719 Update dynamics-vendor-get.md
  api-reference/beta/api/dynamics-vendor-get.md
Labels: external

#11736 Update booking-concept-overview.md
  concepts/booking-concept-overview.md
Labels: external

#11803 Update sitepage.md
  api-reference/beta/resources/sitepage.md
Labels: external

#11716 Yiwen microsoft graph docs
  api-reference/beta/resources/searchrequest.md
  concepts/search-concept-custom-types.md
  concepts/search-concept-files.md
Labels: internal, ready to merge

#11791 Use user/contactFolders (instead of contactFolder)
  api-reference/beta/api/contact-delete.md
  api-reference/beta/api/contact-get.md
  api-reference/beta/api/contact-update.md
  api-reference/beta/api/user-list-contacts.md
  api-reference/v1.0/api/contact-delete.md
  api-reference/v1.0/api/contact-get.md
  api-reference/v1.0/api/contact-update.md
  api-reference/v1.0/api/user-list-contacts.md
  concepts/known-issues.md
Labels: content review, internal

#11795 PrintService: Report startDateTime/endDateTime
  api-reference/beta/api/printershare-delete-allowedgroup.md
  api-reference/beta/api/reports-getgrouparchivedprintjobs.md
  api-reference/beta/api/reports-getprinterarchivedprintjobs.md
  api-reference/beta/api/reports-getuserarchivedprintjobs.md
Labels: content review, internal, ready to merge

#11793 Dynamics: Remove trialBalance
  api-reference/beta/api/dynamics-create-customerpayment.md
  api-reference/beta/api/dynamics-trialbalance-get.md
  api-reference/beta/resources/dynamics-graph-reference.md
  api-reference/beta/resources/dynamics-trialbalance.md
  api-reference/beta/toc.yml
Labels: content review, internal

#11773 Update Graph overview image and descriptions.
  concepts/images/microsoft-graph-dataconnect-connectors-enhance.png
  concepts/overview.md
Labels: do not merge, internal

#11528 Q&Alinks
  concepts/best-practices-concept.md
  concepts/migrate-azure-ad-graph-deploy-test-extend.md
  concepts/office-365-connected-services.md
  concepts/onenote-abs-pos.md
  concepts/onenote-best-practices.md
  concepts/onenote-branding.md
  concepts/onenote-create-page.md
  concepts/onenote-extract-data.md
  concepts/onenote-get-content.md
  concepts/onenote-images-files.md
  concepts/onenote-note-tags.md
  concepts/onenote-update-page.md
  concepts/resolve-auth-errors.md
  concepts/search-concept-overview.md
  concepts/security-partner-overview.md
  concepts/versioning-and-support.md
Labels: internal, ready to merge

#11675 Microsoft Graph Toolkit 2.1 Release docs
  concepts/toc.yml
  concepts/toolkit/components/people-picker.md
  concepts/toolkit/components/person.md
  concepts/toolkit/customize-components/localization.md
  concepts/toolkit/get-started/build-an-electron-app.md
  concepts/toolkit/overview.md
  concepts/toolkit/providers/electron.md
  concepts/toolkit/providers/providers.md
Labels: internal, ready to merge

#11706 Set author field to facilitate assigning of Github issues to respective API owners.
  api-reference/beta/api/user-findmeetingtimes.md
  api-reference/beta/resources/attendeeavailability.md
  api-reference/beta/resources/locationconstraint.md
  api-reference/beta/resources/locationconstraintitem.md
  api-reference/beta/resources/mail-api-overview.md
  api-reference/beta/resources/meetingtimesuggestion.md
  api-reference/beta/resources/meetingtimesuggestionsresult.md
  api-reference/beta/resources/timeconstraint.md
  api-reference/beta/resources/timeslot.md
  api-reference/beta/resources/workinghours.md
  api-reference/v1.0/api/user-findmeetingtimes.md
  api-reference/v1.0/resources/attendeeavailability.md
  api-reference/v1.0/resources/mail-api-overview.md
  api-reference/v1.0/resources/meetingtimesuggestion.md
  api-reference/v1.0/resources/meetingtimesuggestionsresult.md
  api-reference/v1.0/resources/timeslot.md
  api-reference/v1.0/resources/workinghours.md
  concepts/outlook-calendar-meeting-proposals.md
  concepts/outlook-calendar-online-meetings.md
  concepts/outlook-create-event-in-shared-delegated-calendar.md
  concepts/outlook-create-send-messages.md
  concepts/outlook-get-mime-message.md
  concepts/outlook-get-shared-events-calendars.md
  concepts/outlook-immutable-id.md
  concepts/outlook-organize-messages.md
  concepts/outlook-schedule-recurring-events.md
  concepts/outlook-share-messages-folders.md
  concepts/outlook-share-or-delegate-calendar.md
Labels: internal, ready to merge

#11733 ToU - URL Path update
  api-reference/beta/api/agreement-delete.md
  api-reference/beta/api/agreement-get.md
  api-reference/beta/api/agreement-list.md
  api-reference/beta/api/agreement-post-agreements.md
  api-reference/beta/api/agreement-update.md
  api-reference/beta/includes/snippets/csharp/create-agreement-from-agreements-csharp-snippets.md
  api-reference/beta/includes/snippets/csharp/delete-agreement-csharp-snippets.md
  api-reference/beta/includes/snippets/csharp/get-agreement-csharp-snippets.md
  api-reference/beta/includes/snippets/csharp/get-agreements-csharp-snippets.md
  api-reference/beta/includes/snippets/csharp/update-agreement-csharp-snippets.md
  api-reference/beta/includes/snippets/java/create-agreement-from-agreements-java-snippets.md
  api-reference/beta/includes/snippets/java/delete-agreement-java-snippets.md
  api-reference/beta/includes/snippets/java/get-agreement-java-snippets.md
  api-reference/beta/includes/snippets/java/get-agreements-java-snippets.md
  api-reference/beta/includes/snippets/java/update-agreement-java-snippets.md
  api-reference/beta/includes/snippets/javascript/create-agreement-from-agreements-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/delete-agreement-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/get-agreement-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/get-agreements-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/update-agreement-javascript-snippets.md
  api-reference/beta/includes/snippets/objc/create-agreement-from-agreements-objc-snippets.md
  api-reference/beta/includes/snippets/objc/delete-agreement-objc-snippets.md
  api-reference/beta/includes/snippets/objc/get-agreement-objc-snippets.md
  api-reference/beta/includes/snippets/objc/get-agreements-objc-snippets.md
  api-reference/beta/includes/snippets/objc/update-agreement-objc-snippets.md
Labels: internal, ready to merge

#11787 Removing Intune Auditing and Intune Enrollment from V1.0
  api-reference/v1.0/api/intune-auditing-auditevent-create.md
  api-reference/v1.0/api/intune-auditing-auditevent-delete.md
  api-reference/v1.0/api/intune-auditing-auditevent-get.md
  api-reference/v1.0/api/intune-auditing-auditevent-getauditactivitytypes.md
  api-reference/v1.0/api/intune-auditing-auditevent-getauditcategories.md
  api-reference/v1.0/api/intune-auditing-auditevent-list.md
  api-reference/v1.0/api/intune-auditing-auditevent-update.md
  api-reference/v1.0/api/intune-enrollment-importedwindowsautopilotdeviceidentity-create.md
  api-reference/v1.0/api/intune-enrollment-importedwindowsautopilotdeviceidentity-delete.md
  api-reference/v1.0/api/intune-enrollment-importedwindowsautopilotdeviceidentity-get.md
  api-reference/v1.0/api/intune-enrollment-importedwindowsautopilotdeviceidentity-list.md
  api-reference/v1.0/api/intune-enrollment-importedwindowsautopilotdeviceidentity-update.md
  api-reference/v1.0/api/intune-enrollment-importedwindowsautopilotdeviceidentityupload-autopilotdevicestream.md
  api-reference/v1.0/api/intune-enrollment-importedwindowsautopilotdeviceidentityupload-create.md
  api-reference/v1.0/api/intune-enrollment-importedwindowsautopilotdeviceidentityupload-delete.md
  api-reference/v1.0/api/intune-enrollment-importedwindowsautopilotdeviceidentityupload-get.md
  api-reference/v1.0/api/intune-enrollment-importedwindowsautopilotdeviceidentityupload-list.md
  api-reference/v1.0/api/intune-enrollment-importedwindowsautopilotdeviceidentityupload-update.md
  api-reference/v1.0/resources/intune-auditing-auditactor.md
  api-reference/v1.0/resources/intune-auditing-auditevent.md
  api-reference/v1.0/resources/intune-auditing-auditproperty.md
  api-reference/v1.0/resources/intune-auditing-auditresource.md
  api-reference/v1.0/resources/intune-device-mgt-conceptual.md
  api-reference/v1.0/resources/intune-enrollment-conceptual.md
  api-reference/v1.0/resources/intune-enrollment-importedwindowsautopilotdeviceidentity.md
  api-reference/v1.0/resources/intune-enrollment-importedwindowsautopilotdeviceidentityimportstatus.md
  api-reference/v1.0/resources/intune-enrollment-importedwindowsautopilotdeviceidentitystate.md
  api-reference/v1.0/resources/intune-enrollment-importedwindowsautopilotdeviceidentityupload.md
  api-reference/v1.0/resources/intune-shared-devicemanagement.md
  api-reference/v1.0/toc.yml
Labels: content review, internal, ready to merge

#11794 Call: Remove updateMetadata
  api-reference/beta/api/call-updatemetadata.md
  api-reference/beta/includes/snippets/csharp/call-updatemetadata-csharp-snippets.md
  api-reference/beta/includes/snippets/javascript/call-updatemetadata-javascript-snippets.md
  api-reference/beta/includes/snippets/objc/call-updatemetadata-objc-snippets.md
  api-reference/beta/resources/teams-api-overview.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Skype.Calling.json
Labels: internal, ready to merge

#11744 fixed 404 in link
  api-reference/includes/accessreviews-disclaimer-v2.md
  api-reference/includes/accessreviews-disclaimer.md
Labels: area: azure/AAD, internal, ready to merge

#11797 Outlook task group sample URLs
  api-reference/beta/api/outlooktask-complete.md
  api-reference/beta/api/outlooktaskfolder-post-tasks.md
  api-reference/beta/api/outlooktaskgroup-post-taskfolders.md
Labels: content review, internal, ready to merge

#11832 Intune: Fix table formatting
  api-reference/beta/api/intune-deviceconfig-ioscustomconfiguration-create.md
  api-reference/beta/api/intune-deviceconfig-ioscustomconfiguration-update.md
  api-reference/beta/api/intune-deviceconfig-macoscustomappconfiguration-create.md
  api-reference/beta/api/intune-deviceconfig-macoscustomappconfiguration-update.md
  api-reference/beta/api/intune-deviceconfig-macoscustomconfiguration-create.md
  api-reference/beta/api/intune-deviceconfig-macoscustomconfiguration-update.md
  api-reference/beta/api/intune-shared-deviceappmanagement-syncmicrosoftstoreforbusinessapps.md
  api-reference/beta/api/intune-shared-ioslobappprovisioningconfiguration-create.md
  api-reference/beta/api/intune-shared-ioslobappprovisioningconfiguration-update.md
  api-reference/beta/resources/intune-deviceconfig-ioscustomconfiguration.md
  api-reference/beta/resources/intune-deviceconfig-macoscustomappconfiguration.md
  api-reference/beta/resources/intune-deviceconfig-macoscustomconfiguration.md
  api-reference/beta/resources/intune-deviceconfig-omasettingbase64.md
  api-reference/beta/resources/intune-shared-ioslobappprovisioningconfiguration.md
  api-reference/beta/resources/intune-shared-windowsdomainjoinconfiguration.md
  api-reference/v1.0/api/intune-deviceconfig-ioscustomconfiguration-create.md
  api-reference/v1.0/api/intune-deviceconfig-ioscustomconfiguration-update.md
  api-reference/v1.0/api/intune-deviceconfig-macoscustomconfiguration-create.md
  api-reference/v1.0/api/intune-deviceconfig-macoscustomconfiguration-update.md
  api-reference/v1.0/resources/intune-deviceconfig-ioscustomconfiguration.md
  api-reference/v1.0/resources/intune-deviceconfig-macoscustomconfiguration.md
  api-reference/v1.0/resources/intune-deviceconfig-omasettingbase64.md
Labels: content review, internal, ready to merge

#11852 Update to directory role assignment on app-only permission grant
  concepts/permissions-reference.md
Labels: internal, ready to merge

#11855 Clarify that implicit permission grants only apply for delegated permissions
  concepts/migrate-azure-ad-graph-app-registration.md
Labels: internal, ready to merge

#11859 Delete snippets.
  api-reference/beta/api/profile-list-accounts.md
Labels: internal

#11320 Update group.md non-implemented List properties
  api-reference/v1.0/resources/group.md
Labels: external, ready to merge

#10100 update permissions to match what service expects
  api-reference/beta/api/directory-list-featurerolloutpolicies.md
  api-reference/beta/api/directory-post-featurerolloutpolicies.md
  api-reference/beta/api/featurerolloutpolicy-delete-appliesto.md
  api-reference/beta/api/featurerolloutpolicy-delete.md
  api-reference/beta/api/featurerolloutpolicy-get.md
  api-reference/beta/api/featurerolloutpolicy-post-appliesto.md
  api-reference/beta/api/featurerolloutpolicy-update.md
Labels: external, review requested

#11594 Doc update for app staging.
  api-reference/v1.0/api/appcatalogs-list-teamsapps.md
  api-reference/v1.0/api/team-list-installedapps.md
  api-reference/v1.0/api/teamsapp-delete.md
  api-reference/v1.0/api/teamsapp-publish.md
  api-reference/v1.0/api/teamsapp-update.md
  api-reference/v1.0/api/teamworkbot-get.md
  api-reference/v1.0/api/userteamwork-list-installedapps.md
  api-reference/v1.0/resources/teamsapp.md
  api-reference/v1.0/resources/teamsappdefinition.md
  api-reference/v1.0/resources/teamworkbot.md
  changelog/Microsoft.Teams.GraphSvc.json
  concepts/search-concept-custom-types.md
Labels: internal, ready to merge

#11843 Drive: Navigate through items collection
  api-reference/beta/api/driveitem-list-versions.md
  api-reference/beta/api/driveitem-move.md
  api-reference/beta/api/driveitemversion-get-contents.md
  api-reference/beta/api/driveitemversion-get.md
  api-reference/v1.0/api/driveitem-list-versions.md
  api-reference/v1.0/api/driveitem-move.md
  api-reference/v1.0/api/driveitemversion-get-contents.md
  api-reference/v1.0/api/driveitemversion-get.md
Labels: content review, internal

#10961 regionalAndLanguageSettings update to add translation preferences
  api-reference/beta/api/regionalandlanguagesettings-get.md
  api-reference/beta/api/regionalandlanguagesettings-update.md
  api-reference/beta/resources/regionalandlanguagesettings.md
  api-reference/beta/resources/regionalformatoverrides.md
  api-reference/beta/resources/translationlanguageoverride.md
  api-reference/beta/resources/translationlanguageoverride.md.txt
  api-reference/beta/resources/translationpreferences.md
  api-reference/beta/toc.yml
  changelog/Microsoft.DirectoryServices.json
  concepts/changelog.md
Labels: internal, ready to merge

#11841 Excel: Use DELETE verb instead of POST on /delete
  api-reference/beta/api/chart-delete.md
  api-reference/beta/api/table-delete.md
  api-reference/beta/api/tablecolumn-delete.md
  api-reference/beta/api/tablerow-delete.md
  api-reference/beta/api/worksheet-delete.md
  api-reference/v1.0/api/chart-delete.md
  api-reference/v1.0/api/table-delete.md
  api-reference/v1.0/api/tablecolumn-delete.md
  api-reference/v1.0/api/tablerow-delete.md
  api-reference/v1.0/api/worksheet-delete.md
Labels: content review, internal

#11831 Table formatting fixes
  api-reference/beta/api/authentication-list-methods.md
  api-reference/beta/api/authentication-list-passwordmethods.md
  api-reference/beta/api/microsoftauthenticatorauthenticationmethod-delete.md
  api-reference/beta/api/microsoftauthenticatorauthenticationmethod-get.md
  api-reference/beta/api/microsoftauthenticatorauthenticationmethod-list.md
  api-reference/beta/api/passwordauthenticationmethod-get.md
  api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-delete.md
  api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-get.md
  api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-list.md
  api-reference/beta/api/phoneauthenticationmethod-delete.md
  api-reference/beta/api/phoneauthenticationmethod-disablesmssignin.md
  api-reference/beta/api/phoneauthenticationmethod-enablesmssignin.md
  api-reference/beta/api/phoneauthenticationmethod-get.md
  api-reference/beta/api/phoneauthenticationmethod-update.md
  api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md
  api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md
  api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md
  api-reference/beta/api/temporaryaccesspassauthenticationmethod-post.md
  api-reference/beta/api/windowshelloforbusinessauthenticationmethod-list.md
  api-reference/beta/resources/authenticationmethodspolicies-overview.md
  api-reference/beta/resources/opentypeextension.md
  api-reference/beta/resources/organization.md
  api-reference/beta/resources/termstore-term.md
  api-reference/beta/resources/user.md
  api-reference/v1.0/resources/invitation.md
  api-reference/v1.0/resources/opentypeextension.md
  api-reference/v1.0/resources/user.md
  concepts/permissions-reference.md
Labels: content review, internal

#11790 Remove user/calendarGroup
  api-reference/beta/api/user-list-calendars.md
  api-reference/v1.0/api/attachment-get.md
  api-reference/v1.0/api/user-list-calendars.md
Labels: content review, internal

#11789 ShiftPreferences url in example fixed.
  api-reference/v1.0/api/shiftpreferences-get.md
Labels: content review, internal

#11788 EducationSubmission: Remove Recall and Release actions
  api-reference/beta/api/educationsubmission-recall.md
  api-reference/beta/api/educationsubmission-release.md
Labels: content review, internal

#11856 Skip attempting to create PRs for subsequent commits to the snippet branch
  .github/workflows/snippet-generation-pr.yml
Labels: internal, ready to merge

#11850 Update B2X user flow descriptions
  api-reference/beta/resources/b2xidentityuserflow.md
  api-reference/beta/toc.yml
Labels: ready to merge

#11863 Update known-issues.md
  concepts/known-issues.md
Labels: external

#11862 Update presence.md
  api-reference/beta/resources/presence.md
Labels: external

#11834 Update userteamwork-sendactivitynotification.md
  api-reference/beta/api/userteamwork-sendactivitynotification.md
Labels: external

#11868 Added ms.author metadata back
  api-reference/docfx.json
  concepts/docfx.json
Labels: internal

#11784 Fixing sample URLs
  api-reference/beta/api/ediscovery-reviewsetquery-update.md
  api-reference/beta/api/ediscovery-usersource-get.md
  api-reference/beta/api/emailauthenticationmethodconfiguration-get.md
  api-reference/beta/api/emailauthenticationmethodconfiguration-update.md
  api-reference/beta/api/get-device-command-status.md
  api-reference/beta/api/identitycontainer-post-b2xuserflows.md
  api-reference/beta/api/profilephoto-update.md
Labels: content review, internal

#11878 Example URLs fixed
  api-reference/beta/api/printusagesummarybyprinter-get.md
  api-reference/beta/api/shiftpreferences-get.md
Labels: internal, ready to merge

#11876 Teams: v1.0 does not contain user/chats nor chat/messages
  api-reference/v1.0/api/chatmessage-update.md
  api-reference/v1.0/api/conversationmember-get.md
  api-reference/v1.0/api/conversationmember-list.md
Labels: internal, ready to merge

#11872 Fix permissions in messaging docs in v1
  api-reference/v1.0/api/channel-get-message.md
  api-reference/v1.0/api/channel-get-messagereply.md
  api-reference/v1.0/api/channel-list-messagereplies.md
  api-reference/v1.0/api/channel-list-messages.md
  api-reference/v1.0/api/chatmessage-delta.md
Labels: internal, ready to merge

#11616 Update print job update documentation
  api-reference/beta/api/printjob-abort.md
  api-reference/beta/api/printjob-update-configuration.md
  api-reference/beta/api/printjob-update.md
  api-reference/beta/resources/printjob.md
  api-reference/beta/toc.yml
  changelog/Microsoft.PrintService.json
Labels: area: universal print, content review complete, internal, ready to merge

#11869 GroupMember.Read.All scope required for group filtering
  concepts/toolkit/components/people-picker.md
Labels: external

#11904 Update plannertask.md
  api-reference/v1.0/resources/plannertask.md
Labels: external

#11897 Education: adding education root
  api-reference/beta/api/educationsubmission-list-resources.md
  api-reference/beta/api/educationsubmissionresource-delete.md
  api-reference/beta/api/educationsynchronizationerrors-get.md
  api-reference/beta/api/educationsynchronizationprofile-delete.md
  api-reference/beta/api/educationsynchronizationprofile-get.md
  api-reference/beta/api/educationsynchronizationprofile-list.md
  api-reference/beta/api/educationsynchronizationprofile-pause.md
  api-reference/beta/api/educationsynchronizationprofile-post.md
  api-reference/beta/api/educationsynchronizationprofile-put.md
  api-reference/beta/api/educationsynchronizationprofile-reset.md
  api-reference/beta/api/educationsynchronizationprofile-resume.md
  api-reference/beta/api/educationsynchronizationprofile-start.md
  api-reference/beta/api/educationsynchronizationprofile-uploadurl.md
  api-reference/beta/api/educationsynchronizationprofilestatus-get.md
Labels: internal, ready to merge

#11889 Update excel.md
  api-reference/beta/resources/excel.md
  api-reference/v1.0/resources/excel.md
Labels: internal, ready to merge

#10310 Adding Notes and Description
  api-reference/beta/resources/serviceprincipal.md
  api-reference/v1.0/resources/serviceprincipal.md
  changelog/Microsoft.DirectoryServices.json
Labels: content review complete, ready to merge

#10855 Add user:activateServicePlan API Documentation
  api-reference/beta/api/user-activateserviceplan.md
  api-reference/beta/resources/user.md
  api-reference/beta/toc.yml
  changelog/Microsoft.DirectoryServices.json
  concepts/changelog.md
Labels: content review complete, internal, ready to merge

#11792 Adding teamworkHostedContent
  api-reference/beta/resources/chatmessagehostedcontent.md
  api-reference/beta/resources/teamworkhostedcontent.md
  changelog/Microsoft.Teams.Core.json
Labels: content review complete, internal, ready to merge

#11813 Add compliance note to learn page and move PSTN setup steps from each API page to shared page
  api-reference/beta/api/application-post-calls.md
  api-reference/beta/api/call-redirect.md
  api-reference/beta/api/call-transfer.md
  api-reference/beta/api/participant-invite.md
  api-reference/v1.0/api/application-post-calls.md
  api-reference/v1.0/api/call-redirect.md
  api-reference/v1.0/api/call-transfer.md
  api-reference/v1.0/api/participant-invite.md
  concepts/cloud-communications-get-started.md
  concepts/cloud-communications-phone-number.md
Labels: content review complete, ready to merge

#11909 Identity and sign-in: Fixing sample URLs
  api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md
  api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md
  api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md
  api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md
  api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md
  api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md
  api-reference/beta/api/homerealmdiscoverypolicy-list-appliesto.md
  api-reference/beta/api/identityuserflowattribute-update.md
  api-reference/beta/api/tokenissuancepolicy-list-appliesto.md
  api-reference/beta/api/tokenlifetimepolicy-list-appliesto.md
  api-reference/beta/api/userflowlanguageconfiguration-list-overridespages.md
  api-reference/v1.0/api/claimsmappingpolicy-list-appliesto.md
  api-reference/v1.0/api/homerealmdiscoverypolicy-list-appliesto.md
Labels: internal, ready to merge

#11911 Identity: Fixing navigation URL examples
  api-reference/beta/api/directoryobject-delete.md
  api-reference/beta/api/serviceprincipal-list-memberof.md
  api-reference/v1.0/api/orgcontact-list-transitivememberof.md
  api-reference/v1.0/api/serviceprincipal-list-memberof.md
Labels: internal, ready to merge

#11910 Excel: Fixing a few more navigation paths
  api-reference/beta/api/workbookcomment-get.md
  api-reference/beta/api/workbookcommentreply-get.md
  api-reference/beta/api/workbookoperation-get.md
  api-reference/v1.0/api/workbook-list-comments.md
  api-reference/v1.0/api/workbookcomment-get.md
  api-reference/v1.0/api/workbookoperation-get.md
Labels: internal, ready to merge

#11916 Update teamsappdefinition.md
  api-reference/v1.0/resources/teamsappdefinition.md
Labels: external

#11874 Intune: Fix paths in managedDeviceCertificate
  api-reference/beta/api/intune-deviceconfig-manageddevicecertificatestate-create.md
  api-reference/beta/api/intune-deviceconfig-manageddevicecertificatestate-delete.md
  api-reference/beta/api/intune-deviceconfig-manageddevicecertificatestate-get.md
  api-reference/beta/api/intune-deviceconfig-manageddevicecertificatestate-list.md
  api-reference/beta/api/intune-deviceconfig-manageddevicecertificatestate-update.md
  api-reference/beta/api/intune-shared-devicemanagement-getassignedroleidsforloggedinuser.md
  api-reference/v1.0/api/intune-shared-devicecategory-update.md
Labels: internal, ready to merge

#11922 Update synchronization-synchronizationjob-get.md
  api-reference/beta/api/directorydefinition-discover.md
  api-reference/beta/api/synchronization-synchronizationjob-get.md
  api-reference/beta/api/synchronization-synchronizationschema-filteroperators.md
  api-reference/beta/api/synchronization-synchronizationschema-functions.md
  api-reference/beta/api/synchronization-synchronizationschema-get.md
  api-reference/beta/api/synchronization-synchronizationtemplate-get.md
  api-reference/beta/api/synchronization-synchronizationtemplate-list.md
  changelog/Microsoft.DirectoryServices.json
Labels: area: azure/AAD, internal, ready to merge

#11877 SharePoint: Fixing example URLs
  api-reference/beta/api/driveitem-follow.md
  api-reference/beta/api/itemactivity-getbyinterval.md
  api-reference/beta/api/permission-delete.md
  api-reference/beta/api/permission-revokegrants.md
  api-reference/v1.0/api/driveitem-follow.md
  api-reference/v1.0/api/itemactivitystat-getactivitybyinterval.md
  api-reference/v1.0/api/subscriptions-socketio.md
Labels: content review, internal, ready to merge

#11912 Policies, eDiscovery, applications navigation URLs
  api-reference/beta/api/claimsmappingpolicy-list-appliesto.md
  api-reference/beta/api/directorysetting-list.md
  api-reference/beta/api/ediscovery-case-get.md
  api-reference/beta/api/ediscovery-reviewset-addtoreviewset.md
  api-reference/beta/api/notebook-getrecentnotebooks.md
  api-reference/beta/api/privilegedapproval-update.md
  api-reference/beta/api/privilegedroleassignmentrequest-cancel.md
  api-reference/beta/api/program-listcontrols.md
  api-reference/beta/api/program-update.md
  api-reference/beta/api/subscriptions-socketio.md
  api-reference/beta/api/synchronization-synchronizationtemplate-update.md
Labels: content review, internal, ready to merge

#11935 Fixed MicrosoftTeams import statements in Toolkit docs
  concepts/toolkit/components/person-card.md
  concepts/toolkit/get-started/build-a-microsoft-teams-tab.md
  concepts/toolkit/providers/teams.md
Labels: ready to merge

#11264 Almars/organizationbranding
  api-reference/v1.0/api/organizationalbrandingproperties-create.md
  api-reference/v1.0/api/organizationalbrandingproperties-delete.md
  api-reference/v1.0/api/organizationalbrandingproperties-get.md
  api-reference/v1.0/api/organizationalbrandingproperties-update.md
  api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md
  api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md
  api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md
  api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md
  api-reference/v1.0/resources/azure-ad-overview.md
  api-reference/v1.0/resources/organization.md
  api-reference/v1.0/resources/organizationalbrandingproperties.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.DirectoryServices.json
Labels: content review complete, internal, ready to merge

#11937 Update signinactivity.md
  api-reference/beta/resources/signinactivity.md
Labels: external

#11934 Update json-batching.md
  concepts/json-batching.md
Labels: external

#11928 Update regionalandlanguagesettings.md
  api-reference/beta/resources/regionalandlanguagesettings.md
Labels: external

#11642 Moving docs from beta to v1.0 for Terms of Use API's
  api-reference/v1.0/api/agreement-delete.md
  api-reference/v1.0/api/agreement-get.md
  api-reference/v1.0/api/agreement-list.md
  api-reference/v1.0/api/agreement-post-agreements.md
  api-reference/v1.0/api/agreement-update.md
  api-reference/v1.0/api/user-list-agreementacceptances.md
  api-reference/v1.0/resources/agreement.md
  api-reference/v1.0/resources/agreementacceptance.md
  api-reference/v1.0/resources/agreementfile.md
  api-reference/v1.0/resources/agreementfiledata.md
  api-reference/v1.0/resources/agreementfilelocalization.md
  api-reference/v1.0/resources/agreementfileversion.md
  api-reference/v1.0/resources/termsexpiration.md
  api-reference/v1.0/resources/user.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.DirectoryServices.json
  concepts/changelog.md
Labels: content review complete, internal, ready to merge

#11913 Adding changes to reflect the bitlocker recovery's root node is now i…
  api-reference/beta/api/bitlocker-list-recoverykeys.md
  api-reference/beta/api/bitlockerrecoverykey-get.md
  changelog/Microsoft.BitLocker.json
Labels: internal, ready to merge

#11880 Refresh What's new topic.
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: do not merge, internal

#11941 Fixed H3 title.
  concepts/whats-new-overview.md
Labels: internal

#11940 Update what's new topic.
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: internal

#11952 Enabling delegated teams messaging webhooks in v1.0
  api-reference/v1.0/api/subscription-delete.md
  api-reference/v1.0/api/subscription-get.md
  api-reference/v1.0/api/subscription-post-subscriptions.md
  api-reference/v1.0/api/subscription-update.md
  changelog/Microsoft.Teams.Core.json
  concepts/teams-changenotifications-chatmessage.md
Labels: content review complete, internal, ready to merge

#11927 Intune: Remove pfxRecryptionRequest, pfxUserCertificate, and onpremEncryptedPayload
  api-reference/beta/api/intune-raimportcerts-onpremencryptedpayload-create.md
  api-reference/beta/api/intune-raimportcerts-onpremencryptedpayload-delete.md
  api-reference/beta/api/intune-raimportcerts-onpremencryptedpayload-get.md
  api-reference/beta/api/intune-raimportcerts-onpremencryptedpayload-list.md
  api-reference/beta/api/intune-raimportcerts-onpremencryptedpayload-update.md
  api-reference/beta/api/intune-raimportcerts-pfxrecryptionrequest-create.md
  api-reference/beta/api/intune-raimportcerts-pfxrecryptionrequest-delete.md
  api-reference/beta/api/intune-raimportcerts-pfxrecryptionrequest-get.md
  api-reference/beta/api/intune-raimportcerts-pfxrecryptionrequest-list.md
  api-reference/beta/api/intune-raimportcerts-pfxrecryptionrequest-update.md
  api-reference/beta/api/intune-raimportcerts-pfxusercertificate-create.md
  api-reference/beta/api/intune-raimportcerts-pfxusercertificate-delete.md
  api-reference/beta/api/intune-raimportcerts-pfxusercertificate-get.md
  api-reference/beta/api/intune-raimportcerts-pfxusercertificate-list.md
  api-reference/beta/api/intune-raimportcerts-pfxusercertificate-update.md
  api-reference/beta/resources/intune-raimportcerts-onpremencryptedpayload.md
  api-reference/beta/resources/intune-raimportcerts-pfxrecryptionrequest.md
  api-reference/beta/resources/intune-raimportcerts-pfxusercertificate.md
Labels: internal, ready to merge

#11645 approvals apis-initial PR
  api-reference/beta/api/approval-get.md
  api-reference/beta/api/approval-list-steps.md
  api-reference/beta/api/approvalstep-get.md
  api-reference/beta/api/approvalstep-update.md
  api-reference/beta/resources/approval.md
  api-reference/beta/resources/approvalstep.md
  api-reference/beta/resources/entitlementmanagement-root.md
  api-reference/beta/toc.yml
  changelog/Microsoft.DirectoryServices.json
Labels: content review complete, internal, ready to merge

#11948 Update main branch reference for snippet generation GitHub Action
  .github/workflows/snippet-generation-pr.yml
Labels: internal, ready to merge

#11944 Update whats-new-overview.md
  concepts/whats-new-overview.md
Labels: external

#11939 Localization: Removing property names in URL
  api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md
  api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md
Labels: internal, ready to merge

#11951 [mgt] mgt-person additional person properties
  concepts/toolkit/components/person.md
Labels: external, ready to merge

#11754 Added the displayName property to agreementFile, agreementFIleLocalization and agreementFileVersion.
  api-reference/beta/resources/agreementfile.md
  api-reference/beta/resources/agreementfilelocalization.md
  api-reference/beta/resources/agreementfileversion.md
  changelog/Microsoft.DirectoryServices.json
  concepts/changelog.md
Labels: content review complete, internal, ready to merge

#11742 Added localized display name property to policy file.
  api-reference/v1.0/resources/agreementfile.md
  api-reference/v1.0/resources/agreementfilelocalization.md
  api-reference/v1.0/resources/agreementfileversion.md
  changelog/Microsoft.DirectoryServices.json
Labels: content review complete, internal, ready to merge

#11970 Update eol-blocker.yml
  .github/workflows/eol-blocker.yml
Labels: internal

#11974 remove unnecessary slash
  concepts/errors.md
Labels: external

#12000 Note necessary permissions to respond to customer issue. Reformatted sections.
  concepts/outlook-create-event-in-shared-delegated-calendar.md
  concepts/outlook-share-or-delegate-calendar.md
Labels: internal

#11375 java sdk v3 documentation changes
  concepts/sdks/batch-requests.md
  concepts/sdks/choose-authentication-providers.md
  concepts/sdks/create-client.md
  concepts/sdks/customize-client.md
  concepts/sdks/includes/snippets/java/create-requests-list.md
  concepts/sdks/includes/snippets/java/create-requests-queryparams.md
  concepts/sdks/large-file-upload.md
  concepts/sdks/sdk-installation.md
  concepts/sdks/use-beta.md
Labels: internal, ready to merge

#11999 remove duplicate 'Chat' node in v1 toc.yml
  api-reference/v1.0/toc.yml
Labels: internal, ready to merge

#12017 Update team-list-installedapps.md
  api-reference/v1.0/api/team-list-installedapps.md
Labels: external

#12018 Update team-list-installedapps.md
  api-reference/beta/api/team-list-installedapps.md
Labels: external

#11769 update MGT/Teams getting started guide
  concepts/toolkit/get-started/build-a-microsoft-teams-tab.md
Labels: internal, ready to merge

#12026 Update scopes teams-channel-picker
  concepts/toolkit/components/teams-channel-picker.md
Labels: external

#11993 Updated cloud-comm doc author to PM
  api-reference/beta/resources/broadcastmeetingsettings.md
  api-reference/beta/resources/lobbyBypassSettings.md
  api-reference/beta/resources/outofofficesettings.md
  api-reference/v1.0/api/cloudcommunications-getpresencesbyuserid.md
  api-reference/v1.0/api/presence-get.md
  api-reference/v1.0/resources/lobbyBypassSettings.md
  api-reference/v1.0/resources/presence.md
  concepts/cloud-communication-online-meeting-application-access-policy.md
Labels: internal, ready to merge

#12016 Add two enum members to cloudPcDeviceImageStatusDetails
  api-reference/beta/resources/cloudpcdeviceimage.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: content review complete, internal, ready to merge

#12022 Update ms.prod for 55 files in other areas
  api-reference/beta/api/informationprotection-list-threatassessmentrequests.md
  api-reference/beta/api/informationprotection-post-threatassessmentrequests.md
  api-reference/beta/api/informationprotectionlabel-evaluateapplication.md
  api-reference/beta/api/informationprotectionlabel-evaluateclassificationresults.md
  api-reference/beta/api/informationprotectionlabel-evaluateremoval.md
  api-reference/beta/api/informationprotectionlabel-extractlabel.md
  api-reference/beta/api/informationprotectionlabel-get.md
  api-reference/beta/api/informationprotectionpolicy-list-labels.md
  api-reference/beta/api/subscription-delete.md
  api-reference/beta/api/threatassessmentrequest-get.md
  api-reference/beta/resources/accessaction.md
  api-reference/beta/resources/addcontentfooteraction.md
  api-reference/beta/resources/addcontentheaderaction.md
  api-reference/beta/resources/addwatermarkaction.md
  api-reference/beta/resources/applylabelaction.md
  api-reference/beta/resources/classificationresult.md
  api-reference/beta/resources/contentinfo.md
  api-reference/beta/resources/customaction.md
  api-reference/beta/resources/downgradejustification.md
  api-reference/beta/resources/emailfileassessmentrequest.md
  api-reference/beta/resources/employeeorgdata.md
  api-reference/beta/resources/fileassessmentrequest.md
  api-reference/beta/resources/informationprotectionaction.md
  api-reference/beta/resources/informationprotectioncontentlabel.md
  api-reference/beta/resources/informationprotectionlabel.md
  api-reference/beta/resources/justifyaction.md
  api-reference/beta/resources/labeldetails.md
  api-reference/beta/resources/labelingoptions.md
  api-reference/beta/resources/mailassessmentrequest.md
  api-reference/beta/resources/metadataaction.md
  api-reference/beta/resources/protectadhocaction.md
  api-reference/beta/resources/protectbytemplateaction.md
  api-reference/beta/resources/protectdonotforwardaction.md
  api-reference/beta/resources/recommendlabelaction.md
  api-reference/beta/resources/removecontentfooteraction.md
  api-reference/beta/resources/removecontentheaderaction.md
  api-reference/beta/resources/removeprotectionaction.md
  api-reference/beta/resources/removewatermarkaction.md
  api-reference/beta/resources/threatassessmentrequest.md
  api-reference/beta/resources/threatassessmentresult.md
  api-reference/beta/resources/translationlanguageoverride.md
  api-reference/beta/resources/translationlanguageoverride.md.txt
  api-reference/beta/resources/urlassessmentrequest.md
  api-reference/v1.0/api/informationprotection-list-threatassessmentrequests.md
  api-reference/v1.0/api/informationprotection-post-threatassessmentrequests.md
  api-reference/v1.0/api/subscription-delete.md
  api-reference/v1.0/api/threatassessmentrequest-get.md
  api-reference/v1.0/resources/emailFileAssessmentRequest.md
  api-reference/v1.0/resources/employeeorgdata.md
  api-reference/v1.0/resources/fileassessmentrequest.md
  api-reference/v1.0/resources/mailassessmentrequest.md
  api-reference/v1.0/resources/threatassessmentrequest.md
  api-reference/v1.0/resources/threatassessmentresult.md
  api-reference/v1.0/resources/urlassessmentrequest.md
  concepts/device-relay-concept-overview.md
Labels: area: azure/AAD, content review complete, internal, ready to merge

#12021 Typo in Corporate management
  api-reference/beta/toc.yml
Labels: external

#11032 Refactor identified enum types in Users topic
  api-reference/beta/resources/approleassignment.md
  api-reference/beta/resources/calendar.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/group.md
  api-reference/beta/resources/inferenceclassificationoverride.md
  api-reference/beta/resources/mailtips.md
  api-reference/beta/resources/message.md
  api-reference/beta/resources/notebook.md
  api-reference/beta/resources/onenoteoperation.md
  api-reference/beta/resources/outlooktask.md
  api-reference/v1.0/resources/approleassignment.md
  api-reference/v1.0/resources/calendar.md
  api-reference/v1.0/resources/enums.md
  api-reference/v1.0/resources/group.md
  api-reference/v1.0/resources/mailtips.md
  api-reference/v1.0/resources/message.md
  api-reference/v1.0/resources/onenote.md
  api-reference/v1.0/resources/onenoteoperation.md
Labels: area: azure/AAD, area: users, content review complete, internal, ready to merge

#11054 Refactor identified enums in Groups
  api-reference/beta/resources/itembody.md
  api-reference/beta/resources/post.md
Labels: area: azure/AAD, area: groups, content review complete, internal, ready to merge

#11120 Refactor identified enums in Applications
  api-reference/beta/resources/apiapplication.md
  api-reference/beta/resources/application.md
  api-reference/beta/resources/broadcastmeetingsettings.md
  api-reference/beta/resources/call.md
  api-reference/beta/resources/callmediastate.md
  api-reference/beta/resources/callrecords-callrecord.md
  api-reference/beta/resources/connector.md
  api-reference/beta/resources/connectorgroup.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/kerberossignonsettings.md
  api-reference/beta/resources/lobbyBypassSettings.md
  api-reference/beta/resources/meetingcapability.md
  api-reference/beta/resources/meetingparticipantinfo.md
  api-reference/beta/resources/onlinemeeting.md
  api-reference/beta/resources/onpremisesagent.md
  api-reference/beta/resources/onpremisesagentgroup.md
  api-reference/beta/resources/onpremisespublishing.md
  api-reference/beta/resources/publishedresource.md
  api-reference/beta/resources/synchronization-attributedefinition.md
  api-reference/beta/resources/synchronization-directorydefinition.md
  api-reference/beta/resources/toneinfo.md
  api-reference/beta/resources/webapplication.md
  api-reference/v1.0/resources/apiapplication.md
  api-reference/v1.0/resources/application.md
  api-reference/v1.0/resources/call.md
  api-reference/v1.0/resources/callmediastate.md
  api-reference/v1.0/resources/callrecords-callrecord.md
  api-reference/v1.0/resources/enums.md
  api-reference/v1.0/resources/lobbyBypassSettings.md
  api-reference/v1.0/resources/meetingparticipantinfo.md
  api-reference/v1.0/resources/onlinemeeting.md
  api-reference/v1.0/resources/toneinfo.md
Labels: area: azure/AAD, content review complete, internal, ready to merge

#11122 Refactor identified enums in Reports
  api-reference/beta/resources/credentialusagesummary.md
  api-reference/beta/resources/credentialuserregistrationdetails.md
  api-reference/beta/resources/directoryaudit.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/keyvaluepair.md
  api-reference/beta/resources/provisioningstep.md
  api-reference/beta/resources/relyingpartydetailedsummary.md
  api-reference/beta/resources/signin.md
  api-reference/beta/resources/statusbase.md
  api-reference/beta/resources/statusdetails.md
  api-reference/beta/resources/targetresource.md
  api-reference/beta/resources/usercredentialusagedetails.md
  api-reference/v1.0/resources/appliedconditionalaccesspolicy.md
  api-reference/v1.0/resources/directoryaudit.md
  api-reference/v1.0/resources/enums.md
  api-reference/v1.0/resources/signin.md
  api-reference/v1.0/resources/targetresource.md
Labels: area: azure/AAD, area: reports, content review complete, internal, ready to merge

#11727 Update docs & resolve GitHub issues
  api-reference/beta/api/administrativeunit-post-members.md
  api-reference/beta/api/agreement-delete.md
  api-reference/beta/api/agreement-get.md
  api-reference/beta/api/agreement-list.md
  api-reference/beta/api/agreement-post-agreements.md
  api-reference/beta/api/agreement-update.md
  api-reference/beta/api/directory-deleteditems-delete.md
  api-reference/beta/api/phoneauthenticationmethod-delete.md
  api-reference/beta/api/phoneauthenticationmethod-disablesmssignin.md
  api-reference/beta/api/phoneauthenticationmethod-enablesmssignin.md
  api-reference/beta/api/phoneauthenticationmethod-get.md
  api-reference/beta/api/phoneauthenticationmethod-update.md
  api-reference/beta/api/serviceprincipal-delete-approleassignedto.md
  api-reference/beta/api/serviceprincipal-list.md
  api-reference/beta/api/user-list-agreementacceptances.md
  api-reference/beta/api/user-list-manager.md
  api-reference/beta/api/user-list.md
  api-reference/beta/api/user-update.md
  api-reference/beta/resources/application.md
  api-reference/beta/resources/authenticationdetail.md
  api-reference/beta/resources/conditionalaccessconditionset.md
  api-reference/beta/resources/device.md
  api-reference/beta/resources/extensionproperty.md
  api-reference/beta/resources/phoneauthenticationmethod.md
  api-reference/beta/resources/serviceprincipal.md
  api-reference/beta/resources/user.md
  api-reference/v1.0/api/administrativeunit-post-members.md
  api-reference/v1.0/api/application-post-owners.md
  api-reference/v1.0/api/directory-deleteditems-delete.md
  api-reference/v1.0/api/serviceprincipal-delete-approleassignedto.md
  api-reference/v1.0/api/serviceprincipal-update.md
  api-reference/v1.0/api/user-list-manager.md
  api-reference/v1.0/api/user-list.md
  api-reference/v1.0/api/user-update.md
  api-reference/v1.0/resources/application.md
  api-reference/v1.0/resources/conditionalaccessconditionset.md
  api-reference/v1.0/resources/extensionproperty.md
  api-reference/v1.0/resources/serviceprincipal.md
  api-reference/v1.0/resources/user.md
  concepts/permissions-reference.md
  concepts/query-parameters.md
Labels: area: azure/AAD, content review complete, internal, ready to merge

#11991 Add {{this}} docs to mgt templating page
  concepts/toolkit/customize-components/templates.md
Labels: internal, ready to merge

#12007 author change for invitations
  api-reference/beta/api/invitation-post.md
  api-reference/beta/resources/invitation.md
  api-reference/beta/resources/invitedusermessageinfo.md
  api-reference/v1.0/api/invitation-post.md
  api-reference/v1.0/resources/invitation.md
  api-reference/v1.0/resources/invitedusermessageinfo.md
Labels: area: azure/AAD, internal, ready to merge

#12005 Update site-getapplicablecontenttypesforlist.md
  api-reference/beta/api/site-getapplicablecontenttypesforlist.md
Labels: external

#12019 Update contenttype-addcopy.md
  api-reference/beta/api/contenttype-addcopy.md
Labels: external

#12039 - updates trigger branches after rename for conflict bot
  .github/workflows/conflicting-pr-label.yml
Labels: internal, ready to merge

#12040 Update contenttype-associatewithhubsites.md
  api-reference/beta/api/contenttype-associatewithhubsites.md
Labels: external

#11819 Consent requests APIs (preview)
  api-reference/beta/api/adminconsentrequestpolicy-get.md
  api-reference/beta/api/adminconsentrequestpolicy-update.md
  api-reference/beta/api/appconsentrequest-filterByCurrentUser.md
  api-reference/beta/api/appconsentrequest-get.md
  api-reference/beta/api/appconsentrequest-list.md
  api-reference/beta/api/userconsentrequest-filterByCurrentUser.md
  api-reference/beta/api/userconsentrequest-get.md
  api-reference/beta/api/userconsentrequest-list.md
  api-reference/beta/resources/adminconsentrequestpolicy.md
  api-reference/beta/resources/appconsentrequest.md
  api-reference/beta/resources/appconsentrequestscope.md
  api-reference/beta/resources/approval.md
  api-reference/beta/resources/approvalstep.md
  api-reference/beta/resources/azure-ad-overview.md
  api-reference/beta/resources/consentrequests-root.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/userconsentrequest.md
  api-reference/beta/toc.yml
  changelog/Microsoft.DirectoryServices.json
  concepts/permissions-reference.md
Labels: area: azure/AAD, internal, ready to merge

#11272 Migrating featureRolloutPolicies from /directory to /policies
  api-reference/beta/api/featurerolloutpolicy-delete-appliesto.md
  api-reference/beta/api/featurerolloutpolicy-delete.md
  api-reference/beta/api/featurerolloutpolicy-get.md
  api-reference/beta/api/featurerolloutpolicy-post-appliesto.md
  api-reference/beta/api/featurerolloutpolicy-update.md
  api-reference/beta/api/list-featurerolloutpolicies.md
  api-reference/beta/api/post-featurerolloutpolicies.md
  api-reference/beta/resources/directory.md
  api-reference/beta/resources/featurerolloutpolicy.md
  api-reference/beta/toc.yml
  api-reference/includes/directory-featurerolloutpolicies-deprecate.md
  changelog/Microsoft.HybridAuthentication.json
Labels: content review complete, internal, ready to merge

#12042 Update author to Julia
  api-reference/v1.0/api/user-list-agreementacceptances.md
Labels: internal, ready to merge

#11734 Adding featureRolloutPolicies to v1.0
  api-reference/v1.0/api/featurerolloutpolicies-list.md
  api-reference/v1.0/api/featurerolloutpolicies-post.md
  api-reference/v1.0/api/featurerolloutpolicy-delete-appliesto.md
  api-reference/v1.0/api/featurerolloutpolicy-delete.md
  api-reference/v1.0/api/featurerolloutpolicy-get.md
  api-reference/v1.0/api/featurerolloutpolicy-post-appliesto.md
  api-reference/v1.0/api/featurerolloutpolicy-update.md
  api-reference/v1.0/resources/featurerolloutpolicy.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.HybridAuthentication.json
Labels: content review complete, internal, ready to merge, schema live

#11274 Promoting auth method APIs to v1.0
  api-reference/v1.0/api/authentication-list-methods.md
  api-reference/v1.0/api/authenticationmethod-get.md
  api-reference/v1.0/api/emailauthenticationmethodconfiguration-delete.md
  api-reference/v1.0/api/emailauthenticationmethodconfiguration-get.md
  api-reference/v1.0/api/emailauthenticationmethodconfiguration-update.md
  api-reference/v1.0/api/fido2authenticationmethod-delete.md
  api-reference/v1.0/api/fido2authenticationmethod-get.md
  api-reference/v1.0/api/fido2authenticationmethod-list.md
  api-reference/v1.0/api/fido2authenticationmethodconfiguration-delete.md
  api-reference/v1.0/api/fido2authenticationmethodconfiguration-get.md
  api-reference/v1.0/api/fido2authenticationmethodconfiguration-update.md
  api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-delete.md
  api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-get.md
  api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-list.md
  api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-delete.md
  api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md
  api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-update.md
  api-reference/v1.0/api/windowshelloforbusinessauthenticationmethod-delete.md
  api-reference/v1.0/api/windowshelloforbusinessauthenticationmethod-get.md
  api-reference/v1.0/api/windowshelloforbusinessauthenticationmethod-list.md
  api-reference/v1.0/resources/authenticationmethod.md
  api-reference/v1.0/resources/authenticationmethodconfiguration.md
  api-reference/v1.0/resources/authenticationmethods-overview.md
  api-reference/v1.0/resources/authenticationmethodspolicies-overview.md
  api-reference/v1.0/resources/authenticationmethodtarget.md
  api-reference/v1.0/resources/emailauthenticationmethodconfiguration.md
  api-reference/v1.0/resources/enums.md
  api-reference/v1.0/resources/fido2authenticationmethod.md
  api-reference/v1.0/resources/fido2authenticationmethodconfiguration.md
  api-reference/v1.0/resources/fido2keyrestrictions.md
  api-reference/v1.0/resources/microsoftauthenticatorauthenticationmethod.md
  api-reference/v1.0/resources/microsoftauthenticatorauthenticationmethodconfiguration.md
  api-reference/v1.0/resources/microsoftauthenticatorauthenticationmethodtarget.md
  api-reference/v1.0/resources/windowshelloforbusinessauthenticationmethod.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.DirectoryServices.json
Labels: content review complete, ready to merge, schema live

#12044 import fees disclaimer
  api-reference/beta/api/channel-post-message.md
  api-reference/beta/api/channel-post-messagereply.md
  api-reference/beta/api/channel-post.md
  api-reference/beta/api/team-post.md
  api-reference/beta/resources/team.md
Labels: area: teams, internal, ready to merge

#11366 Removed Preview tags from Graph connector articles
  concepts/search-concept-overview.md
  concepts/search-index-manage-connections.md
  concepts/search-index-manage-items.md
  concepts/search-index-manage-schema.md
Labels: internal, ready to merge

#11332 add chat id, channel id to chatmessage
  api-reference/beta/resources/channelidentity.md
  api-reference/beta/resources/chatmessage.md
  changelog/Microsoft.Teams.Core.json
Labels: internal, ready to merge

#11674 Update microsoftauthenticatorauthenticationmethodtarget.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/microsoftauthenticatorauthenticationmethodtarget.md
  changelog/Microsoft.DirectoryServices.json
Labels: ready to merge

#11811 Updated relatedContact docs
  api-reference/beta/api/relatedcontact-update.md
  api-reference/beta/resources/relatedcontact.md
Labels: area: edu, content review complete, internal, ready to merge

#12015 Update user-update.md - Add details for ageGroup, consentProvidedForMinor, companyName, employeeId properties
  api-reference/beta/api/user-update.md
  api-reference/v1.0/api/user-update.md
Labels: area: azure/AAD, content review complete, external, ready to merge, schema live

#12055 Change namedLocations in TOC
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
Labels: internal, ready to merge

#12056 Update group-list.md
  api-reference/v1.0/api/group-list.md
Labels: external

#12050 New notificationContentType and notificationQueryOptions properties/Update UP webhook to v1.0
  api-reference/beta/api/subscription-delete.md
  api-reference/beta/api/subscription-get.md
  api-reference/beta/api/subscription-list.md
  api-reference/beta/api/subscription-post-subscriptions.md
  api-reference/beta/api/subscription-update.md
  api-reference/beta/resources/subscription.md
  api-reference/beta/resources/webhooks.md
  api-reference/v1.0/api/subscription-delete.md
  api-reference/v1.0/api/subscription-get.md
  api-reference/v1.0/api/subscription-list.md
  api-reference/v1.0/api/subscription-post-subscriptions.md
  api-reference/v1.0/api/subscription-update.md
  api-reference/v1.0/resources/subscription.md
  api-reference/v1.0/resources/webhooks.md
  changelog/Microsoft.SubscriptionServices.json
  concepts/universal-print-webhook-notifications.md
Labels: area: universal print, area: webhooks, internal, ready to merge, schema live

#11985 deleted note about restrictions to global role
  api-reference/beta/api/iteminsightssettings-get.md
Labels: ready to merge

#11955 format updates to app proxy tutorial
  concepts/application-proxy-configure-api.md
  concepts/images/application-proxy-configure-api/accept-permissions.PNG
  concepts/images/application-proxy-configure-api/select-permissions.PNG
  concepts/images/application-proxy-configure-api/set-permissions.png
Labels: area: azure/AAD, internal, ready to merge

#12065 Merge to publish (OOB request)
  api-reference/beta/api/iteminsightssettings-get.md
  api-reference/beta/api/subscription-delete.md
  api-reference/beta/api/subscription-get.md
  api-reference/beta/api/subscription-list.md
  api-reference/beta/api/subscription-post-subscriptions.md
  api-reference/beta/api/subscription-update.md
  api-reference/beta/resources/subscription.md
  api-reference/beta/resources/webhooks.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/group-list.md
  api-reference/v1.0/api/subscription-delete.md
  api-reference/v1.0/api/subscription-get.md
  api-reference/v1.0/api/subscription-list.md
  api-reference/v1.0/api/subscription-post-subscriptions.md
  api-reference/v1.0/api/subscription-update.md
  api-reference/v1.0/resources/subscription.md
  api-reference/v1.0/resources/webhooks.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.SubscriptionServices.json
  concepts/application-proxy-configure-api.md
  concepts/images/application-proxy-configure-api/accept-permissions.PNG
  concepts/images/application-proxy-configure-api/select-permissions.PNG
  concepts/images/application-proxy-configure-api/set-permissions.png
  concepts/universal-print-webhook-notifications.md
Labels: internal

#12092 Update contenttype-copytodefaultcontentlocation.md
  api-reference/beta/api/contenttype-copytodefaultcontentlocation.md
Labels: external

#12066 Update group-list.md
  api-reference/beta/api/group-list.md
Labels: external

#12121 Update windowsupdates-deploymentsettings.md
  api-reference/beta/resources/windowsupdates-deploymentsettings.md
Labels: external

#12120 Update windowsupdates-deploymentaudience.md
  api-reference/beta/resources/windowsupdates-deploymentaudience.md
Labels: external

#12123 Update windowsupdates-deploymentstatereason.md
  api-reference/beta/resources/windowsupdates-deploymentstatereason.md
Labels: external

#12125 Editing windowsupdates-deploymentstate.md
  api-reference/beta/resources/windowsupdates-deploymentstate.md
Labels: external

#12126 Update windowsupdates-expeditedqualityupdatereference.md
  api-reference/beta/resources/windowsupdates-expeditedqualityupdatereference.md
Labels: external

#12128 Update windowsupdates-featureupdatereference.md
  api-reference/beta/resources/windowsupdates-featureupdatereference.md
Labels: external

#12131 Update windowsupdates-monitoringrule.md
  api-reference/beta/resources/windowsupdates-monitoringrule.md
Labels: external

#12130 Update windowsupdates-qualityupdatereference.md
  api-reference/beta/resources/windowsupdates-qualityupdatereference.md
Labels: external

#12132 Update windowsupdates-rolloutsettings.md
  api-reference/beta/resources/windowsupdates-rolloutsettings.md
Labels: external

#12129 Update windowsupdates-monitoringsettings.md
  api-reference/beta/resources/windowsupdates-monitoringsettings.md
Labels: external

#12127 Update windowsupdates-featureupdatecatalogentry.md
  api-reference/beta/resources/windowsupdates-featureupdatecatalogentry.md
Labels: external

#12113 Removing the Preview tag for change notifications delivery
  concepts/change-notifications-delivery.md
Labels: content review complete, internal

#12145 Update contenttype-list-columns.md
  api-reference/beta/api/contenttype-list-columns.md
Labels: external

#12108 Update teams-concept-overview.md
  concepts/teams-concept-overview.md
Labels: external

#12105 Update use-postman.md
  concepts/use-postman.md
Labels: external

#12098 Update cloud-communication-online-meeting-application-access-policy.md
  concepts/cloud-communication-online-meeting-application-access-policy.md
Labels: external

#12100 Update columndefinition-update.md
  api-reference/beta/api/columndefinition-update.md
Labels: external

#11695 Changed author and prod for notifications and subscriptions
  api-reference/beta/api/locatedriskevent-get.md
  api-reference/beta/api/subscription-delete.md
  api-reference/beta/resources/changenotification.md
  api-reference/beta/resources/changenotificationcollection.md
  api-reference/beta/resources/changenotificationencryptedcontent.md
  api-reference/beta/resources/directorysizequota.md
  api-reference/beta/resources/locatedriskevent.md
  api-reference/beta/resources/phone.md
  api-reference/beta/resources/privacyprofile.md
  api-reference/beta/resources/provisionedplan.md
  api-reference/beta/resources/resourcedata.md
  api-reference/beta/resources/verifieddomain.md
  api-reference/beta/resources/webhooks.md
  api-reference/v1.0/api/subscription-list.md
  api-reference/v1.0/api/subscription-post-subscriptions.md
  api-reference/v1.0/api/subscription-update.md
  api-reference/v1.0/resources/changenotification.md
  api-reference/v1.0/resources/changenotificationcollection.md
  api-reference/v1.0/resources/phone.md
  api-reference/v1.0/resources/privacyprofile.md
  api-reference/v1.0/resources/provisionedplan.md
  api-reference/v1.0/resources/resourcedata.md
  api-reference/v1.0/resources/verifieddomain.md
  api-reference/v1.0/resources/webhooks.md
Labels: area: azure/AAD, internal, ready to merge

#11842 2021 03 02 iswilli accessreviewscopeupdates
  api-reference/beta/api/accessreviewinstance-batchrecorddecisions.md
  api-reference/beta/api/accessreviewinstance-get.md
  api-reference/beta/api/accessreviewinstance-list.md
  api-reference/beta/api/accessreviewinstancedecisionitem-update.md
  api-reference/beta/resources/accessreviewinactiveusersqueryscope.md
  api-reference/beta/resources/accessreviewinstance.md
  api-reference/beta/resources/accessreviewinstancedecisionitem.md
  api-reference/beta/resources/accessreviewinstancedecisionitemresource.md
  api-reference/beta/resources/accessreviewqueryscope.md
  api-reference/beta/resources/accessreviewreviewerscope.md
  api-reference/beta/resources/accessreviews-root.md
  api-reference/beta/resources/accessreviewscheduledefinition.md
  api-reference/beta/resources/accessreviewschedulesettings.md
  api-reference/beta/resources/accessreviewscope.md
  api-reference/beta/resources/accessreviewsv2-root.md
  api-reference/beta/resources/principalresourcemembershipsscope.md
  api-reference/beta/resources/serviceprincipalidentity.md
  api-reference/beta/toc.yml
  api-reference/includes/accessreviews-disclaimer-v2.md
  api-reference/includes/accessreviews-disclaimer.md
  changelog/Microsoft.IdentityGovernance.AccessReviews.json
Labels: area: azure/AAD, content review complete, ready to merge, schema live

#11921 Consent requests APIs (Promote to GA)
  api-reference/v1.0/api/adminconsentrequestpolicy-get.md
  api-reference/v1.0/api/adminconsentrequestpolicy-update.md
  api-reference/v1.0/api/appconsentrequest-filterbycurrentuser.md
  api-reference/v1.0/api/appconsentrequest-get.md
  api-reference/v1.0/api/appconsentrequest-list.md
  api-reference/v1.0/api/userconsentrequest-filterbycurrentuser.md
  api-reference/v1.0/api/userconsentrequest-get.md
  api-reference/v1.0/api/userconsentrequest-list.md
  api-reference/v1.0/resources/accessreviewreviewerscope.md
  api-reference/v1.0/resources/adminconsentrequestpolicy.md
  api-reference/v1.0/resources/appconsentrequest.md
  api-reference/v1.0/resources/appconsentrequestscope.md
  api-reference/v1.0/resources/approval.md
  api-reference/v1.0/resources/approvalstage.md
  api-reference/v1.0/resources/azure-ad-overview.md
  api-reference/v1.0/resources/consentrequests-root.md
  api-reference/v1.0/resources/enums.md
  api-reference/v1.0/resources/userconsentrequest.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.DirectoryServices.json
Labels: area: azure/AAD, internal, ready to merge, schema live

#12093 Correct ms.prod values
  api-reference/beta/api/serviceprincipal-addtokensigningcertificate.md
  api-reference/beta/resources/selfsignedcertificate.md
  api-reference/v1.0/api/authentication-list-methods.md
  api-reference/v1.0/api/authenticationmethod-get.md
  api-reference/v1.0/api/emailauthenticationmethodconfiguration-delete.md
  api-reference/v1.0/api/emailauthenticationmethodconfiguration-get.md
  api-reference/v1.0/api/emailauthenticationmethodconfiguration-update.md
  api-reference/v1.0/api/fido2authenticationmethod-delete.md
  api-reference/v1.0/api/fido2authenticationmethod-get.md
  api-reference/v1.0/api/fido2authenticationmethod-list.md
  api-reference/v1.0/api/fido2authenticationmethodconfiguration-delete.md
  api-reference/v1.0/api/fido2authenticationmethodconfiguration-get.md
  api-reference/v1.0/api/fido2authenticationmethodconfiguration-update.md
  api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-delete.md
  api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-get.md
  api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-list.md
  api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-delete.md
  api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md
  api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-update.md
  api-reference/v1.0/api/windowshelloforbusinessauthenticationmethod-delete.md
  api-reference/v1.0/api/windowshelloforbusinessauthenticationmethod-get.md
  api-reference/v1.0/api/windowshelloforbusinessauthenticationmethod-list.md
  api-reference/v1.0/resources/authenticationmethod.md
  api-reference/v1.0/resources/authenticationmethodconfiguration.md
  api-reference/v1.0/resources/authenticationmethods-overview.md
  api-reference/v1.0/resources/authenticationmethodspolicies-overview.md
  api-reference/v1.0/resources/authenticationmethodtarget.md
  api-reference/v1.0/resources/emailauthenticationmethodconfiguration.md
  api-reference/v1.0/resources/fido2authenticationmethod.md
  api-reference/v1.0/resources/fido2authenticationmethodconfiguration.md
  api-reference/v1.0/resources/fido2keyrestrictions.md
  api-reference/v1.0/resources/microsoftauthenticatorauthenticationmethod.md
  api-reference/v1.0/resources/microsoftauthenticatorauthenticationmethodconfiguration.md
  api-reference/v1.0/resources/microsoftauthenticatorauthenticationmethodtarget.md
  api-reference/v1.0/resources/windowshelloforbusinessauthenticationmethod.md
Labels: internal, ready to merge

#12057 Various fixes to app role assignemnts
  api-reference/beta/api/group-delete-approleassignments.md
  api-reference/beta/api/group-list-approleassignments.md
  api-reference/beta/api/group-post-approleassignments.md
  api-reference/beta/api/serviceprincipal-delete-approleassignments.md
  api-reference/beta/api/serviceprincipal-list-approleassignments.md
  api-reference/beta/api/serviceprincipal-post-approleassignedto.md
  api-reference/beta/api/serviceprincipal-post-approleassignments.md
  api-reference/beta/api/user-delete-approleassignments.md
  api-reference/beta/api/user-list-approleassignments.md
  api-reference/beta/api/user-post-approleassignments.md
  api-reference/v1.0/api/group-delete-approleassignments.md
  api-reference/v1.0/api/group-post-approleassignments.md
  api-reference/v1.0/api/serviceprincipal-list-approleassignments.md
  api-reference/v1.0/api/serviceprincipal-post-approleassignedto.md
  api-reference/v1.0/api/serviceprincipal-post-approleassignments.md
  api-reference/v1.0/api/user-delete-approleassignments.md
  api-reference/v1.0/api/user-list-approleassignments.md
  api-reference/v1.0/api/user-post-approleassignments.md
  api-reference/v1.0/resources/approleassignment.md
Labels: area: app model, area: azure/AAD, internal, ready to merge
