Repository microsoftgraph/microsoft-graph-docs, pull requests merged in 2021-05, with the labels that each got.

#12554 Update what's new for the last 2 weeks.
  CONTRIBUTING.md
  concepts/whats-new-overview.md
Labels: do not merge, internal

#12564 Refresh "what's new".
  CONTRIBUTING.md
  concepts/whats-new-overview.md
Labels: do not merge, internal

#12585 Update MSAL2Provider docs
  concepts/toolkit/get-started/use-toolkit-with-angular.md
  concepts/toolkit/providers/msal2.md
Labels: do not merge, internal

#12581 Minor fixes to user resource
  api-reference/beta/resources/user.md
  api-reference/v1.0/resources/user.md
Labels: internal, ready to merge

#12572 Update authenticationflowspolicy.md
  api-reference/beta/resources/authenticationflowspolicy.md
Labels: external

#12571 Update authenticationflowspolicy.md
  api-reference/v1.0/resources/authenticationflowspolicy.md
Labels: external

#12569 Fix List and Get secure score control profile links
  api-reference/v1.0/resources/security-api-overview.md
Labels: external

#12336 Add guestUserRoleId property to v1.0
  api-reference/beta/api/authorizationpolicy-update.md
  api-reference/beta/resources/authorizationpolicy.md
  api-reference/v1.0/api/authorizationpolicy-update.md
  api-reference/v1.0/resources/authorizationpolicy.md
  changelog/Microsoft.DirectoryServices.json
Labels: internal, ready to merge

#12563 Update Assignments docs to reflect AppOnly is now GA'ed
  api-reference/beta/api/educationassignment-get-rubric.md
  api-reference/beta/api/educationassignment-get.md
  api-reference/beta/api/educationassignment-list-categories.md
  api-reference/beta/api/educationassignment-list-resources.md
  api-reference/beta/api/educationassignment-list-submissions.md
  api-reference/beta/api/educationassignmentdefaults-get.md
  api-reference/beta/api/educationassignmentresource-get.md
  api-reference/beta/api/educationassignmentsettings-get.md
  api-reference/beta/api/educationcategory-get.md
  api-reference/beta/api/educationclass-list-assignments.md
  api-reference/beta/api/educationclass-list-categories.md
  api-reference/beta/api/educationrubric-get.md
  api-reference/beta/api/educationsubmission-get.md
  api-reference/beta/api/educationsubmission-list-outcomes.md
  api-reference/beta/api/educationsubmission-list-resources.md
  api-reference/beta/api/educationsubmission-list-submittedresources.md
  api-reference/beta/api/educationsubmissionresource-get.md
  api-reference/beta/api/educationsubmittedsubmissionresource-get.md
  changelog/Microsoft.EducationAssignment.json
  concepts/permissions-reference.md
Labels: internal, ready to merge

#12565 Add note on eventual consistency for oauth2PermissionGrants
  api-reference/beta/api/oauth2permissiongrant-list.md
  api-reference/beta/api/user-list-oauth2permissiongrants.md
  api-reference/v1.0/api/oauth2permissiongrant-list.md
  api-reference/v1.0/api/user-list-oauth2permissiongrants.md
Labels: area: app model, area: azure/AAD, internal, ready to merge

#12269 Update educationroot-post-schools.md
  api-reference/v1.0/api/educationroot-post-schools.md
Labels: internal, ready to merge

#12588 Merge to publish.
  api-reference/beta/api/authorizationpolicy-update.md
  api-reference/beta/api/educationassignment-get-rubric.md
  api-reference/beta/api/educationassignment-get.md
  api-reference/beta/api/educationassignment-list-categories.md
  api-reference/beta/api/educationassignment-list-resources.md
  api-reference/beta/api/educationassignment-list-submissions.md
  api-reference/beta/api/educationassignmentdefaults-get.md
  api-reference/beta/api/educationassignmentresource-get.md
  api-reference/beta/api/educationassignmentsettings-get.md
  api-reference/beta/api/educationcategory-get.md
  api-reference/beta/api/educationclass-list-assignments.md
  api-reference/beta/api/educationclass-list-categories.md
  api-reference/beta/api/educationrubric-get.md
  api-reference/beta/api/educationsubmission-get.md
  api-reference/beta/api/educationsubmission-list-outcomes.md
  api-reference/beta/api/educationsubmission-list-resources.md
  api-reference/beta/api/educationsubmission-list-submittedresources.md
  api-reference/beta/api/educationsubmissionresource-get.md
  api-reference/beta/api/educationsubmittedsubmissionresource-get.md
  api-reference/beta/api/oauth2permissiongrant-list.md
  api-reference/beta/api/user-list-oauth2permissiongrants.md
  api-reference/beta/resources/authenticationflowspolicy.md
  api-reference/beta/resources/authorizationpolicy.md
  api-reference/beta/resources/user.md
  api-reference/v1.0/api/authorizationpolicy-update.md
  api-reference/v1.0/api/educationroot-post-schools.md
  api-reference/v1.0/api/oauth2permissiongrant-list.md
  api-reference/v1.0/api/user-list-oauth2permissiongrants.md
  api-reference/v1.0/resources/authenticationflowspolicy.md
  api-reference/v1.0/resources/authorizationpolicy.md
  api-reference/v1.0/resources/security-api-overview.md
  api-reference/v1.0/resources/user.md
  changelog/Microsoft.DirectoryServices.json
  changelog/Microsoft.EducationAssignment.json
  concepts/permissions-reference.md
Labels: internal

#12599 Updated date and scenario
  api-reference/beta/resources/emailauthenticationmethodconfiguration.md
Labels: internal

#12600 Update "true" to "enabled"
  api-reference/beta/api/emailauthenticationmethodconfiguration-get.md
Labels: internal

#12601 Updated "false" to "disabled"
  api-reference/beta/api/emailauthenticationmethodconfiguration-update.md
Labels: internal

#12602 Updated scenario and date for v1
  api-reference/v1.0/resources/emailauthenticationmethodconfiguration.md
Labels: internal

#12603 Updated "True" to "enabled"
  api-reference/v1.0/api/emailauthenticationmethodconfiguration-get.md
Labels: internal

#12593 Update authenticationflowspolicy-get.md
  api-reference/beta/api/authenticationflowspolicy-get.md
Labels: external

#11900 Add lastSeenDateTime property for v1.0 version
  api-reference/v1.0/resources/printer.md
  changelog/Microsoft.PrintService.json
Labels: area: universal print, internal, ready to merge

#12592 Minor fixes to docs
  api-reference/beta/api/user-update.md
  api-reference/beta/resources/serviceprincipal.md
  api-reference/beta/resources/user.md
  api-reference/v1.0/api/user-update.md
  api-reference/v1.0/resources/serviceprincipal.md
  api-reference/v1.0/resources/user.md
Labels: internal, ready to merge

#12107 Access Review History Defintions
  api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md
  api-reference/beta/api/accessreviewhistorydefinition-get.md
  api-reference/beta/api/accessreviewhistorydefinition-list.md
  api-reference/beta/api/accessreviewhistorydefinition-post.md
  api-reference/beta/resources/accessreviewhistorydefinition.md
  api-reference/beta/toc.yml
  changelog/Microsoft.IdentityGovernance.AccessReviews.json
Labels: area: azure/AAD, internal, ready to merge

#12559 Update authenticationmethods-usage-insights-overview.md
  api-reference/beta/resources/authenticationmethods-usage-insights-overview.md
Labels: external

#12149 Update tokenlifetimepolicy.md
  api-reference/v1.0/resources/tokenlifetimepolicy.md
Labels: internal, ready to merge

#12611 Update signin resource & methods
  api-reference/beta/api/signin-get.md
  api-reference/beta/api/signin-list.md
  api-reference/beta/resources/signin.md
  api-reference/v1.0/api/signin-get.md
  api-reference/v1.0/api/signin-list.md
  api-reference/v1.0/resources/signin.md
Labels: internal, ready to merge

#12615 Various doc fixes
  api-reference/beta/api/bitlocker-list-recoverykeys.md
  api-reference/beta/api/bitlockerrecoverykey-get.md
  api-reference/beta/api/rbacapplication-list-roleassignments.md
  api-reference/beta/api/rbacapplication-list-roledefinitions.md
  api-reference/beta/resources/unifiedroleassignment.md
  api-reference/beta/resources/unifiedroleassignmentmultiple.md
  api-reference/beta/resources/unifiedroledefinition.md
Labels: internal, ready to merge

#12616 Turn off snippet generation, known SDK issue, closes #10280
  api-reference/v1.0/api/directory-deleteditems-list.md
Labels: internal, ready to merge

#12622 Update PATCH OnlineMeeting Document
  api-reference/beta/api/onlinemeeting-update.md
  api-reference/v1.0/api/onlinemeeting-update.md
Labels: content review complete, internal, ready to merge

#12609 Update group-update.md
  api-reference/beta/api/group-update.md
Labels: external

#12053 Provisioning logs API move to v1.0
  api-reference/v1.0/api/provisioningobjectsummary-list.md
  api-reference/v1.0/resources/detailsinfo.md
  api-reference/v1.0/resources/enums.md
  api-reference/v1.0/resources/initiator.md
  api-reference/v1.0/resources/provisionedidentity.md
  api-reference/v1.0/resources/provisioningerrorInfo.md
  api-reference/v1.0/resources/provisioningobjectsummary.md
  api-reference/v1.0/resources/provisioningserviceprincipal.md
  api-reference/v1.0/resources/provisioningstatusinfo.md
  api-reference/v1.0/resources/provisioningstep.md
  api-reference/v1.0/resources/provisioningsystem.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.AAD.Reporting.json
Labels: area: azure/AAD, internal, ready to merge

#12443 Add adJoinCheckAccessDenied enum member to cloudPcOnPremisesConnectio…
  api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: content review complete, internal, ready to merge

#12607 [mgt] mgt-person css property cursor
  concepts/toolkit/components/person.md
Labels: do not merge, internal

#12625 Revert "Revert "Updates instructions to use MGT with SPFx""
  concepts/toc.yml
  concepts/toolkit/get-started/build-a-sharepoint-web-part.md
  concepts/toolkit/get-started/mgt-spfx.md
  concepts/toolkit/get-started/overview.md
  concepts/toolkit/providers/sharepoint.md
Labels: internal

#12627 Update overview.md
  concepts/toolkit/get-started/overview.md
Labels: external

#12626 Update authenticationflowspolicy-update.md
  api-reference/beta/api/authenticationflowspolicy-update.md
Labels: external

#12402 Add one enum member to cloudPcOnPremisesConnectionHealthCheckErrorType
  api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: content review complete, internal, ready to merge

#12227 Adds information about caching in MGT components
  concepts/toolkit/components/agenda.md
  concepts/toolkit/components/get.md
  concepts/toolkit/components/login.md
  concepts/toolkit/components/people-picker.md
  concepts/toolkit/components/people.md
  concepts/toolkit/components/person-card.md
  concepts/toolkit/components/person.md
  concepts/toolkit/components/tasks.md
  concepts/toolkit/components/teams-channel-picker.md
  concepts/toolkit/components/todo.md
  concepts/toolkit/customize-components/cache.md
Labels: area: toolkit, internal, ready to merge

#12617 Fixes #12075
  api-reference/beta/api/serviceprincipal-addtokensigningcertificate.md
  api-reference/beta/resources/selfsignedcertificate.md
Labels: internal, ready to merge

#12618 Update for Policy.ReadWrite.AccessReview
  concepts/permissions-reference.md
Labels: area: azure/AAD, ready to merge

#12636 Fix #12307
  concepts/auth-limit-mailbox-access.md
Labels: internal, ready to merge

#12639 Update organizationalbrandingproperties.md
  api-reference/beta/resources/organizationalbrandingproperties.md
  api-reference/v1.0/resources/organizationalbrandingproperties.md
Labels: internal, ready to merge

#12658 accessreviewhistorydefinition-create name change
  api-reference/beta/toc.yml
Labels: internal, ready to merge

#12650 Update microsoftauthenticatorauthenticationmethod.md
  api-reference/beta/resources/microsoftauthenticatorauthenticationmethod.md
Labels: external

#11361 Doc updates for My Access - new PR incorporating all feedback from previous reviews
  api-reference/beta/api/accesspackage-filterbycurrentuser.md
  api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md
  api-reference/beta/api/accesspackageassignmentpolicy-update.md
  api-reference/beta/api/accesspackageassignmentrequest-cancel.md
  api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md
  api-reference/beta/api/accesspackageassignmentrequest-post.md
  api-reference/beta/api/accesspackageresourceenvironment-get.md
  api-reference/beta/api/accesspackageresourceenvironment-list.md
  api-reference/beta/resources/accesspackage-accesspackagefilterbycurrentuseroptions.md
  api-reference/beta/resources/accesspackage.md
  api-reference/beta/resources/accesspackageassignment-accesspackageassignmentfilterbycurrentuseroptions.md
  api-reference/beta/resources/accesspackageassignment.md
  api-reference/beta/resources/accesspackageassignmentrequest-accesspackageassignmentrequestfilterbycurrentuseroptions.md
  api-reference/beta/resources/accesspackageassignmentrequest.md
  api-reference/beta/resources/entitlementmanagement-root.md
  api-reference/beta/toc.yml
  changelog/Microsoft.DirectoryServices.json
Labels: area: azure/AAD, internal, ready to merge, schema live

#12666 Update microsoftauthenticatorauthenticationmethod-get.md
  api-reference/beta/api/microsoftauthenticatorauthenticationmethod-get.md
Labels: external

#12691 minor corrections
  concepts/application-saml-sso-configure-api.md
  concepts/images/application-saml-sso-configure-api/accept-permissions.PNG
  concepts/images/application-saml-sso-configure-api/select-permissions.PNG
Labels: area: azure/AAD, internal, ready to merge

#12685 Update microsoftauthenticatorauthenticationmethod-delete.md
  api-reference/beta/api/microsoftauthenticatorauthenticationmethod-delete.md
Labels: external

#12346 update Permission.md to role definition
  api-reference/beta/resources/permission.md
  api-reference/v1.0/resources/permission.md
Labels: content review, internal, ready to merge

#12608 2021-05-05 Auth Methods Updates
  api-reference/beta/resources/authenticationmethod.md
  api-reference/beta/resources/authenticationmethods-overview.md
  api-reference/beta/resources/fido2authenticationmethod.md
  api-reference/beta/toc.yml
  api-reference/v1.0/resources/authenticationmethod.md
  api-reference/v1.0/resources/authenticationmethods-overview.md
  api-reference/v1.0/resources/fido2authenticationmethod.md
Labels: ready to merge

#12696 Merge to publish.
  api-reference/beta/api/microsoftauthenticatorauthenticationmethod-delete.md
  api-reference/beta/api/microsoftauthenticatorauthenticationmethod-get.md
  api-reference/beta/api/microsoftauthenticatorauthenticationmethod-list.md
  api-reference/beta/api/user-get.md
  api-reference/beta/resources/authenticationmethod.md
  api-reference/beta/resources/authenticationmethods-overview.md
  api-reference/beta/resources/fido2authenticationmethod.md
  api-reference/beta/resources/permission.md
  api-reference/beta/toc.yml
  api-reference/v1.0/resources/authenticationmethod.md
  api-reference/v1.0/resources/authenticationmethods-overview.md
  api-reference/v1.0/resources/fido2authenticationmethod.md
  api-reference/v1.0/resources/permission.md
  concepts/application-saml-sso-configure-api.md
  concepts/images/application-saml-sso-configure-api/accept-permissions.PNG
  concepts/images/application-saml-sso-configure-api/select-permissions.PNG
Labels: internal

#12589 Add the documentation for the allow-any-email attribute in the people picker component
  concepts/toolkit/components/people-picker.md
Labels: area: toolkit, external

#12662 Add default-selected-group-ids attribute for People-Picker component
  concepts/toolkit/components/people-picker.md
Labels: do not merge, internal

#12700 Update userflowlanguageconfiguration.md
  api-reference/beta/resources/userflowlanguageconfiguration.md
Labels: external

#12396 Print API large file upload code samples
  concepts/upload-data-to-upload-session.md
Labels: area: universal print, internal, ready to merge

#12657 Add setUpResourcesFolder
  api-reference/beta/api/educationsubmission-get.md
  api-reference/beta/api/educationsubmission-setupResourcesFolder.md
  api-reference/beta/toc.yml
  changelog/Microsoft.EducationAssignment.json
Labels: Build21, internal, ready to merge

#12698 - adds azure identity as dependency for azure sdk installation
  concepts/sdks/sdk-installation.md
Labels: area: sample code, internal, ready to merge

#12707 Updated the API permissions to include AuditLogs.Read.All and fixed o…
  api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md
  api-reference/beta/api/authenticationmethodsroot-usersregisteredbymethod.md
Labels: area: azure/AAD, internal, ready to merge

#12697 Add links to choosing auth providers and samples using certificates
  concepts/auth/auth-concepts.md
  concepts/auth/index.yml
  concepts/sdks/choose-authentication-providers.md
Labels: internal, ready to merge

#12623 Clarify that assignedLicenses includes inherited.
  api-reference/beta/resources/user.md
  api-reference/v1.0/resources/user.md
Labels: external

#12690 #12688 Update documentation for createdDateTime
  api-reference/beta/resources/user.md
  api-reference/v1.0/resources/user.md
Labels: external, review requested

#12628 [CloudPC]Add supported app-only permissions for APIs
  api-reference/beta/api/cloudpc-get.md
  api-reference/beta/api/cloudpc-reprovision.md
  api-reference/beta/api/cloudpcdeviceimage-delete.md
  api-reference/beta/api/cloudpcdeviceimage-get.md
  api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md
  api-reference/beta/api/cloudpconpremisesconnection-get.md
  api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md
  api-reference/beta/api/cloudpcprovisioningpolicy-assign.md
  api-reference/beta/api/cloudpcprovisioningpolicy-delete.md
  api-reference/beta/api/cloudpcprovisioningpolicy-get.md
  api-reference/beta/api/cloudpcprovisioningpolicy-update.md
  api-reference/beta/api/virtualendpoint-list-cloudpcs.md
  api-reference/beta/api/virtualendpoint-list-deviceimages.md
  api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md
  api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md
  api-reference/beta/api/virtualendpoint-post-deviceimages.md
  api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: content review, do not merge, internal

#12683 Fix query parameters for Export API docs
  api-reference/beta/api/channel-getallmessages.md
Labels: Build21, internal, ready to merge

#11743 Added Policy.ReadWrite.MobilityManagement delegated permission
  changelog/Microsoft.MobilityService.json
  concepts/permissions-reference.md
Labels: ready to merge

#12724 Merge to publish.
  api-reference/beta/api/channel-getallmessages.md
  api-reference/beta/api/cloudpc-get.md
  api-reference/beta/api/cloudpc-reprovision.md
  api-reference/beta/api/cloudpcdeviceimage-delete.md
  api-reference/beta/api/cloudpcdeviceimage-get.md
  api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md
  api-reference/beta/api/cloudpconpremisesconnection-get.md
  api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md
  api-reference/beta/api/cloudpcprovisioningpolicy-assign.md
  api-reference/beta/api/cloudpcprovisioningpolicy-delete.md
  api-reference/beta/api/cloudpcprovisioningpolicy-get.md
  api-reference/beta/api/cloudpcprovisioningpolicy-update.md
  api-reference/beta/api/virtualendpoint-list-cloudpcs.md
  api-reference/beta/api/virtualendpoint-list-deviceimages.md
  api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md
  api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md
  api-reference/beta/api/virtualendpoint-post-deviceimages.md
  api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md
  changelog/Microsoft.CloudManagedDesktop.json
  changelog/Microsoft.MobilityService.json
  concepts/permissions-reference.md
Labels: internal

#12734 Highlight what's new in the last couple of weeks.
  api-reference/beta/api/educationsubmission-get.md
  api-reference/beta/api/educationsubmission-setupResourcesFolder.md
  api-reference/beta/resources/educationsubmission.md
  api-reference/beta/toc.yml
  changelog/Microsoft.CloudManagedDesktop.json
  changelog/Microsoft.DirectoryServices.json
  changelog/Microsoft.EducationAssignment.json
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: internal

#12735 Refresh what's new in Microsoft Graph.
  api-reference/beta/api/educationsubmission-get.md
  api-reference/beta/api/educationsubmission-setupResourcesFolder.md
  api-reference/beta/resources/educationsubmission.md
  api-reference/beta/toc.yml
  changelog/Microsoft.CloudManagedDesktop.json
  changelog/Microsoft.DirectoryServices.json
  changelog/Microsoft.EducationAssignment.json
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: internal

#12739 Anandab msft change notification for channel and teams
  api-reference/beta/api/subscription-delete.md
  api-reference/beta/api/subscription-get.md
  api-reference/beta/api/subscription-post-subscriptions.md
  api-reference/beta/api/subscription-update.md
  api-reference/beta/resources/subscription.md
  api-reference/beta/resources/webhooks.md
  changelog/Microsoft.Teams.Core.json
  concepts/teams-changenotifications-team-and-channels.md
  concepts/teams-changenotifications-teamMembership.md
  concepts/toc.yml
  concepts/webhooks.md
Labels: internal

#12744 Anandab msft support for upn in urls
  api-reference/beta/api/chat-get-members.md
  api-reference/beta/api/chat-get.md
  api-reference/beta/api/chat-list-members.md
  api-reference/beta/api/chat-list-messages.md
  api-reference/beta/api/chat-list.md
  api-reference/beta/api/chatmessage-get.md
  api-reference/beta/api/chatmessage-list-hostedcontents.md
  api-reference/beta/api/chatmessagehostedcontent-get.md
  api-reference/beta/api/chats-getallmessages.md
  api-reference/beta/api/user-list-joinedteams.md
  api-reference/beta/api/userscopeteamsappinstallation-get-chat.md
  api-reference/beta/api/userteamwork-delete-installedapps.md
  api-reference/beta/api/userteamwork-get-installedapps.md
  api-reference/beta/api/userteamwork-list-installedapps.md
  api-reference/beta/api/userteamwork-post-installedapps.md
  api-reference/beta/api/userteamwork-sendactivitynotification.md
  api-reference/beta/api/userteamwork-teamsappinstallation-upgrade.md
  changelog/Microsoft.Teams.Core.json
Labels: internal

#12752 Shared channel api docs
  api-reference/beta/api/channel-delete-members.md
  api-reference/beta/api/channel-get-filesfolder.md
  api-reference/beta/api/channel-get-members.md
  api-reference/beta/api/channel-list-members.md
  api-reference/beta/api/channel-list.md
  api-reference/beta/api/channel-post-members.md
  api-reference/beta/api/channel-post.md
  api-reference/beta/api/channel-update-members.md
  api-reference/beta/api/user-list-joinedteams.md
  api-reference/beta/resources/channel.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/teamsasyncoperationtype.md
  changelog/Microsoft.Teams.Core.json
Labels: internal

#10539 AuthenticationContextClassReferenceDocs
  api-reference/beta/api/authenticationcontextclassreference-get.md
  api-reference/beta/api/authenticationcontextclassreference-update.md
  api-reference/beta/api/conditionalaccessroot-list-authenticationcontextclassreferences.md
  api-reference/beta/api/conditionalaccessroot-post-authenticationcontextclassreferences.md
  api-reference/beta/resources/authenticationcontextclassreference.md
  api-reference/beta/resources/conditionalaccessapplications.md
  api-reference/beta/resources/conditionalaccesspolicy.md
  api-reference/beta/resources/conditionalaccessroot.md
  api-reference/beta/toc.yml
  changelog/Microsoft.DirectoryServices.json
Labels: area: azure/AAD, internal, ready to merge

#12083 New API for AAD mobility management policies
  api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md
  api-reference/beta/api/mobileappmanagementpolicies-get.md
  api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md
  api-reference/beta/api/mobileappmanagementpolicies-list.md
  api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md
  api-reference/beta/api/mobileappmanagementpolicies-update.md
  api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md
  api-reference/beta/api/mobiledevicemanagementpolicies-get.md
  api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md
  api-reference/beta/api/mobiledevicemanagementpolicies-list.md
  api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md
  api-reference/beta/api/mobiledevicemanagementpolicies-update.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/mobilitymanagementpolicy.md
  api-reference/beta/toc.yml
  changelog/Microsoft.MobilityService.json
Labels: Build21, area: azure/AAD, ready to merge

#12715 Update links from UserVoice to new feature request platform
  api-reference/beta/resources/teams-api-overview.md
  api-reference/v1.0/resources/teams-api-overview.md
  concepts/data-connect-datasets.md
  concepts/data-connect-policies.md
  concepts/data-connect-tips.md
  concepts/sdks/choose-authentication-providers.md
  concepts/sdks/sdks-overview.md
  concepts/universal-print-concept-overview.md
Labels: internal, ready to merge

#12738 Fix build warnings for Identity docs
  api-reference/beta/api/b2cidentityuserflow-put-apiconnectorconfiguration.md
  api-reference/beta/api/b2xidentityuserflow-put-apiconnectorconfiguration.md
  api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md
  api-reference/beta/api/identityproviderbase-post-identityproviders.md
  api-reference/beta/api/onpremisespublishingprofile-update.md
  api-reference/beta/resources/agreementfiledata.md
  api-reference/beta/resources/alternativeSecurityId.md
  api-reference/beta/resources/anonymousipriskevent.md
  api-reference/beta/resources/assignedlicense.md
  api-reference/beta/resources/command.md
  api-reference/beta/resources/directory.md
  api-reference/beta/resources/entity.md
  api-reference/beta/resources/implicitgrantsettings.md
  api-reference/beta/resources/impossibletravelriskevent.md
  api-reference/beta/resources/invokeuserflowlistener.md
  api-reference/beta/resources/leakedcredentialsriskevent.md
  api-reference/beta/resources/licenseAssignmentState.md
  api-reference/beta/resources/licensedetails.md
  api-reference/beta/resources/malwareriskevent.md
  api-reference/beta/resources/oauth2permissiongrant.md
  api-reference/beta/resources/opentypeextension.md
  api-reference/beta/resources/organizationalbrandingproperties.md
  api-reference/beta/resources/privilegedidentitymanagement-root.md
  api-reference/beta/resources/provisioningerrorinfo.md
  api-reference/beta/resources/serviceprincipal.md
  api-reference/beta/resources/statusdetails.md
  api-reference/beta/resources/subscription.md
  api-reference/beta/resources/suspiciousipriskevent.md
  api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md
  api-reference/beta/resources/unifiedroleeligibilityschedulerequest.md
  api-reference/beta/resources/userflowlanguageconfiguration.md
  api-reference/v1.0/api/b2xidentityuserflow-put-apiconnectorconfiguration.md
  api-reference/v1.0/api/organizationalbrandingproperties-update.md
  api-reference/v1.0/resources/alternativeSecurityId.md
  api-reference/v1.0/resources/assignedlicense.md
  api-reference/v1.0/resources/azure-ad-auditlog-overview.md
  api-reference/v1.0/resources/azure-ad-overview.md
  api-reference/v1.0/resources/entity.md
  api-reference/v1.0/resources/extension.md
  api-reference/v1.0/resources/invitation.md
  api-reference/v1.0/resources/licensedetails.md
  api-reference/v1.0/resources/opentypeextension.md
  api-reference/v1.0/resources/organizationalbrandingproperties.md
  api-reference/v1.0/resources/patternedrecurrence.md
  api-reference/v1.0/resources/provisioningerrorInfo.md
  api-reference/v1.0/resources/recurrencepattern.md
  api-reference/v1.0/resources/recurrencerange.md
  api-reference/v1.0/resources/settingtemplatevalue.md
  api-reference/v1.0/resources/settingvalue.md
  api-reference/v1.0/resources/subscription.md
  api-reference/v1.0/resources/userflowlanguageconfiguration.md
  concepts/add-properties-profilecard.md
  concepts/application-saml-sso-configure-api.md
  concepts/azuread-identity-access-management-concept-overview.md
  concepts/migrate-azure-ad-graph-planning-checklist.md
  concepts/teams-concept-overview.md
  concepts/webhooks-with-resource-data.md
Labels: internal, ready to merge

#12743 - fixes java paging sample
  concepts/sdks/paging.md
Labels: bug: sample, internal, ready to merge

#12750 Correct owner
  api-reference/v1.0/api/user-checkmembergroups.md
  api-reference/v1.0/api/user-list-memberof.md
Labels: internal, ready to merge

#12747 Add MGT toolkit learning path
  concepts/tutorials.yml
Labels: internal

#12761 Update userflowlanguageconfiguration-list-defaultpages.md
  api-reference/beta/api/userflowlanguageconfiguration-list-defaultpages.md
Labels: external

#12760 Update userflowlanguageconfiguration-delete.md
  api-reference/beta/api/userflowlanguageconfiguration-delete.md
Labels: external

#12768 Adding notes for PSTN related docs to address common customer questions
  api-reference/beta/api/application-post-calls.md
  api-reference/beta/api/call-redirect.md
  api-reference/beta/api/call-transfer.md
  api-reference/beta/api/participant-invite.md
  api-reference/v1.0/api/application-post-calls.md
  api-reference/v1.0/api/call-redirect.md
  api-reference/v1.0/api/call-transfer.md
  api-reference/v1.0/api/participant-invite.md
Labels: content review, internal, ready to merge

#12773 Merge to publish.
  api-reference/beta/api/userflowlanguageconfiguration-delete.md
  api-reference/beta/api/userflowlanguageconfiguration-list-defaultpages.md
  concepts/tutorials.yml
Labels: internal

#12751 Added header information to paging doc
  concepts/sdks/large-file-upload.md
  concepts/sdks/paging.md
Labels: internal, ready to merge

#12781 Update userflowlanguageconfiguration-list-overridespages.md
  api-reference/beta/api/userflowlanguageconfiguration-list-overridespages.md
Labels: external

#12776 Fix a typo for cloud-communications-get-started.md
  concepts/cloud-communications-get-started.md
Labels: external

#9391 Add an FAQ for AAD Graph Migration
  concepts/migrate-azure-ad-graph-overview.md
  concepts/toc.yml
Labels: ready to merge

#12447 accessReviewScheduleDefinition docs refresh
  api-reference/beta/api/accessreviewscheduledefinition-create.md
  api-reference/beta/api/accessreviewscheduledefinition-get.md
  api-reference/beta/api/accessreviewscheduledefinition-list.md
  api-reference/beta/api/accessreviewscheduledefinition-post.md
  api-reference/beta/api/accessreviewscheduledefinition-update.md
  api-reference/beta/resources/accessreview.md
  api-reference/beta/resources/accessreviewapplyaction.md
  api-reference/beta/resources/accessreviewinactiveusersqueryscope.md
  api-reference/beta/resources/accessreviewqueryscope.md
  api-reference/beta/resources/accessreviewreviewerscope.md
  api-reference/beta/resources/accessreviews-root.md
  api-reference/beta/resources/accessreviewscheduledefinition.md
  api-reference/beta/resources/accessreviewschedulesettings.md
  api-reference/beta/resources/accessreviewscope.md
  api-reference/beta/resources/accessreviewsv2-root.md
  api-reference/beta/resources/disableanddeleteuserapplyaction.md
  api-reference/beta/resources/patternedrecurrence.md
  api-reference/beta/resources/principalresourcemembershipsscope.md
  api-reference/beta/resources/removeaccessapplyaction.md
  api-reference/beta/toc.yml
  api-reference/includes/accessreviews-disclaimer-v2.md
  concepts/accessreviews-reviewers-concept.md
  concepts/accessreviews-scope-concept.md
Labels: area: azure/AAD, content review complete, internal, ready to merge

#12758 Update user-get.md
  api-reference/beta/resources/user.md
  api-reference/v1.0/api/user-get.md
Labels: area: azure/AAD, content review complete, internal, ready to merge

#12731 Added GetMeetingByJoinWebUrl to V1
  api-reference/beta/api/onlinemeeting-get.md
  api-reference/v1.0/api/onlinemeeting-get.md
  changelog/Microsoft.Skype.Calling.json
Labels: internal, ready to merge

#8871 Add parent property to informationProtectionLabel entity
  api-reference/beta/api/informationprotectionlabel-extractlabel.md
  api-reference/beta/api/informationprotectionlabel-get.md
  api-reference/beta/api/informationprotectionpolicy-list-labels.md
  api-reference/beta/resources/informationprotectionlabel.md
  api-reference/beta/resources/labeldetails.md
  api-reference/beta/resources/parentlabeldetails.md
  changelog/Microsoft.ThreatAssessment.json
  concepts/changelog.md
Labels: changelog, content review, ready to merge, schema live

#12560 Microsoft Graph Toolkit 2.2 Release
  concepts/toc.yml
  concepts/toolkit/components/file-list.md
  concepts/toolkit/components/file.md
  concepts/toolkit/components/people-picker.md
  concepts/toolkit/components/people.md
  concepts/toolkit/components/person.md
  concepts/toolkit/components/teams-channel-picker.md
  concepts/toolkit/customize-components/cache.md
  concepts/toolkit/customize-components/localization.md
  concepts/toolkit/get-started/add-aad-app-registration.md
  concepts/toolkit/get-started/build-a-sharepoint-web-part.md
  concepts/toolkit/get-started/build-a-web-app.md
  concepts/toolkit/get-started/mgt-spfx.md
  concepts/toolkit/get-started/overview.md
  concepts/toolkit/get-started/use-toolkit-with-angular.md
  concepts/toolkit/get-started/use-toolkit-with-react.md
  concepts/toolkit/overview.md
  concepts/toolkit/providers/msal.md
  concepts/toolkit/providers/msal2.md
  concepts/toolkit/providers/providers.md
  concepts/toolkit/providers/sharepoint.md
Labels: Build21, area: toolkit, internal, ready to merge

#12785 [mgt] mgt-person-card document event "expanded"
  concepts/toolkit/components/person-card.md
Labels: area: toolkit, external

#12813 Updated mgt-spfx docs with React considerations and other minor doc updates
  concepts/toolkit/components/file-list.md
  concepts/toolkit/components/person-card.md
  concepts/toolkit/get-started/build-a-sharepoint-web-part.md
  concepts/toolkit/get-started/build-a-web-app.md
  concepts/toolkit/get-started/mgt-spfx.md
  concepts/toolkit/get-started/overview.md
  concepts/toolkit/overview.md
  concepts/toolkit/providers/sharepoint.md
Labels: internal, ready to merge

#12800 Update accessReviewHistoryDefinition
  api-reference/beta/api/accessreviewhistorydefinition-post.md
Labels: internal, ready to merge

#12802 Document missing AuditLog.Read.All permission
  concepts/permissions-reference.md
Labels: area: azure/AAD, internal, ready to merge

#12804 Add note for license requirement & permissions
  api-reference/beta/api/user-list.md
Labels: area: azure/AAD, area: users, internal, ready to merge

#12820 Merge to publish.
  api-reference/beta/api/accessreviewhistorydefinition-post.md
  api-reference/beta/api/user-list.md
  concepts/permissions-reference.md
  concepts/toolkit/components/file-list.md
  concepts/toolkit/components/person-card.md
  concepts/toolkit/get-started/build-a-sharepoint-web-part.md
  concepts/toolkit/get-started/build-a-web-app.md
  concepts/toolkit/get-started/mgt-spfx.md
  concepts/toolkit/get-started/overview.md
  concepts/toolkit/overview.md
  concepts/toolkit/providers/sharepoint.md
Labels: internal

#12817 [mgt] mgt-people-picker selectGroupsById feature
  concepts/toolkit/components/people-picker.md
Labels: external

#12835 Updating image.
  concepts/images/microsoft-graph-dataconnect-connectors-enhance.png
Labels: internal

#12795 EDU assignments: follow up on prior deprecations and additional beta updates
  api-reference/beta/api/educationassignment-get.md
  api-reference/beta/api/educationassignment-getresourcesfolderurl.md
  api-reference/beta/api/educationassignment-setupresourcesfolder.md
  api-reference/beta/api/educationassignment-update.md
  api-reference/beta/resources/educationassignment.md
  api-reference/beta/resources/educationformresource.md
  api-reference/beta/resources/educationmakecoderesource.md
  api-reference/beta/resources/educationonenoteresource.md
  api-reference/beta/resources/educationsubmission.md
  api-reference/beta/toc.yml
  changelog/Microsoft.EducationAssignment.json
  concepts/whats-new-overview.md
Labels: content review complete, internal, ready to merge

#12807 Update userflowlanguagepage.md
  api-reference/beta/resources/userflowlanguagepage.md
Labels: external

#12703 Hidden Mail Folders - GA Release - Doc Updates
  api-reference/beta/api/mailfolder-list-childfolders.md
  api-reference/beta/api/mailfolder-post-childfolders.md
  api-reference/beta/resources/mailfolder.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/mailfolder-get.md
  api-reference/v1.0/api/mailfolder-list-childfolders.md
  api-reference/v1.0/api/mailfolder-post-childfolders.md
  api-reference/v1.0/api/user-list-mailfolders.md
  api-reference/v1.0/api/user-post-mailfolders.md
  api-reference/v1.0/resources/mailfolder.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.Exchange.json
Labels: Build21, content review, internal

#12837 Published PR 12703 GA hidden mail folders.
  api-reference/beta/api/mailfolder-list-childfolders.md
  api-reference/beta/api/mailfolder-post-childfolders.md
  api-reference/beta/resources/mailfolder.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/mailfolder-get.md
  api-reference/v1.0/api/mailfolder-list-childfolders.md
  api-reference/v1.0/api/mailfolder-post-childfolders.md
  api-reference/v1.0/api/user-list-mailfolders.md
  api-reference/v1.0/api/user-post-mailfolders.md
  api-reference/v1.0/resources/mailfolder.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.Exchange.json
Labels: internal

#12275 Send email with MIME content
  api-reference/beta/api/message-createforward.md
  api-reference/beta/api/message-createreply.md
  api-reference/beta/api/message-createreplyall.md
  api-reference/beta/api/message-forward.md
  api-reference/beta/api/message-reply.md
  api-reference/beta/api/message-replyall.md
  api-reference/beta/api/message-send.md
  api-reference/beta/api/message-update.md
  api-reference/beta/api/user-post-messages.md
  api-reference/beta/api/user-sendmail.md
  api-reference/beta/resources/mail-api-overview.md
  api-reference/v1.0/api/mailfolder-post-messages.md
  api-reference/v1.0/api/message-createforward.md
  api-reference/v1.0/api/message-createreply.md
  api-reference/v1.0/api/message-createreplyall.md
  api-reference/v1.0/api/message-forward.md
  api-reference/v1.0/api/message-reply.md
  api-reference/v1.0/api/message-replyall.md
  api-reference/v1.0/api/message-send.md
  api-reference/v1.0/api/user-post-messages.md
  api-reference/v1.0/api/user-sendmail.md
  api-reference/v1.0/resources/mail-api-overview.md
  changelog/Microsoft.Exchange.json
  concepts/outlook-mail-concept-overview.md
  concepts/outlook-send-mime-message.md
  concepts/toc.yml
Labels: Build21, area: outlook, do not merge, internal

#12755 Update the Universal Print pricing header
  api-reference/includes/cloudprinting-pricing-disclaimer.md
Labels: area: universal print, internal, ready to merge

#12844 Fixed user flow language page delete example
  api-reference/v1.0/api/userflowlanguagepage-delete.md
Labels: ready to merge

#12841 Update educationsubmission-submit.md
  api-reference/beta/api/educationsubmission-submit.md
Labels: external

#12840 Update educationsubmission-setupResourcesFolder.md
  api-reference/beta/api/educationsubmission-setupResourcesFolder.md
Labels: external

#12839 Updating TOC elements for Graph Data Connect
  concepts/data-connect-concept-overview.md
  concepts/toc.yml
Labels: internal, ready to merge

#12818 Creating new branch for quickstart
  concepts/data-connect-quickstart-01.md
  concepts/data-connect-quickstart-02.md
  concepts/data-connect-quickstart-03.md
  concepts/data-connect-quickstart-04.md
  concepts/data-connect-quickstart-05.md
  concepts/data-connect-quickstart-06.md
  concepts/data-connect-quickstart-07.md
  concepts/data-connect-quickstart-08.md
  concepts/data-connect-quickstart.yml
  concepts/images/data-connect-aad-app-owners.png
  concepts/images/data-connect-aad-assigned-roles.png
  concepts/images/data-connect-aad-certs-secrets.png
  concepts/images/data-connect-aad-manage-users.png
  concepts/images/data-connect-aad-redirect-uri.png
  concepts/images/data-connect-aad.png
  concepts/images/data-connect-adf-auth-and-mon.png
  concepts/images/data-connect-adf-create.png
  concepts/images/data-connect-adf-extracted-data-in-blob.png
  concepts/images/data-connect-adf-extraction-approved.png
  concepts/images/data-connect-adf-linked-service.png
  concepts/images/data-connect-adf-ls-config.png
  concepts/images/data-connect-adf-network.png
  concepts/images/data-connect-adf-pipeline-copy-data.png
  concepts/images/data-connect-adf-pipeline-create.png
  concepts/images/data-connect-adf-pipeline-dataset.png
  concepts/images/data-connect-adf-pipeline-details.png
  concepts/images/data-connect-adf-pipeline-runs.png
  concepts/images/data-connect-adf-run-trigger.png
  concepts/images/data-connect-adf-sa-fp-config.png
  concepts/images/data-connect-adf-wait-for-approval.png
  concepts/images/data-connect-azure-aad-app-reg.png
  concepts/images/data-connect-azure-storage-container.png
  concepts/images/data-connect-azure-storage-create.png
  concepts/images/data-connect-azure-storage-role.png
  concepts/images/data-connect-m365-act-grp.png
  concepts/images/data-connect-m365-approve.png
  concepts/images/data-connect-m365-cons-apprv-pref.png
  concepts/images/data-connect-m365-cons-apprv.png
  concepts/images/data-connect-m365-enable-mgdc-for-org.png
  concepts/images/data-connect-m365-mail-sec.png
  concepts/images/data-connect-m365-mgdc-toggle.png
  concepts/images/data-connect-ps-pending-requests.png
  concepts/images/data-connect-vs-add-connected-service-sa.png
  concepts/images/data-connect-vs-add-dependency-azsa.png
  concepts/images/data-connect-vs-add-new-model-class.png
  concepts/images/data-connect-vs-add-view-index.png
  concepts/images/data-connect-vs-add-view-showmetrics.png
  concepts/images/data-connect-vs-configure-az-storage.png
  concepts/images/data-connect-vs-configure-sa-summary.png
  concepts/images/data-connect-vs-create-app-mvc.png
  concepts/images/data-connect-vs-create-app.png
  concepts/images/data-connect-vs-plus-sign.png
  concepts/images/data-connect-vs-select-view-metrics.png
  concepts/images/data-connect-vs-show-email-metrics.png
Labels: internal, ready to merge

#12846 Add note for mail & proxyAddresses
  api-reference/beta/resources/user.md
  api-reference/v1.0/resources/user.md
Labels: internal, ready to merge

#12849 Added what's new from the last week.
  concepts/whats-new-overview.md
Labels: internal

#12850 Refreshed what's new.
  concepts/whats-new-overview.md
Labels: internal

#12858 Update data-connect-quickstart-07.md
  concepts/data-connect-quickstart-07.md
Labels: internal, ready to merge

#12859 Updated missing dataset samples in table.
  concepts/data-connect-datasets.md
  concepts/index.yml
Labels: internal

#12865 Picking up changed files that were merged into the wrong branch
  api-reference/beta/api/application-post-calls.md
  api-reference/beta/api/call-redirect.md
  api-reference/beta/api/call-transfer.md
  api-reference/beta/api/participant-invite.md
  api-reference/v1.0/api/application-post-calls.md
  api-reference/v1.0/api/call-redirect.md
  api-reference/v1.0/api/call-transfer.md
  api-reference/v1.0/api/participant-invite.md
Labels: internal

#12861 Hub update build2021
  concepts/images/hub/icon01-sdk.svg
  concepts/images/hub/icon02-quickstart.svg
  concepts/images/hub/icon03-graphexplorer.svg
  concepts/images/hub/icon04-graphtoolkit.svg
  concepts/index.yml
Labels: internal, ready to merge

#12869 Update educationsubmissionresource-delete.md
  api-reference/beta/api/educationsubmissionresource-delete.md
Labels: external

#12868 Update educationsubmission-post-resources.md
  api-reference/beta/api/educationsubmission-post-resources.md
Labels: external

#12867 Update overview.md
  concepts/overview.md
Labels: internal, ready to merge

#12845 Ssotutorialupdate2
  concepts/application-saml-sso-configure-api.md
  concepts/images/application-saml-sso-configure-api/accept-permissions.PNG
  concepts/images/application-saml-sso-configure-api/select-permissions.PNG
Labels: area: azure/AAD, internal, ready to merge

#12830 Added app only permission to certain education profile actions
  api-reference/beta/api/educationsynchronizationprofile-list.md
  api-reference/beta/api/educationsynchronizationprofile-pause.md
  api-reference/beta/api/educationsynchronizationprofile-reset.md
  api-reference/beta/api/educationsynchronizationprofile-resume.md
  api-reference/beta/api/educationsynchronizationprofile-start.md
  api-reference/beta/api/educationsynchronizationprofile-uploadurl.md
  changelog/Microsoft.EducationDataSync.json
Labels: area: edu, internal, ready to merge

#12892 removing unsupported tutorial
  concepts/application-provisioning-configure-api.md
  concepts/toc.yml
Labels: area: azure/AAD, internal, ready to merge

#12890 Update data-connect-faq.md
  concepts/data-connect-faq.md
Labels: internal, ready to merge

#12888 Fix ms.prod values for new Governance APIs
  api-reference/beta/api/accesspackageassignmentrequest-cancel.md
  api-reference/beta/api/policyroot-list-rolemanagementpolicies.md
  api-reference/beta/api/policyroot-list-rolemanagementpolicyassignments.md
  api-reference/beta/api/rbacapplication-rolescheduleinstances.md
  api-reference/beta/api/rbacapplication-roleschedules.md
  api-reference/beta/api/unifiedroleassignmentschedule-filterbycurrentuser.md
  api-reference/beta/api/unifiedroleassignmentschedule-get.md
  api-reference/beta/api/unifiedroleassignmentschedule-list.md
  api-reference/beta/api/unifiedroleassignmentscheduleinstance-filterbycurrentuser.md
  api-reference/beta/api/unifiedroleassignmentscheduleinstance-get.md
  api-reference/beta/api/unifiedroleassignmentscheduleinstance-list.md
  api-reference/beta/api/unifiedroleassignmentschedulerequest-cancel.md
  api-reference/beta/api/unifiedroleassignmentschedulerequest-filterbycurrentuser.md
  api-reference/beta/api/unifiedroleassignmentschedulerequest-get.md
  api-reference/beta/api/unifiedroleassignmentschedulerequest-list.md
  api-reference/beta/api/unifiedroleassignmentschedulerequest-post-unifiedroleassignmentschedulerequests.md
  api-reference/beta/api/unifiedroleassignmentschedulerequest-update.md
  api-reference/beta/api/unifiedroleeligibilityschedule-filterbycurrentuser.md
  api-reference/beta/api/unifiedroleeligibilityschedule-get.md
  api-reference/beta/api/unifiedroleeligibilityschedule-list.md
  api-reference/beta/api/unifiedroleeligibilityscheduleinstance-filterbycurrentuser.md
  api-reference/beta/api/unifiedroleeligibilityscheduleinstance-get.md
  api-reference/beta/api/unifiedroleeligibilityscheduleinstance-list.md
  api-reference/beta/api/unifiedroleeligibilityschedulerequest-cancel.md
  api-reference/beta/api/unifiedroleeligibilityschedulerequest-filterbycurrentuser.md
  api-reference/beta/api/unifiedroleeligibilityschedulerequest-get.md
  api-reference/beta/api/unifiedroleeligibilityschedulerequest-list.md
  api-reference/beta/api/unifiedroleeligibilityschedulerequest-post-unifiedroleeligibilityschedulerequests.md
  api-reference/beta/api/unifiedroleeligibilityschedulerequest-update.md
  api-reference/beta/api/unifiedrolemanagementpolicy-get.md
  api-reference/beta/api/unifiedrolemanagementpolicy-list-effectiverules.md
  api-reference/beta/api/unifiedrolemanagementpolicy-list-rules.md
  api-reference/beta/api/unifiedrolemanagementpolicy-list.md
  api-reference/beta/api/unifiedrolemanagementpolicyassignment-get.md
  api-reference/beta/api/unifiedrolemanagementpolicyassignment-list.md
  api-reference/beta/api/unifiedrolemanagementpolicyrule-get.md
  api-reference/beta/api/unifiedrolemanagementpolicyrule-list.md
  api-reference/beta/api/unifiedrolemanagementpolicyrule-update.md
  api-reference/beta/resources/parentlabeldetails.md
  api-reference/beta/resources/policyroot.md
  api-reference/beta/resources/provisioningstatusinfo.md
  api-reference/beta/resources/ticketinfo.md
  api-reference/beta/resources/unifiedroleassignmentschedule.md
  api-reference/beta/resources/unifiedroleassignmentscheduleinstance.md
  api-reference/beta/resources/unifiedroleassignmentschedulerequest.md
  api-reference/beta/resources/unifiedroleeligibilityschedule.md
  api-reference/beta/resources/unifiedroleeligibilityscheduleinstance.md
  api-reference/beta/resources/unifiedrolemanagementpolicy.md
  api-reference/beta/resources/unifiedrolemanagementpolicyapprovalrule.md
  api-reference/beta/resources/unifiedrolemanagementpolicyassignment.md
  api-reference/beta/resources/unifiedrolemanagementpolicyauthenticationcontextrule.md
  api-reference/beta/resources/unifiedrolemanagementpolicyenablementrule.md
  api-reference/beta/resources/unifiedrolemanagementpolicyexpirationrule.md
  api-reference/beta/resources/unifiedrolemanagementpolicynotificationrule.md
  api-reference/beta/resources/unifiedrolemanagementpolicyrule.md
  api-reference/beta/resources/unifiedrolemanagementpolicyruletarget.md
  api-reference/beta/resources/unifiedroleschedulebase.md
  api-reference/beta/resources/unifiedrolescheduleinstancebase.md
  api-reference/v1.0/resources/provisioningstatusinfo.md
  concepts/migrate-azure-ad-graph-overview.md
Labels: area: azure/AAD, internal, ready to merge

#12879 Fix org branding owner from MS alias to GitHub alias
  api-reference/beta/api/organizationalbrandingproperties-create.md
  api-reference/beta/api/organizationalbrandingproperties-delete.md
  api-reference/beta/api/organizationalbrandingproperties-get.md
  api-reference/beta/api/organizationalbrandingproperties-update.md
  api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md
  api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md
  api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md
  api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md
  api-reference/beta/resources/organizationalbrandingproperties.md
  api-reference/v1.0/api/organizationalbrandingproperties-create.md
  api-reference/v1.0/api/organizationalbrandingproperties-delete.md
  api-reference/v1.0/api/organizationalbrandingproperties-get.md
  api-reference/v1.0/api/organizationalbrandingproperties-update.md
  api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md
  api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md
  api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md
  api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md
  api-reference/v1.0/resources/organizationalbrandingproperties.md
Labels: area: azure/AAD, internal, ready to merge

#12112 Authentication Methods Registration Campaign Graph Docs
  api-reference/beta/api/authenticationmethodspolicy-get.md
  api-reference/beta/api/authenticationmethodspolicy-update.md
  api-reference/beta/resources/authenticationmethodspolicies-overview.md
  api-reference/beta/resources/authenticationmethodspolicy.md
  api-reference/beta/resources/authenticationmethodsregistrationcampaign.md
  api-reference/beta/resources/authenticationmethodsregistrationcampaignincludetarget.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/excludetarget.md
  api-reference/beta/resources/registrationenforcement.md
  api-reference/beta/toc.yml
  changelog/Microsoft.DirectoryServices.json
Labels: area: azure/AAD, content review complete, internal, ready to merge

#12851 Add team description size message
  api-reference/beta/resources/team.md
  api-reference/v1.0/resources/team.md
Labels: external, ready to merge

#12877 Fix #12862 - From UserVoice to new feature request forum
  CONTRIBUTING.md
  api-reference/v1.0/overview.md
  concepts/use-the-api.md
  concepts/versioning-and-support.md
Labels: area: azure/AAD, area: groups, internal, ready to merge

#12723 Connectors dev docs 2nd part
  concepts/connecting-external-content-build-quickstart-01-intro.md
  concepts/connecting-external-content-build-quickstart-02-register-app.md
  concepts/connecting-external-content-build-quickstart-03-build-app.md
  concepts/connecting-external-content-build-quickstart-04-configure-app.md
  concepts/connecting-external-content-build-quickstart-05-create-db.md
  concepts/connecting-external-content-build-quickstart-06-run-app.md
  concepts/connecting-external-content-build-quickstart-07-surface-data.md
  concepts/connecting-external-content-build-quickstart-08-search-results.md
  concepts/connecting-external-content-build-quickstart-09-summary.md
  concepts/connecting-external-content-build-quickstart.yml
  concepts/images/connectors-images/bu-teams-D365.png
  concepts/images/connectors-images/build1.png
  concepts/images/connectors-images/build10.png
  concepts/images/connectors-images/build11.png
  concepts/images/connectors-images/build12.png
  concepts/images/connectors-images/build13.png
  concepts/images/connectors-images/build14.png
  concepts/images/connectors-images/build15.png
  concepts/images/connectors-images/build16.png
  concepts/images/connectors-images/build17.png
  concepts/images/connectors-images/build18.png
  concepts/images/connectors-images/build19.png
  concepts/images/connectors-images/build2.png
  concepts/images/connectors-images/build20.png
  concepts/images/connectors-images/build3-contoso-partsinv.png
  concepts/images/connectors-images/build3-contoso-register-app.png
  concepts/images/connectors-images/build4.png
  concepts/images/connectors-images/build5.png
  concepts/images/connectors-images/build6.png
  concepts/images/connectors-images/build7.png
  concepts/images/connectors-images/build8.png
  concepts/images/connectors-images/build9.png
  concepts/images/connectors-images/roles-salesforce.png
  concepts/toc.yml
Labels: Build21, content review complete, internal

#12907 Fixing title line in the connectors quickstart yaml file
  concepts/connecting-external-content-build-quickstart.yml
Labels: Build21, internal, ready to merge

#12908 Merge to publish (OOB)
  concepts/connecting-external-content-build-quickstart.yml
Labels: internal

#12910 Update termstore-localizedlabel.md
  api-reference/beta/resources/termstore-localizedlabel.md
Labels: external

#12763 Addressing bug #12694
  api-reference/beta/resources/dynamics-employee.md
Labels: internal, ready to merge

#12914 Merge to publish.
  api-reference/beta/api/chat-get-members.md
  api-reference/beta/api/chat-get.md
  api-reference/beta/api/chat-list-members.md
  api-reference/beta/api/chat-list-messages.md
  api-reference/beta/api/chat-list.md
  api-reference/beta/api/chatmessage-get.md
  api-reference/beta/api/chatmessage-list-hostedcontents.md
  api-reference/beta/api/chatmessagehostedcontent-get.md
  api-reference/beta/api/chats-getallmessages.md
  api-reference/beta/api/user-list-joinedteams.md
  api-reference/beta/api/userscopeteamsappinstallation-get-chat.md
  api-reference/beta/api/userteamwork-delete-installedapps.md
  api-reference/beta/api/userteamwork-get-installedapps.md
  api-reference/beta/api/userteamwork-list-installedapps.md
  api-reference/beta/api/userteamwork-post-installedapps.md
  api-reference/beta/api/userteamwork-sendactivitynotification.md
  api-reference/beta/api/userteamwork-teamsappinstallation-upgrade.md
  api-reference/beta/resources/dynamics-employee.md
  api-reference/beta/resources/termstore-localizedlabel.md
  api-reference/v1.0/api/chat-get-members.md
  api-reference/v1.0/api/chat-get.md
  api-reference/v1.0/api/chat-list-members.md
  api-reference/v1.0/api/chat-list-messages.md
  api-reference/v1.0/api/chatmessage-get.md
  api-reference/v1.0/api/chatmessage-list-hostedcontents.md
  api-reference/v1.0/api/chatmessagehostedcontent-get.md
  api-reference/v1.0/api/user-list-joinedteams.md
  api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md
  api-reference/v1.0/api/userteamwork-delete-installedapps.md
  api-reference/v1.0/api/userteamwork-get-installedapps.md
  api-reference/v1.0/api/userteamwork-list-installedapps.md
  api-reference/v1.0/api/userteamwork-post-installedapps.md
  api-reference/v1.0/api/userteamwork-sendactivitynotification.md
  api-reference/v1.0/api/userteamwork-teamsappinstallation-upgrade.md
  changelog/Microsoft.Teams.Core.json
Labels: internal

#12596 Update insights-customize-item-insights-privacy.md
  concepts/insights-customize-item-insights-privacy.md
  concepts/whats-new-earlier.md
Labels: review requested

#12916 Publish updates to item insights privacy settings (PR 12596).
  concepts/insights-customize-item-insights-privacy.md
  concepts/whats-new-earlier.md
Labels: internal

#12925 Update entity.md
  api-reference/v1.0/resources/entity.md
Labels: external

#12924 Update organization.md
  api-reference/beta/resources/organization.md
Labels: external

#12923 Update organization.md
  api-reference/v1.0/resources/organization.md
Labels: external

#12917 Add links to the MSAL libs for different frameworks
  concepts/auth-v2-service.md
  concepts/auth-v2-user.md
Labels: area: azure/AAD, internal, ready to merge

#12927 Typo on sample for search
  concepts/search-concept-custom-types.md
Labels: internal, ready to merge

#12853 Fix users issues
  api-reference/beta/api/user-list-ownedobjects.md
  api-reference/beta/api/user-list.md
  api-reference/v1.0/api/user-list-ownedobjects.md
  api-reference/v1.0/api/user-list.md
Labels: do not merge, internal, ready to merge

#12922 Various fixes
  api-reference/beta/api/accessreviewscheduledefinition-list.md
  api-reference/beta/api/serviceprincipal-delete-approleassignedto.md
  api-reference/beta/api/serviceprincipal-delete-approleassignments.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/serviceprincipal-delete-approleassignedto.md
  api-reference/v1.0/api/serviceprincipal-delete-approleassignments.md
  api-reference/v1.0/toc.yml
Labels: area: azure/AAD, internal, ready to merge

#12912 bug fixes for POST setUpResourcesFolder request body
  api-reference/beta/api/educationassignment-setupresourcesfolder.md
  api-reference/beta/api/educationsubmission-setupResourcesFolder.md
Labels: do not merge, internal

#12930 Merge to publish.
  api-reference/beta/api/accessreviewscheduledefinition-list.md
  api-reference/beta/api/educationassignment-setupresourcesfolder.md
  api-reference/beta/api/educationsubmission-setupResourcesFolder.md
  api-reference/beta/api/serviceprincipal-delete-approleassignedto.md
  api-reference/beta/api/serviceprincipal-delete-approleassignments.md
  api-reference/beta/api/user-list-ownedobjects.md
  api-reference/beta/api/user-list.md
  api-reference/beta/resources/organization.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/serviceprincipal-delete-approleassignedto.md
  api-reference/v1.0/api/serviceprincipal-delete-approleassignments.md
  api-reference/v1.0/api/user-list-ownedobjects.md
  api-reference/v1.0/api/user-list.md
  api-reference/v1.0/resources/entity.md
  api-reference/v1.0/resources/organization.md
  api-reference/v1.0/toc.yml
  concepts/auth-v2-service.md
  concepts/auth-v2-user.md
  concepts/search-concept-custom-types.md
Labels: internal

#12237 [CloudPC]Add CloudPC RBAC APIs
  api-reference/beta/api/rbacapplication-list-roledefinitions.md
  api-reference/beta/api/rbacapplication-post-roledefinitions.md
  api-reference/beta/api/rbacapplicationmultiple-list-roleassignments.md
  api-reference/beta/api/rbacapplicationmultiple-post-roleassignments.md
  api-reference/beta/api/unifiedroleassignmentmultiple-delete.md
  api-reference/beta/api/unifiedroleassignmentmultiple-get.md
  api-reference/beta/api/unifiedroleassignmentmultiple-list.md
  api-reference/beta/api/unifiedroleassignmentmultiple-update.md
  api-reference/beta/api/unifiedroledefinition-delete.md
  api-reference/beta/api/unifiedroledefinition-get.md
  api-reference/beta/api/unifiedroledefinition-update.md
  api-reference/beta/resources/rbacapplicationmultiple.md
  api-reference/beta/resources/rolemanagement.md
  api-reference/beta/resources/unifiedroleassignmentmultiple.md
  api-reference/beta/resources/unifiedroledefinition.md
  api-reference/beta/toc.yml
  api-reference/includes/cloudpc-api-preview.md
  changelog/Microsoft.CloudManagedDesktop.json
  changelog/Microsoft.DirectoryServices.json
Labels: content review complete, do not merge, internal, schema live

#12939 Publish cloud PC RBAC API.
  api-reference/beta/api/rbacapplication-list-roledefinitions.md
  api-reference/beta/api/rbacapplication-post-roledefinitions.md
  api-reference/beta/api/rbacapplicationmultiple-list-roleassignments.md
  api-reference/beta/api/rbacapplicationmultiple-post-roleassignments.md
  api-reference/beta/api/unifiedroleassignmentmultiple-delete.md
  api-reference/beta/api/unifiedroleassignmentmultiple-get.md
  api-reference/beta/api/unifiedroleassignmentmultiple-list.md
  api-reference/beta/api/unifiedroleassignmentmultiple-update.md
  api-reference/beta/api/unifiedroledefinition-delete.md
  api-reference/beta/api/unifiedroledefinition-get.md
  api-reference/beta/api/unifiedroledefinition-update.md
  api-reference/beta/resources/rbacapplicationmultiple.md
  api-reference/beta/resources/rolemanagement.md
  api-reference/beta/resources/unifiedroleassignmentmultiple.md
  api-reference/beta/resources/unifiedroledefinition.md
  api-reference/beta/toc.yml
  api-reference/includes/cloudpc-api-preview.md
  changelog/Microsoft.CloudManagedDesktop.json
  changelog/Microsoft.DirectoryServices.json
Labels: internal
