Repository microsoftgraph/microsoft-graph-docs, pull requests merged in 2021-10, with the labels that each got.

#13910 Alamaral acs index
  api-reference/beta/resources/application.md
  api-reference/beta/resources/redirecturisettings.md
  api-reference/beta/resources/webapplication.md
  changelog/Microsoft.DirectoryServices.json
Labels: area: azure/AAD, ready to merge, internal, content review complete

#13914 Adding TLS 1.2 notes for driveitem
  api-reference/beta/api/driveitem-get-content-format.md
  api-reference/beta/api/driveitem-get-content.md
  api-reference/beta/api/driveitem-list-thumbnails.md
  api-reference/beta/config/link-validation-config.json
  api-reference/includes/tls-1.2-required.md
  api-reference/v1.0/api/driveitem-get-content-format.md
  api-reference/v1.0/api/driveitem-get-content.md
  api-reference/v1.0/api/driveitem-list-thumbnails.md
  api-reference/v1.0/config/link-validation-config.json
  concepts/best-practices-concept.md
Labels: ready to merge, internal, content review complete

#14147 Updating response examples for educationSynchronizationProfile resources
  api-reference/beta/api/educationsynchronizationprofile-get.md
  api-reference/beta/api/educationsynchronizationprofile-list.md
  api-reference/beta/api/educationsynchronizationprofile-post.md
  api-reference/beta/api/educationsynchronizationprofile-put.md
  api-reference/beta/resources/educationsynchronizationcustomizations.md
Labels: area: education, bug: sample, ready to merge, internal, content review complete

#13327 deprecate userflows
  api-reference/beta/api/identityuserflow-delete.md
  api-reference/beta/api/identityuserflow-get.md
  api-reference/beta/api/identityuserflow-list.md
  api-reference/beta/api/identityuserflow-post-userflows.md
  api-reference/beta/resources/identityuserflow.md
  api-reference/beta/toc.yml
  api-reference/includes/identityuserflow-deprecate.md
  changelog/Microsoft.DirectoryServices.json
Labels: area: azure/AAD, ready to merge, internal, content review in progress

#14445 missing changelog entry for membershipType
  changelog/Microsoft.Teams.Core.json
Labels: ready to merge, ready for content review, internal

#14449 Merge to publish.
  api-reference/beta/api/driveitem-get-content-format.md
  api-reference/beta/api/driveitem-get-content.md
  api-reference/beta/api/driveitem-list-thumbnails.md
  api-reference/beta/api/educationsynchronizationprofile-get.md
  api-reference/beta/api/educationsynchronizationprofile-list.md
  api-reference/beta/api/educationsynchronizationprofile-post.md
  api-reference/beta/api/educationsynchronizationprofile-put.md
  api-reference/beta/api/identityuserflow-delete.md
  api-reference/beta/api/identityuserflow-get.md
  api-reference/beta/api/identityuserflow-list.md
  api-reference/beta/api/identityuserflow-post-userflows.md
  api-reference/beta/config/link-validation-config.json
  api-reference/beta/resources/application.md
  api-reference/beta/resources/educationsynchronizationcustomizations.md
  api-reference/beta/resources/identityuserflow.md
  api-reference/beta/resources/redirecturisettings.md
  api-reference/beta/resources/webapplication.md
  api-reference/beta/toc.yml
  api-reference/includes/identityuserflow-deprecate.md
  api-reference/includes/tls-1.2-required.md
  api-reference/v1.0/api/driveitem-get-content-format.md
  api-reference/v1.0/api/driveitem-get-content.md
  api-reference/v1.0/api/driveitem-list-thumbnails.md
  api-reference/v1.0/config/link-validation-config.json
  changelog/Microsoft.DirectoryServices.json
  changelog/Microsoft.Teams.Core.json
  concepts/best-practices-concept.md
Labels: internal

#14403 Licensing and consumption fees for Teams change notifications and exported APIs
  api-reference/beta/api/channel-getallmessages.md
  api-reference/beta/api/chatmessage-update.md
  api-reference/beta/api/chats-getallmessages.md
  api-reference/includes/teams-model-A-and-B-disclaimer.md
  api-reference/includes/teams-model-A-only-disclaimer.md
  api-reference/includes/teams-subscription-notes.md
  api-reference/v1.0/api/chatmessage-update.md
  concepts/teams-licenses.md
  concepts/toc.yml
Labels: area: teams, ready to merge, internal, content review complete

#14455 Merge to publish (OOB)
  api-reference/beta/api/channel-getallmessages.md
  api-reference/beta/api/chatmessage-update.md
  api-reference/beta/api/chats-getallmessages.md
  api-reference/beta/resources/chatmessage.md
  api-reference/beta/toc.yml
  api-reference/includes/teams-model-A-and-B-disclaimer.md
  api-reference/includes/teams-model-A-only-disclaimer.md
  api-reference/includes/teams-subscription-notes.md
  api-reference/v1.0/api/channel-getallmessages.md
  api-reference/v1.0/api/chatmessage-update.md
  api-reference/v1.0/api/chats-getallmessages.md
  api-reference/v1.0/resources/channel.md
  api-reference/v1.0/resources/chat.md
  api-reference/v1.0/resources/chatmessage.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.Teams.Core.json
  concepts/teams-licenses.md
  concepts/toc.yml
Labels: internal

#14456 Fix link to terms of use
  concepts/teams-licenses.md
Labels: ready to merge, internal

#14457 Merge to publish (OOB)
  concepts/teams-licenses.md
Labels: internal

#14461 Adding disclaimers to a few files we missed
  concepts/teams-change-notification-in-microsoft-teams-overview.md
  concepts/teams-changenotifications-chatMembership.md
  concepts/teams-changenotifications-chatmessage.md
  concepts/teams-changenotifications-teamMembership.md
  includes/teams-model-A-and-B-disclaimer.md
Labels: area: teams, ready to merge, internal

#14429 Update windowsupdates-deploy-update.md
  concepts/windowsupdates-deploy-update.md
Labels: ready to merge, internal

#14460 Update user.md
  api-reference/beta/resources/user.md
Labels: external

#14459 Update user.md
  api-reference/v1.0/resources/user.md
Labels: external

#14462 Merge to publish.
  api-reference/beta/resources/user.md
  api-reference/v1.0/resources/user.md
  concepts/teams-change-notification-in-microsoft-teams-overview.md
  concepts/teams-changenotifications-chatMembership.md
  concepts/teams-changenotifications-chatmessage.md
  concepts/teams-changenotifications-teamMembership.md
  concepts/windowsupdates-deploy-update.md
  includes/teams-model-A-and-B-disclaimer.md
Labels: internal

#14484 Update search-concept-overview.md
  concepts/search-concept-overview.md
Labels: external

#14482 Typo retports
  concepts/reportroot-concept-overview.md
Labels: external

#14481 Isvargasmsft issue9274 flippeddescriptions
  api-reference/beta/resources/bookingworktimeslot.md
Labels: ready to merge, internal

#14480 Issue 9402: Fixing typo
  api-reference/beta/resources/excel.md
  api-reference/v1.0/resources/excel.md
Labels: ready to merge, internal

#14479 Issue 9752: fixing response code
  api-reference/v1.0/api/message-forward.md
Labels: ready to merge, internal

#14478 Issue 14260: Updating to new link
  concepts/hybrid-rest-support.md
Labels: ready to merge, internal

#14474 Issue 14244: adding complete links
  api-reference/beta/resources/security-api-overview.md
  api-reference/v1.0/resources/security-api-overview.md
Labels: ready to merge, internal

#14486 Adding entries to TOC that were missing
  api-reference/beta/resources/ediscovery-case.md
  api-reference/beta/toc.yml
Labels: ready to merge, internal

#14472 Issue 14234: fixing broken links
  api-reference/beta/api/user-post-messages.md
  api-reference/v1.0/api/user-post-messages.md
Labels: ready to merge, internal

#14436 Minor docs improvements
  api-reference/beta/api/driveitem-createuploadsession.md
  api-reference/beta/resources/driverecipient.md
  api-reference/v1.0/api/driveitem-createuploadsession.md
  api-reference/v1.0/resources/driverecipient.md
Labels: ready to merge, internal, review feedback addressed

#14339 Update remarks for Windows updates permissions
  concepts/permissions-reference.md
Labels: ready to merge, internal, content review complete, schema live

#14313 Update windowsupdates-softwareupdatereference.md
  api-reference/beta/resources/windowsupdates-softwareupdatereference.md
Labels: ready to merge, internal, content review complete, schema live

#14380 Delete printdocument-uploaddata.md
  api-reference/beta/api/printdocument-uploaddata.md
  changelog/Microsoft.PrintService.json
Labels: ready to merge, internal, area: universal print

#13658 Update continuousaccessevaluationpolicy-update.md
  api-reference/beta/api/continuousaccessevaluationpolicy-update.md
Labels: area: azure/AAD, ready to merge, internal

#14487 Merge to publish.
  api-reference/beta/api/continuousaccessevaluationpolicy-update.md
  api-reference/beta/api/driveitem-createuploadsession.md
  api-reference/beta/api/printdocument-uploaddata.md
  api-reference/beta/api/user-post-messages.md
  api-reference/beta/resources/bookingworktimeslot.md
  api-reference/beta/resources/driverecipient.md
  api-reference/beta/resources/ediscovery-case.md
  api-reference/beta/resources/excel.md
  api-reference/beta/resources/security-api-overview.md
  api-reference/beta/resources/windowsupdates-softwareupdatereference.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/driveitem-createuploadsession.md
  api-reference/v1.0/api/message-forward.md
  api-reference/v1.0/api/user-post-messages.md
  api-reference/v1.0/resources/driverecipient.md
  api-reference/v1.0/resources/excel.md
  api-reference/v1.0/resources/security-api-overview.md
  changelog/Microsoft.PrintService.json
  concepts/hybrid-rest-support.md
  concepts/permissions-reference.md
  concepts/reportroot-concept-overview.md
  concepts/search-concept-overview.md
Labels: internal

#12257 Initial device registration policy - Preview docs
  api-reference/beta/api/device-update.md
  api-reference/beta/api/deviceregistrationpolicy-get.md
  api-reference/beta/api/deviceregistrationpolicy-update.md
  api-reference/beta/resources/azureadjoinpolicy.md
  api-reference/beta/resources/azureadregistrationpolicy.md
  api-reference/beta/resources/deviceregistrationpolicy.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/policy-overview.md
  api-reference/beta/resources/policyroot.md
  api-reference/beta/toc.yml
  changelog/Microsoft.DeviceRegistrationPolicies.json
Labels: area: azure/AAD, do not merge, internal, area: identity, content review complete

#14498 Fix broken TOC link and update changelog for deviceRegistrationPolicy
  api-reference/beta/toc.yml
  changelog/Microsoft.DeviceRegistrationPolicies.json
Labels: ready to merge, internal

#14499 Fasttrack publication of the Initial Device Registration Policy APIs
  api-reference/beta/api/device-update.md
  api-reference/beta/api/deviceregistrationpolicy-get.md
  api-reference/beta/api/deviceregistrationpolicy-update.md
  api-reference/beta/resources/azureadjoinpolicy.md
  api-reference/beta/resources/azureadregistrationpolicy.md
  api-reference/beta/resources/deviceregistrationpolicy.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/policy-overview.md
  api-reference/beta/resources/policyroot.md
  api-reference/beta/toc.yml
  changelog/Microsoft.DeviceRegistrationPolicies.json
Labels: internal

#14502 Update search-concept-custom-types.md
  concepts/search-concept-custom-types.md
Labels: external

#13745 Document searchSettings for externalConnection API
  api-reference/beta/resources/enums-externalconnectors.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/externalconnectors-displaytemplate.md
  api-reference/beta/resources/externalconnectors-externalconnection.md
  api-reference/beta/resources/externalconnectors-propertyrule.md
  api-reference/beta/resources/externalconnectors-searchsettings.md
  changelog/Microsoft.Search.json
Labels: ready to merge, internal, content review complete

#14523 Fix the Connect-MgGraph command
  concepts/powershell/RegisterAppOnly.ps1
Labels: external

#8151 Remove identityRiskEvents API
  api-reference/beta/api/anonymousipriskevent-get.md
  api-reference/beta/api/anonymousipriskevent-list.md
  api-reference/beta/api/identityriskevent-get.md
  api-reference/beta/api/identityriskevent-list.md
  api-reference/beta/api/impossibletravelriskevent-get.md
  api-reference/beta/api/impossibletravelriskevent-list.md
  api-reference/beta/api/leakedcredentialsriskevent-get.md
  api-reference/beta/api/leakedcredentialsriskevent-list.md
  api-reference/beta/api/locatedriskevent-get.md
  api-reference/beta/api/malwareriskevent-get.md
  api-reference/beta/api/malwareriskevent-list.md
  api-reference/beta/api/suspiciousipriskevent-get.md
  api-reference/beta/api/suspiciousipriskevent-list.md
  api-reference/beta/api/unfamiliarlocationriskevent-get.md
  api-reference/beta/api/unfamiliarlocationriskevent-list.md
  api-reference/beta/resources/anonymousipriskevent.md
  api-reference/beta/resources/identityprotection-root.md
  api-reference/beta/resources/identityriskevent.md
  api-reference/beta/resources/impossibletravelriskevent.md
  api-reference/beta/resources/leakedcredentialsriskevent.md
  api-reference/beta/resources/locatedriskevent.md
  api-reference/beta/resources/malwareriskevent.md
  api-reference/beta/resources/suspiciousipriskevent.md
  api-reference/beta/resources/unfamiliarlocationriskevent.md
  api-reference/beta/toc.yml
Labels: area: azure/AAD, changelog required, changelog, schema live

#14788 Copy-paste error
  concepts/teams-licenses.md
Labels: ready to merge, internal

#14787 Fixing which APIs are in private preview
  api-reference/v1.0/api/team-get-installedapps.md
  concepts/permissions-reference.md
Labels: ready to merge, internal

#14784 Get subscription throttling limits
  includes/throttling-subscription-services.md
Labels: ready to merge, internal

#14528 appiduri updates
  api-reference/beta/resources/application.md
  api-reference/v1.0/resources/application.md
Labels: area: azure/AAD, ready to merge, internal, content review complete

#14791 Added what's new since 10/17.
  changelog/Microsoft.DirectoryServices.json
  concepts/whats-new-overview.md
Labels: internal

#14792 Further refresh the what's new topic.
  changelog/Microsoft.DirectoryServices.json
  concepts/whats-new-overview.md
Labels: internal
