Repository microsoftgraph/microsoft-graph-docs, pull requests merged in 2021-07, with the labels that each got.

#11433 Files - add media, source properties, & recordings special folder
  api-reference/beta/api/drive-get-specialfolder.md
  api-reference/beta/api/driveitem-createuploadsession.md
  api-reference/beta/includes/files-special-folder-list.md
  api-reference/beta/resources/driveitem.md
  api-reference/beta/resources/driveitemsource.md
  api-reference/beta/resources/driveitemuploadableproperties.md
  api-reference/beta/resources/media.md
  api-reference/beta/resources/mediasource.md
  api-reference/beta/resources/specialfolder.md
  changelog/Microsoft.FileServices.json
  concepts/changelog.md
Labels: content review complete, internal, ready to merge, schema live

#13344 Merge to publish.
  api-reference/beta/api/chat-list.md
  api-reference/beta/api/drive-get-specialfolder.md
  api-reference/beta/api/driveitem-createuploadsession.md
  api-reference/beta/includes/files-special-folder-list.md
  api-reference/beta/resources/channel.md
  api-reference/beta/resources/chat.md
  api-reference/beta/resources/chatmessageinfo.md
  api-reference/beta/resources/chatviewpoint.md
  api-reference/beta/resources/driveitem.md
  api-reference/beta/resources/driveitemsource.md
  api-reference/beta/resources/driveitemuploadableproperties.md
  api-reference/beta/resources/media.md
  api-reference/beta/resources/mediasource.md
  api-reference/beta/resources/specialfolder.md
  api-reference/v1.0/resources/channel.md
  changelog/Microsoft.FileServices.json
  changelog/Microsoft.Teams.Core.json
  concepts/changelog.md
  concepts/overview-major-services.md
  concepts/whats-new-overview.md
Labels: internal

#12556 changed case for release
  api-reference/beta/api/ediscovery-noncustodialdatasource-release.md
Labels: internal, ready to merge

#13391 Update findmeetingtimes-example.md
  concepts/findmeetingtimes-example.md
Labels: external

#13390 Update outlook-get-free-busy-schedule.md
  concepts/outlook-get-free-busy-schedule.md
Labels: external

#13389 Change from old ms.prod value
  api-reference/beta/api/orgcontact-get-transitivereports.md
  api-reference/beta/api/user-get-transitivereports.md
Labels: area: azure/AAD, internal, ready to merge

#13380 Update list.md
  api-reference/beta/resources/list.md
Labels: external

#13379 Update list.md
  api-reference/v1.0/resources/list.md
Labels: external

#13358 Fixes #13319 - Correct the value of id
  api-reference/beta/api/serviceprincipal-delete-approleassignedto.md
  api-reference/v1.0/api/serviceprincipal-delete-approleassignedto.md
Labels: internal, ready to merge

#13357 Add note for permission requirement
  api-reference/beta/api/group-post-groups.md
  api-reference/beta/api/group-update.md
  api-reference/beta/api/grouplifecyclepolicy-addgroup.md
  api-reference/beta/api/grouplifecyclepolicy-removegroup.md
  api-reference/beta/resources/group.md
  api-reference/beta/resources/grouplifecyclepolicy.md
  api-reference/v1.0/api/group-post-groups.md
  api-reference/v1.0/api/group-update.md
  api-reference/v1.0/api/grouplifecyclepolicy-addgroup.md
  api-reference/v1.0/api/grouplifecyclepolicy-removegroup.md
  api-reference/v1.0/resources/group.md
  api-reference/v1.0/resources/grouplifecyclepolicy.md
Labels: internal, ready to merge

#13346 Correct consent requests in the TOC
  api-reference/v1.0/toc.yml
Labels: internal, ready to merge

#13362 WindowsUpdates: updatableAssetGroup does not exist as an EntitySet.
  api-reference/beta/api/windowsupdates-updatableasset-unenrollassets.md
  api-reference/beta/api/windowsupdates-updatableassetgroup-addmembers.md
  api-reference/beta/api/windowsupdates-updatableassetgroup-removemembers.md
Labels: internal, ready to merge

#11469 add entitlementManagement to unified RBAC
  api-reference/beta/api/rbacapplication-list-roleassignments.md
  api-reference/beta/api/rbacapplication-list-roledefinitions.md
  api-reference/beta/api/rbacapplication-post-roleassignments.md
  api-reference/beta/api/unifiedroleassignment-delete.md
  api-reference/beta/api/unifiedroleassignment-get.md
  api-reference/beta/api/unifiedroledefinition-get.md
  api-reference/beta/resources/entitlementmanagement-root.md
  api-reference/beta/resources/rbacapplication.md
  api-reference/beta/resources/rolemanagement.md
  api-reference/beta/resources/unifiedroledefinition.md
  api-reference/beta/resources/unifiedrolepermission.md
Labels: area: azure/AAD, internal, ready to merge, review feedback addressed

#13414 Update with activated roles details.
  api-reference/beta/api/directoryrole-list.md
Labels: external

#13411 Update singlevaluelegacyextendedproperty.md
  api-reference/v1.0/resources/singlevaluelegacyextendedproperty.md
Labels: external

#13410 Update singlevaluelegacyextendedproperty.md
  api-reference/beta/resources/singlevaluelegacyextendedproperty.md
Labels: external

#13407 - bumps java SDK to v4
  concepts/sdks/sdk-installation.md
Labels: area: sample code, internal, ready to merge

#13404 Updated amount of requests that can be performed at once
  concepts/json-batching.md
Labels: external

#13403 Update auth-v2-service.md
  concepts/auth-v2-service.md
Labels: external

#13401 Minor fix - correct version
  api-reference/beta/api/serviceprincipal-delete-approleassignedto.md
Labels: area: azure/AAD, internal, ready to merge

#13305 Update role management APIs permissions table
  api-reference/beta/api/rbacapplication-list-roledefinitions.md
  api-reference/beta/api/rbacapplication-post-roledefinitions.md
  api-reference/beta/api/rbacapplicationmultiple-list-roleassignments.md
  api-reference/beta/api/rbacapplicationmultiple-post-roleassignments.md
  api-reference/beta/api/unifiedroleassignmentmultiple-delete.md
  api-reference/beta/api/unifiedroleassignmentmultiple-get.md
  api-reference/beta/api/unifiedroleassignmentmultiple-update.md
  api-reference/beta/api/unifiedroleassignmentschedule-filterbycurrentuser.md
  api-reference/beta/api/unifiedroleassignmentschedule-get.md
  api-reference/beta/api/unifiedroleassignmentschedule-list.md
  api-reference/beta/api/unifiedroleassignmentscheduleinstance-filterbycurrentuser.md
  api-reference/beta/api/unifiedroleassignmentscheduleinstance-get.md
  api-reference/beta/api/unifiedroleassignmentscheduleinstance-list.md
  api-reference/beta/api/unifiedroleassignmentschedulerequest-cancel.md
  api-reference/beta/api/unifiedroleassignmentschedulerequest-filterbycurrentuser.md
  api-reference/beta/api/unifiedroleassignmentschedulerequest-get.md
  api-reference/beta/api/unifiedroleassignmentschedulerequest-list.md
  api-reference/beta/api/unifiedroleassignmentschedulerequest-post-unifiedroleassignmentschedulerequests.md
  api-reference/beta/api/unifiedroleassignmentschedulerequest-update.md
  api-reference/beta/api/unifiedroledefinition-delete.md
  api-reference/beta/api/unifiedroledefinition-get.md
  api-reference/beta/api/unifiedroledefinition-update.md
  api-reference/beta/api/unifiedroleeligibilityschedule-filterbycurrentuser.md
  api-reference/beta/api/unifiedroleeligibilityschedule-get.md
  api-reference/beta/api/unifiedroleeligibilityschedule-list.md
  api-reference/beta/api/unifiedroleeligibilityscheduleinstance-filterbycurrentuser.md
  api-reference/beta/api/unifiedroleeligibilityscheduleinstance-get.md
  api-reference/beta/api/unifiedroleeligibilityscheduleinstance-list.md
  api-reference/beta/api/unifiedroleeligibilityschedulerequest-cancel.md
  api-reference/beta/api/unifiedroleeligibilityschedulerequest-filterbycurrentuser.md
  api-reference/beta/api/unifiedroleeligibilityschedulerequest-get.md
  api-reference/beta/api/unifiedroleeligibilityschedulerequest-list.md
  api-reference/beta/api/unifiedroleeligibilityschedulerequest-post-unifiedroleeligibilityschedulerequests.md
  api-reference/beta/api/unifiedroleeligibilityschedulerequest-update.md
  api-reference/beta/api/unifiedrolemanagementpolicy-get.md
  api-reference/beta/api/unifiedrolemanagementpolicy-list-effectiverules.md
  api-reference/beta/api/unifiedrolemanagementpolicy-list-rules.md
  api-reference/beta/api/unifiedrolemanagementpolicy-list.md
  api-reference/beta/api/unifiedrolemanagementpolicyassignment-get.md
  api-reference/beta/api/unifiedrolemanagementpolicyassignment-list.md
  api-reference/beta/api/unifiedrolemanagementpolicyrule-get.md
  api-reference/beta/api/unifiedrolemanagementpolicyrule-list.md
  api-reference/beta/api/unifiedrolemanagementpolicyrule-update.md
  api-reference/beta/resources/unifiedroleassignmentschedulerequest.md
  api-reference/beta/resources/unifiedroledefinition.md
  api-reference/beta/resources/unifiedroleeligibilityschedulerequest.md
  api-reference/beta/toc.yml
Labels: internal, ready to merge

#13282 Extends documentation of MGT components' events
  concepts/toolkit/components/agenda.md
  concepts/toolkit/components/file-list.md
  concepts/toolkit/components/get.md
  concepts/toolkit/components/login.md
  concepts/toolkit/components/people-picker.md
  concepts/toolkit/components/person-card.md
  concepts/toolkit/components/person.md
  concepts/toolkit/components/tasks.md
  concepts/toolkit/components/teams-channel-picker.md
  concepts/toolkit/components/todo.md
Labels: content review, internal, ready to merge

#13185 Add Person entity to search API
  api-reference/beta/api/search-query.md
  api-reference/beta/resources/search-api-overview.md
  api-reference/beta/resources/searchrequest.md
  changelog/Microsoft.MicrosoftSearch.json
  concepts/search-concept-person.md
  concepts/toc.yml
Labels: internal, ready to merge

#13245 Updated C# link in code sample
  api-reference/v1.0/api/chat-sendactivitynotification.md
Labels: internal, ready to merge

#12730 Update userflowlanguageconfiguration-get.md
  api-reference/beta/api/userflowlanguageconfiguration-get.md
Labels: external

#12213 Add one enum member to cloudPcOnPremisesConnectionHealthCheckErrorType
  api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: internal, ready to merge, schema live

#12788 Update user-list-manager.md - Added requirement
  api-reference/v1.0/api/user-list-manager.md
Labels: external, ready to merge

#13352 Windows updates: Add known issue on accessing and updating deployment audiences
  api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md
  api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md
  api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md
  api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md
  concepts/known-issues.md
Labels: content review complete, internal, ready to merge, schema live

#13368 AuthenticationMethodsPolicy: Fixing sample URLs
  api-reference/v1.0/api/emailauthenticationmethodconfiguration-get.md
  api-reference/v1.0/api/emailauthenticationmethodconfiguration-update.md
  api-reference/v1.0/api/featurerolloutpolicy-get.md
  api-reference/v1.0/api/fido2authenticationmethod-get.md
Labels: internal, ready to merge

#13427 Update chatmessage-post.md
  api-reference/beta/api/chatmessage-post.md
Labels: external

#13426 Update channel-list-messages.md
  api-reference/beta/api/channel-list-messages.md
Labels: external

#12896 Rename and add azureAdDeviceSyncCheck related error types
  api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: internal, ready to merge, schema live

#13243 Update auth basics for Microsoft Graph
  concepts/auth/auth-concepts.md
  concepts/images/auth-v2/permission-types.png
Labels: internal, ready to merge

#13269 Surface the changePassword action on /me
  api-reference/beta/api/user-changepassword.md
  api-reference/beta/api/user-invalidateallrefreshtokens.md
  api-reference/beta/resources/user.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/user-changepassword.md
  api-reference/v1.0/resources/user.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.DirectoryServices.json
Labels: internal, ready to merge, review feedback addressed

#13366 EnterpriseRBAC: Fixing URLs in samples
  api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md
  api-reference/beta/api/unifiedroleassignmentschedule-get.md
  api-reference/beta/api/unifiedroleassignmentscheduleinstance-get.md
Labels: internal, ready to merge

#13373 Add note for properties returned only on $select
  api-reference/beta/api/application-get.md
  api-reference/beta/api/user-get.md
  api-reference/v1.0/api/application-get.md
  api-reference/v1.0/api/application-list.md
  api-reference/v1.0/api/user-get.md
Labels: internal, ready to merge

#13409 Document filter support for other properties of directory objects
  concepts/aad-advanced-queries.md
  includes/filter-directory-objects.md
Labels: internal, ready to merge

#13412 EM add example post request body for unified RBAC
  api-reference/beta/api/rbacapplication-post-roleassignments.md
  api-reference/beta/resources/accesspackagecatalog.md
  api-reference/beta/resources/entitlementmanagementsettings.md
  api-reference/beta/resources/unifiedroleassignment.md
Labels: area: azure/AAD, content review complete, internal, ready to merge

#13417 Fix format of permissions table
  api-reference/beta/api/rbacapplication-list-roleassignments.md
  api-reference/beta/api/rbacapplication-post-roleassignments.md
  api-reference/beta/api/unifiedroleassignment-delete.md
  api-reference/beta/api/unifiedroleassignment-get.md
  api-reference/beta/api/unifiedroledefinition-update.md
Labels: area: azure/AAD, internal, ready to merge

#13421 Correct permission name, fixes #13408
  api-reference/beta/api/governanceresource-get.md
  api-reference/beta/api/governanceresource-list.md
  api-reference/beta/api/governanceresource-register.md
  api-reference/beta/api/governanceroleassignment-export.md
  api-reference/beta/api/governanceroleassignment-get.md
  api-reference/beta/api/governanceroleassignment-list.md
  api-reference/beta/api/governanceroleassignmentrequest-cancel.md
  api-reference/beta/api/governanceroleassignmentrequest-get.md
  api-reference/beta/api/governanceroleassignmentrequest-list.md
  api-reference/beta/api/governanceroleassignmentrequest-post.md
  api-reference/beta/api/governanceroleassignmentrequest-update.md
  api-reference/beta/api/governanceroledefinition-get.md
  api-reference/beta/api/governanceroledefinition-list.md
  api-reference/beta/api/governancerolesetting-get.md
  api-reference/beta/api/governancerolesetting-list.md
  api-reference/beta/api/governancerolesetting-update.md
  concepts/permissions-reference.md
Labels: area: azure/AAD, ready to merge

#13424 Pass 2 on query parameters supported on users
  api-reference/beta/resources/user.md
  api-reference/v1.0/resources/user.md
Labels: area: azure/AAD, internal, ready to merge

#13400 Update insights-customize-item-insights-privacy.md
  concepts/insights-customize-item-insights-privacy.md
Labels: external

#13435 Minor fix string->int
  api-reference/v1.0/api/accessreviewscheduledefinition-post.md
Labels: area: azure/AAD, internal, ready to merge

#13433 Update requests to use Try It feature
  concepts/aad-advanced-queries.md
  concepts/query-parameters.md
  concepts/search-query-parameter.md
Labels: internal, ready to merge

#13149 Doc change notification for chat
  api-reference/beta/api/subscription-delete.md
  api-reference/beta/api/subscription-get.md
  api-reference/beta/api/subscription-post-subscriptions.md
  api-reference/beta/api/subscription-update.md
  api-reference/beta/resources/subscription.md
  api-reference/beta/resources/webhooks.md
  changelog/Microsoft.Teams.Core.json
  concepts/teams-changenotifications-chat.md
  concepts/teams-changenotifications-chatMembership.md
  concepts/toc.yml
  concepts/webhooks.md
Labels: internal, ready to merge, schema live

#13236 Add documents for CR grouping related resources and APIs
  api-reference/v1.0/api/call-answer.md
  api-reference/v1.0/resources/acceptjoinresponse.md
  api-reference/v1.0/resources/invitenewbotresponse.md
  api-reference/v1.0/resources/participantjoiningnotification.md
  api-reference/v1.0/resources/participantjoiningresponse.md
  api-reference/v1.0/resources/participantleftnotification.md
  api-reference/v1.0/resources/rejectjoinresponse.md
  changelog/Microsoft.Skype.Calling.json
Labels: internal, ready to merge

#13220 Add reupload API to cloudPcDeviceImage
  api-reference/beta/api/cloudpcdeviceimage-reupload.md
  api-reference/beta/resources/cloudpcdeviceimage.md
  api-reference/beta/toc.yml
  changelog/Microsoft.CloudManagedDesktop.json
Labels: content review complete, internal, ready to merge, schema live

#12960 Add three enums to CloudPcOnPremisesConnectionHealthCheckErrorType
  api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: content review complete, internal, ready to merge, schema live

#13434 Document query parameters for group properties
  api-reference/beta/resources/group.md
  api-reference/v1.0/resources/group.md
Labels: internal, ready to merge

#13440 Remove preview search note on Graph connector docs
  api-reference/beta/api/connectionoperation-get.md
  api-reference/beta/api/external-post-connections.md
  api-reference/beta/api/externalconnection-delete.md
  api-reference/beta/api/externalconnection-get.md
  api-reference/beta/api/externalconnection-list.md
  api-reference/beta/api/externalconnection-post-schema.md
  api-reference/beta/api/externalconnection-put-items.md
  api-reference/beta/api/externalconnection-update.md
  api-reference/beta/api/externalitem-delete.md
  api-reference/beta/api/externalitem-get.md
  api-reference/beta/api/externalitem-update.md
  api-reference/beta/api/schema-get.md
  api-reference/beta/resources/acl.md
  api-reference/beta/resources/configuration.md
  api-reference/beta/resources/externalconnection.md
  api-reference/beta/resources/externalfile.md
  api-reference/beta/resources/externalitem.md
  api-reference/beta/resources/externalitemcontent.md
  api-reference/beta/resources/indexing-api-overview.md
  api-reference/beta/resources/schema.md
Labels: internal, ready to merge

#13442 Document query parameters for application properties
  api-reference/beta/resources/application.md
  api-reference/v1.0/resources/application.md
Labels: internal, ready to merge

#13446 Document query parameters for device properties
  api-reference/beta/resources/device.md
  api-reference/v1.0/resources/device.md
Labels: internal, ready to merge

#13444 Document query parameters for servicePrincipal properties
  api-reference/beta/resources/serviceprincipal.md
  api-reference/v1.0/resources/serviceprincipal.md
Labels: internal, ready to merge

#13445 Document query parameters for orgContact properties
  api-reference/beta/resources/orgcontact.md
  api-reference/v1.0/resources/orgcontact.md
Labels: internal, ready to merge

#13448 Merge to publish.
  api-reference/beta/api/cloudpcdeviceimage-reupload.md
  api-reference/beta/api/connectionoperation-get.md
  api-reference/beta/api/external-post-connections.md
  api-reference/beta/api/externalconnection-delete.md
  api-reference/beta/api/externalconnection-get.md
  api-reference/beta/api/externalconnection-list.md
  api-reference/beta/api/externalconnection-post-schema.md
  api-reference/beta/api/externalconnection-put-items.md
  api-reference/beta/api/externalconnection-update.md
  api-reference/beta/api/externalitem-delete.md
  api-reference/beta/api/externalitem-get.md
  api-reference/beta/api/externalitem-update.md
  api-reference/beta/api/schema-get.md
  api-reference/beta/api/subscription-delete.md
  api-reference/beta/api/subscription-get.md
  api-reference/beta/api/subscription-post-subscriptions.md
  api-reference/beta/api/subscription-update.md
  api-reference/beta/resources/acl.md
  api-reference/beta/resources/application.md
  api-reference/beta/resources/cloudpcdeviceimage.md
  api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
  api-reference/beta/resources/configuration.md
  api-reference/beta/resources/device.md
  api-reference/beta/resources/externalconnection.md
  api-reference/beta/resources/externalfile.md
  api-reference/beta/resources/externalitem.md
  api-reference/beta/resources/externalitemcontent.md
  api-reference/beta/resources/group.md
  api-reference/beta/resources/indexing-api-overview.md
  api-reference/beta/resources/orgcontact.md
  api-reference/beta/resources/schema.md
  api-reference/beta/resources/serviceprincipal.md
  api-reference/beta/resources/subscription.md
  api-reference/beta/resources/webhooks.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/accessreviewscheduledefinition-post.md
  api-reference/v1.0/resources/application.md
  api-reference/v1.0/resources/device.md
  api-reference/v1.0/resources/group.md
  api-reference/v1.0/resources/orgcontact.md
  api-reference/v1.0/resources/serviceprincipal.md
  changelog/Microsoft.CloudManagedDesktop.json
  changelog/Microsoft.Teams.Core.json
  concepts/aad-advanced-queries.md
  concepts/query-parameters.md
  concepts/search-query-parameter.md
  concepts/teams-changenotifications-chat.md
  concepts/teams-changenotifications-chatMembership.md
  concepts/toc.yml
  concepts/webhooks.md
Labels: internal

#13467 Update projectrome-get-recent-activities.md
  api-reference/beta/api/projectrome-get-recent-activities.md
Labels: external

#13466 Update projectrome-delete-activity.md
  api-reference/beta/api/projectrome-delete-activity.md
Labels: external

#13464 Update projectrome-delete-activity.md
  api-reference/v1.0/api/projectrome-delete-activity.md
Labels: external

#13465 Update projectrome-get-recent-activities.md
  api-reference/v1.0/api/projectrome-get-recent-activities.md
Labels: external

#13462 Update columndefinition-get.md
  api-reference/beta/api/columndefinition-get.md
Labels: external

#13459 Search API - Clarificatrion on retrievable properties
  api-reference/beta/resources/search-api-overview.md
  api-reference/v1.0/resources/search-api-overview.md
  concepts/search-concept-files.md
  concepts/search-concept-overview.md
  concepts/toc.yml
Labels: internal, ready to merge

#13441 Introducing new Graph connector permissions
  concepts/permissions-reference.md
Labels: ready to merge

#13461 Add notes for ConsistencyLevel and $count - User resource
  api-reference/beta/api/user-list.md
  api-reference/beta/resources/user.md
  api-reference/v1.0/api/user-list.md
  api-reference/v1.0/resources/user.md
Labels: area: azure/AAD, area: users, internal, ready to merge

#13422 identity governance: add examples of adding resources and resource roles in entitlement management
  api-reference/beta/api/accesspackage-post-accesspackageresourcerolescopes.md
  api-reference/beta/api/accesspackageassignmentrequest-list.md
  api-reference/beta/api/accesspackagecatalog-list-accesspackageresourceroles.md
  api-reference/beta/api/accesspackageresourcerequest-post.md
  api-reference/beta/resources/accesspackageresourcerole.md
Labels: area: azure/AAD, internal, ready to merge, review feedback addressed

#13316 [CloudPC]Add permissionCheckNoResourceGroupNetworkContributorRole enum
  api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: content review complete, internal, ready to merge

#13187 add incompatible access package and group references to entitlement management accesspackage
  api-reference/beta/api/accesspackage-delete-incompatibleaccesspackage.md
  api-reference/beta/api/accesspackage-delete-incompatiblegroup.md
  api-reference/beta/api/accesspackage-list-accesspackagesincompatiblewith.md
  api-reference/beta/api/accesspackage-list-incompatibleaccesspackages.md
  api-reference/beta/api/accesspackage-list-incompatiblegroups.md
  api-reference/beta/api/accesspackage-post-incompatibleaccesspackage.md
  api-reference/beta/api/accesspackage-post-incompatiblegroup.md
  api-reference/beta/api/accesspackage-post.md
  api-reference/beta/resources/accesspackage.md
  api-reference/beta/resources/entitlementmanagement-root.md
  api-reference/beta/toc.yml
  changelog/Microsoft.DirectoryServices.json
Labels: area: azure/AAD, internal, ready to merge, review feedback addressed

#12490 Add OAuth secret types
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/synchronization-secretkeystringvaluepair.md
  changelog/Microsoft.DirectoryServices.json
Labels: area: azure/AAD, internal, ready to merge

#13059 Added new property and delete APIs
  api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md
  api-reference/beta/api/mobileappmanagementpolicies-delete.md
  api-reference/beta/api/mobileappmanagementpolicies-get.md
  api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md
  api-reference/beta/api/mobileappmanagementpolicies-list.md
  api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md
  api-reference/beta/api/mobileappmanagementpolicies-update.md
  api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md
  api-reference/beta/api/mobiledevicemanagementpolicies-delete.md
  api-reference/beta/api/mobiledevicemanagementpolicies-get.md
  api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md
  api-reference/beta/api/mobiledevicemanagementpolicies-list.md
  api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md
  api-reference/beta/api/mobiledevicemanagementpolicies-update.md
  api-reference/beta/resources/mobilitymanagementpolicy.md
  api-reference/beta/toc.yml
  changelog/Microsoft.MobilityService.json
Labels: content review complete, internal, ready to merge

#13484 Update contenttype-list-columns.md
  api-reference/beta/api/contenttype-list-columns.md
Labels: external

#13489 Update contenttype-post-columns.md
  api-reference/beta/api/contenttype-post-columns.md
Labels: external

#13416 Updating docs, adding and fixing examples for Microsoft Teams
  api-reference/beta/api/chat-post-members.md
  api-reference/beta/api/chatmessage-post.md
  api-reference/v1.0/api/chat-post-members.md
  api-reference/v1.0/api/chatmessage-post.md
  concepts/teams-activity-feed-notifications-best-practices.md
  concepts/teams-change-notification-in-microsoft-teams-overview.md
  concepts/teams-send-activityfeednotifications.md
  concepts/toc.yml
Labels: internal, ready to merge

#13471 Fix invalid date format
  changelog/Microsoft.CloudManagedDesktop.json
Labels: internal, ready to merge

#13493 Retarget Master to Main
  api-reference/v1.0/api/call-answer.md
  api-reference/v1.0/resources/acceptjoinresponse.md
  api-reference/v1.0/resources/invitenewbotresponse.md
  api-reference/v1.0/resources/participantjoiningnotification.md
  api-reference/v1.0/resources/participantjoiningresponse.md
  api-reference/v1.0/resources/participantleftnotification.md
  api-reference/v1.0/resources/rejectjoinresponse.md
  changelog/Microsoft.Skype.Calling.json
Labels: internal, ready to merge

#13481 Recreated Postman screenshot
  concepts/images/postman-screenshot.png
  concepts/use-postman.md
Labels: internal, ready to merge

#13494 Update throttling.md
  concepts/throttling.md
Labels: internal, ready to merge

#13483 Add notes for ConsistencyLevel and count - device resource
  api-reference/beta/api/device-list.md
  api-reference/beta/resources/device.md
  api-reference/v1.0/api/device-list.md
  api-reference/v1.0/resources/device.md
Labels: area: Odata, area: azure/AAD, internal, ready to merge

#13478 Add notes for ConsistencyLevel and - orgContact resource
  api-reference/beta/api/orgcontact-list.md
  api-reference/beta/resources/orgcontact.md
  api-reference/v1.0/api/orgcontact-list.md
  api-reference/v1.0/resources/orgcontact.md
Labels: area: Odata, area: azure/AAD, internal, ready to merge

#13476 Add notes for ConsistencyLevel and $count - servicePrincipal resource
  api-reference/beta/api/serviceprincipal-list.md
  api-reference/beta/resources/serviceprincipal.md
  api-reference/v1.0/api/serviceprincipal-list.md
  api-reference/v1.0/resources/serviceprincipal.md
Labels: area: Odata, area: azure/AAD, internal, ready to merge

#13475 Add notes for ConsistencyLevel and $count - Application resource
  api-reference/beta/api/application-list.md
  api-reference/beta/resources/application.md
  api-reference/v1.0/api/application-list.md
  api-reference/v1.0/resources/application.md
Labels: area: Odata, area: azure/AAD, internal, ready to merge

#13474 Add notes for ConsistencyLevel and $count - Group resource
  api-reference/beta/api/group-list.md
  api-reference/beta/resources/group.md
  api-reference/v1.0/api/group-list.md
  api-reference/v1.0/resources/group.md
Labels: area: Odata, area: azure/AAD, area: groups, internal, ready to merge

#13495 Merge to publish.
  api-reference/beta/api/application-list.md
  api-reference/beta/api/chat-post-members.md
  api-reference/beta/api/chatmessage-post.md
  api-reference/beta/api/contenttype-list-columns.md
  api-reference/beta/api/contenttype-post-columns.md
  api-reference/beta/api/device-list.md
  api-reference/beta/api/group-list.md
  api-reference/beta/api/orgcontact-list.md
  api-reference/beta/api/serviceprincipal-list.md
  api-reference/beta/resources/application.md
  api-reference/beta/resources/device.md
  api-reference/beta/resources/group.md
  api-reference/beta/resources/orgcontact.md
  api-reference/beta/resources/serviceprincipal.md
  api-reference/v1.0/api/application-list.md
  api-reference/v1.0/api/call-answer.md
  api-reference/v1.0/api/chat-post-members.md
  api-reference/v1.0/api/chatmessage-post.md
  api-reference/v1.0/api/device-list.md
  api-reference/v1.0/api/group-list.md
  api-reference/v1.0/api/orgcontact-list.md
  api-reference/v1.0/api/serviceprincipal-list.md
  api-reference/v1.0/resources/acceptjoinresponse.md
  api-reference/v1.0/resources/application.md
  api-reference/v1.0/resources/device.md
  api-reference/v1.0/resources/group.md
  api-reference/v1.0/resources/invitenewbotresponse.md
  api-reference/v1.0/resources/orgcontact.md
  api-reference/v1.0/resources/participantjoiningnotification.md
  api-reference/v1.0/resources/participantjoiningresponse.md
  api-reference/v1.0/resources/participantleftnotification.md
  api-reference/v1.0/resources/rejectjoinresponse.md
  api-reference/v1.0/resources/serviceprincipal.md
  changelog/Microsoft.CloudManagedDesktop.json
  changelog/Microsoft.Skype.Calling.json
  concepts/images/postman-screenshot.png
  concepts/teams-activity-feed-notifications-best-practices.md
  concepts/teams-change-notification-in-microsoft-teams-overview.md
  concepts/teams-send-activityfeednotifications.md
  concepts/throttling.md
  concepts/toc.yml
  concepts/use-postman.md
Labels: internal

#13512 Update driveitem-createuploadsession.md
  api-reference/beta/api/driveitem-createuploadsession.md
Labels: external

#13511 Update driveitem-createuploadsession.md
  api-reference/v1.0/api/driveitem-createuploadsession.md
Labels: external

#13510 Update educationresource.md
  api-reference/v1.0/resources/educationresource.md
Labels: external

#13509 Update educationresource.md
  api-reference/beta/resources/educationresource.md
Labels: external

#13488 Update contenttype-copytodefaultcontentlocation.md
  api-reference/beta/api/contenttype-copytodefaultcontentlocation.md
Labels: external

#13487 Update contenttype-delete.md
  api-reference/beta/api/contenttype-delete.md
Labels: external

#13486 Update contenttype-associatewithhubsites.md
  api-reference/beta/api/contenttype-associatewithhubsites.md
Labels: external

#13485 Update contenttype-ispublished.md
  api-reference/beta/api/contenttype-ispublished.md
Labels: external

#13508 Update educationassignment-post-resources.md
  api-reference/beta/api/educationassignment-post-resources.md
Labels: external

#13499 Content health pass - query parameters
  concepts/aad-advanced-queries.md
  concepts/query-parameters.md
  concepts/search-query-parameter.md
Labels: area: Odata, area: azure/AAD, internal, ready to merge

#13515 What's been added in the last two weeks.
  api-reference/beta/resources/subscription.md
  api-reference/v1.0/resources/subscription.md
  changelog/Microsoft.MicrosoftSearch.json
  concepts/overview-major-services.md
  concepts/search-concept-overview.md
  concepts/search-concept-person.md
  concepts/toc.yml
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: internal, ready to merge

#13102 added countrylookupmethod to v1 docs
  api-reference/v1.0/resources/countrynamedlocation.md
  api-reference/v1.0/resources/enums.md
  changelog/Microsoft.DirectoryServices.json
Labels: area: azure/AAD, content review complete, internal, ready to merge

#11591 Update auth-limit-mailbox-access.md
  concepts/auth-limit-mailbox-access.md
Labels: external, review requested

#13395 Incorporate external and internal feedback to add EWS support for application access policy.
  concepts/auth-limit-mailbox-access.md
Labels: customer support issue, do not merge, internal

#13091 Added Examples for calling site collection termstore APIs
  api-reference/beta/api/termstore-group-get.md
  api-reference/beta/api/termstore-set-get.md
  api-reference/beta/api/termstore-store-get.md
  api-reference/beta/api/termstore-term-get.md
  api-reference/beta/resources/termstore-group.md
  api-reference/beta/toc.yml
Labels: content review complete, internal, ready to merge, review feedback addressed, schema live

#13518 Add reference to Azure AD password policies
  api-reference/beta/resources/user.md
  api-reference/v1.0/resources/user.md
Labels: area: azure/AAD, internal, ready to merge

#13521 Document query parameters supported by schemaExtension
  api-reference/beta/resources/schemaextension.md
  api-reference/v1.0/resources/schemaextension.md
Labels: internal, ready to merge

#13531 Update channel-list-messages.md
  api-reference/v1.0/api/channel-list-messages.md
Labels: external

#13530 Update columndefinition.md
  api-reference/beta/resources/columndefinition.md
Labels: external

#13537 Merge to publish.
  api-reference/beta/api/termstore-group-get.md
  api-reference/beta/api/termstore-set-get.md
  api-reference/beta/api/termstore-store-get.md
  api-reference/beta/api/termstore-term-get.md
  api-reference/beta/resources/columndefinition.md
  api-reference/beta/resources/schemaextension.md
  api-reference/beta/resources/termstore-group.md
  api-reference/beta/resources/user.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/channel-list-messages.md
  api-reference/v1.0/resources/schemaextension.md
  api-reference/v1.0/resources/user.md
  concepts/auth-limit-mailbox-access.md
Labels: internal

#13162 Adding ExternalItem to Graph v1.0
  api-reference/v1.0/api/externalconnectors-connectionoperation-get.md
  api-reference/v1.0/api/externalconnectors-external-post-connections.md
  api-reference/v1.0/api/externalconnectors-externalconnection-delete.md
  api-reference/v1.0/api/externalconnectors-externalconnection-get.md
  api-reference/v1.0/api/externalconnectors-externalconnection-list.md
  api-reference/v1.0/api/externalconnectors-externalconnection-update.md
  api-reference/v1.0/api/externalconnectors-externalitem-create.md
  api-reference/v1.0/api/externalconnectors-externalitem-delete.md
  api-reference/v1.0/api/externalconnectors-externalitem-get.md
  api-reference/v1.0/api/externalconnectors-externalitem-update.md
  api-reference/v1.0/api/externalconnectors-schema-create.md
  api-reference/v1.0/api/externalconnectors-schema-get.md
  api-reference/v1.0/resources/enums-externalConnectors.md
  api-reference/v1.0/resources/externalconnectors-acl.md
  api-reference/v1.0/resources/externalconnectors-configuration.md
  api-reference/v1.0/resources/externalconnectors-connectionoperation.md
  api-reference/v1.0/resources/externalconnectors-externalconnection.md
  api-reference/v1.0/resources/externalconnectors-externalitem.md
  api-reference/v1.0/resources/externalconnectors-externalitemcontent.md
  api-reference/v1.0/resources/externalconnectors-properties.md
  api-reference/v1.0/resources/externalconnectors-property.md
  api-reference/v1.0/resources/externalconnectors-schema.md
  api-reference/v1.0/resources/indexing-api-overview.md
  api-reference/v1.0/resources/publicerror.md
  api-reference/v1.0/resources/publicerrordetail.md
  api-reference/v1.0/resources/publicinnererror.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.Search.json
Labels: content review, do not merge, internal, schema live

#13529 add connectedOrganization relationship to accessPackageSubject
  api-reference/beta/api/accesspackageassignmentrequest-list.md
  api-reference/beta/resources/accesspackagesubject.md
Labels: area: azure/AAD, content review complete, internal, ready to merge, review feedback addressed

#13542 accesspackageassignmentpolicy update example payload
  api-reference/beta/api/accesspackageassignmentpolicy-post.md
  api-reference/beta/api/accesspackageassignmentpolicy-update.md
Labels: area: azure/AAD, internal, ready to merge

#13506 add guidance on retrieving access package resource scopes
  api-reference/beta/api/accesspackage-post-accesspackageresourcerolescopes.md
  api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md
  api-reference/beta/resources/accesspackageresource.md
  api-reference/beta/resources/accesspackageresourcescope.md
Labels: area: azure/AAD, content review complete, internal, ready to merge

#13547 Update contenttype-publish.md
  api-reference/beta/api/contenttype-publish.md
Labels: external

#13546 Update sitepage-list.md
  api-reference/beta/api/sitepage-list.md
Labels: external

#13550 Added example of a frequently inquired scenario
  concepts/cloud-communication-online-meeting-application-access-policy.md
Labels: content review, internal, ready to merge

#13085 Teams - Messaging APIs system event messages support
  api-reference/beta/api/channel-getallmessages.md
  api-reference/beta/api/channel-list-messages.md
  api-reference/beta/api/channel-post-messages.md
  api-reference/beta/api/chat-list-messages.md
  api-reference/beta/api/chat-post-messages.md
  api-reference/beta/api/chatmessage-delta.md
  api-reference/beta/api/chatmessage-get.md
  api-reference/beta/api/chatmessage-list-replies.md
  api-reference/beta/api/chatmessage-post-replies.md
  api-reference/beta/api/chatmessage-post.md
  api-reference/beta/api/chats-getallmessages.md
  api-reference/beta/resources/callendedeventmessagedetail.md
  api-reference/beta/resources/callparticipantinfo.md
  api-reference/beta/resources/callrecordingeventmessagedetail.md
  api-reference/beta/resources/callstartedeventmessagedetail.md
  api-reference/beta/resources/calltranscripteventmessagedetail.md
  api-reference/beta/resources/channeladdedeventmessagedetail.md
  api-reference/beta/resources/channeldeletedeventmessagedetail.md
  api-reference/beta/resources/channeldescriptionupdatedeventmessagedetail.md
  api-reference/beta/resources/channelrenamedeventmessagedetail.md
  api-reference/beta/resources/channelsetasfavoritebydefaulteventmessagedetail.md
  api-reference/beta/resources/channelunsetasfavoritebydefaulteventmessagedetail.md
  api-reference/beta/resources/chatmessage.md
  api-reference/beta/resources/chatrenamedeventmessagedetail.md
  api-reference/beta/resources/conversationmemberroleupdatedeventmessagedetail.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/eventmessagedetail.md
  api-reference/beta/resources/meetingpolicyupdatedeventmessagedetail.md
  api-reference/beta/resources/membersaddedeventmessagedetail.md
  api-reference/beta/resources/membersdeletedeventmessagedetail.md
  api-reference/beta/resources/membersjoinedeventmessagedetail.md
  api-reference/beta/resources/memberslefteventmessagedetail.md
  api-reference/beta/resources/tabupdatedeventmessagedetail.md
  api-reference/beta/resources/teamarchivedeventmessagedetail.md
  api-reference/beta/resources/teamcreatedeventmessagedetail.md
  api-reference/beta/resources/teamdescriptionupdatedeventmessagedetail.md
  api-reference/beta/resources/teamjoiningdisabledeventmessagedetail.md
  api-reference/beta/resources/teamjoiningenabledeventmessagedetail.md
  api-reference/beta/resources/teamrenamedeventmessagedetail.md
  api-reference/beta/resources/teamsappinstalledeventmessagedetail.md
  api-reference/beta/resources/teamsappremovedeventmessagedetail.md
  api-reference/beta/resources/teamsappupgradedeventmessagedetail.md
  api-reference/beta/resources/teamunarchivedeventmessagedetail.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Teams.Core.json
  concepts/system-messages.md
  concepts/toc.yml
Labels: content review in progress, internal, ready to merge, review feedback addressed, schema live

#13566 [Intune] Examples link fix
  concepts/intune-concept-overview.md
Labels: area: intune, internal, ready to merge

#13569 update AR v2 beta disclaimer text
  api-reference/includes/accessreviews-disclaimer-v2.md
Labels: area: azure/AAD, ready to merge

#13413 Add access review error
  api-reference/beta/resources/accessreviewerror.md
  api-reference/beta/resources/accessreviewinstance.md
  changelog/Microsoft.IdentityGovernance.AccessReviews.json
Labels: area: azure/AAD, content review complete, ready to merge

#13560 Update overview.md
  api-reference/v1.0/overview.md
Labels: external

#13559 Update overview.md
  api-reference/beta/overview.md
Labels: external

#13490 Added new properties in education profile status API
  api-reference/beta/api/educationsynchronizationprofilestatus-get.md
  api-reference/beta/resources/educationsynchronizationprofilestatus.md
  api-reference/beta/resources/enums.md
  changelog/Microsoft.EducationDataSync.json
Labels: area: edu, content review complete, internal, ready to merge

#13563 Fixing the Search beta changelog entry
  changelog/Microsoft.Search.json
Labels: internal, ready to merge, schema live

#13584 Update teams-activity-feed-notifications-best-practices.md
  concepts/teams-activity-feed-notifications-best-practices.md
Labels: external

#13581 Update conversationthread-get.md
  api-reference/v1.0/api/conversationthread-get.md
Labels: external

#13576 Rephrase a sentence
  concepts/azuread-identity-access-management-concept-overview.md
Labels: external

#13453 [Action Needed] Change naming from cloud PC to Cloud PC
  api-reference/beta/api/cloudpc-reprovision.md
  api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md
  api-reference/beta/api/cloudpcprovisioningpolicy-assign.md
  api-reference/beta/api/cloudpcprovisioningpolicy-update.md
  api-reference/beta/api/cloudpcusersetting-assign.md
  api-reference/beta/api/rbacapplication-list-roledefinitions.md
  api-reference/beta/api/rbacapplicationmultiple-list-roleassignments.md
  api-reference/beta/api/rbacapplicationmultiple-post-roleassignments.md
  api-reference/beta/api/unifiedroleassignmentmultiple-delete.md
  api-reference/beta/api/unifiedroleassignmentmultiple-get.md
  api-reference/beta/api/unifiedroleassignmentmultiple-update.md
  api-reference/beta/api/unifiedroledefinition-get.md
  api-reference/beta/api/virtualendpoint-geteffectivepermissions.md
  api-reference/beta/api/virtualendpoint-list-deviceimages.md
  api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md
  api-reference/beta/api/virtualendpoint-post-deviceimages.md
  api-reference/beta/api/virtualendpoint-post-onpremisesconnections.md
  api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md
  api-reference/beta/resources/cloudpc.md
  api-reference/beta/resources/cloudpcdeviceimage.md
  api-reference/beta/resources/cloudpconpremisesconnection.md
  api-reference/beta/resources/cloudpcprovisioningpolicy.md
  api-reference/beta/resources/cloudpcusersetting.md
  api-reference/beta/resources/rolemanagement.md
  api-reference/beta/resources/unifiedroleassignmentmultiple.md
  api-reference/beta/resources/unifiedroledefinition.md
  api-reference/beta/resources/virtualendpoint.md
  api-reference/includes/cloudpc-api-preview.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: content review complete, internal, ready to merge

#12975 Updated previously required request headers to now be optional
  api-reference/beta/api/bitlocker-list-recoverykeys.md
  api-reference/beta/api/bitlockerrecoverykey-get.md
  changelog/Microsoft.BitLocker.json
Labels: content review complete, internal, ready to merge

#13193 Adding a new element to the Learning paths section in the hub page
  concepts/index.yml
Labels: internal, ready to merge

#13460 Adding Teams Chat dataset to docs
  concepts/data-connect-datasets.md
Labels: internal, schema live

#13359 upload resource - concept added
  concepts/education-upload-resource-overview.md
  concepts/toc.yml
Labels: content review complete, internal, ready to merge, schema live

#13594 Merge to publish.
  api-reference/beta/api/bitlocker-list-recoverykeys.md
  api-reference/beta/api/bitlockerrecoverykey-get.md
  api-reference/beta/api/cloudpc-reprovision.md
  api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md
  api-reference/beta/api/cloudpcprovisioningpolicy-assign.md
  api-reference/beta/api/cloudpcprovisioningpolicy-update.md
  api-reference/beta/api/cloudpcusersetting-assign.md
  api-reference/beta/api/rbacapplication-list-roledefinitions.md
  api-reference/beta/api/rbacapplicationmultiple-list-roleassignments.md
  api-reference/beta/api/rbacapplicationmultiple-post-roleassignments.md
  api-reference/beta/api/unifiedroleassignmentmultiple-delete.md
  api-reference/beta/api/unifiedroleassignmentmultiple-get.md
  api-reference/beta/api/unifiedroleassignmentmultiple-update.md
  api-reference/beta/api/unifiedroledefinition-get.md
  api-reference/beta/api/virtualendpoint-geteffectivepermissions.md
  api-reference/beta/api/virtualendpoint-list-deviceimages.md
  api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md
  api-reference/beta/api/virtualendpoint-post-deviceimages.md
  api-reference/beta/api/virtualendpoint-post-onpremisesconnections.md
  api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md
  api-reference/beta/resources/cloudpc.md
  api-reference/beta/resources/cloudpcdeviceimage.md
  api-reference/beta/resources/cloudpconpremisesconnection.md
  api-reference/beta/resources/cloudpcprovisioningpolicy.md
  api-reference/beta/resources/cloudpcusersetting.md
  api-reference/beta/resources/rolemanagement.md
  api-reference/beta/resources/unifiedroleassignmentmultiple.md
  api-reference/beta/resources/unifiedroledefinition.md
  api-reference/beta/resources/virtualendpoint.md
  api-reference/includes/cloudpc-api-preview.md
  api-reference/v1.0/api/conversationthread-get.md
  changelog/Microsoft.BitLocker.json
  changelog/Microsoft.CloudManagedDesktop.json
  concepts/azuread-identity-access-management-concept-overview.md
  concepts/data-connect-datasets.md
  concepts/education-upload-resource-overview.md
  concepts/index.yml
  concepts/teams-activity-feed-notifications-best-practices.md
  concepts/toc.yml
Labels: internal

#13606 Change note on accent characters
  api-reference/beta/resources/user.md
  api-reference/v1.0/resources/user.md
Labels: area: azure/AAD, internal, ready to merge

#13604 Fixed Request body
  api-reference/beta/api/sitepage-create.md
Labels: external

#13603 Minor fix to doc scope
  concepts/aad-advanced-queries.md
Labels: area: azure/AAD, area: query, internal, ready to merge

#13491 Update teamworktag.md to have post teamworktagmember link
  api-reference/beta/api/teamworktagmember-post.md
  api-reference/beta/resources/teams-api-overview.md
  api-reference/beta/resources/teamworktag.md
  api-reference/beta/resources/teamworktagmember.md
  api-reference/beta/toc.yml
Labels: internal, ready to merge

#13600 Update workbook-error-handling.md
  concepts/workbook-error-handling.md
Labels: area: excel, internal, ready to merge

#13610 Merge to publish.
  api-reference/beta/api/sitepage-create.md
  api-reference/beta/api/teamworktagmember-post.md
  api-reference/beta/resources/teams-api-overview.md
  api-reference/beta/resources/teamworktag.md
  api-reference/beta/resources/teamworktagmember.md
  api-reference/beta/resources/user.md
  api-reference/beta/toc.yml
  api-reference/v1.0/resources/user.md
  concepts/aad-advanced-queries.md
  concepts/workbook-error-handling.md
Labels: internal

#13618 Update application-post-calls.md
  api-reference/v1.0/api/application-post-calls.md
Labels: content review, internal, ready to merge

#13599 Remove instances from accessReviewScheduleDefinition sub-node
  api-reference/v1.0/resources/accessreviewscheduledefinition.md
  api-reference/v1.0/toc.yml
Labels: area: azure/AAD, internal, ready to merge

#13523 Add details about response object
  api-reference/beta/api/user-list-joinedteams.md
  api-reference/v1.0/api/user-list-joinedteams.md
  concepts/known-issues.md
Labels: ready to merge

#13621 Resolve #11770, format JSON
  api-reference/beta/api/accesspackageassignmentrequest-post.md
Labels: area: azure/AAD, ready to merge

#13622 Resolve #12364, clean up JSON
  api-reference/beta/api/conversationthread-update.md
  api-reference/v1.0/api/conversationthread-update.md
Labels: area: azure/AAD, internal, ready to merge

#13623 Resolve #12675, correct property name
  api-reference/v1.0/resources/preauthorizedapplication.md
Labels: area: azure/AAD, internal, ready to merge

#13624 Resolve #12780, minor doc fixes
  api-reference/beta/api/identityproviderbase-get.md
  api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md
  api-reference/beta/api/identityproviderbase-list.md
  api-reference/beta/api/identityproviderbase-post-identityproviders.md
  api-reference/beta/api/identityproviderbase-update.md
  api-reference/beta/api/identityproviderbase.md
  api-reference/beta/resources/openidconnectidentityprovider.md
  api-reference/beta/resources/socialidentityprovider.md
  api-reference/includes/identityprovider-deprecate.md
  api-reference/v1.0/api/identityproviderbase-list.md
  api-reference/v1.0/api/identityproviderbase-update.md
Labels: area: azure/AAD, internal, ready to merge

#13626 Resolve #13557, #13555 - add odata.type
  api-reference/beta/api/b2cidentityuserflow-userflowidentityproviders-update.md
  api-reference/beta/api/b2xidentityuserflow-userflowidentityproviders-update.md
Labels: area: azure/AAD, internal, ready to merge

#13627 Clean up example
  api-reference/beta/api/domain-list-domainnamereferences.md
  api-reference/v1.0/api/domain-list-domainnamereferences.md
Labels: area: azure/AAD, internal, ready to merge

#13631 Add docs for DelegatedPermissionGrant.ReadWrite.All
  concepts/permissions-reference.md
Labels: area: app model, internal, ready to merge

#13633 Reporting APIs require Directory.Read.All + AuditLog.Read.All
  api-reference/beta/api/directoryaudit-get.md
  api-reference/beta/api/directoryaudit-list.md
  api-reference/beta/api/signin-get.md
  api-reference/beta/api/signin-list.md
  api-reference/v1.0/api/directoryaudit-get.md
  api-reference/v1.0/api/directoryaudit-list.md
Labels: area: azure/AAD, internal, ready to merge

#13634 Resolves #13574 - Extra permission is required
  api-reference/beta/api/user-post-approleassignments.md
  api-reference/v1.0/api/user-post-approleassignments.md
Labels: internal, ready to merge

#13635 Replace placeholder response
  api-reference/beta/api/conversationthread-list-posts.md
  api-reference/v1.0/api/conversationthread-list-posts.md
Labels: area: azure/AAD, internal, ready to merge

#13636 Resolve #12814
  api-reference/beta/api/unifiedrolemanagementpolicyrule-update.md
  api-reference/beta/resources/unifiedrolemanagementpolicyruletarget.md
Labels: internal, ready to merge

#13637 Resolves #12806, Add lesser privileged Application.ReadWrite.OwnedBy permission
  api-reference/beta/api/serviceprincipal-list-ownedobjects.md
  api-reference/v1.0/api/serviceprincipal-list-ownedobjects.md
Labels: internal, ready to merge

#13657 Update conversationthread.md
  api-reference/beta/resources/conversationthread.md
Labels: content review, external, ready to merge

#13418 Application auth method policies
  api-reference/beta/api/appManagementPolicy-delete.md
  api-reference/beta/api/appManagementPolicy-get.md
  api-reference/beta/api/appManagementPolicy-list-appliesTo.md
  api-reference/beta/api/appManagementPolicy-list.md
  api-reference/beta/api/appManagementPolicy-post-appliesto.md
  api-reference/beta/api/appManagementPolicy-post.md
  api-reference/beta/api/appManagementPolicy-update.md
  api-reference/beta/api/tenantAppManagementPolicy-get.md
  api-reference/beta/api/tenantAppManagementPolicy-update.md
  api-reference/beta/resources/appManagementConfiguration.md
  api-reference/beta/resources/appManagementPolicy.md
  api-reference/beta/resources/application.md
  api-reference/beta/resources/applicationAuthMethodPolicy.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/passwordCredentialConfiguration.md
  api-reference/beta/resources/policy-overview.md
  api-reference/beta/resources/serviceprincipal.md
  api-reference/beta/resources/tenantAppManagementPolicy.md
  api-reference/beta/toc.yml
  changelog/Microsoft.DirectoryServices.json
Labels: area: azure/AAD, content review complete, internal, ready to merge

#13659 AD Graph alert box: Important >>> Warning
  concepts/migrate-azure-ad-graph-planning-checklist.md
Labels: do not merge, internal

#13672 Pulling in latest PRs from main to go live
  api-reference/beta/api/appManagementPolicy-delete.md
  api-reference/beta/api/appManagementPolicy-get.md
  api-reference/beta/api/appManagementPolicy-list-appliesTo.md
  api-reference/beta/api/appManagementPolicy-list.md
  api-reference/beta/api/appManagementPolicy-post-appliesto.md
  api-reference/beta/api/appManagementPolicy-post.md
  api-reference/beta/api/appManagementPolicy-update.md
  api-reference/beta/api/tenantAppManagementPolicy-get.md
  api-reference/beta/api/tenantAppManagementPolicy-update.md
  api-reference/beta/resources/appManagementConfiguration.md
  api-reference/beta/resources/appManagementPolicy.md
  api-reference/beta/resources/application.md
  api-reference/beta/resources/applicationAuthMethodPolicy.md
  api-reference/beta/resources/conversationthread.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/passwordCredentialConfiguration.md
  api-reference/beta/resources/policy-overview.md
  api-reference/beta/resources/serviceprincipal.md
  api-reference/beta/resources/tenantAppManagementPolicy.md
  api-reference/beta/toc.yml
  changelog/Microsoft.DirectoryServices.json
  concepts/migrate-azure-ad-graph-planning-checklist.md
Labels: internal
