Repository microsoftgraph/microsoft-graph-docs, pull requests merged in 2021-02, with the labels that each got.

#11484 Changing one screenshot that showed my email address
  concepts/graph-explorer/graph-explorer-features.md
  concepts/graph-explorer/images/get-graph-toolkit-card.PNG
Labels: internal, ready to merge

#11488 Update sharepoint.md
  concepts/toolkit/providers/sharepoint.md
Labels: external

#11478 Update build-a-microsoft-teams-tab.md
  concepts/toolkit/get-started/build-a-microsoft-teams-tab.md
Labels: external

#11475 Specify a concrete odata.type for the abstract "attachment" type
  api-reference/beta/api/post-reply.md
  api-reference/beta/includes/snippets/csharp/post-reply-csharp-snippets.md
  api-reference/beta/includes/snippets/java/post-reply-java-snippets.md
  api-reference/beta/includes/snippets/javascript/post-reply-javascript-snippets.md
  api-reference/v1.0/api/post-reply.md
  api-reference/v1.0/includes/snippets/csharp/post-reply-csharp-snippets.md
  api-reference/v1.0/includes/snippets/java/post-reply-java-snippets.md
  api-reference/v1.0/includes/snippets/javascript/post-reply-javascript-snippets.md
Labels: internal, ready to merge

#11490 Merge to publish.
  api-reference/beta/api/post-reply.md
  api-reference/beta/includes/snippets/csharp/post-reply-csharp-snippets.md
  api-reference/beta/includes/snippets/java/post-reply-java-snippets.md
  api-reference/beta/includes/snippets/javascript/post-reply-javascript-snippets.md
  api-reference/v1.0/api/post-reply.md
  api-reference/v1.0/includes/snippets/csharp/post-reply-csharp-snippets.md
  api-reference/v1.0/includes/snippets/java/post-reply-java-snippets.md
  api-reference/v1.0/includes/snippets/javascript/post-reply-javascript-snippets.md
  concepts/graph-explorer/graph-explorer-features.md
  concepts/graph-explorer/images/get-graph-toolkit-card.PNG
  concepts/toolkit/get-started/build-a-microsoft-teams-tab.md
  concepts/toolkit/providers/sharepoint.md
Labels: internal

#11477 Addressed higher privileges in combo topics. Added best practices to request least privileged permissions.
  api-reference/beta/api/attachment-delete.md
  api-reference/beta/api/attachment-get.md
  api-reference/beta/api/opentypeextension-delete.md
  api-reference/beta/api/opentypeextension-get.md
  api-reference/beta/api/opentypeextension-post-opentypeextension.md
  api-reference/beta/api/opentypeextension-update.md
  api-reference/beta/api/subscription-delete.md
  api-reference/beta/api/subscription-get.md
  api-reference/beta/api/subscription-post-subscriptions.md
  api-reference/beta/api/subscription-update.md
  api-reference/beta/resources/opentypeextension.md
  api-reference/v1.0/api/attachment-delete.md
  api-reference/v1.0/api/attachment-get.md
  api-reference/v1.0/api/opentypeextension-delete.md
  api-reference/v1.0/api/opentypeextension-get.md
  api-reference/v1.0/api/opentypeextension-post-opentypeextension.md
  api-reference/v1.0/api/opentypeextension-update.md
  api-reference/v1.0/api/subscription-delete.md
  api-reference/v1.0/api/subscription-get.md
  api-reference/v1.0/api/subscription-post-subscriptions.md
  api-reference/v1.0/api/subscription-update.md
  api-reference/v1.0/resources/opentypeextension.md
  concepts/auth/auth-concepts.md
  concepts/permissions-reference.md
  includes/auth-use-least-privileged.md
Labels: do not merge, internal

#11493 Adding note about permission for upcoming feature
  concepts/permissions-reference.md
Labels: internal, ready to merge

#11507 Update proxy.md
  concepts/toolkit/providers/proxy.md
Labels: external

#11512 Updates quickstart use MGT with React. Closes #11105
  concepts/toolkit/get-started/use-toolkit-with-react.md
Labels: ready to merge

#11515 Update get.md
  concepts/toolkit/components/get.md
Labels: external

#11506 Fixing documentation for messaging and activity feed notifications
  api-reference/beta/api/channel-post-message.md
  api-reference/beta/api/channel-post-messagereply.md
  api-reference/beta/api/team-post.md
  concepts/teams-changenotifications-chatmessage.md
  concepts/teams-send-activityfeednotifications.md
Labels: internal, ready to merge

#11520 Merge to publish.
  api-reference/beta/api/channel-post-message.md
  api-reference/beta/api/channel-post-messagereply.md
  api-reference/beta/api/team-post.md
  api-reference/beta/includes/snippets/csharp/create-event-recurring-daily-csharp-snippets.md
  api-reference/beta/includes/snippets/csharp/create-item-attachment-from-event-csharp-snippets.md
  api-reference/beta/includes/snippets/csharp/create-item-attachment-from-message-beta-csharp-snippets.md
  api-reference/beta/includes/snippets/csharp/create-item-attachment-with-post-csharp-snippets.md
  api-reference/beta/includes/snippets/csharp/create-trustframeworkkeyset-from-trustframework1-csharp-snippets.md
  api-reference/beta/includes/snippets/csharp/event-delta-events-csharp-snippets.md
  api-reference/beta/includes/snippets/csharp/get-printjob-withtasks-csharp-snippets.md
  api-reference/beta/includes/snippets/java/create-event-recurring-daily-java-snippets.md
  api-reference/beta/includes/snippets/java/create-item-attachment-from-event-java-snippets.md
  api-reference/beta/includes/snippets/java/create-item-attachment-from-message-beta-java-snippets.md
  api-reference/beta/includes/snippets/java/create-item-attachment-with-post-java-snippets.md
  api-reference/beta/includes/snippets/java/create-trustframeworkkeyset-from-trustframework1-java-snippets.md
  api-reference/beta/includes/snippets/java/event-delta-events-java-snippets.md
  api-reference/beta/includes/snippets/java/get-printjob-withtasks-java-snippets.md
  api-reference/beta/includes/snippets/javascript/create-event-recurring-daily-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/create-item-attachment-from-event-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/create-item-attachment-from-message-beta-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/create-item-attachment-with-post-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/create-trustframeworkkeyset-from-trustframework1-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/event-delta-events-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/get-printjob-withtasks-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/update-authzpolicy-guestuserlevel-javascript-snippets.md
  api-reference/beta/includes/snippets/objc/create-event-recurring-daily-objc-snippets.md
  api-reference/beta/includes/snippets/objc/create-item-attachment-from-event-objc-snippets.md
  api-reference/beta/includes/snippets/objc/create-item-attachment-from-message-beta-objc-snippets.md
  api-reference/beta/includes/snippets/objc/create-item-attachment-with-post-objc-snippets.md
  api-reference/beta/includes/snippets/objc/create-trustframeworkkeyset-from-trustframework1-objc-snippets.md
  api-reference/beta/includes/snippets/objc/get-printjob-withtasks-objc-snippets.md
  api-reference/beta/includes/snippets/objc/update-authzpolicy-guestuserlevel-objc-snippets.md
  api-reference/v1.0/includes/snippets/csharp/call-answer-service-hosted-media-csharp-snippets.md
  api-reference/v1.0/includes/snippets/csharp/get-mailboxsettings-1-csharp-snippets.md
  api-reference/v1.0/includes/snippets/java/call-answer-service-hosted-media-java-snippets.md
  api-reference/v1.0/includes/snippets/java/get-mailboxsettings-1-java-snippets.md
  api-reference/v1.0/includes/snippets/javascript/call-answer-service-hosted-media-javascript-snippets.md
  api-reference/v1.0/includes/snippets/javascript/create-item-attachment-with-post-javascript-snippets.md
  api-reference/v1.0/includes/snippets/javascript/get-mailboxsettings-1-javascript-snippets.md
  api-reference/v1.0/includes/snippets/objc/call-answer-service-hosted-media-objc-snippets.md
  api-reference/v1.0/includes/snippets/objc/create-item-attachment-with-post-objc-snippets.md
  api-reference/v1.0/includes/snippets/objc/get-mailboxsettings-1-objc-snippets.md
  concepts/teams-changenotifications-chatmessage.md
  concepts/teams-send-activityfeednotifications.md
  concepts/toolkit/components/get.md
  concepts/toolkit/get-started/use-toolkit-with-react.md
Labels: do not merge, internal

#11530 Fix to conceptual TOC for API reference links using wrong version
  concepts/toc.yml
Labels: internal, ready to merge

#11371 Adding new columns to getSharePointSiteUsageDetail api
  api-reference/beta/api/reportroot-getsharepointsiteusagedetail.md
  api-reference/beta/resources/sharepointsiteusagedetail.md
  changelog/Microsoft.O365Reporting.json
Labels: internal, ready to merge

#11527 Update educationuser.md
  api-reference/v1.0/resources/educationuser.md
Labels: internal, ready to merge

#11522 Update person-card.md
  concepts/toolkit/components/person-card.md
Labels: external

#11536 Fixed the URL for chatMessage PATCH
  api-reference/beta/api/chatmessage-update.md
  api-reference/v1.0/api/chatmessage-update.md
Labels: area: teams, internal, ready to merge

#11535 RSC permissions patch
  api-reference/v1.0/api/channel-get-message.md
  api-reference/v1.0/api/channel-get-messagereply.md
  api-reference/v1.0/api/channel-list-messagereplies.md
  api-reference/v1.0/api/channel-list-messages.md
Labels: area: teams, internal, ready to merge

#11537 Merge to publish.
  api-reference/beta/api/chatmessage-update.md
  api-reference/beta/api/reportroot-getsharepointsiteusagedetail.md
  api-reference/beta/resources/sharepointsiteusagedetail.md
  api-reference/v1.0/api/channel-get-message.md
  api-reference/v1.0/api/channel-get-messagereply.md
  api-reference/v1.0/api/channel-list-messagereplies.md
  api-reference/v1.0/api/channel-list-messages.md
  api-reference/v1.0/api/chatmessage-update.md
  api-reference/v1.0/resources/educationuser.md
  changelog/Microsoft.O365Reporting.json
  concepts/toc.yml
  concepts/toolkit/components/person-card.md
Labels: internal

#11517 Update metadata for docs in Users
  api-reference/beta/api/user-delete-approleassignments.md
  api-reference/beta/api/user-list-approleassignments.md
  api-reference/beta/api/user-post-approleassignments.md
  api-reference/beta/resources/useridentity.md
  api-reference/v1.0/api/user-delete-approleassignments.md
  api-reference/v1.0/api/user-list-approleassignments.md
  api-reference/v1.0/api/user-post-approleassignments.md
  api-reference/v1.0/api/user-post-users.md
  api-reference/v1.0/resources/useridentity.md
Labels: area: users, internal, ready to merge

#11516 Update metadata for docs in Groups
  api-reference/beta/api/group-delete-approleassignments.md
  api-reference/beta/api/group-list-approleassignments.md
  api-reference/beta/api/group-post-approleassignments.md
  api-reference/beta/resources/evaluatedynamicmembershipresult.md
  api-reference/beta/resources/expressionevaluationdetails.md
  api-reference/beta/resources/membershipruleprocessingstatus.md
  api-reference/beta/resources/propertytoevaluate.md
  api-reference/v1.0/api/group-checkmemberobjects.md
  api-reference/v1.0/api/group-delete-approleassignments.md
  api-reference/v1.0/api/group-list-approleassignments.md
  api-reference/v1.0/api/group-post-approleassignments.md
Labels: area: groups, internal, ready to merge

#11486 Update metadata for docs in Reports
  api-reference/beta/api/applicationsignindetailedsummary-get.md
  api-reference/beta/api/applicationsigninsummary-get.md
  api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md
  api-reference/beta/api/authenticationmethodsroot-usersregisteredbymethod.md
  api-reference/beta/api/directoryaudit-get.md
  api-reference/beta/api/directoryaudit-list.md
  api-reference/beta/api/provisioningobjectsummary-list.md
  api-reference/beta/api/relyingpartydetailedsummary-list.md
  api-reference/beta/api/reportroot-getcredentialusagesummary.md
  api-reference/beta/api/reportroot-getcredentialuserregistrationcount.md
  api-reference/beta/api/reportroot-list-credentialuserregistrationdetails.md
  api-reference/beta/api/reportroot-list-usercredentialusagedetails.md
  api-reference/beta/api/signin-get.md
  api-reference/beta/api/signin-list.md
  api-reference/beta/resources/appidentity.md
  api-reference/beta/resources/applicationsignindetailedsummary.md
  api-reference/beta/resources/applicationsigninsummary.md
  api-reference/beta/resources/auditactivityinitiator.md
  api-reference/beta/resources/authenticationdetail.md
  api-reference/beta/resources/authenticationmethods-usage-insights-overview.md
  api-reference/beta/resources/azure-ad-auditlog-overview.md
  api-reference/beta/resources/credentialusagesummary.md
  api-reference/beta/resources/credentialuserregistrationcount.md
  api-reference/beta/resources/credentialuserregistrationdetails.md
  api-reference/beta/resources/detailsinfo.md
  api-reference/beta/resources/directoryaudit.md
  api-reference/beta/resources/geocoordinates.md
  api-reference/beta/resources/initiator.md
  api-reference/beta/resources/keyvalue.md
  api-reference/beta/resources/networkLocationDetail.md
  api-reference/beta/resources/provisioningobjectsummary.md
  api-reference/beta/resources/provisioningstep.md
  api-reference/beta/resources/provisioningsystemdetails.md
  api-reference/beta/resources/relyingpartydetailedsummary.md
  api-reference/beta/resources/report-identity-access.md
  api-reference/beta/resources/signin.md
  api-reference/beta/resources/signinlocation.md
  api-reference/beta/resources/signinstatus.md
  api-reference/beta/resources/targetresource.md
  api-reference/beta/resources/usercredentialusagedetails.md
  api-reference/beta/resources/userregistrationcount.md
  api-reference/beta/resources/userregistrationfeaturecount.md
  api-reference/beta/resources/userregistrationfeaturesummary.md
  api-reference/beta/resources/userregistrationmethodcount.md
  api-reference/beta/resources/userregistrationmethodsummary.md
  api-reference/v1.0/api/directoryaudit-get.md
  api-reference/v1.0/api/directoryaudit-list.md
  api-reference/v1.0/api/signin-get.md
  api-reference/v1.0/api/signin-list.md
  api-reference/v1.0/resources/appidentity.md
  api-reference/v1.0/resources/auditactivityinitiator.md
  api-reference/v1.0/resources/azure-ad-auditlog-overview.md
  api-reference/v1.0/resources/directoryaudit.md
  api-reference/v1.0/resources/geocoordinates.md
  api-reference/v1.0/resources/keyvalue.md
  api-reference/v1.0/resources/signin.md
  api-reference/v1.0/resources/signinlocation.md
  api-reference/v1.0/resources/signinstatus.md
  api-reference/v1.0/resources/targetresource.md
Labels: area: reports, internal, ready to merge

#11549 Added showExpandedDetailsButton to person-card
  concepts/toolkit/customize-components/localization.md
Labels: internal

#11532 [CloudPC]Update boilerplate text
  api-reference/includes/cloudpc-api-preview.md
Labels: content review, internal

#11550 application update - removed text
  api-reference/beta/resources/application.md
  api-reference/v1.0/resources/application.md
Labels: area: azure/AAD, internal, ready to merge

#11525 Update Domain APIs
  api-reference/beta/api/domain-forcedelete.md
  api-reference/beta/api/domain-get.md
  api-reference/beta/api/domain-list.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/domain-forcedelete.md
  api-reference/v1.0/api/domain-get.md
  api-reference/v1.0/api/domain-list.md
  api-reference/v1.0/toc.yml
Labels: area: identity, internal, ready to merge

#11468 Fix #11278
  api-reference/beta/api/user-delete.md
  api-reference/v1.0/api/user-delete.md
Labels: internal, ready to merge

#11465 Update v1.0 TOC for the Reports node
  api-reference/v1.0/toc.yml
Labels: area: reports, internal, ready to merge

#11273 Add the accessPackageResourceEnvironment resource type
  api-reference/beta/api/accesspackageresourceenvironment-get.md
  api-reference/beta/api/accesspackageresourceenvironment-list.md
  api-reference/beta/api/accesspackageresourcerequest-post.md
  api-reference/beta/resources/accesspackageresource.md
  api-reference/beta/resources/accesspackageresourceenvironment.md
  api-reference/beta/resources/connectioninfo.md
  api-reference/beta/resources/entitlementmanagement-root.md
  api-reference/beta/toc.yml
  changelog/Microsoft.DirectoryServices.json
  concepts/whats-new-overview.md
Labels: area: azure/AAD, beta, internal, ready to merge

#11109 Publish consent request APIs (preview)
  api-reference/beta/api/adminconsentrequestpolicy-get.md
  api-reference/beta/api/adminconsentrequestpolicy-update.md
  api-reference/beta/api/appconsentrequest-get.md
  api-reference/beta/api/appconsentrequest-list.md
  api-reference/beta/api/directorysetting-get.md
  api-reference/beta/api/directorysetting-list.md
  api-reference/beta/api/directorysetting-update.md
  api-reference/beta/api/user-get-appconsentrequestsforapproval.md
  api-reference/beta/api/user-list-appconsentrequestsforapproval.md
  api-reference/beta/api/userconsentrequest-get.md
  api-reference/beta/api/userconsentrequest-list.md
  api-reference/beta/resources/adminconsentrequestpolicy.md
  api-reference/beta/resources/appconsentrequest.md
  api-reference/beta/resources/appconsentrequestscope.md
  api-reference/beta/resources/approval.md
  api-reference/beta/resources/approvalstep.md
  api-reference/beta/resources/azure-ad-overview.md
  api-reference/beta/resources/consentrequests-root.md
  api-reference/beta/resources/request.md
  api-reference/beta/resources/userconsentrequest.md
  api-reference/beta/toc.yml
  changelog/Microsoft.DirectoryServices.json
  concepts/changelog.md
  concepts/whats-new-overview.md
Labels: area: identity, beta, content review, do not merge, internal

#11555 List what's new in the last few weeks.
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: internal

#11556 Refresh what's new topic.
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: internal

#11460 [CloudPC]Make inUse optional returned
  api-reference/beta/api/cloudpconpremisesconnection-get.md
  api-reference/beta/api/cloudpconpremisesconnection-update.md
  api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md
  api-reference/beta/api/virtualendpoint-post-onpremisesconnections.md
  api-reference/beta/resources/cloudpconpremisesconnection.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: internal, ready to merge

#11571 Update use-beta.md
  concepts/sdks/use-beta.md
Labels: internal, ready to merge

#11563 fixed typos
  api-reference/beta/api/unifiedroleassignmentmultiple-list.md
Labels: external

#11566 Update whats-new-overview.md
  concepts/whats-new-overview.md
Labels: external

#11567 Update accesspackage.md
  api-reference/beta/resources/accesspackage.md
Labels: external

#11558 Update people-picker.md
  concepts/toolkit/components/people-picker.md
Labels: external

#11564 fixed typos
  api-reference/beta/api/unifiedroleassignmentmultiple-post.md
Labels: external

#11427 Add permissions to site
  api-reference/beta/api/site-delete-permission.md
  api-reference/beta/api/site-get-permission.md
  api-reference/beta/api/site-list-permissions.md
  api-reference/beta/api/site-post-permissions.md
  api-reference/beta/api/site-update-permission.md
  api-reference/beta/resources/site.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/site-delete-permission.md
  api-reference/v1.0/api/site-get-permission.md
  api-reference/v1.0/api/site-list-permissions.md
  api-reference/v1.0/api/site-post-permissions.md
  api-reference/v1.0/api/site-update-permission.md
  api-reference/v1.0/resources/site.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.FileServices.json
Labels: internal, ready to merge

#11485 Update intune-shared-androidmanagedappprotection.md
  api-reference/beta/resources/intune-shared-androidmanagedappprotection.md
Labels: external

#11580 Correctly name enum table headers for discovery by API Doctor
  api-reference/beta/api/tiindicator-update.md
  api-reference/beta/api/user-translateexchangeids.md
  api-reference/beta/resources/calendarpermission.md
  api-reference/beta/resources/enums-termstore.md
  api-reference/beta/resources/permission.md
  api-reference/beta/resources/personOrGroupColumn.md
  api-reference/v1.0/api/user-translateexchangeids.md
  api-reference/v1.0/resources/calendarpermission.md
  api-reference/v1.0/resources/permission.md
Labels: internal, ready to merge

#11557 Adding guidance on usage of $top for list messages and reorganizing examples
  api-reference/beta/api/user-list-messages.md
  api-reference/v1.0/api/user-list-messages.md
  concepts/query-parameters.md
Labels: content review, do not merge, internal

#11583 Update accesspackage-delete.md
  api-reference/beta/api/accesspackage-delete.md
Labels: external

#11595 fix for git issue 7860
  api-reference/beta/api/identityuserflow-post-userflows.md
  api-reference/beta/resources/identityuserflow.md
Labels: area: azure/AAD, internal, ready to merge

#11592 Added clarification to signIn list
  api-reference/beta/api/signin-list.md
  api-reference/v1.0/api/signin-list.md
Labels: area: azure/AAD, internal, ready to merge

#11578 changes to Group documentation
  api-reference/beta/api/directoryobject-checkmembergroups.md
  api-reference/beta/api/user-getmembergroups.md
  api-reference/beta/resources/group.md
  api-reference/v1.0/api/directoryobject-checkmembergroups.md
  api-reference/v1.0/api/user-getmembergroups.md
  api-reference/v1.0/resources/group.md
Labels: internal, ready to merge

#11543 Add note for restore deleted item API
  api-reference/beta/api/directory-deleteditems-restore.md
Labels: internal, ready to merge

#11519 Move PSTN call related samples from Beta to V1 and remove Australia limitation note for Beta
  api-reference/beta/api/application-post-calls.md
  api-reference/beta/api/call-redirect.md
  api-reference/beta/api/call-transfer.md
  api-reference/beta/api/participant-invite.md
  api-reference/v1.0/api/application-post-calls.md
  api-reference/v1.0/api/call-redirect.md
  api-reference/v1.0/api/call-transfer.md
  api-reference/v1.0/api/participant-invite.md
Labels: internal, ready to merge

#11331 Update attachment-get.md
  api-reference/beta/api/attachment-get.md
  api-reference/v1.0/api/attachment-get.md
  concepts/outlook-large-attachments.md
Labels: internal, ready to merge

#11394 2021 01 19 tarkanse planner rosters
  api-reference/beta/api/planner-post-rosters.md
  api-reference/beta/api/plannerroster-delete.md
  api-reference/beta/api/plannerroster-get.md
  api-reference/beta/api/plannerroster-list-members.md
  api-reference/beta/api/plannerroster-list-plans.md
  api-reference/beta/api/plannerroster-post-members.md
  api-reference/beta/api/plannerrostermember-delete.md
  api-reference/beta/api/plannerrostermember-get.md
  api-reference/beta/api/plannertask-update.md
  api-reference/beta/api/planneruser-list-rosterplans.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/planner.md
  api-reference/beta/resources/plannerplancontainer.md
  api-reference/beta/resources/plannerplancontext.md
  api-reference/beta/resources/plannerplancontextdetails.md
  api-reference/beta/resources/plannerroster.md
  api-reference/beta/resources/plannerrostermember.md
  api-reference/beta/resources/planneruser.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Office.Tasks.json
  concepts/changelog.md
Labels: internal, ready to merge

#11613 update batch size
  api-reference/beta/api/riskyusers-dismiss.md
Labels: internal, ready to merge

#11612 Minor update to PSTN scenario
  api-reference/v1.0/api/call-transfer.md
Labels: content review, internal, ready to merge

#11603 Update projectrome-notification.md
  api-reference/beta/resources/projectrome-notification.md
Labels: external

#11602 Update accesspackage-update.md
  api-reference/beta/api/accesspackage-update.md
Labels: external

#11617 Update teams-configuring-builtin-tabs.md
  concepts/teams-configuring-builtin-tabs.md
Labels: external

#11545 Fix link to Microsoft 365 domain add/verify
  concepts/extensibility-schema-groups.md
Labels: internal, ready to merge

#11306 Application Proxy Updated Enums for Header-based Auth
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/onpremisespublishingsinglesignon.md
  changelog/Microsoft.DirectoryServices.json
Labels: area: azure/AAD, ready to merge

#11600 Add support for up to 25 category descriptions on planner plan details
  api-reference/beta/resources/plannerappliedcategories.md
  api-reference/beta/resources/plannercategorydescriptions.md
  api-reference/beta/resources/plannerplandetails.md
  changelog/Microsoft.Office.Tasks.json
Labels: area: planner, internal, ready to merge

#11621 Merge to publish.
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/onpremisespublishingsinglesignon.md
  api-reference/beta/resources/plannerappliedcategories.md
  api-reference/beta/resources/plannercategorydescriptions.md
  api-reference/beta/resources/plannerplandetails.md
  changelog/Microsoft.DirectoryServices.json
  changelog/Microsoft.Office.Tasks.json
  concepts/extensibility-schema-groups.md
  concepts/teams-configuring-builtin-tabs.md
Labels: do not merge, internal

#11445 AndresC-AuthMethodsPolicy-SMS
  api-reference/beta/api/smsauthenticationmethodconfiguration-delete.md
  api-reference/beta/api/smsauthenticationmethodconfiguration-get.md
  api-reference/beta/api/smsauthenticationmethodconfiguration-update.md
  api-reference/beta/resources/authenticationmethodspolicies-overview.md
  api-reference/beta/resources/smsauthenticationmethodconfiguration.md
  api-reference/beta/resources/smsauthenticationmethodtarget.md
  api-reference/beta/toc.yml
  changelog/Microsoft.DirectoryServices.json
  concepts/permissions-reference.md
Labels: ready to merge

#11289 Electron provider with msal
  concepts/toc.yml
  concepts/toolkit/get-started/build-an-electron-app.md
  concepts/toolkit/overview.md
  concepts/toolkit/providers/electron.md
  concepts/toolkit/providers/providers.md
Labels: do not merge, internal

#11627 Update accesspackageresourceenvironment-list.md
  api-reference/beta/api/accesspackageresourceenvironment-list.md
Labels: external

#11626 minor spelling fix
  concepts/cloud-communication-online-meeting-application-access-policy.md
Labels: external

#11551 Add app permissions to synchronization apis
  api-reference/beta/api/synchronization-synchronization-acquireaccesstoken.md
  api-reference/beta/api/synchronization-synchronizationjob-delete.md
  api-reference/beta/api/synchronization-synchronizationjob-get.md
  api-reference/beta/api/synchronization-synchronizationjob-list.md
  api-reference/beta/api/synchronization-synchronizationjob-pause.md
  api-reference/beta/api/synchronization-synchronizationjob-post.md
  api-reference/beta/api/synchronization-synchronizationjob-provision-on-demand.md
  api-reference/beta/api/synchronization-synchronizationjob-restart.md
  api-reference/beta/api/synchronization-synchronizationjob-start.md
  api-reference/beta/api/synchronization-synchronizationjob-validatecredentials.md
  api-reference/beta/api/synchronization-synchronizationschema-delete.md
  api-reference/beta/api/synchronization-synchronizationschema-filteroperators.md
  api-reference/beta/api/synchronization-synchronizationschema-functions.md
  api-reference/beta/api/synchronization-synchronizationschema-get.md
  api-reference/beta/api/synchronization-synchronizationschema-parseexpression.md
  api-reference/beta/api/synchronization-synchronizationschema-update.md
  api-reference/beta/api/synchronization-synchronizationtemplate-get.md
  api-reference/beta/api/synchronization-synchronizationtemplate-list.md
  api-reference/beta/api/synchronization-synchronizationtemplate-post.md
  api-reference/beta/api/synchronization-synchronizationtemplate-update.md
  changelog/Microsoft.DirectoryServices.json
Labels: area: azure/AAD, internal, ready to merge

#10977 Adding new properties to Device entity (Beta)
  api-reference/beta/resources/device.md
  changelog/Microsoft.DirectoryServices.json
  concepts/changelog.md
Labels: internal, ready to merge

#11622 Add note for restore deleted item API
  api-reference/v1.0/api/directory-deleteditems-restore.md
Labels: internal, ready to merge

#11632 Merge to publish.
  api-reference/beta/api/accesspackageresourceenvironment-list.md
  api-reference/beta/api/smsauthenticationmethodconfiguration-delete.md
  api-reference/beta/api/smsauthenticationmethodconfiguration-get.md
  api-reference/beta/api/smsauthenticationmethodconfiguration-update.md
  api-reference/beta/api/synchronization-synchronization-acquireaccesstoken.md
  api-reference/beta/api/synchronization-synchronizationjob-delete.md
  api-reference/beta/api/synchronization-synchronizationjob-get.md
  api-reference/beta/api/synchronization-synchronizationjob-list.md
  api-reference/beta/api/synchronization-synchronizationjob-pause.md
  api-reference/beta/api/synchronization-synchronizationjob-post.md
  api-reference/beta/api/synchronization-synchronizationjob-provision-on-demand.md
  api-reference/beta/api/synchronization-synchronizationjob-restart.md
  api-reference/beta/api/synchronization-synchronizationjob-start.md
  api-reference/beta/api/synchronization-synchronizationjob-validatecredentials.md
  api-reference/beta/api/synchronization-synchronizationschema-delete.md
  api-reference/beta/api/synchronization-synchronizationschema-filteroperators.md
  api-reference/beta/api/synchronization-synchronizationschema-functions.md
  api-reference/beta/api/synchronization-synchronizationschema-get.md
  api-reference/beta/api/synchronization-synchronizationschema-parseexpression.md
  api-reference/beta/api/synchronization-synchronizationschema-update.md
  api-reference/beta/api/synchronization-synchronizationtemplate-get.md
  api-reference/beta/api/synchronization-synchronizationtemplate-list.md
  api-reference/beta/api/synchronization-synchronizationtemplate-post.md
  api-reference/beta/api/synchronization-synchronizationtemplate-update.md
  api-reference/beta/resources/authenticationmethodspolicies-overview.md
  api-reference/beta/resources/device.md
  api-reference/beta/resources/smsauthenticationmethodconfiguration.md
  api-reference/beta/resources/smsauthenticationmethodtarget.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/directory-deleteditems-restore.md
  changelog/Microsoft.DirectoryServices.json
  concepts/changelog.md
  concepts/cloud-communication-online-meeting-application-access-policy.md
  concepts/permissions-reference.md
Labels: internal

#11634 Update accesspackageresourceenvironment.md
  api-reference/beta/resources/accesspackageresourceenvironment.md
Labels: external

#11593 fix for git issue 3925
  api-reference/beta/api/directory-deleteditems-delete.md
  api-reference/v1.0/api/directory-deleteditems-delete.md
Labels: area: azure/AAD, internal, ready to merge

#11573 education assignment defaults api docs
  api-reference/beta/api/educationassignmentdefaults-get.md
  api-reference/beta/api/educationassignmentdefaults-update.md
  api-reference/beta/api/educationassignmentsettings-get.md
  api-reference/beta/api/educationclass-list-assignments.md
  api-reference/beta/resources/educationassignment.md
  api-reference/beta/resources/educationassignmentdefaults.md
  api-reference/beta/toc.yml
  changelog/Microsoft.EducationAssignment.json
Labels: internal, ready to merge

#11452 adding app perm for EM
  api-reference/beta/api/accesspackage-delete.md
  api-reference/beta/api/accesspackage-get.md
  api-reference/beta/api/accesspackage-list-accesspackageresourcerolescopes.md
  api-reference/beta/api/accesspackage-list.md
  api-reference/beta/api/accesspackage-post-accesspackageresourcerolescopes.md
  api-reference/beta/api/accesspackage-post.md
  api-reference/beta/api/accesspackage-update.md
  api-reference/beta/api/accesspackageassignment-list.md
  api-reference/beta/api/accesspackageassignmentpolicy-delete.md
  api-reference/beta/api/accesspackageassignmentpolicy-get.md
  api-reference/beta/api/accesspackageassignmentpolicy-list.md
  api-reference/beta/api/accesspackageassignmentpolicy-post.md
  api-reference/beta/api/accesspackageassignmentpolicy-update.md
  api-reference/beta/api/accesspackageassignmentrequest-get.md
  api-reference/beta/api/accesspackageassignmentrequest-list.md
  api-reference/beta/api/accesspackageassignmentrequest-post.md
  api-reference/beta/api/accesspackageassignmentresourcerole-get.md
  api-reference/beta/api/accesspackageassignmentresourcerole-list.md
  api-reference/beta/api/accesspackagecatalog-delete.md
  api-reference/beta/api/accesspackagecatalog-get.md
  api-reference/beta/api/accesspackagecatalog-list-accesspackageresourceroles.md
  api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md
  api-reference/beta/api/accesspackagecatalog-list.md
  api-reference/beta/api/accesspackagecatalog-post.md
  api-reference/beta/api/accesspackagecatalog-update.md
  api-reference/beta/api/accesspackageresourcerequest-list.md
  api-reference/beta/api/connectedorganization-delete-externalsponsors.md
  api-reference/beta/api/connectedorganization-delete-internalsponsors.md
  api-reference/beta/api/connectedorganization-delete.md
  api-reference/beta/api/connectedorganization-get.md
  api-reference/beta/api/connectedorganization-list-externalsponsors.md
  api-reference/beta/api/connectedorganization-list-internalsponsors.md
  api-reference/beta/api/connectedorganization-list.md
  api-reference/beta/api/connectedorganization-post-externalsponsors.md
  api-reference/beta/api/connectedorganization-post-internalsponsors.md
  api-reference/beta/api/connectedorganization-post.md
  api-reference/beta/api/connectedorganization-update.md
  api-reference/beta/api/entitlementmanagementsettings-get.md
  api-reference/beta/api/entitlementmanagementsettings-update.md
  changelog/Microsoft.DirectoryServices.json
  concepts/permissions-reference.md
Labels: area: azure/AAD, internal, ready to merge

#11638 mgt "avatarType" property
  concepts/toolkit/components/person.md
Labels: do not merge, internal

#11673 Update permission description to reflect current state
  concepts/permissions-reference.md
Labels: internal, ready to merge

#11669 Update synchronization-overview.md
  api-reference/beta/resources/synchronization-overview.md
Labels: external

#11668 Update localization.md
  concepts/toolkit/customize-components/localization.md
Labels: external

#11666 Fix example JSON in educationsubmission-list-submittedresoures.md
  api-reference/beta/api/educationsubmission-list-submittedresources.md
Labels: external

#11661 Update accesspackageresourcerolescope.md
  api-reference/beta/resources/accesspackageresourcerolescope.md
Labels: external

#11654 managment should be management
  api-reference/v1.0/resources/intune-mam-managedappregistration.md
Labels: external

#11653 managment should be management
  api-reference/v1.0/resources/intune-mam-androidmanagedappregistration.md
Labels: external

#11652 Managment should be Management
  api-reference/beta/resources/intune-devices-devicehealthscriptdevicestate.md
Labels: external

#11651 Managment should be Management
  api-reference/beta/resources/intune-devices-devicecompliancescriptdevicestate.md
Labels: external

#11665 Adding more details for how to create app roles
  api-reference/beta/resources/approle.md
  api-reference/v1.0/resources/approle.md
Labels: internal, ready to merge

#11547 Add read-only status. Fixes #11481
  api-reference/beta/resources/user.md
Labels: internal, ready to merge

#11470 Update to governance tutorial
  concepts/toc.yml
  concepts/tutorial-access-package-api.md
Labels: area: azure/AAD, internal, ready to merge

#11639 Updated permission tables on 6 group docs
  api-reference/beta/api/group-list-members.md
  api-reference/beta/api/group-list-owners.md
  api-reference/beta/api/group-list-transitivemembers.md
  api-reference/v1.0/api/group-list-members.md
  api-reference/v1.0/api/group-list-owners.md
  api-reference/v1.0/api/group-list-transitivemembers.md
Labels: internal, ready to merge

#11596 Changed Intune changelog
  changelog/Microsoft.Intune.json
Labels: internal, ready to merge

#11640 application saml sso tutorial update
  concepts/application-saml-sso-configure-api.md
  concepts/images/application-saml-sso-configure-api/accept-permissions.PNG
  concepts/images/application-saml-sso-configure-api/select-permissions.PNG
  concepts/images/application-saml-sso-configure-api/set-permissions.png
Labels: area: azure/AAD, internal, ready to merge

#11678 Update accesspackageresourceenvironment.md
  api-reference/beta/resources/accesspackageresourceenvironment.md
Labels: internal, ready to merge

#11667 Clarification on app role assignment relationships
  api-reference/beta/resources/serviceprincipal.md
  api-reference/v1.0/resources/serviceprincipal.md
Labels: internal, ready to merge

#11643 02 12 2020 tap method policy
  api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md
  api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md
  api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md
  api-reference/beta/api/temporaryaccesspassauthenticationmethod-post.md
  api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md
  api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md
  api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md
  api-reference/beta/resources/authenticationmethods-overview.md
  api-reference/beta/resources/authenticationmethodspolicies-overview.md
  api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md
  api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md
  api-reference/beta/toc.yml
  changelog/Microsoft.DirectoryServices.json
Labels: internal, ready to merge

#11560 Remove unused suppressions
  api-reference/beta/api/application-addkey.md
  api-reference/beta/api/b2cidentityuserflow-update.md
  api-reference/beta/api/identitycontainer-post-b2cuserflows.md
  api-reference/beta/api/place-list.md
  api-reference/beta/api/serviceprincipal-addkey.md
  api-reference/beta/api/user-findmeetingtimes.md
  api-reference/beta/resources/educationclass.md
  api-reference/beta/resources/educationschool.md
  api-reference/beta/resources/educationuser.md
  api-reference/beta/resources/outlookcategory.md
  api-reference/beta/resources/print.md
  api-reference/beta/resources/recurrencerange.md
  api-reference/beta/resources/teamdiscoverysettings.md
  api-reference/beta/resources/userflowapiconnectorconfiguration.md
  api-reference/v1.0/api/application-addkey.md
  api-reference/v1.0/api/attachment-get.md
  api-reference/v1.0/api/drive-get.md
  api-reference/v1.0/api/driveitem-createuploadsession.md
  api-reference/v1.0/api/driveitem-list-thumbnails.md
  api-reference/v1.0/api/invitation-post.md
  api-reference/v1.0/api/place-list.md
  api-reference/v1.0/api/projectrome-get-recent-activities.md
  api-reference/v1.0/api/range-update.md
  api-reference/v1.0/api/serviceprincipal-addkey.md
  api-reference/v1.0/api/site-getbypath.md
  api-reference/v1.0/api/table-post-rows.md
  api-reference/v1.0/api/tablerowcollection-add.md
  api-reference/v1.0/api/user-findmeetingtimes.md
  api-reference/v1.0/api/workbook-closesession.md
  api-reference/v1.0/api/workbook-refreshsession.md
  api-reference/v1.0/resources/azure-ad-auditlog-overview.md
  api-reference/v1.0/resources/educationuser.md
  api-reference/v1.0/resources/intune-deviceconfig-iosupdateconfiguration.md
  api-reference/v1.0/resources/intune-mam-androidmanagedappregistration.md
  api-reference/v1.0/resources/intune-mam-iosmanagedappregistration.md
  api-reference/v1.0/resources/intune-mam-managedappregistration.md
  api-reference/v1.0/resources/organization.md
  api-reference/v1.0/resources/outlookcategory.md
  api-reference/v1.0/resources/recurrencerange.md
  api-reference/v1.0/resources/user.md
  api-reference/v1.0/resources/useridentity.md
Labels: content review, internal, ready to merge

#11688 Added that shownContext can also be null
  api-reference/beta/resources/microsoftauthenticatorauthenticationmethodtarget.md
Labels: external

#11687 Fix minor typo
  api-reference/v1.0/resources/recurrencepattern.md
Labels: external

#11682 Clarify supported errorCodes and errorCategories
  api-reference/beta/resources/statusdetails.md
Labels: area: azure/AAD, internal, ready to merge

#11658 Fix sample URLs to match schema
  api-reference/beta/api/fido2authenticationmethod-get.md
  api-reference/beta/api/openshiftchangerequest-approve.md
  api-reference/beta/api/openshiftchangerequest-decline.md
  api-reference/beta/api/openshiftchangerequest-get.md
  api-reference/beta/api/openshiftchangerequest-list.md
  api-reference/beta/api/openshiftchangerequest-post.md
  api-reference/beta/api/personresponsibility-delete.md
  api-reference/beta/api/personresponsibility-get.md
  api-reference/beta/api/personresponsibility-update.md
  api-reference/beta/api/printershare-delete-alloweduser.md
  api-reference/beta/api/profile-list-accounts.md
  api-reference/beta/api/profile-list-responsibilities.md
  api-reference/beta/api/profile-post-accounts.md
  api-reference/beta/api/profile-post-educationalactivities.md
  api-reference/beta/api/profile-post-responsibilities.md
  api-reference/beta/api/useraccountinformation-delete.md
  api-reference/beta/api/useraccountinformation-get.md
  api-reference/beta/api/useraccountinformation-update.md
  api-reference/v1.0/api/openshiftchangerequest-approve.md
  api-reference/v1.0/api/openshiftchangerequest-decline.md
  api-reference/v1.0/api/openshiftchangerequest-get.md
  api-reference/v1.0/api/openshiftchangerequest-list.md
  api-reference/v1.0/api/openshiftchangerequest-post.md
Labels: changes requested, external, ready to merge

#11646 Updated passwordProfile
  api-reference/v1.0/api/user-update.md
Labels: internal, ready to merge

#11686 Update dynamics-vendor.md
  api-reference/beta/resources/dynamics-vendor.md
Labels: external

#11492 Support policy-based app token scenarios in v1.0
  api-reference/beta/api/application-post-onlinemeetings.md
  api-reference/beta/api/onlinemeeting-createorget.md
  api-reference/beta/api/onlinemeeting-delete.md
  api-reference/beta/api/onlinemeeting-get.md
  api-reference/beta/api/onlinemeeting-update.md
  api-reference/v1.0/api/application-post-onlinemeetings.md
  api-reference/v1.0/api/onlinemeeting-createorget.md
  api-reference/v1.0/api/onlinemeeting-delete.md
  api-reference/v1.0/api/onlinemeeting-get.md
  changelog/Microsoft.Skype.Calling.json
Labels: content review, internal

#11689 Update workbook-error-handling.md
  concepts/workbook-error-handling.md
Labels: area: excel, bug: documentation, internal, ready to merge

#11577 Updates to access review api documentation
  api-reference/beta/resources/accessreview.md
  api-reference/beta/resources/accessreviewapplyaction.md
  api-reference/beta/resources/accessreviewdecision.md
  api-reference/beta/resources/accessreviewinstance.md
  api-reference/beta/resources/accessreviewinstancedecisionitem.md
  api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipaltarget.md
  api-reference/beta/resources/accessreviewinstancedecisionitemtarget.md
  api-reference/beta/resources/accessreviewinstancedecisionitemusertarget.md
  api-reference/beta/resources/accessreviewrecurrencesettings.md
  api-reference/beta/resources/accessreviewreviewerscope.md
  api-reference/beta/resources/accessreviews-root.md
  api-reference/beta/resources/accessreviewscheduledefinition.md
  api-reference/beta/resources/accessreviewschedulesettings.md
  api-reference/beta/resources/accessreviewscope.md
  api-reference/beta/resources/accessreviewsettings.md
  api-reference/beta/resources/accessreviewsv2-root.md
  api-reference/includes/accessreviews-disclaimer-v2.md
  api-reference/includes/accessreviews-disclaimer.md
Labels: area: azure/AAD, ready to merge

#11358 add inputBin to Printer Defaults
  api-reference/beta/resources/printerdefaults.md
  changelog/Microsoft.PrintService.json
  concepts/changelog.md
Labels: area: universal print, internal, ready to merge

#11698 Adds fallback-details to mgt-person
  concepts/toolkit/components/person.md
Labels: external

#11685 Fix app permissions list group-post-owners v1.0
  api-reference/v1.0/api/group-post-owners.md
Labels: internal, ready to merge

#11660 Add appRoleAssignments relationship to user & group resources
  api-reference/beta/resources/group.md
  api-reference/beta/resources/user.md
  api-reference/v1.0/resources/group.md
  api-reference/v1.0/resources/user.md
Labels: internal, ready to merge

#11699 Add details for line templates in mgt-person
  concepts/toolkit/components/person.md
Labels: do not merge, internal

#11531 Update preferredSSOmode serviceprincipal.md
  api-reference/v1.0/resources/serviceprincipal.md
Labels: ready to merge

#11774 minor fix in permission section
  api-reference/beta/api/iteminsightssettings-get.md
  api-reference/beta/api/iteminsightssettings-update.md
Labels: ready to merge

#11768 Fix typo: tje --> the
  api-reference/v1.0/api/subscription-update.md
Labels: external

#11749 Fix typo in session resource doc
  api-reference/v1.0/resources/callrecords-session.md
Labels: external

#11746 Update plannerplan.md
  api-reference/beta/resources/plannerplan.md
Labels: external

#11745 Update plannerplan.md
  api-reference/v1.0/resources/plannerplan.md
Labels: external

#11722 Fixed a small typo
  api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md
Labels: external

#11732 Update table-update.md
  api-reference/beta/api/table-update.md
  api-reference/v1.0/api/table-update.md
Labels: external
