Repository microsoftgraph/microsoft-graph-docs, pull requests merged in 2021-08, with the labels that each got.

#13698 Update throttling.md
  concepts/throttling.md
Labels: area: assignments, content review complete, docs, fixed, ready to merge

#13709 revert #13634
  api-reference/beta/api/user-post-approleassignments.md
  api-reference/v1.0/api/user-post-approleassignments.md
Labels: area: azure/AAD, internal, ready to merge

#13714 Resolves #13148, add limits for B2C
  api-reference/beta/api/user-update.md
  api-reference/beta/resources/user.md
  api-reference/v1.0/api/user-update.md
  api-reference/v1.0/resources/user.md
Labels: area: azure/AAD, area: users, internal, ready to merge

#13715 Fix permission name, resolves #13666
  concepts/permissions-reference.md
Labels: area: azure/AAD, internal, ready to merge

#13718 Merge and publish recent PRs from main to live
  api-reference/beta/api/user-post-approleassignments.md
  api-reference/beta/api/user-update.md
  api-reference/beta/resources/user.md
  api-reference/v1.0/api/user-post-approleassignments.md
  api-reference/v1.0/api/user-update.md
  api-reference/v1.0/resources/user.md
  concepts/permissions-reference.md
  concepts/throttling.md
Labels: internal

#13673 Add new policy to policyRoot
  api-reference/beta/resources/policyroot.md
Labels: internal, ready to merge

#13722 Minor fix, add odata type
  api-reference/beta/resources/keycredential.md
  api-reference/v1.0/resources/keycredential.md
Labels: area: azure/AAD, internal, ready to merge

#13730 Merging latest changes in main to live
  api-reference/beta/resources/keycredential.md
  api-reference/beta/resources/policyroot.md
  api-reference/v1.0/resources/keycredential.md
Labels: do not merge, internal

#13733 Updated .NET snippets for SDK v4
  concepts/sdks/choose-authentication-providers.md
Labels: ready to merge, internal

#13425 [Azure AD] [ELM] created reprocess api
  api-reference/beta/api/accesspackageassignment-reprocess.md
  api-reference/beta/api/accesspackageassignmentrequest-reprocess.md
  api-reference/beta/resources/accesspackageassignment.md
  api-reference/beta/resources/accesspackageassignmentrequest.md
  api-reference/beta/toc.yml
  changelog/Microsoft.DirectoryServices.json
Labels: do not merge, ready to merge, internal, content review complete

#13785 Added prerequisites for Windows Powershell
  concepts/powershell/installation.md
Labels: ready to merge, internal

#13754 Application owners can now be reviewers
  concepts/accessreviews-reviewers-concept.md
Labels: area: azure/AAD, ready to merge, internal

#13757 Fixes #11748, #13496 - Request new snippet generation
  api-reference/beta/api/accessreviewscheduledefinition-update.md
  api-reference/beta/includes/snippets/csharp/update-accessreviewscheduledefinition-csharp-snippets.md
  api-reference/v1.0/api/accessreviewscheduledefinition-update.md
  api-reference/v1.0/includes/snippets/csharp/update-accessreviewscheduledefinition-csharp-snippets.md
Labels: area: azure/AAD, ready to merge, internal

#13755 Fix #13723, Add note for apps soft delete
  api-reference/beta/api/application-delete.md
  api-reference/beta/api/group-delete.md
  api-reference/v1.0/api/application-delete.md
  api-reference/v1.0/api/group-delete.md
Labels: area: azure/AAD, ready to merge, internal

#13743 Fix role management policies in TOC
  api-reference/beta/toc.yml
Labels: ready to merge, internal

#13788 Merging latest changes in main to live
  api-reference/beta/api/accesspackageassignment-reprocess.md
  api-reference/beta/api/accesspackageassignmentrequest-reprocess.md
  api-reference/beta/api/accessreviewscheduledefinition-update.md
  api-reference/beta/api/application-delete.md
  api-reference/beta/api/group-delete.md
  api-reference/beta/includes/snippets/csharp/update-accessreviewscheduledefinition-csharp-snippets.md
  api-reference/beta/resources/accesspackageassignment.md
  api-reference/beta/resources/accesspackageassignmentrequest.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/accessreviewscheduledefinition-update.md
  api-reference/v1.0/api/application-delete.md
  api-reference/v1.0/api/group-delete.md
  api-reference/v1.0/includes/snippets/csharp/update-accessreviewscheduledefinition-csharp-snippets.md
  changelog/Microsoft.DirectoryServices.json
  concepts/accessreviews-reviewers-concept.md
  concepts/powershell/installation.md
  concepts/sdks/choose-authentication-providers.md
Labels: internal

#13759 [Teams] Add toc entries under resource-specific permission grants
  api-reference/beta/resources/resourcespecificpermissiongrant.md
  api-reference/beta/toc.yml
  api-reference/v1.0/resources/resourcespecificpermissiongrant.md
Labels: ready to merge, internal

#13527 Update sdks-overview.md
  concepts/sdks/sdks-overview.md
Labels: external, ready to merge

#13558 Update toc.yml
  api-reference/v1.0/toc.yml
Labels: external, ready to merge

#13640 On 'Remove member from chat' article, fixed required delegate permissions
  api-reference/beta/api/chat-delete-members.md
  api-reference/v1.0/api/chat-delete-members.md
Labels: external

#13639 Update teams-concept-overview.md
  concepts/teams-concept-overview.md
Labels: external, ready to merge

#13688 Update webhooks-lifecycle.md
  concepts/webhooks-lifecycle.md
Labels: external

#13648 Update grouplifecyclepolicy.md
  api-reference/beta/resources/grouplifecyclepolicy.md
Labels: external, ready to merge

#13664 Update user-update.md
  api-reference/v1.0/api/user-update.md
Labels: external, ready to merge

#13685 Add example URLs for non-me users
  api-reference/v1.0/api/attachment-createuploadsession.md
Labels: external

#13696 Clarity/Correction needed for note about a single App Access Policy a…
  concepts/auth-limit-mailbox-access.md
Labels: external

#13732 Update call-keepalive.md
  api-reference/beta/api/call-keepalive.md
Labels: external

#13761 Update cloudpconpremisesconnection-updateaddomainpassword.md
  api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md
Labels: external

#13768 Update cloudpconpremisesconnection.md
  api-reference/beta/resources/cloudpconpremisesconnection.md
Labels: external

#13772 Update service-communications-api-overview.md
  api-reference/beta/resources/service-communications-api-overview.md
Labels: external

#13796 Clarify that "same dependency" batch requests are executed sequentially
  concepts/known-issues.md
Labels: external, ready to merge

#13455 Fix link, fixes #13437
  api-reference/beta/resources/invitation.md
  api-reference/v1.0/resources/invitation.md
Labels: do not merge, ready to merge, internal

#13535 bug fixes for july train
  api-reference/beta/api/educationclass-post-assignments.md
  api-reference/beta/resources/educationassignmentdefaults.md
  api-reference/v1.0/api/educationclass-post-assignment.md
Labels: ready to merge, content review complete, schema live

#13674 added a link to Graph on Q&A
  concepts/index.yml
Labels: ready to merge, content review, internal

#13697 Update group.md
  api-reference/beta/api/group-post-groups.md
  api-reference/beta/resources/group.md
  api-reference/v1.0/api/group-post-groups.md
  api-reference/v1.0/resources/group.md
Labels: ready to merge, internal, content review complete

#13734 Adding all property references to the dataset schemas.
  concepts/data-connect-datasets.md
Labels: ready to merge, internal, content review complete, schema live

#13744 Update references of beta to v1.0
  concepts/teams-create-group-and-team.md
Labels: ready to merge

#13776 Fix#13769, request code snippets
  api-reference/beta/api/group-list-members.md
  api-reference/v1.0/api/group-list-members.md
Labels: do not merge, ready to merge, internal

#13803 fixing conflicts in tutorial
  concepts/tutorial-riskdetection-api.md
Labels: internal

#13806 updating title for datasets page
  concepts/data-connect-datasets.md
Labels: ready to merge, internal

#12973 Minor updates to access reviews(Beta)
  api-reference/beta/resources/accessreviewinstance.md
  api-reference/beta/resources/accessreviewinstancedecisionitemresource.md
  api-reference/beta/resources/accessreviewreviewer.md
  api-reference/beta/resources/accessreviewschedulesettings.md
  changelog/Microsoft.IdentityGovernance.AccessReviews.json
Labels: area: azure/AAD, ready to merge, content review complete, schema live

#13041 added new complex and action, updated changelog
  api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md
  api-reference/beta/resources/accesspackage.md
  api-reference/beta/resources/accesspackageassignmentrequestrequirements.md
  api-reference/beta/toc.yml
  changelog/Microsoft.DirectoryServices.json
Labels: area: azure/AAD, ready to merge, internal

#13196 Minor updates to access reviews(v1.0)
  api-reference/v1.0/resources/accessreviewinstance.md
  changelog/Microsoft.IdentityGovernance.AccessReviews.json
Labels: area: azure/AAD, ready to merge, content review complete, schema live

#13807 Fixes #13496 #11748 - add missing Content-type header
  api-reference/beta/api/accessreviewscheduledefinition-update.md
  api-reference/beta/includes/snippets/csharp/update-accessreviewscheduledefinition-csharp-snippets.md
  api-reference/v1.0/api/accessreviewscheduledefinition-update.md
  api-reference/v1.0/includes/snippets/csharp/update-accessreviewscheduledefinition-csharp-snippets.md
Labels: ready to merge, internal

#13814 Minor fixes
  api-reference/beta/resources/authenticationmethodtarget.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/microsoftauthenticatorauthenticationmethodtarget.md
  api-reference/v1.0/resources/enums.md
  concepts/accessreviews-overview.md
Labels: do not merge, ready to merge, internal

#13810 Link to guide for self-signed cert creation
  concepts/powershell/app-only.md
Labels: ready to merge, internal

#13786 Adding examples for eligible/active scoping
  concepts/accessreviews-scope-concept.md
Labels: area: azure/AAD, ready to merge, content review complete

#13812 Update certificatebasedauthconfiguration-post-certificatebasedauthcon…
  api-reference/v1.0/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration.md
Labels: external

#13823 Merge to publish.
  api-reference/beta/resources/authenticationmethodtarget.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/microsoftauthenticatorauthenticationmethodtarget.md
  api-reference/v1.0/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration.md
  api-reference/v1.0/resources/enums.md
  concepts/accessreviews-overview.md
  concepts/accessreviews-scope-concept.md
  concepts/powershell/app-only.md
Labels: internal

#13813 Update what's new from the last few weeks.
  api-reference/beta/resources/appManagementPolicy.md
  api-reference/beta/resources/applicationAuthMethodPolicy.md
  changelog/Microsoft.DirectoryServices.json
  changelog/Microsoft.M365ServiceCommsPlatform.json
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: do not merge, internal

#13824 Refresh what's new topic.
  api-reference/beta/resources/appManagementPolicy.md
  api-reference/beta/resources/applicationAuthMethodPolicy.md
  changelog/Microsoft.DirectoryServices.json
  changelog/Microsoft.M365ServiceCommsPlatform.json
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: internal

#13259 Move some meeting options from beta to v1.0
  api-reference/beta/api/onlinemeeting-update.md
  api-reference/v1.0/api/onlinemeeting-update.md
  api-reference/v1.0/resources/onlinemeeting.md
  changelog/Microsoft.Skype.Calling.json
Labels: ready to merge, internal, content review complete

#13830 Merge to publish.
  api-reference/beta/api/onlinemeeting-update.md
  api-reference/v1.0/api/onlinemeeting-update.md
  api-reference/v1.0/resources/onlinemeeting.md
  changelog/Microsoft.Skype.Calling.json
Labels: internal

#13801 Add FAQ article for Azure AD Graph to Microsoft Graph migration
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
  concepts/images/aadgraph-to-msgraph-migration/AppClientIDFilter.png
  concepts/images/aadgraph-to-msgraph-migration/AppOwners.png
  concepts/images/aadgraph-to-msgraph-migration/RequestedAPI-AAD.png
  concepts/images/aadgraph-to-msgraph-migration/RequestedAPI.png
  concepts/images/aadgraph-to-msgraph-migration/configuredPermissions.png
  concepts/images/aadgraph-to-msgraph-migration/tenantTechnicalContact.png
  concepts/migrate-azure-ad-graph-faq.md
  concepts/toc.yml
Labels: area: azure/AAD, do not merge, ready to merge, internal

#13839 Merge to publish.
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
  concepts/images/aadgraph-to-msgraph-migration/AppClientIDFilter.png
  concepts/images/aadgraph-to-msgraph-migration/AppOwners.png
  concepts/images/aadgraph-to-msgraph-migration/RequestedAPI-AAD.png
  concepts/images/aadgraph-to-msgraph-migration/RequestedAPI.png
  concepts/images/aadgraph-to-msgraph-migration/configuredPermissions.png
  concepts/images/aadgraph-to-msgraph-migration/tenantTechnicalContact.png
  concepts/migrate-azure-ad-graph-faq.md
  concepts/toc.yml
Labels: internal

#13651 adding .All to applications permissions scope
  api-reference/beta/api/educationassignment-get-rubric.md
  api-reference/beta/api/educationassignment-get.md
  api-reference/beta/api/educationassignment-list-categories.md
  api-reference/beta/api/educationassignment-list-resources.md
  api-reference/beta/api/educationassignment-list-submissions.md
  api-reference/beta/api/educationassignmentdefaults-get.md
  api-reference/beta/api/educationassignmentresource-get.md
  api-reference/beta/api/educationassignmentsettings-get.md
  api-reference/beta/api/educationcategory-get.md
  api-reference/beta/api/educationclass-list-assignments.md
  api-reference/beta/api/educationclass-list-categories.md
  api-reference/beta/api/educationrubric-get.md
  api-reference/beta/api/educationsubmission-get.md
  api-reference/beta/api/educationsubmission-list-outcomes.md
  api-reference/beta/api/educationsubmission-list-resources.md
  api-reference/beta/api/educationsubmission-list-submittedresources.md
  api-reference/beta/api/educationsubmissionresource-get.md
  api-reference/beta/api/educationsubmittedsubmissionresource-get.md
  api-reference/v1.0/api/educationassignment-get-rubric.md
  api-reference/v1.0/api/educationassignment-get.md
  api-reference/v1.0/api/educationassignment-list-categories.md
  api-reference/v1.0/api/educationassignment-list-resources.md
  api-reference/v1.0/api/educationassignment-list-submissions.md
  api-reference/v1.0/api/educationassignmentdefaults-get.md
  api-reference/v1.0/api/educationassignmentresource-get.md
  api-reference/v1.0/api/educationassignmentsettings-get.md
  api-reference/v1.0/api/educationcategory-get.md
  api-reference/v1.0/api/educationclass-list-assignments.md
  api-reference/v1.0/api/educationclass-list-categories.md
  api-reference/v1.0/api/educationrubric-get.md
  api-reference/v1.0/api/educationsubmission-get.md
  api-reference/v1.0/api/educationsubmission-list-outcomes.md
  api-reference/v1.0/api/educationsubmission-list-resources.md
  api-reference/v1.0/api/educationsubmission-list-submittedresources.md
  api-reference/v1.0/api/educationsubmissionresource-get.md
  api-reference/v1.0/api/educationsubmittedsubmissionresource-get.md
Labels: ready to merge, internal, content review complete, schema live

#13828 Main
  api-reference/v1.0/resources/participant.md
  changelog/Microsoft.Skype.Calling.json
Labels: ready to merge, internal, content review complete

#13833 Surface 'Use PowerShell' in reference TOC
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
Labels: ready to merge, internal

#13836 Minor fixes to access reviews
  api-reference/beta/api/accessreviewscheduledefinition-post.md
  api-reference/beta/api/accessreviewscheduledefinition-update.md
  api-reference/beta/resources/accessreviewinstancedecisionitem.md
  api-reference/beta/resources/accessreviewscheduledefinition.md
  api-reference/beta/resources/accessreviewscope.md
  api-reference/v1.0/api/accessreviewscheduledefinition-post.md
  api-reference/v1.0/api/accessreviewscheduledefinition-update.md
  api-reference/v1.0/resources/accessreviewinstancedecisionitem.md
  api-reference/v1.0/resources/accessreviewscheduledefinition.md
  api-reference/v1.0/resources/accessreviewscope.md
Labels: ready to merge, internal

#13703 July trains - error codes and required property
  api-reference/beta/api/educationoutcome-update.md
  api-reference/beta/resources/educationassignmentresource.md
  api-reference/v1.0/api/educationoutcome-update.md
  api-reference/v1.0/resources/educationassignmentresource.md
Labels: ready to merge, internal, content review complete, schema live

#13844 Merge to publish.
  api-reference/beta/api/accessreviewscheduledefinition-post.md
  api-reference/beta/api/accessreviewscheduledefinition-update.md
  api-reference/beta/api/educationassignment-get-rubric.md
  api-reference/beta/api/educationassignment-get.md
  api-reference/beta/api/educationassignment-list-categories.md
  api-reference/beta/api/educationassignment-list-resources.md
  api-reference/beta/api/educationassignment-list-submissions.md
  api-reference/beta/api/educationassignmentdefaults-get.md
  api-reference/beta/api/educationassignmentresource-get.md
  api-reference/beta/api/educationassignmentsettings-get.md
  api-reference/beta/api/educationcategory-get.md
  api-reference/beta/api/educationclass-list-assignments.md
  api-reference/beta/api/educationclass-list-categories.md
  api-reference/beta/api/educationoutcome-update.md
  api-reference/beta/api/educationrubric-get.md
  api-reference/beta/api/educationsubmission-get.md
  api-reference/beta/api/educationsubmission-list-outcomes.md
  api-reference/beta/api/educationsubmission-list-resources.md
  api-reference/beta/api/educationsubmission-list-submittedresources.md
  api-reference/beta/api/educationsubmissionresource-get.md
  api-reference/beta/api/educationsubmittedsubmissionresource-get.md
  api-reference/beta/resources/accessreviewinstancedecisionitem.md
  api-reference/beta/resources/accessreviewscheduledefinition.md
  api-reference/beta/resources/accessreviewscope.md
  api-reference/beta/resources/educationassignmentresource.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/accessreviewscheduledefinition-post.md
  api-reference/v1.0/api/accessreviewscheduledefinition-update.md
  api-reference/v1.0/api/educationassignment-get-rubric.md
  api-reference/v1.0/api/educationassignment-get.md
  api-reference/v1.0/api/educationassignment-list-categories.md
  api-reference/v1.0/api/educationassignment-list-resources.md
  api-reference/v1.0/api/educationassignment-list-submissions.md
  api-reference/v1.0/api/educationassignmentdefaults-get.md
  api-reference/v1.0/api/educationassignmentresource-get.md
  api-reference/v1.0/api/educationassignmentsettings-get.md
  api-reference/v1.0/api/educationcategory-get.md
  api-reference/v1.0/api/educationclass-list-assignments.md
  api-reference/v1.0/api/educationclass-list-categories.md
  api-reference/v1.0/api/educationoutcome-update.md
  api-reference/v1.0/api/educationrubric-get.md
  api-reference/v1.0/api/educationsubmission-get.md
  api-reference/v1.0/api/educationsubmission-list-outcomes.md
  api-reference/v1.0/api/educationsubmission-list-resources.md
  api-reference/v1.0/api/educationsubmission-list-submittedresources.md
  api-reference/v1.0/api/educationsubmissionresource-get.md
  api-reference/v1.0/api/educationsubmittedsubmissionresource-get.md
  api-reference/v1.0/resources/accessreviewinstancedecisionitem.md
  api-reference/v1.0/resources/accessreviewscheduledefinition.md
  api-reference/v1.0/resources/accessreviewscope.md
  api-reference/v1.0/resources/educationassignmentresource.md
  api-reference/v1.0/resources/participant.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.Skype.Calling.json
Labels: internal

#13719 Update auth provider docs for JavaScript
  concepts/sdks/choose-authentication-providers.md
Labels: ready to merge, internal

#13577 Noninteractivesignindatetime Graph update
  api-reference/beta/api/user-list.md
  api-reference/beta/resources/signinactivity.md
  changelog/Microsoft.AAD.Reporting.json
Labels: ready to merge, internal, content review complete

#13847 Fixes to permissions
  api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md
  api-reference/beta/api/authenticationmethodsroot-usersregisteredbymethod.md
  api-reference/beta/api/chatmessage-get.md
  api-reference/beta/api/chatmessage-list-hostedcontents.md
  api-reference/beta/api/chatmessagehostedcontent-get.md
  api-reference/beta/resources/authenticationmethods-usage-insights-overview.md
  api-reference/v1.0/api/chatmessage-get.md
  changelog/Microsoft.DirectoryServices.json
  concepts/changelog-archive.md
  concepts/permissions-reference.md
  concepts/whats-new-earlier.md
Labels: ready to merge, internal

#13860 Update termstore-term-update.md
  api-reference/beta/api/termstore-term-update.md
Labels: external

#13841 Update whats-new-overview.md
  concepts/whats-new-overview.md
Labels: external

#13840 Update deployments.md
  concepts/deployments.md
Labels: external

#13834 Add note for proof lacking support for padding character
  concepts/application-rollkey-prooftoken.md
Labels: external

#12673 contact-get.md update HTTP request hierarchy
  api-reference/v1.0/api/contact-get.md
Labels: external, review requested

#13827 Replace outdated API's for team membership changes
  api-reference/beta/api/group-delete-owners.md
  api-reference/beta/resources/teams-api-overview.md
  api-reference/v1.0/api/group-delete-owners.md
  api-reference/v1.0/resources/teams-api-overview.md
  concepts/known-issues.md
Labels: ready to merge, ready for content review

#13820 changing tenantAppManagementPolicy to defaultAppManagementPolicy
  api-reference/beta/api/appManagementPolicy-post.md
  api-reference/beta/api/tenantAppManagementPolicy-get.md
  api-reference/beta/api/tenantAppManagementPolicy-update.md
  api-reference/beta/resources/applicationAuthenticationMethodPolicy.md
  api-reference/beta/resources/policy-overview.md
  api-reference/beta/resources/tenantAppManagementPolicy.md
  api-reference/beta/toc.yml
Labels: ready to merge, internal

#12136 Add sample code to retrieve IDs for permissions
  concepts/permissions-reference.md
Labels: external, ready to merge, content review complete

#13668 Teams - Updating chatMessageInfo and membersAddedEventMessageDetail resources
  api-reference/beta/api/chat-list.md
  api-reference/beta/resources/chatmessageinfo.md
  api-reference/beta/resources/membersaddedeventmessagedetail.md
  changelog/Microsoft.Teams.Core.json
  concepts/system-messages.md
Labels: ready to merge, internal, content review complete

#13798 Add endGracePeriod API to CloudPC entity
  api-reference/beta/api/cloudpc-endgraceperiod.md
  api-reference/beta/resources/cloudpc.md
  api-reference/beta/toc.yml
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, internal, content review complete

#13763 Added new property recordAutomatically to online meeting
  api-reference/beta/resources/onlinemeeting.md
  changelog/Microsoft.Skype.Calling.json
Labels: ready to merge, internal, content review complete

#13864 Adding note to make admins aware that GPS is not supported in USGov.
  api-reference/beta/resources/countrynamedlocation.md
  api-reference/v1.0/resources/countrynamedlocation.md
Labels: ready to merge, content review complete

#13868 Expand on accessPackageAssignmentRequest's relationships
  api-reference/beta/resources/accesspackageassignmentrequest.md
Labels: ready to merge, internal

#13881 Jodah permissionchanges
  api-reference/beta/api/group-update-event.md
  api-reference/v1.0/api/group-update-event.md
Labels: ready to merge, internal, content review complete

#13869 Edit Teams and Group membership API pages
  api-reference/beta/api/group-delete-members.md
  api-reference/beta/api/group-delete-owners.md
  api-reference/beta/api/group-post-members.md
  api-reference/beta/api/group-post-owners.md
  api-reference/beta/resources/teams-api-overview.md
  api-reference/v1.0/api/group-delete-members.md
  api-reference/v1.0/api/group-delete-owners.md
  api-reference/v1.0/api/group-post-members.md
  api-reference/v1.0/api/group-post-owners.md
  api-reference/v1.0/resources/teams-api-overview.md
  concepts/known-issues.md
Labels: ready to merge, internal, content review complete

#13779 updates to Advanced Queries:
  concepts/aad-advanced-queries.md
  concepts/images/advanced-query-parameters/advanced.png
  concepts/images/advanced-query-parameters/advanced.svg
  concepts/images/advanced-query-parameters/default.png
  concepts/images/advanced-query-parameters/default.svg
  concepts/images/advanced-query-parameters/notSupported.svg
  includes/filter-directory-objects.md
  tatus`q
Labels: ready to merge, internal, content review complete

#13857 Update user-list-memberof.md
  api-reference/v1.0/api/user-list-memberof.md
Labels: ready to merge, internal, content review complete

#13902 - bumps the java sdk versions
  concepts/sdks/sdk-installation.md
Labels: ready to merge, internal, area: SDKs

#13908 Fix link, resolve #13906
  concepts/application-saml-sso-configure-api.md
Labels: area: azure/AAD, ready to merge, internal

#13856 Update user-checkmembergroups.md
  api-reference/v1.0/api/user-checkmembergroups.md
Labels: ready to merge, ready for content review, internal

#13911 Update best-practices-concept.md
  concepts/best-practices-concept.md
Labels: external

#13903 Update call.md
  api-reference/v1.0/resources/call.md
Labels: external

#13891 Update bookingbusiness-publish.md
  api-reference/beta/api/bookingbusiness-publish.md
Labels: external

#13883 Update termstore-term.md
  api-reference/beta/resources/termstore-term.md
Labels: external

#13915 Merge to publish.
  api-reference/beta/api/bookingbusiness-publish.md
  api-reference/beta/resources/termstore-term.md
  api-reference/v1.0/api/user-checkmembergroups.md
  api-reference/v1.0/api/user-list-memberof.md
  api-reference/v1.0/resources/call.md
  concepts/aad-advanced-queries.md
  concepts/application-saml-sso-configure-api.md
  concepts/best-practices-concept.md
  concepts/images/advanced-query-parameters/advanced.png
  concepts/images/advanced-query-parameters/advanced.svg
  concepts/images/advanced-query-parameters/default.png
  concepts/images/advanced-query-parameters/default.svg
  concepts/images/advanced-query-parameters/notSupported.svg
  concepts/sdks/sdk-installation.md
  includes/filter-directory-objects.md
  tatus`q
Labels: internal

#13904 Redirect file cleanup
  .openpublishing.publish.config.json
  .openpublishing.redirection.json
  api-reference/beta/toc.yml
  concepts/migrate-azure-ad-graph-overview.md
  redirects/.openpublishing.redirection.0121.json
  redirects/.openpublishing.redirection.0721.json
  redirects/.openpublishing.redirection.0820.json
  redirects/.openpublishing.redirection.0920.json
  redirects/.openpublishing.redirection.1120.json
Labels: do not merge, internal, content review complete

#13861 update mgt-file-list with new attributes and options from file-upload.
  concepts/toolkit/components/file-list.md
Labels: external, review requested

#13929 Remove beta warnings from v1 doc
  api-reference/v1.0/api/presence-clearpresence.md
  api-reference/v1.0/api/presence-setpresence.md
Labels: ready to merge, internal

#13926 Update onlinemeeting-get.md
  api-reference/beta/api/onlinemeeting-get.md
Labels: external

#13925 Update onlinemeeting-get.md
  api-reference/v1.0/api/onlinemeeting-get.md
Labels: external

#13922 Fix capitalization of Salesforce name
  concepts/connecting-external-content-connectors-overview.md
Labels: ready to merge, internal

#13924 Update application-post-onlinemeetings.md
  api-reference/beta/api/application-post-onlinemeetings.md
Labels: external

#13923 Update teams-create-group-and-team.md
  concepts/teams-create-group-and-team.md
Labels: external

#13909 Fix #13387, document SocialIdp
  api-reference/beta/resources/serviceprincipal.md
  api-reference/v1.0/resources/serviceprincipal.md
Labels: ready to merge, internal

#13912 Change number of groups API can return
  api-reference/beta/api/group-post-groups.md
  api-reference/beta/api/user-getmembergroups.md
  api-reference/v1.0/api/group-post-groups.md
  api-reference/v1.0/api/user-getmembergroups.md
Labels: ready to merge, internal

#13887 Update externalconnectors-property.md
  api-reference/beta/resources/externalconnectors-property.md
Labels: ready to merge, internal, content review complete

#13888 Update externalconnectors-property.md in V1 docs
  api-reference/v1.0/resources/externalconnectors-property.md
Labels: internal

#13889 Update externalconnectors-schema-create.md for v1.0
  api-reference/v1.0/api/externalconnectors-schema-create.md
Labels: internal

#13842 Update RegisterAppOnly.ps1 to allow passing tenant ID to Connect-MgGraph
  concepts/powershell/RegisterAppOnly.ps1
  concepts/powershell/app-only.md
Labels: ready to merge, internal

#13055 Updated TypeScript sample for SDK v3
  concepts/sdks/large-file-upload.md
Labels: ready to merge, internal

#13742 incorrect odatatype - customer issue
  api-reference/beta/api/educationsubmission-post-resources.md
  api-reference/v1.0/api/educationsubmission-post-resources.md
Labels: ready to merge, internal, content review complete, schema live

#13890 Update externalconnectors-schema-create.md for beta
  api-reference/beta/api/externalconnectors-externalconnection-post-schema.md
Labels: ready to merge, internal, content review complete

#12095 Fix examples in Groups topic
  api-reference/beta/api/directorysetting-get.md
  api-reference/beta/api/directorysetting-list.md
  api-reference/beta/api/directorysetting-post-settings.md
  api-reference/beta/api/directorysettingtemplate-get.md
  api-reference/beta/api/directorysettingtemplate-list.md
  api-reference/beta/api/group-assignlicense.md
  api-reference/beta/api/group-delta.md
  api-reference/beta/api/group-getmembergroups.md
  api-reference/beta/api/group-getmemberobjects.md
  api-reference/beta/api/subscribedsku-list.md
  api-reference/v1.0/api/group-assignlicense.md
  api-reference/v1.0/api/group-delta.md
  api-reference/v1.0/api/group-getmembergroups.md
  api-reference/v1.0/api/group-getmemberobjects.md
  api-reference/v1.0/api/groupsetting-list.md
  api-reference/v1.0/api/groupsetting-post-groupsettings.md
  api-reference/v1.0/api/groupsetting-update.md
  api-reference/v1.0/api/groupsettingtemplate-get.md
  api-reference/v1.0/api/groupsettingtemplate-list.md
Labels: do not merge, ready to merge, internal

#13928 made changes to mailnickname in the table
  api-reference/beta/api/group-post-groups.md
  api-reference/v1.0/api/group-post-groups.md
Labels: ready to merge, internal, review feedback addressed

#13913 Update RSC permissions for calls on chats and meetings.
  api-reference/beta/api/application-post-calls.md
  concepts/permissions-reference.md
Labels: ready to merge, internal

#13939 Resolves #13590, fix order of permissions
  api-reference/v1.0/api/application-post-applications.md
Labels: area: azure/AAD, ready to merge, internal

#13946 Resolves #13921, Indicate correct permissions
  api-reference/beta/api/serviceprincipal-addkey.md
  api-reference/beta/api/serviceprincipal-addpassword.md
  api-reference/beta/api/serviceprincipal-removekey.md
  api-reference/beta/resources/passwordcredential.md
  api-reference/v1.0/api/serviceprincipal-addkey.md
  api-reference/v1.0/api/serviceprincipal-addpassword.md
  api-reference/v1.0/api/serviceprincipal-removekey.md
  api-reference/v1.0/resources/passwordcredential.md
  api-reference/v1.0/resources/serviceprincipal.md
Labels: area: azure/AAD, ready to merge, internal

#13948 Add reference to data retention policy
  api-reference/beta/api/signin-list.md
  api-reference/beta/resources/signin.md
  api-reference/v1.0/api/signin-list.md
  api-reference/v1.0/resources/signin.md
Labels: area: azure/AAD, ready to merge, internal

#13952 Update contenttype-post-columns.md
  api-reference/beta/api/contenttype-post-columns.md
Labels: external

#13951 Update contenttype-update.md
  api-reference/beta/api/contenttype-update.md
Labels: external

#13949 Wrong Id in Service Principal Patch call
  concepts/application-saml-sso-configure-api.md
Labels: external

#13940 Fix braces in proxy provider docs
  concepts/toolkit/providers/proxy.md
Labels: external

#13955 Merge to publish.
  api-reference/beta/api/application-post-calls.md
  api-reference/beta/api/contenttype-post-columns.md
  api-reference/beta/api/contenttype-update.md
  api-reference/beta/api/directorysetting-get.md
  api-reference/beta/api/directorysetting-list.md
  api-reference/beta/api/directorysetting-post-settings.md
  api-reference/beta/api/directorysettingtemplate-get.md
  api-reference/beta/api/directorysettingtemplate-list.md
  api-reference/beta/api/educationsubmission-post-resources.md
  api-reference/beta/api/externalconnectors-externalconnection-post-schema.md
  api-reference/beta/api/group-assignlicense.md
  api-reference/beta/api/group-delta.md
  api-reference/beta/api/group-getmembergroups.md
  api-reference/beta/api/group-getmemberobjects.md
  api-reference/beta/api/group-post-groups.md
  api-reference/beta/api/serviceprincipal-addkey.md
  api-reference/beta/api/serviceprincipal-addpassword.md
  api-reference/beta/api/serviceprincipal-removekey.md
  api-reference/beta/api/signin-list.md
  api-reference/beta/api/subscribedsku-list.md
  api-reference/beta/resources/passwordcredential.md
  api-reference/beta/resources/signin.md
  api-reference/v1.0/api/application-post-applications.md
  api-reference/v1.0/api/educationsubmission-post-resources.md
  api-reference/v1.0/api/group-assignlicense.md
  api-reference/v1.0/api/group-delta.md
  api-reference/v1.0/api/group-getmembergroups.md
  api-reference/v1.0/api/group-getmemberobjects.md
  api-reference/v1.0/api/group-post-groups.md
  api-reference/v1.0/api/groupsetting-list.md
  api-reference/v1.0/api/groupsetting-post-groupsettings.md
  api-reference/v1.0/api/groupsetting-update.md
  api-reference/v1.0/api/groupsettingtemplate-get.md
  api-reference/v1.0/api/groupsettingtemplate-list.md
  api-reference/v1.0/api/serviceprincipal-addkey.md
  api-reference/v1.0/api/serviceprincipal-addpassword.md
  api-reference/v1.0/api/serviceprincipal-removekey.md
  api-reference/v1.0/api/signin-list.md
  api-reference/v1.0/resources/passwordcredential.md
  api-reference/v1.0/resources/serviceprincipal.md
  api-reference/v1.0/resources/signin.md
  concepts/application-saml-sso-configure-api.md
  concepts/permissions-reference.md
  concepts/powershell/RegisterAppOnly.ps1
  concepts/powershell/app-only.md
  concepts/sdks/large-file-upload.md
  concepts/toolkit/providers/proxy.md
Labels: internal

#13938 Create excel.md
  api-reference/v1.0/resources/excel.md
Labels: bug: documentation, ready to merge, internal

#13204 Added Limitations description in event-delta CalendarView and None, N…
  api-reference/beta/api/event-delta.md
  api-reference/beta/resources/responsestatus.md
  api-reference/v1.0/api/event-delta.md
  api-reference/v1.0/resources/responsestatus.md
Labels: content review in progress

#13974 Simple typo fix
  concepts/data-connect-quickstart-05.md
Labels: external

#13971 Update contenttype-associatewithhubsites.md
  api-reference/beta/api/contenttype-associatewithhubsites.md
Labels: external

#13970 Update contenttype-addcopy.md
  api-reference/beta/api/contenttype-addcopy.md
Labels: external

#13967 Resolves #13953, query parameter support by posts API
  api-reference/beta/api/conversationthread-list-posts.md
  api-reference/beta/resources/post.md
  api-reference/v1.0/api/conversationthread-list-posts.md
  api-reference/v1.0/resources/post.md
Labels: ready to merge, internal

#13966 Resolves #13954, add query parameter support
  api-reference/beta/api/conversation-delete.md
  api-reference/beta/api/conversation-get.md
  api-reference/beta/api/conversation-list-threads.md
  api-reference/beta/api/conversation-post-threads.md
  api-reference/beta/api/group-list-conversations.md
  api-reference/beta/api/group-post-conversations.md
  api-reference/beta/resources/conversation.md
  api-reference/v1.0/api/conversation-delete.md
  api-reference/v1.0/api/conversation-get.md
  api-reference/v1.0/api/conversation-list-threads.md
  api-reference/v1.0/api/conversation-post-threads.md
  api-reference/v1.0/api/group-list-conversations.md
  api-reference/v1.0/api/group-post-conversations.md
  api-reference/v1.0/resources/conversation.md
  api-reference/v1.0/resources/conversationthread.md
Labels: area: azure/AAD, ready to merge, internal

#13961 Minor updates to User resource and methods
  api-reference/beta/api/user-activateserviceplan.md
  api-reference/beta/resources/user.md
  api-reference/v1.0/resources/user.md
Labels: area: azure/AAD, area: users, ready to merge, internal

#13962 Add note that duration type should be in ISO 8601 format
  api-reference/beta/resources/expirationpattern.md
Labels: area: azure/AAD, ready to merge, internal

#13964 Fixed incorrect label
  api-reference/v1.0/api/oauth2permissiongrant-delta.md
Labels: external, ready to merge

#13973 Update list-post-columns.md
  api-reference/beta/api/list-post-columns.md
Labels: external, ready to merge

#13976 RBAC mention that EM provider now supports query by appScopeId
  api-reference/beta/api/rbacapplication-list-roleassignments.md
Labels: area: azure/AAD, ready to merge, internal, content review complete

#14014 Update directory resource
  api-reference/beta/resources/directory.md
  api-reference/v1.0/resources/directory.md
Labels: area: azure/AAD, ready to merge, internal

#14017 Add redirects for identity provider docs
  redirects/.openpublishing.redirection.0721.json
Labels: ready to merge, internal

#14026 Fixing Typo in getSiteInfoUsageDetail beta api
  api-reference/beta/api/reportroot-getsharepointsiteusagedetail.md
  api-reference/beta/resources/sharepointsiteusagedetail.md
Labels: ready to merge

#13920 Update activity feed RSC permissions
  api-reference/beta/api/chat-sendactivitynotification.md
  api-reference/beta/api/team-sendactivitynotification.md
  api-reference/v1.0/api/team-sendactivitynotification.md
  concepts/permissions-reference.md
Labels: ready to merge, internal

#14020 Add changelog for app role assignment paging in beta
  changelog/Microsoft.DirectoryServices.json
  concepts/whats-new-overview.md
Labels: area: azure/AAD, ready to merge, area: app model, internal, area: app role assigment, area: applications

#14037 Resolves #11524, Azure AD Graph vs Microsoft Graph property differences
  api-reference/beta/resources/application.md
  api-reference/v1.0/resources/application.md
  concepts/migrate-azure-ad-graph-property-differences.md
Labels: ready to merge, internal

#14042 Fix version and casing for getRecentNotebooks API
  api-reference/beta/api/notebook-getrecentnotebooks.md
Labels: external, ready to merge

#14041 Update subscription.md
  api-reference/beta/resources/subscription.md
Labels: external

#14040 Update subscription.md
  api-reference/v1.0/resources/subscription.md
Labels: external

#14039 Update webhooks.md
  api-reference/v1.0/resources/webhooks.md
Labels: external

#14038 Update webhooks.md
  api-reference/beta/resources/webhooks.md
Labels: external

#14027 Update reportroot-getmailboxusagedetail.md
  api-reference/v1.0/api/reportroot-getmailboxusagedetail.md
Labels: external

#13829 Adding forgotten API: /shares/shareIdOrEncodedSharingUrl
  api-reference/beta/api/driveitem-get-content.md
  api-reference/v1.0/api/driveitem-get-content.md
Labels: external, ready to merge

#14046 Update workbook-list-tables.md
  api-reference/v1.0/api/workbook-list-tables.md
Labels: bug: documentation, ready to merge, internal
