Repository microsoftgraph/microsoft-graph-docs, pull requests merged in 2021-09, with the labels that each got.

#14060 Update teams-subscription-notes.md
  api-reference/includes/teams-subscription-notes.md
Labels: external

#13893 Add meeting details to chat
  api-reference/beta/api/chat-get.md
  api-reference/beta/resources/chat.md
  api-reference/beta/resources/teamworkhostedcontent.md
  api-reference/beta/resources/teamworkonlinemeetinginfo.md
  api-reference/v1.0/resources/teamworkhostedcontent.md
  changelog/Microsoft.Teams.GraphSvc.json
Labels: ready to merge, content review complete

#14075 Fixed typo
  api-reference/v1.0/api/appconsentrequest-list.md
Labels: external

#14073 Fixed typo
  api-reference/v1.0/api/workbookoperation-get.md
Labels: external

#14072 Fixed typo
  api-reference/v1.0/api/directory-deleteditems-get.md
Labels: external

#14105 Update team-post.md
  api-reference/beta/api/team-post.md
Labels: external

#12938 Docs for SoftwareOATH
  api-reference/beta/api/authentication-list-methods.md
  api-reference/beta/api/authentication-list-softwareoathmethods.md
  api-reference/beta/api/softwareoathauthenticationmethod-delete.md
  api-reference/beta/api/softwareoathauthenticationmethod-get.md
  api-reference/beta/resources/authenticationmethods-overview.md
  api-reference/beta/resources/softwareoathauthenticationmethod.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/authentication-list-methods.md
  changelog/Microsoft.DirectoryServices.json
Labels: area: azure/AAD, ready to merge

#14079 Resolves ##14067, Add Device permissions
  api-reference/beta/api/device-checkmemberobjects.md
  api-reference/beta/api/device-delete.md
  api-reference/beta/api/device-get.md
  api-reference/beta/api/device-list-memberof.md
  api-reference/beta/api/device-list-registeredowners.md
  api-reference/beta/api/device-list-registeredusers.md
  api-reference/beta/api/device-list-transitivememberof.md
  api-reference/beta/api/device-list-usagerights.md
  api-reference/beta/api/device-list.md
  api-reference/beta/api/device-update.md
  api-reference/v1.0/api/device-checkmemberobjects.md
  api-reference/v1.0/api/device-delete.md
  api-reference/v1.0/api/device-get.md
  api-reference/v1.0/api/device-list-memberof.md
  api-reference/v1.0/api/device-list-registeredowners.md
  api-reference/v1.0/api/device-list-registeredusers.md
  api-reference/v1.0/api/device-list.md
  api-reference/v1.0/api/device-update.md
Labels: ready to merge, internal

#14099 Resolves #14078, remove outdated known issue
  concepts/known-issues.md
Labels: ready to merge, internal

#14102 Resolves #14018, remove incorrect delta method
  api-reference/beta/api/directoryobject-delta.md
  api-reference/beta/resources/directoryobject.md
  api-reference/v1.0/resources/directoryobject.md
Labels: area: azure/AAD, ready to merge, internal

#13129 Added description in Update event file
  api-reference/beta/api/event-update.md
  api-reference/v1.0/api/event-update.md
Labels: ready to merge, content review complete

#14119 Add a step to Use Postman article
  concepts/use-postman.md
Labels: internal

#14095 Various fixes to risky user API
  api-reference/beta/api/riskyuser-list-history.md
  api-reference/beta/api/riskyuserhistoryitem-get.md
  api-reference/beta/api/riskyusers-confirmcompromised.md
  api-reference/beta/api/riskyusers-dismiss.md
  api-reference/v1.0/api/riskyuser-get-riskyuserhistoryitem.md
Labels: area: azure/AAD, area: identity protection, ready to merge, internal

#14121 Add known issue for Azure AD reporting APIs
  api-reference/beta/api/user-list.md
  api-reference/beta/resources/user.md
  concepts/known-issues.md
Labels: area: azure/AAD, ready to merge, internal

#14127 Update driveitem.md
  api-reference/v1.0/resources/driveitem.md
Labels: external

#14126 Update driveitem.md
  api-reference/beta/resources/driveitem.md
Labels: external

#14114 Fixed typo
  api-reference/beta/api/directory-deleteditems-get.md
Labels: external

#14000 Release Live Event in Graphv1.0
  api-reference/beta/api/application-post-onlinemeetings.md
  api-reference/beta/resources/broadcastmeetingsettings.md
  api-reference/beta/resources/onlinemeeting.md
  api-reference/v1.0/api/application-post-onlinemeetings.md
  api-reference/v1.0/resources/broadcastmeetingsettings.md
  api-reference/v1.0/resources/meetingparticipantinfo.md
  api-reference/v1.0/resources/onlinemeeting.md
  changelog/Microsoft.Skype.Calling.json
Labels: ready to merge, internal, content review complete

#13933 Update setUpResourcesFolder from Function to Action
  api-reference/beta/api/educationassignment-setupresourcesfolder.md
  api-reference/beta/api/educationsubmission-setupResourcesFolder.md
  api-reference/v1.0/api/educationassignment-setupresourcesfolder.md
  api-reference/v1.0/api/educationsubmission-setupResourcesFolder.md
  changelog/Microsoft.EducationAssignment.json
Labels: ready to merge, content review complete, schema live

#12045 [Azure AD roles] Unified RBAC API - v1.0
  api-reference/v1.0/api/rbacapplication-list-roleassignments.md
  api-reference/v1.0/api/rbacapplication-list-roledefinitions.md
  api-reference/v1.0/api/rbacapplication-post-roleassignments.md
  api-reference/v1.0/api/rbacapplication-post-roledefinitions.md
  api-reference/v1.0/api/unifiedroleassignment-delete.md
  api-reference/v1.0/api/unifiedroleassignment-get.md
  api-reference/v1.0/api/unifiedroledefinition-delete.md
  api-reference/v1.0/api/unifiedroledefinition-get.md
  api-reference/v1.0/api/unifiedroledefinition-update.md
  api-reference/v1.0/resources/appscope.md
  api-reference/v1.0/resources/rbacapplication.md
  api-reference/v1.0/resources/rolemanagement.md
  api-reference/v1.0/resources/unifiedroleassignment.md
  api-reference/v1.0/resources/unifiedroledefinition.md
  api-reference/v1.0/resources/unifiedrolepermission.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.DirectoryServices.json
Labels: area: azure/AAD, ready to merge, internal, content review complete, schema live

#13885 User-centric Teams messaging subscription documentation
  api-reference/beta/api/subscription-delete.md
  api-reference/beta/api/subscription-get.md
  api-reference/beta/api/subscription-post-subscriptions.md
  api-reference/beta/api/subscription-update.md
  api-reference/beta/resources/webhooks.md
  api-reference/includes/teams-subscription-notes.md
  concepts/teams-changenotifications-chatmessage.md
Labels: ready to merge, internal, content review complete

#14146 Azure AD Graph to Microsoft Graph migration doc fixes
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
  concepts/migrate-azure-ad-graph-app-registration.md
  concepts/migrate-azure-ad-graph-audit-api-use.md
  concepts/migrate-azure-ad-graph-authentication-library.md
  concepts/migrate-azure-ad-graph-client-libraries.md
  concepts/migrate-azure-ad-graph-deploy-test-extend.md
  concepts/migrate-azure-ad-graph-feature-differences.md
  concepts/migrate-azure-ad-graph-method-differences.md
  concepts/migrate-azure-ad-graph-overview.md
  concepts/migrate-azure-ad-graph-planning-checklist.md
  concepts/migrate-azure-ad-graph-property-differences.md
  concepts/migrate-azure-ad-graph-request-differences.md
  concepts/migrate-azure-ad-graph-resource-differences.md
  redirects/.openpublishing.redirection.0920.json
Labels: area: azure/AAD, ready to merge, internal

#14131 Add example for all teams review
  concepts/accessreviews-scope-concept.md
Labels: area: azure/AAD, ready to merge, content review complete

#14148 Correct wrong permission entries
  api-reference/beta/api/group-list-owners.md
  api-reference/beta/api/profilephoto-get.md
  api-reference/beta/api/profilephoto-update.md
  api-reference/v1.0/api/group-list-owners.md
  api-reference/v1.0/api/group-post-groups.md
  api-reference/v1.0/api/profilephoto-get.md
  api-reference/v1.0/api/profilephoto-update.md
Labels: area: azure/AAD, ready to merge, internal

#14149 Updated Domain operation permissions
  api-reference/beta/api/domain-delete.md
  api-reference/beta/api/domain-forcedelete.md
  api-reference/beta/api/domain-get.md
  api-reference/beta/api/domain-list-domainnamereferences.md
  api-reference/beta/api/domain-list-serviceconfigurationrecords.md
  api-reference/beta/api/domain-list-verificationdnsrecords.md
  api-reference/beta/api/domain-list.md
  api-reference/beta/api/domain-post-domains.md
  api-reference/beta/api/domain-update.md
  api-reference/beta/api/domain-verify.md
  api-reference/v1.0/api/domain-delete.md
  api-reference/v1.0/api/domain-forcedelete.md
  api-reference/v1.0/api/domain-get.md
  api-reference/v1.0/api/domain-list-domainnamereferences.md
  api-reference/v1.0/api/domain-list-serviceconfigurationrecords.md
  api-reference/v1.0/api/domain-list-verificationdnsrecords.md
  api-reference/v1.0/api/domain-list.md
  api-reference/v1.0/api/domain-post-domains.md
  api-reference/v1.0/api/domain-update.md
  api-reference/v1.0/api/domain-verify.md
Labels: area: azure/AAD, ready to merge, internal, content review complete

#13858 2021 08 09 mahage ediscovery sites groups
  api-reference/beta/api/ediscovery-custodian-post-sitesources.md
  api-reference/beta/api/ediscovery-custodian-post-unifiedgroupsources.md
  api-reference/beta/api/ediscovery-legalhold-post-sitesources.md
  api-reference/beta/api/ediscovery-legalhold-post-usersources.md
  api-reference/beta/api/ediscovery-noncustodialdatasource-post.md
  api-reference/beta/api/ediscovery-sourcecollection-post-additionalsources.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Compliance.Ediscovery.json
Labels: ready to merge, internal, content review complete

#14138 update documents
  api-reference/beta/resources/report.md
  api-reference/v1.0/resources/report.md
  concepts/reportroot-authorization.md
Labels: ready to merge, internal, content review complete

#14008 Toolkit 2.3 Release Docs
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
  concepts/toc.yml
  concepts/toolkit/components/file-list.md
  concepts/toolkit/components/people-picker.md
  concepts/toolkit/get-started/add-aad-app-registration.md
  concepts/toolkit/get-started/build-a-microsoft-teams-sso-tab.md
  concepts/toolkit/get-started/build-a-microsoft-teams-tab.md
  concepts/toolkit/get-started/build-a-web-app.md
  concepts/toolkit/get-started/overview.md
  concepts/toolkit/get-started/use-toolkit-with-angular.md
  concepts/toolkit/get-started/use-toolkit-with-react.md
  concepts/toolkit/overview.md
  concepts/toolkit/providers/msal.md
  concepts/toolkit/providers/msal2.md
  concepts/toolkit/providers/providers.md
  concepts/toolkit/providers/teams-msal2.md
  concepts/toolkit/providers/teams.md
Labels: ready to merge, internal, content review complete, area: toolkit, review feedback addressed

#14182 Update team.md
  api-reference/beta/resources/team.md
Labels: external

#14181 Update team.md
  api-reference/v1.0/resources/team.md
Labels: external

#14154 Fixed typo: EduRoster.WriteWrite.All
  api-reference/beta/api/educationclass-delta.md
  api-reference/v1.0/api/educationclass-delta.md
Labels: ready to merge

#13794 Danielwood95resilience defaults
  api-reference/beta/resources/conditionalaccesssessioncontrols.md
  changelog/Microsoft.IdentityProtectionServices.json
Labels: area: azure/AAD, ready to merge, internal, content review complete, schema live

#13039 Update Drive and Sites Search App Permission Not Supported
  api-reference/beta/api/driveitem-search.md
  api-reference/beta/api/site-search.md
  api-reference/v1.0/api/driveitem-search.md
  api-reference/v1.0/api/site-search.md
Labels: ready to merge, ready for content review, internal, review feedback addressed

#14163 Various doc fixes
  api-reference/beta/api/claimsmappingpolicy-get.md
  api-reference/beta/api/claimsmappingpolicy-list-appliesto.md
  api-reference/beta/api/claimsmappingpolicy-list.md
  api-reference/beta/api/claimsmappingpolicy-post-claimsmappingpolicies.md
  api-reference/beta/api/claimsmappingpolicy-update.md
  api-reference/beta/api/directory-deleteditems-list.md
  api-reference/beta/api/directoryaudit-get.md
  api-reference/beta/api/directoryaudit-list.md
  api-reference/beta/api/provisioningobjectsummary-list.md
  api-reference/beta/api/serviceprincipal-delete-claimsmappingpolicies.md
  api-reference/beta/api/serviceprincipal-list-claimsmappingpolicies.md
  api-reference/beta/api/serviceprincipal-post-claimsmappingpolicies.md
  api-reference/beta/api/signin-get.md
  api-reference/beta/api/signin-list.md
  api-reference/beta/api/subscribedsku-list.md
  api-reference/beta/api/unifiedroleassignmentschedulerequest-post-unifiedroleassignmentschedulerequests.md
  api-reference/beta/api/unifiedroleeligibilityschedulerequest-post-unifiedroleeligibilityschedulerequests.md
  api-reference/beta/resources/accessreviewsv2-root.md
  api-reference/beta/resources/claimsmappingpolicy.md
  api-reference/beta/resources/directory.md
  api-reference/beta/resources/subscribedsku.md
  api-reference/includes/directory-featurerolloutpolicies-deprecate.md
  api-reference/v1.0/api/claimsmappingpolicy-get.md
  api-reference/v1.0/api/claimsmappingpolicy-list-appliesto.md
  api-reference/v1.0/api/claimsmappingpolicy-list.md
  api-reference/v1.0/api/claimsmappingpolicy-post-claimsmappingpolicies.md
  api-reference/v1.0/api/claimsmappingpolicy-update.md
  api-reference/v1.0/api/directory-deleteditems-list.md
  api-reference/v1.0/api/directoryaudit-get.md
  api-reference/v1.0/api/directoryaudit-list.md
  api-reference/v1.0/api/provisioningobjectsummary-list.md
  api-reference/v1.0/api/serviceprincipal-delete-claimsmappingpolicies.md
  api-reference/v1.0/api/serviceprincipal-list-claimsmappingpolicies.md
  api-reference/v1.0/api/signin-get.md
  api-reference/v1.0/api/signin-list.md
  api-reference/v1.0/api/subscribedsku-list.md
  api-reference/v1.0/resources/accessreviewsv2-root.md
  api-reference/v1.0/resources/claimsmappingpolicy.md
  api-reference/v1.0/resources/directory.md
  api-reference/v1.0/resources/subscribedsku.md
  concepts/accessreviews-scope-concept.md
Labels: area: azure/AAD, ready to merge

#13822 Add docs related to start and stop hold music APIs
  api-reference/beta/api/participant-startholdmusic.md
  api-reference/beta/api/participant-stopholdmusic.md
  api-reference/beta/resources/participant.md
  api-reference/beta/resources/startholdmusicoperation.md
  api-reference/beta/resources/stopholdmusicoperation.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Skype.Calling.json
Labels: ready to merge, internal, content review complete

#13795 added changes for malware addition in driveitem and changelogs
  api-reference/beta/api/driveitem-delta.md
  api-reference/beta/resources/driveitem.md
  api-reference/beta/resources/malware.md
  api-reference/v1.0/api/driveitem-delta.md
  api-reference/v1.0/resources/driveitem.md
  api-reference/v1.0/resources/malware.md
  changelog/Microsoft.FileServices.json
Labels: ready to merge, content review complete

#14205 Fixed example for GET organizationSettings.
  api-reference/beta/api/organizationsettings-get.md
Labels: internal

#14202 Update threatassessmentrequest.md
  api-reference/beta/resources/threatassessmentrequest.md
Labels: external

#14201 Update threatassessmentrequest.md
  api-reference/v1.0/resources/threatassessmentrequest.md
Labels: external

#14197 Minor fixes to known issues article
  api-reference/beta/api/claimsmappingpolicy-get.md
  api-reference/beta/api/claimsmappingpolicy-list.md
  api-reference/beta/api/conditionalaccesspolicy-update.md
  api-reference/v1.0/api/claimsmappingpolicy-get.md
  api-reference/v1.0/api/claimsmappingpolicy-list.md
  api-reference/v1.0/api/conditionalaccesspolicy-update.md
  concepts/known-issues.md
Labels: area: azure/AAD, ready to merge, internal

#14193 Corrected typo "mght" into "might"
  api-reference/v1.0/resources/report.md
Labels: external

#13582 Update group-list-threads.md
  api-reference/beta/api/group-list-threads.md
  api-reference/v1.0/api/group-list-threads.md
Labels: external, ready to merge, content review complete

#14208 Merge to publish.
  api-reference/beta/api/claimsmappingpolicy-get.md
  api-reference/beta/api/claimsmappingpolicy-list.md
  api-reference/beta/api/conditionalaccesspolicy-update.md
  api-reference/beta/api/group-list-threads.md
  api-reference/beta/api/organizationsettings-get.md
  api-reference/beta/resources/threatassessmentrequest.md
  api-reference/v1.0/api/claimsmappingpolicy-get.md
  api-reference/v1.0/api/claimsmappingpolicy-list.md
  api-reference/v1.0/api/conditionalaccesspolicy-update.md
  api-reference/v1.0/api/group-list-threads.md
  api-reference/v1.0/resources/report.md
  api-reference/v1.0/resources/threatassessmentrequest.md
  concepts/known-issues.md
Labels: internal

#14213 Fix typo in title
  concepts/whats-new-earlier.md
Labels: internal

#14021 added totalParticipantCount to meetingAttendanceReport
  api-reference/beta/api/onlinemeeting-get.md
  api-reference/beta/resources/meetingAttendanceReport.md
  changelog/Microsoft.Skype.Calling.json
Labels: ready to merge, internal, content review complete

#14199 remove groupTypes and mailEnabled
  api-reference/beta/api/group-update.md
  api-reference/v1.0/api/group-update.md
Labels: ready to merge, internal, content review complete

#14209 Fix changelog sync
  changelog/Microsoft.IdentityProtectionServices.json
Labels: ready to merge, internal

#14214 Add character limit for reviewer descriptions in access review email …
  api-reference/beta/api/accessreviewscheduledefinition-post.md
  api-reference/beta/resources/accessreviewscheduledefinition.md
  api-reference/beta/resources/accessreviewschedulesettings.md
  api-reference/v1.0/api/accessreviewscheduledefinition-post.md
  api-reference/v1.0/resources/accessreviewscheduledefinition.md
Labels: area: azure/AAD, ready to merge, content review complete

#14218 MInor doc fixes
  api-reference/beta/api/emailauthenticationmethod-delete.md
  api-reference/beta/api/emailauthenticationmethod-get.md
  api-reference/beta/api/emailauthenticationmethod-post.md
  api-reference/beta/api/emailauthenticationmethod-update.md
  api-reference/beta/api/user-delete.md
  api-reference/beta/resources/policybase.md
  api-reference/v1.0/api/user-delete.md
  api-reference/v1.0/resources/policybase.md
  concepts/permissions-reference.md
Labels: area: azure/AAD, ready to merge, internal

#13854 Remove public preview note for Graph connectors
  concepts/search-concept-custom-types.md
Labels: ready to merge, internal, content review complete

#14224 Minor doc fixes
  api-reference/beta/api/directoryobject-checkmembergroups.md
  api-reference/beta/api/directoryobject-delete.md
  api-reference/beta/api/directoryobject-get.md
  api-reference/beta/api/directoryobject-getbyids.md
  api-reference/beta/api/directoryobject-getmembergroups.md
  api-reference/beta/api/unifiedroleeligibilityschedulerequest-post-unifiedroleeligibilityschedulerequests.md
  api-reference/beta/resources/directoryobject.md
  api-reference/beta/resources/unifiedroleeligibilityschedulerequest.md
  api-reference/v1.0/api/directoryobject-checkmembergroups.md
  api-reference/v1.0/api/directoryobject-delete.md
  api-reference/v1.0/api/directoryobject-get.md
  api-reference/v1.0/api/directoryobject-getbyids.md
  api-reference/v1.0/api/directoryobject-getmembergroups.md
  api-reference/v1.0/resources/directoryobject.md
Labels: area: azure/AAD, ready to merge, internal

#14235 Merge to publish.
  api-reference/beta/api/directoryobject-checkmembergroups.md
  api-reference/beta/api/directoryobject-delete.md
  api-reference/beta/api/directoryobject-get.md
  api-reference/beta/api/directoryobject-getbyids.md
  api-reference/beta/api/directoryobject-getmembergroups.md
  api-reference/beta/api/unifiedroleeligibilityschedulerequest-post-unifiedroleeligibilityschedulerequests.md
  api-reference/beta/resources/directoryobject.md
  api-reference/beta/resources/unifiedroleeligibilityschedulerequest.md
  api-reference/v1.0/api/directoryobject-checkmembergroups.md
  api-reference/v1.0/api/directoryobject-delete.md
  api-reference/v1.0/api/directoryobject-get.md
  api-reference/v1.0/api/directoryobject-getbyids.md
  api-reference/v1.0/api/directoryobject-getmembergroups.md
  api-reference/v1.0/resources/directoryobject.md
  concepts/search-concept-custom-types.md
Labels: internal

#14241 Minor doc fixes
  api-reference/beta/api/invitation-post.md
  api-reference/beta/resources/invitation.md
  api-reference/v1.0/api/invitation-post.md
  concepts/migrate-azure-ad-graph-faq.md
Labels: area: azure/AAD, ready to merge, internal

#14243 UPN updates to objectIdentity
  api-reference/beta/resources/objectidentity.md
  api-reference/v1.0/resources/objectidentity.md
Labels: area: azure/AAD, ready to merge, internal, content review complete

#14217 Adding information about how we are changing the case type create case creates
  api-reference/beta/api/ediscovery-case-post.md
  api-reference/beta/resources/ediscovery-case.md
  changelog/Microsoft.Compliance.Ediscovery.json
Labels: ready to merge, internal, content review complete

#13532 delete accessPackageAssignmentRequest
  api-reference/beta/api/accesspackageassignmentrequest-delete.md
  api-reference/beta/resources/accesspackageassignmentrequest.md
  api-reference/beta/resources/entitlementmanagement-root.md
  api-reference/beta/toc.yml
  changelog/Microsoft.DirectoryServices.json
Labels: area: azure/AAD, ready to merge, internal, content review complete

#14016 Improve documentation quality - Bunch #2
  api-reference/beta/api/educationassignment-get.md
  api-reference/beta/api/educationassignment-list-categories.md
  api-reference/beta/api/educationassignment-list-resources.md
  api-reference/beta/api/educationassignment-list-submissions.md
  api-reference/beta/api/educationassignmentdefaults-get.md
  api-reference/beta/api/educationassignmentresource-get.md
  api-reference/beta/api/educationassignmentsettings-get.md
  api-reference/v1.0/api/educationassignment-get.md
  api-reference/v1.0/api/educationassignment-list-categories.md
  api-reference/v1.0/api/educationassignment-list-resources.md
  api-reference/v1.0/api/educationassignment-list-submissions.md
  api-reference/v1.0/api/educationassignmentdefaults-get.md
  api-reference/v1.0/api/educationassignmentresource-get.md
  api-reference/v1.0/api/educationassignmentsettings-get.md
Labels: ready to merge, internal, content review complete, schema live

#14132 Aug trains - Calendar integration
  api-reference/beta/resources/educationassignment.md
  api-reference/beta/resources/educationassignmentdefaults.md
  api-reference/beta/resources/enums.md
  api-reference/v1.0/resources/educationassignment.md
  changelog/Microsoft.EducationAssignment.json
Labels: ready to merge, internal, content review complete, schema live

#14216 Tthrottling on Mega Tenant create user request
  concepts/throttling.md
Labels: external, ready to merge, content review complete

#14255 Update deployments.md
  concepts/deployments.md
Labels: area: excel, ready to merge, internal

#14259 Minor doc fixes
  api-reference/beta/api/group-get.md
  api-reference/beta/api/identitycontainer-post-b2cuserflows.md
  api-reference/beta/api/identityuserflowattribute-list.md
  api-reference/beta/api/schemaextension-delete.md
  api-reference/beta/api/schemaextension-get.md
  api-reference/beta/api/schemaextension-list.md
  api-reference/beta/api/schemaextension-post-schemaextensions.md
  api-reference/beta/api/schemaextension-update.md
  api-reference/beta/api/user-list.md
  api-reference/v1.0/api/group-get.md
  api-reference/v1.0/api/identityuserflowattribute-list.md
  api-reference/v1.0/api/schemaextension-delete.md
  api-reference/v1.0/api/schemaextension-get.md
  api-reference/v1.0/api/schemaextension-list.md
  api-reference/v1.0/api/schemaextension-post-schemaextensions.md
  api-reference/v1.0/api/schemaextension-update.md
  api-reference/v1.0/api/user-list.md
Labels: area: azure/AAD, ready to merge, internal

#14267 Update dynamics-dimension.md
  api-reference/beta/resources/dynamics-dimension.md
Labels: external

#14245 Update bookingbusiness.md
  api-reference/beta/resources/bookingbusiness.md
Labels: external

#14251 [Docbug][Updated TOC]
  concepts/toc.yml
Labels: ready to merge, internal

#14286 Update messagerule.md
  api-reference/beta/resources/messagerule.md
Labels: external

#14285 Update messagerule.md
  api-reference/v1.0/resources/messagerule.md
Labels: external

#14282 Update permissions-reference.md
  concepts/permissions-reference.md
Labels: external, ready to merge

#13846 Subscriptions API | Doc changes to include private channels events
  api-reference/beta/api/subscription-delete.md
  api-reference/beta/api/subscription-get.md
  api-reference/beta/api/subscription-post-subscriptions.md
  api-reference/beta/api/subscription-update.md
  api-reference/beta/resources/webhooks.md
  concepts/teams-changenotifications-team-and-channel.md
  concepts/teams-changenotifications-teamMembership.md
  concepts/toc.yml
Labels: area: teams, ready to merge, internal, content review complete

#13862 Improve documentation quality - Bunch #1
  api-reference/beta/api/educationassignment-delete.md
  api-reference/beta/api/educationassignment-setupresourcesfolder.md
  api-reference/beta/resources/educationoutcome.md
  api-reference/beta/resources/educationresource.md
  api-reference/beta/resources/educationsubmission.md
  api-reference/v1.0/api/educationassignment-delete.md
  api-reference/v1.0/api/educationassignment-setupresourcesfolder.md
  api-reference/v1.0/resources/educationassignment.md
  api-reference/v1.0/resources/educationoutcome.md
  api-reference/v1.0/resources/educationresource.md
  api-reference/v1.0/resources/educationsubmission.md
Labels: ready to merge, internal, content review complete, schema live

#14232 Added documentation for new permission OnlineMeetingArtifact.Read.All
  changelog/Microsoft.Skype.Calling.json
  concepts/cloud-communication-online-meeting-application-access-policy.md
  concepts/permissions-reference.md
Labels: ready to merge, internal, content review complete

#14279 Minor doc fixes
  api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md
  api-reference/beta/api/directoryaudit-get.md
  api-reference/beta/api/directoryaudit-list.md
  api-reference/beta/api/group-list-approleassignments.md
  api-reference/beta/api/group-list-memberof.md
  api-reference/beta/api/group-list-members.md
  api-reference/beta/api/group-list-transitivememberof.md
  api-reference/beta/api/group-post-settings.md
  api-reference/beta/api/oauth2permissiongrant-get.md
  api-reference/beta/api/oauth2permissiongrant-list.md
  api-reference/beta/api/privilegedroleassignmentrequest-my.md
  api-reference/beta/api/provisioningobjectsummary-list.md
  api-reference/beta/api/serviceprincipal-list-memberof.md
  api-reference/beta/api/serviceprincipal-list-oauth2permissiongrants.md
  api-reference/beta/api/serviceprincipal-list-transitivememberof.md
  api-reference/beta/api/signin-get.md
  api-reference/beta/api/signin-list.md
  api-reference/beta/api/sites-list-followed.md
  api-reference/beta/api/subscription-get.md
  api-reference/beta/api/user-list-approleassignments.md
  api-reference/beta/api/user-list-memberof.md
  api-reference/beta/api/user-list-oauth2permissiongrants.md
  api-reference/beta/api/user-list-transitivememberof.md
  api-reference/beta/resources/accessreviewnotificationrecipientscope.md
  api-reference/beta/resources/authenticationlistener.md
  api-reference/beta/resources/authenticationsourcefilter.md
  api-reference/beta/resources/azure-ad-auditlog-overview.md
  api-reference/beta/resources/azure-ad-overview.md
  api-reference/beta/resources/cloudappsecuritysessioncontrol.md
  api-reference/beta/resources/conditionalaccessgrantcontrols.md
  api-reference/beta/resources/group.md
  api-reference/v1.0/api/accessreviewscheduledefinition-post.md
  api-reference/v1.0/api/b2xidentityuserflow-put-apiconnectorconfiguration.md
  api-reference/v1.0/api/directoryaudit-get.md
  api-reference/v1.0/api/directoryaudit-list.md
  api-reference/v1.0/api/group-list-approleassignments.md
  api-reference/v1.0/api/itemactivitystat-getactivitybyinterval.md
  api-reference/v1.0/api/itemanalytics-get.md
  api-reference/v1.0/api/oauth2permissiongrant-get.md
  api-reference/v1.0/api/oauth2permissiongrant-list.md
  api-reference/v1.0/api/provisioningobjectsummary-list.md
  api-reference/v1.0/api/serviceprincipal-list-memberof.md
  api-reference/v1.0/api/serviceprincipal-list-oauth2permissiongrants.md
  api-reference/v1.0/api/signin-get.md
  api-reference/v1.0/api/signin-list.md
  api-reference/v1.0/api/sites-list-followed.md
  api-reference/v1.0/api/subscription-get.md
  api-reference/v1.0/api/user-list-approleassignments.md
  api-reference/v1.0/api/user-list-oauth2permissiongrants.md
  includes/filter-directory-objects.md
Labels: area: azure/AAD, do not merge, ready to merge, internal

#14247 Update extensionAttributes docs
  api-reference/beta/resources/onpremisesextensionattributes.md
  api-reference/v1.0/resources/onpremisesextensionattributes.md
Labels: area: azure/AAD, ready to merge, internal

#14296 Search Update Link typo
  api-reference/beta/resources/searchrequest.md
Labels: ready to merge, internal

#14300 Update dynamics-account-get.md
  api-reference/beta/api/dynamics-account-get.md
Labels: external

#14299 Update service-communications-concept-overview.md
  concepts/service-communications-concept-overview.md
Labels: external

#13720 [CloudPC]Update imageId description in provisionpolicy
  api-reference/beta/api/cloudpcprovisioningpolicy-update.md
  api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md
  api-reference/beta/resources/cloudpcprovisioningpolicy.md
Labels: ready to merge, internal

#14291 Small fixes to code snippets
  concepts/toolkit/get-started/use-toolkit-with-react.md
Labels: external

#14315 Clarified and fixed some recent Excel content.
  api-reference/beta/api/table-post-rows.md
  api-reference/beta/api/workbook-tablerowoperationresult.md
  api-reference/v1.0/api/table-post-rows.md
  api-reference/v1.0/api/workbook-tablerowoperationresult.md
  changelog/Microsoft.Excel.json
Labels: do not merge, internal

#14311 Minor doc fixes
  api-reference/beta/api/organization-get.md
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
Labels: area: azure/AAD, ready to merge

#14312 Adding query option information to get cred thumbprint info
  api-reference/beta/api/application-get.md
  api-reference/beta/api/application-list.md
  api-reference/beta/api/serviceprincipal-get.md
  api-reference/beta/api/serviceprincipal-list.md
  api-reference/v1.0/api/application-get.md
  api-reference/v1.0/api/application-list.md
  api-reference/v1.0/api/serviceprincipal-get.md
  api-reference/v1.0/api/serviceprincipal-list.md
Labels: area: azure/AAD, ready to merge, internal, content review complete

#14321 Minor fixes
  concepts/accessreviews-scope-concept.md
  concepts/auth/auth-concepts.md
  concepts/graph-explorer/graph-explorer-features.md
  concepts/graph-explorer/graph-explorer-overview.md
  concepts/query-parameters.md
Labels: area: azure/AAD, ready to merge, internal

#14123 Create include file for intro text to property table in update topics
  api-reference/includes/update-property-table-intro.md
  api-reference/v1.0/api/event-update.md
Labels: internal

#14274 Update throttling.md
  concepts/throttling.md
Labels: external, ready to merge

#14332 Minor fixes
  api-reference/beta/api/group-list.md
  api-reference/beta/api/group-post-groups.md
  api-reference/beta/resources/group.md
  api-reference/v1.0/api/group-list.md
  api-reference/v1.0/api/group-post-groups.md
  api-reference/v1.0/resources/group.md
  concepts/azuread-identity-access-management-concept-overview.md
  concepts/group-set-options.md
Labels: area: azure/AAD, ready to merge

#14318 Update what's new topic for the last month!
  api-reference/beta/resources/educationassignment.md
  api-reference/beta/resources/educationassignmentdefaults.md
  changelog/Microsoft.DirectoryServices.json
  changelog/Microsoft.Skype.Calling.json
  concepts/search-concept-aggregation.md
  concepts/search-concept-overview.md
  concepts/search-concept-sort.md
  concepts/toc.yml
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: do not merge, internal

#14342 Refresh what's new topic.
  api-reference/beta/resources/educationassignment.md
  api-reference/beta/resources/educationassignmentdefaults.md
  changelog/Microsoft.DirectoryServices.json
  changelog/Microsoft.Skype.Calling.json
  concepts/search-concept-aggregation.md
  concepts/search-concept-overview.md
  concepts/search-concept-sort.md
  concepts/toc.yml
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: internal

#14350 Update optionalclaim.md
  api-reference/v1.0/resources/optionalclaim.md
Labels: external

#14349 Update optionalclaim.md
  api-reference/beta/resources/optionalclaim.md
Labels: external

#14348 Update whats-new-overview.md
  concepts/whats-new-overview.md
Labels: external

#14346 Minor fixes
  api-reference/beta/api/group-post-groups.md
  api-reference/beta/api/group-update.md
  api-reference/v1.0/api/group-post-groups.md
  api-reference/v1.0/api/group-update.md
Labels: area: azure/AAD, ready to merge, internal

#14345 Updated onlinemeeting-update.md with meeting option instructions
  api-reference/beta/api/onlinemeeting-update.md
  api-reference/v1.0/api/onlinemeeting-update.md
Labels: ready to merge, internal, content review complete

#14338 Update connecting-external-content-build-quickstart-03-build-app.md
  concepts/connecting-external-content-build-quickstart-03-build-app.md
Labels: external

#14335 Update dynamics-currencies.md
  api-reference/beta/resources/dynamics-currencies.md
Labels: external

#14334 Update intune-devices-manageddevice-locatedevice.md
  api-reference/v1.0/api/intune-devices-manageddevice-locatedevice.md
Labels: external

#14270 Onboarded new permission for meeting artifacts
  api-reference/beta/api/onlinemeeting-get.md
  concepts/cloud-communications-online-meeting-artifacts.md
  concepts/toc.yml
Labels: ready to merge, internal, content review complete

#13113 Added List and Create api files and its description in the calendarPe…
  api-reference/beta/api/calendar-list-calendarpermissions.md
  api-reference/beta/api/calendar-post-calendarpermissions.md
  api-reference/beta/api/calendarpermission-delete.md
  api-reference/beta/api/calendarpermission-get.md
  api-reference/beta/api/calendarpermission-update.md
  api-reference/beta/resources/calendarpermission.md
  api-reference/beta/resources/event.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/calendar-list-calendarpermissions.md
  api-reference/v1.0/api/calendar-post-calendarpermissions.md
  api-reference/v1.0/api/calendarpermission-delete.md
  api-reference/v1.0/api/calendarpermission-get.md
  api-reference/v1.0/api/calendarpermission-update.md
  api-reference/v1.0/resources/calendarpermission.md
  api-reference/v1.0/resources/event.md
  api-reference/v1.0/toc.yml
Labels: do not merge, conflicting, content review in progress

#14368 Update to latest version of eol-blocker
  .github/workflows/eol-blocker.yml
Labels: internal

#14372 Update directoryaudit-list.md
  api-reference/v1.0/api/directoryaudit-list.md
Labels: external

#14371 Update directoryaudit-list.md
  api-reference/beta/api/directoryaudit-list.md
Labels: external

#14364 Remove unwanted end of metadata
  api-reference/beta/resources/unifiedrolemanagementpolicyruletarget.md
Labels: external

#14357 Minor fixes
  api-reference/beta/api/device-delete.md
  api-reference/beta/api/device-get.md
  api-reference/beta/api/device-update.md
  api-reference/beta/resources/accessreviewsv2-root.md
  api-reference/beta/resources/device.md
  api-reference/beta/resources/user.md
  api-reference/v1.0/api/device-delete.md
  api-reference/v1.0/api/device-get.md
  api-reference/v1.0/api/device-update.md
  api-reference/v1.0/resources/accessreviewsv2-root.md
  api-reference/v1.0/resources/device.md
  api-reference/v1.0/resources/user.md
  concepts/aad-advanced-queries.md
  concepts/accessreviews-overview.md
  concepts/accessreviews-reviewers-concept.md
  concepts/accessreviews-scope-concept.md
Labels: area: azure/AAD, ready to merge, internal

#14107 Updating Organizational Branding beta
  api-reference/beta/api/organizationalbranding-delete.md
  api-reference/beta/api/organizationalbranding-get.md
  api-reference/beta/api/organizationalbranding-list-localizations.md
  api-reference/beta/api/organizationalbranding-post-localizations.md
  api-reference/beta/api/organizationalbranding-update.md
  api-reference/beta/api/organizationalbrandinglocalization-delete.md
  api-reference/beta/api/organizationalbrandinglocalization-get.md
  api-reference/beta/api/organizationalbrandinglocalization-update.md
  api-reference/beta/api/organizationalbrandingproperties-create.md
  api-reference/beta/api/organizationalbrandingproperties-delete.md
  api-reference/beta/api/organizationalbrandingproperties-get.md
  api-reference/beta/api/organizationalbrandingproperties-update.md
  api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md
  api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md
  api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md
  api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md
  api-reference/beta/resources/organization.md
  api-reference/beta/resources/organizationalbranding.md
  api-reference/beta/resources/organizationalbrandinglocalization.md
  api-reference/beta/resources/organizationalbrandingproperties.md
  api-reference/beta/toc.yml
Labels: area: azure/AAD, ready to merge, internal, content review complete

#13174 2021 06 17 tomsato printer state reasons
  api-reference/beta/resources/printerprocessingstatedetail.md
  api-reference/beta/resources/printerstatus.md
  api-reference/v1.0/resources/printerprocessingstatedetail.md
  api-reference/v1.0/resources/printerstatus.md
  changelog/Microsoft.PrintService.json
Labels: ready to merge, internal, area: universal print, content review complete

#14184 Aug Trains - Reassign Submission
  api-reference/beta/api/educationsubmission-reassign.md
  api-reference/beta/resources/educationsubmission.md
  api-reference/beta/resources/enums.md
  api-reference/beta/toc.yml
  changelog/Microsoft.EducationAssignment.json
  concepts/assignments-submissions-states-transition.md
  concepts/images/states-transitions/diagram-submissions.PNG
Labels: ready to merge, internal, content review complete, schema live

#14240 More info for preferredDataLocation - Groups
  api-reference/beta/api/group-post-groups.md
  api-reference/beta/api/group-update.md
  api-reference/beta/resources/group.md
  api-reference/v1.0/api/group-post-groups.md
  api-reference/v1.0/api/group-update.md
  api-reference/v1.0/resources/group.md
Labels: area: azure/AAD, area: groups, ready to merge, internal

#14378 Merge to publish.
  api-reference/v1.0/api/organizationalbranding-delete.md
  api-reference/v1.0/api/organizationalbranding-get.md
  api-reference/v1.0/api/organizationalbranding-list-localizations.md
  api-reference/v1.0/api/organizationalbranding-post-localizations.md
  api-reference/v1.0/api/organizationalbranding-update.md
  api-reference/v1.0/api/organizationalbrandinglocalization-delete.md
  api-reference/v1.0/api/organizationalbrandinglocalization-get.md
  api-reference/v1.0/api/organizationalbrandinglocalization-update.md
  api-reference/v1.0/api/organizationalbrandingproperties-create.md
  api-reference/v1.0/api/organizationalbrandingproperties-delete.md
  api-reference/v1.0/api/organizationalbrandingproperties-get.md
  api-reference/v1.0/api/organizationalbrandingproperties-update.md
  api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md
  api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md
  api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md
  api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md
  api-reference/v1.0/resources/azure-ad-overview.md
  api-reference/v1.0/resources/organization.md
  api-reference/v1.0/resources/organizationalbranding.md
  api-reference/v1.0/resources/organizationalbrandinglocalization.md
  api-reference/v1.0/resources/organizationalbrandingproperties.md
  api-reference/v1.0/toc.yml
Labels: do not merge, internal

#14225 Add redirects for organizational branding docs
  .openpublishing.publish.config.json
  redirects/.openpublishing.redirection.0921.json
Labels: area: azure/AAD, ready to merge, internal

#13397 added description for Id parameter
  api-reference/beta/api/calendar-list-events.md
  api-reference/beta/resources/event.md
  api-reference/v1.0/api/calendar-list-events.md
  api-reference/v1.0/resources/event.md
Labels: do not merge, internal

#14376 Minor fixes
  api-reference/beta/resources/organizationalbranding.md
  api-reference/beta/resources/organizationalbrandinglocalization.md
  api-reference/beta/resources/organizationalbrandingproperties.md
  api-reference/v1.0/api/rbacapplication-list-roleassignments.md
  includes/throttling-identity-and-access.md
Labels: area: azure/AAD, ready to merge, internal

#14389 Added immutable ID include file to appropriate resource topics
  api-reference/beta/resources/contact.md
  api-reference/beta/resources/event.md
  api-reference/beta/resources/eventmessage.md
  api-reference/beta/resources/eventmessageresponse.md
  api-reference/beta/resources/message.md
  api-reference/beta/resources/outlooktask.md
  api-reference/includes/outlook-immutable-id.md
  api-reference/v1.0/resources/contact.md
  api-reference/v1.0/resources/event.md
  api-reference/v1.0/resources/eventmessage.md
  api-reference/v1.0/resources/eventmessageresponse.md
  api-reference/v1.0/resources/message.md
Labels: internal

#14392 Improve online meeting documentation
  api-reference/beta/api/application-post-onlinemeetings.md
  api-reference/beta/api/onlinemeeting-get.md
  api-reference/beta/api/onlinemeeting-update.md
  api-reference/beta/resources/attendanceInterval.md
  api-reference/beta/resources/onlinemeeting.md
  api-reference/v1.0/api/application-post-onlinemeetings.md
  api-reference/v1.0/api/onlinemeeting-update.md
  api-reference/v1.0/resources/onlinemeeting.md
Labels: ready to merge, internal, content review complete

#13789 Add automatically generated documents - Microsoft.Security.AttackSimulation workload
  api-reference/beta/api/attacksimulationroot-list-simulations.md
  api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md
  api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md
  api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md
  api-reference/beta/api/simulationreportoverview-get.md
  api-reference/beta/api/usersimulationdetails-list.md
  api-reference/beta/resources/assignedtraininginfo.md
  api-reference/beta/resources/attacksimulationrepeatoffender.md
  api-reference/beta/resources/attacksimulationroot.md
  api-reference/beta/resources/attacksimulationsimulationusercoverage.md
  api-reference/beta/resources/attacksimulationtrainingusercoverage.md
  api-reference/beta/resources/attacksimulationuser.md
  api-reference/beta/resources/emailidentity.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/recommendedaction.md
  api-reference/beta/resources/report-m365defender-reports-overview.md
  api-reference/beta/resources/security-api-overview.md
  api-reference/beta/resources/security.md
  api-reference/beta/resources/simulation.md
  api-reference/beta/resources/simulationevent.md
  api-reference/beta/resources/simulationeventscontent.md
  api-reference/beta/resources/simulationreport.md
  api-reference/beta/resources/simulationreportoverview.md
  api-reference/beta/resources/trainingeventscontent.md
  api-reference/beta/resources/usersimulationdetails.md
  api-reference/beta/resources/usersimulationeventinfo.md
  api-reference/beta/resources/usertrainingcontenteventinfo.md
  api-reference/beta/resources/usertrainingeventinfo.md
  api-reference/beta/resources/usertrainingstatusinfo.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Security.AttackSimulation.json
Labels: do not merge, internal

#14394 Publish debut release of API docs for attack simulation and training.
  api-reference/beta/api/attacksimulationroot-list-simulations.md
  api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md
  api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md
  api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md
  api-reference/beta/api/simulationreportoverview-get.md
  api-reference/beta/api/usersimulationdetails-list.md
  api-reference/beta/resources/assignedtraininginfo.md
  api-reference/beta/resources/attacksimulationrepeatoffender.md
  api-reference/beta/resources/attacksimulationroot.md
  api-reference/beta/resources/attacksimulationsimulationusercoverage.md
  api-reference/beta/resources/attacksimulationtrainingusercoverage.md
  api-reference/beta/resources/attacksimulationuser.md
  api-reference/beta/resources/emailidentity.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/recommendedaction.md
  api-reference/beta/resources/report-m365defender-reports-overview.md
  api-reference/beta/resources/security-api-overview.md
  api-reference/beta/resources/security.md
  api-reference/beta/resources/simulation.md
  api-reference/beta/resources/simulationevent.md
  api-reference/beta/resources/simulationeventscontent.md
  api-reference/beta/resources/simulationreport.md
  api-reference/beta/resources/simulationreportoverview.md
  api-reference/beta/resources/trainingeventscontent.md
  api-reference/beta/resources/usersimulationdetails.md
  api-reference/beta/resources/usersimulationeventinfo.md
  api-reference/beta/resources/usertrainingcontenteventinfo.md
  api-reference/beta/resources/usertrainingeventinfo.md
  api-reference/beta/resources/usertrainingstatusinfo.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Security.AttackSimulation.json
Labels: internal

#14097 MS Graph connectors | Updating postman collection doc
  concepts/connecting-external-content-connectors-api-postman.md
  concepts/images/connectors-images/02-postman-my-workspace.png
  concepts/images/connectors-images/03-postman-import.png
  concepts/images/connectors-images/04-postman-link.png
  concepts/images/connectors-images/07-postman.png
  concepts/images/connectors-images/08-postman.png
  concepts/images/connectors-images/09a-postman.png
  concepts/images/connectors-images/10-postman.png
  concepts/images/connectors-images/11-postman.png
  concepts/images/connectors-images/16-postman.png
  concepts/images/connectors-images/17-postman.png
  concepts/images/connectors-images/18-postman.png
Labels: ready to merge, internal, content review complete

#14111 Add cloudPcSupportedRegion resource topic
  api-reference/beta/api/virtualendpoint-list-supportedregions.md
  api-reference/beta/resources/cloudpcsupportedregion.md
  api-reference/beta/resources/virtualendpoint.md
  api-reference/beta/toc.yml
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, internal, content review complete

#14406 corrected wrong words and unified format
  api-reference/beta/api/application-post-onlinemeetings.md
  api-reference/beta/api/onlinemeeting-delete.md
  api-reference/beta/api/onlinemeeting-get.md
  api-reference/beta/api/onlinemeeting-update.md
  api-reference/v1.0/api/application-post-onlinemeetings.md
  api-reference/v1.0/api/onlinemeeting-delete.md
  api-reference/v1.0/api/onlinemeeting-get.md
  api-reference/v1.0/api/onlinemeeting-update.md
Labels: ready to merge, internal, content review complete

#14405 Update conditionalaccessfilter.md
  api-reference/beta/resources/conditionalaccessfilter.md
Labels: external

#14404 Update conditionalaccessdevices.md
  api-reference/beta/resources/conditionalaccessdevices.md
Labels: external

#14409 Clarify "(preview)" to address partner confusion.
  concepts/versioning-and-support.md
Labels: internal

#14303 Added autorecord property in v1
  api-reference/v1.0/resources/onlinemeeting.md
  changelog/Microsoft.Skype.Calling.json
Labels: ready to merge, internal, content review complete

#14249 Update topic structure to standardize H3s.
  concepts/known-issues.md
Labels: do not merge, internal

#14415 docs: fix typo
  api-reference/v1.0/resources/requiredresourceaccess.md
Labels: external, ready to merge

#14423 Fix minor spelling issue in driveItem_list_thumbnail
  api-reference/beta/api/driveitem-list-thumbnails.md
  api-reference/v1.0/api/driveitem-list-thumbnails.md
Labels: ready for content review

#14204 2021 09 08 authenticator code match and context tristate
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/microsoftauthenticatorauthenticationmethodtarget.md
  api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md
  changelog/Microsoft.DirectoryServices.json
Labels: ready to merge, internal, content review complete, schema live

#14316 Added attendeeReport to onlineMeeting in v1.0
  api-reference/beta/api/onlinemeeting-get.md
  api-reference/v1.0/api/onlinemeeting-get.md
  api-reference/v1.0/resources/onlinemeeting.md
  changelog/Microsoft.Skype.Calling.json
Labels: ready to merge, internal, content review complete

#14297 Move Start/StopHoldMusic API resources from beta to v1
  api-reference/v1.0/api/participant-startholdmusic.md
  api-reference/v1.0/api/participant-stopholdmusic.md
  api-reference/v1.0/resources/participant.md
  api-reference/v1.0/resources/startholdmusicoperation.md
  api-reference/v1.0/resources/stopholdmusicoperation.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.Skype.Calling.json
Labels: ready to merge, internal, content review complete

#14265 2021 09 14 code matchv1 cleanup
  api-reference/v1.0/resources/enums.md
  api-reference/v1.0/resources/microsoftauthenticatorauthenticationmethodtarget.md
  changelog/Microsoft.DirectoryServices.json
Labels: ready to merge, internal, content review complete, schema live
