Repository microsoftgraph/microsoft-graph-docs, pull requests merged in 2021-11, with the labels that each got.

#14813 Windows updates APIs: safeguard settings and faulted deployment reason
  api-reference/beta/api/windowsupdates-updates-post-deployments.md
  api-reference/beta/resources/enums-windowsupdates.md
  api-reference/beta/resources/windowsupdates-deploymentsettings.md
  api-reference/beta/resources/windowsupdates-safeguardprofile.md
  api-reference/beta/resources/windowsupdates-safeguardsettings.md
  changelog/Microsoft.WindowsUpdates.json
  concepts/toc.yml
  concepts/windowsupdates-concept-overview.md
  concepts/windowsupdates-deploy-expedited-update.md
  concepts/windowsupdates-deploy-update.md
  concepts/windowsupdates-deployments.md
  concepts/windowsupdates-manage-monitoring-rules.md
  concepts/windowsupdates-manage-safeguards.md
  concepts/windowsupdates-schedule-deployment.md
Labels: internal

#14814 Merge to publish.
  api-reference/beta/api/windowsupdates-updates-post-deployments.md
  api-reference/beta/resources/enums-windowsupdates.md
  api-reference/beta/resources/windowsupdates-deploymentsettings.md
  api-reference/beta/resources/windowsupdates-safeguardprofile.md
  api-reference/beta/resources/windowsupdates-safeguardsettings.md
  changelog/Microsoft.WindowsUpdates.json
  concepts/toc.yml
  concepts/windowsupdates-concept-overview.md
  concepts/windowsupdates-deploy-expedited-update.md
  concepts/windowsupdates-deploy-update.md
  concepts/windowsupdates-deployments.md
  concepts/windowsupdates-manage-monitoring-rules.md
  concepts/windowsupdates-manage-safeguards.md
  concepts/windowsupdates-schedule-deployment.md
Labels: internal

#14816 Update externalconnectors-schema.md
  api-reference/v1.0/resources/externalconnectors-schema.md
Labels: external

#14815 Update externalconnectors-schema.md
  api-reference/beta/resources/externalconnectors-schema.md
Labels: external

#14289 Update serviceannouncement-list-messages.md
  api-reference/beta/api/serviceannouncement-list-messages.md
  api-reference/v1.0/api/serviceannouncement-list-messages.md
Labels: external, ready to merge, review feedback addressed

#14795 "application" should be "authentication"
  concepts/sdks/create-client.md
Labels: external, ready to merge, content review complete

#14798 Update site-getapplicablecontenttypesforlist.md
  api-reference/v1.0/api/site-getapplicablecontenttypesforlist.md
Labels: ready to merge, ready for content review, internal

#14799 Resolves #14780, fix broken links to permission reference + paging articles
  api-reference/beta/api/accesspackage-update.md
  api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md
  api-reference/beta/api/accesspackageassignmentpolicy-update.md
  api-reference/beta/api/accesspackagecatalog-update.md
  api-reference/beta/api/accessreview-list.md
  api-reference/beta/api/applicationsignindetailedsummary-get.md
  api-reference/beta/api/applicationsigninsummary-get.md
  api-reference/beta/api/chatmessage-delta.md
  api-reference/beta/api/columndefinition-delete.md
  api-reference/beta/api/columndefinition-get.md
  api-reference/beta/api/columndefinition-update.md
  api-reference/beta/api/contenttype-addcopy.md
  api-reference/beta/api/contenttype-associatewithhubsites.md
  api-reference/beta/api/contenttype-copytodefaultcontentlocation.md
  api-reference/beta/api/contenttype-delete.md
  api-reference/beta/api/contenttype-list-columns.md
  api-reference/beta/api/contenttype-publish.md
  api-reference/beta/api/contenttype-unpublish.md
  api-reference/beta/api/contenttype-update.md
  api-reference/beta/api/list-list-columns.md
  api-reference/beta/api/list-list-contenttypes.md
  api-reference/beta/api/site-list-columns.md
  api-reference/beta/api/site-list-contenttypes.md
  api-reference/beta/api/trustframework-post-trustframeworkpolicy.md
  api-reference/beta/api/trustframework-put-trustframeworkpolicy.md
  api-reference/beta/api/trustframeworkpolicy-delete.md
  api-reference/beta/api/trustframeworkpolicy-get.md
  api-reference/v1.0/api/chatmessage-delta.md
  api-reference/v1.0/api/columndefinition-delete.md
  api-reference/v1.0/api/columndefinition-get.md
  api-reference/v1.0/api/columndefinition-update.md
  api-reference/v1.0/api/contenttype-addcopy.md
  api-reference/v1.0/api/contenttype-associatewithhubsites.md
  api-reference/v1.0/api/contenttype-copytodefaultcontentlocation.md
  api-reference/v1.0/api/contenttype-delete.md
  api-reference/v1.0/api/contenttype-list-columns.md
  api-reference/v1.0/api/contenttype-publish.md
  api-reference/v1.0/api/contenttype-unpublish.md
  api-reference/v1.0/api/contenttype-update.md
  api-reference/v1.0/api/list-list-columns.md
  api-reference/v1.0/api/list-list-contenttypes.md
  api-reference/v1.0/api/riskdetection-get.md
  api-reference/v1.0/api/riskdetection-list.md
  api-reference/v1.0/api/riskyuser-confirmcompromised.md
  api-reference/v1.0/api/riskyuser-dismiss.md
  api-reference/v1.0/api/riskyuser-get-riskyuserhistoryitem.md
  api-reference/v1.0/api/riskyuser-get.md
  api-reference/v1.0/api/riskyuser-list-history.md
  api-reference/v1.0/api/riskyuser-list.md
  api-reference/v1.0/api/signin-get.md
  api-reference/v1.0/api/signin-list.md
  api-reference/v1.0/api/site-list-columns.md
  api-reference/v1.0/api/site-list-contenttypes.md
Labels: ready to merge, internal

#14801 update author on EM docs in /beta for people who have moved teams
  api-reference/beta/api/accesspackage-filterbycurrentuser.md
  api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md
  api-reference/beta/api/accesspackageassignmentrequest-cancel.md
  api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md
  api-reference/beta/api/approval-get.md
  api-reference/beta/api/approval-list-steps.md
  api-reference/beta/api/approvalstep-get.md
  api-reference/beta/api/approvalstep-update.md
  api-reference/beta/resources/accesspackage-accesspackagefilterbycurrentuseroptions.md
  api-reference/beta/resources/accesspackageassignment-accesspackageassignmentfilterbycurrentuseroptions.md
  api-reference/beta/resources/accesspackageassignmentrequest-accesspackageassignmentrequestfilterbycurrentuseroptions.md
  api-reference/beta/resources/approval.md
  api-reference/beta/resources/approvalstep.md
Labels: area: azure/AAD, ready to merge, internal, content review complete

#14803 Update user-update.md
  api-reference/beta/api/user-update.md
  api-reference/v1.0/api/user-update.md
Labels: area: azure/AAD, ready to merge, internal, content review complete

#14319 [Action Needed]Change the naming from cloud PC to Cloud PC
  api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md
  api-reference/beta/resources/cloudpcStatusDetails.md
  api-reference/beta/resources/cloudpconpremisesconnectionstatusdetails.md
Labels: ready to merge, internal, content review complete

#14831 Update chat-post-installedapps.md
  api-reference/beta/api/chat-post-installedapps.md
Labels: external

#14830 Update chat-post-installedapps.md
  api-reference/v1.0/api/chat-post-installedapps.md
Labels: external

#13447 [Azure AD roles] Create group in AU [beta]
  api-reference/beta/api/administrativeunit-post-members.md
  api-reference/beta/includes/snippets/csharp/post-administrativeunits-members-csharp-snippets.md
  api-reference/beta/includes/snippets/java/post-administrativeunits-members-java-snippets.md
  api-reference/beta/includes/snippets/javascript/post-administrativeunits-members-javascript-snippets.md
  api-reference/beta/includes/snippets/objc/post-administrativeunits-members-objc-snippets.md
  changelog/Microsoft.DirectoryServices.json
Labels: area: azure/AAD, ready to merge, internal, content review complete

#14133 Update cloud-communications-media.md
  concepts/cloud-communications-media.md
Labels: ready to merge, content review complete

#14821 Minor fixes
  api-reference/beta/resources/selfsignedcertificate.md
  api-reference/v1.0/api/application-list.md
  api-reference/v1.0/api/user-list.md
  api-reference/v1.0/resources/preauthorizedapplication.md
Labels: area: azure/AAD, ready to merge, internal

#14591 Graph doc - bug fixes
  api-reference/beta/api/educationassignment-list-submissions.md
  api-reference/beta/api/educationassignment-publish.md
  api-reference/beta/api/educationclass-list-assignments.md
  api-reference/beta/api/educationsubmission-post-resources.md
  api-reference/v1.0/api/educationassignment-list-submissions.md
  api-reference/v1.0/api/educationassignment-publish.md
  api-reference/v1.0/api/educationclass-list-assignments.md
  api-reference/v1.0/api/educationsubmission-post-resources.md
Labels: ready to merge, internal, content review complete, schema live

#14667 peopleInsights (Working With Changes)
  .github/workflows/changelog-validation.yml
  api-reference/beta/api/insightssettings-update.md
  api-reference/beta/api/iteminsightssettings-get.md
  api-reference/beta/api/iteminsightssettings-update.md
  api-reference/beta/api/organizationsettings-get.md
  api-reference/beta/api/organizationsettings-list-iteminsights.md
  api-reference/beta/api/organizationsettings-list-peopleinsights.md
  api-reference/beta/api/user-list-people.md
  api-reference/beta/resources/insightssettings.md
  api-reference/beta/resources/iteminsights.md
  api-reference/beta/resources/iteminsightssettings.md
  api-reference/beta/resources/organizationsettings.md
  api-reference/beta/resources/userinsightssettings.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/user-list-people.md
  changelog/Microsoft.OfficeGraph.json
  changelog/Microsoft.People.json
  concepts/insights-customize-item-insights-privacy.md
  concepts/insights-customize-people-insights-privacy.md
  concepts/item-insights-overview.md
  concepts/people-example.md
  concepts/social-intel-concept-overview.md
  concepts/toc.yml
  redirects/.openpublishing.redirection.1121.json
Labels: ready to merge

#14852 Update ediscovery-caseexportoperation.md
  api-reference/beta/resources/ediscovery-caseexportoperation.md
Labels: external

#14851 Update ediscovery-reviewsetquery-applytags.md
  api-reference/beta/api/ediscovery-reviewsetquery-applytags.md
Labels: external

#13855 mention requestor in GET of acecsspackageassignmentrequest
  api-reference/beta/api/accesspackageassignmentrequest-get.md
Labels: area: azure/AAD, ready to merge, internal, content review complete

#14838 Extends MGT React template example
  concepts/toolkit/get-started/mgt-react.md
Labels: ready to merge, internal

#14849 Fixes #14826
  api-reference/beta/api/user-update.md
  api-reference/v1.0/api/user-update.md
Labels: area: azure/AAD, area: users, ready to merge, internal

#14447 2021 09 29 mark chat read unread for user
  api-reference/beta/api/chat-markchatreadforuser.md
  api-reference/beta/api/chat-markchatunreadforuser.md
  api-reference/beta/resources/chat.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Teams.Core.json
Labels: ready to merge, internal, content review complete, schema live

#14854 Merge to publish.
  api-reference/beta/api/accesspackageassignmentrequest-get.md
  api-reference/beta/api/chat-markchatreadforuser.md
  api-reference/beta/api/chat-markchatunreadforuser.md
  api-reference/beta/api/ediscovery-reviewsetquery-applytags.md
  api-reference/beta/api/user-update.md
  api-reference/beta/resources/chat.md
  api-reference/beta/resources/ediscovery-caseexportoperation.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/user-update.md
  changelog/Microsoft.Teams.Core.json
  concepts/toolkit/get-started/mgt-react.md
Labels: internal

#14396 [CloudPC]Add gallery image entity and related APIs
  api-reference/beta/api/cloudpc-get.md
  api-reference/beta/api/cloudpcauditevent-get.md
  api-reference/beta/api/cloudpcdeviceimage-get.md
  api-reference/beta/api/cloudpcgalleryimage-get.md
  api-reference/beta/api/cloudpconpremisesconnection-get.md
  api-reference/beta/api/cloudpcprovisioningpolicy-get.md
  api-reference/beta/api/cloudpcusersetting-get.md
  api-reference/beta/api/virtualendpoint-list-deviceimages.md
  api-reference/beta/api/virtualendpoint-list-galleryimages.md
  api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md
  api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md
  api-reference/beta/api/virtualendpoint-list-usersettings.md
  api-reference/beta/resources/cloudpcgalleryimage.md
  api-reference/beta/resources/virtualendpoint.md
  api-reference/beta/toc.yml
  changelog/Microsoft.CloudManagedDesktop.json
Labels: do not merge, internal, content review complete

#14684 added two new values to lobbyBypassScope enum
  api-reference/beta/resources/lobbybypasssettings.md
  api-reference/v1.0/resources/lobbybypasssettings.md
  changelog/Microsoft.Skype.Calling.json
Labels: ready to merge, internal, content review complete

#14844 Adds the no-data template to mgt-get
  concepts/toolkit/components/get.md
Labels: ready to merge, internal

#14564 [CloudPC]Add domainJoinConfiguration to provisionpolicy
  api-reference/beta/resources/cloudpcdomainjoinconfiguration.md
  api-reference/beta/resources/cloudpcprovisioningpolicy.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, internal, content review complete

#14866 Merge to publish.
  api-reference/beta/api/cloudpc-get.md
  api-reference/beta/api/cloudpcauditevent-get.md
  api-reference/beta/api/cloudpcdeviceimage-get.md
  api-reference/beta/api/cloudpcgalleryimage-get.md
  api-reference/beta/api/cloudpconpremisesconnection-get.md
  api-reference/beta/api/cloudpcprovisioningpolicy-get.md
  api-reference/beta/api/cloudpcusersetting-get.md
  api-reference/beta/api/virtualendpoint-list-deviceimages.md
  api-reference/beta/api/virtualendpoint-list-galleryimages.md
  api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md
  api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md
  api-reference/beta/api/virtualendpoint-list-usersettings.md
  api-reference/beta/resources/cloudpcdomainjoinconfiguration.md
  api-reference/beta/resources/cloudpcgalleryimage.md
  api-reference/beta/resources/cloudpcprovisioningpolicy.md
  api-reference/beta/resources/lobbybypasssettings.md
  api-reference/beta/resources/virtualendpoint.md
  api-reference/beta/toc.yml
  api-reference/v1.0/resources/lobbybypasssettings.md
  changelog/Microsoft.CloudManagedDesktop.json
  changelog/Microsoft.Skype.Calling.json
  concepts/toolkit/components/get.md
Labels: internal

#14877 Update generated files with build 58448 [skip ci]
  api-reference/beta/api/event-post-attachments.md
  api-reference/beta/api/messagerule-delete.md
  api-reference/beta/api/messagerule-get.md
  api-reference/beta/api/messagerule-update.md
  api-reference/beta/api/outlooktask-complete.md
  api-reference/beta/api/outlooktaskfolder-post-tasks.md
  api-reference/beta/includes/snippets/go/create-file-attachment-from-event-beta-go-snippets.md
  api-reference/beta/includes/snippets/go/create-outlooktask-from-outlooktaskfolder-go-snippets.md
  api-reference/beta/includes/snippets/go/delete-messagerule-go-snippets.md
  api-reference/beta/includes/snippets/go/get-messagerule-go-snippets.md
  api-reference/beta/includes/snippets/go/outlooktask-complete-go-snippets.md
  api-reference/beta/includes/snippets/go/update-messagerule-go-snippets.md
Labels: internal

#14881 Update whats-new-overview.md
  concepts/whats-new-overview.md
Labels: external

#14879 Update chat-markchatunreadforuser.md
  api-reference/beta/api/chat-markchatunreadforuser.md
Labels: external

#14884 Update teamsappupgradedeventmessagedetail.md
  api-reference/beta/resources/teamsappupgradedeventmessagedetail.md
Labels: external

#14883 Update teamsappremovedeventmessagedetail.md
  api-reference/beta/resources/teamsappremovedeventmessagedetail.md
Labels: external

#14882 Update teamsappinstalledeventmessagedetail.md
  api-reference/beta/resources/teamsappinstalledeventmessagedetail.md
Labels: external

#14872 Update teams-api-overview.md
  api-reference/v1.0/resources/teams-api-overview.md
Labels: external

#14862 Update cloud-communication-online-meeting-application-access-policy.md
  concepts/cloud-communication-online-meeting-application-access-policy.md
Labels: external

#14874 Add page limits for user, group, application, and servicePrincipal APIs
  api-reference/beta/api/application-list.md
  api-reference/beta/api/group-list.md
  api-reference/beta/api/serviceprincipal-list.md
  api-reference/beta/api/user-list.md
  api-reference/v1.0/api/application-list.md
  api-reference/v1.0/api/group-list.md
  api-reference/v1.0/api/serviceprincipal-list.md
  api-reference/v1.0/api/user-list.md
Labels: area: azure/AAD, ready to merge, internal

#14878 Revert "peopleInsights (Working With Changes)"
  .github/workflows/changelog-validation.yml
  api-reference/beta/api/insightssettings-update.md
  api-reference/beta/api/iteminsightssettings-get.md
  api-reference/beta/api/iteminsightssettings-update.md
  api-reference/beta/api/organizationsettings-get.md
  api-reference/beta/api/organizationsettings-list-iteminsights.md
  api-reference/beta/api/organizationsettings-list-peopleinsights.md
  api-reference/beta/api/user-list-people.md
  api-reference/beta/resources/insightssettings.md
  api-reference/beta/resources/iteminsights.md
  api-reference/beta/resources/iteminsightssettings.md
  api-reference/beta/resources/organizationsettings.md
  api-reference/beta/resources/userinsightssettings.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/user-list-people.md
  changelog/Microsoft.OfficeGraph.json
  changelog/Microsoft.People.json
  concepts/insights-customize-item-insights-privacy.md
  concepts/insights-customize-people-insights-privacy.md
  concepts/item-insights-overview.md
  concepts/people-example.md
  concepts/social-intel-concept-overview.md
  concepts/toc.yml
  redirects/.openpublishing.redirection.1121.json
Labels: ready to merge, internal

#14886 Merge to publish.
  .github/workflows/changelog-validation.yml
  api-reference/beta/api/application-list.md
  api-reference/beta/api/chat-markchatunreadforuser.md
  api-reference/beta/api/group-list.md
  api-reference/beta/api/insightssettings-update.md
  api-reference/beta/api/iteminsightssettings-get.md
  api-reference/beta/api/iteminsightssettings-update.md
  api-reference/beta/api/organizationsettings-get.md
  api-reference/beta/api/organizationsettings-list-iteminsights.md
  api-reference/beta/api/organizationsettings-list-peopleinsights.md
  api-reference/beta/api/serviceprincipal-list.md
  api-reference/beta/api/user-list-people.md
  api-reference/beta/api/user-list.md
  api-reference/beta/resources/insightssettings.md
  api-reference/beta/resources/iteminsights.md
  api-reference/beta/resources/iteminsightssettings.md
  api-reference/beta/resources/organizationsettings.md
  api-reference/beta/resources/teamsappinstalledeventmessagedetail.md
  api-reference/beta/resources/teamsappremovedeventmessagedetail.md
  api-reference/beta/resources/teamsappupgradedeventmessagedetail.md
  api-reference/beta/resources/userinsightssettings.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/application-list.md
  api-reference/v1.0/api/group-list.md
  api-reference/v1.0/api/serviceprincipal-list.md
  api-reference/v1.0/api/user-list-people.md
  api-reference/v1.0/api/user-list.md
  api-reference/v1.0/resources/teams-api-overview.md
  changelog/Microsoft.OfficeGraph.json
  changelog/Microsoft.People.json
  concepts/cloud-communication-online-meeting-application-access-policy.md
  concepts/insights-customize-item-insights-privacy.md
  concepts/insights-customize-people-insights-privacy.md
  concepts/item-insights-overview.md
  concepts/people-example.md
  concepts/social-intel-concept-overview.md
  concepts/toc.yml
  concepts/whats-new-overview.md
  redirects/.openpublishing.redirection.1121.json
Labels: internal

#14454 [mgt][mgt-people] adding "fallback-details" property
  concepts/toolkit/components/people.md
Labels: external

#14890 Fixes code sample. Closes #14873
  concepts/toolkit/customize-components/events.md
Labels: ready to merge

#14889 Update applicationauthenticationmethodpolicy.md
  api-reference/beta/resources/applicationauthenticationmethodpolicy.md
Labels: external, ready to merge

#14894 Update drive.md
  api-reference/v1.0/resources/drive.md
Labels: external, ready to merge

#13900 Add oAuth2PermissionGrant examples
  api-reference/beta/api/oauth2permissiongrant-delete.md
  api-reference/beta/api/oauth2permissiongrant-get.md
  api-reference/beta/api/oauth2permissiongrant-list.md
  api-reference/beta/api/oauth2permissiongrant-post.md
  api-reference/beta/api/oauth2permissiongrant-update.md
  api-reference/beta/api/serviceprincipal-delete-approleassignedto.md
  api-reference/v1.0/api/oauth2permissiongrant-delete.md
  api-reference/v1.0/api/oauth2permissiongrant-get.md
  api-reference/v1.0/api/oauth2permissiongrant-list.md
  api-reference/v1.0/api/oauth2permissiongrant-post.md
Labels: area: azure/AAD, ready to merge, internal

#13892 Sign in with Apple resource in v1.0
  api-reference/v1.0/api/identitycontainer-list-identityproviders.md
  api-reference/v1.0/api/identitycontainer-post-identityproviders.md
  api-reference/v1.0/api/identityproviderbase-delete.md
  api-reference/v1.0/api/identityproviderbase-get.md
  api-reference/v1.0/api/identityproviderbase-update.md
  api-reference/v1.0/resources/applemanagedidentityprovider.md
  api-reference/v1.0/resources/identityproviderbase.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.DirectoryServices.json
Labels: area: azure/AAD, ready to merge, internal, content review complete

#14885 Windows updates APIs: Add unknownFutureValue to enums
  api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md
  api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md
  api-reference/beta/api/windowsupdates-updatableasset-unenrollassets.md
  api-reference/beta/api/windowsupdates-updatableasset-unenrollassetsbyid.md
  api-reference/beta/resources/enums-windowsupdates.md
  api-reference/beta/resources/windowsupdates-azureaddeviceregistrationerror.md
  api-reference/beta/resources/windowsupdates-deploymentstate.md
  api-reference/beta/resources/windowsupdates-deploymentstatereason.md
  api-reference/beta/resources/windowsupdates-expeditedqualityupdatereference.md
  api-reference/beta/resources/windowsupdates-monitoringrule.md
  api-reference/beta/resources/windowsupdates-qualityupdatecatalogentry.md
  api-reference/beta/resources/windowsupdates-qualityupdatereference.md
  api-reference/beta/resources/windowsupdates-safeguardprofile.md
  api-reference/beta/resources/windowsupdates-updatemanagementenrollment.md
Labels: ready to merge, internal, content review complete, schema live

#14892 Added two learning paths to the hub page
  concepts/index.yml
Labels: ready to merge, ready for content review, internal

#14432 Document timestamp delta tokens.
  api-reference/beta/api/driveitem-delta.md
  api-reference/v1.0/api/driveitem-delta.md
  changelog/Microsoft.FileServices.json
Labels: ready to merge, internal, content review complete

#14907 Update dynamics-companies.md
  api-reference/beta/resources/dynamics-companies.md
Labels: external

#14430 Address DriveItemVersion ordering and current version feedback
  api-reference/beta/api/driveitem-list-versions.md
  api-reference/beta/api/driveitemversion-get.md
  api-reference/v1.0/api/driveitem-list-versions.md
  api-reference/v1.0/api/driveitemversion-get.md
Labels: ready to merge, internal, content review complete

#14858 Document workarounds for adding Azure AD Graph permissions
  concepts/migrate-azure-ad-graph-configure-permissions.md
  concepts/migrate-azure-ad-graph-faq.md
  concepts/toc.yml
Labels: area: azure/AAD, ready to merge, internal, content review in progress, review feedback addressed

#14921 Update securityaction.md
  api-reference/beta/resources/securityaction.md
Labels: external

#13758 MS Graph connectors docs updates: Updating links + removing preview tags
  api-reference/beta/api/externalconnectors-externalgroup-post-members.md
  api-reference/beta/api/externalconnectors-externalitem-get.md
  api-reference/beta/api/externalconnectors-externalitem-update.md
  concepts/connecting-external-content-connectors-overview.md
  concepts/overview.md
Labels: ready to merge, content review complete

#14910 Add missing reference TOC entries for migration workarounds
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
Labels: ready to merge, internal

#14918 Fix#14898
  api-reference/beta/resources/application.md
  api-reference/beta/resources/device.md
  api-reference/beta/resources/group.md
  api-reference/beta/resources/orgcontact.md
  api-reference/beta/resources/serviceprincipal.md
  api-reference/beta/resources/user.md
  api-reference/v1.0/resources/application.md
  api-reference/v1.0/resources/device.md
  api-reference/v1.0/resources/group.md
  api-reference/v1.0/resources/orgcontact.md
  api-reference/v1.0/resources/serviceprincipal.md
  api-reference/v1.0/resources/user.md
Labels: area: azure/AAD, ready to merge, internal

#14917 Update profilephoto-get.md removing note
  api-reference/v1.0/api/profilephoto-get.md
Labels: ready to merge, internal

#14828 Add information for Go preview SDK
  concepts/sdks/choose-authentication-providers.md
  concepts/sdks/create-client.md
  concepts/sdks/customize-client.md
  concepts/sdks/sdk-installation.md
  concepts/sdks/sdks-overview.md
  concepts/sdks/use-beta.md
  includes/go-sdk-preview.md
Labels: ready to merge, internal, content review complete

#14947 Update channel-post-tabs.md
  api-reference/beta/api/channel-post-tabs.md
Labels: external

#14946 Update channel-post-tabs.md
  api-reference/v1.0/api/channel-post-tabs.md
Labels: external

#14940 user resource doesn't support $skip
  api-reference/beta/api/user-list.md
  api-reference/v1.0/api/user-list.md
Labels: area: azure/AAD, ready to merge, internal

#14765 Registration Campaign GA Docs
  api-reference/v1.0/api/authenticationmethodspolicy-get.md
  api-reference/v1.0/api/authenticationmethodspolicy-update.md
  api-reference/v1.0/resources/authenticationmethodspolicies-overview.md
  api-reference/v1.0/resources/authenticationmethodspolicy.md
  api-reference/v1.0/resources/authenticationmethodsregistrationcampaign.md
  api-reference/v1.0/resources/authenticationmethodsregistrationcampaignincludetarget.md
  api-reference/v1.0/resources/enums.md
  api-reference/v1.0/resources/excludetarget.md
  api-reference/v1.0/resources/registrationenforcement.md
  changelog/Microsoft.DirectoryServices.json
Labels: ready to merge, internal, schema live, review feedback addressed

#14941 Retrieve identities object on $select
  api-reference/beta/api/user-get.md
  api-reference/v1.0/api/user-get.md
Labels: area: azure/AAD, ready to merge, internal

#14944 Specify maxLifeTime is in ISO 8601 Durations format
  api-reference/beta/resources/keycredentialconfiguration.md
  api-reference/beta/resources/passwordcredentialconfiguration.md
Labels: area: azure/AAD, ready to merge, internal

#14958 Update known-issues.md
  concepts/known-issues.md
Labels: external, ready to merge

#14619 Add warning section about use of multiple Graph API for WUfB settings
  api-reference/beta/resources/intune-graph-overview.md
  api-reference/v1.0/resources/intune-graph-overview.md
Labels: ready to merge, internal

#14672 Convert Exchange and Microsoft Teams usage reports APIs to weak type
  api-reference/beta/api/reportroot-getemailactivitycounts.md
  api-reference/beta/api/reportroot-getemailactivityusercounts.md
  api-reference/beta/api/reportroot-getemailactivityuserdetail.md
  api-reference/beta/api/reportroot-getemailappusageappsusercounts.md
  api-reference/beta/api/reportroot-getemailappusageusercounts.md
  api-reference/beta/api/reportroot-getemailappusageuserdetail.md
  api-reference/beta/api/reportroot-getemailappusageversionsusercounts.md
  api-reference/beta/api/reportroot-getmailboxusagedetail.md
  api-reference/beta/api/reportroot-getmailboxusagemailboxcounts.md
  api-reference/beta/api/reportroot-getmailboxusagequotastatusmailboxcounts.md
  api-reference/beta/api/reportroot-getmailboxusagestorage.md
  api-reference/beta/api/reportroot-getteamsdeviceusagedistributiontotalusercounts.md
  api-reference/beta/api/reportroot-getteamsdeviceusagedistributionusercounts.md
  api-reference/beta/api/reportroot-getteamsdeviceusagetotalusercounts.md
  api-reference/beta/api/reportroot-getteamsdeviceusageusercounts.md
  api-reference/beta/api/reportroot-getteamsdeviceusageuserdetail.md
  api-reference/beta/api/reportroot-getteamsuseractivitycounts.md
  api-reference/beta/api/reportroot-getteamsuseractivitydistributiontotalusercounts.md
  api-reference/beta/api/reportroot-getteamsuseractivitydistributionusercounts.md
  api-reference/beta/api/reportroot-getteamsuseractivitytotalcounts.md
  api-reference/beta/api/reportroot-getteamsuseractivitytotalusercounts.md
  api-reference/beta/api/reportroot-getteamsuseractivityusercounts.md
  api-reference/beta/api/reportroot-getteamsuseractivityuserdetail.md
  api-reference/beta/resources/email-activity-reports.md
  api-reference/beta/resources/email-app-usage-reports.md
  api-reference/beta/resources/emailactivitysummary.md
  api-reference/beta/resources/emailactivityuserdetail.md
  api-reference/beta/resources/emailappusageappsusercounts.md
  api-reference/beta/resources/emailappusageusercounts.md
  api-reference/beta/resources/emailappusageuserdetail.md
  api-reference/beta/resources/emailappusageversionsusercounts.md
  api-reference/beta/resources/mailbox-usage-reports.md
  api-reference/beta/resources/mailboxusagedetail.md
  api-reference/beta/resources/mailboxusagemailboxcounts.md
  api-reference/beta/resources/mailboxusagequotastatusmailboxcounts.md
  api-reference/beta/resources/mailboxusagestorage.md
  api-reference/beta/resources/microsoft-teams-device-usage-reports.md
  api-reference/beta/resources/microsoft-teams-user-activity-reports.md
  api-reference/beta/resources/teamsdeviceusagedistributionusercounts.md
  api-reference/beta/resources/teamsdeviceusageusercounts.md
  api-reference/beta/resources/teamsdeviceusageuserdetail.md
  api-reference/beta/resources/teamsuseractivitycounts.md
  api-reference/beta/resources/teamsuseractivitydistributionusercounts.md
  api-reference/beta/resources/teamsuseractivityusercounts.md
  api-reference/beta/resources/teamsuseractivityuserdetail.md
  changelog/Microsoft.O365Reporting.json
Labels: ready to merge, internal, content review complete, schema live

#14964 Merge to publish.
  api-reference/beta/api/reportroot-getemailactivitycounts.md
  api-reference/beta/api/reportroot-getemailactivityusercounts.md
  api-reference/beta/api/reportroot-getemailactivityuserdetail.md
  api-reference/beta/api/reportroot-getemailappusageappsusercounts.md
  api-reference/beta/api/reportroot-getemailappusageusercounts.md
  api-reference/beta/api/reportroot-getemailappusageuserdetail.md
  api-reference/beta/api/reportroot-getemailappusageversionsusercounts.md
  api-reference/beta/api/reportroot-getmailboxusagedetail.md
  api-reference/beta/api/reportroot-getmailboxusagemailboxcounts.md
  api-reference/beta/api/reportroot-getmailboxusagequotastatusmailboxcounts.md
  api-reference/beta/api/reportroot-getmailboxusagestorage.md
  api-reference/beta/api/reportroot-getteamsdeviceusagedistributiontotalusercounts.md
  api-reference/beta/api/reportroot-getteamsdeviceusagedistributionusercounts.md
  api-reference/beta/api/reportroot-getteamsdeviceusagetotalusercounts.md
  api-reference/beta/api/reportroot-getteamsdeviceusageusercounts.md
  api-reference/beta/api/reportroot-getteamsdeviceusageuserdetail.md
  api-reference/beta/api/reportroot-getteamsuseractivitycounts.md
  api-reference/beta/api/reportroot-getteamsuseractivitydistributiontotalusercounts.md
  api-reference/beta/api/reportroot-getteamsuseractivitydistributionusercounts.md
  api-reference/beta/api/reportroot-getteamsuseractivitytotalcounts.md
  api-reference/beta/api/reportroot-getteamsuseractivitytotalusercounts.md
  api-reference/beta/api/reportroot-getteamsuseractivityusercounts.md
  api-reference/beta/api/reportroot-getteamsuseractivityuserdetail.md
  api-reference/beta/resources/email-activity-reports.md
  api-reference/beta/resources/email-app-usage-reports.md
  api-reference/beta/resources/emailactivitysummary.md
  api-reference/beta/resources/emailactivityuserdetail.md
  api-reference/beta/resources/emailappusageappsusercounts.md
  api-reference/beta/resources/emailappusageusercounts.md
  api-reference/beta/resources/emailappusageuserdetail.md
  api-reference/beta/resources/emailappusageversionsusercounts.md
  api-reference/beta/resources/intune-graph-overview.md
  api-reference/beta/resources/keycredentialconfiguration.md
  api-reference/beta/resources/mailbox-usage-reports.md
  api-reference/beta/resources/mailboxusagedetail.md
  api-reference/beta/resources/mailboxusagemailboxcounts.md
  api-reference/beta/resources/mailboxusagequotastatusmailboxcounts.md
  api-reference/beta/resources/mailboxusagestorage.md
  api-reference/beta/resources/microsoft-teams-device-usage-reports.md
  api-reference/beta/resources/microsoft-teams-user-activity-reports.md
  api-reference/beta/resources/passwordcredentialconfiguration.md
  api-reference/beta/resources/teamsdeviceusagedistributionusercounts.md
  api-reference/beta/resources/teamsdeviceusageusercounts.md
  api-reference/beta/resources/teamsdeviceusageuserdetail.md
  api-reference/beta/resources/teamsuseractivitycounts.md
  api-reference/beta/resources/teamsuseractivitydistributionusercounts.md
  api-reference/beta/resources/teamsuseractivityusercounts.md
  api-reference/beta/resources/teamsuseractivityuserdetail.md
  api-reference/v1.0/resources/intune-graph-overview.md
  changelog/Microsoft.O365Reporting.json
  concepts/known-issues.md
Labels: internal

#14024 [Azure AD] Custom security attributes (Preview)
  api-reference/beta/api/allowedvalue-get.md
  api-reference/beta/api/allowedvalue-update.md
  api-reference/beta/api/attributeset-get.md
  api-reference/beta/api/attributeset-update.md
  api-reference/beta/api/customsecurityattributedefinition-get.md
  api-reference/beta/api/customsecurityattributedefinition-list-allowedvalues.md
  api-reference/beta/api/customsecurityattributedefinition-post-allowedvalues.md
  api-reference/beta/api/customsecurityattributedefinition-update.md
  api-reference/beta/api/directory-list-attributesets.md
  api-reference/beta/api/directory-list-customsecurityattributedefinitions.md
  api-reference/beta/api/directory-post-attributesets.md
  api-reference/beta/api/directory-post-customsecurityattributedefinitions.md
  api-reference/beta/api/serviceprincipal-get.md
  api-reference/beta/api/serviceprincipal-update.md
  api-reference/beta/api/user-get.md
  api-reference/beta/api/user-update.md
  api-reference/beta/resources/allowedvalue.md
  api-reference/beta/resources/attributeset.md
  api-reference/beta/resources/custom-security-attributes-overview.md
  api-reference/beta/resources/customsecurityattributedefinition.md
  api-reference/beta/resources/customsecurityattributevalue.md
  api-reference/beta/resources/directory.md
  api-reference/beta/resources/serviceprincipal.md
  api-reference/beta/resources/user.md
  api-reference/beta/toc.yml
  changelog/Microsoft.DirectoryServices.json
  concepts/custom-security-attributes-examples.md
  concepts/permissions-reference.md
  concepts/toc.yml
Labels: area: azure/AAD, ready to merge, internal, content review complete

#14973 Update educationclass.md
  api-reference/beta/resources/educationclass.md
Labels: external

#14969 Simplify titles in Azure AD Graph migration topics
  concepts/migrate-azure-ad-graph-audit-api-use.md
  concepts/migrate-azure-ad-graph-feature-differences.md
  concepts/migrate-azure-ad-graph-method-differences.md
  concepts/migrate-azure-ad-graph-overview.md
  concepts/migrate-azure-ad-graph-property-differences.md
  concepts/migrate-azure-ad-graph-request-differences.md
  concepts/migrate-azure-ad-graph-resource-differences.md
Labels: area: azure/AAD, ready to merge, internal

#14970 Fix broken links to new connector gallery URL
  concepts/connecting-external-content-connectors-overview.md
Labels: ready to merge, internal, content review complete

#14701 removing managed tenant risky user docs
  api-reference/beta/api/managedtenants-managedtenant-list-riskyusers.md
  api-reference/beta/api/managedtenants-riskyuser-get.md
  api-reference/beta/resources/managedtenants-managedtenant.md
  api-reference/beta/resources/managedtenants-riskyuser.md
  api-reference/beta/toc.yml
  changelog/Microsoft.MultiTenantPlatform.json
Labels: ready to merge, internal, content review complete, area: multi-tenant management

#14971 update possible staff roles
  api-reference/beta/resources/bookingstaffmember.md
Labels: external

#14808 [Cloud PC] Update description for Cloud PCs service plans
  api-reference/beta/api/virtualendpoint-list-serviceplans.md
  api-reference/beta/resources/cloudpcserviceplan.md
Labels: do not merge, internal, content review complete, review feedback addressed

#14807 [Cloud PC] Add Windows 365 service-level conceptual overview
  api-reference/beta/resources/cloudpc-api-overview.md
  concepts/cloudpc-concept-overview.md
  concepts/overview-major-services.md
  concepts/toc.yml
Labels: ready to merge, internal, content review complete

#14922 Add note for app installation about RSC apps
  api-reference/beta/api/chat-post-installedapps.md
  api-reference/beta/api/chat-teamsappinstallation-upgrade.md
  api-reference/beta/api/team-post-installedapps.md
  api-reference/beta/api/team-teamsappinstallation-upgrade.md
  api-reference/v1.0/api/chat-post-installedapps.md
  api-reference/v1.0/api/chat-teamsappinstallation-upgrade.md
  api-reference/v1.0/api/team-post-installedapps.md
  api-reference/v1.0/api/team-teamsappinstallation-upgrade.md
  concepts/known-issues.md
Labels: ready to merge, ready for content review

#14980 GitHub issues Nov 2021
  api-reference/beta/api/driveitem-list-thumbnails.md
  api-reference/beta/api/driveitem-unfollow.md
  api-reference/beta/api/listitem-update.md
  api-reference/beta/api/profilephoto-get.md
  api-reference/beta/api/reportroot-getteamsdeviceusageuserdetail.md
  api-reference/beta/resources/drive.md
  api-reference/beta/resources/responsestatus.md
  api-reference/beta/resources/security-api-overview.md
  api-reference/v1.0/api/event-update.md
  api-reference/v1.0/api/listitem-update.md
  api-reference/v1.0/api/profilephoto-get.md
  api-reference/v1.0/api/reportroot-getteamsdeviceusageuserdetail.md
  api-reference/v1.0/resources/drive.md
  api-reference/v1.0/resources/responsestatus.md
  api-reference/v1.0/resources/security-api-overview.md
  concepts/cloud-communications-phone-number.md
  concepts/known-issues.md
Labels: ready to merge, ready for content review, internal

#14981 Resolve #14899 - can't manage mail-enabled security groups via Microsoft Graph groups API
  api-reference/beta/api/group-post-members.md
  api-reference/beta/api/group-post-owners.md
  api-reference/beta/resources/group.md
  api-reference/v1.0/api/group-post-members.md
  api-reference/v1.0/api/group-post-owners.md
  api-reference/v1.0/resources/group.md
Labels: ready to merge, internal

#14982 Update educationroot-post-schools.md
  api-reference/beta/api/educationroot-post-schools.md
Labels: ready to merge, internal

#14985 Document $filter support by service principal appId
  api-reference/beta/resources/serviceprincipal.md
  api-reference/v1.0/resources/serviceprincipal.md
  includes/filter-directory-objects.md
Labels: area: azure/AAD, ready to merge, internal

#14990 Graph Toolkit 2.3.1 patch update docs
  concepts/toolkit/components/people.md
Labels: ready to merge, internal

#14954 Clean up check/getmemberGroups API
  api-reference/beta/api/directoryobject-checkmembergroups.md
  api-reference/beta/api/directoryobject-getmembergroups.md
  api-reference/beta/api/group-checkmembergroups.md
  api-reference/beta/api/group-getmembergroups.md
  api-reference/beta/api/orgcontact-checkmembergroups.md
  api-reference/beta/api/orgcontact-getmembergroups.md
  api-reference/beta/api/serviceprincipal-checkmembergroups.md
  api-reference/beta/api/serviceprincipal-getmembergroups.md
  api-reference/beta/api/user-checkmembergroups.md
  api-reference/beta/api/user-getmembergroups.md
  api-reference/beta/resources/group.md
  api-reference/beta/resources/groups-overview.md
  api-reference/beta/resources/orgcontact.md
  api-reference/beta/resources/serviceprincipal.md
  api-reference/beta/resources/user.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/directoryobject-checkmembergroups.md
  api-reference/v1.0/api/directoryobject-getmembergroups.md
  api-reference/v1.0/api/group-checkmembergroups.md
  api-reference/v1.0/api/group-getmembergroups.md
  api-reference/v1.0/api/orgcontact-checkmembergroups.md
  api-reference/v1.0/api/orgcontact-getmembergroups.md
  api-reference/v1.0/api/serviceprincipal-checkmembergroups.md
  api-reference/v1.0/api/serviceprincipal-getmembergroups.md
  api-reference/v1.0/api/user-checkmembergroups.md
  api-reference/v1.0/api/user-getmembergroups.md
  api-reference/v1.0/resources/group.md
  api-reference/v1.0/resources/groups-overview.md
  api-reference/v1.0/resources/orgcontact.md
  api-reference/v1.0/resources/serviceprincipal.md
  api-reference/v1.0/resources/user.md
  api-reference/v1.0/toc.yml
  redirects/.openpublishing.redirection.1121.json
Labels: area: azure/AAD, ready to merge, internal

#14986 Fix casing for not operator
  api-reference/beta/api/group-list.md
  api-reference/beta/resources/application.md
  api-reference/beta/resources/device.md
  api-reference/beta/resources/group.md
  api-reference/beta/resources/orgcontact.md
  api-reference/beta/resources/serviceprincipal.md
  api-reference/beta/resources/user.md
  api-reference/v1.0/api/group-list.md
  api-reference/v1.0/resources/application.md
  api-reference/v1.0/resources/device.md
  api-reference/v1.0/resources/group.md
  api-reference/v1.0/resources/orgcontact.md
  api-reference/v1.0/resources/serviceprincipal.md
  api-reference/v1.0/resources/user.md
  concepts/aad-advanced-queries.md
  concepts/query-parameters.md
Labels: area: azure/AAD, ready to merge, internal

#14012 APIs to hide/unhide chat for a user
  api-reference/beta/api/chat-hideforuser.md
  api-reference/beta/api/chat-list.md
  api-reference/beta/api/chat-unhideforuser.md
  api-reference/beta/api/chatmessage-post.md
  api-reference/beta/resources/chat.md
  api-reference/beta/resources/chatviewpoint.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/chat-post-messages.md
  api-reference/v1.0/api/chatmessage-post.md
  changelog/Microsoft.Teams.Core.json
Labels: ready to merge, ready for content review, internal, review feedback addressed

#15000 Update educationclass-list-schools.md
  api-reference/v1.0/api/educationclass-list-schools.md
Labels: external

#14999 Update educationclass-list-schools.md
  api-reference/beta/api/educationclass-list-schools.md
Labels: external

#14983 Adding examples of the licensing models for relevant APIs
  api-reference/beta/api/channel-getallmessages.md
  api-reference/beta/api/chatmessage-update.md
  api-reference/beta/api/chats-getallmessages.md
  api-reference/includes/teams-subscription-notes.md
  api-reference/v1.0/api/channel-getallmessages.md
  api-reference/v1.0/api/chatmessage-update.md
  api-reference/v1.0/api/chats-getallmessages.md
Labels: ready to merge, internal, content review complete

#15002 Merge to publish.
  api-reference/beta/api/channel-getallmessages.md
  api-reference/beta/api/chat-hideforuser.md
  api-reference/beta/api/chat-list.md
  api-reference/beta/api/chat-unhideforuser.md
  api-reference/beta/api/chatmessage-post.md
  api-reference/beta/api/chatmessage-update.md
  api-reference/beta/api/chats-getallmessages.md
  api-reference/beta/api/educationclass-list-schools.md
  api-reference/beta/resources/chat.md
  api-reference/beta/resources/chatviewpoint.md
  api-reference/beta/toc.yml
  api-reference/includes/teams-subscription-notes.md
  api-reference/v1.0/api/channel-getallmessages.md
  api-reference/v1.0/api/chat-post-messages.md
  api-reference/v1.0/api/chatmessage-post.md
  api-reference/v1.0/api/chatmessage-update.md
  api-reference/v1.0/api/chats-getallmessages.md
  api-reference/v1.0/api/educationclass-list-schools.md
  changelog/Microsoft.Teams.Core.json
Labels: internal

#15004 Refresh what's new.
  changelog/Microsoft.DirectoryServices.json
  changelog/Microsoft.MultiTenantPlatform.json
  changelog/Microsoft.Teams.Core.json
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: do not merge, internal

#14998 Added Go SDK examples
  concepts/sdks/create-requests.md
  concepts/sdks/customize-client.md
  concepts/sdks/includes/snippets/go/create-requests-create.md
  concepts/sdks/includes/snippets/go/create-requests-delete.md
  concepts/sdks/includes/snippets/go/create-requests-expand.md
  concepts/sdks/includes/snippets/go/create-requests-headers.md
  concepts/sdks/includes/snippets/go/create-requests-index.md
  concepts/sdks/includes/snippets/go/create-requests-list.md
  concepts/sdks/includes/snippets/go/create-requests-queryparams.md
  concepts/sdks/includes/snippets/go/create-requests-read.md
  concepts/sdks/includes/snippets/go/create-requests-select.md
  concepts/sdks/includes/snippets/go/create-requests-update.md
Labels: ready to merge, internal

#15069 Update subscription-update.md
  api-reference/beta/api/subscription-update.md
Labels: external

#15068 Update subscription-update.md
  api-reference/v1.0/api/subscription-update.md
Labels: external

#15045 Update educationclass-post-category.md
  api-reference/v1.0/api/educationclass-post-category.md
Labels: external

#15044 Update educationclass-post-category.md
  api-reference/beta/api/educationclass-post-category.md
Labels: external

#15052 Update educationclass-delete-members.md
  api-reference/v1.0/api/educationclass-delete-members.md
Labels: external

#15051 Update educationclass-delete-members.md
  api-reference/beta/api/educationclass-delete-members.md
Labels: external

#15038 Update educationclass-delete.md
  api-reference/beta/api/educationclass-delete.md
Labels: external

#15037 Update educationclass-delete.md
  api-reference/v1.0/api/educationclass-delete.md
Labels: external

#15022 Update educationclass-get.md
  api-reference/v1.0/api/educationclass-get.md
Labels: external

#15021 Update educationclass-get.md
  api-reference/beta/api/educationclass-get.md
Labels: external

#15007 Rebranding “Security Center” to the new name
  api-reference/v1.0/resources/security-api-overview.md
Labels: external

#14434 Add conflict behavior query parameter notes
  api-reference/v1.0/api/driveitem-copy.md
Labels: ready to merge, internal, content review complete

#14961 Updating Identity Reporting limits
  concepts/throttling.md
Labels: area: azure/AAD, ready to merge, internal, content review complete

#14996 Update item-insights-overview.md
  concepts/item-insights-overview.md
Labels: ready to merge, content review complete

#15016 Issue 11800 wrong amount
  concepts/search-query-parameter.md
Labels: ready to merge, ready for content review, internal

#15046 New AppCatalog.Read*.All application permissions
  api-reference/beta/api/appcatalogs-list-teamsapps.md
  api-reference/beta/api/teamsappicon-get.md
  api-reference/beta/api/teamworkbot-get.md
  api-reference/beta/api/teamworkhostedcontent-get.md
  changelog/Microsoft.Teams.GraphSvc.json
  concepts/permissions-reference.md
Labels: ready to merge, internal, content review complete

#14950 AttackSimulation (beta) - Removing unused members, unused enums
  api-reference/beta/api/attacksimulationroot-list-simulations.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/simulation.md
  changelog/Microsoft.Security.AttackSimulation.json
Labels: ready to merge, internal, content review complete

#14641 Adding useragent to Azure AD audit events
  api-reference/beta/api/directoryaudit-get.md
  api-reference/beta/api/directoryaudit-list.md
  api-reference/beta/resources/directoryaudit.md
  changelog/Microsoft.AAD.Reporting.json
Labels: area: azure/AAD, ready to merge, content review complete, schema live

#15031 [MGT] Added link to teams samples
  concepts/toolkit/get-started/build-a-microsoft-teams-tab.md
Labels: ready to merge, internal
