Repository microsoftgraph/microsoft-graph-docs, pull requests merged in 2021-04, with the labels that each got.

#12170 Update site-post-permissions.md
  api-reference/beta/api/site-post-permissions.md
Labels: external

#12176 Update externalconnection-put-items.md
  api-reference/beta/api/externalconnection-put-items.md
Labels: external

#12175 Update create-externalitem-from-connections-csharp-snippets.md
  api-reference/beta/includes/snippets/csharp/create-externalitem-from-connections-csharp-snippets.md
Labels: external

#12148 Added countyrLookupMethod property to countryNamedLocation
  api-reference/beta/resources/countrynamedlocation.md
  api-reference/beta/resources/enums.md
  changelog/Microsoft.DirectoryServices.json
Labels: external, ready to merge

#12167 Move Governance to Identity and access node - v1.0 docs
  api-reference/v1.0/toc.yml
Labels: internal, ready to merge

#12169 Update ms.prod
  api-reference/beta/resources/locatedriskevent.md
Labels: internal, ready to merge

#12166 Update excel-use-functions.md
  concepts/excel-use-functions.md
Labels: internal, ready to merge

#12185 - fixes bad variable reference for batch post
  concepts/sdks/batch-requests.md
Labels: area: batch requests, internal, ready to merge

#12182 Update profile.md
  api-reference/beta/resources/profile.md
Labels: external

#12181 Update site-get-permission.md
  api-reference/beta/api/site-get-permission.md
Labels: external

#12180 Add missing changelog files to validaton
  .github/workflows/changelog-validation.yml
Labels: internal, ready to merge

#12072 intro draft for certitifcate authentication
  api-reference/beta/api/identityapiconnector-create.md
  api-reference/beta/api/identityapiconnector-list.md
  api-reference/beta/api/identityapiconnector-update.md
  api-reference/beta/api/identityapiconnector-uploadclientcertificate.md
  api-reference/beta/api/identitycontainer-post-b2cuserflows.md
  api-reference/beta/api/identitycontainer-post-b2xuserflows.md
  api-reference/beta/resources/apiauthenticationconfigurationbase.md
  api-reference/beta/resources/clientcertificateauthentication.md
  api-reference/beta/resources/identityapiconnector.md
  api-reference/beta/resources/pkcs12CertificateInformation.md
  api-reference/beta/resources/pkcs12certificate.md
  api-reference/beta/toc.yml
  changelog/Microsoft.DirectoryServices.json
Labels: content review complete, internal, ready to merge

#12189 Fixed a couple of issues.
  api-reference/beta/resources/calendar.md
  api-reference/v1.0/resources/calendar.md
  concepts/permissions-reference.md
Labels: internal

#12192 Update site-update-permission.md
  api-reference/beta/api/site-update-permission.md
Labels: external

#12193 Update site-list-subsites.md
  api-reference/beta/api/site-list-subsites.md
Labels: external

#12196 Updated the author value for OrganizationalBranding area.
  api-reference/beta/api/organizationalbrandingproperties-create.md
  api-reference/beta/api/organizationalbrandingproperties-delete.md
  api-reference/beta/api/organizationalbrandingproperties-get.md
  api-reference/beta/api/organizationalbrandingproperties-update.md
  api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md
  api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md
  api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md
  api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md
  api-reference/v1.0/api/organizationalbrandingproperties-create.md
  api-reference/v1.0/api/organizationalbrandingproperties-delete.md
  api-reference/v1.0/api/organizationalbrandingproperties-get.md
  api-reference/v1.0/api/organizationalbrandingproperties-update.md
  api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md
  api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md
  api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md
  api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md
Labels: internal, ready to merge

#12165 [mgt] adding personPresence property to mgt-person default template
  concepts/toolkit/components/person.md
Labels: external

#12205 Enabling Chat messages webhooks in v1
  concepts/teams-changenotifications-chatmessage.md
Labels: content review complete, internal, ready to merge

#12208 Update sample PATCH request with correct value
  api-reference/v1.0/api/emailauthenticationmethodconfiguration-update.md
Labels: external

#12137 Publish chats/id/permissionGrants
  api-reference/beta/api/chat-list-permissiongrants.md
  api-reference/beta/api/group-list-permissiongrants.md
  api-reference/beta/resources/chat.md
  api-reference/beta/resources/resourcespecificpermissiongrant.md
  changelog/Microsoft.Teams.Core.json
Labels: content review complete, internal, ready to merge, schema live

#12212 Merge to publish.
  api-reference/beta/api/chat-list-permissiongrants.md
  api-reference/beta/api/group-list-permissiongrants.md
  api-reference/beta/resources/chat.md
  api-reference/beta/resources/resourcespecificpermissiongrant.md
  api-reference/v1.0/api/emailauthenticationmethodconfiguration-update.md
  changelog/Microsoft.Teams.Core.json
  concepts/change-notifications-delivery.md
  concepts/teams-changenotifications-chatmessage.md
Labels: internal

#12215 Update list-list-columns.md
  api-reference/beta/api/list-list-columns.md
Labels: external

#12214 Update site-delete-permission.md
  api-reference/beta/api/site-delete-permission.md
Labels: external

#12226 Clarify that permission claim values may not start with '.'
  api-reference/beta/resources/approle.md
  api-reference/beta/resources/permissionscope.md
  api-reference/v1.0/resources/approle.md
  api-reference/v1.0/resources/permissionscope.md
Labels: area: app model, area: azure/AAD, ready to merge

#12024 Updates instructions to use MGT with SPFx
  concepts/toc.yml
  concepts/toolkit/get-started/build-a-sharepoint-web-part.md
  concepts/toolkit/get-started/mgt-spfx.md
  concepts/toolkit/get-started/overview.md
  concepts/toolkit/providers/sharepoint.md
Labels: do not merge, internal

#11976 Adding new property to teams app definition
  api-reference/beta/api/appcatalogs-list-teamsapps.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/teamsappdefinition.md
  changelog/Microsoft.Teams.GraphSvc.json
Labels: content review complete, internal, ready to merge, schema live

#12235 Update site-post-columns.md
  api-reference/beta/api/site-post-columns.md
Labels: external

#12240 Clearer Wording
  api-reference/v1.0/resources/device.md
Labels: external

#12245 Postman updates apr
  concepts/use-postman.md
Labels: internal, ready to merge

#12223 Updates from the last month.
  api-reference/beta/resources/cloudpcdeviceimage.md
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
  concepts/toc.yml
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: do not merge, internal

#12250 Refresh what's new topic and a few other topic updates.
  api-reference/beta/resources/cloudpcdeviceimage.md
  api-reference/beta/toc.yml
  api-reference/v1.0/resources/device.md
  api-reference/v1.0/toc.yml
  concepts/toc.yml
  concepts/use-postman.md
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: internal

#12252 [MGT] Fixed code example in Provider docs
  concepts/toolkit/providers/providers.md
Labels: internal, ready to merge

#12249 Update site-list-columns.md
  api-reference/beta/api/site-list-columns.md
Labels: external

#12251 Update insights-customize-item-insights-privacy.md
  concepts/insights-customize-item-insights-privacy.md
Labels: external

#12085 Add new fields to pstnCallLogRow
  api-reference/beta/api/callrecords-callrecord-getpstncalls.md
  api-reference/beta/resources/callrecords-pstncalllogrow.md
  api-reference/beta/resources/enums-callrecords.md
  api-reference/beta/resources/enums.md
  changelog/Microsoft.IC3.DataPlatform.json
Labels: area: cloud communications, ready to merge

#11461 [CloudPC]Add CloudPC app-only permissions
  concepts/permissions-reference.md
Labels: internal, ready to merge

#12276 Kanaka main
  concepts/teams-protected-apis.md
Labels: internal, ready to merge

#12268 Update channelidentity.md
  api-reference/beta/resources/channelidentity.md
Labels: external

#12267 Update channelidentity.md
  api-reference/v1.0/resources/channelidentity.md
Labels: external

#12266 Update chatmessage.md
  api-reference/beta/resources/chatmessage.md
Labels: external

#12265 Update chatmessage.md
  api-reference/v1.0/resources/chatmessage.md
Labels: external

#12225 Minor fixes to consent requests
  api-reference/beta/api/appconsentrequest-filterByCurrentUser.md
  api-reference/beta/api/userconsentrequest-filterByCurrentUser.md
  api-reference/beta/api/userconsentrequest-list.md
  api-reference/beta/resources/appconsentrequest.md
  api-reference/beta/resources/consentrequests-root.md
  api-reference/beta/resources/userconsentrequest.md
  api-reference/v1.0/api/appconsentrequest-filterbycurrentuser.md
  api-reference/v1.0/api/userconsentrequest-filterbycurrentuser.md
  api-reference/v1.0/api/userconsentrequest-list.md
  api-reference/v1.0/resources/appconsentrequest.md
  api-reference/v1.0/resources/consentrequests-root.md
  api-reference/v1.0/resources/userconsentrequest.md
  changelog/Microsoft.DirectoryServices.json
Labels: internal, ready to merge

#12277 Merge to publish.
  README.md
  api-reference/beta/api/appconsentrequest-filterByCurrentUser.md
  api-reference/beta/api/userconsentrequest-filterByCurrentUser.md
  api-reference/beta/api/userconsentrequest-list.md
  api-reference/beta/resources/appconsentrequest.md
  api-reference/beta/resources/channelidentity.md
  api-reference/beta/resources/chatmessage.md
  api-reference/beta/resources/consentrequests-root.md
  api-reference/beta/resources/userconsentrequest.md
  api-reference/v1.0/api/appconsentrequest-filterbycurrentuser.md
  api-reference/v1.0/api/userconsentrequest-filterbycurrentuser.md
  api-reference/v1.0/api/userconsentrequest-list.md
  api-reference/v1.0/resources/appconsentrequest.md
  api-reference/v1.0/resources/channelidentity.md
  api-reference/v1.0/resources/chatmessage.md
  api-reference/v1.0/resources/consentrequests-root.md
  api-reference/v1.0/resources/userconsentrequest.md
  changelog/Microsoft.DirectoryServices.json
  concepts/permissions-reference.md
  concepts/teams-protected-apis.md
Labels: internal

#12282 Update resourcespecificpermissiongrant.md
  api-reference/beta/resources/resourcespecificpermissiongrant.md
Labels: external

#12281 Update channel.md
  api-reference/beta/resources/channel.md
Labels: external

#12280 Update channel.md
  api-reference/v1.0/resources/channel.md
Labels: external

#12279 Update whats-new-overview.md
  concepts/whats-new-overview.md
Labels: external

#12273 Fix bugs in CloudPrinting beta APIs documentation
  api-reference/beta/api/print-list-connectors.md
  api-reference/beta/api/print-list-printers.md
  api-reference/beta/api/print-list-shares.md
  api-reference/beta/api/print-post-shares.md
  api-reference/beta/api/print-update-taskdefinition.md
  api-reference/beta/api/printconnector-get.md
  api-reference/beta/api/printconnector-update.md
  api-reference/beta/api/printdocument-get-file.md
  api-reference/beta/api/printer-get.md
  api-reference/beta/api/printer-list-connectors.md
  api-reference/beta/api/printer-list-jobs.md
  api-reference/beta/api/printer-update.md
  api-reference/beta/api/printershare-get.md
  api-reference/beta/api/printershare-list-allowedgroups.md
  api-reference/beta/api/printershare-list-allowedusers.md
  api-reference/beta/api/printershare-list-jobs.md
  api-reference/beta/api/printershare-post-allowedgroups.md
  api-reference/beta/api/printershare-post-allowedusers.md
  api-reference/beta/api/printershare-update.md
  api-reference/beta/api/printjob-get.md
  api-reference/beta/api/printjob-redirect.md
  api-reference/beta/api/printoperation-get.md
  api-reference/beta/api/printtaskdefinition-update-task.md
  api-reference/beta/resources/printer.md
  api-reference/beta/resources/printtask.md
  api-reference/beta/resources/printtaskdefinition.md
  api-reference/beta/resources/printtasktrigger.md
Labels: area: universal print, internal, ready to merge

#12081 Add a note for updating printer using IPP, and fix permissions in LIST printer shares API
  api-reference/beta/api/print-list-shares.md
  api-reference/beta/api/printdocument-createuploadsession.md
  api-reference/beta/api/printer-update.md
  api-reference/v1.0/api/print-list-shares.md
  api-reference/v1.0/api/printer-update.md
  concepts/upload-data-to-upload-session.md
Labels: area: universal print, internal, ready to merge

#12311 - removes duplicated authentication provider for custom java http client
  concepts/sdks/customize-client.md
Labels: bug: sample, internal, ready to merge

#12303 Update applicationtemplate-instantiate.md
  api-reference/v1.0/api/applicationtemplate-instantiate.md
Labels: external

#12302 Update applicationtemplate-instantiate.md
  api-reference/beta/api/applicationtemplate-instantiate.md
Labels: external

#12300 Update applicationtemplate.md
  api-reference/v1.0/resources/applicationtemplate.md
Labels: external

#12299 Update applicationtemplate.md
  api-reference/beta/resources/applicationtemplate.md
Labels: external

#12310 Update user-list-memberof.md
  api-reference/beta/api/user-list-memberof.md
  api-reference/v1.0/api/user-list-memberof.md
Labels: external

#12309 Update examples in organization
  api-reference/v1.0/api/organization-get.md
  api-reference/v1.0/api/organization-list.md
Labels: area: azure/AAD, internal, ready to merge

#12316 Updated call-transfer.md
  api-reference/beta/api/call-transfer.md
  api-reference/v1.0/api/call-transfer.md
Labels: internal, ready to merge

#12326 Fixing checkMember/getMember docs
  api-reference/beta/api/group-checkmembergroups.md
  api-reference/beta/api/group-checkmemberobjects.md
  api-reference/beta/api/group-getmembergroups.md
  api-reference/beta/api/group-getmemberobjects.md
  api-reference/beta/api/serviceprincipal-checkmembergroups.md
  api-reference/beta/api/serviceprincipal-checkmemberobjects.md
  api-reference/beta/api/serviceprincipal-getmembergroups.md
  api-reference/beta/api/serviceprincipal-getmemberobjects.md
  api-reference/beta/api/user-checkmembergroups.md
  api-reference/beta/api/user-checkmemberobjects.md
  api-reference/beta/api/user-getmembergroups.md
  api-reference/beta/api/user-getmemberobjects.md
  api-reference/v1.0/api/group-checkmemberobjects.md
  api-reference/v1.0/api/group-getmemberobjects.md
  api-reference/v1.0/api/serviceprincipal-checkmembergroups.md
  api-reference/v1.0/api/serviceprincipal-checkmemberobjects.md
  api-reference/v1.0/api/serviceprincipal-getmembergroups.md
  api-reference/v1.0/api/serviceprincipal-getmemberobjects.md
  api-reference/v1.0/api/user-checkmembergroups.md
  api-reference/v1.0/api/user-checkmemberobjects.md
  api-reference/v1.0/api/user-getmembergroups.md
  api-reference/v1.0/api/user-getmemberobjects.md
Labels: internal, ready to merge

#12321 Update serviceprincipal.md
  api-reference/v1.0/resources/serviceprincipal.md
Labels: external

#12329 Updated Online Meeting doc with correct markdown alert format
  api-reference/beta/api/application-post-onlinemeetings.md
  api-reference/beta/api/onlinemeeting-createorget.md
  api-reference/beta/api/onlinemeeting-delete.md
  api-reference/beta/api/onlinemeeting-get.md
  api-reference/beta/api/onlinemeeting-update.md
  api-reference/beta/resources/onlinemeeting.md
  api-reference/v1.0/api/application-post-onlinemeetings.md
  api-reference/v1.0/api/onlinemeeting-createorget.md
  api-reference/v1.0/api/onlinemeeting-delete.md
  api-reference/v1.0/api/onlinemeeting-get.md
  api-reference/v1.0/api/onlinemeeting-update.md
  api-reference/v1.0/resources/onlinemeeting.md
Labels: content review, internal, ready to merge

#12330 Updated link to replace UserVoice by Tech Community, and the list of Microsoft 365 apps.
  concepts/overview.md
  concepts/whats-new-overview.md
Labels: internal

#12333 Merge to publish.
  api-reference/beta/api/application-post-onlinemeetings.md
  api-reference/beta/api/call-transfer.md
  api-reference/beta/api/group-checkmembergroups.md
  api-reference/beta/api/group-checkmemberobjects.md
  api-reference/beta/api/group-getmembergroups.md
  api-reference/beta/api/group-getmemberobjects.md
  api-reference/beta/api/onlinemeeting-createorget.md
  api-reference/beta/api/onlinemeeting-delete.md
  api-reference/beta/api/onlinemeeting-get.md
  api-reference/beta/api/onlinemeeting-update.md
  api-reference/beta/api/serviceprincipal-checkmembergroups.md
  api-reference/beta/api/serviceprincipal-checkmemberobjects.md
  api-reference/beta/api/serviceprincipal-getmembergroups.md
  api-reference/beta/api/serviceprincipal-getmemberobjects.md
  api-reference/beta/api/user-checkmembergroups.md
  api-reference/beta/api/user-checkmemberobjects.md
  api-reference/beta/api/user-getmembergroups.md
  api-reference/beta/api/user-getmemberobjects.md
  api-reference/beta/resources/onlinemeeting.md
  api-reference/v1.0/api/application-post-onlinemeetings.md
  api-reference/v1.0/api/call-transfer.md
  api-reference/v1.0/api/group-checkmemberobjects.md
  api-reference/v1.0/api/group-getmemberobjects.md
  api-reference/v1.0/api/onlinemeeting-createorget.md
  api-reference/v1.0/api/onlinemeeting-delete.md
  api-reference/v1.0/api/onlinemeeting-get.md
  api-reference/v1.0/api/onlinemeeting-update.md
  api-reference/v1.0/api/serviceprincipal-checkmembergroups.md
  api-reference/v1.0/api/serviceprincipal-checkmemberobjects.md
  api-reference/v1.0/api/serviceprincipal-getmembergroups.md
  api-reference/v1.0/api/serviceprincipal-getmemberobjects.md
  api-reference/v1.0/api/user-checkmembergroups.md
  api-reference/v1.0/api/user-checkmemberobjects.md
  api-reference/v1.0/api/user-getmembergroups.md
  api-reference/v1.0/api/user-getmemberobjects.md
  api-reference/v1.0/resources/onlinemeeting.md
  api-reference/v1.0/resources/serviceprincipal.md
  concepts/overview.md
  concepts/whats-new-overview.md
Labels: internal

#12315 [mgt] msal domainHint and prompt features
  concepts/toolkit/providers/msal.md
Labels: do not merge, internal

#12335 Removed view parameter from link.
  concepts/overview-major-services.md
Labels: internal

#12062 Updated online meeting attendance report
  api-reference/beta/api/onlinemeeting-get.md
  api-reference/beta/resources/attendanceInterval.md
  api-reference/beta/resources/attendanceRecord.md
  api-reference/beta/resources/meetingAttendanceReport.md
  api-reference/beta/resources/onlinemeeting.md
  changelog/Microsoft.Skype.Calling.json
Labels: content review complete, internal, ready to merge

#12342 Add String limits to user properties
  api-reference/beta/resources/user.md
  api-reference/v1.0/resources/user.md
Labels: internal, ready to merge

#12341 Update serviceprincipal-list.md
  api-reference/beta/api/serviceprincipal-list.md
Labels: external

#12340 Update serviceprincipal-list.md
  api-reference/v1.0/api/serviceprincipal-list.md
Labels: external

#12339 Update serviceprincipal.md
  api-reference/beta/resources/serviceprincipal.md
Labels: external

#12344 Adding link to tutorial
  concepts/auth-v2-service.md
Labels: internal, ready to merge

#12343 Adding link to tutorial
  concepts/auth-v2-user.md
Labels: internal, ready to merge

#12255 Add missing relationships to device resource
  api-reference/beta/resources/device.md
  api-reference/v1.0/resources/device.md
Labels: internal, ready to merge

#12188 [TeamsAppIcon] Add icon relationships to teamsAppDefinition and teamsAppIcon entity type
  api-reference/beta/api/teamsappicon-get.md
  api-reference/beta/api/teamworkhostedcontent-get.md
  api-reference/beta/resources/teamsappdefinition.md
  api-reference/beta/resources/teamsappicon.md
  api-reference/beta/resources/teamworkhostedcontent.md
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
  changelog/Microsoft.Teams.Core.json
Labels: content review complete, internal, ready to merge

#12363 Update universal-print-webhook-notifications.md
  concepts/universal-print-webhook-notifications.md
Labels: external

#12350 updated servicePrincipalType
  api-reference/v1.0/resources/serviceprincipal.md
Labels: internal, ready to merge

#12064 Links: Microsoft Graph (2021-03)
  concepts/application-saml-sso-configure-api.md
  concepts/best-practices-concept.md
  concepts/changelog.md
  concepts/graph-explorer/graph-explorer-features.md
  concepts/migrate-azure-ad-graph-deploy-test-extend.md
  concepts/office-365-connected-services.md
  concepts/onenote-abs-pos.md
  concepts/onenote-best-practices.md
  concepts/onenote-branding.md
  concepts/onenote-create-page.md
  concepts/onenote-extract-data.md
  concepts/onenote-get-content.md
  concepts/onenote-images-files.md
  concepts/onenote-note-tags.md
  concepts/onenote-update-page.md
  concepts/resolve-auth-errors.md
  concepts/sdks/choose-authentication-providers.md
  concepts/search-concept-overview.md
  concepts/security-partner-overview.md
  concepts/toolkit/get-started/build-an-electron-app.md
  concepts/universal-print-webhook-notifications.md
  concepts/versioning-and-support.md
  concepts/whats-new-overview.md
Labels: external, ready to merge

#12375 Davidmeb wufbds updates
  api-reference/beta/resources/windowsupdates-featureupdatecatalogentry.md
  api-reference/beta/resources/windowsupdates-qualityupdatecatalogentry.md
  concepts/images/windowsupdates-wufbds.png
  concepts/windowsupdates-concept-overview.md
  concepts/windowsupdates-deploy-expedited-update.md
  concepts/windowsupdates-deploy-update.md
Labels: do not merge, internal

#12390 Fix links in changelog. Remove link to enum file.
  changelog/Microsoft.IC3.DataPlatform.json
Labels: internal

#12382 Update dynamics-journal-get.md
  api-reference/beta/api/dynamics-journal-get.md
Labels: external

#12383 Files read-only permissions for /search/query
  api-reference/beta/api/search-query.md
  api-reference/v1.0/api/search-query.md
Labels: internal, ready to merge

#12389 Update cloud-communication-online-meeting-application-access-policy.md
  concepts/cloud-communication-online-meeting-application-access-policy.md
Labels: external

#12376 Fix permissions descriptions
  concepts/permissions-reference.md
Labels: internal, ready to merge

#11247 Access reviews tutorial
  concepts/accessreviews-overview.md
  concepts/images/tutorial-accessreviews-api/consentpermissions.png
  concepts/images/tutorial-accessreviews-api/consentpermissions_M365.png
  concepts/images/tutorial-accessreviews-api/selfattest.png
  concepts/images/tutorial-accessreviews-api/settings.png
  concepts/toc.yml
  concepts/tutorial-accessreviews-M365group.md
  concepts/tutorial-accessreviews-securitygroup.md
Labels: area: azure/AAD, internal, ready to merge

#12387 Method is not supported for B2C
  api-reference/beta/api/phoneauthenticationmethod-get.md
Labels: internal, ready to merge

#12405 Set of changes from docs list
  api-reference/beta/api/windowsupdates-catalog-list-entries.md
  api-reference/beta/resources/windowsupdates-expeditedqualityupdatereference.md
  api-reference/beta/resources/windowsupdates-featureupdatecatalogentry.md
  api-reference/beta/resources/windowsupdates-qualityupdatecatalogentry.md
  api-reference/beta/resources/windowsupdates-softwareupdatecatalogentry.md
  api-reference/beta/resources/windowsupdates-softwareupdatereference.md
  api-reference/beta/resources/windowsupdates-updatableassetgroup.md
  api-reference/beta/resources/windowsupdates-windowsdeploymentsettings.md
  concepts/windowsupdates-concept-overview.md
  concepts/windowsupdates-deploy-expedited-update.md
  concepts/windowsupdates-deploy-update.md
  concepts/windowsupdates-deployments.md
  concepts/windowsupdates-enroll.md
  concepts/windowsupdates-manage-monitoring-rules.md
  concepts/windowsupdates-schedule-deployment.md
  concepts/windowsupdates-software-updates.md
Labels: do not merge, internal

#12407 2021 04 21 chinglis wufb deployment service
  api-reference/beta/api/windowsupdates-catalog-list-entries.md
  api-reference/beta/resources/windowsupdates-catalogentry.md
  api-reference/beta/resources/windowsupdates-featureupdatecatalogentry.md
  api-reference/beta/resources/windowsupdates-qualityupdatecatalogentry.md
  api-reference/beta/resources/windowsupdates-softwareupdatecatalogentry.md
Labels: internal

#12410 Additional changes in response to feedback, see comment below and commits for details on changes
  api-reference/beta/api/windowsupdates-azureaddevice-get.md
  api-reference/beta/api/windowsupdates-azureaddevice-list.md
  api-reference/beta/api/windowsupdates-catalog-list-entries.md
  api-reference/beta/api/windowsupdates-deployment-create.md
  api-reference/beta/api/windowsupdates-deployment-delete.md
  api-reference/beta/api/windowsupdates-deployment-get.md
  api-reference/beta/api/windowsupdates-deployment-list.md
  api-reference/beta/api/windowsupdates-deployment-update.md
  api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md
  api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md
  api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md
  api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md
  api-reference/beta/api/windowsupdates-updatableasset-delete.md
  api-reference/beta/api/windowsupdates-updatableasset-get.md
  api-reference/beta/api/windowsupdates-updatableasset-list.md
  api-reference/beta/api/windowsupdates-updatableassetgroup-create.md
  api-reference/beta/api/windowsupdates-updatableassetgroup-delete.md
  api-reference/beta/api/windowsupdates-updatableassetgroup-get.md
  api-reference/beta/api/windowsupdates-updatableassetgroup-list-members.md
  api-reference/beta/api/windowsupdates-updatableassetgroup-list.md
  api-reference/beta/resources/windowsupdates-deploymentstate.md
  api-reference/beta/resources/windowsupdates-deploymentstatereason.md
  api-reference/beta/resources/windowsupdates-qualityupdatecatalogentry.md
Labels: internal

#12412 Made changes to softwareupdatereference to remove references it shouldnt reference.. reference
  api-reference/beta/resources/windowsupdates-softwareupdatereference.md
Labels: internal

#12401 Updated monitoring rule content
  concepts/windowsupdates-concept-overview.md
  concepts/windowsupdates-manage-monitoring-rules.md
Labels: conflicting, do not merge, internal

#12416 2021 04 21 aoneal wufbds revisions 1
  api-reference/beta/api/windowsupdates-updatableassetgroup-list-members.md
  api-reference/beta/api/windowsupdates-updatableassetgroup-list.md
  concepts/toc.yml
  concepts/windowsupdates-deployments.md
  concepts/windowsupdates-software-updates.md
Labels: internal

#12417 Reorganize API reference (add Updates, move Deployment audience down a level)
  api-reference/beta/toc.yml
Labels: internal

#12408 Update user-post-events.md
  api-reference/beta/api/user-post-events.md
Labels: external

#12404 Update featurerolloutpolicy.md
  api-reference/v1.0/resources/featurerolloutpolicy.md
Labels: external

#12332 Added deprecation information of contributors and presenters
  api-reference/beta/api/application-post-onlinemeetings.md
  api-reference/beta/resources/broadcastmeetingsettings.md
  api-reference/beta/resources/meetingparticipants.md
  api-reference/beta/resources/onlinemeeting.md
  changelog/Microsoft.Skype.Calling.json
Labels: content review complete, internal, ready to merge

#12388 Add media size values in documentation
  api-reference/beta/resources/printercapabilities.md
  api-reference/beta/resources/printerdefaults.md
  api-reference/beta/resources/printjobconfiguration.md
  api-reference/v1.0/resources/printercapabilities.md
  api-reference/v1.0/resources/printerdefaults.md
  api-reference/v1.0/resources/printjobconfiguration.md
Labels: area: universal print, internal, ready to merge

#12424 Edits on "all" pages
  api-reference/beta/api/windowsupdates-deployment-create.md
  api-reference/beta/api/windowsupdates-deployment-delete.md
  api-reference/beta/api/windowsupdates-deployment-get.md
  api-reference/beta/api/windowsupdates-deployment-list.md
  api-reference/beta/api/windowsupdates-deployment-update.md
  api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md
  api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md
  api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md
  api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md
  api-reference/beta/resources/windowsupdates-deployablecontent.md
  api-reference/beta/resources/windowsupdates-deployment.md
  api-reference/beta/resources/windowsupdates-deploymentsettings.md
  api-reference/beta/resources/windowsupdates-expeditedqualityupdatereference.md
  api-reference/beta/resources/windowsupdates-rolloutsettings.md
  api-reference/beta/resources/windowsupdates-softwareupdatereference.md
  api-reference/beta/resources/windowsupdates-windowsupdatereference.md
  concepts/windowsupdates-concept-overview.md
  concepts/windowsupdates-deploy-expedited-update.md
  concepts/windowsupdates-deploy-update.md
  concepts/windowsupdates-deployments.md
  concepts/windowsupdates-enroll.md
  concepts/windowsupdates-manage-monitoring-rules.md
  concepts/windowsupdates-schedule-deployment.md
  concepts/windowsupdates-software-updates.md
Labels: internal

#12441 Snippets Update
  api-reference/beta/includes/snippets/csharp/create-datasource-from--1-csharp-snippets.md
  api-reference/beta/includes/snippets/csharp/create-legalhold-from--csharp-snippets.md
  api-reference/beta/includes/snippets/csharp/update-openidconnectprovider-csharp-snippets.md
  api-reference/beta/includes/snippets/java/update-openidconnectprovider-java-snippets.md
  api-reference/beta/includes/snippets/javascript/update-openidconnectprovider-javascript-snippets.md
  api-reference/beta/includes/snippets/objc/update-openidconnectprovider-objc-snippets.md
  api-reference/v1.0/api/group-list-permissiongrants.md
  api-reference/v1.0/includes/snippets/csharp/group-list-permission-grants-csharp-snippets.md
  api-reference/v1.0/includes/snippets/java/group-list-permission-grants-java-snippets.md
  api-reference/v1.0/includes/snippets/javascript/group-list-permission-grants-javascript-snippets.md
  api-reference/v1.0/includes/snippets/objc/group-list-permission-grants-objc-snippets.md
Labels: external, ready to merge

#12409 Updating Chat and Chat members docs to support App context
  api-reference/beta/api/chat-get-members.md
  api-reference/beta/api/chat-get.md
  api-reference/beta/api/chat-list-members.md
  api-reference/v1.0/api/chat-get-members.md
  api-reference/v1.0/api/chat-get.md
  api-reference/v1.0/api/chat-list-members.md
  changelog/Microsoft.Teams.Core.json
Labels: internal, ready to merge

#12429 Update featurerolloutpolicy.md
  api-reference/beta/resources/featurerolloutpolicy.md
Labels: external

#12091 add links to MGT learn module
  concepts/toolkit/get-started/build-a-web-app.md
  concepts/toolkit/get-started/overview.md
  concepts/tutorials.yml
Labels: content review complete, internal, ready to merge

#12369 Update Assignments GET APIs to include AppOnly support
  api-reference/beta/api/educationassignment-get-rubric.md
  api-reference/beta/api/educationassignment-get.md
  api-reference/beta/api/educationassignment-list-categories.md
  api-reference/beta/api/educationassignment-list-resources.md
  api-reference/beta/api/educationassignment-list-submissions.md
  api-reference/beta/api/educationassignmentdefaults-get.md
  api-reference/beta/api/educationassignmentresource-get.md
  api-reference/beta/api/educationassignmentsettings-get.md
  api-reference/beta/api/educationcategory-get.md
  api-reference/beta/api/educationclass-list-assignments.md
  api-reference/beta/api/educationclass-list-categories.md
  api-reference/beta/api/educationrubric-get.md
  api-reference/beta/api/educationsubmission-get.md
  api-reference/beta/api/educationsubmission-list-outcomes.md
  api-reference/beta/api/educationsubmission-list-resources.md
  api-reference/beta/api/educationsubmission-list-submittedresources.md
  api-reference/beta/api/educationsubmissionresource-get.md
  api-reference/beta/api/educationsubmittedsubmissionresource-get.md
  changelog/Microsoft.EducationAssignment.json
Labels: internal, ready to merge

#12414 update EM approval object description
  api-reference/beta/api/approval-get.md
  api-reference/beta/api/approval-list-steps.md
  api-reference/beta/resources/approval.md
  api-reference/beta/toc.yml
Labels: area: azure/AAD, content review complete, internal, ready to merge

#12442 Merge to publish.
  api-reference/beta/api/approval-get.md
  api-reference/beta/api/approval-list-steps.md
  api-reference/beta/api/chat-get-members.md
  api-reference/beta/api/chat-get.md
  api-reference/beta/api/chat-list-members.md
  api-reference/beta/api/educationassignment-get-rubric.md
  api-reference/beta/api/educationassignment-get.md
  api-reference/beta/api/educationassignment-list-categories.md
  api-reference/beta/api/educationassignment-list-resources.md
  api-reference/beta/api/educationassignment-list-submissions.md
  api-reference/beta/api/educationassignmentdefaults-get.md
  api-reference/beta/api/educationassignmentresource-get.md
  api-reference/beta/api/educationassignmentsettings-get.md
  api-reference/beta/api/educationcategory-get.md
  api-reference/beta/api/educationclass-list-assignments.md
  api-reference/beta/api/educationclass-list-categories.md
  api-reference/beta/api/educationrubric-get.md
  api-reference/beta/api/educationsubmission-get.md
  api-reference/beta/api/educationsubmission-list-outcomes.md
  api-reference/beta/api/educationsubmission-list-resources.md
  api-reference/beta/api/educationsubmission-list-submittedresources.md
  api-reference/beta/api/educationsubmissionresource-get.md
  api-reference/beta/api/educationsubmittedsubmissionresource-get.md
  api-reference/beta/includes/snippets/csharp/create-datasource-from--1-csharp-snippets.md
  api-reference/beta/includes/snippets/csharp/create-legalhold-from--csharp-snippets.md
  api-reference/beta/includes/snippets/csharp/update-openidconnectprovider-csharp-snippets.md
  api-reference/beta/includes/snippets/java/update-openidconnectprovider-java-snippets.md
  api-reference/beta/includes/snippets/javascript/update-openidconnectprovider-javascript-snippets.md
  api-reference/beta/includes/snippets/objc/update-openidconnectprovider-objc-snippets.md
  api-reference/beta/resources/approval.md
  api-reference/beta/resources/featurerolloutpolicy.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/chat-get-members.md
  api-reference/v1.0/api/chat-get.md
  api-reference/v1.0/api/chat-list-members.md
  api-reference/v1.0/api/group-list-permissiongrants.md
  api-reference/v1.0/includes/snippets/csharp/group-list-permission-grants-csharp-snippets.md
  api-reference/v1.0/includes/snippets/java/group-list-permission-grants-java-snippets.md
  api-reference/v1.0/includes/snippets/javascript/group-list-permission-grants-javascript-snippets.md
  api-reference/v1.0/includes/snippets/objc/group-list-permission-grants-objc-snippets.md
  changelog/Microsoft.EducationAssignment.json
  changelog/Microsoft.Teams.Core.json
  concepts/toolkit/get-started/build-a-web-app.md
  concepts/toolkit/get-started/overview.md
  concepts/tutorials.yml
Labels: internal

#12394 Add file and file list in cache page
  concepts/toolkit/customize-components/cache.md
Labels: do not merge, internal

#12352 [mgt] updating localize strings for new component mgt-file and file-list
  concepts/toolkit/customize-components/localization.md
Labels: ready to merge

#12439 Update teamworktagmember-delete.md
  api-reference/beta/api/teamworktagmember-delete.md
Labels: do not merge, internal

#12438 Update teamworktagmember-get.md
  api-reference/beta/api/teamworktagmember-get.md
Labels: do not merge, internal

#12437 Update teamworktagmember-list.md
  api-reference/beta/api/teamworktagmember-list.md
Labels: do not merge, internal

#12435 Update teamworktag-delete.md
  api-reference/beta/api/teamworktag-delete.md
Labels: do not merge, internal

#12440 Updated permissions
  api-reference/beta/api/teamworktag-update.md
Labels: do not merge, internal

#12434 Update teamworktag-get.md
  api-reference/beta/api/teamworktag-get.md
Labels: do not merge, internal

#12433 Update teamworktag-list.md
  api-reference/beta/api/teamworktag-list.md
Labels: do not merge, internal

#12283 Add file and file-list docs
  concepts/toc.yml
  concepts/toolkit/components/file-list.md
  concepts/toolkit/components/file.md
Labels: do not merge, internal

#12459 b2cauthenticationmethodspolicy to include phone
  api-reference/beta/resources/b2cauthenticationmethodspolicy.md
Labels: internal, ready to merge

#12460 b2cauthenticationmethodspolicy-get includes phone
  api-reference/beta/api/b2cauthenticationmethodspolicy-get.md
Labels: internal, ready to merge

#12461 b2cauthenticationmethods-update includes phone
  api-reference/beta/api/b2cauthenticationmethodspolicy-update.md
Labels: internal, ready to merge

#12458 Various fixes
  api-reference/beta/api/group-update.md
  api-reference/v1.0/api/serviceprincipal-list.md
Labels: internal, ready to merge

#12452 Update team-post.md
  api-reference/beta/api/team-post.md
Labels: external

#12451 Update team-post.md
  api-reference/v1.0/api/team-post.md
Labels: external

#12448 Update temporaryaccesspassauthenticationmethod-create.md
  api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md
Labels: external

#12465 Fix typo, remove extra line from table
  concepts/reportroot-concept-overview.md
Labels: content review, internal

#12495 Correct Files.ReadWrite.AppFolder MSA support
  concepts/permissions-reference.md
Labels: internal, ready to merge

#12494 Fix ms-author-invalid build errors
  api-reference/beta/api/relatedcontact-update.md
  api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md
  api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md
  api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md
  api-reference/beta/api/temporaryaccesspassauthenticationmethod-post.md
  api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md
  api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md
  api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md
  api-reference/beta/resources/authenticationmethodspolicies-overview.md
  api-reference/beta/resources/relatedcontact.md
  api-reference/beta/resources/searchrequest.md
  api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md
  api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md
  api-reference/includes/accessreviews-disclaimer-v2.md
  api-reference/includes/accessreviews-disclaimer.md
  api-reference/includes/identityprovider-deprecate.md
  concepts/search-concept-custom-types.md
  concepts/search-concept-files.md
Labels: internal, ready to merge

#12493 Doc bug: Add identity provider to user flow is POST, not PATCH
  api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md
  api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md
  api-reference/v1.0/api/b2xidentityuserflow-post-identityproviders.md
Labels: ready to merge

#12483 Update teamworktagmember.md
  api-reference/beta/resources/teamworktagmember.md
Labels: do not merge, internal

#12481 Update teamworktagmember-list.md
  api-reference/beta/api/teamworktagmember-list.md
Labels: do not merge, internal

#12479 Update teamworktagmember-delete.md
  api-reference/beta/api/teamworktagmember-delete.md
Labels: do not merge, internal

#12488 Add note for GET user by UPN
  api-reference/beta/api/user-get.md
  api-reference/v1.0/api/user-get.md
  concepts/known-issues.md
Labels: internal, ready to merge

#12482 Update teamworktag.md
  api-reference/beta/resources/teamworktag.md
Labels: do not merge, internal

#12480 Update teamworktagmember-get.md
  api-reference/beta/api/teamworktagmember-get.md
Labels: do not merge, internal

#12478 Update teamworktag-update.md
  api-reference/beta/api/teamworktag-update.md
Labels: do not merge, internal

#12477 Update teamworktag-post-members.md
  api-reference/beta/api/teamworktag-post-members.md
Labels: do not merge, internal

#12476 Update teamworktag-list.md
  api-reference/beta/api/teamworktag-list.md
Labels: do not merge, internal

#12475 Update teamworktag-get.md
  api-reference/beta/api/teamworktag-get.md
Labels: do not merge, internal

#12474 Update teamworktag-delete.md
  api-reference/beta/api/teamworktag-delete.md
Labels: do not merge, internal

#12470 Update emailauthenticationmethodconfiguration-get.md
  api-reference/beta/api/emailauthenticationmethodconfiguration-get.md
Labels: external

#12294 Update tablerow-delete.md
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
Labels: area: excel, internal, ready to merge

#12391 Update application-post-onlinemeetings.md
  api-reference/v1.0/api/application-post-onlinemeetings.md
Labels: external

#12496 Fix bug in documentation for listing print jobs for a printer share
  api-reference/beta/api/printershare-list-jobs.md
  api-reference/v1.0/api/printershare-list-jobs.md
Labels: area: universal print, internal, ready to merge

#12499 Update approvalstep.md
  api-reference/beta/resources/approvalstep.md
Labels: external

#12143 Updates MGT People with new properties
  concepts/toolkit/components/people.md
Labels: do not merge, internal

#12507 Update to specify Assignments application permissions is in private preview
  api-reference/beta/api/educationassignment-get-rubric.md
  api-reference/beta/api/educationassignment-get.md
  api-reference/beta/api/educationassignment-list-categories.md
  api-reference/beta/api/educationassignment-list-resources.md
  api-reference/beta/api/educationassignment-list-submissions.md
  api-reference/beta/api/educationassignmentdefaults-get.md
  api-reference/beta/api/educationassignmentresource-get.md
  api-reference/beta/api/educationassignmentsettings-get.md
  api-reference/beta/api/educationcategory-get.md
  api-reference/beta/api/educationclass-list-assignments.md
  api-reference/beta/api/educationclass-list-categories.md
  api-reference/beta/api/educationrubric-get.md
  api-reference/beta/api/educationsubmission-get.md
  api-reference/beta/api/educationsubmission-list-outcomes.md
  api-reference/beta/api/educationsubmission-list-resources.md
  api-reference/beta/api/educationsubmission-list-submittedresources.md
  api-reference/beta/api/educationsubmissionresource-get.md
  api-reference/beta/api/educationsubmittedsubmissionresource-get.md
  changelog/Microsoft.EducationAssignment.json
  concepts/permissions-reference.md
Labels: internal, ready to merge

#12498 Correct truncated code boilerplate text
  api-reference/v1.0/api/contactfolder-post-contacts.md
Labels: internal, ready to merge

#12508 Merge to publish.
  CONTRIBUTING.md
  api-reference/beta/api/educationassignment-get-rubric.md
  api-reference/beta/api/educationassignment-get.md
  api-reference/beta/api/educationassignment-list-categories.md
  api-reference/beta/api/educationassignment-list-resources.md
  api-reference/beta/api/educationassignment-list-submissions.md
  api-reference/beta/api/educationassignmentdefaults-get.md
  api-reference/beta/api/educationassignmentresource-get.md
  api-reference/beta/api/educationassignmentsettings-get.md
  api-reference/beta/api/educationcategory-get.md
  api-reference/beta/api/educationclass-list-assignments.md
  api-reference/beta/api/educationclass-list-categories.md
  api-reference/beta/api/educationrubric-get.md
  api-reference/beta/api/educationsubmission-get.md
  api-reference/beta/api/educationsubmission-list-outcomes.md
  api-reference/beta/api/educationsubmission-list-resources.md
  api-reference/beta/api/educationsubmission-list-submittedresources.md
  api-reference/beta/api/educationsubmissionresource-get.md
  api-reference/beta/api/educationsubmittedsubmissionresource-get.md
  api-reference/beta/resources/approvalstep.md
  api-reference/beta/resources/chat.md
  api-reference/v1.0/api/contactfolder-post-contacts.md
  api-reference/v1.0/resources/chat.md
  changelog/Microsoft.EducationAssignment.json
  concepts/permissions-reference.md
Labels: internal

#11810 Add Documents For Speller
  api-reference/beta/api/search-query.md
  api-reference/beta/resources/alterationresponse.md
  api-reference/beta/resources/alteredquerytoken.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/search-api-overview.md
  api-reference/beta/resources/search.md
  api-reference/beta/resources/searchalteration.md
  api-reference/beta/resources/searchalterationoptions.md
  api-reference/beta/resources/searchentity.md
  api-reference/beta/resources/searchresponse.md
  api-reference/beta/resources/searchresultset.md
  changelog/Microsoft.MicrosoftSearch.json
  concepts/search-concept-sort.md
  concepts/search-concept-speller.md
  concepts/toc.yml
Labels: internal, ready to merge, schema live

#12510 Add missing documentation for Device.Read.All
  concepts/permissions-reference.md
Labels: internal, ready to merge

#12505 removing references to just groups in overview
  concepts/accessreviews-overview.md
  concepts/toc.yml
Labels: area: azure/AAD, ready to merge

#12380 Fix Report Fieldname Typo
  api-reference/v1.0/api/reportroot-getskypeforbusinessactivityuserdetail.md
Labels: external, review requested

#12370 access review policy
  api-reference/beta/api/accessreviewpolicy-get.md
  api-reference/beta/api/accessreviewpolicy-update.md
  api-reference/beta/resources/accessreviewpolicy.md
  api-reference/beta/toc.yml
  changelog/Microsoft.IdentityGovernance.AccessReviews.json
Labels: area: azure/AAD, ready to merge

#12512 Adding request block name to CreateUploadSession request
  api-reference/v1.0/api/printdocument-createuploadsession.md
Labels: area: universal print, internal, ready to merge
