Repository microsoftgraph/microsoft-graph-docs, pull requests merged in 2021-01, with the labels that each got.

#11173 Update chat-post.md
  api-reference/beta/api/chat-post.md
Labels: external

#11171 Update people-picker.md
  concepts/toolkit/components/people-picker.md
Labels: external

#11156 Update aaduserconversationmember.md
  api-reference/v1.0/resources/aaduserconversationmember.md
Labels: external

#11155 Update aaduserconversationmember.md
  api-reference/beta/resources/aaduserconversationmember.md
Labels: external

#11153 2020 12 30 typos
  api-reference/v1.0/toc.yml
Labels: external

#11145 Update team-get-members.md
  api-reference/v1.0/api/team-get-members.md
Labels: external

#11144 Update team-get-members.md
  api-reference/beta/api/team-get-members.md
Labels: external

#11130 Update event.md
  api-reference/beta/resources/event.md
Labels: external

#11110 Update tutorial-riskdetection-api.md
  concepts/tutorial-riskdetection-api.md
Labels: external

#11108 Update group.md
  api-reference/v1.0/resources/group.md
Labels: external

#11086 Update educationclass-post-assignments.md
  api-reference/beta/api/educationclass-post-assignments.md
Labels: external

#11053 Update driveitem.md
  api-reference/v1.0/resources/driveitem.md
Labels: external

#10949 Adding Hidden Folder Support to mailFolders Entity in Beta
  api-reference/beta/api/mailfolder-get.md
  api-reference/beta/api/user-list-mailfolders.md
  api-reference/beta/api/user-post-mailfolders.md
  api-reference/beta/resources/mailfolder.md
  changelog/Microsoft.Exchange.json
  concepts/changelog.md
Labels: internal, ready to merge

#11115 Update workbook-best-practice.md
  concepts/workbook-best-practice.md
Labels: internal, ready to merge

#11022 Search - Adding one limitation - Clarification on Special Cloud coverage for Microsoft Search
  api-reference/beta/resources/search-api-overview.md
  api-reference/v1.0/resources/search-api-overview.md
  concepts/deployments.md
Labels: internal, ready to merge

#11097 Add hostnames to device get and list API
  api-reference/beta/api/device-get.md
  api-reference/beta/api/device-list.md
  api-reference/beta/resources/device.md
  changelog/Microsoft.DirectoryServices.json
  concepts/changelog.md
Labels: external

#11113 Added example for frequency in 'termsExpiration' - ToU
  api-reference/beta/resources/termsexpiration.md
Labels: internal, ready to merge

#11100 Update security-api-overview.md
  api-reference/v1.0/config/link-validation-config.json
  api-reference/v1.0/resources/security-api-overview.md
Labels: external

#11181 Update chat-patch.md
  api-reference/beta/api/chat-patch.md
Labels: external

#11182 Update chat-post.md
  api-reference/beta/api/chat-post.md
Labels: external

#11119 Remove signInActivity property from Users v1.0
  api-reference/v1.0/api/user-list.md
  api-reference/v1.0/resources/user.md
Labels: area: users, internal, ready to merge

#11152 Update EM requestorSettings with new scopeType
  api-reference/beta/resources/requestorsettings.md
Labels: area: azure/AAD, internal, ready to merge

#11195 Missing basetype causes issues for client library
  api-reference/beta/resources/applicationserviceprincipal.md
  api-reference/beta/resources/approvalsettings.md
  api-reference/beta/resources/approvalstage.md
  api-reference/beta/resources/assignmentreviewsettings.md
  api-reference/beta/resources/expirationpattern.md
  api-reference/beta/resources/externalitemcontent.md
  api-reference/beta/resources/regionalformatoverrides.md
  api-reference/beta/resources/requestorsettings.md
  api-reference/beta/resources/requestschedule.md
  api-reference/beta/resources/termsexpiration.md
  api-reference/beta/resources/userset.md
Labels: internal, ready to merge

#11206 Powershell updates
  concepts/powershell/get-started.md
  concepts/powershell/navigating.md
Labels: internal, ready to merge

#11204 Changed lambda declaration to avoid CS0136 compiler error
  concepts/sdks/large-file-upload.md
Labels: internal, ready to merge

#11197 Update chat-delete-members.md
  api-reference/beta/api/chat-delete-members.md
Labels: external

#11196 Update chat-post-members.md
  api-reference/beta/api/chat-post-members.md
Labels: external

#11213 Update application-provisioning-configure-api.md
  concepts/application-provisioning-configure-api.md
Labels: area: azure/AAD, content review, internal, ready to merge

#11215 Merge to publish.
  api-reference/beta/api/chat-delete-members.md
  api-reference/beta/api/chat-post-members.md
  api-reference/beta/resources/applicationserviceprincipal.md
  api-reference/beta/resources/approvalsettings.md
  api-reference/beta/resources/approvalstage.md
  api-reference/beta/resources/assignmentreviewsettings.md
  api-reference/beta/resources/expirationpattern.md
  api-reference/beta/resources/externalitemcontent.md
  api-reference/beta/resources/regionalformatoverrides.md
  api-reference/beta/resources/requestorsettings.md
  api-reference/beta/resources/requestschedule.md
  api-reference/beta/resources/termsexpiration.md
  api-reference/beta/resources/userset.md
  concepts/application-provisioning-configure-api.md
  concepts/powershell/get-started.md
  concepts/powershell/navigating.md
  concepts/sdks/large-file-upload.md
Labels: internal

#11223 Update channels-getallmessages.md
  api-reference/beta/api/channels-getallmessages.md
Labels: external

#11221 create-team-csharp-snippets.md
  api-reference/v1.0/includes/snippets/csharp/create-team-csharp-snippets.md
Labels: external

#11211 Update signin.md
  api-reference/beta/resources/signin.md
  api-reference/v1.0/resources/signin.md
Labels: external, ready to merge

#11016 Expose membership processing status of dynamic groups
  api-reference/beta/api/group-get.md
  api-reference/beta/api/group-list.md
  api-reference/beta/resources/group.md
  api-reference/beta/resources/membershipruleprocessingstatus.md
  changelog/Microsoft.DirectoryServices.json
  concepts/changelog.md
Labels: area: azure/AAD, area: groups, beta, internal, ready to merge

#11191 Add xps to pdf conversion details, PrintJob.Create and PrinterShare.ReadBasic.All scope and minor fixes
  api-reference/beta/api/printdocument-createuploadsession.md
  api-reference/beta/api/printdocument-get-file.md
  api-reference/beta/api/printer-get.md
  api-reference/beta/api/printer-post-jobs.md
  api-reference/beta/api/printershare-get.md
  api-reference/beta/api/printjob-abort.md
  api-reference/beta/api/printjob-start.md
  api-reference/beta/api/printjob-update-configuration.md
  api-reference/beta/resources/printjob.md
  api-reference/beta/toc.yml
  changelog/Microsoft.PrintService.json
  concepts/changelog.md
  concepts/permissions-reference.md
Labels: area: universal print, internal, ready to merge

#11227 Merge to publish.
  api-reference/beta/api/channels-getallmessages.md
  api-reference/beta/api/group-get.md
  api-reference/beta/api/group-list.md
  api-reference/beta/api/printdocument-createuploadsession.md
  api-reference/beta/api/printdocument-get-file.md
  api-reference/beta/api/printer-get.md
  api-reference/beta/api/printer-post-jobs.md
  api-reference/beta/api/printershare-get.md
  api-reference/beta/api/printjob-abort.md
  api-reference/beta/api/printjob-start.md
  api-reference/beta/api/printjob-update-configuration.md
  api-reference/beta/resources/group.md
  api-reference/beta/resources/membershipruleprocessingstatus.md
  api-reference/beta/resources/printjob.md
  api-reference/beta/resources/signin.md
  api-reference/beta/toc.yml
  api-reference/v1.0/includes/snippets/csharp/create-team-csharp-snippets.md
  api-reference/v1.0/resources/signin.md
  changelog/Microsoft.DirectoryServices.json
  changelog/Microsoft.PrintService.json
  concepts/changelog.md
  concepts/permissions-reference.md
Labels: internal

#11228 Rephrase TOC titles.
  api-reference/beta/resources/accessreviews-root.md
  api-reference/beta/resources/accessreviewsv2-root.md
  api-reference/beta/toc.yml
Labels: do not merge, internal

#11234 Fixing links in Universal Print overview page
  concepts/universal-print-concept-overview.md
Labels: area: universal print, internal, ready to merge

#11229 Contain incorrect base type for complex types.
  api-reference/beta/resources/cloudpcsourcedeviceimage.md
  api-reference/beta/resources/workbooksortfield.md
Labels: internal, ready to merge

#11236 Remove invisible unicode characters
  api-reference/beta/api/intune-deviceconfig-windows10generalconfiguration-create.md
  api-reference/beta/api/intune-deviceconfig-windows10generalconfiguration-update.md
  api-reference/beta/api/intune-deviceconfig-windowswifienterpriseeapconfiguration-create.md
  api-reference/beta/api/intune-deviceconfig-windowswifienterpriseeapconfiguration-update.md
  api-reference/beta/resources/intune-deviceconfig-windows10generalconfiguration.md
  api-reference/beta/resources/intune-deviceconfig-windowswifienterpriseeapconfiguration.md
Labels: internal, ready to merge

#11232 Update teamworkbot-get.md
  api-reference/beta/api/teamworkbot-get.md
Labels: external

#10833 update permission-update to be more specific on what fields and permission types can be modified
  api-reference/beta/api/permission-update.md
  api-reference/v1.0/api/permission-update.md
Labels: content review, ready to merge

#11230 Messages Fixing: 'code-block-*', 'table-syntax-invalid'. Worse remain.
  api-reference/beta/api/intune-deviceconfig-macosdevicefeaturesconfiguration-create.md
  api-reference/beta/api/intune-deviceconfig-macosdevicefeaturesconfiguration-update.md
  api-reference/beta/api/intune-shared-devicemanagementderivedcredentialsettings-get.md
  api-reference/beta/api/profilephoto-get.md
  api-reference/beta/resources/azure-ad-overview.md
  api-reference/v1.0/api/profilephoto-get.md
Labels: external, ready to merge

#11239 Merge to publish.
  api-reference/beta/api/intune-deviceconfig-macosdevicefeaturesconfiguration-create.md
  api-reference/beta/api/intune-deviceconfig-macosdevicefeaturesconfiguration-update.md
  api-reference/beta/api/intune-deviceconfig-windows10generalconfiguration-create.md
  api-reference/beta/api/intune-deviceconfig-windows10generalconfiguration-update.md
  api-reference/beta/api/intune-deviceconfig-windowswifienterpriseeapconfiguration-create.md
  api-reference/beta/api/intune-deviceconfig-windowswifienterpriseeapconfiguration-update.md
  api-reference/beta/api/intune-shared-devicemanagementderivedcredentialsettings-get.md
  api-reference/beta/api/permission-update.md
  api-reference/beta/api/profilephoto-get.md
  api-reference/beta/api/teamworkbot-get.md
  api-reference/beta/resources/accessreviews-root.md
  api-reference/beta/resources/accessreviewsv2-root.md
  api-reference/beta/resources/azure-ad-overview.md
  api-reference/beta/resources/cloudpcsourcedeviceimage.md
  api-reference/beta/resources/intune-deviceconfig-windows10generalconfiguration.md
  api-reference/beta/resources/intune-deviceconfig-windowswifienterpriseeapconfiguration.md
  api-reference/beta/resources/workbooksortfield.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/permission-update.md
  api-reference/v1.0/api/profilephoto-get.md
  concepts/universal-print-concept-overview.md
Labels: internal

#11243 Update channelmoderationsettings.md
  api-reference/beta/resources/channelmoderationsettings.md
Labels: external

#11240 Update todo-post-lists.md
  api-reference/beta/api/todo-post-lists.md
Labels: external

#11237 Add outOfOfficeSettings for presence
  api-reference/beta/api/cloudcommunications-getpresencesbyuserid.md
  api-reference/beta/api/presence-get.md
  api-reference/beta/resources/outofofficesettings.md
  api-reference/beta/resources/presence.md
  changelog/Microsoft.Skype.Calling.json
  concepts/changelog.md
Labels: internal, ready to merge

#11208 Describing new licensing mechanism for MGDC
  concepts/data-connect-policies.md
Labels: internal, ready to merge

#11058 Add new auth methods, update auth method permissions
  api-reference/beta/api/authentication-list-methods.md
  api-reference/beta/api/authentication-list-passwordmethods.md
  api-reference/beta/api/authentication-list-phonemethods.md
  api-reference/beta/api/authentication-post-phonemethods.md
  api-reference/beta/api/authenticationmethod-get.md
  api-reference/beta/api/emailauthenticationmethod-delete.md
  api-reference/beta/api/emailauthenticationmethod-get.md
  api-reference/beta/api/emailauthenticationmethod-list.md
  api-reference/beta/api/emailauthenticationmethod-post.md
  api-reference/beta/api/emailauthenticationmethod-update.md
  api-reference/beta/api/fido2authenticationmethod-delete.md
  api-reference/beta/api/fido2authenticationmethod-get.md
  api-reference/beta/api/fido2authenticationmethod-list.md
  api-reference/beta/api/microsoftauthenticatorauthenticationmethod-delete.md
  api-reference/beta/api/microsoftauthenticatorauthenticationmethod-get.md
  api-reference/beta/api/microsoftauthenticatorauthenticationmethod-list.md
  api-reference/beta/api/passwordauthenticationmethod-get.md
  api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-delete.md
  api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-get.md
  api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-list.md
  api-reference/beta/api/phoneauthenticationmethod-delete.md
  api-reference/beta/api/phoneauthenticationmethod-disablesmssignin.md
  api-reference/beta/api/phoneauthenticationmethod-enablesmssignin.md
  api-reference/beta/api/phoneauthenticationmethod-get.md
  api-reference/beta/api/phoneauthenticationmethod-update.md
  api-reference/beta/api/windowshelloforbusinessauthenticationmethod-delete.md
  api-reference/beta/api/windowshelloforbusinessauthenticationmethod-get.md
  api-reference/beta/api/windowshelloforbusinessauthenticationmethod-list.md
  api-reference/beta/resources/authenticationmethods-overview.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/microsoftauthenticatorauthenticationmethod.md
  api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethod.md
  api-reference/beta/resources/windowshelloforbusinessauthenticationmethod.md
  api-reference/beta/toc.yml
Labels: internal, ready to merge

#11251 Auth methods changelog updates
  changelog/Microsoft.DirectoryServices.json
Labels: internal, ready to merge

#11252 Merge to publish.
  api-reference/beta/api/authentication-list-methods.md
  api-reference/beta/api/authentication-list-passwordmethods.md
  api-reference/beta/api/authentication-list-phonemethods.md
  api-reference/beta/api/authentication-post-phonemethods.md
  api-reference/beta/api/authenticationmethod-get.md
  api-reference/beta/api/cloudcommunications-getpresencesbyuserid.md
  api-reference/beta/api/emailauthenticationmethod-delete.md
  api-reference/beta/api/emailauthenticationmethod-get.md
  api-reference/beta/api/emailauthenticationmethod-list.md
  api-reference/beta/api/emailauthenticationmethod-post.md
  api-reference/beta/api/emailauthenticationmethod-update.md
  api-reference/beta/api/fido2authenticationmethod-delete.md
  api-reference/beta/api/fido2authenticationmethod-get.md
  api-reference/beta/api/fido2authenticationmethod-list.md
  api-reference/beta/api/microsoftauthenticatorauthenticationmethod-delete.md
  api-reference/beta/api/microsoftauthenticatorauthenticationmethod-get.md
  api-reference/beta/api/microsoftauthenticatorauthenticationmethod-list.md
  api-reference/beta/api/passwordauthenticationmethod-get.md
  api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-delete.md
  api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-get.md
  api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethod-list.md
  api-reference/beta/api/phoneauthenticationmethod-delete.md
  api-reference/beta/api/phoneauthenticationmethod-disablesmssignin.md
  api-reference/beta/api/phoneauthenticationmethod-enablesmssignin.md
  api-reference/beta/api/phoneauthenticationmethod-get.md
  api-reference/beta/api/phoneauthenticationmethod-update.md
  api-reference/beta/api/presence-get.md
  api-reference/beta/api/todo-post-lists.md
  api-reference/beta/api/windowshelloforbusinessauthenticationmethod-delete.md
  api-reference/beta/api/windowshelloforbusinessauthenticationmethod-get.md
  api-reference/beta/api/windowshelloforbusinessauthenticationmethod-list.md
  api-reference/beta/resources/authenticationmethods-overview.md
  api-reference/beta/resources/channelmoderationsettings.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/microsoftauthenticatorauthenticationmethod.md
  api-reference/beta/resources/outofofficesettings.md
  api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethod.md
  api-reference/beta/resources/presence.md
  api-reference/beta/resources/windowshelloforbusinessauthenticationmethod.md
  api-reference/beta/toc.yml
  changelog/Microsoft.DirectoryServices.json
  changelog/Microsoft.Skype.Calling.json
  concepts/changelog.md
  concepts/data-connect-policies.md
Labels: internal

#11260 Doc examples per guidance so to show linking to example from top section of API topic.
  api-reference/beta/api/message-get.md
  api-reference/beta/api/user-list-messages.md
  api-reference/beta/resources/mail-api-overview.md
  api-reference/beta/resources/mention.md
  api-reference/v1.0/api/message-get.md
  api-reference/v1.0/resources/mail-api-overview.md
Labels: internal

#11257 Update teamworkbot.md
  api-reference/beta/resources/teamworkbot.md
Labels: external

#11090 [CloudPC] add UpdateAdDomainPassword api & add 5 enums in cloudPcOnPremisesConnectionHealthCheckErrorType
  api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md
  api-reference/beta/resources/cloudpconpremisesconnection.md
  api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
  api-reference/beta/resources/enums.md
  api-reference/beta/toc.yml
  changelog/Microsoft.CloudManagedDesktop.json
  concepts/changelog.md
Labels: internal, ready to merge

#11194 MSA developer support to call app API v1.0
  api-reference/v1.0/api/application-addpassword.md
  api-reference/v1.0/api/application-delete-extensionproperty.md
  api-reference/v1.0/api/application-delete.md
  api-reference/v1.0/api/application-get.md
  api-reference/v1.0/api/application-list-extensionproperty.md
  api-reference/v1.0/api/application-list.md
  api-reference/v1.0/api/application-post-applications.md
  api-reference/v1.0/api/application-post-extensionproperty.md
  api-reference/v1.0/api/application-removepassword.md
  api-reference/v1.0/api/application-update.md
  api-reference/v1.0/resources/application.md
  changelog/Microsoft.DirectoryServices.json
  concepts/changelog.md
Labels: internal

#11270 Update channel-post-messagereply.md
  api-reference/beta/api/channel-post-messagereply.md
Labels: external

#11265 Remove unused property evaluateOnly
  api-reference/beta/api/privilegedroleassignmentrequest-list.md
  api-reference/beta/api/privilegedroleassignmentrequest-my.md
  api-reference/beta/api/privilegedroleassignmentrequest-post.md
  api-reference/beta/includes/snippets/csharp/post-privilegedroleassignmentrequest-csharp-snippets.md
  api-reference/beta/includes/snippets/java/post-privilegedroleassignmentrequest-java-snippets.md
  api-reference/beta/includes/snippets/javascript/post-privilegedroleassignmentrequest-javascript-snippets.md
  api-reference/beta/includes/snippets/objc/post-privilegedroleassignmentrequest-objc-snippets.md
Labels: area: identity, internal, ready to merge

#11269 Update printjobconfiguration.md
  api-reference/beta/resources/printjobconfiguration.md
Labels: external

#11271 Teams: Add crossreference for duplicated data
  concepts/teams-proactive-messaging.md
  concepts/toc.yml
Labels: do not merge, internal

#10345 Live event document
  api-reference/beta/api/application-post-onlinemeetings.md
  api-reference/beta/api/onlinemeeting-get.md
  api-reference/beta/resources/broadcastmeetingsettings.md
  api-reference/beta/resources/onlinemeeting.md
  api-reference/v1.0/resources/onlinemeeting.md
  changelog/Microsoft.Skype.Calling.json
  concepts/changelog.md
Labels: internal, ready to merge

#11275 Merge to publish.
  api-reference/beta/api/application-post-onlinemeetings.md
  api-reference/beta/api/channel-post-messagereply.md
  api-reference/beta/api/onlinemeeting-get.md
  api-reference/beta/api/privilegedroleassignmentrequest-list.md
  api-reference/beta/api/privilegedroleassignmentrequest-my.md
  api-reference/beta/api/privilegedroleassignmentrequest-post.md
  api-reference/beta/includes/snippets/csharp/post-privilegedroleassignmentrequest-csharp-snippets.md
  api-reference/beta/includes/snippets/java/post-privilegedroleassignmentrequest-java-snippets.md
  api-reference/beta/includes/snippets/javascript/post-privilegedroleassignmentrequest-javascript-snippets.md
  api-reference/beta/includes/snippets/objc/post-privilegedroleassignmentrequest-objc-snippets.md
  api-reference/beta/resources/broadcastmeetingsettings.md
  api-reference/beta/resources/onlinemeeting.md
  api-reference/beta/resources/printjobconfiguration.md
  api-reference/v1.0/resources/onlinemeeting.md
  changelog/Microsoft.Skype.Calling.json
  concepts/changelog.md
  concepts/teams-proactive-messaging.md
  concepts/toc.yml
Labels: internal

#11283 Update event.md
  api-reference/v1.0/resources/event.md
Labels: external

#11288 Redirect changelog to new experience.
  .openpublishing.redirection.json
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
  concepts/toc.yml
Labels: internal

#11287 Added missing link for chat export API
  api-reference/beta/resources/chatmessage.md
Labels: area: teams, internal, ready to merge

#11285 Update insights-customize-item-insights-privacy.md
  concepts/insights-customize-item-insights-privacy.md
Labels: ready to merge

#11249 Fix typo
  api-reference/beta/resources/unifiedrolepermission.md
Labels: internal, ready to merge

#11248 Update POST responses to 201 Created
  api-reference/beta/api/serviceprincipal-post-approleassignedto.md
  api-reference/beta/api/serviceprincipal-post-approleassignments.md
  api-reference/beta/api/serviceprincipal-post-delegatedpermissionclassifications.md
  api-reference/v1.0/api/serviceprincipal-post-approleassignedto.md
  api-reference/v1.0/api/serviceprincipal-post-approleassignments.md
  api-reference/v1.0/api/serviceprincipal-post-delegatedpermissionclassifications.md
Labels: internal, ready to merge

#11250 2021-01-12 Microsoft Authenticator Auth Method Policy
  api-reference/beta/api/authentication-list-methods.md
  api-reference/beta/api/microsoftauthenticatorauthenticationmethod-delete.md
  api-reference/beta/api/microsoftauthenticatorauthenticationmethod-get.md
  api-reference/beta/api/microsoftauthenticatorauthenticationmethod-list.md
  api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-delete.md
  api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md
  api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-update.md
  api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-delete.md
  api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-get.md
  api-reference/beta/api/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-update.md
  api-reference/beta/api/windowshelloforbusinessauthenticationmethod-delete.md
  api-reference/beta/api/windowshelloforbusinessauthenticationmethod-get.md
  api-reference/beta/api/windowshelloforbusinessauthenticationmethod-list.md
  api-reference/beta/resources/authenticationmethod.md
  api-reference/beta/resources/authenticationmethods-overview.md
  api-reference/beta/resources/authenticationmethodspolicies-overview.md
  api-reference/beta/resources/microsoftauthenticatorauthenticationmethodconfiguration.md
  api-reference/beta/resources/microsoftauthenticatorauthenticationmethodtarget.md
  api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md
  api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md
  api-reference/beta/toc.yml
  changelog/Microsoft.DirectoryServices.json
Labels: ready to merge

#11192 Update graph doc for additional scopes
  api-reference/beta/api/print-get-settings.md
  api-reference/beta/api/print-list-connectors.md
  api-reference/beta/api/print-update-settings.md
  api-reference/beta/api/printconnector-delete.md
  api-reference/beta/api/printconnector-get.md
  api-reference/beta/api/printconnector-update.md
  changelog/Microsoft.PrintService.json
  concepts/changelog.md
  concepts/permissions-reference.md
Labels: area: universal print, changes requested, internal, ready to merge

#11292 Teams: Fix regression: Add missing request body.
  api-reference/beta/api/channel-post-members.md
Labels: internal, ready to merge

#11299 Update cloud-communication-online-meeting-application-access-policy.md
  concepts/cloud-communication-online-meeting-application-access-policy.md
Labels: external

#11256 Links: Microsoft Graph (2021-01)
  concepts/activity-feed-concept-overview.md
  concepts/changelog.md
  concepts/device-relay-concept-overview.md
  concepts/insights-customize-item-insights-privacy.md
  concepts/migrate-azure-ad-graph-planning-checklist.md
  concepts/search-index-manage-connections.md
  concepts/search-index-manage-items.md
  concepts/search-index-manage-schema.md
  concepts/toolkit/providers/msal.md
  concepts/universal-print-concept-overview.md
  concepts/webhooks.md
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: external

#11303 Fixes HTTP verbs for workbook range functions
  api-reference/beta/api/workbookrange-columnsafter.md
  api-reference/beta/api/workbookrange-columnsbefore.md
  api-reference/beta/api/workbookrange-rowsabove.md
  api-reference/beta/api/workbookrange-rowsbelow.md
  api-reference/beta/includes/snippets/csharp/workbookrange-columnsafter-csharp-snippets.md
  api-reference/beta/includes/snippets/csharp/workbookrange-columnsbefore-csharp-snippets.md
  api-reference/beta/includes/snippets/csharp/workbookrange-rowsabove-csharp-snippets.md
  api-reference/beta/includes/snippets/csharp/workbookrange-rowsbelow-csharp-snippets.md
  api-reference/beta/includes/snippets/java/workbookrange-columnsafter-java-snippets.md
  api-reference/beta/includes/snippets/java/workbookrange-columnsbefore-java-snippets.md
  api-reference/beta/includes/snippets/java/workbookrange-rowsabove-java-snippets.md
  api-reference/beta/includes/snippets/java/workbookrange-rowsbelow-java-snippets.md
  api-reference/beta/includes/snippets/javascript/workbookrange-columnsafter-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/workbookrange-columnsbefore-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/workbookrange-rowsabove-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/workbookrange-rowsbelow-javascript-snippets.md
  api-reference/beta/includes/snippets/objc/workbookrange-columnsafter-objc-snippets.md
  api-reference/beta/includes/snippets/objc/workbookrange-columnsbefore-objc-snippets.md
  api-reference/beta/includes/snippets/objc/workbookrange-rowsabove-objc-snippets.md
  api-reference/beta/includes/snippets/objc/workbookrange-rowsbelow-objc-snippets.md
  api-reference/v1.0/api/workbookrange-columnsafter.md
  api-reference/v1.0/api/workbookrange-columnsbefore.md
  api-reference/v1.0/api/workbookrange-rowsabove.md
  api-reference/v1.0/api/workbookrange-rowsbelow.md
  api-reference/v1.0/includes/snippets/csharp/workbookrange-columnsafter-csharp-snippets.md
  api-reference/v1.0/includes/snippets/csharp/workbookrange-columnsbefore-csharp-snippets.md
  api-reference/v1.0/includes/snippets/csharp/workbookrange-rowsabove-csharp-snippets.md
  api-reference/v1.0/includes/snippets/csharp/workbookrange-rowsabove-nocount-csharp-snippets.md
  api-reference/v1.0/includes/snippets/csharp/workbookrange-rowsbelow-csharp-snippets.md
  api-reference/v1.0/includes/snippets/java/workbookrange-columnsafter-java-snippets.md
  api-reference/v1.0/includes/snippets/java/workbookrange-columnsbefore-java-snippets.md
  api-reference/v1.0/includes/snippets/java/workbookrange-rowsabove-java-snippets.md
  api-reference/v1.0/includes/snippets/java/workbookrange-rowsabove-nocount-java-snippets.md
  api-reference/v1.0/includes/snippets/java/workbookrange-rowsbelow-java-snippets.md
  api-reference/v1.0/includes/snippets/javascript/workbookrange-columnsafter-javascript-snippets.md
  api-reference/v1.0/includes/snippets/javascript/workbookrange-columnsbefore-javascript-snippets.md
  api-reference/v1.0/includes/snippets/javascript/workbookrange-rowsabove-javascript-snippets.md
  api-reference/v1.0/includes/snippets/javascript/workbookrange-rowsabove-nocount-javascript-snippets.md
  api-reference/v1.0/includes/snippets/javascript/workbookrange-rowsbelow-javascript-snippets.md
  api-reference/v1.0/includes/snippets/objc/workbookrange-columnsafter-objc-snippets.md
  api-reference/v1.0/includes/snippets/objc/workbookrange-columnsbefore-objc-snippets.md
  api-reference/v1.0/includes/snippets/objc/workbookrange-rowsabove-nocount-objc-snippets.md
  api-reference/v1.0/includes/snippets/objc/workbookrange-rowsabove-objc-snippets.md
  api-reference/v1.0/includes/snippets/objc/workbookrange-rowsbelow-objc-snippets.md
Labels: internal, ready to merge

#11308 Updated changelog to fix identical entries
  changelog/Microsoft.DirectoryServices.json
Labels: internal, ready to merge

#11123 Update search-concept-aggregation.md
  api-reference/beta/resources/search-api-overview.md
  api-reference/beta/resources/searchrequest.md
  concepts/search-concept-aggregation.md
Labels: internal, ready to merge

#10921 2020 12 01 tarkansevilmis planner feature update
  api-reference/beta/api/planner-post-plans.md
  api-reference/beta/api/plannergroup-list-plans.md
  api-reference/beta/api/plannerplan-get.md
  api-reference/beta/api/plannerplan-update.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/planner-overview.md
  api-reference/beta/resources/plannerplan.md
  api-reference/beta/resources/plannerplancontainer.md
  api-reference/beta/resources/plannertask.md
  api-reference/beta/resources/plannertaskcreation.md
  api-reference/beta/resources/plannerteamspublicationinfo.md
  changelog/Microsoft.Office.Tasks.json
  concepts/changelog.md
Labels: internal, ready to merge

#11315 Rolled up what's new.
  api-reference/beta/toc.yml
  changelog/Microsoft.PrintService.json
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: do not merge, internal

#11316 Refresh What's new topic.
  api-reference/beta/toc.yml
  changelog/Microsoft.PrintService.json
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: internal

#11321 Minor change for testing.
  concepts/whats-new-overview.md
Labels: do not merge, internal

#11349 1801203: Fixed incorrect code tag.
  concepts/change-notifications-delivery.md
Labels: external

#11340 Update userteamwork-sendactivitynotification.md
  api-reference/beta/api/userteamwork-sendactivitynotification.md
Labels: external

#11342 Update signin-list.md
  api-reference/v1.0/api/signin-list.md
Labels: external

#11305 Add extra info for publisherDomain property
  api-reference/v1.0/resources/application.md
Labels: internal, ready to merge

#11345 Update unifiedrolepermission.md
  api-reference/beta/resources/unifiedrolepermission.md
Labels: internal, ready to merge

#11330 Show usage of endsWith & $select on Users
  api-reference/beta/api/user-list.md
  api-reference/beta/resources/user.md
  api-reference/v1.0/api/user-list.md
  api-reference/v1.0/resources/user.md
  api-reference/v1.0/resources/users.md
Labels: area: users, internal, ready to merge

#11133 Update EM docs to add AdminRemove for resources and delegated assignment list
  api-reference/beta/api/accesspackageassignment-list.md
  api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md
  api-reference/beta/api/accesspackageresourcerequest-post.md
  api-reference/beta/resources/accesspackageresource.md
  api-reference/beta/resources/accesspackageresourcerequest.md
Labels: area: azure/AAD, internal, ready to merge

#11307 Update return type to None - fix #9734
  api-reference/v1.0/resources/application.md
Labels: internal, ready to merge

#11325 id is not a GUID. Fix #4279
  api-reference/beta/resources/directoryaudit.md
Labels: internal, ready to merge

#11374 Update regionalandlanguagesettings.md
  api-reference/beta/resources/regionalandlanguagesettings.md
Labels: external

#11362 Removing duplicate 'Cloud Printing' permissions
  concepts/permissions-reference.md
Labels: area: universal print, internal, ready to merge

#11355 Update team-list-installedapps.md
  api-reference/beta/api/team-list-installedapps.md
Labels: external

#11329 Update user-list-transitivememberof.md
  api-reference/beta/api/user-list-transitivememberof.md
Labels: external

#11246 Update changelogs for modified printerProcessingStateDetail values
  changelog/Microsoft.PrintService.json
  concepts/changelog.md
Labels: area: universal print, internal, ready to merge

#10996 Fixing conditions for custom roles
  api-reference/beta/resources/unifiedrolepermission.md
Labels: area: azure/AAD, external, ready to merge, review requested

#11226 Add and update UP related webhook notification docs
  api-reference/beta/api/subscription-delete.md
  api-reference/beta/api/subscription-get.md
  api-reference/beta/api/subscription-post-subscriptions.md
  api-reference/beta/api/subscription-update.md
  api-reference/beta/resources/printer.md
  api-reference/beta/resources/printtaskdefinition.md
  api-reference/beta/resources/subscription.md
  changelog/Microsoft.PrintService.json
  concepts/toc.yml
  concepts/universal-print-webhook-notifications.md
  concepts/webhooks.md
Labels: area: universal print, area: webhooks, internal, ready to merge

#11373 Documenting future possibilities of consumption fees
  api-reference/beta/api/subscription-delete.md
  api-reference/beta/api/subscription-get.md
  api-reference/beta/api/subscription-post-subscriptions.md
  api-reference/beta/api/subscription-update.md
  api-reference/v1.0/api/subscription-delete.md
  api-reference/v1.0/api/subscription-get.md
  api-reference/v1.0/api/subscription-post-subscriptions.md
  api-reference/v1.0/api/subscription-update.md
Labels: area: teams, internal, ready to merge

#11376 Merge to publish.
  api-reference/beta/api/accesspackageassignment-list.md
  api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md
  api-reference/beta/api/accesspackageresourcerequest-post.md
  api-reference/beta/api/subscription-delete.md
  api-reference/beta/api/subscription-get.md
  api-reference/beta/api/subscription-post-subscriptions.md
  api-reference/beta/api/subscription-update.md
  api-reference/beta/api/team-list-installedapps.md
  api-reference/beta/api/user-list-transitivememberof.md
  api-reference/beta/api/user-list.md
  api-reference/beta/resources/accesspackageresource.md
  api-reference/beta/resources/accesspackageresourcerequest.md
  api-reference/beta/resources/directoryaudit.md
  api-reference/beta/resources/printer.md
  api-reference/beta/resources/printtaskdefinition.md
  api-reference/beta/resources/regionalandlanguagesettings.md
  api-reference/beta/resources/subscription.md
  api-reference/beta/resources/unifiedrolepermission.md
  api-reference/beta/resources/user.md
  api-reference/v1.0/api/subscription-delete.md
  api-reference/v1.0/api/subscription-get.md
  api-reference/v1.0/api/subscription-post-subscriptions.md
  api-reference/v1.0/api/subscription-update.md
  api-reference/v1.0/api/user-list.md
  api-reference/v1.0/resources/application.md
  api-reference/v1.0/resources/user.md
  api-reference/v1.0/resources/users.md
  changelog/Microsoft.PrintService.json
  concepts/changelog.md
  concepts/permissions-reference.md
  concepts/toc.yml
  concepts/universal-print-webhook-notifications.md
  concepts/webhooks.md
Labels: internal

#11354 Update externalconnection-delete.md
  api-reference/beta/api/externalconnection-delete.md
Labels: external, review requested

#11395 Update teamsappinstallation.md
  api-reference/beta/resources/teamsappinstallation.md
Labels: external

#11384 Update participant.md
  api-reference/beta/resources/participant.md
  api-reference/v1.0/resources/participant.md
Labels: external, ready to merge

#11380 Update application-proxy-configure-api.md
  concepts/application-proxy-configure-api.md
Labels: external, ready to merge

#11398 Merge to publish.
  api-reference/beta/api/device-list-usagerights.md
  api-reference/beta/api/user-list-usagerights.md
  api-reference/beta/resources/device.md
  api-reference/beta/resources/usageright.md
  api-reference/beta/resources/user.md
  api-reference/beta/toc.yml
  changelog/Microsoft.DirectoryServices.json
Labels: internal

#11400 Various fixes.
  api-reference/v1.0/overview.md
Labels: internal

#11407 Update windowshelloforbusinessauthenticationmethod.md
  api-reference/beta/resources/windowshelloforbusinessauthenticationmethod.md
Labels: external

#11393 Sanitize domain addresses
  api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md
  api-reference/beta/api/accessreviewscheduledefinition-create.md
  api-reference/beta/api/accessreviewscheduledefinition-get.md
  api-reference/beta/api/accessreviewscheduledefinition-list.md
  api-reference/beta/api/cloudpconpremisesconnection-update.md
  api-reference/beta/api/governanceroleassignmentrequest-cancel.md
  api-reference/beta/api/governanceroleassignmentrequest-post.md
  api-reference/beta/api/governancerolesetting-get.md
  api-reference/beta/api/governancerolesetting-list.md
  api-reference/beta/api/mailfolder-list-messages.md
  api-reference/beta/api/printershare-list-allowedusers.md
  api-reference/beta/api/printusagesummarybyuser-get.md
  api-reference/beta/api/reportroot-list-dailyprintusagesummariesbyuser.md
  api-reference/beta/api/reportroot-list-monthlyprintusagesummariesbyuser.md
  api-reference/beta/api/sitepage-get.md
  api-reference/beta/api/user-list-messages.md
  api-reference/beta/api/virtualendpoint-post-onpremisesconnections.md
  api-reference/beta/resources/cloudpconpremisesconnection.md
  api-reference/v1.0/api/mailfolder-list-messages.md
  api-reference/v1.0/api/search-query.md
  api-reference/v1.0/api/user-list-messages.md
Labels: internal, ready to merge

#11413 Add permissions info for each operation in a few task-based concept topics.
  concepts/outlook-large-attachments.md
  concepts/outlook-share-messages-folders.md
  concepts/outlook-share-or-delegate-calendar.md
Labels: do not merge, internal

#11415 Fix for invalid changelog json file
  .github/workflows/changelog-validation.yml
  changelog/Manual.NonWorkloadChanges.json
  changelog/Microsoft.AAD.Reporting.json
  changelog/Microsoft.Analytics.json
  changelog/Microsoft.BitLocker.json
  changelog/Microsoft.DirectoryServices.json
  changelog/Microsoft.Exchange.json
  changelog/Microsoft.Intune.json
  changelog/Microsoft.PrintService.json
  changelog/Microsoft.SharePoint.json
  changelog/Microsoft.Skype.Calling.json
Labels: internal, ready to merge

#11420 Adds line click events to mgt-person
  concepts/toolkit/components/person.md
Labels: external

#11409 Remove List & Get endpoints from Groups v1.0
  api-reference/beta/resources/endpoint.md
  api-reference/v1.0/api/endpoint-get.md
  api-reference/v1.0/api/group-list-endpoints.md
  api-reference/v1.0/resources/endpoint.md
  api-reference/v1.0/resources/group.md
  api-reference/v1.0/resources/serviceprincipal.md
  api-reference/v1.0/toc.yml
Labels: internal, ready to merge

#10095 Updating the location of the MGDC toggle for the new Portal
  concepts/data-connect-get-started.md
Labels: internal, ready to merge

#10718 Adding user risk + change password to v1
  api-reference/v1.0/resources/conditionalaccessconditionset.md
  api-reference/v1.0/resources/conditionalaccessgrantcontrols.md
  changelog/Microsoft.IdentityProtectionServices.json
Labels: ready to merge

#11424 Fix conceptual TOC fusion.
  .openpublishing.publish.config.json
Labels: internal

#11423 Update windowshelloforbusinessauthenticationmethod-list.md
  api-reference/beta/api/windowshelloforbusinessauthenticationmethod-list.md
Labels: external

#10807 Adding Graph Explorer documentation
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
  concepts/graph-explorer/graph-explorer-features.md
  concepts/graph-explorer/graph-explorer-overview.md
  concepts/graph-explorer/images/access-token.PNG
  concepts/graph-explorer/images/adaptive-cards.png
  concepts/graph-explorer/images/adding-key-value-pairs.PNG
  concepts/graph-explorer/images/change-theme.PNG
  concepts/graph-explorer/images/code-snippets.PNG
  concepts/graph-explorer/images/expand-collapse-response-preview.PNG
  concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG
  concepts/graph-explorer/images/getting-started.PNG
  concepts/graph-explorer/images/graph-toolkit.PNG
  concepts/graph-explorer/images/link-to-m365-dev-program.PNG
  concepts/graph-explorer/images/making-a-get-request.PNG
  concepts/graph-explorer/images/making-a-non-get-request.PNG
  concepts/graph-explorer/images/making-a-post-request.PNG
  concepts/graph-explorer/images/modify-permissions.PNG
  concepts/graph-explorer/images/request-header.PNG
  concepts/graph-explorer/images/select-permissions.PNG
  concepts/graph-explorer/images/share-query.PNG
  concepts/graph-explorer/images/storing-and-sharing-queries.PNG
  concepts/toc.yml
Labels: changes requested, content review, internal, ready to merge

#11401 Clarified minimum 24-month deprecation period is for GA APIs only.
  concepts/versioning-and-support.md
Labels: internal, ready to merge

#11442 Added auth links per verbatim feedback.
  api-reference/beta/resources/mail-api-overview.md
  api-reference/v1.0/resources/mail-api-overview.md
Labels: internal

#11435 Update app permission for get printer endpoint
  api-reference/beta/api/printdocument-get-file.md
  api-reference/beta/api/printer-get.md
  changelog/Microsoft.PrintService.json
Labels: area: universal print, internal, ready to merge

#11426 id of a WorkbookTableColumn object should be string
  api-reference/beta/api/table-list-columns.md
  api-reference/beta/api/table-post-columns.md
  api-reference/beta/api/tablecolumn-get.md
  api-reference/beta/api/tablecolumn-list.md
  api-reference/beta/api/tablecolumn-update.md
  api-reference/beta/api/tablecolumncollection-add.md
  api-reference/beta/api/tablecolumncollection-itemat.md
  api-reference/beta/resources/workbooktablecolumn.md
  api-reference/v1.0/api/table-list-columns.md
  api-reference/v1.0/api/table-post-columns.md
  api-reference/v1.0/api/tablecolumn-get.md
  api-reference/v1.0/api/tablecolumn-list.md
  api-reference/v1.0/api/tablecolumn-update.md
  api-reference/v1.0/api/tablecolumncollection-add.md
  api-reference/v1.0/api/tablecolumncollection-itemat.md
  api-reference/v1.0/resources/workbooktablecolumn.md
Labels: internal, ready to merge

#11432 Update windowshelloforbusinessauthenticationmethod-get.md
  api-reference/beta/api/windowshelloforbusinessauthenticationmethod-get.md
Labels: external

#11439 Fix typo in line 19
  concepts/group-set-options.md
Labels: external

#11437 Pull the shared language about Teams subscriptions into its own file
  api-reference/beta/api/subscription-delete.md
  api-reference/beta/api/subscription-get.md
  api-reference/beta/api/subscription-post-subscriptions.md
  api-reference/beta/api/subscription-update.md
  api-reference/includes/teams-subscription-notes.md
  api-reference/v1.0/api/subscription-delete.md
  api-reference/v1.0/api/subscription-get.md
  api-reference/v1.0/api/subscription-post-subscriptions.md
  api-reference/v1.0/api/subscription-update.md
Labels: area: teams, internal, ready to merge

#11291 [CloudPC]Add description for CloudPC enum types
  api-reference/beta/resources/cloudpc.md
  api-reference/beta/resources/cloudpcdeviceimage.md
  api-reference/beta/resources/cloudpconpremisesconnection.md
  api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
  api-reference/beta/resources/enums.md
Labels: ready to merge

#11339 education assignments settings graph api docs
  api-reference/beta/api/educationassignmentsettings-get.md
  api-reference/beta/api/educationassignmentsettings-update.md
  api-reference/beta/resources/educationassignmentsettings.md
  api-reference/beta/toc.yml
  changelog/Microsoft.EducationAssignment.json
Labels: area: edu, internal, ready to merge

#11451 Update windowshelloforbusinessauthenticationmethod-delete.md
  api-reference/beta/api/windowshelloforbusinessauthenticationmethod-delete.md
Labels: external

#11411 Update serviceprincipal.md
  api-reference/beta/resources/serviceprincipal.md
Labels: internal, ready to merge

#11174 Adding userRegistrationFeatureSummary.md file to graph docs reference…
  api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md
  api-reference/beta/api/authenticationmethodsroot-usersregisteredbymethod.md
  api-reference/beta/resources/authenticationmethods-usage-insights-overview.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/userregistrationfeaturecount.md
  api-reference/beta/resources/userregistrationfeaturesummary.md
  api-reference/beta/resources/userregistrationmethodcount.md
  api-reference/beta/resources/userregistrationmethodsummary.md
  api-reference/beta/toc.yml
  changelog/Microsoft.AAD.Reporting.json
  concepts/changelog.md
Labels: area: azure/AAD, internal, ready to merge

#11444 Update office-365-connected-services.md
  concepts/office-365-connected-services.md
Labels: external

#11459 Merge to publish.
  api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md
  api-reference/beta/api/authenticationmethodsroot-usersregisteredbymethod.md
  api-reference/beta/api/windowshelloforbusinessauthenticationmethod-delete.md
  api-reference/beta/resources/authenticationmethods-usage-insights-overview.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/serviceprincipal.md
  api-reference/beta/resources/userregistrationfeaturecount.md
  api-reference/beta/resources/userregistrationfeaturesummary.md
  api-reference/beta/resources/userregistrationmethodcount.md
  api-reference/beta/resources/userregistrationmethodsummary.md
  api-reference/beta/toc.yml
  changelog/Microsoft.AAD.Reporting.json
  concepts/changelog.md
  concepts/office-365-connected-services.md
Labels: internal

#11467 Minor typo
  concepts/cloud-communications-concept-overview.md
Labels: external

#11466 Update add-aad-app-registration.md
  concepts/toolkit/get-started/add-aad-app-registration.md
Labels: external

#11458 Room properties fix
  api-reference/beta/api/place-get.md
  api-reference/beta/api/place-list.md
  api-reference/beta/api/place-update.md
  api-reference/beta/includes/snippets/csharp/update-room-csharp-snippets.md
  api-reference/beta/includes/snippets/java/update-room-java-snippets.md
  api-reference/beta/includes/snippets/javascript/update-room-javascript-snippets.md
  api-reference/beta/includes/snippets/objc/update-room-objc-snippets.md
  api-reference/beta/resources/room.md
  api-reference/v1.0/api/place-get.md
  api-reference/v1.0/api/place-list.md
  api-reference/v1.0/api/place-update.md
  api-reference/v1.0/includes/snippets/csharp/update-room-csharp-snippets.md
  api-reference/v1.0/includes/snippets/java/update-room-java-snippets.md
  api-reference/v1.0/includes/snippets/javascript/update-room-javascript-snippets.md
  api-reference/v1.0/includes/snippets/objc/update-room-objc-snippets.md
  api-reference/v1.0/resources/room.md
Labels: internal, ready to merge

#11075 Updating postman collection steps
  concepts/use-postman.md
Labels: internal, ready to merge
