Repository microsoftgraph/microsoft-graph-docs, pull requests merged in 2022-08, with the labels that each got.

#17916 Update settings.md
  api-reference/beta/resources/settings.md
Labels: external

#17915 Update useranalytics.md
  api-reference/beta/resources/useranalytics.md
Labels: external

#17914 Edits in PR 17566
  api-reference/beta/api/browsersharedcookie-get.md
  api-reference/beta/api/browsersharedcookie-update.md
  api-reference/beta/api/browsersite-get.md
  api-reference/beta/api/browsersite-update.md
  api-reference/beta/api/browsersitelist-delete-sharedcookies.md
  api-reference/beta/api/browsersitelist-delete-sites.md
  api-reference/beta/api/browsersitelist-get.md
  api-reference/beta/api/browsersitelist-list-sharedcookies.md
  api-reference/beta/api/browsersitelist-list-sites.md
  api-reference/beta/api/browsersitelist-post-sharedcookies.md
  api-reference/beta/api/browsersitelist-post-sites.md
  api-reference/beta/api/browsersitelist-publish.md
  api-reference/beta/api/browsersitelist-update.md
  api-reference/beta/api/internetexplorermode-delete-sitelists.md
  api-reference/beta/api/internetexplorermode-list-sitelists.md
  api-reference/beta/api/internetexplorermode-post-sitelists.md
  api-reference/beta/resources/browsersharedcookie.md
  api-reference/beta/resources/browsersharedcookiehistory.md
  api-reference/beta/resources/browsersite.md
Labels: external

#17897 Update teamtemplatedefinition.md
  api-reference/beta/resources/teamtemplatedefinition.md
Labels: external

#17879 Update grouplifecyclepolicy-addgroup.md
  api-reference/v1.0/api/grouplifecyclepolicy-addgroup.md
Labels: external

#17878 Update grouplifecyclepolicy-addgroup.md
  api-reference/beta/api/grouplifecyclepolicy-addgroup.md
Labels: external

#17873 Edits in PR 17715
  api-reference/v1.0/resources/listitem.md
  changelog/Microsoft.FileServices.json
Labels: external

#17858 Update chat-list-tabs.md
  api-reference/v1.0/api/chat-list-tabs.md
Labels: external

#17857 Update chat-list-tabs.md
  api-reference/beta/api/chat-list-tabs.md
Labels: external

#17876 Edits in PR 17646
  api-reference/beta/api/educationsubmission-setupresourcesfolder.md
  api-reference/v1.0/api/educationsubmission-setupresourcesfolder.md
Labels: external

#17887 update: Add a new property to mgt-person
  concepts/toolkit/components/person.md
Labels: external, ready to merge

#17855 Edits in PR 17628
  api-reference/beta/api/b2xidentityuserflow-put-apiconnectorconfiguration.md
  api-reference/beta/api/channel-doesuserhaveaccess.md
  api-reference/beta/api/chatmessage-delta.md
  api-reference/beta/api/chatmessage-softdelete.md
  api-reference/beta/api/chatmessage-undosoftdelete.md
  api-reference/beta/api/listitem-list-documentsetversions.md
  api-reference/beta/api/openshift-delete.md
  api-reference/beta/api/openshift-get.md
  api-reference/beta/api/openshift-update.md
  api-reference/beta/api/openshiftchangerequest-get.md
  api-reference/beta/api/opentypeextension-get.md
  api-reference/beta/api/opentypeextension-post-opentypeextension.md
  api-reference/beta/api/printdocument-createuploadsession.md
  api-reference/beta/api/printjob-get.md
  api-reference/beta/api/printjob-redirect.md
  api-reference/beta/api/termstore-term-get.md
  api-reference/beta/api/unifiedroledefinition-delete.md
  api-reference/beta/api/unifiedroledefinition-get.md
  api-reference/beta/api/unifiedroledefinition-update.md
  api-reference/beta/api/userflowlanguagepage-delete.md
  api-reference/v1.0/api/channel-doesuserhaveaccess.md
  api-reference/v1.0/api/channel-post-members.md
  api-reference/v1.0/api/chatmessage-post.md
  api-reference/v1.0/api/opentypeextension-get.md
  api-reference/v1.0/api/unifiedroledefinition-update.md
Labels: external

#17840 Update outlookcategory-get.md
  api-reference/beta/api/outlookcategory-get.md
Labels: external

#17839 Update outlookcategory-get.md
  api-reference/v1.0/api/outlookcategory-get.md
Labels: external

#17807 Update mailfolder-delete.md
  api-reference/beta/api/mailfolder-delete.md
Labels: external

#17806 Update mailfolder-delete.md
  api-reference/v1.0/api/mailfolder-delete.md
Labels: external

#17734 Removed duplicate sentence from Groups use cases
  api-reference/v1.0/resources/groups-overview.md
Labels: external

#17812 Update throttling-subscription-services.md
  includes/throttling-subscription-services.md
Labels: external, ready to merge

#17912 Defining enums as Strings in JSON representation
  api-reference/beta/resources/call.md
  api-reference/v1.0/resources/call.md
Labels: ready to merge, ready for content review

#17906 Minor doc fixes
  api-reference/beta/api/application-addkey.md
  api-reference/beta/api/application-removekey.md
  api-reference/beta/resources/accessreviewinstancedecisionitem.md
  api-reference/v1.0/api/accessreviewstage-list-decisions.md
  api-reference/v1.0/api/application-addkey.md
  api-reference/v1.0/api/application-removekey.md
  api-reference/v1.0/resources/accessreviewinstancedecisionitem.md
  api-reference/v1.0/toc.yml
Labels: area: Azure AD, ready to merge, internal

#17898 replacing instances of ADF with 'Azure Synapse or Azure Data Factory'
  concepts/data-connect-concept-overview.md
  concepts/data-connect-datasets.md
  concepts/data-connect-faq.md
  concepts/data-connect-filtering.md
  concepts/data-connect-pam.md
  concepts/data-connect-policies.md
  concepts/data-connect-quickstart.yml
Labels: ready to merge, internal, content review complete

#17788 [Doc Improvement][Update permissions reference]
  concepts/permissions-reference.md
Labels: ready to merge, internal, content review complete

#17702 Update search-concept-aggregation.md
  concepts/search-concept-aggregation.md
Labels: ready to merge

#17672 Monetization update
  concepts/teams-licenses.md
Labels: area: teams, ready to merge, internal, content review complete

#17654 Adding 3 properties to tenant settings API. New properties requested b O365 Secure Score team
  api-reference/beta/api/tenantadmin-settings-get.md
  api-reference/beta/api/tenantadmin-settings-update.md
  api-reference/beta/resources/tenantadmin-idlesessionsignout.md
  api-reference/beta/resources/tenantadmin-settings.md
  changelog/Microsoft.FileServices.json
Labels: ready to merge, internal, content review complete, schema live

#16264 [Cloud PC]Add external partner settings
  api-reference/beta/api/cloudpcexternalpartnersetting-get.md
  api-reference/beta/api/cloudpcexternalpartnersetting-update.md
  api-reference/beta/api/virtualendpoint-list-externalpartnersettings.md
  api-reference/beta/api/virtualendpoint-post-externalpartnersettings.md
  api-reference/beta/resources/cloudpcexternalpartnersetting.md
  api-reference/beta/resources/virtualendpoint.md
  api-reference/beta/toc.yml
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, internal, content review complete, schema live

#15348 Add Transcript APIs and Resources.
  api-reference/beta/api/calltranscript-get.md
  api-reference/beta/api/onlinemeeting-list-transcripts.md
  api-reference/beta/resources/calltranscript.md
  api-reference/beta/resources/onlinemeeting.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Teams.Core.json
Labels: ready to merge, internal, content review complete

#17924 Update chat-list.md
  api-reference/beta/api/chat-list.md
Labels: external

#17925 Edits in PR 17566
  api-reference/beta/api/browsersharedcookie-update.md
  api-reference/beta/api/browsersite-get.md
  api-reference/beta/api/browsersite-update.md
  api-reference/beta/api/browsersitelist-post-sites.md
  api-reference/beta/api/browsersitelist-publish.md
  api-reference/beta/api/internetexplorermode-post-sitelists.md
  api-reference/beta/resources/browsersharedcookie.md
  api-reference/beta/resources/browsersite.md
  api-reference/beta/resources/browsersitehistory.md
  api-reference/beta/resources/browsersitelist.md
  api-reference/beta/resources/edge.md
  api-reference/beta/resources/internetexplorermode.md
  api-reference/beta/toc.yml
Labels: external

#17926 Update user-findrooms.md
  api-reference/beta/api/user-findrooms.md
Labels: external

#17646 Adding 400 error request-response examples for setupResourceFolder su…
  api-reference/beta/api/educationsubmission-setupresourcesfolder.md
  api-reference/v1.0/api/educationsubmission-setupresourcesfolder.md
Labels: ready to merge, internal, content review complete

#16154 Add Activities related resources and api documentation
  api-reference/beta/api/externalconnectors-externalitem-addactivities.md
  api-reference/beta/resources/enums-externalconnectors.md
  api-reference/beta/resources/externalconnectors-activitysettings.md
  api-reference/beta/resources/externalconnectors-externalactivity.md
  api-reference/beta/resources/externalconnectors-externalactivitybase.md
  api-reference/beta/resources/externalconnectors-externalactivityresult.md
  api-reference/beta/resources/externalconnectors-externalconnection.md
  api-reference/beta/resources/externalconnectors-externalitem.md
  api-reference/beta/resources/externalconnectors-identity.md
  api-reference/beta/resources/externalconnectors-itemidresolver.md
  api-reference/beta/resources/externalconnectors-urlmatchinfo.md
  api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Search.json
Labels: do not merge, ready to merge, internal, content review complete, schema live

#17923 Resolve #17907
  api-reference/beta/api/claimsmappingpolicy-update.md
  api-reference/beta/resources/claimsmappingpolicy.md
  api-reference/v1.0/api/claimsmappingpolicy-update.md
  api-reference/v1.0/resources/claimsmappingpolicy.md
Labels: area: Azure AD, ready to merge

#16957 [Teamwork] Add `orderBy` query option when listing chats
  api-reference/beta/api/chat-list-messages.md
  api-reference/beta/api/chat-list.md
  changelog/Microsoft.Teams.Core.json
Labels: ready to merge, internal, content review complete

#17903 Adding character limits and invalid character for chat patch topic;
  api-reference/beta/api/chat-patch.md
  api-reference/v1.0/api/chat-patch.md
  changelog/Microsoft.Teams.Core.json
Labels: ready to merge, internal, content review complete

#17940 Update mailfolder-get.md
  api-reference/beta/api/mailfolder-get.md
Labels: external

#17939 Update mailfolder-get.md
  api-reference/v1.0/api/mailfolder-get.md
Labels: external

#17936 Edits in PR 17628
  api-reference/beta/api/security-ediscoveryreviewset-delete-queries.md
  api-reference/v1.0/api/security-ediscoveryreviewset-delete-queries.md
  api-reference/v1.0/api/team-get-installedapps.md
Labels: external

#17934 Edits in PR 17566
  api-reference/beta/api/browsersharedcookie-get.md
  api-reference/beta/api/internetexplorermode-post-sitelists.md
  api-reference/beta/resources/browsersharedcookie.md
  api-reference/beta/resources/browsersite.md
  api-reference/beta/resources/browsersitelist.md
  api-reference/beta/resources/edge.md
  api-reference/beta/resources/internetexplorermode.md
  api-reference/beta/toc.yml
Labels: external

#17937 sort properties documentation errors fixed
  api-reference/beta/resources/search-api-overview.md
  api-reference/v1.0/resources/search-api-overview.md
Labels: external

#16896 [Microsoft 365 Lighthouse] - Audit events update
  api-reference/beta/api/managedtenants-auditevent-get.md
Labels: ready to merge, internal, content review complete, area: multi-tenant management

#17808 Updating attacksimulation api's permission
  api-reference/beta/api/attacksimulationroot-list-simulationautomations.md
  api-reference/beta/api/attacksimulationroot-list-simulations.md
  api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md
  api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md
  api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md
  api-reference/beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md
  api-reference/beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md
  api-reference/beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md
  api-reference/beta/api/simulationautomation-list-runs.md
  api-reference/beta/api/simulationreportoverview-get.md
  api-reference/beta/api/usersimulationdetails-list.md
  concepts/permissions-reference.md
Labels: ready to merge, internal, content review complete

#17837 Supporting Application Context for List Chats API in v1.0
  api-reference/beta/api/chat-list.md
  api-reference/v1.0/api/chat-list.md
  changelog/Microsoft.Teams.Core.json
Labels: ready to merge, internal, content review complete

#17922 Fix @odata.type value in recipient field in examples
  api-reference/beta/api/chat-sendactivitynotification.md
  api-reference/beta/api/team-sendactivitynotification.md
  api-reference/v1.0/api/chat-sendactivitynotification.md
  api-reference/v1.0/api/team-sendactivitynotification.md
Labels: ready to merge, internal, content review complete

#17777 Virtual Appointment Graph API Updating with day 1 changes (etag and if-match)
  api-reference/beta/api/virtualappointment-delete.md
  api-reference/beta/api/virtualappointment-get.md
  api-reference/beta/api/virtualappointment-put.md
  api-reference/beta/api/virtualappointment-update.md
  api-reference/beta/resources/virtualappointment.md
Labels: ready to merge, internal, content review complete, schema live

#17932 Split $filter into separate doc + add syntaxes
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
  concepts/filter-query-parameter.md
  concepts/query-parameters.md
  concepts/toc.yml
Labels: area: Azure AD, ready to merge, internal

#17942 Fix changelog sync
  changelog/Microsoft.Teams.Core.json
Labels: ready to merge, internal

#17954 Update mailfolder-list-messagerules.md
  api-reference/v1.0/api/mailfolder-list-messagerules.md
Labels: external

#17953 Update mailfolder-list-messagerules.md
  api-reference/beta/api/mailfolder-list-messagerules.md
Labels: external

#17929 Minor doc fixes
  api-reference/beta/resources/application.md
  api-reference/beta/resources/federatedidentitycredentials-overview.md
  api-reference/beta/toc.yml
  api-reference/v1.0/resources/application.md
  api-reference/v1.0/toc.yml
  concepts/azuread-users-concept-overview.md
  concepts/extensibility-overview.md
  concepts/query-parameters.md
  concepts/search-query-parameter.md
  concepts/throttling.md
  concepts/toc.yml
  concepts/webhooks.md
Labels: area: Azure AD, ready to merge, internal, review feedback addressed

#17935 Remove externalActivityBase
  api-reference/beta/resources/externalconnectors-externalactivity.md
  api-reference/beta/resources/externalconnectors-externalactivitybase.md
  api-reference/beta/resources/externalconnectors-externalactivityresult.md
  api-reference/beta/resources/externalconnectors-externalitem.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Search.json
Labels: ready to merge, internal, content review complete, schema live

#17952 Edits in PR 17674
  concepts/insights-customize-people-insights-privacy.md
  concepts/people-insights-overview.md
  concepts/search-concept-person.md
Labels: external

#17947 Update national clouds article - remove Azure Germany
  concepts/deployments.md
Labels: area: Azure AD, ready to merge, internal

#17948 Fix incorrectly rendered table - subscription throttling limits
  includes/throttling-subscription-services.md
Labels: ready to merge, internal

#17951 Fixed topic and API links in beta TOC.
  api-reference/beta/toc.yml
Labels: ready to merge, internal, content review complete

#17956 Merge to publish.
  api-reference/beta/api/mailfolder-list-messagerules.md
  api-reference/beta/resources/application.md
  api-reference/beta/resources/externalconnectors-externalactivity.md
  api-reference/beta/resources/externalconnectors-externalactivitybase.md
  api-reference/beta/resources/externalconnectors-externalactivityresult.md
  api-reference/beta/resources/externalconnectors-externalitem.md
  api-reference/beta/resources/federatedidentitycredentials-overview.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/mailfolder-list-messagerules.md
  api-reference/v1.0/resources/application.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.Search.json
  changelog/Microsoft.Teams.Core.json
  concepts/azuread-users-concept-overview.md
  concepts/deployments.md
  concepts/extensibility-overview.md
  concepts/query-parameters.md
  concepts/search-query-parameter.md
  concepts/throttling.md
  concepts/toc.yml
  concepts/webhooks.md
  includes/throttling-subscription-services.md
Labels: internal

#17910 Update site-list-permissions.md
  api-reference/v1.0/api/site-list-permissions.md
Labels: do not merge, ready to merge, internal, customer support issue, content review complete

#17945 Add group settings
  api-reference/beta/resources/directorysettingtemplate.md
  api-reference/v1.0/resources/groupsettingtemplate.md
  concepts/group-directory-settings.md
  concepts/toc.yml
Labels: area: Azure AD, area: groups, ready to merge, internal

#17959 Minor doc fixes
  api-reference/beta/api/administrativeunit-get.md
  api-reference/beta/api/directory-list-administrativeunits.md
  api-reference/beta/api/group-get.md
  api-reference/beta/api/group-list.md
  api-reference/beta/api/user-get.md
  api-reference/beta/api/user-list.md
  api-reference/beta/resources/extensionproperty.md
  api-reference/beta/resources/schemaextension.md
  api-reference/v1.0/api/administrativeunit-get.md
  api-reference/v1.0/api/directory-list-administrativeunits.md
  api-reference/v1.0/api/group-get.md
  api-reference/v1.0/api/group-list.md
  api-reference/v1.0/api/group-post-groups.md
  api-reference/v1.0/api/user-get.md
  api-reference/v1.0/api/user-list.md
  api-reference/v1.0/resources/extensionproperty.md
  api-reference/v1.0/resources/schemaextension.md
Labels: area: Azure AD, ready to merge, internal

#17961 attachment doc fixes
  api-reference/beta/api/taskfileattachment-createuploadsession.md
  concepts/todo-attachments.md
Labels: ready to merge, internal

#17536 Adding isAdmin and userType
  api-reference/beta/api/authenticationmethodsroot-list-userregistrationdetails.md
  api-reference/beta/api/userregistrationdetails-get.md
  api-reference/beta/resources/userregistrationdetails.md
  changelog/Microsoft.AAD.Reporting.json
Labels: area: Azure AD, ready to merge, internal, content review complete, schema live

#17964 Merge to publish.
  api-reference/beta/api/administrativeunit-get.md
  api-reference/beta/api/authenticationmethodsroot-list-userregistrationdetails.md
  api-reference/beta/api/directory-list-administrativeunits.md
  api-reference/beta/api/group-get.md
  api-reference/beta/api/group-list.md
  api-reference/beta/api/taskfileattachment-createuploadsession.md
  api-reference/beta/api/user-get.md
  api-reference/beta/api/user-list.md
  api-reference/beta/api/userregistrationdetails-get.md
  api-reference/beta/resources/directorysettingtemplate.md
  api-reference/beta/resources/extensionproperty.md
  api-reference/beta/resources/schemaextension.md
  api-reference/beta/resources/userregistrationdetails.md
  api-reference/v1.0/api/administrativeunit-get.md
  api-reference/v1.0/api/directory-list-administrativeunits.md
  api-reference/v1.0/api/group-get.md
  api-reference/v1.0/api/group-list.md
  api-reference/v1.0/api/group-post-groups.md
  api-reference/v1.0/api/site-list-permissions.md
  api-reference/v1.0/api/user-get.md
  api-reference/v1.0/api/user-list.md
  api-reference/v1.0/resources/extensionproperty.md
  api-reference/v1.0/resources/groupsettingtemplate.md
  api-reference/v1.0/resources/schemaextension.md
  changelog/Microsoft.AAD.Reporting.json
  concepts/group-directory-settings.md
  concepts/toc.yml
  concepts/todo-attachments.md
Labels: internal

#17963 Address inconsistent docs about request size limits.
  api-reference/beta/api/post-post-attachments.md
  api-reference/beta/resources/attachment.md
  api-reference/v1.0/api/post-post-attachments.md
  api-reference/v1.0/resources/attachment.md
  concepts/use-the-api.md
Labels: do not merge, review requested, internal

#17971 Correct permissions required for app role assignments
  api-reference/beta/api/serviceprincipal-post-approleassignedto.md
  api-reference/beta/api/serviceprincipal-post-approleassignments.md
  api-reference/v1.0/api/serviceprincipal-post-approleassignedto.md
  api-reference/v1.0/api/serviceprincipal-post-approleassignments.md
Labels: ready to merge, internal

#17970 "forceChangePasswordNextSignIn" can be set to "true" in B2C user flow
  api-reference/beta/api/user-post-users.md
  api-reference/v1.0/api/user-post-users.md
Labels: external, ready to merge

#17982 Added new APIs through 7/13.
  api-reference/beta/resources/todotask.md
  api-reference/v1.0/resources/todotask.md
  changelog/Microsoft.DirectoryServices.json
  changelog/Microsoft.Teams.Core.json
  concepts/whats-new-overview.md
Labels: internal

#17983 Update what's new topic through 7/13.
  api-reference/beta/resources/todotask.md
  api-reference/v1.0/resources/todotask.md
  changelog/Microsoft.DirectoryServices.json
  changelog/Microsoft.Teams.Core.json
  concepts/whats-new-overview.md
Labels: internal

#17715 Added documentation for promoting document set version apis
  api-reference/beta/resources/documentset.md
  api-reference/v1.0/api/documentsetversion-delete.md
  api-reference/v1.0/api/documentsetversion-get.md
  api-reference/v1.0/api/documentsetversion-restore.md
  api-reference/v1.0/api/listitem-list-documentsetversions.md
  api-reference/v1.0/api/listitem-post-documentsetversions.md
  api-reference/v1.0/resources/documentset.md
  api-reference/v1.0/resources/documentsetversion.md
  api-reference/v1.0/resources/documentsetversionitem.md
  api-reference/v1.0/resources/listitem.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.FileServices.json
Labels: ready to merge, internal, schema live

#17861 Update throttling limits
  concepts/throttling-limits.md
Labels: ready to merge, content review complete

#17987 Update site-post-permissions.md
  api-reference/beta/api/site-post-permissions.md
  api-reference/v1.0/api/site-post-permissions.md
Labels: external, ready to merge

#16634 Update toc.yml
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
Labels: external, ready to merge, conflicting

#17992 Merge to publish.
  api-reference/beta/api/site-post-permissions.md
  api-reference/beta/resources/documentset.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/documentsetversion-delete.md
  api-reference/v1.0/api/documentsetversion-get.md
  api-reference/v1.0/api/documentsetversion-restore.md
  api-reference/v1.0/api/listitem-list-documentsetversions.md
  api-reference/v1.0/api/listitem-post-documentsetversions.md
  api-reference/v1.0/api/site-post-permissions.md
  api-reference/v1.0/resources/documentset.md
  api-reference/v1.0/resources/documentsetversion.md
  api-reference/v1.0/resources/documentsetversionitem.md
  api-reference/v1.0/resources/listitem.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.FileServices.json
  concepts/throttling-limits.md
Labels: internal

#16504 Moving place type workspaces to public beta
  api-reference/beta/api/place-get.md
  api-reference/beta/api/place-list.md
  api-reference/beta/api/place-update.md
  api-reference/beta/resources/place.md
  api-reference/beta/resources/roomlist.md
  api-reference/beta/resources/workspace.md
  changelog/Microsoft.Exchange.Places.json
Labels: ready to merge, internal, content review complete, schema live

#16717 Fercobo msft dataset updates
  concepts/data-connect-datasets.md
  concepts/data-connect-faq.md
  concepts/data-connect-pam.md
  includes/data-connect-quickstart-01.md
Labels: ready to merge, internal, content review complete

#17928 Application permission- rectifying for some APIs
  api-reference/beta/api/bookingcustomquestion-get.md
  api-reference/v1.0/api/bookingappointment-delete.md
  api-reference/v1.0/api/bookingbusiness-list.md
  api-reference/v1.0/api/bookingcustomquestion-get.md
Labels: ready to merge, internal, content review complete

#17999 Minor doc fixes
  api-reference/beta/api/directory-deleteditems-delete.md
  api-reference/beta/api/directory-deleteditems-get.md
  api-reference/beta/api/directory-deleteditems-getuserownedobjects.md
  api-reference/beta/api/directory-deleteditems-restore.md
  api-reference/beta/api/x509certificateauthenticationmethodconfiguration-delete.md
  api-reference/beta/api/x509certificateauthenticationmethodconfiguration-get.md
  api-reference/beta/api/x509certificateauthenticationmethodconfiguration-update.md
  api-reference/beta/resources/application.md
  api-reference/beta/resources/directory.md
  api-reference/beta/resources/group.md
  api-reference/beta/resources/x509certificateauthenticationmethodconfiguration.md
  api-reference/beta/resources/x509certificateauthenticationmodeconfiguration.md
  api-reference/beta/resources/x509certificaterule.md
  api-reference/beta/resources/x509certificateuserbinding.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/directory-deleteditems-delete.md
  api-reference/v1.0/api/directory-deleteditems-get.md
  api-reference/v1.0/api/directory-deleteditems-getuserownedobjects.md
  api-reference/v1.0/api/directory-deleteditems-restore.md
  api-reference/v1.0/resources/application.md
  api-reference/v1.0/resources/directory.md
  api-reference/v1.0/resources/group.md
  api-reference/v1.0/resources/user.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.DirectoryServices.json
  concepts/throttling-limits.md
  includes/throttling-identity-and-access.md
  redirects/.openpublishing.redirection.0522.json
Labels: area: Azure AD, ready to merge, internal

#18003 Update insights-customize-people-insights-privacy.md
  concepts/insights-customize-people-insights-privacy.md
Labels: external

#18007 Add threat submissions API, fix description & TOC.
  api-reference/beta/resources/security-threatsubmission.md
  api-reference/beta/toc.yml
  concepts/whats-new-overview.md
Labels: do not merge, internal

#18009 Refresh what's new with debut of threat submission API.
  api-reference/beta/resources/security-threatsubmission.md
  api-reference/beta/toc.yml
  concepts/whats-new-overview.md
Labels: internal

#18013 correct completedDateTime in filterbycurrentuser
  api-reference/v1.0/api/accesspackageassignmentrequest-filterbycurrentuser.md
  api-reference/v1.0/api/entitlementmanagement-list-assignmentrequests.md
  api-reference/v1.0/resources/accesspackageassignmentrequest.md
Labels: area: Azure AD, ready to merge, internal, content review complete

#18015 fixing bug changes
  concepts/data-connect-datasets.md
Labels: ready to merge, internal

#17686 Release teams message in graph beta endpoint
  api-reference/beta/resources/search-api-overview.md
  concepts/search-concept-chat-messages.md
  concepts/toc.yml
Labels: ready to merge, internal, content review complete

#18019 Merge to publish.
  api-reference/beta/resources/search-api-overview.md
  api-reference/v1.0/api/accesspackageassignmentrequest-filterbycurrentuser.md
  api-reference/v1.0/api/entitlementmanagement-list-assignmentrequests.md
  api-reference/v1.0/resources/accesspackageassignmentrequest.md
  concepts/data-connect-datasets.md
  concepts/search-concept-chat-messages.md
  concepts/toc.yml
Labels: internal

#18014 Update resource behavior options
  concepts/group-set-options.md
Labels: area: groups, ready to merge, internal, content review complete

#18022 Retirement of licensing assignment in Azure AD Graph
  concepts/migrate-azure-ad-graph-overview.md
Labels: area: Azure AD, ready to merge, internal

#18025 Minor doc fixes
  api-reference/beta/resources/accessreviewinstancedecisionitem.md
  api-reference/beta/resources/approvalstep.md
  api-reference/v1.0/resources/accessreviewinstancedecisionitem.md
  api-reference/v1.0/resources/approvalstage.md
Labels: area: Azure AD, ready to merge, internal

#18026 Minor fixes to consent requests docs
  api-reference/beta/api/appconsentapprovalroute-list-appconsentrequests.md
  api-reference/beta/api/appconsentrequest-filterByCurrentUser.md
  api-reference/beta/api/appconsentrequest-get.md
  api-reference/beta/api/appconsentrequest-list-userconsentrequests.md
  api-reference/beta/api/userconsentrequest-filterByCurrentUser.md
  api-reference/beta/resources/accessreviewreviewerscope.md
  api-reference/beta/resources/adminconsentrequestpolicy.md
  api-reference/beta/resources/appconsentrequest.md
  api-reference/beta/resources/consentrequests-overview.md
  api-reference/beta/resources/userconsentrequest.md
  api-reference/v1.0/api/appconsentapprovalroute-list-appconsentrequests.md
  api-reference/v1.0/api/appconsentrequest-filterbycurrentuser.md
  api-reference/v1.0/api/appconsentrequest-get.md
  api-reference/v1.0/api/appconsentrequest-list-userconsentrequests.md
  api-reference/v1.0/api/userconsentrequest-filterbycurrentuser.md
  api-reference/v1.0/api/userconsentrequest-get.md
  api-reference/v1.0/resources/accessreviewreviewerscope.md
  api-reference/v1.0/resources/adminconsentrequestpolicy.md
  api-reference/v1.0/resources/appconsentrequest.md
  api-reference/v1.0/resources/consentrequests-overview.md
  api-reference/v1.0/resources/userconsentrequest.md
Labels: ready to merge, internal, area: governance

#17640 signInFrequency beta to v1
  api-reference/v1.0/resources/enums.md
  api-reference/v1.0/resources/signinfrequencysessioncontrol.md
  changelog/Microsoft.IdentityProtectionServices.json
Labels: area: Azure AD, ready to merge, internal, content review complete, schema live

#18034 Refresh what's new topic through July.
  api-reference/beta/toc.yml
  changelog/Microsoft.Bookings.json
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: do not merge, internal

#18035 Refresh what's new topic through early August.
  api-reference/beta/toc.yml
  changelog/Microsoft.Bookings.json
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: internal

#18045 Update cloudpcreviewstatus.md
  api-reference/beta/resources/cloudpcreviewstatus.md
Labels: external

#18046 Update Microsoft.CloudManagedDesktop.json
  changelog/Microsoft.CloudManagedDesktop.json
Labels: external

#18048 Update Microsoft.CloudManagedDesktop.json
  changelog/Microsoft.CloudManagedDesktop.json
Labels: external

#18047 Update cloudpcsupportedregion.md
  api-reference/beta/resources/cloudpcsupportedregion.md
Labels: external

#18050 Update projectrome-historyitem.md
  api-reference/v1.0/resources/projectrome-historyitem.md
Labels: external

#18049 Update projectrome-historyitem.md
  api-reference/beta/resources/projectrome-historyitem.md
Labels: external

#16685 [CloudPC] Add connectivityStatus to CloudPc Entity
  api-reference/beta/api/cloudpc-get.md
  api-reference/beta/api/cloudpc-getcloudpcconnectivityhistory.md
  api-reference/beta/resources/cloudpc.md
  api-reference/beta/resources/cloudpcconnectivityevent.md
  api-reference/beta/resources/cloudpcconnectivityresult.md
  api-reference/beta/resources/cloudpchealthcheckitem.md
  api-reference/beta/toc.yml
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, internal, content review complete, schema live

#17276 Update clouds deployment table, add deployment of airgaped clouds.
  api-reference/beta/resources/report.md
Labels: ready to merge, internal, content review complete

#18011 Update description on toDateTime
  api-reference/beta/api/callrecords-callrecord-getdirectroutingcalls.md
  api-reference/v1.0/api/callrecords-callrecord-getdirectroutingcalls.md
Labels: external, ready to merge

#17010 Add api to get user's Cloud PCs and add apis to operate Cloud PC
  api-reference/beta/api/cloudpc-get.md
  api-reference/beta/api/cloudpc-reboot.md
  api-reference/beta/api/cloudpc-rename.md
  api-reference/beta/api/cloudpc-reprovision.md
  api-reference/beta/api/cloudpc-troubleshoot.md
  api-reference/beta/toc.yml
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, internal, content review complete, schema live

#17407 [CloudPC]Add 3 new onprem connection error codes (516,517,518)
  api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, internal, content review complete, schema live

#17551 [CloudPC]Add enableMemAutoEnroll property
  api-reference/beta/api/cloudpcorganizationsettings-get.md
  api-reference/beta/api/cloudpcorganizationsettings-update.md
  api-reference/beta/resources/cloudpcorganizationsettings.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, internal, content review complete, schema live

#17630 [CloudPC]Add azureStorageContainerName in cloudPcReviewStatus
  api-reference/beta/api/manageddevice-getcloudpcreviewstatus.md
  api-reference/beta/resources/cloudpcreviewstatus.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, internal, content review complete, schema live

#18052 Merge to publish.
  api-reference/beta/api/callrecords-callrecord-getdirectroutingcalls.md
  api-reference/beta/api/cloudpc-get.md
  api-reference/beta/api/cloudpc-getcloudpcconnectivityhistory.md
  api-reference/beta/api/cloudpc-reboot.md
  api-reference/beta/api/cloudpc-rename.md
  api-reference/beta/api/cloudpc-reprovision.md
  api-reference/beta/api/cloudpc-troubleshoot.md
  api-reference/beta/api/cloudpcorganizationsettings-get.md
  api-reference/beta/api/cloudpcorganizationsettings-update.md
  api-reference/beta/api/manageddevice-getcloudpcreviewstatus.md
  api-reference/beta/resources/cloudpc.md
  api-reference/beta/resources/cloudpcconnectivityevent.md
  api-reference/beta/resources/cloudpcconnectivityresult.md
  api-reference/beta/resources/cloudpchealthcheckitem.md
  api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
  api-reference/beta/resources/cloudpcorganizationsettings.md
  api-reference/beta/resources/cloudpcreviewstatus.md
  api-reference/beta/resources/projectrome-historyitem.md
  api-reference/beta/resources/report.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/callrecords-callrecord-getdirectroutingcalls.md
  api-reference/v1.0/resources/projectrome-historyitem.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: internal

#18054 Refresh what's new through mid August.
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
  changelog/Microsoft.StrongAuthenticationAPI.json
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: do not merge, internal

#18055 Refresh what's new through mid August.
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
  changelog/Microsoft.StrongAuthenticationAPI.json
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: internal

#18066 Update teamsappinstallation.md
  api-reference/v1.0/resources/teamsappinstallation.md
Labels: external

#18065 Update teamsappinstallation.md
  api-reference/beta/resources/teamsappinstallation.md
Labels: external

#18064 Edits in PR 17684
  api-reference/beta/api/cloudpc-restore.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: external

#18062 Update cloudpconpremisesconnectionhealthcheck.md
  api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
Labels: external

#18060 Application permissions are not supported
  api-reference/beta/api/accesspackagecatalog-post-customaccesspackageworkflowextensions.md
Labels: external

#18042 Minor doc fixes
  api-reference/beta/api/externalidentitiespolicy-update.md
  api-reference/beta/api/organization-get.md
  api-reference/beta/api/organization-list.md
  api-reference/beta/api/organization-update.md
  api-reference/beta/api/orgcontact-get.md
  api-reference/beta/resources/authenticationmethods-overview.md
  api-reference/beta/resources/externalidentitiespolicy.md
  api-reference/beta/resources/organization.md
  api-reference/v1.0/api/organization-get.md
  api-reference/v1.0/api/organization-list.md
  api-reference/v1.0/api/organization-update.md
  api-reference/v1.0/api/orgcontact-get.md
  api-reference/v1.0/resources/authenticationmethods-overview.md
  api-reference/v1.0/resources/organization.md
  concepts/traverse-the-graph.md
Labels: area: Azure AD, ready to merge, internal

#18069 Merge to publish.
  api-reference/beta/api/accesspackagecatalog-post-customaccesspackageworkflowextensions.md
  api-reference/beta/api/externalidentitiespolicy-update.md
  api-reference/beta/api/organization-get.md
  api-reference/beta/api/organization-list.md
  api-reference/beta/api/organization-update.md
  api-reference/beta/api/orgcontact-get.md
  api-reference/beta/resources/authenticationmethods-overview.md
  api-reference/beta/resources/externalidentitiespolicy.md
  api-reference/beta/resources/organization.md
  api-reference/beta/resources/teamsappinstallation.md
  api-reference/v1.0/api/organization-get.md
  api-reference/v1.0/api/organization-list.md
  api-reference/v1.0/api/organization-update.md
  api-reference/v1.0/api/orgcontact-get.md
  api-reference/v1.0/resources/authenticationmethods-overview.md
  api-reference/v1.0/resources/organization.md
  api-reference/v1.0/resources/teamsappinstallation.md
  concepts/traverse-the-graph.md
Labels: internal

#18074 Edits in PR 15761
  api-reference/beta/api/user-get-mailboxsettings.md
  api-reference/beta/resources/mailboxsettings.md
  api-reference/beta/resources/userpurpose.md
  api-reference/beta/resources/workinghours.md
  api-reference/v1.0/api/user-get-mailboxsettings.md
  api-reference/v1.0/resources/mailboxsettings.md
  api-reference/v1.0/resources/userpurpose.md
  changelog/Microsoft.Exchange.json
Labels: external

#18075 Edits in PR 17684
  api-reference/beta/api/manageddevice-restorecloudpc.md
  api-reference/beta/resources/cloudpc.md
Labels: external

#18076 Update contenttype-ispublished.md
  api-reference/v1.0/api/contenttype-ispublished.md
Labels: external

#18077 Update contenttype-ispublished.md
  api-reference/beta/api/contenttype-ispublished.md
Labels: external

#17824 Fix threat submission example namespace issue
  api-reference/beta/api/security-emailthreatsubmission-get.md
  api-reference/beta/api/security-emailthreatsubmission-list.md
  api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md
  api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md
  api-reference/beta/api/security-filethreatsubmission-get.md
  api-reference/beta/api/security-filethreatsubmission-list.md
  api-reference/beta/api/security-filethreatsubmission-post-filethreats.md
  api-reference/beta/api/security-urlthreatsubmission-get.md
  api-reference/beta/api/security-urlthreatsubmission-list.md
  api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md
Labels: do not merge, ready to merge, internal, content review complete

#14745 Add Security Incidents & Alert_v2 APIs
  api-reference/beta/api/security-alert-get.md
  api-reference/beta/api/security-alert-update.md
  api-reference/beta/api/security-incident-get.md
  api-reference/beta/api/security-incident-update.md
  api-reference/beta/api/security-list-alerts_v2.md
  api-reference/beta/api/security-list-incidents.md
  api-reference/beta/includes/alerts-callout-two-types.md
  api-reference/beta/resources/alert.md
  api-reference/beta/resources/enums-security.md
  api-reference/beta/resources/security-alert.md
  api-reference/beta/resources/security-alertcomment.md
  api-reference/beta/resources/security-alertevidence.md
  api-reference/beta/resources/security-analyzedmessageevidence.md
  api-reference/beta/resources/security-api-overview.md
  api-reference/beta/resources/security-cloudapplicationevidence.md
  api-reference/beta/resources/security-deviceevidence.md
  api-reference/beta/resources/security-emailsender.md
  api-reference/beta/resources/security-filedetails.md
  api-reference/beta/resources/security-fileevidence.md
  api-reference/beta/resources/security-incident.md
  api-reference/beta/resources/security-ipevidence.md
  api-reference/beta/resources/security-loggedonuser.md
  api-reference/beta/resources/security-mailboxevidence.md
  api-reference/beta/resources/security-mailclusterevidence.md
  api-reference/beta/resources/security-oauthapplicationevidence.md
  api-reference/beta/resources/security-processEvidence.md
  api-reference/beta/resources/security-registrykeyevidence.md
  api-reference/beta/resources/security-registryvalueevidence.md
  api-reference/beta/resources/security-securitygroupevidence.md
  api-reference/beta/resources/security-urlevidence.md
  api-reference/beta/resources/security-useraccount.md
  api-reference/beta/resources/security-userevidence.md
  api-reference/beta/resources/security-vmmetadata.md
  api-reference/beta/resources/security.md
  api-reference/beta/toc.yml
  api-reference/v1.0/resources/alert.md
  api-reference/v1.0/resources/security-api-overview.md
  changelog/Microsoft.M365.Defender.json
  concepts/permissions-reference.md
  concepts/security-concept-overview.md
Labels: ready to merge, internal, content review complete, schema live

#18078 Fixes to changelog in 15348
  changelog/Microsoft.Teams.Core.json
Labels: ready to merge, ready for content review, internal

#18083 Fix #18082, #18067
  api-reference/beta/api/directoryobject-getbyids.md
  api-reference/v1.0/api/directoryobject-getbyids.md
  api-reference/v1.0/resources/serviceprincipal.md
Labels: ready to merge, internal

#18086 Update data-connect-faq.md
  concepts/data-connect-faq.md
Labels: ready to merge, internal

#18087 Update data-connect-quickstart-06.md
  includes/data-connect-quickstart-06.md
Labels: ready to merge, internal

#18073 [Doc Bug][Fix-links]
  concepts/teams-concept-overview.md
Labels: ready to merge, internal, content review complete

#17979 U/rimisra/update mgdc faq
  concepts/data-connect-faq.md
  concepts/data-connect-policies.md
Labels: do not merge, ready to merge, internal, content review complete

#18094 Enable #sign-off comment on PRs
  .github/fabricbot.json
Labels: internal

#18029 Update data-connect-quickstart-01.md
  includes/data-connect-quickstart-01.md
Labels: ready to merge, internal, content review complete

#18032 Update data-connect-quickstart-05.md
  includes/data-connect-quickstart-05.md
Labels: ready to merge, internal

#18031 Update data-connect-quickstart-04.md
  includes/data-connect-quickstart-04.md
Labels: ready to merge, internal

#18030 Update data-connect-quickstart-02.md
  includes/data-connect-quickstart-02.md
Labels: ready to merge, internal

#18097 Fixed docs for channelMembershipType enum in v1.0 and beta
  api-reference/beta/api/conversationmember-update.md
  api-reference/beta/resources/channel.md
  api-reference/beta/resources/enums.md
  api-reference/v1.0/resources/channel.md
  api-reference/v1.0/resources/enums.md
Labels: external

#17973 Add redirects for EM
  .openpublishing.publish.config.json
  redirects/.openpublishing.redirection.changedapi.json
Labels: area: Azure AD, do not merge, ready to merge, internal, area: governance

#18092 July drop - All Microsoft Graph permissions GUIDs
  concepts/includes/permissions-ids.md
Labels: area: Azure AD, ready to merge, internal, area: permissions

#18096 Update MGDC tutorial
  concepts/images/data-connect-m365-act-grp.png
  concepts/images/data-connect-m365-cons-apprv-pref.png
  concepts/images/data-connect-m365-cons-apprv.png
  concepts/images/data-connect-m365-mail-sec.png
  includes/data-connect-quickstart-01.md
  includes/data-connect-quickstart-02.md
  includes/data-connect-quickstart-04.md
  includes/data-connect-quickstart-05.md
Labels: ready to merge, internal

#17548 Entitlement Management - Auto-assignment doc update
  api-reference/v1.0/api/accesspackageassignmentpolicy-update.md
  api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md
  api-reference/v1.0/resources/accesspackageassignmentpolicy.md
  api-reference/v1.0/resources/accesspackageautomaticrequestsettings.md
  api-reference/v1.0/resources/attributerulemembers.md
  api-reference/v1.0/resources/subjectset.md
  changelog/Microsoft.IGAELM.json
Labels: ready to merge, internal, content review complete

#18103 Merge to publish.
  .github/fabricbot.json
  .openpublishing.publish.config.json
  api-reference/beta/api/conversationmember-update.md
  api-reference/beta/resources/channel.md
  api-reference/beta/resources/enums.md
  api-reference/v1.0/api/accesspackageassignmentpolicy-update.md
  api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md
  api-reference/v1.0/resources/accesspackageassignmentpolicy.md
  api-reference/v1.0/resources/accesspackageautomaticrequestsettings.md
  api-reference/v1.0/resources/attributerulemembers.md
  api-reference/v1.0/resources/channel.md
  api-reference/v1.0/resources/enums.md
  api-reference/v1.0/resources/subjectset.md
  changelog/Microsoft.IGAELM.json
  concepts/images/data-connect-m365-act-grp.png
  concepts/images/data-connect-m365-cons-apprv-pref.png
  concepts/images/data-connect-m365-cons-apprv.png
  concepts/images/data-connect-m365-mail-sec.png
  concepts/includes/permissions-ids.md
  includes/data-connect-quickstart-01.md
  includes/data-connect-quickstart-02.md
  includes/data-connect-quickstart-04.md
  includes/data-connect-quickstart-05.md
  redirects/.openpublishing.redirection.changedapi.json
Labels: internal

#18023 Update Upper Limit For Sharepoint and ODB Items
  api-reference/beta/resources/search-api-overview.md
  api-reference/v1.0/resources/search-api-overview.md
Labels: ready to merge, internal, content review complete

#18109 Update planner-overview.md
  api-reference/v1.0/resources/planner-overview.md
Labels: external, ready to merge

#18104 Minor doc fixes
  api-reference/beta/api/authentication-list-passwordmethods.md
  api-reference/beta/api/passwordauthenticationmethod-get.md
  api-reference/beta/resources/passwordauthenticationmethod.md
  api-reference/v1.0/api/authenticationmethod-resetpassword.md
  api-reference/v1.0/resources/passwordauthenticationmethod.md
Labels: ready to merge, internal

#18124 Update cloudpconpremisesconnectionhealthcheck.md
  api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
Labels: external

#18137 Revert "Update site-post-permissions.md"
  api-reference/beta/api/site-post-permissions.md
  api-reference/v1.0/api/site-post-permissions.md
Labels: ready to merge, internal

#18139 Update cloudpcauditevent.md
  api-reference/beta/resources/cloudpcauditevent.md
Labels: external

#18133 Edits in PR 18085
  api-reference/beta/api/teamworktag-delete.md
  api-reference/beta/api/teamworktag-post.md
  api-reference/beta/api/teamworktagmember-delete.md
  api-reference/beta/api/teamworktagmember-get.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/teamworktag.md
  api-reference/beta/resources/teamworktagmember.md
  api-reference/v1.0/api/teamworktag-delete.md
  api-reference/v1.0/api/teamworktag-get.md
  api-reference/v1.0/api/teamworktag-list.md
  api-reference/v1.0/api/teamworktag-post.md
  api-reference/v1.0/api/teamworktag-update.md
  api-reference/v1.0/api/teamworktagmember-delete.md
  api-reference/v1.0/api/teamworktagmember-get.md
  api-reference/v1.0/api/teamworktagmember-list.md
  api-reference/v1.0/api/teamworktagmember-post.md
  api-reference/v1.0/resources/enums.md
  api-reference/v1.0/resources/teams-api-overview.md
  api-reference/v1.0/resources/teamworktag.md
Labels: external

#18121 Minor doc fixes
  api-reference/beta/resources/schemaextension.md
  api-reference/v1.0/api/subscription-post-subscriptions.md
  api-reference/v1.0/resources/schemaextension.md
  concepts/includes/azure-ad-graph-migration-scripts/azureadgraph-microsoftgraph-permissions.md
  concepts/includes/azure-ad-graph-migration-scripts/azureadgraphpermissions.md
  concepts/includes/azure-ad-graph-migration-scripts/fetchpermissions-response.md
  concepts/includes/azure-ad-graph-migration-scripts/fetchpermissions.md
  concepts/known-issues.md
  concepts/migrate-azure-ad-graph-configure-permissions.md
Labels: area: Azure AD, ready to merge, internal

#18125 Remove reference to Group.Selected
  concepts/permissions-reference.md
Labels: ready to merge, internal

#18132 Update data-connect-quickstart-03.md
  includes/data-connect-quickstart-03.md
Labels: ready to merge

#18130 Update data-connect-quickstart-04.md
  concepts/images/data-connect-adf-extracted-data-in-blob.png
  includes/data-connect-quickstart-04.md
  includes/data-connect-quickstart-05.md
  includes/data-connect-quickstart-06.md
Labels: ready to merge, internal

#18140 Merge to publish.
  api-reference/beta/api/site-post-permissions.md
  api-reference/beta/resources/cloudpcauditevent.md
  api-reference/beta/resources/schemaextension.md
  api-reference/v1.0/api/site-post-permissions.md
  api-reference/v1.0/api/subscription-post-subscriptions.md
  api-reference/v1.0/resources/schemaextension.md
  concepts/images/data-connect-adf-extracted-data-in-blob.png
  concepts/includes/azure-ad-graph-migration-scripts/azureadgraph-microsoftgraph-permissions.md
  concepts/includes/azure-ad-graph-migration-scripts/azureadgraphpermissions.md
  concepts/includes/azure-ad-graph-migration-scripts/fetchpermissions-response.md
  concepts/includes/azure-ad-graph-migration-scripts/fetchpermissions.md
  concepts/known-issues.md
  concepts/migrate-azure-ad-graph-configure-permissions.md
  concepts/permissions-reference.md
  includes/data-connect-quickstart-03.md
  includes/data-connect-quickstart-04.md
  includes/data-connect-quickstart-05.md
  includes/data-connect-quickstart-06.md
Labels: internal

#17356 Mail api doc updates
  api-reference/beta/api/message-createreply.md
  api-reference/beta/api/message-createreplyall.md
  api-reference/beta/api/message-delta.md
  api-reference/beta/api/message-reply.md
  api-reference/beta/api/message-replyall.md
  api-reference/beta/api/user-sendmail.md
  api-reference/beta/resources/itemattachment.md
  api-reference/beta/resources/referenceattachment.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/message-createreply.md
  api-reference/v1.0/api/message-createreplyall.md
  api-reference/v1.0/api/message-delta.md
  api-reference/v1.0/api/message-reply.md
  api-reference/v1.0/api/message-replyall.md
  api-reference/v1.0/api/user-sendmail.md
  api-reference/v1.0/resources/itemattachment.md
  api-reference/v1.0/resources/referenceattachment.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.Exchange.json
  concepts/delta-query-messages.md
  concepts/outlook-things-to-know-about-send-mail.md
  concepts/toc.yml
Labels: do not merge, internal, content review complete

#17844 Fix: remove permission as not supported.
  api-reference/beta/api/profilephoto-update.md
  api-reference/v1.0/api/profilephoto-get.md
  api-reference/v1.0/api/profilephoto-update.md
Labels: ready to merge, internal, content review complete
