Repository microsoftgraph/microsoft-graph-docs, pull requests merged in 2022-02, with the labels that each got.

#15690 Update cloudpconpremisesconnection-delete.md
  api-reference/beta/api/cloudpconpremisesconnection-delete.md
Labels: external

#15689 Update cloudpconpremisesconnection-runhealthcheck.md
  api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md
Labels: external

#15686 Remove extra space for msgraph-interactive
  api-reference/v1.0/api/appcatalogs-list-teamsapps.md
Labels: external

#15570 Enabling Tags APIs in delegated permissions
  api-reference/beta/api/teamworktag-delete.md
  api-reference/beta/api/teamworktag-get.md
  api-reference/beta/api/teamworktag-list.md
  api-reference/beta/api/teamworktag-post.md
  api-reference/beta/api/teamworktag-update.md
  api-reference/beta/api/teamworktagmember-delete.md
  api-reference/beta/api/teamworktagmember-get.md
  api-reference/beta/api/teamworktagmember-list.md
  api-reference/beta/api/teamworktagmember-post.md
  changelog/Microsoft.Teams.Core.json
  concepts/permissions-reference.md
Labels: ready to merge, content review complete

#15651 remove the incorrect description
  api-reference/beta/resources/serviceannouncementattachment.md
  api-reference/beta/resources/servicehealthissue.md
  api-reference/beta/resources/serviceupdatemessage.md
  api-reference/v1.0/resources/serviceannouncementattachment.md
  api-reference/v1.0/resources/servicehealthissue.md
  api-reference/v1.0/resources/serviceupdatemessage.md
  concepts/images/service-communications-concept-overview-admin-center-windowshealth2.png
  concepts/service-communications-concept-overview.md
Labels: ready to merge, internal, content review complete, schema live

#15692 Update known issues document
  concepts/known-issues.md
Labels: ready to merge, internal, content review complete

#15716 Update termstore-group.md
  api-reference/beta/resources/termstore-group.md
Labels: external

#15715 Update termstore-group.md
  api-reference/v1.0/resources/termstore-group.md
Labels: external

#15515 Update resourceaccess.md
  api-reference/v1.0/resources/resourceaccess.md
Labels: area: Azure AD, external, ready to merge, area: app model, content review complete, review feedback addressed

#15545 Updating billing references in FAQ and Policies docs
  concepts/data-connect-faq.md
  concepts/data-connect-policies.md
Labels: ready to merge, internal, content review complete

#15710 Minor doc fixes
  api-reference/beta/resources/recurrencerange.md
  api-reference/beta/resources/signin.md
  api-reference/v1.0/resources/recurrencerange.md
  api-reference/v1.0/resources/signin.md
Labels: area: Azure AD, ready to merge, internal

#15649 Patch 9
  api-reference/beta/resources/serviceplaninfo.md
  api-reference/v1.0/resources/serviceplaninfo.md
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, external, ready to merge, content review complete

#15730 Update schedule-list-shifts.md
  api-reference/beta/api/schedule-list-shifts.md
Labels: external

#15729 Update schedule-list-shifts.md
  api-reference/v1.0/api/schedule-list-shifts.md
Labels: external

#15629 Update toc.yml
  api-reference/v1.0/toc.yml
Labels: external

#15635 Update toc.yml
  api-reference/beta/toc.yml
Labels: external

#15410 Add write throttling limits per app signInAudience
  concepts/throttling.md
Labels: area: Azure AD, ready to merge, internal

#15523 Remove known issue because it's by design
  api-reference/beta/api/user-get.md
  api-reference/v1.0/api/user-get.md
  concepts/known-issues.md
Labels: area: Azure AD, awaiting internal response, ready to merge, internal

#15720 Minor doc fixes
  api-reference/beta/api/user-update.md
  api-reference/beta/resources/user.md
  api-reference/v1.0/api/serviceprincipal-list-homerealmdiscoverypolicies.md
  api-reference/v1.0/api/user-update.md
  api-reference/v1.0/resources/user.md
Labels: area: Azure AD, ready to merge, internal

#15743 Update meetingregistration-post.md
  api-reference/beta/api/meetingregistration-post.md
Labels: external

#15742 Update resulttemplate.md
  api-reference/beta/resources/resulttemplate.md
Labels: external

#15713 verifiedPublisher in examples
  api-reference/beta/api/serviceprincipal-get.md
  api-reference/v1.0/api/application-get.md
  api-reference/v1.0/api/serviceprincipal-get.md
Labels: ready to merge, internal, content review complete

#15714 Fix broken links to relative pages for more info
  concepts/information-protection-overview.md
Labels: ready to merge, internal

#15718 [Azure AD] Read permission scopes for custom security attributes
  api-reference/beta/api/allowedvalue-get.md
  api-reference/beta/api/attributeset-get.md
  api-reference/beta/api/customsecurityattributedefinition-get.md
  api-reference/beta/api/customsecurityattributedefinition-list-allowedvalues.md
  api-reference/beta/api/directory-list-attributesets.md
  api-reference/beta/api/directory-list-customsecurityattributedefinitions.md
  api-reference/beta/api/serviceprincipal-get.md
  api-reference/beta/api/user-get.md
  changelog/Microsoft.DirectoryServices.json
  concepts/permissions-reference.md
Labels: area: Azure AD, ready to merge, internal, content review complete

#15733 Minor doc fixes
  api-reference/beta/resources/extensionproperty.md
  api-reference/v1.0/resources/extensionproperty.md
  concepts/deployments.md
  concepts/known-issues.md
Labels: area: Azure AD, ready to merge, internal

#15744 Merge to publish.
  api-reference/beta/api/allowedvalue-get.md
  api-reference/beta/api/attributeset-get.md
  api-reference/beta/api/customsecurityattributedefinition-get.md
  api-reference/beta/api/customsecurityattributedefinition-list-allowedvalues.md
  api-reference/beta/api/directory-list-attributesets.md
  api-reference/beta/api/directory-list-customsecurityattributedefinitions.md
  api-reference/beta/api/meetingregistration-post.md
  api-reference/beta/api/serviceprincipal-get.md
  api-reference/beta/api/user-get.md
  api-reference/beta/resources/extensionproperty.md
  api-reference/beta/resources/resulttemplate.md
  api-reference/v1.0/api/application-get.md
  api-reference/v1.0/api/serviceprincipal-get.md
  api-reference/v1.0/resources/extensionproperty.md
  changelog/Microsoft.DirectoryServices.json
  concepts/deployments.md
  concepts/information-protection-overview.md
  concepts/known-issues.md
  concepts/permissions-reference.md
Labels: internal

#15528 [Azure ABAC] Custom security attribute with allowed values
  api-reference/beta/api/customsecurityattributedefinition-update.md
  api-reference/beta/api/directory-post-customsecurityattributedefinitions.md
Labels: area: Azure AD, ready to merge, internal, content review complete

#15748 update paths for EM articles
  api-reference/beta/api/accesspackage-list-accesspackagesincompatiblewith.md
  api-reference/beta/api/accesspackage-list-incompatibleaccesspackages.md
  api-reference/beta/api/accesspackage-list-incompatiblegroups.md
  api-reference/beta/api/accesspackageassignmentrequest-reprocess.md
  api-reference/v1.0/api/accesspackagecatalog-update.md
Labels: area: Azure AD, ready to merge, internal, content review complete

#15750 Minor doc fixes
  api-reference/beta/api/directoryobject-checkmembergroups.md
  api-reference/beta/api/directoryobject-checkmemberobjects.md
  api-reference/beta/api/directoryobject-getmembergroups.md
  api-reference/beta/api/directoryobject-getmemberobjects.md
  api-reference/beta/api/user-update.md
  api-reference/beta/resources/licenseAssignmentState.md
  api-reference/beta/resources/user.md
  api-reference/v1.0/api/directoryobject-checkmembergroups.md
  api-reference/v1.0/api/directoryobject-checkmemberobjects.md
  api-reference/v1.0/api/directoryobject-getmembergroups.md
  api-reference/v1.0/api/directoryobject-getmemberobjects.md
  api-reference/v1.0/api/user-update.md
  api-reference/v1.0/resources/licenseassignmentstate.md
  api-reference/v1.0/resources/user.md
Labels: area: Azure AD, ready to merge, internal

#15755 Clarify which chatMessage webhooks will be monetized
  api-reference/beta/api/channel-getallmessages.md
  api-reference/beta/api/chats-getallmessages.md
  api-reference/includes/teams-subscription-notes.md
  api-reference/v1.0/api/channel-getallmessages.md
  api-reference/v1.0/api/chats-getallmessages.md
Labels: ready to merge, internal

#15524 Add Certificate Based Authentication APIs, resources, and changelog
  api-reference/beta/api/x509certificateauthenticationmethodconfiguration-delete.md
  api-reference/beta/api/x509certificateauthenticationmethodconfiguration-get.md
  api-reference/beta/api/x509certificateauthenticationmethodconfiguration-update.md
  api-reference/beta/resources/authenticationmethodspolicies-overview.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/x509certificateauthenticationmethodconfiguration.md
  api-reference/beta/resources/x509certificateauthenticationmodeconfiguration.md
  api-reference/beta/resources/x509certificaterule.md
  api-reference/beta/resources/x509certificateuserbinding.md
  api-reference/beta/toc.yml
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, ready to merge, internal, content review complete, schema live

#15756 Merge to publish.
  api-reference/beta/api/accesspackage-list-accesspackagesincompatiblewith.md
  api-reference/beta/api/accesspackage-list-incompatibleaccesspackages.md
  api-reference/beta/api/accesspackage-list-incompatiblegroups.md
  api-reference/beta/api/accesspackageassignmentrequest-reprocess.md
  api-reference/beta/api/channel-getallmessages.md
  api-reference/beta/api/chats-getallmessages.md
  api-reference/beta/api/customsecurityattributedefinition-update.md
  api-reference/beta/api/directory-post-customsecurityattributedefinitions.md
  api-reference/beta/api/directoryobject-checkmembergroups.md
  api-reference/beta/api/directoryobject-checkmemberobjects.md
  api-reference/beta/api/directoryobject-getmembergroups.md
  api-reference/beta/api/directoryobject-getmemberobjects.md
  api-reference/beta/api/user-update.md
  api-reference/beta/api/x509certificateauthenticationmethodconfiguration-delete.md
  api-reference/beta/api/x509certificateauthenticationmethodconfiguration-get.md
  api-reference/beta/api/x509certificateauthenticationmethodconfiguration-update.md
  api-reference/beta/resources/authenticationmethodspolicies-overview.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/licenseAssignmentState.md
  api-reference/beta/resources/user.md
  api-reference/beta/resources/x509certificateauthenticationmethodconfiguration.md
  api-reference/beta/resources/x509certificateauthenticationmodeconfiguration.md
  api-reference/beta/resources/x509certificaterule.md
  api-reference/beta/resources/x509certificateuserbinding.md
  api-reference/beta/toc.yml
  api-reference/includes/teams-subscription-notes.md
  api-reference/v1.0/api/accesspackagecatalog-update.md
  api-reference/v1.0/api/channel-getallmessages.md
  api-reference/v1.0/api/chats-getallmessages.md
  api-reference/v1.0/api/directoryobject-checkmembergroups.md
  api-reference/v1.0/api/directoryobject-checkmemberobjects.md
  api-reference/v1.0/api/directoryobject-getmembergroups.md
  api-reference/v1.0/api/directoryobject-getmemberobjects.md
  api-reference/v1.0/api/user-update.md
  api-reference/v1.0/resources/licenseassignmentstate.md
  api-reference/v1.0/resources/user.md
  changelog/Microsoft.DirectoryServices.json
Labels: internal

#13821 XTAP API doc set creation
  api-reference/beta/api/crosstenantaccesspolicy-get.md
  api-reference/beta/api/crosstenantaccesspolicy-list-partners.md
  api-reference/beta/api/crosstenantaccesspolicy-post-partners.md
  api-reference/beta/api/crosstenantaccesspolicy-update.md
  api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md
  api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md
  api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md
  api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md
  api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md
  api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md
  api-reference/beta/resources/crosstenantaccesspolicy-overview.md
  api-reference/beta/resources/crosstenantaccesspolicy.md
  api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md
  api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md
  api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md
  api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md
  api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md
  api-reference/beta/resources/crosstenantaccesspolicytarget.md
  api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/policyroot.md
  api-reference/beta/resources/tenantrelationshipaccesspolicybase.md
  api-reference/beta/toc.yml
  changelog/Microsoft.DirectoryServices.json
  concepts/permissions-reference.md
Labels: area: Azure AD, ready to merge, content review complete, review feedback addressed

#15768 Merge to publish (OOB).
  api-reference/beta/api/crosstenantaccesspolicy-get.md
  api-reference/beta/api/crosstenantaccesspolicy-list-partners.md
  api-reference/beta/api/crosstenantaccesspolicy-post-partners.md
  api-reference/beta/api/crosstenantaccesspolicy-update.md
  api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md
  api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md
  api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md
  api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md
  api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md
  api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md
  api-reference/beta/resources/crosstenantaccesspolicy-overview.md
  api-reference/beta/resources/crosstenantaccesspolicy.md
  api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md
  api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md
  api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md
  api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md
  api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md
  api-reference/beta/resources/crosstenantaccesspolicytarget.md
  api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/policyroot.md
  api-reference/beta/resources/tenantrelationshipaccesspolicybase.md
  api-reference/beta/toc.yml
  changelog/Microsoft.DirectoryServices.json
  concepts/permissions-reference.md
Labels: internal

#15773 Update dynamics-customer-get.md
  api-reference/beta/api/dynamics-customer-get.md
Labels: external

#15385 New concept doc to explain how to build notificationChannelurl
  api-reference/beta/api/educationassignment-update.md
  api-reference/beta/api/educationassignmentdefaults-update.md
  api-reference/v1.0/api/educationassignment-update.md
  api-reference/v1.0/api/educationassignmentdefaults-update.md
  concepts/education-build-notificationchannelurl.md
  concepts/images/notificationchannel-channel.png
  concepts/images/notificationchannel-team.png
  concepts/toc.yml
Labels: ready to merge, internal, content review complete, schema live, review feedback addressed

#15759 Fixing URLs in documentation
  api-reference/beta/api/driveitem-copy.md
  api-reference/beta/api/driveitem-createuploadsession.md
  api-reference/beta/api/educationassignment-delta.md
  api-reference/beta/api/tasklist-delete.md
  api-reference/beta/api/userinsightssettings-get.md
  api-reference/v1.0/api/driveitem-copy.md
Labels: ready to merge, internal, content review complete

#15762 URL correction for termstore APIs
  api-reference/v1.0/api/termstore-group-list-sets.md
  api-reference/v1.0/api/termstore-relation-post.md
Labels: ready to merge, internal, content review complete

#15652 GA online meeting details in chat
  api-reference/v1.0/api/chat-get.md
  api-reference/v1.0/resources/chat.md
  api-reference/v1.0/resources/teamworkonlinemeetinginfo.md
  changelog/Microsoft.Teams.GraphSvc.json
Labels: ready to merge, content review complete

#15770 Added section for Design considerations
  api-reference/beta/resources/federatedidentitycredentials-overview.md
Labels: area: Azure AD, ready to merge, internal

#15752 EM beta: make adding an app as resource more discoverable
  api-reference/beta/api/entitlementmanagement-post-accesspackageresourcerequests.md
  api-reference/beta/resources/accesspackagemultiplechoicequestion.md
  api-reference/beta/resources/accesspackagequestion.md
  api-reference/beta/resources/accesspackageresource.md
  api-reference/beta/resources/accesspackageresourceattribute.md
  api-reference/beta/resources/accesspackageresourceattributedestination.md
  api-reference/beta/resources/accesspackageresourceattributequestion.md
  api-reference/beta/resources/accesspackageresourceattributesource.md
  api-reference/beta/resources/accesspackageresourcerequest.md
  api-reference/beta/resources/accesspackagetextinputquestion.md
  api-reference/beta/resources/entitlementmanagement-overview.md
Labels: area: Azure AD, ready to merge, internal, content review complete

#15760 Update sitepage-get.md
  api-reference/beta/api/sitepage-get.md
Labels: external

#15790 Merge to publish.
  api-reference/beta/api/entitlementmanagement-post-accesspackageresourcerequests.md
  api-reference/beta/api/sitepage-get.md
  api-reference/beta/resources/accesspackagemultiplechoicequestion.md
  api-reference/beta/resources/accesspackagequestion.md
  api-reference/beta/resources/accesspackageresource.md
  api-reference/beta/resources/accesspackageresourceattribute.md
  api-reference/beta/resources/accesspackageresourceattributedestination.md
  api-reference/beta/resources/accesspackageresourceattributequestion.md
  api-reference/beta/resources/accesspackageresourceattributesource.md
  api-reference/beta/resources/accesspackageresourcerequest.md
  api-reference/beta/resources/accesspackagetextinputquestion.md
  api-reference/beta/resources/entitlementmanagement-overview.md
  api-reference/beta/resources/federatedidentitycredentials-overview.md
Labels: internal

#15805 Update team.md
  api-reference/v1.0/resources/team.md
Labels: external

#15804 Update team.md
  api-reference/beta/resources/team.md
Labels: external

#15803 Update attacksimulationroot.md
  api-reference/beta/resources/attacksimulationroot.md
Labels: external

#15101 second draft commit to ebasseri fork
  api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md
  api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md
  api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md
  api-reference/beta/api/riskyserviceprincipal-dismiss.md
  api-reference/beta/api/riskyserviceprincipal-get.md
  api-reference/beta/api/riskyserviceprincipal-list-history.md
  api-reference/beta/api/serviceprincipalriskdetection-get.md
  api-reference/beta/resources/conditionalaccessconditionset.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/identityprotection-overview.md
  api-reference/beta/resources/identityprotectionroot.md
  api-reference/beta/resources/riskserviceprincipalactivity.md
  api-reference/beta/resources/riskyserviceprincipal.md
  api-reference/beta/resources/riskyserviceprincipalhistoryitem.md
  api-reference/beta/resources/serviceprincipalriskdetection.md
  api-reference/beta/toc.yml
  changelog/Microsoft.IdentityProtectionServices.json
  concepts/permissions-reference.md
Labels: area: Azure AD, ready to merge, internal, content review complete

#15660 Update conditionalaccessplatforms.md
  api-reference/beta/resources/conditionalaccessplatforms.md
  changelog/Microsoft.IdentityProtectionServices.json
Labels: area: Azure AD, do not merge, ready to merge, internal, content review complete

#15763 Minor doc fixes
  api-reference/beta/api/accessreviewhistorydefinition-get.md
  api-reference/beta/api/accessreviewhistorydefinition-list-instances.md
  api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md
  api-reference/beta/resources/accessreviewhistorydefinition.md
  api-reference/beta/resources/accessreviewhistoryinstance.md
  api-reference/beta/resources/accessreviewsv2-overview.md
  api-reference/beta/resources/conditionalaccessplatforms.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/federatedidentitycredentials-overview.md
  api-reference/beta/resources/homerealmdiscoverypolicy.md
  api-reference/beta/resources/keycredential.md
  api-reference/beta/resources/serviceprincipal.md
  api-reference/v1.0/resources/homerealmdiscoverypolicy.md
  api-reference/v1.0/resources/keycredential.md
  concepts/group-set-options.md
  concepts/toc.yml
Labels: area: Azure AD, ready to merge, internal

#15785 EM beta app permission update to POST resourcerequest
  api-reference/beta/api/accesspackageresourceenvironment-get.md
  api-reference/beta/api/entitlementmanagement-list-accesspackageresourceenvironment.md
  api-reference/beta/api/entitlementmanagement-post-accesspackageresourcerequests.md
  api-reference/beta/resources/accesspackageresource.md
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, ready to merge, internal, content review complete

#15831 Update site-get.md
  api-reference/v1.0/api/site-get.md
Labels: external

#15830 Update site-get.md
  api-reference/beta/api/site-get.md
Labels: external

#15828 Update onenoteresource.md
  api-reference/beta/resources/onenoteresource.md
Labels: external

#15003 New branding properties
  api-reference/beta/api/organizationalbranding-get.md
  api-reference/beta/api/organizationalbranding-list-localizations.md
  api-reference/beta/api/organizationalbranding-post-localizations.md
  api-reference/beta/api/organizationalbranding-update.md
  api-reference/beta/api/organizationalbrandinglocalization-get.md
  api-reference/beta/api/organizationalbrandinglocalization-update.md
  api-reference/beta/resources/loginpagetextvisibilitysettings.md
  api-reference/beta/resources/organizationalbranding.md
  api-reference/beta/resources/organizationalbrandinglocalization.md
  api-reference/beta/resources/organizationalbrandingproperties.md
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, ready to merge, internal, content review complete

#15535 Announce search rollout to GCCH
  concepts/deployments.md
Labels: ready to merge, internal

#15811 [Action needed] Fix API URLs for organizationSettings resource
  api-reference/beta/api/cloudpcorganizationsettings-get.md
  api-reference/beta/api/cloudpcorganizationsettings-update.md
Labels: ready to merge, internal, content review complete

#15846 Update educationuser-post-rubrics.md
  api-reference/beta/api/educationuser-post-rubrics.md
Labels: external

#15845 Update educationuser-post-rubrics.md
  api-reference/v1.0/api/educationuser-post-rubrics.md
Labels: external

#15387 Add multi-stage scenarios in Access Review API beta
  api-reference/beta/api/accessreviewinstance-list-stages.md
  api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md
  api-reference/beta/api/accessreviewinstancedecisionitem-get.md
  api-reference/beta/api/accessreviewinstancedecisionitem-update.md
  api-reference/beta/api/accessreviewscheduledefinition-update.md
  api-reference/beta/api/accessreviewset-post-definitions.md
  api-reference/beta/api/accessreviewstage-filterbycurrentuser.md
  api-reference/beta/api/accessreviewstage-get.md
  api-reference/beta/api/accessreviewstage-list-decisions.md
  api-reference/beta/api/accessreviewstage-stop.md
  api-reference/beta/api/accessreviewstage-update.md
  api-reference/beta/resources/accessreviewinstance.md
  api-reference/beta/resources/accessreviewscheduledefinition.md
  api-reference/beta/resources/accessreviewschedulesettings.md
  api-reference/beta/resources/accessreviewstage.md
  api-reference/beta/resources/accessreviewstagesettings.md
  api-reference/beta/resources/enums.md
  api-reference/beta/toc.yml
  changelog/Microsoft.IdentityGovernance.AccessReviews.json
Labels: area: Azure AD, ready to merge, content review complete

#15848 Merge to publish.
  api-reference/beta/api/accessreviewinstance-list-stages.md
  api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md
  api-reference/beta/api/accessreviewinstancedecisionitem-get.md
  api-reference/beta/api/accessreviewinstancedecisionitem-update.md
  api-reference/beta/api/accessreviewscheduledefinition-update.md
  api-reference/beta/api/accessreviewset-post-definitions.md
  api-reference/beta/api/accessreviewstage-filterbycurrentuser.md
  api-reference/beta/api/accessreviewstage-get.md
  api-reference/beta/api/accessreviewstage-list-decisions.md
  api-reference/beta/api/accessreviewstage-stop.md
  api-reference/beta/api/accessreviewstage-update.md
  api-reference/beta/api/educationuser-post-rubrics.md
  api-reference/beta/resources/accessreviewinstance.md
  api-reference/beta/resources/accessreviewscheduledefinition.md
  api-reference/beta/resources/accessreviewschedulesettings.md
  api-reference/beta/resources/accessreviewstage.md
  api-reference/beta/resources/accessreviewstagesettings.md
  api-reference/beta/resources/enums.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/educationuser-post-rubrics.md
  changelog/Microsoft.IdentityGovernance.AccessReviews.json
Labels: internal

#15872 Update list.md
  api-reference/v1.0/resources/list.md
Labels: external

#15871 Update list.md
  api-reference/beta/resources/list.md
Labels: external

#15843 EM assignment request fix property name inconsistency completedDateTime
  api-reference/v1.0/api/accesspackageassignmentrequest-get.md
  api-reference/v1.0/api/entitlementmanagement-list-assignmentrequests.md
  api-reference/v1.0/resources/accesspackageassignmentrequest.md
Labels: area: Azure AD, ready to merge, internal, content review complete

#15887 Update columndefinition-get.md
  api-reference/beta/api/columndefinition-get.md
Labels: external

#15886 Update columndefinition-get.md
  api-reference/v1.0/api/columndefinition-get.md
Labels: external

#15888 Minor fixes on participant invite and stop hold music docs
  api-reference/beta/api/participant-invite.md
  api-reference/beta/api/participant-stopholdmusic.md
  api-reference/v1.0/api/participant-invite.md
  api-reference/v1.0/api/participant-stopholdmusic.md
Labels: internal

#15416 Add Snapshots relationship to cloudpc virtualendpoint
  api-reference/beta/api/cloudpcsnapshot-get.md
  api-reference/beta/api/virtualendpoint-list-snapshots.md
  api-reference/beta/resources/cloudpcsnapshot.md
  api-reference/beta/resources/virtualendpoint.md
  api-reference/beta/toc.yml
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, internal, content review complete, schema live

#14685 [Azure AD roles] Devices In AU support [beta]
  api-reference/beta/api/administrativeunit-delete-members.md
  api-reference/beta/api/administrativeunit-get-members.md
  api-reference/beta/api/administrativeunit-list-members.md
  api-reference/beta/api/administrativeunit-post-members.md
  api-reference/beta/api/device-list-memberof.md
  api-reference/beta/resources/administrativeunit.md
  api-reference/beta/resources/device.md
  api-reference/beta/toc.yml
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, ready to merge, internal, content review complete, schema live

#15883 Clean up delta query for users, groups; Add note about DB consistency for users/groups
  api-reference/beta/api/serviceprincipal-list-approleassignedto.md
  api-reference/beta/api/serviceprincipal-list-approleassignments.md
  api-reference/v1.0/api/group-get.md
  api-reference/v1.0/api/group-list.md
  api-reference/v1.0/api/serviceprincipal-list-approleassignedto.md
  api-reference/v1.0/api/serviceprincipal-list-approleassignments.md
  api-reference/v1.0/api/user-get.md
  api-reference/v1.0/api/user-list.md
  concepts/delta-query-groups.md
  concepts/delta-query-overview.md
  concepts/delta-query-users.md
Labels: area: Azure AD, ready to merge, internal

#15884 Resolves #15802 - Remove code snippets, resolve snippet name conflict
  api-reference/beta/api/termstore-group-get.md
  api-reference/v1.0/api/group-get.md
  api-reference/v1.0/api/termstore-group-get.md
Labels: area: Azure AD, ready to merge, internal

#15885 Resolves #15877 - change response code to avoid confusion due to known issue
  api-reference/beta/api/user-revokesigninsessions.md
  api-reference/v1.0/api/user-revokesigninsessions.md
Labels: area: Azure AD, ready to merge, internal

#15904 Update search-api-overview.md
  api-reference/beta/resources/search-api-overview.md
Labels: external

#15903 Update enums.md
  api-reference/beta/resources/enums.md
Labels: external

#15902 Update search-api-overview.md
  api-reference/v1.0/resources/search-api-overview.md
Labels: external

#15901 Update resulttemplate.md
  api-reference/v1.0/resources/resulttemplate.md
Labels: external

#15900 Update enums.md
  api-reference/v1.0/resources/enums.md
Labels: external

#15563 Permission reference update
  concepts/permissions-reference.md
Labels: ready to merge, internal, content review complete, area: multi-tenant management

#15801 Added SDK examples of AAD advanced queries
  concepts/aad-advanced-queries.md
  concepts/powershell/get-started.md
  concepts/powershell/navigating.md
  concepts/sdks/create-requests.md
  includes/aad-advanced-queries-note.md
Labels: area: Azure AD, ready to merge, internal, area: SDKs

#15894 BitLocker API docs - Add a required header
  api-reference/beta/api/bitlocker-list-recoverykeys.md
  api-reference/beta/api/bitlockerrecoverykey-get.md
  api-reference/v1.0/api/bitlocker-list-recoverykeys.md
  api-reference/v1.0/api/bitlockerrecoverykey-get.md
  changelog/Microsoft.BitLocker.json
Labels: area: Azure AD, ready to merge, internal

#15899 Resolve #15880 - Add note about permission requirements for a service principal calling itself
  api-reference/beta/api/serviceprincipal-get.md
  api-reference/v1.0/api/serviceprincipal-get.md
Labels: area: Azure AD, ready to merge, area: app model, internal

#15851 Added missing & to expand series master event example
  api-reference/beta/api/event-get.md
Labels: external

#15906 Merge to publish.
  api-reference/beta/api/bitlocker-list-recoverykeys.md
  api-reference/beta/api/bitlockerrecoverykey-get.md
  api-reference/beta/api/event-get.md
  api-reference/beta/api/serviceprincipal-get.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/search-api-overview.md
  api-reference/v1.0/api/bitlocker-list-recoverykeys.md
  api-reference/v1.0/api/bitlockerrecoverykey-get.md
  api-reference/v1.0/api/serviceprincipal-get.md
  api-reference/v1.0/resources/enums.md
  api-reference/v1.0/resources/resulttemplate.md
  api-reference/v1.0/resources/search-api-overview.md
  changelog/Microsoft.BitLocker.json
  concepts/aad-advanced-queries.md
  concepts/permissions-reference.md
  concepts/powershell/get-started.md
  concepts/powershell/navigating.md
  concepts/sdks/create-requests.md
  includes/aad-advanced-queries-note.md
Labels: do not merge, internal

#15860 entitlement management beta: address feedback on required collections in an approval stage
  api-reference/beta/resources/approvalstage.md
Labels: area: Azure AD, ready to merge, internal, content review complete

#15568 Exo rich notifications beta
  api-reference/beta/api/subscription-delete.md
  api-reference/beta/api/subscription-get.md
  api-reference/beta/api/subscription-post-subscriptions.md
  api-reference/beta/api/subscription-update.md
  api-reference/beta/resources/webhooks.md
  api-reference/includes/outlook-subscription-notes.md
  api-reference/v1.0/api/subscription-delete.md
  api-reference/v1.0/api/subscription-get.md
  api-reference/v1.0/api/subscription-post-subscriptions.md
  api-reference/v1.0/api/subscription-update.md
  changelog/Microsoft.Exchange.json
  concepts/outlook-change-notifications-overview.md
  concepts/toc.yml
  concepts/webhooks-with-resource-data.md
  includes/outlook-subscription-notes.md
Labels: ready to merge, internal, content review complete

#15908 Adding claims limits
  api-reference/v1.0/resources/claimsmappingpolicy.md
Labels: ready to merge, internal

#15913 Minor doc fixes
  api-reference/beta/resources/claimsmappingpolicy.md
  api-reference/beta/resources/riskdetection.md
  api-reference/beta/toc.yml
  api-reference/v1.0/resources/claimsmappingpolicy.md
  api-reference/v1.0/resources/riskdetection.md
  api-reference/v1.0/toc.yml
Labels: area: Azure AD, ready to merge, internal

#15916 Merge to publish.
  api-reference/beta/api/subscription-delete.md
  api-reference/beta/api/subscription-get.md
  api-reference/beta/api/subscription-post-subscriptions.md
  api-reference/beta/api/subscription-update.md
  api-reference/beta/resources/approvalstage.md
  api-reference/beta/resources/claimsmappingpolicy.md
  api-reference/beta/resources/riskdetection.md
  api-reference/beta/resources/webhooks.md
  api-reference/beta/toc.yml
  api-reference/includes/outlook-subscription-notes.md
  api-reference/v1.0/api/subscription-delete.md
  api-reference/v1.0/api/subscription-get.md
  api-reference/v1.0/api/subscription-post-subscriptions.md
  api-reference/v1.0/api/subscription-update.md
  api-reference/v1.0/resources/claimsmappingpolicy.md
  api-reference/v1.0/resources/riskdetection.md
  api-reference/v1.0/resources/user.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.Exchange.json
  concepts/outlook-change-notifications-overview.md
  concepts/toc.yml
  concepts/webhooks-with-resource-data.md
  includes/outlook-subscription-notes.md
Labels: internal

#15929 User/jaluthra/expose extract sensitivity label
  api-reference/v1.0/api/driveitem-extractsensitivitylabels.md
  api-reference/v1.0/resources/extractsensitivitylabelsresult.md
  api-reference/v1.0/resources/sensitivitylabelassignment.md
Labels: internal

#15943 Update list-create.md
  api-reference/v1.0/api/list-create.md
Labels: external

#15942 Update list-create.md
  api-reference/beta/api/list-create.md
Labels: external

#15944 Add documentation for mgt-peoplepicker disableImages property
  concepts/toolkit/components/people-picker.md
Labels: external

#15826 Windows Updates: Fix sample to use derived and not abstract type
  api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md
Labels: ready to merge, internal, content review complete

#15844 EM improve consistency of property lists of resources in beta
  api-reference/beta/resources/accesspackagecatalog.md
  api-reference/beta/resources/accesspackageresource.md
  api-reference/beta/resources/connectedorganization.md
Labels: area: Azure AD, ready to merge, internal, content review complete

#15867 Adding Conversation Member Role Validation for Tenant Gust User
  api-reference/beta/api/chat-post.md
  api-reference/v1.0/api/chat-post.md
  changelog/Microsoft.Teams.Core.json
Labels: ready to merge, internal, content review complete

#15896 EM: add more description of the prerequisite role and permission requirement for resource onboarding
  api-reference/beta/api/entitlementmanagement-post-accesspackageresourcerequests.md
Labels: area: Azure AD, ready to merge, internal, content review complete

#15918 [Doc Improvement][Update see also for sending activity feed notification and best practices]
  concepts/teams-activity-feed-notifications-best-practices.md
  concepts/teams-send-activityfeednotifications.md
Labels: ready to merge, internal

#15926 Complete PR #15908 - add limits to property descriptions
  api-reference/beta/resources/claimsmappingpolicy.md
  api-reference/v1.0/resources/claimsmappingpolicy.md
Labels: area: Azure AD, ready to merge, internal

#15940 Add missing tabs relationship in chat entity
  api-reference/beta/resources/chat.md
  api-reference/v1.0/resources/chat.md
Labels: ready to merge, internal, content review complete

#15917 Update navigating.md
  concepts/powershell/navigating.md
Labels: external

#15928 Update whats-new-overview.md
  concepts/whats-new-overview.md
Labels: external

#15448 Fix compile error in Java example
  concepts/sdks/paging.md
Labels: external, review requested

#15967 Update outlookuser-post-mastercategories.md
  api-reference/beta/api/outlookuser-post-mastercategories.md
Labels: external

#15966 Update outlookuser-post-mastercategories.md
  api-reference/v1.0/api/outlookuser-post-mastercategories.md
Labels: external

#15897 Add C# and Java examples for Outlook uploads
  concepts/sdks/large-file-upload.md
Labels: ready to merge, internal, content review complete, area: SDKs

#15936 Add documentation for mgt-person person-card property
  concepts/toolkit/components/person-card.md
Labels: external, ready to merge

#15959 Jupetter licensing
  api-reference/beta/api/user-list-licensedetails.md
  api-reference/v1.0/api/user-list-licensedetails.md
Labels: area: Azure AD, ready to merge, internal

#15962 Rename presence.md relationship column to property for beta and v1
  api-reference/beta/resources/presence.md
  api-reference/v1.0/resources/presence.md
Labels: ready to merge, internal

#15960 Jupetter update user
  api-reference/beta/api/user-update.md
  api-reference/v1.0/api/user-update.md
Labels: area: Azure AD, ready to merge, internal

#15934 Add the documentation for the people-picker properties
  concepts/toolkit/components/people-picker.md
Labels: external

#15866 Fix column name in ServiceAnnouncement docs
  api-reference/beta/resources/serviceannouncement.md
  api-reference/v1.0/resources/serviceannouncement.md
Labels: external, do not merge, schema live

#15949 Update outlook-change-notifications-overview.md
  concepts/outlook-change-notifications-overview.md
Labels: internal

#15981 Update bookingappointment-delete.md
  api-reference/beta/api/bookingappointment-delete.md
Labels: external

#15980 Update bookingappointment-delete.md
  api-reference/v1.0/api/bookingappointment-delete.md
Labels: external

#15979 Remove USGov support warning from NamedLocation doc
  api-reference/beta/resources/countrynamedlocation.md
Labels: internal, content review complete

#15458 [Azure AD roles] List transitiveRoleAssignments method
  api-reference/beta/api/rbacapplication-list-transitiveroleassignments.md
  api-reference/beta/resources/rbacapplication.md
  api-reference/beta/resources/unifiedroleassignment.md
  api-reference/beta/toc.yml
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, ready to merge, internal, content review complete

#15869 [MS Graph] [ELM] custom extensions for logic apps api
  api-reference/beta/api/accesspackageassignmentpolicy-get.md
  api-reference/beta/api/accesspackageassignmentpolicy-update.md
  api-reference/beta/api/accesspackageassignmentrequest-get.md
  api-reference/beta/api/accesspackagecatalog-list-customaccesspackageworkflowextensions.md
  api-reference/beta/api/accesspackagecatalog-post-customaccesspackageworkflowextensions.md
  api-reference/beta/api/customaccesspackageworkflowextension-delete.md
  api-reference/beta/api/customaccesspackageworkflowextension-get.md
  api-reference/beta/api/customaccesspackageworkflowextension-update.md
  api-reference/beta/resources/accesspackageassignmentpolicy.md
  api-reference/beta/resources/accesspackageassignmentrequest.md
  api-reference/beta/resources/accesspackagecatalog.md
  api-reference/beta/resources/azureadtokenauthentication.md
  api-reference/beta/resources/customaccesspackageworkflowextension.md
  api-reference/beta/resources/customcalloutextension.md
  api-reference/beta/resources/customextensionauthenticationconfiguration.md
  api-reference/beta/resources/customextensionclientconfiguration.md
  api-reference/beta/resources/customextensionendpointconfiguration.md
  api-reference/beta/resources/customextensionhandler.md
  api-reference/beta/resources/customextensionhandlerinstance.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/logicapptriggerendpointconfiguration.md
  api-reference/beta/toc.yml
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, ready to merge, internal, content review complete

#15784 Go SDK updates
  concepts/sdks/paging.md
  concepts/sdks/sdk-installation.md
Labels: ready to merge, area: sample code, internal, content review complete, area: SDKs

#15824 Access reviews tutorial refresh - Part I
  api-reference/beta/resources/accessreviewsv2-overview.md
  api-reference/v1.0/resources/accessreviewsv2-overview.md
  concepts/accessreviews-overview.md
  concepts/images/tutorial-accessreviews-api/emailnotification.png
  concepts/images/tutorial-accessreviews-api/selfattest.png
  concepts/tutorial-accessreviews-securitygroup.md
Labels: area: Azure AD, ready to merge, internal

#15947 Minor doc fixes
  api-reference/beta/resources/schemaextension.md
  api-reference/v1.0/resources/schemaextension.md
Labels: area: Azure AD, ready to merge, internal

#15974 Minor doc fixes
  api-reference/beta/resources/crosstenantaccesspolicy-overview.md
  api-reference/beta/resources/onpremisesextensionattributes.md
  api-reference/v1.0/resources/onpremisesextensionattributes.md
Labels: area: Azure AD, ready to merge, internal

#15958 Update verbiage on schema update capabilities
  concepts/connecting-external-content-manage-connections.md
Labels: internal, content review complete

#15983 Merge to publish.
  api-reference/beta/api/accesspackageassignmentpolicy-get.md
  api-reference/beta/api/accesspackageassignmentpolicy-update.md
  api-reference/beta/api/accesspackageassignmentrequest-get.md
  api-reference/beta/api/accesspackagecatalog-list-customaccesspackageworkflowextensions.md
  api-reference/beta/api/accesspackagecatalog-post-customaccesspackageworkflowextensions.md
  api-reference/beta/api/bookingappointment-delete.md
  api-reference/beta/api/customaccesspackageworkflowextension-delete.md
  api-reference/beta/api/customaccesspackageworkflowextension-get.md
  api-reference/beta/api/customaccesspackageworkflowextension-update.md
  api-reference/beta/api/rbacapplication-list-transitiveroleassignments.md
  api-reference/beta/resources/accesspackageassignmentpolicy.md
  api-reference/beta/resources/accesspackageassignmentrequest.md
  api-reference/beta/resources/accesspackagecatalog.md
  api-reference/beta/resources/accessreviewsv2-overview.md
  api-reference/beta/resources/azureadtokenauthentication.md
  api-reference/beta/resources/countrynamedlocation.md
  api-reference/beta/resources/crosstenantaccesspolicy-overview.md
  api-reference/beta/resources/customaccesspackageworkflowextension.md
  api-reference/beta/resources/customcalloutextension.md
  api-reference/beta/resources/customextensionauthenticationconfiguration.md
  api-reference/beta/resources/customextensionclientconfiguration.md
  api-reference/beta/resources/customextensionendpointconfiguration.md
  api-reference/beta/resources/customextensionhandler.md
  api-reference/beta/resources/customextensionhandlerinstance.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/logicapptriggerendpointconfiguration.md
  api-reference/beta/resources/onpremisesextensionattributes.md
  api-reference/beta/resources/rbacapplication.md
  api-reference/beta/resources/schemaextension.md
  api-reference/beta/resources/unifiedroleassignment.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/bookingappointment-delete.md
  api-reference/v1.0/resources/accessreviewsv2-overview.md
  api-reference/v1.0/resources/onpremisesextensionattributes.md
  api-reference/v1.0/resources/schemaextension.md
  changelog/Microsoft.DirectoryServices.json
  concepts/accessreviews-overview.md
  concepts/connecting-external-content-manage-connections.md
  concepts/images/tutorial-accessreviews-api/emailnotification.png
  concepts/images/tutorial-accessreviews-api/selfattest.png
  concepts/sdks/paging.md
  concepts/sdks/sdk-installation.md
  concepts/tutorial-accessreviews-securitygroup.md
Labels: do not merge, internal

#15043 [Azure AD roles] Resource namespace and resource action (Preview)
  api-reference/beta/api/rbacapplicationmultiple-list-resourcenamespaces.md
  api-reference/beta/api/unifiedrbacresourceaction-get.md
  api-reference/beta/api/unifiedrbacresourcenamespace-get.md
  api-reference/beta/api/unifiedrbacresourcenamespace-list-resourceactions.md
  api-reference/beta/resources/rbacapplication.md
  api-reference/beta/resources/rbacapplicationmultiple.md
  api-reference/beta/resources/unifiedrbacresourceaction.md
  api-reference/beta/resources/unifiedrbacresourcenamespace.md
  api-reference/beta/toc.yml
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, ready to merge, internal, content review complete, schema live

#15950 [Doc Improvement][Update Presence maximum expiration time]
  api-reference/v1.0/resources/subscription.md
Labels: ready to merge, internal, content review complete

#16003 Refresh what's new.
  api-reference/v1.0/resources/chat.md
  changelog/Microsoft.DirectoryServices.json
  concepts/toc.yml
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: do not merge, internal

#16005 Refresh what's new.
  api-reference/v1.0/resources/chat.md
  changelog/Microsoft.DirectoryServices.json
  concepts/toc.yml
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: internal
