Repository microsoftgraph/microsoft-graph-docs, pull requests merged in 2022-11, with the labels that each got.

#19039 Update educationsynchronizationprofile-post.md
  api-reference/beta/api/educationsynchronizationprofile-post.md
Labels: external

#19037 Take presence out of beta.
  api-reference/beta/resources/subscription.md
Labels: external

#19035 Update driveitem-update.md
  api-reference/v1.0/api/driveitem-update.md
Labels: external

#19034 Update learningcontent.md
  api-reference/beta/resources/learningcontent.md
Labels: external

#19033 Update learningcontent-update.md
  api-reference/beta/api/learningcontent-update.md
Labels: external

#19032 Update plannerroster.md
  api-reference/beta/resources/plannerroster.md
Labels: external

#18418 Entitlement Management - AP move to new catalog
  api-reference/beta/api/accesspackage-movetocatalog.md
  api-reference/beta/resources/accesspackage.md
  api-reference/beta/resources/entitlementmanagement-overview.md
  api-reference/beta/toc.yml
  changelog/Microsoft.IGAELM.json
Labels: area: Azure AD, do not merge, ready to merge, internal, content review complete, schema live

#18906 #ATCP Added list call
  concepts/custom-security-attributes-examples.md
Labels: external, ready to merge, content review complete

#19045 Request code snippets
  api-reference/v1.0/api/authentication-list-methods.md
Labels: area: Azure AD, ready to merge, internal, area: identity

#19044 Request code snippets for open extensions tutorial
  concepts/extensibility-open-users.md
Labels: area: Azure AD, ready to merge

#18958 Adds defaultUsageLocation documentation
  api-reference/beta/api/organization-get.md
  api-reference/beta/api/organization-list.md
  api-reference/beta/resources/organization.md
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, ready to merge, internal, content review complete

#18153 docs: update mgt-login for fluentui update
  concepts/toolkit/components/login.md
  concepts/toolkit/components/person.md
Labels: do not merge, internal, no recent activity, area: toolkit

#19073 Edits in PR 19028
  api-reference/beta/api/chat-sendactivitynotification.md
  api-reference/beta/api/team-sendactivitynotification.md
  api-reference/beta/resources/channelmembersnotificationrecipient.md
  api-reference/beta/resources/chatmembersnotificationrecipient.md
  api-reference/beta/resources/teammembersnotificationrecipient.md
  api-reference/beta/resources/teamworknotificationrecipient.md
  api-reference/v1.0/api/chat-sendactivitynotification.md
  api-reference/v1.0/api/team-sendactivitynotification.md
  api-reference/v1.0/resources/channelmembersnotificationrecipient.md
  api-reference/v1.0/resources/chatmembersnotificationrecipient.md
  api-reference/v1.0/resources/teammembersnotificationrecipient.md
  api-reference/v1.0/resources/teamworknotificationrecipient.md
  changelog/Microsoft.Teams.Core.json
Labels: external

#19076 Update shift.md
  api-reference/beta/resources/shift.md
Labels: external

#19075 Update shift.md
  api-reference/v1.0/resources/shift.md
Labels: external

#19067 feat: update the new CSS properties for the people picker component
  concepts/toolkit/components/people-picker.md
Labels: external

#18053 Add applicationFilter and servicePrincipalFilter property
  api-reference/beta/resources/conditionalaccessapplications.md
  api-reference/beta/resources/conditionalaccessclientapplications.md
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, resolved: awaiting prod deployment, awaiting internal response, ready to merge, internal, content review complete, schema live

#18706 Chentong xiang support collapse
  api-reference/beta/resources/collapseproperty.md
  api-reference/beta/resources/search-api-overview.md
  api-reference/beta/resources/searchrequest.md
  changelog/Microsoft.MicrosoftSearch.json
  concepts/search-concept-collapse.md
  concepts/toc.yml
Labels: ready to merge, internal, Ignite22, content review complete

#19062 Clarity on APIs to see directly assigned vs inherited licenses
  api-reference/beta/resources/licenseAssignmentState.md
  api-reference/beta/resources/user.md
  api-reference/v1.0/resources/licenseassignmentstate.md
  api-reference/v1.0/resources/user.md
Labels: area: Azure AD, ready to merge, internal

#19098 Edits in PR 19068
  api-reference/beta/resources/admin.md
  api-reference/beta/resources/adminwindows.md
  api-reference/beta/resources/adminwindowsupdates.md
  api-reference/beta/resources/windowsupdates-applicablecontent.md
  api-reference/beta/resources/windowsupdates-applicablecontentdevicematch.md
  api-reference/beta/resources/windowsupdates-catalogcontent.md
  api-reference/beta/resources/windowsupdates-catalogentry.md
  api-reference/beta/resources/windowsupdates-compliancechange.md
  api-reference/beta/resources/windowsupdates-compliancechangerule.md
  api-reference/beta/resources/windowsupdates-contentapplicabilitysettings.md
  api-reference/beta/resources/windowsupdates-contentapproval.md
  api-reference/beta/resources/windowsupdates-contentapprovalrule.md
  api-reference/beta/resources/windowsupdates-contentfilter.md
  api-reference/beta/resources/windowsupdates-datedrivenrolloutsettings.md
Labels: external

#19100 Update timeoff.md
  api-reference/beta/resources/timeoff.md
Labels: external

#19099 Update timeoff.md
  api-reference/v1.0/resources/timeoff.md
Labels: external

#19085 Directory objects don't support $skip
  api-reference/beta/api/group-list.md
  api-reference/v1.0/api/group-list.md
  concepts/query-parameters.md
Labels: area: Azure AD, ready to merge, internal, area: query parameters

#19086 Fix snippets request
  concepts/extensibility-open-users.md
Labels: area: Azure AD, ready to merge, internal

#17566 Cloud Site List Management API Docs
  api-reference/beta/api/browsersharedcookie-get.md
  api-reference/beta/api/browsersharedcookie-update.md
  api-reference/beta/api/browsersite-get.md
  api-reference/beta/api/browsersite-update.md
  api-reference/beta/api/browsersitelist-delete-sharedcookies.md
  api-reference/beta/api/browsersitelist-delete-sites.md
  api-reference/beta/api/browsersitelist-get.md
  api-reference/beta/api/browsersitelist-list-sharedcookies.md
  api-reference/beta/api/browsersitelist-list-sites.md
  api-reference/beta/api/browsersitelist-post-sharedcookies.md
  api-reference/beta/api/browsersitelist-post-sites.md
  api-reference/beta/api/browsersitelist-publish.md
  api-reference/beta/api/browsersitelist-update.md
  api-reference/beta/api/internetexplorermode-delete-sitelists.md
  api-reference/beta/api/internetexplorermode-list-sitelists.md
  api-reference/beta/api/internetexplorermode-post-sitelists.md
  api-reference/beta/config/link-validation-config.json
  api-reference/beta/resources/admin.md
  api-reference/beta/resources/browser-edge-api-overview.md
  api-reference/beta/resources/browsersharedcookie.md
  api-reference/beta/resources/browsersharedcookiehistory.md
  api-reference/beta/resources/browsersite.md
  api-reference/beta/resources/browsersitehistory.md
  api-reference/beta/resources/browsersitelist.md
  api-reference/beta/resources/edge.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/internetexplorermode.md
  api-reference/beta/toc.yml
  api-reference/v1.0/config/link-validation-config.json
  changelog/Microsoft.Edge.CloudSiteListManagement.json
  concepts/browser-edge-concept-overview.md
  concepts/images/edge-site-lists.png
  concepts/overview-major-services.md
  concepts/permissions-reference.md
  concepts/toc.yml
Labels: ready to merge, internal, content review complete

#17622 Graph Explorer docs update
  concepts/graph-explorer/graph-explorer-features.md
  concepts/graph-explorer/graph-explorer-overview.md
  concepts/graph-explorer/images/access-token.PNG
  concepts/graph-explorer/images/adaptive-cards-screenshot.png
  concepts/graph-explorer/images/adaptive-cards.png
  concepts/graph-explorer/images/adding-key-value-pairs.PNG
  concepts/graph-explorer/images/change-theme.PNG
  concepts/graph-explorer/images/code-snippets-screenshot.png
  concepts/graph-explorer/images/code-snippets.PNG
  concepts/graph-explorer/images/consent-permissions.png
  concepts/graph-explorer/images/download-collection-screenshot.png
  concepts/graph-explorer/images/expand-collapse-response-preview.PNG
  concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG
  concepts/graph-explorer/images/get-graph-toolkit-card.PNG
  concepts/graph-explorer/images/get-request.png
  concepts/graph-explorer/images/getting-started.PNG
  concepts/graph-explorer/images/graph-explorer-screen.png
  concepts/graph-explorer/images/graph-toolkit.PNG
  concepts/graph-explorer/images/header-screenshot.png
  concepts/graph-explorer/images/history-tab-screenshot.png
  concepts/graph-explorer/images/link-to-m365-dev-program.PNG
  concepts/graph-explorer/images/making-a-get-request.PNG
  concepts/graph-explorer/images/making-a-non-get-request.PNG
  concepts/graph-explorer/images/making-a-post-request.PNG
  concepts/graph-explorer/images/modify-permissions-screenshot.png
  concepts/graph-explorer/images/modify-permissions.PNG
  concepts/graph-explorer/images/post-request.png
  concepts/graph-explorer/images/request-header.PNG
  concepts/graph-explorer/images/request-headers.png
  concepts/graph-explorer/images/resources-tab-screenshot.png
  concepts/graph-explorer/images/run-query-tabs-screenshot.png
  concepts/graph-explorer/images/sample-queries-screenshot.png
  concepts/graph-explorer/images/select-permissions.PNG
  concepts/graph-explorer/images/share-query-screenshot.png
  concepts/graph-explorer/images/share-query.PNG
  concepts/graph-explorer/images/storing-and-sharing-queries.PNG
  concepts/graph-explorer/images/toolkit-screenshot.png
Labels: ready to merge, internal, content review complete

#19118 Edits in PR 19068
  api-reference/beta/resources/windowsupdates-catalogentry.md
  api-reference/beta/resources/windowsupdates-datedrivenrolloutsettings.md
  api-reference/beta/resources/windowsupdates-deployablecontent.md
  api-reference/beta/resources/windowsupdates-deploymentaudience.md
  api-reference/beta/resources/windowsupdates-deploymentsettings.md
  api-reference/beta/resources/windowsupdates-deploymentstate.md
  api-reference/beta/resources/windowsupdates-driverupdatecatalogentry.md
  api-reference/beta/resources/windowsupdates-driverupdatefilter.md
  api-reference/beta/resources/windowsupdates-durationdrivenrolloutsettings.md
  api-reference/beta/resources/windowsupdates-expeditesettings.md
  api-reference/beta/resources/windowsupdates-gradualrolloutsettings.md
  api-reference/beta/resources/windowsupdates-ratedrivenrolloutsettings.md
  api-reference/beta/resources/windowsupdates-schedulesettings.md
  api-reference/beta/resources/windowsupdates-softwareupdatecatalogentry.md
  api-reference/beta/resources/windowsupdates-softwareupdatefilter.md
  api-reference/beta/resources/windowsupdates-updatepolicy.md
  api-reference/beta/resources/windowsupdates-windowsupdatefilter.md
Labels: external

#19115 Update enums.md
  api-reference/beta/resources/enums.md
Labels: external

#19120 Update timeoffreason.md
  api-reference/beta/resources/timeoffreason.md
Labels: external, ready to merge

#19119 Update timeoffreason.md
  api-reference/v1.0/resources/timeoffreason.md
Labels: external, ready to merge

#19109 Add link to conceptual
  api-reference/beta/resources/user.md
Labels: area: Azure AD, ready to merge, internal, area: governance

#17818 Update identity types in online meeting
  api-reference/beta/resources/meetingparticipantinfo.md
Labels: ready to merge, internal, content review complete

#19113 Update security-security-runhuntingquery.md
  api-reference/beta/api/security-security-runhuntingquery.md
Labels: external, ready to merge

#19112 fixing bugs
  concepts/data-connect-datasets.md
Labels: ready to merge, internal, content review complete

#19110 Add refresh_token return circumstance clarity
  concepts/auth-v2-user.md
Labels: external, ready to merge

#19036 Update call-addlargegalleryview.md
  api-reference/beta/api/call-addlargegalleryview.md
  api-reference/v1.0/api/call-addlargegalleryview.md
Labels: ready to merge, content review complete

#19121 Merge to publish.
  api-reference/beta/api/call-addlargegalleryview.md
  api-reference/beta/api/security-security-runhuntingquery.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/meetingparticipantinfo.md
  api-reference/beta/resources/timeoffreason.md
  api-reference/beta/resources/user.md
  api-reference/v1.0/api/call-addlargegalleryview.md
  api-reference/v1.0/resources/timeoffreason.md
  concepts/auth-v2-user.md
  concepts/data-connect-datasets.md
Labels: internal

#19116 GitHub Workflows security hardening
  .github/workflows/assign-to-author.yml
  .github/workflows/conflicting-pr-label.yml
  .github/workflows/eol-blocker.yml
  .github/workflows/snippet-generation-pr.yml
Labels: external, ready to merge

#18931 docs: pin unpkg links to current major version for mgt documentation
  concepts/toolkit/get-started/build-a-microsoft-teams-sso-tab.md
  concepts/toolkit/get-started/build-a-microsoft-teams-tab.md
  concepts/toolkit/get-started/build-a-web-app.md
  concepts/toolkit/get-started/overview.md
  concepts/toolkit/providers/providers.md
  concepts/toolkit/providers/teams-msal2.md
  concepts/toolkit/providers/teams.md
Labels: ready to merge, internal, content review complete

#19038 Add Teams Presence to v1.0
  api-reference/v1.0/resources/subscription.md
Labels: external, ready to merge

#16222 [Azure AD roles] assignedPrincipals method
  api-reference/beta/api/unifiedroledefinition-assignedprincipals.md
  api-reference/beta/resources/unifiedroledefinition.md
  api-reference/beta/toc.yml
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, ready to merge, internal, content review complete, area: directory management

#18511 Added missing request to create upload session
  api-reference/beta/api/driveitem-createuploadsession.md
  api-reference/v1.0/api/driveitem-createuploadsession.md
Labels: external, ready to merge

#19134 Merge to publish.
  .github/workflows/assign-to-author.yml
  .github/workflows/conflicting-pr-label.yml
  .github/workflows/eol-blocker.yml
  .github/workflows/snippet-generation-pr.yml
  api-reference/beta/api/driveitem-createuploadsession.md
  api-reference/beta/api/unifiedroledefinition-assignedprincipals.md
  api-reference/beta/resources/unifiedroledefinition.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/driveitem-createuploadsession.md
  api-reference/v1.0/resources/subscription.md
  changelog/Microsoft.DirectoryServices.json
  concepts/toolkit/get-started/build-a-microsoft-teams-sso-tab.md
  concepts/toolkit/get-started/build-a-microsoft-teams-tab.md
  concepts/toolkit/get-started/build-a-web-app.md
  concepts/toolkit/get-started/overview.md
  concepts/toolkit/providers/providers.md
  concepts/toolkit/providers/teams-msal2.md
  concepts/toolkit/providers/teams.md
Labels: do not merge, internal

#19151 Edits in PR 19068
  api-reference/beta/api/adminwindowsupdates-list-deploymentaudiences.md
  api-reference/beta/api/adminwindowsupdates-list-updatepolicies.md
  api-reference/beta/api/adminwindowsupdates-post-deploymentaudiences.md
  api-reference/beta/api/adminwindowsupdates-post-deployments.md
  api-reference/beta/api/adminwindowsupdates-post-updatepolicies.md
  api-reference/beta/api/windowsupdates-compliancechange-delete.md
  api-reference/beta/api/windowsupdates-compliancechange-get.md
  api-reference/beta/api/windowsupdates-compliancechange-update.md
  api-reference/beta/api/windowsupdates-contentapproval-delete.md
  api-reference/beta/api/windowsupdates-contentapproval-get.md
  api-reference/beta/api/windowsupdates-contentapproval-update.md
  api-reference/beta/api/windowsupdates-deploymentaudience-delete.md
  api-reference/beta/api/windowsupdates-deploymentaudience-get.md
  api-reference/beta/api/windowsupdates-updatableasset-unenrollassets.md
  api-reference/beta/api/windowsupdates-updatepolicy-delete.md
  api-reference/beta/api/windowsupdates-updatepolicy-get.md
  api-reference/beta/api/windowsupdates-updatepolicy-list-compliancechanges-contentapproval.md
  api-reference/beta/api/windowsupdates-updatepolicy-list-compliancechanges.md
  api-reference/beta/api/windowsupdates-updatepolicy-post-compliancechanges-contentapproval.md
  api-reference/beta/api/windowsupdates-updatepolicy-update.md
  api-reference/beta/resources/admin.md
  api-reference/beta/resources/adminwindows.md
  api-reference/beta/resources/adminwindowsupdates.md
  api-reference/beta/resources/windowsupdates-updatemanagementenrollment.md
  concepts/windowsupdates-schedule-deployment.md
Labels: external

#19153 Update cloudpconpremisesconnection-delete.md
  api-reference/beta/api/cloudpconpremisesconnection-delete.md
Labels: external

#19001 Updated MESG description
  api-reference/v1.0/resources/groups-overview.md
Labels: area: Azure AD, area: groups, ready to merge, internal, content review complete

#19101 Removed extra resource file and updated query option support
  api-reference/beta/api/identitygovernance-userprocessingresult-summary.md
  api-reference/beta/resources/identitygovernance-customtaskextension.md
  api-reference/beta/resources/identitygovernance-run.md
  api-reference/beta/resources/identitygovernance-task.md
  api-reference/beta/resources/identitygovernance-taskdefinition.md
  api-reference/beta/resources/identitygovernance-taskprocessingresult.md
  api-reference/beta/resources/identitygovernance-taskreport.md
  api-reference/beta/resources/identitygovernance-userprocessingresult.md
  api-reference/beta/resources/identitygovernance-usersprocessingsummary.md
  api-reference/beta/resources/identitygovernance-workflow.md
  api-reference/beta/resources/identitygovernance-workflowtemplate.md
  api-reference/beta/resources/identitygovernance-workflowversion.md
Labels: area: Azure AD, ready to merge, content review complete, schema live, area: governance

#18901 Adding TenantId Validation notes to chatmessage-update.md
  api-reference/v1.0/api/chatmessage-update.md
  changelog/Microsoft.Teams.Core.json
Labels: ready to merge, internal, content review complete

#19127 Query capabilities FY23 Q2 refresh - Azure AD
  api-reference/beta/api/agreement-list-acceptances.md
  api-reference/beta/api/user-list-agreementacceptances.md
  api-reference/beta/resources/agreementacceptance.md
  api-reference/beta/resources/orgcontact.md
  api-reference/v1.0/api/agreement-list-acceptances.md
  api-reference/v1.0/api/user-list-agreementacceptances.md
  api-reference/v1.0/resources/agreementacceptance.md
  api-reference/v1.0/resources/orgcontact.md
  concepts/aad-advanced-queries.md
  includes/filter-directory-objects.md
Labels: area: Azure AD, ready to merge, internal, area: query parameters

#19131 remove .(dot) from mailnickname-v1
  api-reference/v1.0/resources/group.md
Labels: area: Azure AD, area: groups, ready to merge, internal, content review complete

#19123 Request snippets for examples in include files
  concepts/includes/tutorial-assign-custom-roles.md
Labels: area: Azure AD, ready to merge, internal

#19132 remove .(dot) for beta
  api-reference/beta/resources/group.md
Labels: area: Azure AD, area: groups, ready to merge, internal, content review complete

#19135 Update best-practices-concept.md
  concepts/best-practices-concept.md
Labels: external, ready to merge

#19145 Fix #18287
  api-reference/beta/resources/user.md
  api-reference/v1.0/resources/user.md
Labels: area: Azure AD, area: users, ready to merge

#19146 employee leave date time link added within article
  concepts/tutorial-lifecycle-workflows-scheduled-leaver.md
Labels: ready to merge, internal

#19130 call out invalid characters are not validated
  api-reference/v1.0/api/directoryobject-validateproperties.md
Labels: area: Azure AD, area: groups, ready to merge, internal, content review complete

#19157 Merge to publish.
  .github/workflows/assign-to-author.yml
  .github/workflows/eol-blocker.yml
  .github/workflows/snippet-generation-pr.yml
  api-reference/beta/api/agreement-list-acceptances.md
  api-reference/beta/api/cloudpconpremisesconnection-delete.md
  api-reference/beta/api/identitygovernance-userprocessingresult-summary.md
  api-reference/beta/api/user-list-agreementacceptances.md
  api-reference/beta/resources/agreementacceptance.md
  api-reference/beta/resources/group.md
  api-reference/beta/resources/identitygovernance-customtaskextension.md
  api-reference/beta/resources/identitygovernance-run.md
  api-reference/beta/resources/identitygovernance-task.md
  api-reference/beta/resources/identitygovernance-taskdefinition.md
  api-reference/beta/resources/identitygovernance-taskprocessingresult.md
  api-reference/beta/resources/identitygovernance-taskreport.md
  api-reference/beta/resources/identitygovernance-userprocessingresult.md
  api-reference/beta/resources/identitygovernance-usersprocessingsummary.md
  api-reference/beta/resources/identitygovernance-workflow.md
  api-reference/beta/resources/identitygovernance-workflowtemplate.md
  api-reference/beta/resources/identitygovernance-workflowversion.md
  api-reference/beta/resources/orgcontact.md
  api-reference/beta/resources/user.md
  api-reference/v1.0/api/agreement-list-acceptances.md
  api-reference/v1.0/api/chatmessage-update.md
  api-reference/v1.0/api/directoryobject-validateproperties.md
  api-reference/v1.0/api/user-list-agreementacceptances.md
  api-reference/v1.0/resources/agreementacceptance.md
  api-reference/v1.0/resources/group.md
  api-reference/v1.0/resources/groups-overview.md
  api-reference/v1.0/resources/orgcontact.md
  api-reference/v1.0/resources/user.md
  changelog/Microsoft.Teams.Core.json
  concepts/aad-advanced-queries.md
  concepts/best-practices-concept.md
  concepts/includes/tutorial-assign-custom-roles.md
  concepts/tutorial-lifecycle-workflows-scheduled-leaver.md
  includes/filter-directory-objects.md
Labels: do not merge, internal

#19141 Configure zone pivots
  .openpublishing.publish.config.json
  concepts/zone-pivot-groups.yml
Labels: ready to merge, ready for content review, internal

#19177 Update team.md
  api-reference/beta/resources/team.md
Labels: external

#19176 Update teamsummary.md
  api-reference/beta/resources/teamsummary.md
Labels: external

#19159 Remove the requireChangeOnNextSignIn property from the resetPassword action
  api-reference/v1.0/api/authenticationmethod-resetpassword.md
  changelog/Microsoft.StrongAuthenticationAPI.json
Labels: area: Azure AD, ready to merge, internal, area: authentication methods, area: identity

#16217 Grant API permissions using Microsoft Graph
  concepts/permissions-grant-via-msgraph.md
  concepts/toc.yml
Labels: area: Azure AD, ready to merge, internal, area: permissions, review feedback addressed

#19162 Sensitive actions on user objects
  api-reference/beta/resources/users.md
  api-reference/v1.0/resources/users.md
Labels: area: users, ready to merge, internal

#19164 Directory.ReadWrite.All not sufficient for write on apps
  api-reference/beta/api/application-delete.md
  api-reference/beta/api/application-post-applications.md
  api-reference/beta/api/application-update.md
Labels: area: Azure AD, ready to merge, internal

#19172 Added send onboarding reminder email task
  api-reference/beta/includes/lifecycle-workflows-tasks-table.md
Labels: do not merge, ready to merge, internal

#19160 Update user-revokesigninsessions.md
  api-reference/beta/api/user-revokesigninsessions.md
  api-reference/v1.0/api/user-revokesigninsessions.md
Labels: area: users, do not merge, ready to merge, internal

#19188 Edits in PR 19068
  api-reference/beta/api/adminwindowsupdates-list-deploymentaudiences.md
  api-reference/beta/api/adminwindowsupdates-list-updatepolicies.md
  api-reference/beta/api/adminwindowsupdates-post-deploymentaudiences.md
  api-reference/beta/api/adminwindowsupdates-post-updatepolicies.md
  api-reference/beta/api/windowsupdates-compliancechange-get.md
  api-reference/beta/api/windowsupdates-compliancechange-update.md
  api-reference/beta/api/windowsupdates-contentapproval-get.md
  api-reference/beta/api/windowsupdates-contentapproval-update.md
  api-reference/beta/api/windowsupdates-deploymentaudience-get.md
  api-reference/beta/api/windowsupdates-updatepolicy-get.md
  api-reference/beta/api/windowsupdates-updatepolicy-list-compliancechanges-contentapproval.md
  api-reference/beta/api/windowsupdates-updatepolicy-list-compliancechanges.md
  api-reference/beta/api/windowsupdates-updatepolicy-post-compliancechanges-contentapproval.md
  api-reference/beta/api/windowsupdates-updatepolicy-update.md
  api-reference/beta/resources/windowsupdates-datedrivenrolloutsettings.md
  api-reference/beta/resources/windowsupdates-driverupdatecatalogentry.md
  api-reference/beta/resources/windowsupdates-durationdrivenrolloutsettings.md
  api-reference/beta/resources/windowsupdates-ratedrivenrolloutsettings.md
  api-reference/beta/resources/windowsupdates-schedulesettings.md
  api-reference/beta/resources/windowsupdates-updatableassetgroup.md
  changelog/Microsoft.WindowsUpdates.json
Labels: external

#19190 Update planner-post-buckets.md
  api-reference/beta/api/planner-post-buckets.md
Labels: external

#19189 Update planner-post-buckets.md
  api-reference/v1.0/api/planner-post-buckets.md
Labels: external

#19178 Update team.md
  api-reference/v1.0/resources/team.md
Labels: external

#18171 Edit Sample response to add a Content-Length header
  concepts/throttling.md
Labels: external, ready to merge, review requested

#19092 Update LCW tasks to use cross-repo include
  api-reference/beta/includes/lifecycle-workflows-tasks-table.md
  api-reference/beta/resources/identitygovernance-lifecycleworkflows-overview.md
  api-reference/beta/resources/identitygovernance-task.md
Labels: area: Azure AD, ready to merge, internal

#18517 Adding service principal lock configuration property
  api-reference/beta/resources/application.md
  api-reference/beta/resources/servicePrincipalLockConfiguration.md
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, ready to merge, internal, content review complete, schema live

#19191 Merge to publish.
  api-reference/beta/api/planner-post-buckets.md
  api-reference/beta/includes/lifecycle-workflows-tasks-table.md
  api-reference/beta/resources/application.md
  api-reference/beta/resources/identitygovernance-lifecycleworkflows-overview.md
  api-reference/beta/resources/identitygovernance-task.md
  api-reference/beta/resources/servicePrincipalLockConfiguration.md
  api-reference/v1.0/api/planner-post-buckets.md
  api-reference/v1.0/resources/team.md
  changelog/Microsoft.DirectoryServices.json
  concepts/throttling.md
Labels: internal

#19203 Edits in PR 19015
  api-reference/beta/resources/businessscenario.md
  api-reference/beta/resources/businessscenariogrouptarget.md
  api-reference/beta/resources/businessscenarioplanner.md
  api-reference/beta/resources/businessscenarioplanreference.md
  api-reference/beta/resources/businessscenarioproperties.md
  api-reference/beta/resources/businessscenariotask.md
  api-reference/beta/resources/businessscenariotasktargetbase.md
  api-reference/beta/resources/plannerbucketpropertyrule.md
  api-reference/beta/resources/plannerfieldrules.md
  api-reference/beta/resources/plannerplanconfiguration.md
Labels: external

#19206 spelling-fix
  concepts/migrate-azure-ad-graph-app-registration.md
Labels: external

#19205 Update plannerplandetails.md
  api-reference/beta/resources/plannerplandetails.md
Labels: external

#19204 Update plannerplandetails.md
  api-reference/v1.0/resources/plannerplandetails.md
Labels: external

#19196 Typo correction
  concepts/paging.md
Labels: external

#19199 fixing link
  concepts/outlook-send-mime-message.md
Labels: ready to merge, internal

#19187 Change how training modules are referenced in docs
  concepts/azuread-users-concept-overview.md
  concepts/delta-query-overview.md
  concepts/extensibility-overview.md
  concepts/query-parameters.md
  concepts/throttling.md
  concepts/toc.yml
  concepts/webhooks.md
Labels: area: Azure AD, ready to merge, internal

#19194 Fix throttling limits tables + reassign includes to respective doc owners
  includes/throttling-aad-reports.md
  includes/throttling-cpim.md
  includes/throttling-education-rostering-apis.md
  includes/throttling-excel.md
  includes/throttling-extensions.md
  includes/throttling-files-and-lists.md
  includes/throttling-identity-and-access.md
  includes/throttling-identityprotection-ca.md
  includes/throttling-information-protection.md
  includes/throttling-intune-android-for-work.md
  includes/throttling-intune-applications.md
  includes/throttling-intune-auditing.md
  includes/throttling-intune-books.md
  includes/throttling-intune-bundles.md
  includes/throttling-intune-chromebook-sync.md
  includes/throttling-intune-company-terms.md
  includes/throttling-intune-device-config-v2.md
  includes/throttling-intune-device-configuration.md
  includes/throttling-intune-device-enrollment.md
  includes/throttling-intune-device-intent.md
  includes/throttling-intune-devices.md
  includes/throttling-intune-endpoint-protection.md
  includes/throttling-intune-enrollment.md
  includes/throttling-intune-fencing.md
  includes/throttling-intune-gpanalytics.md
  includes/throttling-intune-managed-applications.md
  includes/throttling-intune-notifications.md
  includes/throttling-intune-odj.md
  includes/throttling-intune-partner-integration.md
  includes/throttling-intune-rbac.md
  includes/throttling-intune-remote-assistance.md
  includes/throttling-intune-telephony.md
  includes/throttling-intune-tem.md
  includes/throttling-intune-throttling-tunnel.md
  includes/throttling-intune-troubleshooting.md
  includes/throttling-intune-unlock.md
  includes/throttling-intune-updates.md
  includes/throttling-intune-wip.md
  includes/throttling-multi-tenant-platform.md
  includes/throttling-onenote.md
  includes/throttling-skype-calling.md
  includes/throttling-tasks-and-plans.md
  includes/throttling-teams.md
Labels: ready to merge, internal

#19048 Document Azure AD Graph & Microsoft Graph permissions differences
  concepts/migrate-azure-ad-graph-audit-api-use.md
  concepts/migrate-azure-ad-graph-method-differences.md
  concepts/migrate-azure-ad-graph-permissions-differences.md
  concepts/migrate-azure-ad-graph-planning-checklist.md
  concepts/toc.yml
Labels: area: Azure AD, ready to merge, internal, area: permissions, API migration

#19225 Update responsestatus.md
  api-reference/v1.0/resources/responsestatus.md
Labels: external

#19224 Update bitlockerrecoverykey-get.md
  api-reference/beta/api/bitlockerrecoverykey-get.md
Labels: external

#19223 Update bitlockerrecoverykey-get.md
  api-reference/v1.0/api/bitlockerrecoverykey-get.md
Labels: external

#19222 Update bitlocker-list-recoverykeys.md
  api-reference/beta/api/bitlocker-list-recoverykeys.md
Labels: external

#19221 Update bitlocker-list-recoverykeys.md
  api-reference/v1.0/api/bitlocker-list-recoverykeys.md
Labels: external

#19219 Update security-retentionduration.md
  api-reference/beta/resources/security-retentionduration.md
Labels: external

#19212 Request code snippets
  concepts/delta-query-groups.md
  concepts/delta-query-users.md
  concepts/extensibility-overview.md
Labels: area: Azure AD, ready to merge, internal, area: SDKs

#19213 Add links to permissions how-to
  api-reference/beta/resources/approleassignment.md
  api-reference/beta/resources/oauth2permissiongrant.md
  api-reference/v1.0/resources/approleassignment.md
  api-reference/v1.0/resources/oauth2permissiongrant.md
Labels: area: Azure AD, ready to merge, internal

#19226 Merge to publish.
  api-reference/beta/api/bitlocker-list-recoverykeys.md
  api-reference/beta/api/bitlockerrecoverykey-get.md
  api-reference/beta/resources/approleassignment.md
  api-reference/beta/resources/oauth2permissiongrant.md
  api-reference/beta/resources/security-retentionduration.md
  api-reference/v1.0/api/bitlocker-list-recoverykeys.md
  api-reference/v1.0/api/bitlockerrecoverykey-get.md
  api-reference/v1.0/resources/approleassignment.md
  api-reference/v1.0/resources/oauth2permissiongrant.md
  api-reference/v1.0/resources/responsestatus.md
  concepts/delta-query-groups.md
  concepts/delta-query-users.md
  concepts/extensibility-overview.md
Labels: internal

#19242 Update plannerroster-delete.md
  api-reference/beta/api/plannerroster-delete.md
Labels: external

#19241 Update extensibility-overview.md
  concepts/extensibility-overview.md
Labels: external

#19234 Update choose-online-meeting-api.md
  concepts/choose-online-meeting-api.md
Labels: external

#18260 Introduce appId as alternate key in servicePrincipals
  api-reference/beta/api/serviceprincipal-addkey.md
  api-reference/beta/api/serviceprincipal-addpassword.md
  api-reference/beta/api/serviceprincipal-addtokensigningcertificate.md
  api-reference/beta/api/serviceprincipal-createpasswordsinglesignoncredentials.md
  api-reference/beta/api/serviceprincipal-delete-claimsmappingpolicies.md
  api-reference/beta/api/serviceprincipal-delete-delegatedpermissionclassifications.md
  api-reference/beta/api/serviceprincipal-delete-homerealmdiscoverypolicies.md
  api-reference/beta/api/serviceprincipal-delete.md
  api-reference/beta/api/serviceprincipal-deletepasswordsinglesignoncredentials.md
  api-reference/beta/api/serviceprincipal-get.md
  api-reference/beta/api/serviceprincipal-getpasswordsinglesignoncredentials.md
  api-reference/beta/api/serviceprincipal-post-approleassignedto.md
  api-reference/beta/api/serviceprincipal-post-approleassignments.md
  api-reference/beta/api/serviceprincipal-post-claimsmappingpolicies.md
  api-reference/beta/api/serviceprincipal-post-delegatedpermissionclassifications.md
  api-reference/beta/api/serviceprincipal-post-homerealmdiscoverypolicies.md
  api-reference/beta/api/serviceprincipal-post-owners.md
  api-reference/beta/api/serviceprincipal-removekey.md
  api-reference/beta/api/serviceprincipal-removepassword.md
  api-reference/beta/api/serviceprincipal-update.md
  api-reference/beta/api/serviceprincipal-updatepasswordsinglesignoncredentials.md
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, ready to merge, internal, content review complete

#19058 Fixed app-only permissions for list and get methods
  api-reference/beta/api/rbacapplication-list-roleassignmentschedulerequests.md
  api-reference/beta/api/rbacapplication-list-roleeligibilityschedulerequests.md
  api-reference/beta/api/unifiedroleassignmentschedulerequest-get.md
  api-reference/beta/api/unifiedroleeligibilityschedulerequest-get.md
  api-reference/v1.0/api/rbacapplication-list-roleassignmentschedulerequests.md
  api-reference/v1.0/api/rbacapplication-list-roleeligibilityschedulerequests.md
  api-reference/v1.0/api/unifiedroleassignmentschedulerequest-get.md
  api-reference/v1.0/api/unifiedroleeligibilityschedulerequest-get.md
Labels: area: Azure AD, ready to merge, internal, content review complete, area: governance

#19195 $filter for extension properties - user
  api-reference/beta/api/user-list.md
  includes/filter-directory-objects.md
Labels: area: Azure AD, ready to merge, area: query parameters, area: extensions

#19231 Update serviceprincipal.md
  api-reference/beta/resources/serviceprincipal.md
  api-reference/v1.0/resources/serviceprincipal.md
  concepts/migrate-azure-ad-graph-configure-permissions.md
Labels: ready to merge, internal

#19232 Application/SP quick how-to
  concepts/toc.yml
  concepts/tutorial-applications-basics.md
Labels: area: Azure AD, ready to merge, area: applications

#19243 Merge to publish.
  api-reference/beta/api/plannerroster-delete.md
  api-reference/beta/api/rbacapplication-list-roleassignmentschedulerequests.md
  api-reference/beta/api/rbacapplication-list-roleeligibilityschedulerequests.md
  api-reference/beta/api/serviceprincipal-addkey.md
  api-reference/beta/api/serviceprincipal-addpassword.md
  api-reference/beta/api/serviceprincipal-addtokensigningcertificate.md
  api-reference/beta/api/serviceprincipal-createpasswordsinglesignoncredentials.md
  api-reference/beta/api/serviceprincipal-delete-claimsmappingpolicies.md
  api-reference/beta/api/serviceprincipal-delete-delegatedpermissionclassifications.md
  api-reference/beta/api/serviceprincipal-delete-homerealmdiscoverypolicies.md
  api-reference/beta/api/serviceprincipal-delete.md
  api-reference/beta/api/serviceprincipal-deletepasswordsinglesignoncredentials.md
  api-reference/beta/api/serviceprincipal-get.md
  api-reference/beta/api/serviceprincipal-getpasswordsinglesignoncredentials.md
  api-reference/beta/api/serviceprincipal-post-approleassignedto.md
  api-reference/beta/api/serviceprincipal-post-approleassignments.md
  api-reference/beta/api/serviceprincipal-post-claimsmappingpolicies.md
  api-reference/beta/api/serviceprincipal-post-delegatedpermissionclassifications.md
  api-reference/beta/api/serviceprincipal-post-homerealmdiscoverypolicies.md
  api-reference/beta/api/serviceprincipal-post-owners.md
  api-reference/beta/api/serviceprincipal-removekey.md
  api-reference/beta/api/serviceprincipal-removepassword.md
  api-reference/beta/api/serviceprincipal-update.md
  api-reference/beta/api/serviceprincipal-updatepasswordsinglesignoncredentials.md
  api-reference/beta/api/unifiedroleassignmentschedulerequest-get.md
  api-reference/beta/api/unifiedroleeligibilityschedulerequest-get.md
  api-reference/beta/api/user-list.md
  api-reference/beta/resources/serviceprincipal.md
  api-reference/v1.0/api/rbacapplication-list-roleassignmentschedulerequests.md
  api-reference/v1.0/api/rbacapplication-list-roleeligibilityschedulerequests.md
  api-reference/v1.0/api/unifiedroleassignmentschedulerequest-get.md
  api-reference/v1.0/api/unifiedroleeligibilityschedulerequest-get.md
  api-reference/v1.0/resources/serviceprincipal.md
  changelog/Microsoft.DirectoryServices.json
  concepts/choose-online-meeting-api.md
  concepts/extensibility-overview.md
  concepts/migrate-azure-ad-graph-configure-permissions.md
  concepts/toc.yml
  concepts/tutorial-applications-basics.md
  includes/filter-directory-objects.md
Labels: internal

#19246 Fix a Link Error in Report Setting page
  api-reference/beta/resources/report.md
Labels: ready to merge, internal

#19216 adding additional permissions
  api-reference/beta/api/group-list-transitivememberof.md
Labels: area: groups, ready to merge, internal, content review complete

#19217 Update group-list-transitivememberof.md
  api-reference/v1.0/api/group-list-transitivememberof.md
Labels: area: groups, ready to merge, internal, content review complete

#19237 Jupetter authmethodspolicy
  api-reference/beta/api/emailauthenticationmethodconfiguration-delete.md
  api-reference/beta/api/emailauthenticationmethodconfiguration-get.md
  api-reference/beta/api/emailauthenticationmethodconfiguration-update.md
  api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md
  api-reference/beta/api/fido2authenticationmethodconfiguration-get.md
  api-reference/beta/api/fido2authenticationmethodconfiguration-update.md
  api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md
  api-reference/beta/api/smsauthenticationmethodconfiguration-get.md
  api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md
  api-reference/beta/api/x509certificateauthenticationmethodconfiguration-delete.md
  api-reference/beta/api/x509certificateauthenticationmethodconfiguration-get.md
  api-reference/beta/api/x509certificateauthenticationmethodconfiguration-update.md
  api-reference/v1.0/api/emailauthenticationmethodconfiguration-get.md
  api-reference/v1.0/api/fido2authenticationmethodconfiguration-get.md
  api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md
  api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-get.md
  api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-get.md
Labels: area: Azure AD, ready to merge, internal, content review complete

#19244 Update schemaextension.md
  api-reference/beta/resources/schemaextension.md
  api-reference/v1.0/resources/schemaextension.md
Labels: ready to merge, internal

#19253 Clarity on $top
  concepts/query-parameters.md
Labels: area: Azure AD, ready to merge, internal, area: query parameters

#19258 Edits in PR 19015
  api-reference/beta/api/businessscenario-update.md
  api-reference/beta/resources/businessscenario-overview.md
  api-reference/beta/resources/businessscenario-planner-overview.md
  api-reference/beta/resources/businessscenario.md
  api-reference/beta/resources/businessscenariogrouptarget.md
  api-reference/beta/resources/businessscenarioplanner.md
  api-reference/beta/resources/planner-task-rules-overview.md
  api-reference/beta/resources/plannerplanconfiguration.md
  api-reference/beta/resources/plannerplanconfigurationbucketdefinition.md
Labels: external

#19259 Update onlinemeeting-delete.md
  api-reference/beta/api/onlinemeeting-delete.md
Labels: external

#19261 Merge to publish.
  api-reference/beta/api/emailauthenticationmethodconfiguration-delete.md
  api-reference/beta/api/emailauthenticationmethodconfiguration-get.md
  api-reference/beta/api/emailauthenticationmethodconfiguration-update.md
  api-reference/beta/api/fido2authenticationmethodconfiguration-delete.md
  api-reference/beta/api/fido2authenticationmethodconfiguration-get.md
  api-reference/beta/api/fido2authenticationmethodconfiguration-update.md
  api-reference/beta/api/group-list-transitivememberof.md
  api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md
  api-reference/beta/api/onlinemeeting-delete.md
  api-reference/beta/api/smsauthenticationmethodconfiguration-get.md
  api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md
  api-reference/beta/api/user-list.md
  api-reference/beta/api/user-update.md
  api-reference/beta/api/x509certificateauthenticationmethodconfiguration-delete.md
  api-reference/beta/api/x509certificateauthenticationmethodconfiguration-get.md
  api-reference/beta/api/x509certificateauthenticationmethodconfiguration-update.md
  api-reference/beta/resources/groups-overview.md
  api-reference/beta/resources/report.md
  api-reference/beta/resources/schemaextension.md
  api-reference/beta/resources/user.md
  api-reference/beta/resources/users.md
  api-reference/v1.0/api/emailauthenticationmethodconfiguration-get.md
  api-reference/v1.0/api/fido2authenticationmethodconfiguration-get.md
  api-reference/v1.0/api/group-list-transitivememberof.md
  api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md
  api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-get.md
  api-reference/v1.0/api/user-list.md
  api-reference/v1.0/api/user-update.md
  api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-get.md
  api-reference/v1.0/resources/groups-overview.md
  api-reference/v1.0/resources/schemaextension.md
  api-reference/v1.0/resources/user.md
  api-reference/v1.0/resources/users.md
  concepts/query-parameters.md
Labels: internal

#19274 Edits in PR 19015
  api-reference/beta/api/businessscenarioplanner-post-tasks.md
  api-reference/beta/api/businessscenariotask-update.md
  api-reference/beta/api/plannerplanconfiguration-delete-localizations.md
  api-reference/beta/api/plannerplanconfiguration-post-localizations.md
  api-reference/beta/api/plannerplanconfiguration-update.md
  api-reference/beta/api/plannerplanconfigurationlocalization-update.md
  api-reference/beta/api/solutionsroot-list-businessscenarios.md
  api-reference/beta/resources/businessscenario.md
  api-reference/beta/resources/businessscenarioplanner.md
  api-reference/beta/resources/businessscenarioplanreference.md
  api-reference/beta/resources/businessscenariotask.md
  api-reference/beta/resources/plannerplanconfiguration.md
  api-reference/beta/resources/plannerpropertyrule.md
  api-reference/beta/resources/plannertaskpropertyrule.md
  concepts/businessScenarios-concept-overview.md
  concepts/permissions-reference.md
Labels: external

#19275 Edits in PR 19015
  concepts/businessScenarios-concept-overview.md
Labels: external

#19278 Update plannertask.md
  api-reference/v1.0/resources/plannertask.md
Labels: external

#19277 Update plannertask.md
  api-reference/beta/resources/plannertask.md
Labels: external

#19260 Update onlinemeeting-delete.md
  api-reference/v1.0/api/onlinemeeting-delete.md
Labels: external

#19218 Adding documentation for an aria-label property that's being added to the people picker component
  concepts/toolkit/components/people-picker.md
Labels: external, ready to merge, content review complete

#19268 team-post-installedapps.md: fix link to known issues
  api-reference/beta/api/team-post-installedapps.md
Labels: external, ready to merge

#19271 Fix link
  api-reference/beta/resources/identitygovernance-lifecycleworkflows-overview.md
  api-reference/beta/resources/identitygovernance-lifecycleworkflows-reporting-overview.md
Labels: ready to merge, internal

#19270 Various edits
  api-reference/beta/api/group-post-approleassignments.md
  api-reference/beta/resources/approleassignment.md
  api-reference/v1.0/api/group-post-approleassignments.md
  api-reference/v1.0/resources/approleassignment.md
  concepts/tutorial-applications-basics.md
Labels: area: Azure AD, ready to merge, internal

#19263 Update teamsfx auth provider docs
  concepts/toolkit/providers/teamsfx.md
Labels: external, ready to merge

#19295 Edits in PR 19015
  api-reference/beta/api/businessscenario-get.md
  api-reference/beta/api/businessscenario-update.md
  api-reference/beta/api/businessscenarioplanner-delete-tasks.md
  api-reference/beta/api/businessscenarioplanner-get.md
  api-reference/beta/api/businessscenarioplanner-getplan.md
  api-reference/beta/api/businessscenarioplanner-list-tasks.md
  api-reference/beta/api/businessscenarioplanner-post-tasks.md
  api-reference/beta/api/businessscenariotask-get.md
  api-reference/beta/api/businessscenariotask-update.md
  api-reference/beta/api/plannerplanconfiguration-delete-localizations.md
  api-reference/beta/api/plannerplanconfiguration-get.md
  api-reference/beta/api/plannerplanconfiguration-list-localizations.md
  api-reference/beta/api/plannerplanconfiguration-post-localizations.md
  api-reference/beta/api/plannerplanconfiguration-update.md
  api-reference/beta/api/plannerplanconfigurationlocalization-get.md
  api-reference/beta/api/plannerplanconfigurationlocalization-update.md
  api-reference/beta/api/plannertaskconfiguration-get.md
  api-reference/beta/api/plannertaskconfiguration-update.md
  api-reference/beta/api/solutionsroot-delete-businessscenarios.md
  api-reference/beta/resources/businessscenario-overview.md
  api-reference/beta/resources/businessscenario-planner-overview.md
  api-reference/beta/resources/planner-task-rules-overview.md
  api-reference/beta/resources/plannertaskpropertyrule.md
  concepts/businessscenarios-concept-overview.md
Labels: external

#19282 Limits on requested permissions per app
  api-reference/beta/resources/application.md
  api-reference/v1.0/resources/application.md
  concepts/includes/msgraph-permissions-limits.md
Labels: area: Azure AD, ready to merge, internal, area: permissions

#19296 Merge to publish.
  api-reference/beta/resources/application.md
  api-reference/v1.0/resources/application.md
  concepts/includes/msgraph-permissions-limits.md
  concepts/toolkit/providers/teamsfx.md
  concepts/tutorial-applications-basics.md
Labels: internal

#19303 Update search-bookmark-update.md
  api-reference/beta/api/search-bookmark-update.md
Labels: external

#19302 Update chatmessage-post.md
  api-reference/beta/api/chatmessage-post.md
Labels: external

#19301 Update chatmessage-post.md
  api-reference/v1.0/api/chatmessage-post.md
Labels: external

#19117 Add isExactMatchRequired property
  api-reference/beta/resources/externalconnectors-property.md
  changelog/Microsoft.Search.json
  concepts/connecting-external-content-manage-schema.md
Labels: ready to merge, internal, content review complete, schema live

#19292 Select_escaped is not found, there is Select which does the expected thing
  concepts/sdks/includes/snippets/go/create-requests-list.md
Labels: external, ready to merge

#19254 Update directory-deleteditems-list.md
  api-reference/beta/api/directory-deleteditems-delete.md
  api-reference/beta/api/directory-deleteditems-get.md
  api-reference/beta/api/directory-deleteditems-list.md
  api-reference/beta/api/directory-deleteditems-restore.md
  api-reference/v1.0/api/directory-deleteditems-delete.md
  api-reference/v1.0/api/directory-deleteditems-get.md
  api-reference/v1.0/api/directory-deleteditems-list.md
  api-reference/v1.0/api/directory-deleteditems-restore.md
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, external, ready to merge, content review complete, area: directory management

#19304 Merge to publish.
  api-reference/beta/api/chatmessage-post.md
  api-reference/beta/api/directory-deleteditems-delete.md
  api-reference/beta/api/directory-deleteditems-get.md
  api-reference/beta/api/directory-deleteditems-list.md
  api-reference/beta/api/directory-deleteditems-restore.md
  api-reference/beta/api/search-bookmark-update.md
  api-reference/beta/resources/externalconnectors-property.md
  api-reference/v1.0/api/chatmessage-post.md
  api-reference/v1.0/api/directory-deleteditems-delete.md
  api-reference/v1.0/api/directory-deleteditems-get.md
  api-reference/v1.0/api/directory-deleteditems-list.md
  api-reference/v1.0/api/directory-deleteditems-restore.md
  changelog/Microsoft.DirectoryServices.json
  changelog/Microsoft.Search.json
  concepts/connecting-external-content-manage-schema.md
  concepts/sdks/includes/snippets/go/create-requests-list.md
Labels: internal

#19323 Edits in PR 19068
  api-reference/beta/api/adminwindowsupdates-list-updatepolicies.md
  api-reference/beta/api/windowsupdates-deployment-update.md
  api-reference/beta/resources/windowsupdates-applicablecontentdevicematch.md
  api-reference/beta/resources/windowsupdates-catalogcontent.md
  api-reference/beta/resources/windowsupdates-expeditesettings.md
  changelog/Microsoft.WindowsUpdates.json
  concepts/windowsupdates-deployments.md
Labels: external

#19322 Make Graph Explorer more visible in Explore section per feedback.
  concepts/toc.yml
Labels: do not merge, internal

#19328 Added back subject rights request sub-node.
  api-reference/beta/resources/complianceapioverview.md
  api-reference/beta/toc.yml
Labels: do not merge, internal

#19331 Publish 2 PRs to live site.
  api-reference/beta/resources/complianceapioverview.md
  api-reference/beta/toc.yml
  concepts/toc.yml
Labels: internal

#19319 Minor doc fixes
  api-reference/beta/api/application-update.md
  api-reference/beta/resources/unifiedrolepermission.md
  api-reference/v1.0/api/application-update.md
  api-reference/v1.0/resources/unifiedrolepermission.md
  concepts/identitygovernance-lifecycleworkflows-task-arguments.md
Labels: area: Azure AD, ready to merge, internal

#19297 Get ownerless apps and SPs
  api-reference/beta/api/application-delete-owners.md
  api-reference/beta/api/application-list.md
  api-reference/beta/api/serviceprincipal-delete-owners.md
  api-reference/beta/api/serviceprincipal-list.md
  api-reference/beta/resources/application.md
  api-reference/beta/resources/serviceprincipal.md
  api-reference/v1.0/api/application-delete-owners.md
  api-reference/v1.0/api/application-list.md
  api-reference/v1.0/api/serviceprincipal-delete-owners.md
  api-reference/v1.0/api/serviceprincipal-list.md
  api-reference/v1.0/resources/application.md
  api-reference/v1.0/resources/serviceprincipal.md
  concepts/tutorial-applications-basics.md
Labels: area: Azure AD, ready to merge, internal, area: applications

#19344 Release latest Identity updates to Live
  api-reference/beta/api/application-delete-owners.md
  api-reference/beta/api/application-list.md
  api-reference/beta/api/application-update.md
  api-reference/beta/api/serviceprincipal-delete-owners.md
  api-reference/beta/api/serviceprincipal-list.md
  api-reference/beta/resources/application.md
  api-reference/beta/resources/serviceprincipal.md
  api-reference/beta/resources/unifiedrolepermission.md
  api-reference/v1.0/api/application-delete-owners.md
  api-reference/v1.0/api/application-list.md
  api-reference/v1.0/api/application-update.md
  api-reference/v1.0/api/serviceprincipal-delete-owners.md
  api-reference/v1.0/api/serviceprincipal-list.md
  api-reference/v1.0/resources/application.md
  api-reference/v1.0/resources/serviceprincipal.md
  api-reference/v1.0/resources/unifiedrolepermission.md
  concepts/identitygovernance-lifecycleworkflows-task-arguments.md
  concepts/tutorial-applications-basics.md
Labels: internal

#19347 Documented what was new through Oct. 14.
  api-reference/beta/api/chatmessage-update.md
  changelog/Microsoft.Teams.Core.json
  changelog/Microsoft.Teams.GraphSvc.json
  concepts/whats-new-overview.md
Labels: do not merge, internal

#19348 $filter for empty collections - change wording
  api-reference/beta/resources/application.md
  api-reference/beta/resources/device.md
  api-reference/beta/resources/group.md
  api-reference/beta/resources/orgcontact.md
  api-reference/beta/resources/serviceprincipal.md
  api-reference/beta/resources/user.md
  api-reference/v1.0/resources/application.md
  api-reference/v1.0/resources/device.md
  api-reference/v1.0/resources/group.md
  api-reference/v1.0/resources/orgcontact.md
  api-reference/v1.0/resources/serviceprincipal.md
  api-reference/v1.0/resources/user.md
  concepts/aad-advanced-queries.md
  includes/filter-directory-objects.md
Labels: area: Azure AD, ready to merge, internal, area: query parameters

#18890 Product Backlog Item 2124976: SaaS App Tutorial: Graph APIs to configure SAML-based single sign-on Update
  concepts/application-saml-sso-configure-api.md
Labels: area: Azure AD, external, ready to merge, review requested, content review complete

#19352 Daily publishing 23 NOV 2022
  api-reference/beta/api/application-delta.md
  api-reference/beta/api/application-get.md
  api-reference/beta/api/application-list-extensionproperty.md
  api-reference/beta/api/application-list-federatedidentitycredentials.md
  api-reference/beta/api/application-list-owners.md
  api-reference/beta/api/application-list.md
  api-reference/beta/api/serviceprincipal-delta.md
  api-reference/beta/api/serviceprincipal-get.md
  api-reference/beta/api/serviceprincipal-list-approleassignedto.md
  api-reference/beta/api/serviceprincipal-list-approleassignments.md
  api-reference/beta/api/serviceprincipal-list-delegatedpermissionclassifications.md
  api-reference/beta/api/serviceprincipal-list-owners.md
  api-reference/beta/api/serviceprincipal-list.md
  api-reference/beta/api/tenantadmin-settings-update.md
  api-reference/beta/resources/application.md
  api-reference/beta/resources/device.md
  api-reference/beta/resources/group.md
  api-reference/beta/resources/orgcontact.md
  api-reference/beta/resources/privilegedidentitymanagementv3-overview.md
  api-reference/beta/resources/serviceprincipal.md
  api-reference/beta/resources/signinfrequencysessioncontrol.md
  api-reference/beta/resources/tenantadmin-settings.md
  api-reference/beta/resources/user.md
  api-reference/includes/permissions-applicationreadwriteownedby-disclaimer.md
  api-reference/v1.0/api/application-delta.md
  api-reference/v1.0/api/application-get.md
  api-reference/v1.0/api/application-list-extensionproperty.md
  api-reference/v1.0/api/application-list-owners.md
  api-reference/v1.0/api/application-list.md
  api-reference/v1.0/api/serviceprincipal-delta.md
  api-reference/v1.0/api/serviceprincipal-get.md
  api-reference/v1.0/api/serviceprincipal-list-approleassignedto.md
  api-reference/v1.0/api/serviceprincipal-list-approleassignments.md
  api-reference/v1.0/api/serviceprincipal-list-delegatedpermissionclassifications.md
  api-reference/v1.0/api/serviceprincipal-list-owners.md
  api-reference/v1.0/api/serviceprincipal-list.md
  api-reference/v1.0/resources/application.md
  api-reference/v1.0/resources/device.md
  api-reference/v1.0/resources/group.md
  api-reference/v1.0/resources/orgcontact.md
  api-reference/v1.0/resources/privilegedidentitymanagementv3-overview.md
  api-reference/v1.0/resources/serviceprincipal.md
  api-reference/v1.0/resources/signinfrequencysessioncontrol.md
  api-reference/v1.0/resources/user.md
  changelog/Microsoft.MicrosoftSearch.json
  concepts/aad-advanced-queries.md
  concepts/application-saml-sso-configure-api.md
  concepts/permissions-reference.md
  concepts/search-concept-searchall.md
  includes/filter-directory-objects.md
Labels: do not merge, internal

#19359 Edits in PR 19174
  api-reference/beta/api/planner-post-plans.md
  api-reference/beta/resources/plannerplan.md
  api-reference/beta/resources/plannerplancontainer.md
  api-reference/v1.0/api/planner-post-plans.md
  api-reference/v1.0/resources/plannerplan.md
  api-reference/v1.0/resources/plannerplancontainer.md
Labels: external

#19379 Examples of creating app roles
  concepts/tutorial-applications-basics.md
Labels: area: Azure AD, ready to merge, internal

#19378 Various updates - query parameters
  api-reference/beta/resources/group.md
  api-reference/beta/resources/serviceprincipal.md
  api-reference/beta/resources/user.md
  api-reference/v1.0/resources/group.md
  api-reference/v1.0/resources/serviceprincipal.md
  api-reference/v1.0/resources/user.md
  concepts/filter-query-parameter.md
  includes/filter-directory-objects.md
Labels: area: Azure AD, ready to merge, internal, area: query parameters

#19377 roleManagement license requirements for custom roles
  api-reference/beta/api/rbacapplication-post-roledefinitions.md
  api-reference/beta/api/unifiedroledefinition-delete.md
  api-reference/beta/api/unifiedroledefinition-update.md
  api-reference/v1.0/api/rbacapplication-post-roledefinitions.md
  api-reference/v1.0/api/unifiedroledefinition-delete.md
  api-reference/v1.0/api/unifiedroledefinition-update.md
Labels: area: Azure AD, ready to merge, internal

#19367 [Graph Search API] Update interleaving documents
  api-reference/beta/resources/search-api-overview.md
  concepts/search-concept-interleaving.md
  concepts/toc.yml
Labels: ready to merge, internal, Ignite22, content review complete

#19380 Daily publishing 24 NOV 2022
  api-reference/beta/api/rbacapplication-post-roledefinitions.md
  api-reference/beta/api/unifiedroledefinition-delete.md
  api-reference/beta/api/unifiedroledefinition-update.md
  api-reference/beta/resources/group.md
  api-reference/beta/resources/search-api-overview.md
  api-reference/beta/resources/serviceprincipal.md
  api-reference/beta/resources/user.md
  api-reference/v1.0/api/rbacapplication-post-roledefinitions.md
  api-reference/v1.0/api/unifiedroledefinition-delete.md
  api-reference/v1.0/api/unifiedroledefinition-update.md
  api-reference/v1.0/resources/group.md
  api-reference/v1.0/resources/serviceprincipal.md
  api-reference/v1.0/resources/user.md
  concepts/filter-query-parameter.md
  concepts/search-concept-interleaving.md
  concepts/toc.yml
  concepts/tutorial-applications-basics.md
  includes/filter-directory-objects.md
Labels: internal

#19382 Edits in PR 19209
  concepts/permissions-reference.md
Labels: external

#19383 Edits in PR 19174
  api-reference/beta/api/planner-post-plans.md
  api-reference/v1.0/api/planner-post-plans.md
  changelog/Microsoft.Office.Tasks.json
Labels: external

#19384 Edits in PR 19015
  api-reference/beta/api/businessscenariotask-update.md
  concepts/planner-task-rules-overview.md
  concepts/toc.yml
Labels: external
