Repository microsoftgraph/microsoft-graph-docs, pull requests merged in 2022-01, with the labels that each got.

#15386 Update directoryobject.md
  api-reference/v1.0/resources/directoryobject.md
Labels: external

#15384 Update directoryobject.md
  api-reference/beta/resources/directoryobject.md
Labels: external

#15402 fixed malformed urls
  api-reference/beta/api/externalmeetingregistrant-delete.md
  api-reference/beta/api/externalmeetingregistrant-list.md
  api-reference/beta/api/externalmeetingregistrant-post.md
  api-reference/v1.0/api/meetingattendancereport-get.md
Labels: ready to merge, internal, content review complete

#15401 Update office365groupsactivitydetail.md
  api-reference/beta/resources/office365groupsactivitydetail.md
Labels: external

#15399 Update conversationmember-add.md
  api-reference/v1.0/api/conversationmember-add.md
Labels: external

#14420 Document audio resource limited to OneDrive Personal.
  api-reference/beta/resources/audio.md
  api-reference/beta/resources/driveitem.md
  api-reference/v1.0/resources/audio.md
  api-reference/v1.0/resources/driveitem.md
Labels: ready to merge, internal, content review complete

#15403 Merge to publish.
  api-reference/beta/api/externalmeetingregistrant-delete.md
  api-reference/beta/api/externalmeetingregistrant-list.md
  api-reference/beta/api/externalmeetingregistrant-post.md
  api-reference/beta/resources/audio.md
  api-reference/beta/resources/driveitem.md
  api-reference/beta/resources/office365groupsactivitydetail.md
  api-reference/v1.0/api/conversationmember-add.md
  api-reference/v1.0/api/meetingattendancereport-get.md
  api-reference/v1.0/resources/audio.md
  api-reference/v1.0/resources/driveitem.md
Labels: internal

#15412 Update workinghours.md
  api-reference/v1.0/resources/workinghours.md
Labels: external

#15411 Update workinghours.md
  api-reference/beta/resources/workinghours.md
Labels: external

#15254 Adding teams/getAllMembers subscription resource
  api-reference/beta/api/subscription-delete.md
  api-reference/beta/api/subscription-get.md
  api-reference/beta/api/subscription-list.md
  api-reference/beta/api/subscription-post-subscriptions.md
  api-reference/beta/api/subscription-update.md
Labels: ready to merge, internal, content review complete

#15299 Update externalconnectors-externalitem-create.md
  api-reference/v1.0/api/externalconnectors-externalitem-create.md
Labels: ready to merge, internal, content review complete

#15415 Merge to publish.
  api-reference/beta/api/subscription-delete.md
  api-reference/beta/api/subscription-get.md
  api-reference/beta/api/subscription-list.md
  api-reference/beta/api/subscription-post-subscriptions.md
  api-reference/beta/api/subscription-update.md
  api-reference/beta/includes/snippets/csharp/assign-user-customsecurityattribute-string-csharp-snippets.md
  api-reference/beta/includes/snippets/csharp/create-custom-question-csharp-snippets.md
  api-reference/beta/includes/snippets/csharp/get-registration-csharp-snippets.md
  api-reference/beta/includes/snippets/csharp/list-custom-questions-csharp-snippets.md
  api-reference/beta/includes/snippets/go/assign-user-customsecurityattribute-string-go-snippets.md
  api-reference/beta/includes/snippets/go/create-custom-question-go-snippets.md
  api-reference/beta/includes/snippets/go/get-registration-go-snippets.md
  api-reference/beta/includes/snippets/go/list-custom-questions-go-snippets.md
  api-reference/beta/includes/snippets/java/create-custom-question-java-snippets.md
  api-reference/beta/includes/snippets/java/get-registration-java-snippets.md
  api-reference/beta/includes/snippets/java/list-custom-questions-java-snippets.md
  api-reference/beta/includes/snippets/javascript/assign-user-customsecurityattribute-string-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/create-custom-question-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/get-registration-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/list-custom-questions-javascript-snippets.md
  api-reference/beta/includes/snippets/objc/create-custom-question-objc-snippets.md
  api-reference/beta/includes/snippets/objc/get-registration-objc-snippets.md
  api-reference/beta/includes/snippets/objc/list-custom-questions-objc-snippets.md
  api-reference/beta/resources/workinghours.md
  api-reference/v1.0/api/externalconnectors-externalitem-create.md
  api-reference/v1.0/includes/snippets/go/create-accessreviewscheduledefinition-allusers-m365-aadrole-go-snippets.md
  api-reference/v1.0/includes/snippets/javascript/create-accessreviewscheduledefinition-allusers-m365-aadrole-javascript-snippets.md
  api-reference/v1.0/resources/workinghours.md
Labels: internal

#15214 Updated custom client code for Azure identity libs
  concepts/sdks/customize-client.md
Labels: ready to merge, internal

#15186 Adding a onBehalfOf property to chatMessageEntity
  api-reference/beta/api/channel-list-messages.md
  api-reference/beta/api/channel-post-messages.md
  api-reference/beta/api/chat-list-messages.md
  api-reference/beta/api/chat-post-messages.md
  api-reference/beta/api/chatmessage-delta.md
  api-reference/beta/api/chatmessage-get.md
  api-reference/beta/api/chatmessage-list-replies.md
  api-reference/beta/api/chatmessage-post-replies.md
  api-reference/beta/api/chatmessage-post.md
  api-reference/beta/resources/chatmessage.md
  changelog/Microsoft.Teams.Core.json
  concepts/system-messages.md
Labels: ready to merge, internal, content review complete

#15426 Update operation.md
  api-reference/v1.0/resources/operation.md
Labels: external

#15425 Update operation.md
  api-reference/beta/resources/operation.md
Labels: external

#13931 [Azure AD] [ELM] added attribute resource docs
  api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md
  api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md
  api-reference/beta/resources/accesspackagequestion.md
  api-reference/beta/resources/accesspackageresource.md
  api-reference/beta/resources/accesspackageresourceattribute.md
  api-reference/beta/resources/accesspackageresourceattributedestination.md
  api-reference/beta/resources/accesspackageresourceattributequestion.md
  api-reference/beta/resources/accesspackageresourceattributesource.md
  api-reference/beta/resources/accesspackageuserdirectoryattributestore.md
  changelog/Microsoft.DirectoryServices.json
Labels: area: azure/AAD, ready to merge, internal, content review complete

#15012 Add new properties to API documentation
  api-reference/beta/api/reportroot-getmailboxusagedetail.md
Labels: ready to merge, internal, content review complete

#15395 Added http request example
  api-reference/beta/api/federatedidentitycredential-delete.md
  api-reference/beta/api/federatedidentitycredential-get.md
  api-reference/beta/api/federatedidentitycredential-update.md
Labels: area: azure/AAD, ready to merge, internal, content review complete

#15406 Minor doc fixes
  api-reference/beta/api/profilephoto-get.md
  api-reference/beta/api/profilephoto-update.md
  api-reference/beta/resources/application.md
  api-reference/beta/resources/profilephoto.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/profilephoto-get.md
  api-reference/v1.0/api/profilephoto-update.md
  api-reference/v1.0/resources/application.md
  api-reference/v1.0/resources/profilephoto.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.AAD.Reporting.json
  changelog/Microsoft.DirectoryServices.json
  concepts/known-issues.md
Labels: area: azure/AAD, ready to merge, internal, review feedback addressed

#15383 Update reports documentation to clarify that optional parameters cannot be omitted
  api-reference/beta/api/reports-getgrouparchivedprintjobs.md
  api-reference/beta/api/reports-getprinterarchivedprintjobs.md
  api-reference/beta/api/reports-getuserarchivedprintjobs.md
  api-reference/v1.0/api/reports-getgrouparchivedprintjobs.md
  api-reference/v1.0/api/reports-getprinterarchivedprintjobs.md
  api-reference/v1.0/api/reports-getuserarchivedprintjobs.md
  concepts/universal-print-concept-overview.md
Labels: ready to merge, internal, area: universal print

#15210 Updated Teams MSAL reference
  concepts/toolkit/providers/teams-msal2.md
Labels: external, review requested

#15422 Corrected scope name for Microsoft Graph
  concepts/permissions-reference.md
Labels: external, ready to merge, content review complete

#14219 Update Java Code Snippet for Consistency
  concepts/sdks/customize-client.md
Labels: external, do not merge

#15420 Remove the mention of 'size' in the GET /team/{id}/photo API docs since it's unsupported.
  api-reference/beta/api/team-get-photo.md
Labels: ready to merge, internal, content review complete

#15435 Merge to publish.
  api-reference/beta/api/reports-getgrouparchivedprintjobs.md
  api-reference/beta/api/reports-getprinterarchivedprintjobs.md
  api-reference/beta/api/reports-getuserarchivedprintjobs.md
  api-reference/beta/api/team-get-photo.md
  api-reference/v1.0/api/reports-getgrouparchivedprintjobs.md
  api-reference/v1.0/api/reports-getprinterarchivedprintjobs.md
  api-reference/v1.0/api/reports-getuserarchivedprintjobs.md
  concepts/permissions-reference.md
  concepts/sdks/customize-client.md
  concepts/toolkit/providers/teams-msal2.md
  concepts/universal-print-concept-overview.md
Labels: internal

#15408 What's new in the last 3 weeks.
  concepts/delta-query-overview.md
  concepts/whats-new-overview.md
Labels: do not merge, internal

#15437 Refresh what's new.
  concepts/delta-query-overview.md
  concepts/whats-new-overview.md
Labels: internal

#15457 Update channel-delete-members.md
  api-reference/beta/api/channel-delete-members.md
Labels: external

#15456 Update channel-delete-members.md
  api-reference/v1.0/api/channel-delete-members.md
Labels: external

#15455 Update teams-api-overview.md
  api-reference/v1.0/resources/teams-api-overview.md
Labels: external

#15373 Update person.md
  concepts/toolkit/components/person.md
Labels: ready to merge, internal, content review complete

#15419 Amanda han123 fix excel graph documentation bug
  api-reference/beta/api/table-post-rows.md
  api-reference/beta/api/workbook-tablerowoperationresult.md
  api-reference/v1.0/api/table-post-rows.md
  api-reference/v1.0/api/workbook-tablerowoperationresult.md
Labels: ready to merge, internal, content review complete

#15442 Update directoryaudit-list.md
  api-reference/v1.0/api/directoryaudit-list.md
Labels: external, ready to merge, content review complete

#15445 Minor doc fixes
  api-reference/beta/api/directoryaudit-get.md
  api-reference/beta/api/directoryaudit-list.md
  api-reference/beta/api/provisioningobjectsummary-list.md
  api-reference/beta/api/signin-get.md
  api-reference/beta/api/signin-list.md
  api-reference/beta/api/user-list.md
  api-reference/beta/resources/user.md
  api-reference/v1.0/api/directoryaudit-get.md
  api-reference/v1.0/api/provisioningobjectsummary-list.md
  api-reference/v1.0/api/signin-get.md
  api-reference/v1.0/api/signin-list.md
  api-reference/v1.0/resources/user.md
Labels: area: azure/AAD, ready to merge, internal

#15465 Expose subject rights requests API in what's new, as permissions have been deployed.
  api-reference/beta/resources/social-overview.md
  api-reference/beta/resources/subjectrightsrequest-subjectrightsrequestapioverview.md
  api-reference/v1.0/resources/subjectrightsrequest-subjectrightsrequestapioverview.md
  changelog/Microsoft.Compliance.DataSubjectRequest.json
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: internal

#15466 Refresh what's new to better expose subject rights request API.
  api-reference/beta/resources/social-overview.md
  api-reference/beta/resources/subjectrightsrequest-subjectrightsrequestapioverview.md
  api-reference/v1.0/resources/subjectrightsrequest-subjectrightsrequestapioverview.md
  changelog/Microsoft.Compliance.DataSubjectRequest.json
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: internal

#15476 Update schedule-list-shifts.md
  api-reference/beta/api/schedule-list-shifts.md
Labels: external

#15475 Update schedule-list-shifts.md
  api-reference/v1.0/api/schedule-list-shifts.md
Labels: external

#15474 Update shift.md
  api-reference/beta/resources/shift.md
Labels: external

#15468 Change channel to channels
  concepts/system-messages.md
Labels: external

#15467 Update people.md
  concepts/toolkit/components/people.md
Labels: ready to merge, internal

#15478 Merge to publish.
  api-reference/beta/api/schedule-list-shifts.md
  api-reference/beta/resources/shift.md
  api-reference/v1.0/api/schedule-list-shifts.md
  concepts/system-messages.md
  concepts/toolkit/components/people.md
Labels: internal

#15377 Fix address examples in Microsoft Graph Documentation : Bookings API v1.0
  api-reference/v1.0/api/bookingappointment-get.md
  api-reference/v1.0/api/bookingbusiness-list-appointments.md
  api-reference/v1.0/api/bookingbusiness-list-calendarview.md
  api-reference/v1.0/api/bookingbusiness-list-services.md
  api-reference/v1.0/api/bookingbusiness-post-appointments.md
  api-reference/v1.0/api/bookingbusiness-post-services.md
  api-reference/v1.0/api/bookingservice-get.md
Labels: ready to merge, internal, content review complete

#15398 Adding OrderBy Query Option to Chat.GetMessages Requests
  api-reference/beta/api/chat-list-messages.md
  changelog/Microsoft.Teams.Core.json
Labels: ready to merge, internal, content review complete

#15491 Update contact.md
  api-reference/v1.0/resources/contact.md
Labels: external

#15488 Minor doc fixes
  api-reference/beta/api/subscription-post-subscriptions.md
  api-reference/beta/resources/orgcontact.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/subscription-post-subscriptions.md
  api-reference/v1.0/resources/orgcontact.md
  api-reference/v1.0/toc.yml
Labels: area: azure/AAD, ready to merge, internal

#15481 Fix url in http request for v1.0
  api-reference/v1.0/api/bookingappointment-cancel.md
  api-reference/v1.0/api/bookingappointment-delete.md
  api-reference/v1.0/api/bookingappointment-get.md
  api-reference/v1.0/api/bookingappointment-update.md
  api-reference/v1.0/api/bookingbusiness-delete.md
  api-reference/v1.0/api/bookingbusiness-get.md
  api-reference/v1.0/api/bookingbusiness-list-appointments.md
  api-reference/v1.0/api/bookingbusiness-list-calendarview.md
  api-reference/v1.0/api/bookingbusiness-list-customers.md
  api-reference/v1.0/api/bookingbusiness-list-customquestions.md
  api-reference/v1.0/api/bookingbusiness-list-services.md
  api-reference/v1.0/api/bookingbusiness-list-staffmembers.md
  api-reference/v1.0/api/bookingbusiness-list.md
  api-reference/v1.0/api/bookingbusiness-post-appointments.md
  api-reference/v1.0/api/bookingbusiness-post-bookingbusinesses.md
  api-reference/v1.0/api/bookingbusiness-post-customers.md
  api-reference/v1.0/api/bookingbusiness-post-customquestions.md
  api-reference/v1.0/api/bookingbusiness-post-services.md
  api-reference/v1.0/api/bookingbusiness-post-staffmembers.md
  api-reference/v1.0/api/bookingbusiness-publish.md
  api-reference/v1.0/api/bookingbusiness-unpublish.md
  api-reference/v1.0/api/bookingbusiness-update.md
  api-reference/v1.0/api/bookingcurrency-get.md
  api-reference/v1.0/api/bookingcurrency-list.md
  api-reference/v1.0/api/bookingcustomer-delete.md
  api-reference/v1.0/api/bookingcustomer-get.md
  api-reference/v1.0/api/bookingcustomer-update.md
  api-reference/v1.0/api/bookingcustomquestion-delete.md
  api-reference/v1.0/api/bookingcustomquestion-get.md
  api-reference/v1.0/api/bookingcustomquestion-update.md
  api-reference/v1.0/api/bookingservice-delete.md
  api-reference/v1.0/api/bookingservice-get.md
  api-reference/v1.0/api/bookingservice-update.md
  api-reference/v1.0/api/bookingstaffmember-delete.md
  api-reference/v1.0/api/bookingstaffmember-get.md
  api-reference/v1.0/api/bookingstaffmember-update.md
Labels: internal, content review complete

#15510 Update social-intel-concept-overview.md
  concepts/social-intel-concept-overview.md
Labels: external

#15509 Update toc.yml
  api-reference/beta/toc.yml
Labels: external

#15508 Update toc.yml
  api-reference/v1.0/toc.yml
Labels: external

#15498 Update oauth2permissiongrant-delete.md
  api-reference/v1.0/api/oauth2permissiongrant-delete.md
Labels: external

#15505 Minor doc fixes
  api-reference/beta/api/synchronization-synchronizationjob-pause.md
  api-reference/beta/api/synchronization-synchronizationjob-restart.md
  api-reference/beta/resources/accessreviewinstancedecisionitem.md
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
Labels: area: azure/AAD, ready to merge, internal

#15495 Update usersettings-update.md
  api-reference/v1.0/api/usersettings-update.md
Labels: external, ready to merge

#15512 Merge to publish.
  api-reference/beta/api/attachment-createuploadsession.md
  api-reference/beta/api/synchronization-synchronizationjob-pause.md
  api-reference/beta/api/synchronization-synchronizationjob-restart.md
  api-reference/beta/resources/accessreviewinstancedecisionitem.md
  api-reference/beta/resources/attachmentitem.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/attachment-createuploadsession.md
  api-reference/v1.0/api/oauth2permissiongrant-delete.md
  api-reference/v1.0/api/usersettings-update.md
  api-reference/v1.0/resources/attachmentitem.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.Exchange.json
  concepts/social-intel-concept-overview.md
Labels: internal

#15513 Add entries that were overwritten in recent Intune drop.
  changelog/Microsoft.Intune.json
Labels: internal

#15417 Adding new conversation types
  api-reference/beta/api/chat-post.md
  api-reference/beta/resources/anonymousguestconversationmember.md
  api-reference/beta/resources/conversationmember.md
  api-reference/beta/resources/microsoftaccountuserconversationmember.md
  api-reference/beta/resources/skypeforbusinessuserconversationmember.md
  api-reference/beta/resources/skypeuserconversationmember.md
  api-reference/v1.0/api/chat-post.md
  changelog/Microsoft.Teams.Core.json
Labels: ready to merge, internal, content review complete

#15520 Update migration article - property differences
  concepts/migrate-azure-ad-graph-property-differences.md
  concepts/migrate-azure-ad-graph-resource-differences.md
Labels: area: Azure AD, ready to merge, internal

#15396 2022 01 04 mahage custodian weburl
  api-reference/beta/api/ediscovery-custodian-list-usersources.md
  api-reference/beta/api/ediscovery-custodian-post-usersources.md
  api-reference/beta/api/ediscovery-usersource-get.md
  api-reference/beta/resources/ediscovery-usersource.md
  changelog/Microsoft.Compliance.Ediscovery.json
Labels: ready to merge, internal, content review complete

#15525 Fix role issue in CreateJob for printerShare
  api-reference/beta/api/printershare-post-jobs.md
  api-reference/v1.0/api/printershare-post-jobs.md
Labels: ready to merge, internal, area: universal print

#15529 Merge to publish.
  api-reference/beta/api/chat-post.md
  api-reference/beta/api/ediscovery-custodian-list-usersources.md
  api-reference/beta/api/ediscovery-custodian-post-usersources.md
  api-reference/beta/api/ediscovery-usersource-get.md
  api-reference/beta/api/printershare-post-jobs.md
  api-reference/beta/resources/anonymousguestconversationmember.md
  api-reference/beta/resources/conversationmember.md
  api-reference/beta/resources/ediscovery-usersource.md
  api-reference/beta/resources/microsoftaccountuserconversationmember.md
  api-reference/beta/resources/skypeforbusinessuserconversationmember.md
  api-reference/beta/resources/skypeuserconversationmember.md
  api-reference/v1.0/api/chat-post.md
  api-reference/v1.0/api/printershare-post-jobs.md
  changelog/Microsoft.Compliance.Ediscovery.json
  changelog/Microsoft.Intune.json
  changelog/Microsoft.Teams.Core.json
  concepts/migrate-azure-ad-graph-property-differences.md
  concepts/migrate-azure-ad-graph-resource-differences.md
Labels: do not merge, internal

#15551 LinkFix: microsoft-graph-docs (2022-01) - 1
  api-reference/v1.0/api/serviceprincipal-update.md
  api-reference/v1.0/api/team-get-installedapps.md
  api-reference/v1.0/api/team-get-members.md
  api-reference/v1.0/api/team-sendactivitynotification.md
  api-reference/v1.0/api/team-update.md
  api-reference/v1.0/resources/security-api-overview.md
  api-reference/v1.0/resources/serviceprincipal.md
  concepts/assignments-submissions-states-transition.md
  concepts/data-connect-pam.md
  concepts/index.yml
  concepts/known-issues.md
  concepts/teams-licenses.md
  concepts/toolkit/components/todo.md
  concepts/windowsupdates-software-updates.md
Labels: external

#15549 Update toc.yml
  api-reference/beta/toc.yml
Labels: external

#15548 Update toc.yml
  api-reference/v1.0/toc.yml
Labels: external

#11933 add resource name to changelog descriptions for EM app permissions
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, ready to merge, internal, content review complete

#14668 service health communications API: api and resource, toc files update for attachment
  api-reference/beta/api/serviceannouncement-list-healthoverviews.md
  api-reference/beta/api/serviceannouncement-list-issues.md
  api-reference/beta/api/serviceannouncement-list-messages.md
  api-reference/beta/api/serviceannouncementattachment-get.md
  api-reference/beta/api/servicehealthissue-incidentreport.md
  api-reference/beta/api/serviceupdatemessage-list-attachments.md
  api-reference/beta/resources/service-communications-api-overview.md
  api-reference/beta/resources/serviceannouncementattachment.md
  api-reference/beta/resources/servicehealth.md
  api-reference/beta/resources/servicehealthissue.md
  api-reference/beta/resources/serviceupdatemessage.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/serviceannouncement-list-healthoverviews.md
  api-reference/v1.0/api/serviceannouncement-list-issues.md
  api-reference/v1.0/api/serviceannouncement-list-messages.md
  api-reference/v1.0/api/serviceannouncementattachment-get.md
  api-reference/v1.0/api/servicehealthissue-incidentreport.md
  api-reference/v1.0/api/serviceupdatemessage-list-attachments.md
  api-reference/v1.0/resources/service-communications-api-overview.md
  api-reference/v1.0/resources/serviceannouncementattachment.md
  api-reference/v1.0/resources/servicehealth.md
  api-reference/v1.0/resources/servicehealthissue.md
  api-reference/v1.0/resources/serviceupdatemessage.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.M365ServiceCommsPlatform.json
  concepts/throttling.md
Labels: ready to merge, internal, content review complete, schema live

#15532 Minor doc fixes
  api-reference/beta/api/administrativeunit-get.md
  api-reference/beta/api/administrativeunit-list.md
  api-reference/beta/api/directoryrole-get.md
  api-reference/beta/api/directoryrole-list.md
  api-reference/beta/resources/administrativeunit.md
  api-reference/beta/resources/directoryrole.md
  api-reference/v1.0/api/administrativeunit-get.md
  api-reference/v1.0/api/administrativeunit-list.md
  api-reference/v1.0/api/directoryrole-get.md
  api-reference/v1.0/api/directoryrole-list.md
  api-reference/v1.0/resources/administrativeunit.md
  api-reference/v1.0/resources/directoryrole.md
  concepts/aad-advanced-queries.md
  concepts/deployments.md
  concepts/query-parameters.md
Labels: area: Azure AD, ready to merge, internal

#15360 Update M365 usage report API list
  api-reference/beta/resources/report.md
  changelog/Microsoft.O365Reporting.json
Labels: ready to merge, internal, content review complete, schema live

#15550 LinkFix: microsoft-graph-docs (2022-01) - 0
  api-reference/beta/api/application-post-calls.md
  api-reference/beta/api/application-update.md
  api-reference/beta/api/channel-delete.md
  api-reference/beta/api/channel-list.md
  api-reference/beta/api/chat-delete-installedapps.md
  api-reference/beta/api/chat-delete-members.md
  api-reference/beta/api/chat-delete-tabs.md
  api-reference/beta/api/chat-get-installedapps.md
  api-reference/beta/api/chat-get-members.md
  api-reference/beta/api/chat-get-tabs.md
  api-reference/beta/api/chat-get.md
  api-reference/beta/api/chat-list-installedapps.md
  api-reference/beta/api/chat-list-members.md
  api-reference/beta/api/chat-list-permissiongrants.md
  api-reference/beta/api/chat-patch-tabs.md
  api-reference/beta/api/chat-patch.md
  api-reference/beta/api/chat-post-installedapps.md
  api-reference/beta/api/chat-post-members.md
  api-reference/beta/api/chat-post-tabs.md
  api-reference/beta/api/chat-sendactivitynotification.md
  api-reference/beta/api/chat-teamsappinstallation-upgrade.md
  api-reference/beta/api/ediscovery-sourcecollection-estimatestatistics.md
  api-reference/beta/api/serviceprincipal-update.md
  api-reference/beta/api/team-archive.md
  api-reference/beta/api/team-get-installedapps.md
  api-reference/beta/api/team-get-members.md
  api-reference/beta/api/team-get-photo.md
  api-reference/beta/api/team-get.md
  api-reference/beta/api/team-sendactivitynotification.md
  api-reference/beta/api/team-unarchive.md
  api-reference/beta/api/team-update.md
  api-reference/beta/config/link-validation-config.json
  api-reference/beta/resources/cloudappsecuritysessioncontrol.md
  api-reference/beta/resources/connector.md
  api-reference/beta/resources/connectorgroup.md
  api-reference/beta/resources/contentType.md
  api-reference/beta/resources/ediscovery-ediscoveryapioverview.md
  api-reference/beta/resources/ediscovery-noncustodialdatasource.md
  api-reference/beta/resources/ediscovery-sourcecollection.md
  api-reference/beta/resources/externalconnectors-displaytemplate.md
  api-reference/beta/resources/group.md
  api-reference/beta/resources/onpremisespublishing.md
  api-reference/beta/resources/onpremisespublishingprofile-root.md
  api-reference/beta/resources/onpremisespublishingprofile.md
  api-reference/beta/resources/searchrequest.md
  api-reference/beta/resources/security-api-overview.md
  api-reference/beta/resources/serviceprincipal.md
  api-reference/v1.0/api/channel-delete.md
  api-reference/v1.0/api/channel-list.md
  api-reference/v1.0/api/chat-get-members.md
  api-reference/v1.0/api/conversationmember-get.md
Labels: external

#15555 Update conversationmembers-add.md
  api-reference/beta/api/conversationmembers-add.md
  api-reference/v1.0/api/conversationmembers-add.md
Labels: external

#15560 Remove extraneous beta from Get team photo doc
  api-reference/beta/api/team-get-photo.md
Labels: ready to merge, internal

#15569 Update site.md
  api-reference/v1.0/resources/site.md
Labels: external

#15571 Update site.md
  api-reference/beta/resources/site.md
Labels: external

#15573 Update toc.yml
  api-reference/v1.0/toc.yml
Labels: external

#15572 Update toc.yml
  api-reference/beta/toc.yml
Labels: external

#14738 Minor updates to Access Review Beta
  api-reference/beta/resources/accessreviewinstancedecisionitem.md
  api-reference/beta/resources/accessreviewrecommendationinsightsetting.md
  api-reference/beta/resources/accessreviewschedulesettings.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/governanceinsight.md
  api-reference/beta/resources/userlastsignInrecommendationinsightsetting.md
  api-reference/beta/resources/usersigninInsight.md
  changelog/Microsoft.IdentityGovernance.AccessReviews.json
Labels: area: Azure AD, ready to merge, content review complete, schema live

#15182 added Conditional Access Resilience Defaults to session control list …
  api-reference/v1.0/resources/conditionalaccesssessioncontrols.md
  changelog/Microsoft.AAD.Reporting.json
Labels: area: Azure AD, ready to merge, internal, content review complete

#15284 Updates for Azure AD reporting Q2 FY22
  api-reference/beta/api/signin-get.md
  api-reference/beta/api/signin-list.md
  api-reference/beta/resources/authenticationcontext.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/sessionlifetimepolicy.md
  api-reference/beta/resources/signin.md
  changelog/Microsoft.AAD.Reporting.json
  changelog/Microsoft.IdentityProtectionServices.json
Labels: area: Azure AD, ready to merge, internal, content review complete

#15588 Update toc.yml
  api-reference/beta/toc.yml
Labels: external

#15587 Update toc.yml
  api-reference/v1.0/toc.yml
Labels: external

#14938 Added documentation for content type sync apis
  api-reference/beta/api/contenttype-addcopyfromcontenttypehub.md
  api-reference/beta/api/contenttype-getcompatiblehubcontenttypes.md
  api-reference/beta/api/list-list-operations.md
  api-reference/beta/api/richlongrunningoperation-get.md
  api-reference/beta/api/site-list-operations.md
  api-reference/beta/resources/contentType.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/list.md
  api-reference/beta/resources/richlongrunningoperation.md
  api-reference/beta/resources/site.md
  api-reference/beta/toc.yml
  changelog/Microsoft.FileServices.json
Labels: ready to merge, internal, content review complete

#15036 Minor updates to access review beta to expose top-level decisions navigation route
  api-reference/beta/api/accessreviewinstance-list-decisions.md
  api-reference/beta/api/accessreviewinstancedecisionitem-recordalldecisions.md
  api-reference/beta/resources/accessreviewinstancedecisionitem.md
  api-reference/beta/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md
  api-reference/beta/resources/accessreviewinstancedecisionitemazureroleresource.md
  api-reference/beta/resources/accessreviewinstancedecisionitemresource.md
  api-reference/beta/resources/accessreviewinstancedecisionitemserviceprincipalresource.md
  api-reference/beta/toc.yml
  changelog/Microsoft.IdentityGovernance.AccessReviews.json
Labels: area: Azure AD, ready to merge, content review complete, schema live, review feedback addressed

#15239 Expose contactedReviewers API in v1.0 and misc. updates
  api-reference/v1.0/api/accessreviewinstance-list-contactedreviewers.md
  api-reference/v1.0/resources/accessreviewinstance.md
  api-reference/v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md
  api-reference/v1.0/resources/accessreviewinstancedecisionitemazureroleresource.md
  api-reference/v1.0/resources/accessreviewinstancedecisionitemresource.md
  api-reference/v1.0/resources/accessreviewinstancedecisionitemserviceprincipalresource.md
  api-reference/v1.0/resources/accessreviewreviewer.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.IdentityGovernance.AccessReviews.json
Labels: area: Azure AD, ready to merge, internal, content review complete, schema live

#15506 [Azure ABAC] Custom security attributes permission updates
  api-reference/beta/api/attributeset-get.md
  api-reference/beta/api/customsecurityattributedefinition-get.md
  api-reference/beta/api/customsecurityattributedefinition-list-allowedvalues.md
  api-reference/beta/api/directory-list-attributesets.md
  api-reference/beta/api/directory-list-customsecurityattributedefinitions.md
  concepts/custom-security-attributes-examples.md
Labels: area: Azure AD, ready to merge, internal

#15533 Updating reauthorizationRequired notifications
  api-reference/beta/api/subscription-update.md
  api-reference/v1.0/api/subscription-update.md
  concepts/webhooks-lifecycle.md
Labels: area: Azure AD, ready to merge, internal, content review complete

#15596 Minor doc fixes
  api-reference/beta/api/group-post-owners.md
  api-reference/beta/resources/authenticationmethods-overview.md
  api-reference/beta/resources/group.md
  api-reference/v1.0/api/group-post-owners.md
  api-reference/v1.0/resources/authenticationmethods-overview.md
  api-reference/v1.0/resources/group.md
  concepts/query-parameters.md
Labels: area: Azure AD, ready to merge, internal

#15599 Merge to publish.
  api-reference/beta/api/attributeset-get.md
  api-reference/beta/api/customsecurityattributedefinition-get.md
  api-reference/beta/api/customsecurityattributedefinition-list-allowedvalues.md
  api-reference/beta/api/directory-list-attributesets.md
  api-reference/beta/api/directory-list-customsecurityattributedefinitions.md
  api-reference/beta/api/group-post-owners.md
  api-reference/beta/api/subscription-update.md
  api-reference/beta/resources/authenticationmethods-overview.md
  api-reference/beta/resources/group.md
  api-reference/v1.0/api/group-post-owners.md
  api-reference/v1.0/api/subscription-update.md
  api-reference/v1.0/resources/authenticationmethods-overview.md
  api-reference/v1.0/resources/group.md
  concepts/custom-security-attributes-examples.md
  concepts/query-parameters.md
  concepts/webhooks-lifecycle.md
Labels: internal

#15102 Added missing permissions to Universal Print topics
  api-reference/beta/api/print-list-services.md
  api-reference/beta/api/printservice-get.md
  api-reference/beta/api/printservice-list-endpoints.md
  api-reference/beta/api/printserviceendpoint-get.md
  api-reference/v1.0/api/print-list-services.md
  api-reference/v1.0/api/printservice-get.md
  api-reference/v1.0/api/printservice-list-endpoints.md
  api-reference/v1.0/api/printserviceendpoint-get.md
Labels: do not merge, internal, content review in progress, review feedback addressed

#15519 Added PS cmd to list available Graph modules
  concepts/powershell/installation.md
Labels: internal

#15625 Update team-get.md
  api-reference/v1.0/api/team-get.md
Labels: external

#15624 Update team-get.md
  api-reference/beta/api/team-get.md
Labels: external

#15623 Update group-post-events.md
  api-reference/beta/api/group-post-events.md
Labels: external

#15622 Update group-post-events.md
  api-reference/v1.0/api/group-post-events.md
Labels: external

#15181 Dawoo/auth methods activity api docs
  api-reference/beta/api/authenticationmethodsroot-list-userregistrationdetails.md
  api-reference/beta/api/userregistrationdetails-get.md
  api-reference/beta/resources/authenticationmethods-usage-insights-overview.md
  api-reference/beta/resources/authenticationmethodsroot.md
  api-reference/beta/resources/userregistrationdetails.md
  api-reference/beta/toc.yml
  changelog/Microsoft.AAD.Reporting.json
Labels: area: Azure AD, ready to merge, content review complete, schema live

#15584 Deprecate the me/devices endpoint
  api-reference/beta/api/get-device-command-status.md
  api-reference/beta/api/send-device-command.md
  api-reference/beta/api/user-list-devices.md
  api-reference/beta/resources/project-rome-overview.md
  api-reference/beta/toc.yml
  changelog/Microsoft.DirectoryServices.json
Labels: area: rome, ready to merge, internal

#15608 Minor fixes to registration details in TOC
  api-reference/beta/toc.yml
Labels: area: Azure AD, area: reports, ready to merge, internal

#15609 Minor doc fixes
  api-reference/beta/api/directory-deleteditems-get.md
  api-reference/beta/api/directory-deleteditems-list.md
  api-reference/beta/api/group-delete-members.md
  api-reference/beta/api/group-delete-owners.md
  api-reference/beta/api/group-post-members.md
  api-reference/beta/api/group-post-owners.md
  api-reference/beta/resources/group.md
  api-reference/beta/resources/rbacapplicationmultiple.md
  api-reference/v1.0/api/directory-deleteditems-get.md
  api-reference/v1.0/api/directory-deleteditems-list.md
  api-reference/v1.0/api/group-delete-members.md
  api-reference/v1.0/api/group-delete-owners.md
  api-reference/v1.0/api/group-post-members.md
  api-reference/v1.0/api/group-post-owners.md
  api-reference/v1.0/resources/group.md
  api-reference/v1.0/resources/groups-overview.md
  concepts/known-issues.md
Labels: area: Azure AD, ready to merge, internal

#15627 Merge to publish.
  api-reference/beta/api/authenticationmethodsroot-list-userregistrationdetails.md
  api-reference/beta/api/directory-deleteditems-get.md
  api-reference/beta/api/directory-deleteditems-list.md
  api-reference/beta/api/get-device-command-status.md
  api-reference/beta/api/group-delete-members.md
  api-reference/beta/api/group-delete-owners.md
  api-reference/beta/api/group-post-events.md
  api-reference/beta/api/group-post-members.md
  api-reference/beta/api/group-post-owners.md
  api-reference/beta/api/print-list-services.md
  api-reference/beta/api/printservice-get.md
  api-reference/beta/api/printservice-list-endpoints.md
  api-reference/beta/api/printserviceendpoint-get.md
  api-reference/beta/api/send-device-command.md
  api-reference/beta/api/team-get.md
  api-reference/beta/api/user-list-devices.md
  api-reference/beta/api/userregistrationdetails-get.md
  api-reference/beta/resources/authenticationmethods-usage-insights-overview.md
  api-reference/beta/resources/authenticationmethodsroot.md
  api-reference/beta/resources/group.md
  api-reference/beta/resources/project-rome-overview.md
  api-reference/beta/resources/rbacapplicationmultiple.md
  api-reference/beta/resources/userregistrationdetails.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/directory-deleteditems-get.md
  api-reference/v1.0/api/directory-deleteditems-list.md
  api-reference/v1.0/api/group-delete-members.md
  api-reference/v1.0/api/group-delete-owners.md
  api-reference/v1.0/api/group-post-events.md
  api-reference/v1.0/api/group-post-members.md
  api-reference/v1.0/api/group-post-owners.md
  api-reference/v1.0/api/print-list-services.md
  api-reference/v1.0/api/printservice-get.md
  api-reference/v1.0/api/printservice-list-endpoints.md
  api-reference/v1.0/api/printserviceendpoint-get.md
  api-reference/v1.0/api/team-get.md
  api-reference/v1.0/resources/group.md
  api-reference/v1.0/resources/groups-overview.md
  changelog/Microsoft.AAD.Reporting.json
  changelog/Microsoft.DirectoryServices.json
  concepts/known-issues.md
  concepts/powershell/installation.md
Labels: internal

#15639 Fixed minor typo
  api-reference/v1.0/resources/planneruser.md
Labels: external

#14800 Create synchronization-secrets.md
  api-reference/beta/api/synchronization-synchronization-acquireaccesstoken.md
  api-reference/beta/api/synchronization-synchronization-secrets.md
  api-reference/beta/api/synchronization-synchronizationjob-validatecredentials.md
  api-reference/beta/resources/educationsynchronizationdataprovider.md
  api-reference/beta/resources/synchronization-synchronization.md
  api-reference/beta/resources/synchronization-synchronizationsecretkeystringvaluepair.md
  api-reference/beta/toc.yml
Labels: area: Azure AD, ready to merge, internal

#15581 Update extended-properties-overview.md
  api-reference/beta/resources/extended-properties-overview.md
  api-reference/v1.0/resources/extended-properties-overview.md
Labels: ready to merge, internal, content review complete

#15631 Minor doc fixes
  api-reference/beta/api/accesspackage-filterbycurrentuser.md
  api-reference/beta/resources/accesspackage-accesspackagefilterbycurrentuseroptions.md
  api-reference/beta/resources/enums.md
Labels: area: Azure AD, ready to merge, internal

#15472 Scheduled Access Review History Definition
  api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md
  api-reference/beta/api/accessreviewhistorydefinition-get.md
  api-reference/beta/api/accessreviewhistorydefinition-list-instances.md
  api-reference/beta/api/accessreviewhistoryinstance-generatedownloaduri.md
  api-reference/beta/api/accessreviewset-list-historydefinitions.md
  api-reference/beta/api/accessreviewset-post-historydefinitions.md
  api-reference/beta/resources/accessreviewhistorydefinition.md
  api-reference/beta/resources/accessreviewhistoryinstance.md
  api-reference/beta/resources/accessreviewhistoryschedulesettings.md
  api-reference/beta/resources/accessreviewsv2-overview.md
  api-reference/beta/toc.yml
  changelog/Microsoft.IdentityGovernance.AccessReviews.json
Labels: area: Azure AD, ready to merge, internal, content review complete

#15658 Update calendar.md
  api-reference/v1.0/resources/calendar.md
Labels: external

#15657 Update calendar.md
  api-reference/beta/resources/calendar.md
Labels: external

#15453 updated docs for clientApplications
  api-reference/beta/resources/conditionalaccessclientapplications.md
  api-reference/beta/resources/conditionalaccessconditionset.md
  changelog/Microsoft.IdentityProtectionServices.json
Labels: area: Azure AD, ready to merge, internal, content review complete

#15536 Update max staff count in resources
  api-reference/beta/resources/bookingstaffmember.md
  api-reference/v1.0/resources/bookingstaffmember.md
Labels: ready to merge, internal, content review complete

#15554 Add user id property to Teams usage report APIs
  api-reference/beta/api/reportroot-getteamsdeviceusageuserdetail.md
  api-reference/beta/api/reportroot-getteamsuseractivityuserdetail.md
  api-reference/v1.0/api/reportroot-getteamsdeviceusageuserdetail.md
  api-reference/v1.0/api/reportroot-getteamsuseractivityuserdetail.md
  changelog/Microsoft.O365Reporting.json
Labels: ready to merge, internal, content review complete, schema live

#15630 Add the deprecation notice in all AR v1 docs
  api-reference/beta/api/accessreview-addreviewer.md
  api-reference/beta/api/accessreview-apply.md
  api-reference/beta/api/accessreview-create.md
  api-reference/beta/api/accessreview-delete.md
  api-reference/beta/api/accessreview-get.md
  api-reference/beta/api/accessreview-list.md
  api-reference/beta/api/accessreview-listdecisions.md
  api-reference/beta/api/accessreview-listmydecisions.md
  api-reference/beta/api/accessreview-listreviewers.md
  api-reference/beta/api/accessreview-removereviewer.md
  api-reference/beta/api/accessreview-reset.md
  api-reference/beta/api/accessreview-sendreminder.md
  api-reference/beta/api/accessreview-stop.md
  api-reference/beta/api/accessreview-update.md
  api-reference/beta/api/businessflowtemplate-list.md
  api-reference/beta/api/program-create.md
  api-reference/beta/api/program-delete.md
  api-reference/beta/api/program-list.md
  api-reference/beta/api/program-listcontrols.md
  api-reference/beta/api/program-update.md
  api-reference/beta/api/programcontrol-create.md
  api-reference/beta/api/programcontrol-delete.md
  api-reference/beta/api/programcontrol-list.md
  api-reference/beta/api/programcontroltype-list.md
  api-reference/beta/resources/autoreviewsettings.md
  api-reference/beta/resources/businessflowtemplate.md
  api-reference/beta/resources/program.md
  api-reference/beta/resources/programcontrol.md
  api-reference/beta/resources/programcontroltype.md
  api-reference/beta/resources/programresource.md
  api-reference/includes/accessreviews-disclaimer.md
Labels: area: Azure AD, ready to merge, area: governance

#15644 Minor doc fixes
  api-reference/beta/api/authenticationmethodspolicy-get.md
  api-reference/beta/api/authenticationmethodsroot-list-userregistrationdetails.md
  api-reference/beta/api/emailauthenticationmethodconfiguration-get.md
  api-reference/beta/api/fido2authenticationmethodconfiguration-get.md
  api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md
  api-reference/beta/api/smsauthenticationmethodconfiguration-get.md
  api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md
  api-reference/beta/api/userregistrationdetails-get.md
  api-reference/beta/resources/authenticationmethodconfiguration.md
  api-reference/beta/resources/authenticationmethodspolicy.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/authenticationmethodspolicy-get.md
  api-reference/v1.0/api/emailauthenticationmethodconfiguration-get.md
  api-reference/v1.0/api/fido2authenticationmethodconfiguration-get.md
  api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md
  api-reference/v1.0/resources/authenticationmethodconfiguration.md
  api-reference/v1.0/resources/authenticationmethodspolicy.md
  concepts/toc.yml
Labels: area: Azure AD, ready to merge, internal

#15585 Add app-only permissions to read operations for teamsApp and teamworkBot
  api-reference/v1.0/api/appcatalogs-list-teamsapps.md
  api-reference/v1.0/api/teamworkbot-get.md
  changelog/Microsoft.Teams.GraphSvc.json
Labels: ready to merge, internal, content review complete

#15672 Teams terms of use clarification
  concepts/teams-licenses.md
Labels: ready to merge, internal

#15670 Update list-list.md
  api-reference/v1.0/api/list-list.md
Labels: external

#15669 Update list-list.md
  api-reference/beta/api/list-list.md
Labels: external

#15668 Update site-unfollow.md
  api-reference/beta/api/site-unfollow.md
Labels: external

#15463 [Action Needed] Update CRUD files for newly added properties
  api-reference/beta/api/cloudpc-get.md
  api-reference/beta/api/cloudpcdeviceimage-get.md
  api-reference/beta/api/cloudpconpremisesconnection-get.md
  api-reference/beta/api/cloudpconpremisesconnection-update.md
  api-reference/beta/api/virtualendpoint-list-cloudpcs.md
  api-reference/beta/api/virtualendpoint-list-deviceimages.md
  api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md
  api-reference/beta/api/virtualendpoint-post-deviceimages.md
  api-reference/beta/api/virtualendpoint-post-onpremisesconnections.md
Labels: ready to merge, internal, content review complete

#15610 Fix documentation issues
  api-reference/beta/api/contenttype-addcopyfromcontenttypehub.md
  api-reference/beta/api/contenttype-getcompatiblehubcontenttypes.md
  api-reference/beta/api/list-list-operations.md
  api-reference/beta/api/richlongrunningoperation-get.md
  api-reference/beta/api/site-list-operations.md
Labels: ready to merge, internal, content review complete

#15667 Minor doc fixes
  api-reference/beta/api/homerealmdiscoverypolicy-get.md
  api-reference/beta/api/homerealmdiscoverypolicy-list-appliesto.md
  api-reference/beta/api/homerealmdiscoverypolicy-list.md
  api-reference/beta/api/homerealmdiscoverypolicy-post-homerealmdiscoverypolicies.md
  api-reference/beta/api/homerealmdiscoverypolicy-update.md
  api-reference/beta/api/serviceprincipal-delete-homerealmdiscoverypolicies.md
  api-reference/beta/api/serviceprincipal-list-homerealmdiscoverypolicies.md
  api-reference/beta/api/serviceprincipal-post-homerealmdiscoverypolicies.md
  api-reference/v1.0/api/homerealmdiscoverypolicy-get.md
  api-reference/v1.0/api/homerealmdiscoverypolicy-list-appliesto.md
  api-reference/v1.0/api/homerealmdiscoverypolicy-list.md
  api-reference/v1.0/api/homerealmdiscoverypolicy-post-homerealmdiscoverypolicies.md
  api-reference/v1.0/api/homerealmdiscoverypolicy-update.md
Labels: area: Azure AD, ready to merge, internal

#15662 by dima.bondarenko888@gmail.com
  api-reference/beta/api/user-update.md
  api-reference/v1.0/api/user-update.md
Labels: external, ready to merge

#14939 Add device management APIs and resources.
  api-reference/beta/api/teamworkdevice-get.md
  api-reference/beta/api/teamworkdevice-list.md
  api-reference/beta/api/teamworkdevice-restart.md
  api-reference/beta/api/teamworkdevice-rundiagnostics.md
  api-reference/beta/api/teamworkdevice-updatesoftware.md
  api-reference/beta/api/teamworkdeviceactivity-get.md
  api-reference/beta/api/teamworkdeviceconfiguration-get.md
  api-reference/beta/api/teamworkdevicehealth-get.md
  api-reference/beta/api/teamworkdeviceoperation-get.md
  api-reference/beta/api/teamworkdeviceoperation-list.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/teamwork.md
  api-reference/beta/resources/teamworkaccountconfiguration.md
  api-reference/beta/resources/teamworkactiveperipherals.md
  api-reference/beta/resources/teamworkcameraconfiguration.md
  api-reference/beta/resources/teamworkconfiguredperipheral.md
  api-reference/beta/resources/teamworkconnection.md
  api-reference/beta/resources/teamworkcontentcameraconfiguration.md
  api-reference/beta/resources/teamworkdatetimeconfiguration.md
  api-reference/beta/resources/teamworkdevice.md
  api-reference/beta/resources/teamworkdeviceactivity.md
  api-reference/beta/resources/teamworkdeviceconfiguration.md
  api-reference/beta/resources/teamworkdevicehealth.md
  api-reference/beta/resources/teamworkdeviceoperation.md
  api-reference/beta/resources/teamworkdevicesoftwareversions.md
  api-reference/beta/resources/teamworkdisplayconfiguration.md
  api-reference/beta/resources/teamworkdisplayscreenconfiguration.md
  api-reference/beta/resources/teamworkfeaturesconfiguration.md
  api-reference/beta/resources/teamworkhardwareconfiguration.md
  api-reference/beta/resources/teamworkhardwaredetail.md
  api-reference/beta/resources/teamworkhardwarehealth.md
  api-reference/beta/resources/teamworkloginstatus.md
  api-reference/beta/resources/teamworkmicrophoneconfiguration.md
  api-reference/beta/resources/teamworknetworkconfiguration.md
  api-reference/beta/resources/teamworkonpremisescalendarsyncconfiguration.md
  api-reference/beta/resources/teamworkperipheral.md
  api-reference/beta/resources/teamworkperipheralhealth.md
  api-reference/beta/resources/teamworkperipheralshealth.md
  api-reference/beta/resources/teamworksoftwareupdatehealth.md
  api-reference/beta/resources/teamworksoftwareupdatestatus.md
  api-reference/beta/resources/teamworkspeakerconfiguration.md
  api-reference/beta/resources/teamworksystemconfiguration.md
  api-reference/beta/resources/teamworkteamsclientconfiguration.md
  api-reference/beta/resources/userteamwork.md
  api-reference/beta/toc.yml
  api-reference/includes/teamworkdevice-api-disclaimer.md
  changelog/Microsoft.Teams.Core.json
  concepts/permissions-reference.md
Labels: ready to merge, internal, content review complete, schema live

#15600 Refresh what's new.
  api-reference/beta/api/contenttype-getcompatiblehubcontenttypes.md
  api-reference/beta/api/site-list-operations.md
  api-reference/beta/resources/cloudpcorganizationsettings.md
  api-reference/beta/toc.yml
  changelog/Microsoft.AAD.Reporting.json
  changelog/Microsoft.Compliance.Ediscovery.json
  changelog/Microsoft.FileServices.json
  changelog/Microsoft.SharePoint.json
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: do not merge, internal

#15674 Refresh what's new topic.
  api-reference/beta/api/contenttype-getcompatiblehubcontenttypes.md
  api-reference/beta/api/site-list-operations.md
  api-reference/beta/resources/cloudpcorganizationsettings.md
  api-reference/beta/toc.yml
  changelog/Microsoft.AAD.Reporting.json
  changelog/Microsoft.Compliance.Ediscovery.json
  changelog/Microsoft.FileServices.json
  changelog/Microsoft.SharePoint.json
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: internal

#15325 Update Speller Doc For Graph Search API
  api-reference/beta/api/search-query.md
  api-reference/beta/resources/search-api-overview.md
  api-reference/beta/resources/search.md
  api-reference/beta/resources/searchentity.md
  api-reference/beta/resources/searchrequest.md
  api-reference/beta/resources/searchresponse.md
  api-reference/beta/resources/searchresultset.md
  changelog/Microsoft.MicrosoftSearch.json
  concepts/search-concept-speller.md
Labels: ready to merge, internal, content review complete

#15680 Remove rendered --->
  concepts/connecting-external-content-connectors-overview.md
Labels: external

#15678 Update user-list-contacts.md
  api-reference/beta/api/user-list-contacts.md
  api-reference/v1.0/api/user-list-contacts.md
Labels: external, ready to merge

#15684 Merge to publish.
  api-reference/beta/api/search-query.md
  api-reference/beta/api/user-list-contacts.md
  api-reference/beta/resources/search-api-overview.md
  api-reference/beta/resources/search.md
  api-reference/beta/resources/searchentity.md
  api-reference/beta/resources/searchrequest.md
  api-reference/beta/resources/searchresponse.md
  api-reference/beta/resources/searchresultset.md
  api-reference/v1.0/api/user-list-contacts.md
  changelog/Microsoft.MicrosoftSearch.json
  concepts/connecting-external-content-connectors-overview.md
  concepts/search-concept-speller.md
Labels: internal
