Repository microsoftgraph/microsoft-graph-docs, pull requests merged in 2022-05, with the labels that each got.

#16736 Edits in PR 16575
  api-reference/v1.0/api/contenttype-addcopyfromcontenttypehub.md
  api-reference/v1.0/api/list-list-operations.md
  api-reference/v1.0/api/richlongrunningoperation-get.md
  api-reference/v1.0/api/site-list-operations.md
  api-reference/v1.0/resources/contentType.md
  api-reference/v1.0/resources/list.md
  api-reference/v1.0/resources/richlongrunningoperation.md
  api-reference/v1.0/resources/site.md
  changelog/Microsoft.FileServices.json
Labels: external

#16745 Edits in PR 16372
  api-reference/beta/api/managedtenants-managedtenant-list-myroles.md
  api-reference/beta/resources/managedtenants-managedtenant.md
  api-reference/beta/resources/managedtenants-myrole.md
  api-reference/beta/resources/managedtenants-roleassignment.md
  api-reference/beta/resources/managedtenants-roledefinition.md
  api-reference/beta/toc.yml
  changelog/Microsoft.MultiTenantPlatform.json
Labels: external

#16748 Update bookingservice-delete.md
  api-reference/beta/api/bookingservice-delete.md
Labels: external

#16747 Update bookingservice-delete.md
  api-reference/v1.0/api/bookingservice-delete.md
Labels: external

#16746 Edits in PR 16575
  api-reference/v1.0/api/contenttype-addcopyfromcontenttypehub.md
  api-reference/v1.0/api/list-list-operations.md
  api-reference/v1.0/api/richlongrunningoperation-get.md
  api-reference/v1.0/api/site-list-operations.md
  api-reference/v1.0/resources/list.md
  api-reference/v1.0/resources/richlongrunningoperation.md
  api-reference/v1.0/resources/site.md
  changelog/Microsoft.FileServices.json
Labels: external

#16738 Edits in PR 16455
  api-reference/beta/api/listitem-delta.md
  changelog/Microsoft.FileServices.json
  concepts/delta-query-overview.md
Labels: external

#16723 Edited Graph Explorer pages
  concepts/graph-explorer/graph-explorer-features.md
  concepts/graph-explorer/graph-explorer-overview.md
Labels: ready to merge, internal

#16716 Added note that Graph cannot query mailboxes for permissions
  concepts/outlook-send-mail-from-other-user.md
Labels: ready to merge, internal, content review complete

#16734 Edited Connectors docs
  concepts/connecting-external-content-connectors-api-overview.md
  concepts/connecting-external-content-connectors-api-postman.md
  concepts/connecting-external-content-connectors-overview.md
  concepts/connecting-external-content-manage-connections.md
Labels: internal, content review complete

#16759 Edits in PR 16575
  api-reference/v1.0/resources/richlongrunningoperation.md
Labels: external

#16766 Update subjectrightsrequest-post-notes.md
  api-reference/v1.0/api/subjectrightsrequest-post-notes.md
Labels: external

#16765 Update subjectrightsrequest-post-notes.md
  api-reference/beta/api/subjectrightsrequest-post-notes.md
Labels: external

#16764 Update whats-new-overview.md
  concepts/whats-new-overview.md
Labels: external

#16762 Edits in PR 16343
  api-reference/beta/api/subjectrightsrequest-post.md
  api-reference/beta/resources/complianceapioverview.md
  api-reference/beta/resources/subjectrightsrequest.md
  api-reference/beta/resources/subjectrightsrequestallmailboxlocation.md
  api-reference/beta/resources/subjectrightsrequestmailboxlocation.md
  api-reference/beta/resources/subjectrightsrequestsitelocation.md
  api-reference/includes/subject-rights-request-privacy-deprecate.md
  api-reference/v1.0/resources/subjectrightsrequest-subjectrightsrequestapioverview.md
  changelog/Microsoft.Compliance.DataSubjectRequest.json
Labels: external

#16654 [bulk] Validation: metadata and tab group changes
  api-reference/v1.0/api/group-delete.md
  api-reference/v1.0/api/group-get.md
  api-reference/v1.0/api/securescorecontrolprofile-update.md
  api-reference/v1.0/api/security-list-securescorecontrolprofiles.md
  api-reference/v1.0/api/security-list-securescores.md
  api-reference/v1.0/api/shares-get.md
  api-reference/v1.0/api/singlevaluelegacyextendedproperty-get.md
  api-reference/v1.0/api/singlevaluelegacyextendedproperty-post-singlevalueextendedproperties.md
  api-reference/v1.0/api/sites-list-followed.md
  api-reference/v1.0/api/termstore-group-delete.md
  api-reference/v1.0/api/termstore-group-get.md
  api-reference/v1.0/api/termstore-group-post.md
  api-reference/v1.0/api/termstore-list-groups.md
  api-reference/v1.0/api/termstore-set-delete.md
  api-reference/v1.0/api/termstore-set-get.md
  api-reference/v1.0/api/termstore-set-post.md
  api-reference/v1.0/api/termstore-set-update.md
  api-reference/v1.0/api/termstore-store-get.md
  api-reference/v1.0/api/termstore-store-update.md
  api-reference/v1.0/api/termstore-term-delete.md
  api-reference/v1.0/api/termstore-term-get.md
  api-reference/v1.0/api/termstore-term-list-children.md
  api-reference/v1.0/api/termstore-term-list-relations.md
  api-reference/v1.0/api/termstore-term-post.md
  api-reference/v1.0/api/termstore-term-update.md
Labels: external, ready to merge

#16411 Added new example showing how to move a participant between calls.
  api-reference/beta/api/application-post-calls.md
  api-reference/beta/api/participant-invite.md
  api-reference/beta/resources/invitationparticipantinfo.md
  api-reference/v1.0/api/participant-invite.md
  api-reference/v1.0/resources/invitationparticipantinfo.md
  changelog/Microsoft.Skype.Calling.json
Labels: ready to merge, internal, content review complete

#16575 Added docs to promote ct sync apis to v1.0
  api-reference/v1.0/api/contenttype-addcopyfromcontenttypehub.md
  api-reference/v1.0/api/contenttype-getcompatiblehubcontenttypes.md
  api-reference/v1.0/api/list-list-operations.md
  api-reference/v1.0/api/richlongrunningoperation-get.md
  api-reference/v1.0/api/site-list-operations.md
  api-reference/v1.0/resources/contentType.md
  api-reference/v1.0/resources/enums.md
  api-reference/v1.0/resources/list.md
  api-reference/v1.0/resources/richlongrunningoperation.md
  api-reference/v1.0/resources/site.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.FileServices.json
Labels: ready to merge, internal, content review complete

#16767 Merge to publish.
  api-reference/beta/api/application-post-calls.md
  api-reference/beta/api/participant-invite.md
  api-reference/beta/api/subjectrightsrequest-post-notes.md
  api-reference/beta/resources/invitationparticipantinfo.md
  api-reference/v1.0/api/contenttype-addcopyfromcontenttypehub.md
  api-reference/v1.0/api/contenttype-getcompatiblehubcontenttypes.md
  api-reference/v1.0/api/group-delete.md
  api-reference/v1.0/api/group-get.md
  api-reference/v1.0/api/list-list-operations.md
  api-reference/v1.0/api/participant-invite.md
  api-reference/v1.0/api/richlongrunningoperation-get.md
  api-reference/v1.0/api/securescorecontrolprofile-update.md
  api-reference/v1.0/api/security-list-securescorecontrolprofiles.md
  api-reference/v1.0/api/security-list-securescores.md
  api-reference/v1.0/api/shares-get.md
  api-reference/v1.0/api/singlevaluelegacyextendedproperty-get.md
  api-reference/v1.0/api/singlevaluelegacyextendedproperty-post-singlevalueextendedproperties.md
  api-reference/v1.0/api/site-list-operations.md
  api-reference/v1.0/api/sites-list-followed.md
  api-reference/v1.0/api/subjectrightsrequest-post-notes.md
  api-reference/v1.0/api/termstore-group-delete.md
  api-reference/v1.0/api/termstore-group-get.md
  api-reference/v1.0/api/termstore-group-post.md
  api-reference/v1.0/api/termstore-list-groups.md
  api-reference/v1.0/api/termstore-set-delete.md
  api-reference/v1.0/api/termstore-set-get.md
  api-reference/v1.0/api/termstore-set-post.md
  api-reference/v1.0/api/termstore-set-update.md
  api-reference/v1.0/api/termstore-store-get.md
  api-reference/v1.0/api/termstore-store-update.md
  api-reference/v1.0/api/termstore-term-delete.md
  api-reference/v1.0/api/termstore-term-get.md
  api-reference/v1.0/api/termstore-term-list-children.md
  api-reference/v1.0/api/termstore-term-list-relations.md
  api-reference/v1.0/api/termstore-term-post.md
  api-reference/v1.0/api/termstore-term-update.md
  api-reference/v1.0/resources/contentType.md
  api-reference/v1.0/resources/enums.md
  api-reference/v1.0/resources/invitationparticipantinfo.md
  api-reference/v1.0/resources/list.md
  api-reference/v1.0/resources/richlongrunningoperation.md
  api-reference/v1.0/resources/site.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.FileServices.json
  changelog/Microsoft.Skype.Calling.json
  concepts/whats-new-overview.md
Labels: internal

#16781 Edits in PR 16494
  api-reference/v1.0/api/plannertask-update.md
  api-reference/v1.0/resources/planner-overview.md
  api-reference/v1.0/resources/plannercategorydescriptions.md
  api-reference/v1.0/resources/plannerplan.md
  api-reference/v1.0/resources/plannerplancontainer.md
  api-reference/v1.0/resources/plannerplandetails.md
  api-reference/v1.0/resources/plannertask.md
  changelog/Microsoft.Office.Tasks.json
Labels: external

#16784 Update plannerbucket.md
  api-reference/beta/resources/plannerbucket.md
Labels: external

#16783 Update plannerbucket.md
  api-reference/v1.0/resources/plannerbucket.md
Labels: external

#16782 Edits in PR 16343
  api-reference/beta/api/subjectrightsrequest-post.md
  api-reference/beta/resources/subjectrightsrequest.md
Labels: external

#16612 Fix OIDC text
  concepts/permissions-reference.md
Labels: ready to merge, internal, area: permissions

#16718 Update paging.md
  concepts/paging.md
Labels: area: Azure AD, ready to merge, internal

#16763 [Azure AD roles] allowedToReadBitlockerKeysForOwnedDevice property
  api-reference/beta/resources/defaultuserrolepermissions.md
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, ready to merge, changes requested, internal

#16775 remove preview tag from calling permissions
  concepts/permissions-reference.md
Labels: ready to merge

#16779 Edited remaining Connectors docs
  concepts/connecting-external-content-api-limits.md
  concepts/connecting-external-content-external-groups.md
  concepts/connecting-external-content-manage-connections.md
  concepts/connecting-external-content-manage-items.md
  concepts/connecting-external-content-manage-schema.md
Labels: ready to merge, internal, content review complete

#16793 Edits in PR 16494
  api-reference/beta/resources/planner-overview.md
  api-reference/v1.0/resources/planner-overview.md
  api-reference/v1.0/resources/plannercategorydescriptions.md
  api-reference/v1.0/resources/plannerplancontainer.md
Labels: external

#16790 Fixed two minor typos
  concepts/connecting-external-content-api-limits.md
Labels: ready to merge, internal

#16792 Edited remaining Data Connect docs
  concepts/data-connect-datasets.md
  concepts/data-connect-filtering.md
  concepts/data-connect-pam.md
Labels: ready to merge, internal, content review complete

#16752 Update migrate-azure-ad-graph-configure-permissions.md
  concepts/migrate-azure-ad-graph-configure-permissions.md
Labels: area: Azure AD, external, ready to merge, content review complete

#16791 April deployment - update Microsoft Graph permissions IDs
  concepts/permissions-reference.md
Labels: ready to merge, internal, area: permissions

#16404 Update onpremisespublishing.md
  api-reference/beta/resources/onpremisespublishing.md
  changelog/Microsoft.DirectoryServices.json
Labels: ready to merge, content review complete, schema live

#15663 Microsoft 365 Lighthouse changelog updates
  changelog/Microsoft.MultiTenantPlatform.json
  includes/throttling-multi-tenant-platform.md
Labels: ready to merge, internal, content review complete, review feedback addressed, area: multi-tenant management

#15816 Add serviceManagementReference property to /applications
  api-reference/beta/resources/application.md
  api-reference/v1.0/resources/application.md
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, ready to merge, internal

#16799 Update authN +authZ basics - references to access tokens
  concepts/auth/auth-concepts.md
Labels: area: Azure AD, ready to merge, internal

#16800 Minor fixes to migration guidance for properties
  concepts/migrate-azure-ad-graph-property-differences.md
Labels: area: Azure AD, ready to merge, internal

#16803 Reassign organization docs
  api-reference/beta/api/organization-get.md
  api-reference/beta/api/organization-list.md
  api-reference/beta/api/organization-update.md
  api-reference/beta/resources/organization.md
  api-reference/v1.0/api/organization-get.md
  api-reference/v1.0/api/organization-list.md
  api-reference/v1.0/api/organization-update.md
  api-reference/v1.0/resources/organization.md
Labels: area: Azure AD, ready to merge, internal, area: directory management

#16805 Update user-exportpersonaldata.md
  api-reference/beta/api/user-exportpersonaldata.md
  api-reference/v1.0/api/user-exportpersonaldata.md
Labels: external, ready to merge

#16807 Update v1 documentation for setPresence
  api-reference/v1.0/api/presence-setpresence.md
Labels: ready to merge, internal, content review complete

#16810 Merge to publish.
  api-reference/beta/api/organization-get.md
  api-reference/beta/api/organization-list.md
  api-reference/beta/api/organization-update.md
  api-reference/beta/api/user-exportpersonaldata.md
  api-reference/beta/resources/application.md
  api-reference/beta/resources/organization.md
  api-reference/v1.0/api/organization-get.md
  api-reference/v1.0/api/organization-list.md
  api-reference/v1.0/api/organization-update.md
  api-reference/v1.0/api/presence-setpresence.md
  api-reference/v1.0/api/user-exportpersonaldata.md
  api-reference/v1.0/resources/application.md
  api-reference/v1.0/resources/organization.md
  changelog/Microsoft.DirectoryServices.json
  concepts/auth/auth-concepts.md
  concepts/migrate-azure-ad-graph-property-differences.md
Labels: do not merge, internal

#16609 Added a Microsoft Graph PowerShell tab in the article
  concepts/auth-cloudsolutionprovider.md
Labels: ready to merge, internal

#16350 Enabling Expand Query Option for Channel List Message API
  api-reference/beta/api/channel-list-messages.md
  api-reference/beta/api/chatmessage-delta.md
  api-reference/beta/resources/chatmessage.md
  api-reference/v1.0/api/channel-list-messages.md
  api-reference/v1.0/api/chatmessage-delta.md
  api-reference/v1.0/resources/chatmessage.md
  changelog/Microsoft.Teams.Core.json
Labels: ready to merge, internal, content review complete

#16816 Resolve #16806 - Show reference for getting synchronization ruleID
  api-reference/beta/resources/synchronization-synchronizationjobapplicationparameters.md
Labels: area: Azure AD, ready to merge, internal

#16817 Minor doc fixes
  api-reference/beta/api/schemaextension-delete.md
  api-reference/beta/api/schemaextension-list.md
  api-reference/beta/api/schemaextension-post-schemaextensions.md
  api-reference/beta/api/schemaextension-update.md
  api-reference/beta/resources/groups-overview.md
  api-reference/beta/resources/schemaextension.md
  api-reference/v1.0/api/schemaextension-delete.md
  api-reference/v1.0/api/schemaextension-list.md
  api-reference/v1.0/api/schemaextension-post-schemaextensions.md
  api-reference/v1.0/api/schemaextension-update.md
  api-reference/v1.0/resources/groups-overview.md
  api-reference/v1.0/resources/schemaextension.md
  concepts/auth-v2-service.md
  concepts/migrate-azure-ad-graph-property-differences.md
  concepts/toc.yml
Labels: area: Azure AD, ready to merge, internal

#16802 Removed redundancy
  concepts/connecting-external-content-api-limits.md
Labels: ready to merge, internal, review feedback addressed

#16364 Adding saml/wsfed based identity provider graph Api to v1.0
  api-reference/v1.0/api/samlorwsfedexternaldomainfederation-delete.md
  api-reference/v1.0/api/samlorwsfedexternaldomainfederation-get.md
  api-reference/v1.0/api/samlorwsfedexternaldomainfederation-list-domains.md
  api-reference/v1.0/api/samlorwsfedexternaldomainfederation-list.md
  api-reference/v1.0/api/samlorwsfedexternaldomainfederation-post-domains.md
  api-reference/v1.0/api/samlorwsfedexternaldomainfederation-post.md
  api-reference/v1.0/api/samlorwsfedexternaldomainfederation-update.md
  api-reference/v1.0/resources/directory.md
  api-reference/v1.0/resources/enums.md
  api-reference/v1.0/resources/externaldomainname.md
  api-reference/v1.0/resources/samlorwsfedexternaldomainfederation.md
  api-reference/v1.0/resources/samlorwsfedprovider.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, ready to merge, internal, content review complete, schema live

#16828 Merge to publish.
  api-reference/beta/api/channel-list-messages.md
  api-reference/beta/api/chatmessage-delta.md
  api-reference/beta/api/schemaextension-delete.md
  api-reference/beta/api/schemaextension-list.md
  api-reference/beta/api/schemaextension-post-schemaextensions.md
  api-reference/beta/api/schemaextension-update.md
  api-reference/beta/resources/chatmessage.md
  api-reference/beta/resources/groups-overview.md
  api-reference/beta/resources/schemaextension.md
  api-reference/beta/resources/synchronization-synchronizationjobapplicationparameters.md
  api-reference/v1.0/api/channel-list-messages.md
  api-reference/v1.0/api/chatmessage-delta.md
  api-reference/v1.0/api/samlorwsfedexternaldomainfederation-delete.md
  api-reference/v1.0/api/samlorwsfedexternaldomainfederation-get.md
  api-reference/v1.0/api/samlorwsfedexternaldomainfederation-list-domains.md
  api-reference/v1.0/api/samlorwsfedexternaldomainfederation-list.md
  api-reference/v1.0/api/samlorwsfedexternaldomainfederation-post-domains.md
  api-reference/v1.0/api/samlorwsfedexternaldomainfederation-post.md
  api-reference/v1.0/api/samlorwsfedexternaldomainfederation-update.md
  api-reference/v1.0/api/schemaextension-delete.md
  api-reference/v1.0/api/schemaextension-list.md
  api-reference/v1.0/api/schemaextension-post-schemaextensions.md
  api-reference/v1.0/api/schemaextension-update.md
  api-reference/v1.0/resources/chatmessage.md
  api-reference/v1.0/resources/directory.md
  api-reference/v1.0/resources/enums.md
  api-reference/v1.0/resources/externaldomainname.md
  api-reference/v1.0/resources/groups-overview.md
  api-reference/v1.0/resources/samlorwsfedexternaldomainfederation.md
  api-reference/v1.0/resources/samlorwsfedprovider.md
  api-reference/v1.0/resources/schemaextension.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.DirectoryServices.json
  changelog/Microsoft.Teams.Core.json
  concepts/auth-cloudsolutionprovider.md
  concepts/auth-v2-service.md
  concepts/connecting-external-content-api-limits.md
  concepts/migrate-azure-ad-graph-property-differences.md
  concepts/toc.yml
Labels: do not merge, internal

#16841 What's new for Toolkit in March.
  concepts/toc.yml
  concepts/toolkit/components/people-picker.md
  concepts/whats-new-overview.md
Labels: do not merge, internal

#16839 Edits in PR 16372
  api-reference/beta/api/managedtenants-managedtenant-list-myroles.md
  api-reference/beta/resources/managedtenants-managedtenant.md
  api-reference/beta/resources/managedtenants-myrole.md
  api-reference/beta/resources/managedtenants-roleassignment.md
  changelog/Microsoft.MultiTenantPlatform.json
Labels: external

#16834 Minor doc fixes
  api-reference/beta/api/agreement-post-files.md
  api-reference/beta/api/user-delta.md
  api-reference/beta/resources/claimsmappingpolicy.md
  api-reference/beta/resources/user.md
  api-reference/v1.0/api/agreement-post-files.md
  api-reference/v1.0/api/user-delta.md
  api-reference/v1.0/resources/agreementfile.md
  api-reference/v1.0/resources/claimsmappingpolicy.md
  concepts/application-saml-sso-configure-api.md
Labels: area: Azure AD, ready to merge, internal

#16644 [bulk] Validation: Metadata and tab group updates
  api-reference/v1.0/api/multivaluelegacyextendedproperty-get.md
  api-reference/v1.0/api/multivaluelegacyextendedproperty-post-multivalueextendedproperties.md
  api-reference/v1.0/api/nameditem-add.md
  api-reference/v1.0/api/nameditem-addformulalocal.md
  api-reference/v1.0/api/nameditem-get.md
  api-reference/v1.0/api/nameditem-list.md
  api-reference/v1.0/api/nameditem-range.md
  api-reference/v1.0/api/nameditem-update.md
  api-reference/v1.0/api/organizationalbranding-get.md
  api-reference/v1.0/api/organizationalbranding-update.md
  api-reference/v1.0/api/outlookuser-supportedtimezones.md
  api-reference/v1.0/api/permission-delete.md
  api-reference/v1.0/api/place-list.md
  api-reference/v1.0/api/place-update.md
  api-reference/v1.0/api/print-post-taskdefinitions.md
  api-reference/v1.0/api/printershare-get.md
Labels: external, review requested, changes requested

#16862 Edits in PR 16047
  api-reference/beta/api/tenantAdmin-settings-get.md
  api-reference/beta/api/tenantAdmin-settings-update.md
  api-reference/beta/resources/admin.md
  api-reference/beta/resources/tenantAdmin-settings.md
  api-reference/beta/resources/tenantAdmin-sharepoint.md
Labels: external

#16863 Update educationroot-list-schools.md
  api-reference/beta/api/educationroot-list-schools.md
Labels: external

#16861 Update known-issues.md
  concepts/known-issues.md
Labels: external

#16859 Edits in PR 16343
  api-reference/beta/api/subjectrightsrequest-get.md
  api-reference/beta/api/subjectrightsrequest-list-notes.md
  api-reference/beta/api/subjectrightsrequest-list.md
  api-reference/beta/api/subjectrightsrequest-post-notes.md
  api-reference/beta/api/subjectrightsrequest-post.md
  api-reference/beta/api/subjectrightsrequest-update.md
  api-reference/beta/resources/subjectrightsrequest.md
  api-reference/beta/resources/subjectrightsrequestallsitelocation.md
  api-reference/beta/resources/subjectrightsrequestenumeratedsitelocation.md
  changelog/Microsoft.Compliance.DataSubjectRequest.json
Labels: external

#15907 Add two new complex types for forensic.
  api-reference/beta/api/cloudpcsnapshot-getstorageaccounts.md
  api-reference/beta/api/cloudpcsnapshot-getsubscriptions.md
  api-reference/beta/resources/cloudpcforensicstorageaccount.md
  api-reference/beta/resources/cloudpcsubscription.md
  api-reference/beta/toc.yml
  changelog/Microsoft.CloudManagedDesktop.json
Labels: do not merge, ready to merge, internal

#16589 Bulk reprovision add response
  api-reference/beta/api/manageddevice-bulkreprovisioncloudpc.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, internal, content review complete

#16760 AAD best practices info for CRI reduction
  concepts/throttling.md
Labels: area: Azure AD, ready to merge, internal, content review complete

#16618 Delta Queries V1.0 Documentation
  api-reference/beta/resources/educationassignment.md
  api-reference/beta/resources/educationcategory.md
  api-reference/v1.0/api/educationassignment-delta.md
  api-reference/v1.0/api/educationcategory-delta.md
  api-reference/v1.0/resources/educationassignment.md
  api-reference/v1.0/resources/educationcategory.md
  api-reference/v1.0/resources/educationclass.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.EducationAssignment.json
Labels: ready to merge, changes requested, internal, content review complete

#16878 Edits in PR 16047
  api-reference/beta/api/tenantAdmin-settings-update.md
  api-reference/beta/resources/admin.md
  api-reference/beta/resources/tenantAdmin-settings.md
  api-reference/beta/resources/tenantAdmin-sharepoint.md
Labels: external

#16880 Update educationschool-delete-users.md
  api-reference/v1.0/api/educationschool-delete-users.md
Labels: external

#16876 [mgt] updating person-card with new custom css properties
  concepts/toolkit/components/person-card.md
Labels: external

#16879 Update educationschool-delete-users.md
  api-reference/beta/api/educationschool-delete-users.md
Labels: external

#16849 Minor doc fixes
  api-reference/beta/api/device-update.md
  api-reference/beta/api/group-list.md
  api-reference/beta/api/group-post-members.md
  api-reference/v1.0/api/device-update.md
  api-reference/v1.0/api/group-list.md
  api-reference/v1.0/api/group-post-members.md
  concepts/delta-query-overview.md
Labels: area: Azure AD, ready to merge, internal

#15424 Adding tenant usage
  api-reference/beta/api/managedtenants-managedtenant-list-tenantusage.md
  api-reference/beta/resources/managedtenants-managedtenant.md
  api-reference/beta/resources/managedtenants-serviceusage.md
  api-reference/beta/resources/managedtenants-tenantusage.md
  api-reference/beta/toc.yml
  changelog/Microsoft.MultiTenantPlatform.json
Labels: ready to merge, internal, content review complete, review feedback addressed, area: multi-tenant management

#16881 Enabling list chats in app context
  api-reference/beta/api/chat-list.md
  api-reference/beta/api/chat-post.md
  api-reference/beta/resources/eventmessagedetail.md
  api-reference/v1.0/api/chat-post.md
  api-reference/v1.0/resources/eventmessagedetail.md
  changelog/Microsoft.Teams.Core.json
Labels: ready to merge, internal, content review complete

#16703 Bulk validation changes ms.prod
  api-reference/beta/resources/chunkeduploadsessiondescriptor.md
  api-reference/beta/resources/cloudappsecuritystate.md
  api-reference/beta/resources/copystatusmodel.md
  api-reference/beta/resources/filehash.md
  api-reference/beta/resources/filehashtypeenumtype.md
  api-reference/beta/resources/filesecuritystate.md
  api-reference/beta/resources/geolocationcolumn.md
  api-reference/beta/resources/importstatusmodel.md
  api-reference/beta/resources/incompletedata.md
Labels: external, ready to merge, content review complete

#16884 Minor doc fixes
  api-reference/beta/api/user-list-licensedetails.md
  api-reference/beta/resources/subscription.md
  api-reference/v1.0/api/user-list-licensedetails.md
  api-reference/v1.0/resources/subscription.md
Labels: area: Azure AD, ready to merge, internal

#16494 Promoting fields from beta to v1.0 for the Planner Graph API
  api-reference/beta/api/plannerplandetails-get.md
  api-reference/beta/api/plannerplandetails-update.md
  api-reference/beta/api/plannertask-get.md
  api-reference/beta/resources/planner-overview.md
  api-reference/v1.0/api/plannerplan-get.md
  api-reference/v1.0/api/plannerplan-update.md
  api-reference/v1.0/api/plannerplandetails-get.md
  api-reference/v1.0/api/plannerplandetails-update.md
  api-reference/v1.0/api/plannertask-get.md
  api-reference/v1.0/api/plannertask-update.md
  api-reference/v1.0/resources/enums.md
  api-reference/v1.0/resources/planner-overview.md
  api-reference/v1.0/resources/plannercategorydescriptions.md
  api-reference/v1.0/resources/plannerplan.md
  api-reference/v1.0/resources/plannerplancontainer.md
  api-reference/v1.0/resources/plannerplandetails.md
  api-reference/v1.0/resources/plannertask.md
  changelog/Microsoft.Office.Tasks.json
Labels: ready to merge, internal, content review complete

#16894 Merge to publish.
  api-reference/beta/api/plannerplandetails-get.md
  api-reference/beta/api/plannerplandetails-update.md
  api-reference/beta/api/plannertask-get.md
  api-reference/beta/api/user-list-licensedetails.md
  api-reference/beta/resources/chunkeduploadsessiondescriptor.md
  api-reference/beta/resources/cloudappsecuritystate.md
  api-reference/beta/resources/copystatusmodel.md
  api-reference/beta/resources/filehash.md
  api-reference/beta/resources/filehashtypeenumtype.md
  api-reference/beta/resources/filesecuritystate.md
  api-reference/beta/resources/geolocationcolumn.md
  api-reference/beta/resources/importstatusmodel.md
  api-reference/beta/resources/incompletedata.md
  api-reference/beta/resources/planner-overview.md
  api-reference/beta/resources/subscription.md
  api-reference/v1.0/api/plannerplan-get.md
  api-reference/v1.0/api/plannerplan-update.md
  api-reference/v1.0/api/plannerplandetails-get.md
  api-reference/v1.0/api/plannerplandetails-update.md
  api-reference/v1.0/api/plannertask-get.md
  api-reference/v1.0/api/plannertask-update.md
  api-reference/v1.0/api/user-list-licensedetails.md
  api-reference/v1.0/resources/enums.md
  api-reference/v1.0/resources/planner-overview.md
  api-reference/v1.0/resources/plannercategorydescriptions.md
  api-reference/v1.0/resources/plannerplan.md
  api-reference/v1.0/resources/plannerplancontainer.md
  api-reference/v1.0/resources/plannerplandetails.md
  api-reference/v1.0/resources/plannertask.md
  api-reference/v1.0/resources/subscription.md
  changelog/Microsoft.Office.Tasks.json
Labels: internal

#16916 Edits in PR 15683
  api-reference/beta/api/informationprotectionlabel-evaluateapplication.md
  api-reference/beta/api/informationprotectionlabel-evaluateclassificationresults.md
  api-reference/beta/api/informationprotectionlabel-evaluateremoval.md
  api-reference/beta/api/informationprotectionlabel-extractlabel.md
  api-reference/beta/api/informationprotectionlabel-get.md
  api-reference/beta/api/informationprotectionpolicy-list-labels.md
  api-reference/beta/resources/addcontentfooteraction.md
  api-reference/beta/resources/addcontentheaderaction.md
  api-reference/beta/resources/addwatermarkaction.md
  api-reference/beta/resources/applylabelaction.md
  api-reference/beta/resources/classificationresult.md
  api-reference/beta/resources/contentinfo.md
  api-reference/beta/resources/customaction.md
  api-reference/beta/resources/downgradejustification.md
  api-reference/beta/resources/informationprotectionaction.md
  api-reference/beta/resources/informationprotectioncontentlabel.md
  api-reference/beta/resources/informationprotectionlabel.md
  api-reference/beta/resources/justifyaction.md
  api-reference/beta/resources/labelingoptions.md
  api-reference/beta/resources/metadataaction.md
  api-reference/beta/resources/protectadhocaction.md
  api-reference/beta/resources/protectbytemplateaction.md
  api-reference/beta/resources/protectdonotforwardaction.md
  api-reference/beta/resources/recommendlabelaction.md
  api-reference/beta/resources/removecontentfooteraction.md
  api-reference/beta/resources/removecontentheaderaction.md
  api-reference/beta/resources/removeprotectionaction.md
  api-reference/beta/resources/removewatermarkaction.md
Labels: external

#16915 Edits in PR 16809
  api-reference/beta/api/educationassignment-setupfeedbackresourcesfolder.md
  api-reference/beta/api/educationsubmission-list-outcomes.md
  api-reference/beta/api/educationsubmission-post-feedbackresource.md
  api-reference/beta/api/educationsubmissionfeedbackresource-delete.md
  api-reference/beta/resources/educationassignment.md
  api-reference/beta/resources/educationfeedbackresourceoutcome.md
  changelog/Microsoft.EducationAssignment.json
Labels: external

#16900 Update migrate-azure-ad-graph-configure-permissions.md
  concepts/migrate-azure-ad-graph-configure-permissions.md
Labels: external

#16906 Update user-post-messages.md
  api-reference/beta/api/user-post-messages.md
Labels: external

#16905 Update user-post-messages.md
  api-reference/v1.0/api/user-post-messages.md
Labels: external

#16877 Install instructions for PowerShell
  concepts/sdks/sdk-installation.md
Labels: ready to merge, internal

#16825 Documentation Hub updates
  concepts/index.yml
  concepts/sdks/sdks-overview.md
Labels: ready to merge, internal, content review complete

#16889 Update opentypeextension.md
  api-reference/v1.0/resources/opentypeextension.md
Labels: external, changes requested

#16887 Update advanced query capabilities for $count, $batch, and endsWith
  api-reference/beta/resources/application.md
  api-reference/beta/resources/device.md
  api-reference/beta/resources/group.md
  api-reference/beta/resources/orgcontact.md
  api-reference/beta/resources/user.md
  api-reference/v1.0/resources/application.md
  api-reference/v1.0/resources/device.md
  api-reference/v1.0/resources/group.md
  api-reference/v1.0/resources/orgcontact.md
  api-reference/v1.0/resources/user.md
  changelog/Microsoft.DirectoryServices.json
  concepts/aad-advanced-queries.md
  concepts/json-batching.md
  concepts/query-parameters.md
Labels: area: Azure AD, ready to merge, internal

#16898 Update opentypeextension.md
  api-reference/beta/resources/opentypeextension.md
Labels: external

#16851 Edit of Toolkit overview and get started pages
  concepts/toolkit/get-started/overview.md
  concepts/toolkit/overview.md
Labels: ready to merge, internal

#16928 Update C# using statement for latest Beta SDK
  concepts/sdks/use-beta.md
Labels: internal

#16932 Edits in PR 16047
  api-reference/beta/api/tenantadmin-settings-update.md
  api-reference/beta/resources/tenantadmin-settings.md
  api-reference/beta/toc.yml
  changelog/Microsoft.FileServices.json
Labels: external

#16934 Edits in PR 16047
  api-reference/beta/api/tenantadmin-settings-update.md
  api-reference/beta/resources/tenantadmin-settings.md
Labels: external

#16938 Edits in PR 16047
  api-reference/beta/resources/tenantadmin-settings.md
  api-reference/beta/resources/tenantadmin-sharepoint.md
Labels: external

#16937 Edits in PR 16852
  api-reference/beta/api/windowsupdates-operationalinsightsconnection-delete.md
  api-reference/beta/api/windowsupdates-operationalinsightsconnection-get.md
  api-reference/beta/api/windowsupdates-resourceconnection-delete.md
  api-reference/beta/api/windowsupdates-resourceconnection-get.md
  api-reference/beta/api/windowsupdates-updates-list-resourceconnections-operationalinsightsconnection.md
  api-reference/beta/api/windowsupdates-updates-list-resourceconnections.md
  api-reference/beta/api/windowsupdates-updates-post-resourceconnections-operationalinsightsconnection.md
  api-reference/beta/resources/windowsupdates-operationalinsightsconnection.md
  api-reference/beta/resources/windowsupdates-resourceconnection.md
  api-reference/beta/resources/windowsupdates-updates.md
  api-reference/beta/toc.yml
  changelog/Microsoft.WindowsUpdates.json
Labels: external

#16925 Fix missing "$" character on example code
  api-reference/v1.0/api/channel-list-messages.md
Labels: external

#16921 Update educationassignment-setupresourcesfolder.md
  api-reference/beta/api/educationassignment-setupresourcesfolder.md
Labels: external

#16920 Update educationassignment-setupresourcesfolder.md
  api-reference/v1.0/api/educationassignment-setupresourcesfolder.md
Labels: external

#16929 Toolkit overview: fixed broken link
  concepts/toolkit/overview.md
Labels: ready to merge, internal

#16531 MyA/WPA-->Viva Insights transition
  api-reference/beta/resources/social-overview.md
  concepts/overview-major-services.md
  concepts/overview.md
  concepts/social-intel-concept-overview.md
Labels: ready to merge, internal, content review complete

#16891 Edited two Postman docs
  concepts/connecting-external-content-connectors-api-postman.md
  concepts/use-postman.md
Labels: ready to merge, internal, review feedback addressed

#16616 Teams App Resource Documentation
  api-reference/beta/api/educationassignment-post-resources.md
  api-reference/beta/resources/educationresource.md
  api-reference/beta/resources/educationteamsappresource.md
  changelog/Microsoft.EducationAssignment.json
Labels: ready to merge, internal, content review complete, schema live, review feedback addressed

#16343 Add new properties for SubjectRightsRequest
  api-reference/beta/api/subjectrightsrequest-get.md
  api-reference/beta/api/subjectrightsrequest-getfinalattachment.md
  api-reference/beta/api/subjectrightsrequest-getfinalreport.md
  api-reference/beta/api/subjectrightsrequest-list-notes.md
  api-reference/beta/api/subjectrightsrequest-list.md
  api-reference/beta/api/subjectrightsrequest-post-notes.md
  api-reference/beta/api/subjectrightsrequest-post.md
  api-reference/beta/api/subjectrightsrequest-update.md
  api-reference/beta/resources/complianceapioverview.md
  api-reference/beta/resources/subjectrightsrequest-subjectrightsrequestapioverview.md
  api-reference/beta/resources/subjectrightsrequest.md
  api-reference/beta/resources/subjectrightsrequestallmailboxlocation.md
  api-reference/beta/resources/subjectrightsrequestallsitelocation.md
  api-reference/beta/resources/subjectrightsrequestenumeratedmailboxlocation.md
  api-reference/beta/resources/subjectrightsrequestenumeratedsitelocation.md
  api-reference/beta/resources/subjectrightsrequestmailboxlocation.md
  api-reference/beta/resources/subjectrightsrequestsitelocation.md
  api-reference/includes/subject-rights-request-privacy-deprecate.md
  api-reference/v1.0/resources/complianceapioverview.md
  api-reference/v1.0/resources/subjectrightsrequest-subjectrightsrequestapioverview.md
  api-reference/v1.0/resources/subjectrightsrequest.md
  changelog/Microsoft.Compliance.DataSubjectRequest.json
Labels: ready to merge, internal, content review complete

#16940 Merge to publish.
  api-reference/beta/api/educationassignment-post-resources.md
  api-reference/beta/api/educationassignment-setupresourcesfolder.md
  api-reference/beta/api/subjectrightsrequest-get.md
  api-reference/beta/api/subjectrightsrequest-getfinalattachment.md
  api-reference/beta/api/subjectrightsrequest-getfinalreport.md
  api-reference/beta/api/subjectrightsrequest-list-notes.md
  api-reference/beta/api/subjectrightsrequest-list.md
  api-reference/beta/api/subjectrightsrequest-post-notes.md
  api-reference/beta/api/subjectrightsrequest-post.md
  api-reference/beta/api/subjectrightsrequest-update.md
  api-reference/beta/resources/complianceapioverview.md
  api-reference/beta/resources/educationresource.md
  api-reference/beta/resources/educationteamsappresource.md
  api-reference/beta/resources/social-overview.md
  api-reference/beta/resources/subjectrightsrequest-subjectrightsrequestapioverview.md
  api-reference/beta/resources/subjectrightsrequest.md
  api-reference/beta/resources/subjectrightsrequestallmailboxlocation.md
  api-reference/beta/resources/subjectrightsrequestallsitelocation.md
  api-reference/beta/resources/subjectrightsrequestenumeratedmailboxlocation.md
  api-reference/beta/resources/subjectrightsrequestenumeratedsitelocation.md
  api-reference/beta/resources/subjectrightsrequestmailboxlocation.md
  api-reference/beta/resources/subjectrightsrequestsitelocation.md
  api-reference/includes/subject-rights-request-privacy-deprecate.md
  api-reference/v1.0/api/channel-list-messages.md
  api-reference/v1.0/api/educationassignment-setupresourcesfolder.md
  api-reference/v1.0/resources/complianceapioverview.md
  api-reference/v1.0/resources/subjectrightsrequest-subjectrightsrequestapioverview.md
  api-reference/v1.0/resources/subjectrightsrequest.md
  changelog/Microsoft.Compliance.DataSubjectRequest.json
  changelog/Microsoft.EducationAssignment.json
  concepts/connecting-external-content-connectors-api-postman.md
  concepts/overview-major-services.md
  concepts/overview.md
  concepts/sdks/use-beta.md
  concepts/social-intel-concept-overview.md
  concepts/toolkit/overview.md
  concepts/use-postman.md
Labels: internal

#16843 Edits in PR 16653
  api-reference/beta/api/chat-delete-pinnedmessages.md
  api-reference/beta/api/chat-list-pinnedmessages.md
  api-reference/beta/api/chat-post-pinnedmessages.md
  api-reference/beta/resources/chat.md
  api-reference/beta/resources/pinnedChatMessageInfo.md
  changelog/Microsoft.Teams.GraphSvc.json
Labels: external

#16742 Updating EWS parity documentation of EWS to Graph APIs
  concepts/migrate-exchange-web-services-api-mapping.md
  concepts/migrate-exchange-web-services-authentication.md
  concepts/migrate-exchange-web-services-overview.md
Labels: ready to merge, internal, content review complete

#16960 Update educationschool-update.md
  api-reference/beta/api/educationschool-update.md
Labels: external

#16958 Edits in PR 16852
  api-reference/beta/resources/windowsupdates-updates.md
Labels: external

#16930 Overview: Cleaned up bold formatting
  concepts/overview.md
Labels: ready to merge, internal

#16942 Fix PIM redirects
  .openpublishing.publish.config.json
Labels: area: Azure AD, ready to merge, internal

#16950 Minor doc fixes
  api-reference/beta/api/device-update.md
  api-reference/beta/api/user-assignlicense.md
  api-reference/beta/api/user-list-licensedetails.md
  api-reference/beta/resources/assignedlicense.md
  api-reference/beta/resources/assignedplan.md
  api-reference/beta/resources/licenseAssignmentState.md
  api-reference/beta/resources/licensedetails.md
  api-reference/beta/resources/licenseunitsdetail.md
  api-reference/beta/resources/serviceplaninfo.md
  api-reference/v1.0/api/device-update.md
  api-reference/v1.0/api/user-assignlicense.md
  api-reference/v1.0/api/user-list-licensedetails.md
  api-reference/v1.0/resources/assignedlicense.md
  api-reference/v1.0/resources/assignedplan.md
  api-reference/v1.0/resources/licenseassignmentstate.md
  api-reference/v1.0/resources/licensedetails.md
  api-reference/v1.0/resources/licenseunitsdetail.md
  api-reference/v1.0/resources/serviceplaninfo.md
  api-reference/v1.0/resources/unifiedroleassignmentscheduleinstance.md
  api-reference/v1.0/resources/unifiedroleeligibilityscheduleinstance.md
Labels: area: Azure AD, ready to merge, internal

#16956 Edits in PR 16047
  api-reference/beta/resources/tenantadmin-settings.md
  api-reference/beta/resources/tenantadmin-sharepoint.md
Labels: external

#16965 Merge to publish.
  .openpublishing.publish.config.json
  api-reference/beta/api/device-update.md
  api-reference/beta/api/educationschool-update.md
  api-reference/beta/api/listitem-delta.md
  api-reference/beta/api/user-assignlicense.md
  api-reference/beta/api/user-list-licensedetails.md
  api-reference/beta/resources/assignedlicense.md
  api-reference/beta/resources/assignedplan.md
  api-reference/beta/resources/licenseAssignmentState.md
  api-reference/beta/resources/licensedetails.md
  api-reference/beta/resources/licenseunitsdetail.md
  api-reference/beta/resources/listitem.md
  api-reference/beta/resources/serviceplaninfo.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/device-update.md
  api-reference/v1.0/api/educationschool-update.md
  api-reference/v1.0/api/user-assignlicense.md
  api-reference/v1.0/api/user-list-licensedetails.md
  api-reference/v1.0/resources/assignedlicense.md
  api-reference/v1.0/resources/assignedplan.md
  api-reference/v1.0/resources/licenseassignmentstate.md
  api-reference/v1.0/resources/licensedetails.md
  api-reference/v1.0/resources/licenseunitsdetail.md
  api-reference/v1.0/resources/serviceplaninfo.md
  api-reference/v1.0/resources/unifiedroleassignmentscheduleinstance.md
  api-reference/v1.0/resources/unifiedroleeligibilityscheduleinstance.md
  changelog/Microsoft.FileServices.json
  concepts/delta-query-overview.md
  concepts/migrate-exchange-web-services-api-mapping.md
  concepts/migrate-exchange-web-services-authentication.md
  concepts/migrate-exchange-web-services-overview.md
  concepts/overview.md
Labels: do not merge, internal

#16980 Edits in PR 16852
  changelog/Microsoft.WindowsUpdates.json
Labels: external

#16873 Updates to language tags and example requests
  api-reference/beta/api/search-bookmark-get.md
  api-reference/beta/api/search-qna-get.md
  api-reference/beta/api/search-searchentity-list-bookmarks.md
  api-reference/beta/api/search-searchentity-list-qnas.md
  api-reference/beta/api/search-searchentity-post-bookmarks.md
  api-reference/beta/api/search-searchentity-post-qnas.md
  api-reference/beta/resources/search-api-answers-overview.md
  api-reference/beta/resources/search-bookmark.md
  api-reference/beta/resources/search-qna.md
Labels: ready to merge, internal, content review complete

#16977 Minor doc fixes
  api-reference/beta/api/accessreviewpolicy-get.md
  api-reference/beta/api/accessreviewpolicy-update.md
  api-reference/beta/api/application-list-federatedidentitycredentials.md
  api-reference/beta/api/application-post-federatedidentitycredentials.md
  api-reference/beta/api/device-delete.md
  api-reference/beta/api/device-post-devices.md
  api-reference/beta/api/device-update.md
  api-reference/beta/api/federatedidentitycredential-delete.md
  api-reference/beta/api/federatedidentitycredential-get.md
  api-reference/beta/api/federatedidentitycredential-update.md
  api-reference/beta/resources/federatedidentitycredential.md
  api-reference/beta/resources/federatedidentitycredentials-overview.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/device-delete.md
  api-reference/v1.0/api/device-post-devices.md
  api-reference/v1.0/api/device-update.md
  changelog/Microsoft.DirectoryServices.json
  concepts/permissions-reference.md
Labels: area: Azure AD, ready to merge, internal

#16744 Update bookingbusiness-list.md
  api-reference/beta/api/bookingbusiness-list.md
Labels: ready to merge, internal, content review complete

#16983 Merge to publish.
  api-reference/beta/api/accessreviewpolicy-get.md
  api-reference/beta/api/accessreviewpolicy-update.md
  api-reference/beta/api/application-list-federatedidentitycredentials.md
  api-reference/beta/api/application-post-federatedidentitycredentials.md
  api-reference/beta/api/bookingbusiness-list.md
  api-reference/beta/api/device-delete.md
  api-reference/beta/api/device-post-devices.md
  api-reference/beta/api/device-update.md
  api-reference/beta/api/federatedidentitycredential-delete.md
  api-reference/beta/api/federatedidentitycredential-get.md
  api-reference/beta/api/federatedidentitycredential-update.md
  api-reference/beta/api/search-bookmark-get.md
  api-reference/beta/api/search-qna-get.md
  api-reference/beta/api/search-searchentity-list-bookmarks.md
  api-reference/beta/api/search-searchentity-list-qnas.md
  api-reference/beta/api/search-searchentity-post-bookmarks.md
  api-reference/beta/api/search-searchentity-post-qnas.md
  api-reference/beta/resources/federatedidentitycredential.md
  api-reference/beta/resources/federatedidentitycredentials-overview.md
  api-reference/beta/resources/search-api-answers-overview.md
  api-reference/beta/resources/search-bookmark.md
  api-reference/beta/resources/search-qna.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/device-delete.md
  api-reference/v1.0/api/device-post-devices.md
  api-reference/v1.0/api/device-update.md
  changelog/Microsoft.DirectoryServices.json
  concepts/permissions-reference.md
Labels: internal

#16984 Added what's new for Cloud PC and fixed its TOC.
  api-reference/beta/api/user-list-cloudpcs.md
  api-reference/beta/api/virtualendpoint-list-cloudpcs.md
  api-reference/beta/toc.yml
  concepts/whats-new-overview.md
Labels: do not merge, internal

#16872 Revise tutorial/quickstart/SDK lists
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
  concepts/quick-start-faq.yml
  concepts/sdks/sdk-installation.md
  concepts/toc.yml
  concepts/tutorials.md
  concepts/tutorials.yml
  includes/python-sdk-preview.md
Labels: do not merge, content review complete

#16988 Fixes datetime in Microsoft.CloudManagedDesktop.json
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, internal

#17002 Updated what's new through May 10 (refresh issue).
  api-reference/beta/resources/externalconnectors-connectionquota.md
  changelog/Microsoft.Search.json
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: do not merge, internal

#16990 Minor doc fixes
  api-reference/beta/resources/assignedplan.md
  api-reference/beta/resources/organization.md
  api-reference/beta/resources/user.md
  api-reference/v1.0/resources/assignedplan.md
  api-reference/v1.0/resources/organization.md
  api-reference/v1.0/resources/user.md
  concepts/known-issues.md
Labels: area: Azure AD, ready to merge, internal

#16997 Delete synchronization-synchronizationtemplate-post.md
  api-reference/beta/api/synchronization-synchronizationtemplate-post.md
Labels: area: Azure AD, ready to merge, internal

#15909 Add APIs to get/set CloudPC's review status.
  api-reference/beta/api/manageddevice-bulksetcloudpcreviewstatus.md
  api-reference/beta/api/manageddevice-getcloudpcreviewstatus.md
  api-reference/beta/api/manageddevice-setcloudpcreviewstatus.md
  api-reference/beta/resources/cloudpc.md
  api-reference/beta/resources/cloudpcreviewstatus.md
  api-reference/beta/toc.yml
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, internal, content review complete, schema live

#17024 Edits in PR 16167
  api-reference/beta/resources/managedtenants-cloudpcdevice.md
  api-reference/beta/resources/managedtenants-cloudpcoverview.md
  changelog/Microsoft.MultiTenantPlatform.json
Labels: external

#17023 Edits in PR 16809
  api-reference/beta/api/educationsubmission-list-outcomes.md
  api-reference/beta/api/educationsubmission-post-feedbackresource.md
  api-reference/beta/resources/educationfeedbackresourceoutcome.md
  changelog/Microsoft.EducationAssignment.json
Labels: external

#16378 Add allowedCloudEndpoints property to crossTenantAccessPolicy
  api-reference/beta/api/crosstenantaccesspolicy-get.md
  api-reference/beta/api/crosstenantaccesspolicy-update.md
  api-reference/beta/resources/crosstenantaccesspolicy-overview.md
  api-reference/beta/resources/crosstenantaccesspolicy.md
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, ready to merge, content review complete

#16047 Adding new resource [SharePointTenantSettings] to FileServices workload. API at /admin/sharepoint/settings
  api-reference/beta/api/tenantadmin-settings-get.md
  api-reference/beta/api/tenantadmin-settings-update.md
  api-reference/beta/resources/admin.md
  api-reference/beta/resources/tenantadmin-settings.md
  api-reference/beta/resources/tenantadmin-sharepoint.md
  api-reference/beta/toc.yml
  changelog/Microsoft.FileServices.json
Labels: ready to merge, internal, Build22, content review complete, schema live

#16974 Add new properties to email activity reports v1.0 APIs
  api-reference/beta/api/reportroot-getemailactivitycounts.md
  api-reference/beta/api/reportroot-getemailactivityusercounts.md
  api-reference/beta/api/reportroot-getemailactivityuserdetail.md
  api-reference/v1.0/api/reportroot-getemailactivitycounts.md
  api-reference/v1.0/api/reportroot-getemailactivityusercounts.md
  api-reference/v1.0/api/reportroot-getemailactivityuserdetail.md
  changelog/Microsoft.O365Reporting.json
Labels: ready to merge, internal, content review complete, schema live

#16994 Update to Microsoft Graph documentation hub
  concepts/index.yml
Labels: ready to merge, internal

#17016 Edit Install SDK, Tutorials, Quick start FAQ
  concepts/quick-start-faq.yml
  concepts/sdks/sdk-installation.md
  concepts/tutorials.md
Labels: ready to merge, internal

#17019 Bulk refresh: Query parameters tables
  includes/filter-directory-objects.md
Labels: area: Azure AD, ready to merge, internal

#17020 Update exportPersonalData for users doc
  api-reference/beta/api/user-exportpersonaldata.md
  api-reference/beta/config/link-validation-config.json
  api-reference/v1.0/api/user-exportpersonaldata.md
  api-reference/v1.0/config/link-validation-config.json
Labels: ready to merge, internal

#16653 update doc for pinnedmessage
  api-reference/beta/api/chat-delete-pinnedmessages.md
  api-reference/beta/api/chat-list-pinnedmessages.md
  api-reference/beta/api/chat-post-pinnedmessages.md
  api-reference/beta/resources/chat.md
  api-reference/beta/resources/pinnedchatmessageinfo.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Teams.Core.json
  changelog/Microsoft.Teams.GraphSvc.json
Labels: ready to merge, internal, content review complete

#17021 Update community call link and wording
  concepts/whats-new-overview.md
Labels: ready to merge, internal

#17025 Merge to publish.
  api-reference/beta/api/chat-delete-pinnedmessages.md
  api-reference/beta/api/chat-list-pinnedmessages.md
  api-reference/beta/api/chat-post-pinnedmessages.md
  api-reference/beta/api/crosstenantaccesspolicy-get.md
  api-reference/beta/api/crosstenantaccesspolicy-update.md
  api-reference/beta/api/reportroot-getemailactivitycounts.md
  api-reference/beta/api/reportroot-getemailactivityusercounts.md
  api-reference/beta/api/reportroot-getemailactivityuserdetail.md
  api-reference/beta/api/tenantadmin-settings-get.md
  api-reference/beta/api/tenantadmin-settings-update.md
  api-reference/beta/api/user-exportpersonaldata.md
  api-reference/beta/config/link-validation-config.json
  api-reference/beta/resources/admin.md
  api-reference/beta/resources/chat.md
  api-reference/beta/resources/crosstenantaccesspolicy-overview.md
  api-reference/beta/resources/crosstenantaccesspolicy.md
  api-reference/beta/resources/pinnedchatmessageinfo.md
  api-reference/beta/resources/tenantadmin-settings.md
  api-reference/beta/resources/tenantadmin-sharepoint.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/reportroot-getemailactivitycounts.md
  api-reference/v1.0/api/reportroot-getemailactivityusercounts.md
  api-reference/v1.0/api/reportroot-getemailactivityuserdetail.md
  api-reference/v1.0/api/user-exportpersonaldata.md
  api-reference/v1.0/config/link-validation-config.json
  changelog/Microsoft.DirectoryServices.json
  changelog/Microsoft.FileServices.json
  changelog/Microsoft.O365Reporting.json
  changelog/Microsoft.Teams.Core.json
  changelog/Microsoft.Teams.GraphSvc.json
  concepts/index.yml
  concepts/quick-start-faq.yml
  concepts/sdks/sdk-installation.md
  concepts/tutorials.md
  concepts/whats-new-overview.md
  includes/filter-directory-objects.md
Labels: do not merge, internal

#17028 Refresh the what's new topic.
  api-reference/beta/toc.yml
  api-reference/v1.0/resources/plannerplancontainer.md
  changelog/Microsoft.CloudManagedDesktop.json
  concepts/delta-query-overview.md
  concepts/whats-new-overview.md
Labels: internal

#17040 Update managedtenants-tenanttag-delete.md
  api-reference/beta/api/managedtenants-tenanttag-delete.md
Labels: external

#16853 EM: introduce crossCloudAzureActiveDirectoryTenant in beta
  api-reference/beta/resources/connectedorganization.md
  api-reference/beta/resources/crosscloudazureactivedirectorytenant.md
  api-reference/beta/resources/entitlementmanagement-overview.md
  api-reference/beta/resources/identitysource.md
  changelog/Microsoft.IGAELM.json
Labels: area: Azure AD, ready to merge, internal, content review complete, schema live

#16993 Adding TeamsFx provider docs
  concepts/toc.yml
  concepts/toolkit/providers/teamsfx.md
Labels: ready to merge, internal, content review complete, area: toolkit

#17018 update descriptions in entitlementmanagement.md
  api-reference/beta/resources/entitlementmanagement.md
  api-reference/v1.0/resources/entitlementmanagement.md
Labels: area: Azure AD, ready to merge, ready for content review, internal

#16864 Send activity notification to multiple users in bulk
  api-reference/beta/api/teamwork-sendactivitynotificationtorecipients.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Teams.GraphSvc.json
  concepts/teams-send-activityfeednotifications.md
Labels: ready to merge, internal, content review complete

#16947 restricting scopes to least privileged permissions
  api-reference/beta/api/subscription-post-subscriptions.md
  api-reference/v1.0/api/subscription-post-subscriptions.md
Labels: ready to merge, internal

#17050 Edits in PR 15683
  api-reference/beta/api/informationprotectionlabel-evaluateapplication.md
  api-reference/beta/api/informationprotectionlabel-evaluateclassificationresults.md
  api-reference/beta/api/informationprotectionlabel-evaluateremoval.md
  api-reference/beta/api/informationprotectionlabel-extractlabel.md
  api-reference/beta/api/informationprotectionlabel-get.md
  api-reference/beta/api/informationprotectionpolicy-list-labels.md
  api-reference/beta/resources/informationprotectionaction.md
  api-reference/beta/resources/informationprotectioncontentlabel.md
  api-reference/beta/resources/informationprotectionlabel.md
Labels: external

#17053 Edits in PR 16957
  api-reference/beta/api/chat-list.md
  changelog/Microsoft.Teams.Core.json
Labels: external

#17055 Update educationschool-delete-classes.md
  api-reference/v1.0/api/educationschool-delete-classes.md
Labels: external

#17054 Update educationschool-delete-classes.md
  api-reference/beta/api/educationschool-delete-classes.md
Labels: external

#16590 Azure AD reporting: Adding defaultMethod to Auth Methods report and sessionControlsNotSatisfied to applied CA
  api-reference/beta/api/authenticationmethodsroot-list-userregistrationdetails.md
  api-reference/beta/api/userregistrationdetails-get.md
  api-reference/beta/resources/appliedconditionalaccesspolicy.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/userregistrationdetails.md
  changelog/Microsoft.AAD.Reporting.json
Labels: area: Azure AD, ready to merge, internal, content review complete

#17009 Update max page size in graph search
  api-reference/v1.0/resources/search-api-overview.md
  api-reference/v1.0/resources/searchrequest.md
  changelog/Microsoft.MicrosoftSearch.json
Labels: ready to merge, internal, content review complete

#17060 Merge to publish.
  api-reference/beta/api/authenticationmethodsroot-list-userregistrationdetails.md
  api-reference/beta/api/educationschool-delete-classes.md
  api-reference/beta/api/userregistrationdetails-get.md
  api-reference/beta/resources/appliedconditionalaccesspolicy.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/userregistrationdetails.md
  api-reference/v1.0/api/educationschool-delete-classes.md
  api-reference/v1.0/resources/search-api-overview.md
  api-reference/v1.0/resources/searchrequest.md
  changelog/Microsoft.AAD.Reporting.json
  changelog/Microsoft.DirectoryServices.json
  changelog/Microsoft.MicrosoftSearch.json
Labels: internal

#17031 Fix version in URL for example 3
  api-reference/v1.0/api/application-post-onlinemeetings.md
  api-reference/v1.0/api/onlinemeeting-get.md
Labels: internal, content review complete

#16893 Adding GDPR boxes to GET sign in and LIST sign in
  api-reference/beta/api/signin-get.md
  api-reference/beta/api/signin-list.md
  api-reference/includes/gdpr-msgraph-export-note.md
  api-reference/v1.0/api/signin-get.md
  api-reference/v1.0/api/signin-list.md
Labels: area: Azure AD, ready to merge, internal, content review complete
