Repository microsoftgraph/microsoft-graph-docs, pull requests merged in 2022-12, with the labels that each got.

#19071 ELM - Mark onBehalfAdd unsupported
  api-reference/v1.0/resources/accesspackageassignmentrequest.md
Labels: ready to merge, internal, content review complete

#19245 Promote domain v1 documentation
  api-reference/v1.0/api/domain-promote.md
  api-reference/v1.0/resources/domain.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, do not merge, ready to merge, internal, content review complete

#16857 Export API-Add message history support
  api-reference/beta/api/channel-list-messages.md
  api-reference/beta/api/chat-list-messages.md
  api-reference/beta/api/chat-post-messages.md
  api-reference/beta/api/chatmessage-delta.md
  api-reference/beta/api/chatmessage-get.md
  api-reference/beta/api/chatmessage-list-replies.md
  api-reference/beta/api/chatmessage-post-replies.md
  api-reference/beta/api/chatmessage-post.md
  api-reference/beta/api/chatmessage-update.md
  api-reference/beta/resources/chatmessage.md
  api-reference/beta/resources/chatmessagehistoryitem.md
  api-reference/beta/resources/enums.md
  changelog/Microsoft.Teams.GraphSvc.json
Labels: ready to merge, internal, content review complete, review feedback addressed

#18788 adding support for resetRedemption on v1.0
  api-reference/v1.0/api/invitation-post.md
  api-reference/v1.0/resources/invitation.md
  changelog/Microsoft.AADInviteMgr.json
Labels: area: Azure AD, ready to merge, internal, content review complete, schema live

#19439 Merge to publish.
  api-reference/beta/api/channel-list-messages.md
  api-reference/beta/api/chat-list-messages.md
  api-reference/beta/api/chat-post-messages.md
  api-reference/beta/api/chatmessage-delta.md
  api-reference/beta/api/chatmessage-get.md
  api-reference/beta/api/chatmessage-list-replies.md
  api-reference/beta/api/chatmessage-post-replies.md
  api-reference/beta/api/chatmessage-post.md
  api-reference/beta/api/chatmessage-update.md
  api-reference/beta/resources/chatmessage.md
  api-reference/beta/resources/chatmessagehistoryitem.md
  api-reference/beta/resources/enums.md
  api-reference/v1.0/api/domain-promote.md
  api-reference/v1.0/api/invitation-post.md
  api-reference/v1.0/resources/accesspackageassignmentrequest.md
  api-reference/v1.0/resources/domain.md
  api-reference/v1.0/resources/invitation.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.AADInviteMgr.json
  changelog/Microsoft.DirectoryServices.json
  changelog/Microsoft.Teams.GraphSvc.json
Labels: internal

#19447 Typo "resouce"→"resource"
  api-reference/beta/resources/mediasource.md
Labels: external

#19444 Reverting query parameter
  api-reference/beta/api/security-security-runhuntingquery.md
Labels: external

#19410 Removed "Subscribe to messages across all channels" from onlinemeetings changes doc
  concepts/changenotifications-for-onlinemeeting.md
Labels: ready to merge, content review complete

#19442 Update ms.prod for tracking change notifications docs
  concepts/change-notifications-delivery.md
  concepts/webhooks-lifecycle.md
  concepts/webhooks-with-resource-data.md
  concepts/webhooks.md
Labels: ready to merge, internal, area: change notifications

#19448 Query example numbering update
  api-reference/beta/api/identitygovernance-workflow-list-versions.md
Labels: ready to merge, internal

#19450 Link to signInAudience guidance
  api-reference/beta/api/application-update.md
  api-reference/beta/resources/application.md
  api-reference/v1.0/api/application-update.md
  api-reference/v1.0/resources/application.md
  concepts/toc.yml
Labels: area: Azure AD, ready to merge, internal, area: applications

#19431 Update connecting-external-content-manage-schema.md
  concepts/connecting-external-content-manage-schema.md
Labels: ready to merge, internal, schema live

#19471 Edits in PR 18043
  api-reference/beta/resources/industrydata-azuredatalakeconnector.md
  api-reference/beta/resources/industrydata-filevalidateoperation.md
  api-reference/beta/resources/industrydata-inboundflow.md
  api-reference/beta/resources/industrydata-industrydatarun.md
  api-reference/beta/resources/industrydata-overview.md
  api-reference/beta/resources/industrydata-referencedefinition.md
  api-reference/beta/resources/industrydata-usermatchingsetting.md
Labels: external

#19474 Update plannerplan.md
  api-reference/v1.0/resources/plannerplan.md
Labels: external

#19473 Update plannerplan.md
  api-reference/beta/resources/plannerplan.md
Labels: external

#19472 Update browser-edge-api-overview.md
  api-reference/beta/resources/browser-edge-api-overview.md
Labels: external

#19468 typo fixed
  api-reference/beta/resources/teamsapp.md
Labels: ready to merge

#19463 Typo "resouce"→"resource"
  api-reference/beta/resources/media.md
Labels: external

#19462 Update message-reply.md
  api-reference/beta/api/message-reply.md
Labels: external

#19461 Update message-reply.md
  api-reference/v1.0/api/message-reply.md
Labels: external

#19406 Backfill for Update Assignment|USER STORY 105823
  api-reference/beta/resources/educationassignment.md
  api-reference/v1.0/resources/educationassignment.md
Labels: ready to merge, internal, content review complete

#19415 [Doc Improvement][Feed-notifs-images]
  concepts/images/teams-activityfeednotifications/examplefeednotification.png
  concepts/images/teams-activityfeednotifications/notificationtemplate.png
Labels: ready to merge, internal, content review complete

#19475 Merge to publish.
  api-reference/beta/api/message-reply.md
  api-reference/beta/resources/browser-edge-api-overview.md
  api-reference/beta/resources/educationassignment.md
  api-reference/beta/resources/media.md
  api-reference/beta/resources/plannerplan.md
  api-reference/beta/resources/teamsapp.md
  api-reference/v1.0/api/message-reply.md
  api-reference/v1.0/resources/educationassignment.md
  api-reference/v1.0/resources/plannerplan.md
  api-reference/v1.0/resources/service-communications-api-overview.md
  concepts/images/teams-activityfeednotifications/examplefeednotification.png
  concepts/images/teams-activityfeednotifications/notificationtemplate.png
Labels: internal

#19477 Edits in PR 19015
  api-reference/beta/api/businessscenarioplanner-list-tasks.md
  api-reference/beta/api/plannerplanconfiguration-list-localizations.md
  api-reference/beta/api/plannertaskconfiguration-update.md
  api-reference/beta/resources/businessscenario-planner-overview.md
  api-reference/beta/resources/businessscenario.md
  api-reference/beta/resources/plannertaskpropertyrule.md
  concepts/businessscenarios-concept-overview.md
  concepts/planner-task-rules-overview.md
Labels: external

#19478 Fixed broken links
  concepts/planner-task-rules-overview.md
Labels: external

#19497 Edits PR 18043
  api-reference/beta/resources/industrydata-overview.md
  api-reference/beta/toc.yml
Labels: external

#19499 Update plannerplan-list-tasks.md
  api-reference/beta/api/plannerplan-list-tasks.md
Labels: external

#19496 Update plannerplan-list-tasks.md
  api-reference/v1.0/api/plannerplan-list-tasks.md
Labels: external

#19480 Update plannerbuckettaskboardtaskformat.md
  api-reference/v1.0/resources/plannerbuckettaskboardtaskformat.md
Labels: external

#18297 add documentation for new resources/apis for pages API
  api-reference/beta/api/horizontalsection-get.md
  api-reference/beta/api/horizontalsection-list.md
  api-reference/beta/api/horizontalsectioncolumn-get.md
  api-reference/beta/api/horizontalsectioncolumn-list.md
  api-reference/beta/api/sitepage-create.md
  api-reference/beta/api/sitepage-get.md
  api-reference/beta/api/sitepage-getwebpartsbyposition.md
  api-reference/beta/api/sitepage-list.md
  api-reference/beta/api/sitepage-publish.md
  api-reference/beta/api/sitepage-update.md
  api-reference/beta/api/verticalsection-get.md
  api-reference/beta/api/webpart-get.md
  api-reference/beta/api/webpart-getposition.md
  api-reference/beta/api/webpart-list.md
  api-reference/beta/resources/canvaslayout.md
  api-reference/beta/resources/horizontalsection.md
  api-reference/beta/resources/horizontalsectioncolumn.md
  api-reference/beta/resources/metadatakeystringpair.md
  api-reference/beta/resources/metadatakeyvaluepair.md
  api-reference/beta/resources/reactionsfacet.md
  api-reference/beta/resources/serverprocessedcontent.md
  api-reference/beta/resources/sitepage.md
  api-reference/beta/resources/standardwebpart.md
  api-reference/beta/resources/textwebpart.md
  api-reference/beta/resources/titlearea.md
  api-reference/beta/resources/verticalsection.md
  api-reference/beta/resources/webpart.md
  api-reference/beta/resources/webpartdata.md
  api-reference/beta/resources/webpartposition.md
  api-reference/beta/toc.yml
  changelog/Microsoft.FileServices.json
Labels: area: sharepoint, ready to merge, internal, content review complete, review feedback addressed

#19486 Update migrate-azure-ad-graph-configure-permissions.md
  concepts/migrate-azure-ad-graph-configure-permissions.md
Labels: area: Azure AD, do not merge, ready to merge, internal

#19489 Fix continueOnError description
  api-reference/beta/resources/identitygovernance-task.md
Labels: area: Azure AD, ready to merge, internal, area: governance

#19514 Edits in PR 17441
  api-reference/beta/resources/bookingappointment.md
  api-reference/beta/resources/bookingservice.md
  api-reference/v1.0/resources/bookingappointment.md
  api-reference/v1.0/resources/bookingcustomerinformation.md
  api-reference/v1.0/resources/bookingcustomquestion.md
  api-reference/v1.0/resources/bookingservice.md
  api-reference/v1.0/resources/bookingstaffmember.md
  changelog/Microsoft.Bookings.json
Labels: external

#19515 Edits in PR 17441
  api-reference/v1.0/api/bookingappointment-get.md
  api-reference/v1.0/api/bookingbusiness-list-appointments.md
  api-reference/v1.0/api/bookingbusiness-list-calendarview.md
  api-reference/v1.0/api/bookingbusiness-post-appointments.md
Labels: external

#19517 Edits in PR 17441
  api-reference/beta/api/bookingappointment-get.md
  api-reference/beta/api/bookingbusiness-list-appointments.md
  api-reference/beta/api/bookingbusiness-list-calendarview.md
  api-reference/beta/api/bookingbusiness-list-services.md
  api-reference/beta/api/bookingbusiness-post-appointments.md
  api-reference/beta/api/bookingbusiness-post-services.md
  api-reference/beta/api/bookingservice-get.md
Labels: external

#19519 Update externallink.md
  api-reference/beta/resources/externallink.md
Labels: external

#19518 Update externallink.md
  api-reference/v1.0/resources/externallink.md
Labels: external

#19502 Update event.md
  api-reference/v1.0/resources/event.md
Labels: external

#18831 Add New Permission For Search API
  api-reference/beta/api/search-query.md
Labels: ready to merge, internal, content review complete

#19298 Map Graph API to Azure portal config - PIM rules/settings
  api-reference/beta/api/unifiedrolemanagementpolicyrule-update.md
  api-reference/beta/resources/privilegedidentitymanagementv3-overview.md
  api-reference/v1.0/api/unifiedrolemanagementpolicyrule-update.md
  api-reference/v1.0/resources/privilegedidentitymanagementv3-overview.md
  concepts/how-to-pim-update-rules.md
  concepts/identity-governance-pim-rules-overview.md
  concepts/images/identity-governance-pim-ux-role-rules-screenshots/pim-ux-role-rule.activation.png
  concepts/images/identity-governance-pim-ux-role-rules-screenshots/pim-ux-role-rule.assignment.png
  concepts/images/identity-governance-pim-ux-role-rules-screenshots/pim-ux-role-rule.notification.png
  concepts/toc.yml
Labels: area: Azure AD, do not merge, ready to merge, internal, review feedback addressed, area: governance

#18546 Added CSS styling
  api-reference/beta/api/organizationalbranding-get.md
  api-reference/beta/api/organizationalbranding-list-localizations.md
  api-reference/beta/api/organizationalbranding-update.md
  api-reference/beta/api/organizationalbrandinglocalization-get.md
  api-reference/beta/api/organizationalbrandinglocalization-update.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/loginPageLayoutConfiguration.md
  api-reference/beta/resources/organizationalbranding.md
  api-reference/beta/resources/organizationalbrandinglocalization.md
  api-reference/beta/resources/organizationalbrandingproperties.md
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, ready to merge, internal, content review complete

#19512 Update presence-setpresence.md
  api-reference/beta/api/presence-setpresence.md
  api-reference/v1.0/api/presence-setpresence.md
Labels: external

#19536 Edits in PR 17441
  api-reference/beta/api/bookingservice-update.md
  api-reference/v1.0/api/bookingbusiness-post-services.md
  api-reference/v1.0/api/bookingservice-update.md
  api-reference/v1.0/resources/bookingservice.md
Labels: external

#19537 Edits in PR 17441
  api-reference/beta/api/bookingappointment-get.md
  api-reference/beta/api/bookingbusiness-list-appointments.md
  api-reference/v1.0/api/bookingappointment-get.md
Labels: external

#19539 Edits in PR 19015
  api-reference/beta/api/businessscenarioplanner-list-tasks.md
  api-reference/beta/api/businessscenariotask-update.md
  api-reference/beta/api/plannerplanconfiguration-delete-localizations.md
  api-reference/beta/api/plannerplanconfiguration-get.md
  api-reference/beta/api/plannerplanconfiguration-list-localizations.md
  api-reference/beta/api/plannerplanconfiguration-post-localizations.md
  api-reference/beta/api/plannerplanconfigurationlocalization-get.md
  api-reference/beta/api/plannerplanconfigurationlocalization-update.md
  api-reference/beta/api/plannertaskconfiguration-update.md
Labels: external

#19541 Update identityset.md
  api-reference/v1.0/resources/identityset.md
Labels: external

#19535 Update serviceannouncement-list-healthoverviews.md
  api-reference/v1.0/api/serviceannouncement-list-healthoverviews.md
Labels: external

#19532 Change notifications - supported resources using include
  api-reference/beta/resources/subscription.md
  api-reference/v1.0/resources/subscription.md
  concepts/includes/change-notifications-supported-resources.md
Labels: area: Azure AD, ready to merge, internal, area: change notifications

#18829 [CloudPC]Add partner agent installation status and graph api for retry partner agent
  api-reference/beta/api/cloudpc-retrypartneragentinstallation.md
  api-reference/beta/resources/cloudpc.md
  api-reference/beta/resources/cloudpcpartneragentinstallresult.md
  api-reference/beta/toc.yml
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, internal, content review complete

#19445 update service principal docs with alternate keys usage information
  api-reference/v1.0/api/serviceprincipal-addkey.md
  api-reference/v1.0/api/serviceprincipal-addpassword.md
  api-reference/v1.0/api/serviceprincipal-addtokensigningcertificate.md
  api-reference/v1.0/api/serviceprincipal-delete-approleassignedto.md
  api-reference/v1.0/api/serviceprincipal-delete-approleassignments.md
  api-reference/v1.0/api/serviceprincipal-delete-claimsmappingpolicies.md
  api-reference/v1.0/api/serviceprincipal-delete-delegatedpermissionclassifications.md
  api-reference/v1.0/api/serviceprincipal-delete-homerealmdiscoverypolicies.md
  api-reference/v1.0/api/serviceprincipal-delete-owners.md
  api-reference/v1.0/api/serviceprincipal-delete.md
  api-reference/v1.0/api/serviceprincipal-get.md
  api-reference/v1.0/api/serviceprincipal-list-approleassignedto.md
  api-reference/v1.0/api/serviceprincipal-list-approleassignments.md
  api-reference/v1.0/api/serviceprincipal-list-claimsmappingpolicies.md
  api-reference/v1.0/api/serviceprincipal-list-createdobjects.md
  api-reference/v1.0/api/serviceprincipal-list-delegatedpermissionclassifications.md
  api-reference/v1.0/api/serviceprincipal-list-homerealmdiscoverypolicies.md
  api-reference/v1.0/api/serviceprincipal-list-memberof.md
  api-reference/v1.0/api/serviceprincipal-list-oauth2permissiongrants.md
  api-reference/v1.0/api/serviceprincipal-list-ownedobjects.md
  api-reference/v1.0/api/serviceprincipal-list-owners.md
  api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md
  api-reference/v1.0/api/serviceprincipal-post-approleassignedto.md
  api-reference/v1.0/api/serviceprincipal-post-approleassignments.md
  api-reference/v1.0/api/serviceprincipal-post-claimsmappingpolicies.md
  api-reference/v1.0/api/serviceprincipal-post-delegatedpermissionclassifications.md
  api-reference/v1.0/api/serviceprincipal-post-homerealmdiscoverypolicies.md
  api-reference/v1.0/api/serviceprincipal-post-owners.md
  api-reference/v1.0/api/serviceprincipal-removekey.md
  api-reference/v1.0/api/serviceprincipal-removepassword.md
  api-reference/v1.0/api/serviceprincipal-update.md
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, ready to merge, internal, content review complete

#19460 Added documentation for devices alternate keys usage with deviceId
  api-reference/v1.0/api/device-delete.md
  api-reference/v1.0/api/device-get.md
  api-reference/v1.0/api/device-list-memberof.md
  api-reference/v1.0/api/device-list-registeredowners.md
  api-reference/v1.0/api/device-list-registeredusers.md
  api-reference/v1.0/api/device-list-transitivememberof.md
  api-reference/v1.0/api/device-post-registeredowners.md
  api-reference/v1.0/api/device-post-registeredusers.md
  api-reference/v1.0/api/device-update.md
  api-reference/v1.0/resources/device.md
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, ready to merge, internal, content review complete

#19551 Create changelog-links.yml
  .github/workflows/changelog-links.yml
Labels: internal

#19555 Edits in PR 19104
  api-reference/beta/api/cloudpcorganizationsettings-update.md
  api-reference/beta/api/cloudpcprovisioningpolicy-update.md
  api-reference/beta/resources/cloudpcorganizationsettings.md
  api-reference/beta/resources/cloudpcprovisioningpolicy.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: external

#19556 Fixed invalid links in PR 19015
  changelog/Microsoft.BusinessExtensibility.json
  changelog/Microsoft.Office.Tasks.json
Labels: external

#19558 Edits in PR 19428
  concepts/custom-connector-sdk-sample-hosting.md
  concepts/custom-connector-sdk-troubleshooting.md
Labels: external

#19559 Update virtualendpoint-list-provisioningpolicies.md
  api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md
Labels: external

#19422 [Action Required][Cloud PC] Fix TOC order under Cloud PC node
  api-reference/beta/toc.yml
Labels: ready to merge, internal, content review complete

#19531 Update register your app article
  concepts/auth-register-app-v2.md
  concepts/images/portal-directory-subscription-filter.png
  concepts/images/quickstart-register-app/portal-02-app-reg-01.png
  concepts/images/quickstart-register-app/portal-03-app-reg-02.png
  concepts/images/quickstart-register-app/portal-04-app-reg-03-platform-config.png
  concepts/images/quickstart-register-app/portal-05-app-reg-04-credentials.png
  concepts/includes/active-directory-develop-quickstart-register-app.md
Labels: area: Azure AD, ready to merge, internal

#19553 [METADATA UPDATE] Global metadata/header/navigation changes 
  api-reference/beta/breadcrumb/toc.yml
  api-reference/docfx.json
  api-reference/v1.0/breadcrumb/toc.yml
  concepts/breadcrumb/toc.yml
  concepts/docfx.json
Labels: external, ready to merge

#19542 Update identityset.md
  api-reference/beta/resources/identityset.md
Labels: external, ready to merge

#19545 [Action Needed] Refresh Cloud PC graph API overview
  api-reference/beta/resources/cloudpc-api-overview.md
Labels: do not merge, ready to merge, internal, content review complete

#19547 Update title for programmatic permissions grant
  concepts/permissions-grant-via-msgraph.md
Labels: area: Azure AD, ready to merge, area: permissions

#19548 Ms.prod updates to permissions docs
  concepts/permissions-overview.md
  concepts/permissions-reference.md
Labels: ready to merge, internal

#19562 Merge to publish.
  .github/workflows/changelog-links.yml
  api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md
  api-reference/beta/breadcrumb/toc.yml
  api-reference/beta/resources/cloudpc-api-overview.md
  api-reference/beta/resources/identityset.md
  api-reference/beta/toc.yml
  api-reference/docfx.json
  api-reference/v1.0/breadcrumb/toc.yml
  concepts/auth-register-app-v2.md
  concepts/breadcrumb/toc.yml
  concepts/docfx.json
  concepts/images/portal-directory-subscription-filter.png
  concepts/images/quickstart-register-app/portal-02-app-reg-01.png
  concepts/images/quickstart-register-app/portal-03-app-reg-02.png
  concepts/images/quickstart-register-app/portal-04-app-reg-03-platform-config.png
  concepts/images/quickstart-register-app/portal-05-app-reg-04-credentials.png
  concepts/includes/active-directory-develop-quickstart-register-app.md
  concepts/permissions-grant-via-msgraph.md
  concepts/permissions-overview.md
  concepts/permissions-reference.md
Labels: internal

#19569 Split tutorials into user-auth and app-auth variants
  concepts/toc.yml
  concepts/tutorials.md
Labels: internal

#19428 Rchanda1392 graphconnectors
  concepts/custom-connector-sdk-publish.md
  concepts/custom-connector-sdk-sample-hosting.md
  concepts/custom-connector-sdk-sample-publish.md
  concepts/custom-connector-sdk-sample-search.md
  concepts/custom-connector-sdk-troubleshooting.md
Labels: ready to merge, internal, content review complete, area: connectors

#19550 Update chatmessage.md (beta)
  api-reference/beta/resources/chatmessage.md
Labels: ready to merge, internal, content review complete

#19154 Add ExternalSource to Planner Task, Plan and Bucket
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/plannerbucket.md
  api-reference/beta/resources/plannerbucketcreation.md
  api-reference/beta/resources/plannerexternalbucketsource.md
  api-reference/beta/resources/plannerexternalplansource.md
  api-reference/beta/resources/plannerexternaltasksource.md
  api-reference/beta/resources/plannerplan.md
  api-reference/beta/resources/plannerplancreation.md
  api-reference/beta/resources/plannertaskcreation.md
  api-reference/beta/resources/plannerteamspublicationinfo.md
  changelog/Microsoft.Office.Tasks.json
Labels: ready to merge, internal, content review complete, schema live

#19582 Edits in PR 19104
  changelog/Microsoft.CloudManagedDesktop.json
Labels: external

#19586 Fixed invalid links
  changelog/Microsoft.CloudManagedDesktop.json
Labels: external

#19578 Update search-concept-interleaving.md
  concepts/search-concept-interleaving.md
Labels: ready to merge, internal, Ignite22, content review complete

#18505 [CloudPC]Onboard new canary error type: UdpConnectivityCheckStunUrlNotAllowListed,UdpConnectivityCheckUnknownError
  api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, internal, content review complete, schema live

#18172 Application Permission Support Documentation
  api-reference/beta/api/virtualappointment-delete.md
  api-reference/beta/api/virtualappointment-get.md
  api-reference/beta/api/virtualappointment-put.md
  api-reference/beta/api/virtualappointment-update.md
  api-reference/beta/resources/virtualappointment.md
Labels: ready to merge, internal, content review complete

#17441 Adding attributes for v1 endpoints
  api-reference/beta/api/bookingappointment-get.md
  api-reference/beta/api/bookingbusiness-get.md
  api-reference/beta/api/bookingbusiness-list-appointments.md
  api-reference/beta/api/bookingbusiness-list-calendarview.md
  api-reference/beta/api/bookingbusiness-list-services.md
  api-reference/beta/api/bookingbusiness-post-appointments.md
  api-reference/beta/api/bookingbusiness-post-services.md
  api-reference/beta/api/bookingservice-get.md
  api-reference/beta/api/bookingservice-update.md
  api-reference/beta/api/bookingstaffmember-update.md
  api-reference/beta/resources/bookingappointment.md
  api-reference/beta/resources/bookingbusiness.md
  api-reference/beta/resources/bookingservice.md
  api-reference/beta/resources/bookingstaffmember.md
  api-reference/beta/resources/enums.md
  api-reference/v1.0/api/bookingappointment-get.md
  api-reference/v1.0/api/bookingbusiness-get.md
  api-reference/v1.0/api/bookingbusiness-list-appointments.md
  api-reference/v1.0/api/bookingbusiness-list-calendarview.md
  api-reference/v1.0/api/bookingbusiness-list-services.md
  api-reference/v1.0/api/bookingbusiness-list-staffmembers.md
  api-reference/v1.0/api/bookingbusiness-post-appointments.md
  api-reference/v1.0/api/bookingbusiness-post-bookingbusinesses.md
  api-reference/v1.0/api/bookingbusiness-post-services.md
  api-reference/v1.0/api/bookingbusiness-post-staffmembers.md
  api-reference/v1.0/api/bookingservice-get.md
  api-reference/v1.0/api/bookingservice-update.md
  api-reference/v1.0/api/bookingstaffmember-get.md
  api-reference/v1.0/api/bookingstaffmember-update.md
  api-reference/v1.0/resources/bookingappointment.md
  api-reference/v1.0/resources/bookingbusiness.md
  api-reference/v1.0/resources/bookingcustomerinformation.md
  api-reference/v1.0/resources/bookingservice.md
  api-reference/v1.0/resources/bookingstaffmember.md
  api-reference/v1.0/resources/enums.md
  changelog/Microsoft.Bookings.json
Labels: ready to merge, internal, content review complete

#19549 Delete the code snippets in sitepage-create
  api-reference/beta/api/sitepage-create.md
Labels: ready to merge, internal, content review complete

#19601 Daily publishing 13 DEC 2022
  api-reference/beta/api/bookingappointment-get.md
  api-reference/beta/api/bookingbusiness-get.md
  api-reference/beta/api/bookingbusiness-list-appointments.md
  api-reference/beta/api/bookingbusiness-list-calendarview.md
  api-reference/beta/api/bookingbusiness-list-services.md
  api-reference/beta/api/bookingbusiness-post-appointments.md
  api-reference/beta/api/bookingbusiness-post-services.md
  api-reference/beta/api/bookingservice-get.md
  api-reference/beta/api/bookingservice-update.md
  api-reference/beta/api/bookingstaffmember-update.md
  api-reference/beta/api/sitepage-create.md
  api-reference/beta/api/virtualappointment-delete.md
  api-reference/beta/api/virtualappointment-get.md
  api-reference/beta/api/virtualappointment-put.md
  api-reference/beta/api/virtualappointment-update.md
  api-reference/beta/resources/bookingappointment.md
  api-reference/beta/resources/bookingbusiness.md
  api-reference/beta/resources/bookingservice.md
  api-reference/beta/resources/bookingstaffmember.md
  api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/virtualappointment.md
  api-reference/v1.0/api/bookingappointment-get.md
  api-reference/v1.0/api/bookingbusiness-get.md
  api-reference/v1.0/api/bookingbusiness-list-appointments.md
  api-reference/v1.0/api/bookingbusiness-list-calendarview.md
  api-reference/v1.0/api/bookingbusiness-list-services.md
  api-reference/v1.0/api/bookingbusiness-list-staffmembers.md
  api-reference/v1.0/api/bookingbusiness-post-appointments.md
  api-reference/v1.0/api/bookingbusiness-post-bookingbusinesses.md
  api-reference/v1.0/api/bookingbusiness-post-services.md
  api-reference/v1.0/api/bookingbusiness-post-staffmembers.md
  api-reference/v1.0/api/bookingservice-get.md
  api-reference/v1.0/api/bookingservice-update.md
  api-reference/v1.0/api/bookingstaffmember-get.md
  api-reference/v1.0/api/bookingstaffmember-update.md
  api-reference/v1.0/resources/bookingappointment.md
  api-reference/v1.0/resources/bookingbusiness.md
  api-reference/v1.0/resources/bookingcustomerinformation.md
  api-reference/v1.0/resources/bookingservice.md
  api-reference/v1.0/resources/bookingstaffmember.md
  api-reference/v1.0/resources/chatmessage.md
  api-reference/v1.0/resources/enums.md
  changelog/Microsoft.Bookings.json
  changelog/Microsoft.CloudManagedDesktop.json
  concepts/search-concept-interleaving.md
Labels: do not merge, internal

#19606 Edits in PR 19015
  api-reference/beta/resources/businessscenario-planner-overview.md
  api-reference/beta/resources/plannertaskpropertyrule.md
  api-reference/beta/toc.yml
  concepts/permissions-reference.md
  concepts/planner-concept-overview.md
  concepts/planner-task-rules-overview.md
  concepts/toc.yml
Labels: external

#19610 Clarify what SDKs in preview status means.
  concepts/sdks/sdks-overview.md
  concepts/sdks/use-beta.md
Labels: do not merge, internal

#19611 Publish clarification about SDKs in preview status.
  concepts/sdks/sdks-overview.md
  concepts/sdks/use-beta.md
Labels: internal

#19617 Minor doc fixes
  api-reference/beta/api/group-post-groups.md
  api-reference/beta/api/riskdetection-get.md
  api-reference/beta/api/riskdetection-list.md
  api-reference/beta/api/riskyuser-list-history.md
  api-reference/beta/api/riskyuserhistoryitem-get.md
  api-reference/beta/api/riskyusers-confirmcompromised.md
  api-reference/beta/api/riskyusers-dismiss.md
  api-reference/beta/api/riskyusers-get.md
  api-reference/beta/api/riskyusers-list.md
  api-reference/beta/resources/group.md
  api-reference/beta/resources/riskdetection.md
  api-reference/beta/resources/riskuseractivity.md
  api-reference/beta/resources/riskyuser.md
  api-reference/beta/resources/riskyuserhistoryitem.md
  api-reference/beta/resources/targetresource.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/group-post-groups.md
  api-reference/v1.0/api/riskdetection-get.md
  api-reference/v1.0/api/riskdetection-list.md
  api-reference/v1.0/api/riskyuser-confirmcompromised.md
  api-reference/v1.0/api/riskyuser-dismiss.md
  api-reference/v1.0/api/riskyuser-get-riskyuserhistoryitem.md
  api-reference/v1.0/api/riskyuser-get.md
  api-reference/v1.0/api/riskyuser-list-history.md
  api-reference/v1.0/api/riskyuser-list.md
  api-reference/v1.0/resources/group.md
  api-reference/v1.0/resources/riskuseractivity.md
  api-reference/v1.0/resources/riskyuser.md
  api-reference/v1.0/resources/riskyuserhistoryitem.md
  api-reference/v1.0/toc.yml
Labels: area: Azure AD, ready to merge, internal

#19604 Alphabetizing
  api-reference/v1.0/resources/aaduserconversationmember.md
  api-reference/v1.0/resources/accessreviewinstance.md
  api-reference/v1.0/resources/accessreviewnotificationrecipientitem.md
  api-reference/v1.0/resources/accessreviewnotificationrecipientqueryscope.md
  api-reference/v1.0/resources/accessreviewreviewerscope.md
  api-reference/v1.0/resources/accessreviewscheduledefinition.md
  api-reference/v1.0/resources/activitybasedtimeoutpolicy.md
  api-reference/v1.0/resources/alternativeSecurityId.md
  api-reference/v1.0/resources/archivedprintjob.md
  api-reference/v1.0/resources/assignedlabel.md
  api-reference/v1.0/resources/attendeebase.md
  api-reference/v1.0/resources/audioconferencing.md
  api-reference/v1.0/resources/authenticationcontextclassreference.md
  api-reference/v1.0/resources/authenticationflowspolicy.md
Labels: ready to merge, internal

#19469 Python SDK: updates to whats new
  concepts/whats-new-overview.md
Labels: ready to merge, ready for content review, internal

#19587 Add Limitations Warning of Attendance Report API
  api-reference/beta/api/meetingattendancereport-get.md
  api-reference/v1.0/api/meetingattendancereport-get.md
Labels: ready to merge, internal, content review complete

#19622 Daily publishing 14 DEC 2022
  api-reference/beta/api/group-post-groups.md
  api-reference/beta/api/meetingattendancereport-get.md
  api-reference/beta/api/riskdetection-get.md
  api-reference/beta/api/riskdetection-list.md
  api-reference/beta/api/riskyuser-list-history.md
  api-reference/beta/api/riskyuserhistoryitem-get.md
  api-reference/beta/api/riskyusers-confirmcompromised.md
  api-reference/beta/api/riskyusers-dismiss.md
  api-reference/beta/api/riskyusers-get.md
  api-reference/beta/api/riskyusers-list.md
  api-reference/beta/resources/group.md
  api-reference/beta/resources/riskdetection.md
  api-reference/beta/resources/riskuseractivity.md
  api-reference/beta/resources/riskyuser.md
  api-reference/beta/resources/riskyuserhistoryitem.md
  api-reference/beta/resources/targetresource.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/group-post-groups.md
  api-reference/v1.0/api/meetingattendancereport-get.md
  api-reference/v1.0/api/riskdetection-get.md
  api-reference/v1.0/api/riskdetection-list.md
  api-reference/v1.0/api/riskyuser-confirmcompromised.md
  api-reference/v1.0/api/riskyuser-dismiss.md
  api-reference/v1.0/api/riskyuser-get-riskyuserhistoryitem.md
  api-reference/v1.0/api/riskyuser-get.md
  api-reference/v1.0/api/riskyuser-list-history.md
  api-reference/v1.0/api/riskyuser-list.md
  api-reference/v1.0/resources/aaduserconversationmember.md
  api-reference/v1.0/resources/accessreviewinstance.md
  api-reference/v1.0/resources/accessreviewnotificationrecipientitem.md
  api-reference/v1.0/resources/accessreviewnotificationrecipientqueryscope.md
  api-reference/v1.0/resources/accessreviewreviewerscope.md
  api-reference/v1.0/resources/accessreviewscheduledefinition.md
  api-reference/v1.0/resources/activitybasedtimeoutpolicy.md
  api-reference/v1.0/resources/alternativeSecurityId.md
  api-reference/v1.0/resources/archivedprintjob.md
  api-reference/v1.0/resources/assignedlabel.md
  api-reference/v1.0/resources/attendeebase.md
  api-reference/v1.0/resources/audioconferencing.md
  api-reference/v1.0/resources/authenticationcontextclassreference.md
  api-reference/v1.0/resources/authenticationflowspolicy.md
  api-reference/v1.0/resources/group.md
  api-reference/v1.0/resources/riskuseractivity.md
  api-reference/v1.0/resources/riskyuser.md
  api-reference/v1.0/resources/riskyuserhistoryitem.md
  api-reference/v1.0/toc.yml
  concepts/whats-new-overview.md
Labels: internal

#19625 Edits in PR 19430
  api-reference/beta/resources/educationresource.md
  api-reference/beta/resources/educationteamsappresource.md
  api-reference/v1.0/api/educationassignment-post-resource.md
  api-reference/v1.0/resources/educationresource.md
  api-reference/v1.0/resources/educationteamsappresource.md
  changelog/Microsoft.EducationAssignment.json
Labels: external

#19627 Edits in PR 19458
  api-reference/beta/api/cloudpcreports-getshareduselicenseusagereoport.md
  api-reference/beta/resources/cloudpcexportjob.md
  api-reference/beta/resources/cloudpcreports.md
  api-reference/beta/toc.yml
  changelog/Microsoft.CloudManagedDesktop.json
Labels: external

#19621 Updated Go paging snippets for latest SDK
  concepts/sdks/paging.md
Labels: ready to merge, internal

#19560 Add AzureAD Admin role information to permissions section
  api-reference/beta/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration.md
  api-reference/v1.0/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration.md
Labels: area: Azure AD, external, awaiting internal response, ready to merge, review requested

#19633 Fix typo: servicePrinciple -> servicePrincipal
  api-reference/v1.0/api/serviceprincipal-list.md
Labels: external, ready to merge

#19638 Daily publishing 15 DEC 2022
  api-reference/beta/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration.md
  api-reference/v1.0/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration.md
  api-reference/v1.0/api/serviceprincipal-list.md
  concepts/sdks/paging.md
Labels: do not merge, internal

#19642 Update SP owners
  api-reference/beta/api/serviceprincipal-post-owners.md
  api-reference/v1.0/api/serviceprincipal-post-owners.md
Labels: area: Azure AD, ready to merge, internal

#19509 Add limitation notes for create shared channel
  api-reference/beta/api/channel-post.md
  api-reference/v1.0/api/channel-post.md
Labels: ready to merge, internal, content review complete

#19572 Add QnA.Read.All Permisison
  api-reference/beta/api/search-query.md
  changelog/Microsoft.MicrosoftSearch.json
  concepts/permissions-reference.md
Labels: ready to merge, internal, content review complete

#19645 Daily publishing 16 DEC 2022
  api-reference/beta/api/channel-post.md
  api-reference/beta/api/search-query.md
  api-reference/beta/api/serviceprincipal-post-owners.md
  api-reference/v1.0/api/channel-post.md
  api-reference/v1.0/api/serviceprincipal-post-owners.md
  changelog/Microsoft.MicrosoftSearch.json
  concepts/permissions-reference.md
Labels: internal

#19239 Documentation for new setStatusMessage action and presenceStatusMessage type
  api-reference/beta/api/presence-setstatusmessage.md
  api-reference/beta/resources/presence.md
  api-reference/beta/resources/presenceStatusMessage.md
  changelog/Microsoft.Skype.Calling.json
Labels: ready to merge, internal, content review complete

#19646 Daily publishing II 16 DEC 2022
  api-reference/beta/api/presence-setstatusmessage.md
  api-reference/beta/resources/presence.md
  api-reference/beta/resources/presenceStatusMessage.md
  changelog/Microsoft.Skype.Calling.json
Labels: internal

#19647 Edits in PR 19209
  concepts/permissions-reference.md
Labels: external

#19648 Edits in PR 19430
  api-reference/beta/resources/educationteamsappresource.md
  changelog/Microsoft.EducationAssignment.json
Labels: external

#19649 Edits in PR 19430
  api-reference/v1.0/resources/educationteamsappresource.md
  changelog/Microsoft.EducationAssignment.json
Labels: external

#19650 Edits in PR 19430
  api-reference/beta/api/educationassignment-post-resources.md
  api-reference/beta/resources/educationresource.md
  api-reference/v1.0/api/educationassignment-post-resource.md
  api-reference/v1.0/resources/educationresource.md
  changelog/Microsoft.EducationAssignment.json
Labels: external

#19652 Edits in PR 18884
  api-reference/beta/api/attacksimulationroot-create-simulation.md
  api-reference/beta/api/attacksimulationroot-delete-simulation.md
  api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md
  api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md
  api-reference/beta/api/attacksimulationroot-get-operation.md
  api-reference/beta/api/attacksimulationroot-get-payload.md
  api-reference/beta/api/attacksimulationroot-get-payloadsDetails.md
  api-reference/beta/api/attacksimulationroot-list-payloads.md
  api-reference/beta/api/attacksimulationroot-list-simulations.md
  api-reference/beta/api/attacksimulationroot-update-simulation.md
  api-reference/beta/resources/accounttargetcontent.md
  api-reference/beta/resources/addressbookaccounttargetcontent.md
  api-reference/beta/resources/attackSimulationOperation.md
  api-reference/beta/resources/emailPayloadDetail.md
  api-reference/beta/resources/includeallaccounttargetcontent.md
  api-reference/beta/resources/payload.md
  api-reference/beta/resources/payloadCoachmark.md
  api-reference/beta/resources/payloadDetail.md
  api-reference/beta/toc.yml
Labels: external

#19664 Edits in PR 18359
  api-reference/beta/resources/cloudpconpremisesconnection.md
  api-reference/beta/resources/cloudpcsupportedregion.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: external

#19662 Added presence-setstatusmessage to TOC in beta.
  api-reference/beta/toc.yml
Labels: ready to merge, internal, content review complete

#19595 Correction in update to-do list example and its description
  concepts/onenote-note-tags.md
Labels: ready to merge, internal, customer support issue, content review complete

#19667 Generate proof of possession keys (update)
  concepts/application-rollkey-prooftoken.md
  concepts/toc.yml
Labels: area: Azure AD, ready to merge, internal

#19676 Edits in PR 18884
  api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md
  api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md
  api-reference/beta/resources/accounttargetcontent.md
  api-reference/beta/resources/addressbookaccounttargetcontent.md
  api-reference/beta/resources/attacksimulationoperation.md
  api-reference/beta/resources/coachmarklocation.md
  api-reference/beta/resources/emailpayloaddetail.md
  api-reference/beta/resources/includeallaccounttargetcontent.md
  api-reference/beta/resources/longrunningoperation.md
  api-reference/beta/resources/payload.md
  api-reference/beta/resources/payloadcoachmark.md
  api-reference/beta/resources/payloaddetail.md
  api-reference/beta/resources/simulation.md
Labels: external

#19678 Reordered Cloud PC TOC sub-nodes for consistency.
  api-reference/beta/toc.yml
Labels: do not merge, internal

#19679 Re-order sub-nodes of "Cloud PCs" for consistency.
  api-reference/beta/toc.yml
Labels: internal

#19059 Add description for alert workflow
  api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md
  api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md
  api-reference/beta/resources/cloudpc-api-overview.md
  api-reference/beta/resources/devicemanagement-alertimpact.md
  api-reference/beta/resources/devicemanagement-alertrecord.md
  api-reference/beta/resources/devicemanagement-alertrule.md
  api-reference/beta/resources/devicemanagement-monitoring.md
  api-reference/beta/resources/devicemanagement-portalnotification.md
  api-reference/beta/resources/devicemanagement-rulethreshold.md
  api-reference/beta/toc.yml
Labels: do not merge, changes requested, internal, content review in progress

#19683 Publish content and TOC updates for the monitoring APIs.
  api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md
  api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md
  api-reference/beta/resources/cloudpc-api-overview.md
  api-reference/beta/resources/devicemanagement-alertimpact.md
  api-reference/beta/resources/devicemanagement-alertrecord.md
  api-reference/beta/resources/devicemanagement-alertrule.md
  api-reference/beta/resources/devicemanagement-monitoring.md
  api-reference/beta/resources/devicemanagement-portalnotification.md
  api-reference/beta/resources/devicemanagement-rulethreshold.md
  api-reference/beta/toc.yml
Labels: internal

#19690 Edits in PR 19458
  api-reference/beta/resources/cloudpcexportjob.md
Labels: external

#19687 Fix broken links in DirectoryServices changelog file
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, ready to merge, internal

#19686 Group members - update allowed members note
  api-reference/beta/api/group-list-transitivemembers.md
  api-reference/beta/api/group-post-members.md
  api-reference/beta/resources/groups-overview.md
  api-reference/v1.0/api/group-list-transitivemembers.md
  api-reference/v1.0/api/group-post-members.md
  api-reference/v1.0/resources/groups-overview.md
  concepts/includes/groups-allowed-member-types.md
Labels: area: Azure AD, area: groups, ready to merge

#19631 [Change notifications] Move supported resources to one shared table
  api-reference/beta/resources/subscription.md
  api-reference/beta/resources/webhooks.md
  api-reference/v1.0/resources/subscription.md
  api-reference/v1.0/resources/webhooks.md
  concepts/includes/change-notifications-supported-resources-expanded.md
  concepts/includes/change-notifications-supported-resources-flat.md
  concepts/webhooks.md
Labels: area: Azure AD, ready to merge, internal, area: change notifications

#19692 Daily publishing DEC 21st 2022
  api-reference/beta/api/group-list-transitivemembers.md
  api-reference/beta/api/group-post-members.md
  api-reference/beta/resources/groups-overview.md
  api-reference/beta/resources/subscription.md
  api-reference/beta/resources/webhooks.md
  api-reference/v1.0/api/group-list-transitivemembers.md
  api-reference/v1.0/api/group-post-members.md
  api-reference/v1.0/resources/groups-overview.md
  api-reference/v1.0/resources/subscription.md
  api-reference/v1.0/resources/webhooks.md
  changelog/Microsoft.DirectoryServices.json
  concepts/includes/change-notifications-supported-resources-expanded.md
  concepts/includes/change-notifications-supported-resources-flat.md
  concepts/includes/groups-allowed-member-types.md
  concepts/webhooks.md
Labels: internal

#19691 Renamed TOC title per guidance for consistency.
  api-reference/beta/resources/cloudpc-api-overview.md
  api-reference/beta/resources/devicemanagement-monitoring.md
  api-reference/beta/toc.yml
Labels: do not merge, internal

#19693 Publish renaming of TOC title per guidance for consistency.
  api-reference/beta/resources/cloudpc-api-overview.md
  api-reference/beta/resources/devicemanagement-monitoring.md
  api-reference/beta/toc.yml
Labels: internal

#19694 Edits in PR 18884
  api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md
  api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md
  api-reference/beta/api/attacksimulationroot-get-operation.md
  api-reference/beta/api/attacksimulationroot-get-payloadsdetails.md
  api-reference/beta/resources/accounttargetcontent.md
  api-reference/beta/resources/addressbookaccounttargetcontent.md
  api-reference/beta/resources/attacksimulationoperation.md
  api-reference/beta/resources/attacksimulationroot.md
  api-reference/beta/resources/emailpayloaddetail.md
  api-reference/beta/resources/includeallaccounttargetcontent.md
  api-reference/beta/resources/longrunningoperation.md
  api-reference/beta/resources/payload.md
  api-reference/beta/resources/payloadcoachmark.md
  api-reference/beta/resources/payloaddetail.md
  api-reference/beta/resources/simulation.md
  api-reference/beta/toc.yml
Labels: external

#19699 Incorporated a few new items from November.
  api-reference/beta/api/security-ediscoverysearch-purgedata.md
  api-reference/v1.0/api/security-ediscoverysearch-purgedata.md
  changelog/Microsoft.Security.Ediscovery.json
  concepts/whats-new-overview.md
Labels: internal

#19701 Refresh what's new through Nov. 30.
  api-reference/beta/api/security-ediscoverysearch-purgedata.md
  api-reference/v1.0/api/security-ediscoverysearch-purgedata.md
  changelog/Microsoft.Security.Ediscovery.json
  concepts/whats-new-overview.md
Labels: internal

#19174 Remove nullable for plannerPlanContainer URL
  api-reference/beta/api/planner-post-plans.md
  api-reference/beta/resources/plannerplan.md
  api-reference/beta/resources/plannerplancontainer.md
  api-reference/v1.0/api/planner-post-plans.md
  api-reference/v1.0/resources/plannerplan.md
  api-reference/v1.0/resources/plannerplancontainer.md
  changelog/Microsoft.Office.Tasks.json
Labels: ready to merge, internal, content review complete

#19716 A few more items through Dec. 22, 2022.
  api-reference/beta/api/sitepage-getwebpartsbyposition.md
  api-reference/beta/resources/plannerexternalbucketsource.md
  api-reference/beta/resources/plannerexternalplansource.md
  api-reference/beta/resources/plannerexternaltasksource.md
  api-reference/beta/toc.yml
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: do not merge, internal

#19719 Refreshed what's new on the live site.
  api-reference/beta/api/sitepage-getwebpartsbyposition.md
  api-reference/beta/resources/plannerexternalbucketsource.md
  api-reference/beta/resources/plannerexternalplansource.md
  api-reference/beta/resources/plannerexternaltasksource.md
  api-reference/beta/toc.yml
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: do not merge, internal

#19715 Adds isIncrementalConsentDisabled for MSAL2
  concepts/toolkit/providers/msal2.md
Labels: ready to merge

#19714 Updating reference for People API
  concepts/toolkit/components/people-picker.md
Labels: ready to merge

#19713 Clarify Teams migration mode throttling limits
  concepts/throttling-limits.md
Labels: ready to merge

#19630 Removing "the" from Microsoft Graph
  concepts/toolkit/components/agenda.md
  concepts/toolkit/components/file-list.md
  concepts/toolkit/components/file.md
  concepts/toolkit/components/get.md
  concepts/toolkit/components/login.md
  concepts/toolkit/components/people-picker.md
  concepts/toolkit/components/people.md
  concepts/toolkit/components/person-card.md
  concepts/toolkit/components/person.md
  concepts/toolkit/components/tasks.md
  concepts/toolkit/components/teams-channel-picker.md
  concepts/toolkit/components/todo.md
Labels: ready to merge

#19142 Allow Collapse Against ExternalItem
  api-reference/beta/resources/search-api-overview.md
  concepts/search-concept-collapse.md
Labels: ready to merge, internal, content review complete

#18363 [Doc Issue][Get channel does not support $expand]
  api-reference/beta/api/channel-get.md
  api-reference/v1.0/api/channel-get.md
Labels: ready to merge, internal, content review complete
