Repository microsoftgraph/microsoft-graph-docs, pull requests merged in 2022-04, with the labels that each got.

#16375 Update bundle-removeitem.md
  api-reference/beta/api/bundle-removeitem.md
Labels: external

#16374 Update bundle-removeitem.md
  api-reference/v1.0/api/bundle-removeitem.md
Labels: external

#15939 Purge data
  api-reference/beta/api/ediscovery-sourcecollection-purgedata.md
  api-reference/beta/resources/ediscovery-caseoperation.md
  api-reference/beta/resources/ediscovery-purgedataoperation.md
  api-reference/beta/resources/ediscovery-sourcecollection.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Compliance.Ediscovery.json
Labels: ready to merge, internal, review feedback addressed

#16348 Add permissions to call and participant APIs
  api-reference/beta/api/application-post-calls.md
  api-reference/beta/api/call-answer.md
  api-reference/beta/api/call-cancelmediaprocessing.md
  api-reference/beta/api/call-changescreensharingrole.md
  api-reference/beta/api/call-delete.md
  api-reference/beta/api/call-get.md
  api-reference/beta/api/call-keepalive.md
  api-reference/beta/api/call-list-audioroutinggroups.md
  api-reference/beta/api/call-list-participants.md
  api-reference/beta/api/call-mute.md
  api-reference/beta/api/call-playprompt.md
  api-reference/beta/api/call-post-audioroutinggroups.md
  api-reference/beta/api/call-record.md
  api-reference/beta/api/call-redirect.md
  api-reference/beta/api/call-reject.md
  api-reference/beta/api/call-subscribetotone.md
  api-reference/beta/api/call-transfer.md
  api-reference/beta/api/call-unmute.md
  api-reference/beta/api/call-updaterecordingstatus.md
  api-reference/beta/api/participant-configuremixer.md
  api-reference/beta/api/participant-delete.md
  api-reference/beta/api/participant-get.md
  api-reference/beta/api/participant-invite.md
  api-reference/beta/api/participant-mute.md
  api-reference/beta/api/participant-muteall.md
  api-reference/beta/api/participant-startholdmusic.md
  api-reference/beta/api/participant-stopholdmusic.md
  api-reference/v1.0/api/application-post-calls.md
  api-reference/v1.0/api/call-answer.md
  api-reference/v1.0/api/call-cancelmediaprocessing.md
  api-reference/v1.0/api/call-changescreensharingrole.md
  api-reference/v1.0/api/call-delete.md
  api-reference/v1.0/api/call-get.md
  api-reference/v1.0/api/call-keepalive.md
  api-reference/v1.0/api/call-list-participants.md
  api-reference/v1.0/api/call-mute.md
  api-reference/v1.0/api/call-playprompt.md
  api-reference/v1.0/api/call-record.md
  api-reference/v1.0/api/call-redirect.md
  api-reference/v1.0/api/call-reject.md
  api-reference/v1.0/api/call-subscribetotone.md
  api-reference/v1.0/api/call-transfer.md
  api-reference/v1.0/api/call-unmute.md
  api-reference/v1.0/api/call-updaterecordingstatus.md
  api-reference/v1.0/api/participant-delete.md
  api-reference/v1.0/api/participant-get.md
  api-reference/v1.0/api/participant-invite.md
  api-reference/v1.0/api/participant-mute.md
  api-reference/v1.0/api/participant-startholdmusic.md
  api-reference/v1.0/api/participant-stopholdmusic.md
Labels: ready to merge, internal, content review complete

#16355 [Azure AD roles] [Admin units] toc fix
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
Labels: area: Azure AD, ready to merge, internal, content review complete

#16360 [Azure ABAC] [Custom security attributes] Link to Limits and constraints
  api-reference/beta/resources/custom-security-attributes-overview.md
Labels: area: Azure AD, ready to merge, internal, content review complete

#15098 introduce policy and OBO to entitlement management in Graph v1.0
  api-reference/v1.0/api/accesspackage-get.md
  api-reference/v1.0/api/accesspackageassignmentpolicy-delete.md
  api-reference/v1.0/api/accesspackageassignmentpolicy-get.md
  api-reference/v1.0/api/accesspackageassignmentpolicy-update.md
  api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md
  api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md
  api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md
  api-reference/v1.0/resources/accesspackage.md
  api-reference/v1.0/resources/accesspackageapprovalstage.md
  api-reference/v1.0/resources/accesspackageassignment.md
  api-reference/v1.0/resources/accesspackageassignmentapprovalsettings.md
  api-reference/v1.0/resources/accesspackageassignmentpolicy.md
  api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md
  api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md
  api-reference/v1.0/resources/entitlementmanagement-overview.md
  api-reference/v1.0/resources/entitlementmanagement.md
  api-reference/v1.0/resources/enums.md
  api-reference/v1.0/resources/subjectset.md
  api-reference/v1.0/resources/targetapplicationowners.md
  api-reference/v1.0/resources/targetmanager.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.DirectoryServices.json
  changelog/Microsoft.IGAELM.json
Labels: area: Azure AD, ready to merge, internal, content review complete, schema live

#16354 unified RBAC: add EM in v1.0
  api-reference/v1.0/api/rbacapplication-list-roleassignments.md
  api-reference/v1.0/api/rbacapplication-list-roledefinitions.md
  api-reference/v1.0/api/rbacapplication-post-roleassignments.md
  api-reference/v1.0/api/unifiedroleassignment-delete.md
  api-reference/v1.0/api/unifiedroleassignment-get.md
  api-reference/v1.0/api/unifiedroledefinition-get.md
  api-reference/v1.0/resources/entitlementmanagement-overview.md
Labels: area: Azure AD, ready to merge, internal, content review complete

#16376 List of call end reasons.
  api-reference/beta/api/call-delete.md
  api-reference/v1.0/api/call-delete.md
Labels: ready to merge, internal, content review complete

#16387 Minor doc updates
  api-reference/beta/api/signin-list.md
  api-reference/beta/api/user-get.md
  api-reference/beta/api/user-list-memberof.md
  api-reference/beta/api/user-list-ownedobjects.md
  api-reference/beta/api/user-list-registereddevices.md
  api-reference/beta/api/user-list.md
  api-reference/beta/api/user-update.md
  api-reference/v1.0/api/signin-list.md
  api-reference/v1.0/api/user-get.md
  api-reference/v1.0/api/user-list-owneddevices.md
  api-reference/v1.0/api/user-list-ownedobjects.md
  api-reference/v1.0/api/user-list-registereddevices.md
  api-reference/v1.0/api/user-list.md
  api-reference/v1.0/api/user-update.md
  concepts/query-parameters.md
Labels: area: Azure AD, ready to merge, internal

#16392 Graph Task Triggers and task definition should have same app Id
  api-reference/beta/api/printer-post-tasktriggers.md
  api-reference/v1.0/api/printer-post-tasktriggers.md
  concepts/universal-print-concept-overview.md
Labels: ready to merge, internal, area: universal print

#16406 Edits in PR 16065
  api-reference/beta/resources/call.md
  changelog/Microsoft.Skype.Calling.json
Labels: external

#16329 Remove Ruby from supported SDKs
  concepts/sdks/sdks-overview.md
Labels: ready to merge, internal

#16408 Edits in PR 16104
  api-reference/beta/api/call-addlargegalleryview.md
  api-reference/beta/resources/addlargegalleryviewoperation.md
  changelog/Microsoft.Skype.Calling.json
Labels: external

#16412 Fixed minor typo
  api-reference/v1.0/api/serviceprincipal-addkey.md
Labels: do not merge, internal

#16409 Update group.md
  api-reference/v1.0/resources/group.md
Labels: external

#16398 Minor fixes
  api-reference/beta/api/directory-deleteditems-list.md
  api-reference/beta/api/passwordauthenticationmethod-resetpassword.md
  api-reference/beta/resources/group.md
  api-reference/beta/resources/passwordauthenticationmethod.md
  api-reference/beta/resources/user.md
  api-reference/v1.0/api/directory-deleteditems-list.md
  api-reference/v1.0/resources/group.md
  api-reference/v1.0/resources/user.md
  includes/filter-directory-objects.md
Labels: area: Azure AD, ready to merge, internal

#16377 adding context on the isArchived property
  api-reference/v1.0/resources/group.md
Labels: area: Azure AD, ready to merge, internal, content review complete

#16065 updates for content sharing notifications
  api-reference/beta/api/application-post-calls.md
  api-reference/beta/api/call-answer.md
  api-reference/beta/api/call-list-contentsharingsessions.md
  api-reference/beta/api/contentsharingsession-get.md
  api-reference/beta/resources/call.md
  api-reference/beta/resources/calloptions.md
  api-reference/beta/resources/contentsharingsession.md
  api-reference/beta/resources/incomingcalloptions.md
  api-reference/beta/resources/outgoingcalloptions.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Skype.Calling.json
Labels: ready to merge, content review complete, schema live, review feedback addressed

#16388 entitlement management: add example of creating a request with requestType userAdd
  api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md
Labels: area: Azure AD, ready to merge, internal, content review complete

#16321 update teamwork device description and TOC
  api-reference/beta/resources/teamworkdevice.md
Labels: ready to merge, internal, content review complete

#16413 Revert "updates for content sharing notifications"
  api-reference/beta/api/application-post-calls.md
  api-reference/beta/api/call-answer.md
  api-reference/beta/api/call-list-contentsharingsessions.md
  api-reference/beta/api/contentsharingsession-get.md
  api-reference/beta/resources/call.md
  api-reference/beta/resources/calloptions.md
  api-reference/beta/resources/contentsharingsession.md
  api-reference/beta/resources/incomingcalloptions.md
  api-reference/beta/resources/outgoingcalloptions.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Skype.Calling.json
Labels: ready to merge, internal

#16414 Merge to publish.
  api-reference/beta/api/directory-deleteditems-list.md
  api-reference/beta/api/passwordauthenticationmethod-resetpassword.md
  api-reference/beta/resources/group.md
  api-reference/beta/resources/passwordauthenticationmethod.md
  api-reference/beta/resources/teamworkdevice.md
  api-reference/beta/resources/user.md
  api-reference/v1.0/api/directory-deleteditems-list.md
  api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md
  api-reference/v1.0/api/serviceprincipal-addkey.md
  api-reference/v1.0/resources/group.md
  api-reference/v1.0/resources/user.md
  concepts/sdks/sdks-overview.md
  includes/filter-directory-objects.md
Labels: internal

#16428 Edits in PR 16093
  api-reference/beta/api/application-post-calls.md
  api-reference/beta/resources/joinmeetingidmeetinginfo.md
  api-reference/beta/resources/meetinginfo.md
Labels: external

#16432 Update call-answer.md
  api-reference/v1.0/api/call-answer.md
Labels: external

#16426 [BrokenLinksH2] Fix path in link
  concepts/application-proxy-configure-api.md
Labels: external

#16431 Update bundle-update.md
  api-reference/v1.0/api/bundle-update.md
Labels: external

#16429 Edits in PR 16104
  api-reference/beta/api/call-addlargegalleryview.md
  api-reference/beta/resources/addlargegalleryviewoperation.md
Labels: external, conflicting

#16290 Access Reviews Graph API overview GDPR note
  api-reference/beta/api/accessreviewscheduledefinition-delete.md
  api-reference/beta/resources/accessreviewsv2-overview.md
  api-reference/includes/accessreviews-gdpr-delete-intro-sentence.md
  api-reference/includes/accessreviews-gdpr-overview-note.md
  api-reference/v1.0/api/accessreviewscheduledefinition-delete.md
  api-reference/v1.0/resources/accessreviewsv2-overview.md
Labels: area: Azure AD, ready to merge, content review complete

#16385 Change sub-node name Get auth tokens > Authentication and authorization
  concepts/toc.yml
Labels: ready to merge, internal

#16427 Update conditionalaccessplatforms.md
  api-reference/beta/resources/conditionalaccessplatforms.md
Labels: ready to merge, internal, content review complete

#14650 shared channel beta - updated
  api-reference/beta/api/associatedteaminfo-list.md
  api-reference/beta/api/channel-delete-members.md
  api-reference/beta/api/channel-doesuserhaveaccess.md
  api-reference/beta/api/channel-get-members.md
  api-reference/beta/api/channel-list-members.md
  api-reference/beta/api/channel-list.md
  api-reference/beta/api/channel-post-members.md
  api-reference/beta/api/channel-post.md
  api-reference/beta/api/channel-update-members.md
  api-reference/beta/api/sharedwithchannelteaminfo-delete.md
  api-reference/beta/api/sharedwithchannelteaminfo-get.md
  api-reference/beta/api/sharedwithchannelteaminfo-list-allowedmembers.md
  api-reference/beta/api/sharedwithchannelteaminfo-list.md
  api-reference/beta/api/team-delete-incomingchannel.md
  api-reference/beta/api/team-list-allchannels.md
  api-reference/beta/api/team-list-incomingchannels.md
  api-reference/beta/api/user-list-joinedteams.md
  api-reference/beta/resources/associatedteaminfo.md
  api-reference/beta/resources/channel.md
  api-reference/beta/resources/group.md
  api-reference/beta/resources/sharedwithchannelteaminfo.md
  api-reference/beta/resources/team.md
  api-reference/beta/resources/teaminfo.md
  api-reference/beta/resources/teams-api-overview.md
  api-reference/beta/resources/userteamwork.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Teams.Core.json
  concepts/known-issues.md
  concepts/teams-changenotifications-team-and-channel.md
Labels: ready to merge, internal, content review complete, review feedback addressed

#16446 Edits in PR 16104
  api-reference/beta/api/call-addlargegalleryview.md
  api-reference/beta/resources/identifylargegalleryview.md
Labels: external

#16454 Update team-list-allchannels.md
  api-reference/beta/api/team-list-allchannels.md
Labels: external

#16453 Update team-list-incomingchannels.md
  api-reference/beta/api/team-list-incomingchannels.md
Labels: external

#16452 Update team-delete-incomingchannel.md
  api-reference/beta/api/team-delete-incomingchannel.md
Labels: external

#16451 Update channel-doesuserhaveaccess.md
  api-reference/beta/api/channel-doesuserhaveaccess.md
Labels: external

#16450 Update sharedwithchannelteaminfo-list.md
  api-reference/beta/api/sharedwithchannelteaminfo-list.md
Labels: external

#16449 Update sharedwithchannelteaminfo-get.md
  api-reference/beta/api/sharedwithchannelteaminfo-get.md
Labels: external

#16448 Update sharedwithchannelteaminfo-delete.md
  api-reference/beta/api/sharedwithchannelteaminfo-delete.md
Labels: external

#16447 Update sharedwithchannelteaminfo-list-allowedmembers.md
  api-reference/beta/api/sharedwithchannelteaminfo-list-allowedmembers.md
Labels: external

#15948 Updated Graph API Doc for Teams user usage
  api-reference/beta/api/reportroot-getteamsuseractivitycounts.md
  api-reference/beta/api/reportroot-getteamsuseractivitytotalcounts.md
  api-reference/beta/api/reportroot-getteamsuseractivitytotaldistributioncounts.md
  api-reference/beta/api/reportroot-getteamsuseractivityuserdetail.md
  api-reference/beta/resources/microsoft-teams-user-activity-reports.md
  api-reference/beta/toc.yml
  changelog/Microsoft.O365Reporting.json
Labels: ready to merge, internal

#16394 Updated online meeting doc and added a warning
  api-reference/beta/api/meetingattendancereport-get.md
  api-reference/beta/api/meetingattendancereport-list.md
  api-reference/v1.0/api/meetingattendancereport-get.md
  api-reference/v1.0/api/meetingattendancereport-list.md
Labels: ready to merge, internal, review feedback addressed

#16419 Update GDAP ms.prod to customer-relationship-management
  api-reference/beta/api/delegatedadminaccessassignment-delete.md
  api-reference/beta/api/delegatedadminaccessassignment-get.md
  api-reference/beta/api/delegatedadminaccessassignment-update.md
  api-reference/beta/api/delegatedadmincustomer-get.md
  api-reference/beta/api/delegatedadmincustomer-list-servicemanagementdetails.md
  api-reference/beta/api/delegatedadminrelationship-delete.md
  api-reference/beta/api/delegatedadminrelationship-get.md
  api-reference/beta/api/delegatedadminrelationship-list-accessassignments.md
  api-reference/beta/api/delegatedadminrelationship-list-operations.md
  api-reference/beta/api/delegatedadminrelationship-list-requests.md
  api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md
  api-reference/beta/api/delegatedadminrelationship-post-requests.md
  api-reference/beta/api/delegatedadminrelationship-update.md
  api-reference/beta/api/delegatedadminrelationshipoperation-get.md
  api-reference/beta/api/delegatedadminrelationshiprequest-get.md
  api-reference/beta/api/tenantrelationship-list-delegatedadmincustomers.md
  api-reference/beta/api/tenantrelationship-list-delegatedadminrelationships.md
  api-reference/beta/api/tenantrelationship-post-delegatedadminrelationships.md
  api-reference/beta/resources/delegatedadminaccessassignment.md
  api-reference/beta/resources/delegatedadminaccesscontainer.md
  api-reference/beta/resources/delegatedadminaccessdetails.md
  api-reference/beta/resources/delegatedadmincustomer.md
  api-reference/beta/resources/delegatedadminrelationship.md
  api-reference/beta/resources/delegatedadminrelationshipcustomerparticipant.md
  api-reference/beta/resources/delegatedadminrelationshipoperation.md
  api-reference/beta/resources/delegatedadminrelationshiprequest.md
  api-reference/beta/resources/delegatedadminservicemanagementdetail.md
  api-reference/beta/resources/unifiedrole.md
Labels: area: Azure AD, ready to merge, internal

#16457 Merge to publish.
  api-reference/beta/api/channel-doesuserhaveaccess.md
  api-reference/beta/api/delegatedadminaccessassignment-delete.md
  api-reference/beta/api/delegatedadminaccessassignment-get.md
  api-reference/beta/api/delegatedadminaccessassignment-update.md
  api-reference/beta/api/delegatedadmincustomer-get.md
  api-reference/beta/api/delegatedadmincustomer-list-servicemanagementdetails.md
  api-reference/beta/api/delegatedadminrelationship-delete.md
  api-reference/beta/api/delegatedadminrelationship-get.md
  api-reference/beta/api/delegatedadminrelationship-list-accessassignments.md
  api-reference/beta/api/delegatedadminrelationship-list-operations.md
  api-reference/beta/api/delegatedadminrelationship-list-requests.md
  api-reference/beta/api/delegatedadminrelationship-post-accessassignments.md
  api-reference/beta/api/delegatedadminrelationship-post-requests.md
  api-reference/beta/api/delegatedadminrelationship-update.md
  api-reference/beta/api/delegatedadminrelationshipoperation-get.md
  api-reference/beta/api/delegatedadminrelationshiprequest-get.md
  api-reference/beta/api/meetingattendancereport-get.md
  api-reference/beta/api/meetingattendancereport-list.md
  api-reference/beta/api/reportroot-getteamsuseractivitycounts.md
  api-reference/beta/api/reportroot-getteamsuseractivitytotalcounts.md
  api-reference/beta/api/reportroot-getteamsuseractivitytotaldistributioncounts.md
  api-reference/beta/api/reportroot-getteamsuseractivityuserdetail.md
  api-reference/beta/api/sharedwithchannelteaminfo-delete.md
  api-reference/beta/api/sharedwithchannelteaminfo-get.md
  api-reference/beta/api/sharedwithchannelteaminfo-list-allowedmembers.md
  api-reference/beta/api/sharedwithchannelteaminfo-list.md
  api-reference/beta/api/team-delete-incomingchannel.md
  api-reference/beta/api/team-list-allchannels.md
  api-reference/beta/api/team-list-incomingchannels.md
  api-reference/beta/api/tenantrelationship-list-delegatedadmincustomers.md
  api-reference/beta/api/tenantrelationship-list-delegatedadminrelationships.md
  api-reference/beta/api/tenantrelationship-post-delegatedadminrelationships.md
  api-reference/beta/resources/conditionalaccessplatforms.md
  api-reference/beta/resources/delegatedadminaccessassignment.md
  api-reference/beta/resources/delegatedadminaccesscontainer.md
  api-reference/beta/resources/delegatedadminaccessdetails.md
  api-reference/beta/resources/delegatedadmincustomer.md
  api-reference/beta/resources/delegatedadminrelationship.md
  api-reference/beta/resources/delegatedadminrelationshipcustomerparticipant.md
  api-reference/beta/resources/delegatedadminrelationshipoperation.md
  api-reference/beta/resources/delegatedadminrelationshiprequest.md
  api-reference/beta/resources/delegatedadminservicemanagementdetail.md
  api-reference/beta/resources/microsoft-teams-user-activity-reports.md
  api-reference/beta/resources/unifiedrole.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/meetingattendancereport-get.md
  api-reference/v1.0/api/meetingattendancereport-list.md
  changelog/Microsoft.O365Reporting.json
Labels: internal

#16461 - updates kiota libs reference for Go after move
  concepts/sdks/choose-authentication-providers.md
  concepts/sdks/create-client.md
  concepts/sdks/customize-client.md
  concepts/sdks/sdk-installation.md
  concepts/sdks/use-beta.md
Labels: ready to merge, area: sample code, internal

#16462 Edits in PR 16207
  api-reference/beta/api/bookingappointment-get.md
  api-reference/beta/api/bookingbusiness-get.md
  api-reference/beta/api/bookingsbusiness-business-rules.md
  api-reference/beta/resources/bookingavailability.md
  api-reference/beta/resources/bookingstaffavailabilityitem.md
  api-reference/beta/resources/bookingstaffavailabilityresponse.md
  api-reference/v1.0/api/bookingcustomer-delete.md
Labels: external

#16464 Update call-list-audioroutinggroups.md
  api-reference/beta/api/call-list-audioroutinggroups.md
Labels: external

#16463 Update message.md
  api-reference/beta/resources/message.md
Labels: external

#16367 Refine some strings in ANC pages and also some missed OPNC
  api-reference/beta/api/cloudpconpremisesconnection-delete.md
  api-reference/beta/api/cloudpconpremisesconnection-update.md
  api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md
  api-reference/beta/api/virtualendpoint-post-onpremisesconnections.md
  api-reference/beta/resources/cloudpconpremisesconnection.md
Labels: ready to merge, internal, content review complete

#16255 Cloud pc/add windows settings
  api-reference/beta/api/cloudpcorganizationsettings-get.md
  api-reference/beta/api/cloudpcorganizationsettings-update.md
  api-reference/beta/resources/cloudpcorganizationsettings.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, internal, content review complete, schema live, review feedback addressed

#16425 Add DAP API Overview
  api-reference/beta/config/link-validation-config.json
  api-reference/beta/resources/delegatedadminrelationships-api-overview.md
  api-reference/beta/toc.yml
Labels: area: Azure AD, ready to merge, internal, area: customer relationship management

#16466 Merge to publish.
  api-reference/beta/api/call-list-audioroutinggroups.md
  api-reference/beta/api/cloudpconpremisesconnection-delete.md
  api-reference/beta/api/cloudpconpremisesconnection-update.md
  api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md
  api-reference/beta/api/cloudpcorganizationsettings-get.md
  api-reference/beta/api/cloudpcorganizationsettings-update.md
  api-reference/beta/api/virtualendpoint-post-onpremisesconnections.md
  api-reference/beta/config/link-validation-config.json
  api-reference/beta/resources/cloudpconpremisesconnection.md
  api-reference/beta/resources/cloudpcorganizationsettings.md
  api-reference/beta/resources/delegatedadminrelationships-api-overview.md
  api-reference/beta/resources/message.md
  api-reference/beta/toc.yml
  changelog/Microsoft.CloudManagedDesktop.json
  concepts/sdks/choose-authentication-providers.md
  concepts/sdks/create-client.md
  concepts/sdks/customize-client.md
  concepts/sdks/sdk-installation.md
  concepts/sdks/use-beta.md
Labels: internal

#16475 Use GDAP as advised by PG and for consistency across
  api-reference/beta/resources/delegatedadminrelationships-api-overview.md
  api-reference/beta/toc.yml
  concepts/permissions-reference.md
Labels: area: Azure AD, ready to merge, internal

#16477 Merge to publish.
  api-reference/beta/resources/delegatedadminrelationships-api-overview.md
  api-reference/beta/toc.yml
  concepts/permissions-reference.md
Labels: internal

#16207 Kwekua bookings 3 16
  api-reference/beta/api/bookingappointment-cancel.md
  api-reference/beta/api/bookingappointment-delete.md
  api-reference/beta/api/bookingappointment-get.md
  api-reference/beta/api/bookingappointment-update.md
  api-reference/beta/api/bookingbusiness-delete.md
  api-reference/beta/api/bookingbusiness-get.md
  api-reference/beta/api/bookingbusiness-getstaffavailability.md
  api-reference/beta/api/bookingbusiness-list-appointments.md
  api-reference/beta/api/bookingbusiness-list-calendarview.md
  api-reference/beta/api/bookingbusiness-list-services.md
  api-reference/beta/api/bookingbusiness-list-staffmembers.md
  api-reference/beta/api/bookingbusiness-list.md
  api-reference/beta/api/bookingbusiness-post-appointments.md
  api-reference/beta/api/bookingcustomer-delete.md
  api-reference/beta/api/bookingcustomer-get.md
  api-reference/beta/api/bookingcustomer-update.md
  api-reference/beta/api/bookingcustomquestion-get.md
  api-reference/beta/api/bookingservice-get.md
  api-reference/beta/api/bookingstaffmember-get.md
  api-reference/beta/resources/availabilityitem.md
  api-reference/beta/resources/bookingappointment.md
  api-reference/beta/resources/bookingbusiness.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/staffavailabilityitem.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/bookingcustomer-delete.md
  changelog/Microsoft.Bookings.json
  concepts/bookingsbusiness-business-rules.md
  concepts/images/business-hrs.png
  concepts/images/default-schd-policy.png
  concepts/permissions-reference.md
  concepts/toc.yml
Labels: ready to merge, content review complete, schema live

#16478 Merge to publish.
  api-reference/beta/api/bookingappointment-cancel.md
  api-reference/beta/api/bookingappointment-delete.md
  api-reference/beta/api/bookingappointment-get.md
  api-reference/beta/api/bookingappointment-update.md
  api-reference/beta/api/bookingbusiness-delete.md
  api-reference/beta/api/bookingbusiness-get.md
  api-reference/beta/api/bookingbusiness-getstaffavailability.md
  api-reference/beta/api/bookingbusiness-list-appointments.md
  api-reference/beta/api/bookingbusiness-list-calendarview.md
  api-reference/beta/api/bookingbusiness-list-services.md
  api-reference/beta/api/bookingbusiness-list-staffmembers.md
  api-reference/beta/api/bookingbusiness-list.md
  api-reference/beta/api/bookingbusiness-post-appointments.md
  api-reference/beta/api/bookingcustomer-delete.md
  api-reference/beta/api/bookingcustomer-get.md
  api-reference/beta/api/bookingcustomer-update.md
  api-reference/beta/api/bookingcustomquestion-get.md
  api-reference/beta/api/bookingservice-get.md
  api-reference/beta/api/bookingstaffmember-get.md
  api-reference/beta/resources/availabilityitem.md
  api-reference/beta/resources/bookingappointment.md
  api-reference/beta/resources/bookingbusiness.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/staffavailabilityitem.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/bookingcustomer-delete.md
  changelog/Microsoft.Bookings.json
  concepts/bookingsbusiness-business-rules.md
  concepts/images/business-hrs.png
  concepts/images/default-schd-policy.png
  concepts/permissions-reference.md
  concepts/toc.yml
Labels: do not merge, internal

#16487 Update Microsoft.Bookings.json
  changelog/Microsoft.Bookings.json
Labels: internal

#16459 Config changes to reflect the default branch from master to main. Please merge to complete the default branch renaming job.
  .openpublishing.publish.config.json
Labels: do not merge, internal

#16488 merge changelog fix to live
  .openpublishing.publish.config.json
  changelog/Microsoft.Bookings.json
Labels: internal

#16489 Edits in PR 16104
  api-reference/beta/api/call-addlargegalleryview-get.md
  api-reference/beta/api/call-addlargegalleryview.md
  changelog/Microsoft.Skype.Calling.json
  concepts/cloud-communications-identifylargegalleryview.md
Labels: external

#16507 Update Microsoft.Bookings.json
  changelog/Microsoft.Bookings.json
Labels: internal, content review complete

#16515 Merge to publish.
  changelog/Microsoft.Bookings.json
Labels: internal

#16493 accessReviewHistoryDefinition removing reference to unreleased scheduleSettings feature
  api-reference/beta/api/accessreviewset-post-historydefinitions.md
  api-reference/beta/resources/accessreviewhistorydefinition.md
  api-reference/v1.0/api/accessreviewset-post-historydefinitions.md
  api-reference/v1.0/resources/accessreviewhistorydefinition.md
Labels: area: Azure AD, ready to merge, internal, content review complete

#16480 Reassign webhooks article + update title
  concepts/webhooks-lifecycle.md
  concepts/webhooks.md
Labels: area: Azure AD, ready to merge, internal

#16390 Adding group relationship with team
  api-reference/beta/resources/group.md
  api-reference/v1.0/resources/group.md
Labels: area: Azure AD, ready to merge, internal, content review complete, review feedback addressed

#16526 Updating Live with the latest content updates for Identity
  api-reference/beta/api/accessreviewset-post-historydefinitions.md
  api-reference/beta/resources/accessreviewhistorydefinition.md
  api-reference/beta/resources/group.md
  api-reference/v1.0/api/accesspackageassignmentpolicy-update.md
  api-reference/v1.0/api/accessreviewset-post-historydefinitions.md
  api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md
  api-reference/v1.0/resources/accessreviewhistorydefinition.md
  api-reference/v1.0/resources/entitlementmanagementschedule.md
  api-reference/v1.0/resources/group.md
  concepts/webhooks-lifecycle.md
  concepts/webhooks.md
Labels: internal

#16456 Create a contextual TOC to the PSh docs and remove the PSh folder
  concepts/insights-customize-item-insights-privacy.md
  concepts/powershell/RegisterAppOnly.ps1
  concepts/powershell/app-only.md
  concepts/powershell/get-started.md
  concepts/powershell/images/aad-application-id.png
  concepts/powershell/images/aad-portal-app-registrations.png
  concepts/powershell/images/configured-permissions.png
  concepts/powershell/images/register-app.png
  concepts/powershell/installation.md
  concepts/powershell/navigating.md
  concepts/sdks/create-requests.md
  concepts/sdks/sdk-installation.md
  concepts/toc.yml
Labels: ready for content review, internal

#16529 - updates query parameters and headers options for Go page iterator s…
  concepts/sdks/paging.md
Labels: bug: sample, ready to merge, area: sample code, internal

#16530 Groups overview refresh
  api-reference/beta/api/group-post-members.md
  api-reference/beta/resources/groups-overview.md
  concepts/aad-advanced-queries.md
  concepts/images/yesandnosymbols/greencheck.svg
  concepts/images/yesandnosymbols/no.svg
  concepts/images/yesandnosymbols/whitecheck-in-greencircle.svg
  includes/filter-directory-objects.md
Labels: area: Azure AD, ready to merge, internal

#16524 Windows application patch
  api-reference/beta/api/application-get.md
  api-reference/beta/resources/windowsapplication.md
Labels: area: Azure AD, ready to merge, internal

#16532 Minor doc updates
  api-reference/beta/api/application-post-extensionproperty.md
  api-reference/beta/resources/directoryaudit.md
  api-reference/v1.0/api/application-post-extensionproperty.md
  api-reference/v1.0/resources/directoryaudit.md
Labels: area: Azure AD, ready to merge, internal

#16534 Updating Live with the latest in Main
  api-reference/beta/api/application-get.md
  api-reference/beta/api/application-post-extensionproperty.md
  api-reference/beta/api/group-post-members.md
  api-reference/beta/resources/directoryaudit.md
  api-reference/beta/resources/groups-overview.md
  api-reference/beta/resources/windowsapplication.md
  api-reference/v1.0/api/application-post-extensionproperty.md
  api-reference/v1.0/resources/directoryaudit.md
  concepts/aad-advanced-queries.md
  concepts/images/yesandnosymbols/greencheck.svg
  concepts/images/yesandnosymbols/no.svg
  concepts/images/yesandnosymbols/whitecheck-in-greencircle.svg
  concepts/insights-customize-item-insights-privacy.md
  concepts/powershell/RegisterAppOnly.ps1
  concepts/powershell/app-only.md
  concepts/powershell/get-started.md
  concepts/powershell/images/aad-application-id.png
  concepts/powershell/images/aad-portal-app-registrations.png
  concepts/powershell/images/configured-permissions.png
  concepts/powershell/images/register-app.png
  concepts/powershell/installation.md
  concepts/powershell/navigating.md
  concepts/sdks/create-requests.md
  concepts/sdks/paging.md
  concepts/sdks/sdk-installation.md
  concepts/toc.yml
  includes/filter-directory-objects.md
Labels: internal

#16383 Q3 small signin updates
  api-reference/beta/api/signin-confirmcompromised.md
  api-reference/beta/api/signin-confirmsafe.md
  api-reference/beta/api/signin-get.md
  api-reference/beta/api/signin-list.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/signin.md
  api-reference/beta/toc.yml
  changelog/Microsoft.AAD.Reporting.json
Labels: area: Azure AD, ready to merge, internal, content review complete

#16140 Internal federation api docs
  api-reference/beta/api/domain-post-federationconfiguration.md
  api-reference/beta/api/internaldomainfederation-delete.md
  api-reference/beta/api/internaldomainfederation-get.md
  api-reference/beta/api/internaldomainfederation-update.md
  api-reference/beta/resources/domain.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/internaldomainfederation.md
  api-reference/beta/resources/signingcertificateupdatestatus.md
  api-reference/beta/toc.yml
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, ready to merge, internal, content review complete, schema live

#16537 Updating Live with Identity doc updates
  api-reference/beta/api/domain-post-federationconfiguration.md
  api-reference/beta/api/internaldomainfederation-delete.md
  api-reference/beta/api/internaldomainfederation-get.md
  api-reference/beta/api/internaldomainfederation-update.md
  api-reference/beta/api/signin-confirmcompromised.md
  api-reference/beta/api/signin-confirmsafe.md
  api-reference/beta/api/signin-get.md
  api-reference/beta/api/signin-list.md
  api-reference/beta/resources/domain.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/internaldomainfederation.md
  api-reference/beta/resources/signin.md
  api-reference/beta/resources/signingcertificateupdatestatus.md
  api-reference/beta/toc.yml
  changelog/Microsoft.AAD.Reporting.json
  changelog/Microsoft.DirectoryServices.json
Labels: internal

#16506 Edits in PR 15683
  api-reference/beta/api/informationprotectionlabel-evaluateapplication.md
  api-reference/beta/api/informationprotectionlabel-evaluateclassificationresults.md
  api-reference/beta/api/informationprotectionlabel-evaluateremoval.md
  api-reference/beta/api/informationprotectionlabel-extractlabel.md
  api-reference/beta/api/security-informationprotectionpolicysetting-get.md
  api-reference/beta/api/security-list-sensitivitylabels.md
  api-reference/beta/api/security-sensitivitylabel-evaluateapplication.md
  api-reference/beta/api/security-sensitivitylabel-evaluateclassificationresults.md
  api-reference/beta/api/security-sensitivitylabel-evaluateremoval.md
  api-reference/beta/api/security-sensitivitylabel-extractcontentlabel.md
  api-reference/beta/api/security-sensitivitylabel-get.md
  api-reference/beta/resources/security-contentlabel.md
  api-reference/beta/resources/security-informationprotection.md
  api-reference/beta/resources/security-recommendlabelaction.md
  concepts/security-information-protection-overview.md
Labels: external

#16521 Edits in PR 16415
  api-reference/beta/api/documentsetversion-delete.md
  api-reference/beta/api/documentsetversion-get.md
  api-reference/beta/api/documentsetversion-restore.md
  api-reference/beta/api/listitem-list-documentsetversions.md
  api-reference/beta/api/listitem-post-documentsetversions.md
  api-reference/beta/resources/documentsetversion.md
  api-reference/beta/resources/documentsetversionitem.md
  api-reference/beta/resources/listitem.md
  changelog/Microsoft.FileServices.json
Labels: external, conflicting

#16554 - updates go paging snippet imports
  concepts/sdks/paging.md
Labels: ready to merge, area: sample code, internal

#16518 Edits in PR 16104
  api-reference/beta/resources/addlargegalleryviewoperation.md
  api-reference/beta/resources/call.md
  concepts/cloud-communications-identifylargegalleryview.md
Labels: external

#16540 Edits in PR 16455
  api-reference/beta/api/listitem-delta.md
Labels: external

#16523 Update chat-delete-tabs.md
  api-reference/v1.0/api/chat-delete-tabs.md
Labels: external

#16522 Update chat-delete-tabs.md
  api-reference/beta/api/chat-delete-tabs.md
Labels: external

#16535 Update channel-post-members.md
  api-reference/beta/api/channel-post-members.md
  api-reference/v1.0/api/channel-post-members.md
Labels: external, ready to merge

#16509 Update reportroot-getteamsdeviceusageuserdetail.md
  api-reference/beta/api/reportroot-getteamsdeviceusageuserdetail.md
Labels: external

#16508 Update reportroot-getteamsdeviceusageuserdetail.md
  api-reference/v1.0/api/reportroot-getteamsdeviceusageuserdetail.md
Labels: external

#16491 Update bookingbusiness-getstaffavailability.md
  api-reference/beta/api/bookingbusiness-getstaffavailability.md
Labels: external

#16490 Update staffavailabilityitem.md
  api-reference/beta/resources/staffavailabilityitem.md
Labels: external

#15930 Adding resources and api documentation for ExtractSensitivityLabel API
  api-reference/beta/api/driveitem-extractsensitivitylabels.md
  api-reference/beta/resources/driveitem.md
  api-reference/beta/resources/extractsensitivitylabelsresult.md
  api-reference/beta/resources/sensitivitylabelassignment.md
  api-reference/beta/toc.yml
  changelog/Microsoft.FileServices.json
Labels: ready to merge, internal, Build22, content review complete

#16516 Added link to Login Prompt Behavior
  concepts/auth-v2-user.md
Labels: external, ready to merge

#15972 New Teams team Graph API doc
  api-reference/beta/api/reportroot-getteamsteamactivitycounts.md
  api-reference/beta/api/reportroot-getteamsteamactivitydetail.md
  api-reference/beta/api/reportroot-getteamsteamactivitydistributioncounts.md
  api-reference/beta/resources/microsoft-teams-team-usage-reports.md
  api-reference/beta/resources/report.md
  api-reference/beta/toc.yml
  changelog/Microsoft.O365Reporting.json
  concepts/reportroot-concept-overview.md
Labels: ready to merge, internal, content review complete

#16351 Adding "emailuser" to TeamworkUserIdentity
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/teamworkuseridentity.md
  api-reference/v1.0/resources/enums.md
  api-reference/v1.0/resources/teamworkuseridentity.md
  changelog/Microsoft.Teams.Core.json
Labels: awaiting internal response, ready to merge, internal, content review complete

#16550 updates for content sharing notifications
  api-reference/beta/api/application-post-calls.md
  api-reference/beta/api/call-answer.md
  api-reference/beta/api/call-list-contentsharingsessions.md
  api-reference/beta/api/contentsharingsession-get.md
  api-reference/beta/resources/call.md
  api-reference/beta/resources/calloptions.md
  api-reference/beta/resources/contentsharingsession.md
  api-reference/beta/resources/incomingcalloptions.md
  api-reference/beta/resources/outgoingcalloptions.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Skype.Calling.json
Labels: ready to merge, content review complete, schema live

#16557 Edits to Graph Overview
  concepts/overview.md
Labels: do not merge, internal

#16558 Merge to publish.
  api-reference/beta/api/application-post-calls.md
  api-reference/beta/api/bookingbusiness-getstaffavailability.md
  api-reference/beta/api/call-answer.md
  api-reference/beta/api/call-list-contentsharingsessions.md
  api-reference/beta/api/channel-post-members.md
  api-reference/beta/api/chat-delete-tabs.md
  api-reference/beta/api/contentsharingsession-get.md
  api-reference/beta/api/driveitem-extractsensitivitylabels.md
  api-reference/beta/api/reportroot-getteamsdeviceusageuserdetail.md
  api-reference/beta/api/reportroot-getteamsteamactivitycounts.md
  api-reference/beta/api/reportroot-getteamsteamactivitydetail.md
  api-reference/beta/api/reportroot-getteamsteamactivitydistributioncounts.md
  api-reference/beta/resources/call.md
  api-reference/beta/resources/calloptions.md
  api-reference/beta/resources/contentsharingsession.md
  api-reference/beta/resources/driveitem.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/extractsensitivitylabelsresult.md
  api-reference/beta/resources/incomingcalloptions.md
  api-reference/beta/resources/microsoft-teams-team-usage-reports.md
  api-reference/beta/resources/outgoingcalloptions.md
  api-reference/beta/resources/report.md
  api-reference/beta/resources/sensitivitylabelassignment.md
  api-reference/beta/resources/staffavailabilityitem.md
  api-reference/beta/resources/teamworkuseridentity.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/channel-post-members.md
  api-reference/v1.0/api/chat-delete-tabs.md
  api-reference/v1.0/api/reportroot-getteamsdeviceusageuserdetail.md
  api-reference/v1.0/resources/enums.md
  api-reference/v1.0/resources/teamworkuseridentity.md
  changelog/Microsoft.FileServices.json
  changelog/Microsoft.O365Reporting.json
  changelog/Microsoft.Skype.Calling.json
  changelog/Microsoft.Teams.Core.json
  concepts/auth-v2-user.md
  concepts/overview.md
  concepts/reportroot-concept-overview.md
  concepts/sdks/paging.md
Labels: internal

#16560 Brought what's new topic to mid March.
  api-reference/beta/resources/search-api-answers-overview.md
  changelog/Microsoft.CloudManagedDesktop.json
  changelog/Microsoft.Search.Admin.json
  concepts/search-concept-answers.md
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: do not merge, internal

#16555 Updates to Go Message Paging Examples
  concepts/sdks/paging.md
Labels: external, ready to merge, content review complete

#16569 Edits in PR 15683
  api-reference/beta/api/security-informationprotectionpolicysetting-get.md
  api-reference/beta/api/security-list-sensitivitylabels.md
  api-reference/beta/api/security-sensitivitylabel-evaluateapplication.md
  api-reference/beta/api/security-sensitivitylabel-evaluateclassificationresults.md
  api-reference/beta/api/security-sensitivitylabel-evaluateremoval.md
  api-reference/beta/api/security-sensitivitylabel-extractcontentlabel.md
  api-reference/beta/api/security-sensitivitylabel-get.md
  api-reference/beta/resources/security-contentinfo.md
Labels: external

#16568 Edits in PR 16415
  api-reference/beta/api/documentsetversion-delete.md
  api-reference/beta/api/documentsetversion-get.md
  api-reference/beta/api/documentsetversion-restore.md
  api-reference/beta/api/listitem-list-documentsetversions.md
  api-reference/beta/api/listitem-post-documentsetversions.md
  api-reference/beta/resources/documentsetversion.md
  api-reference/beta/resources/documentsetversionitem.md
  api-reference/beta/resources/listitem.md
  changelog/Microsoft.FileServices.json
Labels: external

#16572 Removed planId property
  api-reference/beta/api/plannerbucket-update.md
  api-reference/v1.0/api/plannerbucket-update.md
Labels: external, ready to merge

#16573 Merge to publish.
  api-reference/beta/api/plannerbucket-update.md
  api-reference/v1.0/api/plannerbucket-update.md
  changelog/Microsoft.Skype.Calling.json
  concepts/connecting-external-content-connectors-api-postman.md
  concepts/sdks/paging.md
  redirects/.openpublishing.redirection.1221.json
Labels: internal

#16579 Corrected the PowerShell redirects to make the source path an in-repo…
  redirects/.openpublishing.redirection.1221.json
Labels: ready for content review, internal

#16536 Minor doc fixes
  api-reference/beta/api/application-list-extensionproperty.md
  api-reference/beta/api/extensionproperty-delete.md
  api-reference/beta/api/extensionproperty-get.md
  api-reference/beta/api/group-post-approleassignments.md
  api-reference/v1.0/api/application-list-extensionproperty.md
  api-reference/v1.0/api/extensionproperty-delete.md
  api-reference/v1.0/api/extensionproperty-get.md
  api-reference/v1.0/api/group-post-approleassignments.md
Labels: area: Azure AD, ready to merge, internal

#16553 EM apps can read role definitions and update assignments
  api-reference/v1.0/api/rbacapplication-list-roleassignments.md
  api-reference/v1.0/api/rbacapplication-list-roledefinitions.md
  api-reference/v1.0/api/rbacapplication-post-roleassignments.md
  api-reference/v1.0/api/unifiedroleassignment-delete.md
  api-reference/v1.0/api/unifiedroleassignment-get.md
  api-reference/v1.0/api/unifiedroledefinition-get.md
  changelog/Microsoft.IGAELM.json
Labels: area: Azure AD, ready to merge, internal, content review complete

#16588 Merge to publish.
  api-reference/beta/api/application-list-extensionproperty.md
  api-reference/beta/api/extensionproperty-delete.md
  api-reference/beta/api/extensionproperty-get.md
  api-reference/beta/api/group-post-approleassignments.md
  api-reference/v1.0/api/application-list-extensionproperty.md
  api-reference/v1.0/api/extensionproperty-delete.md
  api-reference/v1.0/api/extensionproperty-get.md
  api-reference/v1.0/api/group-post-approleassignments.md
  api-reference/v1.0/api/rbacapplication-list-roleassignments.md
  api-reference/v1.0/api/rbacapplication-list-roledefinitions.md
  api-reference/v1.0/api/rbacapplication-post-roleassignments.md
  api-reference/v1.0/api/unifiedroleassignment-delete.md
  api-reference/v1.0/api/unifiedroleassignment-get.md
  api-reference/v1.0/api/unifiedroledefinition-get.md
  changelog/Microsoft.IGAELM.json
  redirects/.openpublishing.redirection.1221.json
Labels: internal

#16104 Added new docs for enabling Large Gallery view API.
  api-reference/beta/api/addlargegalleryviewoperation-get.md
  api-reference/beta/api/call-addlargegalleryview.md
  api-reference/beta/resources/addlargegalleryviewoperation.md
  api-reference/beta/resources/call.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Skype.Calling.json
  concepts/cloud-communications-identifylargegalleryview.md
  concepts/toc.yml
Labels: ready to merge, internal, content review complete, schema live

#16592 Merge to publish.
  api-reference/beta/api/addlargegalleryviewoperation-get.md
  api-reference/beta/api/call-addlargegalleryview.md
  api-reference/beta/resources/addlargegalleryviewoperation.md
  api-reference/beta/resources/call.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Skype.Calling.json
  concepts/cloud-communications-identifylargegalleryview.md
  concepts/toc.yml
Labels: do not merge, internal

#16593 Included most of what's updated in March.
  changelog/Microsoft.IdentityProtectionServices.json
  changelog/Microsoft.Security.AttackSimulation.json
  changelog/Microsoft.Teams.Core.json
  concepts/whats-new-overview.md
Labels: internal

#16594 Publish what's new to include most of the updates in March.
  changelog/Microsoft.IdentityProtectionServices.json
  changelog/Microsoft.Security.AttackSimulation.json
  changelog/Microsoft.Teams.Core.json
  concepts/whats-new-overview.md
Labels: internal

#16602 Edits in PR 16415
  api-reference/beta/resources/documentsetversion.md
  changelog/Microsoft.FileServices.json
Labels: external

#16604 Edits in PR 16343
  api-reference/beta/resources/subjectrightsrequestallmailboxlocation.md
  api-reference/beta/resources/subjectrightsrequestenumeratedmailboxlocation.md
  api-reference/beta/resources/subjectrightsrequestenumeratedsitelocation.md
Labels: external

#16585 Updated SDKs overview
  concepts/sdks/sdks-overview.md
Labels: ready to merge, internal, review feedback addressed

#16595 Minor doc fixes
  api-reference/beta/api/application-update.md
  api-reference/beta/api/rbacapplication-post-roledefinitions.md
  api-reference/beta/api/unifiedrolemanagementpolicyrule-update.md
  api-reference/beta/resources/identityprotection-overview.md
  api-reference/beta/resources/riskdetection.md
  api-reference/beta/resources/riskyuser.md
  api-reference/beta/resources/riskyuserhistoryitem.md
  api-reference/v1.0/api/application-update.md
  api-reference/v1.0/api/rbacapplication-post-roledefinitions.md
  api-reference/v1.0/resources/identityprotection-overview.md
  api-reference/v1.0/resources/riskdetection.md
  api-reference/v1.0/resources/riskyuser.md
  api-reference/v1.0/resources/riskyuserhistoryitem.md
  concepts/application-proxy-configure-api.md
Labels: area: Azure AD, ready to merge, internal

#16601 Add documentation for the group-ids attribute on people-picker
  concepts/toolkit/components/people-picker.md
Labels: external, ready to merge

#16607 Merge to publish.
  api-reference/beta/api/application-update.md
  api-reference/beta/api/rbacapplication-post-roledefinitions.md
  api-reference/beta/api/unifiedrolemanagementpolicyrule-update.md
  api-reference/beta/resources/identityprotection-overview.md
  api-reference/beta/resources/riskdetection.md
  api-reference/beta/resources/riskyuser.md
  api-reference/beta/resources/riskyuserhistoryitem.md
  api-reference/v1.0/api/application-update.md
  api-reference/v1.0/api/rbacapplication-post-roledefinitions.md
  api-reference/v1.0/resources/identityprotection-overview.md
  api-reference/v1.0/resources/riskdetection.md
  api-reference/v1.0/resources/riskyuser.md
  api-reference/v1.0/resources/riskyuserhistoryitem.md
  concepts/application-proxy-configure-api.md
  concepts/sdks/sdks-overview.md
  concepts/toolkit/components/people-picker.md
Labels: internal

#16610 Adding a couple updates in late March.
  api-reference/beta/resources/site.md
  changelog/Microsoft.Compliance.Ediscovery.json
  concepts/whats-new-overview.md
Labels: do not merge, internal

#16611 Refresh what's new topic with a couple of updates in late March.
  api-reference/beta/resources/site.md
  changelog/Microsoft.Compliance.Ediscovery.json
  concepts/whats-new-overview.md
Labels: internal

#16473 Minor doc fixes
  api-reference/beta/api/synchronization-synchronizationjob-provision-on-demand.md
  api-reference/beta/resources/synchronization-synchronizationjobsubject.md
Labels: area: Azure AD, ready to merge, internal, area: applications

#16627 Merge to publish.
  api-reference/beta/api/connectorgroup-post-applications.md
  api-reference/beta/api/synchronization-synchronizationjob-provision-on-demand.md
  api-reference/beta/api/unifiedroledefinition-get.md
  api-reference/beta/resources/groups-overview.md
  api-reference/beta/resources/synchronization-synchronizationjobsubject.md
  api-reference/beta/resources/users.md
  api-reference/v1.0/api/rbacapplication-list-roledefinitions.md
  api-reference/v1.0/api/unifiedroledefinition-get.md
  api-reference/v1.0/resources/groups-overview.md
  api-reference/v1.0/resources/users.md
Labels: do not merge, internal

#16628 Added remaining March updates.
  api-reference/beta/api/sharedwithchannelteaminfo-delete.md
  api-reference/beta/api/sharedwithchannelteaminfo-get.md
  api-reference/beta/api/sharedwithchannelteaminfo-list-allowedmembers.md
  api-reference/beta/api/sharedwithchannelteaminfo-list.md
  api-reference/beta/api/team-delete-incomingchannel.md
  api-reference/beta/resources/channel.md
  api-reference/beta/resources/sharedwithchannelteaminfo.md
  api-reference/beta/toc.yml
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: do not merge, internal

#16630 Refresh what's new update in early April.
  api-reference/beta/api/sharedwithchannelteaminfo-delete.md
  api-reference/beta/api/sharedwithchannelteaminfo-get.md
  api-reference/beta/api/sharedwithchannelteaminfo-list-allowedmembers.md
  api-reference/beta/api/sharedwithchannelteaminfo-list.md
  api-reference/beta/api/team-delete-incomingchannel.md
  api-reference/beta/resources/channel.md
  api-reference/beta/resources/sharedwithchannelteaminfo.md
  api-reference/beta/toc.yml
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: do not merge, internal

#16635 Edits in PR 15909
  api-reference/beta/api/manageddevice-bulksetcloudpcreviewstatus.md
  api-reference/beta/api/manageddevice-getcloudpcreviewstatus.md
  api-reference/beta/api/manageddevice-setcloudpcreviewstatus.md
  api-reference/beta/resources/cloudpc.md
  api-reference/beta/resources/cloudpcreviewstatus.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: external

#16638 Fix changelog sync
  changelog/Microsoft.Teams.Core.json
Labels: do not merge, internal

#16633 Edits in PR 16411
  api-reference/beta/api/participant-invite.md
  api-reference/beta/resources/invitationparticipantinfo.md
  api-reference/v1.0/api/participant-invite.md
  api-reference/v1.0/resources/invitationparticipantinfo.md
Labels: external

#16656 Included in what's new all April updates so far.
  changelog/Microsoft.AAD.Reporting.json
  changelog/Microsoft.Bookings.json
  changelog/Microsoft.CloudManagedDesktop.json
  concepts/whats-new-overview.md
Labels: do not merge, internal

#16379 Doc changes to expose 'teamsAppId' in chat message attachment type
  api-reference/beta/api/chatmessage-post.md
  api-reference/beta/resources/chatmessageattachment.md
  changelog/Microsoft.Teams.Core.json
Labels: ready to merge, internal, content review complete

#16445 Added app-only DelegatedPermissionGrant.RW.All
  api-reference/beta/api/oauth2permissiongrant-delete.md
  api-reference/beta/api/oauth2permissiongrant-delta.md
  api-reference/beta/api/oauth2permissiongrant-get.md
  api-reference/beta/api/oauth2permissiongrant-list.md
  api-reference/beta/api/oauth2permissiongrant-post.md
  api-reference/beta/api/oauth2permissiongrant-update.md
  api-reference/v1.0/api/oauth2permissiongrant-delete.md
  api-reference/v1.0/api/oauth2permissiongrant-delta.md
  api-reference/v1.0/api/oauth2permissiongrant-get.md
  api-reference/v1.0/api/oauth2permissiongrant-list.md
  api-reference/v1.0/api/oauth2permissiongrant-post.md
  api-reference/v1.0/api/oauth2permissiongrant-update.md
Labels: area: Azure AD, ready to merge, internal, content review complete

#16583 AR scoping for direct vs transitive group members
  concepts/accessreviews-scope-concept.md
Labels: area: Azure AD, ready to merge, internal, area: governance

#16637 Minor doc fixes
  api-reference/beta/api/applicationtemplate-instantiate.md
  api-reference/beta/api/group-post-threads.md
  api-reference/beta/api/invitation-post.md
  api-reference/beta/resources/domain.md
  api-reference/beta/resources/groups-overview.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/applicationtemplate-instantiate.md
  api-reference/v1.0/api/group-post-threads.md
  api-reference/v1.0/api/invitation-post.md
  api-reference/v1.0/resources/domain.md
  api-reference/v1.0/resources/groups-overview.md
  api-reference/v1.0/toc.yml
  concepts/application-saml-sso-configure-api.md
Labels: area: Azure AD, ready to merge, internal

#16415 Added documentation for document set version APIs
  api-reference/beta/api/documentsetversion-delete.md
  api-reference/beta/api/documentsetversion-get.md
  api-reference/beta/api/documentsetversion-restore.md
  api-reference/beta/api/listitem-list-documentsetversions.md
  api-reference/beta/api/listitem-post-documentsetversions.md
  api-reference/beta/resources/documentsetversion.md
  api-reference/beta/resources/documentsetversionitem.md
  api-reference/beta/resources/listitem.md
  api-reference/beta/toc.yml
  changelog/Microsoft.FileServices.json
Labels: ready to merge, internal, content review in progress, review feedback addressed

#16675 Edits in PR 16411
  api-reference/beta/api/participant-invite.md
  api-reference/beta/resources/invitationparticipantinfo.md
  api-reference/v1.0/resources/invitationparticipantinfo.md
  changelog/Microsoft.Skype.Calling.json
Labels: external

#16672 Edits in PR 15909
  api-reference/beta/api/manageddevice-bulksetcloudpcreviewstatus.md
  api-reference/beta/api/manageddevice-getcloudpcreviewstatus.md
  api-reference/beta/api/manageddevice-setcloudpcreviewstatus.md
  api-reference/beta/resources/cloudpc.md
Labels: external

#16681 Edits in PR 16575
  api-reference/v1.0/api/contenttype-addcopyfromcontenttypehub.md
  api-reference/v1.0/api/contenttype-getcompatiblehubcontenttypes.md
  api-reference/v1.0/api/list-list-operations.md
  api-reference/v1.0/api/richlongrunningoperation-get.md
  api-reference/v1.0/api/site-list-operations.md
  api-reference/v1.0/resources/richlongrunningoperation.md
Labels: external

#16652 Updated links
  concepts/overview.md
Labels: ready to merge, internal, content review complete

#16659 Minor doc fixes
  api-reference/beta/api/accesspackage-list-incompatibleaccesspackages.md
  api-reference/beta/api/user-list-directreports.md
  api-reference/beta/resources/directoryobject.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/user-list-directreports.md
  api-reference/v1.0/resources/directoryobject.md
  concepts/delta-query-overview.md
Labels: area: Azure AD, ready to merge, internal

#16669 Clarifying required parameter
  api-reference/beta/api/reportroot-getcredentialusagesummary.md
Labels: area: Azure AD, ready to merge, internal, content review complete

#16682 Edited Services and features doc
  concepts/overview-major-services.md
Labels: ready to merge, internal

#16340 Xtap updates based on schema changes
  api-reference/beta/resources/crosstenantaccesspolicy.md
  api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md
  api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md
  api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, ready to merge, content review complete

#16683 Merge to publish.
  api-reference/beta/api/accesspackage-list-incompatibleaccesspackages.md
  api-reference/beta/api/reportroot-getcredentialusagesummary.md
  api-reference/beta/api/user-list-directreports.md
  api-reference/beta/resources/crosstenantaccesspolicy.md
  api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md
  api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md
  api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md
  api-reference/beta/resources/directoryobject.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/user-list-directreports.md
  api-reference/v1.0/resources/directoryobject.md
  changelog/Microsoft.DirectoryServices.json
  concepts/delta-query-overview.md
  concepts/overview-major-services.md
  concepts/overview.md
Labels: do not merge, internal

#16704 Edits in PR 16575
  api-reference/v1.0/api/contenttype-addcopyfromcontenttypehub.md
  api-reference/v1.0/api/contenttype-getcompatiblehubcontenttypes.md
  api-reference/v1.0/api/list-list-operations.md
  api-reference/v1.0/api/site-list-operations.md
  api-reference/v1.0/resources/richlongrunningoperation.md
Labels: external

#16687 Minor doc fixes
  api-reference/beta/resources/service-root.md
  api-reference/beta/toc.yml
  api-reference/v1.0/resources/service-root.md
Labels: area: Azure AD, ready to merge, internal

#16699 Edited FAQ
  concepts/data-connect-faq.md
Labels: ready to merge, internal

#15791 Add api to get user's Cloud PC list and add api to get user's Cloud PC Launch Info
  api-reference/beta/api/cloudpc-getcloudpclaunchinfo.md
  api-reference/beta/api/user-list-cloudpcs.md
  api-reference/beta/resources/cloudpc.md
  api-reference/beta/resources/cloudpclaunchinfo.md
  api-reference/beta/resources/user.md
  api-reference/beta/toc.yml
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, internal, content review complete, schema live

#16708 Merge to publish.
  api-reference/beta/api/cloudpc-getcloudpclaunchinfo.md
  api-reference/beta/api/user-list-cloudpcs.md
  api-reference/beta/resources/cloudpc.md
  api-reference/beta/resources/cloudpclaunchinfo.md
  api-reference/beta/resources/service-root.md
  api-reference/beta/resources/user.md
  api-reference/beta/toc.yml
  api-reference/v1.0/resources/service-root.md
  changelog/Microsoft.CloudManagedDesktop.json
  concepts/data-connect-faq.md
Labels: internal

#16714 Updated redirect URI
  concepts/use-postman.md
Labels: ready for content review, internal

#16619 validation: multiple-fixes-1
  concepts/outlook-large-attachments.md
  concepts/teams-list-all-teams.md
  concepts/throttling.md
  concepts/upload-data-to-upload-session.md
  includes/outlook-mailbox-type-support.md
  includes/snippets/snippets-sdk-documentation-link.md
Labels: external, content review complete

#15946 [Graph connector] Add new permissions to MSGraph external docs
  api-reference/beta/api/externalconnectors-connectionoperation-get.md
  api-reference/beta/api/externalconnectors-external-post-connections.md
  api-reference/beta/api/externalconnectors-externalconnection-delete.md
  api-reference/beta/api/externalconnectors-externalconnection-get.md
  api-reference/beta/api/externalconnectors-externalconnection-list.md
  api-reference/beta/api/externalconnectors-externalconnection-post-groups.md
  api-reference/beta/api/externalconnectors-externalconnection-post-schema.md
  api-reference/beta/api/externalconnectors-externalconnection-put-items.md
  api-reference/beta/api/externalconnectors-externalconnection-update.md
  api-reference/beta/api/externalconnectors-externalgroup-delete.md
  api-reference/beta/api/externalconnectors-externalgroup-post-members.md
  api-reference/beta/api/externalconnectors-externalgroupmember-delete.md
  api-reference/beta/api/externalconnectors-externalitem-delete.md
  api-reference/beta/api/externalconnectors-externalitem-get.md
  api-reference/beta/api/externalconnectors-externalitem-update.md
  api-reference/beta/api/externalconnectors-schema-get.md
  api-reference/beta/api/externalconnectors-schema-update.md
  api-reference/v1.0/api/externalconnectors-connectionoperation-get.md
  api-reference/v1.0/api/externalconnectors-external-post-connections.md
  api-reference/v1.0/api/externalconnectors-externalconnection-delete.md
  api-reference/v1.0/api/externalconnectors-externalconnection-get.md
  api-reference/v1.0/api/externalconnectors-externalconnection-list.md
  api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md
  api-reference/v1.0/api/externalconnectors-externalconnection-update.md
  api-reference/v1.0/api/externalconnectors-externalgroup-delete.md
  api-reference/v1.0/api/externalconnectors-externalgroup-get.md
  api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md
  api-reference/v1.0/api/externalconnectors-externalgroup-update.md
  api-reference/v1.0/api/externalconnectors-externalitem-create.md
  api-reference/v1.0/api/externalconnectors-externalitem-delete.md
  api-reference/v1.0/api/externalconnectors-externalitem-get.md
  api-reference/v1.0/api/externalconnectors-externalitem-update.md
  api-reference/v1.0/api/externalconnectors-identity-delete.md
  api-reference/v1.0/api/externalconnectors-schema-create.md
  api-reference/v1.0/api/externalconnectors-schema-get.md
  changelog/Microsoft.Search.json
  concepts/permissions-reference.md
Labels: ready to merge, internal, content review complete

#16726 Invite one PSTN participant to an existing call - v1.0
  api-reference/beta/api/participant-invite.md
  api-reference/v1.0/api/participant-invite.md
Labels: external

#16639 release Teams related Graph APIs to US government cloud
  api-reference/beta/resources/report.md
Labels: ready to merge, internal

#16713 Minor doc fixes
  api-reference/beta/api/application-list-extensionproperty.md
  api-reference/beta/api/serviceprincipal-post-serviceprincipals.md
  api-reference/v1.0/api/application-list-extensionproperty.md
  api-reference/v1.0/api/serviceprincipal-post-serviceprincipals.md
  concepts/auth-v2-service.md
  concepts/tutorial-accessreviews-roleassignments.md
Labels: area: Azure AD, ready to merge, internal
