Repository microsoftgraph/microsoft-graph-docs, pull requests merged in 2022-06, with the labels that each got.

#17103 Edits in PR 17089
  api-reference/beta/api/cloudpcprovisioningpolicy-get.md
  api-reference/beta/resources/cloudpcprovisioningpolicy.md
Labels: external

#17105 Update educationassignment-remove-category.md
  api-reference/v1.0/api/educationassignment-remove-category.md
Labels: external

#17104 Update educationassignment-remove-category.md
  api-reference/beta/api/educationassignment-remove-category.md
Labels: external

#17101 Edit in PR 16809
  api-reference/beta/resources/educationfeedbackresourceoutcome.md
Labels: external

#17097 Edit in PR 16957
  changelog/Microsoft.Teams.Core.json
Labels: external

#17096 Edits in PR 16979
  api-reference/beta/resources/archivedprintjob.md
  api-reference/v1.0/resources/archivedprintjob.md
Labels: external

#17087 Delete plannerPlan - Add references to page
  api-reference/beta/resources/plannerplan.md
  api-reference/beta/toc.yml
  api-reference/v1.0/resources/plannerplan.md
  api-reference/v1.0/toc.yml
Labels: external

#17090 fix typo
  api-reference/v1.0/resources/authenticationmethods-overview.md
Labels: external

#17085 Update plannerPlan - Removed owner property from body
  api-reference/beta/api/plannerplan-update.md
  api-reference/v1.0/api/plannerplan-update.md
Labels: external

#17052 EM create policy: include example for review settings
  api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md
Labels: area: Azure AD, ready to merge, internal, content review complete

#17057 Add confirmsafe confirmcompromised methods to signin.md
  api-reference/beta/resources/signin.md
Labels: ready to merge, internal, content review complete

#17074 Properly define markdown link in accessreviewstage-list-decisions.md
  api-reference/beta/api/accessreviewstage-list-decisions.md
Labels: ready to merge, internal, content review complete

#15534 Marks activateService and activateServicePlan public APIs as deprecated.
  api-reference/beta/api/organization-activateservice.md
  api-reference/beta/api/user-activateserviceplan.md
  api-reference/beta/resources/activateservice.md
  api-reference/beta/resources/organization.md
  api-reference/beta/resources/user.md
  api-reference/beta/toc.yml
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, ready to merge, internal, content review complete

#17078 docs: Batch limits on Batching page
  concepts/json-batching.md
Labels: external, ready to merge, area: batch requests, content review complete

#17083 entitlement management: backport example description fix to beta
  api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentrequests.md
Labels: area: Azure AD, ready to merge, internal

#16923 GDAP Documentation updates (beta APIs)
  api-reference/beta/api/delegatedadminrelationship-list-operations.md
  api-reference/beta/api/delegatedadminrelationship-list-requests.md
  api-reference/beta/api/delegatedadminrelationshipoperation-get.md
  api-reference/beta/resources/access-assignment-status-transitions.png
  api-reference/beta/resources/delegatedadminrelationship.md
  api-reference/beta/resources/delegatedadminrelationshipoperation.md
  api-reference/beta/resources/delegatedadminrelationshiprequest.md
  api-reference/beta/resources/delegatedadminrelationships-api-overview.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/relationship-status-transitions.png
  changelog/Microsoft.Partner.CustomerSvcAdmin.json
Labels: external, changes requested, review feedback addressed

#17108 Pushing GDAP APIs (beta) from Main to Live
  api-reference/beta/api/delegatedadminrelationship-list-operations.md
  api-reference/beta/api/delegatedadminrelationship-list-requests.md
  api-reference/beta/api/delegatedadminrelationshipoperation-get.md
  api-reference/beta/resources/access-assignment-status-transitions.png
  api-reference/beta/resources/delegatedadminrelationship.md
  api-reference/beta/resources/delegatedadminrelationshipoperation.md
  api-reference/beta/resources/delegatedadminrelationshiprequest.md
  api-reference/beta/resources/delegatedadminrelationships-api-overview.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/relationship-status-transitions.png
  changelog/Microsoft.Partner.CustomerSvcAdmin.json
Labels: internal

#17112 Fixed links to PowerShell docs
  concepts/sdks/create-requests.md
Labels: ready to merge, internal

#17116 Edits in PR 17089
  changelog/Microsoft.CloudManagedDesktop.json
Labels: external

#17120 Update userscopeteamsappinstallation-get-chat.md
  api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md
Labels: external

#17119 Update userscopeteamsappinstallation-get-chat.md
  api-reference/beta/api/userscopeteamsappinstallation-get-chat.md
Labels: external

#17118 Edits in PR 17059
  api-reference/beta/resources/messagepinnedeventmessagedetail.md
  api-reference/beta/resources/messageunpinnedeventmessagedetail.md
Labels: external

#17037 Fixing permission
  api-reference/beta/api/signin-confirmsafe.md
Labels: ready to merge, internal

#17038 Fixing permission
  api-reference/beta/api/signin-confirmcompromised.md
Labels: ready to merge, internal, content review complete

#17113 issue 17075
  api-reference/beta/api/nameditem-addformulalocal.md
  api-reference/v1.0/api/nameditem-addformulalocal.md
Labels: ready to merge, internal, content review complete

#17114 Correcting the wording
  api-reference/beta/api/accessreviewinstance-list-contactedreviewers.md
  api-reference/v1.0/api/accessreviewinstance-list-contactedreviewers.md
Labels: external, ready to merge

#16631 Change updateDomainPassword method using from "Patch"to "Post"
  api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, internal, content review complete

#14511 Update throttling.md
  concepts/throttling.md
Labels: do not merge, ready to merge, internal, content review complete

#17133 Edits in PR 17089
  api-reference/beta/resources/cloudpconpremisesconnection.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: external

#17134 Update reportroot-getteamsdeviceusageuserdetail.md
  api-reference/beta/api/reportroot-getteamsdeviceusageuserdetail.md
Labels: external

#17125 Update page-delete.md
  api-reference/beta/api/page-delete.md
Labels: external

#17124 Update page-delete.md
  api-reference/v1.0/api/page-delete.md
Labels: external

#16605 Added a new property for Entity credentialuserregistrationssummary.
  api-reference/beta/api/managedtenants-credentialuserregistrationssummary-get.md
  api-reference/beta/api/managedtenants-managedtenant-list-credentialuserregistrationssummaries.md
  api-reference/beta/resources/managedtenants-credentialuserregistrationssummary.md
  changelog/Microsoft.MultiTenantPlatform.json
Labels: ready to merge, internal, content review complete

#17026 Purview rebrand update
  api-reference/beta/api/informationprotectionlabel-evaluateclassificationresults.md
  api-reference/beta/resources/contentinfo.md
  api-reference/beta/resources/recommendlabelaction.md
  api-reference/v1.0/resources/assignedlabel.md
  concepts/information-protection-overview.md
  concepts/whats-new-earlier.md
Labels: external, ready to merge

#17076 GA devices in AUs
  api-reference/beta/api/device-list-transitivememberof.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/administrativeunit-delete-members.md
  api-reference/v1.0/api/administrativeunit-get-members.md
  api-reference/v1.0/api/administrativeunit-list-members.md
  api-reference/v1.0/api/administrativeunit-post-members.md
  api-reference/v1.0/api/device-list-memberof.md
  api-reference/v1.0/api/device-list-transitivememberof.md
  api-reference/v1.0/resources/administrativeunit.md
  api-reference/v1.0/resources/device.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, ready to merge, internal, area: directory management

#17115 Issues June 2022
  api-reference/beta/config/link-validation-config.json
  api-reference/beta/resources/driveitem.md
  api-reference/v1.0/config/link-validation-config.json
  api-reference/v1.0/resources/driveitem.md
  api-reference/v1.0/resources/security-api-overview.md
  concepts/outlook-large-attachments.md
Labels: do not merge, ready to merge, ready for content review, internal

#17136 Improve online meeting docs
  api-reference/beta/api/onlinemeeting-get.md
  api-reference/beta/resources/lobbybypasssettings.md
  api-reference/beta/resources/meetingparticipantinfo.md
  api-reference/beta/resources/onlinemeeting.md
  api-reference/v1.0/api/onlinemeeting-get.md
  api-reference/v1.0/resources/lobbybypasssettings.md
  api-reference/v1.0/resources/meetingparticipantinfo.md
  api-reference/v1.0/resources/onlinemeeting.md
Labels: ready to merge, internal

#17137 Merge to publish.
  api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md
  api-reference/beta/api/device-list-transitivememberof.md
  api-reference/beta/api/informationprotectionlabel-evaluateclassificationresults.md
  api-reference/beta/api/managedtenants-credentialuserregistrationssummary-get.md
  api-reference/beta/api/managedtenants-managedtenant-list-credentialuserregistrationssummaries.md
  api-reference/beta/api/onlinemeeting-get.md
  api-reference/beta/api/page-delete.md
  api-reference/beta/api/reportroot-getteamsdeviceusageuserdetail.md
  api-reference/beta/config/link-validation-config.json
  api-reference/beta/resources/contentinfo.md
  api-reference/beta/resources/driveitem.md
  api-reference/beta/resources/lobbybypasssettings.md
  api-reference/beta/resources/managedtenants-credentialuserregistrationssummary.md
  api-reference/beta/resources/meetingparticipantinfo.md
  api-reference/beta/resources/onlinemeeting.md
  api-reference/beta/resources/recommendlabelaction.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/administrativeunit-delete-members.md
  api-reference/v1.0/api/administrativeunit-get-members.md
  api-reference/v1.0/api/administrativeunit-list-members.md
  api-reference/v1.0/api/administrativeunit-post-members.md
  api-reference/v1.0/api/device-list-memberof.md
  api-reference/v1.0/api/device-list-transitivememberof.md
  api-reference/v1.0/api/onlinemeeting-get.md
  api-reference/v1.0/api/page-delete.md
  api-reference/v1.0/config/link-validation-config.json
  api-reference/v1.0/resources/administrativeunit.md
  api-reference/v1.0/resources/assignedlabel.md
  api-reference/v1.0/resources/device.md
  api-reference/v1.0/resources/driveitem.md
  api-reference/v1.0/resources/lobbybypasssettings.md
  api-reference/v1.0/resources/meetingparticipantinfo.md
  api-reference/v1.0/resources/onlinemeeting.md
  api-reference/v1.0/resources/security-api-overview.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.CloudManagedDesktop.json
  changelog/Microsoft.DirectoryServices.json
  changelog/Microsoft.MultiTenantPlatform.json
  concepts/information-protection-overview.md
  concepts/outlook-large-attachments.md
  concepts/throttling.md
  concepts/whats-new-earlier.md
Labels: internal

#17130 Update choose-authentication-providers.md
  concepts/sdks/choose-authentication-providers.md
Labels: external, ready to merge, area: SDKs

#16667 Bulk validation fixes ms.prod
  api-reference/beta/resources/diagnostic.md
  api-reference/beta/resources/editaction.md
  api-reference/beta/resources/enums-termstore.md
  api-reference/beta/resources/externallink.md
  api-reference/beta/resources/filesysteminfo.md
  api-reference/beta/resources/hashes.md
  api-reference/beta/resources/identity.md
  api-reference/beta/resources/inferenceclassification.md
  api-reference/beta/resources/inferenceclassificationoverride.md
  api-reference/beta/resources/integerrange.md
  api-reference/beta/resources/intune-deviceconfig-ioscustomconfiguration.md
  api-reference/beta/resources/intune-deviceconfig-macoscustomappconfiguration.md
  api-reference/beta/resources/intune-deviceconfig-macoscustomconfiguration.md
  api-reference/beta/resources/intune-deviceconfig-omasettingbase64.md
  api-reference/beta/resources/intune-deviceconfig-windows10networkproxyserver.md
  api-reference/beta/resources/intune-shared-deviceappmanagement.md
  api-reference/beta/resources/intune-shared-ioslobappprovisioningconfiguration.md
  api-reference/beta/resources/intune-shared-windowsdomainjoinconfiguration.md
  api-reference/beta/resources/intune-shared-windowsupdatestate.md
Labels: external, ready to merge

#16668 metadata, duplicate headers, disallowed html
  api-reference/v1.0/api/driveitem-get.md
  api-reference/v1.0/api/filter-apply.md
  api-reference/v1.0/api/filter-clear.md
  api-reference/v1.0/api/formatprotection-get.md
  api-reference/v1.0/api/formatprotection-update.md
  api-reference/v1.0/api/icon-get.md
  api-reference/v1.0/api/icon-update.md
  api-reference/v1.0/api/inferenceclassification-list-overrides.md
  api-reference/v1.0/api/inferenceclassification-post-overrides.md
  api-reference/v1.0/api/inferenceclassificationoverride-delete.md
  api-reference/v1.0/api/inferenceclassificationoverride-update.md
  api-reference/v1.0/api/intune-deviceconfig-ioscustomconfiguration-create.md
  api-reference/v1.0/api/intune-deviceconfig-macoscustomconfiguration-create.md
  api-reference/v1.0/api/intune-onboarding-deviceappmanagement-update.md
  api-reference/v1.0/api/list-create.md
Labels: external, ready to merge

#16670 VALIDATION ms.prod fixes
  api-reference/v1.0/resources/baseItemVersion.md
  api-reference/v1.0/resources/baseitem.md
  api-reference/v1.0/resources/clonableteamparts.md
Labels: external, ready to merge

#16671 BULK VALIDATION fixes
  api-reference/v1.0/resources/filter.md
  api-reference/v1.0/resources/filtercriteria.md
  api-reference/v1.0/resources/filterdatetime.md
  api-reference/v1.0/resources/folder.md
  api-reference/v1.0/resources/folderview.md
  api-reference/v1.0/resources/formatprotection.md
  api-reference/v1.0/resources/hashes.md
  api-reference/v1.0/resources/icon.md
  api-reference/v1.0/resources/identity.md
  api-reference/v1.0/resources/identityset.md
  api-reference/v1.0/resources/image.md
  api-reference/v1.0/resources/integerrange.md
  api-reference/v1.0/resources/intune-deviceconfig-ioscustomconfiguration.md
  api-reference/v1.0/resources/intune-deviceconfig-macoscustomconfiguration.md
  api-reference/v1.0/resources/intune-deviceconfig-omasettingbase64.md
  api-reference/v1.0/resources/intune-deviceconfig-windows10networkproxyserver.md
  api-reference/v1.0/resources/intune-onboarding-deviceappmanagement.md
  api-reference/v1.0/resources/itempreviewinfo.md
  api-reference/v1.0/resources/json.md
  api-reference/v1.0/resources/licenseunitsdetail.md
  api-reference/v1.0/resources/locationconstraint.md
  api-reference/v1.0/resources/locationconstraintitem.md
  api-reference/v1.0/resources/lookupcolumn.md
  api-reference/v1.0/resources/manage-focused-inbox.md
Labels: external, ready to merge

#17145 Update bookingbusiness-post-bookingbusinesses.md
  api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md
  api-reference/v1.0/api/bookingbusiness-post-bookingbusinesses.md
Labels: external, ready to merge

#16697 Bulk validation fixes ms.prod
  api-reference/beta/resources/attendeebase.md
  api-reference/beta/resources/baseItemVersion.md
  api-reference/beta/resources/customtimezone.md
  api-reference/beta/resources/datetimecolumn.md
  api-reference/beta/resources/daylighttimezoneoffset.md
  api-reference/beta/resources/deleted.md
  api-reference/beta/resources/devicehealth.md
  api-reference/beta/resources/fieldvalueset.md
  api-reference/beta/resources/file.md
  api-reference/beta/resources/filterdatetime.md
  api-reference/beta/resources/folder.md
  api-reference/beta/resources/folderview.md
  api-reference/beta/resources/followupflag.md
  api-reference/beta/resources/formatprotection.md
  api-reference/beta/resources/freebusyerror.md
  api-reference/beta/resources/genericerror.md
  api-reference/beta/resources/image.md
Labels: external, ready to merge

#16945 Update group-delete-members.md
  api-reference/beta/api/group-delete-members.md
  api-reference/v1.0/api/group-delete-members.md
Labels: external, ready to merge

#16715 validation: multiple-fixes-4
  api-reference/v1.0/resources/video.md
  api-reference/v1.0/resources/vulnerabilitystate.md
  api-reference/v1.0/resources/website.md
  concepts/auth/auth-concepts.md
Labels: external, ready to merge

#16695 VALIDATION fixes
  api-reference/beta/resources/json.md
  api-reference/beta/resources/personwebsite.md
  api-reference/v1.0/api/workbookcomment-post-replies.md
Labels: external, ready to merge

#16724 Documentation changes for enabling subscriptions in v1.0
  api-reference/beta/api/subscription-delete.md
  api-reference/beta/api/subscription-get.md
  api-reference/beta/api/subscription-list.md
  api-reference/beta/api/subscription-post-subscriptions.md
  api-reference/beta/api/subscription-update.md
  api-reference/beta/resources/subscription.md
  api-reference/v1.0/api/subscription-delete.md
  api-reference/v1.0/api/subscription-get.md
  api-reference/v1.0/api/subscription-list.md
  api-reference/v1.0/api/subscription-post-subscriptions.md
  api-reference/v1.0/api/subscription-update.md
  api-reference/v1.0/resources/subscription.md
  api-reference/v1.0/resources/webhooks.md
  changelog/Microsoft.Teams.Core.json
  concepts/teams-changenotifications-chat.md
  concepts/teams-changenotifications-chatMembership.md
  concepts/teams-changenotifications-chatmessage.md
  concepts/teams-changenotifications-team-and-channel.md
  concepts/teams-changenotifications-teamMembership.md
  concepts/webhooks-with-resource-data.md
  concepts/webhooks.md
Labels: area: teams, ready to merge, internal, content review complete

#17106 [Azure AD roles] [Admin units] Prerequisite roles
  api-reference/beta/api/administrativeunit-delete-members.md
  api-reference/beta/api/administrativeunit-delete-scopedrolemembers.md
  api-reference/beta/api/administrativeunit-delete.md
  api-reference/beta/api/administrativeunit-get-scopedrolemembers.md
  api-reference/beta/api/administrativeunit-list-scopedrolemembers.md
  api-reference/beta/api/administrativeunit-post-members.md
  api-reference/beta/api/administrativeunit-post-scopedrolemembers.md
  api-reference/beta/api/administrativeunit-update.md
  api-reference/beta/api/directory-post-administrativeunits.md
  api-reference/beta/resources/administrativeunit.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/administrativeunit-delete-members.md
  api-reference/v1.0/api/administrativeunit-delete-scopedrolemembers.md
  api-reference/v1.0/api/administrativeunit-delete.md
  api-reference/v1.0/api/administrativeunit-get-scopedrolemembers.md
  api-reference/v1.0/api/administrativeunit-list-scopedrolemembers.md
  api-reference/v1.0/api/administrativeunit-post-members.md
  api-reference/v1.0/api/administrativeunit-post-scopedrolemembers.md
  api-reference/v1.0/api/administrativeunit-update.md
  api-reference/v1.0/api/directory-post-administrativeunits.md
  api-reference/v1.0/resources/administrativeunit.md
  api-reference/v1.0/toc.yml
Labels: area: Azure AD, ready to merge, internal, content review complete

#17131 Match PIM beta docs with v1.0 - Part I
  api-reference/beta/api/policyroot-list-rolemanagementpolicies.md
  api-reference/beta/api/rbacapplication-list-roleassignmentscheduleinstances.md
  api-reference/beta/api/rbacapplication-list-roleassignmentschedulerequests.md
  api-reference/beta/api/rbacapplication-list-roleassignmentschedules.md
  api-reference/beta/api/unifiedroleassignmentschedule-filterbycurrentuser.md
  api-reference/beta/api/unifiedroleassignmentschedule-get.md
  api-reference/beta/api/unifiedroleassignmentscheduleinstance-filterbycurrentuser.md
  api-reference/beta/api/unifiedroleassignmentscheduleinstance-get.md
  api-reference/beta/api/unifiedroleassignmentschedulerequest-cancel.md
  api-reference/beta/api/unifiedroleassignmentschedulerequest-filterbycurrentuser.md
  api-reference/beta/api/unifiedroleassignmentschedulerequest-get.md
  api-reference/beta/api/unifiedrolemanagementpolicy-get.md
  api-reference/beta/api/unifiedrolemanagementpolicy-list-rules.md
  api-reference/beta/api/unifiedrolemanagementpolicyrule-get.md
  api-reference/beta/api/unifiedrolemanagementpolicyrule-update.md
  api-reference/beta/resources/approvalsettings.md
  api-reference/beta/resources/approvalstage.md
  api-reference/beta/resources/request.md
  api-reference/beta/resources/requestschedule.md
  api-reference/beta/resources/ticketinfo.md
  api-reference/beta/resources/unifiedroleassignmentschedule.md
  api-reference/beta/resources/unifiedroleassignmentscheduleinstance.md
  api-reference/beta/resources/unifiedroleassignmentschedulerequest.md
  api-reference/beta/resources/unifiedrolemanagementpolicy.md
  api-reference/beta/resources/unifiedrolemanagementpolicyapprovalrule.md
  api-reference/beta/resources/unifiedrolemanagementpolicyauthenticationcontextrule.md
  api-reference/beta/resources/unifiedrolemanagementpolicyenablementrule.md
  api-reference/beta/resources/unifiedrolemanagementpolicyexpirationrule.md
  api-reference/beta/resources/unifiedrolemanagementpolicynotificationrule.md
  api-reference/beta/resources/unifiedrolemanagementpolicyrule.md
  api-reference/beta/resources/unifiedrolemanagementpolicyruletarget.md
  api-reference/beta/resources/unifiedroleschedulebase.md
  api-reference/beta/resources/unifiedrolescheduleinstancebase.md
  api-reference/v1.0/api/rbacapplication-list-roleassignmentschedulerequests.md
  api-reference/v1.0/api/rbacapplication-post-roleassignmentschedulerequests.md
  api-reference/v1.0/api/unifiedroleassignmentschedule-filterbycurrentuser.md
  api-reference/v1.0/api/unifiedroleassignmentscheduleinstance-filterbycurrentuser.md
  api-reference/v1.0/resources/unifiedroleassignmentschedulerequest.md
Labels: area: Azure AD, ready to merge, internal, area: governance

#16808 Updating roles/permissions for CA data
  api-reference/beta/api/signin-get.md
  api-reference/beta/api/signin-list.md
  api-reference/includes/signins-roles-for-ca-data.md
  api-reference/v1.0/api/signin-get.md
  api-reference/v1.0/api/signin-list.md
Labels: area: Azure AD, ready to merge, internal, content review in progress

#16809 Education Feedback resource outcome
  api-reference/beta/api/educationassignment-setupfeedbackresourcesfolder.md
  api-reference/beta/api/educationfeedbackresourceoutcome-delete.md
  api-reference/beta/api/educationfeedbackresourceoutcome-post-outcomes.md
  api-reference/beta/api/educationsubmission-list-outcomes.md
  api-reference/beta/resources/educationassignment.md
  api-reference/beta/resources/educationfeedbackresourceoutcome.md
  api-reference/beta/resources/educationoutcome.md
  api-reference/beta/resources/enums.md
  api-reference/beta/toc.yml
  changelog/Microsoft.EducationAssignment.json
Labels: ready to merge, internal, content review complete, schema live, review feedback addressed

#17163 Edits in PR 17014
  concepts/workbook-error-codes.md
  concepts/workbook-error-handling.md
Labels: external

#17164 Update cloudpc-get.md
  api-reference/beta/api/cloudpc-get.md
Labels: external

#16733 Create snippet-unavailable.md
  includes/snippet-unavailable.md
Labels: external, ready to merge, review requested

#16357 Adding hideAccountResetCredentials property
  api-reference/beta/resources/loginpagetextvisibilitysettings.md
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, ready to merge, internal, content review complete

#16833 To be consistent with V1 production
  api-reference/v1.0/api/reportroot-getteamsdeviceusagedistributionusercounts.md
  api-reference/v1.0/api/reportroot-getteamsdeviceusageusercounts.md
  api-reference/v1.0/api/reportroot-getteamsdeviceusageuserdetail.md
  api-reference/v1.0/api/reportroot-getteamsuseractivitycounts.md
  api-reference/v1.0/api/reportroot-getteamsuseractivityuserdetail.md
  api-reference/v1.0/resources/microsoft-teams-user-activity-reports.md
  changelog/Microsoft.O365Reporting.json
Labels: ready to merge, internal, content review complete

#16837 add domain promote
  api-reference/beta/api/domain-promote.md
  api-reference/beta/resources/domain.md
  api-reference/beta/toc.yml
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, ready to merge, internal, content review complete

#17141 Add PIM to supported features in national clouds
  concepts/deployments.md
Labels: area: Azure AD, ready to merge, internal, area: governance

#16911 Add documentation for new CallRecord fields and enums
  api-reference/beta/resources/callrecords-mediastream.md
  api-reference/beta/resources/callrecords-networkinfo.md
  api-reference/beta/resources/callrecords-traceroutehop.md
  api-reference/beta/resources/enums-callrecords.md
  api-reference/v1.0/resources/callrecords-mediastream.md
  api-reference/v1.0/resources/callrecords-networkinfo.md
  api-reference/v1.0/resources/callrecords-traceroutehop.md
  api-reference/v1.0/resources/enums-callrecords.md
  changelog/Microsoft.IC3.DataPlatform.json
Labels: ready to merge, internal, area: cloud communications, content review complete

#17169 Merge to publish.
  api-reference/beta/api/cloudpc-get.md
  api-reference/beta/api/domain-promote.md
  api-reference/beta/resources/callrecords-mediastream.md
  api-reference/beta/resources/callrecords-networkinfo.md
  api-reference/beta/resources/callrecords-traceroutehop.md
  api-reference/beta/resources/domain.md
  api-reference/beta/resources/enums-callrecords.md
  api-reference/beta/resources/loginpagetextvisibilitysettings.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/reportroot-getteamsdeviceusagedistributionusercounts.md
  api-reference/v1.0/api/reportroot-getteamsdeviceusageusercounts.md
  api-reference/v1.0/api/reportroot-getteamsdeviceusageuserdetail.md
  api-reference/v1.0/api/reportroot-getteamsuseractivitycounts.md
  api-reference/v1.0/api/reportroot-getteamsuseractivityuserdetail.md
  api-reference/v1.0/resources/callrecords-mediastream.md
  api-reference/v1.0/resources/callrecords-networkinfo.md
  api-reference/v1.0/resources/callrecords-traceroutehop.md
  api-reference/v1.0/resources/enums-callrecords.md
  api-reference/v1.0/resources/microsoft-teams-user-activity-reports.md
  changelog/Microsoft.DirectoryServices.json
  changelog/Microsoft.IC3.DataPlatform.json
  changelog/Microsoft.O365Reporting.json
  concepts/deployments.md
  includes/snippet-unavailable.md
Labels: do not merge, internal

#17178 Moved include file to reference folder.
  api-reference/includes/snippets/snippet-unavailable.md
Labels: internal

#17179 Added include file to subfolders.
  api-reference/beta/includes/snippets/snippet-unavailable.md
  api-reference/v1.0/includes/snippet-unavailable.md
Labels: internal

#16643 042522 3 - Validation fixes
  api-reference/beta/api/termstore-group-delete.md
  api-reference/beta/api/termstore-group-get.md
  api-reference/beta/api/termstore-group-list-sets.md
  api-reference/beta/api/termstore-group-post.md
  api-reference/beta/api/termstore-list-groups.md
  api-reference/beta/api/termstore-relation-post.md
  api-reference/beta/api/termstore-set-delete.md
  api-reference/beta/api/termstore-set-get.md
  api-reference/beta/api/termstore-set-post.md
  api-reference/beta/api/termstore-set-update.md
  api-reference/beta/api/termstore-store-get.md
  api-reference/beta/api/termstore-store-update.md
  api-reference/beta/api/termstore-term-get.md
  api-reference/beta/api/termstore-term-list-children.md
  api-reference/beta/api/termstore-term-list-relations.md
  api-reference/beta/api/termstore-term-post.md
  api-reference/beta/api/termstore-term-update.md
  api-reference/beta/api/user-findrooms.md
  api-reference/beta/api/user-update.md
Labels: external, ready to merge

#17177 Edits in PR 17059
  api-reference/beta/resources/messagepinnedeventmessagedetail.md
  api-reference/beta/resources/messageunpinnedeventmessagedetail.md
Labels: external

#16711 Update teams-list-all-teams.md
  concepts/teams-list-all-teams.md
Labels: external, ready to merge

#16097 Committing changes for signInFrequency updates
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/signinfrequencysessioncontrol.md
  changelog/Microsoft.IdentityProtectionServices.json
Labels: area: Azure AD, external, ready to merge, content review complete

#16323 Update permissions-reference.md
  concepts/permissions-reference.md
Labels: area: Azure AD, external, area: groups, ready to merge, area: permissions

#17171 Minor doc fixes
  api-reference/beta/resources/unifiedroleassignmentschedulerequest.md
  api-reference/includes/signins-roles-for-ca-data.md
  concepts/toc.yml
Labels: area: Azure AD, ready to merge, internal

#17185 Remove canary endpoint reference in example response
  api-reference/beta/api/teamsappicon-get.md
Labels: ready to merge

#17189 Edits in PR 15683
  changelog/Microsoft.InformationProtection.json
Labels: external

#16650 BULK VALIDATION fixes, ms prod, tabs
  api-reference/beta/api/multivaluelegacyextendedproperty-get.md
  api-reference/beta/api/multivaluelegacyextendedproperty-post-multivalueextendedproperties.md
  api-reference/beta/api/nameditem-add.md
  api-reference/beta/api/nameditem-get.md
  api-reference/beta/api/nameditem-list.md
  api-reference/beta/api/nameditem-range.md
  api-reference/beta/api/nameditem-update.md
  api-reference/beta/api/opentypeextension-get.md
  api-reference/beta/api/organizationalbranding-get.md
  api-reference/beta/api/organizationalbranding-update.md
  api-reference/beta/api/organizationalbrandinglocalization-get.md
  api-reference/beta/api/outlookuser-supportedtimezones.md
  api-reference/beta/api/participant-delete.md
  api-reference/beta/api/participant-invite.md
  api-reference/beta/api/permission-delete.md
  api-reference/beta/api/place-list.md
  api-reference/beta/api/place-update.md
  api-reference/beta/api/presence-get.md
Labels: external, ready to merge

#16665 BULK VALIDATION ms.prod
  api-reference/v1.0/resources/archivedprintjob.md
  api-reference/v1.0/resources/attendee.md
  api-reference/v1.0/resources/attendeebase.md
  api-reference/v1.0/resources/automaticrepliesmailtips.md
  api-reference/v1.0/resources/automaticrepliessetting.md
  api-reference/v1.0/resources/booleancolumn.md
  api-reference/v1.0/resources/calculatedcolumn.md
  api-reference/v1.0/resources/choicecolumn.md
  api-reference/v1.0/resources/cloudappsecuritystate.md
  api-reference/v1.0/resources/columnLink.md
  api-reference/v1.0/resources/complianceinformation.md
  api-reference/v1.0/resources/contentTypeInfo.md
  api-reference/v1.0/resources/contentTypeOrder.md
  api-reference/v1.0/resources/currencycolumn.md
  api-reference/v1.0/resources/datetimecolumn.md
  api-reference/v1.0/resources/defaultColumnValue.md
  api-reference/v1.0/resources/deleted.md
  api-reference/v1.0/resources/externallink.md
  api-reference/v1.0/resources/fieldvalueset.md
  api-reference/v1.0/resources/filehash.md
  api-reference/v1.0/resources/filesecuritystate.md
Labels: external, ready to merge

#17196 Edits in PR 15683
  changelog/Microsoft.InformationProtection.json
Labels: external

#17198 Fix TOC warnings.
  api-reference/beta/toc.yml
Labels: internal

#17200 Update projectrome-get-recent-activities.md
  api-reference/beta/api/projectrome-get-recent-activities.md
Labels: external

#16680 BULK VALIDATION ms.prod fixes
  api-reference/v1.0/resources/nameditem.md
  api-reference/v1.0/resources/numbercolumn.md
  api-reference/v1.0/resources/onenoteentityhierarchymodel.md
  api-reference/v1.0/resources/operation.md
  api-reference/v1.0/resources/operationerror.md
  api-reference/v1.0/resources/package.md
  api-reference/v1.0/resources/page.md
  api-reference/v1.0/resources/pagelinks.md
  api-reference/v1.0/resources/patchcontentcommand.md
  api-reference/v1.0/resources/photo.md
  api-reference/v1.0/resources/printerprocessingstatedetail.md
  api-reference/v1.0/resources/project-rome-overview.md
  api-reference/v1.0/resources/publicationfacet.md
  api-reference/v1.0/resources/quota.md
  api-reference/v1.0/resources/recentnotebook.md
  api-reference/v1.0/resources/recentnotebooklinks.md
  api-reference/v1.0/resources/recipient.md
  api-reference/v1.0/resources/remoteitem.md
  api-reference/v1.0/resources/resource.md
  api-reference/v1.0/resources/root.md
  api-reference/v1.0/resources/scoredemailaddress.md
  api-reference/v1.0/resources/searchresult.md
  api-reference/v1.0/resources/section.md
  api-reference/v1.0/resources/sectionlinks.md
  api-reference/v1.0/resources/shared.md
  api-reference/v1.0/resources/shareddriveitem.md
  api-reference/v1.0/resources/sharinginvitation.md
  api-reference/v1.0/resources/sharinglink.md
Labels: external, ready to merge

#16972 Update add channel members graph documentation to display maximum bul…
  api-reference/beta/api/channel-post.md
  api-reference/v1.0/api/channel-post.md
Labels: ready to merge, internal, review feedback addressed

#17143 Update displayName in Microsoft Graph TOC
  concepts/toc.yml
Labels: ready to merge, internal, review feedback addressed

#17158 [Azure ABAC] Role assignment with attribute set scope
  api-reference/beta/api/rbacapplication-post-roleassignments.md
  api-reference/v1.0/api/rbacapplication-post-roleassignments.md
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, ready to merge, internal, content review complete

#17201 Merge to publish.
  api-reference/beta/api/channel-post.md
  api-reference/beta/api/projectrome-get-recent-activities.md
  api-reference/beta/api/rbacapplication-post-roleassignments.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/channel-post.md
  api-reference/v1.0/api/rbacapplication-post-roleassignments.md
  api-reference/v1.0/resources/nameditem.md
  api-reference/v1.0/resources/numbercolumn.md
  api-reference/v1.0/resources/onenoteentityhierarchymodel.md
  api-reference/v1.0/resources/operation.md
  api-reference/v1.0/resources/operationerror.md
  api-reference/v1.0/resources/package.md
  api-reference/v1.0/resources/page.md
  api-reference/v1.0/resources/pagelinks.md
  api-reference/v1.0/resources/patchcontentcommand.md
  api-reference/v1.0/resources/photo.md
  api-reference/v1.0/resources/printerprocessingstatedetail.md
  api-reference/v1.0/resources/project-rome-overview.md
  api-reference/v1.0/resources/publicationfacet.md
  api-reference/v1.0/resources/quota.md
  api-reference/v1.0/resources/recentnotebook.md
  api-reference/v1.0/resources/recentnotebooklinks.md
  api-reference/v1.0/resources/recipient.md
  api-reference/v1.0/resources/remoteitem.md
  api-reference/v1.0/resources/resource.md
  api-reference/v1.0/resources/root.md
  api-reference/v1.0/resources/scoredemailaddress.md
  api-reference/v1.0/resources/searchresult.md
  api-reference/v1.0/resources/section.md
  api-reference/v1.0/resources/sectionlinks.md
  api-reference/v1.0/resources/shared.md
  api-reference/v1.0/resources/shareddriveitem.md
  api-reference/v1.0/resources/sharinginvitation.md
  api-reference/v1.0/resources/sharinglink.md
  changelog/Microsoft.DirectoryServices.json
  concepts/toc.yml
Labels: internal

#17214 Fix #17213 - typo
  concepts/json-batching.md
Labels: ready to merge, internal

#17212 Fix #17128 - Expand role requirement for 'Delete user' to apps
  api-reference/beta/api/user-delete.md
  api-reference/v1.0/api/user-delete.md
Labels: area: Azure AD, ready to merge, internal

#17210 Fix #17165 - Request fresh snippets
  api-reference/beta/api/invitation-post.md
  api-reference/v1.0/api/invitation-post.md
Labels: area: Azure AD, ready to merge, internal

#17211 Add note about percent-encoding requirement as per RFC 3986
  concepts/query-parameters.md
Labels: area: Azure AD, ready to merge, internal

#17138 Updated documentations for application API to include samlMetadataUrl property
  api-reference/beta/api/application-get.md
  api-reference/beta/api/application-post-applications.md
  api-reference/beta/resources/application.md
  changelog/Microsoft.DirectoryServices.json
  concepts/migrate-azure-ad-graph-property-differences.md
Labels: area: Azure AD, ready to merge, content review complete

#17219 Merge to publish.
  api-reference/beta/api/application-get.md
  api-reference/beta/api/application-post-applications.md
  api-reference/beta/api/invitation-post.md
  api-reference/beta/api/user-delete.md
  api-reference/beta/resources/application.md
  api-reference/v1.0/api/invitation-post.md
  api-reference/v1.0/api/user-delete.md
  changelog/Microsoft.DirectoryServices.json
  concepts/json-batching.md
  concepts/migrate-azure-ad-graph-property-differences.md
  concepts/query-parameters.md
Labels: internal

#17226 Edits in PR 17059
  api-reference/beta/resources/messagepinnedeventmessagedetail.md
  api-reference/beta/resources/messageunpinnedeventmessagedetail.md
Labels: external

#17227 Edits in PR 16979
  api-reference/beta/api/printjob-cancel.md
  api-reference/beta/api/printjob-get.md
  api-reference/v1.0/api/printjob-cancel.md
  api-reference/v1.0/api/printjob-get.md
Labels: external

#17228 Edits in PR 15683
  changelog/Microsoft.InformationProtection.json
  concepts/security-information-protection-overview.md
Labels: external

#17230 Update securescores.md
  api-reference/beta/resources/securescores.md
Labels: external

#16372 [Microsoft 365 Lighthouse] - My roles feature
  api-reference/beta/api/managedtenants-managedtenant-list-myroles.md
  api-reference/beta/resources/enums-managedtenants.md
  api-reference/beta/resources/managedtenants-managedtenant.md
  api-reference/beta/resources/managedtenants-myrole.md
  api-reference/beta/resources/managedtenants-roleassignment.md
  api-reference/beta/resources/managedtenants-roledefinition.md
  api-reference/beta/toc.yml
  changelog/Microsoft.MultiTenantPlatform.json
Labels: ready to merge, internal, content review complete, area: multi-tenant management

#17215 Jupetter identities
  api-reference/beta/api/user-list.md
  api-reference/beta/resources/objectidentity.md
  api-reference/v1.0/api/user-list.md
  api-reference/v1.0/resources/objectidentity.md
Labels: area: Azure AD, ready to merge, internal

#16995 Update application.md
  api-reference/v1.0/api/application-get.md
  api-reference/v1.0/resources/application.md
  api-reference/v1.0/resources/certification.md
  changelog/Microsoft.DirectoryServices.json
Labels: ready to merge, internal, content review complete

#17251 Edits in PR 17184
  api-reference/beta/api/driveitem-createuploadsession.md
  api-reference/beta/api/site-list.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/driveitem-createuploadsession.md
  api-reference/v1.0/api/driveitemversion-get-contents.md
  api-reference/v1.0/api/site-list.md
  api-reference/v1.0/toc.yml
Labels: external

#17250 Update driveitemversion-get-contents.md
  api-reference/v1.0/api/driveitemversion-get-contents.md
Labels: external

#16731 Update outlook-change-notifications-overview.md
  api-reference/beta/api/subscription-delete.md
  api-reference/beta/api/subscription-get.md
  api-reference/beta/api/subscription-list.md
  api-reference/beta/api/subscription-post-subscriptions.md
  api-reference/beta/api/subscription-update.md
  api-reference/v1.0/api/subscription-delete.md
  api-reference/v1.0/api/subscription-get.md
  api-reference/v1.0/api/subscription-list.md
  api-reference/v1.0/api/subscription-post-subscriptions.md
  api-reference/v1.0/api/subscription-update.md
  concepts/outlook-change-notifications-overview.md
Labels: ready to merge, internal, content review complete

#17186 Update metadata for Explore docs
  concepts/deployments.md
  concepts/hybrid-rest-support.md
  concepts/overview-major-services.md
  concepts/overview.md
  concepts/tutorials.md
  concepts/users-you-can-reach.md
  concepts/versioning-and-support.md
  concepts/whats-new-overview.md
Labels: ready to merge, internal

#17195 Update metadata for Learn docs: Users, Groups, Applications
  api-reference/v1.0/resources/groups-overview.md
  concepts/application-proxy-configure-api.md
  concepts/application-saml-sso-configure-api.md
  concepts/applications-concept-overview.md
  concepts/azuread-users-concept-overview.md
  concepts/group-set-options.md
  concepts/office365-groups-concept-overview.md
Labels: ready to merge, internal, review feedback addressed

#17216 Update metadata for Learn docs: Data Connect and Connectors
  concepts/connecting-external-content-api-limits.md
  concepts/connecting-external-content-connectors-api-overview.md
  concepts/connecting-external-content-connectors-api-postman.md
  concepts/connecting-external-content-connectors-overview.md
  concepts/connecting-external-content-external-groups.md
  concepts/connecting-external-content-manage-connections.md
  concepts/connecting-external-content-manage-items.md
  concepts/connecting-external-content-manage-schema.md
  concepts/data-connect-concept-overview.md
  concepts/data-connect-datasets.md
  concepts/data-connect-faq.md
  concepts/data-connect-filtering.md
  concepts/data-connect-pam.md
  concepts/data-connect-policies.md
Labels: ready to merge, internal

#17267 Edits in PR 17061
  api-reference/beta/api/taskfileattachment-delete.md
  api-reference/beta/api/taskfileattachment-get.md
  api-reference/beta/api/todotask-list-attachments.md
  api-reference/beta/api/todotask-post-attachments.md
  api-reference/beta/resources/attachmentbase.md
  api-reference/beta/resources/attachmentinfo.md
  api-reference/beta/resources/attachmentsession.md
  api-reference/beta/resources/taskfileattachment.md
Labels: external

#17268 Update outlook-large-attachments.md
  concepts/outlook-large-attachments.md
Labels: external

#17269 Updated v1.0 and beta TOCs to match all-up TOC
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
Labels: ready to merge, internal

#17263 Remove beta references
  concepts/teams-list-all-teams.md
Labels: ready to merge, content review complete

#17217 Remove apostrophe workaround as it is no longer needed
  concepts/webhooks.md
Labels: ready to merge, internal, content review complete

#17245 Update chat-post.md: new sample with federated user
  api-reference/beta/api/chat-post.md
  api-reference/v1.0/api/chat-post.md
Labels: external, ready to merge, review feedback addressed

#17256 Minor doc fixes
  api-reference/beta/api/application-delete-owners.md
  api-reference/beta/api/device-delete-registeredowners.md
  api-reference/beta/api/device-delete-registeredusers.md
  api-reference/beta/api/directoryrole-delete-member.md
  api-reference/beta/api/group-delete-members.md
  api-reference/beta/api/oauth2permissiongrant-get.md
  api-reference/beta/api/oauth2permissiongrant-list.md
  api-reference/beta/resources/application.md
  api-reference/beta/resources/oauth2permissiongrant.md
  api-reference/v1.0/api/application-delete-owners.md
  api-reference/v1.0/api/device-delete-registeredowners.md
  api-reference/v1.0/api/device-delete-registeredusers.md
  api-reference/v1.0/api/directoryrole-delete-member.md
  api-reference/v1.0/api/group-delete-members.md
  api-reference/v1.0/api/oauth2permissiongrant-get.md
  api-reference/v1.0/api/oauth2permissiongrant-list.md
  api-reference/v1.0/resources/oauth2permissiongrant.md
  concepts/json-batching.md
Labels: area: Azure AD, ready to merge, internal

#17059 pinned message event detail
  api-reference/beta/resources/eventmessagedetail.md
  api-reference/beta/resources/messagepinnedeventmessagedetail.md
  api-reference/beta/resources/messageunpinnedeventmessagedetail.md
  changelog/Microsoft.Teams.Core.json
  concepts/system-messages.md
Labels: ready to merge, internal, content review complete

#17260 Minor update to description for preAuthorizedApplications
  api-reference/beta/resources/preauthorizedapplication.md
  api-reference/v1.0/resources/preauthorizedapplication.md
Labels: ready to merge, area: app model, internal

#17265 change deprecation date
  api-reference/beta/includes/todo-deprecate-basetaskapi-sharedfeature.md
  api-reference/beta/includes/todo-deprecate-basetaskapi.md
Labels: ready to merge, internal, area: todo

#17240 [Update] New section Examples and Additional documentation to upload …
  api-reference/beta/api/driveitem-createuploadsession.md
  api-reference/v1.0/api/driveitem-createuploadsession.md
Labels: external, ready to merge

#17275 Merge to publish.
  api-reference/beta/api/application-delete-owners.md
  api-reference/beta/api/chat-post.md
  api-reference/beta/api/device-delete-registeredowners.md
  api-reference/beta/api/device-delete-registeredusers.md
  api-reference/beta/api/directoryrole-delete-member.md
  api-reference/beta/api/driveitem-createuploadsession.md
  api-reference/beta/api/group-delete-members.md
  api-reference/beta/api/oauth2permissiongrant-get.md
  api-reference/beta/api/oauth2permissiongrant-list.md
  api-reference/beta/includes/todo-deprecate-basetaskapi-sharedfeature.md
  api-reference/beta/includes/todo-deprecate-basetaskapi.md
  api-reference/beta/resources/application.md
  api-reference/beta/resources/eventmessagedetail.md
  api-reference/beta/resources/messagepinnedeventmessagedetail.md
  api-reference/beta/resources/messageunpinnedeventmessagedetail.md
  api-reference/beta/resources/oauth2permissiongrant.md
  api-reference/beta/resources/preauthorizedapplication.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/application-delete-owners.md
  api-reference/v1.0/api/chat-post.md
  api-reference/v1.0/api/device-delete-registeredowners.md
  api-reference/v1.0/api/device-delete-registeredusers.md
  api-reference/v1.0/api/directoryrole-delete-member.md
  api-reference/v1.0/api/driveitem-createuploadsession.md
  api-reference/v1.0/api/group-delete-members.md
  api-reference/v1.0/api/oauth2permissiongrant-get.md
  api-reference/v1.0/api/oauth2permissiongrant-list.md
  api-reference/v1.0/resources/oauth2permissiongrant.md
  api-reference/v1.0/resources/preauthorizedapplication.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.Teams.Core.json
  concepts/json-batching.md
  concepts/outlook-large-attachments.md
  concepts/system-messages.md
  concepts/teams-list-all-teams.md
  concepts/webhooks.md
Labels: internal

#17282 Fixed links.
  api-reference/beta/api/driveitem-createuploadsession.md
  api-reference/v1.0/api/driveitem-createuploadsession.md
Labels: ready to merge, internal

#17287 Edits in PR 17014
  concepts/workbook-error-handling.md
Labels: external

#17297 removing keyCredentials property
  includes/filter-directory-objects.md
Labels: ready to merge, internal

#17290 Edits in PR 17061
  api-reference/beta/api/taskFileAttachment-createuploadsession.md
  api-reference/beta/api/todotask-post-attachments.md
  api-reference/beta/resources/attachmentbase.md
  api-reference/beta/resources/attachmentsession.md
Labels: external

#17292 Update fileattachment.md
  api-reference/beta/resources/fileattachment.md
Labels: external

#17262 Fix description for role property
  api-reference/beta/api/team-post-members.md
  api-reference/beta/resources/conversationmember.md
  api-reference/v1.0/api/team-post-members.md
  api-reference/v1.0/resources/conversationmember.md
Labels: ready to merge

#17302 Merge to publish.
  api-reference/beta/api/driveitem-createuploadsession.md
  api-reference/beta/api/team-post-members.md
  api-reference/beta/resources/conversationmember.md
  api-reference/beta/resources/fileattachment.md
  api-reference/v1.0/api/driveitem-createuploadsession.md
  api-reference/v1.0/api/team-post-members.md
  api-reference/v1.0/resources/conversationmember.md
  includes/filter-directory-objects.md
Labels: internal

#17303 Include updates in what's new through end of May.
  api-reference/beta/resources/search-api-overview.md
  api-reference/v1.0/resources/search-api-overview.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.AAD.Reporting.json
  changelog/Microsoft.Teams.GraphSvc.json
  concepts/teams-send-activityfeednotifications.md
  concepts/whats-new-overview.md
Labels: do not merge, internal

#17304 Refresh what's new topic to include all May updates.
  api-reference/beta/resources/search-api-overview.md
  api-reference/v1.0/resources/search-api-overview.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.AAD.Reporting.json
  changelog/Microsoft.Teams.GraphSvc.json
  concepts/teams-send-activityfeednotifications.md
  concepts/whats-new-overview.md
Labels: internal

#17291 Update fileattachment.md
  api-reference/v1.0/resources/fileattachment.md
Labels: external

#16979 User/vnagula/permissionchange
  api-reference/beta/api/printjob-cancel.md
  api-reference/beta/api/printjob-get.md
  api-reference/beta/resources/archivedprintjob.md
  api-reference/v1.0/api/printjob-cancel.md
  api-reference/v1.0/api/printjob-get.md
  api-reference/v1.0/resources/archivedprintjob.md
Labels: ready to merge, area: universal print, content review complete

#17170 Fixed shared channel doc nconsistencies
  api-reference/beta/api/team-delete-incomingchannels.md
  api-reference/beta/resources/channel.md
  api-reference/beta/resources/team.md
  api-reference/beta/toc.yml
  concepts/whats-new-overview.md
Labels: ready to merge, internal, content review complete

#17187 [Azure AD roles] [Admin units] Prerequisite roles create new group
  api-reference/beta/api/administrativeunit-post-members.md
Labels: area: Azure AD, ready to merge, internal, content review complete

#16824 Users/komalpandey/adding missing attributes
  api-reference/beta/api/bookingappointment-get.md
  api-reference/beta/api/bookingbusiness-get.md
  api-reference/beta/api/bookingbusiness-list-appointments.md
  api-reference/beta/api/bookingbusiness-list-calendarview.md
  api-reference/beta/api/bookingbusiness-list-services.md
  api-reference/beta/api/bookingbusiness-list-staffmembers.md
  api-reference/beta/api/bookingbusiness-post-appointments.md
  api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md
  api-reference/beta/api/bookingbusiness-post-services.md
  api-reference/beta/api/bookingbusiness-post-staffmembers.md
  api-reference/beta/api/bookingbusiness-update.md
  api-reference/beta/api/bookingservice-get.md
  api-reference/beta/api/bookingservice-update.md
  api-reference/beta/api/bookingstaffmember-get.md
  api-reference/beta/api/bookingstaffmember-update.md
  api-reference/beta/resources/bookingappointment.md
  api-reference/beta/resources/bookingbusiness.md
  api-reference/beta/resources/bookingcustomer.md
  api-reference/beta/resources/bookingcustomerinformation.md
  api-reference/beta/resources/bookingcustomquestion.md
  api-reference/beta/resources/bookingservice.md
  api-reference/beta/resources/bookingstaffmember.md
  api-reference/beta/resources/enums.md
  changelog/Microsoft.Bookings.json
Labels: ready to merge, internal, content review complete

#17298 Update model B date and errors
  concepts/teams-licenses.md
Labels: external, ready to merge

#17343 Merge to publish.
  api-reference/beta/api/administrativeunit-post-members.md
  api-reference/beta/api/bookingappointment-get.md
  api-reference/beta/api/bookingbusiness-get.md
  api-reference/beta/api/bookingbusiness-list-appointments.md
  api-reference/beta/api/bookingbusiness-list-calendarview.md
  api-reference/beta/api/bookingbusiness-list-services.md
  api-reference/beta/api/bookingbusiness-list-staffmembers.md
  api-reference/beta/api/bookingbusiness-post-appointments.md
  api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md
  api-reference/beta/api/bookingbusiness-post-services.md
  api-reference/beta/api/bookingbusiness-post-staffmembers.md
  api-reference/beta/api/bookingbusiness-update.md
  api-reference/beta/api/bookingservice-get.md
  api-reference/beta/api/bookingservice-update.md
  api-reference/beta/api/bookingstaffmember-get.md
  api-reference/beta/api/bookingstaffmember-update.md
  api-reference/beta/api/printjob-cancel.md
  api-reference/beta/api/printjob-get.md
  api-reference/beta/api/team-delete-incomingchannels.md
  api-reference/beta/resources/archivedprintjob.md
  api-reference/beta/resources/bookingappointment.md
  api-reference/beta/resources/bookingbusiness.md
  api-reference/beta/resources/bookingcustomer.md
  api-reference/beta/resources/bookingcustomerinformation.md
  api-reference/beta/resources/bookingcustomquestion.md
  api-reference/beta/resources/bookingservice.md
  api-reference/beta/resources/bookingstaffmember.md
  api-reference/beta/resources/channel.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/team.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/printjob-cancel.md
  api-reference/v1.0/api/printjob-get.md
  api-reference/v1.0/resources/archivedprintjob.md
  api-reference/v1.0/resources/fileattachment.md
  changelog/Microsoft.Bookings.json
  concepts/teams-licenses.md
  concepts/whats-new-overview.md
Labels: internal

#17349 Change WebJoinUrl to JoinWebUrl in example to improve consistency
  api-reference/beta/api/subscription-post-subscriptions.md
Labels: external

#17353 Validation: fixes for preserve-view-not-set
  concepts/changelog-archive.md
Labels: external, ready to merge

#17364 Validation: preserve-view-not-set
  concepts/changelog-archive.md
Labels: external, ready to merge

#17361 Validation: preserve-view-not-set on changelog-archive
  concepts/changelog-archive.md
Labels: external, ready to merge

#17360 Validation: Fix preserve view
  concepts/changelog-archive.md
Labels: external, ready to merge

#17359 Validation: Fix preserve-view-not-set
  concepts/changelog-archive.md
Labels: external, ready to merge

#17348 Fix resource to create onlineMeeting subscriptions
  concepts/changenotifications-for-onlinemeeting.md
Labels: external, ready to merge

#17341 Validation: preserve views not set
  concepts/changelog-archive.md
Labels: external, ready to merge

#17337 Validation: Preserve-view not set fixes.
  concepts/changelog-archive.md
Labels: external, ready to merge

#16976 [Window365] add new property alternateResourceUrl in ANC payload
  api-reference/beta/resources/cloudpconpremisesconnection.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, internal, content review complete

#17089 Added managedBy,cloudPcGroupDisplayName,gracePeriodInHours,localAdmin…
  api-reference/beta/api/cloudpcprovisioningpolicy-get.md
  api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md
  api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md
  api-reference/beta/resources/cloudpcprovisioningpolicy.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, internal, content review complete

#17325 preserve-view-not-set-fixes-4
  concepts/changelog-archive.md
Labels: external

#17322 preserve-view-not-set-fixes-3
  concepts/changelog-archive.md
Labels: external

#17274 chore: Set permissions for GitHub actions
  .github/workflows/changelog-validation.yml
Labels: external, review requested

#17368 Merge to publish.
  .github/workflows/changelog-validation.yml
  api-reference/beta/api/cloudpcprovisioningpolicy-get.md
  api-reference/beta/api/subscription-post-subscriptions.md
  api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md
  api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md
  api-reference/beta/resources/cloudpconpremisesconnection.md
  api-reference/beta/resources/cloudpcprovisioningpolicy.md
  api-reference/v1.0/api/projectrome-get-recent-activities.md
  changelog/Microsoft.CloudManagedDesktop.json
  concepts/changelog-archive.md
  concepts/changenotifications-for-onlinemeeting.md
Labels: internal

#17386 chore: Included githubactions in the dependabot config
  .github/dependabot.yml
Labels: external

#17320 preserve-view-not-set-fixes-2
  concepts/changelog-archive.md
Labels: external

#17324 Update metadata for Learn docs: Bookings & Device and app management
  concepts/booking-concept-overview.md
  concepts/bookingsbusiness-business-rules.md
  concepts/cloudpc-concept-overview.md
  concepts/intune-concept-overview.md
  concepts/managedtenants-concept-overview.md
  concepts/service-communications-concept-overview.md
  concepts/universal-print-concept-overview.md
  concepts/universal-print-webhook-notifications.md
  concepts/upload-data-to-upload-session.md
  concepts/whats-new-earlier.md
  concepts/windowsupdates-concept-overview.md
  concepts/windowsupdates-deploy-expedited-update.md
  concepts/windowsupdates-deploy-update.md
  concepts/windowsupdates-deployments.md
  concepts/windowsupdates-enroll.md
  concepts/windowsupdates-manage-monitoring-rules.md
  concepts/windowsupdates-manage-safeguards.md
  concepts/windowsupdates-schedule-deployment.md
  concepts/windowsupdates-software-updates.md
Labels: ready to merge, internal, content review complete

#17342 Update metadata for Learn docs: Education, Files, & Financials
  concepts/assignments-submissions-states-transition.md
  concepts/dynamics-business-central-concept-overview.md
  concepts/education-build-notificationchannelurl.md
  concepts/education-concept-overview.md
  concepts/education-rubric-overview.md
  concepts/education-upload-resource-overview.md
  concepts/onedrive-addressing-driveitems.md
  concepts/onedrive-concept-overview.md
Labels: ready to merge, internal, content review complete, review feedback addressed

#17367 Update metadata for Learn docs: Mail
  concepts/outlook-create-send-messages.md
  concepts/outlook-get-mime-message.md
  concepts/outlook-mail-concept-overview.md
  concepts/outlook-organize-messages.md
  concepts/outlook-send-mail-from-other-user.md
  concepts/outlook-send-mime-message.md
  concepts/outlook-share-messages-folders.md
Labels: ready to merge, internal

#17194 Internal Federation API v1 updates
  api-reference/v1.0/api/domain-post-federationconfiguration.md
  api-reference/v1.0/api/internaldomainfederation-delete.md
  api-reference/v1.0/api/internaldomainfederation-get.md
  api-reference/v1.0/api/internaldomainfederation-update.md
  api-reference/v1.0/resources/domain.md
  api-reference/v1.0/resources/enums.md
  api-reference/v1.0/resources/internaldomainfederation.md
  api-reference/v1.0/resources/signingcertificateupdatestatus.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, ready to merge, internal, content review complete, schema live
