Repository microsoftgraph/microsoft-graph-docs, pull requests merged in 2022-09, with the labels that each got.

#18267 Update plannerbuckettaskboardtaskformat-update.md
  api-reference/beta/api/plannerbuckettaskboardtaskformat-update.md
Labels: external

#18266 Update plannerbuckettaskboardtaskformat-update.md
  api-reference/v1.0/api/plannerbuckettaskboardtaskformat-update.md
Labels: external

#18265 Edits in PR 18018
  includes/data-connect-quickstart-02.md
  includes/data-connect-quickstart-03.md
  includes/data-connect-quickstart-04.md
  includes/data-connect-quickstart-05.md
  includes/data-connect-quickstart-06.md
  includes/data-connect-quickstart-07.md
Labels: external

#18145 Add user securityIdentifier to v1
  api-reference/v1.0/resources/user.md
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, area: users, ready to merge, internal, content review complete

#18273 Fix incorrect permissions reference
  api-reference/v1.0/api/presence-clearpresence.md
Labels: ready to merge, internal, content review complete

#18275 Edits in PR 18018
  includes/data-connect-quickstart-01.md
  includes/data-connect-quickstart-02.md
  includes/data-connect-quickstart-03.md
  includes/data-connect-quickstart-04.md
  includes/data-connect-quickstart-05.md
  includes/data-connect-quickstart-06.md
  includes/data-connect-quickstart-07.md
Labels: external

#18274 lifecycle info/permissions, and changelog
  api-reference/beta/api/user-update.md
  api-reference/beta/resources/user.md
  changelog/Microsoft.DirectoryServices.json
  concepts/permissions-reference.md
Labels: ready to merge, internal, content review complete

#18176 Microsoft Communications DLP enable note
  concepts/teams-licenses.md
Labels: ready to merge, internal, content review complete

#17576 teamworkcommunications merge
  api-reference/beta/resources/teams-api-overview.md
  api-reference/beta/toc.yml
  api-reference/v1.0/resources/teams-api-overview.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.Skype.Calling.json
  changelog/Microsoft.Teams.Core.json
  changelog/Microsoft.Teams.GraphSvc.json
  changelog/Microsoft.Teams.Shifts.json
  concepts/cloud-communication-online-meeting-application-access-policy.md
  concepts/cloud-communications-callrecords.md
  concepts/cloud-communications-calls.md
  concepts/cloud-communications-get-started.md
  concepts/cloud-communications-identifylargegalleryview.md
  concepts/cloud-communications-media.md
  concepts/cloud-communications-online-meeting-artifacts.md
  concepts/cloud-communications-online-meetings.md
  concepts/cloud-communications-phone-number.md
  concepts/overview-major-services.md
  concepts/teams-concept-overview.md
  concepts/toc.yml
Labels: ready to merge, changes requested, internal, content review in progress

#18278 Merged and publish cloud communication API and Teams API under one TOC node.
  api-reference/beta/resources/teams-api-overview.md
  api-reference/beta/toc.yml
  api-reference/v1.0/resources/teams-api-overview.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.Skype.Calling.json
  changelog/Microsoft.Teams.Core.json
  changelog/Microsoft.Teams.GraphSvc.json
  changelog/Microsoft.Teams.Shifts.json
  concepts/cloud-communication-online-meeting-application-access-policy.md
  concepts/cloud-communications-callrecords.md
  concepts/cloud-communications-calls.md
  concepts/cloud-communications-get-started.md
  concepts/cloud-communications-identifylargegalleryview.md
  concepts/cloud-communications-media.md
  concepts/cloud-communications-online-meeting-artifacts.md
  concepts/cloud-communications-online-meetings.md
  concepts/cloud-communications-phone-number.md
  concepts/overview-major-services.md
  concepts/teams-concept-overview.md
  concepts/toc.yml
Labels: internal

#17588 Updating Authentication Methods Policy beta branch with new feature settings changes.
  api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md
  api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-update.md
  api-reference/beta/resources/authenticationmethodfeatureconfiguration.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/featuretarget.md
  api-reference/beta/resources/microsoftauthenticatorauthenticationmethodconfiguration.md
  api-reference/beta/resources/microsoftauthenticatorauthenticationmethodtarget.md
  api-reference/beta/resources/microsoftauthenticatorfeaturesettings.md
  changelog/Microsoft.AuthenticationMethodsPolicy.json
Labels: area: Azure AD, resolved: awaiting prod deployment, ready to merge, content review complete, schema live

#18136 Update permissions-reference.md
  concepts/permissions-reference.md
Labels: ready to merge, internal, content review complete

#18244 updated assignmentsubbmission-get
  concepts/assignments-submissions-states-transition.md
Labels: ready to merge, internal, content review complete

#17854 Adding assign sensitivity label api documentation
  api-reference/beta/api/driveitem-assignsensitivitylabel.md
  api-reference/beta/resources/driveitem.md
  api-reference/beta/toc.yml
  changelog/Microsoft.FileServices.json
Labels: ready to merge, internal, content review complete, schema live

#18261 EM: more details on originid of resource roles
  api-reference/beta/api/accesspackage-list-accesspackageresourcerolescopes.md
  api-reference/beta/api/accesspackage-post-accesspackageresourcerolescopes.md
  api-reference/beta/api/accesspackagecatalog-list-accesspackageresourceroles.md
  api-reference/beta/api/entitlementmanagement-post-accesspackageresourcerequests.md
  api-reference/beta/resources/accesspackageresourcerole.md
Labels: area: Azure AD, ready to merge, internal, content review complete

#18281 Merge to publish.
  api-reference/beta/api/accesspackage-list-accesspackageresourcerolescopes.md
  api-reference/beta/api/accesspackage-post-accesspackageresourcerolescopes.md
  api-reference/beta/api/accesspackagecatalog-list-accesspackageresourceroles.md
  api-reference/beta/api/driveitem-assignsensitivitylabel.md
  api-reference/beta/api/entitlementmanagement-post-accesspackageresourcerequests.md
  api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md
  api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-update.md
  api-reference/beta/resources/accesspackageresourcerole.md
  api-reference/beta/resources/authenticationmethodfeatureconfiguration.md
  api-reference/beta/resources/driveitem.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/featuretarget.md
  api-reference/beta/resources/microsoftauthenticatorauthenticationmethodconfiguration.md
  api-reference/beta/resources/microsoftauthenticatorauthenticationmethodtarget.md
  api-reference/beta/resources/microsoftauthenticatorfeaturesettings.md
  api-reference/beta/toc.yml
  changelog/Microsoft.AuthenticationMethodsPolicy.json
  changelog/Microsoft.FileServices.json
  concepts/assignments-submissions-states-transition.md
  concepts/permissions-reference.md
Labels: do not merge, internal

#18282 Make consistent proper use of singular or plural terms in the first 2 levels of reference TOC (v1 and beta).
  api-reference/beta/resources/opentypeextension.md
  api-reference/beta/toc.yml
  api-reference/v1.0/resources/opentypeextension.md
  api-reference/v1.0/toc.yml
Labels: do not merge, internal

#18283 Fixed first 2 levels of reference TOCs (v1.0 and beta) to use singular/plural in TOC titles consistently.
  api-reference/beta/resources/opentypeextension.md
  api-reference/beta/toc.yml
  api-reference/v1.0/resources/opentypeextension.md
  api-reference/v1.0/toc.yml
Labels: do not merge, internal

#18292 Edits in PR 18178
  includes/data-connect-quickstart-06.md
  includes/data-connect-quickstart-07.md
  includes/data-connect-quickstart-08.md
Labels: external

#18293 Edits in PR 18018
  includes/data-connect-quickstart-05.md
Labels: external

#18314 Edits in PR 18178
  includes/data-connect-quickstart-06.md
Labels: external

#18318 Edit in PR 17674
  concepts/outlook-calendar-concept-overview.md
Labels: external

#18313 Correct URL path for swapping refresh token
  concepts/auth-v2-user.md
Labels: external

#18319 Update educationsubmittedsubmissionresource-get.md
  api-reference/beta/api/educationsubmittedsubmissionresource-get.md
Labels: external, ready to merge

#18294 Update educationsynchronizationprofile-delete.md
  api-reference/beta/api/educationsynchronizationprofile-delete.md
Labels: external

#18298 Update teams-licenses.md
  concepts/teams-licenses.md
Labels: external

#18307 [BrokenLinksH2] Fix path in link
  concepts/throttling-limits.md
  includes/throttling-intune-android-for-work.md
  includes/throttling-intune-applications.md
  includes/throttling-intune-auditing.md
  includes/throttling-intune-books.md
  includes/throttling-intune-bundles.md
  includes/throttling-intune-chromebook-sync.md
  includes/throttling-intune-device-config-v2.md
  includes/throttling-intune-device-configuration.md
  includes/throttling-intune-device-enrollment.md
  includes/throttling-intune-device-intent.md
  includes/throttling-intune-devices.md
  includes/throttling-intune-endpoint-protection.md
  includes/throttling-intune-enrollment.md
  includes/throttling-intune-fencing.md
  includes/throttling-intune-managed-applications.md
  includes/throttling-intune-partner-integration.md
  includes/throttling-intune-rbac.md
  includes/throttling-intune-troubleshooting.md
  includes/throttling-multi-tenant-platform.md
Labels: external

#18320 [BrokenLinksH2] - Fixing broken link
  api-reference/v1.0/api/contenttype-post-columns.md
Labels: external

#17278 Update chatmessage-update.md
  api-reference/beta/api/chatmessage-update.md
  api-reference/v1.0/api/chatmessage-update.md
Labels: external, ready to merge

#18039 Adding description about `$filter` support
  api-reference/v1.0/api/alert-list.md
Labels: external, ready to merge

#16846 Add certificateUserIds attribute for users
  api-reference/beta/api/user-update.md
  api-reference/beta/resources/authorizationinfo.md
  api-reference/beta/resources/certificatebasedauthconfiguration.md
  api-reference/beta/resources/user.md
  changelog/Microsoft.DirectoryServices.json
  includes/filter-directory-objects.md
Labels: area: Azure AD, ready to merge, internal

#18289 Update custom-connector-sdk-overview.md
  concepts/custom-connector-sdk-overview.md
Labels: ready to merge, internal, content review complete, area: connectors

#18286 Minor doc fixes
  api-reference/beta/api/application-list.md
  api-reference/beta/resources/application.md
  api-reference/beta/resources/users.md
  api-reference/v1.0/api/application-list.md
  api-reference/v1.0/resources/application.md
  api-reference/v1.0/resources/users.md
Labels: area: Azure AD, ready to merge, internal

#18335 Added MGT productivity hub tutorial to TOC
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
  concepts/includes/graph-toolkit-building-one-productivity-hub-06-summary.md
  concepts/toc.yml
  concepts/toolkit/get-started/building-one-productivity-hub.yml
  concepts/toolkit/get-started/includes/building-one-productivity-hub-01-intro.md
  concepts/toolkit/get-started/includes/building-one-productivity-hub-02-register-app.md
  concepts/toolkit/get-started/includes/building-one-productivity-hub-03-build-app.md
  concepts/toolkit/get-started/includes/building-one-productivity-hub-04-design-app.md
  concepts/toolkit/get-started/includes/building-one-productivity-hub-05-run-app.md
  concepts/toolkit/get-started/includes/building-one-productivity-hub-06-summary.md
Labels: internal

#18348 [BrokenLinksH2] Fix path in link
  includes/throttling-intune-device-configuration.md
Labels: external

#18345 [BrokenLinksH2] Fix path in link
  concepts/throttling-limits.md
  includes/throttling-intune-applications.md
  includes/throttling-intune-company-terms.md
  includes/throttling-intune-devices.md
  includes/throttling-intune-fencing.md
  includes/throttling-intune-gpanalytics.md
  includes/throttling-intune-managed-applications.md
  includes/throttling-intune-notifications.md
  includes/throttling-intune-partner-integration.md
  includes/throttling-intune-rbac.md
  includes/throttling-intune-remote-assistance.md
  includes/throttling-intune-telephony.md
  includes/throttling-intune-tem.md
  includes/throttling-intune-throttling-tunnel.md
  includes/throttling-intune-unlock.md
  includes/throttling-intune-updates.md
  includes/throttling-intune-wip.md
  includes/throttling-skype-calling.md
Labels: external

#18344 [BrokenLinksH2] - Permissions link
  api-reference/beta/api/governancerolesetting-get.md
Labels: external, ready to merge

#18337 Update responsestatus.md
  api-reference/beta/resources/responsestatus.md
Labels: ready to merge, internal

#18336 Update webhooks.md
  concepts/webhooks.md
Labels: ready to merge, internal

#18156 Entitlement management: access package assignment request requesttype values
  api-reference/beta/resources/accesspackageassignmentrequest.md
  api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md
  api-reference/v1.0/resources/accesspackageassignmentrequest.md
Labels: area: Azure AD, ready to merge, internal, content review complete

#18347 [BrokenLinksH2] - Team link
  api-reference/v1.0/api/group-delete-owners.md
Labels: external, ready to merge

#18346 Updating docs author
  concepts/data-connect-concept-overview.md
  concepts/data-connect-datasets.md
  concepts/data-connect-filtering.md
  concepts/data-connect-pam.md
  concepts/data-connect-policies.md
  concepts/data-connect-quickstart.yml
Labels: ready to merge, internal

#18342 Update networkinterface.md
  api-reference/beta/resources/networkinterface.md
Labels: ready to merge, internal

#18334 [BrokenLinksH2] Update ediscovery-case-post.md
  api-reference/beta/api/ediscovery-case-post.md
Labels: external, ready to merge

#17667 Entitlement Management - Added regexPattern to textinputquestion
  api-reference/beta/resources/accesspackagetextinputquestion.md
  changelog/Microsoft.IGAELM.json
Labels: do not merge, ready to merge, internal, content review complete

#18331 Update custom-connector-sdk-publish.md
  concepts/custom-connector-sdk-publish.md
Labels: ready to merge, internal, content review complete, area: connectors

#18326 Minor doc fixes
  api-reference/beta/api/directory-deleteditems-delete.md
  api-reference/beta/api/directory-deleteditems-list.md
  api-reference/beta/resources/user.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/directory-deleteditems-delete.md
  api-reference/v1.0/api/directory-deleteditems-list.md
  api-reference/v1.0/toc.yml
Labels: area: Azure AD, ready to merge, internal

#17853 Adding role specific details to the document educationSubmission:submit/unsubmit
  api-reference/beta/api/educationsubmission-submit.md
  api-reference/beta/api/educationsubmission-unsubmit.md
  api-reference/v1.0/api/educationsubmission-submit.md
  api-reference/v1.0/api/educationsubmission-unsubmit.md
Labels: ready to merge, internal, content review complete, review feedback addressed

#18340 Update worksheetcollection-add.md
  api-reference/beta/api/worksheetcollection-add.md
Labels: ready to merge, internal

#18338 Update security-concept-overview.md
  concepts/security-concept-overview.md
Labels: ready to merge, internal

#18358 Merge to publish.
  api-reference/beta/api/directory-deleteditems-delete.md
  api-reference/beta/api/directory-deleteditems-list.md
  api-reference/beta/api/ediscovery-case-post.md
  api-reference/beta/api/educationsubmission-submit.md
  api-reference/beta/api/educationsubmission-unsubmit.md
  api-reference/beta/api/governancerolesetting-get.md
  api-reference/beta/api/worksheetcollection-add.md
  api-reference/beta/resources/accesspackageassignmentrequest.md
  api-reference/beta/resources/accesspackagetextinputquestion.md
  api-reference/beta/resources/networkinterface.md
  api-reference/beta/resources/responsestatus.md
  api-reference/beta/resources/user.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/directory-deleteditems-delete.md
  api-reference/v1.0/api/directory-deleteditems-list.md
  api-reference/v1.0/api/educationsubmission-submit.md
  api-reference/v1.0/api/educationsubmission-unsubmit.md
  api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md
  api-reference/v1.0/api/group-delete-owners.md
  api-reference/v1.0/resources/accesspackageassignmentrequest.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.IGAELM.json
  concepts/custom-connector-sdk-publish.md
  concepts/data-connect-concept-overview.md
  concepts/data-connect-datasets.md
  concepts/data-connect-filtering.md
  concepts/data-connect-pam.md
  concepts/data-connect-policies.md
  concepts/data-connect-quickstart.yml
  concepts/includes/graph-toolkit-building-one-productivity-hub-06-summary.md
  concepts/security-concept-overview.md
  concepts/throttling-limits.md
  concepts/toc.yml
  concepts/toolkit/get-started/building-one-productivity-hub.yml
  concepts/toolkit/get-started/includes/building-one-productivity-hub-01-intro.md
  concepts/toolkit/get-started/includes/building-one-productivity-hub-02-register-app.md
  concepts/toolkit/get-started/includes/building-one-productivity-hub-03-build-app.md
  concepts/toolkit/get-started/includes/building-one-productivity-hub-04-design-app.md
  concepts/toolkit/get-started/includes/building-one-productivity-hub-05-run-app.md
  concepts/toolkit/get-started/includes/building-one-productivity-hub-06-summary.md
  concepts/webhooks.md
  includes/throttling-intune-applications.md
  includes/throttling-intune-company-terms.md
  includes/throttling-intune-device-configuration.md
  includes/throttling-intune-devices.md
  includes/throttling-intune-fencing.md
  includes/throttling-intune-gpanalytics.md
  includes/throttling-intune-managed-applications.md
  includes/throttling-intune-notifications.md
  includes/throttling-intune-partner-integration.md
  includes/throttling-intune-rbac.md
  includes/throttling-intune-remote-assistance.md
  includes/throttling-intune-telephony.md
  includes/throttling-intune-tem.md
  includes/throttling-intune-throttling-tunnel.md
  includes/throttling-intune-unlock.md
  includes/throttling-intune-updates.md
  includes/throttling-intune-wip.md
  includes/throttling-skype-calling.md
Labels: internal

#18238 [METADATA UPDATE] Global metadata changes
  concepts/onedrive-concept-overview.md
Labels: do not merge, internal

#18376 Fix metadata.
  concepts/onedrive-concept-overview.md
Labels: ready to merge, internal

#18370 [BrokenLinksH2] Update insights-list-trending.md
  api-reference/beta/api/insights-list-trending.md
Labels: external, ready to merge

#18369 [BrokenLinksH2] Broken link fix
  api-reference/beta/api/insights-list-used.md
Labels: external, ready to merge

#18364 [BrokenLinksH2] Fix path in link
  concepts/throttling-limits.md
  includes/throttling-aad-reports.md
  includes/throttling-cpim.md
  includes/throttling-education-rostering-apis.md
  includes/throttling-excel.md
  includes/throttling-intune-bundles.md
  includes/throttling-intune-device-configuration.md
  includes/throttling-skype-calling.md
  includes/throttling-teams.md
Labels: external, ready to merge

#17675 Changes to post members API page for 1.0 create in AU
  api-reference/beta/api/administrativeunit-post-members.md
  api-reference/v1.0/api/administrativeunit-post-members.md
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, ready to merge, internal, content review complete

#18018 U/rmisra/update build mgdc app
  concepts/images/data-connect-aad-app-owners-new.png
  concepts/images/data-connect-aad-certs-secrets-new.png
  concepts/images/data-connect-adf-copy-activity.png
  concepts/images/data-connect-adf-dataset.png
  concepts/images/data-connect-adf-integration-runtime-b-new.png
  concepts/images/data-connect-adf-m365icon-new.png
  concepts/images/data-connect-adf-network-new.png
  concepts/images/data-connect-adf-studio-new.png
  concepts/images/data-connect-app-tenant-new.png
  concepts/images/data-connect-azure-storage-network-new.png
  concepts/images/data-connect-azure-storageaccount-create.png
  concepts/images/data-connect-consent-request-a-new.png
  concepts/images/data-connect-consent-request-b-new.png
  concepts/images/data-connect-m365-active-groups-new.png
  concepts/images/data-connect-m365-consent-approver-new.png
  concepts/images/data-connect-m365-sec-distr-new.png
  includes/data-connect-quickstart-01.md
  includes/data-connect-quickstart-02.md
  includes/data-connect-quickstart-03.md
  includes/data-connect-quickstart-04.md
  includes/data-connect-quickstart-05.md
  includes/data-connect-quickstart-06.md
  includes/data-connect-quickstart-07.md
Labels: ready to merge, internal, content review complete

#18367 Minor doc fixes
  api-reference/beta/api/authenticationmethodsroot-list-userregistrationdetails.md
  api-reference/beta/api/domain-post-federationconfiguration.md
  api-reference/beta/api/group-delete-members.md
  api-reference/beta/api/group-post-groups.md
  api-reference/beta/api/group-post-members.md
  api-reference/beta/api/internaldomainfederation-delete.md
  api-reference/beta/api/internaldomainfederation-get.md
  api-reference/beta/api/internaldomainfederation-update.md
  api-reference/beta/api/user-delete.md
  api-reference/beta/api/userregistrationdetails-get.md
  api-reference/v1.0/api/domain-post-federationconfiguration.md
  api-reference/v1.0/api/group-delete-members.md
  api-reference/v1.0/api/group-post-groups.md
  api-reference/v1.0/api/group-post-members.md
  api-reference/v1.0/api/internaldomainfederation-delete.md
  api-reference/v1.0/api/internaldomainfederation-get.md
  api-reference/v1.0/api/internaldomainfederation-update.md
  api-reference/v1.0/api/user-delete.md
  concepts/application-saml-sso-configure-api.md
  concepts/json-batching.md
  concepts/resolve-auth-errors.md
Labels: area: Azure AD, ready to merge, internal

#18383 Merge to publish.
  SECURITY.md
  api-reference/beta/api/administrativeunit-post-members.md
  api-reference/beta/api/authenticationmethodsroot-list-userregistrationdetails.md
  api-reference/beta/api/domain-post-federationconfiguration.md
  api-reference/beta/api/group-delete-members.md
  api-reference/beta/api/group-post-groups.md
  api-reference/beta/api/group-post-members.md
  api-reference/beta/api/insights-list-trending.md
  api-reference/beta/api/insights-list-used.md
  api-reference/beta/api/internaldomainfederation-delete.md
  api-reference/beta/api/internaldomainfederation-get.md
  api-reference/beta/api/internaldomainfederation-update.md
  api-reference/beta/api/user-delete.md
  api-reference/beta/api/userregistrationdetails-get.md
  api-reference/v1.0/api/administrativeunit-post-members.md
  api-reference/v1.0/api/domain-post-federationconfiguration.md
  api-reference/v1.0/api/group-delete-members.md
  api-reference/v1.0/api/group-post-groups.md
  api-reference/v1.0/api/group-post-members.md
  api-reference/v1.0/api/internaldomainfederation-delete.md
  api-reference/v1.0/api/internaldomainfederation-get.md
  api-reference/v1.0/api/internaldomainfederation-update.md
  api-reference/v1.0/api/user-delete.md
  changelog/Microsoft.DirectoryServices.json
  concepts/application-saml-sso-configure-api.md
  concepts/images/data-connect-aad-app-owners-new.png
  concepts/images/data-connect-aad-certs-secrets-new.png
  concepts/images/data-connect-adf-copy-activity.png
  concepts/images/data-connect-adf-dataset.png
  concepts/images/data-connect-adf-integration-runtime-b-new.png
  concepts/images/data-connect-adf-m365icon-new.png
  concepts/images/data-connect-adf-network-new.png
  concepts/images/data-connect-adf-studio-new.png
  concepts/images/data-connect-app-tenant-new.png
  concepts/images/data-connect-azure-storage-network-new.png
  concepts/images/data-connect-azure-storageaccount-create.png
  concepts/images/data-connect-consent-request-a-new.png
  concepts/images/data-connect-consent-request-b-new.png
  concepts/images/data-connect-m365-active-groups-new.png
  concepts/images/data-connect-m365-consent-approver-new.png
  concepts/images/data-connect-m365-sec-distr-new.png
  concepts/json-batching.md
  concepts/onedrive-concept-overview.md
  concepts/resolve-auth-errors.md
  concepts/throttling-limits.md
  includes/data-connect-quickstart-01.md
  includes/data-connect-quickstart-02.md
  includes/data-connect-quickstart-03.md
  includes/data-connect-quickstart-04.md
  includes/data-connect-quickstart-05.md
  includes/data-connect-quickstart-06.md
  includes/data-connect-quickstart-07.md
  includes/throttling-aad-reports.md
  includes/throttling-cpim.md
  includes/throttling-education-rostering-apis.md
  includes/throttling-excel.md
  includes/throttling-intune-bundles.md
  includes/throttling-intune-device-configuration.md
  includes/throttling-skype-calling.md
  includes/throttling-teams.md
Labels: internal

#18386 Fix changelog sync
  changelog/Microsoft.Teams.Core.json
Labels: ready to merge, internal

#18395 Added missing files to TOC.
  api-reference/beta/resources/workbooktablerow.md
  api-reference/beta/toc.yml
  api-reference/v1.0/resources/workbooktablerow.md
  api-reference/v1.0/toc.yml
Labels: ready to merge, internal

#18397 Update plannerplan-delete.md
  api-reference/beta/api/plannerplan-delete.md
Labels: external

#18396 Update plannerplan-delete.md
  api-reference/v1.0/api/plannerplan-delete.md
Labels: external

#18401 update to say guest and federated users are included in online meetings
  concepts/cloud-communications-online-meeting-artifacts.md
Labels: ready to merge

#15864 Concept Document - Microsoft Graph Onboarding
  api-reference/beta/api/educationassignment-post-categories.md
  api-reference/beta/api/educationassignment-remove-category.md
  concepts/education-build-notificationchannelurl.md
  concepts/images/msgraph-onboarding/assignments.png
  concepts/images/msgraph-onboarding/edutenant-6.png
  concepts/images/msgraph-onboarding/explorer8-createassignment.png
  concepts/images/msgraph-onboarding/sds10-settingup.png
  concepts/images/msgraph-onboarding/sds11-status.png
  concepts/images/msgraph-onboarding/sds2-connection.png
  concepts/images/msgraph-onboarding/sds3-syncoptions.png
  concepts/images/msgraph-onboarding/sds4-upload.png
  concepts/images/msgraph-onboarding/sds6-teacher.png
  concepts/images/msgraph-onboarding/sds7-student.png
  concepts/images/msgraph-onboarding/teams6-people.png
  concepts/images/msgraph-onboarding/teams7-created.png
  concepts/msgraph-onboarding-devtenant.md
  concepts/msgraph-onboarding-edutenant.md
  concepts/msgraph-onboarding-graphexplorer.md
  concepts/msgraph-onboarding-mpn.md
  concepts/msgraph-onboarding-msteams.md
  concepts/msgraph-onboarding-overview.md
  concepts/msgraph-onboarding-sds.md
  concepts/toc.yml
Labels: ready to merge, internal, content review complete, schema live

#18301 Update termstore-store.md
  api-reference/v1.0/resources/termstore-store.md
Labels: ready to merge, internal, content review complete

#18366 Minor doc fixes
  api-reference/beta/resources/synchronization-synchronizationschedule.md
  concepts/auth-v2-user.md
  concepts/best-practices-concept.md
Labels: area: Azure AD, ready to merge, internal

#18402 Merge to publish.
  api-reference/beta/api/educationassignment-post-categories.md
  api-reference/beta/api/educationassignment-remove-category.md
  api-reference/beta/api/plannerplan-delete.md
  api-reference/beta/resources/synchronization-synchronizationschedule.md
  api-reference/beta/resources/workbooktablerow.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/plannerplan-delete.md
  api-reference/v1.0/resources/termstore-store.md
  api-reference/v1.0/resources/workbooktablerow.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.Teams.Core.json
  concepts/auth-v2-user.md
  concepts/best-practices-concept.md
  concepts/cloud-communications-online-meeting-artifacts.md
  concepts/education-build-notificationchannelurl.md
  concepts/images/msgraph-onboarding/assignments.png
  concepts/images/msgraph-onboarding/edutenant-6.png
  concepts/images/msgraph-onboarding/explorer8-createassignment.png
  concepts/images/msgraph-onboarding/sds10-settingup.png
  concepts/images/msgraph-onboarding/sds11-status.png
  concepts/images/msgraph-onboarding/sds2-connection.png
  concepts/images/msgraph-onboarding/sds3-syncoptions.png
  concepts/images/msgraph-onboarding/sds4-upload.png
  concepts/images/msgraph-onboarding/sds6-teacher.png
  concepts/images/msgraph-onboarding/sds7-student.png
  concepts/images/msgraph-onboarding/teams6-people.png
  concepts/images/msgraph-onboarding/teams7-created.png
  concepts/msgraph-onboarding-devtenant.md
  concepts/msgraph-onboarding-edutenant.md
  concepts/msgraph-onboarding-graphexplorer.md
  concepts/msgraph-onboarding-mpn.md
  concepts/msgraph-onboarding-msteams.md
  concepts/msgraph-onboarding-overview.md
  concepts/msgraph-onboarding-sds.md
  concepts/toc.yml
Labels: internal

#17990 App-scoped chat subscriptions
  api-reference/beta/api/subscription-delete.md
  api-reference/beta/api/subscription-get.md
  api-reference/beta/api/subscription-list.md
  api-reference/beta/api/subscription-post-subscriptions.md
  api-reference/beta/api/subscription-update.md
  api-reference/beta/resources/webhooks.md
  api-reference/includes/teams-subscription-notes.md
  api-reference/v1.0/resources/webhooks.md
  changelog/Microsoft.Teams.Core.json
  concepts/permissions-reference.md
  concepts/teams-change-notification-in-microsoft-teams-overview.md
  concepts/teams-changenotifications-chat.md
  concepts/teams-changenotifications-chatMembership.md
  concepts/teams-changenotifications-chatmessage.md
  concepts/teams-changenotifications-team-and-channel.md
  concepts/teams-changenotifications-teamMembership.md
  concepts/teams-licenses.md
Labels: internal, content review complete

#18403 Publish PR 17990 to live branch.
  api-reference/beta/api/subscription-delete.md
  api-reference/beta/api/subscription-get.md
  api-reference/beta/api/subscription-list.md
  api-reference/beta/api/subscription-post-subscriptions.md
  api-reference/beta/api/subscription-update.md
  api-reference/beta/resources/webhooks.md
  api-reference/includes/teams-subscription-notes.md
  api-reference/v1.0/resources/webhooks.md
  changelog/Microsoft.Teams.Core.json
  concepts/permissions-reference.md
  concepts/teams-change-notification-in-microsoft-teams-overview.md
  concepts/teams-changenotifications-chat.md
  concepts/teams-changenotifications-chatMembership.md
  concepts/teams-changenotifications-chatmessage.md
  concepts/teams-changenotifications-team-and-channel.md
  concepts/teams-changenotifications-teamMembership.md
  concepts/teams-licenses.md
Labels: do not merge, internal

#18404 Made introduction more inclusive.
  api-reference/beta/resources/webhooks.md
  api-reference/v1.0/resources/webhooks.md
Labels: internal

#18405 Publish PR 18404 to live branch.
  api-reference/beta/resources/webhooks.md
  api-reference/v1.0/resources/webhooks.md
Labels: internal

#18435 Fine-tune topic & section titles to match customer intent.
  concepts/outlook-calendar-concept-overview.md
  concepts/outlook-calendar-online-meetings.md
  concepts/toc.yml
Labels: internal

#18437 [BrokenLinksH2] Update ediscovery-case.md
  api-reference/beta/resources/ediscovery-case.md
Labels: external

#18436 [BrokenLinksH2] Update driveitem.md
  api-reference/v1.0/resources/driveitem.md
Labels: external

#18434 [BrokenLinksH2] Update changenotificationencryptedcontent.md
  api-reference/v1.0/resources/changenotificationencryptedcontent.md
Labels: external

#18433 [BrokenLinksH2] Update changenotificationcollection.md
  api-reference/v1.0/resources/changenotificationcollection.md
Labels: external

#18432 [BrokenLinksH2] Update booking-api-overview.md
  api-reference/beta/resources/booking-api-overview.md
Labels: external

#18431 Update eventmessagedetail.md
  api-reference/beta/resources/eventmessagedetail.md
Labels: external

#18430 Update eventmessagedetail.md
  api-reference/v1.0/resources/eventmessagedetail.md
Labels: external

#18427 [BrokenLinksH2] Update azure-ad-overview.md
  api-reference/v1.0/resources/azure-ad-overview.md
Labels: external

#18426 [BrokenLinksH2] Update rangeformat-update.md
  api-reference/beta/api/rangeformat-update.md
Labels: external

#18424 Edits in PR 18119
  api-reference/beta/api/chat-list-pinnedmessages.md
  api-reference/beta/api/chat-post-pinnedmessages.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/chat-list-pinnedmessages.md
  api-reference/v1.0/api/chat-post-pinnedmessages.md
  api-reference/v1.0/resources/pinnedchatmessageinfo.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.Teams.Core.json
Labels: external

#18422 Update data-connect-quickstart-04.md
  includes/data-connect-quickstart-04.md
Labels: external

#18411 [BrokenLinksH2] Update message-unsubscribe.md
  api-reference/beta/api/message-unsubscribe.md
Labels: external

#18410 [BrokenLinksH2] Update list-post-columns.md
  api-reference/v1.0/api/list-post-columns.md
Labels: external

#18373 [BULK] DocuTune - Fix build validation issues: docs-link-absolute (part 2)
  api-reference/beta/api/reportroot-getteamsuseractivityuserdetail.md
  api-reference/beta/resources/communicationsapplicationidentity.md
  api-reference/beta/resources/communicationsapplicationinstanceidentity.md
  api-reference/beta/resources/communicationsuseridentity.md
  api-reference/beta/resources/crosstenantaccesspolicy-overview.md
Labels: external

#18374 [BULK] DocuTune - Fix build validation issues: docs-link-absolute (part 3)
  api-reference/beta/resources/security-ediscoveryfile.md
  api-reference/v1.0/api/reportroot-getteamsuseractivityuserdetail.md
  concepts/application-proxy-configure-api.md
  concepts/universal-print-webhook-notifications.md
  concepts/whats-new-earlier.md
  includes/search-api-preview-signup.md
Labels: external

#18224 Jupetter updatesensitiveproperties
  api-reference/beta/api/user-update.md
  api-reference/v1.0/api/user-update.md
Labels: area: Azure AD, ready to merge, content review complete

#18412 Update extensions ms.prod
  concepts/extensibility-open-users.md
  concepts/extensibility-overview.md
  concepts/extensibility-schema-groups.md
Labels: ready to merge, internal

#18416 Request code snippets - Identity conceptual articles
  concepts/application-proxy-configure-api.md
  concepts/application-saml-sso-configure-api.md
  concepts/custom-security-attributes-examples.md
  concepts/tutorial-access-package-api.md
  concepts/tutorial-riskdetection-api.md
Labels: ready to merge, internal

#18152 Add M365DAdminDismissedDetection
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/riskdetection.md
  api-reference/v1.0/resources/enums.md
  api-reference/v1.0/resources/riskdetection.md
  changelog/Microsoft.IdentityProtectionServices.json
Labels: area: Azure AD, external, ready to merge, content review complete

#18425 Update driveitem-assignsensitivitylabel.md
  api-reference/beta/api/driveitem-assignsensitivitylabel.md
Labels: external, ready to merge

#18417 [BrokenLinksH2] Fix path in link
  concepts/toolkit/components/todo.md
  concepts/toolkit/providers/teams-msal2.md
  concepts/tutorial-accessreviews-roleassignments.md
  concepts/webhooks-with-resource-data.md
  concepts/whats-new-earlier.md
Labels: external, ready to merge

#18438 Merge to publish.
  api-reference/beta/api/driveitem-assignsensitivitylabel.md
  api-reference/beta/api/message-unsubscribe.md
  api-reference/beta/api/rangeformat-update.md
  api-reference/beta/api/reportroot-getteamsuseractivityuserdetail.md
  api-reference/beta/api/user-update.md
  api-reference/beta/resources/booking-api-overview.md
  api-reference/beta/resources/communicationsapplicationidentity.md
  api-reference/beta/resources/communicationsapplicationinstanceidentity.md
  api-reference/beta/resources/communicationsuseridentity.md
  api-reference/beta/resources/crosstenantaccesspolicy-overview.md
  api-reference/beta/resources/ediscovery-case.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/eventmessagedetail.md
  api-reference/beta/resources/riskdetection.md
  api-reference/beta/resources/security-ediscoveryfile.md
  api-reference/v1.0/api/list-post-columns.md
  api-reference/v1.0/api/reportroot-getteamsuseractivityuserdetail.md
  api-reference/v1.0/api/user-update.md
  api-reference/v1.0/resources/azure-ad-overview.md
  api-reference/v1.0/resources/changenotificationcollection.md
  api-reference/v1.0/resources/changenotificationencryptedcontent.md
  api-reference/v1.0/resources/driveitem.md
  api-reference/v1.0/resources/enums.md
  api-reference/v1.0/resources/eventmessagedetail.md
  api-reference/v1.0/resources/riskdetection.md
  changelog/Microsoft.IdentityProtectionServices.json
  concepts/application-proxy-configure-api.md
  concepts/application-saml-sso-configure-api.md
  concepts/custom-security-attributes-examples.md
  concepts/extensibility-open-users.md
  concepts/extensibility-overview.md
  concepts/extensibility-schema-groups.md
  concepts/outlook-calendar-concept-overview.md
  concepts/outlook-calendar-online-meetings.md
  concepts/toc.yml
  concepts/toolkit/components/todo.md
  concepts/toolkit/providers/teams-msal2.md
  concepts/tutorial-access-package-api.md
  concepts/tutorial-accessreviews-roleassignments.md
  concepts/tutorial-riskdetection-api.md
  concepts/universal-print-webhook-notifications.md
  concepts/webhooks-with-resource-data.md
  concepts/whats-new-earlier.md
  includes/data-connect-quickstart-04.md
  includes/search-api-preview-signup.md
Labels: internal

#18466 [Bulk]MS-09-13-graph-docs-fixes
  concepts/known-issues.md
  concepts/migrate-azure-ad-graph-resource-differences.md
  concepts/notifications-integrating-app-server.md
  concepts/onenote-update-page.md
  concepts/outlook-send-mime-message.md
Labels: external

#18465 [BrokenLinksH2] Update onedrive.md
  api-reference/v1.0/resources/onedrive.md
Labels: external

#18463 [BrokenLinksH2] Update message.md
  api-reference/v1.0/resources/message.md
Labels: external

#18455 [BrokenLinksH2] Update eventmessageresponse.md
  api-reference/v1.0/resources/eventmessageresponse.md
Labels: external

#18454 [BrokenLinksH2] Update eventmessagerequest.md
  api-reference/v1.0/resources/eventmessagerequest.md
Labels: external

#18453 [BrokenLinksH2] Update eventmessage.md
  api-reference/v1.0/resources/eventmessage.md
Labels: external

#18448 [BrokenLinksH2] Fix path in link
  concepts/whats-new-earlier.md
Labels: external

#18362 reducing the image size
  concepts/images/mgt-one-productivity-hub/aad-app-registration.png
  concepts/images/mgt-one-productivity-hub/aad-new-app-registration-form.png
  concepts/toolkit/get-started/includes/building-one-productivity-hub-02-register-app.md
Labels: external, ready to merge

#18467 Merge to publish.
  api-reference/v1.0/resources/eventmessage.md
  api-reference/v1.0/resources/eventmessagerequest.md
  api-reference/v1.0/resources/eventmessageresponse.md
  api-reference/v1.0/resources/message.md
  api-reference/v1.0/resources/onedrive.md
  concepts/images/mgt-one-productivity-hub/aad-app-registration.png
  concepts/images/mgt-one-productivity-hub/aad-new-app-registration-form.png
  concepts/known-issues.md
  concepts/migrate-azure-ad-graph-resource-differences.md
  concepts/notifications-integrating-app-server.md
  concepts/onenote-update-page.md
  concepts/outlook-send-mime-message.md
  concepts/toolkit/get-started/includes/building-one-productivity-hub-02-register-app.md
  concepts/whats-new-earlier.md
Labels: internal

#18469 What's new through 8/29/2022.
  concepts/whats-new-overview.md
Labels: do not merge, internal

#18472 Refreshed what's new topic through August.
  concepts/whats-new-overview.md
Labels: internal

#18489 [BrokenLinksH2] Update teamworkbot-get.md
  api-reference/v1.0/api/teamworkbot-get.md
Labels: external

#18488 [BrokenLinksH2] Update site-post-columns.md
  api-reference/v1.0/api/site-post-columns.md
Labels: external

#18492 Update educationassignmentdefaults-get.md
  api-reference/beta/api/educationassignmentdefaults-get.md
Labels: external

#18491 [BrokenLinksH2] Update teamworkhostedcontent-get.md
  api-reference/beta/api/teamworkhostedcontent-get.md
Labels: external

#18490 Edits in PR 18256
  api-reference/beta/api/devicemanagement-alertrecord-get.md
  api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md
  api-reference/beta/api/devicemanagement-alertrecord-list.md
  api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md
  api-reference/beta/api/devicemanagement-alertrule-get.md
  api-reference/beta/api/devicemanagement-alertrule-list.md
  api-reference/beta/api/devicemanagement-alertrule-post.md
  api-reference/beta/api/devicemanagement-alertrule-update.md
  api-reference/beta/resources/devicemanagement-alertimpact.md
  changelog/Microsoft.DeviceManagement.Monitoring.json
Labels: external

#18487 [BrokenLinksH2] Update search-query.md
  api-reference/v1.0/api/search-query.md
Labels: external

#18483 Edits in PR 18280
  api-reference/beta/toc.yml
  api-reference/v1.0/api/addlargegalleryviewoperation-get.md
  api-reference/v1.0/api/call-addlargegalleryview.md
  api-reference/v1.0/resources/addlargegalleryviewoperation.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.Skype.Calling.json
Labels: external

#18482 [BrokenLinksH2] Update searchrequest.md
  api-reference/v1.0/resources/searchrequest.md
Labels: external

#18477 Edits in PR 18119
  api-reference/beta/api/chat-list-pinnedmessages.md
  api-reference/beta/resources/chat.md
  api-reference/v1.0/api/chat-list-pinnedmessages.md
  api-reference/v1.0/resources/chat.md
  api-reference/v1.0/resources/pinnedchatmessageinfo.md
  changelog/Microsoft.Teams.Core.json
Labels: external

#18475 Update alert-update.md
  api-reference/beta/api/alert-update.md
Labels: external

#18476 Update alert-update.md
  api-reference/v1.0/api/alert-update.md
Labels: external

#17891 Adding a new menu for feedback resources page in toc.yml
  api-reference/beta/toc.yml
  concepts/education-upload-feedback-resource-overview.md
  concepts/toc.yml
Labels: ready to merge, internal, content review complete, schema live

#18203 update changelogs and fix text in resource.
  api-reference/beta/resources/chatmessage.md
  changelog/Microsoft.Teams.Core.json
Labels: ready to merge, internal, content review complete

#18389 updated the concept/permission-reference.md
  concepts/permissions-reference.md
Labels: ready to merge, internal

#18470 Minor doc fixes
  api-reference/beta/api/authenticationcontextclassreference-delete.md
  api-reference/beta/api/authenticationcontextclassreference-get.md
  api-reference/beta/api/authenticationcontextclassreference-update.md
  api-reference/beta/api/conditionalaccessroot-list-authenticationcontextclassreferences.md
  api-reference/beta/api/conditionalaccessroot-post-authenticationcontextclassreferences.md
  api-reference/beta/api/user-update.md
  api-reference/beta/resources/authenticationcontextclassreference.md
  api-reference/beta/resources/conditionalaccessclientapplications.md
  api-reference/beta/resources/conditionalaccessroot.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/user-update.md
  api-reference/v1.0/resources/conditionalaccessclientapplications.md
  api-reference/v1.0/resources/conditionalaccessroot.md
Labels: area: Azure AD, ready to merge, internal

#18471 Fix permission related to chat delete/undelete
  api-reference/beta/api/chatmessage-softdelete.md
  api-reference/beta/api/chatmessage-undosoftdelete.md
Labels: bug, ready to merge, internal

#18486 [BrokenLinksH2] Update teams-api-overview.md
  api-reference/beta/resources/teams-api-overview.md
  api-reference/v1.0/resources/teams-api-overview.md
Labels: external, ready to merge

#18503 Added what's new in September so far.
  api-reference/beta/api/driveitem-assignsensitivitylabel.md
  api-reference/beta/api/driveitem-extractsensitivitylabels.md
  changelog/Microsoft.FileServices.json
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: do not merge, internal

#18504 Refreshed what's new topic for September updates.
  api-reference/beta/api/driveitem-assignsensitivitylabel.md
  api-reference/beta/api/driveitem-extractsensitivitylabels.md
  changelog/Microsoft.FileServices.json
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: internal

#18515 [BrokenLinksH2] Update known-issues.md
  concepts/known-issues.md
Labels: external

#18513 Edits in PR 17997
  api-reference/beta/api/learningcontent-get.md
  api-reference/beta/api/learningcontent-update.md
  api-reference/beta/api/learningprovider-delete-learningcontents.md
  api-reference/beta/api/learningprovider-list-learningcontents.md
  api-reference/beta/resources/learningcontent.md
  changelog/Microsoft.Viva.Learning.json
Labels: external

#18509 Edits in PR 18134
  api-reference/beta/api/learningcontent-get.md
  api-reference/beta/api/learningcontent-update.md
  api-reference/beta/api/learningprovider-list-learningcontents.md
  api-reference/beta/resources/learningcontent.md
  changelog/Microsoft.Viva.Learning.json
Labels: external

#18512 [BrokenLinksH2] Update delta-query-groups.md
  concepts/delta-query-groups.md
Labels: external

#18493 Update author
  api-reference/beta/api/directoryobject-checkmemberobjects.md
  api-reference/beta/api/user-changepassword.md
  api-reference/beta/api/user-delete.md
  api-reference/beta/api/user-delta.md
  api-reference/beta/api/user-exportpersonaldata.md
  api-reference/beta/api/user-get.md
  api-reference/beta/api/user-invalidateallrefreshtokens.md
  api-reference/beta/api/user-list-createdobjects.md
  api-reference/beta/api/user-list-devices.md
  api-reference/beta/api/user-list-directreports.md
  api-reference/beta/api/user-list-manager.md
  api-reference/beta/api/user-list-memberof.md
  api-reference/beta/api/user-list-owneddevices.md
  api-reference/beta/api/user-list-ownedobjects.md
  api-reference/beta/api/user-list-registereddevices.md
  api-reference/beta/api/user-list-scopedrolememberof.md
  api-reference/beta/api/user-list-trendingaround.md
  api-reference/beta/api/user-list.md
  api-reference/beta/api/user-post-manager.md
  api-reference/beta/api/user-post-users.md
  api-reference/beta/api/user-reprocesslicenseassignment.md
  api-reference/beta/api/user-revokesigninsessions.md
  api-reference/beta/api/user-update.md
  api-reference/beta/api/usersettings-get.md
  api-reference/beta/api/usersettings-update.md
  api-reference/beta/resources/objectidentity.md
  api-reference/beta/resources/onpremisesextensionattributes.md
  api-reference/beta/resources/user.md
  api-reference/beta/resources/users.md
  api-reference/beta/resources/usersecuritystate.md
  api-reference/beta/resources/usersettings.md
  api-reference/v1.0/api/directoryobject-checkmemberobjects.md
  api-reference/v1.0/api/user-changepassword.md
  api-reference/v1.0/api/user-delete.md
  api-reference/v1.0/api/user-delta.md
  api-reference/v1.0/api/user-exportpersonaldata.md
  api-reference/v1.0/api/user-get.md
  api-reference/v1.0/api/user-list-createdobjects.md
  api-reference/v1.0/api/user-list-directreports.md
  api-reference/v1.0/api/user-list-manager.md
  api-reference/v1.0/api/user-list-owneddevices.md
  api-reference/v1.0/api/user-list-ownedobjects.md
  api-reference/v1.0/api/user-list-registereddevices.md
  api-reference/v1.0/api/user-list.md
  api-reference/v1.0/api/user-post-manager.md
  api-reference/v1.0/api/user-post-users.md
  api-reference/v1.0/api/user-reprocesslicenseassignment.md
  api-reference/v1.0/api/user-revokesigninsessions.md
  api-reference/v1.0/api/user-update.md
  api-reference/v1.0/api/usersettings-get.md
  api-reference/v1.0/api/usersettings-update.md
  api-reference/v1.0/resources/objectidentity.md
  api-reference/v1.0/resources/onpremisesextensionattributes.md
  api-reference/v1.0/resources/user.md
  api-reference/v1.0/resources/users.md
  api-reference/v1.0/resources/usersecuritystate.md
  api-reference/v1.0/resources/usersettings.md
Labels: area: Azure AD, ready to merge, internal, content review complete

#18502 Minor fix
  api-reference/beta/api/authenticationcontextclassreference-delete.md
  changelog/Microsoft.DirectoryServices.json
Labels: ready to merge, internal

#18178 adding synapse page
  concepts/data-connect-quickstart.yml
  concepts/images/azure-synapse-studio-tile.png
  concepts/images/data-connect-synapse-IR.png
  concepts/images/data-connect-synapse-accept-request.png
  concepts/images/data-connect-synapse-activity-run.png
  concepts/images/data-connect-synapse-azure.png
  concepts/images/data-connect-synapse-basic-dataset-choose.png
  concepts/images/data-connect-synapse-create.png
  concepts/images/data-connect-synapse-general.png
  concepts/images/data-connect-synapse-import-schema.png
  concepts/images/data-connect-synapse-integration-service.png
  concepts/images/data-connect-synapse-linked-service.png
  concepts/images/data-connect-synapse-locate-dataset.png
  concepts/images/data-connect-synapse-move-transform.png
  concepts/images/data-connect-synapse-new-linked-service.png
  concepts/images/data-connect-synapse-pipeline-runs.png
  concepts/images/data-connect-synapse-pipeline.png
  concepts/images/data-connect-synapse-service-id.png
  concepts/images/data-connect-synapse-set-properties.png
  concepts/images/data-connect-synapse-sink.png
  concepts/images/data-connect-synapse-storage.png
  concepts/images/data-connect-synapse-trigger.png
  concepts/images/data-connect-synapse-workspace.png
  includes/data-connect-quickstart-05.md
  includes/data-connect-quickstart-06.md
  includes/data-connect-quickstart-07.md
  includes/data-connect-quickstart-08.md
  includes/data-connect-quickstart-09.md
Labels: ready to merge, content review complete

#18525 Updated taxonomy values in JSON files.
  changelog/Microsoft.Skype.Calling.json
  changelog/Microsoft.Teams.Core.json
  changelog/Microsoft.Viva.Learning.json
Labels: ready to merge, internal

#18521 Fix HTTP URLs
  api-reference/v1.0/api/opentypeextension-delete.md
Labels: area: Azure AD, ready to merge, internal

#18495 Update security-api-overview.md
  api-reference/beta/resources/security-api-overview.md
  api-reference/v1.0/resources/security-api-overview.md
Labels: external, ready to merge

#18353 Live Event Captions promote to GA
  api-reference/v1.0/resources/broadcastmeetingcaptionsettings.md
  api-reference/v1.0/resources/broadcastmeetingsettings.md
  changelog/Microsoft.Skype.Calling.json
Labels: ready to merge, internal, content review complete

#16651 BULK VALIDATION fixes
  api-reference/beta/api/accesspackageassignmentpolicy-update.md
  api-reference/beta/api/accessreviewinstance-list-decisions.md
  api-reference/beta/api/accessreviewpolicy-update.md
  api-reference/beta/api/activities-list.md
  api-reference/beta/api/b2cidentityuserflow-put-apiconnectorconfiguration.md
  api-reference/beta/api/b2xidentityuserflow-put-apiconnectorconfiguration.md
  api-reference/beta/api/call-transfer.md
  api-reference/beta/api/channel-post-messages.md
  api-reference/beta/api/contactfolder-post-contacts.md
  api-reference/beta/api/driveitem-get.md
  api-reference/beta/api/driveitem-restore.md
  api-reference/beta/api/educationsubmission-get.md
  api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md
  api-reference/beta/api/filter-apply.md
  api-reference/beta/api/filter-clear.md
  api-reference/beta/api/formatprotection-get.md
  api-reference/beta/api/formatprotection-update.md
  api-reference/beta/api/get-device-command-status.md
  api-reference/beta/api/group-evaluatedynamicmembership.md
  api-reference/beta/api/group-list-members.md
  api-reference/beta/api/group-list-transitivemembers.md
  api-reference/beta/api/icon-get.md
  api-reference/beta/api/icon-update.md
  api-reference/beta/api/inferenceclassification-list-overrides.md
  api-reference/beta/api/inferenceclassification-post-overrides.md
  api-reference/beta/api/inferenceclassificationoverride-delete.md
  api-reference/beta/api/inferenceclassificationoverride-update.md
Labels: external, ready to merge

#18535 Update externalconnectors-externalitem-delete.md
  api-reference/beta/api/externalconnectors-externalitem-delete.md
Labels: external

#18543 Edits in PR 18256
  api-reference/beta/api/devicemanagement-alertrule-post.md
  api-reference/beta/resources/devicemanagement-alertrecord.md
  api-reference/beta/resources/devicemanagement-alertrule.md
  api-reference/beta/resources/devicemanagement-monitoring.md
  api-reference/beta/resources/devicemanagement-notificationchannel.md
  api-reference/beta/resources/devicemanagement-notificationreceiver.md
Labels: external

#18541 Update filter-query-parameter.md
  concepts/filter-query-parameter.md
Labels: ready to merge

#18533 Added the missing scopes in the v1.0 endpoint.
  api-reference/v1.0/resources/sharinglink.md
Labels: external

#18540 Update devicemanagement-alertimpact.md
  api-reference/beta/resources/devicemanagement-alertimpact.md
Labels: external

#18538 Add link to default user permissions
  api-reference/beta/resources/users.md
  api-reference/v1.0/resources/users.md
  concepts/toc.yml
Labels: area: Azure AD, ready to merge, internal

#18547 Updated list attendance record with one more example
  api-reference/beta/api/attendancerecord-list.md
  api-reference/beta/resources/attendancerecord.md
Labels: ready to merge, internal, content review complete

#18548 Merge to publish.
  api-reference/beta/api/attendancerecord-list.md
  api-reference/beta/api/externalconnectors-externalitem-delete.md
  api-reference/beta/resources/attendancerecord.md
  api-reference/beta/resources/users.md
  api-reference/v1.0/api/externalconnectors-externalitem-delete.md
  api-reference/v1.0/resources/sharinglink.md
  api-reference/v1.0/resources/users.md
  concepts/filter-query-parameter.md
  concepts/toc.yml
Labels: internal

#18557 Updated service values.
  changelog/Microsoft.IC3.DataPlatform.json
  changelog/Microsoft.Skype.Calling.json
Labels: do not merge, internal

#18559 Update termstore-list-groups.md
  api-reference/beta/api/termstore-list-groups.md
Labels: external

#18564 Add appropriate link to meetingParticipantInfo
  concepts/changenotifications-for-onlinemeeting.md
Labels: ready to merge, internal

#18563 Update chat-patch.md
  api-reference/beta/api/chat-patch.md
Labels: external
