Repository microsoftgraph/microsoft-graph-docs, pull requests merged in 2022-03, with the labels that each got.

#16015 Update plannertaskdetails.md
  api-reference/v1.0/resources/plannertaskdetails.md
Labels: external

#16014 Update plannertaskdetails.md
  api-reference/beta/resources/plannertaskdetails.md
Labels: external

#16002 Update team.md
  api-reference/beta/resources/team.md
  api-reference/v1.0/resources/team.md
Labels: external

#15418 Add restorePointSetting to cloudPcUserSetting
  api-reference/beta/api/cloudpcusersetting-get.md
  api-reference/beta/api/cloudpcusersetting-update.md
  api-reference/beta/api/virtualendpoint-list-usersettings.md
  api-reference/beta/api/virtualendpoint-post-usersettings.md
  api-reference/beta/resources/cloudpcrestorepointsetting.md
  api-reference/beta/resources/cloudpcusersetting.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, internal, content review complete

#15671 Add windows application properties
  api-reference/beta/api/application-get.md
  api-reference/beta/api/application-post-applications.md
  api-reference/beta/api/application-update.md
  api-reference/beta/resources/application.md
  api-reference/beta/resources/windowsapplication.md
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, external, ready to merge, content review complete

#13343 adding search admin answers
  api-reference/beta/api/search-acronym-delete.md
  api-reference/beta/api/search-acronym-get.md
  api-reference/beta/api/search-acronym-update.md
  api-reference/beta/api/search-bookmark-delete.md
  api-reference/beta/api/search-bookmark-get.md
  api-reference/beta/api/search-bookmark-update.md
  api-reference/beta/api/search-qna-delete.md
  api-reference/beta/api/search-qna-get.md
  api-reference/beta/api/search-qna-update.md
  api-reference/beta/api/search-searchentity-list-acronyms.md
  api-reference/beta/api/search-searchentity-list-bookmarks.md
  api-reference/beta/api/search-searchentity-list-qnas.md
  api-reference/beta/api/search-searchentity-post-acronyms.md
  api-reference/beta/api/search-searchentity-post-bookmarks.md
  api-reference/beta/api/search-searchentity-post-qnas.md
  api-reference/beta/resources/enums-search.md
  api-reference/beta/resources/search-acronym.md
  api-reference/beta/resources/search-answerkeyword.md
  api-reference/beta/resources/search-answervariant.md
  api-reference/beta/resources/search-api-answers-overview.md
  api-reference/beta/resources/search-bookmark.md
  api-reference/beta/resources/search-qna.md
  api-reference/beta/resources/search-searchanswer.md
  api-reference/beta/resources/searchentity.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Search.Admin.json
  concepts/permissions-reference.md
  concepts/search-concept-answers.md
  concepts/search-concept-display-layout.md
  concepts/search-concept-overview.md
  concepts/toc.yml
Labels: ready to merge, internal, content review complete, schema live

#15556 [CloudPC]Add restore and bulkRestore API
  api-reference/beta/api/manageddevice-bulkrestorecloudpc.md
  api-reference/beta/api/manageddevice-restorecloudpc.md
  api-reference/beta/resources/cloudpc.md
  api-reference/beta/resources/cloudpcbulkremoteactionresult.md
  api-reference/beta/resources/cloudpcremoteactionresult.md
  api-reference/beta/toc.yml
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, internal, content review complete, schema live

#16016 Merge to publish.
  api-reference/beta/api/application-get.md
  api-reference/beta/api/application-post-applications.md
  api-reference/beta/api/application-update.md
  api-reference/beta/api/cloudpcusersetting-get.md
  api-reference/beta/api/cloudpcusersetting-update.md
  api-reference/beta/api/manageddevice-bulkrestorecloudpc.md
  api-reference/beta/api/manageddevice-restorecloudpc.md
  api-reference/beta/api/search-acronym-delete.md
  api-reference/beta/api/search-acronym-get.md
  api-reference/beta/api/search-acronym-update.md
  api-reference/beta/api/search-bookmark-delete.md
  api-reference/beta/api/search-bookmark-get.md
  api-reference/beta/api/search-bookmark-update.md
  api-reference/beta/api/search-qna-delete.md
  api-reference/beta/api/search-qna-get.md
  api-reference/beta/api/search-qna-update.md
  api-reference/beta/api/search-searchentity-list-acronyms.md
  api-reference/beta/api/search-searchentity-list-bookmarks.md
  api-reference/beta/api/search-searchentity-list-qnas.md
  api-reference/beta/api/search-searchentity-post-acronyms.md
  api-reference/beta/api/search-searchentity-post-bookmarks.md
  api-reference/beta/api/search-searchentity-post-qnas.md
  api-reference/beta/api/virtualendpoint-list-usersettings.md
  api-reference/beta/api/virtualendpoint-post-usersettings.md
  api-reference/beta/resources/application.md
  api-reference/beta/resources/cloudpc.md
  api-reference/beta/resources/cloudpcbulkremoteactionresult.md
  api-reference/beta/resources/cloudpcremoteactionresult.md
  api-reference/beta/resources/cloudpcrestorepointsetting.md
  api-reference/beta/resources/cloudpcusersetting.md
  api-reference/beta/resources/enums-search.md
  api-reference/beta/resources/plannertaskdetails.md
  api-reference/beta/resources/search-acronym.md
  api-reference/beta/resources/search-answerkeyword.md
  api-reference/beta/resources/search-answervariant.md
  api-reference/beta/resources/search-api-answers-overview.md
  api-reference/beta/resources/search-bookmark.md
  api-reference/beta/resources/search-qna.md
  api-reference/beta/resources/search-searchanswer.md
  api-reference/beta/resources/searchentity.md
  api-reference/beta/resources/team.md
  api-reference/beta/resources/windowsapplication.md
  api-reference/beta/toc.yml
  api-reference/v1.0/resources/plannertaskdetails.md
  api-reference/v1.0/resources/team.md
  changelog/Microsoft.CloudManagedDesktop.json
  changelog/Microsoft.DirectoryServices.json
  changelog/Microsoft.Search.Admin.json
  concepts/permissions-reference.md
  concepts/search-concept-answers.md
  concepts/search-concept-display-layout.md
  concepts/search-concept-overview.md
  concepts/toc.yml
Labels: internal

#16019 Fix date in Microsoft.CloudManagedDesktop.json
  changelog/Microsoft.CloudManagedDesktop.json
Labels: internal

#16029 Update itemanalytics-get.md
  api-reference/v1.0/api/itemanalytics-get.md
Labels: external

#16028 Update itemanalytics-get.md
  api-reference/beta/api/itemanalytics-get.md
Labels: external

#15650 App policy custom password block
  api-reference/beta/api/tenantappmanagementpolicy-update.md
  api-reference/beta/resources/applicationauthenticationmethodpolicy.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/passwordcredentialconfiguration.md
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, ready to merge, internal, content review complete

#16006 Minor doc fixes
  api-reference/beta/api/directorysetting-delete.md
  api-reference/beta/api/directorysetting-get.md
  api-reference/beta/api/directorysetting-post-settings.md
  api-reference/beta/api/directorysetting-update.md
  api-reference/beta/api/group-list-settings.md
  api-reference/beta/api/group-list.md
  api-reference/beta/api/group-post-settings.md
  api-reference/beta/resources/assignedplan.md
  api-reference/beta/resources/changenotification.md
  api-reference/beta/resources/changenotificationcollection.md
  api-reference/beta/resources/changenotificationencryptedcontent.md
  api-reference/beta/resources/directorysetting.md
  api-reference/beta/resources/directorysettingtemplate.md
  api-reference/beta/resources/group.md
  api-reference/beta/resources/resourcedata.md
  api-reference/beta/resources/subscription.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/group-list-settings.md
  api-reference/v1.0/api/group-list.md
  api-reference/v1.0/api/group-post-settings.md
  api-reference/v1.0/api/groupsetting-delete.md
  api-reference/v1.0/api/groupsetting-get.md
  api-reference/v1.0/api/groupsetting-update.md
  api-reference/v1.0/resources/assignedplan.md
  api-reference/v1.0/resources/changenotification.md
  api-reference/v1.0/resources/changenotificationcollection.md
  api-reference/v1.0/resources/changenotificationencryptedcontent.md
  api-reference/v1.0/resources/group.md
  api-reference/v1.0/resources/groupsetting.md
  api-reference/v1.0/resources/groupsettingtemplate.md
  api-reference/v1.0/resources/resourcedata.md
  api-reference/v1.0/resources/subscription.md
  api-reference/v1.0/toc.yml
  redirects/.openpublishing.redirection.1221.json
Labels: area: Azure AD, ready to merge, internal

#15999 Typo "**[listItem][]**"→"listItem"
  api-reference/v1.0/api/listitem-update.md
Labels: external

#15984 Add documentation for people-picker user-ids property
  concepts/toolkit/components/people-picker.md
Labels: external

#15951 adding precision related to refinable properties
  concepts/connecting-external-content-manage-schema.md
Labels: external

#16045 Update whats-new-overview.md
  concepts/whats-new-overview.md
Labels: external

#16044 Update itemactivity-getbyinterval.md
  api-reference/beta/api/itemactivity-getbyinterval.md
Labels: external

#16048 Remove June 30, 2022
  concepts/migrate-azure-ad-graph-faq.md
Labels: internal

#16049 Remove June 30 2022 date
  concepts/migrate-azure-ad-graph-configure-permissions.md
Labels: internal

#14283 Tutorial: access review of assignments to privileged roles
  concepts/images/tutorial-accessreviews-api/settings.png
  concepts/toc.yml
  concepts/tutorial-accessreviews-roleassignments.md
  concepts/tutorial-accessreviews-securitygroup.md
  concepts/tutorial-assign-azureadroles.md
Labels: area: Azure AD, ready to merge, internal

#15110 Updates to authentication and authorization basics article
  concepts/auth-limit-mailbox-access.md
  concepts/auth-v2-service.md
  concepts/auth-v2-user.md
  concepts/auth/auth-concepts.md
  concepts/best-practices-concept.md
  concepts/images/auth-v2/admin-consent.png
  concepts/images/auth-v2/v2-application-permissions.png
  concepts/images/auth-v2/v2-consumer-consent-old.png
  concepts/images/auth-v2/v2-consumer-consent.png
  concepts/images/auth-v2/v2-delegated-permissions.png
  concepts/images/auth-v2/v2-service-registration.png
  concepts/images/auth-v2/v2-web-registration.png
  concepts/permissions-reference.md
Labels: area: authentication, area: Azure AD, ready to merge, internal, area: permissions

#15308 [Doc issue][Update guest member permissions]
  api-reference/beta/api/team-post-members.md
  api-reference/v1.0/api/team-post-members.md
Labels: ready to merge, content review complete

#16032 [Doc Improvement][Update guest member role limitations]
  api-reference/beta/api/team-update-members.md
  api-reference/v1.0/api/team-update-members.md
Labels: ready to merge, changes requested, content review complete

#16041 Update user.md
  api-reference/beta/resources/user.md
Labels: area: Azure AD, ready to merge, internal

#15392 Adding ContactMergeSuggestion User Privacy setting to contact merge suggestion feature
  api-reference/beta/api/contactmergesuggestions-get.md
  api-reference/beta/api/contactmergesuggestions-update.md
  api-reference/beta/resources/contactmergesuggestions.md
  api-reference/beta/resources/usersettings.md
  api-reference/beta/toc.yml
  changelog/Microsoft.People.json
Labels: ready to merge, internal, content review complete, schema live

#16059 Update approleassignment.md
  api-reference/beta/resources/approleassignment.md
Labels: external

#16058 Update approleassignment.md
  api-reference/v1.0/resources/approleassignment.md
Labels: external

#14309 Correcting expirationDate property description
  api-reference/beta/resources/educationsynchronizationprofile.md
Labels: area: education, bug: documentation, ready to merge, internal, content review complete

#16036 Minor doc fixes
  api-reference/beta/api/application-list-extensionproperty.md
  api-reference/beta/api/application-post-extensionproperty.md
  api-reference/beta/api/extensionproperty-delete.md
  api-reference/beta/api/extensionproperty-get.md
  api-reference/beta/api/synchronization-synchronization-secrets.md
  api-reference/beta/resources/application.md
  api-reference/beta/resources/authenticationmethodconfiguration.md
  api-reference/beta/resources/directoryobject.md
  api-reference/beta/resources/extensionproperty.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/application-list-extensionproperty.md
  api-reference/v1.0/api/application-post-extensionproperty.md
  api-reference/v1.0/api/directoryobject-getavailableextensionproperties.md
  api-reference/v1.0/api/extensionproperty-delete.md
  api-reference/v1.0/api/extensionproperty-get.md
  api-reference/v1.0/resources/application.md
  api-reference/v1.0/resources/directoryobject.md
  api-reference/v1.0/resources/extensionproperty.md
  api-reference/v1.0/toc.yml
  concepts/toc.yml
  redirects/.openpublishing.redirection.1221.json
Labels: area: Azure AD, ready to merge, internal

#16055 Fixed shift-put.md
  api-reference/v1.0/api/shift-put.md
  api-reference/v1.0/includes/snippets/csharp/shift-put-csharp-snippets.md
Labels: external, ready to merge

#15241 Graph Explorer v4 issue 1310
  api-reference/beta/api/driveitem-get-content.md
  api-reference/v1.0/api/driveitem-get-content.md
Labels: ready to merge, internal, review feedback addressed

#16046 Add documentation for mgt-person disableImageFetch property
  concepts/toolkit/components/person.md
Labels: external, ready to merge

#16056 Update hybrid-rest-support.md
  concepts/hybrid-rest-support.md
  concepts/toc.yml
Labels: external, ready to merge, content review complete

#16057 EM: update case in filter used in role assignment query
  api-reference/beta/api/rbacapplication-list-roleassignments.md
Labels: area: Azure AD, ready to merge, internal, content review complete

#16066 Minor refresh to AR tutorial for guest users
  concepts/toc.yml
  concepts/tutorial-accessreviews-M365group.md
Labels: area: Azure AD, ready to merge

#16070 Updating ownership of files
  api-reference/beta/api/chat-list-members.md
  api-reference/beta/api/chat-patch.md
  api-reference/beta/api/chat-post-members.md
  api-reference/beta/api/schedule-get.md
  api-reference/beta/api/schedule-list-schedulinggroups.md
  api-reference/beta/api/schedule-list-shifts.md
  api-reference/beta/api/schedule-list-timeoffreasons.md
  api-reference/beta/api/schedule-list-timesoff.md
  api-reference/beta/api/schedule-post-schedulinggroups.md
  api-reference/beta/api/schedule-post-shifts.md
  api-reference/beta/api/schedule-post-timeoffreasons.md
  api-reference/beta/api/schedule-post-timesoff.md
  api-reference/beta/api/schedule-share.md
  api-reference/beta/api/schedulinggroup-delete.md
  api-reference/beta/api/schedulinggroup-get.md
  api-reference/beta/api/schedulinggroup-put.md
  api-reference/beta/api/shift-delete.md
  api-reference/beta/api/shift-put.md
  api-reference/beta/api/timeoff-delete.md
  api-reference/beta/api/timeoff-get.md
  api-reference/beta/api/timeoff-put.md
  api-reference/beta/api/timeoffreason-get.md
  api-reference/beta/api/timeoffreason-put.md
  api-reference/beta/resources/channelmoderationsettings.md
  api-reference/beta/resources/schedule.md
  api-reference/beta/resources/schedulinggroup.md
  api-reference/beta/resources/shift.md
  api-reference/beta/resources/shiftactivity.md
  api-reference/beta/resources/shiftitem.md
  api-reference/beta/resources/timeoff.md
  api-reference/beta/resources/timeoffitem.md
  api-reference/beta/resources/timeoffreason.md
  api-reference/v1.0/api/chat-get-members.md
  api-reference/v1.0/api/chat-list-members.md
  api-reference/v1.0/api/chat-patch.md
  api-reference/v1.0/api/chat-post-members.md
  api-reference/v1.0/resources/shiftactivity.md
  api-reference/v1.0/resources/shiftitem.md
Labels: ready to merge, internal

#15598 Adding audit event to M365 Lighthouse
  api-reference/beta/api/managedtenants-auditevent-get.md
  api-reference/beta/api/managedtenants-managedtenant-list-auditevents.md
  api-reference/beta/resources/managedtenants-auditevent.md
  api-reference/beta/resources/managedtenants-managedtenant.md
  api-reference/beta/toc.yml
  changelog/Microsoft.MultiTenantPlatform.json
Labels: ready to merge, internal, content review complete, area: multi-tenant management

#16071 Document example POST accessPackageAssignmentPolicy with custom extension workflow
  api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md
Labels: area: Azure AD, ready to merge, internal

#16072 Update Azure AD Graph deprecation date - not June 30
  concepts/migrate-azure-ad-graph-configure-permissions.md
  concepts/migrate-azure-ad-graph-overview.md
Labels: area: Azure AD, ready to merge, internal

#16073 Fixes #16069 - preAuthorizedApplication in v1.0 vs beta API
  api-reference/v1.0/resources/preauthorizedapplication.md
Labels: area: Azure AD, ready to merge, internal

#16079 Merge to publish.
  api-reference/beta/api/chat-list-members.md
  api-reference/beta/api/chat-patch.md
  api-reference/beta/api/chat-post-members.md
  api-reference/beta/api/driveitem-get-content.md
  api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md
  api-reference/beta/api/managedtenants-auditevent-get.md
  api-reference/beta/api/managedtenants-managedtenant-list-auditevents.md
  api-reference/beta/api/rbacapplication-list-roleassignments.md
  api-reference/beta/api/schedule-get.md
  api-reference/beta/api/schedule-list-schedulinggroups.md
  api-reference/beta/api/schedule-list-shifts.md
  api-reference/beta/api/schedule-list-timeoffreasons.md
  api-reference/beta/api/schedule-list-timesoff.md
  api-reference/beta/api/schedule-post-schedulinggroups.md
  api-reference/beta/api/schedule-post-shifts.md
  api-reference/beta/api/schedule-post-timeoffreasons.md
  api-reference/beta/api/schedule-post-timesoff.md
  api-reference/beta/api/schedule-share.md
  api-reference/beta/api/schedulinggroup-delete.md
  api-reference/beta/api/schedulinggroup-get.md
  api-reference/beta/api/schedulinggroup-put.md
  api-reference/beta/api/shift-delete.md
  api-reference/beta/api/shift-put.md
  api-reference/beta/api/timeoff-delete.md
  api-reference/beta/api/timeoff-get.md
  api-reference/beta/api/timeoff-put.md
  api-reference/beta/api/timeoffreason-get.md
  api-reference/beta/api/timeoffreason-put.md
  api-reference/beta/resources/channelmoderationsettings.md
  api-reference/beta/resources/managedtenants-auditevent.md
  api-reference/beta/resources/managedtenants-managedtenant.md
  api-reference/beta/resources/schedule.md
  api-reference/beta/resources/schedulinggroup.md
  api-reference/beta/resources/shift.md
  api-reference/beta/resources/shiftactivity.md
  api-reference/beta/resources/shiftitem.md
  api-reference/beta/resources/timeoff.md
  api-reference/beta/resources/timeoffitem.md
  api-reference/beta/resources/timeoffreason.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/chat-get-members.md
  api-reference/v1.0/api/chat-list-members.md
  api-reference/v1.0/api/chat-patch.md
  api-reference/v1.0/api/chat-post-members.md
  api-reference/v1.0/api/driveitem-get-content.md
  api-reference/v1.0/resources/preauthorizedapplication.md
  api-reference/v1.0/resources/shiftactivity.md
  api-reference/v1.0/resources/shiftitem.md
  changelog/Microsoft.MultiTenantPlatform.json
  concepts/hybrid-rest-support.md
  concepts/migrate-azure-ad-graph-configure-permissions.md
  concepts/migrate-azure-ad-graph-overview.md
  concepts/toc.yml
  concepts/toolkit/components/person.md
  concepts/tutorial-accessreviews-M365group.md
Labels: internal

#16082 Update subscription-delete.md
  api-reference/beta/api/subscription-delete.md
Labels: external

#16081 Update subscription-delete.md
  api-reference/v1.0/api/subscription-delete.md
Labels: external

#16085 FIX: Url + Extra step
  concepts/use-postman.md
Labels: external, ready to merge

#16090 Change Devices and apps to Device and app management.
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
  concepts/toc.yml
Labels: ready to merge, internal

#15781 Kwekua bookings 1 31 11
  api-reference/beta/api/bookingappointment-update.md
  api-reference/beta/api/bookingbusiness-post-appointments.md
  api-reference/beta/resources/bookingappointment.md
  api-reference/beta/resources/bookingservice.md
  api-reference/v1.0/api/bookingappointment-update.md
  api-reference/v1.0/api/bookingbusiness-post-appointments.md
  api-reference/v1.0/resources/bookingappointment.md
  api-reference/v1.0/resources/bookingservice.md
Labels: ready to merge, internal, review feedback addressed

#15177 Wi rawlin work documentation for context state
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/plannerplancontextdetails.md
  changelog/Microsoft.Office.Tasks.json
Labels: external, ready to merge, content review complete

#15856 Adding resourceSpecificApplicationPermissions to servicePrincipal in v1.0
  api-reference/v1.0/api/serviceprincipal-get.md
  api-reference/v1.0/resources/resourcespecificpermission.md
  api-reference/v1.0/resources/serviceprincipal.md
  changelog/Microsoft.DirectoryServices.json
Labels: ready to merge, internal, content review complete

#15727 Add onlinemeeting subscription documentation
  api-reference/beta/api/subscription-delete.md
  api-reference/beta/api/subscription-get.md
  api-reference/beta/api/subscription-list.md
  api-reference/beta/api/subscription-post-subscriptions.md
  api-reference/beta/api/subscription-update.md
  api-reference/beta/resources/onlinemeeting.md
  api-reference/beta/resources/subscription.md
  api-reference/beta/resources/webhooks.md
  concepts/changenotifications-for-onlinemeeting.md
  concepts/toc.yml
  concepts/webhooks-with-resource-data.md
  concepts/webhooks.md
Labels: ready to merge, content review complete

#16105 Added missing permissions table to OneDrive APIs
  api-reference/beta/api/driveitem-get-content-format.md
  api-reference/v1.0/api/driveitem-get-content-format.md
Labels: ready to merge, internal, missing-permissions

#16114 Update subjectrightsrequest-getfinalattachment.md
  api-reference/v1.0/api/subjectrightsrequest-getfinalattachment.md
Labels: external

#16113 Update itemanalytics-get.md
  api-reference/v1.0/api/itemanalytics-get.md
Labels: external

#16112 Update itemanalytics-get.md
  api-reference/beta/api/itemanalytics-get.md
Labels: external

#16111 Update list-list.md
  api-reference/v1.0/api/list-list.md
Labels: external

#16110 Update list-list.md
  api-reference/beta/api/list-list.md
Labels: external

#16063 Use Graph Query to retrieve Service Principal added as members in Azu…
  api-reference/beta/api/group-list-members.md
Labels: area: Azure AD, external, ready to merge, content review complete

#16074 Document all permissions GUIDs
  concepts/permissions-reference.md
Labels: area: Azure AD, ready to merge, internal, area: permissions

#16076 Update itemanalytics-get.md
  api-reference/v1.0/api/itemanalytics-get.md
Labels: external, ready to merge, review requested, ready for content review

#16083 Minor doc fixes
  api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md
  concepts/accessreviews-scope-concept.md
Labels: area: Azure AD, ready to merge, internal

#16088 fix unified role management resource link for EM
  api-reference/v1.0/resources/rbacapplication.md
  api-reference/v1.0/resources/rolemanagement.md
Labels: area: Azure AD, ready to merge, internal, content review complete

#16106 Removed topics for non-existent APIs
  api-reference/beta/api/orgcontact-delete.md
  api-reference/beta/api/orgcontact-post-directreports.md
  api-reference/beta/api/orgcontact-post-memberof.md
  api-reference/beta/api/orgcontact-update.md
Labels: area: Azure AD, ready to merge, internal

#16108 Add missing documentation for online meeting sub/pub
  api-reference/beta/api/subscription-delete.md
  api-reference/beta/api/subscription-get.md
  api-reference/beta/api/subscription-post-subscriptions.md
  api-reference/beta/api/subscription-update.md
  api-reference/beta/resources/subscription.md
Labels: ready to merge, ready for content review

#16115 Address feedback from Laura - move GUIDs table to last
  concepts/permissions-reference.md
Labels: ready to merge, internal, area: permissions

#15132 Exposing Entitlement Management access package assignment approvals in v1.0
  api-reference/v1.0/api/approval-filterbycurrentuser.md
  api-reference/v1.0/api/approval-get.md
  api-reference/v1.0/api/approval-list-stages.md
  api-reference/v1.0/api/approvalstage-get.md
  api-reference/v1.0/api/approvalstage-update.md
  api-reference/v1.0/resources/approval.md
  api-reference/v1.0/resources/approvalstage.md
  api-reference/v1.0/resources/entitlementmanagement-overview.md
  api-reference/v1.0/resources/entitlementmanagement.md
  api-reference/v1.0/resources/enums.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.IGAELM.json
Labels: area: Azure AD, ready to merge, changes requested, internal, content review complete, schema live

#16126 Update site-list-subsites.md
  api-reference/beta/api/site-list-subsites.md
Labels: external

#16125 Update site-list-subsites.md
  api-reference/v1.0/api/site-list-subsites.md
Labels: external

#16068 Minor doc fixes
  api-reference/beta/api/agreement-delete.md
  api-reference/beta/api/agreement-get.md
  api-reference/beta/api/agreement-list-acceptances.md
  api-reference/beta/api/agreement-list-files.md
  api-reference/beta/api/agreement-post-files.md
  api-reference/beta/api/agreement-update.md
  api-reference/beta/api/agreementfile-get.md
  api-reference/beta/api/termsofusecontainer-list-agreements.md
  api-reference/beta/api/termsofusecontainer-post-agreements.md
  api-reference/beta/api/user-list-agreementacceptances.md
  api-reference/beta/resources/agreement.md
  api-reference/beta/resources/agreementacceptance.md
  api-reference/beta/resources/agreementfile.md
  api-reference/beta/resources/agreementfiledata.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/agreement-delete.md
  api-reference/v1.0/api/agreement-get.md
  api-reference/v1.0/api/agreement-list-acceptances.md
  api-reference/v1.0/api/agreement-list-files.md
  api-reference/v1.0/api/agreement-post-files.md
  api-reference/v1.0/api/agreement-update.md
  api-reference/v1.0/api/agreementfile-get.md
  api-reference/v1.0/api/termsofusecontainer-list-agreements.md
  api-reference/v1.0/api/termsofusecontainer-post-agreements.md
  api-reference/v1.0/api/user-list-agreementacceptances.md
  api-reference/v1.0/resources/agreement.md
  api-reference/v1.0/resources/agreementacceptance.md
  api-reference/v1.0/resources/agreementfiledata.md
  api-reference/v1.0/toc.yml
Labels: area: Azure AD, ready to merge

#16107 Jupetter usersettings
  api-reference/beta/resources/usersettings.md
  api-reference/v1.0/resources/usersettings.md
Labels: area: Azure AD, ready to merge, internal

#16130 Merge to publish.
  api-reference/beta/api/agreement-delete.md
  api-reference/beta/api/agreement-get.md
  api-reference/beta/api/agreement-list-acceptances.md
  api-reference/beta/api/agreement-list-files.md
  api-reference/beta/api/agreement-post-files.md
  api-reference/beta/api/agreement-update.md
  api-reference/beta/api/agreementfile-get.md
  api-reference/beta/api/site-list-subsites.md
  api-reference/beta/api/termsofusecontainer-list-agreements.md
  api-reference/beta/api/termsofusecontainer-post-agreements.md
  api-reference/beta/api/user-list-agreementacceptances.md
  api-reference/beta/resources/agreement.md
  api-reference/beta/resources/agreementacceptance.md
  api-reference/beta/resources/agreementfile.md
  api-reference/beta/resources/agreementfiledata.md
  api-reference/beta/resources/usersettings.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/agreement-delete.md
  api-reference/v1.0/api/agreement-get.md
  api-reference/v1.0/api/agreement-list-acceptances.md
  api-reference/v1.0/api/agreement-list-files.md
  api-reference/v1.0/api/agreement-post-files.md
  api-reference/v1.0/api/agreement-update.md
  api-reference/v1.0/api/agreementfile-get.md
  api-reference/v1.0/api/site-list-subsites.md
  api-reference/v1.0/api/termsofusecontainer-list-agreements.md
  api-reference/v1.0/api/termsofusecontainer-post-agreements.md
  api-reference/v1.0/api/user-list-agreementacceptances.md
  api-reference/v1.0/resources/agreement.md
  api-reference/v1.0/resources/agreementacceptance.md
  api-reference/v1.0/resources/agreementfiledata.md
  api-reference/v1.0/resources/usersettings.md
  api-reference/v1.0/toc.yml
Labels: internal

#16142 Update user-delete.md
  api-reference/v1.0/api/user-delete.md
Labels: external

#16141 Update user-delete.md
  api-reference/beta/api/user-delete.md
Labels: external

#16018 Support Sort For Connector
  concepts/search-concept-sort.md
Labels: ready to merge, internal, content review complete

#15891 Tasks API updates in property names
  api-reference/beta/api/basetask-get.md
  api-reference/beta/api/basetask-update.md
  api-reference/beta/api/basetasklist-list-tasks.md
  api-reference/beta/api/basetasklist-post-tasks.md
  api-reference/beta/api/tasklist-update.md
  api-reference/beta/api/tasks-post-lists.md
  api-reference/beta/resources/basetask.md
  api-reference/beta/resources/checklistitem.md
  api-reference/beta/resources/task.md
  api-reference/beta/resources/tasks-overview.md
  api-reference/beta/resources/taskviewpoint.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Tasks.json
Labels: ready to merge, internal, content review complete, schema live

#16143 Reword and include online meetings to create subscriptions text
  api-reference/beta/api/subscription-post-subscriptions.md
Labels: ready to merge, ready for content review, internal

#15993 Remove extraneous "Device management" items in TOC
  api-reference/v1.0/toc.yml
Labels: external, area: intune, ready to merge

#16152 - removes -u switch for go package installation
  concepts/sdks/sdk-installation.md
Labels: ready to merge, area: sample code, internal, area: SDKs

#16151 Remove extra http tab header
  api-reference/v1.0/api/accessreviewset-post-historydefinitions.md
Labels: do not merge, internal

#16156 Merge to publish.
  api-reference/v1.0/api/accessreviewset-post-historydefinitions.md
  api-reference/v1.0/toc.yml
  concepts/sdks/sdk-installation.md
Labels: internal

#16164 Fix TOC entry.
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
Labels: internal

#16169 Update insightssettings.md
  api-reference/beta/resources/insightssettings.md
Labels: external

#16159 typo fix
  concepts/powershell/installation.md
Labels: external

#16157 Update change-notifications-delivery.md: Fix typo
  concepts/change-notifications-delivery.md
Labels: external

#15810 Support MembershipSummary changes in TGS
  api-reference/beta/api/team-get.md
  api-reference/beta/resources/team.md
  api-reference/beta/resources/teamsummary.md
  changelog/Microsoft.Teams.Core.json
Labels: ready to merge, internal, content review complete

#16161 Update people.md
  concepts/toolkit/components/people.md
Labels: ready to merge, internal

#16170 Fix example issue
  api-reference/beta/api/cloudpcusersetting-update.md
Labels: ready to merge, internal, schema live

#16017 Add support for RoleManagement.Read.CloudPC & RoleManagement.ReadWrite.CloudPC permission
  api-reference/beta/api/rbacapplication-list-roledefinitions.md
  api-reference/beta/api/rbacapplication-post-roledefinitions.md
  api-reference/beta/api/unifiedroledefinition-delete.md
  api-reference/beta/api/unifiedroledefinition-get.md
  api-reference/beta/api/unifiedroledefinition-update.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, internal, content review complete

#16171 Merge to publish.
  api-reference/beta/api/cloudpcusersetting-update.md
  api-reference/beta/api/rbacapplication-list-roledefinitions.md
  api-reference/beta/api/rbacapplication-post-roledefinitions.md
  api-reference/beta/api/team-get.md
  api-reference/beta/api/unifiedroledefinition-delete.md
  api-reference/beta/api/unifiedroledefinition-get.md
  api-reference/beta/api/unifiedroledefinition-update.md
  api-reference/beta/resources/insightssettings.md
  api-reference/beta/resources/team.md
  api-reference/beta/resources/teamsummary.md
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
  changelog/Microsoft.CloudManagedDesktop.json
  changelog/Microsoft.Teams.Core.json
  concepts/change-notifications-delivery.md
  concepts/powershell/installation.md
  concepts/toolkit/components/people.md
Labels: internal

#16165 Jupetter transitivememberof
  api-reference/beta/api/user-list-transitivememberof.md
  api-reference/v1.0/api/user-list-transitivememberof.md
Labels: area: Azure AD, ready to merge, internal

#16168 Adding Note to provide context for property values.
  api-reference/v1.0/api/educationuser-list-assignments.md
Labels: ready to merge, internal, content review complete, schema live

#16177 Various doc fixes
  api-reference/beta/api/extensionproperty-delete.md
  api-reference/v1.0/api/extensionproperty-delete.md
Labels: area: Azure AD, ready to merge, internal

#16178 Update teams-protected-apis.md
  concepts/teams-protected-apis.md
Labels: external, ready to merge

#16039 Added first EWS migration docs
  concepts/migrate-exchange-web-services-api-mapping.md
  concepts/migrate-exchange-web-services-authentication.md
  concepts/migrate-exchange-web-services-overview.md
  concepts/toc.yml
Labels: ready to merge, internal, content review complete, review feedback addressed

#16180 Update listitem-list.md
  api-reference/beta/api/listitem-list.md
Labels: external

#16197 Update contentType.md
  api-reference/beta/resources/contentType.md
Labels: external

#16196 Update contentType.md
  api-reference/v1.0/resources/contentType.md
Labels: external

#16012 Assignment States Update - Diagram and Table
  concepts/assignments-submissions-states-transition.md
  concepts/images/states-transitions/diagram-assignments.PNG
Labels: ready to merge, internal, content review complete, schema live

#16179 Update listitem-list.md
  api-reference/v1.0/api/listitem-list.md
Labels: external

#13177 Publish bundles to v1.0 and fix doc consistency between beta and v1.0
  api-reference/beta/resources/drive.md
  api-reference/beta/resources/driveitem.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/bundle-additem.md
  api-reference/v1.0/api/bundle-delete.md
  api-reference/v1.0/api/bundle-get.md
  api-reference/v1.0/api/bundle-list.md
  api-reference/v1.0/api/bundle-removeitem.md
  api-reference/v1.0/api/bundle-update.md
  api-reference/v1.0/api/drive-post-bundles.md
  api-reference/v1.0/resources/album.md
  api-reference/v1.0/resources/bundle.md
  api-reference/v1.0/resources/drive.md
  api-reference/v1.0/resources/driveitem.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.FileServices.json
Labels: ready to merge, changes requested, internal, content review in progress

#16192 update to use new iterator api
  concepts/sdks/paging.md
Labels: external, ready to merge, area: sample code, area: SDKs

#16031 Update description externalItemContent type
  api-reference/beta/resources/externalconnectors-externalitemcontent.md
  api-reference/v1.0/resources/externalconnectors-externalitemcontent.md
  concepts/connecting-external-content-manage-items.md
Labels: ready to merge, internal

#16198 Merge to publish.
  api-reference/beta/resources/contentType.md
  api-reference/beta/resources/drive.md
  api-reference/beta/resources/driveitem.md
  api-reference/beta/resources/externalconnectors-externalitemcontent.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/bundle-additem.md
  api-reference/v1.0/api/bundle-delete.md
  api-reference/v1.0/api/bundle-get.md
  api-reference/v1.0/api/bundle-list.md
  api-reference/v1.0/api/bundle-removeitem.md
  api-reference/v1.0/api/bundle-update.md
  api-reference/v1.0/api/drive-post-bundles.md
  api-reference/v1.0/api/listitem-list.md
  api-reference/v1.0/resources/album.md
  api-reference/v1.0/resources/bundle.md
  api-reference/v1.0/resources/contentType.md
  api-reference/v1.0/resources/drive.md
  api-reference/v1.0/resources/driveitem.md
  api-reference/v1.0/resources/externalconnectors-externalitemcontent.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.FileServices.json
  concepts/assignments-submissions-states-transition.md
  concepts/connecting-external-content-manage-items.md
  concepts/images/states-transitions/diagram-assignments.PNG
  concepts/sdks/paging.md
Labels: do not merge, internal

#16215 Add a clause about supported service plans
  concepts/teams-licenses.md
Labels: ready to merge, internal

#16025 Accept-Language header support for GET service principals
  api-reference/beta/api/serviceprincipal-get.md
  api-reference/v1.0/api/serviceprincipal-get.md
Labels: ready to merge, internal, content review complete

#15792 Add `managedby` property in `cloudPcOnPremisesConnection`
  api-reference/beta/api/cloudpconpremisesconnection-get.md
  api-reference/beta/api/cloudpconpremisesconnection-update.md
  api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md
  api-reference/beta/api/virtualendpoint-post-onpremisesconnections.md
  api-reference/beta/resources/cloudpconpremisesconnection.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, internal, content review complete, schema live

#16013 Dawoo/caspv1
  api-reference/v1.0/resources/conditionalaccessclientapplications.md
  api-reference/v1.0/resources/conditionalaccessconditionset.md
  changelog/Microsoft.IdentityProtectionServices.json
Labels: area: Azure AD, ready to merge, internal, content review complete

#16086 Additional documentation for Excel Graph throttling
  concepts/throttling.md
  concepts/workbook-best-practice.md
  concepts/workbook-error-codes.md
  concepts/workbook-error-handling.md
Labels: area: excel, ready to merge, internal, area: throttling, content review complete, review feedback addressed

#16109 Added documentation for co-organizer
  api-reference/beta/resources/meetingparticipantinfo.md
  changelog/Microsoft.Skype.Calling.json
Labels: ready to merge, internal, content review complete

#16145 Remove preview and update to v1.0 endpoints
  concepts/search-concept-custom-types.md
Labels: ready to merge, internal, content review complete

#16153 [Azure AD] [ELM] Update JSON example
  api-reference/beta/resources/customaccesspackageworkflowextension.md
Labels: area: Azure AD, ready to merge, internal, content review complete

#16131 Added documentation for registrantId
  api-reference/beta/api/attendancerecord-list.md
  api-reference/beta/resources/attendancerecord.md
  changelog/Microsoft.Skype.Calling.json
Labels: ready to merge, internal, content review complete, review feedback addressed

#16201 Minor doc fixes
  api-reference/beta/api/oauth2permissiongrant-delete.md
  api-reference/beta/api/oauth2permissiongrant-post.md
  api-reference/beta/api/oauth2permissiongrant-update.md
  api-reference/beta/api/phoneauthenticationmethod-get.md
  api-reference/beta/api/signin-list.md
  api-reference/beta/api/unifiedroleassignment-get.md
  api-reference/beta/api/unifiedrolemanagementpolicy-get.md
  api-reference/beta/api/unifiedrolemanagementpolicy-list-effectiverules.md
  api-reference/beta/api/unifiedrolemanagementpolicy-list-rules.md
  api-reference/beta/api/unifiedrolemanagementpolicy-list.md
  api-reference/beta/api/user-post-manager.md
  api-reference/beta/resources/signin.md
  api-reference/beta/resources/unifiedrolemanagementpolicy.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/oauth2permissiongrant-delete.md
  api-reference/v1.0/api/oauth2permissiongrant-post.md
  api-reference/v1.0/api/oauth2permissiongrant-update.md
  api-reference/v1.0/api/unifiedroleassignment-get.md
  api-reference/v1.0/api/user-post-manager.md
  api-reference/v1.0/resources/oauth2permissiongrant.md
Labels: area: Azure AD, ready to merge, internal

#16181 Requiring users to specify sort direction when using orderBy query option for chat-list-messages Api
  api-reference/beta/api/chat-list-messages.md
  changelog/Microsoft.Teams.Core.json
Labels: ready to merge, internal

#16183 Update conditionalaccessplatforms.md
  api-reference/v1.0/resources/conditionalaccessplatforms.md
  changelog/Microsoft.IdentityProtectionServices.json
Labels: do not merge, ready to merge, internal, content review complete

#16221 Updating PersonCard with right permissions
  concepts/toolkit/components/person-card.md
Labels: ready to merge, internal

#16239 Update bundle-additem.md
  api-reference/beta/api/bundle-additem.md
Labels: external

#16238 Update bundle-additem.md
  api-reference/v1.0/api/bundle-additem.md
Labels: external

#16236 Update channel-doesuserhaveaccess.md
  api-reference/beta/api/channel-doesuserhaveaccess.md
Labels: external

#16226 Update data-connect-pam.md
  concepts/data-connect-pam.md
Labels: external

#16139 Update group.md
  api-reference/v1.0/resources/group.md
Labels: ready to merge, internal, content review complete

#16176 Adding GDPR note to the Access Reviews intro page
  api-reference/beta/api/accessreviewinstance-filterbycurrentuser.md
  api-reference/beta/api/accessreviewinstance-list-contactedreviewers.md
  api-reference/beta/api/accessreviewinstance-list-decisions.md
  api-reference/beta/api/accessreviewinstance-pendingaccessreviewinstances.md
  api-reference/beta/api/accessreviewinstancedecisionitem-filterbycurrentuser.md
  api-reference/beta/api/accessreviewinstancedecisionitem-listpendingapproval.md
  api-reference/beta/api/accessreviewscheduledefinition-delete.md
  api-reference/beta/api/accessreviewscheduledefinition-filterbycurrentuser.md
  api-reference/beta/api/accessreviewscheduledefinition-list-instances.md
  api-reference/beta/api/accessreviewset-list-definitions.md
  api-reference/beta/api/accessreviewset-list-historydefinitions.md
  api-reference/beta/api/accessreviewstage-list-decisions.md
  api-reference/includes/accessreviews-gdpr-intro-sentence.md
  api-reference/v1.0/api/accessreviewinstance-filterbycurrentuser.md
  api-reference/v1.0/api/accessreviewinstance-list-contactedreviewers.md
  api-reference/v1.0/api/accessreviewinstance-list-decisions.md
  api-reference/v1.0/api/accessreviewinstancedecisionitem-filterbycurrentuser.md
  api-reference/v1.0/api/accessreviewscheduledefinition-delete.md
  api-reference/v1.0/api/accessreviewscheduledefinition-filterbycurrentuser.md
  api-reference/v1.0/api/accessreviewscheduledefinition-get.md
  api-reference/v1.0/api/accessreviewscheduledefinition-list-instances.md
  api-reference/v1.0/api/accessreviewset-list-definitions.md
  api-reference/v1.0/api/accessreviewset-list-historydefinitions.md
  api-reference/v1.0/resources/accessreviewsv2-overview.md
Labels: area: Azure AD, ready to merge, content review complete, review feedback addressed

#16227 Be more explicit about who needs to pay
  concepts/teams-licenses.md
Labels: ready to merge

#16229 Minor doc fixes
  api-reference/beta/resources/entitlementmanagement-overview.md
  api-reference/v1.0/resources/entitlementmanagement-overview.md
Labels: ready to merge, internal

#15407 [Cloud PC] Add windowsSettings to cloudPcProvisioningPolicy
  api-reference/beta/api/cloudpcprovisioningpolicy-get.md
  api-reference/beta/api/cloudpcprovisioningpolicy-update.md
  api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md
  api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md
  api-reference/beta/resources/cloudpcprovisioningpolicy.md
  api-reference/beta/resources/cloudpcwindowssettings.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, internal, content review complete, schema live

#15606 Add SubscriptionId and SubscriptionDisplayName in cloudPcSourceDeviceImage
  api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md
  api-reference/beta/resources/cloudpcsourcedeviceimage.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, internal, content review complete, schema live

#16252 Update bookingbusiness-list-staffmembers.md
  api-reference/v1.0/api/bookingbusiness-list-staffmembers.md
Labels: external

#16251 Update bundle-delete.md
  api-reference/beta/api/bundle-delete.md
Labels: external

#16250 Update bundle-delete.md
  api-reference/v1.0/api/bundle-delete.md
Labels: external

#15580 Microsoft.Security.AttackSimulation [beta] - Introduction of new entity
  api-reference/beta/api/attacksimulationroot-list-simulationautomations.md
  api-reference/beta/api/attacksimulationroot-list-simulations.md
  api-reference/beta/api/simulationautomation-list-runs.md
  api-reference/beta/resources/attacksimulationroot.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/simulation.md
  api-reference/beta/resources/simulationautomation.md
  api-reference/beta/resources/simulationautomationrun.md
  api-reference/beta/resources/usertrainingeventinfo.md
  api-reference/beta/resources/usertrainingstatusinfo.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Security.AttackSimulation.json
Labels: area: Security, ready to merge, internal, content review complete

#15920 Documentation fixes
  api-reference/beta/resources/documentset.md
  api-reference/beta/resources/termcolumn.md
  api-reference/v1.0/resources/columnvalidation.md
  api-reference/v1.0/resources/documentset.md
  api-reference/v1.0/resources/documentsetcontent.md
  api-reference/v1.0/resources/hyperlinkorpicturecolumn.md
  api-reference/v1.0/resources/termcolumn.md
  changelog/Microsoft.FileServices.json
Labels: ready to merge, internal, content review complete, review feedback addressed

#16265 Updated taxonomy value.
  changelog/Microsoft.Intune.json
  changelog/Microsoft.M365ServiceCommsPlatform.json
  changelog/Microsoft.MultiTenantPlatform.json
Labels: internal

#16270 Update bundle-get.md
  api-reference/v1.0/api/bundle-get.md
Labels: external

#16271 Update bundle-get.md
  api-reference/beta/api/bundle-get.md
Labels: external

#16275 [BrokenLinksH2] fixing broken link
  concepts/known-issues.md
Labels: external

#16273 [BrokenLinksH2] fixing broken link
  concepts/connecting-external-content-manage-schema.md
Labels: external, ready to merge

#16269 [BrokenLinksH2] fixing broken link
  concepts/cloud-communications-callrecords.md
Labels: external, ready to merge

#16268 [BrokenLinksH2] fixing broken link
  concepts/applications-concept-overview.md
Labels: external, ready to merge

#16266 Added embedded video.
  concepts/item-insights-overview.md
Labels: ready to merge, internal

#16272 [BrokenLinksH2] fixing broken link
  concepts/connecting-external-content-connectors-api-postman.md
Labels: external, ready to merge

#16276 Merge to publish.
  api-reference/beta/api/bundle-get.md
  api-reference/v1.0/api/bundle-get.md
  changelog/Microsoft.Intune.json
  changelog/Microsoft.M365ServiceCommsPlatform.json
  changelog/Microsoft.MultiTenantPlatform.json
  concepts/applications-concept-overview.md
  concepts/cloud-communications-callrecords.md
  concepts/connecting-external-content-connectors-api-postman.md
  concepts/connecting-external-content-manage-schema.md
  concepts/item-insights-overview.md
  concepts/known-issues.md
Labels: internal

#16300 Update planner-post-tasks.md
  api-reference/beta/api/planner-post-tasks.md
Labels: external

#16299 Update planner-post-tasks.md
  api-reference/v1.0/api/planner-post-tasks.md
Labels: external

#16298 [BrokenLinksH2] fixing broken link
  concepts/known-issues.md
Labels: external, ready to merge

#16294 [BrokenLinksH2] fixing broken link
  concepts/known-issues.md
Labels: external, ready to merge

#16293 [BrokenLinksH2] fixing broken link
  concepts/connecting-external-content-connectors-api-postman.md
Labels: external, ready to merge

#16292 [BrokenLinksH2] fixing broken link
  concepts/changelog-archive.md
Labels: external, ready to merge

#16291 [BrokenLinksH2] fixing broken link
  concepts/teams-concept-overview.md
Labels: external, ready to merge

#16289 [BrokenLinksH2] fixing broken link
  concepts/teams-concept-overview.md
Labels: external, ready to merge

#16286 Fixing typos on the Toolkit overview
  concepts/toolkit/get-started/overview.md
Labels: ready to merge

#16287 [BrokenLinksH2] fixing broken link
  concepts/social-intel-concept-overview.md
Labels: external, ready to merge
