Repository microsoftgraph/microsoft-graph-docs, pull requests merged in 2022-07, with the labels that each got.

#17534 Update user-post-calendars.md
  api-reference/v1.0/api/user-post-calendars.md
Labels: external

#17533 Update user-post-calendars.md
  api-reference/beta/api/user-post-calendars.md
Labels: external

#17532 Edits in PR 17061
  api-reference/beta/api/taskFileAttachment-createuploadsession.md
  api-reference/beta/resources/taskfileattachment.md
  concepts/todo-attachments.md
Labels: external

#17528 Update metadata for remaining Develop docs
  api-reference/beta/overview.md
  api-reference/v1.0/overview.md
  concepts/best-practices-concept.md
  concepts/errors.md
  concepts/known-issues.md
  concepts/migrate-azure-ad-graph-configure-permissions.md
  concepts/migrate-azure-ad-graph-overview.md
  concepts/migrate-azure-ad-graph-planning-checklist.md
  concepts/migrate-exchange-web-services-overview.md
  concepts/sdks/sdk-installation.md
  concepts/sdks/sdks-overview.md
  concepts/toolkit/get-started/overview.md
  concepts/toolkit/overview.md
Labels: ready to merge, internal

#17530 Update isArchived typo
  api-reference/v1.0/resources/group.md
Labels: area: groups, ready to merge, internal

#16649 Export API-Add deleted team API
  api-reference/beta/api/deletedteam-getallmessages.md
  api-reference/beta/api/teamwork-list-deletedteams.md
  api-reference/beta/resources/deletedteam.md
  api-reference/beta/resources/teamwork.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Teams.GraphSvc.json
  concepts/teams-protected-apis.md
Labels: ready to merge, content review complete

#17223 Remove parameter 'content' from app usage reports URL.
  api-reference/beta/api/reportroot-getm365appplatformusercounts.md
  api-reference/beta/api/reportroot-getm365appusercounts.md
  api-reference/beta/api/reportroot-getm365appuserdetail.md
  api-reference/beta/includes/snippets/csharp/reportroot-getm365appplatformusercounts-csv-csharp-snippets.md
  api-reference/beta/includes/snippets/csharp/reportroot-getm365appplatformusercounts-json-csharp-snippets.md
  api-reference/beta/includes/snippets/csharp/reportroot-getm365appusercoundetail-csharp-snippets.md
  api-reference/beta/includes/snippets/csharp/reportroot-getm365appusercountdetail-csharp-snippets.md
  api-reference/beta/includes/snippets/csharp/reportroot-getm365appusercounts-csv-csharp-snippets.md
  api-reference/beta/includes/snippets/csharp/reportroot-getm365appusercounts-json-csharp-snippets.md
  api-reference/beta/includes/snippets/java/reportroot-getm365appplatformusercounts-csv-java-snippets.md
  api-reference/beta/includes/snippets/java/reportroot-getm365appplatformusercounts-json-java-snippets.md
  api-reference/beta/includes/snippets/java/reportroot-getm365appusercoundetail-java-snippets.md
  api-reference/beta/includes/snippets/java/reportroot-getm365appusercountdetail-java-snippets.md
  api-reference/beta/includes/snippets/java/reportroot-getm365appusercounts-csv-java-snippets.md
  api-reference/beta/includes/snippets/java/reportroot-getm365appusercounts-json-java-snippets.md
  api-reference/beta/includes/snippets/javascript/reportroot-getm365appplatformusercounts-csv-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/reportroot-getm365appplatformusercounts-json-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/reportroot-getm365appusercoundetail-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/reportroot-getm365appusercountdetail-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/reportroot-getm365appusercounts-csv-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/reportroot-getm365appusercounts-json-javascript-snippets.md
  api-reference/beta/includes/snippets/objc/reportroot-getm365appplatformusercounts-csv-objc-snippets.md
  api-reference/beta/includes/snippets/objc/reportroot-getm365appplatformusercounts-json-objc-snippets.md
  api-reference/beta/includes/snippets/objc/reportroot-getm365appusercoundetail-objc-snippets.md
  api-reference/beta/includes/snippets/objc/reportroot-getm365appusercountdetail-objc-snippets.md
  api-reference/beta/includes/snippets/objc/reportroot-getm365appusercounts-csv-objc-snippets.md
  api-reference/beta/includes/snippets/objc/reportroot-getm365appusercounts-json-objc-snippets.md
  changelog/Microsoft.O365Reporting.json
Labels: ready to merge, internal, content review complete

#17537 Refreshed what's new through June 21.
  concepts/whats-new-overview.md
Labels: do not merge, internal

#17525 Fix const declarations
  concepts/sdks/choose-authentication-providers.md
Labels: external, ready to merge

#17517 Validation issues | 1 (BULK)
  api-reference/v1.0/resources/addin.md
  api-reference/v1.0/resources/assignedlabel.md
  api-reference/v1.0/resources/directoryobjectpartnerreference.md
  api-reference/v1.0/resources/package.md
  api-reference/v1.0/resources/place.md
  api-reference/v1.0/resources/usersettings.md
  concepts/accessreviews-scope-concept.md
  concepts/application-rollkey-prooftoken.md
Labels: external, ready to merge

#17526 Changes for Graph API Docs --ESS capabilities
  concepts/connecting-external-content-api-limits.md
Labels: ready to merge, internal, content review complete

#17543 Updates monetization docs
  concepts/teams-licenses.md
Labels: ready to merge, internal, content review complete

#17546 Refresh what's new topic through 7/1.
  api-reference/beta/resources/complianceapioverview.md
  api-reference/beta/resources/security-recordsmanagement-overview.md
  changelog/Microsoft.Compliance.RecordsManagement.json
  changelog/Microsoft.DirectoryServices.json
  concepts/permissions-reference.md
  concepts/whats-new-overview.md
Labels: do not merge, internal

#17547 Merge to publish.
  api-reference/beta/resources/complianceapioverview.md
  api-reference/beta/resources/security-recordsmanagement-overview.md
  api-reference/v1.0/resources/addin.md
  api-reference/v1.0/resources/assignedlabel.md
  api-reference/v1.0/resources/directoryobjectpartnerreference.md
  api-reference/v1.0/resources/package.md
  api-reference/v1.0/resources/place.md
  api-reference/v1.0/resources/usersettings.md
  changelog/Microsoft.Compliance.RecordsManagement.json
  changelog/Microsoft.DirectoryServices.json
  concepts/accessreviews-scope-concept.md
  concepts/application-rollkey-prooftoken.md
  concepts/connecting-external-content-api-limits.md
  concepts/permissions-reference.md
  concepts/sdks/choose-authentication-providers.md
  concepts/teams-licenses.md
  concepts/whats-new-overview.md
Labels: internal

#17558 Edits in PR 17246
  api-reference/beta/resources/virtualappointment.md
  api-reference/beta/resources/virtualappointmentsettings.md
  api-reference/beta/resources/virtualappointmentuser.md
  api-reference/beta/toc.yml
Labels: external

#17557 Edits in PR 17061
  api-reference/beta/api/taskfileattachment-createuploadsession.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Todo.json
  concepts/todo-attachments.md
Labels: external

#17484 preserve-view-not-set-fixes-7
  concepts/changelog-archive.md
Labels: external, ready to merge

#17570 Edits in PR 17246
  api-reference/beta/api/virtualappointment-get.md
  api-reference/beta/api/virtualappointment-put.md
  api-reference/beta/api/virtualappointment-update.md
  api-reference/beta/resources/virtualappointment.md
  api-reference/beta/resources/virtualappointmentsettings.md
  api-reference/beta/resources/virtualappointmentuser.md
  changelog/Microsoft.Skype.Calling.json
Labels: external

#17571 Update table-update.md
  api-reference/v1.0/api/table-update.md
Labels: external

#17572 Update table-update.md
  api-reference/beta/api/table-update.md
Labels: external

#17554 Minor doc fixes
  api-reference/beta/api/group-post-members.md
  api-reference/beta/api/group-update.md
  api-reference/beta/api/user-list-memberof.md
  api-reference/beta/api/user-list-transitivememberof.md
  api-reference/beta/resources/accessreviewrecommendationinsightsetting.md
  api-reference/beta/resources/group.md
  api-reference/beta/resources/groupwritebackconfiguration.md
  api-reference/beta/resources/synchronization-synchronizationjobsubject.md
  api-reference/beta/resources/synchronization-synchronizationlinkedobjects.md
  api-reference/beta/resources/user.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/group-post-members.md
  api-reference/v1.0/api/user-list-memberof.md
  api-reference/v1.0/api/user-list-transitivememberof.md
  api-reference/v1.0/resources/group.md
  api-reference/v1.0/resources/user.md
  changelog/Microsoft.DirectoryServices.json
  concepts/whats-new-overview.md
Labels: area: Azure AD, ready to merge, internal

#16093 join call with id and passcode
  api-reference/beta/api/application-post-calls.md
  api-reference/beta/resources/call.md
  api-reference/beta/resources/joinmeetingidmeetinginfo.md
  api-reference/beta/resources/meetinginfo.md
  changelog/Microsoft.Skype.Calling.json
Labels: ready to merge, internal, content review complete

#15637 joinMeetingIdSettings for online meeting
  api-reference/beta/api/application-post-onlinemeetings.md
  api-reference/beta/api/onlinemeeting-get.md
  api-reference/beta/resources/joinmeetingidsettings.md
  api-reference/beta/resources/onlinemeeting.md
  changelog/Microsoft.Skype.Calling.json
Labels: ready to merge, internal, content review complete

#17111 Update signin-confirmcompromised.md
  api-reference/beta/api/signin-confirmcompromised.md
Labels: ready to merge, internal, content review complete

#17461 Updated profilephoto-update.md for size dimensions
  api-reference/v1.0/api/profilephoto-update.md
Labels: ready to merge, internal, content review complete

#17129 Adding Teams App Settings resource and operations.
  api-reference/beta/api/teamsappsettings-get.md
  api-reference/beta/api/teamsappsettings-update.md
  api-reference/beta/resources/teamsappsettings.md
  api-reference/beta/resources/teamwork.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Teams.GraphSvc.json
  concepts/known-issues.md
Labels: ready to merge, internal, content review complete, review feedback addressed

#17531 Adding new CA rule enums
  api-reference/beta/resources/conditionalaccessrulesatisfied.md
  api-reference/beta/resources/enums.md
  changelog/Microsoft.AAD.Reporting.json
Labels: ready to merge, internal, content review complete

#17061 Add attachment support for todoTask
  api-reference/beta/api/taskfileattachment-createuploadsession.md
  api-reference/beta/api/taskfileattachment-delete.md
  api-reference/beta/api/taskfileattachment-get.md
  api-reference/beta/api/todotask-list-attachments.md
  api-reference/beta/api/todotask-post-attachments.md
  api-reference/beta/resources/attachmentbase.md
  api-reference/beta/resources/attachmentinfo.md
  api-reference/beta/resources/attachmentsession.md
  api-reference/beta/resources/taskfileattachment.md
  api-reference/beta/resources/todotask.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Todo.json
  concepts/toc.yml
  concepts/todo-attachments.md
Labels: ready to merge, internal, content review complete

#17317 Validation: Duplicate alt-text fixes.
  api-reference/beta/api/callrecords-callrecord-get.md
  api-reference/beta/api/chart-image.md
Labels: external, ready to merge

#17575 Merge to publish.
  api-reference/beta/api/application-post-calls.md
  api-reference/beta/api/application-post-onlinemeetings.md
  api-reference/beta/api/callrecords-callrecord-get.md
  api-reference/beta/api/chart-image.md
  api-reference/beta/api/group-post-members.md
  api-reference/beta/api/group-update.md
  api-reference/beta/api/onlinemeeting-get.md
  api-reference/beta/api/signin-confirmcompromised.md
  api-reference/beta/api/table-update.md
  api-reference/beta/api/taskfileattachment-createuploadsession.md
  api-reference/beta/api/taskfileattachment-delete.md
  api-reference/beta/api/taskfileattachment-get.md
  api-reference/beta/api/teamsappsettings-get.md
  api-reference/beta/api/teamsappsettings-update.md
  api-reference/beta/api/todotask-list-attachments.md
  api-reference/beta/api/todotask-post-attachments.md
  api-reference/beta/api/user-list-memberof.md
  api-reference/beta/api/user-list-transitivememberof.md
  api-reference/beta/resources/accessreviewrecommendationinsightsetting.md
  api-reference/beta/resources/attachmentbase.md
  api-reference/beta/resources/attachmentinfo.md
  api-reference/beta/resources/attachmentsession.md
  api-reference/beta/resources/call.md
  api-reference/beta/resources/conditionalaccessrulesatisfied.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/group.md
  api-reference/beta/resources/groupwritebackconfiguration.md
  api-reference/beta/resources/joinmeetingidmeetinginfo.md
  api-reference/beta/resources/joinmeetingidsettings.md
  api-reference/beta/resources/meetinginfo.md
  api-reference/beta/resources/onlinemeeting.md
  api-reference/beta/resources/synchronization-synchronizationjobsubject.md
  api-reference/beta/resources/synchronization-synchronizationlinkedobjects.md
  api-reference/beta/resources/taskfileattachment.md
  api-reference/beta/resources/teamsappsettings.md
  api-reference/beta/resources/teamwork.md
  api-reference/beta/resources/todotask.md
  api-reference/beta/resources/user.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/group-post-members.md
  api-reference/v1.0/api/profilephoto-update.md
  api-reference/v1.0/api/table-update.md
  api-reference/v1.0/api/user-list-memberof.md
  api-reference/v1.0/api/user-list-transitivememberof.md
  api-reference/v1.0/resources/group.md
  api-reference/v1.0/resources/user.md
  changelog/Microsoft.AAD.Reporting.json
  changelog/Microsoft.DirectoryServices.json
  changelog/Microsoft.Skype.Calling.json
  changelog/Microsoft.Teams.GraphSvc.json
  changelog/Microsoft.Todo.json
  concepts/changelog-archive.md
  concepts/known-issues.md
  concepts/toc.yml
  concepts/todo-attachments.md
  concepts/whats-new-overview.md
  concepts/workbook-error-handling.md
Labels: internal

#17587 Edits in PR 17246
  api-reference/beta/api/onlinemeeting-put-virtualappointment.md
  api-reference/beta/api/virtualappointment-update.md
  api-reference/beta/resources/virtualappointment.md
  api-reference/beta/toc.yml
Labels: external

#17592 Update todo-attachments.md
  concepts/todo-attachments.md
Labels: external

#17591 Edits in PR 17246
  api-reference/beta/api/virtualappointment-put.md
  api-reference/beta/api/virtualappointment-update.md
  api-reference/beta/resources/virtualappointment.md
  api-reference/beta/toc.yml
Labels: external

#17586 Validation: Fix preserve-view-not-set
  api-reference/beta/resources/addin.md
  api-reference/beta/resources/communications-api-overview.md
  api-reference/beta/resources/groups-overview.md
  api-reference/beta/resources/licenseunitsdetail.md
  api-reference/beta/resources/report-identity-access.md
Labels: external

#17564 Fix broken links to API pages and overview
  concepts/teams-licenses.md
Labels: ready to merge, internal

#17544 fix for odataType in educationClass-Post-Assignments
  api-reference/beta/api/educationclass-post-assignments.md
  api-reference/v1.0/api/educationclass-post-assignment.md
Labels: ready to merge, internal, content review complete

#17560 Added samlMetadataUrl property to Application entity in v1
  api-reference/beta/api/application-update.md
  api-reference/v1.0/api/application-get.md
  api-reference/v1.0/api/application-post-applications.md
  api-reference/v1.0/api/application-update.md
  api-reference/v1.0/resources/application.md
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, ready to merge, internal, content review complete

#17577 The type of API is POST and not GET.
  api-reference/beta/api/bookingbusiness-getstaffavailability.md
Labels: ready to merge, internal, content review complete

#17583 Minor doc fixes
  api-reference/beta/resources/conditionalaccessapplications.md
  api-reference/beta/resources/unifiedrolepermission.md
  api-reference/v1.0/resources/conditionalaccessapplications.md
  api-reference/v1.0/resources/unifiedrolepermission.md
  concepts/delta-query-events.md
  concepts/delta-query-groups.md
  concepts/delta-query-messages.md
  concepts/delta-query-overview.md
  concepts/delta-query-users.md
Labels: area: Azure AD, ready to merge, internal

#17584 Split throttling reference from conceptual info
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
  concepts/cloud-communications-concept-overview.md
  concepts/json-batching.md
  concepts/onenote-error-codes.md
  concepts/throttling-limits.md
  concepts/throttling.md
  concepts/toc.yml
Labels: ready to merge, internal

#17609 Update chat.md
  api-reference/beta/resources/chat.md
Labels: external

#17608 Update chat.md
  api-reference/v1.0/resources/chat.md
Labels: external

#17607 Edit in PR 17246
  api-reference/beta/api/virtualappointment-put.md
Labels: external

#17602 Reassign device registration policy docs
  api-reference/beta/api/deviceregistrationpolicy-get.md
  api-reference/beta/api/deviceregistrationpolicy-update.md
  api-reference/beta/resources/azureadjoinpolicy.md
  api-reference/beta/resources/azureadregistrationpolicy.md
  api-reference/beta/resources/deviceregistrationpolicy.md
Labels: area: Azure AD, ready to merge, internal

#17603 Clarify multitenant apps monetization
  concepts/teams-licenses.md
Labels: ready to merge, internal

#16827 Chalie teamstemplates graph api doc
  api-reference/beta/api/teamtemplate-list-definitions.md
  api-reference/beta/api/teamtemplatedefinition-get-teamdefinition.md
  api-reference/beta/api/teamtemplatedefinition-get.md
  api-reference/beta/api/teamwork-list-teamtemplates.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/teamstemplate.md
  api-reference/beta/resources/teamtemplate.md
  api-reference/beta/resources/teamtemplatedefinition.md
  api-reference/beta/resources/teamwork.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Teams.Core.json
Labels: ready to merge, internal, content review complete

#17613 Merge to publish.
  api-reference/beta/api/deviceregistrationpolicy-get.md
  api-reference/beta/api/deviceregistrationpolicy-update.md
  api-reference/beta/api/teamtemplate-list-definitions.md
  api-reference/beta/api/teamtemplatedefinition-get-teamdefinition.md
  api-reference/beta/api/teamtemplatedefinition-get.md
  api-reference/beta/api/teamwork-list-teamtemplates.md
  api-reference/beta/resources/azureadjoinpolicy.md
  api-reference/beta/resources/azureadregistrationpolicy.md
  api-reference/beta/resources/chat.md
  api-reference/beta/resources/deviceregistrationpolicy.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/teamstemplate.md
  api-reference/beta/resources/teamtemplate.md
  api-reference/beta/resources/teamtemplatedefinition.md
  api-reference/beta/resources/teamwork.md
  api-reference/beta/toc.yml
  api-reference/v1.0/resources/chat.md
  changelog/Microsoft.Teams.Core.json
  concepts/teams-licenses.md
Labels: internal

#17621 Update calendar-list-calendarview.md
  api-reference/v1.0/api/calendar-list-calendarview.md
Labels: external

#17620 Update calendar-list-calendarview.md
  api-reference/beta/api/calendar-list-calendarview.md
Labels: external

#17279 Adding transcripts classic permissions
  concepts/permissions-reference.md
Labels: ready to merge, internal, content review complete

#17612 Update teamsfx provider doc
  concepts/toolkit/providers/teamsfx.md
Labels: external, ready to merge

#17611 Update user-get.md
  api-reference/v1.0/api/user-get.md
Labels: area: Azure AD, area: users, ready to merge, internal, content review complete

#17295 Validation: Added Preserve Views
  concepts/onenote-update-page.md
  concepts/outlook-calendar-concept-overview.md
  concepts/outlook-create-send-messages.md
  concepts/outlook-get-free-busy-schedule.md
  concepts/outlook-get-mime-message.md
Labels: external, ready to merge

#17315 [Bulk] Validation: validation fixes 6/17
  concepts/findmeetingtimes-example.md
  concepts/long-running-actions-overview.md
  concepts/onedrive-concept-overview.md
Labels: external, ready to merge

#17619 Permissions GUIDs refresh - June
  concepts/includes/permissions-ids.md
  concepts/permissions-reference.md
Labels: area: Azure AD, ready to merge, internal, area: permissions

#17585 [ELM] [MSGraph] added reprocess to v1.0
  api-reference/v1.0/api/accesspackageassignment-reprocess.md
  api-reference/v1.0/api/accesspackageassignmentrequest-reprocess.md
  api-reference/v1.0/resources/accesspackageassignment.md
  api-reference/v1.0/resources/accesspackageassignmentrequest.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, ready to merge, internal, content review complete, schema live, area: governance

#17638 Edits in PR 15683
  api-reference/includes/informationprotection-deprecate.md
Labels: external

#17644 Update to feedback URL
  concepts/whats-new-overview.md
Labels: external

#17643 Update teamwork-list-teamtemplates.md
  api-reference/beta/api/teamwork-list-teamtemplates.md
Labels: external

#17642 Edits in PR 17394
  api-reference/beta/api/team-get-photo.md
  api-reference/beta/api/team-update-photo.md
Labels: external

#17637 Update application-post-calls.md
  api-reference/beta/api/application-post-calls.md
Labels: external

#17635 Update meetinginfo.md
  api-reference/beta/resources/meetinginfo.md
Labels: external

#17634 Edits in PR 17246
  api-reference/beta/api/virtualappointment-update.md
Labels: external

#17627 Update page-copytosection.md
  api-reference/v1.0/api/page-copytosection.md
Labels: external

#17633 Validation: Misc validation fixes
  api-reference/includes/outlook-mailbox-type-support.md
  api-reference/v1.0/api/callrecords-callrecord-get.md
  api-reference/v1.0/api/chart-image.md
Labels: external, ready to merge

#17626 Update page-copytosection.md
  api-reference/beta/api/page-copytosection.md
Labels: external

#17629 fixing reported TOC link issues
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
Labels: external, ready to merge

#16700 [Bulk] Validation: Fix invalid ms.value
  api-reference/beta/resources/root.md
  api-reference/beta/resources/searchresult.md
  api-reference/beta/resources/sectionlinks.md
  api-reference/beta/resources/securescorecontrolprofiles.md
  api-reference/beta/resources/shareaction.md
  api-reference/beta/resources/shared.md
  api-reference/beta/resources/shareddriveitem.md
  api-reference/beta/resources/sharinginvitation.md
  api-reference/beta/resources/sharinglink.md
  api-reference/beta/resources/singlevaluelegacyextendedproperty.md
  api-reference/beta/resources/sizerange.md
  api-reference/beta/resources/standardtimezoneoffset.md
  api-reference/beta/resources/storageplaninformation.md
  api-reference/beta/resources/systemfacet.md
  api-reference/beta/resources/targetresourceapp.md
  api-reference/beta/resources/tasks-identifiers-disclaimer.md
  api-reference/beta/resources/termstore-group.md
  api-reference/beta/resources/termstore-localizeddescription.md
  api-reference/beta/resources/termstore-localizedlabel.md
  api-reference/beta/resources/termstore-localizedname.md
  api-reference/beta/resources/termstore-relation.md
  api-reference/beta/resources/termstore-set.md
  api-reference/beta/resources/termstore-store.md
  api-reference/beta/resources/termstore-term.md
  api-reference/beta/resources/textColumn.md
  api-reference/beta/resources/thumbnail.md
  api-reference/beta/resources/thumbnailset.md
  api-reference/beta/resources/timestamp.md
  api-reference/beta/resources/timezonebase.md
  api-reference/beta/resources/timezoneinformation.md
  api-reference/beta/resources/typedemailaddress.md
  api-reference/beta/resources/versionaction.md
  api-reference/beta/resources/video.md
  api-reference/beta/resources/vulnerabilitystate.md
  api-reference/beta/resources/website.md
  api-reference/beta/resources/workposition.md
Labels: external, ready to merge, review feedback addressed

#17623 Validation: Missing description
  concepts/data-connect-quickstart.yml
  includes/data-connect-quickstart-01.md
  includes/data-connect-quickstart-02.md
  includes/data-connect-quickstart-03.md
  includes/data-connect-quickstart-04.md
  includes/data-connect-quickstart-05.md
  includes/data-connect-quickstart-06.md
  includes/data-connect-quickstart-07.md
  includes/data-connect-quickstart-08.md
Labels: external, review requested

#17539 Update fabricbot.json
  .github/fabricbot.json
Labels: do not merge, internal

#17666 Update plannertaskdetails-get.md
  api-reference/v1.0/api/plannertaskdetails-get.md
Labels: external

#17665 Update plannertaskdetails-get.md
  api-reference/beta/api/plannertaskdetails-get.md
Labels: external

#17664 Edits in PR 16264
  api-reference/beta/api/cloudpcexternalpartnersetting-get.md
  api-reference/beta/api/cloudpcexternalpartnersetting-update.md
  api-reference/beta/api/virtualendpoint-list-externalpartnersettings.md
  api-reference/beta/api/virtualendpoint-post-externalpartnersettings.md
  api-reference/beta/resources/cloudpcexternalpartnersetting.md
  api-reference/beta/resources/virtualendpoint.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: external

#17662 Edits in PR 17407
  api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: external

#17659 Edits in PR 15683
  api-reference/beta/api/informationprotectionlabel-evaluateapplication.md
  api-reference/beta/api/informationprotectionlabel-evaluateclassificationresults.md
  api-reference/beta/api/informationprotectionlabel-evaluateremoval.md
  api-reference/beta/api/informationprotectionlabel-extractlabel.md
  api-reference/beta/api/informationprotectionlabel-get.md
  api-reference/beta/api/informationprotectionpolicy-list-labels.md
  api-reference/beta/resources/addcontentfooteraction.md
  api-reference/beta/resources/addcontentheaderaction.md
  api-reference/beta/resources/addwatermarkaction.md
  api-reference/beta/resources/applylabelaction.md
  api-reference/beta/resources/classificationresult.md
  api-reference/beta/resources/contentinfo.md
  api-reference/beta/resources/customaction.md
  api-reference/beta/resources/downgradejustification.md
  api-reference/beta/resources/informationprotectionaction.md
  api-reference/beta/resources/informationprotectioncontentlabel.md
  api-reference/beta/resources/informationprotectionlabel.md
  api-reference/beta/resources/justifyaction.md
  api-reference/beta/resources/labelingoptions.md
  api-reference/beta/resources/metadataaction.md
  api-reference/beta/resources/protectadhocaction.md
  api-reference/beta/resources/protectbytemplateaction.md
  api-reference/beta/resources/protectdonotforwardaction.md
  api-reference/beta/resources/recommendlabelaction.md
  api-reference/beta/resources/removecontentfooteraction.md
  api-reference/beta/resources/removecontentheaderaction.md
  api-reference/beta/resources/removeprotectionaction.md
  api-reference/beta/resources/removewatermarkaction.md
  api-reference/beta/resources/security-informationprotectionaction.md
  concepts/information-protection-overview.md
  concepts/security-information-protection-overview.md
Labels: external

#17652 Validation - fix link build issues
  api-reference/v1.0/api/serviceprincipal-update.md
  api-reference/v1.0/api/usersettings-update.md
Labels: external, ready to merge

#17656 Request code snippets
  api-reference/v1.0/api/directory-deleteditems-list.md
Labels: area: Azure AD, ready to merge, area: SDKs

#17650 Minor updates to AR scope and reviewers how-to's
  concepts/accessreviews-reviewers-concept.md
  concepts/accessreviews-scope-concept.md
Labels: area: Azure AD, ready to merge, internal, area: governance

#17636 Direct Fed changes
  api-reference/beta/api/samlorwsfedexternaldomainfederation-delete.md
  api-reference/beta/api/samlorwsfedexternaldomainfederation-list-domains.md
  api-reference/beta/api/samlorwsfedexternaldomainfederation-list.md
  api-reference/beta/api/samlorwsfedexternaldomainfederation-post-domains.md
  api-reference/beta/api/samlorwsfedexternaldomainfederation-post.md
  api-reference/beta/api/samlorwsfedexternaldomainfederation-update.md
  api-reference/v1.0/api/samlorwsfedexternaldomainfederation-get.md
  api-reference/v1.0/api/samlorwsfedexternaldomainfederation-list-domains.md
  api-reference/v1.0/api/samlorwsfedexternaldomainfederation-list.md
  api-reference/v1.0/api/samlorwsfedexternaldomainfederation-post-domains.md
  api-reference/v1.0/api/samlorwsfedexternaldomainfederation-post.md
  api-reference/v1.0/api/samlorwsfedexternaldomainfederation-update.md
Labels: area: Azure AD, ready to merge, internal, content review complete

#15444 Create external-identity-policy.md
  api-reference/beta/api/externalidentitiespolicy-get.md
  api-reference/beta/api/externalidentitiespolicy-update.md
  api-reference/beta/resources/externalidentitiespolicy.md
  api-reference/beta/resources/policyroot.md
  api-reference/beta/toc.yml
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, ready to merge, internal, content review complete

#16836 Added Support for editing properties of message in user context.
  api-reference/beta/api/chatmessage-update.md
Labels: ready to merge, internal, content review complete

#16011 Delete message API for chat and channel
  api-reference/beta/api/chatmessage-softdelete.md
  api-reference/beta/api/chatmessage-undosoftdelete.md
  api-reference/beta/resources/chatmessage.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Teams.Core.json
Labels: ready to merge, internal, teams: messaging, content review complete

#17573 ADFS2AAD Public Preview Updates
  api-reference/beta/resources/tokenissuancepolicy.md
  api-reference/v1.0/resources/tokenissuancepolicy.md
Labels: area: Azure AD, ready to merge, internal, content review complete

#17410 Add startDateTime property to a todoTask
  api-reference/beta/api/todotask-get.md
  api-reference/beta/api/todotask-update.md
  api-reference/beta/api/todotasklist-delta.md
  api-reference/beta/api/todotasklist-post-tasks.md
  api-reference/beta/resources/todotask.md
  changelog/Microsoft.Todo.json
Labels: ready to merge, internal, content review complete

#17670 Merge to publish.
  .github/fabricbot.json
  api-reference/beta/api/chatmessage-softdelete.md
  api-reference/beta/api/chatmessage-undosoftdelete.md
  api-reference/beta/api/chatmessage-update.md
  api-reference/beta/api/externalidentitiespolicy-get.md
  api-reference/beta/api/externalidentitiespolicy-update.md
  api-reference/beta/api/plannertaskdetails-get.md
  api-reference/beta/api/samlorwsfedexternaldomainfederation-delete.md
  api-reference/beta/api/samlorwsfedexternaldomainfederation-list-domains.md
  api-reference/beta/api/samlorwsfedexternaldomainfederation-list.md
  api-reference/beta/api/samlorwsfedexternaldomainfederation-post-domains.md
  api-reference/beta/api/samlorwsfedexternaldomainfederation-post.md
  api-reference/beta/api/samlorwsfedexternaldomainfederation-update.md
  api-reference/beta/api/todotask-get.md
  api-reference/beta/api/todotask-update.md
  api-reference/beta/api/todotasklist-delta.md
  api-reference/beta/api/todotasklist-post-tasks.md
  api-reference/beta/resources/chatmessage.md
  api-reference/beta/resources/externalidentitiespolicy.md
  api-reference/beta/resources/policyroot.md
  api-reference/beta/resources/todotask.md
  api-reference/beta/resources/tokenissuancepolicy.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/directory-deleteditems-list.md
  api-reference/v1.0/api/plannertaskdetails-get.md
  api-reference/v1.0/api/samlorwsfedexternaldomainfederation-get.md
  api-reference/v1.0/api/samlorwsfedexternaldomainfederation-list-domains.md
  api-reference/v1.0/api/samlorwsfedexternaldomainfederation-list.md
  api-reference/v1.0/api/samlorwsfedexternaldomainfederation-post-domains.md
  api-reference/v1.0/api/samlorwsfedexternaldomainfederation-post.md
  api-reference/v1.0/api/samlorwsfedexternaldomainfederation-update.md
  api-reference/v1.0/api/serviceprincipal-update.md
  api-reference/v1.0/api/usersettings-update.md
  api-reference/v1.0/resources/tokenissuancepolicy.md
  changelog/Microsoft.DirectoryServices.json
  changelog/Microsoft.Teams.Core.json
  changelog/Microsoft.Todo.json
  concepts/accessreviews-reviewers-concept.md
  concepts/accessreviews-scope-concept.md
  concepts/data-connect-quickstart.yml
  includes/data-connect-quickstart-01.md
  includes/data-connect-quickstart-02.md
  includes/data-connect-quickstart-03.md
  includes/data-connect-quickstart-04.md
  includes/data-connect-quickstart-05.md
  includes/data-connect-quickstart-06.md
  includes/data-connect-quickstart-07.md
  includes/data-connect-quickstart-08.md
Labels: internal

#17682 Update plannerbucket-delete.md
  api-reference/v1.0/api/plannerbucket-delete.md
Labels: external

#17681 Update plannerbucket-delete.md
  api-reference/beta/api/plannerbucket-delete.md
Labels: external

#17680 Edits in PR 17582
  api-reference/beta/api/employeeexperience-delete-learningproviders.md
  api-reference/beta/api/employeeexperience-list-learningproviders.md
  api-reference/beta/api/employeeexperience-post-learningproviders.md
  api-reference/beta/api/learningcontent-get.md
  api-reference/beta/api/learningcontent-update.md
  api-reference/beta/api/learningprovider-delete-learningcontents.md
  api-reference/beta/api/learningprovider-get.md
  api-reference/beta/api/learningprovider-list-learningcontents.md
  api-reference/beta/api/learningprovider-update.md
  api-reference/beta/resources/learningcontent.md
  api-reference/beta/resources/learningprovider.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Viva.Learning.json
  concepts/overview-major-services.md
  concepts/permissions-reference.md
  concepts/toc.yml
  concepts/viva-learning-concept-overview.md
Labels: external, ready to merge

#12756 Initial commit to add support for restoring and permanently deleting SPs
  api-reference/beta/api/directory-deleteditems-delete.md
  api-reference/beta/api/directory-deleteditems-get.md
  api-reference/beta/api/directory-deleteditems-list.md
  api-reference/beta/api/directory-deleteditems-restore.md
  api-reference/beta/resources/serviceprincipal.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/directory-deleteditems-delete.md
  api-reference/v1.0/api/directory-deleteditems-get.md
  api-reference/v1.0/api/directory-deleteditems-list.md
  api-reference/v1.0/api/directory-deleteditems-restore.md
  api-reference/v1.0/resources/serviceprincipal.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, resolved: awaiting prod deployment, ready to merge, internal, content review complete

#17606 Clarify permission needed for consent directory settings
  api-reference/beta/api/directorysetting-delete.md
  api-reference/beta/api/directorysetting-update.md
  api-reference/v1.0/api/groupsetting-delete.md
  api-reference/v1.0/api/groupsetting-update.md
Labels: area: Azure AD, awaiting internal response, ready to merge, internal, content review complete

#17655 Fix display template docs gap
  api-reference/beta/resources/externalconnectors-displaytemplate.md
  api-reference/beta/resources/externalconnectors-searchsettings.md
Labels: ready to merge, internal, content review complete

#17673 Minor fixes to users
  api-reference/beta/api/user-list-transitivememberof.md
  api-reference/beta/api/user-update.md
  api-reference/beta/resources/user.md
  api-reference/v1.0/api/user-list-transitivememberof.md
  api-reference/v1.0/api/user-update.md
  api-reference/v1.0/resources/user.md
Labels: area: Azure AD, area: users, ready to merge

#17683 Merge to publish.
  api-reference/beta/api/directory-deleteditems-delete.md
  api-reference/beta/api/directory-deleteditems-get.md
  api-reference/beta/api/directory-deleteditems-list.md
  api-reference/beta/api/directory-deleteditems-restore.md
  api-reference/beta/api/directorysetting-delete.md
  api-reference/beta/api/directorysetting-update.md
  api-reference/beta/api/plannerbucket-delete.md
  api-reference/beta/api/user-list-transitivememberof.md
  api-reference/beta/api/user-update.md
  api-reference/beta/resources/externalconnectors-displaytemplate.md
  api-reference/beta/resources/externalconnectors-searchsettings.md
  api-reference/beta/resources/serviceprincipal.md
  api-reference/beta/resources/user.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/directory-deleteditems-delete.md
  api-reference/v1.0/api/directory-deleteditems-get.md
  api-reference/v1.0/api/directory-deleteditems-list.md
  api-reference/v1.0/api/directory-deleteditems-restore.md
  api-reference/v1.0/api/groupsetting-delete.md
  api-reference/v1.0/api/groupsetting-update.md
  api-reference/v1.0/api/plannerbucket-delete.md
  api-reference/v1.0/api/user-list-transitivememberof.md
  api-reference/v1.0/api/user-update.md
  api-reference/v1.0/resources/serviceprincipal.md
  api-reference/v1.0/resources/user.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.DirectoryServices.json
Labels: do not merge, internal

#17695 Update fabricbot.json
  .github/fabricbot.json
Labels: do not merge, internal

#17697 Edits in PR 17582
  api-reference/beta/api/employeeexperience-delete-learningproviders.md
  api-reference/beta/api/employeeexperience-list-learningproviders.md
  api-reference/beta/api/employeeexperience-post-learningproviders.md
  api-reference/beta/api/learningcontent-get.md
  api-reference/beta/api/learningcontent-update.md
  api-reference/beta/api/learningprovider-delete-learningcontents.md
  api-reference/beta/api/learningprovider-get.md
  api-reference/beta/api/learningprovider-list-learningcontents.md
  api-reference/beta/api/learningprovider-update.md
  api-reference/beta/resources/api-overview.md
  api-reference/beta/resources/learningcontent.md
  api-reference/beta/resources/learningprovider.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Viva.Learning.json
  concepts/permissions-reference.md
  concepts/viva-learning-concept-overview.md
Labels: external, conflicting

#17693 minor fixes to the To Do API
  api-reference/beta/api/todotasklist-get.md
  api-reference/beta/resources/todotask.md
  api-reference/beta/resources/webhooks.md
  api-reference/v1.0/api/todotasklist-get.md
  api-reference/v1.0/resources/todotask.md
  api-reference/v1.0/resources/webhooks.md
Labels: ready to merge, internal

#17409 Add change log for the message hitId format changes
  api-reference/beta/resources/searchhit.md
  api-reference/v1.0/resources/searchhit.md
  changelog/Microsoft.MicrosoftSearch.json
Labels: ready to merge, internal, content review complete

#17698 Merge to publish.
  .github/fabricbot.json
  api-reference/beta/api/todotasklist-get.md
  api-reference/beta/resources/searchhit.md
  api-reference/beta/resources/todotask.md
  api-reference/beta/resources/webhooks.md
  api-reference/v1.0/api/todotasklist-get.md
  api-reference/v1.0/resources/searchhit.md
  api-reference/v1.0/resources/todotask.md
  api-reference/v1.0/resources/webhooks.md
  changelog/Microsoft.MicrosoftSearch.json
Labels: do not merge, internal

#17707 Update viva-learning-api-overview.md
  api-reference/beta/resources/viva-learning-api-overview.md
Labels: do not merge, internal

#17706 Update viva-learning-api-overview.md
  api-reference/beta/resources/viva-learning-api-overview.md
Labels: do not merge, internal

#17717 Edits in PR 17582
  api-reference/beta/api/learningcontent-update.md
  api-reference/beta/resources/employeeexperience.md
  api-reference/beta/resources/learningcontent.md
  api-reference/beta/resources/learningprovider.md
  changelog/Microsoft.Viva.Learning.json
Labels: external

#17718 Edits in PR 16264
  api-reference/beta/api/cloudpcexternalpartnersetting-get.md
  api-reference/beta/resources/cloudpcexternalpartnersetting.md
Labels: external

#17720 Edits in PR 17301
  api-reference/beta/api/virtualendpoint-list-supportedregions.md
  api-reference/beta/resources/cloudpcsupportedregion.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: external

#17708 Delete viva-learning-concept-overview.md
  concepts/viva-learning-concept-overview.md
Labels: do not merge, internal

#17725 Update identity.md
  api-reference/beta/resources/identity.md
Labels: external

#17723 Update identity.md
  api-reference/v1.0/resources/identity.md
Labels: external

#17722 Update reportroot.md
  api-reference/beta/resources/reportroot.md
Labels: external

#17241 added get/update team photo from beta to v1
  api-reference/beta/api/profilephoto-get.md
  api-reference/beta/api/profilephoto-update.md
  api-reference/beta/api/team-get-photo.md
  api-reference/beta/resources/profilephoto.md
  api-reference/beta/resources/team.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/profilephoto-get.md
  api-reference/v1.0/api/profilephoto-update.md
  api-reference/v1.0/resources/profilephoto.md
  api-reference/v1.0/resources/team.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.Teams.Core.json
  changelog/Microsoft.Teams.GraphSvc.json
  concepts/changelog-archive.md
Labels: ready to merge, internal, content review complete

#17365 Graph additions to V1
  api-reference/v1.0/api/bookingappointment-cancel.md
  api-reference/v1.0/api/bookingappointment-delete.md
  api-reference/v1.0/api/bookingappointment-get.md
  api-reference/v1.0/api/bookingappointment-update.md
  api-reference/v1.0/api/bookingbusiness-get.md
  api-reference/v1.0/api/bookingbusiness-getstaffavailability.md
  api-reference/v1.0/api/bookingbusiness-list-appointments.md
  api-reference/v1.0/api/bookingbusiness-list-calendarview.md
  api-reference/v1.0/api/bookingbusiness-list-services.md
  api-reference/v1.0/api/bookingbusiness-list-staffmembers.md
  api-reference/v1.0/api/bookingbusiness-list.md
  api-reference/v1.0/api/bookingbusiness-post-appointments.md
  api-reference/v1.0/api/bookingcustomer-delete.md
  api-reference/v1.0/api/bookingcustomer-get.md
  api-reference/v1.0/api/bookingcustomer-update.md
  api-reference/v1.0/api/bookingcustomquestion-get.md
  api-reference/v1.0/api/bookingservice-get.md
  api-reference/v1.0/api/bookingstaffmember-get.md
  api-reference/v1.0/resources/availabilityitem.md
  api-reference/v1.0/resources/bookingappointment.md
  api-reference/v1.0/resources/bookingbusiness.md
  api-reference/v1.0/resources/enums.md
  api-reference/v1.0/resources/staffavailabilityitem.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.Bookings.json
Labels: ready to merge, internal, content review complete

#17657 ESS scale change
  api-reference/v1.0/resources/indexing-api-overview.md
Labels: ready to merge, internal

#17711 fix parameters for using a refresh token
  concepts/auth-v2-user.md
Labels: area: authentication, area: Azure AD, external, ready to merge, content review complete

#17716 Minor doc fixes
  api-reference/beta/api/opentypeextension-delete.md
  api-reference/beta/api/opentypeextension-get.md
  api-reference/beta/api/opentypeextension-post-opentypeextension.md
  api-reference/beta/api/opentypeextension-update.md
  api-reference/beta/resources/delegatedadminrelationships-api-overview.md
  concepts/extensibility-overview.md
  concepts/toc.yml
Labels: area: Azure AD, ready to merge, internal

#17255 Add doc for adminReportSettings API
  api-reference/beta/api/adminreportsettings-get.md
  api-reference/beta/api/adminreportsettings-update.md
  api-reference/beta/resources/admin.md
  api-reference/beta/resources/adminreportsettings.md
  api-reference/beta/resources/report.md
  api-reference/beta/toc.yml
  changelog/Microsoft.O365Reporting.json
Labels: ready to merge, content review complete, review feedback addressed

#17724 Adding details for notifications, create jobs and list printer shares
  api-reference/beta/api/print-list-printers.md
  api-reference/beta/api/print-list-shares.md
  api-reference/beta/api/printer-post-jobs.md
  api-reference/beta/api/printershare-post-jobs.md
  api-reference/v1.0/api/print-list-printers.md
  api-reference/v1.0/api/print-list-shares.md
  api-reference/v1.0/api/printer-post-jobs.md
  api-reference/v1.0/api/printershare-post-jobs.md
  concepts/universal-print-webhook-notifications.md
  concepts/upload-data-to-upload-session.md
Labels: ready to merge, internal, area: universal print

#16852 Windows Updates: Add resourceConnection and operationalInsightsConnection
  api-reference/beta/api/windowsupdates-operationalinsightsconnection-delete.md
  api-reference/beta/api/windowsupdates-operationalinsightsconnection-get.md
  api-reference/beta/api/windowsupdates-resourceconnection-delete.md
  api-reference/beta/api/windowsupdates-resourceconnection-get.md
  api-reference/beta/api/windowsupdates-updates-list-resourceconnections-operationalinsightsconnection.md
  api-reference/beta/api/windowsupdates-updates-list-resourceconnections.md
  api-reference/beta/api/windowsupdates-updates-post-resourceconnections-operationalinsightsconnection.md
  api-reference/beta/resources/enums-windowsupdates.md
  api-reference/beta/resources/windowsupdates-operationalinsightsconnection.md
  api-reference/beta/resources/windowsupdates-resourceconnection.md
  api-reference/beta/resources/windowsupdates-updates.md
  api-reference/beta/toc.yml
  changelog/Microsoft.WindowsUpdates.json
Labels: awaiting internal response, ready to merge, internal, review feedback addressed

#16242 Add security threat submission beta api docs
  api-reference/beta/api/security-emailthreatsubmission-get.md
  api-reference/beta/api/security-emailthreatsubmission-list.md
  api-reference/beta/api/security-emailthreatsubmission-post-emailthreats.md
  api-reference/beta/api/security-emailthreatsubmission-review.md
  api-reference/beta/api/security-emailthreatsubmissionpolicy-delete.md
  api-reference/beta/api/security-emailthreatsubmissionpolicy-get.md
  api-reference/beta/api/security-emailthreatsubmissionpolicy-list.md
  api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md
  api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md
  api-reference/beta/api/security-filethreatsubmission-get.md
  api-reference/beta/api/security-filethreatsubmission-list.md
  api-reference/beta/api/security-filethreatsubmission-post-filethreats.md
  api-reference/beta/api/security-urlthreatsubmission-get.md
  api-reference/beta/api/security-urlthreatsubmission-list.md
  api-reference/beta/api/security-urlthreatsubmission-post-urlthreats.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/security-api-overview.md
  api-reference/beta/resources/security-attacksimulationinfo.md
  api-reference/beta/resources/security-emailcontentthreatsubmission.md
  api-reference/beta/resources/security-emailthreatsubmission.md
  api-reference/beta/resources/security-emailthreatsubmissionpolicy.md
  api-reference/beta/resources/security-emailurlthreatsubmission.md
  api-reference/beta/resources/security-filecontentthreatsubmission.md
  api-reference/beta/resources/security-filethreatsubmission.md
  api-reference/beta/resources/security-fileurlthreatsubmission.md
  api-reference/beta/resources/security-submissionadminreview.md
  api-reference/beta/resources/security-submissiondetectedfile.md
  api-reference/beta/resources/security-submissionresult.md
  api-reference/beta/resources/security-submissionuseridentity.md
  api-reference/beta/resources/security-tenantallowblocklistentryresult.md
  api-reference/beta/resources/security-tenantalloworblocklistaction.md
  api-reference/beta/resources/security-threatsubmission.md
  api-reference/beta/resources/security-urlthreatsubmission.md
  api-reference/beta/resources/security.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Security.Submission.json
  concepts/security-concept-overview.md
Labels: ready to merge, internal, content review complete

#17758 Edits in PR 17654
  api-reference/beta/api/tenantadmin-settings-update.md
  api-reference/beta/resources/tenantadmin-idlesessionsignout.md
  api-reference/beta/resources/tenantadmin-settings.md
  changelog/Microsoft.FileServices.json
Labels: external

#17760 Edits in PR 17654
  api-reference/beta/resources/tenantadmin-idlesessionsignout.md
Labels: external

#17765 Update applicationtemplate-get.md
  api-reference/v1.0/api/applicationtemplate-get.md
Labels: do not merge, ready to merge, internal

#17761 Update application-list-extensionproperty.md
  api-reference/v1.0/api/application-list-extensionproperty.md
Labels: do not merge, ready to merge, internal

#17181 Add communications identity types
  api-reference/beta/resources/azurecommunicationservicesuseridentity.md
  api-reference/beta/resources/communicationsapplicationidentity.md
  api-reference/beta/resources/communicationsapplicationinstanceidentity.md
  api-reference/beta/resources/communicationsencryptedidentity.md
  api-reference/beta/resources/communicationsguestidentity.md
  api-reference/beta/resources/communicationsidentityset.md
  api-reference/beta/resources/communicationsphoneidentity.md
  api-reference/beta/resources/communicationsuseridentity.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/invitationparticipantinfo.md
  api-reference/beta/resources/participantinfo.md
  changelog/Microsoft.Skype.Calling.json
Labels: ready to merge, internal, content review complete

#17601 Adding self permissions for Tab resource in Teams.
  api-reference/beta/api/channel-delete-tabs.md
  api-reference/beta/api/channel-get-tabs.md
  api-reference/beta/api/channel-list-tabs.md
  api-reference/beta/api/channel-patch-tabs.md
  api-reference/beta/api/channel-post-tabs.md
  api-reference/beta/api/chat-delete-tabs.md
  api-reference/beta/api/chat-get-tabs.md
  api-reference/beta/api/chat-list-tabs.md
  api-reference/beta/api/chat-patch-tabs.md
  api-reference/beta/api/chat-post-tabs.md
  api-reference/v1.0/api/channel-delete-tabs.md
  api-reference/v1.0/api/channel-get-tabs.md
  api-reference/v1.0/api/channel-list-tabs.md
  api-reference/v1.0/api/channel-patch-tabs.md
  api-reference/v1.0/api/channel-post-tabs.md
  api-reference/v1.0/api/chat-delete-tabs.md
  api-reference/v1.0/api/chat-get-tabs.md
  api-reference/v1.0/api/chat-list-tabs.md
  api-reference/v1.0/api/chat-patch-tabs.md
  api-reference/v1.0/api/chat-post-tabs.md
  changelog/Microsoft.Teams.GraphSvc.json
  concepts/permissions-reference.md
Labels: ready to merge, content review complete

#17649 Resolve #16460 - Clarify resetScope values
  api-reference/beta/resources/synchronization-synchronizationjobrestartcriteria.md
Labels: area: Azure AD, ready to merge, internal

#17705 Fixed required permissions for mobility APIs
  api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md
  api-reference/beta/api/mobileappmanagementpolicies-update.md
  api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md
  api-reference/beta/api/mobiledevicemanagementpolicies-update.md
Labels: ready to merge, internal, content review complete

#17745 Update administrativeunit-get-members.md
  api-reference/v1.0/api/administrativeunit-get-members.md
Labels: do not merge, ready to merge, internal

#17747 Update administrativeunit-list-scopedrolemembers.md
  api-reference/v1.0/api/administrativeunit-list-scopedrolemembers.md
Labels: do not merge, ready to merge, internal

#17748 Update administrativeunit-list-members.md
  api-reference/v1.0/api/administrativeunit-list-members.md
Labels: do not merge, ready to merge, internal

#17749 Update activitybasedtimeoutpolicy-get.md
  api-reference/v1.0/api/activitybasedtimeoutpolicy-get.md
Labels: do not merge, ready to merge, internal

#17750 Update activitybasedtimeoutpolicy-list.md
  api-reference/v1.0/api/activitybasedtimeoutpolicy-list.md
Labels: do not merge, ready to merge, internal

#17246 Virtual Appointment Beta Documentation
  api-reference/beta/api/virtualappointment-delete.md
  api-reference/beta/api/virtualappointment-get.md
  api-reference/beta/api/virtualappointment-put.md
  api-reference/beta/api/virtualappointment-update.md
  api-reference/beta/resources/virtualappointment.md
  api-reference/beta/resources/virtualappointmentsettings.md
  api-reference/beta/resources/virtualappointmentuser.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Skype.Calling.json
Labels: ready to merge, internal, content review complete

#17752 Update agreement-get.md
  api-reference/v1.0/api/agreement-get.md
Labels: do not merge, ready to merge, internal

#17753 Update alert-get.md
  api-reference/v1.0/api/alert-get.md
Labels: do not merge, ready to merge, internal

#17755 Update application-get.md
  api-reference/v1.0/api/application-get.md
Labels: do not merge, ready to merge, internal

#17757 erikre-graph-15009273
  changelog/Microsoft.Intune.json
Labels: area: intune, ready to merge, internal

#17762 Update application-list-owners.md
  api-reference/v1.0/api/application-list-owners.md
Labels: do not merge, ready to merge, internal

#17763 Update application-list-tokenissuancepolicies.md
  api-reference/v1.0/api/application-list-tokenissuancepolicies.md
Labels: do not merge, ready to merge

#17764 Update application-list-tokenlifetimepolicies.md
  api-reference/v1.0/api/application-list-tokenlifetimepolicies.md
Labels: do not merge, ready to merge, internal

#17766 Update attachment-get.md
  api-reference/v1.0/api/attachment-get.md
Labels: do not merge, ready to merge, internal

#17767 Update authentication-list-methods.md
  api-reference/v1.0/api/authentication-list-methods.md
Labels: do not merge, ready to merge, internal

#17774 Update administrativeunit-get.md
  api-reference/v1.0/api/administrativeunit-get.md
Labels: ready to merge, internal

#17046 Adding the mention of TeamsFx in providers page
  concepts/toolkit/providers/providers.md
Labels: ready to merge, internal, content review complete

#17233 Adding new reports api details
  api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md
  api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md
  api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md
  api-reference/beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md
  api-reference/beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md
  api-reference/beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md
  api-reference/beta/includes/attacksim-deprecate-queryurl-reportapi.md
  api-reference/beta/resources/report-m365defender-reports-overview.md
  api-reference/beta/resources/reportroot.md
  api-reference/beta/resources/securityreportsroot.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Security.AttackSimulation.json
Labels: area: security, do not merge, ready to merge, internal, content review complete

#17301 [CloudPC]Bizhao/Add regionStatus to supported region
  api-reference/beta/api/virtualendpoint-list-supportedregions.md
  api-reference/beta/resources/cloudpcsupportedregion.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, content review complete, schema live

#17785 Daily publishing July 20th, 2022
  api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md
  api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md
  api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md
  api-reference/beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md
  api-reference/beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md
  api-reference/beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md
  api-reference/beta/api/virtualendpoint-list-supportedregions.md
  api-reference/beta/includes/attacksim-deprecate-queryurl-reportapi.md
  api-reference/beta/resources/cloudpcsupportedregion.md
  api-reference/beta/resources/report-m365defender-reports-overview.md
  api-reference/beta/resources/reportroot.md
  api-reference/beta/resources/securityreportsroot.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/administrativeunit-get.md
  changelog/Microsoft.CloudManagedDesktop.json
  changelog/Microsoft.Security.AttackSimulation.json
  concepts/toolkit/providers/providers.md
Labels: internal

#17780 Edits in PR 17646
  api-reference/beta/api/educationsubmission-setupResourcesFolder.md
  api-reference/v1.0/api/educationsubmission-setupResourcesFolder.md
Labels: external

#17783 Update directory-deleteditems-get.md
  api-reference/v1.0/api/directory-deleteditems-get.md
Labels: external

#17784 Update directory-deleteditems-get.md
  api-reference/beta/api/directory-deleteditems-get.md
Labels: external

#17778 Edits in PR 17407
  api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
Labels: external, ready to merge

#17773 Update administrativeunit-get-scopedrolemembers.md
  api-reference/v1.0/api/administrativeunit-get-scopedrolemembers.md
Labels: ready to merge, internal

#17787 Fixed issues with the try it experience across several API ref topics
  api-reference/v1.0/api/.workforceintegration-list.md.swp
  api-reference/v1.0/api/authentication-list-temporaryaccesspassmethods.md
  api-reference/v1.0/api/authenticationmethod-get.md
  api-reference/v1.0/api/authorizationpolicy-get.md
  api-reference/v1.0/api/bundle-get.md
  api-reference/v1.0/api/bundle-list.md
  api-reference/v1.0/api/calendargroup-get.md
  api-reference/v1.0/api/calendargroup-list-calendars.md
  api-reference/v1.0/api/calendarpermission-get.md
  api-reference/v1.0/api/call-get.md
  api-reference/v1.0/api/call-list-participants.md
  api-reference/v1.0/api/callrecords-callrecord-get.md
  api-reference/v1.0/api/callrecords-session-list.md
  api-reference/v1.0/api/certificatebasedauthconfiguration-get.md
  api-reference/v1.0/api/certificatebasedauthconfiguration-list.md
  api-reference/v1.0/api/channel-get-filesfolder.md
  api-reference/v1.0/api/channel-get-members.md
  api-reference/v1.0/api/channel-list-messages.md
  api-reference/v1.0/api/channel-list-tabs.md
  api-reference/v1.0/api/chart-get.md
  api-reference/v1.0/api/chart-list-series.md
  api-reference/v1.0/api/chart-list.md
  api-reference/v1.0/api/chartaxis-get.md
  api-reference/v1.0/api/chartaxistitle-get.md
  api-reference/v1.0/api/chartdatalabels-get.md
  api-reference/v1.0/api/chartfont-get.md
  api-reference/v1.0/api/chartgridlines-get.md
  api-reference/v1.0/api/chartlegend-get.md
  api-reference/v1.0/api/chartlineformat-get.md
  api-reference/v1.0/api/chartpoint-get.md
  api-reference/v1.0/api/chartpoint-list.md
  api-reference/v1.0/api/chartseries-get.md
  api-reference/v1.0/api/chartseries-list-points.md
  api-reference/v1.0/api/chartseries-list.md
  api-reference/v1.0/api/charttitle-get.md
  api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md
  api-reference/v1.0/api/userteamwork-get-installedapps.md
  api-reference/v1.0/api/userteamwork-list-installedapps.md
  api-reference/v1.0/api/workforceintegration-get.md
Labels: ready to merge, internal
