Repository microsoftgraph/microsoft-graph-docs, pull requests merged in 2022-10, with the labels that each got.

#17801 Clarify limit on length of scope property of oauth2PermissionGrant
  api-reference/beta/api/oauth2permissiongrant-post.md
  api-reference/beta/api/oauth2permissiongrant-update.md
  api-reference/beta/resources/oauth2permissiongrant.md
  api-reference/v1.0/api/oauth2permissiongrant-post.md
  api-reference/v1.0/api/oauth2permissiongrant-update.md
  api-reference/v1.0/resources/oauth2permissiongrant.md
Labels: ready to merge, internal, content review complete

#18496 Create Assignment - fix request body and update response
  api-reference/beta/api/educationclass-post-assignments.md
  api-reference/v1.0/api/educationclass-post-assignment.md
Labels: ready to merge, internal, content review complete, schema live

#18542 DriveItem delta scanning permissions; scan guidance for driveItem and listItem delta
  api-reference/beta/api/driveitem-delta.md
  api-reference/beta/api/listitem-delta.md
  api-reference/v1.0/api/driveitem-delta.md
Labels: ready to merge, internal, content review complete

#18619 Updated fabric bote file to replace docs.ms.com with learn.ms.com and added a new rule
  .github/fabricbot.json
Labels: ready to merge, internal, content review complete

#18672 Fixing permissions for 'send message in chat/channel' api
  api-reference/beta/api/channel-post-messages.md
  api-reference/beta/api/chatmessage-post-replies.md
  api-reference/beta/api/chatmessage-post.md
  api-reference/beta/api/chatmessage-update.md
  api-reference/v1.0/api/channel-post-messages.md
  api-reference/v1.0/api/chatmessage-post-replies.md
  api-reference/v1.0/api/chatmessage-post.md
  api-reference/v1.0/api/chatmessage-update.md
Labels: area: teams, ready to merge, internal, content review complete

#18638 add optional Prefer header for customized paging for ListIssues and ListMessages
  api-reference/beta/api/serviceannouncement-list-issues.md
  api-reference/beta/api/serviceannouncement-list-messages.md
  api-reference/v1.0/api/serviceannouncement-list-issues.md
  api-reference/v1.0/api/serviceannouncement-list-messages.md
Labels: ready to merge, internal, content review complete

#18693 Update tutorial-accessreviews-roleassignments.md
  concepts/tutorial-accessreviews-roleassignments.md
Labels: area: Azure AD, ready to merge, internal

#18705 September permissions GUIDs drop
  concepts/includes/permissions-ids.md
  concepts/permissions-reference.md
Labels: area: Azure AD, ready to merge, area: permissions

#18709 Reassign identity protection docs to Etan
  api-reference/beta/api/riskdetection-get.md
  api-reference/beta/api/riskdetection-list.md
  api-reference/beta/api/riskyuser-list-history.md
  api-reference/beta/api/riskyuserhistoryitem-get.md
  api-reference/beta/api/riskyusers-confirmcompromised.md
  api-reference/beta/api/riskyusers-dismiss.md
  api-reference/beta/api/riskyusers-get.md
  api-reference/beta/api/riskyusers-list.md
  api-reference/beta/resources/identityprotection-overview.md
  api-reference/beta/resources/identityprotectionroot.md
  api-reference/beta/resources/riskdetection.md
  api-reference/beta/resources/riskuseractivity.md
  api-reference/beta/resources/riskyuser.md
  api-reference/beta/resources/riskyuserhistoryitem.md
  api-reference/beta/resources/targetresource.md
  api-reference/v1.0/api/riskdetection-get.md
  api-reference/v1.0/api/riskdetection-list.md
  api-reference/v1.0/api/riskyuser-confirmcompromised.md
  api-reference/v1.0/api/riskyuser-dismiss.md
  api-reference/v1.0/api/riskyuser-get-riskyuserhistoryitem.md
  api-reference/v1.0/api/riskyuser-get.md
  api-reference/v1.0/api/riskyuser-list-history.md
  api-reference/v1.0/api/riskyuser-list.md
  api-reference/v1.0/resources/identityprotection-overview.md
  api-reference/v1.0/resources/identityprotectionroot.md
  api-reference/v1.0/resources/riskdetection.md
  api-reference/v1.0/resources/riskuseractivity.md
  api-reference/v1.0/resources/riskyuser.md
  api-reference/v1.0/resources/riskyuserhistoryitem.md
Labels: area: Azure AD, ready to merge, internal

#16858 Adding enabled content experiences and compliance settings
  api-reference/beta/resources/enums-externalconnectors.md
  api-reference/beta/resources/externalconnectors-compliancesettings.md
  api-reference/beta/resources/externalconnectors-externalconnection.md
  api-reference/beta/resources/externalconnectors-searchsettings.md
  changelog/Microsoft.Search.json
Labels: ready to merge, internal, content review complete

#17288 Add enabled content experiences conceptual doc
  concepts/connecting-external-content-manage-connections.md
  concepts/connecting-external-content-manage-items.md
  concepts/images/connectors-images/connecting-external-content-connection-settings-adaptiveCard-target-version.png
  concepts/images/connectors-images/connecting-external-content-connection-settings-eDiscovery-result-example.png
  concepts/images/connectors-images/overview.png
Labels: ready to merge, content review complete

#18713 Fixed capitalization error
  api-reference/v1.0/resources/azure-ad-overview.md
Labels: external, ready to merge

#16167 Adding new properties for the cloud PC entities
  api-reference/beta/api/managedtenants-cloudpcdevice-get.md
  api-reference/beta/api/managedtenants-cloudpcoverview-get.md
  api-reference/beta/api/managedtenants-managedtenant-list-cloudpcdevices.md
  api-reference/beta/api/managedtenants-managedtenant-list-cloudpcsoverview.md
  api-reference/beta/resources/managedtenants-cloudpcdevice.md
  api-reference/beta/resources/managedtenants-cloudpcoverview.md
  changelog/Microsoft.MultiTenantPlatform.json
Labels: ready to merge, internal, content review complete, area: multi-tenant management

#17645 Change notifications | Support for membership changes in all the channels across the tenant
  api-reference/beta/api/subscription-delete.md
  api-reference/beta/api/subscription-get.md
  api-reference/beta/api/subscription-list.md
  api-reference/beta/api/subscription-post-subscriptions.md
  api-reference/beta/api/subscription-update.md
  api-reference/beta/resources/webhooks.md
  changelog/Microsoft.Teams.Core.json
  concepts/teams-change-notification-in-microsoft-teams-overview.md
  concepts/teams-changenotifications-teamMembership.md
  concepts/webhooks-with-resource-data.md
Labels: area: teams, ready to merge, internal, content review complete, review feedback addressed

#17981 Adding API doc for organization contact merge suggestion settings
  api-reference/beta/api/insightssettings-update.md
  api-reference/beta/api/organizationsettings-list-contactinsights.md
  api-reference/beta/resources/insightssettings.md
  api-reference/beta/resources/organizationsettings.md
  api-reference/beta/toc.yml
  changelog/Microsoft.People.json
Labels: ready to merge, internal, content review complete

#18720 Document allowed arguments for Lifecycle Workflows built-in tasks
  api-reference/beta/resources/identitygovernance-task.md
  api-reference/beta/resources/keyvaluepair.md
  concepts/identitygovernance-lifecycleworkflows-task-arguments.md
  concepts/toc.yml
Labels: area: Azure AD, ready to merge, internal, area: governance

#18736 Update printer-delete.md
  api-reference/v1.0/api/printer-delete.md
Labels: external

#18737 Update printer-delete.md
  api-reference/beta/api/printer-delete.md
Labels: external

#17589 PHP SDK 2.0.0-RC5 release
  concepts/whats-new-overview.md
Labels: ready to merge, internal, content review complete

#17933 Document filter and order by properties for each endpoint -queryparameters
  api-reference/beta/api/educationassignment-get-rubric.md
  api-reference/beta/api/educationassignment-get.md
  api-reference/beta/api/educationassignment-list-categories.md
  api-reference/beta/api/educationassignment-list-resources.md
  api-reference/beta/api/educationassignment-list-submissions.md
  api-reference/beta/api/educationassignmentresource-get.md
  api-reference/beta/api/educationcategory-get.md
  api-reference/beta/api/educationrubric-get.md
  api-reference/beta/api/educationsubmission-get.md
  api-reference/beta/api/educationsubmission-list-outcomes.md
  api-reference/beta/api/educationsubmission-list-resources.md
  api-reference/beta/api/educationsubmission-list-submittedresources.md
  api-reference/beta/api/educationsubmissionresource-get.md
  api-reference/beta/api/educationsubmittedsubmissionresource-get.md
  api-reference/beta/api/educationuser-list-assignments.md
  api-reference/beta/api/educationuser-list-rubrics.md
  api-reference/v1.0/api/educationassignment-get-rubric.md
  api-reference/v1.0/api/educationassignment-get.md
  api-reference/v1.0/api/educationassignment-list-categories.md
  api-reference/v1.0/api/educationassignment-list-resources.md
  api-reference/v1.0/api/educationassignment-list-submissions.md
  api-reference/v1.0/api/educationassignmentresource-get.md
  api-reference/v1.0/api/educationcategory-get.md
  api-reference/v1.0/api/educationclass-list-assignments.md
  api-reference/v1.0/api/educationclass-list-categories.md
  api-reference/v1.0/api/educationrubric-get.md
  api-reference/v1.0/api/educationsubmission-get.md
  api-reference/v1.0/api/educationsubmission-list-outcomes.md
  api-reference/v1.0/api/educationsubmission-list-resources.md
  api-reference/v1.0/api/educationsubmission-list-submittedresources.md
  api-reference/v1.0/api/educationsubmissionresource-get.md
  api-reference/v1.0/api/educationsubmittedsubmissionresource-get.md
  api-reference/v1.0/api/educationuser-list-assignments.md
  api-reference/v1.0/api/educationuser-list-rubrics.md
Labels: ready to merge, internal, content review complete, schema live

#18210 add project to plannerPlanContainer
  api-reference/beta/config/link-validation-config.json
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/plannerplancontainer.md
  changelog/Microsoft.Office.Tasks.json
Labels: ready to merge, internal, content review complete

#18665 Including note for PAG access reviews
  concepts/accessreviews-reviewers-concept.md
  concepts/tutorial-accessreviews-securitygroup.md
Labels: area: Azure AD, ready to merge, internal, content review complete, area: governance

#18711 Update Access Reviews Insights name from peer outlier to user-to-group affiliation.md
  api-reference/beta/api/accessreviewset-post-definitions.md
  api-reference/beta/resources/grouppeeroutlierrecommendationinsightsettings.md
  api-reference/beta/resources/membershipOutlierInsight.md
  changelog/Microsoft.IdentityGovernance.AccessReviews.json
Labels: area: Azure AD, external, ready to merge, content review complete, area: governance

#18727 Fix isAssignableToRole privilege statement
  api-reference/beta/resources/group.md
  api-reference/v1.0/resources/group.md
Labels: area: Azure AD, area: groups, ready to merge, internal

#18732 Add link to M365 reports in national clouds
  concepts/deployments.md
Labels: ready to merge, internal

#18734 Update directoryaudit.md
  api-reference/beta/resources/directoryaudit.md
  api-reference/v1.0/resources/directoryaudit.md
Labels: area: Azure AD, ready to merge, internal

#18473 added documentation changes for the notes field in Planner Graph APIs beta
  api-reference/beta/api/plannertaskdetails-get.md
  api-reference/beta/api/plannertaskdetails-update.md
  api-reference/beta/resources/plannertaskdetails.md
  changelog/Microsoft.Office.Tasks.json
Labels: ready to merge, internal, content review complete

#18501 Add XRANK doc
  api-reference/beta/resources/search-api-overview.md
  api-reference/v1.0/resources/search-api-overview.md
  concepts/search-concept-xrank.md
Labels: ready to merge, Ignite22, content review complete

#18744 Update Microsoft.Teams.Core.json
  changelog/Microsoft.Teams.Core.json
Labels: ready to merge, internal

#18760 Update reportroot-getteamsuseractivitycounts.md
  api-reference/beta/api/reportroot-getteamsuseractivitycounts.md
Labels: external

#18759 Update reportroot-getteamsuseractivitycounts.md
  api-reference/v1.0/api/reportroot-getteamsuseractivitycounts.md
Labels: external

#18758 Update reportroot-getteamsteamactivitydetail.md
  api-reference/beta/api/reportroot-getteamsteamactivitydetail.md
Labels: external

#18757 Edits in PR 17566
  api-reference/beta/resources/browser-edge-api-overview.md
  api-reference/beta/resources/internetexplorermode.md
  changelog/Microsoft.Edge.CloudSiteListManagement.json
  concepts/browser-edge-concept-overview.md
  concepts/overview-major-services.md
Labels: external

#18756 Edits in PR 17600
  api-reference/beta/api/reportroot-getm365appplatformusercounts.md
  api-reference/beta/api/reportroot-getm365appusercounts.md
  api-reference/beta/api/reportroot-getm365appuserdetail.md
  api-reference/beta/resources/microsoft-365-apps-usage-report.md
  api-reference/beta/resources/report.md
  api-reference/v1.0/api/reportroot-getm365appplatformusercounts.md
  api-reference/v1.0/api/reportroot-getm365appusercounts.md
  api-reference/v1.0/api/reportroot-getm365appuserdetail.md
  api-reference/v1.0/resources/microsoft-365-apps-usage-report.md
  api-reference/v1.0/resources/report.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.O365Reporting.json
Labels: external

#17674 3s people api
  api-reference/beta/resources/person.md
  api-reference/v1.0/resources/person.md
  concepts/changelog-archive.md
  concepts/images/people-insights-admin-center-groupcontrol.png
  concepts/images/people-insights-admin-center.png
  concepts/insights-customize-people-insights-privacy.md
  concepts/outlook-calendar-concept-overview.md
  concepts/outlook-contacts-concept-overview.md
  concepts/outlook-mail-concept-overview.md
  concepts/people-insights-overview.md
  concepts/search-concept-person.md
  concepts/search-query-parameter.md
  concepts/social-intel-concept-overview.md
  concepts/toc.yml
Labels: ready to merge, internal, content review complete

#18751 entitlement management: add missing close to HTTP block
  api-reference/beta/api/accesspackage-post-incompatiblegroup.md
Labels: area: Azure AD, ready to merge, internal, content review complete

#18747 update: Documentation to use the Developer Portal for teams
  concepts/toolkit/components/agenda.md
  concepts/toolkit/customize-components/style.md
  concepts/toolkit/providers/teams-msal2.md
  concepts/toolkit/providers/teams.md
Labels: external, ready to merge

#18762 Merge to publish.
  api-reference/beta/api/accesspackage-post-incompatiblegroup.md
  api-reference/beta/api/reportroot-getteamsteamactivitydetail.md
  api-reference/beta/api/reportroot-getteamsuseractivitycounts.md
  api-reference/beta/resources/person.md
  api-reference/v1.0/api/reportroot-getteamsuseractivitycounts.md
  api-reference/v1.0/resources/person.md
  changelog/Microsoft.Teams.Core.json
  concepts/changelog-archive.md
  concepts/images/people-insights-admin-center-groupcontrol.png
  concepts/images/people-insights-admin-center.png
  concepts/insights-customize-people-insights-privacy.md
  concepts/outlook-calendar-concept-overview.md
  concepts/outlook-contacts-concept-overview.md
  concepts/outlook-mail-concept-overview.md
  concepts/people-insights-overview.md
  concepts/search-concept-person.md
  concepts/search-query-parameter.md
  concepts/social-intel-concept-overview.md
  concepts/toc.yml
  concepts/toolkit/components/agenda.md
  concepts/toolkit/customize-components/style.md
  concepts/toolkit/providers/teams-msal2.md
  concepts/toolkit/providers/teams.md
Labels: internal

#18773 Edits in PR 17566
  api-reference/beta/api/browsersharedcookie-get.md
  api-reference/beta/resources/browser-edge-api-overview.md
  api-reference/beta/resources/browsersharedcookie.md
Labels: external

#18365 Auth strengths overview
  api-reference/beta/resources/authenticationstrengths-overview.md
  api-reference/beta/resources/conditionalaccessgrantcontrols.md
Labels: area: Azure AD, do not merge, internal, area: authentication methods

#18775 Update callrecords-session.md
  api-reference/beta/resources/callrecords-session.md
Labels: external

#18774 Update callrecords-session.md
  api-reference/v1.0/resources/callrecords-session.md
Labels: external

#18770 Edits in PR 18085
  api-reference/beta/api/teamworktag-delete.md
  api-reference/beta/api/teamworktag-get.md
  api-reference/beta/api/teamworktag-list.md
  api-reference/beta/api/teamworktag-update.md
  api-reference/beta/api/teamworktagmember-delete.md
  api-reference/beta/api/teamworktagmember-get.md
  api-reference/beta/resources/teams-api-overview.md
  api-reference/beta/resources/teamworktag.md
  api-reference/beta/resources/teamworktagmember.md
  api-reference/v1.0/api/teamworktag-delete.md
  api-reference/v1.0/api/teamworktag-get.md
  api-reference/v1.0/api/teamworktag-list.md
  api-reference/v1.0/api/teamworktag-post.md
  api-reference/v1.0/api/teamworktag-update.md
  api-reference/v1.0/api/teamworktagmember-delete.md
  api-reference/v1.0/api/teamworktagmember-get.md
  api-reference/v1.0/api/teamworktagmember-list.md
  api-reference/v1.0/api/teamworktagmember-post.md
  api-reference/v1.0/resources/teams-api-overview.md
  api-reference/v1.0/resources/teamworktag.md
  api-reference/v1.0/resources/teamworktagmember.md
  changelog/Microsoft.Teams.GraphSvc.json
Labels: external

#18777 move change screensharing role api to call
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
Labels: ready to merge

#18768 Document contains and has operators for $filter
  concepts/filter-query-parameter.md
Labels: ready to merge, internal

#18726 Update reportroot-getteamsuseractivityuserdetail.md
  api-reference/v1.0/api/reportroot-getteamsuseractivityuserdetail.md
Labels: external

#17997 Introduction of Id in Learning Content for Viva Learning Workload
  api-reference/beta/api/learningcontent-get.md
  api-reference/beta/api/learningcontent-update.md
  api-reference/beta/api/learningprovider-delete-learningcontents.md
  api-reference/beta/api/learningprovider-list-learningcontents.md
  api-reference/beta/resources/learningcontent.md
  changelog/Microsoft.Viva.Learning.json
Labels: ready to merge, internal, content review complete

#18262 Update throttling-limits.md
  concepts/throttling-limits.md
  includes/throttling-aad-reports.md
  includes/throttling-cpim.md
  includes/throttling-education-rostering-apis.md
  includes/throttling-excel.md
  includes/throttling-multi-tenant-platform.md
  includes/throttling-skype-calling.md
  includes/throttling-teams.md
Labels: ready to merge, internal

#18349 Update security-integration.md
  concepts/security-integration.md
Labels: ready to merge, internal, review feedback addressed

#18134 Changing the contributor value from String to String Collection as pe…
  api-reference/beta/api/learningcontent-get.md
  api-reference/beta/api/learningcontent-update.md
  api-reference/beta/api/learningprovider-list-learningcontents.md
  api-reference/beta/resources/learningcontent.md
  changelog/Microsoft.Viva.Learning.json
Labels: ready to merge, internal, content review complete

#18707 entitlement management: add AdminUpdate for resource requests in beta
  api-reference/beta/api/entitlementmanagement-post-accesspackageresourcerequests.md
  api-reference/beta/resources/accesspackageresource.md
  api-reference/beta/resources/accesspackageresourcerequest.md
Labels: area: Azure AD, ready to merge, internal, content review complete

#18494 Application permissions - update permissions table
  api-reference/beta/api/educationoutcome-update.md
  api-reference/beta/api/educationsubmission-reassign.md
  api-reference/beta/api/educationsubmission-return.md
  api-reference/beta/api/educationsubmission-submit.md
  api-reference/beta/api/educationsubmission-unsubmit.md
  api-reference/v1.0/api/educationoutcome-update.md
  api-reference/v1.0/api/educationsubmission-reassign.md
  api-reference/v1.0/api/educationsubmission-return.md
  api-reference/v1.0/api/educationsubmission-submit.md
  api-reference/v1.0/api/educationsubmission-unsubmit.md
  changelog/Microsoft.EducationAssignment.json
Labels: ready to merge, internal, content review complete, schema live

#18315 CA templates beta public preview
  api-reference/beta/api/conditionalaccessroot-list-templates.md
  api-reference/beta/api/conditionalaccesstemplate-get.md
  api-reference/beta/resources/conditionalaccesspolicydetail.md
  api-reference/beta/resources/conditionalaccessroot.md
  api-reference/beta/resources/conditionalaccesstemplate.md
  api-reference/beta/resources/enums.md
  api-reference/beta/toc.yml
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, ready to merge, internal, content review complete

#18717 Set and unset reaction doc update
  api-reference/beta/api/chatmessage-setreaction.md
  api-reference/beta/api/chatmessage-unsetreaction.md
  api-reference/beta/resources/chatmessage.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Teams.Core.json
Labels: do not merge, ready to merge, internal, content review complete

#16144 Documentation for getting list of recently used shared printers
  api-reference/beta/api/print-list-recentshares.md
  api-reference/beta/resources/printershare.md
  api-reference/beta/resources/printershareviewpoint.md
  api-reference/beta/toc.yml
  changelog/Microsoft.PrintService.json
Labels: internal, area: universal print, content review complete, schema live

#18341 Update driveitem.md
  api-reference/beta/resources/driveitem.md
  api-reference/v1.0/resources/driveitem.md
Labels: ready to merge, internal, content review complete

#18779 Merge to publish.
  api-reference/beta/api/chatmessage-setreaction.md
  api-reference/beta/api/chatmessage-unsetreaction.md
  api-reference/beta/api/conditionalaccessroot-list-templates.md
  api-reference/beta/api/conditionalaccesstemplate-get.md
  api-reference/beta/api/educationoutcome-update.md
  api-reference/beta/api/educationsubmission-reassign.md
  api-reference/beta/api/educationsubmission-return.md
  api-reference/beta/api/educationsubmission-submit.md
  api-reference/beta/api/educationsubmission-unsubmit.md
  api-reference/beta/api/entitlementmanagement-post-accesspackageresourcerequests.md
  api-reference/beta/api/learningcontent-get.md
  api-reference/beta/api/learningcontent-update.md
  api-reference/beta/api/learningprovider-delete-learningcontents.md
  api-reference/beta/api/learningprovider-list-learningcontents.md
  api-reference/beta/api/print-list-recentshares.md
  api-reference/beta/resources/accesspackageresource.md
  api-reference/beta/resources/accesspackageresourcerequest.md
  api-reference/beta/resources/callrecords-session.md
  api-reference/beta/resources/chatmessage.md
  api-reference/beta/resources/conditionalaccesspolicydetail.md
  api-reference/beta/resources/conditionalaccessroot.md
  api-reference/beta/resources/conditionalaccesstemplate.md
  api-reference/beta/resources/driveitem.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/learningcontent.md
  api-reference/beta/resources/printershare.md
  api-reference/beta/resources/printershareviewpoint.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/educationoutcome-update.md
  api-reference/v1.0/api/educationsubmission-reassign.md
  api-reference/v1.0/api/educationsubmission-return.md
  api-reference/v1.0/api/educationsubmission-submit.md
  api-reference/v1.0/api/educationsubmission-unsubmit.md
  api-reference/v1.0/api/reportroot-getteamsuseractivityuserdetail.md
  api-reference/v1.0/resources/callrecords-session.md
  api-reference/v1.0/resources/driveitem.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.DirectoryServices.json
  changelog/Microsoft.EducationAssignment.json
  changelog/Microsoft.PrintService.json
  changelog/Microsoft.Teams.Core.json
  changelog/Microsoft.Viva.Learning.json
  concepts/filter-query-parameter.md
  concepts/security-integration.md
  concepts/throttling-limits.md
  includes/throttling-aad-reports.md
  includes/throttling-cpim.md
  includes/throttling-education-rostering-apis.md
  includes/throttling-excel.md
  includes/throttling-multi-tenant-platform.md
  includes/throttling-skype-calling.md
  includes/throttling-teams.md
Labels: internal

#18785 Update cloudpcusersetting.md
  api-reference/beta/resources/cloudpcusersetting.md
Labels: external

#18783 Update use-postman.md
  concepts/use-postman.md
Labels: external, ready to merge

#18667 Update json-batching.md
  concepts/json-batching.md
Labels: ready to merge, content review complete

#18806 Edits in PR 17441
  api-reference/beta/api/bookingstaffmember-update.md
  api-reference/beta/resources/bookingappointment.md
  api-reference/beta/resources/bookingbusiness.md
  api-reference/beta/resources/bookingstaffmember.md
  api-reference/beta/resources/enums.md
  api-reference/v1.0/api/bookingstaffmember-update.md
  api-reference/v1.0/resources/bookingappointment.md
  api-reference/v1.0/resources/bookingbusiness.md
  api-reference/v1.0/resources/bookingcustomerinformation.md
  api-reference/v1.0/resources/bookingservice.md
  api-reference/v1.0/resources/bookingstaffmember.md
  api-reference/v1.0/resources/enums.md
  changelog/Microsoft.Bookings.json
Labels: external

#18107 Support Bookmark And Acronym Searching
  api-reference/beta/resources/search-api-overview.md
  concepts/search-concept-acronym.md
  concepts/search-concept-bookmark.md
  concepts/toc.yml
  includes/search-schema-updated.md
Labels: ready to merge, internal, content review complete

#17871 entitlement management: introduce SOD relationships to v1.0
  api-reference/v1.0/api/accesspackage-delete-incompatibleaccesspackage.md
  api-reference/v1.0/api/accesspackage-delete-incompatiblegroup.md
  api-reference/v1.0/api/accesspackage-list-accesspackagesincompatiblewith.md
  api-reference/v1.0/api/accesspackage-list-incompatibleaccesspackages.md
  api-reference/v1.0/api/accesspackage-list-incompatiblegroups.md
  api-reference/v1.0/api/accesspackage-post-incompatibleaccesspackage.md
  api-reference/v1.0/api/accesspackage-post-incompatiblegroup.md
  api-reference/v1.0/api/accesspackageassignment-additionalaccess.md
  api-reference/v1.0/resources/accesspackage.md
  api-reference/v1.0/resources/accesspackageassignment.md
  api-reference/v1.0/resources/entitlementmanagement-overview.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.IGAELM.json
Labels: area: Azure AD, do not merge, ready to merge, internal, content review complete, schema live

#17305 Append Change Log For Supporting Bookmark/Acronyms/Teamschatmessage
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/searchrequest.md
  changelog/Microsoft.MicrosoftSearch.json
Labels: ready to merge, internal, content review complete

#18752 Fixing permission required for sensitivity label APIs
  api-reference/beta/api/driveitem-assignsensitivitylabel.md
  api-reference/beta/api/driveitem-extractsensitivitylabels.md
Labels: ready to merge, internal, Ignite22

#18352 Adding troubleshooting page
  concepts/data-connect-faq.md
  concepts/data-connect-troubleshooting.md
  concepts/images/data-connect-azure-storage-network-new.png
  concepts/images/data-connect-troubleshooting-PAM.png
  concepts/images/data-connect-troubleshooting-azure-IR-1.png
  concepts/images/data-connect-troubleshooting-azure-IR-2.png
  concepts/images/data-connect-troubleshooting-copy-adf.png
  concepts/images/data-connect-troubleshooting-spn.png
  concepts/images/data-connect-viva-insights-mgdc.png
  concepts/toc.yml
  includes/data-connect-quickstart-04.md
  includes/data-connect-quickstart-06.md
Labels: ready to merge, internal, Ignite22, content review complete

#18220 Add Bookmark.read.all And Acronym.read.all Permission
  changelog/Microsoft.MicrosoftSearch.json
  concepts/permissions-reference.md
Labels: ready to merge, internal, area: permissions, content review complete, review feedback addressed

#17904 07 22 search all
  api-reference/beta/api/search-query.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/search-api-overview.md
  api-reference/beta/resources/searchrequest.md
  api-reference/beta/resources/sharepointonedriveoptions.md
  api-reference/v1.0/resources/search-api-overview.md
  changelog/Microsoft.Search.json
  concepts/search-concept-searchall.md
  concepts/toc.yml
Labels: ready to merge, internal, Ignite22, content review complete

#18388 Move isEnabled and isSchedulingEnabled proeprties from Workflow to WorkflowBase
  api-reference/beta/api/identitygovernance-workflow-list-versions.md
  api-reference/beta/api/identitygovernance-workflowversion-get.md
  api-reference/beta/resources/identitygovernance-workflow.md
  api-reference/beta/resources/identitygovernance-workflowbase.md
  api-reference/beta/resources/identitygovernance-workflowversion.md
  changelog/Microsoft.AAD.LCM.json
Labels: area: Azure AD, ready to merge, internal, Ignite22, content review complete

#18697 Promote /sendActivityNotificationToRecipients API to v1
  api-reference/v1.0/api/teamwork-sendactivitynotificationtorecipients.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.Teams.Core.json
  concepts/teams-send-activityfeednotifications.md
Labels: ready to merge, internal, Ignite22, content review complete

#18791 Updating structured properties
  api-reference/v1.0/api/contact-update.md
Labels: ready to merge, internal, customer support issue, content review complete

#18807 Merge to publish.
  api-reference/beta/api/driveitem-assignsensitivitylabel.md
  api-reference/beta/api/driveitem-extractsensitivitylabels.md
  api-reference/beta/api/identitygovernance-workflow-list-versions.md
  api-reference/beta/api/identitygovernance-workflowversion-get.md
  api-reference/beta/api/search-query.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/identitygovernance-workflow.md
  api-reference/beta/resources/identitygovernance-workflowbase.md
  api-reference/beta/resources/identitygovernance-workflowversion.md
  api-reference/beta/resources/search-api-overview.md
  api-reference/beta/resources/searchrequest.md
  api-reference/beta/resources/sharepointonedriveoptions.md
  api-reference/v1.0/api/accesspackage-delete-incompatibleaccesspackage.md
  api-reference/v1.0/api/accesspackage-delete-incompatiblegroup.md
  api-reference/v1.0/api/accesspackage-list-accesspackagesincompatiblewith.md
  api-reference/v1.0/api/accesspackage-list-incompatibleaccesspackages.md
  api-reference/v1.0/api/accesspackage-list-incompatiblegroups.md
  api-reference/v1.0/api/accesspackage-post-incompatibleaccesspackage.md
  api-reference/v1.0/api/accesspackage-post-incompatiblegroup.md
  api-reference/v1.0/api/accesspackageassignment-additionalaccess.md
  api-reference/v1.0/api/contact-update.md
  api-reference/v1.0/api/teamwork-sendactivitynotificationtorecipients.md
  api-reference/v1.0/resources/accesspackage.md
  api-reference/v1.0/resources/accesspackageassignment.md
  api-reference/v1.0/resources/entitlementmanagement-overview.md
  api-reference/v1.0/resources/search-api-overview.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.AAD.LCM.json
  changelog/Microsoft.IGAELM.json
  changelog/Microsoft.MicrosoftSearch.json
  changelog/Microsoft.Search.json
  changelog/Microsoft.Teams.Core.json
  concepts/data-connect-faq.md
  concepts/data-connect-troubleshooting.md
  concepts/images/data-connect-azure-storage-network-new.png
  concepts/images/data-connect-troubleshooting-PAM.png
  concepts/images/data-connect-troubleshooting-azure-IR-1.png
  concepts/images/data-connect-troubleshooting-azure-IR-2.png
  concepts/images/data-connect-troubleshooting-copy-adf.png
  concepts/images/data-connect-troubleshooting-spn.png
  concepts/images/data-connect-viva-insights-mgdc.png
  concepts/permissions-reference.md
  concepts/search-concept-acronym.md
  concepts/search-concept-bookmark.md
  concepts/search-concept-searchall.md
  concepts/teams-send-activityfeednotifications.md
  concepts/toc.yml
  includes/data-connect-quickstart-04.md
  includes/data-connect-quickstart-06.md
  includes/search-schema-updated.md
Labels: do not merge, internal

#18811 Bringing what's new up-to-date through end of Sept.
  api-reference/beta/api/user-list-approleassignedresources.md
  api-reference/beta/resources/security-api-overview.md
  api-reference/beta/resources/user.md
  api-reference/beta/toc.yml
  api-reference/v1.0/resources/security-api-overview.md
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: internal

#18813 Refresh the what's new topic to include updates in the second half of September.
  api-reference/beta/api/user-list-approleassignedresources.md
  api-reference/beta/resources/security-api-overview.md
  api-reference/beta/resources/user.md
  api-reference/beta/toc.yml
  api-reference/v1.0/resources/security-api-overview.md
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: internal

#18823 Edits in PR 18629
  api-reference/beta/api/chat-list-messages.md
  api-reference/v1.0/api/chat-list-messages.md
  changelog/Microsoft.Teams.Core.json
Labels: external

#18821 Use relative paths for links and remove image
  concepts/teams-licenses.md
Labels: do not merge, ready for content review, internal

#18826 Update chat-sendactivitynotification.md
  api-reference/v1.0/api/chat-sendactivitynotification.md
Labels: external

#18825 Update chat-sendactivitynotification.md
  api-reference/beta/api/chat-sendactivitynotification.md
Labels: external

#18810 Update educationassignmentdefaults-update.md
  api-reference/beta/api/educationassignmentdefaults-update.md
Labels: external

#18246 Cbagraphv1.0
  api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-delete.md
  api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-get.md
  api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-update.md
  api-reference/v1.0/resources/authenticationmethodspolicies-overview.md
  api-reference/v1.0/resources/enums.md
  api-reference/v1.0/resources/x509certificateauthenticationmethodconfiguration.md
  api-reference/v1.0/resources/x509certificateauthenticationmodeconfiguration.md
  api-reference/v1.0/resources/x509certificaterule.md
  api-reference/v1.0/resources/x509certificateuserbinding.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, ready to merge, internal, Ignite22, content review complete, schema live

#18443 Rchanda1392 graphconnectors
  concepts/custom-connector-sdk-best-practices.md
  concepts/custom-connector-sdk-contracts-common.md
  concepts/custom-connector-sdk-contracts-connectionmanagement.md
  concepts/custom-connector-sdk-contracts-connectorcrawler.md
  concepts/custom-connector-sdk-contracts-connectorinfo.md
  concepts/custom-connector-sdk-contracts-connectoroauth.md
  concepts/custom-connector-sdk-contracts-services.md
  concepts/custom-connector-sdk-overview.md
  concepts/custom-connector-sdk-publish.md
  concepts/custom-connector-sdk-sample-create.md
  concepts/custom-connector-sdk-sample-overview.md
  concepts/custom-connector-sdk-sample-test.md
  concepts/custom-connector-sdk-testapp.md
  concepts/custom-connector-sdk-troubleshooting.md
  concepts/toc.yml
Labels: ready to merge, internal, content review complete, review feedback addressed, area: connectors

#18674 Update riskdetection.md
  api-reference/beta/resources/riskdetection.md
Labels: area: Azure AD, awaiting internal response, ready to merge, internal, content review complete

#18677 Update riskdetection.md
  api-reference/v1.0/resources/riskdetection.md
Labels: area: Azure AD, awaiting internal response, ready to merge, internal, content review complete

#18814 Add missing sample keys and fix wrong ones
  api-reference/beta/api/calltranscript-get.md
  api-reference/beta/api/driveitem-assignsensitivitylabel.md
  api-reference/beta/api/driveitem-createlink.md
  api-reference/beta/api/educationassignment-setupresourcesfolder.md
  api-reference/beta/api/educationassignmentresource-get.md
  api-reference/beta/api/identitygovernance-task-get.md
  api-reference/beta/api/identitygovernance-taskprocessingresult-resume.md
  api-reference/beta/api/identitygovernance-workflowversion-get.md
  api-reference/beta/api/identitygovernance-workflowversion-list-tasks.md
  api-reference/beta/api/listitem-createlink.md
  api-reference/beta/api/onlinemeeting-list-transcripts.md
  api-reference/beta/api/place-list.md
  api-reference/beta/api/riskdetection-get.md
  api-reference/beta/api/riskyusers-get.md
  api-reference/beta/api/security-informationprotection-list-sensitivitylabels.md
  api-reference/beta/api/security-informationprotectionpolicysetting-get.md
  api-reference/beta/api/security-sensitivitylabel-evaluateapplication.md
  api-reference/beta/api/security-sensitivitylabel-evaluateclassificationresults.md
  api-reference/beta/api/security-sensitivitylabel-evaluateremoval.md
  api-reference/beta/api/security-sensitivitylabel-extractcontentlabel.md
  api-reference/beta/api/security-sensitivitylabel-get.md
  api-reference/beta/api/sharedwithchannelteaminfo-list.md
  api-reference/v1.0/api/authentication-post-emailmethods.md
  api-reference/v1.0/api/calendar-post-calendarpermissions.md
  api-reference/v1.0/api/chat-get-members.md
  api-reference/v1.0/api/chat-get.md
  api-reference/v1.0/api/educationassignment-delete.md
  api-reference/v1.0/api/educationassignment-setupresourcesfolder.md
  api-reference/v1.0/api/educationassignmentresource-get.md
  api-reference/v1.0/api/emailauthenticationmethod-delete.md
  api-reference/v1.0/api/emailauthenticationmethod-update.md
  api-reference/v1.0/api/group-get.md
  api-reference/v1.0/api/messagerule-get.md
  api-reference/v1.0/api/outlookcategory-get.md
  api-reference/v1.0/api/place-get.md
  api-reference/v1.0/api/schemaextension-get.md
  api-reference/v1.0/api/softwareoathauthenticationmethod-delete.md
  api-reference/v1.0/api/subscribedsku-get.md
  api-reference/v1.0/api/team-update-members.md
Labels: ready to merge, internal, content review complete

#18816 Correct the teams search documentation error
  concepts/search-concept-chat-messages.md
Labels: ready to merge, Ignite22

#18256 [CloudPC]Add Alerting docs
  api-reference/beta/api/devicemanagement-alertrecord-get.md
  api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md
  api-reference/beta/api/devicemanagement-alertrecord-list.md
  api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md
  api-reference/beta/api/devicemanagement-alertrule-get.md
  api-reference/beta/api/devicemanagement-alertrule-list.md
  api-reference/beta/api/devicemanagement-alertrule-post.md
  api-reference/beta/api/devicemanagement-alertrule-update.md
  api-reference/beta/resources/devicemanagement-alertimpact.md
  api-reference/beta/resources/devicemanagement-alertrecord.md
  api-reference/beta/resources/devicemanagement-alertrule.md
  api-reference/beta/resources/devicemanagement-monitoring.md
  api-reference/beta/resources/devicemanagement-notificationchannel.md
  api-reference/beta/resources/devicemanagement-notificationreceiver.md
  api-reference/beta/resources/devicemanagement-portalnotification.md
  api-reference/beta/resources/devicemanagement-rulethreshold.md
  api-reference/beta/toc.yml
  changelog/Microsoft.DeviceManagement.Monitoring.json
Labels: ready to merge, content review complete, schema live

#18819 Screenshot of Cost Analysis for Metered APIs
  concepts/images/cost-analysis-sample.png
  concepts/teams-licenses.md
Labels: ready to merge, internal

#18834 Added what's new in October so far.
  changelog/Microsoft.People.json
  changelog/Microsoft.Search.json
  changelog/Microsoft.Teams.Core.json
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: internal

#18835 Update teams-configuring-builtin-tabs.md
  concepts/teams-configuring-builtin-tabs.md
Labels: ready to merge, internal

#18164 Authentication Strengths documentation
  api-reference/beta/api/authenticationcombinationconfiguration-get.md
  api-reference/beta/api/authenticationcombinationconfiguration-update.md
  api-reference/beta/api/authenticationcontextclassreference-get.md
  api-reference/beta/api/authenticationmethodmodedetail-get.md
  api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md
  api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md
  api-reference/beta/api/authenticationstrengthpolicy-get.md
  api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md
  api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md
  api-reference/beta/api/authenticationstrengthpolicy-update.md
  api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md
  api-reference/beta/api/authenticationstrengthpolicy-usage.md
  api-reference/beta/api/authenticationstrengthroot-delete-policies.md
  api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md
  api-reference/beta/api/authenticationstrengthroot-list-policies.md
  api-reference/beta/api/authenticationstrengthroot-post-policies.md
  api-reference/beta/api/conditionalaccesspolicy-get.md
  api-reference/beta/api/conditionalaccessroot-list-policies.md
  api-reference/beta/resources/authenticationcombinationconfiguration.md
  api-reference/beta/resources/authenticationmethodmodedetail.md
  api-reference/beta/resources/authenticationstrengthpolicy.md
  api-reference/beta/resources/authenticationstrengthroot.md
  api-reference/beta/resources/authenticationstrengths-overview.md
  api-reference/beta/resources/authenticationstrengthusage.md
  api-reference/beta/resources/conditionalaccessgrantcontrols.md
  api-reference/beta/resources/conditionalaccessroot.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/fido2combinationconfiguration.md
  api-reference/beta/resources/policyroot.md
  api-reference/beta/resources/updateallowedcombinationsresult.md
  api-reference/beta/toc.yml
  changelog/Microsoft.AuthenticationMethodsPolicy.json
  changelog/Microsoft.IdentityProtectionServices.json
Labels: area: Azure AD, do not merge, area: authentication methods, Ignite22, content review complete

#18843 Edits in PR 18043
  api-reference/beta/resources/industrydata-aggregatedinboundstatistics.md
  api-reference/beta/resources/industrydata-filedataconnector.md
  api-reference/beta/resources/industrydata-fileuploadsession.md
  api-reference/beta/resources/industrydata-filevalidateoperation.md
  api-reference/beta/resources/industrydata-identifiertypereferencevalue.md
  api-reference/beta/resources/industrydata-inboundactivityresults.md
  api-reference/beta/resources/industrydata-inboundfileflow.md
Labels: external

#18845 Update plannerplandetails-get.md
  api-reference/beta/api/plannerplandetails-get.md
Labels: external

#18844 Update plannerplandetails-get.md
  api-reference/v1.0/api/plannerplandetails-get.md
Labels: external

#18839 Resolve #18787
  api-reference/beta/api/application-delete.md
  api-reference/beta/api/application-get.md
  api-reference/beta/api/application-update.md
  api-reference/v1.0/api/application-delete.md
  api-reference/v1.0/api/application-get.md
  api-reference/v1.0/api/application-update.md
Labels: area: Azure AD, ready to merge, internal

#18520 Adding Changelog for PATCH Chat Message Validation Update
  api-reference/beta/api/chatmessage-update.md
  changelog/Microsoft.Teams.Core.json
Labels: ready to merge, internal, content review complete

#18682 [Cloud PC]Remove description about deprecate patch addomainpassword API As deprecate period is over now.
  api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md
Labels: ready to merge, internal, content review complete

#18748 LCW - Add more examples using query parameters for GET/LIST
  api-reference/beta/api/identitygovernance-deleteditemcontainer-get.md
  api-reference/beta/api/identitygovernance-lifecycleworkflowscontainer-list-deleteditems.md
  api-reference/beta/api/identitygovernance-run-get.md
  api-reference/beta/api/identitygovernance-run-list-taskprocessingresults.md
  api-reference/beta/api/identitygovernance-run-list-userprocessingresults.md
  api-reference/beta/api/identitygovernance-taskreport-list-taskprocessingresults.md
  api-reference/beta/api/identitygovernance-userprocessingresult-get.md
  api-reference/beta/api/identitygovernance-userprocessingresult-list-taskprocessingresults.md
  api-reference/beta/api/identitygovernance-workflow-list-runs.md
  api-reference/beta/api/identitygovernance-workflow-list-taskreports.md
  api-reference/beta/api/identitygovernance-workflow-list-userprocessingresults.md
  api-reference/beta/api/identitygovernance-workflow-list-versions.md
  api-reference/beta/api/identitygovernance-workflowversion-get.md
  api-reference/beta/api/identitygovernance-workflowversion-list-tasks.md
Labels: area: Azure AD, ready to merge, internal, Ignite22, area: governance

#18749 Add info on user properties for LCW rules
  api-reference/beta/resources/identitygovernance-rulebasedsubjectset.md
Labels: area: Azure AD, ready to merge, internal, Ignite22, area: governance

#18656 Add LCW tutorials
  concepts/images/tutorial-lifecycle-workflows/arch-2.png
  concepts/toc.yml
  concepts/tutorial-lifecycle-workflows-offboard-custom-workflow.md
  concepts/tutorial-lifecycle-workflows-onboard-custom-workflow.md
  concepts/tutorial-lifecycle-workflows-scheduled-leaver.md
  concepts/tutorial-lifecycle-workflows-set-employeeleavedatetime.md
Labels: area: Azure AD, ready to merge, internal, Ignite22, area: governance

#18866 Update data-connect-troubleshooting.md
  concepts/data-connect-troubleshooting.md
Labels: external

#18868 Edits in PR 18043
  api-reference/beta/resources/industrydata-inboundflow.md
  api-reference/beta/resources/industrydata-inboundflowactivity.md
  api-reference/beta/resources/industrydata-industrydataactivity.md
  api-reference/beta/resources/industrydata-industrydataactivitystatistics.md
  api-reference/beta/resources/industrydata-industrydataconnector.md
  api-reference/beta/resources/industrydata-industrydataroot.md
  api-reference/beta/resources/industrydata-industrydatarunactivity.md
  api-reference/beta/resources/industrydata-industrydatarunentitycountmetric.md
  api-reference/beta/resources/industrydata-industrydatarunrolecountmetric.md
  api-reference/beta/resources/industrydata-industrydatarunstatistics.md
  api-reference/beta/resources/industrydata-outboundflowactivity.md
  api-reference/beta/resources/industrydata-referencedefinition.md
Labels: external

#18474 Lifecycle Workflows Overview
  .openpublishing.publish.config.json
  api-reference/beta/includes/identitygovernance-lifecycleworkflows-workflowtemplates.md
  api-reference/beta/includes/lifecycle-workflows-tasks-table.md
  api-reference/beta/resources/identitygovernance-lifecycleworkflows-overview.md
  api-reference/beta/resources/identitygovernance-lifecycleworkflows-reporting-overview.md
  api-reference/beta/resources/identitygovernance-overview.md
  api-reference/beta/resources/identitygovernance-task.md
  api-reference/beta/resources/identitygovernance-workflowtemplate.md
  api-reference/beta/toc.yml
  concepts/images/identitygovernance-workflow-parts.png
Labels: area: Azure AD, ready to merge, internal, area: governance

#18852 Change doc owner
  api-reference/beta/resources/directorysizequota.md
Labels: area: Azure AD, ready to merge, internal, area: directory management

#18853 Add has operator for taskDefinition
  api-reference/beta/api/identitygovernance-lifecycleworkflowscontainer-list-taskdefinitions.md
  api-reference/beta/resources/identitygovernance-taskdefinition.md
Labels: area: Azure AD, ready to merge, internal, area: governance

#18855 Group extensions docs
  api-reference/beta/api/application-list-extensionproperty.md
  api-reference/beta/api/application-post-extensionproperty.md
  api-reference/beta/api/extensionproperty-delete.md
  api-reference/beta/api/extensionproperty-get.md
  api-reference/beta/resources/extensionproperty.md
  api-reference/v1.0/api/application-list-extensionproperty.md
  api-reference/v1.0/api/application-post-extensionproperty.md
  api-reference/v1.0/api/extensionproperty-delete.md
  api-reference/v1.0/api/extensionproperty-get.md
  api-reference/v1.0/resources/extensionproperty.md
Labels: area: Azure AD, ready to merge, internal

#18858 Change owner of phone complex type to Dan
  api-reference/v1.0/resources/phone.md
Labels: area: Azure AD, ready to merge, internal, area: directory management

#18859 New Azure AD Graph deprecation date
  concepts/migrate-azure-ad-graph-overview.md
Labels: area: Azure AD, ready to merge, internal, API migration

#18869 Merge to publish.
  .openpublishing.publish.config.json
  api-reference/beta/api/application-list-extensionproperty.md
  api-reference/beta/api/application-post-extensionproperty.md
  api-reference/beta/api/extensionproperty-delete.md
  api-reference/beta/api/extensionproperty-get.md
  api-reference/beta/api/identitygovernance-lifecycleworkflowscontainer-list-taskdefinitions.md
  api-reference/beta/includes/identitygovernance-lifecycleworkflows-workflowtemplates.md
  api-reference/beta/includes/lifecycle-workflows-tasks-table.md
  api-reference/beta/resources/directorysizequota.md
  api-reference/beta/resources/extensionproperty.md
  api-reference/beta/resources/identitygovernance-lifecycleworkflows-overview.md
  api-reference/beta/resources/identitygovernance-lifecycleworkflows-reporting-overview.md
  api-reference/beta/resources/identitygovernance-overview.md
  api-reference/beta/resources/identitygovernance-task.md
  api-reference/beta/resources/identitygovernance-taskdefinition.md
  api-reference/beta/resources/identitygovernance-workflowtemplate.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/application-list-extensionproperty.md
  api-reference/v1.0/api/application-post-extensionproperty.md
  api-reference/v1.0/api/extensionproperty-delete.md
  api-reference/v1.0/api/extensionproperty-get.md
  api-reference/v1.0/resources/extensionproperty.md
  api-reference/v1.0/resources/phone.md
  concepts/data-connect-troubleshooting.md
  concepts/images/identitygovernance-workflow-parts.png
  concepts/migrate-azure-ad-graph-overview.md
Labels: internal

#18272 Add hunting API.
  api-reference/beta/api/security-alert-post-comments.md
  api-reference/beta/api/security-incident-post-comments.md
  api-reference/beta/api/security-security-runhuntingquery.md
  api-reference/beta/resources/security-alert.md
  api-reference/beta/resources/security-analyzedmessageevidence.md
  api-reference/beta/resources/security-api-overview.md
  api-reference/beta/resources/security-huntingqueryresults.md
  api-reference/beta/resources/security-huntingrowresult.md
  api-reference/beta/resources/security-incident.md
  api-reference/beta/resources/security-singlepropertyschema.md
  api-reference/beta/resources/security.md
  api-reference/beta/toc.yml
  changelog/Microsoft.M365.Defender.json
  concepts/permissions-reference.md
Labels: internal, schema live, content review in progress, review feedback addressed

#18872 Publish API for advanced hunting.
  api-reference/beta/api/security-alert-post-comments.md
  api-reference/beta/api/security-incident-post-comments.md
  api-reference/beta/api/security-security-runhuntingquery.md
  api-reference/beta/resources/security-alert.md
  api-reference/beta/resources/security-analyzedmessageevidence.md
  api-reference/beta/resources/security-api-overview.md
  api-reference/beta/resources/security-huntingqueryresults.md
  api-reference/beta/resources/security-huntingrowresult.md
  api-reference/beta/resources/security-incident.md
  api-reference/beta/resources/security-singlepropertyschema.md
  api-reference/beta/resources/security.md
  api-reference/beta/toc.yml
  changelog/Microsoft.M365.Defender.json
  concepts/permissions-reference.md
Labels: internal

#18879 Request Payload remove hidden unwanted characters
  api-reference/beta/api/bookingbusiness-getstaffavailability.md
Labels: ready to merge, internal, customer support issue, content review complete

#18876 Request Payload remove hidden unwanted characters
  api-reference/v1.0/api/bookingbusiness-getstaffavailability.md
Labels: ready to merge, internal, customer support issue, content review complete

#18860 Reduce docs nesting - PIM
  api-reference/beta/resources/privilegedidentitymanagement-root.md
  api-reference/beta/toc.yml
  api-reference/includes/pim-v2AADRoles-deprecation.md
  api-reference/v1.0/toc.yml
Labels: area: Azure AD, ready to merge, internal

#18877 Remove RoleManagement.Read.All app-only for PIM
  api-reference/beta/api/rbacapplication-list-roleassignmentschedulerequests.md
  api-reference/beta/api/rbacapplication-list-roleeligibilityschedulerequests.md
  api-reference/beta/api/unifiedroleassignmentschedulerequest-get.md
  api-reference/beta/api/unifiedroleeligibilityschedulerequest-get.md
  api-reference/v1.0/api/rbacapplication-list-roleassignmentschedulerequests.md
  api-reference/v1.0/api/rbacapplication-list-roleeligibilityschedulerequests.md
  api-reference/v1.0/api/unifiedroleassignmentschedulerequest-get.md
  api-reference/v1.0/api/unifiedroleeligibilityschedulerequest-get.md
Labels: area: Azure AD, ready to merge, internal, area: governance

#18878 Hide unrendered LCW graphic
  api-reference/beta/resources/identitygovernance-lifecycleworkflows-overview.md
Labels: area: Azure AD, ready to merge, internal

#17821 GA - Updating Authentication Methods Policy V1.0 branch with new feature settings changes.
  api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md
  api-reference/v1.0/resources/authenticationmethodfeatureconfiguration.md
  api-reference/v1.0/resources/enums.md
  api-reference/v1.0/resources/featuretarget.md
  api-reference/v1.0/resources/microsoftauthenticatorauthenticationmethodconfiguration.md
  api-reference/v1.0/resources/microsoftauthenticatorfeaturesettings.md
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, ready to merge, content review complete, schema live

#16737 Add docs for allowUserConsentForRiskyApps
  api-reference/beta/api/authorizationpolicy-get.md
  api-reference/beta/api/authorizationpolicy-update.md
  api-reference/beta/resources/authorizationpolicy.md
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, ready to merge, internal, content review complete, schema live

#18881 Added advanced hunting and alert comments.
  concepts/whats-new-overview.md
Labels: do not merge, internal

#18883 Added advanced hunting API to what's new.
  concepts/whats-new-overview.md
Labels: internal

#18886 Edits in PR 18043
  api-reference/beta/api/industrydata-azuredatalakeconnector-delete.md
  api-reference/beta/api/industrydata-azuredatalakeconnector-get.md
  api-reference/beta/api/industrydata-azuredatalakeconnector-getuploadsession.md
  api-reference/beta/api/industrydata-azuredatalakeconnector-list.md
  api-reference/beta/api/industrydata-azuredatalakeconnector-update.md
  api-reference/beta/api/industrydata-filedataconnector-delete.md
  api-reference/beta/api/industrydata-filedataconnector-get.md
  api-reference/beta/api/industrydata-filedataconnector-list.md
  api-reference/beta/api/industrydata-filedataconnector-update.md
  api-reference/beta/api/industrydata-filedataconnector-validate.md
  api-reference/beta/resources/industrydata-filedataconnector.md
  api-reference/beta/resources/industrydata-inboundactivityresults.md
  api-reference/beta/resources/industrydata-inboundfileflow.md
  api-reference/beta/resources/industrydata-inboundflow.md
  api-reference/beta/resources/industrydata-industrydataactivitystatistics.md
  api-reference/beta/resources/industrydata-industrydatarunstatistics.md
  api-reference/beta/resources/industrydata-outboundflowactivity.md
  api-reference/beta/resources/industrydata-referencedefinition.md
  api-reference/beta/resources/industrydata-rolegroup.md
  api-reference/beta/resources/industrydata-rolereferencevalue.md
  api-reference/beta/resources/industrydata-sourcesystemdefinition.md
  api-reference/beta/resources/industrydata-usermatchingsetting.md
  api-reference/beta/resources/industrydata-usermatchtargetreferencevalue.md
  api-reference/beta/resources/industrydata-validateoperation.md
  api-reference/beta/resources/industrydata-yearreferencevalue.md
  api-reference/beta/resources/industrydata-yeartimeperioddefinition.md
  api-reference/beta/resources/longrunningoperation.md
Labels: external

#18902 Edits in PR 18043
  api-reference/beta/api/industrydata-azuredatalakeconnector-list.md
  api-reference/beta/api/industrydata-azuredatalakeconnector-update.md
  api-reference/beta/api/industrydata-filedataconnector-delete.md
  api-reference/beta/api/industrydata-filedataconnector-get.md
  api-reference/beta/api/industrydata-filedataconnector-list.md
  api-reference/beta/api/industrydata-filedataconnector-update.md
  api-reference/beta/api/industrydata-filedataconnector-validate.md
  api-reference/beta/api/industrydata-inboundfileflow-delete.md
  api-reference/beta/api/industrydata-inboundfileflow-get.md
  api-reference/beta/api/industrydata-inboundfileflow-list.md
  api-reference/beta/api/industrydata-inboundfileflow-update.md
  api-reference/beta/api/industrydata-inboundflow-get.md
  api-reference/beta/api/industrydata-inboundflow-update.md
  api-reference/beta/api/industrydata-industrydataconnector-get.md
  api-reference/beta/api/industrydata-industrydataconnector-update.md
  api-reference/beta/api/industrydata-industrydataconnector-validate.md
  api-reference/beta/api/industrydata-industrydataroot-delete-dataconnectors.md
  api-reference/beta/api/industrydata-industrydataroot-delete-inboundflows.md
  api-reference/beta/api/industrydata-industrydataroot-list-dataconnectors.md
  api-reference/beta/api/industrydata-industrydataroot-list-inboundflows.md
  api-reference/beta/api/industrydata-industrydataroot-post-dataconnectors.md
  api-reference/beta/api/industrydata-industrydataroot-post-inboundflows.md
  api-reference/beta/resources/industrydata-fileuploadsession.md
Labels: external

#18894 TOC search display name
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
Labels: area: Azure AD, ready to merge, internal

#18888 Update plannertask-delete.md
  api-reference/beta/api/plannertask-delete.md
Labels: external

#18887 Update plannertask-delete.md
  api-reference/v1.0/api/plannertask-delete.md
Labels: external

#18630 Adding Federation Related Notes to Associated Pages
  api-reference/beta/api/channel-get.md
  api-reference/beta/api/channel-list-members.md
  api-reference/beta/api/channel-list-messages.md
  api-reference/beta/api/channel-list.md
  api-reference/beta/api/chat-get.md
  api-reference/beta/api/chat-list-members.md
  api-reference/beta/api/chat-list-messages.md
  api-reference/beta/api/chat-list.md
  api-reference/v1.0/api/channel-get.md
  api-reference/v1.0/api/channel-list-members.md
  api-reference/v1.0/api/channel-list-messages.md
  api-reference/v1.0/api/channel-list.md
  api-reference/v1.0/api/chat-get.md
  api-reference/v1.0/api/chat-list-members.md
  api-reference/v1.0/api/chat-list-messages.md
  api-reference/v1.0/api/chat-list.md
Labels: ready to merge, internal, content review complete

#18803 [Azure AD roles] Delete and restore users
  api-reference/beta/api/user-delete.md
  api-reference/v1.0/api/user-delete.md
Labels: ready to merge, ready for content review, internal

#18629 Updating documentation for list-chat-messages filter query option
  api-reference/beta/api/chat-list-messages.md
  api-reference/v1.0/api/chat-list-messages.md
  changelog/Microsoft.Teams.Core.json
Labels: ready to merge, internal, content review complete

#16001 Add document for new source cloudPcCrossCloudGovernmentOrganizationMapping and related APIs
  api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-get.md
  api-reference/beta/api/virtualendpoint-post-crosscloudgovernmentorganizationmapping.md
  api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md
  api-reference/beta/resources/virtualendpoint.md
  api-reference/beta/toc.yml
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, internal, content review complete

#18800 Remove preview tags from UserAuthenticationMethod
  concepts/authenticationmethods-get-started.md
  concepts/permissions-reference.md
Labels: area: Azure AD, ready to merge, internal, content review complete

#18909 Merge to publish.
  .github/workflows/assign-to-author.yml
  .github/workflows/eol-blocker.yml
  .github/workflows/snippet-generation-pr.yml
  api-reference/beta/api/channel-get.md
  api-reference/beta/api/channel-list-members.md
  api-reference/beta/api/channel-list-messages.md
  api-reference/beta/api/channel-list.md
  api-reference/beta/api/chat-get.md
  api-reference/beta/api/chat-list-members.md
  api-reference/beta/api/chat-list-messages.md
  api-reference/beta/api/chat-list.md
  api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-get.md
  api-reference/beta/api/plannertask-delete.md
  api-reference/beta/api/user-delete.md
  api-reference/beta/api/virtualendpoint-post-crosscloudgovernmentorganizationmapping.md
  api-reference/beta/resources/cloudpccrosscloudgovernmentorganizationmapping.md
  api-reference/beta/resources/virtualendpoint.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/channel-get.md
  api-reference/v1.0/api/channel-list-members.md
  api-reference/v1.0/api/channel-list-messages.md
  api-reference/v1.0/api/channel-list.md
  api-reference/v1.0/api/chat-get.md
  api-reference/v1.0/api/chat-list-members.md
  api-reference/v1.0/api/chat-list-messages.md
  api-reference/v1.0/api/chat-list.md
  api-reference/v1.0/api/plannertask-delete.md
  api-reference/v1.0/api/user-delete.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.CloudManagedDesktop.json
  changelog/Microsoft.Teams.Core.json
  concepts/authenticationmethods-get-started.md
  concepts/permissions-reference.md
Labels: internal

#18824 Update the post content type in example response to HTML, which is the support type in service communications API
  api-reference/beta/api/serviceannouncement-list-healthoverviews.md
  api-reference/beta/api/serviceannouncement-list-issues.md
  api-reference/beta/api/serviceannouncement-list-messages.md
  api-reference/beta/api/servicehealth-get.md
  api-reference/beta/api/servicehealthissue-get.md
  api-reference/beta/api/serviceupdatemessage-get.md
  api-reference/beta/resources/servicehealthissuepost.md
  api-reference/beta/resources/serviceupdatemessage.md
  api-reference/v1.0/api/serviceannouncement-list-healthoverviews.md
  api-reference/v1.0/api/serviceannouncement-list-issues.md
  api-reference/v1.0/api/serviceannouncement-list-messages.md
  api-reference/v1.0/api/servicehealth-get.md
  api-reference/v1.0/api/servicehealthissue-get.md
  api-reference/v1.0/api/serviceupdatemessage-get.md
  api-reference/v1.0/resources/servicehealthissuepost.md
  api-reference/v1.0/resources/serviceupdatemessage.md
Labels: ready to merge, internal, content review complete

#18920 Clarify privileges to update or delete privileged users
  api-reference/beta/api/user-delete.md
  api-reference/beta/api/user-update.md
  api-reference/v1.0/api/user-delete.md
  api-reference/v1.0/api/user-update.md
Labels: area: Azure AD, ready to merge, internal

#18921 [BrokenLinksH2] Fix path in link
  concepts/includes/connecting-external-content-build-quickstart-06-run-app.md
Labels: external, ready to merge

#18922 update contact for Search APIs
  api-reference/beta/api/search-query.md
  api-reference/beta/resources/aggregationoption.md
  api-reference/beta/resources/alterationresponse.md
  api-reference/beta/resources/alteredquerytoken.md
  api-reference/beta/resources/bucketaggregationdefinition.md
  api-reference/beta/resources/bucketaggregationrange.md
  api-reference/beta/resources/search-api-overview.md
  api-reference/beta/resources/search.md
  api-reference/beta/resources/searchaggregation.md
  api-reference/beta/resources/searchalteration.md
  api-reference/beta/resources/searchalterationoptions.md
  api-reference/beta/resources/searchbucket.md
  api-reference/beta/resources/searchentity.md
  api-reference/beta/resources/searchhit.md
  api-reference/beta/resources/searchhitscontainer.md
  api-reference/beta/resources/searchquery.md
  api-reference/beta/resources/searchquerystring.md
  api-reference/beta/resources/searchrequest.md
  api-reference/beta/resources/searchresponse.md
  api-reference/beta/resources/sortproperty.md
  api-reference/v1.0/api/search-query.md
  api-reference/v1.0/resources/aggregationoption.md
  api-reference/v1.0/resources/alterationresponse.md
  api-reference/v1.0/resources/alteredquerytoken.md
  api-reference/v1.0/resources/bucketaggregationdefinition.md
  api-reference/v1.0/resources/bucketaggregationrange.md
  api-reference/v1.0/resources/search-api-overview.md
  api-reference/v1.0/resources/search.md
  api-reference/v1.0/resources/searchalteration.md
  api-reference/v1.0/resources/searchalterationoptions.md
  api-reference/v1.0/resources/searchbucket.md
  api-reference/v1.0/resources/searchentity.md
  api-reference/v1.0/resources/searchhit.md
  api-reference/v1.0/resources/searchhitscontainer.md
  api-reference/v1.0/resources/searchquery.md
  api-reference/v1.0/resources/searchrequest.md
  api-reference/v1.0/resources/searchresponse.md
  api-reference/v1.0/resources/sortproperty.md
  concepts/search-concept-aggregation.md
  concepts/search-concept-custom-types.md
  concepts/search-concept-files.md
  concepts/search-concept-sort.md
  concepts/search-concept-speller.md
Labels: do not merge, ready to merge, internal

#18518 [CloudPC]Add CloudPC reports related API
  api-reference/beta/api/cloudpcexportjob-get.md
  api-reference/beta/api/cloudpcreports-getdailyaggregatedremoteconnectionreports.md
  api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionlatency.md
  api-reference/beta/api/cloudpcreports-getrealtimeremoteconnectionstatus.md
  api-reference/beta/api/cloudpcreports-getremoteconnectionhistoricalreports.md
  api-reference/beta/api/cloudpcreports-gettotalaggregatedremoteconnectionreports.md
  api-reference/beta/api/cloudpcreports-post-exportjobs.md
  api-reference/beta/resources/cloudpcexportjob.md
  api-reference/beta/resources/cloudpcreports.md
  api-reference/beta/resources/virtualendpoint.md
  api-reference/beta/toc.yml
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, content review complete, schema live

#18059 Update authenticationmethods-overview.md
  api-reference/v1.0/resources/authenticationmethods-overview.md
Labels: ready to merge, internal, content review complete

#18598 Add note about how to renew expired tenant
  concepts/msgraph-onboarding-edutenant.md
Labels: do not merge, ready to merge, internal, content review complete

#18618 GetRubric not apponly permissions & match beta-v1.0
  api-reference/beta/api/educationassignment-get-rubric.md
  api-reference/beta/api/educationrubric-get.md
  api-reference/v1.0/api/educationassignment-get-rubric.md
  api-reference/v1.0/api/educationrubric-get.md
Labels: ready to merge, internal, content review complete, schema live

#18730 Updated allowDeletedIdentitiesDataRemoval
  api-reference/beta/api/externalidentitiespolicy-update.md
  api-reference/beta/resources/externalidentitiespolicy.md
Labels: area: Azure AD, ready to merge, content review complete

#18117 Adding new enum "azureCommunicationServicesUser" to teamworkUserIdentityType
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/teamworkuseridentity.md
  changelog/Microsoft.Teams.Core.json
Labels: do not merge, ready to merge, internal, content review complete

#18936 Merge to publish.
  api-reference/beta/api/educationassignment-get-rubric.md
  api-reference/beta/api/educationrubric-get.md
  api-reference/beta/api/externalidentitiespolicy-update.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/externalidentitiespolicy.md
  api-reference/beta/resources/teamworkuseridentity.md
  api-reference/v1.0/api/educationassignment-get-rubric.md
  api-reference/v1.0/api/educationrubric-get.md
  api-reference/v1.0/resources/authenticationmethods-overview.md
  changelog/Microsoft.Teams.Core.json
  concepts/msgraph-onboarding-edutenant.md
Labels: internal

#18929 Added code snippet for using proxy with Go SDK
  concepts/sdks/customize-client.md
Labels: ready to merge, internal, content review complete

#18944 Clarified you can't PATCH a read-only property
  api-reference/beta/api/chatmessage-update.md
Labels: ready to merge

#18924 remove org message api
  api-reference/beta/api/intune-partnerintegration-devicemanagement-getorganizationalmessagetenantconsent.md
  api-reference/beta/api/intune-partnerintegration-devicemanagement-postorganizationalmessagetenantconsent.md
  api-reference/beta/api/intune-partnerintegration-devicemanagement-updateorganizationalmessagetenantconsent.md
  api-reference/beta/api/intune-partnerintegration-organizationalmessagedetail-create.md
  api-reference/beta/api/intune-partnerintegration-organizationalmessagedetail-delete.md
  api-reference/beta/api/intune-partnerintegration-organizationalmessagedetail-get.md
  api-reference/beta/api/intune-partnerintegration-organizationalmessagedetail-list.md
  api-reference/beta/api/intune-partnerintegration-organizationalmessagedetail-update.md
  api-reference/beta/api/intune-partnerintegration-organizationalmessageguidedcontent-create.md
  api-reference/beta/api/intune-partnerintegration-organizationalmessageguidedcontent-delete.md
  api-reference/beta/api/intune-partnerintegration-organizationalmessageguidedcontent-get.md
  api-reference/beta/api/intune-partnerintegration-organizationalmessageguidedcontent-list.md
  api-reference/beta/api/intune-partnerintegration-organizationalmessageguidedcontent-update.md
  api-reference/beta/resources/intune-partnerintegration-organizationalmessagecontent.md
  api-reference/beta/resources/intune-partnerintegration-organizationalmessagedetail.md
  api-reference/beta/resources/intune-partnerintegration-organizationalmessagefrequency.md
  api-reference/beta/resources/intune-partnerintegration-organizationalmessageguidedcontent.md
  api-reference/beta/resources/intune-partnerintegration-organizationalmessageinsights.md
  api-reference/beta/resources/intune-partnerintegration-organizationalmessagelocalizedtext.md
  api-reference/beta/resources/intune-partnerintegration-organizationalmessagelogo.md
  api-reference/beta/resources/intune-partnerintegration-organizationalmessagelogodimensions.md
  api-reference/beta/resources/intune-partnerintegration-organizationalmessagelogoguide.md
  api-reference/beta/resources/intune-partnerintegration-organizationalmessagelogotype.md
  api-reference/beta/resources/intune-partnerintegration-organizationalmessageplacement.md
  api-reference/beta/resources/intune-partnerintegration-organizationalmessageplacementdetail.md
  api-reference/beta/resources/intune-partnerintegration-organizationalmessagescenario.md
  api-reference/beta/resources/intune-partnerintegration-organizationalmessagestatus.md
  api-reference/beta/resources/intune-partnerintegration-organizationalmessagesurface.md
  api-reference/beta/resources/intune-partnerintegration-organizationalmessagetargeting.md
  api-reference/beta/resources/intune-partnerintegration-organizationalmessagetargetingtype.md
  api-reference/beta/resources/intune-partnerintegration-organizationalmessagetenantconsent.md
  api-reference/beta/resources/intune-partnerintegration-organizationalmessagetext.md
  api-reference/beta/resources/intune-partnerintegration-organizationalmessagetheme.md
  api-reference/beta/resources/intune-partnerintegration-organizationalmessagevariant.md
  changelog/Microsoft.Intune.json
Labels: ready to merge, internal

#18946 Merge to publish.
  api-reference/beta/api/chatmessage-update.md
  api-reference/beta/api/intune-partnerintegration-devicemanagement-getorganizationalmessagetenantconsent.md
  api-reference/beta/api/intune-partnerintegration-devicemanagement-postorganizationalmessagetenantconsent.md
  api-reference/beta/api/intune-partnerintegration-devicemanagement-updateorganizationalmessagetenantconsent.md
  api-reference/beta/api/intune-partnerintegration-organizationalmessagedetail-create.md
  api-reference/beta/api/intune-partnerintegration-organizationalmessagedetail-delete.md
  api-reference/beta/api/intune-partnerintegration-organizationalmessagedetail-get.md
  api-reference/beta/api/intune-partnerintegration-organizationalmessagedetail-list.md
  api-reference/beta/api/intune-partnerintegration-organizationalmessagedetail-update.md
  api-reference/beta/api/intune-partnerintegration-organizationalmessageguidedcontent-create.md
  api-reference/beta/api/intune-partnerintegration-organizationalmessageguidedcontent-delete.md
  api-reference/beta/api/intune-partnerintegration-organizationalmessageguidedcontent-get.md
  api-reference/beta/api/intune-partnerintegration-organizationalmessageguidedcontent-list.md
  api-reference/beta/api/intune-partnerintegration-organizationalmessageguidedcontent-update.md
  api-reference/beta/resources/intune-partnerintegration-organizationalmessagecontent.md
  api-reference/beta/resources/intune-partnerintegration-organizationalmessagedetail.md
  api-reference/beta/resources/intune-partnerintegration-organizationalmessagefrequency.md
  api-reference/beta/resources/intune-partnerintegration-organizationalmessageguidedcontent.md
  api-reference/beta/resources/intune-partnerintegration-organizationalmessageinsights.md
  api-reference/beta/resources/intune-partnerintegration-organizationalmessagelocalizedtext.md
  api-reference/beta/resources/intune-partnerintegration-organizationalmessagelogo.md
  api-reference/beta/resources/intune-partnerintegration-organizationalmessagelogodimensions.md
  api-reference/beta/resources/intune-partnerintegration-organizationalmessagelogoguide.md
  api-reference/beta/resources/intune-partnerintegration-organizationalmessagelogotype.md
  api-reference/beta/resources/intune-partnerintegration-organizationalmessageplacement.md
  api-reference/beta/resources/intune-partnerintegration-organizationalmessageplacementdetail.md
  api-reference/beta/resources/intune-partnerintegration-organizationalmessagescenario.md
  api-reference/beta/resources/intune-partnerintegration-organizationalmessagestatus.md
  api-reference/beta/resources/intune-partnerintegration-organizationalmessagesurface.md
  api-reference/beta/resources/intune-partnerintegration-organizationalmessagetargeting.md
  api-reference/beta/resources/intune-partnerintegration-organizationalmessagetargetingtype.md
  api-reference/beta/resources/intune-partnerintegration-organizationalmessagetenantconsent.md
  api-reference/beta/resources/intune-partnerintegration-organizationalmessagetext.md
  api-reference/beta/resources/intune-partnerintegration-organizationalmessagetheme.md
  api-reference/beta/resources/intune-partnerintegration-organizationalmessagevariant.md
  changelog/Microsoft.Intune.json
  concepts/sdks/customize-client.md
Labels: internal

#18948 Edits in PR 18043
  api-reference/beta/api/industrydata-filedataconnector-update.md
  api-reference/beta/api/industrydata-filedataconnector-validate.md
  api-reference/beta/api/industrydata-industrydataroot-get.md
  api-reference/beta/api/industrydata-industrydataroot-list-operations.md
  api-reference/beta/api/industrydata-industrydataroot-list-referencedefinitions.md
  api-reference/beta/api/industrydata-industrydataroot-list-rolegroups.md
  api-reference/beta/api/industrydata-referencedefinition-get.md
  api-reference/beta/api/industrydata-rolegroup-get.md
  api-reference/beta/api/longrunningoperation-get.md
  api-reference/beta/resources/industrydata-fileuploadsession.md
  api-reference/beta/resources/industrydata-inboundfileflow.md
  api-reference/beta/resources/industrydata-inboundflow.md
  api-reference/beta/resources/industrydata-inboundflowactivity.md
  api-reference/beta/resources/industrydata-industrydataactivity.md
  api-reference/beta/resources/industrydata-industrydataroot.md
  api-reference/beta/resources/industrydata-outboundflowactivity.md
  api-reference/beta/resources/industrydata-sourcesystemdefinition.md
  api-reference/beta/resources/longrunningoperation.md
Labels: external

#18966 Edits in PR 18043
  api-reference/beta/api/industrydata-industrydataroot-list-runs.md
  api-reference/beta/api/industrydata-industrydataroot-post-sourcesystems.md
  api-reference/beta/api/industrydata-industrydataroot-post-years.md
  api-reference/beta/api/industrydata-industrydatarun-get.md
  api-reference/beta/api/industrydata-industrydatarun-getstatistics.md
  api-reference/beta/api/industrydata-industrydatarun-list-activities.md
  api-reference/beta/api/industrydata-industrydatarunactivity-get.md
  api-reference/beta/api/industrydata-sourcesystemdefinition-get.md
  api-reference/beta/api/industrydata-sourcesystemdefinition-update.md
  api-reference/beta/api/industrydata-yeartimeperioddefinition-get.md
  api-reference/beta/api/industrydata-yeartimeperioddefinition-update.md
  api-reference/beta/resources/industrydata-industrydatarun.md
  api-reference/beta/resources/industrydata-sourcesystemdefinition.md
Labels: external

#18970 Update user-list-people.md
  api-reference/beta/api/user-list-people.md
Labels: external

#18969 Update user-list-people.md
  api-reference/v1.0/api/user-list-people.md
Labels: external

#18968 Update plannerbucket-list-tasks.md
  api-reference/beta/api/plannerbucket-list-tasks.md
Labels: external
