Repository microsoftgraph/microsoft-graph-docs, pull requests merged in 2023-04, with the labels that each got.

#19584 planner recurring tasks documentation to beta
  api-reference/beta/api/plannertask-get.md
  api-reference/beta/api/plannertask-update.md
  api-reference/beta/resources/plannerrecurrenceschedule.md
  api-reference/beta/resources/plannertask.md
  api-reference/beta/resources/plannertaskrecurrence.md
  changelog/Microsoft.Office.Tasks.json
  concepts/planner-task-recurrence-overview.md
  concepts/toc.yml
Labels: ready to merge, internal, content review complete

#20798 Add cross-link to cert update guidance
  api-reference/beta/resources/keycredential.md
  api-reference/v1.0/resources/keycredential.md
Labels: area: Azure AD, ready to merge, internal

#19792 Adding tenant Id property to teamworkuseridentity.md
  api-reference/beta/api/chatmessage-delta.md
  api-reference/beta/api/chatmessage-get.md
  api-reference/beta/api/chatmessage-list-replies.md
  api-reference/beta/api/chatmessage-post-replies.md
  api-reference/beta/api/chatmessage-post.md
  api-reference/beta/resources/chatmessagefromidentityset.md
  api-reference/beta/resources/teamworkuseridentity.md
  api-reference/v1.0/api/chatmessage-delta.md
  api-reference/v1.0/api/chatmessage-get.md
  api-reference/v1.0/api/chatmessage-list-replies.md
  api-reference/v1.0/api/chatmessage-post-replies.md
  api-reference/v1.0/api/chatmessage-post.md
  api-reference/v1.0/resources/chatmessagefromidentityset.md
  api-reference/v1.0/resources/teamworkuseridentity.md
  changelog/Microsoft.Teams.Core.json
Labels: ready to merge, internal, content review complete

#20800 Add email authenticity note
  api-reference/beta/resources/emailsettings.md
Labels: ready to merge, internal

#20805 Merge to publish.
  api-reference/beta/api/chatmessage-delta.md
  api-reference/beta/api/chatmessage-get.md
  api-reference/beta/api/chatmessage-list-replies.md
  api-reference/beta/api/chatmessage-post-replies.md
  api-reference/beta/api/chatmessage-post.md
  api-reference/beta/api/plannertask-get.md
  api-reference/beta/api/plannertask-update.md
  api-reference/beta/resources/chatmessagefromidentityset.md
  api-reference/beta/resources/emailsettings.md
  api-reference/beta/resources/keycredential.md
  api-reference/beta/resources/plannerrecurrenceschedule.md
  api-reference/beta/resources/plannertask.md
  api-reference/beta/resources/plannertaskrecurrence.md
  api-reference/beta/resources/teamworkuseridentity.md
  api-reference/v1.0/api/chatmessage-delta.md
  api-reference/v1.0/api/chatmessage-get.md
  api-reference/v1.0/api/chatmessage-list-replies.md
  api-reference/v1.0/api/chatmessage-post-replies.md
  api-reference/v1.0/api/chatmessage-post.md
  api-reference/v1.0/resources/chatmessagefromidentityset.md
  api-reference/v1.0/resources/keycredential.md
  api-reference/v1.0/resources/teamworkuseridentity.md
  changelog/Microsoft.Office.Tasks.json
  changelog/Microsoft.Teams.Core.json
  concepts/planner-task-recurrence-overview.md
  concepts/toc.yml
Labels: internal

#20773 Refresh for the month.
  api-reference/beta/resources/conditionalaccessrulesatisfied.md
  changelog/Microsoft.AAD.Reporting.json
  concepts/whats-new-overview.md
Labels: do not merge, internal

#20806 Added a few more March items.
  api-reference/beta/resources/conditionalaccessrulesatisfied.md
  changelog/Microsoft.AAD.Reporting.json
  concepts/whats-new-overview.md
Labels: do not merge, internal

#20811 Edits in PR 20340
  api-reference/beta/api/cloudpcprovisioningpolicy-apply.md
  api-reference/beta/api/cloudpcprovisioningpolicy-applyconfig.md
  api-reference/beta/resources/cloudpcprovisioningpolicy.md
  api-reference/beta/toc.yml
  changelog/Microsoft.CloudManagedDesktop.json
Labels: external

#20812 Edits in PR 20340
  api-reference/beta/api/cloudpcprovisioningpolicy-apply.md
  api-reference/beta/api/cloudpcprovisioningpolicy-applyconfig.md
  api-reference/beta/resources/cloudpc.md
  api-reference/beta/resources/cloudpcprovisioningpolicy.md
  api-reference/beta/toc.yml
  changelog/Microsoft.CloudManagedDesktop.json
Labels: external

#20808 Continue with March items.
  changelog/Microsoft.Security.Ediscovery.json
  concepts/whats-new-overview.md
Labels: do not merge, internal

#20813 Refresh what's new with a few more items.
  changelog/Microsoft.Security.Ediscovery.json
  concepts/whats-new-overview.md
Labels: internal

#20820 Update bookingappointment-cancel.md
  api-reference/v1.0/api/bookingappointment-cancel.md
Labels: external

#20819 Update bookingappointment-cancel.md
  api-reference/beta/api/bookingappointment-cancel.md
Labels: external

#20807 Update securityactions-post.md
  api-reference/beta/api/securityactions-post.md
Labels: external

#19074 updating MESG defintion in beta doc
  api-reference/beta/resources/groups-overview.md
Labels: ready to merge, internal, content review complete

#20795 [BrokenLinksH2] | Fixed broken links 4 | Bulk Update
  concepts/changelog-archive.md
Labels: external, ready to merge

#19185 Schema changes for teams app installation related to new consented permission set.
  api-reference/beta/api/appcatalogs-list-teamsapps.md
  api-reference/beta/api/chat-get-installedapps.md
  api-reference/beta/api/chat-list-installedapps.md
  api-reference/beta/api/chat-post-installedapps.md
  api-reference/beta/api/chat-teamsappinstallation-upgrade.md
  api-reference/beta/api/team-get-installedapps.md
  api-reference/beta/api/team-list-installedapps.md
  api-reference/beta/api/team-post-installedapps.md
  api-reference/beta/api/team-teamsappinstallation-upgrade.md
  api-reference/beta/resources/teamsappauthorization.md
  api-reference/beta/resources/teamsappdefinition.md
  api-reference/beta/resources/teamsappinstallation.md
  api-reference/beta/resources/teamsapppermissionset.md
  api-reference/beta/resources/teamsappresourcespecificpermission.md
  changelog/Microsoft.Teams.GraphSvc.json
  concepts/permissions-reference.md
  includes/teamwork-permissions-note.md
Labels: ready to merge, content review complete, schema live, review feedback addressed

#20601 Removed canary link from Beta and added post emoji example in v1.0
  api-reference/beta/api/chatmessage-post.md
  api-reference/v1.0/api/chatmessage-post.md
Labels: ready to merge

#20814 Minor doc fixes
  api-reference/beta/api/user-update.md
  api-reference/beta/resources/accessreviewschedulesettings.md
  api-reference/beta/resources/conditionalaccessusers.md
  api-reference/v1.0/api/user-update.md
  api-reference/v1.0/resources/accessreviewschedulesettings.md
  api-reference/v1.0/resources/conditionalaccessusers.md
Labels: area: Azure AD, ready to merge

#20702 doc changelog
  api-reference/beta/api/signin-get.md
  api-reference/beta/api/signin-list.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/managedidentity.md
  api-reference/beta/resources/signin.md
  changelog/Microsoft.AAD.Reporting.json
Labels: area: Azure AD, ready to merge, internal, content review complete

#20822 Merge to publish.
  api-reference/beta/api/appcatalogs-list-teamsapps.md
  api-reference/beta/api/bookingappointment-cancel.md
  api-reference/beta/api/chat-get-installedapps.md
  api-reference/beta/api/chat-list-installedapps.md
  api-reference/beta/api/chat-post-installedapps.md
  api-reference/beta/api/chat-teamsappinstallation-upgrade.md
  api-reference/beta/api/chatmessage-post.md
  api-reference/beta/api/securityactions-post.md
  api-reference/beta/api/signin-get.md
  api-reference/beta/api/signin-list.md
  api-reference/beta/api/team-get-installedapps.md
  api-reference/beta/api/team-list-installedapps.md
  api-reference/beta/api/team-post-installedapps.md
  api-reference/beta/api/team-teamsappinstallation-upgrade.md
  api-reference/beta/api/user-update.md
  api-reference/beta/resources/accessreviewschedulesettings.md
  api-reference/beta/resources/conditionalaccessusers.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/groups-overview.md
  api-reference/beta/resources/managedidentity.md
  api-reference/beta/resources/signin.md
  api-reference/beta/resources/teamsappauthorization.md
  api-reference/beta/resources/teamsappdefinition.md
  api-reference/beta/resources/teamsappinstallation.md
  api-reference/beta/resources/teamsapppermissionset.md
  api-reference/beta/resources/teamsappresourcespecificpermission.md
  api-reference/v1.0/api/bookingappointment-cancel.md
  api-reference/v1.0/api/chatmessage-post.md
  api-reference/v1.0/api/user-update.md
  api-reference/v1.0/resources/accessreviewschedulesettings.md
  api-reference/v1.0/resources/conditionalaccessusers.md
  changelog/Microsoft.AAD.Reporting.json
  changelog/Microsoft.Teams.GraphSvc.json
  concepts/changelog-archive.md
  concepts/permissions-reference.md
  includes/teamwork-permissions-note.md
Labels: internal

#20824 Edits in PR 20362
  api-reference/beta/api/cloudpc-start.md
  api-reference/beta/api/cloudpc-stop.md
  api-reference/beta/resources/cloudpc.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: external

#20827 Edits in PR 19952
  api-reference/beta/resources/plannerTaskCompletionRequirements.md
  api-reference/beta/resources/plannerchecklistrequirement.md
  api-reference/beta/resources/plannertask.md
  api-reference/beta/resources/plannertaskcompletionrequirementdetails.md
  api-reference/beta/resources/plannertaskdetails.md
Labels: external

#20832 Refresh what's new topic to include remaining items for March.
  api-reference/beta/resources/security-api-overview.md
  concepts/whats-new-overview.md
Labels: internal

#20825 Update permissions-reference.md
  concepts/permissions-reference.md
Labels: external

#20787 Fixing duplicate example names in v1
  api-reference/v1.0/api/appmanagementpolicy-delete-appliesto.md
  api-reference/v1.0/api/appmanagementpolicy-post-appliesto.md
  api-reference/v1.0/api/bundle-get.md
  api-reference/v1.0/api/chat-get.md
  api-reference/v1.0/api/chat-post.md
  api-reference/v1.0/api/featurerolloutpolicy-delete-appliesto.md
  api-reference/v1.0/api/featurerolloutpolicy-post-appliesto.md
  api-reference/v1.0/api/group-list-calendarview.md
  api-reference/v1.0/api/rangeformat-update.md
  api-reference/v1.0/api/serviceprincipal-delete-owners.md
  api-reference/v1.0/api/user-get.md
  api-reference/v1.0/api/user-list-calendarview.md
  api-reference/v1.0/api/workbook-closesession.md
  api-reference/v1.0/api/workbook-createsession.md
  concepts/excel-update-range-format.md
  concepts/tutorial-riskdetection-api.md
  concepts/workbook-best-practice.md
Labels: ready to merge, internal

#20818 adding appropiate blocktype
  api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md
  api-reference/v1.0/api/accesspackage-getapplicablepolicyrequirements.md
  api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md
  api-reference/v1.0/api/site-list.md
  api-reference/v1.0/api/user-post-messages.md
Labels: ready to merge, internal

#20837 Minor doc fixes
  api-reference/beta/api/agreement-delete.md
  api-reference/beta/api/agreement-get.md
  api-reference/beta/api/agreement-update.md
  api-reference/beta/api/synchronization-synchronizationtemplate-get.md
  api-reference/beta/api/synchronization-synchronizationtemplate-list.md
  api-reference/beta/api/synchronization-synchronizationtemplate-update.md
  api-reference/beta/api/termsofusecontainer-list-agreements.md
  api-reference/beta/api/termsofusecontainer-post-agreements.md
  api-reference/beta/includes/rbac-for-apis/rbac-tou-apis.md
  concepts/toc.yml
Labels: area: Azure AD, ready to merge, internal

#20843 Merge to publish.
  api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md
  api-reference/beta/api/agreement-delete.md
  api-reference/beta/api/agreement-get.md
  api-reference/beta/api/agreement-update.md
  api-reference/beta/api/synchronization-synchronizationtemplate-get.md
  api-reference/beta/api/synchronization-synchronizationtemplate-list.md
  api-reference/beta/api/synchronization-synchronizationtemplate-update.md
  api-reference/beta/api/termsofusecontainer-list-agreements.md
  api-reference/beta/api/termsofusecontainer-post-agreements.md
  api-reference/beta/includes/rbac-for-apis/rbac-tou-apis.md
  api-reference/v1.0/api/accesspackage-getapplicablepolicyrequirements.md
  api-reference/v1.0/api/appmanagementpolicy-delete-appliesto.md
  api-reference/v1.0/api/appmanagementpolicy-post-appliesto.md
  api-reference/v1.0/api/bundle-get.md
  api-reference/v1.0/api/chat-get.md
  api-reference/v1.0/api/chat-post.md
  api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md
  api-reference/v1.0/api/featurerolloutpolicy-delete-appliesto.md
  api-reference/v1.0/api/featurerolloutpolicy-post-appliesto.md
  api-reference/v1.0/api/group-list-calendarview.md
  api-reference/v1.0/api/rangeformat-update.md
  api-reference/v1.0/api/serviceprincipal-delete-owners.md
  api-reference/v1.0/api/site-list.md
  api-reference/v1.0/api/user-get.md
  api-reference/v1.0/api/user-list-calendarview.md
  api-reference/v1.0/api/user-post-messages.md
  api-reference/v1.0/api/workbook-closesession.md
  api-reference/v1.0/api/workbook-createsession.md
  concepts/excel-update-range-format.md
  concepts/permissions-reference.md
  concepts/toc.yml
  concepts/tutorial-riskdetection-api.md
  concepts/workbook-best-practice.md
Labels: do not merge, internal

#20846 Edits in PR 20504
  api-reference/beta/resources/sharepoint.md
  api-reference/v1.0/resources/sharepoint.md
Labels: external

#20584 [Doc Improvement][Metadatacontent update][2918735]
  api-reference/beta/api/calltranscript-get.md
  api-reference/beta/resources/calltranscript.md
  changelog/Microsoft.Teams.Core.json
Labels: ready to merge, internal, content review complete, review feedback addressed

#20841 Taskprocessingresult resume permissions updated
  api-reference/beta/api/identitygovernance-taskprocessingresult-resume.md
  changelog/Microsoft.AAD.LCM.json
Labels: ready to merge, internal

#20852 Fixing duplicate names in examples - beta
  api-reference/beta/api/accessreviewinstance-update.md
  api-reference/beta/api/adminwindowsupdates-list-deployments.md
  api-reference/beta/api/appmanagementpolicy-delete-appliesto.md
  api-reference/beta/api/browsersitelist-delete-sharedcookies.md
  api-reference/beta/api/browsersitelist-delete-sites.md
  api-reference/beta/api/browsersitelist-publish.md
  api-reference/beta/api/bundle-list.md
  api-reference/beta/api/businessscenarioplanner-list-tasks.md
  api-reference/beta/api/channel-post-members.md
  api-reference/beta/api/channel-removeemail.md
  api-reference/beta/api/chat-get.md
  api-reference/beta/api/chat-teamsappinstallation-upgrade.md
  api-reference/beta/api/chatmessage-post.md
  api-reference/beta/api/device-get.md
  api-reference/beta/api/device-list.md
  api-reference/beta/api/directory-list-outboundshareduserprofiles.md
  api-reference/beta/api/directory-list-recommendation.md
  api-reference/beta/api/driveitem-restore.md
  api-reference/beta/api/educationassignmentdefaults-update.md
  api-reference/beta/api/educationassignmentresource-get.md
  api-reference/beta/api/externalconnectors-externalitem-get.md
  api-reference/beta/api/group-delta.md
  api-reference/beta/api/horizontalsection-get.md
  api-reference/beta/api/horizontalsectioncolumn-get.md
  api-reference/beta/api/identitygovernance-run-get.md
  api-reference/beta/api/identitygovernance-userprocessingresult-get.md
  api-reference/beta/api/industrydata-azuredatalakeconnector-delete.md
  api-reference/beta/api/industrydata-azuredatalakeconnector-get.md
  api-reference/beta/api/industrydata-azuredatalakeconnector-list.md
  api-reference/beta/api/industrydata-inboundfileflow-delete.md
  api-reference/beta/api/industrydata-inboundfileflow-list.md
  api-reference/beta/api/industrydata-inboundfileflow-update.md
  api-reference/beta/api/industrydata-inboundflow-get.md
  api-reference/beta/api/onpremisesdirectorysynchronization-get.md
  api-reference/beta/api/onpremisesdirectorysynchronization-update.md
  api-reference/beta/api/planner-post-plans.md
  api-reference/beta/api/plannerplan-delta.md
  api-reference/beta/api/plannerplanconfiguration-list-localizations.md
  api-reference/beta/api/plannertask-delta.md
  api-reference/beta/api/rbacapplication-post-roleeligibilityschedulerequests.md
  api-reference/beta/api/samlorwsfedexternaldomainfederation-delete.md
  api-reference/beta/api/samlorwsfedexternaldomainfederation-get.md
  api-reference/beta/api/samlorwsfedexternaldomainfederation-list-domains.md
  api-reference/beta/api/samlorwsfedexternaldomainfederation-post-domains.md
  api-reference/beta/api/samlorwsfedexternaldomainfederation-post.md
  api-reference/beta/api/samlorwsfedexternaldomainfederation-update.md
  api-reference/beta/api/search-searchentity-post-acronyms.md
  api-reference/beta/api/search-searchentity-post-bookmarks.md
  api-reference/beta/api/security-article-get.md
  api-reference/beta/api/security-host-list-passivedns.md
  api-reference/beta/api/team-post-installedapps.md
  api-reference/beta/api/team-post.md
  api-reference/beta/api/user-list-mailfolders.md
  api-reference/beta/api/user-list.md
  api-reference/beta/api/userflowlanguageconfiguration-delete.md
  api-reference/beta/api/verticalsection-get.md
  api-reference/beta/api/workbook-tablerowoperationresult.md
  api-reference/beta/api/workflow-list-executionscope.md
Labels: ready to merge, internal

#20856 [2303] PE - Beta (Prod, FF, MC) Fixed TOC issues
  api-reference/beta/toc.yml
Labels: ready to merge, internal

#20858 Removed reports section as we fixed the only issue
  concepts/known-issues.md
Labels: ready to merge, internal, content review complete

#20730 Update defaultuserrolepermissions.md
  api-reference/beta/resources/defaultuserrolepermissions.md
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, ready to merge, internal, content review complete

#20860 Edits in PR 20786
  api-reference/beta/api/drive-sharedwithme.md
  api-reference/v1.0/api/drive-sharedwithme.md
Labels: external

#20842 Adding note about 120 top limit
  api-reference/beta/api/user-list.md
  api-reference/beta/resources/user.md
  api-reference/v1.0/api/user-list.md
  api-reference/v1.0/resources/user.md
Labels: area: Azure AD, ready to merge, internal, content review complete

#20854 Clarification
  api-reference/beta/resources/identitygovernance-customtaskextensioncallbackconfiguration.md
Labels: ready to merge, internal

#20309 Add M365 Active User Report to Beta ITAR
  api-reference/beta/resources/report.md
Labels: ready to merge, internal, content review complete

#20765 Fixing Sync API docs
  api-reference/beta/api/synchronization-synchronizationjob-validatecredentials.md
  api-reference/beta/resources/synchronization-attributemapping.md
  api-reference/beta/resources/synchronization-stringkeylongvaluepair.md
  api-reference/beta/resources/synchronization-synchronizationerror.md
  api-reference/beta/resources/synchronization-synchronizationsecretkeystringvaluepair.md
Labels: area: Azure AD, ready to merge, internal, content review complete

#20867 Fix odata type annotation namespace in documentation examples
  api-reference/beta/api/chatmessage-delta.md
  api-reference/beta/api/chatmessage-get.md
  api-reference/beta/api/chatmessage-list-replies.md
  api-reference/beta/api/chatmessage-post-replies.md
  api-reference/beta/api/chatmessage-post.md
  api-reference/v1.0/api/chatmessage-delta.md
  api-reference/v1.0/api/chatmessage-get.md
  api-reference/v1.0/api/chatmessage-list-replies.md
  api-reference/v1.0/api/chatmessage-post-replies.md
  api-reference/v1.0/api/chatmessage-post.md
Labels: ready to merge, internal

#20755 Cloud Site List Management v1.0 Docs
  api-reference/v1.0/api/browsersharedcookie-get.md
  api-reference/v1.0/api/browsersharedcookie-update.md
  api-reference/v1.0/api/browsersite-get.md
  api-reference/v1.0/api/browsersite-update.md
  api-reference/v1.0/api/browsersitelist-delete-sharedcookies.md
  api-reference/v1.0/api/browsersitelist-delete-sites.md
  api-reference/v1.0/api/browsersitelist-get.md
  api-reference/v1.0/api/browsersitelist-list-sharedcookies.md
  api-reference/v1.0/api/browsersitelist-list-sites.md
  api-reference/v1.0/api/browsersitelist-post-sharedcookies.md
  api-reference/v1.0/api/browsersitelist-post-sites.md
  api-reference/v1.0/api/browsersitelist-publish.md
  api-reference/v1.0/api/browsersitelist-update.md
  api-reference/v1.0/api/internetexplorermode-delete-sitelists.md
  api-reference/v1.0/api/internetexplorermode-list-sitelists.md
  api-reference/v1.0/api/internetexplorermode-post-sitelists.md
  api-reference/v1.0/resources/admin.md
  api-reference/v1.0/resources/browser-edge-api-overview.md
  api-reference/v1.0/resources/browsersharedcookie.md
  api-reference/v1.0/resources/browsersharedcookiehistory.md
  api-reference/v1.0/resources/browsersite.md
  api-reference/v1.0/resources/browsersitehistory.md
  api-reference/v1.0/resources/browsersitelist.md
  api-reference/v1.0/resources/edge.md
  api-reference/v1.0/resources/enums.md
  api-reference/v1.0/resources/internetexplorermode.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.Edge.CloudSiteListManagement.json
Labels: ready to merge, internal, content review complete

#20870 Update dynamics-customerpayment.md
  api-reference/beta/resources/dynamics-customerpayment.md
Labels: external

#20873 Update listitem.md
  api-reference/beta/resources/listitem.md
Labels: external

#20866 Update description to clarify retricted experience on watermark unsupported client endpoint.
  api-reference/beta/resources/watermarkprotectionvalues.md
  concepts/cloud-communications-watermark-meeting.md
Labels: ready to merge, content review complete

#20880 Update synchronization-synchronizationjob-provisionondemand.md
  api-reference/beta/api/synchronization-synchronizationjob-provisionondemand.md
Labels: area: Azure AD, ready to merge, ready for content review, internal

#20882 Merge to publish.
  api-reference/beta/api/synchronization-synchronizationjob-provisionondemand.md
  api-reference/beta/resources/dynamics-customerpayment.md
  api-reference/beta/resources/listitem.md
  api-reference/beta/resources/watermarkprotectionvalues.md
  concepts/cloud-communications-watermark-meeting.md
Labels: do not merge, internal

#20886 Misspelling correction in first note section
  api-reference/v1.0/api/user-update.md
Labels: external

#20874 Remove leftover preview labels
  api-reference/v1.0/resources/browser-edge-api-overview.md
  concepts/browser-edge-concept-overview.md
  concepts/toc.yml
Labels: ready to merge, internal

#20603 Docs for GAing app-scoped chat subscriptions
  api-reference/v1.0/api/subscription-delete.md
  api-reference/v1.0/api/subscription-get.md
  api-reference/v1.0/api/subscription-list.md
  api-reference/v1.0/api/subscription-post-subscriptions.md
  api-reference/v1.0/api/subscription-update.md
  changelog/Microsoft.Teams.Core.json
  concepts/includes/change-notifications-supported-resources-expanded.md
  concepts/teams-changenotifications-chat.md
  concepts/teams-changenotifications-chatMembership.md
  concepts/teams-changenotifications-chatmessage.md
Labels: ready to merge, internal, content review complete, review feedback addressed

#20887 Merge to publish.
  api-reference/v1.0/api/subscription-delete.md
  api-reference/v1.0/api/subscription-get.md
  api-reference/v1.0/api/subscription-list.md
  api-reference/v1.0/api/subscription-post-subscriptions.md
  api-reference/v1.0/api/subscription-update.md
  api-reference/v1.0/api/user-update.md
  api-reference/v1.0/resources/browser-edge-api-overview.md
  changelog/Microsoft.Teams.Core.json
  concepts/browser-edge-concept-overview.md
  concepts/includes/change-notifications-supported-resources-expanded.md
  concepts/teams-changenotifications-chat.md
  concepts/teams-changenotifications-chatMembership.md
  concepts/teams-changenotifications-chatmessage.md
  concepts/toc.yml
Labels: internal

#20892 publish one set of perms content fix.
  api-reference/beta/api/chatmessage-setreaction.md
  api-reference/beta/api/chatmessage-softdelete.md
  api-reference/beta/api/chatmessage-undosoftdelete.md
  api-reference/beta/api/chatmessage-unsetreaction.md
  api-reference/beta/api/chatmessage-update.md
  api-reference/beta/api/profilephoto-get.md
  api-reference/beta/api/profilephoto-update.md
  api-reference/beta/api/site-list.md
  api-reference/v1.0/api/chatmessage-softdelete.md
  api-reference/v1.0/api/chatmessage-undosoftdelete.md
  api-reference/v1.0/api/chatmessage-update.md
  api-reference/v1.0/api/profilephoto-get.md
  api-reference/v1.0/api/profilephoto-update.md
  api-reference/v1.0/api/site-list.md
Labels: do not merge, internal

#20504 Add examples for developers familiar with SharePoint REST v1 API URL patterns
  api-reference/beta/resources/sharepoint.md
  api-reference/v1.0/resources/sharepoint.md
Labels: ready to merge, internal, content review complete

#20260 Document system preferred auth method
  api-reference/beta/api/authenticationmethodspolicy-get.md
  api-reference/beta/api/authenticationmethodspolicy-update.md
  api-reference/beta/resources/authentication.md
  api-reference/beta/resources/authenticationmethodspolicy.md
  api-reference/beta/resources/includetarget.md
  api-reference/beta/resources/signinpreferences.md
  api-reference/beta/resources/systemcredentialpreferences.md
  api-reference/beta/resources/user.md
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, ready to merge, internal, content review complete

#20903 Fix overlooked areas in PR 20891 earlier.
  api-reference/beta/api/profilephoto-get.md
  api-reference/beta/api/profilephoto-update.md
Labels: internal

#20885 Updating that 120+ doesn't fail
  api-reference/beta/api/user-list.md
  api-reference/beta/resources/user.md
  api-reference/v1.0/api/user-list.md
  api-reference/v1.0/resources/user.md
Labels: ready to merge, internal, content review complete

#20901 Fixing new name duplicates in http examples
  api-reference/beta/api/chat-post-installedapps.md
  api-reference/beta/api/userflowlanguagepage-delete.md
  api-reference/v1.0/api/browsersitelist-delete-sharedcookies.md
  api-reference/v1.0/api/browsersitelist-delete-sites.md
  api-reference/v1.0/api/browsersitelist-publish.md
  api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md
Labels: ready to merge, internal

#20890 Fixed grammar mistake
  api-reference/beta/api/group-list-transitivemembers.md
  api-reference/v1.0/api/group-list-transitivemembers.md
Labels: external, ready to merge

#20085 (Graph Beta) Docs for new PSTN and SMS reports
  api-reference/beta/api/callrecords-callrecord-getdirectroutingcalls.md
  api-reference/beta/api/callrecords-callrecord-getpstnblockeduserslog.md
  api-reference/beta/api/callrecords-callrecord-getpstncalls.md
  api-reference/beta/api/callrecords-callrecord-getpstnonlinemeetingdialoutreport.md
  api-reference/beta/api/callrecords-callrecord-getsmslog.md
  api-reference/beta/resources/callrecords-api-overview.md
  api-reference/beta/resources/callrecords-callrecord.md
  api-reference/beta/resources/callrecords-directroutinglogrow.md
  api-reference/beta/resources/callrecords-pstnblockeduserslogrow.md
  api-reference/beta/resources/callrecords-pstncalllogrow.md
  api-reference/beta/resources/callrecords-pstnonlinemeetingdialoutreport.md
  api-reference/beta/resources/callrecords-smslogrow.md
  api-reference/beta/resources/enums-callrecords.md
  api-reference/beta/toc.yml
  changelog/Microsoft.IC3.DataPlatform.json
Labels: ready to merge, internal, content review complete, schema live

#20900 Fix teamwork permission note
  api-reference/beta/api/team-get-installedapps.md
  api-reference/beta/api/team-list-installedapps.md
  includes/teams-app-installation-permission-note.md
  includes/teamwork-permissions-note.md
Labels: ready to merge, internal, content review complete

#20362 [CloudPC] Added User\CloudPC Start and Stop methods
  api-reference/beta/api/cloudpc-start.md
  api-reference/beta/api/cloudpc-stop.md
  api-reference/beta/resources/cloudpc.md
  api-reference/beta/toc.yml
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, internal, content review complete, schema live

#20711 Add ranking hints docs
  api-reference/beta/resources/enums-externalconnectors.md
  api-reference/beta/resources/externalconnectors-property.md
  api-reference/beta/resources/externalconnectors-rankinghint.md
  changelog/Microsoft.Search.json
Labels: ready to merge, internal, content review complete

#20365 [CloudPC] Added MEM admin poweron and poweroff actions
  api-reference/beta/api/cloudpc-poweroff.md
  api-reference/beta/api/cloudpc-poweron.md
  api-reference/beta/resources/cloudpc.md
  api-reference/beta/toc.yml
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, changes requested, internal, content review complete

#20915 Merge to publish.
  api-reference/beta/api/callrecords-callrecord-getdirectroutingcalls.md
  api-reference/beta/api/callrecords-callrecord-getpstnblockeduserslog.md
  api-reference/beta/api/callrecords-callrecord-getpstncalls.md
  api-reference/beta/api/callrecords-callrecord-getpstnonlinemeetingdialoutreport.md
  api-reference/beta/api/callrecords-callrecord-getsmslog.md
  api-reference/beta/api/cloudpc-poweroff.md
  api-reference/beta/api/cloudpc-poweron.md
  api-reference/beta/api/cloudpc-start.md
  api-reference/beta/api/cloudpc-stop.md
  api-reference/beta/api/team-get-installedapps.md
  api-reference/beta/api/team-list-installedapps.md
  api-reference/beta/resources/callrecords-api-overview.md
  api-reference/beta/resources/callrecords-callrecord.md
  api-reference/beta/resources/callrecords-directroutinglogrow.md
  api-reference/beta/resources/callrecords-pstnblockeduserslogrow.md
  api-reference/beta/resources/callrecords-pstncalllogrow.md
  api-reference/beta/resources/callrecords-pstnonlinemeetingdialoutreport.md
  api-reference/beta/resources/callrecords-smslogrow.md
  api-reference/beta/resources/cloudpc.md
  api-reference/beta/resources/enums-callrecords.md
  api-reference/beta/resources/enums-externalconnectors.md
  api-reference/beta/resources/externalconnectors-property.md
  api-reference/beta/resources/externalconnectors-rankinghint.md
  api-reference/beta/toc.yml
  changelog/Microsoft.CloudManagedDesktop.json
  changelog/Microsoft.IC3.DataPlatform.json
  changelog/Microsoft.Search.json
  includes/teams-app-installation-permission-note.md
  includes/teamwork-permissions-note.md
Labels: internal

#20725 Add PowerShell examples for Pronouns Settings
  concepts/pronouns-configure-pronouns-availability.md
Labels: ready to merge, internal, content review complete

#20920 Update event-delta.md
  api-reference/v1.0/api/event-delta.md
Labels: ready to merge, internal

#20921 fixing new issues with duplicate names
  api-reference/beta/api/industrydata-industrydataconnector-update.md
  api-reference/beta/api/webpart-get.md
  api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md
Labels: ready to merge, internal

#20931 Merge to publish.
  api-reference/beta/api/industrydata-industrydataconnector-update.md
  api-reference/beta/api/webpart-get.md
  api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md
  api-reference/v1.0/api/event-delta.md
  concepts/pronouns-configure-pronouns-availability.md
Labels: internal

#20125 changed text in permissions reference to reflect that deivce.readwrit…
  api-reference/beta/api/device-delete.md
  api-reference/v1.0/api/device-delete.md
  concepts/permissions-reference.md
Labels: area: Azure AD, ready to merge, internal, area: permissions, content review complete

#20933 Minor tweaks to extensions overview
  concepts/extensibility-open-users.md
  concepts/extensibility-overview.md
  concepts/extensibility-schema-groups.md
  concepts/migrate-azure-ad-graph-feature-differences.md
Labels: area: Azure AD, ready to merge, area: extensions

#20934 Permissions GUIDs drop - April
  concepts/includes/permissions-ids.md
Labels: area: Azure AD, ready to merge, internal

#20025 Add new workload Microsoft.Exchange.Rbac to beta endpoint
  api-reference/beta/api/rbacapplication-list-roleassignments.md
  api-reference/beta/api/rbacapplication-list-roledefinitions.md
  api-reference/beta/api/rbacapplication-post-roleassignments.md
  api-reference/beta/api/unifiedroleassignment-delete.md
  api-reference/beta/api/unifiedroleassignment-get.md
  api-reference/beta/api/unifiedroledefinition-get.md
  api-reference/beta/resources/rolemanagement.md
  api-reference/beta/resources/unifiedrbacapplication.md
  api-reference/beta/resources/unifiedroledefinition.md
  changelog/Microsoft.DirectoryServices.json
  concepts/permissions-reference.md
Labels: ready to merge, internal, content review complete, schema live, review feedback addressed

#20652 Correct errors within code snippets tab section
  api-reference/beta/api/crosstenantaccesspolicy-update.md
  api-reference/beta/api/drive-get-specialfolder.md
  api-reference/beta/api/drive-get.md
  api-reference/beta/api/drive-list-following.md
  api-reference/beta/api/drive-list.md
  api-reference/beta/api/drive-recent.md
  api-reference/beta/api/drive-sharedwithme.md
  api-reference/beta/api/driveitem-createlink.md
  api-reference/beta/api/ediscovery-case-post-reviewsets.md
  api-reference/beta/api/ediscovery-reviewset-addtoreviewset.md
  api-reference/beta/api/identityprovider-delete.md
  api-reference/beta/api/identityprovider-list-availableprovidertypes.md
  api-reference/beta/api/identityprovider-post-identityproviders.md
  api-reference/beta/api/identityprovider-update.md
  api-reference/beta/api/learningcontent-update.md
  api-reference/beta/api/outlookuser-post-tasks.md
  api-reference/beta/api/presence-setstatusmessage.md
  api-reference/beta/api/riskyusers-confirmcompromised.md
  api-reference/beta/api/riskyusers-dismiss.md
  api-reference/beta/api/simulationreportoverview-get.md
  api-reference/beta/api/teamsappsettings-update.md
  api-reference/beta/api/user-list-approleassignedresources.md
  api-reference/beta/resources/appManagementPolicy.md
  api-reference/v1.0/api/appManagementPolicy-delete.md
  api-reference/v1.0/api/drive-get-specialfolder.md
  api-reference/v1.0/api/drive-get.md
  api-reference/v1.0/api/drive-list-following.md
  api-reference/v1.0/api/drive-list.md
  api-reference/v1.0/api/drive-recent.md
  api-reference/v1.0/api/drive-sharedwithme.md
  api-reference/v1.0/api/identityprovider-update.md
Labels: ready to merge, internal

#20948 Edits in PR 20786
  api-reference/beta/api/drive-sharedwithme.md
  api-reference/v1.0/api/drive-sharedwithme.md
Labels: external

#20950 Edits in PR 19952
  api-reference/beta/resources/plannertask.md
  api-reference/beta/resources/plannertaskpropertyrule.md
  changelog/Microsoft.BusinessExtensibility.json
  changelog/Microsoft.Office.Tasks.json
  changelog/Microsoft.Tasks.json
Labels: external

#20955 Update driveitem-assignsensitivitylabel.md
  api-reference/beta/api/driveitem-assignsensitivitylabel.md
Labels: ready to merge

#19936 Add Forms Reports Graph API Doc
  api-reference/beta/api/reportroot-getformsuseractivitycounts.md
  api-reference/beta/api/reportroot-getformsuseractivityusercounts.md
  api-reference/beta/api/reportroot-getformsuseractivityuserdetail.md
  api-reference/beta/resources/microsoft-forms-usage-reports.md
  api-reference/beta/resources/report.md
  api-reference/beta/toc.yml
  changelog/Microsoft.O365Reporting.json
Labels: ready to merge, internal, content review complete

#20782 Virtual appointment function updates to beta
  api-reference/beta/api/virtualappointment-delete.md
  api-reference/beta/api/virtualappointment-get.md
  api-reference/beta/api/virtualappointment-getvirtualappointmentjoinweburl.md
  api-reference/beta/api/virtualappointment-put.md
  api-reference/beta/api/virtualappointment-update.md
  api-reference/beta/resources/virtualappointment.md
  api-reference/beta/resources/virtualappointmentsettings.md
  api-reference/beta/resources/virtualappointmentuser.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Skype.Calling.json
Labels: ready to merge, internal, content review complete, schema live, review feedback addressed

#20979 Updating fabric bot rules
  .github/fabricbot.json
Labels: ready to merge, internal

#19682 Minor changes for sitePage related API
  api-reference/beta/api/sitepage-create.md
  api-reference/beta/api/sitepage-delete.md
  api-reference/beta/api/sitepage-get.md
  api-reference/beta/api/sitepage-list.md
  api-reference/beta/api/sitepage-publish.md
  api-reference/beta/api/sitepage-update.md
Labels: ready to merge, internal, content review complete, review feedback addressed

#20932 Refresh advanced query capabilities articles
  concepts/aad-advanced-queries.md
  concepts/filter-query-parameter.md
  includes/filter-directory-objects.md
Labels: area: Azure AD, ready to merge, internal

#20845 Update deviceregistrationpolicy.md
  api-reference/beta/api/deviceregistrationpolicy-get.md
  api-reference/beta/api/deviceregistrationpolicy-update.md
  api-reference/beta/resources/deviceregistrationpolicy.md
  api-reference/beta/resources/localadminpasswordsettings.md
  changelog/Microsoft.DeviceRegistrationPolicies.json
Labels: area: Azure AD, resolved: awaiting prod deployment, ready to merge, internal, content review complete, review feedback addressed

#20980 Update get-links-to-assignments-and-submissions.md
  concepts/get-links-to-assignments-and-submissions.md
Labels: ready to merge, internal

#20944 Add permissions header to topic
  api-reference/beta/api/connectorgroup-post-members.md
Labels: ready to merge, internal

#20984 Edits in PR 20791
  api-reference/beta/api/driveitem-getretentionlabel.md
  api-reference/beta/api/driveitem-lockorunlockrecord.md
  api-reference/beta/api/driveitem-removeretentionlabel.md
  api-reference/beta/api/driveitem-setretentionlabel.md
  api-reference/beta/resources/driveitem.md
  api-reference/beta/resources/itemRetentionLabel.md
  api-reference/beta/resources/itemretentionlabel.md
  api-reference/beta/resources/retentionLabelSettings.md
  api-reference/beta/resources/retentionlabelsettings.md
  api-reference/beta/toc.yml
  changelog/Microsoft.FileServices.json
Labels: external

#20557 Viva Learning Course Activity Public Preview Graph Documentation
  api-reference/beta/api/employeeexperienceuser-post-learningcourseactivities.md
  api-reference/beta/api/learningcourseactivity-delete.md
  api-reference/beta/api/learningcourseactivity-get.md
  api-reference/beta/api/learningcourseactivity-list.md
  api-reference/beta/api/learningcourseactivity-update.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/learningassignment.md
  api-reference/beta/resources/learningcourseactivity.md
  api-reference/beta/resources/learningselfinitiatedcourse.md
  api-reference/beta/resources/viva-learning-api-overview.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Viva.Learning.json
  concepts/permissions-reference.md
Labels: ready to merge, internal, content review complete

#20995 Update outlook-send-mime-message.md
  concepts/outlook-send-mime-message.md
Labels: ready to merge, internal

#20836 Docs refresh: lifecycle notifications
  api-reference/beta/api/subscription-reauthorize.md
  api-reference/beta/resources/subscription.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/subscription-reauthorize.md
  api-reference/v1.0/resources/subscription.md
  api-reference/v1.0/toc.yml
  concepts/change-notifications-delivery-event-hubs.md
  concepts/change-notifications-delivery-webhooks.md
  concepts/includes/change-notifications-delivery-notificationurl-validation.md
  concepts/webhooks-lifecycle.md
  concepts/webhooks.md
Labels: area: Azure AD, ready to merge, internal, area: change notifications

#20781 docs: update the mgt file list documentation page
  concepts/toolkit/components/file-list.md
Labels: ready to merge, internal, content review complete

#20908 docs: update the mgt people documentation page
  concepts/toolkit/components/people.md
Labels: ready to merge, internal

#20981 Breadcrumb test
  concepts/breadcrumb/toc.yml
Labels: external, ready to merge

#20829 Ship queryTemplate to v1.0 doc
  api-reference/v1.0/api/search-query.md
  api-reference/v1.0/resources/searchquery.md
  api-reference/v1.0/resources/searchrequest.md
  changelog/Microsoft.Search.json
Labels: ready to merge, internal, content review complete

#20945 Update doctype of resource topics with erroneous value in YAML frontmatter
  api-reference/beta/resources/appManagementPolicy.md
  api-reference/beta/resources/authenticationmethodconfiguration.md
  api-reference/beta/resources/authenticationmethodtarget.md
  api-reference/beta/resources/educationassignmentdefaults.md
  api-reference/beta/resources/educationonpremisesinfo.md
  api-reference/beta/resources/educationsynchronizationoauth2clientcredentialsconnectionsettings.md
  api-reference/beta/resources/emailauthenticationmethod.md
  api-reference/beta/resources/fido2authenticationmethod.md
  api-reference/beta/resources/fido2authenticationmethodconfiguration.md
  api-reference/beta/resources/fido2keyrestrictions.md
  api-reference/beta/resources/identitysecuritydefaultsenforcementpolicy.md
  api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethod.md
  api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md
  api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethodtarget.md
  api-reference/beta/resources/security-ediscoverysearch.md
  api-reference/beta/resources/securityreportsroot.md
  api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md
  api-reference/beta/resources/tenantAppManagementPolicy.md
  api-reference/v1.0/resources/appManagementPolicy.md
  api-reference/v1.0/resources/authenticationmethodconfiguration.md
  api-reference/v1.0/resources/authenticationmethodtarget.md
  api-reference/v1.0/resources/educationassignmentdefaults.md
  api-reference/v1.0/resources/emailauthenticationmethod.md
  api-reference/v1.0/resources/fido2authenticationmethod.md
  api-reference/v1.0/resources/fido2authenticationmethodconfiguration.md
  api-reference/v1.0/resources/fido2keyrestrictions.md
  api-reference/v1.0/resources/identitysecuritydefaultsenforcementpolicy.md
  api-reference/v1.0/resources/security-ediscoverysearch.md
  api-reference/v1.0/resources/securityreportsroot.md
  api-reference/v1.0/resources/temporaryaccesspassauthenticationmethodconfiguration.md
  api-reference/v1.0/resources/tenantAppManagementPolicy.md
Labels: ready to merge, internal

#20946 Add suppression for error flagged by new API Doctor version
  api-reference/beta/api/group-post-members.md
Labels: ready to merge, internal

#20991 Update update-assignment-and-grade-data.md
  concepts/update-assignment-and-grade-data.md
Labels: ready to merge, internal

#20990 update attributefunctionmappingschema
  api-reference/beta/resources/synchronization-attributemappingfunctionschema.md
Labels: area: Azure AD, ready to merge, internal, content review complete

#20896 docs: update the mgt-person-card docs
  concepts/toolkit/components/person-card.md
Labels: ready to merge, internal

#20993 Update whats-new-earlier.md
  concepts/whats-new-earlier.md
Labels: ready to merge, internal

#20909 docs: update the mgt login documentation page
  concepts/toolkit/components/login.md
Labels: ready to merge, internal

#21002 Edits in PR 20791
  api-reference/beta/api/driveitem-removeretentionlabel.md
  api-reference/beta/api/driveitem-setretentionlabel.md
  api-reference/beta/resources/itemretentionlabel.md
  api-reference/beta/resources/retentionlabelsettings.md
Labels: external

#20780 docs: update mgt-file component documentation page
  concepts/toolkit/components/file.md
Labels: ready to merge, ready for content review, internal

#20848 [Doc Improvement] [Updates teams app settings][3002790]
  api-reference/beta/api/teamsappsettings-update.md
  api-reference/beta/resources/teamsappsettings.md
Labels: ready to merge, internal, content review complete

#19895 add chat history flag to onlinemeeting
  api-reference/beta/resources/onlinemeeting.md
  changelog/Microsoft.Skype.Calling.json
Labels: ready to merge, internal, content review complete

#21006 Update security-incident-update.md to reflect changes for the false positive determination
  api-reference/beta/api/security-incident-update.md
  api-reference/v1.0/api/security-incident-update.md
Labels: external, ready to merge

#21003 Update person.md with new css tokens
  concepts/toolkit/components/person.md
Labels: ready to merge, ready for content review, internal

#20295 Entitlement Management + Verified ID
  api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md
  api-reference/beta/api/accesspackageassignmentpolicy-get.md
  api-reference/beta/api/accesspackageassignmentpolicy-update.md
  api-reference/beta/api/customaccesspackageworkflowextension-delete.md
  api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md
  api-reference/beta/resources/accesspackageassignmentpolicy.md
  api-reference/beta/resources/accesspackageassignmentrequest.md
  api-reference/beta/resources/accesspackageassignmentrequestrequirements.md
  api-reference/beta/resources/customextensionhandler.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/verifiablecredentialrequired.md
  api-reference/beta/resources/verifiablecredentialrequirementstatus.md
  api-reference/beta/resources/verifiablecredentialretrieved.md
  api-reference/beta/resources/verifiablecredentialsettings.md
  api-reference/beta/resources/verifiablecredentialtype.md
  api-reference/beta/resources/verifiablecredentialverified.md
  api-reference/beta/resources/verifiedcredentialclaims.md
  api-reference/beta/resources/verifiedcredentialdata.md
  changelog/Microsoft.IGAELM.json
Labels: area: Azure AD, ready to merge, internal, content review complete, area: governance

#21004 Add Event Grid change delivery channel
  concepts/toc.yml
  concepts/webhooks-lifecycle.md
  concepts/webhooks.md
Labels: area: Azure AD, ready to merge, internal, area: change notifications

#21008 Update toc.yml
  api-reference/beta/api/devicelocalcredentialinfo-get.md
  api-reference/beta/toc.yml
Labels: ready to merge, content review complete

#21009 Update group-list-members.md
  api-reference/v1.0/api/group-list-members.md
Labels: ready to merge, internal

#21011 tags property supports $search
  api-reference/beta/resources/application.md
  api-reference/v1.0/resources/application.md
Labels: area: Azure AD, ready to merge, internal

#21013 Fixed bug in docs
  api-reference/beta/resources/device.md
  api-reference/v1.0/resources/device.md
Labels: ready to merge, internal, content review complete

#20918 docs: Adds picker.md to document mgt-picker
  concepts/toolkit/components/picker.md
Labels: ready to merge, internal

#20919 docs: update agenda.md
  concepts/toolkit/components/agenda.md
Labels: ready to merge, ready for content review, internal

#21028 Custom task extension property fix
  api-reference/beta/resources/identitygovernance-customtaskextension.md
Labels: area: Azure AD, ready to merge, internal

#20958 Promote allowedToReadBitlockerKeysForOwnedDevice from beta to v1
  api-reference/v1.0/resources/defaultuserrolepermissions.md
  changelog/Microsoft.DirectoryServices.json
Labels: ready to merge, ready for content review, internal

#21012 Breadcrumb fix
  concepts/breadcrumb/toc.yml
  concepts/docfx.json
Labels: external

#21022 Edits in PR 20929
  concepts/changenotifications-for-virtualevent.md
Labels: external, conflicting

#20994 Update msgraph-onboarding-sds.md
  concepts/msgraph-onboarding-sds.md
Labels: do not merge, review requested, ready for content review, internal

#21045 Edits in PR 20929
  concepts/changenotifications-for-virtualevent.md
  concepts/toc.yml
Labels: external

#21047 Update auth-limit-mailbox-access.md
  concepts/auth-limit-mailbox-access.md
Labels: external

#21044 Update learningassignment.md
  api-reference/beta/resources/learningassignment.md
Labels: external, ready to merge

#21043 Update learningcourseactivity.md
  api-reference/beta/resources/learningcourseactivity.md
Labels: external, ready to merge

#21042 Update learningcourseactivity-list.md
  api-reference/beta/api/learningcourseactivity-list.md
Labels: external

#21041 Update employeeexperienceuser-post-learningcourseactivities.md
  api-reference/beta/api/employeeexperienceuser-post-learningcourseactivities.md
Labels: external

#21040 Update learningcourseactivity-get.md
  api-reference/beta/api/learningcourseactivity-get.md
Labels: external

#21039 Update learningcourseactivity-update.md
  api-reference/beta/api/learningcourseactivity-update.md
Labels: external

#21038 Update learningcourseactivity-delete.md
  api-reference/beta/api/learningcourseactivity-delete.md
Labels: external

#21036 Update communications-api-overview.md
  api-reference/beta/resources/communications-api-overview.md
Labels: external

#21035 Update communications-api-overview.md
  api-reference/v1.0/resources/communications-api-overview.md
Labels: external

#21034 Update planner-list-plans.md
  api-reference/v1.0/api/planner-list-plans.md
Labels: external

#21033 Update planner-list-plans.md
  api-reference/beta/api/planner-list-plans.md
Labels: external

#19822 Updated description of preferredTokenSigningKeyThumbprint property on service principal
  api-reference/beta/resources/serviceprincipal.md
  api-reference/v1.0/resources/serviceprincipal.md
Labels: area: Azure AD, ready to merge, internal

#19229 docs: update the provider documentation for MGT Providers
  concepts/toolkit/providers/electron.md
  concepts/toolkit/providers/msal.md
  concepts/toolkit/providers/msal2.md
  concepts/toolkit/providers/sharepoint.md
  concepts/toolkit/providers/teams-msal2.md
  concepts/toolkit/providers/teams.md
  concepts/toolkit/providers/teamsfx.md
Labels: ready to merge, internal

#20974 [CloudPC] Update permission for some APIs
  api-reference/beta/api/cloudpc-getsupportedcloudpcremoteactions.md
  api-reference/beta/api/cloudpcexportjob-get.md
  api-reference/beta/api/cloudpcorganizationsettings-update.md
  api-reference/beta/api/cloudpcreports-post-exportjobs.md
  api-reference/beta/api/cloudpcusersetting-update.md
  api-reference/beta/api/manageddevice-getcloudpcremoteactionresults.md
  api-reference/beta/api/unifiedroleassignmentmultiple-update.md
  api-reference/beta/toc.yml
Labels: ready to merge, content review complete

#21048 Minor doc fixes
  concepts/add-properties-profilecard.md
  concepts/migrate-azure-ad-graph-overview.md
  concepts/webhooks.md
Labels: area: Azure AD, ready to merge, internal

#21050 [Azure AD] Cross-tenant sync role beta
  api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-put-identitysynchronization.md
  api-reference/beta/api/crosstenantidentitysyncpolicypartner-delete.md
  api-reference/beta/api/crosstenantidentitysyncpolicypartner-get.md
  api-reference/beta/api/crosstenantidentitysyncpolicypartner-update.md
Labels: ready to merge, internal

#20859 Updating CallRecords API documentation - New fields added
  api-reference/beta/api/callrecords-callrecord-get.md
  api-reference/beta/api/callrecords-session-list.md
  api-reference/beta/resources/callrecords-mediastream.md
  api-reference/beta/resources/callrecords-participantendpoint.md
  api-reference/beta/resources/callrecords-session.md
  changelog/Microsoft.IC3.DataPlatform.json
Labels: ready to merge, internal, content review complete

#21055 Edits in PR 20791
  api-reference/beta/api/driveitem-lockorunlockrecord.md
  api-reference/beta/api/driveitem-removeretentionlabel.md
  api-reference/beta/api/driveitem-setretentionlabel.md
  api-reference/beta/resources/itemretentionlabel.md
Labels: external

#21068 fixing duplicate name
  api-reference/beta/api/virtualappointment-getvirtualappointmentjoinweburl.md
Labels: ready to merge, internal

#20674 Add ssoCheckKerberosConfigurationError type in cloudPcOnPremisesConne…
  api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, internal

#20777 docs: update how to theme components
  concepts/toolkit/customize-components/style.md
  concepts/toolkit/images/login-fluentui-override-dark.png
  concepts/toolkit/images/login-fluentui-override.png
Labels: ready to merge, internal

#21007 docs: update mgt-people-picker component documentation page
  concepts/toolkit/components/people-picker.md
Labels: ready to merge, ready for content review, internal

#21074 Edits in PR 20996
  api-reference/beta/api/virtualappointment-getvirtualappointmentjoinweburl.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/virtualappointment-getvirtualappointmentjoinweburl.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.Skype.Calling.json
Labels: external

#21082 signInActivity updated on all attempts
  api-reference/beta/resources/signinactivity.md
  api-reference/v1.0/resources/signinactivity.md
Labels: ready to merge, internal

#21065 Update wrongly formatted HTTP requests
  api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md
  api-reference/beta/api/ediscovery-custodian-post-unifiedgroupsources.md
  api-reference/beta/api/ediscovery-unifiedgroupsource-delete.md
  api-reference/beta/api/listitem-createlink.md
  api-reference/v1.0/api/rbacapplication-list-roledefinitions.md
  api-reference/v1.0/api/termstore-group-delete.md
  api-reference/v1.0/api/termstore-group-get.md
  api-reference/v1.0/api/termstore-group-post.md
  api-reference/v1.0/api/termstore-list-groups.md
  api-reference/v1.0/api/termstore-relation-post.md
  api-reference/v1.0/api/termstore-set-get.md
  api-reference/v1.0/api/termstore-set-post.md
  api-reference/v1.0/api/termstore-set-update.md
  api-reference/v1.0/api/termstore-store-get.md
  api-reference/v1.0/api/termstore-term-delete.md
  api-reference/v1.0/api/termstore-term-get.md
  api-reference/v1.0/api/termstore-term-list-children.md
  api-reference/v1.0/api/termstore-term-list-relations.md
  api-reference/v1.0/api/termstore-term-post.md
  api-reference/v1.0/api/termstore-term-update.md
Labels: internal, content review complete

#20434 Documentation update to Graph beta for Delta Roster
  api-reference/beta/api/application-post-calls.md
  api-reference/beta/resources/deltaparticipants.md
  api-reference/beta/resources/participant.md
  api-reference/beta/resources/removedstate.md
  changelog/Microsoft.Skype.Calling.json
Labels: ready to merge, content review complete, schema live

#21086 Edits in PR 21058
  api-reference/beta/api/devicemanagement-alertrule-post.md
  api-reference/beta/resources/devicemanagement-alertrecord.md
  api-reference/beta/resources/devicemanagement-alertrule.md
  api-reference/beta/resources/devicemanagement-portalnotification.md
  changelog/Microsoft.DeviceManagement.Monitoring.json
Labels: external

#21093 Update whats-new-overview.md
  concepts/whats-new-overview.md
Labels: external

#21094 Update subjectrightsrequest-subjectrightsrequestapioverview.md
  api-reference/beta/resources/subjectrightsrequest-subjectrightsrequestapioverview.md
Labels: external
