Repository microsoftgraph/microsoft-graph-docs, pull requests merged in 2023-03, with the labels that each got.

#20396 Update dynamics-taxgroups.md
  api-reference/beta/resources/dynamics-taxgroups.md
Labels: external

#20384 [BrokenLinksH2] | Fixed broken links | Bulk Update
  api-reference/beta/api/chart-image.md
  api-reference/beta/api/images/GetChart-default.png
  api-reference/beta/api/images/GetChart-fill.png
  api-reference/beta/api/intune-enrollment-importedappledeviceidentity-create.md
  api-reference/beta/api/intune-enrollment-importedappledeviceidentity-update.md
  api-reference/beta/api/intune-shared-deviceappmanagement-get.md
  api-reference/beta/api/intune-shared-deviceappmanagement-update.md
  api-reference/beta/api/intune-shared-devicecategory-get.md
  api-reference/beta/api/intune-shared-devicemanagement-get.md
  api-reference/beta/api/intune-shared-reportroot-get.md
  api-reference/beta/resources/changenotificationencryptedcontent.md
  api-reference/beta/resources/intune-enrollment-depenrollmentbaseprofile.md
  api-reference/beta/resources/intune-enrollment-importedappledeviceidentity.md
  api-reference/beta/resources/intune-graph-overview.md
  api-reference/beta/resources/plannerplancontainer.md
  api-reference/v1.0/resources/intune-graph-overview.md
  api-reference/v1.0/resources/plannerplancontainer.md
Labels: external, ready to merge

#20393 [Bulk] Broken Link fixes
  api-reference/beta/api/bookingbusiness-getstaffavailability.md
  api-reference/beta/api/contenttype-post-columns.md
  api-reference/beta/api/group-delete-owners.md
  api-reference/beta/api/intune-enrollment-depenrollmentprofile-create.md
  api-reference/beta/api/intune-enrollment-depenrollmentprofile-update.md
  api-reference/beta/api/intune-enrollment-depiosenrollmentprofile-create.md
  api-reference/beta/api/intune-enrollment-depiosenrollmentprofile-update.md
  api-reference/beta/api/intune-enrollment-depmacosenrollmentprofile-create.md
  api-reference/beta/api/intune-enrollment-depmacosenrollmentprofile-update.md
  api-reference/beta/api/intune-shared-devicemanagementderivedcredentialsettings-update.md
  api-reference/beta/api/intune-shared-user-get.md
  api-reference/beta/api/intune-shared-windowsdomainjoinconfiguration-get.md
  api-reference/beta/api/intune-shared-windowsupdatestate-create.md
  api-reference/beta/api/intune-shared-windowsupdatestate-update.md
  api-reference/beta/api/list-post-columns.md
  api-reference/beta/api/rangeformat-update.md
  api-reference/v1.0/api/bookingbusiness-getstaffavailability.md
Labels: external, ready to merge

#19750 [Doc Improvement][Update graph samples][2817941]
  api-reference/beta/api/chat-post-pinnedmessages.md
  api-reference/beta/api/chat-sendactivitynotification.md
  api-reference/beta/api/team-sendactivitynotification.md
  api-reference/beta/api/userteamwork-sendactivitynotification.md
  api-reference/beta/resources/channel.md
  api-reference/beta/resources/chat.md
  api-reference/beta/resources/event.md
  api-reference/beta/resources/teamsapp.md
  api-reference/beta/resources/teamsappinstallation.md
  api-reference/beta/resources/webhooks.md
  api-reference/v1.0/api/chat-post-pinnedmessages.md
  api-reference/v1.0/api/chat-sendactivitynotification.md
  api-reference/v1.0/api/team-sendactivitynotification.md
  api-reference/v1.0/api/userteamwork-sendactivitynotification.md
  api-reference/v1.0/resources/channel.md
  api-reference/v1.0/resources/chat.md
  api-reference/v1.0/resources/event.md
  api-reference/v1.0/resources/teamsapp.md
  api-reference/v1.0/resources/teamsappinstallation.md
  api-reference/v1.0/resources/webhooks.md
  concepts/changenotifications-for-onlinemeeting.md
  concepts/teams-changenotifications-chat.md
  concepts/teams-changenotifications-team-and-channel.md
  concepts/webhooks-with-resource-data.md
Labels: ready to merge, internal, review feedback addressed

#20153 GA ACS user conversation member for Teams
  api-reference/v1.0/resources/azurecommunicationservicesuserconversationmember.md
  api-reference/v1.0/resources/conversationmember.md
  changelog/Microsoft.Teams.GraphSvc.json
Labels: ready to merge, content review complete

#20242 Add new synchronization permissions
  api-reference/beta/api/synchronization-synchronization-acquireaccesstoken.md
  api-reference/beta/api/synchronization-synchronization-secrets.md
  api-reference/beta/api/synchronization-synchronizationjob-delete.md
  api-reference/beta/api/synchronization-synchronizationjob-get.md
  api-reference/beta/api/synchronization-synchronizationjob-list.md
  api-reference/beta/api/synchronization-synchronizationjob-pause.md
  api-reference/beta/api/synchronization-synchronizationjob-post.md
  api-reference/beta/api/synchronization-synchronizationjob-provision-on-demand.md
  api-reference/beta/api/synchronization-synchronizationjob-restart.md
  api-reference/beta/api/synchronization-synchronizationjob-start.md
  api-reference/beta/api/synchronization-synchronizationjob-validatecredentials.md
  api-reference/beta/api/synchronization-synchronizationschema-delete.md
  api-reference/beta/api/synchronization-synchronizationschema-filteroperators.md
  api-reference/beta/api/synchronization-synchronizationschema-functions.md
  api-reference/beta/api/synchronization-synchronizationschema-get.md
  api-reference/beta/api/synchronization-synchronizationschema-parseexpression.md
  api-reference/beta/api/synchronization-synchronizationschema-update.md
  api-reference/beta/api/synchronization-synchronizationtemplate-get.md
  api-reference/beta/api/synchronization-synchronizationtemplate-list.md
  api-reference/beta/api/synchronization-synchronizationtemplate-update.md
  changelog/Microsoft.DirectoryServices.json
  concepts/permissions-reference.md
Labels: area: Azure AD, ready to merge, internal, content review complete

#18960 [CloudPC]Add the provisioningType property to CloudPC entity
  api-reference/beta/api/cloudpc-get.md
  api-reference/beta/api/user-list-cloudpcs.md
  api-reference/beta/api/virtualendpoint-list-cloudpcs.md
  api-reference/beta/resources/cloudpc.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, internal, content review complete

#20310 [Viva Learning] PR for removal of isEnabled from LearningProvider schema
  api-reference/beta/api/employeeexperience-list-learningproviders.md
  api-reference/beta/api/employeeexperience-post-learningproviders.md
  api-reference/beta/api/learningprovider-get.md
  api-reference/beta/api/learningprovider-update.md
  api-reference/beta/resources/learningprovider.md
  api-reference/beta/resources/viva-learning-api-overview.md
  changelog/Microsoft.Viva.Learning.json
Labels: ready to merge, content review complete

#20382 [Azure AD] appRoleAssignedResources and count
  api-reference/beta/api/unifiedroledefinition-assignedprincipals.md
  api-reference/beta/api/user-list-approleassignedresources.md
Labels: area: Azure AD, ready to merge, internal

#20282 Calendars.ReadBasic permission
  api-reference/beta/api/calendar-get.md
  api-reference/beta/api/calendar-getschedule.md
  api-reference/beta/api/calendar-list-calendarpermissions.md
  api-reference/beta/api/calendar-list-calendarview.md
  api-reference/beta/api/calendar-list-events.md
  api-reference/beta/api/calendargroup-get.md
  api-reference/beta/api/calendargroup-list-calendars.md
  api-reference/beta/api/calendarpermission-get.md
  api-reference/beta/api/event-delta.md
  api-reference/beta/api/event-get.md
  api-reference/beta/api/event-list-instances.md
  api-reference/beta/api/user-list-calendargroups.md
  api-reference/beta/api/user-list-calendars.md
  api-reference/beta/api/user-list-calendarview.md
  api-reference/beta/api/user-list-events.md
  api-reference/beta/api/user-reminderview.md
  changelog/Microsoft.Exchange.json
Labels: ready to merge, content review complete

#20406 Edits in PR 20343
  api-reference/beta/api/employeeexperience-post-learningproviders.md
  api-reference/beta/api/learningcontent-update.md
  api-reference/beta/api/learningprovider-get.md
  api-reference/beta/api/learningprovider-update.md
  api-reference/beta/resources/learningcontent.md
  api-reference/beta/resources/learningprovider.md
  api-reference/beta/resources/teams-api-overview.md
  api-reference/beta/resources/viva-learning-api-overview.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/employeeexperience-delete-learningproviders.md
  api-reference/v1.0/api/employeeexperience-list-learningproviders.md
  api-reference/v1.0/api/employeeexperience-post-learningproviders.md
  api-reference/v1.0/api/learningcontent-get.md
  api-reference/v1.0/api/learningcontent-update.md
  api-reference/v1.0/api/learningprovider-delete-learningcontents.md
  api-reference/v1.0/api/learningprovider-get.md
  api-reference/v1.0/api/learningprovider-list-learningcontents.md
  api-reference/v1.0/api/learningprovider-update.md
  api-reference/v1.0/resources/employeeexperience.md
  api-reference/v1.0/resources/learningcontent.md
  api-reference/v1.0/resources/learningprovider.md
  api-reference/v1.0/resources/viva-learning-api-overview.md
  changelog/Microsoft.Viva.Learning.json
  concepts/overview-major-services.md
  concepts/teams-concept-overview.md
Labels: external

#20408 Started Feb updates.
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: do not merge, internal

#20409 Publish a few items from February in the what's new topic.
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: internal

#20415 Update authenticationmethods-overview.md
  api-reference/v1.0/resources/authenticationmethods-overview.md
Labels: external

#20422 Remove space to fix formatting.
  api-reference/beta/api/teamsappsettings-update.md
Labels: do not merge, internal

#20405 [BrokenLinksH2] | Fixed broken links 2 | Bulk Update
  api-reference/beta/api/search-query.md
  api-reference/beta/api/security-emailthreatsubmissionpolicy-post-emailthreatsubmissionpolicies.md
  api-reference/beta/api/security-emailthreatsubmissionpolicy-update.md
  api-reference/beta/api/site-post-columns.md
  api-reference/beta/api/teamworkbot-get.md
  api-reference/beta/resources/changenotificationcollection.md
  api-reference/beta/resources/ediscovery-sitesource.md
  api-reference/beta/resources/eventmessage.md
  api-reference/beta/resources/eventmessagerequest.md
  api-reference/beta/resources/eventmessageresponse.md
  api-reference/beta/resources/message.md
  api-reference/beta/resources/onedrive.md
  api-reference/includes/outlook-mailbox-type-support.md
Labels: external, ready to merge

#19778 Added 'employeeLeaveDateTime' to 'User' object.
  api-reference/beta/api/user-update.md
  api-reference/beta/resources/user.md
  api-reference/v1.0/api/user-update.md
  api-reference/v1.0/resources/user.md
  changelog/Microsoft.DirectoryServices.json
  concepts/tutorial-lifecycle-workflows-set-employeeleavedatetime.md
Labels: area: Azure AD, ready to merge, internal, content review complete, schema live

#20379 Update code samples for V5 dotnet
  concepts/sdks/batch-requests.md
  concepts/sdks/choose-authentication-providers.md
  concepts/sdks/customize-client.md
  concepts/sdks/includes/snippets/csharp/create-requests-create.md
  concepts/sdks/includes/snippets/csharp/create-requests-delete.md
  concepts/sdks/includes/snippets/csharp/create-requests-expand.md
  concepts/sdks/includes/snippets/csharp/create-requests-headers.md
  concepts/sdks/includes/snippets/csharp/create-requests-index.md
  concepts/sdks/includes/snippets/csharp/create-requests-list.md
  concepts/sdks/includes/snippets/csharp/create-requests-queryparams.md
  concepts/sdks/includes/snippets/csharp/create-requests-read.md
  concepts/sdks/includes/snippets/csharp/create-requests-select.md
  concepts/sdks/includes/snippets/csharp/create-requests-update.md
  concepts/sdks/large-file-upload.md
  concepts/sdks/national-clouds.md
  concepts/sdks/paging.md
Labels: ready to merge

#20388 Minor doc fixes
  api-reference/beta/resources/identitygovernance-lifecycleworkflowscontainer.md
  api-reference/beta/resources/identitygovernance.md
  concepts/known-issues.md
Labels: area: Azure AD, ready to merge

#20049 Add sendNotification parameter to createlink api to enable email sending feature for createlink
  api-reference/beta/api/driveitem-createlink.md
  api-reference/beta/api/listitem-createlink.md
  api-reference/v1.0/api/driveitem-createlink.md
  changelog/Microsoft.FileServices.json
Labels: ready to merge, internal, content review complete

#20400 Update connecting-external-content-manage-connections.md
  concepts/connecting-external-content-manage-connections.md
  concepts/images/connectors-images/share-activity-recommendation-example.png
Labels: awaiting internal response, ready to merge, internal, content review complete

#20425 Edits in PR 20052
  api-reference/beta/api/payload-get.md
  api-reference/beta/api/simulation-get.md
  api-reference/beta/api/simulationautomation-get.md
  api-reference/beta/resources/payload.md
  api-reference/beta/resources/payloadcoachmark.md
  api-reference/beta/resources/simulationautomation.md
  api-reference/v1.0/api/simulation-get.md
  api-reference/v1.0/api/simulationautomation-get.md
  api-reference/v1.0/resources/simulationautomation.md
  concepts/whats-new-earlier.md
  redirects/.openpublishing.redirection.0223.json
Labels: external

#20426 Edits in PR 20343
  api-reference/beta/api/employeeexperience-delete-learningproviders.md
  api-reference/beta/api/employeeexperience-list-learningproviders.md
  api-reference/beta/api/employeeexperience-post-learningproviders.md
  api-reference/beta/api/learningcontent-get.md
  api-reference/beta/api/learningcontent-update.md
  api-reference/beta/api/learningprovider-delete-learningcontents.md
  api-reference/beta/api/learningprovider-get.md
  api-reference/beta/api/learningprovider-list-learningcontents.md
  api-reference/beta/api/learningprovider-update.md
  api-reference/beta/resources/viva-learning-api-overview.md
  api-reference/v1.0/api/employeeexperience-delete-learningproviders.md
  api-reference/v1.0/api/learningcontent-get.md
  api-reference/v1.0/api/learningprovider-delete-learningcontents.md
  api-reference/v1.0/resources/employeeexperience.md
  api-reference/v1.0/resources/viva-learning-api-overview.md
  concepts/permissions-reference.md
Labels: external

#20428 Fix incorrect datetime
  changelog/Microsoft.DirectoryServices.json
Labels: ready to merge, internal

#20431 Update customize-client.md
  concepts/sdks/customize-client.md
Labels: ready to merge, internal

#20432 Format examples for snippets generation
  concepts/how-to-pim-update-rules.md
Labels: area: Azure AD, ready to merge, internal, area: governance

#15074 adding docs for createLink and Invite API changes
  api-reference/beta/api/driveitem-createlink.md
  api-reference/beta/api/driveitem-invite.md
  api-reference/beta/api/listitem-createlink.md
  api-reference/v1.0/api/driveitem-createlink.md
  api-reference/v1.0/api/driveitem-invite.md
  changelog/Microsoft.FileServices.json
Labels: ready to merge, internal, content review complete, schema live

#20433 [Bulk] Broken Link fixes
  concepts/data-connect-policies.md
  concepts/insights-customize-item-insights-privacy.md
  concepts/known-issues.md
  concepts/notifications-integrating-with-android.md
  concepts/onenote-create-page.md
  concepts/onenote-get-content.md
  concepts/open-onenote-client.md
  concepts/teams-concept-overview.md
  concepts/todo-concept-overview.md
  concepts/toolkit/components/tasks.md
  concepts/toolkit/providers/teams-msal2.md
  concepts/whats-new-earlier.md
  includes/outlook-mailbox-type-support.md
  includes/throttling-intune-android-for-work.md
  includes/throttling-intune-applications.md
  includes/throttling-intune-bundles.md
  includes/throttling-intune-device-configuration.md
  includes/throttling-intune-device-intent.md
  includes/throttling-intune-devices.md
  includes/throttling-intune-managed-applications.md
  includes/throttling-intune-odj.md
  includes/throttling-intune-troubleshooting.md
Labels: external, ready to merge

#15761 UserPurpose API Changes
  api-reference/beta/api/user-get-mailboxsettings.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/mailboxsettings.md
  api-reference/beta/resources/userpurpose.md
  api-reference/beta/resources/workinghours.md
  api-reference/v1.0/api/user-get-mailboxsettings.md
  api-reference/v1.0/resources/enums.md
  api-reference/v1.0/resources/mailboxsettings.md
  api-reference/v1.0/resources/workinghours.md
  changelog/Microsoft.Exchange.json
  redirects/.openpublishing.redirection.0822.json
Labels: ready to merge, changes requested, internal, content review in progress

#16565 Add documents for device delta
  api-reference/beta/api/device-delta.md
  api-reference/beta/resources/device.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/device-delta.md
  api-reference/v1.0/resources/device.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.DirectoryServices.json
  concepts/delta-query-overview.md
Labels: area: Azure AD, external, resolved: awaiting prod deployment, ready to merge, content review complete, review feedback addressed

#19944 Skadam add approver to subject right request
  api-reference/beta/api/subjectrightsrequest-post.md
  api-reference/beta/resources/subjectrightsrequest.md
  api-reference/beta/resources/subjectrightsrequeststagedetail.md
  changelog/Microsoft.Compliance.DataSubjectRequest.json
Labels: ready to merge, internal, content review complete, review feedback addressed

#19902 Add Group Report Change
  api-reference/beta/api/reportroot-getoffice365groupsactivitycounts.md
  api-reference/beta/api/reportroot-getoffice365groupsactivitydetail.md
  api-reference/beta/resources/office365groupsactivitycounts.md
  api-reference/beta/resources/office365groupsactivitydetail.md
  changelog/Microsoft.O365Reporting.json
Labels: ready to merge, internal, content review complete

#17974 Updates to the doc
  api-reference/beta/resources/team.md
  changelog/Microsoft.Teams.GraphSvc.json
Labels: ready to merge, internal, content review complete

#20443 Merge to publish.
  api-reference/beta/api/device-delta.md
  api-reference/beta/api/driveitem-createlink.md
  api-reference/beta/api/driveitem-invite.md
  api-reference/beta/api/listitem-createlink.md
  api-reference/beta/api/reportroot-getoffice365groupsactivitycounts.md
  api-reference/beta/api/reportroot-getoffice365groupsactivitydetail.md
  api-reference/beta/api/subjectrightsrequest-post.md
  api-reference/beta/api/user-get-mailboxsettings.md
  api-reference/beta/resources/device.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/mailboxsettings.md
  api-reference/beta/resources/office365groupsactivitycounts.md
  api-reference/beta/resources/office365groupsactivitydetail.md
  api-reference/beta/resources/subjectrightsrequest.md
  api-reference/beta/resources/subjectrightsrequeststagedetail.md
  api-reference/beta/resources/team.md
  api-reference/beta/resources/userpurpose.md
  api-reference/beta/resources/workinghours.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/device-delta.md
  api-reference/v1.0/api/driveitem-createlink.md
  api-reference/v1.0/api/driveitem-invite.md
  api-reference/v1.0/api/user-get-mailboxsettings.md
  api-reference/v1.0/resources/device.md
  api-reference/v1.0/resources/enums.md
  api-reference/v1.0/resources/mailboxsettings.md
  api-reference/v1.0/resources/workinghours.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.Compliance.DataSubjectRequest.json
  changelog/Microsoft.DirectoryServices.json
  changelog/Microsoft.Exchange.json
  changelog/Microsoft.FileServices.json
  changelog/Microsoft.O365Reporting.json
  changelog/Microsoft.Teams.GraphSvc.json
  concepts/data-connect-policies.md
  concepts/delta-query-overview.md
  concepts/how-to-pim-update-rules.md
  concepts/insights-customize-item-insights-privacy.md
  concepts/known-issues.md
  concepts/notifications-integrating-with-android.md
  concepts/onenote-create-page.md
  concepts/onenote-get-content.md
  concepts/open-onenote-client.md
  concepts/sdks/customize-client.md
  concepts/teams-concept-overview.md
  concepts/todo-concept-overview.md
  concepts/toolkit/components/tasks.md
  concepts/toolkit/providers/teams-msal2.md
  concepts/whats-new-earlier.md
  includes/outlook-mailbox-type-support.md
  includes/throttling-intune-android-for-work.md
  includes/throttling-intune-applications.md
  includes/throttling-intune-bundles.md
  includes/throttling-intune-device-configuration.md
  includes/throttling-intune-device-intent.md
  includes/throttling-intune-devices.md
  includes/throttling-intune-managed-applications.md
  includes/throttling-intune-odj.md
  includes/throttling-intune-troubleshooting.md
  redirects/.openpublishing.redirection.0822.json
Labels: do not merge, internal

#20446 Update what's new through 2/15.
  api-reference/beta/toc.yml
  api-reference/v1.0/resources/accesspackageassignmentpolicy.md
  changelog/Microsoft.IGAELM.json
  concepts/whats-new-overview.md
  concepts/windowsupdates-manage-driver-update.md
Labels: do not merge, internal

#20447 Publish what's new through 2/15.
  api-reference/beta/toc.yml
  api-reference/v1.0/resources/accesspackageassignmentpolicy.md
  changelog/Microsoft.IGAELM.json
  concepts/whats-new-overview.md
  concepts/windowsupdates-manage-driver-update.md
Labels: internal

#20451 Merging metered API includes into working branch
  api-reference/beta/api/chatmessage-update.md
  api-reference/includes/teams-model-A-and-B-disclaimer.md
  api-reference/includes/teams-model-A-and-B-errors.md
  api-reference/includes/teams-model-A-only-disclaimer.md
  api-reference/includes/teams-model-A-only-errors.md
  api-reference/v1.0/api/chats-getallmessages.md
  concepts/errors.md
Labels: do not merge, internal

#20066 Change to create new list of broken links
  changelog/Microsoft.AAD.Reporting.json
  changelog/Microsoft.Intune.json
  concepts/toc.yml
Labels: ready to merge, internal

#20436 Update permissions-reference.md
  concepts/includes/permissions-ids.md
  concepts/permissions-reference.md
Labels: area: Azure AD, ready to merge, internal

#20452 Fix redirect and unblock PR #20448 changelog validation
  redirects/.openpublishing.redirection.0822.json
Labels: ready to merge

#19976 Allow Participant to Rename Themselves
  api-reference/beta/resources/onlinemeeting.md
  changelog/Microsoft.Skype.Calling.json
Labels: do not merge, ready to merge, internal, content review complete

#20460 Include more items in what's new topics thro 3/5.
  api-reference/beta/api/driveitem-createlink.md
  api-reference/beta/api/listitem-createlink.md
  api-reference/beta/resources/conversationmember.md
  api-reference/beta/resources/pronounssettings.md
  api-reference/v1.0/resources/conversationmember.md
  changelog/Microsoft.FileServices.json
  changelog/Microsoft.People.json
  concepts/pronouns-configure-pronouns-availability.md
  concepts/search-concept-searchall.md
  concepts/toc.yml
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: do not merge, internal

#20465 Refresh what's new topic through March 5.
  api-reference/beta/api/driveitem-createlink.md
  api-reference/beta/api/listitem-createlink.md
  api-reference/beta/resources/conversationmember.md
  api-reference/beta/resources/pronounssettings.md
  api-reference/v1.0/resources/conversationmember.md
  changelog/Microsoft.FileServices.json
  changelog/Microsoft.People.json
  concepts/pronouns-configure-pronouns-availability.md
  concepts/search-concept-searchall.md
  concepts/toc.yml
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: do not merge, internal

#20466 Edits in PR 20061
  api-reference/beta/api/security-ediscoveryexportoperation-getdownloadurl.md
  api-reference/beta/api/security-ediscoveryreviewset-export.md
  api-reference/beta/api/security-ediscoveryreviewsetquery-export.md
  api-reference/beta/resources/security-ediscoveryexportfilemetadata.md
  api-reference/beta/resources/security-ediscoveryexportoperation.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Security.Ediscovery.json
Labels: external

#20469 Update dynamics-agedaccountspayable.md
  api-reference/beta/resources/dynamics-agedaccountspayable.md
Labels: external

#20463 Fixed TOC entry for rbac conceptual topic
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
Labels: external

#20462 Added missing currencies TOC entry for PATCH operation
  api-reference/beta/toc.yml
Labels: external

#19353 Cleanup sync APIs
  api-reference/beta/api/synchronization-serviceprincipal-put-synchronization.md
  api-reference/beta/api/synchronization-synchronizationjob-provisionondemand.md
  api-reference/beta/resources/application.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/serviceprincipal.md
  api-reference/beta/resources/synchronization-attributemapping.md
  api-reference/beta/resources/synchronization-attributemappingparameterschema.md
  api-reference/beta/resources/synchronization-attributemappingsource.md
  api-reference/beta/resources/synchronization-directorydefinition.md
  api-reference/beta/resources/synchronization-filteroperatorschema.md
  api-reference/beta/resources/synchronization-objectdefinition.md
  api-reference/beta/resources/synchronization-objectmapping.md
  api-reference/beta/resources/synchronization-overview.md
  api-reference/beta/resources/synchronization-synchronization.md
  api-reference/beta/resources/synchronization-synchronizationerror.md
  api-reference/beta/resources/synchronization-synchronizationjob.md
  api-reference/beta/resources/synchronization-synchronizationprogress.md
  api-reference/beta/resources/synchronization-synchronizationquarantine.md
  api-reference/beta/resources/synchronization-synchronizationschedule.md
  api-reference/beta/resources/synchronization-synchronizationstatus.md
  api-reference/beta/resources/synchronization-synchronizationtaskexecution.md
  api-reference/beta/resources/synchronization-synchronizationtemplate.md
  api-reference/beta/toc.yml
  concepts/synchronization-configure-with-custom-target-attributes.md
  concepts/synchronization-configure-with-directory-extension-attributes.md
  redirects/.openpublishing.redirection.changedapi.json
Labels: area: Azure AD, bug: documentation, ready to merge, ready for content review, internal, area: applications

#20327 Update Speller And Answer
  api-reference/beta/resources/search-api-overview.md
  concepts/search-concept-acronym.md
  concepts/search-concept-bookmark.md
  concepts/search-concept-qna.md
  concepts/search-concept-speller.md
Labels: ready to merge, internal, content review complete

#20420 Updated LCW titles
  api-reference/beta/api/identitygovernance-lifecyclemanagementsettings-get.md
  api-reference/beta/api/identitygovernance-lifecyclemanagementsettings-update.md
  api-reference/beta/api/identitygovernance-lifecycleworkflowscontainer-list-workflows.md
  api-reference/beta/api/identitygovernance-lifecycleworkflowscontainer-post-workflows.md
  api-reference/beta/api/identitygovernance-run-get.md
  api-reference/beta/api/identitygovernance-run-list-taskprocessingresults.md
  api-reference/beta/api/identitygovernance-run-list-userprocessingresults.md
  api-reference/beta/api/identitygovernance-run-summary.md
  api-reference/beta/api/identitygovernance-task-get.md
  api-reference/beta/api/identitygovernance-task-update.md
  api-reference/beta/api/identitygovernance-taskreport-list-taskprocessingresults.md
  api-reference/beta/api/identitygovernance-taskreport-summary.md
  api-reference/beta/api/identitygovernance-userprocessingresult-get.md
  api-reference/beta/api/identitygovernance-userprocessingresult-list-taskprocessingresults.md
  api-reference/beta/api/identitygovernance-workflow-activate.md
  api-reference/beta/api/identitygovernance-workflow-delete.md
  api-reference/beta/api/identitygovernance-workflow-get.md
  api-reference/beta/api/identitygovernance-workflow-list-runs.md
  api-reference/beta/api/identitygovernance-workflow-list-task.md
  api-reference/beta/api/identitygovernance-workflow-list-taskreports.md
  api-reference/beta/api/identitygovernance-workflow-list-userprocessingresults.md
  api-reference/beta/api/identitygovernance-workflow-list-versions.md
  api-reference/beta/api/identitygovernance-workflow-restore.md
  api-reference/beta/api/identitygovernance-workflow-update.md
  api-reference/beta/api/workflow-list-executionscope.md
Labels: area: Azure AD, ready to merge, internal, content review complete

#20480 Changes User.ReadBasic.All
  api-reference/beta/api/educationalactivity-get.md
  api-reference/beta/api/itemaddress-get.md
  api-reference/beta/api/itememail-get.md
  api-reference/beta/api/itempatent-get.md
  api-reference/beta/api/itemphone-get.md
  api-reference/beta/api/itempublication-get.md
  api-reference/beta/api/languageproficiency-get.md
  api-reference/beta/api/personanniversary-get.md
  api-reference/beta/api/personannotation-delete.md
  api-reference/beta/api/personannotation-get.md
  api-reference/beta/api/personannotation-update.md
  api-reference/beta/api/personaward-get.md
  api-reference/beta/api/personcertification-get.md
  api-reference/beta/api/personinterest-get.md
  api-reference/beta/api/personname-get.md
  api-reference/beta/api/personresponsibility-delete.md
  api-reference/beta/api/personresponsibility-get.md
  api-reference/beta/api/personresponsibility-update.md
  api-reference/beta/api/personwebsite-get.md
  api-reference/beta/api/profile-get.md
  api-reference/beta/api/profile-list-accounts.md
  api-reference/beta/api/profile-list-addresses.md
  api-reference/beta/api/profile-list-anniversaries.md
  api-reference/beta/api/profile-list-awards.md
  api-reference/beta/api/profile-list-certifications.md
  api-reference/beta/api/profile-list-educationalactivities.md
  api-reference/beta/api/profile-list-emails.md
  api-reference/beta/api/profile-list-interests.md
  api-reference/beta/api/profile-list-languages.md
  api-reference/beta/api/profile-list-names.md
  api-reference/beta/api/profile-list-notes.md
  api-reference/beta/api/profile-list-patents.md
  api-reference/beta/api/profile-list-phones.md
  api-reference/beta/api/profile-list-positions.md
  api-reference/beta/api/profile-list-projects.md
  api-reference/beta/api/profile-list-publications.md
  api-reference/beta/api/profile-list-responsibilities.md
  api-reference/beta/api/profile-list-skills.md
  api-reference/beta/api/profile-list-webaccounts.md
  api-reference/beta/api/profile-list-websites.md
  api-reference/beta/api/profile-post-names.md
  api-reference/beta/api/projectparticipation-get.md
  api-reference/beta/api/skillproficiency-get.md
  api-reference/beta/api/useraccountinformation-get.md
  api-reference/beta/api/webaccount-get.md
  api-reference/beta/api/workposition-get.md
Labels: ready to merge, internal

#20052 AST GRaph doc fix
  api-reference/beta/api/attacksimulationoperation-get.md
  api-reference/beta/api/attacksimulationroot-list-payloads.md
  api-reference/beta/api/attacksimulationroot-post-simulation.md
  api-reference/beta/api/payload-get.md
  api-reference/beta/api/payloaddetail-get.md
  api-reference/beta/api/simulation-delete.md
  api-reference/beta/api/simulation-get.md
  api-reference/beta/api/simulation-update.md
  api-reference/beta/api/simulationautomation-get.md
  api-reference/beta/resources/attacksimulationoperation.md
  api-reference/beta/resources/attacksimulationroot.md
  api-reference/beta/resources/payload.md
  api-reference/beta/resources/payloadcoachmark.md
  api-reference/beta/resources/simulation.md
  api-reference/beta/resources/simulationautomation.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/simulation-get.md
  api-reference/v1.0/api/simulationautomation-get.md
  api-reference/v1.0/resources/simulation.md
  api-reference/v1.0/resources/simulationautomation.md
  api-reference/v1.0/toc.yml
  concepts/whats-new-overview.md
  redirects/.openpublishing.redirection.0223.json
Labels: ready to merge, content review complete

#20459 Update dynamics-currencies.md
  api-reference/beta/resources/dynamics-currencies.md
Labels: external

#20450 Update dynamics-shipmentmethods.md
  api-reference/beta/resources/dynamics-shipmentmethods.md
Labels: external

#20454 Jeremyke metered api day one updates
  api-reference/beta/api/chatmessage-update.md
  api-reference/beta/toc.yml
  api-reference/includes/teams-model-A-and-B-disclaimer.md
  api-reference/includes/teams-model-A-and-B-errors.md
  api-reference/includes/teams-model-A-only-disclaimer.md
  api-reference/includes/teams-model-A-only-errors.md
  api-reference/v1.0/api/chats-getallmessages.md
  api-reference/v1.0/toc.yml
  concepts/errors.md
  concepts/includes/metered-api-known-limitations.md
  concepts/metered-api-list.md
  concepts/metered-api-overview.md
  concepts/metered-api-setup.md
  concepts/teams-licenses.md
  concepts/toc.yml
Labels: do not merge, internal, content review complete

#20489 Update whats-new-overview.md
  concepts/whats-new-overview.md
Labels: external

#20493 Updated table for Graph Explorer.
  concepts/deployments.md
Labels: ready to merge, internal

#20494 Merge to publish.
  concepts/deployments.md
  concepts/whats-new-overview.md
Labels: internal

#20495 Edits in PR 20061
  api-reference/beta/api/security-ediscoveryexportoperation-getdownloadurl.md
  api-reference/beta/api/security-ediscoveryreviewset-export.md
  api-reference/beta/resources/security-ediscoveryexportfilemetadata.md
  api-reference/beta/resources/security-ediscoveryexportoperation.md
Labels: external

#20497 Edits in PR 20260
  api-reference/beta/api/authenticationmethodspolicy-update.md
  api-reference/beta/resources/authenticationmethodspolicy.md
  api-reference/beta/resources/systemcredentialpreferences.md
  changelog/Microsoft.DirectoryServices.json
Labels: external

#20506 Update openshift-list.md
  api-reference/v1.0/api/openshift-list.md
Labels: external

#20505 Update openshift-list.md
  api-reference/beta/api/openshift-list.md
Labels: external

#20423 [BrokenLinksH2] | Fixed broken links 3 | Bulk Update
  concepts/changelog-archive.md
Labels: external, ready to merge

#20277 Add Warning about Attendance Report Entries
  api-reference/beta/api/meetingattendancereport-list.md
  api-reference/v1.0/api/meetingattendancereport-list.md
Labels: ready to merge, content review complete

#20479 Adding role requirements to sync API docs
  api-reference/beta/api/directorydefinition-discover.md
  api-reference/beta/api/synchronization-serviceprincipal-put-synchronization.md
  api-reference/beta/api/synchronization-synchronization-acquireaccesstoken.md
  api-reference/beta/api/synchronization-synchronizationjob-delete.md
  api-reference/beta/api/synchronization-synchronizationjob-get.md
  api-reference/beta/api/synchronization-synchronizationjob-list.md
  api-reference/beta/api/synchronization-synchronizationjob-pause.md
  api-reference/beta/api/synchronization-synchronizationjob-post.md
  api-reference/beta/api/synchronization-synchronizationjob-provisionondemand.md
  api-reference/beta/api/synchronization-synchronizationjob-restart.md
  api-reference/beta/api/synchronization-synchronizationjob-start.md
  api-reference/beta/api/synchronization-synchronizationjob-validatecredentials.md
  api-reference/beta/api/synchronization-synchronizationschema-delete.md
  api-reference/beta/api/synchronization-synchronizationschema-filteroperators.md
  api-reference/beta/api/synchronization-synchronizationschema-functions.md
  api-reference/beta/api/synchronization-synchronizationschema-get.md
  api-reference/beta/api/synchronization-synchronizationschema-parseexpression.md
  api-reference/beta/api/synchronization-synchronizationschema-update.md
  api-reference/beta/api/synchronization-synchronizationtemplate-get.md
  api-reference/beta/api/synchronization-synchronizationtemplate-list.md
  api-reference/beta/api/synchronization-synchronizationtemplate-update.md
  api-reference/beta/includes/rbac-for-apis/rbac-synchronization-apis.md
Labels: area: Azure AD, ready to merge, internal, content review complete

#20514 Edits in PR 18043
  api-reference/beta/api/industrydata-azuredatalakeconnector-get.md
  api-reference/beta/api/industrydata-azuredatalakeconnector-getuploadsession.md
  api-reference/beta/api/industrydata-azuredatalakeconnector-list.md
  api-reference/beta/api/industrydata-azuredatalakeconnector-post.md
  api-reference/beta/api/industrydata-filevalidateoperation-get.md
  api-reference/beta/api/industrydata-filevalidateoperation-list.md
  api-reference/beta/api/industrydata-inboundfileflow-get.md
  api-reference/beta/api/industrydata-inboundfileflow-list.md
  api-reference/beta/api/industrydata-inboundfileflow-post.md
  api-reference/beta/api/industrydata-inboundflow-get.md
  api-reference/beta/api/industrydata-inboundflow-list.md
  api-reference/beta/api/industrydata-inboundflow-post.md
  api-reference/beta/api/industrydata-industrydataconnector-get.md
  api-reference/beta/api/industrydata-industrydataconnector-list.md
  api-reference/beta/api/industrydata-industrydataconnector-post.md
  api-reference/beta/api/industrydata-industrydatarun-get.md
  api-reference/beta/api/industrydata-industrydatarun-getstatistics.md
  api-reference/beta/api/industrydata-industrydatarun-list.md
  api-reference/beta/api/industrydata-referencedefinition-get.md
  api-reference/beta/api/industrydata-referencedefinition-list.md
  api-reference/beta/api/industrydata-rolegroup-get.md
  api-reference/beta/api/industrydata-rolegroup-list.md
  api-reference/beta/api/industrydata-sourcesystemdefinition-get.md
  api-reference/beta/api/industrydata-sourcesystemdefinition-list.md
  api-reference/beta/api/industrydata-sourcesystemdefinition-post.md
  api-reference/beta/api/industrydata-yeartimeperioddefinition-get.md
  api-reference/beta/api/industrydata-yeartimeperioddefinition-list.md
  api-reference/beta/api/industrydata-yeartimeperioddefinition-post.md
Labels: external

#20526 Update metered-api-setup.md
  concepts/metered-api-setup.md
Labels: do not merge, internal

#20529 Merge to publish.
  concepts/metered-api-setup.md
Labels: internal

#20536 XTAP fix typo in inboundOutboundPolicyConfiguration
  api-reference/beta/resources/inboundoutboundpolicyconfiguration.md
Labels: ready to merge

#20283 Doc updates for authStrengthResults
  api-reference/beta/resources/authenticationstrength.md
  api-reference/beta/resources/conditionalaccessrulesatisfied.md
  api-reference/beta/resources/enums.md
  changelog/Microsoft.AAD.Reporting.json
Labels: area: Azure AD, ready to merge, internal, content review complete, schema live

#20533 Update bookingbusiness-post-customers.md
  api-reference/beta/api/bookingbusiness-post-customers.md
  api-reference/v1.0/api/bookingbusiness-post-customers.md
Labels: external, ready to merge

#20534 Update bookingcustomer-get.md
  api-reference/beta/api/bookingcustomer-get.md
  api-reference/v1.0/api/bookingcustomer-get.md
Labels: external, ready to merge

#20544 Fix smaLL typo
  api-reference/beta/api/directoryobject-getbyids.md
Labels: external

#20543 Update directoryobject-getbyids.md
  api-reference/v1.0/api/directoryobject-getbyids.md
Labels: external

#20537 Updated SubmissionResultDetail Values
  api-reference/beta/resources/security-submissionresult.md
Labels: external, ready to merge, content review complete

#20547 Fix link for PR 20190, line 8845
  api-reference/beta/toc.yml
Labels: ready to merge, internal

#20551 Reorganized headings.
  concepts/known-issues.md
Labels: ready to merge, internal

#20552 Merge to publish.
  api-reference/beta/api/directoryobject-getbyids.md
  api-reference/beta/resources/security-submissionresult.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/directoryobject-getbyids.md
  concepts/known-issues.md
Labels: internal

#20561 Edits in PR 20434
  api-reference/beta/api/application-post-calls.md
  api-reference/beta/resources/deltaparticipants.md
  api-reference/beta/resources/removedstate.md
  changelog/Microsoft.Skype.Calling.json
Labels: external

#20562 Edits in PR 20261
  concepts/delta-query-overview.md
Labels: external

#20577 Update outlookuser-list-mastercategories.md
  api-reference/beta/api/outlookuser-list-mastercategories.md
Labels: external

#20576 Update outlookuser-list-mastercategories.md
  api-reference/v1.0/api/outlookuser-list-mastercategories.md
Labels: external

#20556 Update virtualendpoint-geteffectivepermissions.md
  api-reference/beta/api/virtualendpoint-geteffectivepermissions.md
Labels: external

#19994 Users/jessezhu/deltaquerydirectoryobjects
  api-reference/beta/api/directoryobject-delta.md
  api-reference/beta/resources/directoryobject.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/directoryobject-delta.md
  api-reference/v1.0/resources/directoryobject.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.DirectoryServices.json
  concepts/delta-query-overview.md
Labels: area: Azure AD, ready to merge, internal, content review complete, area: change tracking

#20346 Adds aad user manager remove page
  api-reference/beta/api/user-delete-manager.md
  api-reference/beta/resources/user.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/user-delete-manager.md
  api-reference/v1.0/resources/user.md
  api-reference/v1.0/toc.yml
Labels: area: Azure AD, area: users, ready to merge, internal, content review complete

#20363 [2302] PE - V1.0 (Prod, FF, MC) Intune Graph Doc Publishing
  api-reference/v1.0/api/intune-apps-enterprisecodesigningcertificate-create.md
  api-reference/v1.0/api/intune-apps-enterprisecodesigningcertificate-delete.md
  api-reference/v1.0/api/intune-apps-enterprisecodesigningcertificate-get.md
  api-reference/v1.0/api/intune-apps-enterprisecodesigningcertificate-list.md
  api-reference/v1.0/api/intune-apps-enterprisecodesigningcertificate-update.md
  api-reference/v1.0/api/intune-apps-ioslobappprovisioningconfigurationassignment-create.md
  api-reference/v1.0/api/intune-apps-ioslobappprovisioningconfigurationassignment-delete.md
  api-reference/v1.0/api/intune-apps-ioslobappprovisioningconfigurationassignment-get.md
  api-reference/v1.0/api/intune-apps-ioslobappprovisioningconfigurationassignment-list.md
  api-reference/v1.0/api/intune-apps-ioslobappprovisioningconfigurationassignment-update.md
  api-reference/v1.0/api/intune-devices-manageddevice-get.md
  api-reference/v1.0/api/intune-onboarding-mobilethreatdefenseconnector-create.md
  api-reference/v1.0/api/intune-onboarding-mobilethreatdefenseconnector-update.md
  api-reference/v1.0/resources/intune-apps-certificatestatus.md
  api-reference/v1.0/resources/intune-apps-enterprisecodesigningcertificate.md
  api-reference/v1.0/resources/intune-apps-ioslobappprovisioningconfigurationassignment.md
  api-reference/v1.0/resources/intune-onboarding-mobilethreatdefenseconnector.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.Intune.json
Labels: area: intune, ready to merge, internal, content review complete, invalid links

#20563 Add H2 title
  concepts/tutorial-applications-basics.md
Labels: area: Azure AD, ready to merge, internal

#20565 Update customize-client.md
  concepts/sdks/customize-client.md
Labels: ready to merge, internal

#20566 Add PIM auth context rule that's in public preview
  concepts/identity-governance-pim-rules-overview.md
  concepts/images/identity-governance-pim-ux-role-rules-screenshots/pim-ux-role-rule.activation.png
  concepts/toc.yml
Labels: area: Azure AD, ready to merge, internal, area: governance

#20571 Add missing HTTP tab in conceptual page
  concepts/tutorial-applications-basics.md
Labels: ready to merge, internal

#20419 clarified site/permission api docs
  api-reference/beta/api/site-post-permissions.md
  api-reference/beta/api/site-update-permission.md
  api-reference/v1.0/api/site-post-permissions.md
  api-reference/v1.0/api/site-update-permission.md
Labels: ready to merge

#20580 Edits in PR 19584
  api-reference/beta/api/plannertask-update.md
  api-reference/beta/resources/plannerrecurrenceschedule.md
  api-reference/beta/resources/plannertaskrecurrence.md
  concepts/planner-task-recurrence-concept.md
  concepts/toc.yml
Labels: external

#20581 Edits in PR 20260
  api-reference/beta/api/authenticationmethodspolicy-update.md
  api-reference/beta/resources/authenticationmethodspolicy.md
  api-reference/beta/resources/systemcredentialpreferences.md
Labels: external

#20582 Update groups-overview.md
  api-reference/v1.0/resources/groups-overview.md
Labels: external

#20251 [Graph API][CloudPC][Minor Change]Remove Gov token for get cloudPcCrossCloudGovernmentOrganizationMapping API
  api-reference/beta/api/cloudpccrosscloudgovernmentorganizationmapping-get.md
Labels: ready to merge, internal, content review complete

#20587 Update authenticationmethod-resetpassword.md
  api-reference/v1.0/api/authenticationmethod-resetpassword.md
Labels: ready to merge, internal

#20589 vfrankson-03.14.2023
  api-reference/beta/resources/industrydata-industrydatarun.md
  api-reference/beta/resources/industrydata-overview.md
  concepts/industrydata-concept-overview.md
Labels: ready to merge, internal

#19449 Remove docs for the deprecated activateService and activateServicePlan APIs
  api-reference/beta/api/organization-activateservice.md
  api-reference/beta/api/user-activateserviceplan.md
  api-reference/beta/resources/activateservice.md
  api-reference/beta/resources/organization.md
  api-reference/beta/resources/user.md
  api-reference/beta/toc.yml
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, resolved: awaiting prod deployment, ready to merge, internal

#20168 Update custom-connector-sdk-overview.md
  concepts/custom-connector-sdk-best-practices.md
  concepts/custom-connector-sdk-contracts-common.md
  concepts/custom-connector-sdk-contracts-connectionmanagement.md
  concepts/custom-connector-sdk-contracts-connectorcrawler.md
  concepts/custom-connector-sdk-contracts-connectorinfo.md
  concepts/custom-connector-sdk-contracts-connectoroauth.md
  concepts/custom-connector-sdk-contracts-services.md
  concepts/custom-connector-sdk-overview.md
  concepts/custom-connector-sdk-publish.md
  concepts/custom-connector-sdk-sample-create.md
  concepts/custom-connector-sdk-sample-overview.md
  concepts/custom-connector-sdk-sample-publish.md
  concepts/custom-connector-sdk-sample-search.md
  concepts/custom-connector-sdk-sample-test.md
  concepts/custom-connector-sdk-testapp.md
  concepts/custom-connector-sdk-troubleshooting.md
  concepts/images/connectors-sdk/projectstructure.png
  concepts/images/connectors-sdk/test1complete.png
  concepts/images/connectors-sdk/test2complete.png
  concepts/images/connectors-sdk/test3complete.png
  concepts/images/connectors-sdk/test4complete.png
  concepts/images/connectors-sdk/test5complete.png
Labels: ready to merge, internal, content review complete, area: connectors

#20269 Execution scope clarification
  api-reference/beta/api/workflow-list-executionscope.md
Labels: area: Azure AD, ready to merge, changes requested, internal, content review complete, review feedback addressed

#20600 Fix broken links
  includes/throttling-excel.md
  includes/throttling-skype-calling.md
Labels: area: Azure AD, ready to merge, internal

#18857 Correction on update the profile photo of a group permission
  api-reference/v1.0/api/profilephoto-update.md
Labels: internal, customer support issue, content review complete

#19156 Update service plan description
  api-reference/beta/resources/cloudpcserviceplan.md
Labels: internal, content review complete

#20530 Making updates per-discussion on M365 vs Microsoft Graph
  concepts/includes/metered-api-known-limitations.md
  concepts/metered-api-list.md
  concepts/metered-api-overview.md
  concepts/metered-api-setup.md
  concepts/overview.md
  concepts/teams-licenses.md
  concepts/toc.yml
Labels: do not merge, internal, content review complete

#20545 Remove flag that is no longer required on CLI
  concepts/metered-api-setup.md
Labels: internal, content review complete

#20604 update security-api-overview.md
  api-reference/beta/resources/security-api-overview.md
  api-reference/v1.0/resources/security-api-overview.md
Labels: do not merge, internal, content review complete

#20606 Edits in PR 20260
  api-reference/beta/api/authentication-get.md
  api-reference/beta/api/authenticationmethodspolicy-update.md
  api-reference/beta/resources/authentication.md
  api-reference/beta/resources/authenticationmethodspolicy-update.md
  api-reference/beta/resources/signinpreferences.md
  api-reference/beta/resources/systemcredentialpreferences.md
  changelog/Microsoft.DirectoryServices.json
Labels: external

#20610 Edits in PR 19584
  api-reference/beta/resources/plannerrecurrenceschedule.md
  api-reference/beta/resources/plannertaskrecurrence.md
  concepts/planner-task-recurrence-concept.md
Labels: external

#20613 Update plannerbucket-get.md
  api-reference/v1.0/api/plannerbucket-get.md
Labels: external

#20612 Update plannerbucket-get.md
  api-reference/beta/api/plannerbucket-get.md
Labels: external

#19097 remove .(dot) from invalid mailnickname characters
  api-reference/beta/api/group-post-groups.md
  api-reference/v1.0/api/group-post-groups.md
Labels: area: Azure AD, ready to merge, internal, content review complete

#19575 Update calendar-list-events.md
  api-reference/beta/api/calendar-list-events.md
  api-reference/v1.0/api/calendar-list-events.md
Labels: ready to merge, internal, content review complete

#19900 Add Teams Team Report
  api-reference/beta/api/reportroot-getteamsteamcounts.md
  api-reference/beta/resources/microsoft-teams-team-usage-reports.md
  api-reference/beta/resources/report.md
  api-reference/beta/toc.yml
  changelog/Microsoft.O365Reporting.json
Labels: ready to merge, internal, content review complete

#20616 Adds enhanced validation of changelog files.
  .github/workflows/changelog-validation.yml
  changelog/Changelog.Schema.json
  changelog/validate-json.ps1
Labels: ready to merge, internal

#20620 Adding 2 new routines for the bot
  .github/fabricbot.json
Labels: ready to merge, internal

#20621 Update driveitem-createlink.md
  api-reference/v1.0/api/driveitem-createlink.md
Labels: external, ready to merge

#20061 Changes to eDiscovery export beta endpoint
  api-reference/beta/api/security-ediscoveryexportoperation-getdownloadurl.md
  api-reference/beta/api/security-ediscoveryreviewset-export.md
  api-reference/beta/api/security-ediscoveryreviewsetquery-export.md
  api-reference/beta/resources/security-ediscoveryexportfilemetadata.md
  api-reference/beta/resources/security-ediscoveryexportoperation.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Security.Ediscovery.json
Labels: ready to merge, internal, content review complete, schema live

#20476 Add role based control explanations in service communications api overview page (beta and v1.0)
  api-reference/beta/resources/service-communications-api-overview.md
  api-reference/v1.0/resources/service-communications-api-overview.md
Labels: ready to merge, content review complete

#20349 USQ docs to Beta
  api-reference/beta/api/servicestoragequotabreakdown-get.md
  api-reference/beta/api/unifiedstoragequota-get.md
  api-reference/beta/api/unifiedstoragequota-list-services.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/quota.md
  api-reference/beta/resources/servicestoragequotabreakdown.md
  api-reference/beta/resources/unifiedstoragequota.md
  api-reference/beta/toc.yml
  api-reference/v1.0/resources/quota.md
  changelog/Microsoft.UnifiedStorageQuota.json
Labels: ready to merge, internal, content review complete

#20626 Merge to publish.
  .github/fabricbot.json
  .github/workflows/changelog-validation.yml
  api-reference/beta/api/calendar-list-events.md
  api-reference/beta/api/group-post-groups.md
  api-reference/beta/api/plannerbucket-get.md
  api-reference/beta/api/reportroot-getteamsteamcounts.md
  api-reference/beta/api/security-ediscoveryexportoperation-getdownloadurl.md
  api-reference/beta/api/security-ediscoveryreviewset-export.md
  api-reference/beta/api/security-ediscoveryreviewsetquery-export.md
  api-reference/beta/api/servicestoragequotabreakdown-get.md
  api-reference/beta/api/unifiedstoragequota-get.md
  api-reference/beta/api/unifiedstoragequota-list-services.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/microsoft-teams-team-usage-reports.md
  api-reference/beta/resources/quota.md
  api-reference/beta/resources/report.md
  api-reference/beta/resources/security-ediscoveryexportfilemetadata.md
  api-reference/beta/resources/security-ediscoveryexportoperation.md
  api-reference/beta/resources/service-communications-api-overview.md
  api-reference/beta/resources/servicestoragequotabreakdown.md
  api-reference/beta/resources/unifiedstoragequota.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/calendar-list-events.md
  api-reference/v1.0/api/driveitem-createlink.md
  api-reference/v1.0/api/group-post-groups.md
  api-reference/v1.0/api/plannerbucket-get.md
  api-reference/v1.0/resources/quota.md
  api-reference/v1.0/resources/service-communications-api-overview.md
  changelog/Changelog.Schema.json
  changelog/Microsoft.O365Reporting.json
  changelog/Microsoft.Security.Ediscovery.json
  changelog/Microsoft.UnifiedStorageQuota.json
  changelog/validate-json.ps1
Labels: do not merge, internal, invalid links

#20627 Edits in PR 20434
  api-reference/beta/resources/deltaparticipants.md
  api-reference/beta/resources/participant.md
  api-reference/beta/resources/removedstate.md
Labels: external

#20629 Edits in PR 20340
  api-reference/beta/api/cloudpcprovisioningpolicy-apply.md
  api-reference/beta/api/cloudpcprovisioningpolicy-applyconfig.md
  api-reference/beta/resources/cloudpcprovisioningpolicy.md
  api-reference/beta/toc.yml
  changelog/Microsoft.CloudManagedDesktop.json
Labels: external

#20630 updates
  .github/fabricbot.json
Labels: do not merge, internal

#20631 updates to bot
  .github/fabricbot.json
Labels: internal

#20108 list usermemberships v1 permissions table update
  api-reference/v1.0/api/user-list-transitivememberof.md
Labels: area: Azure AD, area: groups, ready to merge, internal, content review complete

#20109 beta permissions update for list users memberships
  api-reference/beta/api/user-list-transitivememberof.md
Labels: area: Azure AD, area: groups, ready to merge, internal, content review complete

#20407 Adding section for deflection - bug449977
  api-reference/beta/resources/dynamics-graph-reference.md
  api-reference/beta/resources/dynamics-tenant-admin-environment.png
Labels: ready to merge, internal, content review complete

#20456 Changes made to reflect team templates graph apis and permissions bei…
  api-reference/beta/api/team-post.md
  api-reference/beta/api/teamtemplatedefinition-get-teamdefinition.md
  api-reference/beta/api/teamtemplatedefinition-get.md
  api-reference/beta/resources/teamtemplate.md
  api-reference/beta/resources/teamtemplatedefinition.md
Labels: ready to merge, internal, content review complete

#20595 Add query template redirect link to query
  api-reference/beta/api/search-query.md
Labels: ready to merge, internal, Ignite22, content review complete

#20614 Minor doc fixes
  api-reference/beta/api/application-delete-tokenlifetimepolicies.md
  api-reference/beta/api/application-list-tokenlifetimepolicies.md
  api-reference/beta/api/application-post-tokenlifetimepolicies.md
  api-reference/beta/api/directory-deleteditems-list.md
  api-reference/beta/api/tokenlifetimepolicy-delete.md
  api-reference/beta/api/tokenlifetimepolicy-get.md
  api-reference/beta/api/tokenlifetimepolicy-list-appliesto.md
  api-reference/beta/api/tokenlifetimepolicy-list.md
  api-reference/beta/api/tokenlifetimepolicy-post-tokenlifetimepolicies.md
  api-reference/beta/api/tokenlifetimepolicy-update.md
  api-reference/beta/api/user-update.md
  api-reference/beta/resources/signinactivity.md
  api-reference/beta/resources/tokenlifetimepolicy.md
  api-reference/beta/resources/user.md
  api-reference/v1.0/api/application-delete-tokenlifetimepolicies.md
  api-reference/v1.0/api/application-list-tokenlifetimepolicies.md
  api-reference/v1.0/api/application-post-tokenlifetimepolicies.md
  api-reference/v1.0/api/directory-deleteditems-list.md
  api-reference/v1.0/api/tokenlifetimepolicy-delete.md
  api-reference/v1.0/api/tokenlifetimepolicy-get.md
  api-reference/v1.0/api/tokenlifetimepolicy-list-appliesto.md
  api-reference/v1.0/api/tokenlifetimepolicy-list.md
  api-reference/v1.0/api/tokenlifetimepolicy-post-tokenlifetimepolicies.md
  api-reference/v1.0/api/tokenlifetimepolicy-update.md
  api-reference/v1.0/api/user-update.md
  api-reference/v1.0/resources/tokenlifetimepolicy.md
  concepts/permissions-grant-via-msgraph.md
  concepts/search-query-parameter.md
Labels: area: Azure AD, ready to merge, internal

#20634 Polishing the bot message
  .github/fabricbot.json
Labels: ready to merge

#20542 [Doc Improvement][Updated teamworkTag]
  api-reference/beta/resources/teamworktag.md
  api-reference/v1.0/resources/teamworktag.md
Labels: ready to merge, internal, content review complete

#20374 Adding new custom extensibility changes with new models with a request resume action
  api-reference/beta/api/accesspackageassignmentpolicy-get.md
  api-reference/beta/api/accesspackageassignmentpolicy-update.md
  api-reference/beta/api/accesspackageassignmentrequest-resume.md
  api-reference/beta/api/accesspackageassignmentrequestworkflowextension-delete.md
  api-reference/beta/api/accesspackageassignmentrequestworkflowextension-get.md
  api-reference/beta/api/accesspackageassignmentrequestworkflowextension-update.md
  api-reference/beta/api/accesspackageassignmentworkflowextension-delete.md
  api-reference/beta/api/accesspackageassignmentworkflowextension-get.md
  api-reference/beta/api/accesspackageassignmentworkflowextension-update.md
  api-reference/beta/api/accesspackagecatalog-list-accesspackagecustomworkflowextensions.md
  api-reference/beta/api/accesspackagecatalog-post-accesspackagecustomworkflowextensions.md
  api-reference/beta/api/accesspackagecatalog-post-customaccesspackageworkflowextensions.md
  api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md
  api-reference/beta/resources/accesspackageassignment.md
  api-reference/beta/resources/accesspackageassignmentpolicy.md
  api-reference/beta/resources/accesspackageassignmentrequest.md
  api-reference/beta/resources/accesspackageassignmentrequestcallbackdata.md
  api-reference/beta/resources/accesspackageassignmentrequestworkflowextension.md
  api-reference/beta/resources/accesspackageassignmentworkflowextension.md
  api-reference/beta/resources/accesspackagecatalog.md
  api-reference/beta/resources/azureadpoptokenauthentication.md
  api-reference/beta/resources/customcalloutextension.md
  api-reference/beta/resources/customextensioncallbackconfiguration.md
  api-reference/beta/resources/customextensioncalloutinstance.md
  api-reference/beta/resources/customextensiondata.md
  api-reference/beta/resources/customextensionstagesetting.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/logicapptriggerendpointconfiguration.md
  api-reference/beta/toc.yml
  changelog/Microsoft.IGAELM.json
Labels: area: Azure AD, ready to merge, internal, content review complete

#20646 Edits in PR 20096
  api-reference/beta/includes/education-deprecate-educationsynchronizationprofile.md
  api-reference/beta/toc.yml
  changelog/Microsoft.EducationDataSync.json
Labels: external

#20641 Update userscopeteamsappinstallation-get-chat.md
  api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md
Labels: external

#20640 Update dynamics-companies-get.md
  api-reference/beta/api/dynamics-companies-get.md
Labels: external

#16706 ListChannels perf improvement for v1.0
  api-reference/v1.0/api/channel-list.md
Labels: ready to merge, internal, content review complete

#19666 Remove no needed properties odata.type and subscriptionName in create Cloudpc onpremisesconenctions
  api-reference/beta/api/virtualendpoint-post-onpremisesconnections.md
  api-reference/beta/includes/snippets/csharp/create-cloudpconpremisesconnection-from-cloudpconpremisesconnection-csharp-snippets.md
  api-reference/beta/includes/snippets/go/create-cloudpconpremisesconnection-from-cloudpconpremisesconnection-go-snippets.md
  api-reference/beta/includes/snippets/java/create-cloudpconpremisesconnection-from-cloudpconpremisesconnection-java-snippets.md
  api-reference/beta/includes/snippets/javascript/create-cloudpconpremisesconnection-from-cloudpconpremisesconnection-javascript-snippets.md
  api-reference/beta/includes/snippets/php/create-cloudpconpremisesconnection-from-cloudpconpremisesconnection-php-snippets.md
  api-reference/beta/includes/snippets/powershell/create-cloudpconpremisesconnection-from-cloudpconpremisesconnection-powershell-snippets.md
Labels: do not merge, ready to merge, internal, content review complete

#20607 Update toc.yml
  concepts/toc.yml
Labels: ready to merge, internal, area: connectors

#20639 Update resume action
  api-reference/beta/api/accesspackageassignmentrequest-resume.md
  api-reference/beta/resources/customextensiondata.md
  api-reference/beta/toc.yml
Labels: ready to merge, ready for content review, internal

#20651 vfrankson-03.20.2023
  api-reference/beta/resources/industrydata-overview.md
  concepts/industrydata-concept-overview.md
Labels: ready to merge, internal

#20671 Update inbar's branch because I can't
  api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md
  api-reference/beta/api/authenticationstrengthpolicy-get.md
  api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md
  api-reference/beta/api/authenticationstrengthroot-list-policies.md
  api-reference/beta/includes/snippets/java/create-authenticationcombinationconfiguration-from--java-snippets.md
  api-reference/beta/includes/snippets/java/delete-authenticationcombinationconfiguration-java-snippets.md
  api-reference/beta/includes/snippets/java/get-authenticationcombinationconfiguration-java-snippets.md
  api-reference/beta/includes/snippets/java/get-authenticationmethodmodedetail-java-snippets.md
  api-reference/beta/includes/snippets/java/list-authenticationcombinationconfiguration-java-snippets.md
  api-reference/beta/includes/snippets/java/list-authenticationmethodmodedetail-java-snippets.md
  api-reference/beta/includes/snippets/java/update-authenticationcombinationconfiguration-java-snippets.md
  api-reference/beta/includes/snippets/javascript/get-authenticationmethodmodedetail-javascript-snippets.md
  api-reference/beta/includes/snippets/javascript/list-authenticationmethodmodedetail-javascript-snippets.md
  api-reference/beta/includes/snippets/php/create-authenticationcombinationconfiguration-from--php-snippets.md
  api-reference/beta/includes/snippets/php/delete-authenticationcombinationconfiguration-php-snippets.md
  api-reference/beta/includes/snippets/php/get-authenticationcombinationconfiguration-php-snippets.md
  api-reference/beta/includes/snippets/php/get-authenticationmethodmodedetail-php-snippets.md
  api-reference/beta/includes/snippets/php/list-authenticationcombinationconfiguration-php-snippets.md
  api-reference/beta/includes/snippets/php/list-authenticationmethodmodedetail-php-snippets.md
  api-reference/beta/includes/snippets/php/update-authenticationcombinationconfiguration-php-snippets.md
  api-reference/beta/resources/authenticationcombinationconfiguration.md
  api-reference/beta/resources/authenticationstrengths-overview.md
  api-reference/beta/resources/conditionalaccessgrantcontrols.md
  api-reference/beta/resources/conditionalaccessroot.md
  api-reference/v1.0/api/authenticationcombinationconfiguration-get.md
  api-reference/v1.0/api/authenticationstrengthpolicy-get.md
  api-reference/v1.0/api/authenticationstrengthpolicy-list-combinationconfigurations.md
  api-reference/v1.0/api/authenticationstrengthpolicy-post-combinationconfigurations.md
  api-reference/v1.0/api/authenticationstrengthpolicy-updateallowedcombinations.md
  api-reference/v1.0/api/authenticationstrengthroot-list-authenticationmethodmodes.md
  api-reference/v1.0/api/authenticationstrengthroot-list-policies.md
  api-reference/v1.0/resources/authenticationcombinationconfiguration.md
  api-reference/v1.0/resources/authenticationstrengths-overview.md
  api-reference/v1.0/resources/conditionalaccessgrantcontrols.md
  api-reference/v1.0/resources/policyroot.md
Labels: external

#20669 Edits in PR 19584
  concepts/planner-task-recurrence-concept.md
Labels: external

#14644 Auth Methods API - Remove self on email and phone
  api-reference/beta/api/emailauthenticationmethod-update.md
  api-reference/beta/api/phoneauthenticationmethod-update.md
Labels: area: Azure AD, ready to merge, area: identity, content review complete

#19008 [CloudPC]add shiftWorkCloudPcAccessState.md in resource and cloudpc-getshiftwo…
  api-reference/beta/api/cloudpc-getcloudpclaunchinfo.md
  api-reference/beta/api/cloudpc-getshiftworkcloudpcaccessstate.md
  api-reference/beta/resources/cloudpc.md
  api-reference/beta/toc.yml
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, internal, content review complete, schema live

#20387 Fix: typo in webpart-list.md
  api-reference/beta/api/sitepage-getwebpartsbyposition.md
  api-reference/beta/api/webpart-list.md
Labels: ready to merge, internal

#20440 Updating examples to correctly match production
  concepts/accessreviews-scope-concept.md
Labels: area: Azure AD, ready to merge, internal, content review complete

#20666 excluding blocked PRs
  .github/fabricbot.json
Labels: ready to merge, internal

#19781 [CloudPC] Add service plan supportedSolution and provisioningType property
  api-reference/beta/resources/cloudpcserviceplan.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, internal

#19880 updated gcc docs for todo
  api-reference/beta/resources/subscription.md
  api-reference/v1.0/resources/subscription.md
  concepts/deployments.md
  concepts/includes/change-notifications-supported-resources-flat.md
Labels: ready to merge, internal, content review complete
