Repository microsoftgraph/microsoft-graph-docs, pull requests merged in 2023-02, with the labels that each got.

#20080 Add Members permissions table - beta
  api-reference/beta/api/group-post-members.md
Labels: area: Azure AD, area: groups, ready to merge, internal, content review complete

#19737 Add note regarding permissions
  api-reference/v1.0/api/group-post-members.md
Labels: area: Azure AD, area: groups, awaiting internal response, ready to merge, internal, content review complete

#18254 [CloudPC]Add disk encryption type to CloudPC entity
  api-reference/beta/api/cloudpc-get.md
  api-reference/beta/api/user-list-cloudpcs.md
  api-reference/beta/api/virtualendpoint-list-cloudpcs.md
  api-reference/beta/resources/cloudpc.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, internal, content review complete, schema live

#20086 Edits in PR 18043
  api-reference/beta/api/industrydata-fileValidateOperation-get.md
  api-reference/beta/api/industrydata-fileValidateOperation-list.md
  api-reference/beta/api/industrydata-filevalidateoperation-get.md
  api-reference/beta/api/industrydata-filevalidateoperation-list.md
  api-reference/beta/api/industrydata-inboundfileflow-post.md
  api-reference/beta/api/industrydata-inboundflow-update.md
  api-reference/beta/api/industrydata-industrydataconnector-list.md
  api-reference/beta/api/industrydata-sourcesystemdefinition-list.md
  api-reference/beta/api/industrydata-validateOperation-get.md
  api-reference/beta/api/industrydata-validateOperation-list.md
  api-reference/beta/api/industrydata-yeartimeperioddefinition-list.md
  api-reference/beta/resources/industrydata-filevalidateoperation.md
  api-reference/beta/resources/industrydata-identifiertypereferencevalue.md
  api-reference/beta/resources/industrydata-industrydataroot.md
  api-reference/beta/resources/industrydata-longrunningoperation.md
  api-reference/beta/resources/industrydata-overview.md
  api-reference/beta/resources/industrydata-rolereferencevalue.md
  api-reference/beta/resources/industrydata-usermatchtargetreferencevalue.md
  api-reference/beta/resources/industrydata-validateoperation.md
  api-reference/beta/toc.yml
  changelog/Microsoft.IndustryData.json
Labels: external

#20104 Update plannertask-update.md
  api-reference/beta/api/plannertask-update.md
Labels: external

#20103 Update plannertask-update.md
  api-reference/beta/api/plannertask-update.md
Labels: external

#20102 Update plannertask-update.md
  api-reference/v1.0/api/plannertask-update.md
Labels: external

#20101 Edits in PR 19584
  api-reference/beta/api/plannertask-update.md
  api-reference/beta/resources/plannerrecurrenceschedule.md
  api-reference/beta/resources/plannertask.md
  api-reference/beta/resources/plannertaskrecurrence.md
  changelog/Microsoft.Office.Tasks.json
Labels: external

#20091 Minor doc fixes
  api-reference/beta/api/oauth2permissiongrant-update.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/oauth2permissiongrant-update.md
  api-reference/v1.0/toc.yml
  concepts/deployments.md
  concepts/filter-query-parameter.md
  concepts/toc.yml
  concepts/tutorial-applications-basics.md
Labels: area: Azure AD, ready to merge, internal

#20106 Adding note to for call establishing/established notification order to v1 as well
  api-reference/beta/api/application-post-calls.md
  api-reference/beta/api/call-answer.md
  api-reference/v1.0/api/application-post-calls.md
  api-reference/v1.0/api/call-answer.md
Labels: do not merge, internal, content review complete

#20124 Edits in PR 18684
  api-reference/beta/resources/riskuseractivity.md
  api-reference/beta/resources/riskyuser.md
  api-reference/beta/resources/riskyuserhistoryitem.md
  api-reference/beta/resources/signin.md
  api-reference/v1.0/resources/riskuseractivity.md
  api-reference/v1.0/resources/riskyuser.md
  api-reference/v1.0/resources/riskyuserhistoryitem.md
  api-reference/v1.0/resources/signin.md
Labels: external

#20128 Fixed service name.
  api-reference/beta/toc.yml
Labels: external

#20129 Fixed issues in the TOC
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
Labels: external

#20122 Update dynamics-currencies-delete.md
  api-reference/beta/api/dynamics-currencies-delete.md
Labels: external

#19864 Execution Scope API
  api-reference/beta/api/workflow-list-executionscope.md
  api-reference/beta/resources/identitygovernance-workflow.md
  api-reference/beta/toc.yml
  changelog/Microsoft.AAD.LCM.json
Labels: area: Azure AD, ready to merge, internal, content review complete

#19926 Added coorganizer meeting role to v1.0
  api-reference/v1.0/api/application-post-onlinemeetings.md
  api-reference/v1.0/resources/meetingparticipantinfo.md
  changelog/Microsoft.Skype.Calling.json
Labels: ready to merge, internal, content review complete

#20116 Content freshness - Extensions module
  concepts/extensibility-open-users.md
  concepts/extensibility-overview.md
  concepts/extensibility-schema-groups.md
Labels: area: Azure AD, ready to merge, internal, area: extensions

#20117 Minor doc fixes
  api-reference/beta/resources/ipnamedlocation.md
  api-reference/v1.0/resources/ipnamedlocation.md
  concepts/applications-how-to-add-certificate.md
  concepts/deployments.md
Labels: area: Azure AD, ready to merge

#20105 Creating new PR with clean AADR API changes
  api-reference/beta/api/directory-list-recommendation.md
  api-reference/beta/api/impactedresource-complete.md
  api-reference/beta/api/impactedresource-dismiss.md
  api-reference/beta/api/impactedresource-get.md
  api-reference/beta/api/impactedresource-postpone.md
  api-reference/beta/api/impactedresource-reactivate.md
  api-reference/beta/api/recommendation-complete.md
  api-reference/beta/api/recommendation-dismiss.md
  api-reference/beta/api/recommendation-get.md
  api-reference/beta/api/recommendation-list-impactedresources.md
  api-reference/beta/api/recommendation-postpone.md
  api-reference/beta/api/recommendation-reactivate.md
  api-reference/beta/resources/actionstep.md
  api-reference/beta/resources/actionurl.md
  api-reference/beta/resources/directory.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/impactedresource.md
  api-reference/beta/resources/recommendation.md
  api-reference/beta/resources/recommendationbase.md
  api-reference/beta/toc.yml
  changelog/Microsoft.AAD.Reporting.json
  concepts/permissions-reference.md
Labels: area: Azure AD, ready to merge, internal, content review complete

#20097 preventing misunderstandings
  api-reference/beta/resources/internaldomainfederation.md
  api-reference/v1.0/resources/internaldomainfederation.md
Labels: area: Azure AD, external, ready to merge, review requested

#20120 list groups expand members
  api-reference/v1.0/api/group-list.md
Labels: area: Azure AD, area: groups, ready to merge, internal, content review complete

#20121 list groups expand members - beta
  api-reference/beta/api/group-list.md
Labels: area: Azure AD, area: groups, ready to merge, internal, content review complete

#20136 Fixed broken TOC entry.
  api-reference/beta/toc.yml
Labels: do not merge, internal

#18356 Adding documentation for ELM questions v1
  api-reference/v1.0/api/accesspackageassignmentpolicy-update.md
  api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md
  api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md
  api-reference/v1.0/resources/accesspackageanswer.md
  api-reference/v1.0/resources/accesspackageanswerchoice.md
  api-reference/v1.0/resources/accesspackageanswerstring.md
  api-reference/v1.0/resources/accesspackageassignmentpolicy.md
  api-reference/v1.0/resources/accesspackageassignmentrequest.md
  api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md
  api-reference/v1.0/resources/accesspackagelocalizedtext.md
  api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md
  api-reference/v1.0/resources/accesspackagequestion.md
  api-reference/v1.0/resources/accesspackagetextinputquestion.md
  changelog/Microsoft.IGAELM.json
Labels: area: Azure AD, ready to merge, internal, area: identity, content review complete, schema live

#20132 Update identitycontainer-post-identityproviders.md
  api-reference/beta/api/identitycontainer-post-identityproviders.md
  api-reference/v1.0/api/identitycontainer-post-identityproviders.md
Labels: external, ready to merge

#20137 Merge to publish.
  api-reference/beta/api/group-list.md
  api-reference/beta/api/identitycontainer-post-identityproviders.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/accesspackageassignmentpolicy-update.md
  api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md
  api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md
  api-reference/v1.0/api/group-list.md
  api-reference/v1.0/api/identitycontainer-post-identityproviders.md
  api-reference/v1.0/resources/accesspackageanswer.md
  api-reference/v1.0/resources/accesspackageanswerchoice.md
  api-reference/v1.0/resources/accesspackageanswerstring.md
  api-reference/v1.0/resources/accesspackageassignmentpolicy.md
  api-reference/v1.0/resources/accesspackageassignmentrequest.md
  api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md
  api-reference/v1.0/resources/accesspackagelocalizedtext.md
  api-reference/v1.0/resources/accesspackagemultiplechoicequestion.md
  api-reference/v1.0/resources/accesspackagequestion.md
  api-reference/v1.0/resources/accesspackagetextinputquestion.md
  changelog/Microsoft.CloudManagedDesktop.json
  changelog/Microsoft.IGAELM.json
Labels: do not merge, internal

#20148 Edits in PR 18537
  api-reference/beta/api/cloudpcprovisioningpolicy-update.md
  api-reference/beta/api/cloudpcshareduseserviceplan-get.md
  api-reference/beta/api/virtualendpoint-list-shareduseserviceplans.md
  api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md
  api-reference/beta/resources/cloudpcmanagementgroupassignmenttarget.md
  api-reference/beta/resources/cloudpcprovisioningpolicy.md
  api-reference/beta/resources/virtualendpoint.md
Labels: external

#20150 Edits in PR 19104
  api-reference/beta/api/cloudpcorganizationsettings-update.md
  api-reference/beta/api/cloudpcprovisioningpolicy-update.md
  api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md
  api-reference/beta/resources/cloudpcorganizationsettings.md
  api-reference/beta/resources/cloudpcprovisioningpolicy.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: external

#20151 Update dynamics-generalledgerentries.md
  api-reference/beta/resources/dynamics-generalledgerentries.md
Labels: external

#20139 Update contactfolder.md
  api-reference/beta/resources/contactfolder.md
Labels: external

#20138 Update contactfolder.md
  api-reference/v1.0/resources/contactfolder.md
Labels: external

#20144 Change placement of cross-link to training module
  concepts/delta-query-overview.md
  concepts/extensibility-overview.md
  concepts/query-parameters.md
  concepts/throttling.md
  concepts/webhooks.md
Labels: ready to merge, internal, area: query parameters

#20149 Correcting documentation on ListChatMessages $filter operators
  api-reference/beta/api/chat-list-messages.md
  api-reference/v1.0/api/chat-list-messages.md
Labels: ready to merge, internal, content review complete

#19200 Add ACS user type to Teams chats
  api-reference/beta/resources/azurecommunicationservicesuserconversationmember.md
  api-reference/beta/resources/conversationmember.md
  changelog/Microsoft.Teams.GraphSvc.json
Labels: ready to merge, internal, content review complete, invalid links

#20141 Update ItemReference to add information about listItems
  api-reference/beta/resources/itemreference.md
  api-reference/v1.0/resources/itemreference.md
Labels: ready to merge, internal, content review complete

#20152 Merge to publish.
  api-reference/beta/api/chat-list-messages.md
  api-reference/beta/resources/azurecommunicationservicesuserconversationmember.md
  api-reference/beta/resources/contactfolder.md
  api-reference/beta/resources/conversationmember.md
  api-reference/beta/resources/dynamics-generalledgerentries.md
  api-reference/beta/resources/itemreference.md
  api-reference/v1.0/api/chat-list-messages.md
  api-reference/v1.0/resources/contactfolder.md
  api-reference/v1.0/resources/itemreference.md
  changelog/Microsoft.Teams.GraphSvc.json
  concepts/delta-query-overview.md
  concepts/extensibility-overview.md
  concepts/query-parameters.md
  concepts/throttling.md
  concepts/webhooks.md
Labels: do not merge, internal, invalid links

#20164 Edits in PR 20085
  api-reference/beta/api/callrecords-callrecord-getpstnblockeduserslog.md
  api-reference/beta/api/callrecords-callrecord-getpstnonlinemeetingdialoutreport.md
  api-reference/beta/api/callrecords-callrecord-getsmslog.md
  api-reference/beta/resources/callrecords-api-overview.md
  api-reference/beta/resources/callrecords-callrecord.md
  api-reference/beta/resources/callrecords-directroutinglogrow.md
  api-reference/beta/resources/callrecords-pstnblockeduserslogrow.md
  api-reference/beta/resources/callrecords-pstncalllogrow.md
  api-reference/beta/resources/callrecords-pstnonlinemeetingdialoutreport.md
  api-reference/beta/resources/callrecords-smslogrow.md
  api-reference/beta/toc.yml
  changelog/Microsoft.IC3.DataPlatform.json
Labels: external

#20166 Update callrecords-pstncalllogrow.md
  api-reference/v1.0/resources/callrecords-pstncalllogrow.md
Labels: external

#19978 Added note to Shifts topics.
  api-reference/beta/api/schedule-post-shifts.md
  api-reference/beta/api/shift-put.md
  api-reference/beta/resources/shift.md
  api-reference/v1.0/api/schedule-post-shifts.md
  api-reference/v1.0/api/shift-put.md
  api-reference/v1.0/resources/shift.md
Labels: ready to merge, internal

#20156 Restore accidentally deleted examples
  concepts/applications-how-to-add-certificate.md
  concepts/how-to-pim-update-rules.md
  concepts/search-query-parameter.md
  concepts/tutorial-applications-basics.md
Labels: area: Azure AD, ready to merge, internal

#20165 Update callrecords-pstncalllogrow.md
  api-reference/beta/resources/callrecords-pstncalllogrow.md
Labels: external

#20093 Update connecting-external-content-api-limits.md
  concepts/connecting-external-content-api-limits.md
Labels: external

#20193 Edits in PR 20085
  api-reference/beta/api/callrecords-callrecord-getdirectroutingcalls.md
  api-reference/beta/api/callrecords-callrecord-getpstnblockeduserslog.md
  api-reference/beta/api/callrecords-callrecord-getpstncalls.md
  api-reference/beta/api/callrecords-callrecord-getpstnonlinemeetingdialoutreport.md
  api-reference/beta/api/callrecords-callrecord-getsmslog.md
  api-reference/beta/resources/callrecords-callrecord.md
  api-reference/beta/resources/callrecords-directroutinglogrow.md
  api-reference/beta/resources/callrecords-pstnblockeduserslogrow.md
  api-reference/beta/resources/callrecords-pstncalllogrow.md
  api-reference/beta/resources/callrecords-pstnonlinemeetingdialoutreport.md
  api-reference/beta/resources/callrecords-smslogrow.md
  api-reference/beta/toc.yml
  changelog/Microsoft.IC3.DataPlatform.json
Labels: external

#20195 Fixed issues in PR 19629
  api-reference/beta/resources/onlineMeetingRestricted.md
  api-reference/beta/resources/onlinemeeting.md
  api-reference/beta/resources/onlinemeetingrestricted.md
  api-reference/beta/resources/participant.md
  api-reference/beta/resources/watermarkprotectionvalues.md
  changelog/Microsoft.Skype.Calling.json
Labels: external

#20155 Recommendations API overview
  api-reference/beta/resources/recommendation.md
  api-reference/beta/resources/recommendations-api-overview.md
  api-reference/beta/toc.yml
Labels: area: Azure AD, ready to merge, internal, area: identity

#20162 Privileged Access Groups = PIM for groups
  concepts/accessreviews-reviewers-concept.md
Labels: area: Azure AD, ready to merge, internal, area: governance

#20169 Add rbac roles to domain api docs v1
  api-reference/v1.0/api/domain-delete.md
  api-reference/v1.0/api/domain-forcedelete.md
  api-reference/v1.0/api/domain-get.md
  api-reference/v1.0/api/domain-list-domainnamereferences.md
  api-reference/v1.0/api/domain-list-verificationdnsrecords.md
  api-reference/v1.0/api/domain-list.md
  api-reference/v1.0/api/domain-post-domains.md
  api-reference/v1.0/api/domain-update.md
  api-reference/v1.0/api/domain-verify.md
Labels: area: Azure AD, ready to merge, internal, content review complete

#20175 Update identitygovernance.md
  api-reference/beta/resources/identitygovernance.md
Labels: area: Azure AD, ready to merge, internal

#20178 Add note for #20172
  api-reference/beta/api/rbacapplication-list-transitiveroleassignments.md
Labels: area: Azure AD, ready to merge, internal, area: directory management

#20179 Update externalconnectors-urltoitemresolverbase.md
  api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md
Labels: ready to merge, internal, content review complete

#20185 Fixes Planner Roster typo and toc label
  api-reference/beta/api/plannerroster-post-members.md
  api-reference/beta/toc.yml
Labels: external

#20173 Fix minor typo for "oAuth2PermissionGrant"
  concepts/permissions-reference.md
Labels: external

#20197 Merge to publish.
  api-reference/beta/api/plannerroster-post-members.md
  api-reference/beta/api/rbacapplication-list-transitiveroleassignments.md
  api-reference/beta/api/schedule-post-shifts.md
  api-reference/beta/api/shift-put.md
  api-reference/beta/resources/callrecords-pstncalllogrow.md
  api-reference/beta/resources/externalconnectors-urltoitemresolverbase.md
  api-reference/beta/resources/identitygovernance.md
  api-reference/beta/resources/recommendation.md
  api-reference/beta/resources/recommendations-api-overview.md
  api-reference/beta/resources/shift.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/domain-delete.md
  api-reference/v1.0/api/domain-forcedelete.md
  api-reference/v1.0/api/domain-get.md
  api-reference/v1.0/api/domain-list-domainnamereferences.md
  api-reference/v1.0/api/domain-list-verificationdnsrecords.md
  api-reference/v1.0/api/domain-list.md
  api-reference/v1.0/api/domain-post-domains.md
  api-reference/v1.0/api/domain-update.md
  api-reference/v1.0/api/domain-verify.md
  api-reference/v1.0/api/schedule-post-shifts.md
  api-reference/v1.0/api/shift-put.md
  api-reference/v1.0/resources/callrecords-pstncalllogrow.md
  api-reference/v1.0/resources/shift.md
  concepts/accessreviews-reviewers-concept.md
  concepts/applications-how-to-add-certificate.md
  concepts/connecting-external-content-api-limits.md
  concepts/how-to-pim-update-rules.md
  concepts/permissions-reference.md
  concepts/search-query-parameter.md
  concepts/tutorial-applications-basics.md
Labels: do not merge, internal

#20206 Edits in PR 19629
  concepts/cloud-communications-watermark-meeting.md
Labels: external

#20207 Update calltranscript.md
  api-reference/beta/resources/calltranscript.md
Labels: external

#18537 [CloudPC]Add sharedUseLicenseType to virtualEndpoint resource (feature First Line Worker)
  api-reference/beta/api/cloudpcprovisioningpolicy-get.md
  api-reference/beta/api/cloudpcprovisioningpolicy-update.md
  api-reference/beta/api/cloudpcshareduseserviceplan-get.md
  api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md
  api-reference/beta/api/virtualendpoint-list-shareduseserviceplans.md
  api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md
  api-reference/beta/resources/cloudpcmanagementgroupassignmenttarget.md
  api-reference/beta/resources/cloudpcprovisioningpolicy.md
  api-reference/beta/resources/cloudpcshareduseserviceplan.md
  api-reference/beta/resources/virtualendpoint.md
  api-reference/beta/toc.yml
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, internal, content review complete, schema live

#19104 [CloudPC]add singleSignOn into ProvisioningPolicy and OrganizationSetting
  api-reference/beta/api/cloudpcorganizationsettings-get.md
  api-reference/beta/api/cloudpcorganizationsettings-update.md
  api-reference/beta/api/cloudpcprovisioningpolicy-get.md
  api-reference/beta/api/cloudpcprovisioningpolicy-update.md
  api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md
  api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md
  api-reference/beta/resources/cloudpcorganizationsettings.md
  api-reference/beta/resources/cloudpcprovisioningpolicy.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: do not merge, ready to merge, internal, content review complete, invalid links

#20045 Add new property to Teams App Settings.
  api-reference/beta/api/teamsappsettings-get.md
  api-reference/beta/api/teamsappsettings-update.md
  api-reference/beta/resources/teamsappsettings.md
  changelog/Microsoft.Teams.GraphSvc.json
Labels: ready to merge, internal, content review complete

#20227 Edits in PR 19629
  api-reference/beta/resources/onlinemeetingrestricted.md
  api-reference/beta/resources/watermarkprotectionvalues.md
  changelog/Microsoft.Skype.Calling.json
  concepts/cloud-communications-watermark-meeting.md
  concepts/toc.yml
Labels: external

#20187 Add RBAC roles to device apis
  api-reference/beta/api/device-delete-registeredusers.md
  api-reference/beta/api/device-get.md
  api-reference/beta/api/device-list-registeredusers.md
  api-reference/beta/api/device-list.md
  api-reference/beta/api/device-post-registeredusers.md
Labels: area: Azure AD, ready to merge, internal, content review complete

#20201 Update Organization docs with rbac roles
  api-reference/beta/api/organization-get.md
  api-reference/beta/api/organization-update.md
Labels: ready to merge, internal, content review complete

#20208 Ryanwilliams-windowsupdates-public_preview_updates
  concepts/windowsupdates-concept-overview.md
  concepts/windowsupdates-manage-driver-update.md
Labels: ready to merge, internal, content review complete

#20215 Use descriptive example names
  api-reference/beta/api/directory-deleteditems-delete.md
  api-reference/beta/api/directory-deleteditems-get.md
  api-reference/beta/api/directory-deleteditems-getuserownedobjects.md
  api-reference/beta/api/directory-deleteditems-list.md
  api-reference/beta/api/directory-deleteditems-restore.md
  api-reference/v1.0/api/directory-deleteditems-delete.md
  api-reference/v1.0/api/directory-deleteditems-get.md
  api-reference/v1.0/api/directory-deleteditems-getuserownedobjects.md
  api-reference/v1.0/api/directory-deleteditems-list.md
  api-reference/v1.0/api/directory-deleteditems-restore.md
Labels: area: Azure AD, ready to merge, internal

#20219 Fix request block
  concepts/tutorial-applications-basics.md
Labels: area: Azure AD, ready to merge

#20222 Fix #16138
  api-reference/beta/api/serviceprincipal-post-serviceprincipals.md
  api-reference/v1.0/api/serviceprincipal-post-serviceprincipals.md
Labels: area: Azure AD, ready to merge, internal

#20223 Update user-delete.md
  api-reference/beta/api/user-delete.md
  api-reference/v1.0/api/user-delete.md
Labels: area: users, ready to merge, internal

#20228 Edits in PR 19584
  api-reference/beta/resources/plannerrecurrenceschedule.md
  api-reference/beta/resources/plannertaskrecurrence.md
Labels: external

#20229 Update workbooknameditem.md
  api-reference/beta/resources/workbooknameditem.md
Labels: external

#20230 Update range-unmerge.md
  api-reference/beta/api/range-unmerge.md
Labels: external

#20232 Update range-unmerge.md
  api-reference/v1.0/api/range-unmerge.md
Labels: external

#20217 Update group-post-members.md
  api-reference/v1.0/api/group-post-members.md
Labels: external

#20235 Merge to publish.
  api-reference/beta/api/device-delete-registeredusers.md
  api-reference/beta/api/device-get.md
  api-reference/beta/api/device-list-registeredusers.md
  api-reference/beta/api/device-list.md
  api-reference/beta/api/device-post-registeredusers.md
  api-reference/beta/api/directory-deleteditems-delete.md
  api-reference/beta/api/directory-deleteditems-get.md
  api-reference/beta/api/directory-deleteditems-getuserownedobjects.md
  api-reference/beta/api/directory-deleteditems-list.md
  api-reference/beta/api/directory-deleteditems-restore.md
  api-reference/beta/api/organization-get.md
  api-reference/beta/api/organization-update.md
  api-reference/beta/api/range-unmerge.md
  api-reference/beta/api/serviceprincipal-post-serviceprincipals.md
  api-reference/beta/api/user-delete.md
  api-reference/beta/resources/workbooknameditem.md
  api-reference/v1.0/api/directory-deleteditems-delete.md
  api-reference/v1.0/api/directory-deleteditems-get.md
  api-reference/v1.0/api/directory-deleteditems-getuserownedobjects.md
  api-reference/v1.0/api/directory-deleteditems-list.md
  api-reference/v1.0/api/directory-deleteditems-restore.md
  api-reference/v1.0/api/group-post-members.md
  api-reference/v1.0/api/range-unmerge.md
  api-reference/v1.0/api/serviceprincipal-post-serviceprincipals.md
  api-reference/v1.0/api/user-delete.md
  concepts/tutorial-applications-basics.md
  concepts/windowsupdates-concept-overview.md
  concepts/windowsupdates-manage-driver-update.md
Labels: internal

#20244 Update search-concept-searchall.md
  concepts/search-concept-searchall.md
Labels: external

#20245 Update workbookrange-resizedrange.md
  api-reference/v1.0/api/workbookrange-resizedrange.md
Labels: external

#20246 Update workbookrange-resizedrange.md
  api-reference/beta/api/workbookrange-resizedrange.md
Labels: external

#20089 Create include file - access reviews filter by scope
  api-reference/beta/api/accessreviewset-list-definitions.md
  api-reference/beta/api/accessreviewset-post-historydefinitions.md
  api-reference/includes/accessreviews-definition-filter-scope.md
  api-reference/v1.0/api/accessreviewset-list-definitions.md
  api-reference/v1.0/api/accessreviewset-post-historydefinitions.md
Labels: area: Azure AD, ready to merge, internal, area: governance

#20225 [Azure AD] [Custom security attributes] Add list examples
  api-reference/beta/api/serviceprincipal-update.md
  api-reference/beta/api/user-get.md
  api-reference/beta/api/user-list.md
  api-reference/beta/api/user-update.md
  api-reference/beta/resources/custom-security-attributes-overview.md
  api-reference/beta/resources/serviceprincipal.md
  api-reference/beta/resources/user.md
  concepts/custom-security-attributes-examples.md
  concepts/toc.yml
Labels: ready to merge, internal, content review complete

#20241 Update user/app privileges for write actions on user objects
  api-reference/beta/api/directory-deleteditems-restore.md
  api-reference/beta/api/user-delete.md
  api-reference/beta/api/user-update.md
  api-reference/beta/resources/users.md
  api-reference/v1.0/api/directory-deleteditems-restore.md
  api-reference/v1.0/api/user-delete.md
  api-reference/v1.0/api/user-update.md
  api-reference/v1.0/resources/user.md
  api-reference/v1.0/resources/users.md
Labels: area: Azure AD, area: users, ready to merge, internal, area: permissions

#19629 Added watermark doc to onlineMeeting and participant in beta.
  api-reference/beta/resources/onlinemeeting.md
  api-reference/beta/resources/onlinemeetingrestricted.md
  api-reference/beta/resources/participant.md
  api-reference/beta/resources/watermarkprotectionvalues.md
  changelog/Microsoft.Skype.Calling.json
  concepts/cloud-communications-watermark-meeting.md
  concepts/toc.yml
Labels: ready to merge, content review complete

#20248 Merge to publish.
  api-reference/beta/api/accessreviewset-list-definitions.md
  api-reference/beta/api/accessreviewset-post-historydefinitions.md
  api-reference/beta/api/directory-deleteditems-restore.md
  api-reference/beta/api/serviceprincipal-update.md
  api-reference/beta/api/user-delete.md
  api-reference/beta/api/user-get.md
  api-reference/beta/api/user-list.md
  api-reference/beta/api/user-update.md
  api-reference/beta/api/workbookrange-resizedrange.md
  api-reference/beta/resources/custom-security-attributes-overview.md
  api-reference/beta/resources/onlinemeeting.md
  api-reference/beta/resources/onlinemeetingrestricted.md
  api-reference/beta/resources/participant.md
  api-reference/beta/resources/serviceprincipal.md
  api-reference/beta/resources/user.md
  api-reference/beta/resources/users.md
  api-reference/beta/resources/watermarkprotectionvalues.md
  api-reference/includes/accessreviews-definition-filter-scope.md
  api-reference/v1.0/api/accessreviewset-list-definitions.md
  api-reference/v1.0/api/accessreviewset-post-historydefinitions.md
  api-reference/v1.0/api/directory-deleteditems-restore.md
  api-reference/v1.0/api/user-delete.md
  api-reference/v1.0/api/user-update.md
  api-reference/v1.0/api/workbookrange-resizedrange.md
  api-reference/v1.0/resources/user.md
  api-reference/v1.0/resources/users.md
  changelog/Microsoft.Skype.Calling.json
  concepts/cloud-communications-watermark-meeting.md
  concepts/custom-security-attributes-examples.md
  concepts/search-concept-searchall.md
  concepts/toc.yml
Labels: internal

#20262 Edits in PR 20011
  api-reference/beta/api/chat-list.md
  api-reference/beta/api/chatmessage-post.md
  api-reference/v1.0/api/chat-list.md
  api-reference/v1.0/api/chatmessage-post.md
  changelog/Microsoft.Teams.Core.json
Labels: external

#20263 Update mention.md
  api-reference/beta/resources/mention.md
Labels: external

#19950 Documentation for supported national clouds - 2
  api-reference/beta/api/calltranscript-get.md
  api-reference/beta/api/chat-list-messages.md
  api-reference/beta/api/chat-list.md
  api-reference/beta/api/chatmessage-softdelete.md
  api-reference/beta/api/onlinemeeting-list-transcripts.md
  api-reference/beta/api/userteamwork-delete-installedapps.md
  api-reference/beta/api/userteamwork-get-installedapps.md
  api-reference/beta/api/userteamwork-list-installedapps.md
  api-reference/beta/api/userteamwork-post-installedapps.md
  api-reference/beta/api/userteamwork-teamsappinstallation-upgrade.md
  api-reference/v1.0/api/chat-get.md
  api-reference/v1.0/api/chat-list-messages.md
  api-reference/v1.0/api/chat-list.md
  api-reference/v1.0/api/chatmessage-softdelete.md
  api-reference/v1.0/api/userteamwork-delete-installedapps.md
  api-reference/v1.0/api/userteamwork-get-installedapps.md
  api-reference/v1.0/api/userteamwork-list-installedapps.md
  api-reference/v1.0/api/userteamwork-post-installedapps.md
  api-reference/v1.0/api/userteamwork-teamsappinstallation-upgrade.md
  concepts/deployments.md
  concepts/teamwork-national-cloud-differences.md
  concepts/toc.yml
Labels: ready to merge, internal, content review complete

#20191 changes ownership of docs from shantaram to myra
  api-reference/beta/api/device-delete.md
  api-reference/beta/api/device-list-memberof.md
  api-reference/beta/api/device-list-registeredowners.md
  api-reference/beta/api/device-list-registeredusers.md
  api-reference/beta/api/device-list-transitivememberof.md
  api-reference/beta/api/device-post-devices.md
  api-reference/beta/api/device-post-registeredowners.md
  api-reference/beta/api/device-post-registeredusers.md
  api-reference/beta/resources/alternativeSecurityId.md
  api-reference/beta/resources/command.md
  api-reference/beta/resources/devicedetail.md
  api-reference/v1.0/api/device-delete.md
  api-reference/v1.0/api/device-list-memberof.md
  api-reference/v1.0/api/device-list-registeredowners.md
  api-reference/v1.0/api/device-list-registeredusers.md
  api-reference/v1.0/api/device-list-transitivememberof.md
  api-reference/v1.0/api/device-post-devices.md
  api-reference/v1.0/api/device-post-registeredowners.md
  api-reference/v1.0/api/device-post-registeredusers.md
  api-reference/v1.0/resources/alternativeSecurityId.md
Labels: ready to merge, internal, content review complete

#20192 Add throttling rules for callRecords resource
  concepts/throttling-limits.md
Labels: ready to merge, internal, area: cloud communications, content review complete

#20259 Update externalconnectors-itemidresolver.md
  api-reference/beta/resources/externalconnectors-itemidresolver.md
Labels: ready to merge, ready for content review, internal

#20264 Merge to publish.
  api-reference/beta/api/calltranscript-get.md
  api-reference/beta/api/chat-list-messages.md
  api-reference/beta/api/chat-list.md
  api-reference/beta/api/chatmessage-softdelete.md
  api-reference/beta/api/device-delete.md
  api-reference/beta/api/device-list-memberof.md
  api-reference/beta/api/device-list-registeredowners.md
  api-reference/beta/api/device-list-registeredusers.md
  api-reference/beta/api/device-list-transitivememberof.md
  api-reference/beta/api/device-post-devices.md
  api-reference/beta/api/device-post-registeredowners.md
  api-reference/beta/api/device-post-registeredusers.md
  api-reference/beta/api/onlinemeeting-list-transcripts.md
  api-reference/beta/api/userteamwork-delete-installedapps.md
  api-reference/beta/api/userteamwork-get-installedapps.md
  api-reference/beta/api/userteamwork-list-installedapps.md
  api-reference/beta/api/userteamwork-post-installedapps.md
  api-reference/beta/api/userteamwork-teamsappinstallation-upgrade.md
  api-reference/beta/resources/alternativeSecurityId.md
  api-reference/beta/resources/command.md
  api-reference/beta/resources/devicedetail.md
  api-reference/beta/resources/externalconnectors-itemidresolver.md
  api-reference/beta/resources/mention.md
  api-reference/v1.0/api/chat-get.md
  api-reference/v1.0/api/chat-list-messages.md
  api-reference/v1.0/api/chat-list.md
  api-reference/v1.0/api/chatmessage-softdelete.md
  api-reference/v1.0/api/device-delete.md
  api-reference/v1.0/api/device-list-memberof.md
  api-reference/v1.0/api/device-list-registeredowners.md
  api-reference/v1.0/api/device-list-registeredusers.md
  api-reference/v1.0/api/device-list-transitivememberof.md
  api-reference/v1.0/api/device-post-devices.md
  api-reference/v1.0/api/device-post-registeredowners.md
  api-reference/v1.0/api/device-post-registeredusers.md
  api-reference/v1.0/api/userteamwork-delete-installedapps.md
  api-reference/v1.0/api/userteamwork-get-installedapps.md
  api-reference/v1.0/api/userteamwork-list-installedapps.md
  api-reference/v1.0/api/userteamwork-post-installedapps.md
  api-reference/v1.0/api/userteamwork-teamsappinstallation-upgrade.md
  api-reference/v1.0/resources/alternativeSecurityId.md
  concepts/deployments.md
  concepts/teamwork-national-cloud-differences.md
  concepts/throttling-limits.md
  concepts/toc.yml
Labels: do not merge, internal

#20224 Replace Protected API link with Self-Serve User Guide
  concepts/images/teams-export-csv-sample.png
  concepts/images/teams-user-activity-report-sample.png
  concepts/teams-licenses.md
Labels: do not merge, internal

#20276 Edits in PR 20011
  api-reference/beta/api/chatmessage-post.md
  api-reference/v1.0/api/chatmessage-post.md
  changelog/Microsoft.Teams.Core.json
Labels: external

#20279 Edits in PR 20261
  api-reference/beta/api/plannerbucket-delta.md
  api-reference/beta/api/plannerplan-delta.md
  api-reference/beta/api/plannertask-delta.md
  api-reference/beta/resources/plannerbucket.md
Labels: external

#20265 Update connecting-external-content-api-limits.md
  concepts/connecting-external-content-api-limits.md
Labels: external

#20024 Change notifications docs refresh (Batch 2)
  api-reference/beta/resources/changenotificationcollection.md
  api-reference/beta/resources/subscription.md
  api-reference/beta/toc.yml
  api-reference/v1.0/resources/changenotificationcollection.md
  api-reference/v1.0/resources/subscription.md
  api-reference/v1.0/toc.yml
  concepts/change-notifications-delivery-event-hubs.md
  concepts/change-notifications-delivery-webhooks.md
  concepts/includes/change-notifications-delivery-notificationurl-validation.md
  concepts/toc.yml
  concepts/webhooks.md
  redirects/.openpublishing.redirection.changedapi.json
Labels: area: Azure AD, ready to merge, internal, area: change notifications

#20065 Document RBAC for domain federation APIs
  api-reference/beta/api/domain-post-federationconfiguration.md
  api-reference/beta/api/internaldomainfederation-delete.md
  api-reference/beta/api/internaldomainfederation-get.md
  api-reference/beta/api/internaldomainfederation-update.md
  api-reference/v1.0/api/domain-post-federationconfiguration.md
  api-reference/v1.0/api/internaldomainfederation-delete.md
  api-reference/v1.0/api/internaldomainfederation-get.md
  api-reference/v1.0/api/internaldomainfederation-update.md
Labels: area: Azure AD, ready to merge, internal, area: identity

#20250 Minor doc fixes
  api-reference/beta/api/user-list.md
  concepts/custom-security-attributes-examples.md
Labels: area: Azure AD, ready to merge, internal

#20271 Permissions updates
  api-reference/beta/api/user-update.md
  api-reference/v1.0/api/user-update.md
  changelog/Microsoft.DirectoryServices.json
  concepts/includes/permissions-ids.md
  concepts/permissions-reference.md
Labels: area: Azure AD, area: users, ready to merge, internal

#20131 Add disclaimer about expirationDateTime parameter on driveItem.Invite
  api-reference/beta/api/driveitem-invite.md
  api-reference/v1.0/api/driveitem-invite.md
Labels: ready to merge, internal, content review complete

#20281 Merge to publish.
  api-reference/beta/api/domain-post-federationconfiguration.md
  api-reference/beta/api/driveitem-invite.md
  api-reference/beta/api/internaldomainfederation-delete.md
  api-reference/beta/api/internaldomainfederation-get.md
  api-reference/beta/api/internaldomainfederation-update.md
  api-reference/beta/api/user-list.md
  api-reference/beta/api/user-update.md
  api-reference/beta/resources/changenotificationcollection.md
  api-reference/beta/resources/subscription.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/domain-post-federationconfiguration.md
  api-reference/v1.0/api/driveitem-invite.md
  api-reference/v1.0/api/internaldomainfederation-delete.md
  api-reference/v1.0/api/internaldomainfederation-get.md
  api-reference/v1.0/api/internaldomainfederation-update.md
  api-reference/v1.0/api/user-update.md
  api-reference/v1.0/resources/changenotificationcollection.md
  api-reference/v1.0/resources/subscription.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.DirectoryServices.json
  concepts/change-notifications-delivery-event-hubs.md
  concepts/change-notifications-delivery-webhooks.md
  concepts/connecting-external-content-api-limits.md
  concepts/custom-security-attributes-examples.md
  concepts/includes/change-notifications-delivery-notificationurl-validation.md
  concepts/includes/permissions-ids.md
  concepts/permissions-reference.md
  concepts/toc.yml
  concepts/webhooks.md
  redirects/.openpublishing.redirection.changedapi.json
Labels: do not merge, internal

#20290 Fixed typo in HTTP request
  api-reference/beta/api/calltranscript-get.md
  api-reference/v1.0/api/securescorecontrolprofile-get.md
Labels: ready to merge, internal, content review complete

#20273 Updating to point to MS Graph endpoint instead of Outlook REST endpoint
  api-reference/v1.0/resources/mailfolder.md
Labels: ready to merge, internal, content review complete

#20293 #ATCP - corrected a mistake
  api-reference/beta/resources/group.md
  api-reference/v1.0/resources/group.md
Labels: ready to merge, internal

#20304 Edits in PR 20261
  api-reference/beta/api/plannerbucket-delta.md
  api-reference/beta/api/plannerplan-delta.md
  api-reference/beta/api/plannertask-delta.md
  api-reference/beta/resources/plannerplan.md
  api-reference/beta/resources/plannertask.md
  changelog/Microsoft.Office.Tasks.json
Labels: external

#20247 Update TeamsFx provider doc for v3.0.0
  concepts/toolkit/providers/teamsfx.md
Labels: external

#20320 Edits in PR 20282
  changelog/Microsoft.Exchange.json
Labels: external

#20323 Edits in PR 18960
  api-reference/beta/resources/cloudpc.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: external

#20337 Edits in PR 20085
  api-reference/beta/api/callrecords-callrecord-getpstnblockeduserslog.md
  api-reference/beta/api/callrecords-callrecord-getpstnonlinemeetingdialoutreport.md
  api-reference/beta/api/callrecords-callrecord-getsmslog.md
  api-reference/beta/resources/callrecords-pstncalllogrow.md
  api-reference/beta/resources/callrecords-pstnonlinemeetingdialoutreport.md
  api-reference/beta/resources/callrecords-smslogrow.md
Labels: external

#20345 Change author names to github alias
  api-reference/beta/api/accesspackagecatalog-list-customaccesspackageworkflowextensions.md
  api-reference/beta/api/accesspackagecatalog-post-customaccesspackageworkflowextensions.md
  api-reference/beta/api/call-addlargegalleryview.md
  api-reference/beta/api/chatmessage-setreaction.md
  api-reference/beta/api/chatmessage-softdelete.md
  api-reference/beta/api/chatmessage-undosoftdelete.md
  api-reference/beta/api/chatmessage-unsetreaction.md
  api-reference/beta/api/customaccesspackageworkflowextension-delete.md
  api-reference/beta/api/customaccesspackageworkflowextension-get.md
  api-reference/beta/api/customaccesspackageworkflowextension-update.md
  api-reference/v1.0/api/call-addlargegalleryview.md
Labels: ready to merge, internal, content review complete

#20370 Add example for best practices.
  concepts/permissions-overview.md
Labels: internal

#20371 Publish permissions best practice example, and fixes to a few accumulated OPS warnings.
  api-reference/beta/api/accesspackagecatalog-list-customaccesspackageworkflowextensions.md
  api-reference/beta/api/accesspackagecatalog-post-customaccesspackageworkflowextensions.md
  api-reference/beta/api/call-addlargegalleryview.md
  api-reference/beta/api/chatmessage-setreaction.md
  api-reference/beta/api/chatmessage-softdelete.md
  api-reference/beta/api/chatmessage-undosoftdelete.md
  api-reference/beta/api/chatmessage-unsetreaction.md
  api-reference/beta/api/customaccesspackageworkflowextension-delete.md
  api-reference/beta/api/customaccesspackageworkflowextension-get.md
  api-reference/beta/api/customaccesspackageworkflowextension-update.md
  api-reference/v1.0/api/call-addlargegalleryview.md
  concepts/permissions-overview.md
Labels: do not merge, internal

#20353 Edits in PR 20052
  api-reference/beta/api/simulation-get.md
  api-reference/beta/api/simulation-update.md
  api-reference/beta/api/simulationautomation-get.md
  api-reference/beta/resources/simulationautomation.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/simulation-get.md
  api-reference/v1.0/api/simulationautomation-get.md
  api-reference/v1.0/resources/simulationautomation.md
  api-reference/v1.0/toc.yml
  concepts/whats-new-overview.md
Labels: external

#20372 Update dynamics-paymentmethods.md
  api-reference/beta/resources/dynamics-paymentmethods.md
Labels: external

#20297 Update dynamics-paymentterms-get.md
  api-reference/beta/api/dynamics-paymentterms-get.md
Labels: external

#20325 Update security-ediscoveryreviewset-get.md
  api-reference/beta/api/security-ediscoveryreviewset-get.md
Labels: external

#20326 Update security-ediscoveryreviewset-get.md
  api-reference/v1.0/api/security-ediscoveryreviewset-get.md
Labels: external

#20328 Update calendargroup-get.md
  api-reference/v1.0/api/calendargroup-get.md
Labels: external

#20329 Update calendargroup-get.md
  api-reference/beta/api/calendargroup-get.md
Labels: external

#20338 Update dynamics-item-get.md
  api-reference/beta/api/dynamics-item-get.md
Labels: external

#20354 Update attacksimulationroot-get-excludedaccounttarget.md
  api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md
Labels: external

#20355 Update attacksimulationroot-get-includedaccounttarget.md
  api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md
Labels: external

#20373 Make link relative
  api-reference/beta/api/call-addlargegalleryview.md
  api-reference/v1.0/api/call-addlargegalleryview.md
Labels: ready to merge, internal

#20352 Add ms.prod
  concepts/aad-advanced-queries.md
  concepts/filter-query-parameter.md
  concepts/query-parameters.md
  concepts/search-query-parameter.md
Labels: area: Azure AD, ready to merge, internal

#20299 Update sample keys
  api-reference/beta/api/chat-get.md
  api-reference/beta/api/educationassignment-list-submissions.md
  api-reference/beta/api/identitygovernance-workflowversion-get.md
  api-reference/beta/api/printer-delete.md
  api-reference/v1.0/api/chat-get.md
  api-reference/v1.0/api/printer-delete.md
Labels: ready to merge, internal

#19252 XTAP add allowedCloudEndpoints to v1.0
  api-reference/v1.0/api/crosstenantaccesspolicy-get.md
  api-reference/v1.0/api/crosstenantaccesspolicy-update.md
  api-reference/v1.0/resources/crosstenantaccesspolicy-overview.md
  api-reference/v1.0/resources/crosstenantaccesspolicy.md
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, ready to merge, content review complete

#19002 New Doc changes for Teams Tempates
  api-reference/beta/api/teamtemplate-list-definitions.md
  api-reference/beta/api/teamtemplatedefinition-get-teamdefinition.md
  api-reference/beta/api/teamtemplatedefinition-get.md
  api-reference/beta/api/teamwork-list-teamtemplates.md
  changelog/Microsoft.Teams.Core.json
  concepts/permissions-reference.md
Labels: ready to merge, changes requested, internal, content review in progress, invalid links

#18442 [CloudPC]guoantang/Add regionGroup into domainJoinConfiguration
  api-reference/beta/resources/cloudpcdomainjoinconfiguration.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, internal, content review complete

#20135 Added Go examples to batching topic
  concepts/sdks/batch-requests.md
Labels: ready to merge, internal

#20275 removed $count requirement from list managers
  api-reference/beta/api/user-list-manager.md
  api-reference/v1.0/api/user-list-manager.md
Labels: ready to merge, internal, content review complete, area: query parameters

#20294 Update author for callRecords and disable Try It feature on snippets
  api-reference/beta/api/callrecords-callrecord-get.md
  api-reference/v1.0/api/callrecords-callrecord-get.md
Labels: ready to merge, internal, area: cloud communications, content review complete

#19632 Documentation and change logs for pronouns settings
  api-reference/beta/api/organizationsettings-list-pronounssettings.md
  api-reference/beta/api/pronounssettings-update.md
  api-reference/beta/resources/organizationsettings.md
  api-reference/beta/resources/pronounssettings.md
  api-reference/beta/toc.yml
  changelog/Microsoft.People.json
  concepts/pronouns-configure-pronouns-availability.md
  concepts/toc.yml
Labels: ready to merge, internal, content review complete, schema live

#20011 Removing ChannelMessage.ReadWrite.All permission and add a note for $top query expectation
  api-reference/beta/api/chat-list.md
  api-reference/beta/api/chatmessage-post-replies.md
  api-reference/beta/api/chatmessage-post.md
  api-reference/beta/api/chatmessage-update.md
  api-reference/v1.0/api/chat-list.md
  api-reference/v1.0/api/chatmessage-post-replies.md
  api-reference/v1.0/api/chatmessage-post.md
  api-reference/v1.0/api/chatmessage-update.md
  changelog/Microsoft.Teams.Core.json
Labels: ready to merge, internal, content review complete

#20075 Add snapshotType, expirationDatetime to snapshot entity
  api-reference/beta/resources/cloudpcsnapshot.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, internal, content review in progress, review feedback addressed

#20143 02 06 2023 ship search all and teams message to v1 dot0
  api-reference/v1.0/api/search-query.md
  api-reference/v1.0/resources/enums.md
  api-reference/v1.0/resources/search-api-overview.md
  api-reference/v1.0/resources/searchrequest.md
  api-reference/v1.0/resources/sharepointonedriveoptions.md
  changelog/Microsoft.Search.json
Labels: ready to merge, internal, content review complete

#20032 Bringing changes back from other broken branch
  concepts/metered-api-list.md
  concepts/metered-api-overview.md
  concepts/metered-api-setup.md
  concepts/overview.md
Labels: do not merge, ready to merge, internal

#18602 Proposed template updates
  api-reference/beta/api/channel-getallmessages.md
  api-reference/beta/api/chats-getallmessages.md
  api-reference/beta/api/driveitem-assignsensitivitylabel.md
  api-reference/includes/teams-metered-apis.md
  api-reference/includes/teams-model-A-only-disclaimer.md
  api-reference/includes/teams-subscription-notes.md
  api-reference/v1.0/api/channel-getallmessages.md
  api-reference/v1.0/api/chats-getallmessages.md
  concepts/images/teams-export-csv-sample.png
  concepts/images/teams-user-activity-report-sample.png
  concepts/teams-licenses.md
  concepts/toc.yml
Labels: ready to merge, internal

#20386 Edits in PR 20052
  api-reference/beta/api/attacksimulationoperation-get.md
  api-reference/beta/api/payload-list.md
  api-reference/beta/api/payloaddetail-get.md
Labels: external
