Repository microsoftgraph/microsoft-graph-docs, pull requests merged in 2023-08, with the labels that each got.

#22280 Update securityactions-list.md
  api-reference/beta/api/securityactions-list.md
Labels: external

#22281 Update securityaction-cancelsecurityaction.md
  api-reference/beta/api/securityaction-cancelsecurityaction.md
Labels: external

#22287 Edits in PR 21920
  api-reference/beta/api/peopleadminsettings-post-profilecardproperties.md
  api-reference/beta/resources/peopleadminsettings.md
  api-reference/beta/resources/profilecardproperty.md
  changelog/Microsoft.People.json
  redirects/.openpublishing.redirection.0723.json
Labels: external

#21512 Add deprecation notification for externalitem legacy
  api-reference/beta/resources/search-api-overview.md
  concepts/search-concept-custom-types.md
  concepts/search-concept-display-layout.md
  concepts/search-concept-interleaving.md
Labels: ready to merge, internal, content review complete

#21823 [CloudPC] Added GetInaccessibleCloudPcReports API.
  api-reference/beta/api/cloudpcreports-getinaccessiblecloudpcreports.md
  api-reference/beta/resources/cloudpcreports.md
  api-reference/beta/toc.yml
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, content review complete, schema live

#21270 [CloudPC] Add property resetEnabled into CloudPCUserSetting
  api-reference/beta/api/cloudpcusersetting-get.md
  api-reference/beta/api/cloudpcusersetting-update.md
  api-reference/beta/resources/cloudpcusersetting.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: do not merge, ready to merge, internal, content review complete, schema live

#22030 [Doc Improvement][Swap shift response code update][3140613]
  api-reference/beta/api/swapshiftschangerequest-approve.md
  api-reference/v1.0/api/swapshiftschangerequest-approve.md
Labels: do not merge, internal, content review complete

#22309 Removed links to Partners page.
  api-reference/beta/resources/azure-ad-overview.md
  api-reference/beta/resources/booking-api-overview.md
  api-reference/beta/resources/browser-edge-api-overview.md
  api-reference/beta/resources/businessscenario-overview.md
  api-reference/beta/resources/mail-api-overview.md
  api-reference/beta/resources/report.md
  api-reference/beta/resources/security-api-overview.md
  api-reference/beta/resources/service-communications-api-overview.md
  api-reference/v1.0/resources/azure-ad-overview.md
  api-reference/v1.0/resources/booking-api-overview.md
  api-reference/v1.0/resources/browser-edge-api-overview.md
  api-reference/v1.0/resources/mail-api-overview.md
  api-reference/v1.0/resources/report.md
  api-reference/v1.0/resources/security-api-overview.md
  api-reference/v1.0/resources/service-communications-api-overview.md
Labels: ready to merge, internal

#22302 Edits in PR 21920
  api-reference/beta/api/profilecardproperty-delete.md
  api-reference/beta/api/profilecardproperty-update.md
  api-reference/beta/resources/peopleadminsettings.md
  api-reference/beta/resources/profilecardproperty.md
  api-reference/beta/toc.yml
Labels: external

#22303 Edits in PR 21988
  api-reference/beta/resources/windowsupdates-featureupdatecatalogentry.md
  api-reference/beta/resources/windowsupdates-productrevision.md
  changelog/Microsoft.WindowsUpdates.json
Labels: external

#21358 [Doc Improvement][Protected API update][3003689]
  concepts/teams-licenses.md
Labels: do not merge, ready to merge, internal, content review complete

#20881 Update teams-licenses to show model breakdown
  api-reference/includes/teams-subscription-notes.md
  concepts/teams-licenses.md
Labels: ready to merge, internal, content review complete

#21473 [Doc Improvement][Change notification for transcript using graph API][3099832]
  api-reference/beta/api/subscription-delete.md
  api-reference/beta/api/subscription-get.md
  api-reference/beta/api/subscription-list.md
  api-reference/beta/api/subscription-post-subscriptions.md
  api-reference/beta/api/subscription-reauthorize.md
  api-reference/beta/api/subscription-update.md
  api-reference/beta/resources/webhooks.md
  changelog/Microsoft.SubscriptionServices.json
  concepts/includes/change-notifications-delivery-latency.md
  concepts/includes/change-notifications-rich-notifications-supported-resources.md
  concepts/includes/change-notifications-subscription-lifetime.md
  concepts/includes/change-notifications-supported-resources-expanded.md
  concepts/includes/change-notifications-supported-resources-flat.md
  concepts/teams-change-notification-in-microsoft-teams-overview.md
  concepts/teams-changenotifications-callrecording-and-calltranscript.md
  concepts/toc.yml
Labels: ready to merge, internal, content review complete

#22066 [Doc Improvement][Added note for metered API][3140610]
  api-reference/beta/api/channel-patch.md
  api-reference/beta/api/chat-patch.md
  api-reference/v1.0/api/channel-patch.md
  api-reference/v1.0/api/chat-patch.md
Labels: do not merge, ready to merge, internal, content review complete

#22069 [Doc Improvement][SortOrderIndex property removed][3140610]
  api-reference/beta/api/channel-get-tabs.md
  api-reference/v1.0/api/channel-get-tabs.md
Labels: do not merge, ready to merge, internal, content review complete

#20877 Update session page details and revise more doc ownership
  api-reference/beta/api/callrecords-callrecord-get.md
  api-reference/beta/api/callrecords-session-list.md
  api-reference/beta/resources/callrecords-clientuseragent.md
  api-reference/beta/resources/callrecords-deviceinfo.md
  api-reference/beta/resources/callrecords-directroutinglogrow.md
  api-reference/beta/resources/callrecords-endpoint.md
  api-reference/beta/resources/callrecords-failureinfo.md
  api-reference/beta/resources/callrecords-feedbacktokenset.md
  api-reference/beta/resources/callrecords-media.md
  api-reference/beta/resources/callrecords-mediastream.md
  api-reference/beta/resources/callrecords-networkinfo.md
  api-reference/beta/resources/callrecords-participantendpoint.md
  api-reference/beta/resources/callrecords-pstncalllogrow.md
  api-reference/beta/resources/callrecords-segment.md
  api-reference/beta/resources/callrecords-serviceendpoint.md
  api-reference/beta/resources/callrecords-serviceuseragent.md
  api-reference/beta/resources/callrecords-session.md
  api-reference/beta/resources/callrecords-traceroutehop.md
  api-reference/beta/resources/callrecords-useragent.md
  api-reference/beta/resources/callrecords-userfeedback.md
  api-reference/v1.0/api/callrecords-callrecord-get.md
  api-reference/v1.0/api/callrecords-session-list.md
  api-reference/v1.0/resources/callrecords-clientuseragent.md
  api-reference/v1.0/resources/callrecords-deviceinfo.md
  api-reference/v1.0/resources/callrecords-directroutinglogrow.md
  api-reference/v1.0/resources/callrecords-endpoint.md
  api-reference/v1.0/resources/callrecords-failureinfo.md
  api-reference/v1.0/resources/callrecords-feedbacktokenset.md
  api-reference/v1.0/resources/callrecords-media.md
  api-reference/v1.0/resources/callrecords-mediastream.md
  api-reference/v1.0/resources/callrecords-networkinfo.md
  api-reference/v1.0/resources/callrecords-participantendpoint.md
  api-reference/v1.0/resources/callrecords-pstncalllogrow.md
  api-reference/v1.0/resources/callrecords-segment.md
  api-reference/v1.0/resources/callrecords-serviceendpoint.md
  api-reference/v1.0/resources/callrecords-serviceuseragent.md
  api-reference/v1.0/resources/callrecords-session.md
  api-reference/v1.0/resources/callrecords-traceroutehop.md
  api-reference/v1.0/resources/callrecords-useragent.md
  api-reference/v1.0/resources/callrecords-userfeedback.md
  changelog/Microsoft.IC3.DataPlatform.json
Labels: ready to merge, internal, area: cloud communications, content review complete

#22163 add chat history flag to onlinemeeting V1
  api-reference/v1.0/resources/onlinemeeting.md
  changelog/Microsoft.Skype.Calling.json
Labels: ready to merge, internal

#22164 Add allowParticipantsToChangeName V1
  api-reference/v1.0/resources/onlinemeeting.md
  changelog/Microsoft.Skype.Calling.json
Labels: ready to merge, internal

#22333 Update plannerbuckettaskboardtaskformat-update.md
  api-reference/beta/api/plannerbuckettaskboardtaskformat-update.md
Labels: external

#22332 Update plannerbuckettaskboardtaskformat-update.md
  api-reference/v1.0/api/plannerbuckettaskboardtaskformat-update.md
Labels: external

#22330 Edits in PR 21988
  api-reference/beta/api/windowsupdates-catalog-list-entries.md
  concepts/windowsupdates-deploy-expedited-update.md
Labels: external

#22315 Edits in PR 21559
  api-reference/beta/api/teamsappsettings-update.md
  api-reference/beta/api/user-list-permissiongrants.md
  api-reference/beta/api/userteamwork-post-installedapps.md
  api-reference/beta/api/userteamwork-teamsappinstallation-upgrade.md
  api-reference/v1.0/api/userteamwork-post-installedapps.md
  api-reference/v1.0/api/userteamwork-teamsappinstallation-upgrade.md
  changelog/Microsoft.Teams.Core.json
Labels: external

#22099 Enable rsc installation in app context for teams scope
  api-reference/beta/api/team-post-installedapps.md
  api-reference/beta/api/team-teamsappinstallation-upgrade.md
Labels: do not merge, ready to merge, internal, content review complete, schema live

#22307 Docs update for enabling Private/shared channel change notifications in v1.0
  concepts/teams-changenotifications-team-and-channel.md
  concepts/teams-changenotifications-teammembership.md
Labels: ready to merge, internal, content review complete

#22316 Added new dataset entry for ConferenceRoomCalendar
  concepts/data-connect-datasets.md
Labels: external, ready to merge

#21631 Issue #21272 fix and updating workflow to include access assignment.
  api-reference/beta/resources/delegatedadminrelationships-api-overview.md
  api-reference/v1.0/resources/delegatedadminrelationships-api-overview.md
Labels: ready to merge, changes requested, internal, content review complete

#21642 Added cloudPcFrontlineInsufficientLicensesScenario in alertRuleTemplate values
  api-reference/beta/resources/devicemanagement-alertimpact.md
  api-reference/beta/resources/devicemanagement-alertrecord.md
  changelog/Microsoft.DeviceManagement.Monitoring.json
Labels: ready to merge, internal, content review complete

#22342 Merge to publish
  .openpublishing.publish.config.json
Labels: internal

#21730 Support MDC related entities
  api-reference/beta/resources/security-alertevidence.md
  api-reference/beta/resources/security-blobcontainerevidence.md
  api-reference/beta/resources/security-blobevidence.md
  api-reference/beta/resources/security-containerevidence.md
  api-reference/beta/resources/security-containerimageevidence.md
  api-reference/beta/resources/security-containerregistryevidence.md
  api-reference/beta/resources/security-dictionary.md
  api-reference/beta/resources/security-filehash.md
  api-reference/beta/resources/security-kubernetesclusterevidence.md
  api-reference/beta/resources/security-kubernetescontrollerevidence.md
  api-reference/beta/resources/security-kubernetesnamespaceevidence.md
  api-reference/beta/resources/security-kubernetespodevidence.md
  api-reference/beta/resources/security-kubernetessecretevidence.md
  api-reference/beta/resources/security-kubernetesserviceaccountevidence.md
  api-reference/beta/resources/security-kubernetesserviceevidence.md
  api-reference/beta/resources/security-kubernetesserviceport.md
  api-reference/beta/toc.yml
  api-reference/v1.0/resources/security-alertevidence.md
  api-reference/v1.0/resources/security-blobcontainerevidence.md
  api-reference/v1.0/resources/security-blobevidence.md
  api-reference/v1.0/resources/security-containerevidence.md
  api-reference/v1.0/resources/security-containerimageevidence.md
  api-reference/v1.0/resources/security-containerregistryevidence.md
  api-reference/v1.0/resources/security-dictionary.md
  api-reference/v1.0/resources/security-filehash.md
  api-reference/v1.0/resources/security-kubernetesclusterevidence.md
  api-reference/v1.0/resources/security-kubernetescontrollerevidence.md
  api-reference/v1.0/resources/security-kubernetesnamespaceevidence.md
  api-reference/v1.0/resources/security-kubernetespodevidence.md
  api-reference/v1.0/resources/security-kubernetessecretevidence.md
  api-reference/v1.0/resources/security-kubernetesserviceaccountevidence.md
  api-reference/v1.0/resources/security-kubernetesserviceevidence.md
  api-reference/v1.0/resources/security-kubernetesserviceport.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.M365.Defender.json
Labels: ready to merge, internal, content review complete

#21831 [Doc Improvement][Response code update][3140605]
  api-reference/beta/api/appcatalogs-list-teamsapps.md
  api-reference/v1.0/api/appcatalogs-list-teamsapps.md
Labels: ready to merge, internal, content review complete

#22024 [Doc Improvement][Update open shift response code][3140613]
  api-reference/v1.0/api/openshift-update.md
Labels: ready to merge, internal, content review complete

#22250 adding new updates to Getting Started
  concepts/data-connect-quickstart.yml
  concepts/images/data-connect-new-consent-flow-enable-mgdc.png
  concepts/images/data-connect-overview-flowchart.png
  includes/data-connect-quickstart-01.md
  includes/data-connect-quickstart-02.md
  includes/data-connect-quickstart-03.md
  includes/data-connect-quickstart-04.md
  includes/data-connect-quickstart-05.md
  includes/data-connect-quickstart-06.md
  includes/data-connect-quickstart-07.md
  includes/data-connect-quickstart-08.md
Labels: ready to merge, internal, content review complete

#22344 Minor doc updates
  api-reference/beta/api/unifiedroledefinition-assignedprincipals.md
  api-reference/beta/resources/credential.md
  api-reference/beta/resources/passwordsinglesignoncredentialset.md
  changelog/Microsoft.DirectoryServices.json
  concepts/extensibility-overview.md
Labels: area: Entra, ready to merge, internal

#22294 New Update PowerBI tutorial PR.
  concepts/data-connect-quickstart.yml
  concepts/images/data-connect-pbi-add-blob-account-name.png
  concepts/images/data-connect-pbi-apply-changes.png
  concepts/images/data-connect-pbi-connect-blob-storage.png
  concepts/images/data-connect-pbi-display-columns-data.png
  concepts/images/data-connect-pbi-expand-columns-close.png
  concepts/images/data-connect-pbi-expand-columns.png
  concepts/images/data-connect-pbi-expand-query.png
  concepts/images/data-connect-pbi-expand-records.png
  concepts/images/data-connect-pbi-key-influencers.png
  concepts/images/data-connect-pbi-transform-binary.png
  concepts/images/data-connect-pbi-transform-columns.png
  concepts/images/data-connect-storageaccountcompletion.png
  includes/data-connect-quickstart-07.md
  includes/data-connect-quickstart-08.md
Labels: ready to merge, internal, content review complete

#22366 Revert "New Update PowerBI tutorial PR."
  concepts/data-connect-quickstart.yml
  concepts/images/data-connect-pbi-add-blob-account-name.png
  concepts/images/data-connect-pbi-apply-changes.png
  concepts/images/data-connect-pbi-connect-blob-storage.png
  concepts/images/data-connect-pbi-display-columns-data.png
  concepts/images/data-connect-pbi-expand-columns-close.png
  concepts/images/data-connect-pbi-expand-columns.png
  concepts/images/data-connect-pbi-expand-query.png
  concepts/images/data-connect-pbi-expand-records.png
  concepts/images/data-connect-pbi-key-influencers.png
  concepts/images/data-connect-pbi-transform-binary.png
  concepts/images/data-connect-pbi-transform-columns.png
  concepts/images/data-connect-storageaccountcompletion.png
  includes/data-connect-quickstart-07.md
  includes/data-connect-quickstart-08.md
Labels: do not merge, internal

#22160 Update data-connect-relationship-mesh-template.md
  concepts/data-connect-relationship-mesh-template.md
  concepts/data-connect-skills-finder-template.md
Labels: external, ready to merge, changes requested, content review in progress

#22337 Adds application only permissions for onPremisesDirectorySynchronization resource type
  api-reference/beta/api/onpremisesdirectorysynchronization-get.md
  api-reference/beta/api/onpremisesdirectorysynchronization-update.md
  api-reference/v1.0/api/onpremisesdirectorysynchronization-get.md
  api-reference/v1.0/api/onpremisesdirectorysynchronization-update.md
  changelog/Microsoft.DirectoryServices.json
  concepts/permissions-reference.md
Labels: area: Entra, ready to merge, content review complete, area: directory management

#22161 Add mgdc templates section
  concepts/data-connect-conversation-lineage-template.md
  concepts/data-connect-information-oversharing-template.md
  concepts/data-connect-organizational-network-template.md
  concepts/data-connect-relationship-mesh-template.md
  concepts/data-connect-skills-finder-template.md
  concepts/data-connect-templates-overview.md
  concepts/toc.yml
Labels: external, ready to merge, changes requested, content review in progress

#22038 Add Host Pairs
  api-reference/beta/api/security-host-list-childhostpairs.md
  api-reference/beta/api/security-host-list-hostpairs.md
  api-reference/beta/api/security-host-list-parenthostpairs.md
  api-reference/beta/api/security-hostpair-get.md
  api-reference/beta/resources/security-host.md
  api-reference/beta/resources/security-hostpair.md
  api-reference/beta/resources/security-threatintelligence.md
  api-reference/beta/toc.yml
  changelog/Microsoft.ThreatIntelligence.json
Labels: ready to merge, internal, content review complete, review feedback addressed

#22367 Revert "adding new updates to Getting Started"
  concepts/data-connect-quickstart.yml
  concepts/images/data-connect-new-consent-flow-enable-mgdc.png
  concepts/images/data-connect-overview-flowchart.png
  includes/data-connect-quickstart-01.md
  includes/data-connect-quickstart-02.md
  includes/data-connect-quickstart-03.md
  includes/data-connect-quickstart-04.md
  includes/data-connect-quickstart-05.md
  includes/data-connect-quickstart-06.md
  includes/data-connect-quickstart-07.md
  includes/data-connect-quickstart-10.md
Labels: ready to merge, internal

#22384 Update .openpublishing.publish.config.json
  .openpublishing.publish.config.json
Labels: internal

#21637 Update authentication-update.md
  api-reference/beta/api/authentication-update.md
Labels: external

#22171 Update basesitepage-list.md
  api-reference/beta/api/basesitepage-list.md
Labels: external

#22365 Edits in PR 20973
  api-reference/beta/api/attacksimulationroot-list-endusernotifications.md
  api-reference/beta/api/attacksimulationroot-list-landingpage.md
  api-reference/beta/api/attacksimulationroot-list-loginpage.md
  api-reference/beta/api/attacksimulationroot-list-payloads.md
  api-reference/beta/api/attacksimulationroot-list-trainings.md
  api-reference/beta/api/attacksimulationroot-post-simulation.md
  api-reference/beta/api/endusernotification-get.md
  api-reference/beta/api/endusernotificationdetail-get.md
  api-reference/beta/api/landingpage-get.md
  api-reference/beta/api/landingpage-list-details.md
  api-reference/beta/api/landingpagedetail-get.md
  api-reference/beta/api/loginpage-get.md
  api-reference/beta/api/payload-get.md
  api-reference/beta/api/payloaddetail-get.md
  api-reference/beta/api/traininglanguagedetail-get.md
  api-reference/beta/resources/baseendusernotification.md
  api-reference/beta/resources/customtrainingsetting.md
  api-reference/beta/resources/endusernotification.md
  api-reference/beta/resources/endusernotificationdetail.md
  api-reference/beta/resources/endusernotificationsetting.md
  api-reference/beta/resources/landingpagedetail.md
  api-reference/beta/resources/loginpage.md
  api-reference/beta/resources/microsoftcustomtrainingsetting.md
  api-reference/beta/resources/microsoftmanagedtrainingsetting.md
  api-reference/beta/resources/microsofttrainingassignmentmapping.md
  api-reference/beta/resources/notrainingnotificationsetting.md
  api-reference/beta/resources/oauthconsentappdetail.md
  api-reference/beta/resources/positivereinforcementnotification.md
  api-reference/beta/resources/simulation.md
  api-reference/beta/resources/simulationnotification.md
  api-reference/beta/resources/training.md
  api-reference/beta/resources/traininglanguagedetail.md
  api-reference/beta/resources/trainingnotificationsetting.md
  api-reference/beta/resources/trainingremindernotification.md
  api-reference/beta/resources/trainingsetting.md
  changelog/Microsoft.Security.AttackSimulation.json
Labels: external

#22373 Update educationclass-delete-teachers.md
  api-reference/beta/api/educationclass-delete-teachers.md
Labels: external

#21607 Small tweak to set expectations for when call records will be available
  concepts/includes/change-notifications-supported-resources-expanded.md
Labels: area: Entra, ready to merge, internal, content review complete, area: change notifications

#21772 Adjusting for customer flow if they land on API page first
  api-reference/v1.0/resources/webhooks.md
Labels: area: Entra, ready to merge, content review complete, area: change notifications

#21774 Small change to describe the JWT acronym
  concepts/webhooks-with-resource-data.md
Labels: area: Entra, ready to merge, internal, content review complete, area: change notifications

#21984 Update driveitem-assignsensitivitylabel.md
  api-reference/v1.0/api/driveitem-assignsensitivitylabel.md
Labels: external, ready to merge

#21997 [Doc Feature][Call recording API][3099832]
  api-reference/beta/api/callrecording-get.md
  api-reference/beta/api/calltranscript-get.md
  api-reference/beta/api/onlinemeeting-list-recordings.md
  api-reference/beta/api/onlinemeeting-list-transcripts.md
  api-reference/beta/resources/callrecording.md
  api-reference/beta/resources/onlinemeeting.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Skype.Calling.json
  changelog/Microsoft.Teams.GraphSvc.json
  concepts/permissions-reference.md
  concepts/teams-licenses.md
  concepts/teamwork-national-cloud-differences.md
Labels: do not merge, ready to merge, internal, content review complete

#22011 Update change-notifications-delivery-webhooks.md
  concepts/change-notifications-delivery-webhooks.md
  concepts/webhooks-lifecycle.md
Labels: area: Entra, ready to merge, content review complete, area: change notifications

#22014 Update customextensionclientconfiguration.md
  api-reference/beta/resources/customextensionclientconfiguration.md
Labels: area: Entra, ready to merge, internal, content review complete

#22166 Update security-security-runhuntingquery.md
  api-reference/beta/api/security-security-runhuntingquery.md
  api-reference/v1.0/api/security-security-runhuntingquery.md
Labels: external, ready to merge

#22359 Moved limitations note to bottom of table for better readability.
  concepts/includes/change-notifications-supported-resources-expanded.md
Labels: area: Entra, ready to merge, content review complete, area: change notifications

#22361 Reorganized for better readability
  concepts/webhooks.md
Labels: area: Entra, ready to merge, content review complete, area: change notifications

#22372 Edits in PR 21208
  concepts/teams-changenotifications-callrecording-and-calltranscript.md
  concepts/toc.yml
Labels: external, ready to merge

#22385 Update change-notifications-subscription-lifetime.md
  concepts/includes/change-notifications-subscription-lifetime.md
Labels: ready to merge, internal

#22081 Oved haruvi add properties to alert evidence
  api-reference/beta/api/security-alert-get.md
  api-reference/beta/api/security-list-alerts_v2.md
  api-reference/beta/api/security-list-incidents.md
  api-reference/beta/resources/security-alertevidence.md
  api-reference/beta/resources/security-deviceevidence.md
  api-reference/beta/resources/security-registryvalueevidence.md
  api-reference/v1.0/api/security-alert-get.md
  api-reference/v1.0/api/security-list-alerts_v2.md
  api-reference/v1.0/api/security-list-incidents.md
  api-reference/v1.0/resources/security-alertevidence.md
  api-reference/v1.0/resources/security-deviceevidence.md
  api-reference/v1.0/resources/security-registryvalueevidence.md
  changelog/Microsoft.M365.Defender.json
Labels: ready to merge, content review complete

#22360 General cleanup
  api-reference/beta/resources/webhooks.md
  api-reference/v1.0/resources/webhooks.md
Labels: area: Entra, ready to merge, internal, content review complete

#22362 Small tweaks for readability as part of the webhooks documentation flow
  concepts/includes/change-notifications-delivery-notificationurl-validation.md
Labels: area: Entra, ready to merge, content review complete, area: change notifications

#22371 Edits in PR 22185
  api-reference/beta/api/virtualeventsession-get.md
  api-reference/beta/api/virtualeventsession-list.md
  api-reference/beta/resources/virtualeventsession.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Skype.Calling.json
Labels: external, ready to merge

#22395 Merge to publish.
  .openpublishing.publish.config.json
  api-reference/beta/api/authentication-update.md
  api-reference/beta/api/basesitepage-list.md
  api-reference/beta/api/callrecording-get.md
  api-reference/beta/api/calltranscript-get.md
  api-reference/beta/api/educationclass-delete-teachers.md
  api-reference/beta/api/onlinemeeting-list-recordings.md
  api-reference/beta/api/onlinemeeting-list-transcripts.md
  api-reference/beta/api/security-alert-get.md
  api-reference/beta/api/security-list-alerts_v2.md
  api-reference/beta/api/security-list-incidents.md
  api-reference/beta/api/security-security-runhuntingquery.md
  api-reference/beta/resources/callrecording.md
  api-reference/beta/resources/customextensionclientconfiguration.md
  api-reference/beta/resources/onlinemeeting.md
  api-reference/beta/resources/security-alertevidence.md
  api-reference/beta/resources/security-deviceevidence.md
  api-reference/beta/resources/security-registryvalueevidence.md
  api-reference/beta/resources/webhooks.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/driveitem-assignsensitivitylabel.md
  api-reference/v1.0/api/security-alert-get.md
  api-reference/v1.0/api/security-list-alerts_v2.md
  api-reference/v1.0/api/security-list-incidents.md
  api-reference/v1.0/api/security-security-runhuntingquery.md
  api-reference/v1.0/resources/security-alertevidence.md
  api-reference/v1.0/resources/security-deviceevidence.md
  api-reference/v1.0/resources/security-registryvalueevidence.md
  api-reference/v1.0/resources/webhooks.md
  changelog/Microsoft.M365.Defender.json
  changelog/Microsoft.Skype.Calling.json
  changelog/Microsoft.Teams.GraphSvc.json
  concepts/change-notifications-delivery-webhooks.md
  concepts/includes/change-notifications-delivery-notificationurl-validation.md
  concepts/includes/change-notifications-subscription-lifetime.md
  concepts/includes/change-notifications-supported-resources-expanded.md
  concepts/permissions-reference.md
  concepts/teams-licenses.md
  concepts/teamwork-national-cloud-differences.md
  concepts/webhooks-lifecycle.md
  concepts/webhooks-with-resource-data.md
  concepts/webhooks.md
Labels: do not merge, internal
