Repository microsoftgraph/microsoft-graph-docs, pull requests merged in 2023-06, with the labels that each got.

#21173 Closing out doc changes for Sync APIs
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/keyvaluepair.md
  api-reference/beta/resources/synchronization-attributedefinition.md
  api-reference/beta/resources/synchronization-attributedefinitionmetadataentry.md
  api-reference/beta/resources/synchronization-metadataentry.md
  api-reference/beta/resources/synchronization-objectdefinition.md
  api-reference/beta/resources/synchronization-objectdefinitionmetadataentry.md
  api-reference/beta/resources/synchronization-objectmapping.md
  api-reference/beta/resources/synchronization-objectmappingmetadataentry.md
  api-reference/beta/resources/synchronization-synchronizationjobrestartcriteria.md
  api-reference/beta/resources/synchronization-synchronizationmetadataentry.md
  api-reference/beta/resources/synchronization-synchronizationtemplate.md
  changelog/Microsoft.IAM.json
Labels: area: Azure AD, ready to merge, internal, content review complete

#20675 [CloudPC] Rename hibernated to standbyMode in ShiftWorkCloudPcAccessState.
  api-reference/beta/api/cloudpc-getshiftworkcloudpcaccessstate.md
  api-reference/beta/resources/cloudpc.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, internal, content review complete

#21383 Fix typo in audioCodec enum
  api-reference/beta/resources/callrecords-mediastream.md
  api-reference/v1.0/resources/callrecords-mediastream.md
Labels: ready to merge, internal, area: cloud communications, content review complete

#21420 Add search with application permission redirect link to application permission.
  concepts/search-concept-overview.md
Labels: ready to merge, internal, content review complete

#21325 Add Approval API docs for PAG
  api-reference/beta/api/approval-get.md
  api-reference/beta/api/approval-list-steps.md
  api-reference/beta/api/approvalstep-get.md
  api-reference/beta/api/approvalstep-update.md
  api-reference/beta/resources/approval.md
  api-reference/beta/resources/approvalstep.md
  api-reference/beta/resources/privilegedidentitymanagement-for-groups-api-overview.md
  api-reference/beta/toc.yml
Labels: area: Azure AD, ready to merge, internal, content review complete

#21477 Rule evaluation case-sensitive.
  api-reference/beta/resources/identitygovernance-rulebasedsubjectset.md
Labels: ready to merge, internal

#21490 Fix #21470
  api-reference/beta/api/user-update.md
  api-reference/v1.0/api/user-update.md
Labels: area: Azure AD, area: users, ready to merge, area: permissions

#21495 Add note concerning wildcard query to search for sites
  api-reference/beta/api/site-search.md
  api-reference/v1.0/api/site-search.md
Labels: external, ready to merge

#21414 Expose preferredDisplayName property in participant.
  api-reference/beta/resources/participant.md
  changelog/Microsoft.Skype.Calling.json
Labels: ready to merge, content review complete

#21508 Update projectrome-put-historyitem.md
  api-reference/beta/api/projectrome-put-historyitem.md
Labels: external

#21507 Update projectrome-put-historyitem.md
  api-reference/v1.0/api/projectrome-put-historyitem.md
Labels: external

#21506 Update known-issues.md
  concepts/known-issues.md
Labels: external

#21505 Update taskfileattachment-get.md
  api-reference/beta/api/taskfileattachment-get.md
Labels: external

#21504 Update taskfileattachment-get.md
  api-reference/v1.0/api/taskfileattachment-get.md
Labels: external

#20438 Assignment and submission state transition
  concepts/assignments-states-transition.md
  concepts/assignments-submissions-states-transition.md
  concepts/images/states-transitions/diagram-assignments.PNG
  concepts/images/states-transitions/diagram-submissions.PNG
  concepts/submissions-states-transition.md
  concepts/toc.yml
Labels: ready to merge, internal, content review complete

#21482 Fix doc bug #17962
  concepts/webhooks-with-resource-data.md
Labels: do not merge, ready to merge, internal, content review complete

#21484 Clarifying that DQ can only filter by Object ID
  concepts/delta-query-overview.md
Labels: do not merge, ready to merge, internal, content review complete

#21502 Revert "Expose preferredDisplayName property in participant."
  api-reference/beta/resources/participant.md
  changelog/Microsoft.Skype.Calling.json
Labels: ready to merge, review requested

#21168 add loopPage and project to plannerPlanContextType
  api-reference/beta/resources/plannerplancontextdetails.md
  changelog/Microsoft.Office.Tasks.json
Labels: ready to merge, internal

#21186 Docs update for enabling Private/shared channel change notifications
  concepts/teams-changenotifications-team-and-channel.md
  concepts/teams-changenotifications-teamMembership.md
Labels: ready to merge, internal, content review complete

#21315 Support MDC workload
  api-reference/beta/resources/security-alert.md
  api-reference/beta/resources/security-alertevidence.md
  api-reference/beta/resources/security-amazonresourceevidence.md
  api-reference/beta/resources/security-azureresourceevidence.md
  api-reference/beta/resources/security-googlecloudresourceevidence.md
  api-reference/beta/toc.yml
  api-reference/v1.0/resources/security-alert.md
  api-reference/v1.0/resources/security-alertevidence.md
  api-reference/v1.0/resources/security-amazonresourceevidence.md
  api-reference/v1.0/resources/security-azureresourceevidence.md
  api-reference/v1.0/resources/security-googlecloudresourceevidence.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.M365.Defender.json
Labels: ready to merge, internal, content review complete, schema live

#21311 Remove deprecated submission state
  api-reference/beta/api/educationsubmittedsubmissionresource-get.md
  api-reference/beta/resources/educationsubmission.md
  api-reference/beta/resources/enums.md
  api-reference/v1.0/api/educationsubmittedsubmissionresource-get.md
  api-reference/v1.0/resources/educationsubmission.md
  api-reference/v1.0/resources/enums.md
  changelog/Microsoft.EducationAssignment.json
Labels: ready to merge, internal, content review complete

#21511 Merge to publish.
  api-reference/beta/api/educationsubmittedsubmissionresource-get.md
  api-reference/beta/api/projectrome-put-historyitem.md
  api-reference/beta/api/taskfileattachment-get.md
  api-reference/beta/resources/educationsubmission.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/participant.md
  api-reference/beta/resources/plannerplancontextdetails.md
  api-reference/beta/resources/security-alert.md
  api-reference/beta/resources/security-alertevidence.md
  api-reference/beta/resources/security-amazonresourceevidence.md
  api-reference/beta/resources/security-azureresourceevidence.md
  api-reference/beta/resources/security-googlecloudresourceevidence.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/educationsubmittedsubmissionresource-get.md
  api-reference/v1.0/api/projectrome-put-historyitem.md
  api-reference/v1.0/api/taskfileattachment-get.md
  api-reference/v1.0/resources/educationsubmission.md
  api-reference/v1.0/resources/enums.md
  api-reference/v1.0/resources/security-alert.md
  api-reference/v1.0/resources/security-alertevidence.md
  api-reference/v1.0/resources/security-amazonresourceevidence.md
  api-reference/v1.0/resources/security-azureresourceevidence.md
  api-reference/v1.0/resources/security-googlecloudresourceevidence.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.EducationAssignment.json
  changelog/Microsoft.M365.Defender.json
  changelog/Microsoft.Office.Tasks.json
  changelog/Microsoft.Skype.Calling.json
  concepts/assignments-states-transition.md
  concepts/assignments-submissions-states-transition.md
  concepts/delta-query-overview.md
  concepts/images/states-transitions/diagram-assignments.PNG
  concepts/images/states-transitions/diagram-submissions.PNG
  concepts/known-issues.md
  concepts/submissions-states-transition.md
  concepts/teams-changenotifications-team-and-channel.md
  concepts/teams-changenotifications-teamMembership.md
  concepts/toc.yml
  concepts/webhooks-with-resource-data.md
Labels: internal

#21520 Update printconnector-delete.md
  api-reference/beta/api/printconnector-delete.md
Labels: external

#21519 Update printconnector-delete.md
  api-reference/v1.0/api/printconnector-delete.md
Labels: external

#21516 Update query-parameters.md
  concepts/query-parameters.md
Labels: external

#21162 release answer and collapse to v1.0
  api-reference/v1.0/resources/collapseproperty.md
  api-reference/v1.0/resources/search-api-overview.md
  api-reference/v1.0/resources/searchhit.md
  api-reference/v1.0/resources/searchrequest.md
  changelog/Microsoft.MicrosoftSearch.json
Labels: ready to merge, internal, content review complete

#21521 Merge to publish.
  api-reference/beta/api/printconnector-delete.md
  api-reference/v1.0/api/printconnector-delete.md
  api-reference/v1.0/resources/collapseproperty.md
  api-reference/v1.0/resources/search-api-overview.md
  api-reference/v1.0/resources/searchhit.md
  api-reference/v1.0/resources/searchrequest.md
  changelog/Microsoft.MicrosoftSearch.json
  concepts/query-parameters.md
Labels: internal

#21524 Edits for PR 21517
  api-reference/beta/resources/participant.md
  changelog/Microsoft.Skype.Calling.json
Labels: external

#21527 Edits for PR 21017
  changelog/Microsoft.DirectoryServices.json
Labels: external

#21531 Removed preview disclaimer for Go SDK
  concepts/sdks/batch-requests.md
  concepts/sdks/choose-authentication-providers.md
  concepts/sdks/create-requests.md
  concepts/sdks/customize-client.md
  concepts/sdks/paging.md
  concepts/sdks/sdk-installation.md
  concepts/sdks/use-beta.md
  includes/go-sdk-preview.md
Labels: ready to merge

#21537 Update participant-stopholdmusic.md
  api-reference/beta/api/participant-stopholdmusic.md
Labels: external

#21536 Update participant-stopholdmusic.md
  api-reference/v1.0/api/participant-stopholdmusic.md
Labels: external

#21526 Update participant-startholdmusic.md
  api-reference/beta/api/participant-startholdmusic.md
Labels: external

#21525 Update participant-startholdmusic.md
  api-reference/v1.0/api/participant-startholdmusic.md
Labels: external

#20726 M365d security-useraccount add display name
  api-reference/beta/api/security-alert-get.md
  api-reference/beta/api/security-list-alerts_v2.md
  api-reference/beta/resources/security-useraccount.md
  api-reference/v1.0/api/security-alert-get.md
  api-reference/v1.0/api/security-list-alerts_v2.md
  api-reference/v1.0/resources/security-useraccount.md
  changelog/Microsoft.M365.Defender.json
Labels: ready to merge, internal, content review complete

#21151 Bug fix for app mgmt policy appliesTo response
  api-reference/beta/api/appmanagementpolicy-list-appliesto.md
  api-reference/v1.0/api/appManagementPolicy-list-appliesTo.md
Labels: area: Azure AD, ready to merge, internal, content review complete

#21215 Readd reverted VE doc files
  concepts/changenotifications-for-virtualevent.md
  concepts/toc.yml
Labels: ready to merge, content review complete

#21498 Add all available retrievable properties in search for chatMessage
  concepts/search-concept-chat-messages.md
Labels: ready to merge, internal, content review complete

#21529 Update user-revokesigninsessions.md
  api-reference/v1.0/api/user-revokesigninsessions.md
Labels: ready to merge, internal

#21059 add 2 new error type for UDP connectivity
  api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: external, ready to merge, content review complete, schema live

#20889 Added documentation for virtual event (P0)
  api-reference/beta/api/attendancerecord-list.md
  api-reference/beta/api/meetingattendancereport-get.md
  api-reference/beta/api/meetingattendancereport-list.md
  api-reference/beta/api/virtualeventregistrant-get.md
  api-reference/beta/api/virtualeventsession-get.md
  api-reference/beta/api/virtualeventwebinar-get.md
  api-reference/beta/resources/virtualevent.md
  api-reference/beta/resources/virtualeventpresenter.md
  api-reference/beta/resources/virtualeventpresenterdetails.md
  api-reference/beta/resources/virtualeventregistrant.md
  api-reference/beta/resources/virtualeventregistration.md
  api-reference/beta/resources/virtualeventregistrationquestion.md
  api-reference/beta/resources/virtualeventregistrationquestionanswer.md
  api-reference/beta/resources/virtualeventsession.md
  api-reference/beta/resources/virtualeventwebinar.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Skype.Calling.json
  concepts/permissions-reference.md
  concepts/throttling-limits.md
Labels: ready to merge, internal, content review complete

#21057 add top parameter in list-cloudpcs
  api-reference/beta/api/virtualendpoint-list-cloudpcs.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, internal, content review complete, schema live

#21462 Update the CSS tokens used in mgt-teams-channel-picker
  concepts/toolkit/components/teams-channel-picker.md
Labels: internal, content review complete

#21264 doc bug in device registration policy
  api-reference/beta/api/deviceregistrationpolicy-get.md
  api-reference/beta/api/deviceregistrationpolicy-update.md
Labels: area: Azure AD, ready to merge, internal, content review complete

#21051 OnlineMeeting Option to Disable Recording
  api-reference/beta/resources/onlinemeeting.md
  changelog/Microsoft.Skype.Calling.json
Labels: ready to merge, internal, content review complete, invalid links

#21398 update links to IT Pro content for Microsoft Entra Identity Governance
  api-reference/beta/resources/accessreviews-root.md
  api-reference/beta/resources/accessreviewsv2-overview.md
  api-reference/beta/resources/entitlementmanagement-overview.md
  api-reference/beta/resources/identitygovernance-lifecycleworkflows-overview.md
  api-reference/beta/resources/identitygovernance-lifecycleworkflows-reporting-overview.md
  api-reference/beta/resources/identitygovernance-lifecycleworkflowscontainer.md
  api-reference/beta/resources/identitygovernance-overview.md
  api-reference/beta/resources/privilegedidentitymanagementv3-overview.md
  api-reference/v1.0/resources/accessreviewsv2-overview.md
  api-reference/v1.0/resources/entitlementmanagement-overview.md
  api-reference/v1.0/resources/identitygovernance-overview.md
  api-reference/v1.0/resources/privilegedidentitymanagementv3-overview.md
Labels: area: Azure AD, ready to merge, internal, content review complete

#21509 Update authorizationpolicy-update.md with roles
  api-reference/beta/api/authorizationpolicy-update.md
  api-reference/v1.0/api/authorizationpolicy-update.md
Labels: area: Azure AD, ready to merge, internal, content review complete

#21324 add AllowTranscription to OnlineMeeting
  api-reference/beta/resources/onlinemeeting.md
Labels: ready to merge, internal, content review complete

#21541 Amended Virtual Event API Docs
  api-reference/beta/api/virtualeventregistrant-get.md
  api-reference/beta/api/virtualeventsession-get.md
  api-reference/beta/api/virtualeventwebinar-get.md
  concepts/cloud-communication-online-meeting-application-access-policy.md
Labels: ready to merge, internal, content review complete

#21575 Embed Postman video
  concepts/use-postman.md
Labels: do not merge, internal

#21553 Fix Http response code in `regionalandlanguagesettings-update.md`
  api-reference/beta/api/regionalandlanguagesettings-update.md
Labels: external, ready to merge

#21167 Synchronization API docs - Clean up JSON representation
  api-reference/beta/api/directorydefinition-discover.md
  api-reference/beta/api/synchronization-synchronization-acquireaccesstoken.md
  api-reference/beta/api/synchronization-synchronizationjob-validatecredentials.md
  api-reference/beta/api/synchronization-synchronizationschema-filteroperators.md
  api-reference/beta/api/synchronization-synchronizationschema-functions.md
  api-reference/beta/api/synchronization-synchronizationschema-get.md
  api-reference/beta/api/synchronization-synchronizationschema-parseexpression.md
  api-reference/beta/api/synchronization-synchronizationtemplate-get.md
  api-reference/beta/api/synchronization-synchronizationtemplate-list.md
  api-reference/beta/api/synchronization-synchronizationtemplate-update.md
  api-reference/beta/resources/initiator.md
  api-reference/beta/resources/provisionedidentity.md
  api-reference/beta/resources/provisioningobjectsummary.md
  api-reference/beta/resources/provisioningserviceprincipal.md
  api-reference/beta/resources/provisioningstatusinfo.md
  api-reference/beta/resources/provisioningstep.md
  api-reference/beta/resources/provisioningsystem.md
  api-reference/beta/resources/synchronization-attributedefinition.md
  api-reference/beta/resources/synchronization-attributemapping.md
  api-reference/beta/resources/synchronization-attributemappingfunctionschema.md
  api-reference/beta/resources/synchronization-attributemappingsource.md
  api-reference/beta/resources/synchronization-directorydefinition.md
  api-reference/beta/resources/synchronization-expressioninputobject.md
  api-reference/beta/resources/synchronization-filter.md
  api-reference/beta/resources/synchronization-filterclause.md
  api-reference/beta/resources/synchronization-filtergroup.md
  api-reference/beta/resources/synchronization-filteroperand.md
  api-reference/beta/resources/synchronization-filteroperatorschema.md
  api-reference/beta/resources/synchronization-objectdefinition.md
  api-reference/beta/resources/synchronization-objectmapping.md
  api-reference/beta/resources/synchronization-parseexpressionresponse.md
  api-reference/beta/resources/synchronization-referencedobject.md
  api-reference/beta/resources/synchronization-stringkeyattributemappingsourcevaluepair.md
  api-reference/beta/resources/synchronization-stringkeylongvaluepair.md
  api-reference/beta/resources/synchronization-stringkeyobjectvaluepair.md
  api-reference/beta/resources/synchronization-synchronization.md
  api-reference/beta/resources/synchronization-synchronizationerror.md
  api-reference/beta/resources/synchronization-synchronizationjob.md
  api-reference/beta/resources/synchronization-synchronizationquarantine.md
  api-reference/beta/resources/synchronization-synchronizationrule.md
  api-reference/beta/resources/synchronization-synchronizationschedule.md
  api-reference/beta/resources/synchronization-synchronizationsecretkeystringvaluepair.md
  api-reference/beta/resources/synchronization-synchronizationstatus.md
  api-reference/beta/resources/synchronization-synchronizationtaskexecution.md
  api-reference/beta/resources/synchronization-synchronizationtemplate.md
  api-reference/v1.0/api/provisioningobjectsummary-list.md
  api-reference/v1.0/resources/provisionedidentity.md
  api-reference/v1.0/resources/provisioningobjectsummary.md
  api-reference/v1.0/resources/provisioningstatusinfo.md
  api-reference/v1.0/resources/provisioningstep.md
  api-reference/v1.0/resources/provisioningsystem.md
Labels: area: Azure AD, ready to merge, internal, area: identity

#21357 Role settings management in PIM for Groups
  api-reference/beta/api/policyroot-list-rolemanagementpolicies.md
  api-reference/beta/api/policyroot-list-rolemanagementpolicyassignments.md
  api-reference/beta/api/unifiedrolemanagementpolicy-get.md
  api-reference/beta/api/unifiedrolemanagementpolicy-list-rules.md
  api-reference/beta/api/unifiedrolemanagementpolicy-update.md
  api-reference/beta/api/unifiedrolemanagementpolicyassignment-get.md
  api-reference/beta/api/unifiedrolemanagementpolicyrule-get.md
  api-reference/beta/api/unifiedrolemanagementpolicyrule-update.md
  api-reference/beta/resources/privilegedidentitymanagement-for-groups-api-overview.md
  api-reference/beta/resources/privilegedidentitymanagementv3-overview.md
  api-reference/beta/resources/unifiedrolemanagementpolicy.md
  api-reference/beta/resources/unifiedrolemanagementpolicyassignment.md
  api-reference/beta/toc.yml
  changelog/Microsoft.PIM.AzureRBAC.json
  concepts/how-to-pim-update-rules.md
  concepts/identity-governance-pim-rules-overview.md
  concepts/permissions-reference.md
  concepts/toc.yml
Labels: area: Azure AD, ready to merge, internal, content review complete

#21494 Update Identity set doc to include new properties.
  api-reference/beta/resources/identityset.md
Labels: ready to merge, internal, content review complete

#21562 Best practices: remove mention of x-ms-ags-diagnostic
  concepts/best-practices-concept.md
Labels: ready to merge, internal, content review complete

#21567 Add $search for mobilePhone
  api-reference/beta/resources/user.md
  api-reference/v1.0/resources/user.md
Labels: area: Azure AD, ready to merge

#19952 Planner task completion requirements documentation beta
  api-reference/beta/resources/plannerchecklistrequirement.md
  api-reference/beta/resources/plannertask.md
  api-reference/beta/resources/plannertaskcompletionrequirementdetails.md
  api-reference/beta/resources/plannertaskdetails.md
  api-reference/beta/resources/plannertaskpropertyrule.md
  changelog/Microsoft.Office.Tasks.json
  changelog/Microsoft.Tasks.json
  concepts/planner-task-rules-overview.md
Labels: ready to merge, content review complete

#21464 IsCourseActivitySyncEnabled for LearningProvider
  api-reference/beta/api/employeeexperience-post-learningproviders.md
  api-reference/beta/api/employeeexperienceuser-post-learningcourseactivities.md
  api-reference/beta/api/learningcourseactivity-delete.md
  api-reference/beta/api/learningcourseactivity-update.md
  api-reference/beta/api/learningprovider-update.md
  api-reference/beta/resources/learningcourseactivity.md
  api-reference/beta/resources/learningprovider.md
  api-reference/v1.0/resources/learningprovider.md
  changelog/Microsoft.Viva.Learning.json
Labels: ready to merge, internal, content review complete, review feedback addressed

#21539 Update identity-governance-pim-rules-overview.md
  concepts/identity-governance-pim-rules-overview.md
Labels: area: Azure AD, external, ready to merge, content review complete

#21590 Reassign docs
  api-reference/beta/api/subscription-delete.md
  api-reference/beta/api/subscription-get.md
  api-reference/beta/api/subscription-list.md
  api-reference/beta/api/subscription-post-subscriptions.md
  api-reference/beta/api/subscription-reauthorize.md
  api-reference/beta/api/subscription-update.md
  api-reference/beta/resources/changenotification.md
  api-reference/beta/resources/changenotificationcollection.md
  api-reference/beta/resources/changenotificationencryptedcontent.md
  api-reference/beta/resources/phone.md
  api-reference/beta/resources/privacyprofile.md
  api-reference/beta/resources/provisionedplan.md
  api-reference/beta/resources/resourcedata.md
  api-reference/beta/resources/subscription.md
  api-reference/beta/resources/verifieddomain.md
  api-reference/beta/resources/webhooks.md
  api-reference/v1.0/api/subscription-delete.md
  api-reference/v1.0/api/subscription-get.md
  api-reference/v1.0/api/subscription-list.md
  api-reference/v1.0/api/subscription-post-subscriptions.md
  api-reference/v1.0/api/subscription-reauthorize.md
  api-reference/v1.0/api/subscription-update.md
  api-reference/v1.0/resources/changenotification.md
  api-reference/v1.0/resources/changenotificationcollection.md
  api-reference/v1.0/resources/privacyprofile.md
  api-reference/v1.0/resources/provisionedplan.md
  api-reference/v1.0/resources/resourcedata.md
  api-reference/v1.0/resources/subscription.md
  api-reference/v1.0/resources/verifieddomain.md
  api-reference/v1.0/resources/webhooks.md
  concepts/change-notifications-delivery-event-hubs.md
  concepts/change-notifications-delivery-webhooks.md
  concepts/delta-query-groups.md
  concepts/delta-query-overview.md
  concepts/delta-query-users.md
  concepts/includes/change-notifications-delivery-latency.md
  concepts/includes/change-notifications-delivery-notificationurl-validation.md
  concepts/includes/change-notifications-subscription-lifetime.md
  concepts/includes/change-notifications-supported-resources-flat.md
  concepts/webhooks-lifecycle.md
  concepts/webhooks-with-resource-data.md
  concepts/webhooks.md
  includes/throttling-subscription-services.md
Labels: area: Azure AD, ready to merge, internal

#21589 Update calendar-getschedule.md
  api-reference/v1.0/api/calendar-getschedule.md
Labels: ready to merge, internal, customer support issue, content review complete

#21149 Add notice about required license to ThreatIntelligence APIs
  api-reference/beta/api/security-article-get.md
  api-reference/beta/api/security-article-list-indicators.md
  api-reference/beta/api/security-article-list.md
  api-reference/beta/api/security-articleindicator-get.md
  api-reference/beta/api/security-host-get-reputation.md
  api-reference/beta/api/security-host-get.md
  api-reference/beta/api/security-host-list-components.md
  api-reference/beta/api/security-host-list-cookies.md
  api-reference/beta/api/security-host-list-passivedns.md
  api-reference/beta/api/security-host-list-passivednsreverse.md
  api-reference/beta/api/security-host-list-trackers.md
  api-reference/beta/api/security-hostcomponent-get.md
  api-reference/beta/api/security-hostcookie-get.md
  api-reference/beta/api/security-hosttracker-get.md
  api-reference/beta/api/security-intelligenceprofile-get.md
  api-reference/beta/api/security-intelligenceprofile-list-indicators.md
  api-reference/beta/api/security-intelligenceprofile-list.md
  api-reference/beta/api/security-intelligenceprofileindicator-get.md
  api-reference/beta/api/security-passivednsrecord-get.md
  api-reference/beta/api/security-vulnerability-get.md
  api-reference/beta/api/security-vulnerability-list-components.md
  api-reference/beta/api/security-vulnerabilitycomponent-get.md
  api-reference/beta/resources/security-article.md
  api-reference/beta/resources/security-articleindicator.md
  api-reference/beta/resources/security-artifact.md
  api-reference/beta/resources/security-autonomoussystem.md
  api-reference/beta/resources/security-cvsssummary.md
  api-reference/beta/resources/security-host.md
  api-reference/beta/resources/security-hostcomponent.md
  api-reference/beta/resources/security-hostcookie.md
  api-reference/beta/resources/security-hostname.md
  api-reference/beta/resources/security-hostreputation.md
  api-reference/beta/resources/security-hostreputationrule.md
  api-reference/beta/resources/security-hosttracker.md
  api-reference/beta/resources/security-indicator.md
  api-reference/beta/resources/security-intelligenceprofile.md
  api-reference/beta/resources/security-intelligenceprofileindicator.md
  api-reference/beta/resources/security-intelligenceprofilesponsorstate.md
  api-reference/beta/resources/security-ipaddress.md
  api-reference/beta/resources/security-passivednsrecord.md
  api-reference/beta/resources/security-threatintelligence-overview.md
  api-reference/beta/resources/security-threatintelligence.md
  api-reference/beta/resources/security-unclassifiedartifact.md
  api-reference/beta/resources/security-vulnerability.md
  api-reference/beta/resources/security-vulnerabilitycomponent.md
  api-reference/includes/threatintelligence-api-disclaimer.md
Labels: ready to merge, internal, content review complete

#16295 [Azure AD roles] Restricted management administrative unit properties (Beta)
  api-reference/beta/api/administrativeunit-get.md
  api-reference/beta/api/administrativeunit-post-members.md
  api-reference/beta/api/administrativeunit-update.md
  api-reference/beta/api/directory-post-administrativeunits.md
  api-reference/beta/api/group-get.md
  api-reference/beta/api/user-list.md
  api-reference/beta/resources/administrativeunit.md
  api-reference/beta/resources/device.md
  api-reference/beta/resources/group.md
  api-reference/beta/resources/user.md
  changelog/Microsoft.DirectoryServices.json
  concepts/permissions-reference.md
Labels: area: Azure AD, ready to merge, content review complete

#21564 Update localization documentation
  concepts/toolkit/components/file-list.md
  concepts/toolkit/components/file.md
  concepts/toolkit/components/get.md
  concepts/toolkit/components/people-picker.md
  concepts/toolkit/components/person-card.md
  concepts/toolkit/components/person.md
  concepts/toolkit/components/picker.md
  concepts/toolkit/components/tasks.md
  concepts/toolkit/components/teams-channel-picker.md
  concepts/toolkit/components/theme-toggle.md
Labels: ready to merge, ready for content review, internal

#21583 Update permissions-reference.md
  concepts/permissions-reference.md
Labels: external, ready to merge, content review complete

#21598 Minor doc fixes
  api-reference/beta/api/approleassignment-get.md
  api-reference/beta/api/user-list-approleassignments.md
  api-reference/beta/resources/approleassignment.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/approleassignment-get.md
  api-reference/v1.0/api/user-list-approleassignments.md
  api-reference/v1.0/resources/approleassignment.md
  api-reference/v1.0/toc.yml
  concepts/auth-v2-service.md
  concepts/auth-v2-user.md
  concepts/extensibility-overview.md
  concepts/permissions-overview.md
  concepts/permissions-reference.md
  concepts/traverse-the-graph.md
Labels: area: Azure AD, ready to merge, internal

#21610 Fixed example metadata
  api-reference/v1.0/api/accesspackageassignment-reprocess.md
  api-reference/v1.0/api/accesspackageassignmentrequest-reprocess.md
  api-reference/v1.0/api/authenticationmethod-get.md
  api-reference/v1.0/api/authorizationpolicy-get.md
  api-reference/v1.0/api/bitlocker-list-recoverykeys.md
  api-reference/v1.0/api/bitlockerrecoverykey-get.md
  api-reference/v1.0/api/bookingappointment-cancel.md
  api-reference/v1.0/api/bookingappointment-delete.md
  api-reference/v1.0/api/bookingappointment-get.md
  api-reference/v1.0/api/bookingbusiness-list-appointments.md
  api-reference/v1.0/api/bookingbusiness-list-calendarview.md
  api-reference/v1.0/api/bookingbusiness-list-customers.md
  api-reference/v1.0/api/bookingbusiness-list-customquestions.md
  api-reference/v1.0/api/bookingbusiness-list-services.md
  api-reference/v1.0/api/bookingbusiness-list-staffmembers.md
  api-reference/v1.0/api/bookingbusiness-list.md
  api-reference/v1.0/api/bookingbusiness-post-appointments.md
  api-reference/v1.0/api/bookingbusiness-post-bookingbusinesses.md
  api-reference/v1.0/api/bookingbusiness-post-customers.md
  api-reference/v1.0/api/bookingbusiness-post-customquestions.md
  api-reference/v1.0/api/bookingbusiness-post-services.md
  api-reference/v1.0/api/bookingbusiness-post-staffmembers.md
  api-reference/v1.0/api/bookingbusiness-publish.md
  api-reference/v1.0/api/bookingbusiness-unpublish.md
  api-reference/v1.0/api/bookingbusiness-update.md
  api-reference/v1.0/api/bookingcurrency-get.md
  api-reference/v1.0/api/bookingcurrency-list.md
  api-reference/v1.0/api/bookingcustomer-delete.md
  api-reference/v1.0/api/bookingcustomer-get.md
  api-reference/v1.0/api/bookingcustomer-update.md
  api-reference/v1.0/api/bookingcustomquestion-delete.md
  api-reference/v1.0/api/bookingcustomquestion-get.md
  api-reference/v1.0/api/bookingcustomquestion-update.md
Labels: ready to merge, internal

#20937 Add lastUpdatedDateTime to userRegistrationDetails
  api-reference/beta/api/authenticationmethodsroot-list-userregistrationdetails.md
  api-reference/beta/api/userregistrationdetails-get.md
  api-reference/beta/resources/userregistrationdetails.md
  changelog/Microsoft.AAD.Reporting.json
Labels: area: Azure AD, external, ready to merge, content review complete, schema live

#21310 user default method documentation
  api-reference/beta/api/authentication-get.md
  api-reference/beta/api/authentication-update.md
  api-reference/beta/resources/authentication.md
  api-reference/beta/resources/authenticationmethods-overview.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/signinpreferences.md
  api-reference/beta/toc.yml
  changelog/Microsoft.StrongAuthenticationAPI.json
Labels: area: Azure AD, ready to merge, internal, area: authentication methods, content review complete

#21599 Corrected reference to Facets example
  api-reference/beta/resources/onedrive.md
  api-reference/v1.0/resources/onedrive.md
Labels: external, ready to merge

#20964 Update connecting-external-content-external-groups.md
  concepts/connecting-external-content-external-groups.md
Labels: do not merge, ready to merge, internal, content review complete

#21261 [CloudPC] Add correlationId to CloudPcOnPremisesConnectionHealthCheck
  api-reference/beta/api/cloudpconpremisesconnection-get.md
  api-reference/beta/resources/cloudpconpremisesconnection.md
  api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
  api-reference/beta/resources/cloudpconpremisesconnectionstatusdetails.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, internal, content review complete

#21604 App-only support enabled for PIM for groups policy endpoints
  api-reference/beta/api/policyroot-list-rolemanagementpolicies.md
  api-reference/beta/api/policyroot-list-rolemanagementpolicyassignments.md
  api-reference/beta/api/unifiedrolemanagementpolicy-get.md
  api-reference/beta/api/unifiedrolemanagementpolicy-list-rules.md
  api-reference/beta/api/unifiedrolemanagementpolicy-update.md
  api-reference/beta/api/unifiedrolemanagementpolicyassignment-get.md
  api-reference/beta/api/unifiedrolemanagementpolicyrule-get.md
  api-reference/beta/api/unifiedrolemanagementpolicyrule-update.md
Labels: area: Azure AD, ready to merge, internal, content review complete

#21549 docs: update mgt-todo documentation
  concepts/toolkit/components/todo.md
Labels: ready to merge, internal, content review complete

#21609 adds new css property for mgt-picker
  concepts/toolkit/components/picker.md
Labels: ready to merge, ready for content review, internal

#21625 Add Link to List Attendance Report API in Virtual Event Sessions Page
  api-reference/beta/resources/virtualeventsession.md
Labels: ready to merge, ready for content review, internal

#21627 Merge to publish.
  api-reference/beta/api/cloudpconpremisesconnection-get.md
  api-reference/beta/api/policyroot-list-rolemanagementpolicies.md
  api-reference/beta/api/policyroot-list-rolemanagementpolicyassignments.md
  api-reference/beta/api/unifiedrolemanagementpolicy-get.md
  api-reference/beta/api/unifiedrolemanagementpolicy-list-rules.md
  api-reference/beta/api/unifiedrolemanagementpolicy-update.md
  api-reference/beta/api/unifiedrolemanagementpolicyassignment-get.md
  api-reference/beta/api/unifiedrolemanagementpolicyrule-get.md
  api-reference/beta/api/unifiedrolemanagementpolicyrule-update.md
  api-reference/beta/resources/cloudpconpremisesconnection.md
  api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
  api-reference/beta/resources/cloudpconpremisesconnectionstatusdetails.md
  api-reference/beta/resources/virtualeventsession.md
  changelog/Microsoft.CloudManagedDesktop.json
  concepts/connecting-external-content-external-groups.md
Labels: do not merge, internal

#21329 Added noLicenseAvailableConnectivityFailureReport enum member (roadmap 17559)
  api-reference/beta/api/cloudpcreports-post-exportjobs.md
  api-reference/beta/resources/cloudpcexportjob.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, internal, content review complete

#21492 alt key syntax v1 update
  api-reference/v1.0/api/application-addkey.md
  api-reference/v1.0/api/application-addpassword.md
  api-reference/v1.0/api/application-delete-owners.md
  api-reference/v1.0/api/application-delete-tokenissuancepolicies.md
  api-reference/v1.0/api/application-delete-tokenlifetimepolicies.md
  api-reference/v1.0/api/application-delete.md
  api-reference/v1.0/api/application-get.md
  api-reference/v1.0/api/application-list-federatedidentitycredentials.md
  api-reference/v1.0/api/application-list-owners.md
  api-reference/v1.0/api/application-list-tokenissuancepolicies.md
  api-reference/v1.0/api/application-list-tokenlifetimepolicies.md
  api-reference/v1.0/api/application-post-federatedidentitycredentials.md
  api-reference/v1.0/api/application-post-owners.md
  api-reference/v1.0/api/application-post-tokenissuancepolicies.md
  api-reference/v1.0/api/application-post-tokenlifetimepolicies.md
  api-reference/v1.0/api/application-removekey.md
  api-reference/v1.0/api/application-removepassword.md
  api-reference/v1.0/api/application-setverifiedpublisher.md
  api-reference/v1.0/api/application-unsetverifiedpublisher.md
  api-reference/v1.0/api/application-update.md
  api-reference/v1.0/api/federatedidentitycredential-delete.md
  api-reference/v1.0/api/federatedidentitycredential-get.md
  api-reference/v1.0/api/federatedidentitycredential-update.md
  api-reference/v1.0/resources/application.md
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, ready to merge, internal, content review complete

#21621 Update identity set for v1.0
  api-reference/v1.0/resources/identityset.md
Labels: ready to merge, internal, content review complete

#21626 fixed example metadata
  api-reference/v1.0/api/calendar-list-calendarpermissions.md
  api-reference/v1.0/api/channel-delete-tabs.md
  api-reference/v1.0/api/channel-get-tabs.md
  api-reference/v1.0/api/channel-patch-tabs.md
  api-reference/v1.0/api/channel-post-tabs.md
  api-reference/v1.0/api/chart-image.md
  api-reference/v1.0/api/columndefinition-update.md
  api-reference/v1.0/api/contenttype-post-columns.md
  api-reference/v1.0/api/conversationmember-delete.md
  api-reference/v1.0/api/conversationmember-get.md
  api-reference/v1.0/api/conversationmember-update.md
  api-reference/v1.0/api/domain-post-domains.md
  api-reference/v1.0/api/educationsubmittedsubmissionresource-get.md
  api-reference/v1.0/api/entitlementmanagement-post-connectedorganizations.md
  api-reference/v1.0/api/fido2authenticationmethod-list.md
  api-reference/v1.0/api/group-post-members.md
  api-reference/v1.0/api/grouplifecyclepolicy-addgroup.md
  api-reference/v1.0/api/grouplifecyclepolicy-removegroup.md
  api-reference/v1.0/api/icon-get.md
  api-reference/v1.0/api/icon-update.md
  api-reference/v1.0/api/identityprovider-post-identityproviders.md
  api-reference/v1.0/api/insights-list-shared.md
  api-reference/v1.0/api/insights-list-trending.md
  api-reference/v1.0/api/list-post-columns.md
  api-reference/v1.0/api/multivaluelegacyextendedproperty-get.md
  api-reference/v1.0/api/multivaluelegacyextendedproperty-post-multivalueextendedproperties.md
  api-reference/v1.0/api/onenote-list-pages.md
  api-reference/v1.0/api/openshift-post.md
  api-reference/v1.0/api/openshiftchangerequest-post.md
  api-reference/v1.0/api/page-get.md
  api-reference/v1.0/api/page-update.md
  api-reference/v1.0/api/projectrome-put-historyitem.md
Labels: ready to merge, internal

#21630 Minor doc fixes
  api-reference/beta/api/group-list-members.md
  api-reference/v1.0/api/group-list-members.md
Labels: area: Azure AD, ready to merge, internal

#21573 Update attachment-get.md
  api-reference/beta/api/attachment-get.md
  api-reference/v1.0/api/attachment-get.md
Labels: ready to merge, internal, customer support issue, content review complete

#21535 Updating CallRecords API v1.0 documentation - New fields added
  api-reference/beta/api/callrecords-callrecord-get.md
  api-reference/v1.0/api/callrecords-callrecord-get.md
  api-reference/v1.0/api/callrecords-session-list.md
  api-reference/v1.0/resources/callrecords-mediastream.md
  api-reference/v1.0/resources/callrecords-participantendpoint.md
  api-reference/v1.0/resources/callrecords-session.md
  changelog/Microsoft.IC3.DataPlatform.json
Labels: ready to merge, internal, content review complete

#19150 Updating documentation for Channel Summary property
  api-reference/beta/api/channel-get.md
  api-reference/beta/resources/channel.md
  api-reference/beta/resources/channelsummary.md
  changelog/Microsoft.Teams.GraphSvc.json
Labels: ready to merge, content review complete

#21485 Breadcrumb investigation
  concepts/breadcrumb/toc.yml
  concepts/docfx.json
Labels: external, ready to merge

#21554 Update security-api-overview.md
  api-reference/v1.0/resources/security-api-overview.md
Labels: external, ready to merge

#21649 fixing duplicate names in new docs
  api-reference/beta/api/approleassignment-get.md
  api-reference/v1.0/api/approleassignment-get.md
Labels: ready to merge, internal

#21083 Authentication Behaviors API beta documentation
  api-reference/beta/resources/application.md
  api-reference/beta/resources/authenticationbehaviors.md
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, ready to merge, internal, content review complete

#21628 Added documentation for recentPrinterShares API
  api-reference/v1.0/api/print-list-recentprintershares.md
  api-reference/v1.0/resources/printershare.md
  api-reference/v1.0/resources/printershareviewpoint.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.PrintService.json
Labels: ready to merge, area: universal print, content review in progress

#21665 Minor doc fixes
  api-reference/beta/api/smsauthenticationmethodconfiguration-delete.md
  api-reference/beta/api/smsauthenticationmethodconfiguration-get.md
  api-reference/beta/api/smsauthenticationmethodconfiguration-update.md
  api-reference/beta/api/user-get.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/smsauthenticationmethodconfiguration-delete.md
  api-reference/v1.0/api/smsauthenticationmethodconfiguration-get.md
  api-reference/v1.0/api/smsauthenticationmethodconfiguration-update.md
  api-reference/v1.0/api/user-get.md
  api-reference/v1.0/toc.yml
Labels: area: Azure AD, ready to merge, internal

#21672 Merge to publish.
  api-reference/beta/api/smsauthenticationmethodconfiguration-delete.md
  api-reference/beta/api/smsauthenticationmethodconfiguration-get.md
  api-reference/beta/api/smsauthenticationmethodconfiguration-update.md
  api-reference/beta/api/user-get.md
  api-reference/beta/resources/application.md
  api-reference/beta/resources/authenticationbehaviors.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/print-list-recentprintershares.md
  api-reference/v1.0/api/smsauthenticationmethodconfiguration-delete.md
  api-reference/v1.0/api/smsauthenticationmethodconfiguration-get.md
  api-reference/v1.0/api/smsauthenticationmethodconfiguration-update.md
  api-reference/v1.0/api/user-get.md
  api-reference/v1.0/resources/printershare.md
  api-reference/v1.0/resources/printershareviewpoint.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.DirectoryServices.json
  changelog/Microsoft.PrintService.json
Labels: internal

#21686 Replaced code blocks with snippet references in SDK documentation
  .openpublishing.publish.config.json
  concepts/docfx.json
  concepts/sdks/batch-requests.md
  concepts/sdks/choose-authentication-providers.md
  concepts/sdks/create-client.md
  concepts/sdks/create-requests.md
  concepts/sdks/customize-client.md
  concepts/sdks/includes/snippets/csharp/create-requests-create.md
  concepts/sdks/includes/snippets/csharp/create-requests-delete.md
  concepts/sdks/includes/snippets/csharp/create-requests-expand.md
  concepts/sdks/includes/snippets/csharp/create-requests-headers.md
  concepts/sdks/includes/snippets/csharp/create-requests-index.md
  concepts/sdks/includes/snippets/csharp/create-requests-list.md
  concepts/sdks/includes/snippets/csharp/create-requests-queryparams.md
  concepts/sdks/includes/snippets/csharp/create-requests-read.md
  concepts/sdks/includes/snippets/csharp/create-requests-select.md
  concepts/sdks/includes/snippets/csharp/create-requests-update.md
  concepts/sdks/includes/snippets/go/create-requests-create.md
  concepts/sdks/includes/snippets/go/create-requests-delete.md
  concepts/sdks/includes/snippets/go/create-requests-expand.md
  concepts/sdks/includes/snippets/go/create-requests-headers.md
  concepts/sdks/includes/snippets/go/create-requests-index.md
  concepts/sdks/includes/snippets/go/create-requests-list.md
  concepts/sdks/includes/snippets/go/create-requests-queryparams.md
  concepts/sdks/includes/snippets/go/create-requests-read.md
  concepts/sdks/includes/snippets/go/create-requests-select.md
  concepts/sdks/includes/snippets/go/create-requests-update.md
  concepts/sdks/includes/snippets/java/create-requests-create.md
  concepts/sdks/includes/snippets/java/create-requests-delete.md
  concepts/sdks/includes/snippets/java/create-requests-expand.md
  concepts/sdks/includes/snippets/java/create-requests-headers.md
  concepts/sdks/includes/snippets/java/create-requests-index.md
  concepts/sdks/includes/snippets/java/create-requests-list.md
  concepts/sdks/includes/snippets/java/create-requests-queryparams.md
  concepts/sdks/includes/snippets/java/create-requests-read.md
  concepts/sdks/includes/snippets/java/create-requests-select.md
  concepts/sdks/includes/snippets/java/create-requests-update.md
  concepts/sdks/includes/snippets/typescript/create-requests-create.md
  concepts/sdks/includes/snippets/typescript/create-requests-delete.md
  concepts/sdks/includes/snippets/typescript/create-requests-expand.md
  concepts/sdks/includes/snippets/typescript/create-requests-headers.md
  concepts/sdks/includes/snippets/typescript/create-requests-index.md
  concepts/sdks/includes/snippets/typescript/create-requests-list.md
  concepts/sdks/includes/snippets/typescript/create-requests-queryparams.md
  concepts/sdks/includes/snippets/typescript/create-requests-read.md
  concepts/sdks/includes/snippets/typescript/create-requests-select.md
  concepts/sdks/includes/snippets/typescript/create-requests-update.md
  concepts/sdks/large-file-upload.md
  concepts/sdks/national-clouds.md
  concepts/sdks/paging.md
  concepts/sdks/sdk-installation.md
  concepts/sdks/sdks-overview.md
  concepts/sdks/use-beta.md
Labels: ready to merge, internal

#21671 fixed snippet metadata round 2
  api-reference/v1.0/api/search-query.md
  api-reference/v1.0/api/section-list-pages.md
  api-reference/v1.0/api/section-post-pages.md
  api-reference/v1.0/api/security-ediscoverysearch-purgedata.md
  api-reference/v1.0/api/security-retentioneventtype-update.md
  api-reference/v1.0/api/site-getallsites.md
  api-reference/v1.0/api/site-getbypath.md
  api-reference/v1.0/api/swapshiftschangerequest-post.md
  api-reference/v1.0/api/tablerow-range.md
  api-reference/v1.0/api/teamwork-sendactivitynotificationtorecipients.md
  api-reference/v1.0/api/termstore-group-post.md
  api-reference/v1.0/api/termstore-relation-post.md
  api-reference/v1.0/api/termstore-set-post.md
  api-reference/v1.0/api/todotask-delta.md
  api-reference/v1.0/api/todotasklist-delta.md
  api-reference/v1.0/api/usersettings-get.md
  api-reference/v1.0/api/usersettings-update.md
  api-reference/v1.0/api/worksheet-post-tables.md
Labels: ready to merge, internal

#21245 Update owner for admin consent workflow APIs
  api-reference/beta/api/adminconsentrequestpolicy-get.md
  api-reference/beta/api/adminconsentrequestpolicy-update.md
  api-reference/beta/api/appconsentapprovalroute-list-appconsentrequests.md
  api-reference/beta/api/appconsentrequest-filterByCurrentUser.md
  api-reference/beta/api/appconsentrequest-get.md
  api-reference/beta/api/appconsentrequest-list-userconsentrequests.md
  api-reference/beta/api/userconsentrequest-filterByCurrentUser.md
  api-reference/beta/api/userconsentrequest-get.md
  api-reference/beta/resources/adminconsentrequestpolicy.md
  api-reference/beta/resources/appconsentapprovalroute.md
  api-reference/beta/resources/appconsentrequest.md
  api-reference/beta/resources/appconsentrequestscope.md
  api-reference/beta/resources/consentrequests-overview.md
  api-reference/beta/resources/userconsentrequest.md
  api-reference/v1.0/api/adminconsentrequestpolicy-get.md
  api-reference/v1.0/api/adminconsentrequestpolicy-update.md
  api-reference/v1.0/api/appconsentapprovalroute-list-appconsentrequests.md
  api-reference/v1.0/api/appconsentrequest-filterbycurrentuser.md
  api-reference/v1.0/api/appconsentrequest-get.md
  api-reference/v1.0/api/appconsentrequest-list-userconsentrequests.md
  api-reference/v1.0/api/userconsentrequest-filterbycurrentuser.md
  api-reference/v1.0/api/userconsentrequest-get.md
  api-reference/v1.0/resources/adminconsentrequestpolicy.md
  api-reference/v1.0/resources/appconsentapprovalroute.md
  api-reference/v1.0/resources/appconsentrequest.md
  api-reference/v1.0/resources/appconsentrequestscope.md
  api-reference/v1.0/resources/approval.md
  api-reference/v1.0/resources/approvalstage.md
  api-reference/v1.0/resources/consentrequests-overview.md
  api-reference/v1.0/resources/userconsentrequest.md
Labels: ready to merge, internal, content review complete

#21248 Update organizationalbranding with contentCustomization property
  api-reference/beta/api/organizationalbranding-get.md
  api-reference/beta/api/organizationalbranding-list-localizations.md
  api-reference/beta/api/organizationalbranding-update.md
  api-reference/beta/api/organizationalbrandinglocalization-get.md
  api-reference/beta/api/organizationalbrandinglocalization-update.md
  api-reference/beta/resources/contentcustomization.md
  api-reference/beta/resources/keyvalue.md
  api-reference/beta/resources/organizationalbranding.md
  api-reference/beta/resources/organizationalbrandinglocalization.md
  api-reference/beta/resources/organizationalbrandingproperties.md
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, ready to merge, internal, content review complete, schema live

#21481 docs: add selected value documentation for mgt-picker
  concepts/toolkit/components/picker.md
Labels: ready to merge, internal, area: toolkit

#21661 Update documentation for IsCourseActivitySyncEnabled for List and Get for LearningProvider
  api-reference/beta/api/employeeexperience-list-learningproviders.md
  api-reference/beta/api/learningprovider-get.md
Labels: ready to merge, internal, content review complete

#21683 Removing deprecating providers
  concepts/toc.yml
  concepts/toolkit/components/person-card.md
  concepts/toolkit/get-started/build-a-microsoft-teams-sso-tab.md
  concepts/toolkit/get-started/build-a-microsoft-teams-tab.md
  concepts/toolkit/get-started/overview.md
  concepts/toolkit/overview.md
  concepts/toolkit/providers/msal.md
  concepts/toolkit/providers/providers.md
  concepts/toolkit/providers/teams-msal2.md
  concepts/toolkit/providers/teams.md
Labels: ready to merge, ready for content review, internal, area: toolkit

#21695 Update authentication-update.md
  api-reference/beta/api/authentication-update.md
Labels: area: authentication, area: Azure AD, ready to merge, internal, content review complete

#21555 docs: Adding search components
  concepts/toc.yml
  concepts/toolkit/components/includes/preview-disclaimer.md
  concepts/toolkit/components/search-box.md
  concepts/toolkit/components/search-results.md
  concepts/toolkit/overview.md
Labels: ready to merge, internal, area: toolkit

#21416 Support multiple entity request
  concepts/search-concept-interleaving.md
  concepts/search-concept-multipleRequest.md
  concepts/toc.yml
Labels: ready to merge, content review complete

#21708 Merge to publish.
  api-reference/beta/api/adminconsentrequestpolicy-get.md
  api-reference/beta/api/adminconsentrequestpolicy-update.md
  api-reference/beta/api/appconsentapprovalroute-list-appconsentrequests.md
  api-reference/beta/api/appconsentrequest-filterByCurrentUser.md
  api-reference/beta/api/appconsentrequest-get.md
  api-reference/beta/api/appconsentrequest-list-userconsentrequests.md
  api-reference/beta/api/authentication-update.md
  api-reference/beta/api/employeeexperience-list-learningproviders.md
  api-reference/beta/api/learningprovider-get.md
  api-reference/beta/api/organization-get.md
  api-reference/beta/api/organization-list.md
  api-reference/beta/api/organizationalbranding-get.md
  api-reference/beta/api/organizationalbranding-list-localizations.md
  api-reference/beta/api/organizationalbranding-update.md
  api-reference/beta/api/organizationalbrandinglocalization-get.md
  api-reference/beta/api/organizationalbrandinglocalization-update.md
  api-reference/beta/api/userconsentrequest-filterByCurrentUser.md
  api-reference/beta/api/userconsentrequest-get.md
  api-reference/beta/resources/adminconsentrequestpolicy.md
  api-reference/beta/resources/appconsentapprovalroute.md
  api-reference/beta/resources/appconsentrequest.md
  api-reference/beta/resources/appconsentrequestscope.md
  api-reference/beta/resources/consentrequests-overview.md
  api-reference/beta/resources/contentcustomization.md
  api-reference/beta/resources/keyvalue.md
  api-reference/beta/resources/organization.md
  api-reference/beta/resources/organizationalbranding.md
  api-reference/beta/resources/organizationalbrandinglocalization.md
  api-reference/beta/resources/organizationalbrandingproperties.md
  api-reference/beta/resources/userconsentrequest.md
  api-reference/v1.0/api/adminconsentrequestpolicy-get.md
  api-reference/v1.0/api/adminconsentrequestpolicy-update.md
  api-reference/v1.0/api/appconsentapprovalroute-list-appconsentrequests.md
  api-reference/v1.0/api/appconsentrequest-filterbycurrentuser.md
  api-reference/v1.0/api/appconsentrequest-get.md
  api-reference/v1.0/api/appconsentrequest-list-userconsentrequests.md
  api-reference/v1.0/api/userconsentrequest-filterbycurrentuser.md
  api-reference/v1.0/api/userconsentrequest-get.md
  api-reference/v1.0/resources/adminconsentrequestpolicy.md
  api-reference/v1.0/resources/appconsentapprovalroute.md
  api-reference/v1.0/resources/appconsentrequest.md
  api-reference/v1.0/resources/appconsentrequestscope.md
  api-reference/v1.0/resources/approval.md
  api-reference/v1.0/resources/approvalstage.md
  api-reference/v1.0/resources/consentrequests-overview.md
  api-reference/v1.0/resources/userconsentrequest.md
  changelog/Microsoft.DirectoryServices.json
  concepts/search-concept-interleaving.md
  concepts/search-concept-multipleRequest.md
  concepts/toc.yml
Labels: do not merge, internal

#21723 Update and rename alternativeSecurityId.md to alternativesecurityid.md
  api-reference/beta/resources/alternativeSecurityId.md
  api-reference/beta/resources/alternativesecurityid.md
Labels: external

#21722 Update and rename alternativeSecurityId.md to alternativesecurityid.md
  api-reference/v1.0/resources/alternativesecurityid.md
Labels: external

#21721 Update chatmessage.md
  api-reference/v1.0/resources/chatmessage.md
Labels: external

#21719 Update chatmessage-post.md
  api-reference/v1.0/api/chatmessage-post.md
Labels: external

#21718 Update managedtenants-tenant.md
  api-reference/beta/resources/managedtenants-tenant.md
Labels: external

#21720 Update chatmessage.md
  api-reference/beta/resources/chatmessage.md
Labels: external

#21712 Fix changelog and unblock #21662
  changelog/Microsoft.IdentityGovernance.AccessReviews.json
Labels: area: Azure AD, ready to merge, internal

#21726 Update search-concept-multipleRequest.md
  concepts/search-concept-multipleRequest.md
Labels: ready to merge, internal, content review complete

#21732 docs: Moving the why and who sections to be higher in the page
  concepts/toolkit/overview.md
Labels: ready to merge, internal, area: toolkit

#21733 Update employeeexperience-post-learningproviders.md
  api-reference/beta/api/employeeexperience-post-learningproviders.md
  api-reference/v1.0/api/employeeexperience-post-learningproviders.md
Labels: external, ready to merge

#21707 Updating with TeamsFx the Teams getting started
  concepts/toolkit/get-started/build-a-microsoft-teams-tab.md
Labels: ready to merge, internal

#21728 docs: add picker to overview page
  concepts/toolkit/overview.md
Labels: ready to merge, internal

#21735 fixing issues in snippet gen
  api-reference/beta/api/channel-get.md
  api-reference/v1.0/api/swapshiftschangerequest-list.md
  api-reference/v1.0/api/teamwork-sendactivitynotificationtorecipients.md
  api-reference/v1.0/api/todotask-delta.md
Labels: ready to merge, internal

#21655 feat: disambiguation in mgt
  concepts/toc.yml
  concepts/toolkit/customize-components/disambiguation.md
  concepts/toolkit/get-started/mgt-react.md
  concepts/toolkit/get-started/mgt-spfx.md
  concepts/toolkit/get-started/overview.md
Labels: ready to merge, ready for content review, internal, area: toolkit

#21754 Update and rename certificationControl.md to certificationcontrol.md
  api-reference/beta/resources/certificationcontrol.md
Labels: external

#21748 Update calculatedcolumn.md
  api-reference/beta/resources/calculatedcolumn.md
Labels: external

#21747 Update calculatedcolumn.md
  api-reference/v1.0/resources/calculatedcolumn.md
Labels: external

#20204 Add PIM Alert Graph API docs to Beta
  api-reference/beta/api/longrunningoperation-get.md
  api-reference/beta/api/rolemanagementalert-list-alertconfigurations.md
  api-reference/beta/api/rolemanagementalert-list-alertdefinitions.md
  api-reference/beta/api/rolemanagementalert-list-alerts.md
  api-reference/beta/api/unifiedrolemanagementalert-get.md
  api-reference/beta/api/unifiedrolemanagementalert-list-alertincidents.md
  api-reference/beta/api/unifiedrolemanagementalert-refresh.md
  api-reference/beta/api/unifiedrolemanagementalert-update.md
  api-reference/beta/api/unifiedrolemanagementalertconfiguration-get.md
  api-reference/beta/api/unifiedrolemanagementalertconfiguration-update.md
  api-reference/beta/api/unifiedrolemanagementalertdefinition-get.md
  api-reference/beta/api/unifiedrolemanagementalertincident-get.md
  api-reference/beta/api/unifiedrolemanagementalertincident-remediate.md
  api-reference/beta/includes/rbac-for-apis/rbac-pim-alerts-apis-read.md
  api-reference/beta/includes/rbac-for-apis/rbac-pim-alerts-apis-write.md
  api-reference/beta/resources/identitygovernance.md
  api-reference/beta/resources/invalidlicensealertconfiguration.md
  api-reference/beta/resources/invalidlicensealertincident.md
  api-reference/beta/resources/longrunningoperation.md
  api-reference/beta/resources/nomfaonroleactivationalertconfiguration.md
  api-reference/beta/resources/nomfaonroleactivationalertincident.md
  api-reference/beta/resources/privilegedidentitymanagementv3-overview.md
  api-reference/beta/resources/redundantassignmentalertconfiguration.md
  api-reference/beta/resources/redundantassignmentalertincident.md
  api-reference/beta/resources/rolemanagementalert.md
  api-reference/beta/resources/rolesassignedoutsideprivilegedidentitymanagementalertconfiguration.md
  api-reference/beta/resources/rolesassignedoutsideprivilegedidentitymanagementalertincident.md
  api-reference/beta/resources/sequentialactivationrenewalsalertconfiguration.md
  api-reference/beta/resources/sequentialactivationrenewalsalertincident.md
  api-reference/beta/resources/stalesigninalertconfiguration.md
  api-reference/beta/resources/stalesigninalertincident.md
  api-reference/beta/resources/toomanyglobaladminsassignedtotenantalertconfiguration.md
  api-reference/beta/resources/toomanyglobaladminsassignedtotenantalertincident.md
  api-reference/beta/resources/unifiedrolemanagementalert.md
  api-reference/beta/resources/unifiedrolemanagementalertconfiguration.md
  api-reference/beta/resources/unifiedrolemanagementalertdefinition.md
  api-reference/beta/resources/unifiedrolemanagementalertincident.md
  api-reference/beta/toc.yml
  changelog/Microsoft.PIM.AzureRBAC.json
  concepts/permissions-reference.md
Labels: area: Azure AD, ready to merge, internal, content review complete, schema live, area: governance

#21736 Fix docs issues being flagged by new API Doctor version
  api-reference/v1.0/api/approleassignment-get.md
  api-reference/v1.0/api/chart-image.md
  api-reference/v1.0/api/group-post-members.md
  api-reference/v1.0/api/offershiftrequest-post.md
  api-reference/v1.0/api/organizationalbranding-get.md
  api-reference/v1.0/api/organizationalbranding-update.md
  api-reference/v1.0/api/organizationalbrandinglocalization-get.md
  api-reference/v1.0/api/organizationalbrandinglocalization-update.md
  api-reference/v1.0/api/page-update.md
  api-reference/v1.0/api/termstore-group-post.md
  api-reference/v1.0/api/termstore-relation-post.md
  api-reference/v1.0/api/todotask-delta.md
  api-reference/v1.0/resources/authentication.md
  api-reference/v1.0/resources/chatmessage.md
  api-reference/v1.0/resources/offershiftrequest.md
  api-reference/v1.0/resources/schedule.md
  api-reference/v1.0/resources/timeoffrequest.md
  api-reference/v1.0/resources/user.md
  api-reference/v1.0/resources/workbook.md
Labels: ready to merge, internal

#21737 Update identityprotection-overview.md
  api-reference/beta/resources/identityprotection-overview.md
  api-reference/v1.0/resources/identityprotection-overview.md
Labels: area: Azure AD, ready to merge, internal

#21750 Privileges to manage member of restricted AU
  api-reference/beta/resources/administrativeunit.md
  api-reference/beta/resources/device.md
  api-reference/beta/resources/group.md
  api-reference/beta/resources/user.md
Labels: area: Azure AD, ready to merge, internal, area: directory management

#21753 Add note about rules in PIM for groups being in beta only
  concepts/how-to-pim-update-rules.md
Labels: area: Azure AD, ready to merge, area: governance

#21557 ThreatIntelligence - Backporting changes made for v1.0 to beta
  api-reference/beta/api/security-article-list-indicators.md
  api-reference/beta/api/security-articleindicator-get.md
  api-reference/beta/api/security-intelligenceprofile-list-indicators.md
  api-reference/beta/api/security-intelligenceprofileindicator-get.md
  api-reference/beta/resources/enums-security.md
  api-reference/beta/resources/security-articleindicator.md
  api-reference/beta/resources/security-indicator.md
  changelog/Microsoft.ThreatIntelligence.json
Labels: ready to merge, internal, content review in progress

#21624 Update metered-api-list.md
  concepts/metered-api-list.md
Labels: external, ready to merge, review requested

#21588 Rich notifications doc refresh (Batch 1)
  concepts/includes/change-notifications-delivery-latency.md
  concepts/includes/change-notifications-delivery-notificationurl-validation.md
  concepts/includes/change-notifications-rich-notifications-supported-resources.md
  concepts/includes/change-notifications-subscription-lifetime.md
  concepts/includes/change-notifications-supported-resources-expanded.md
  concepts/includes/change-notifications-supported-resources-flat.md
  concepts/webhooks-lifecycle.md
  concepts/webhooks-with-resource-data.md
Labels: area: Azure AD, ready to merge, internal, content review complete, area: change notifications

#21673 Updates to userRegistrationDetails API
  api-reference/beta/api/authenticationmethodsroot-list-userregistrationdetails.md
  api-reference/beta/api/userregistrationdetails-get.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/userregistrationdetails.md
  changelog/Microsoft.AAD.Reporting.json
Labels: area: Azure AD, ready to merge, internal, content review complete, schema live

#21761 Minor doc fixes
  api-reference/beta/api/administrativeunit-delete-members.md
  api-reference/beta/api/application-delete-tokenlifetimepolicies.md
  api-reference/beta/api/user-update.md
  api-reference/beta/resources/organization.md
  api-reference/beta/resources/tokenlifetimepolicy.md
  api-reference/v1.0/api/administrativeunit-delete-members.md
  api-reference/v1.0/api/application-delete-tokenlifetimepolicies.md
  api-reference/v1.0/api/user-update.md
  api-reference/v1.0/resources/organization.md
  api-reference/v1.0/resources/tokenlifetimepolicy.md
  concepts/application-rollkey-prooftoken.md
  concepts/migrate-azure-ad-graph-faq.md
  concepts/migrate-azure-ad-graph-overview.md
Labels: area: Azure AD, ready to merge

#21789 Trying to update conversationthread-update.md
  api-reference/v1.0/api/conversationthread-update.md
  api-reference/v1.0/api/multivaluelegacyextendedproperty-get.md
  api-reference/v1.0/api/multivaluelegacyextendedproperty-post-multivalueextendedproperties.md
  api-reference/v1.0/api/onenote-list-pages.md
  api-reference/v1.0/api/profilephoto-get.md
  api-reference/v1.0/api/projectrome-put-activity.md
Labels: ready to merge, internal

#21794 Fixing issues in examples
  api-reference/v1.0/api/usersettings-update.md
  api-reference/v1.0/resources/usersettings.md
Labels: ready to merge, internal

#21773 Update bookingbusiness-list.md
  api-reference/beta/api/bookingbusiness-list.md
  api-reference/v1.0/api/bookingbusiness-list.md
Labels: external, ready to merge

#21797 Update drive-sharedwithme.md
  api-reference/beta/api/drive-sharedwithme.md
  api-reference/v1.0/api/drive-sharedwithme.md
Labels: external, ready to merge

#21785 Update and rename contentType.md to contenttype.md
  api-reference/v1.0/resources/contenttype.md
Labels: external, ready to merge

#21779 Add May items to the what's new topic.
  api-reference/beta/resources/searchhit.md
  api-reference/v1.0/resources/searchhit.md
  changelog/Microsoft.M365.Defender.json
  changelog/Microsoft.MicrosoftSearch.json
  concepts/whats-new-overview.md
Labels: ready to merge, internal

#21788 updating strings for localization of mgt-people-picker
  concepts/toolkit/components/people-picker.md
Labels: ready to merge, ready for content review, internal

#21799 Update contentType.md
  api-reference/beta/resources/contentType.md
  api-reference/beta/resources/contenttype.md
Labels: external

#21803 Update and rename contentTypeOrder.md to contenttypeorder.md
  api-reference/v1.0/resources/contentTypeOrder.md
  api-reference/v1.0/resources/contenttypeorder.md
Labels: external

#21804 Update and rename contentTypeInfo.md to contenttypeinfo.md
  api-reference/v1.0/resources/contentTypeInfo.md
  api-reference/v1.0/resources/contenttypeinfo.md
Labels: external

#21805 Update contenttypeinfo.md
  api-reference/beta/resources/contenttypeinfo.md
Labels: external

#21806 Update and rename defaultColumnValue.md to defaultcolumnvalue.md
  api-reference/beta/resources/defaultColumnValue.md
  api-reference/beta/resources/defaultcolumnvalue.md
Labels: external

#21807 Update and rename defaultColumnValue.md to defaultcolumnvalue.md
  api-reference/v1.0/resources/defaultColumnValue.md
  api-reference/v1.0/resources/defaultcolumnvalue.md
Labels: external

#21390 [Doc Improvement][Docx format removed][3099832]
  api-reference/beta/api/calltranscript-get.md
  api-reference/beta/api/onlinemeeting-list-transcripts.md
Labels: ready to merge, internal, content review complete, review feedback addressed

#20184 [CloudPC] Documentation update for cloudPcStatus.movingRegion
  api-reference/beta/resources/cloudpc.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, internal, content review complete, schema live

#20183 [CloudPC] Documentation update for new API - GetProvisionedCloudPCs
  api-reference/beta/api/cloudpc-getprovisionedcloudpcs.md
  api-reference/beta/resources/cloudpc.md
  api-reference/beta/toc.yml
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, internal, content review complete, schema live

#21778 Group rich notifications samples using conceptual tabs
  concepts/webhooks-with-resource-data.md
Labels: area: Azure AD, ready to merge, internal, area: change notifications

#21755 GA v3 of Toolkit
  concepts/toc.yml
  concepts/toolkit/components/agenda.md
  concepts/toolkit/components/file-list.md
  concepts/toolkit/components/file.md
  concepts/toolkit/components/get.md
  concepts/toolkit/components/images/mgt-taxonomy-picker-locale-term.png
  concepts/toolkit/components/images/mgt-taxonomy-picker-term.png
  concepts/toolkit/components/images/mgt-taxonomy-picker-termset.png
  concepts/toolkit/components/includes/preview-disclaimer.md
  concepts/toolkit/components/login.md
  concepts/toolkit/components/people-picker.md
  concepts/toolkit/components/people.md
  concepts/toolkit/components/person-card.md
  concepts/toolkit/components/person.md
  concepts/toolkit/components/picker.md
  concepts/toolkit/components/search-box.md
  concepts/toolkit/components/search-results.md
  concepts/toolkit/components/tasks.md
  concepts/toolkit/components/taxonomy-picker.md
  concepts/toolkit/components/teams-channel-picker.md
  concepts/toolkit/components/theme-toggle.md
  concepts/toolkit/components/todo.md
  concepts/toolkit/customize-components/disambiguation.md
  concepts/toolkit/customize-components/style.md
  concepts/toolkit/get-started/build-a-microsoft-teams-sso-tab.md
  concepts/toolkit/get-started/build-a-microsoft-teams-tab.md
  concepts/toolkit/get-started/build-a-sharepoint-web-part.md
  concepts/toolkit/get-started/build-a-web-app.md
  concepts/toolkit/get-started/build-an-electron-app.md
  concepts/toolkit/get-started/mgt-react.md
  concepts/toolkit/get-started/mgt-spfx.md
  concepts/toolkit/get-started/overview.md
  concepts/toolkit/get-started/use-toolkit-with-angular.md
  concepts/toolkit/get-started/use-toolkit-with-react.md
  concepts/toolkit/images/login-fluentui-override-dark.png
  concepts/toolkit/images/login-fluentui-override.png
  concepts/toolkit/overview.md
  concepts/toolkit/providers/electron.md
  concepts/toolkit/providers/msal.md
  concepts/toolkit/providers/msal2.md
  concepts/toolkit/providers/providers.md
  concepts/toolkit/providers/proxy.md
  concepts/toolkit/providers/sharepoint.md
  concepts/toolkit/providers/teams-msal2.md
  concepts/toolkit/providers/teams.md
  concepts/toolkit/providers/teamsfx.md
  concepts/toolkit/upgrade.md
Labels: ready to merge, internal, content review complete

#21770 Update driveitem-createuploadsession.md
  api-reference/beta/api/driveitem-createuploadsession.md
  api-reference/v1.0/api/driveitem-createuploadsession.md
Labels: ready to merge, internal, content review complete
