Repository microsoftgraph/microsoft-graph-docs, pull requests merged in 2023-05, with the labels that each got.

#21128 Edits in PR 20791
  api-reference/beta/api/driveitem-setretentionlabel.md
  api-reference/includes/premium-metered-apis-disclaimer.md
  api-reference/includes/premium-metered-apis-request-access-disclaimer.md
  concepts/metered-api-list.md
Labels: external

#21129 Edits in PR 20954
  api-reference/beta/resources/conditionalaccessallexternaltenants.md
  api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md
  api-reference/beta/resources/conditionalaccessexternaltenants.md
  api-reference/beta/resources/conditionalaccessguestsorexternalusers.md
  api-reference/beta/resources/conditionalaccessusers.md
  api-reference/beta/resources/enums.md
  api-reference/v1.0/resources/conditionalaccessallexternaltenants.md
  api-reference/v1.0/resources/conditionalaccessenumeratedexternaltenants.md
  api-reference/v1.0/resources/conditionalaccessexternaltenants.md
  api-reference/v1.0/resources/conditionalaccessguestsorexternalusers.md
  api-reference/v1.0/resources/conditionalaccessusers.md
  api-reference/v1.0/resources/enums.md
  changelog/Microsoft.IdentityProtectionServices.json
Labels: external

#21130 vfrankson-05.01.2023
  api-reference/beta/resources/industrydata-overview.md
  concepts/industrydata-concept-overview.md
Labels: ready to merge, internal

#21122 Update timecard-confirm.md
  api-reference/beta/api/timecard-confirm.md
Labels: external

#21121 Update timecard-delete.md
  api-reference/beta/api/timecard-delete.md
Labels: external

#21120 Update timecard-post.md
  api-reference/beta/api/timecard-post.md
Labels: external

#21119 Update timecard-get.md
  api-reference/beta/api/timecard-get.md
Labels: external

#21115 Update timecard.md
  api-reference/beta/resources/timecard.md
Labels: external

#21114 Update accesspackageassignmentrequestorsettings.md
  api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md
Labels: external

#21113 Update directoryobject-delete.md
  api-reference/beta/api/directoryobject-delete.md
Labels: external

#21112 Update directoryobject-delete.md
  api-reference/v1.0/api/directoryobject-delete.md
Labels: external

#21110 Update onenote-post-notebooks.md
  api-reference/v1.0/api/onenote-post-notebooks.md
Labels: external

#21109 Update onenote-post-notebooks.md
  api-reference/beta/api/onenote-post-notebooks.md
Labels: external

#21108 Update dynamics-itemcategories.md
  api-reference/beta/resources/dynamics-itemcategories.md
Labels: external

#21132 Update user-list.md
  api-reference/beta/api/user-list.md
  api-reference/v1.0/api/user-list.md
Labels: external, ready to merge

#20592 first iteration of PR
  concepts/data-connect-users-and-groups.md
  concepts/images/data-connect-groups-1.png
  concepts/images/data-connect-groups-2.5.png
  concepts/images/data-connect-groups-2.png
  concepts/images/data-connect-groups-3.png
  concepts/images/data-connect-groups-4.png
  concepts/toc.yml
Labels: ready to merge, internal

#21133 Merge to publish.
  api-reference/beta/api/directoryobject-delete.md
  api-reference/beta/api/onenote-post-notebooks.md
  api-reference/beta/api/timecard-confirm.md
  api-reference/beta/api/timecard-delete.md
  api-reference/beta/api/timecard-get.md
  api-reference/beta/api/timecard-post.md
  api-reference/beta/api/user-list.md
  api-reference/beta/resources/dynamics-itemcategories.md
  api-reference/beta/resources/industrydata-overview.md
  api-reference/beta/resources/timecard.md
  api-reference/v1.0/api/directoryobject-delete.md
  api-reference/v1.0/api/onenote-post-notebooks.md
  api-reference/v1.0/api/user-list.md
  api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md
  concepts/data-connect-users-and-groups.md
  concepts/images/data-connect-groups-1.png
  concepts/images/data-connect-groups-2.5.png
  concepts/images/data-connect-groups-2.png
  concepts/images/data-connect-groups-3.png
  concepts/images/data-connect-groups-4.png
  concepts/industrydata-concept-overview.md
  concepts/toc.yml
Labels: internal

#20833 Update throttling-limits.md
  concepts/json-batching.md
  concepts/throttling-limits.md
  concepts/throttling.md
Labels: ready to merge, internal, content review complete

#21135 Publish updates to Outlook throttling behavior for batched requests.
  concepts/json-batching.md
  concepts/throttling-limits.md
  concepts/throttling.md
Labels: internal

#21136 Edits in PR 20971
  api-reference/beta/api/unifiedrbacapplication-delete-customappscope.md
  api-reference/beta/api/unifiedrbacapplication-get-customappscope.md
  api-reference/beta/api/unifiedrbacapplication-list-customappscopes.md
  api-reference/beta/api/unifiedrbacapplication-post-customappscope.md
  api-reference/beta/api/unifiedrbacapplication-update-customappscope.md
  api-reference/beta/resources/customappscope.md
  api-reference/beta/resources/customappscopeattributesdictionary.md
  api-reference/beta/resources/unifiedrbacapplication.md
  changelog/Microsoft.DirectoryServices.json
Labels: external

#20957 Removing useForSignIn property that isn't in the schema
  api-reference/beta/resources/authenticationmethodtarget.md
  api-reference/v1.0/resources/authenticationmethodtarget.md
Labels: area: Azure AD, ready to merge

#21106 Update phoneauthenticationmethod.md
  api-reference/beta/resources/phoneauthenticationmethod.md
  api-reference/v1.0/resources/phoneauthenticationmethod.md
Labels: area: Azure AD, ready to merge, content review complete

#21145 Fixes Json schema
  changelog/Changelog.Schema.json
  changelog/Microsoft.Skype.Calling.json
Labels: ready to merge, internal

#21147 Minor doc fixes
  api-reference/beta/api/accesspackagecatalog-post-accesspackagecustomworkflowextensions.md
Labels: area: Azure AD, ready to merge

#20739 Update membershipOutlierInsight.md
  api-reference/beta/resources/membershipOutlierInsight.md
  changelog/Microsoft.AAD.Reporting.json
Labels: area: Azure AD, ready to merge, internal, content review complete

#21150 OffSetInDays range fix
  api-reference/beta/resources/identitygovernance-timebasedattributetrigger.md
Labels: area: Azure AD, ready to merge, internal

#21156 update table for onlinemeeting get permission
  api-reference/beta/api/onlinemeeting-get.md
  api-reference/v1.0/api/onlinemeeting-get.md
Labels: ready to merge, internal

#20488 Promote FileServices > Tenant Settings API from beta to v1.0
  api-reference/beta/api/sharepointsettings-get.md
  api-reference/beta/api/sharepointsettings-update.md
  api-reference/beta/resources/admin.md
  api-reference/beta/resources/idlesessionsignout.md
  api-reference/beta/resources/sharepoint.md
  api-reference/beta/resources/sharepointsettings.md
  api-reference/beta/resources/tenantadmin-sharepoint.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/sharepointsettings-get.md
  api-reference/v1.0/api/sharepointsettings-update.md
  api-reference/v1.0/resources/admin.md
  api-reference/v1.0/resources/idlesessionsignout.md
  api-reference/v1.0/resources/sharepoint.md
  api-reference/v1.0/resources/sharepointsettings.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.FileServices.json
Labels: ready to merge, internal, content review complete

#20966 [BugFix] GET and LIST Api's are also accessible by ReadWrite Permissions
  api-reference/beta/api/employeeexperience-list-learningproviders.md
  api-reference/beta/api/learningcontent-get.md
  api-reference/beta/api/learningprovider-get.md
  api-reference/beta/api/learningprovider-list-learningcontents.md
  api-reference/v1.0/api/employeeexperience-list-learningproviders.md
  api-reference/v1.0/api/learningcontent-get.md
  api-reference/v1.0/api/learningprovider-get.md
  api-reference/v1.0/api/learningprovider-list-learningcontents.md
Labels: ready to merge

#21027 Update appmanagementpolicy-delete-appliesto.md
  api-reference/beta/api/appmanagementpolicy-delete-appliesto.md
  api-reference/v1.0/api/appmanagementpolicy-delete-appliesto.md
Labels: area: Azure AD, external, ready to merge

#21148 docs: update mgt-tasks documentation page
  concepts/toolkit/components/tasks.md
Labels: ready to merge, ready for content review, internal

#21153 signin-activity-update-050223
  api-reference/beta/api/user-list.md
  api-reference/beta/resources/user.md
  api-reference/v1.0/api/user-list.md
  api-reference/v1.0/resources/user.md
Labels: area: Azure AD, ready to merge, internal, content review complete

#21165 Update applicationsignindetailedsummary-get.md
  api-reference/beta/api/applicationsignindetailedsummary-get.md
Labels: ready to merge, internal

#21178 Edits in PR 20804
  api-reference/beta/api/customappscope-delete.md
  api-reference/beta/api/customappscope-get.md
  api-reference/beta/api/customappscope-update.md
  api-reference/beta/api/unifiedrbacapplication-list-customappscopes.md
  api-reference/beta/api/unifiedrbacapplication-post-customappscope.md
  api-reference/beta/resources/customappscope.md
  api-reference/beta/toc.yml
Labels: external

#18778 Adding new chat manage delete permissions
  changelog/Microsoft.Teams.GraphSvc.json
  concepts/permissions-reference.md
Labels: ready to merge, internal, content review complete

#21179 fix doc bug in deviceregistrationpolicy-update.md
  api-reference/beta/api/deviceregistrationpolicy-update.md
Labels: ready to merge, internal

#20965 Promote device properties from beta to v1.0
  api-reference/v1.0/resources/device.md
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, ready to merge, internal, content review complete

#21191 Edits in PR 20996
  api-reference/beta/api/virtualappointment-getvirtualappointmentjoinweburl.md
  api-reference/beta/resources/onlinemeeting.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/virtualappointment-getvirtualappointmentjoinweburl.md
  api-reference/v1.0/resources/onlinemeeting.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.Skype.Calling.json
Labels: external

#21192 Edits in PR 20996
  api-reference/beta/api/onlinemeeting-getvirtualappointmentjoinweburl.md
  api-reference/beta/resources/onlinemeeting.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/onlinemeeting-getvirtualappointmentjoinweburl.md
  api-reference/v1.0/resources/onlinemeeting.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.Skype.Calling.json
  redirects/.openpublishing.redirection.0523.json
Labels: external

#20786 Include sample request and response to dereference a remote item
  api-reference/beta/api/drive-sharedwithme.md
  api-reference/v1.0/api/drive-sharedwithme.md
Labels: ready to merge, internal, content review complete, review feedback addressed

#21090 Update group.md
  api-reference/v1.0/resources/group.md
Labels: ready to merge

#20670 GraphDoc_ActiveInactiveAssignments
  api-reference/beta/api/educationassignment-activate.md
  api-reference/beta/api/educationassignment-deactivate.md
  api-reference/beta/api/educationassignment-get.md
  api-reference/beta/resources/educationassignment.md
  api-reference/beta/toc.yml
  changelog/Microsoft.EducationAssignment.json
Labels: ready to merge, internal, content review complete

#21201 Update preferredTokenSigningKeyEndDateTime
  api-reference/beta/resources/serviceprincipal.md
Labels: external, ready to merge

#20929 Introduce concept page discussing VE notifications
  concepts/changenotifications-for-virtualevent.md
  concepts/toc.yml
Labels: ready to merge, internal, content review complete

#21204 Edits in PR 21010
  api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-put-identitysynchronization.md
  api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md
  api-reference/beta/api/crosstenantidentitysyncpolicypartner-delete.md
  api-reference/beta/api/crosstenantidentitysyncpolicypartner-get.md
  api-reference/beta/api/crosstenantidentitysyncpolicypartner-update.md
  api-reference/beta/resources/crosstenantaccesspolicy-overview.md
  api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md
  api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md
  api-reference/beta/resources/crosstenantidentitysyncpolicypartner.md
  api-reference/beta/resources/crosstenantusersyncinbound.md
  api-reference/beta/resources/inboundoutboundpolicyconfiguration.md
  api-reference/v1.0/api/crosstenantaccesspolicyconfigurationpartner-put-identitysynchronization.md
  api-reference/v1.0/api/crosstenantaccesspolicyconfigurationpartner-update.md
  api-reference/v1.0/api/crosstenantidentitysyncpolicypartner-delete.md
  api-reference/v1.0/api/crosstenantidentitysyncpolicypartner-get.md
  api-reference/v1.0/api/crosstenantidentitysyncpolicypartner-update.md
  api-reference/v1.0/resources/crosstenantaccesspolicy-overview.md
  api-reference/v1.0/resources/crosstenantaccesspolicyconfigurationdefault.md
  api-reference/v1.0/resources/crosstenantaccesspolicyconfigurationpartner.md
  api-reference/v1.0/resources/crosstenantidentitysyncpolicypartner.md
  api-reference/v1.0/resources/crosstenantusersyncinbound.md
  api-reference/v1.0/resources/inboundoutboundpolicyconfiguration.md
  changelog/Microsoft.DirectoryServices.json
Labels: external

#21213 Revert "Introduce concept page discussing VE notifications"
  concepts/changenotifications-for-virtualevent.md
  concepts/toc.yml
Labels: internal

#21214 Merge to publish (OOB).
  concepts/changenotifications-for-virtualevent.md
  concepts/toc.yml
Labels: do not merge, internal

#21211 Minor and typo fixes in attendancerecord.md and onlinemeeting.md.
  api-reference/beta/resources/attendancerecord.md
  api-reference/v1.0/resources/attendancerecord.md
  api-reference/v1.0/resources/onlinemeeting.md
Labels: external, ready to merge

#21194 Update listitemversion.md
  api-reference/beta/resources/listitemversion.md
  api-reference/v1.0/resources/listitemversion.md
Labels: external, ready to merge

#19783 [CloudPC] add new type cloudPcManagementUserAssignmentResult
  api-reference/beta/resources/cloudpcprovisioningpolicy.md
  api-reference/beta/resources/cloudpcprovisioningpolicyassignment.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, content review complete

#19364 [CloudPC]add new property domainJoinConfiguration list for policy
  api-reference/beta/api/cloudpcprovisioningpolicy-get.md
  api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md
  api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md
  api-reference/beta/resources/cloudpcprovisioningpolicy.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, content review complete

#20082 [CloudPC] add property "cloudPcNamingTemplate" into policy entity
  api-reference/beta/resources/cloudpcprovisioningpolicy.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, content review complete

#21218 Edits in PR 21010
  api-reference/beta/api/crosstenantaccesspolicy-list-partners.md
  api-reference/beta/api/crosstenantaccesspolicy-post-partners.md
  api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md
  api-reference/v1.0/api/crosstenantaccesspolicy-list-partners.md
  api-reference/v1.0/api/crosstenantaccesspolicy-post-partners.md
  api-reference/v1.0/api/crosstenantaccesspolicyconfigurationpartner-delete.md
  changelog/Microsoft.DirectoryServices.json
Labels: external

#21229 Update plannerrostermember-get.md
  api-reference/beta/api/plannerrostermember-get.md
Labels: external

#21228 Update sharepointsettings-update.md
  api-reference/v1.0/api/sharepointsettings-update.md
Labels: external

#21227 Update sharepointsettings-update.md
  api-reference/beta/api/sharepointsettings-update.md
Labels: external

#21226 Update sharepointsettings-get.md
  api-reference/beta/api/sharepointsettings-get.md
Labels: external

#21225 Update sharepointsettings-get.md
  api-reference/v1.0/api/sharepointsettings-get.md
Labels: external

#21224 Update toc.yml
  api-reference/v1.0/toc.yml
Labels: external

#21223 Update toc.yml
  api-reference/beta/toc.yml
Labels: external

#21221 Update connecting-external-content-api-limits.md
  concepts/connecting-external-content-api-limits.md
Labels: external

#21220 Update sharepointsettings.md
  api-reference/beta/resources/sharepointsettings.md
Labels: external

#21219 Update sharepointsettings.md
  api-reference/v1.0/resources/sharepointsettings.md
Labels: external

#21243 Fix links in the Microsoft.DirectoryServices changelog
  changelog/Microsoft.DirectoryServices.json
Labels: ready to merge, internal

#21250 Edits in PR 21240
  concepts/data-connect-troubleshooting.md
  includes/data-connect-quickstart-01.md
  includes/data-connect-quickstart-02.md
  includes/data-connect-quickstart-03.md
Labels: external

#21251 Update plannerroster-list-members.md
  api-reference/beta/api/plannerroster-list-members.md
Labels: external

#20448 Add v1.0 docs for allowUserConsentForRiskyApps
  api-reference/beta/api/authorizationpolicy-update.md
  api-reference/beta/resources/authorizationpolicy.md
  api-reference/v1.0/api/authorizationpolicy-get.md
  api-reference/v1.0/api/authorizationpolicy-update.md
  api-reference/v1.0/resources/authorizationpolicy.md
  changelog/Microsoft.DirectoryServices.json
Labels: ready to merge, internal, content review complete

#21237 Update Key Credentials patch info
  api-reference/beta/resources/keycredential.md
Labels: area: Azure AD, ready to merge, internal, content review complete

#20996 v1.0 function documentation
  api-reference/beta/api/virtualappointment-delete.md
  api-reference/beta/api/virtualappointment-get.md
  api-reference/beta/api/virtualappointment-getvirtualappointmentjoinweburl.md
  api-reference/beta/api/virtualappointment-put.md
  api-reference/beta/api/virtualappointment-update.md
  api-reference/beta/resources/onlinemeeting.md
  api-reference/beta/resources/virtualappointment.md
  api-reference/beta/resources/virtualappointmentsettings.md
  api-reference/beta/resources/virtualappointmentuser.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/virtualappointment-getvirtualappointmentjoinweburl.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.Skype.Calling.json
Labels: ready to merge, internal, content review complete

#21267 Update plannerrostermember-delete.md
  api-reference/beta/api/plannerrostermember-delete.md
Labels: external

#21266 Update plannerroster-post-members.md
  api-reference/beta/api/plannerroster-post-members.md
Labels: external

#21259 Fix missing double quotes on deviceregistrationpolicy
  api-reference/beta/api/deviceregistrationpolicy-update.md
Labels: external

#20701 Added application permissions for presence setStatusMessage
  api-reference/beta/api/presence-setstatusmessage.md
  changelog/Microsoft.Skype.Calling.json
Labels: ready to merge, internal, content review complete

#20916 Enable Teams Report APIs in Gallatin
  api-reference/beta/resources/report.md
Labels: ready to merge, internal, content review complete

#20490 Add user, group and contact service provisioning errors.
  api-reference/beta/api/group-get.md
  api-reference/beta/api/group-list.md
  api-reference/beta/api/group-retryserviceprovisioning.md
  api-reference/beta/api/orgcontact-get.md
  api-reference/beta/api/orgcontact-retryserviceprovisioning.md
  api-reference/beta/api/user-retryserviceprovisioning.md
  api-reference/beta/resources/group.md
  api-reference/beta/resources/orgcontact.md
  api-reference/beta/resources/serviceprovisioningerror.md
  api-reference/beta/resources/serviceprovisioningxmlerror.md
  api-reference/beta/resources/user.md
  api-reference/beta/toc.yml
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, ready to merge, internal, content review complete, review feedback addressed

#21185 Add mapping data flow url
  concepts/data-connect-datasets.md
  concepts/data-connect-troubleshooting.md
Labels: ready to merge, internal, content review complete

#20975 docs: adds taxonomy-picker.md to document mgt-taxonomy-picker
  concepts/toolkit/components/images/mgt-taxonomy-picker-locale-term.png
  concepts/toolkit/components/images/mgt-taxonomy-picker-term.png
  concepts/toolkit/components/images/mgt-taxonomy-picker-termset.png
  concepts/toolkit/components/taxonomy-picker.md
Labels: ready to merge, internal, content review complete

#21255 Update accesspackageassignmentpolicy-update.md
  api-reference/beta/api/accesspackageassignmentpolicy-update.md
  api-reference/v1.0/api/accesspackageassignmentpolicy-update.md
Labels: area: Azure AD, bug: documentation, ready to merge, internal, content review complete

#21260 Minor doc fixes
  api-reference/beta/resources/defaultuserrolepermissions.md
  api-reference/beta/toc.yml
  api-reference/v1.0/resources/defaultuserrolepermissions.md
  api-reference/v1.0/toc.yml
  concepts/group-directory-settings.md
Labels: area: Azure AD, ready to merge, internal

#21271 Fixes changelog entry.
  changelog/Microsoft.Skype.Calling.json
Labels: ready to merge, internal

#21134 Updating user oof days
  api-reference/beta/resources/attacksimulationuser.md
  api-reference/beta/resources/usersimulationdetails.md
  changelog/Microsoft.Security.AttackSimulation.json
Labels: ready to merge, ready for content review, internal

#20968 Adds documentation for new on-premises directory synchronization configuration properties to MSGraph beta
  api-reference/beta/api/onpremisesdirectorysynchronization-get.md
  api-reference/beta/resources/onpremisescurrentexportdata.md
  api-reference/beta/resources/onpremisesdirectorysynchronizationconfiguration.md
  api-reference/beta/resources/onpremiseswritebackconfiguration.md
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, ready to merge, internal, content review complete, invalid links

#21155 Adding watermark participant restrictedExperience doc in V1.0
  api-reference/beta/resources/watermarkprotectionvalues.md
  api-reference/v1.0/resources/onlinemeetingrestricted.md
  api-reference/v1.0/resources/participant.md
  api-reference/v1.0/resources/watermarkprotectionvalues.md
  changelog/Microsoft.Skype.Calling.json
  concepts/cloud-communications-watermark-meeting.md
Labels: ready to merge, content review complete

#21180 removing note for app context installation in chat and Teams app settings known issue
  api-reference/beta/api/chat-post-installedapps.md
  api-reference/beta/api/chat-teamsappinstallation-upgrade.md
  api-reference/beta/api/teamsappsettings-update.md
  concepts/known-issues.md
Labels: ready to merge, internal, content review complete, schema live

#21286 Update application-post-calls.md
  api-reference/beta/api/application-post-calls.md
  api-reference/v1.0/api/application-post-calls.md
Labels: external, ready to merge

#21298 Edits in PR 20894
  api-reference/beta/api/allowedvalue-get.md
  api-reference/beta/api/allowedvalue-update.md
  api-reference/beta/api/attributeset-get.md
  api-reference/beta/api/attributeset-update.md
  api-reference/beta/api/customsecurityattributedefinition-get.md
  api-reference/beta/api/customsecurityattributedefinition-list-allowedvalues.md
  api-reference/beta/api/customsecurityattributedefinition-post-allowedvalues.md
  api-reference/beta/api/customsecurityattributedefinition-update.md
  api-reference/beta/api/directory-list-attributesets.md
  api-reference/beta/api/directory-list-customsecurityattributedefinitions.md
  api-reference/beta/api/directory-post-attributesets.md
  api-reference/beta/api/directory-post-customsecurityattributedefinitions.md
  api-reference/beta/resources/allowedvalue.md
  api-reference/beta/resources/attributeset.md
  api-reference/beta/resources/custom-security-attributes-overview.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/allowedvalue-get.md
  api-reference/v1.0/api/allowedvalue-update.md
  api-reference/v1.0/api/attributeset-get.md
  api-reference/v1.0/api/attributeset-update.md
  api-reference/v1.0/api/customsecurityattributedefinition-get.md
  api-reference/v1.0/api/customsecurityattributedefinition-list-allowedvalues.md
  api-reference/v1.0/api/customsecurityattributedefinition-post-allowedvalues.md
  api-reference/v1.0/api/customsecurityattributedefinition-update.md
  api-reference/v1.0/api/directory-list-attributesets.md
  api-reference/v1.0/api/directory-list-customsecurityattributedefinitions.md
  api-reference/v1.0/api/directory-post-attributesets.md
  api-reference/v1.0/api/directory-post-customsecurityattributedefinitions.md
  api-reference/v1.0/resources/allowedvalue.md
  api-reference/v1.0/resources/attributeset.md
  api-reference/v1.0/resources/custom-security-attributes-overview.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.DirectoryServices.json
Labels: external

#21306 Edits in PR 21240
  includes/data-connect-quickstart-01.md
  includes/data-connect-quickstart-02.md
  includes/data-connect-quickstart-03.md
  includes/data-connect-quickstart-05.md
  includes/data-connect-quickstart-06.md
  includes/data-connect-quickstart-07.md
  includes/data-connect-quickstart-10.md
Labels: external

#21307 Edits in PR 21240
  concepts/images/data-connect-synapse-publishall.png
  concepts/images/data-connect-synapse-validateall.png
  includes/data-connect-quickstart-06.md
Labels: external

#21297 Update planneruser-list-rosterplans.md
  api-reference/beta/api/planneruser-list-rosterplans.md
Labels: external

#21296 Update plannerroster-list-plans.md
  api-reference/beta/api/plannerroster-list-plans.md
Labels: external

#21295 Update swapshiftschangerequest-list.md
  api-reference/v1.0/api/swapshiftschangerequest-list.md
Labels: external

#21293 Update toc.yml
  api-reference/beta/toc.yml
Labels: external

#21294 Update swapshiftschangerequest-list.md
  api-reference/beta/api/swapshiftschangerequest-list.md
Labels: external

#21292 Update site-delete-permission.md
  api-reference/beta/api/site-delete-permission.md
Labels: external

#21291 Update site-update-permission.md
  api-reference/beta/api/site-update-permission.md
Labels: external

#21290 Update site-get-permission.md
  api-reference/beta/api/site-get-permission.md
Labels: external

#21289 Update site-post-permissions.md
  api-reference/beta/api/site-post-permissions.md
Labels: external

#21288 Update site-list-permissions.md
  api-reference/beta/api/site-list-permissions.md
Labels: external

#20487 Update authorizationpolicy.md
  api-reference/beta/resources/authorizationpolicy.md
Labels: ready to merge, internal, content review complete

#21193 Graph API reference docs for custom extensions and onTokenIssuanceStart
  api-reference/beta/api/authenticationeventlistener-delete.md
  api-reference/beta/api/authenticationeventlistener-get.md
  api-reference/beta/api/authenticationeventlistener-update.md
  api-reference/beta/api/customauthenticationextension-delete.md
  api-reference/beta/api/customauthenticationextension-get.md
  api-reference/beta/api/customauthenticationextension-update.md
  api-reference/beta/api/customauthenticationextension-validateauthenticationconfiguration.md
  api-reference/beta/api/identitycontainer-list-authenticationeventlisteners.md
  api-reference/beta/api/identitycontainer-list-customauthenticationextensions.md
  api-reference/beta/api/identitycontainer-post-authenticationeventlisteners.md
  api-reference/beta/api/identitycontainer-post-customauthenticationextensions.md
  api-reference/beta/resources/authenticationconditionapplication.md
  api-reference/beta/resources/authenticationconditions.md
  api-reference/beta/resources/authenticationconditionsapplications.md
  api-reference/beta/resources/authenticationconfigurationvalidation.md
  api-reference/beta/resources/authenticationeventlistener.md
  api-reference/beta/resources/customauthenticationextension.md
  api-reference/beta/resources/customcalloutextension.md
  api-reference/beta/resources/customextensionclientconfiguration.md
  api-reference/beta/resources/customextensionendpointconfiguration.md
  api-reference/beta/resources/httprequestendpoint.md
  api-reference/beta/resources/identitycontainer.md
  api-reference/beta/resources/ontokenissuancestartcustomextension.md
  api-reference/beta/resources/ontokenissuancestartcustomextensionhandler.md
  api-reference/beta/resources/ontokenissuancestarthandler.md
  api-reference/beta/resources/ontokenissuancestartlistener.md
  api-reference/beta/resources/ontokenissuancestartreturnclaim.md
  api-reference/beta/toc.yml
  changelog/Microsoft.CPIM.json
  concepts/permissions-reference.md
Labels: area: Azure AD, ready to merge, internal, Build23, content review complete

#21274 Add ms.prod to change tracking docs
  api-reference/beta/api/user-assignlicense.md
  api-reference/beta/resources/credentialuserregistrationcount.md
  api-reference/v1.0/api/user-assignlicense.md
  concepts/delta-query-events.md
  concepts/delta-query-groups.md
  concepts/delta-query-messages.md
  concepts/delta-query-overview.md
  concepts/delta-query-users.md
  concepts/deployments.md
  concepts/identitygovernance-lifecycleworkflows-task-arguments.md
Labels: area: Azure AD, ready to merge, review feedback addressed

#21305 fixing duplicates in beta
  api-reference/beta/api/privilegedaccessgroup-list-eligibilityschedulerequests.md
  api-reference/beta/api/privilegedaccessgroup-list-eligibilityschedules.md
  api-reference/beta/api/privilegedaccessgroup-post-assignmentschedulerequests.md
  api-reference/beta/api/privilegedaccessgroup-post-eligibilityschedulerequests.md
  api-reference/beta/api/privilegedaccessgroupeligibilityschedule-filterbycurrentuser.md
  api-reference/beta/api/privilegedaccessgroupeligibilityschedulerequest-get.md
Labels: ready to merge, internal

#20517 Add user isLicenseReconciliationNeeded property in beta
  api-reference/beta/resources/user.md
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, ready to merge, internal, content review complete

#20764 education grading categories
  api-reference/beta/api/educationassignment-delete-gradingcategory.md
  api-reference/beta/api/educationassignment-list-gradingcategory.md
  api-reference/beta/api/educationassignment-post-gradingcategory.md
  api-reference/beta/api/educationassignmentsettings-update.md
  api-reference/beta/api/educationgradingcategory-update.md
  api-reference/beta/resources/educationassignment.md
  api-reference/beta/resources/educationassignmentsettings.md
  api-reference/beta/resources/educationgradingcategory.md
  api-reference/beta/toc.yml
  changelog/Microsoft.EducationAssignment.json
Labels: ready to merge, internal, content review complete, review feedback addressed

#21313 Edits in PR 20791
  api-reference/beta/api/driveitem-getretentionlabel.md
  api-reference/beta/api/driveitem-lockorunlockrecord.md
  api-reference/beta/api/driveitem-removeretentionlabel.md
  api-reference/beta/api/driveitem-setretentionlabel.md
  changelog/Microsoft.FileServices.json
  concepts/metered-api-list.md
Labels: external

#21316 Include new items up to April 19.
  api-reference/beta/api/employeeexperienceuser-post-learningcourseactivities.md
  api-reference/beta/api/learningcourseactivity-update.md
  api-reference/beta/api/virtualappointment-delete.md
  api-reference/beta/api/virtualappointment-get.md
  api-reference/beta/api/virtualappointment-getvirtualappointmentjoinweburl.md
  api-reference/beta/api/virtualappointment-put.md
  api-reference/beta/api/virtualappointment-update.md
  api-reference/beta/resources/learningcourseactivity.md
  api-reference/beta/resources/virtualappointment.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Skype.Calling.json
  concepts/whats-new-overview.md
Labels: internal

#19767 Update create-team-post-minimal-go-snippets.md
  api-reference/v1.0/includes/snippets/go/create-team-post-minimal-go-snippets.md
Labels: external, ready to merge, review requested

#21222 [MGDC] Adding entry for new Datasets: Todotasks and Todotaskfolders
  concepts/data-connect-datasets.md
Labels: ready to merge, internal, content review complete

#21241 Updated roles and perms to access laps
  api-reference/beta/api/devicelocalcredentialinfo-get.md
  api-reference/beta/includes/rbac-for-apis/rbac-device-local-credentials-apis-read.md
Labels: area: Azure AD, ready to merge, internal, content review complete

#21319 chore: use class names for styling
  concepts/toolkit/components/agenda.md
  concepts/toolkit/components/file-list.md
  concepts/toolkit/components/file.md
  concepts/toolkit/components/login.md
  concepts/toolkit/components/people-picker.md
  concepts/toolkit/components/people.md
  concepts/toolkit/components/person-card.md
  concepts/toolkit/components/person.md
  concepts/toolkit/components/picker.md
  concepts/toolkit/components/tasks.md
  concepts/toolkit/components/taxonomy-picker.md
  concepts/toolkit/components/teams-channel-picker.md
  concepts/toolkit/components/todo.md
  concepts/toolkit/customize-components/style.md
Labels: ready to merge, ready for content review, internal

#21323 fixing duplicate in beta
  api-reference/beta/api/educationclass-post-category.md
Labels: ready to merge, internal

#21054 Removed unnecessary step from metered API setup and added additional …
  concepts/metered-api-setup.md
Labels: ready to merge, internal, content review complete

#21330 Include new items through end of April.
  concepts/whats-new-overview.md
Labels: internal

#21331 Refresh what's new topic for April.
  concepts/whats-new-overview.md
Labels: do not merge, internal

#21332 Update metered-api-setup.md
  concepts/metered-api-setup.md
Labels: external

#21196 Fix to beta
  concepts/tutorial-lifecycle-workflows-set-employeeleavedatetime.md
Labels: area: Azure AD, ready to merge, internal, content review complete

#21338 Minor doc fixes
  api-reference/beta/api/b2cidentityuserflow-get.md
  api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md
  api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md
  api-reference/beta/api/b2xidentityuserflow-get.md
  api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md
  api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md
  api-reference/beta/api/identityprovider-get.md
  api-reference/beta/api/identityuserflowattribute-get.md
  api-reference/beta/resources/appliedauthenticationeventlistener.md
  api-reference/beta/resources/authenticationeventhandlerresult.md
  api-reference/beta/resources/customextensioncalloutresult.md
  api-reference/v1.0/api/b2xidentityuserflow-get.md
  api-reference/v1.0/api/b2xidentityuserflow-list-identityproviders.md
  api-reference/v1.0/api/identityprovider-get.md
  api-reference/v1.0/api/identityuserflowattribute-get.md
Labels: area: Azure AD, ready to merge, internal

#21139 Removing ".Shared" requirement
  api-reference/beta/api/user-findmeetingtimes.md
  api-reference/v1.0/api/user-findmeetingtimes.md
Labels: ready to merge, internal, customer support issue, content review complete

#21348 Update delegatedadminrelationship.md
  api-reference/v1.0/resources/delegatedadminrelationship.md
Labels: external

#21347 Update delegatedadminrelationship.md
  api-reference/beta/resources/delegatedadminrelationship.md
Labels: external

#19914 Add SharedWithContainers field to Planner's Plan
  api-reference/beta/api/plannerplan-get.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/plannerplan.md
  api-reference/beta/resources/plannerplancontainer.md
  api-reference/beta/resources/plannersharedwithcontainer.md
  changelog/Microsoft.Office.Tasks.json
Labels: ready to merge, internal, content review complete

#20401 Export API - Add messageHistory support in v1
  api-reference/v1.0/api/channel-list-messages.md
  api-reference/v1.0/api/chat-list-messages.md
  api-reference/v1.0/api/chat-post-messages.md
  api-reference/v1.0/api/chatmessage-delta.md
  api-reference/v1.0/api/chatmessage-get.md
  api-reference/v1.0/api/chatmessage-list-replies.md
  api-reference/v1.0/api/chatmessage-post-replies.md
  api-reference/v1.0/api/chatmessage-post.md
  api-reference/v1.0/api/chatmessage-update.md
  api-reference/v1.0/resources/chatmessage.md
  api-reference/v1.0/resources/chatmessagehistoryitem.md
  api-reference/v1.0/resources/enums.md
  changelog/Microsoft.Teams.GraphSvc.json
Labels: ready to merge, internal, content review complete

#21337 Update create-client.md
  concepts/sdks/create-client.md
Labels: ready to merge, internal

#21350 Updating the path for chat message set/unset Reaction
  api-reference/beta/api/chatmessage-setreaction.md
  api-reference/beta/api/chatmessage-unsetreaction.md
Labels: ready to merge, internal, content review complete

#21053 Promote allowedToCreateTenants from beta to v1
  api-reference/v1.0/resources/defaultuserrolepermissions.md
  changelog/Microsoft.DirectoryServices.json
Labels: ready to merge, content review complete

#21362 Included a few items for May.
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: internal

#21363 Refresh what's new topic with some May items.
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: do not merge, internal

#21361 Update outlookcategory.md
  api-reference/beta/resources/outlookcategory.md
Labels: external

#21360 Update outlookcategory.md
  api-reference/v1.0/resources/outlookcategory.md
Labels: external

#21364 Minor doc fixes
  api-reference/beta/resources/group.md
  api-reference/beta/resources/grouplifecyclepolicy.md
  api-reference/beta/resources/groups-overview.md
  api-reference/beta/toc.yml
  api-reference/v1.0/resources/group.md
  api-reference/v1.0/resources/grouplifecyclepolicy.md
  api-reference/v1.0/resources/groups-overview.md
  api-reference/v1.0/toc.yml
  concepts/group-set-options.md
  concepts/index.yml
  concepts/microsoft365-groups-concept-overview.md
  concepts/migrate-azure-ad-graph-overview.md
  concepts/overview-major-services.md
  concepts/overview.md
  concepts/toc.yml
  redirects/.openpublishing.redirection.0423.json
Labels: area: Azure AD, ready to merge, internal

#19923 Multigeo site enumeration API support
  api-reference/beta/api/site-getallsites.md
  api-reference/beta/api/site-list.md
  api-reference/beta/resources/site.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/site-getallsites.md
  api-reference/v1.0/api/site-list.md
  api-reference/v1.0/resources/site.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.FileServices.json
Labels: ready to merge, internal, content review complete

#21370 Merge to publish.
  api-reference/beta/api/site-getallsites.md
  api-reference/beta/api/site-list.md
  api-reference/beta/resources/group.md
  api-reference/beta/resources/grouplifecyclepolicy.md
  api-reference/beta/resources/groups-overview.md
  api-reference/beta/resources/outlookcategory.md
  api-reference/beta/resources/site.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/site-getallsites.md
  api-reference/v1.0/api/site-list.md
  api-reference/v1.0/resources/group.md
  api-reference/v1.0/resources/grouplifecyclepolicy.md
  api-reference/v1.0/resources/groups-overview.md
  api-reference/v1.0/resources/outlookcategory.md
  api-reference/v1.0/resources/site.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.FileServices.json
  concepts/group-set-options.md
  concepts/index.yml
  concepts/microsoft365-groups-concept-overview.md
  concepts/migrate-azure-ad-graph-overview.md
  concepts/overview-major-services.md
  concepts/overview.md
  concepts/toc.yml
  redirects/.openpublishing.redirection.0423.json
Labels: do not merge, internal

#21374 Add items to what's new topic through 5/15.
  api-reference/beta/resources/attacksimulationuser.md
  api-reference/beta/resources/educationassignmentsettings.md
  api-reference/beta/toc.yml
  changelog/Microsoft.CloudManagedDesktop.json
  changelog/Microsoft.DirectoryServices.json
  concepts/whats-new-overview.md
Labels: internal

#21375 Refresh what's new topic through 5/15.
  api-reference/beta/resources/attacksimulationuser.md
  api-reference/beta/resources/educationassignmentsettings.md
  api-reference/beta/toc.yml
  changelog/Microsoft.CloudManagedDesktop.json
  changelog/Microsoft.DirectoryServices.json
  concepts/whats-new-overview.md
Labels: internal

#21371 Update onenote.md
  api-reference/v1.0/resources/onenote.md
Labels: external

#21377 Multigeo site enumeration patch
  api-reference/beta/api/site-getallsites.md
  api-reference/v1.0/api/site-getallsites.md
Labels: ready to merge, internal, content review complete

#21380 Minor doc fixes
  api-reference/beta/api/subscribedsku-get.md
  api-reference/beta/api/subscribedsku-list.md
  api-reference/beta/resources/subscribedsku.md
  api-reference/v1.0/api/subscribedsku-get.md
  api-reference/v1.0/api/subscribedsku-list.md
  api-reference/v1.0/resources/subscribedsku.md
Labels: area: Azure AD, ready to merge, internal

#20186 MV Extension API Updates
  api-reference/beta/api/application-list-extensionproperty.md
  api-reference/beta/api/application-post-extensionproperty.md
  api-reference/beta/resources/extensionproperty.md
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, ready to merge, internal, content review complete, schema live

#21382 Added information regarding Access to OData is disabled error
  concepts/resolve-auth-errors.md
  concepts/use-postman.md
Labels: ready to merge, ready for content review, internal

#21384 Merge to publish.
  api-reference/beta/api/application-list-extensionproperty.md
  api-reference/beta/api/application-post-extensionproperty.md
  api-reference/beta/api/site-getallsites.md
  api-reference/beta/api/subscribedsku-get.md
  api-reference/beta/api/subscribedsku-list.md
  api-reference/beta/resources/extensionproperty.md
  api-reference/beta/resources/subscribedsku.md
  api-reference/v1.0/api/site-getallsites.md
  api-reference/v1.0/api/subscribedsku-get.md
  api-reference/v1.0/api/subscribedsku-list.md
  api-reference/v1.0/resources/onenote.md
  api-reference/v1.0/resources/subscribedsku.md
  changelog/Microsoft.DirectoryServices.json
  concepts/resolve-auth-errors.md
  concepts/use-postman.md
Labels: internal

#21386 Edits in PR 20894
  api-reference/beta/resources/allowedvalue.md
  api-reference/beta/resources/attributeset.md
  api-reference/beta/resources/customsecurityattributedefinition.md
  api-reference/beta/toc.yml
  api-reference/v1.0/resources/allowedvalue.md
  api-reference/v1.0/resources/attributeset.md
  api-reference/v1.0/resources/customsecurityattributedefinition.md
  api-reference/v1.0/toc.yml
  concepts/custom-security-attributes-examples.md
Labels: external

#21385 Included new items through May 22.
  api-reference/beta/api/site-getallsites.md
  api-reference/beta/api/site-list.md
  api-reference/v1.0/api/site-getallsites.md
  api-reference/v1.0/api/site-list.md
  changelog/Microsoft.DirectoryServices.json
  concepts/whats-new-overview.md
Labels: do not merge, internal

#21387 Refresh what's new topic through May 22.
  api-reference/beta/api/site-getallsites.md
  api-reference/beta/api/site-list.md
  api-reference/v1.0/api/site-getallsites.md
  api-reference/v1.0/api/site-list.md
  changelog/Microsoft.DirectoryServices.json
  concepts/whats-new-overview.md
Labels: internal

#21399 Update securescorecontrolprofile.md
  api-reference/v1.0/resources/securescorecontrolprofile.md
Labels: external

#21359 Fix Update API url for LearningCourseActivities
  api-reference/beta/api/learningcourseactivity-update.md
Labels: ready to merge, internal, content review complete

#21368 EM assignment policy update: add table description for request body
  api-reference/v1.0/api/accesspackageassignmentpolicy-update.md
Labels: area: Azure AD, ready to merge, internal, content review complete

#21389 Minor doc fixes
  changelog/Microsoft.IdentityProtectionServices.json
  concepts/webhooks.md
Labels: area: Azure AD, ready to merge, internal

#21397 fixing new duplicates in beta
  api-reference/beta/api/authenticationeventsflow-update.md
  api-reference/beta/api/onattributecollectionexternalusersselfservicesignup-delete-attributes.md
  api-reference/beta/api/onattributecollectionexternalusersselfservicesignup-post-attributes.md
Labels: ready to merge, internal

#19207 Update Office 365 Connected Services Documentation
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
  concepts/office-365-connected-services.md
  concepts/toc.yml
Labels: ready to merge, internal, content review complete

#21354 Update the max size value limitation.
  api-reference/beta/resources/searchrequest.md
  api-reference/v1.0/resources/searchrequest.md
Labels: ready to merge, internal, content review complete
