Repository microsoftgraph/microsoft-graph-docs, pull requests merged in 2023-01, with the labels that each got.

#19745 Edits in PR 18884
  api-reference/beta/api/attacksimulationroot-create-simulation.md
  api-reference/beta/api/attacksimulationroot-delete-simulation.md
  api-reference/beta/api/attacksimulationroot-get-payload.md
  api-reference/beta/api/attacksimulationroot-get-payloadsdetails.md
  api-reference/beta/api/attacksimulationroot-list-payloads.md
  api-reference/beta/api/attacksimulationroot-update-simulation.md
  api-reference/beta/resources/attacksimulationoperation.md
  api-reference/beta/resources/coachmarklocation.md
  api-reference/beta/resources/emailpayloaddetail.md
  api-reference/beta/resources/includeallaccounttargetcontent.md
  api-reference/beta/resources/payload.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Security.AttackSimulation.json
  concepts/permissions-reference.md
Labels: external

#19458 [CloudPC]Added "getSharedUseLicenseUsageReport" API to and updated "cloudPcRep…
  api-reference/beta/api/cloudpcreports-getshareduselicenseusagereport.md
  api-reference/beta/resources/cloudpcexportjob.md
  api-reference/beta/resources/cloudpcreports.md
  api-reference/beta/toc.yml
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, internal, content review complete

#19755 Daily publishing
  api-reference/beta/api/cloudpcreports-getshareduselicenseusagereport.md
  api-reference/beta/resources/cloudpcexportjob.md
  api-reference/beta/resources/cloudpcreports.md
  api-reference/beta/toc.yml
  changelog/Microsoft.CloudManagedDesktop.json
Labels: do not merge, internal

#19759 Edits in PR 18884
  api-reference/beta/api/attacksimulationroot-list-payloads.md
  api-reference/beta/resources/emailpayloaddetail.md
  api-reference/beta/resources/payload.md
  changelog/Microsoft.Security.AttackSimulation.json
Labels: external

#19756 Updated Table parameters
  api-reference/beta/includes/identitygovernance-lifecycleworkflows-tasks-table.md
Labels: ready to merge, internal

#19760 Edits in PR 18359
  api-reference/beta/resources/cloudpconpremisesconnection.md
  api-reference/beta/resources/cloudpcsupportedregion.md
Labels: external

#19747 Update teamworkdeviceconfiguration-get.md
  api-reference/beta/api/teamworkdeviceconfiguration-get.md
Labels: external

#19746 Update teamworkdevicehealth-get.md
  api-reference/beta/api/teamworkdevicehealth-get.md
Labels: external

#19739 Fix Broken Links in "Known Limitations" Section
  concepts/search-concept-chat-messages.md
Labels: external

#19711 Update windowsupdates-deployment-update.md
  api-reference/beta/api/windowsupdates-deployment-update.md
Labels: external

#19703 maximum duration is 62 days, not 42
  concepts/outlook-get-free-busy-schedule.md
Labels: external

#19695 Update longrunningoperation.md
  api-reference/v1.0/resources/longrunningoperation.md
Labels: external

#19669 Spelling Error
  api-reference/beta/api/user-update.md
Labels: external

#19673 Typo "resouce"→"resource"
  api-reference/v1.0/resources/policy-overview.md
Labels: external

#19574 use docs important box for very important message
  concepts/auth-cloudsolutionprovider.md
Labels: external

#19580 Update user-list-mailfolders.md
  api-reference/v1.0/api/user-list-mailfolders.md
Labels: external

#19581 Update user-list-mailfolders.md
  api-reference/beta/api/user-list-mailfolders.md
Labels: external

#19607 Update print-list-connectors.md
  api-reference/v1.0/api/print-list-connectors.md
Labels: external

#19608 Update print-list-connectors.md
  api-reference/beta/api/print-list-connectors.md
Labels: external

#19628 Update dynamics-account.md
  api-reference/beta/resources/dynamics-account.md
Labels: external

#19643 change a name
  api-reference/v1.0/api/user-sendmail.md
Labels: external

#19665 Update dynamics-paymentterms.md
  api-reference/beta/resources/dynamics-paymentterms.md
Labels: external

#16691 VALIDATION ms.prod outlook
  api-reference/v1.0/resources/customtimezone.md
  api-reference/v1.0/resources/daylighttimezoneoffset.md
  api-reference/v1.0/resources/extensionschemaproperty.md
  api-reference/v1.0/resources/followupflag.md
  api-reference/v1.0/resources/genericerror.md
  api-reference/v1.0/resources/inferenceclassification.md
  api-reference/v1.0/resources/inferenceclassificationoverride.md
  api-reference/v1.0/resources/internetmessageheader.md
  api-reference/v1.0/resources/multivaluelegacyextendedproperty.md
Labels: external

#16692 VALIDATION ms.prod fixes
  api-reference/v1.0/resources/singlevaluelegacyextendedproperty.md
  api-reference/v1.0/resources/sizerange.md
  api-reference/v1.0/resources/sortfield.md
  api-reference/v1.0/resources/specialfolder.md
  api-reference/v1.0/resources/standardtimezoneoffset.md
  api-reference/v1.0/resources/textcolumn.md
  api-reference/v1.0/resources/thumbnail.md
  api-reference/v1.0/resources/thumbnailset.md
  api-reference/v1.0/resources/timestamp.md
  api-reference/v1.0/resources/timezonebase.md
  api-reference/v1.0/resources/timezoneinformation.md
  api-reference/v1.0/resources/uploadsession.md
Labels: external

#19498 Update indexing limitations for graph connectors
  api-reference/beta/resources/indexing-api-overview.md
  api-reference/v1.0/resources/indexing-api-overview.md
Labels: ready to merge, internal, content review complete

#19506 Update outlook-change-notifications-overview.md
  concepts/outlook-change-notifications-overview.md
Labels: ready to merge, internal, content review complete

#19639 Alphabetize 12 15 22
  api-reference/v1.0/resources/applemanagedidentityprovider.md
  api-reference/v1.0/resources/assignedplan.md
  api-reference/v1.0/resources/averagecomparativescore.md
  api-reference/v1.0/resources/b2xidentityuserflow.md
  api-reference/v1.0/resources/baseitem.md
  api-reference/v1.0/resources/basicauthentication.md
  api-reference/v1.0/resources/bookingcustomer.md
  api-reference/v1.0/resources/builtinidentityprovider.md
  api-reference/v1.0/resources/bundle.md
  api-reference/v1.0/resources/callrecords-clientuseragent.md
  api-reference/v1.0/resources/callrecords-media.md
  api-reference/v1.0/resources/callrecords-participantendpoint.md
  api-reference/v1.0/resources/callrecords-segment.md
  api-reference/v1.0/resources/calltranscriptioninfo.md
  api-reference/v1.0/resources/channel.md
  api-reference/v1.0/resources/chartpoint.md
  api-reference/v1.0/resources/chatmessage.md
  api-reference/v1.0/resources/chatmessageattachment.md
  api-reference/v1.0/resources/chatmessagehostedcontent.md
  api-reference/v1.0/resources/chatmessagemention.md
  api-reference/v1.0/resources/claimsmapping.md
  api-reference/v1.0/resources/claimsmappingpolicy.md
  api-reference/v1.0/resources/cloudappsecuritysessioncontrol.md
  api-reference/v1.0/resources/columndefinition.md
Labels: ready to merge, internal, content review complete

#19721 Added example on how to use $filter parameter
  api-reference/beta/api/user-get.md
  api-reference/v1.0/api/user-get.md
Labels: external, ready to merge

#19775 Edits in PR 19641
  api-reference/beta/resources/meetinginfo.md
  api-reference/v1.0/api/application-post-calls.md
  api-reference/v1.0/resources/joinmeetingidmeetinginfo.md
  api-reference/v1.0/resources/meetinginfo.md
  changelog/Microsoft.Skype.Calling.json
Labels: external

#19777 Update plannerassignedtotaskboardtaskformat-get.md
  api-reference/v1.0/api/plannerassignedtotaskboardtaskformat-get.md
Labels: external

#19266 [Doc Issue][resource-id]
  api-reference/beta/resources/team.md
  api-reference/v1.0/resources/team.md
Labels: ready to merge, content review complete

#19247 [Doc Improvement][Update channel-post]
  api-reference/beta/api/channel-get-filesfolder.md
  api-reference/beta/api/channel-post.md
  api-reference/v1.0/api/channel-get-filesfolder.md
  api-reference/v1.0/api/channel-post.md
  concepts/known-issues.md
Labels: ready to merge, content review complete, review feedback addressed

#18359 [CloudPC] Add Supported Region region group parameter and add RPA box to CloudPCManagementService enum
  api-reference/beta/api/virtualendpoint-list-supportedregions.md
  api-reference/beta/resources/cloudpconpremisesconnection.md
  api-reference/beta/resources/cloudpcprovisioningpolicy.md
  api-reference/beta/resources/cloudpcsupportedregion.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, internal, content review complete, schema live

#19729 Alphabetize through printjobconfiguration.md
  api-reference/v1.0/resources/printercreateoperation.md
  api-reference/v1.0/resources/printerdefaults.md
  api-reference/v1.0/resources/printerlocation.md
  api-reference/v1.0/resources/printershare.md
  api-reference/v1.0/resources/printerstatus.md
  api-reference/v1.0/resources/printjob.md
  api-reference/v1.0/resources/printjobconfiguration.md
Labels: ready to merge, internal, content review complete

#19793 Fixed stray punctuation.
  changelog/Manual.NonWorkloadChanges.json
  changelog/Microsoft.AAD.Reporting.json
  changelog/Microsoft.Analytics.json
  changelog/Microsoft.DirectoryServices.json
  changelog/Microsoft.EducationAssignment.json
  changelog/Microsoft.Exchange.json
  changelog/Microsoft.FileServices.json
  changelog/Microsoft.Intune.json
  changelog/Microsoft.Office.Tasks.json
  changelog/Microsoft.SharePoint.json
  changelog/Microsoft.Skype.Calling.json
  changelog/Microsoft.Teams.Core.json
  changelog/Microsoft.ThreatAssessment.json
Labels: ready to merge, internal, invalid links

#19789 description of property avatarSize missing in table
  concepts/toolkit/components/person.md
Labels: external, ready to merge

#19801 Edits in PR 19641
  api-reference/beta/resources/meetinginfo.md
  changelog/Microsoft.Skype.Calling.json
Labels: external

#19804 Edits in PR 19640
  api-reference/beta/api/application-post-onlinemeetings.md
  api-reference/beta/api/onlinemeeting-get.md
  api-reference/beta/resources/onlinemeeting.md
  api-reference/v1.0/api/application-post-onlinemeetings.md
  api-reference/v1.0/api/onlinemeeting-get.md
  api-reference/v1.0/resources/joinmeetingidsettings.md
  api-reference/v1.0/resources/onlinemeeting.md
  changelog/Microsoft.Skype.Calling.json
Labels: external

#19800 import { CacheService } from '@microsoft/mgt-element'
  concepts/toolkit/customize-components/cache.md
Labels: external

#19805 Update search-qna.md
  api-reference/beta/resources/search-qna.md
Labels: external

#19796 Made sppkg prepreq more clear
  concepts/toolkit/get-started/mgt-spfx.md
Labels: external, ready to merge

#19698 [Doc Improvement][channel-post-messages]
  api-reference/beta/api/channel-post-messages.md
  api-reference/v1.0/api/channel-post-messages.md
Labels: ready to merge, internal

#19799 Update insights-customize-item-insights-privacy.md
  concepts/insights-customize-item-insights-privacy.md
Labels: ready to merge, internal, content review complete

#19725 [Doc Improvement][channel displayName]
  api-reference/beta/api/channel-post.md
  api-reference/v1.0/api/channel-post.md
Labels: ready to merge, conflicting, content review complete

#19723 [Doc Improvement][add-codesamples-teamsapp]
  api-reference/beta/resources/teamsapp.md
  api-reference/v1.0/resources/teamsapp.md
Labels: ready to merge, internal, content review complete

#19806 Merge to publish.
  api-reference/beta/api/channel-post-messages.md
  api-reference/beta/api/channel-post.md
  api-reference/beta/resources/search-qna.md
  api-reference/beta/resources/teamsapp.md
  api-reference/v1.0/api/channel-post-messages.md
  api-reference/v1.0/api/channel-post.md
  api-reference/v1.0/resources/teamsapp.md
  concepts/insights-customize-item-insights-privacy.md
  concepts/toolkit/customize-components/cache.md
  concepts/toolkit/get-started/mgt-spfx.md
Labels: do not merge, internal

#19817 Edits in PR 19015
  api-reference/beta/resources/businessscenario-overview.md
  api-reference/beta/resources/businessscenario-planner-overview.md
  concepts/planner-task-rules-overview.md
Labels: external

#19819 Edits in PR 18043
  api-reference/beta/api/industrydata-azuredatalakeconnector-delete.md
  api-reference/beta/api/industrydata-azuredatalakeconnector-get.md
  api-reference/beta/api/industrydata-azuredatalakeconnector-getuploadsession.md
  api-reference/beta/api/industrydata-azuredatalakeconnector-update.md
  api-reference/beta/api/industrydata-inboundfileflow-get.md
  api-reference/beta/api/industrydata-inboundfileflow-post.md
  api-reference/beta/api/industrydata-inboundfileflow-update.md
  api-reference/beta/api/industrydata-inboundflow-get.md
  api-reference/beta/api/industrydata-inboundflow-update.md
  api-reference/beta/api/industrydata-industrydataconnector-get.md
  api-reference/beta/api/industrydata-industrydataconnector-update.md
  api-reference/beta/api/industrydata-industrydataconnector-validate.md
  api-reference/beta/api/industrydata-industrydataroot-delete-dataconnectors.md
  api-reference/beta/api/industrydata-industrydataroot-delete-inboundflows.md
  api-reference/beta/api/industrydata-industrydataroot-delete-sourcesystems.md
  api-reference/beta/api/industrydata-industrydataroot-delete-years.md
  api-reference/beta/api/industrydata-industrydataroot-list-sourcesystems.md
  api-reference/beta/api/industrydata-industrydataroot-list-years.md
  api-reference/beta/api/industrydata-industrydatarun-get.md
  api-reference/beta/api/industrydata-industrydatarun-getstatistics.md
  api-reference/beta/api/industrydata-operation-get.md
  api-reference/beta/api/industrydata-referencedefinition-get.md
  api-reference/beta/api/industrydata-rolegroup-get.md
  api-reference/beta/api/industrydata-sourcesystemdefinition-get.md
  api-reference/beta/api/industrydata-sourcesystemdefinition-update.md
  api-reference/beta/api/industrydata-yeartimeperioddefinition-get.md
  api-reference/beta/api/industrydata-yeartimeperioddefinition-update.md
  api-reference/beta/resources/industrydata-overview.md
  api-reference/images/industrydata-overview.png
  concepts/images/industrydata-overview.png
Labels: external

#19821 Update security-caseoperation.md
  api-reference/beta/resources/security-caseoperation.md
Labels: external

#19820 Update security-caseoperation.md
  api-reference/v1.0/resources/security-caseoperation.md
Labels: external

#19807 Minor update
  api-reference/beta/api/identitygovernance-lifecycleworkflowscontainer-post-customtaskextensions.md
Labels: area: Azure AD, ready to merge, internal, area: governance

#19114 Assignments and grades - customer scenarios
  concepts/msgraph-customer-assignmentgradedatafortool.md
  concepts/msgraph-customer-scenarios.md
  concepts/toc.yml
Labels: ready to merge, internal, content review complete

#19689 Assignments and grades - customer scenario 5
  concepts/msgraph-customer-teamsapps.md
Labels: do not merge, ready to merge, internal, content review complete

#19417 Add Gallatin Support Announcement
  concepts/deployments.md
Labels: ready to merge, internal, Ignite22, content review complete

#19640 GA Promotion - Schedule Meeting with joinMeetingIdSettings
  api-reference/beta/api/application-post-onlinemeetings.md
  api-reference/beta/api/onlinemeeting-get.md
  api-reference/beta/resources/onlinemeeting.md
  api-reference/v1.0/api/application-post-onlinemeetings.md
  api-reference/v1.0/api/onlinemeeting-get.md
  api-reference/v1.0/resources/joinmeetingidsettings.md
  api-reference/v1.0/resources/onlinemeeting.md
  changelog/Microsoft.Skype.Calling.json
Labels: ready to merge, internal, content review complete

#18325 Adding note for list channel api
  api-reference/beta/api/channel-list.md
  api-reference/v1.0/api/channel-list.md
Labels: ready to merge, internal, content review complete

#19641 GA Promotion - Join Meeting with joinMeetingIdMeetingInfo
  api-reference/beta/resources/meetinginfo.md
  api-reference/v1.0/api/application-post-calls.md
  api-reference/v1.0/resources/call.md
  api-reference/v1.0/resources/joinmeetingidmeetinginfo.md
  api-reference/v1.0/resources/meetinginfo.md
  changelog/Microsoft.Skype.Calling.json
Labels: ready to merge, internal, content review complete

#19824 Merge to publish.
  api-reference/beta/api/application-post-onlinemeetings.md
  api-reference/beta/api/channel-list.md
  api-reference/beta/api/identitygovernance-lifecycleworkflowscontainer-post-customtaskextensions.md
  api-reference/beta/api/onlinemeeting-get.md
  api-reference/beta/resources/meetinginfo.md
  api-reference/beta/resources/onlinemeeting.md
  api-reference/beta/resources/security-caseoperation.md
  api-reference/v1.0/api/application-post-calls.md
  api-reference/v1.0/api/application-post-onlinemeetings.md
  api-reference/v1.0/api/channel-list.md
  api-reference/v1.0/api/onlinemeeting-get.md
  api-reference/v1.0/resources/call.md
  api-reference/v1.0/resources/joinmeetingidmeetinginfo.md
  api-reference/v1.0/resources/joinmeetingidsettings.md
  api-reference/v1.0/resources/meetinginfo.md
  api-reference/v1.0/resources/onlinemeeting.md
  api-reference/v1.0/resources/security-caseoperation.md
  changelog/Microsoft.Skype.Calling.json
  concepts/deployments.md
  concepts/msgraph-customer-assignmentgradedatafortool.md
  concepts/msgraph-customer-scenarios.md
  concepts/msgraph-customer-teamsapps.md
  concepts/toc.yml
Labels: internal

#19835 merge main into alphabetize-1-2-23
  api-reference/beta/api/application-post-onlinemeetings.md
  api-reference/beta/api/channel-list.md
  api-reference/beta/api/channel-post-messages.md
  api-reference/beta/api/channel-post.md
  api-reference/beta/api/identitygovernance-lifecycleworkflowscontainer-post-customtaskextensions.md
  api-reference/beta/api/onlinemeeting-get.md
  api-reference/beta/resources/meetinginfo.md
  api-reference/beta/resources/onlinemeeting.md
  api-reference/beta/resources/search-qna.md
  api-reference/beta/resources/security-caseoperation.md
  api-reference/beta/resources/teamsapp.md
  api-reference/v1.0/api/application-post-calls.md
  api-reference/v1.0/api/application-post-onlinemeetings.md
  api-reference/v1.0/api/channel-list.md
  api-reference/v1.0/api/channel-post-messages.md
  api-reference/v1.0/api/channel-post.md
  api-reference/v1.0/api/onlinemeeting-get.md
  api-reference/v1.0/resources/call.md
  api-reference/v1.0/resources/joinmeetingidmeetinginfo.md
  api-reference/v1.0/resources/joinmeetingidsettings.md
  api-reference/v1.0/resources/meetinginfo.md
  api-reference/v1.0/resources/onlinemeeting.md
  api-reference/v1.0/resources/security-caseoperation.md
  api-reference/v1.0/resources/teamsapp.md
  changelog/Microsoft.Skype.Calling.json
  concepts/deployments.md
  concepts/insights-customize-item-insights-privacy.md
  concepts/msgraph-customer-assignmentgradedatafortool.md
  concepts/msgraph-customer-scenarios.md
  concepts/msgraph-customer-teamsapps.md
  concepts/toc.yml
  concepts/toolkit/customize-components/cache.md
  concepts/toolkit/get-started/mgt-spfx.md
Labels: internal

#19838 Edits in PR 19534
  concepts/msgraph-customer-build-tool-to-download-all-the-resources-from-assignment.md
  concepts/msgraph-customer-create-assignment-with-teamsapp-content-for-application.md
Labels: external

#19839 Update dynamics-customer-delete.md
  api-reference/beta/api/dynamics-customer-delete.md
Labels: external

#19766 Removing query parameter
  api-reference/beta/api/channel-list.md
  api-reference/v1.0/api/channel-list.md
Labels: ready to merge, internal, content review complete, review feedback addressed

#19808 Content freshness fixes
  concepts/device-relay-concept-overview.md
  concepts/how-to-pim-update-rules.md
  concepts/tutorial-assign-azureadroles.md
Labels: ready to merge, internal, review feedback addressed

#19814 Fix broken links (Identity)
  api-reference/beta/api/group-list-transitivemembers.md
  api-reference/beta/api/unifiedroledefinition-assignedprincipals.md
  api-reference/beta/resources/azure-ad-overview.md
  api-reference/beta/resources/groups-overview.md
  api-reference/beta/resources/webhooks.md
  api-reference/includes/limited-info.md
  api-reference/v1.0/api/group-list-transitivemembers.md
  api-reference/v1.0/resources/changenotificationcollection.md
  api-reference/v1.0/resources/groups-overview.md
  api-reference/v1.0/resources/webhooks.md
  concepts/changelog-archive.md
Labels: ready to merge, internal

#19813 Address feedback for ownerless apps examples
  concepts/tutorial-applications-basics.md
Labels: area: Azure AD, ready to merge, internal, area: applications

#19826 Reassign domain federation docs
  api-reference/beta/api/domain-post-federationconfiguration.md
  api-reference/beta/api/internaldomainfederation-delete.md
  api-reference/beta/api/internaldomainfederation-get.md
  api-reference/beta/api/internaldomainfederation-update.md
  api-reference/beta/resources/internaldomainfederation.md
  api-reference/beta/resources/signingcertificateupdatestatus.md
  api-reference/v1.0/api/domain-post-federationconfiguration.md
  api-reference/v1.0/api/internaldomainfederation-delete.md
  api-reference/v1.0/api/internaldomainfederation-get.md
  api-reference/v1.0/api/internaldomainfederation-update.md
  api-reference/v1.0/resources/internaldomainfederation.md
  api-reference/v1.0/resources/signingcertificateupdatestatus.md
Labels: area: Azure AD, ready to merge, internal

#19830 Minor fixes
  api-reference/beta/api/administrativeunit-post-members.md
  api-reference/beta/api/group-list-members.md
  api-reference/beta/api/opentypeextension-post-opentypeextension.md
  api-reference/includes/teams-subscription-notes.md
  api-reference/v1.0/api/administrativeunit-post-members.md
  api-reference/v1.0/api/group-list-members.md
  concepts/filter-query-parameter.md
Labels: area: Azure AD, ready to merge, internal

#19831 Clarify contributions DO's & DON'Ts
  CONTRIBUTING.md
Labels: ready to merge, internal

#19724 Adding documentation for the value (hiddenMembership) for team visibility type
  api-reference/beta/resources/teamvisibilitytype.md
  api-reference/v1.0/resources/teamvisibilitytype.md
Labels: ready to merge, internal, content review complete

#19738 identity governance: hide PSh in beta that is not correctly generated
  api-reference/beta/api/accesspackageassignmentpolicy-update.md
  api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentpolicies.md
  api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentrequests.md
  api-reference/v1.0/api/accesspackageassignmentpolicy-update.md
Labels: area: Azure AD, do not merge, ready to merge, internal, content review complete

#19015 Adding Business Scenario Related API documentation
  api-reference/beta/api/businessscenario-get.md
  api-reference/beta/api/businessscenario-update.md
  api-reference/beta/api/businessscenarioplanner-delete-tasks.md
  api-reference/beta/api/businessscenarioplanner-get.md
  api-reference/beta/api/businessscenarioplanner-getplan.md
  api-reference/beta/api/businessscenarioplanner-list-tasks.md
  api-reference/beta/api/businessscenarioplanner-post-tasks.md
  api-reference/beta/api/businessscenariotask-get.md
  api-reference/beta/api/businessscenariotask-update.md
  api-reference/beta/api/plannerplanconfiguration-delete-localizations.md
  api-reference/beta/api/plannerplanconfiguration-get.md
  api-reference/beta/api/plannerplanconfiguration-list-localizations.md
  api-reference/beta/api/plannerplanconfiguration-post-localizations.md
  api-reference/beta/api/plannerplanconfiguration-update.md
  api-reference/beta/api/plannerplanconfigurationlocalization-get.md
  api-reference/beta/api/plannerplanconfigurationlocalization-update.md
  api-reference/beta/api/plannertaskconfiguration-get.md
  api-reference/beta/api/plannertaskconfiguration-update.md
  api-reference/beta/api/solutionsroot-delete-businessscenarios.md
  api-reference/beta/api/solutionsroot-list-businessscenarios.md
  api-reference/beta/api/solutionsroot-post-businessscenarios.md
  api-reference/beta/resources/businessscenario-overview.md
  api-reference/beta/resources/businessscenario-planner-overview.md
  api-reference/beta/resources/businessscenario.md
  api-reference/beta/resources/businessscenariogrouptarget.md
  api-reference/beta/resources/businessscenarioplanner.md
  api-reference/beta/resources/businessscenarioplanreference.md
  api-reference/beta/resources/businessscenarioproperties.md
  api-reference/beta/resources/businessscenariotask.md
  api-reference/beta/resources/businessscenariotasktargetbase.md
  api-reference/beta/resources/enums.md
  api-reference/beta/resources/plannerfieldrules.md
  api-reference/beta/resources/plannerplanconfiguration.md
  api-reference/beta/resources/plannerplanconfigurationbucketdefinition.md
  api-reference/beta/resources/plannerplanconfigurationbucketlocalization.md
  api-reference/beta/resources/plannerplanconfigurationlocalization.md
  api-reference/beta/resources/plannerpropertyrule.md
  api-reference/beta/resources/plannerrelationshipbasedusertype.md
  api-reference/beta/resources/plannerruleoverride.md
  api-reference/beta/resources/plannertaskconfiguration.md
  api-reference/beta/resources/plannertaskconfigurationrolebase.md
  api-reference/beta/resources/plannertaskpolicy.md
  api-reference/beta/resources/plannertaskpropertyrule.md
  api-reference/beta/resources/plannertaskrolebasedrule.md
  api-reference/beta/toc.yml
  changelog/Microsoft.BusinessExtensibility.json
  changelog/Microsoft.Office.Tasks.json
  concepts/businessscenarios-concept-overview.md
  concepts/permissions-reference.md
  concepts/planner-concept-overview.md
  concepts/planner-task-rules-overview.md
  concepts/toc.yml
Labels: ready to merge, internal, content review complete

#19852 Edits in PR 19534
  concepts/msgraph-customer-build-tool-to-download-all-the-resources-from-assignment.md
  concepts/msgraph-customer-create-assignment-with-teamsapp-content-for-application.md
Labels: external

#19846 Minor fixes
  api-reference/beta/api/authentication-list-methods.md
  api-reference/beta/resources/authenticationmethod.md
  api-reference/beta/resources/emailauthenticationmethod.md
  api-reference/beta/resources/fido2authenticationmethod.md
  api-reference/beta/resources/microsoftauthenticatorauthenticationmethod.md
  api-reference/beta/resources/passwordauthenticationmethod.md
  api-reference/beta/resources/passwordlessmicrosoftauthenticatorauthenticationmethod.md
  api-reference/beta/resources/phoneauthenticationmethod.md
  api-reference/beta/resources/softwareoathauthenticationmethod.md
  api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md
  api-reference/beta/resources/windowshelloforbusinessauthenticationmethod.md
  api-reference/v1.0/api/authentication-list-methods.md
  api-reference/v1.0/resources/authenticationmethod.md
  api-reference/v1.0/resources/emailauthenticationmethod.md
  api-reference/v1.0/resources/fido2authenticationmethod.md
  api-reference/v1.0/resources/microsoftauthenticatorauthenticationmethod.md
  api-reference/v1.0/resources/passwordauthenticationmethod.md
  api-reference/v1.0/resources/phoneauthenticationmethod.md
  api-reference/v1.0/resources/softwareoathauthenticationmethod.md
  api-reference/v1.0/resources/temporaryaccesspassauthenticationmethod.md
  api-reference/v1.0/resources/windowshelloforbusinessauthenticationmethod.md
Labels: area: Azure AD, ready to merge, internal

#19762 Release Qna Search
  api-reference/beta/resources/search-api-overview.md
  concepts/search-concept-acronym.md
  concepts/search-concept-bookmark.md
  concepts/search-concept-qna.md
  concepts/toc.yml
Labels: ready to merge, internal, review feedback addressed

#19851 Added note to more resource topics to increase awareness how Cloud PC relates to the monitoring API.
  api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md
  api-reference/beta/includes/monitoring-api-support-solicit.md
  api-reference/beta/resources/devicemanagement-alertimpact.md
  api-reference/beta/resources/devicemanagement-alertrecord.md
  api-reference/beta/resources/devicemanagement-alertrule.md
  api-reference/beta/resources/devicemanagement-monitoring.md
  api-reference/beta/resources/devicemanagement-notificationchannel.md
  api-reference/beta/resources/devicemanagement-notificationreceiver.md
  api-reference/beta/resources/devicemanagement-portalnotification.md
  api-reference/beta/resources/devicemanagement-rulethreshold.md
Labels: do not merge, internal

#19857 Publish updates to increase awareness how Cloud PC relates to the alert monitoring API
  api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md
  api-reference/beta/includes/monitoring-api-support-solicit.md
  api-reference/beta/resources/devicemanagement-alertimpact.md
  api-reference/beta/resources/devicemanagement-alertrecord.md
  api-reference/beta/resources/devicemanagement-alertrule.md
  api-reference/beta/resources/devicemanagement-monitoring.md
  api-reference/beta/resources/devicemanagement-notificationchannel.md
  api-reference/beta/resources/devicemanagement-notificationreceiver.md
  api-reference/beta/resources/devicemanagement-portalnotification.md
  api-reference/beta/resources/devicemanagement-rulethreshold.md
Labels: internal

#19868 Edits in PR 19534
  concepts/msgraph-customer-create-assignment-with-teamsapp-content-for-application.md
  concepts/msgraph-customer-scenarios.md
  concepts/toc.yml
Labels: external

#19869 Edits in PR 18043
  api-reference/beta/api/industrydata-azuredatalakeconnector-getuploadsession.md
  api-reference/beta/api/industrydata-inboundfileflow-post.md
  api-reference/beta/api/industrydata-inboundflow-update.md
  api-reference/beta/resources/industrydata-azuredatalakeconnector.md
  api-reference/beta/resources/industrydata-fileuploadsession.md
  api-reference/beta/resources/industrydata-filevalidateoperation.md
  api-reference/beta/resources/industrydata-inboundfileflow.md
  api-reference/beta/resources/industrydata-inboundflow.md
  api-reference/beta/resources/industrydata-industrydatarunactivity.md
  api-reference/beta/resources/industrydata-usermatchingsetting.md
Labels: external

#19870 Update issuerAssignedId limitation
  api-reference/beta/resources/objectidentity.md
  api-reference/v1.0/resources/objectidentity.md
Labels: external

#19836 Alphabetize 1 2 23
  api-reference/v1.0/resources/aaduserconversationmember.md
  api-reference/v1.0/resources/accesspackage.md
  api-reference/v1.0/resources/accesspackageapprovalstage.md
  api-reference/v1.0/resources/accesspackageassignment.md
  api-reference/v1.0/resources/accesspackageassignmentpolicy.md
  api-reference/v1.0/resources/accesspackageassignmentrequest.md
  api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md
  api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md
  api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md
  api-reference/v1.0/resources/accesspackagecatalog.md
  api-reference/v1.0/resources/accesspackagesubject.md
  api-reference/v1.0/resources/accessreviewhistorydefinition.md
  api-reference/v1.0/resources/accessreviewhistoryinstance.md
  api-reference/v1.0/resources/accessreviewhistoryschedulesettings.md
  api-reference/v1.0/resources/accessreviewinactiveusersqueryscope.md
  api-reference/v1.0/resources/accessreviewinstance.md
  api-reference/v1.0/resources/accessreviewinstancedecisionitem.md
  api-reference/v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md
  api-reference/v1.0/resources/accessreviewinstancedecisionitemazureroleresource.md
  api-reference/v1.0/resources/accessreviewinstancedecisionitemresource.md
  api-reference/v1.0/resources/accessreviewinstancedecisionitemserviceprincipalresource.md
  api-reference/v1.0/resources/accessreviewnotificationrecipientqueryscope.md
  api-reference/v1.0/resources/tokenlifetimepolicy.md
  api-reference/v1.0/resources/unifiedroleassignment.md
  api-reference/v1.0/resources/urlassessmentrequest.md
  api-reference/v1.0/resources/user.md
  api-reference/v1.0/resources/userflowapiconnectorconfiguration.md
  api-reference/v1.0/resources/userflowlanguageconfiguration.md
  api-reference/v1.0/resources/userscopeteamsappinstallation.md
  api-reference/v1.0/resources/usersettings.md
  api-reference/v1.0/resources/website.md
  api-reference/v1.0/resources/windowshelloforbusinessauthenticationmethod.md
  api-reference/v1.0/resources/workbook.md
  api-reference/v1.0/resources/workbookoperation.md
  api-reference/v1.0/resources/workbookoperationerror.md
  api-reference/v1.0/resources/workinghours.md
  api-reference/v1.0/resources/worksheetprotection.md
  api-reference/v1.0/resources/x509certificateauthenticationmethodconfiguration.md
  api-reference/v1.0/resources/x509certificateauthenticationmodeconfiguration.md
  api-reference/v1.0/resources/x509certificaterule.md
  api-reference/v1.0/resources/x509certificateuserbinding.md
Labels: ready to merge, internal, content review complete

#19871 Update businessscenario-planner-overview.md
  api-reference/beta/resources/businessscenario-planner-overview.md
Labels: external

#19872 Merge to publish.
  api-reference/beta/resources/businessscenario-planner-overview.md
  api-reference/beta/resources/objectidentity.md
  api-reference/v1.0/resources/aaduserconversationmember.md
  api-reference/v1.0/resources/accesspackage.md
  api-reference/v1.0/resources/accesspackageapprovalstage.md
  api-reference/v1.0/resources/accesspackageassignment.md
  api-reference/v1.0/resources/accesspackageassignmentpolicy.md
  api-reference/v1.0/resources/accesspackageassignmentrequest.md
  api-reference/v1.0/resources/accesspackageassignmentrequestorsettings.md
  api-reference/v1.0/resources/accesspackageassignmentrequestrequirements.md
  api-reference/v1.0/resources/accesspackageassignmentreviewsettings.md
  api-reference/v1.0/resources/accesspackagecatalog.md
  api-reference/v1.0/resources/accesspackagesubject.md
  api-reference/v1.0/resources/accessreviewhistorydefinition.md
  api-reference/v1.0/resources/accessreviewhistoryinstance.md
  api-reference/v1.0/resources/accessreviewhistoryschedulesettings.md
  api-reference/v1.0/resources/accessreviewinactiveusersqueryscope.md
  api-reference/v1.0/resources/accessreviewinstance.md
  api-reference/v1.0/resources/accessreviewinstancedecisionitem.md
  api-reference/v1.0/resources/accessreviewinstancedecisionitemaccesspackageassignmentpolicyresource.md
  api-reference/v1.0/resources/accessreviewinstancedecisionitemazureroleresource.md
  api-reference/v1.0/resources/accessreviewinstancedecisionitemresource.md
  api-reference/v1.0/resources/accessreviewinstancedecisionitemserviceprincipalresource.md
  api-reference/v1.0/resources/accessreviewnotificationrecipientqueryscope.md
  api-reference/v1.0/resources/objectidentity.md
  api-reference/v1.0/resources/tokenlifetimepolicy.md
  api-reference/v1.0/resources/unifiedroleassignment.md
  api-reference/v1.0/resources/urlassessmentrequest.md
  api-reference/v1.0/resources/user.md
  api-reference/v1.0/resources/userflowapiconnectorconfiguration.md
  api-reference/v1.0/resources/userflowlanguageconfiguration.md
  api-reference/v1.0/resources/userscopeteamsappinstallation.md
  api-reference/v1.0/resources/usersettings.md
  api-reference/v1.0/resources/website.md
  api-reference/v1.0/resources/windowshelloforbusinessauthenticationmethod.md
  api-reference/v1.0/resources/workbook.md
  api-reference/v1.0/resources/workbookoperation.md
  api-reference/v1.0/resources/workbookoperationerror.md
  api-reference/v1.0/resources/workinghours.md
  api-reference/v1.0/resources/worksheetprotection.md
  api-reference/v1.0/resources/x509certificateauthenticationmethodconfiguration.md
  api-reference/v1.0/resources/x509certificateauthenticationmodeconfiguration.md
  api-reference/v1.0/resources/x509certificaterule.md
  api-reference/v1.0/resources/x509certificateuserbinding.md
Labels: internal

#19858 Add note to clarify how Planner relates to business scenario API.
  api-reference/beta/api/businessscenario-delete.md
  api-reference/beta/resources/businessscenario-overview.md
  api-reference/beta/resources/businessscenario.md
  api-reference/beta/toc.yml
Labels: do not merge, internal

#19875 Publish further clarification for how Planner relates to business scenarios API.
  api-reference/beta/api/businessscenario-delete.md
  api-reference/beta/resources/businessscenario-overview.md
  api-reference/beta/resources/businessscenario.md
  api-reference/beta/toc.yml
Labels: internal

#19874 Link correction
  concepts/outlook-schedule-recurring-events.md
Labels: external

#19876 Minor doc fixes
  api-reference/beta/resources/passwordprofile.md
  api-reference/beta/resources/user.md
  api-reference/v1.0/resources/passwordprofile.md
  api-reference/v1.0/resources/user.md
  changelog/Microsoft.AAD.Reporting.json
  concepts/aad-advanced-queries.md
Labels: ready to merge, internal

#19825 Francismbui/default usage location v1
  api-reference/v1.0/api/organization-get.md
  api-reference/v1.0/api/organization-list.md
  api-reference/v1.0/resources/organization.md
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, ready to merge, internal, content review complete

#19899 Edits in PR 18043
  api-reference/beta/resources/industrydata-azuredatalakeconnector.md
  api-reference/beta/resources/industrydata-filedataconnector.md
  api-reference/beta/resources/industrydata-fileuploadsession.md
  api-reference/beta/resources/industrydata-filevalidateoperation.md
  api-reference/beta/resources/industrydata-inboundactivityresults.md
  api-reference/beta/resources/industrydata-inboundfileflow.md
  api-reference/beta/resources/industrydata-inboundflow.md
  api-reference/beta/resources/industrydata-industrydataactivity.md
  api-reference/beta/resources/industrydata-industrydataactivitystatistics.md
  api-reference/beta/resources/industrydata-industrydataconnector.md
  api-reference/beta/resources/industrydata-industrydatarun.md
  api-reference/beta/resources/industrydata-industrydatarunactivity.md
  api-reference/beta/resources/industrydata-outboundflowactivity.md
  api-reference/beta/resources/industrydata-referencedefinition.md
  api-reference/beta/resources/industrydata-referencevalue.md
  api-reference/beta/resources/industrydata-sourcesystemdefinition.md
  api-reference/beta/resources/industrydata-validateoperation.md
  api-reference/beta/resources/industrydata-yeartimeperioddefinition.md
Labels: external

#19898 Update todotask-get.md
  api-reference/beta/api/todotask-get.md
Labels: external

#19897 Update todotask-get.md
  api-reference/v1.0/api/todotask-get.md
Labels: external

#19916 Edits in PR 19228
  api-reference/beta/api/cloudpc-getsupportedcloudpcremoteactions.md
  api-reference/beta/resources/cloudpc.md
  api-reference/beta/resources/cloudpcremoteactioncapability.md
  api-reference/beta/toc.yml
  changelog/Microsoft.CloudManagedDesktop.json
Labels: external

#19917 Fixed TOC entry
  api-reference/beta/toc.yml
Labels: external

#19918 Update cloudpc-get.md
  api-reference/beta/api/cloudpc-get.md
Labels: external

#19228 [CloudPC] Get Supported CloudPc Remote Actions
  api-reference/beta/api/cloudpc-getsupportedcloudpcremoteactions.md
  api-reference/beta/resources/cloudpc.md
  api-reference/beta/resources/cloudpcremoteactioncapability.md
  api-reference/beta/toc.yml
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, internal, schema live

#19892 Add max expiration time to meeting call resource doc
  concepts/changenotifications-for-onlinemeeting.md
Labels: ready to merge, internal, content review complete

#19158 [CloudPC]Add virtualNetworkLocation to onPremisesConnection
  api-reference/beta/api/cloudpconpremisesconnection-get.md
  api-reference/beta/api/cloudpconpremisesconnection-update.md
  api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md
  api-reference/beta/resources/cloudpconpremisesconnection.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, internal, content review complete, schema live

#19888 Update appcatalogs-list-teamsapps.md
  api-reference/v1.0/api/appcatalogs-list-teamsapps.md
Labels: external

#19887 Update appcatalogs-list-teamsapps.md
  api-reference/beta/api/appcatalogs-list-teamsapps.md
Labels: external

#19930 Fixed issues in PR 18537
  api-reference/beta/api/cloudpcprovisioningpolicy-update.md
  api-reference/beta/api/cloudpcshareduseserviceplan-get.md
  api-reference/beta/api/virtualendpoint-list-shareduseserviceplans.md
  api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md
  api-reference/beta/resources/cloudpcmanagementgroupassignmenttarget.md
  api-reference/beta/resources/cloudpcprovisioningpolicy.md
  api-reference/beta/resources/cloudpcshareduseserviceplan.md
  api-reference/beta/toc.yml
  changelog/Microsoft.CloudManagedDesktop.json
Labels: external

#19932 Edits in PR 18537
  api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md
  changelog/Microsoft.CloudManagedDesktop.json
Labels: external

#19934 Update chat.md
  api-reference/beta/resources/chat.md
Labels: external

#19891 Minor fixes
  api-reference/beta/api/device-update.md
  api-reference/beta/api/directorysetting-update.md
  api-reference/beta/resources/group.md
  api-reference/beta/resources/groups-overview.md
  api-reference/v1.0/api/device-update.md
  api-reference/v1.0/resources/group.md
  api-reference/v1.0/resources/groups-overview.md
  concepts/identity-governance-pim-rules-overview.md
  concepts/migrate-azure-ad-graph-property-differences.md
Labels: area: Azure AD, ready to merge

#19300 User Story 154682|User Story 154680| Doc customer scenarios
  concepts/assignments-and-grades-scenarios.md
  concepts/connect-to-assignments-and-grades.md
  concepts/get-links-to-assignments-and-submissions.md
  concepts/toc.yml
  concepts/update-assignment-and-grade-data.md
Labels: ready to merge, internal, content review complete, review feedback addressed

#19935 Merge to publish.
  api-reference/beta/api/device-update.md
  api-reference/beta/api/directorysetting-update.md
  api-reference/beta/resources/chat.md
  api-reference/beta/resources/group.md
  api-reference/beta/resources/groups-overview.md
  api-reference/v1.0/api/device-update.md
  api-reference/v1.0/resources/group.md
  api-reference/v1.0/resources/groups-overview.md
  concepts/assignments-and-grades-scenarios.md
  concepts/connect-to-assignments-and-grades.md
  concepts/get-links-to-assignments-and-submissions.md
  concepts/identity-governance-pim-rules-overview.md
  concepts/migrate-azure-ad-graph-property-differences.md
  concepts/toc.yml
  concepts/update-assignment-and-grade-data.md
Labels: internal

#19941 Fix property name in changelog
  changelog/Microsoft.CloudManagedDesktop.json
Labels: ready to merge, internal

#19945 Edits in PR 18043
  api-reference/beta/api/industrydata-azuredatalakeconnector-post.md
  api-reference/beta/api/industrydata-inboundfileflow-delete.md
  api-reference/beta/api/industrydata-inboundfileflow-post.md
  api-reference/beta/api/industrydata-inboundfileflow-update.md
  api-reference/beta/api/industrydata-inboundflow-post.md
  api-reference/beta/api/industrydata-industrydatarun-getstatistics.md
  api-reference/beta/api/industrydata-sourcesystemdefinition-delete.md
  api-reference/beta/api/industrydata-yeartimeperioddefinition-delete.md
  api-reference/beta/resources/enums-industryData.md
  api-reference/beta/resources/enums-industrydata.md
  api-reference/beta/resources/industrydata-inboundactivityresults.md
  api-reference/beta/resources/industrydata-inboundfileflow.md
  api-reference/beta/resources/industrydata-inboundflow.md
  api-reference/beta/resources/industrydata-inboundflowactivity.md
  api-reference/beta/resources/industrydata-industrydataactivity.md
  api-reference/beta/resources/industrydata-industrydataactivitystatistics.md
  api-reference/beta/resources/industrydata-industrydataroot.md
  api-reference/beta/resources/industrydata-industrydatarun.md
  api-reference/beta/resources/industrydata-industrydatarunactivity.md
  api-reference/beta/resources/industrydata-industrydatarunstatistics.md
  api-reference/beta/resources/industrydata-longrunningoperation.md
  api-reference/beta/resources/industrydata-outboundflowactivity.md
  api-reference/beta/resources/industrydata-overview.md
  api-reference/beta/resources/industrydata-referencevalue.md
  concepts/permissions-reference.md
Labels: external

#19929 Update security-api-overview.md
  api-reference/beta/resources/security-api-overview.md
  api-reference/v1.0/resources/security-api-overview.md
  concepts/known-issues.md
Labels: ready to merge, internal, content review complete

#19947 Merge to publish (OOB)
  api-reference/beta/resources/security-api-overview.md
  api-reference/v1.0/resources/security-api-overview.md
  changelog/Microsoft.CloudManagedDesktop.json
  concepts/known-issues.md
Labels: internal

#19946 Update list.md
  api-reference/v1.0/resources/list.md
Labels: external

#18147 Added Support for editing properties of message in user context for v1.0
  api-reference/beta/api/chatmessage-update.md
  api-reference/v1.0/api/chatmessage-update.md
Labels: ready to merge, internal, Ignite22, content review complete

#18884 Create simulation changes
  api-reference/beta/api/attacksimulationroot-create-simulation.md
  api-reference/beta/api/attacksimulationroot-delete-simulation.md
  api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md
  api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md
  api-reference/beta/api/attacksimulationroot-get-operation.md
  api-reference/beta/api/attacksimulationroot-get-payload.md
  api-reference/beta/api/attacksimulationroot-get-payloadsdetails.md
  api-reference/beta/api/attacksimulationroot-list-payloads.md
  api-reference/beta/api/attacksimulationroot-list-simulations.md
  api-reference/beta/api/attacksimulationroot-update-simulation.md
  api-reference/beta/resources/accounttargetcontent.md
  api-reference/beta/resources/addressbookaccounttargetcontent.md
  api-reference/beta/resources/attacksimulationoperation.md
  api-reference/beta/resources/attacksimulationroot.md
  api-reference/beta/resources/coachmarklocation.md
  api-reference/beta/resources/emailpayloaddetail.md
  api-reference/beta/resources/includeallaccounttargetcontent.md
  api-reference/beta/resources/longrunningoperation.md
  api-reference/beta/resources/payload.md
  api-reference/beta/resources/payloadcoachmark.md
  api-reference/beta/resources/payloaddetail.md
  api-reference/beta/resources/simulation.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Security.AttackSimulation.json
  concepts/includes/permissions-ids.md
  concepts/permissions-reference.md
Labels: ready to merge, content review complete

#19949 Merge to publish.
  api-reference/beta/api/attacksimulationroot-create-simulation.md
  api-reference/beta/api/attacksimulationroot-delete-simulation.md
  api-reference/beta/api/attacksimulationroot-get-excludedaccounttarget.md
  api-reference/beta/api/attacksimulationroot-get-includedaccounttarget.md
  api-reference/beta/api/attacksimulationroot-get-operation.md
  api-reference/beta/api/attacksimulationroot-get-payload.md
  api-reference/beta/api/attacksimulationroot-get-payloadsdetails.md
  api-reference/beta/api/attacksimulationroot-list-payloads.md
  api-reference/beta/api/attacksimulationroot-list-simulations.md
  api-reference/beta/api/attacksimulationroot-update-simulation.md
  api-reference/beta/api/chatmessage-update.md
  api-reference/beta/resources/accounttargetcontent.md
  api-reference/beta/resources/addressbookaccounttargetcontent.md
  api-reference/beta/resources/attacksimulationoperation.md
  api-reference/beta/resources/attacksimulationroot.md
  api-reference/beta/resources/coachmarklocation.md
  api-reference/beta/resources/emailpayloaddetail.md
  api-reference/beta/resources/includeallaccounttargetcontent.md
  api-reference/beta/resources/longrunningoperation.md
  api-reference/beta/resources/payload.md
  api-reference/beta/resources/payloadcoachmark.md
  api-reference/beta/resources/payloaddetail.md
  api-reference/beta/resources/simulation.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/chatmessage-update.md
  api-reference/v1.0/resources/list.md
  changelog/Microsoft.Security.AttackSimulation.json
  concepts/includes/permissions-ids.md
  concepts/permissions-reference.md
Labels: internal

#19951 Minor doc fixes
  api-reference/beta/api/synchronization-synchronizationjob-restart.md
  api-reference/beta/resources/keycredential.md
  api-reference/v1.0/resources/keycredential.md
  concepts/accessreviews-scope-concept.md
  concepts/known-issues.md
Labels: ready to merge, internal

#19209 Create New Permission- Calendars.ReadBasic
  concepts/permissions-reference.md
Labels: ready to merge, internal, content review complete

#19925 - updates go concepts snippets to reflect recent changes in the SDK
  concepts/sdks/choose-authentication-providers.md
  concepts/sdks/create-client.md
  concepts/sdks/customize-client.md
  concepts/sdks/includes/snippets/go/create-requests-create.md
  concepts/sdks/includes/snippets/go/create-requests-delete.md
  concepts/sdks/includes/snippets/go/create-requests-expand.md
  concepts/sdks/includes/snippets/go/create-requests-headers.md
  concepts/sdks/includes/snippets/go/create-requests-index.md
  concepts/sdks/includes/snippets/go/create-requests-list.md
  concepts/sdks/includes/snippets/go/create-requests-queryparams.md
  concepts/sdks/includes/snippets/go/create-requests-read.md
  concepts/sdks/includes/snippets/go/create-requests-select.md
  concepts/sdks/includes/snippets/go/create-requests-update.md
  concepts/sdks/national-clouds.md
  concepts/sdks/sdk-installation.md
  concepts/sdks/use-beta.md
Labels: ready to merge, internal, content review complete

#18146 Changes for Delete Message API from beta to V1.0
  api-reference/v1.0/api/chatmessage-softdelete.md
  api-reference/v1.0/api/chatmessage-undosoftdelete.md
  api-reference/v1.0/resources/chatmessage.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.Teams.Core.json
Labels: ready to merge, internal, Ignite22, content review complete, invalid links

#19960 Merge to publish.
  api-reference/beta/api/synchronization-synchronizationjob-restart.md
  api-reference/beta/resources/keycredential.md
  api-reference/v1.0/api/chatmessage-softdelete.md
  api-reference/v1.0/api/chatmessage-undosoftdelete.md
  api-reference/v1.0/resources/chatmessage.md
  api-reference/v1.0/resources/keycredential.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.Teams.Core.json
  concepts/accessreviews-scope-concept.md
  concepts/known-issues.md
  concepts/permissions-reference.md
  concepts/sdks/choose-authentication-providers.md
  concepts/sdks/create-client.md
  concepts/sdks/customize-client.md
  concepts/sdks/includes/snippets/go/create-requests-create.md
  concepts/sdks/includes/snippets/go/create-requests-delete.md
  concepts/sdks/includes/snippets/go/create-requests-expand.md
  concepts/sdks/includes/snippets/go/create-requests-headers.md
  concepts/sdks/includes/snippets/go/create-requests-index.md
  concepts/sdks/includes/snippets/go/create-requests-list.md
  concepts/sdks/includes/snippets/go/create-requests-queryparams.md
  concepts/sdks/includes/snippets/go/create-requests-read.md
  concepts/sdks/includes/snippets/go/create-requests-select.md
  concepts/sdks/includes/snippets/go/create-requests-update.md
  concepts/sdks/national-clouds.md
  concepts/sdks/sdk-installation.md
  concepts/sdks/use-beta.md
Labels: internal, invalid links

#19964 Planner Roster resource: typo fix
  api-reference/beta/resources/plannerroster.md
Labels: external

#19977 Update signin.md
  api-reference/v1.0/resources/signin.md
Labels: external

#19962 Missing `planner roster get` in left navigation
  api-reference/beta/toc.yml
Labels: external

#19342 Entitlement Management - Adding crossCloudAzureActiveDirectoryTenant to v1.0
  api-reference/v1.0/resources/connectedorganization.md
  api-reference/v1.0/resources/crosscloudazureactivedirectorytenant.md
  api-reference/v1.0/resources/identitysource.md
  changelog/Microsoft.IGAELM.json
Labels: area: Azure AD, ready to merge, internal, content review complete

#18162 Document automaticUserConsentSettings in XTAP
  api-reference/beta/api/crosstenantaccesspolicy-list-partners.md
  api-reference/beta/api/crosstenantaccesspolicy-post-partners.md
  api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md
  api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md
  api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md
  api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md
  api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md
  api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md
  api-reference/beta/resources/inboundoutboundpolicyconfiguration.md
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, resolved: awaiting prod deployment, ready to merge, internal, content review complete

#19534 USER STORY 154686|USER STORY 154688 customer scenarios
  concepts/assignments-and-grades-scenarios.md
  concepts/download-resources-from-assignment.md
  concepts/embed-teams-app-in-assignment.md
  concepts/toc.yml
Labels: ready to merge, internal, content review in progress, review feedback addressed

#19637 V1 documentation for teamsummary
  api-reference/v1.0/api/team-get.md
  api-reference/v1.0/resources/team.md
  api-reference/v1.0/resources/teamsummary.md
  changelog/Microsoft.Teams.Core.json
Labels: ready to merge, internal, content review complete, invalid links

#19674 Guidance for adding certificate credentials to an app
  concepts/applications-how-to-add-certificate.md
  concepts/toc.yml
  concepts/tutorial-applications-basics.md
Labels: area: authentication, area: Azure AD, ready to merge, internal, review feedback addressed, area: applications

#19968 Application permissions not supported for followedSites
  api-reference/beta/api/sites-list-followed.md
  api-reference/v1.0/api/sites-list-followed.md
Labels: external, ready to merge

#19433 [Azure AD] userSyncInbound in XTAP v2
  api-reference/beta/api/crosstenantaccesspolicy-list-partners.md
  api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md
  api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-put-identitysynchronization.md
  api-reference/beta/api/crosstenantidentitysyncpolicypartner-delete.md
  api-reference/beta/api/crosstenantidentitysyncpolicypartner-get.md
  api-reference/beta/api/crosstenantidentitysyncpolicypartner-update.md
  api-reference/beta/resources/crosstenantaccesspolicy-overview.md
  api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md
  api-reference/beta/resources/crosstenantidentitysyncpolicypartner.md
  api-reference/beta/resources/crosstenantusersyncinbound.md
  api-reference/beta/toc.yml
  changelog/Microsoft.DirectoryServices.json
Labels: area: Azure AD, ready to merge, internal, content review complete

#19980 Merge to publish.
  api-reference/beta/api/crosstenantaccesspolicy-list-partners.md
  api-reference/beta/api/crosstenantaccesspolicy-post-partners.md
  api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md
  api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md
  api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md
  api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md
  api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-put-identitysynchronization.md
  api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md
  api-reference/beta/api/crosstenantidentitysyncpolicypartner-delete.md
  api-reference/beta/api/crosstenantidentitysyncpolicypartner-get.md
  api-reference/beta/api/crosstenantidentitysyncpolicypartner-update.md
  api-reference/beta/api/sites-list-followed.md
  api-reference/beta/resources/crosstenantaccesspolicy-overview.md
  api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md
  api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md
  api-reference/beta/resources/crosstenantidentitysyncpolicypartner.md
  api-reference/beta/resources/crosstenantusersyncinbound.md
  api-reference/beta/resources/inboundoutboundpolicyconfiguration.md
  api-reference/beta/resources/plannerroster.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/sites-list-followed.md
  api-reference/v1.0/api/team-get.md
  api-reference/v1.0/resources/connectedorganization.md
  api-reference/v1.0/resources/crosscloudazureactivedirectorytenant.md
  api-reference/v1.0/resources/identitysource.md
  api-reference/v1.0/resources/signin.md
  api-reference/v1.0/resources/team.md
  api-reference/v1.0/resources/teamsummary.md
  changelog/Microsoft.DirectoryServices.json
  changelog/Microsoft.IGAELM.json
  changelog/Microsoft.Teams.Core.json
  concepts/applications-how-to-add-certificate.md
  concepts/assignments-and-grades-scenarios.md
  concepts/download-resources-from-assignment.md
  concepts/embed-teams-app-in-assignment.md
  concepts/toc.yml
  concepts/tutorial-applications-basics.md
Labels: do not merge, internal, invalid links

#19577 Various updates/fixes for NAPI docs
  api-reference/beta/api/teamwork-sendactivitynotificationtorecipients.md
  api-reference/v1.0/api/teamwork-sendactivitynotificationtorecipients.md
  concepts/teams-activity-feed-notifications-best-practices.md
Labels: ready to merge, internal, content review complete

#19913 Update task within workflow API
  api-reference/beta/api/identitygovernance-task-update.md
  api-reference/beta/resources/identitygovernance-task.md
  api-reference/beta/toc.yml
  changelog/Microsoft.AAD.LCM.json
Labels: area: Azure AD, ready to merge, internal, content review complete

#19927 Update connecting-external-content-connectors-api-postman.md
  concepts/connecting-external-content-connectors-api-postman.md
Labels: ready to merge, internal, content review complete

#19981 Added application permissions required
  api-reference/beta/api/todo-list-lists.md
  api-reference/v1.0/api/todo-list-lists.md
Labels: external, ready to merge

#19982 Added application permissions
  api-reference/beta/api/todo-post-lists.md
  api-reference/v1.0/api/todo-post-lists.md
Labels: external, ready to merge

#19983 Added application permissions
  api-reference/beta/api/todotasklist-list-tasks.md
  api-reference/v1.0/api/todotasklist-list-tasks.md
Labels: external, ready to merge

#19984 Added application permissions
  api-reference/beta/api/todotasklist-post-tasks.md
  api-reference/v1.0/api/todotasklist-post-tasks.md
Labels: external, ready to merge

#19990 Update ms.date, add ms.author, reassign authN/Z landing page
  concepts/auth/index.yml
Labels: area: Azure AD, ready to merge, internal

#19979 changes made to enable displayName property in PrintJob in beta graph api
  api-reference/beta/api/printer-post-jobs.md
  api-reference/beta/api/printershare-post-jobs.md
  api-reference/beta/api/printjob-get.md
  api-reference/beta/api/printjob-redirect.md
  api-reference/beta/api/printjob-update.md
  api-reference/beta/resources/printjob.md
  api-reference/v1.0/resources/printjob.md
  changelog/Microsoft.PrintService.json
Labels: ready to merge, area:universal print, content review complete

#19996 Merge to publish.
  api-reference/beta/api/identitygovernance-task-update.md
  api-reference/beta/api/printer-post-jobs.md
  api-reference/beta/api/printershare-post-jobs.md
  api-reference/beta/api/printjob-get.md
  api-reference/beta/api/printjob-redirect.md
  api-reference/beta/api/printjob-update.md
  api-reference/beta/api/teamwork-sendactivitynotificationtorecipients.md
  api-reference/beta/api/todo-list-lists.md
  api-reference/beta/api/todo-post-lists.md
  api-reference/beta/api/todotasklist-list-tasks.md
  api-reference/beta/api/todotasklist-post-tasks.md
  api-reference/beta/resources/identitygovernance-task.md
  api-reference/beta/resources/printjob.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/teamwork-sendactivitynotificationtorecipients.md
  api-reference/v1.0/api/todo-list-lists.md
  api-reference/v1.0/api/todo-post-lists.md
  api-reference/v1.0/api/todotasklist-list-tasks.md
  api-reference/v1.0/api/todotasklist-post-tasks.md
  api-reference/v1.0/resources/printjob.md
  changelog/Microsoft.AAD.LCM.json
  changelog/Microsoft.PrintService.json
  concepts/auth/index.yml
  concepts/connecting-external-content-connectors-api-postman.md
  concepts/teams-activity-feed-notifications-best-practices.md
Labels: internal

#19434 Update onpremisespublishingsinglesignon.md
  api-reference/beta/resources/onpremisespublishingsinglesignon.md
  changelog/Microsoft.DirectoryServices.json
Labels: ready to merge, internal, content review complete

#20003 Merge to publish (OOB).
  api-reference/beta/resources/onpremisespublishingsinglesignon.md
  changelog/Microsoft.DirectoryServices.json
Labels: internal

#20012 Edits in PR 18043
  api-reference/beta/resources/industrydata-azuredatalakeconnector.md
  api-reference/beta/resources/industrydata-filedataconnector.md
  api-reference/beta/resources/industrydata-identifiertypereferencevalue.md
  api-reference/beta/resources/industrydata-inboundfileflow.md
  api-reference/beta/resources/industrydata-inboundflow.md
  api-reference/beta/resources/industrydata-inboundflowactivity.md
  api-reference/beta/resources/industrydata-industrydataconnector.md
  api-reference/beta/resources/industrydata-industrydatarunactivity.md
  api-reference/beta/resources/industrydata-outboundflowactivity.md
  api-reference/beta/resources/industrydata-referencevalue.md
  api-reference/beta/resources/industrydata-rolereferencevalue.md
  api-reference/beta/resources/industrydata-usermatchtargetreferencevalue.md
  api-reference/beta/resources/industrydata-validateoperation.md
  api-reference/beta/resources/industrydata-yearreferencevalue.md
  api-reference/beta/resources/longrunningoperation.md
Labels: external

#20013 Update attacksimulationoperation.md
  api-reference/beta/resources/attacksimulationoperation.md
Labels: external

#19985 Content refresh - extensions docs
  api-reference/beta/api/opentypeextension-update.md
  api-reference/beta/resources/opentypeextension.md
  api-reference/beta/resources/schemaextension.md
  api-reference/v1.0/api/opentypeextension-update.md
  api-reference/v1.0/resources/opentypeextension.md
  api-reference/v1.0/resources/schemaextension.md
  concepts/extensibility-overview.md
Labels: area: Azure AD, ready to merge, area: extensions

#19999 Update owner GitHub alias
  api-reference/beta/api/domain-post-federationconfiguration.md
  api-reference/beta/api/internaldomainfederation-delete.md
  api-reference/beta/api/internaldomainfederation-get.md
  api-reference/beta/api/internaldomainfederation-update.md
  api-reference/beta/resources/internaldomainfederation.md
  api-reference/beta/resources/signingcertificateupdatestatus.md
  api-reference/v1.0/api/domain-post-federationconfiguration.md
  api-reference/v1.0/api/internaldomainfederation-delete.md
  api-reference/v1.0/api/internaldomainfederation-get.md
  api-reference/v1.0/api/internaldomainfederation-update.md
  api-reference/v1.0/resources/internaldomainfederation.md
  api-reference/v1.0/resources/signingcertificateupdatestatus.md
Labels: area: Azure AD, ready to merge, internal, area: directory management

#20000 Update RBAC Roles for domain apis
  api-reference/beta/api/domain-delete.md
  api-reference/beta/api/domain-forcedelete.md
  api-reference/beta/api/domain-get.md
  api-reference/beta/api/domain-list-domainnamereferences.md
  api-reference/beta/api/domain-list-verificationdnsrecords.md
  api-reference/beta/api/domain-list.md
  api-reference/beta/api/domain-post-domains.md
  api-reference/beta/api/domain-promote.md
  api-reference/beta/api/domain-update.md
  api-reference/beta/api/domain-verify.md
Labels: area: Azure AD, ready to merge, internal, content review complete

#20002 Add User.ReadBasic.All application permission, GUIDs refresh (Jan drop)
  changelog/Microsoft.DirectoryServices.json
  concepts/includes/permissions-ids.md
  concepts/permissions-reference.md
Labels: area: Azure AD, ready to merge, area: permissions

#20006 [Graph] Added the note for call notifications
  api-reference/beta/api/application-post-calls.md
  api-reference/beta/api/call-answer.md
Labels: internal, content review complete

#20018 Update what's new in January, 2023.
  api-reference/beta/api/cloudpcexportjob-get.md
  api-reference/beta/api/cloudpcreports-getshareduselicenseusagereport.md
  api-reference/beta/api/cloudpcreports-post-exportjobs.md
  api-reference/beta/resources/cloudpcexportjob.md
  api-reference/beta/resources/cloudpconpremisesconnection.md
  api-reference/beta/resources/cloudpcprovisioningpolicy.md
  api-reference/beta/resources/cloudpcreports.md
  api-reference/beta/resources/cloudpcsupportedregion.md
  api-reference/beta/toc.yml
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: internal

#20020 Refresh what's new since late December through Jan. 16, 2023.
  api-reference/beta/api/cloudpcexportjob-get.md
  api-reference/beta/api/cloudpcreports-getshareduselicenseusagereport.md
  api-reference/beta/api/cloudpcreports-post-exportjobs.md
  api-reference/beta/resources/cloudpcexportjob.md
  api-reference/beta/resources/cloudpconpremisesconnection.md
  api-reference/beta/resources/cloudpcprovisioningpolicy.md
  api-reference/beta/resources/cloudpcreports.md
  api-reference/beta/resources/cloudpcsupportedregion.md
  api-reference/beta/toc.yml
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: do not merge, internal

#20034 Edits in PR 18043
  api-reference/beta/resources/enums-industrydata.md
  api-reference/beta/resources/industrydata-azuredatalakeconnector.md
  api-reference/beta/resources/industrydata-filevalidateoperation.md
  api-reference/beta/resources/industrydata-overview.md
  api-reference/beta/toc.yml
  concepts/industrydata-concept-overview.md
  concepts/overview-major-services.md
Labels: external
