Repository microsoftgraph/microsoft-graph-docs, pull requests merged in 2023-07, with the labels that each got.

#21883 Update and rename appManagementPolicy-update.md to appmanagementpolicy-update.md
  api-reference/v1.0/api/appmanagementpolicy-update.md
Labels: external

#21886 Update and rename appManagementPolicy-delete.md to appmanagementpolicy-delete.md
  api-reference/v1.0/api/appmanagementpolicy-delete.md
Labels: external

#21884 Update and rename appManagementPolicy-update.md to appmanagementpolicy-update.md
  api-reference/beta/api/appmanagementpolicy-update.md
Labels: external

#21887 Update and rename appManagementPolicy-delete.md to appmanagementpolicy-delete.md
  api-reference/beta/api/appmanagementpolicy-delete.md
Labels: external

#21253 Update teams-protected-apis.md
  api-reference/beta/api/channel-getallmessages.md
  api-reference/beta/api/channel-list-messages.md
  api-reference/beta/api/chat-get-members.md
  api-reference/beta/api/chat-list-members.md
  api-reference/beta/api/chat-list-messages.md
  api-reference/beta/api/chatmessage-delta.md
  api-reference/beta/api/chatmessage-get.md
  api-reference/beta/api/chatmessage-list-hostedcontents.md
  api-reference/beta/api/chatmessage-list-replies.md
  api-reference/beta/api/chatmessagehostedcontent-get.md
  api-reference/beta/api/chats-getallmessages.md
  api-reference/beta/api/deletedteam-getallmessages.md
  api-reference/v1.0/api/channel-getallmessages.md
  api-reference/v1.0/api/channel-list-messages.md
  api-reference/v1.0/api/chat-get-members.md
  api-reference/v1.0/api/chat-list-members.md
  api-reference/v1.0/api/chat-list-messages.md
  api-reference/v1.0/api/chatmessage-delta.md
  api-reference/v1.0/api/chatmessage-get.md
  api-reference/v1.0/api/chatmessage-list-hostedcontents.md
  api-reference/v1.0/api/chatmessage-list-replies.md
  api-reference/v1.0/api/chatmessagehostedcontent-get.md
  api-reference/v1.0/api/chats-getallmessages.md
  api-reference/v1.0/api/deletedteam-getallmessages.md
  api-reference/v1.0/api/team-get-members.md
  concepts/metered-api-list.md
  concepts/teams-protected-apis.md
  concepts/toc.yml
Labels: ready to merge, internal, content review complete, review feedback addressed

#21796 fixes to search query examples
  api-reference/v1.0/api/search-query.md
  api-reference/v1.0/resources/enums.md
  api-reference/v1.0/resources/searchrequest.md
Labels: do not merge, ready to merge, internal

#21835 Update cloudpconpremisesconnectionhealthcheck.md
  api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
Labels: ready to merge, internal, content review complete

#21875 LCW Licensing update
  api-reference/beta/resources/identitygovernance-lifecycleworkflows-overview.md
  api-reference/beta/resources/identitygovernance-lifecycleworkflows-reporting-overview.md
  concepts/tutorial-lifecycle-workflows-offboard-custom-workflow.md
  concepts/tutorial-lifecycle-workflows-onboard-custom-workflow.md
  concepts/tutorial-lifecycle-workflows-scheduled-leaver.md
Labels: ready to merge, internal

#21892 LCW crosslink tasks
  concepts/identitygovernance-lifecycleworkflows-task-arguments.md
Labels: ready to merge, internal

#20879 FilePlanDescriptors for RetentionLabels
  api-reference/beta/api/security-authoritytemplate-get.md
  api-reference/beta/api/security-categorytemplate-delete-subcategories.md
  api-reference/beta/api/security-categorytemplate-get.md
  api-reference/beta/api/security-categorytemplate-list-subcategories.md
  api-reference/beta/api/security-categorytemplate-post-subcategories.md
  api-reference/beta/api/security-citationtemplate-get.md
  api-reference/beta/api/security-departmenttemplate-get.md
  api-reference/beta/api/security-fileplanreferencetemplate-get.md
  api-reference/beta/api/security-labelsroot-delete-authorities.md
  api-reference/beta/api/security-labelsroot-delete-categories.md
  api-reference/beta/api/security-labelsroot-delete-citations.md
  api-reference/beta/api/security-labelsroot-delete-departments.md
  api-reference/beta/api/security-labelsroot-delete-fileplanreferences.md
  api-reference/beta/api/security-labelsroot-list-authorities.md
  api-reference/beta/api/security-labelsroot-list-categories.md
  api-reference/beta/api/security-labelsroot-list-citations.md
  api-reference/beta/api/security-labelsroot-list-departments.md
  api-reference/beta/api/security-labelsroot-list-fileplanreferences.md
  api-reference/beta/api/security-labelsroot-list-retentionlabel.md
  api-reference/beta/api/security-labelsroot-post-authorities.md
  api-reference/beta/api/security-labelsroot-post-categories.md
  api-reference/beta/api/security-labelsroot-post-citations.md
  api-reference/beta/api/security-labelsroot-post-departments.md
  api-reference/beta/api/security-labelsroot-post-fileplanreferences.md
  api-reference/beta/api/security-labelsroot-post-retentionlabel.md
  api-reference/beta/api/security-subcategorytemplate-get.md
  api-reference/beta/resources/security-appliedcategory.md
  api-reference/beta/resources/security-authority.md
  api-reference/beta/resources/security-authoritytemplate.md
  api-reference/beta/resources/security-categorytemplate.md
  api-reference/beta/resources/security-citation.md
  api-reference/beta/resources/security-citationtemplate.md
  api-reference/beta/resources/security-department.md
  api-reference/beta/resources/security-departmenttemplate.md
  api-reference/beta/resources/security-dispositionreviewstage.md
  api-reference/beta/resources/security-fileplandescriptor.md
  api-reference/beta/resources/security-fileplandescriptorbase.md
  api-reference/beta/resources/security-fileplandescriptortemplate.md
  api-reference/beta/resources/security-fileplanreference.md
  api-reference/beta/resources/security-fileplanreferencetemplate.md
  api-reference/beta/resources/security-labelsroot.md
  api-reference/beta/resources/security-retentionlabel.md
  api-reference/beta/resources/security-subcategory.md
  api-reference/beta/resources/security-subcategorytemplate.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/security-retentionevent-post.md
  changelog/Microsoft.Security.RecordsManagement.json
Labels: do not merge, ready to merge, internal, content review complete, area: governance, area: compliance

#21767 CLI Preview docs
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
  concepts/cli/app-only.md
  concepts/cli/get-started.md
  concepts/cli/installation.md
  concepts/cli/navigating.md
  concepts/cli/overview.md
  concepts/images/cli/aad-application-id.png
  concepts/images/cli/aad-portal-app-registrations.png
  concepts/images/cli/configured-permissions.png
  concepts/toc.yml
  includes/cli-preview.md
Labels: ready to merge, internal, content review complete

#21936 Replaced inline code blocks and INCLUDE files for Python with snippet references
  .openpublishing.publish.config.json
  concepts/docfx.json
  concepts/sdks/choose-authentication-providers.md
  concepts/sdks/create-client.md
  concepts/sdks/create-requests.md
  concepts/sdks/customize-client.md
  concepts/sdks/includes/snippets/python/create-requests-create.md
  concepts/sdks/includes/snippets/python/create-requests-delete.md
  concepts/sdks/includes/snippets/python/create-requests-expand.md
  concepts/sdks/includes/snippets/python/create-requests-headers.md
  concepts/sdks/includes/snippets/python/create-requests-index.md
  concepts/sdks/includes/snippets/python/create-requests-list.md
  concepts/sdks/includes/snippets/python/create-requests-queryparams.md
  concepts/sdks/includes/snippets/python/create-requests-read.md
  concepts/sdks/includes/snippets/python/create-requests-select.md
  concepts/sdks/includes/snippets/python/create-requests-update.md
  concepts/sdks/national-clouds.md
Labels: internal

#21941 Fix link in what's new topic.
  concepts/whats-new-overview.md
Labels: internal

#21939 Fix what appears to be a broken link
  concepts/auth/auth-concepts.md
Labels: external

#21926 Remove canary domain name in sample
  concepts/search-concept-person.md
Labels: external

#21925 Update data-connect-quickstart-07.md in update-tutorial-pbi branch
  includes/data-connect-quickstart-07.md
Labels: external

#21924 Update data-connect-quickstart-01.md in update-tutorial-pbi branch.
  includes/data-connect-quickstart-01.md
Labels: external

#21923 Update search-concept-interleaving.md in yiwenwang-ms-patch-1 branch
  concepts/search-concept-interleaving.md
Labels: external

#21918 Update accessreviewnotificationrecipientqueryscope.md
  api-reference/v1.0/resources/accessreviewnotificationrecipientqueryscope.md
Labels: external

#21917 Update and rename accessReviewnotificationrecipientqueryscope.md to accessreviewnotificationrecipientqueryscope.md
  api-reference/beta/resources/accessreviewnotificationrecipientqueryscope.md
Labels: external

#21916 Update and rename teams-changenotifications-teamMembership.md to teams-changenotifications-teammembership.md
  concepts/teams-changenotifications-teammembership.md
Labels: external

#21914 Rename teams-changenotifications-chatMembership.md to teams-changenotifications-chatmembership.md
  concepts/teams-changenotifications-chatmembership.md
Labels: external

#21910 Update toc.yml
  api-reference/beta/toc.yml
Labels: external

#21909 Update Microsoft.FileServices.json in kyracatwork-graphretentionlabels branch
  changelog/Microsoft.FileServices.json
Labels: external

#21698 Replaced "application ID (object ID)" with "application ID (client ID)"
  concepts/auth-v2-service.md
  concepts/auth-v2-user.md
Labels: external

#21912 Update extensibility-overview.md
  concepts/extensibility-overview.md
Labels: external, ready to merge

#21239 Adding OrgSettings Docs
  api-reference/beta/api/adminappsandservices-get.md
  api-reference/beta/api/adminappsandservices-update.md
  api-reference/beta/api/admindynamics-get.md
  api-reference/beta/api/admindynamics-update.md
  api-reference/beta/api/adminforms-get.md
  api-reference/beta/api/adminforms-update.md
  api-reference/beta/api/admintodo-get.md
  api-reference/beta/api/admintodo-update.md
  api-reference/beta/resources/adminappsandservices.md
  api-reference/beta/resources/admindynamics.md
  api-reference/beta/resources/adminforms.md
  api-reference/beta/resources/admintodo.md
  api-reference/beta/resources/appsandservicessettings.md
  api-reference/beta/resources/customervoicesettings.md
  api-reference/beta/resources/formssettings.md
  api-reference/beta/resources/todosettings.md
  api-reference/beta/toc.yml
  changelog/Microsoft.OrgSettings.json
Labels: ready to merge, review requested, internal, content review complete, schema live, review feedback addressed

#20659 add document for inline webpart
  api-reference/beta/resources/standardwebpart.md
  changelog/Microsoft.FileServices.json
Labels: ready to merge, internal, content review complete, invalid links

#20723 Update documentation for adding MarkAsJunk and MarkAsNotJunk APIs
  api-reference/beta/api/message-markasjunk.md
  api-reference/beta/api/message-markasnotjunk.md
  api-reference/beta/resources/message.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Exchange.json
Labels: ready to merge, content review complete, schema live

#21902 Update user-findmeetingtimes.md
  api-reference/v1.0/api/user-findmeetingtimes.md
Labels: ready to merge, internal

#21905 Fixing typos in docs
  api-reference/v1.0/api/driveitem-createuploadsession.md
  concepts/call-api.md
Labels: ready to merge, internal

#21930 Update security-ediscoverycustodian-post-unifiedgroupsources.md
  api-reference/v1.0/api/security-ediscoverycustodian-post-unifiedgroupsources.md
Labels: ready to merge

#21931 Update rbacapplication-post-roleeligibilityschedulerequests.md
  api-reference/v1.0/api/rbacapplication-post-roleeligibilityschedulerequests.md
Labels: ready to merge, internal

#21934 Fixing duplicate names
  api-reference/v1.0/api/accessreviewinstance-list-decisions.md
Labels: ready to merge, internal

#21700 Export API to v1.0
  api-reference/beta/toc.yml
  api-reference/v1.0/api/security-caseoperation-get.md
  api-reference/v1.0/api/security-ediscoveryreviewset-export.md
  api-reference/v1.0/api/security-ediscoveryreviewsetquery-export.md
  api-reference/v1.0/resources/security-ediscoveryexportfilemetadata.md
  api-reference/v1.0/resources/security-ediscoveryexportoperation.md
  api-reference/v1.0/resources/security-ediscoveryreviewset.md
  api-reference/v1.0/resources/security-ediscoveryreviewsetquery.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.Security.Ediscovery.json
Labels: ready to merge, internal, content review complete

#21929 add guest support
  api-reference/beta/resources/search-api-overview.md
  concepts/whats-new-overview.md
Labels: ready to merge, internal, content review complete

#21691 Added details of synchronization bulk upload API
  api-reference/beta/api/synchronization-synchronizationjob-post-bulkupload.md
  api-reference/beta/resources/synchronization-bulkupload.md
  api-reference/beta/resources/synchronization-synchronizationjob.md
  api-reference/beta/toc.yml
  changelog/Microsoft.IAM.json
  concepts/permissions-reference.md
Labels: area: Azure AD, do not merge, ready to merge, internal, content review complete

#21949 Update and rename cloudpcStatusDetails.md to cloudpcstatusdetails.md
  api-reference/beta/resources/cloudpcstatusdetails.md
Labels: external

#21947 Edits in PR 21559
  api-reference/beta/api/chat-list-permissiongrants.md
  api-reference/beta/api/group-list-permissiongrants.md
  api-reference/beta/api/team-list-permissiongrants.md
  api-reference/beta/api/teamsappsettings-update.md
  api-reference/beta/api/teamwork-sendactivitynotificationtorecipients.md
  api-reference/beta/api/user-list-permissiongrants.md
  api-reference/beta/api/userteamwork-post-installedapps.md
  api-reference/beta/api/userteamwork-sendactivitynotification.md
  api-reference/beta/api/userteamwork-teamsappinstallation-upgrade.md
  api-reference/beta/resources/teamsappsettings.md
  api-reference/beta/resources/user.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/userteamwork-post-installedapps.md
  api-reference/v1.0/api/userteamwork-teamsappinstallation-upgrade.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.Teams.Core.json
  concepts/includes/permissions-ids.md
  concepts/permissions-reference.md
Labels: external

#21077 [Doc Improvement][Note updated in list tabs channel][3139503]
  api-reference/beta/api/channel-list-tabs.md
Labels: do not merge, ready to merge, internal, content review complete

#21944 Minor doc fixes
  api-reference/beta/resources/privilegedidentitymanagementv3-overview.md
  api-reference/beta/toc.yml
Labels: area: Azure AD, ready to merge, internal

#21955 Update ToU owner
  api-reference/beta/api/agreement-delete.md
  api-reference/beta/api/agreement-get.md
  api-reference/beta/api/agreement-list-acceptances.md
  api-reference/beta/api/agreement-list-files.md
  api-reference/beta/api/agreement-post-files.md
  api-reference/beta/api/agreement-update.md
  api-reference/beta/api/agreementfile-get.md
  api-reference/beta/api/termsofusecontainer-list-agreements.md
  api-reference/beta/api/termsofusecontainer-post-agreements.md
  api-reference/beta/api/user-list-agreementacceptances.md
  api-reference/beta/includes/rbac-for-apis/rbac-tou-apis.md
  api-reference/beta/resources/agreement.md
  api-reference/beta/resources/agreementacceptance.md
  api-reference/beta/resources/agreementfile.md
  api-reference/beta/resources/agreementfiledata.md
  api-reference/beta/resources/agreementfilelocalization.md
  api-reference/beta/resources/agreementfileproperties.md
  api-reference/beta/resources/termsOfUseContainer.md
  api-reference/beta/resources/termsexpiration.md
  api-reference/v1.0/api/agreement-delete.md
  api-reference/v1.0/api/agreement-get.md
  api-reference/v1.0/api/agreement-list-acceptances.md
  api-reference/v1.0/api/agreement-list-files.md
  api-reference/v1.0/api/agreement-post-files.md
  api-reference/v1.0/api/agreement-update.md
  api-reference/v1.0/api/agreementfile-get.md
  api-reference/v1.0/api/termsofusecontainer-list-agreements.md
  api-reference/v1.0/api/termsofusecontainer-post-agreements.md
  api-reference/v1.0/api/user-list-agreementacceptances.md
  api-reference/v1.0/resources/agreement.md
  api-reference/v1.0/resources/agreementacceptance.md
  api-reference/v1.0/resources/agreementfile.md
  api-reference/v1.0/resources/agreementfiledata.md
  api-reference/v1.0/resources/agreementfilelocalization.md
  api-reference/v1.0/resources/agreementfileproperties.md
  api-reference/v1.0/resources/termsOfUseContainer.md
  api-reference/v1.0/resources/termsexpiration.md
Labels: ready to merge, internal

#19844 introduce a new set APIs to create/update/delete page sections
  api-reference/beta/api/horizontalsection-delete.md
  api-reference/beta/api/horizontalsection-get.md
  api-reference/beta/api/horizontalsection-update.md
  api-reference/beta/api/sitepage-post-horizontalsection.md
  api-reference/beta/api/sitepage-post-verticalsection.md
  api-reference/beta/api/verticalsection-delete.md
  api-reference/beta/api/verticalsection-get.md
  api-reference/beta/api/verticalsection-update.md
  api-reference/beta/resources/horizontalsection.md
  api-reference/beta/resources/verticalsection.md
  api-reference/beta/toc.yml
  changelog/Microsoft.FileServices.json
Labels: ready to merge, internal, content review complete, review feedback addressed

#21827 V1.0 documentation for List teams Graph API
  api-reference/v1.0/api/associatedteaminfo-list.md
  api-reference/v1.0/api/teams-list.md
  api-reference/v1.0/api/user-list-joinedteams.md
  api-reference/v1.0/resources/team.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.Teams.Core.json
Labels: ready to merge

#21244 Added dynamicColumnValue complex type to advanced hunting API
  api-reference/beta/resources/security-dynamiccolumnvalue.md
  api-reference/v1.0/resources/security-dynamiccolumnvalue.md
  changelog/Microsoft.M365.Defender.json
Labels: ready to merge, internal, content review complete

#21959 Edits in PR 21559
  changelog/Microsoft.Teams.Core.json
Labels: external

#21945 Update booleancolumn.md
  api-reference/v1.0/resources/booleancolumn.md
Labels: external

#21528 Change teamworkdevices - Add enum type : sipAnalog
  api-reference/beta/resources/teamworkdevice.md
  changelog/Microsoft.Teams.GraphSvc.json
Labels: ready to merge, internal, content review complete

#21636 Updating national cloud availability
  concepts/delta-query-overview.md
Labels: ready to merge, internal, content review complete

#21962 Update cloudpcprovisioningpolicy-assign.md
  api-reference/beta/api/cloudpcprovisioningpolicy-assign.md
Labels: ready to merge, internal

#21963 Update user-findmeetingtimes.md
  api-reference/beta/api/user-findmeetingtimes.md
Labels: ready to merge, internal

#21965 Update conversationthread-update.md
  api-reference/beta/api/conversationthread-update.md
Labels: ready to merge, internal

#21538 Adding SLA attainment
  api-reference/beta/api/azureadauthentication-get.md
  api-reference/beta/resources/azureadauthentication.md
  api-reference/beta/resources/reportroot.md
  api-reference/beta/resources/servicelevelagreementattainment.md
  api-reference/beta/resources/servicelevelagreementroot.md
  changelog/Microsoft.AAD.Reporting.json
Labels: area: Azure AD, ready to merge, internal, content review complete

#21972 Update what's new topic with more June items.
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
  concepts/whats-new-overview.md
Labels: do not merge, internal

#21973 Update what's new topic with some more June items.
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
  concepts/whats-new-overview.md
Labels: internal

#21711 Add support to the single connection Interleaving in Search API
  concepts/search-concept-interleaving.md
Labels: ready to merge, internal, content review complete

#21938 07 05 22 jupetter authmethods
  api-reference/beta/api/authentication-post-emailmethods.md
  api-reference/beta/api/authentication-post-phonemethods.md
  api-reference/beta/api/emailauthenticationmethod-update.md
  api-reference/beta/api/phoneauthenticationmethod-update.md
  api-reference/v1.0/api/authentication-post-emailmethods.md
  api-reference/v1.0/api/authentication-post-phonemethods.md
  api-reference/v1.0/api/emailauthenticationmethod-update.md
  api-reference/v1.0/api/phoneauthenticationmethod-update.md
Labels: area: Azure AD, ready to merge, internal, area: authentication methods, content review complete

#21334 Add awaitingAction enum value to incidentStatus enum
  api-reference/beta/resources/security-incident.md
  api-reference/v1.0/resources/security-incident.md
  changelog/Microsoft.M365.Defender.json
Labels: ready to merge, internal, content review complete

#21404 Update Pronouns admin settings
  .openpublishing.publish.config.json
  api-reference/beta/api/organizationsettings-list-pronounssettings.md
  api-reference/beta/api/peopleadminsettings-list-pronouns.md
  api-reference/beta/api/pronounssettings-update.md
  api-reference/beta/resources/organizationsettings.md
  api-reference/beta/resources/peopleadminsettings.md
  api-reference/beta/resources/pronounssettings.md
  api-reference/beta/toc.yml
  changelog/Microsoft.People.json
  concepts/permissions-reference.md
  concepts/pronouns-configure-pronouns-availability.md
  redirects/.openpublishing.redirection.0523.json
Labels: ready to merge, internal, content review complete

#21605 Changes for rsc app installation support in v1.0
  api-reference/beta/api/team-teamsappinstallation-upgrade.md
  api-reference/v1.0/api/appcatalogs-list-teamsapps.md
  api-reference/v1.0/api/chat-get-installedapps.md
  api-reference/v1.0/api/chat-list-installedapps.md
  api-reference/v1.0/api/chat-post-installedapps.md
  api-reference/v1.0/api/chat-teamsappinstallation-upgrade.md
  api-reference/v1.0/api/team-get-installedapps.md
  api-reference/v1.0/api/team-list-installedapps.md
  api-reference/v1.0/api/team-post-installedapps.md
  api-reference/v1.0/api/team-teamsappinstallation-upgrade.md
  api-reference/v1.0/resources/teamsappauthorization.md
  api-reference/v1.0/resources/teamsappdefinition.md
  api-reference/v1.0/resources/teamsappinstallation.md
  api-reference/v1.0/resources/teamsapppermissionset.md
  api-reference/v1.0/resources/teamsappresourcespecificpermission.md
  changelog/Microsoft.Teams.GraphSvc.json
Labels: ready to merge, internal, content review complete, schema live

#21998 Add one item to what's new topic.
  api-reference/beta/resources/privilegedidentitymanagementv3-overview.md
  api-reference/beta/resources/unifiedrolemanagementalert.md
  api-reference/beta/resources/unifiedrolemanagementalertconfiguration.md
  api-reference/beta/resources/unifiedrolemanagementalertdefinition.md
  api-reference/beta/resources/unifiedrolemanagementalertincident.md
  concepts/whats-new-overview.md
Labels: do not merge, internal

#21999 Refresh what's new topic.
  api-reference/beta/resources/privilegedidentitymanagementv3-overview.md
  api-reference/beta/resources/unifiedrolemanagementalert.md
  api-reference/beta/resources/unifiedrolemanagementalertconfiguration.md
  api-reference/beta/resources/unifiedrolemanagementalertdefinition.md
  api-reference/beta/resources/unifiedrolemanagementalertincident.md
  concepts/whats-new-overview.md
Labels: internal

#22013 Update and rename devicesFilter.md to devicesfilter.md
  api-reference/beta/resources/devicesfilter.md
Labels: external

#22012 Update and rename decisionItemPrincipalResourceMembership.md to decisionitemprincipalresourcemembership.md
  api-reference/beta/resources/decisionitemprincipalresourcemembership.md
Labels: external

#22010 Update complianceinformation.md
  api-reference/v1.0/resources/complianceinformation.md
Labels: external

#21635 Added behavior note for empty results containing odata.nextLink
  concepts/delta-query-overview.md
Labels: area: Azure AD, ready to merge, content review complete, area: change tracking

#22001 Minor doc fixes
  api-reference/beta/resources/directoryaudit.md
  api-reference/v1.0/resources/directoryaudit.md
Labels: area: Azure AD, ready to merge

#22002 Update conversation-post-threads.md
  api-reference/beta/api/conversation-post-threads.md
Labels: ready to merge, internal

#21209 Update custom-connector-sdk-testapp.md
  concepts/custom-connector-sdk-testapp.md
Labels: ready to merge, internal, content review complete

#22005 Updates MGT caching documentation to v3
  concepts/toolkit/customize-components/cache.md
  concepts/toolkit/images/indexedDBpanel.png
Labels: ready to merge, internal, content review complete

#22019 Edits in PR 21614
  api-reference/v1.0/api/user-list-calendargroups.md
  changelog/Microsoft.Exchange.json
Labels: external

#22029 Add `staffMemberIds` to bookingbusiness-post-appointments.md
  api-reference/v1.0/api/bookingbusiness-post-appointments.md
Labels: external

#22027 Edits in PR 21473
  api-reference/beta/api/subscription-post-subscriptions.md
  concepts/teams-changenotifications-calltranscript.md
  concepts/toc.yml
Labels: external

#22018 Edits in PR 21823
  api-reference/beta/api/cloudpcreports-getInaccessibleCloudPcReports.md
  api-reference/beta/api/cloudpcreports-getinaccessiblecloudpcreports.md
  api-reference/beta/resources/cloudpcreports.md
  api-reference/beta/toc.yml
  changelog/Microsoft.CloudManagedDesktop.json
Labels: external

#21184 Restructuring the 'National cloud implementation differences' topic
  api-reference/beta/api/channel-provisionemail.md
  api-reference/v1.0/api/channel-provisionemail.md
  concepts/teamwork-national-cloud-differences.md
Labels: ready to merge, internal, content review complete

#22020 Update learningcourseactivity-update.md
  api-reference/v1.0/api/learningcourseactivity-update.md
Labels: ready to merge, internal

#22021 Update user-revokesigninsessions.md
  api-reference/beta/api/user-revokesigninsessions.md
Labels: ready to merge, internal

#22022 Update attacksimulationroot-post-simulation.md
  api-reference/beta/api/attacksimulationroot-post-simulation.md
Labels: ready to merge, internal

#22023 Update security-ediscoverycase-post-legalholds.md
  api-reference/beta/api/security-ediscoverycase-post-legalholds.md
Labels: ready to merge, internal

#22026 http example added
  api-reference/v1.0/api/security-ediscoveryreviewset-export.md
  api-reference/v1.0/api/security-ediscoveryreviewsetquery-export.md
Labels: ready to merge, internal, content review complete

#22032 Minor doc fixes
  api-reference/beta/resources/extensionproperty.md
  api-reference/v1.0/resources/extensionproperty.md
  concepts/known-issues.md
Labels: area: Azure AD, ready to merge, internal

#22040 Updated rule to assign Entra PRs to Faith
  .github/policies/resourceManagement.yml
Labels: ready to merge, internal

#22044 Edits in PR 21997
  api-reference/beta/api/callrecording-get.md
  api-reference/beta/api/onlinemeeting-list-recordings.md
  api-reference/beta/api/onlinemeeting-list-transcripts.md
  api-reference/beta/resources/callrecording.md
  api-reference/beta/resources/onlinemeeting.md
  api-reference/beta/toc.yml
  changelog/Microsoft.Skype.Calling.json
  changelog/Microsoft.Teams.GraphSvc.json
  concepts/permissions-reference.md
Labels: external

#22055 Update chatinfo.md
  api-reference/v1.0/resources/chatinfo.md
Labels: external

#22054 Rename chatInfo.md to chatinfo.md
  api-reference/beta/resources/chatinfo.md
Labels: external

#20977 Pages API phase 2 release
  api-reference/beta/api/basesitepage-delete.md
  api-reference/beta/api/basesitepage-get.md
  api-reference/beta/api/basesitepage-list.md
  api-reference/beta/api/horizontalsection-delete.md
  api-reference/beta/api/horizontalsection-get.md
  api-reference/beta/api/horizontalsection-list.md
  api-reference/beta/api/horizontalsection-update.md
  api-reference/beta/api/horizontalsectioncolumn-get.md
  api-reference/beta/api/horizontalsectioncolumn-list.md
  api-reference/beta/api/sitepage-create-webpart.md
  api-reference/beta/api/sitepage-create.md
  api-reference/beta/api/sitepage-get.md
  api-reference/beta/api/sitepage-getwebpartsbyposition.md
  api-reference/beta/api/sitepage-list.md
  api-reference/beta/api/sitepage-post-horizontalsection.md
  api-reference/beta/api/sitepage-post-verticalsection.md
  api-reference/beta/api/sitepage-publish.md
  api-reference/beta/api/sitepage-update.md
  api-reference/beta/api/verticalsection-delete.md
  api-reference/beta/api/verticalsection-get.md
  api-reference/beta/api/verticalsection-update.md
  api-reference/beta/api/webpart-delete.md
  api-reference/beta/api/webpart-get.md
  api-reference/beta/api/webpart-getposition.md
  api-reference/beta/api/webpart-list.md
  api-reference/beta/api/webpart-update.md
  api-reference/beta/resources/basesitepage.md
  api-reference/beta/resources/site.md
  api-reference/beta/resources/sitepage.md
  api-reference/beta/resources/webpart.md
  api-reference/beta/toc.yml
  changelog/Microsoft.FileServices.json
Labels: ready to merge, internal

#22034 Update application-post-tokenlifetimepolicies.md
  api-reference/beta/api/application-list-tokenlifetimepolicies.md
  api-reference/beta/api/application-post-tokenlifetimepolicies.md
  api-reference/v1.0/api/application-list-tokenlifetimepolicies.md
  api-reference/v1.0/api/application-post-tokenlifetimepolicies.md
  api-reference/v1.0/api/tokenlifetimepolicy-list.md
Labels: area: Azure AD, external, ready to merge, content review complete

#22053 fixing wrong endpoint in example
  api-reference/v1.0/api/table-post-rows.md
  api-reference/v1.0/api/tablerowcollection-itemat.md
  concepts/workbook-best-practice.md
Labels: do not merge, ready to merge, internal

#22057 Fixed typo in intelligenceprofileindicator-get Graph API documentation page
  api-reference/beta/api/security-intelligenceprofileindicator-get.md
Labels: ready to merge, ready for content review, internal

#22059 Merge to publish.
  api-reference/beta/api/application-list-tokenlifetimepolicies.md
  api-reference/beta/api/application-post-tokenlifetimepolicies.md
  api-reference/beta/api/basesitepage-delete.md
  api-reference/beta/api/basesitepage-get.md
  api-reference/beta/api/basesitepage-list.md
  api-reference/beta/api/horizontalsection-delete.md
  api-reference/beta/api/horizontalsection-get.md
  api-reference/beta/api/horizontalsection-list.md
  api-reference/beta/api/horizontalsection-update.md
  api-reference/beta/api/horizontalsectioncolumn-get.md
  api-reference/beta/api/horizontalsectioncolumn-list.md
  api-reference/beta/api/security-intelligenceprofileindicator-get.md
  api-reference/beta/api/sitepage-create-webpart.md
  api-reference/beta/api/sitepage-create.md
  api-reference/beta/api/sitepage-get.md
  api-reference/beta/api/sitepage-getwebpartsbyposition.md
  api-reference/beta/api/sitepage-list.md
  api-reference/beta/api/sitepage-post-horizontalsection.md
  api-reference/beta/api/sitepage-post-verticalsection.md
  api-reference/beta/api/sitepage-publish.md
  api-reference/beta/api/sitepage-update.md
  api-reference/beta/api/verticalsection-delete.md
  api-reference/beta/api/verticalsection-get.md
  api-reference/beta/api/verticalsection-update.md
  api-reference/beta/api/webpart-delete.md
  api-reference/beta/api/webpart-get.md
  api-reference/beta/api/webpart-getposition.md
  api-reference/beta/api/webpart-list.md
  api-reference/beta/api/webpart-update.md
  api-reference/beta/resources/basesitepage.md
  api-reference/beta/resources/chatinfo.md
  api-reference/beta/resources/site.md
  api-reference/beta/resources/sitepage.md
  api-reference/beta/resources/webpart.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/application-list-tokenlifetimepolicies.md
  api-reference/v1.0/api/application-post-tokenlifetimepolicies.md
  api-reference/v1.0/api/table-post-rows.md
  api-reference/v1.0/api/tablerowcollection-itemat.md
  api-reference/v1.0/api/tokenlifetimepolicy-list.md
  api-reference/v1.0/resources/chatinfo.md
  changelog/Microsoft.FileServices.json
  concepts/workbook-best-practice.md
Labels: do not merge, internal

#22064 Continue to add June items to what's new topic.
  api-reference/beta/resources/unifiedrolemanagementalert.md
  changelog/Microsoft.ThreatIntelligence.json
  concepts/whats-new-overview.md
Labels: do not merge, internal

#22071 Correct error that DirectoryRole supports $count/$search
  api-reference/beta/api/directoryrole-list.md
Labels: external

#21990 Update TOC to include SLA
  api-reference/beta/toc.yml
Labels: area: Entra, ready to merge, internal, content review complete, review feedback addressed

#21996 Fix Example 2 payload in Add Member to Channel
  api-reference/beta/api/channel-post-members.md
  api-reference/v1.0/api/channel-post-members.md
Labels: ready to merge, internal, content review complete

#22048 Document known issue bug 18185
  concepts/search-query-parameter.md
Labels: area: Entra, ready to merge, area: query parameters, potential known issue

#22062 Correction to description of Application.ReadWrite.OwnedBy
  concepts/permissions-reference.md
Labels: ready to merge, internal

#22065 Minor doc fixes
  api-reference/beta/api/agreement-list-files.md
  api-reference/beta/api/agreementfile-get.md
  api-reference/beta/api/agreementfile-list-localizations.md
  api-reference/beta/api/domain-update.md
  api-reference/beta/api/user-list.md
  api-reference/beta/resources/agreementfile.md
  api-reference/beta/resources/agreementfilelocalization.md
  api-reference/beta/resources/agreementfileproperties.md
  api-reference/beta/resources/domain.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/agreement-list-files.md
  api-reference/v1.0/api/agreementfile-get.md
  api-reference/v1.0/api/agreementfile-list-localizations.md
  api-reference/v1.0/api/domain-update.md
  api-reference/v1.0/api/user-list.md
  api-reference/v1.0/resources/agreementfile.md
  api-reference/v1.0/resources/agreementfilelocalization.md
  api-reference/v1.0/resources/agreementfileproperties.md
  api-reference/v1.0/resources/domain.md
  api-reference/v1.0/toc.yml
  concepts/aad-advanced-queries.md
Labels: area: Entra, ready to merge, internal

#22073 Fixed intelProfileIndicators documentation error in v1.0 Microsoft Graph documentation
  api-reference/v1.0/api/security-intelligenceprofileindicator-get.md
Labels: ready to merge, ready for content review, internal

#22075 Updated TOC and redirects to point to the new known issues site
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
  concepts/index.yml
  concepts/toc.yml
  redirects/.openpublishing.redirection.0723.json
Labels: ready to merge, internal, content review complete

#22079 Merge to publish.
  api-reference/beta/api/agreement-list-files.md
  api-reference/beta/api/agreementfile-get.md
  api-reference/beta/api/agreementfile-list-localizations.md
  api-reference/beta/api/channel-post-members.md
  api-reference/beta/api/directoryrole-list.md
  api-reference/beta/api/domain-update.md
  api-reference/beta/api/user-list.md
  api-reference/beta/resources/agreementfile.md
  api-reference/beta/resources/agreementfilelocalization.md
  api-reference/beta/resources/agreementfileproperties.md
  api-reference/beta/resources/domain.md
  api-reference/beta/resources/unifiedrolemanagementalert.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/agreement-list-files.md
  api-reference/v1.0/api/agreementfile-get.md
  api-reference/v1.0/api/agreementfile-list-localizations.md
  api-reference/v1.0/api/channel-post-members.md
  api-reference/v1.0/api/domain-update.md
  api-reference/v1.0/api/security-intelligenceprofileindicator-get.md
  api-reference/v1.0/api/user-list.md
  api-reference/v1.0/resources/agreementfile.md
  api-reference/v1.0/resources/agreementfilelocalization.md
  api-reference/v1.0/resources/agreementfileproperties.md
  api-reference/v1.0/resources/domain.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.ThreatIntelligence.json
  concepts/aad-advanced-queries.md
  concepts/index.yml
  concepts/permissions-reference.md
  concepts/search-query-parameter.md
  concepts/toc.yml
  concepts/whats-new-overview.md
  redirects/.openpublishing.redirection.0723.json
Labels: internal

#22080 Add a couple of items to what's new topic.
  api-reference/beta/toc.yml
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: do not merge, internal

#22103 Remove en-us from links
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
  concepts/toc.yml
Labels: internal

#22102 Refresh what's new topic with a couple of items.
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
  concepts/toc.yml
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: do not merge, internal

#21974 Edits in PR 21730
  api-reference/beta/resources/security-alertevidence.md
  api-reference/beta/resources/security-blobcontainerevidence.md
  api-reference/beta/resources/security-blobevidence.md
  api-reference/beta/resources/security-containerevidence.md
  api-reference/beta/resources/security-containerimageevidence.md
  api-reference/beta/resources/security-containerregistryevidence.md
  api-reference/beta/resources/security-dictionary.md
  api-reference/beta/resources/security-filehash.md
  api-reference/beta/resources/security-kubernetesclusterevidence.md
  api-reference/beta/resources/security-kubernetescontrollerevidence.md
  api-reference/beta/resources/security-kubernetesnamespaceevidence.md
  api-reference/beta/resources/security-kubernetespodevidence.md
  api-reference/beta/resources/security-kubernetessecretevidence.md
  api-reference/beta/resources/security-kubernetesserviceaccountevidence.md
  api-reference/beta/resources/security-kubernetesserviceevidence.md
  api-reference/beta/resources/security-kubernetesserviceport.md
  api-reference/beta/toc.yml
  api-reference/v1.0/resources/security-alertevidence.md
  api-reference/v1.0/resources/security-blobcontainerevidence.md
  api-reference/v1.0/resources/security-blobevidence.md
  api-reference/v1.0/resources/security-containerevidence.md
  api-reference/v1.0/resources/security-containerimageevidence.md
  api-reference/v1.0/resources/security-containerregistryevidence.md
  api-reference/v1.0/resources/security-dictionary.md
  api-reference/v1.0/resources/security-filehash.md
  api-reference/v1.0/resources/security-kubernetesclusterevidence.md
  api-reference/v1.0/resources/security-kubernetescontrollerevidence.md
  api-reference/v1.0/resources/security-kubernetesnamespaceevidence.md
  api-reference/v1.0/resources/security-kubernetespodevidence.md
  api-reference/v1.0/resources/security-kubernetessecretevidence.md
  api-reference/v1.0/resources/security-kubernetesserviceaccountevidence.md
  api-reference/v1.0/resources/security-kubernetesserviceevidence.md
  api-reference/v1.0/resources/security-kubernetesserviceport.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.M365.Defender.json
Labels: external

#22110 Edits in PR 21988
  api-reference/beta/resources/windowsupdates-buildversiondetails.md
  api-reference/beta/resources/windowsupdates-cveinformation.md
  api-reference/beta/resources/windowsupdates-featureupdatecatalogentry.md
  api-reference/beta/resources/windowsupdates-knowledgebasearticle.md
  api-reference/beta/resources/windowsupdates-monitoringrule.md
  api-reference/beta/resources/windowsupdates-productrevision.md
  api-reference/beta/resources/windowsupdates-qualityupdatecatalogentry.md
  api-reference/beta/resources/windowsupdates-qualityupdatecveseverityinformation.md
Labels: external, ready to merge, content review complete

#22123 fix#21685
  api-reference/beta/resources/apiapplication.md
  api-reference/v1.0/resources/apiapplication.md
Labels: area: Entra, ready to merge, internal, area: applications

#22122 Permissions GUIDs update - July drop
  concepts/includes/permissions-ids.md
Labels: area: Entra, ready to merge, internal, area: permissions

#22097 fix #21098
  concepts/filter-query-parameter.md
Labels: area: Entra, ready to merge, internal, area: query parameters

#21166 Public preview documentation for sponsors
  api-reference/beta/api/user-delete-sponsors.md
  api-reference/beta/api/user-list-sponsors.md
  api-reference/beta/api/user-post-sponsors.md
  api-reference/beta/resources/approvalstage.md
  api-reference/beta/resources/entitlementmanagement-overview.md
  api-reference/beta/resources/invitation.md
  api-reference/beta/resources/targetusersponsors.md
  api-reference/beta/resources/user.md
  api-reference/beta/resources/userset.md
  api-reference/beta/toc.yml
  changelog/Microsoft.AADInviteMgr.json
  changelog/Microsoft.DirectoryServices.json
  changelog/Microsoft.IGAELM.json
Labels: area: Entra, ready to merge, internal, content review complete

#20804 Subscriptions API and SubscribedSkus API
  api-reference/beta/api/companysubscription-get.md
  api-reference/beta/api/directory-list-subscriptions.md
  api-reference/beta/api/subscribedsku-get.md
  api-reference/beta/api/subscribedsku-list.md
  api-reference/beta/resources/companysubscription.md
  api-reference/beta/resources/directory.md
  api-reference/beta/resources/licenseunitsdetail.md
  api-reference/beta/resources/subscribedsku.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/subscribedsku-get.md
  api-reference/v1.0/api/subscribedsku-list.md
  api-reference/v1.0/resources/directory.md
  api-reference/v1.0/resources/licenseunitsdetail.md
  api-reference/v1.0/resources/subscribedsku.md
  changelog/Microsoft.DirectoryServices.json
Labels: area: Entra, ready to merge, internal, content review complete

#20747 Deprecating previous custom extension modles
  api-reference/beta/api/accesspackageassignmentrequest-get.md
  api-reference/beta/resources/customaccesspackageworkflowextension.md
  api-reference/beta/resources/customextensionclientconfiguration.md
  api-reference/beta/resources/customextensionhandler.md
  api-reference/beta/resources/customextensionhandlerinstance.md
  api-reference/beta/toc.yml
  changelog/Microsoft.IGAELM.json
Labels: area: Entra, ready to merge, internal, content review complete, area: governance, invalid links

#22127 Daily publishing July 18th, 2023
  api-reference/beta/api/accesspackageassignmentrequest-get.md
  api-reference/beta/api/companysubscription-get.md
  api-reference/beta/api/directory-list-subscriptions.md
  api-reference/beta/api/subscribedsku-get.md
  api-reference/beta/api/subscribedsku-list.md
  api-reference/beta/api/user-delete-sponsors.md
  api-reference/beta/api/user-list-sponsors.md
  api-reference/beta/api/user-post-sponsors.md
  api-reference/beta/resources/apiapplication.md
  api-reference/beta/resources/approvalstage.md
  api-reference/beta/resources/companysubscription.md
  api-reference/beta/resources/customaccesspackageworkflowextension.md
  api-reference/beta/resources/customextensionclientconfiguration.md
  api-reference/beta/resources/customextensionhandler.md
  api-reference/beta/resources/customextensionhandlerinstance.md
  api-reference/beta/resources/directory.md
  api-reference/beta/resources/entitlementmanagement-overview.md
  api-reference/beta/resources/invitation.md
  api-reference/beta/resources/licenseunitsdetail.md
  api-reference/beta/resources/subscribedsku.md
  api-reference/beta/resources/targetusersponsors.md
  api-reference/beta/resources/user.md
  api-reference/beta/resources/userset.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/subscribedsku-get.md
  api-reference/v1.0/api/subscribedsku-list.md
  api-reference/v1.0/resources/apiapplication.md
  api-reference/v1.0/resources/directory.md
  api-reference/v1.0/resources/licenseunitsdetail.md
  api-reference/v1.0/resources/subscribedsku.md
  changelog/Microsoft.AADInviteMgr.json
  changelog/Microsoft.DirectoryServices.json
  changelog/Microsoft.IGAELM.json
  concepts/filter-query-parameter.md
  concepts/includes/permissions-ids.md
Labels: internal

#22109 Continue to add new items to what's new topic.
  api-reference/beta/api/security-ediscoveryreviewsetquery-export.md
  api-reference/v1.0/api/security-ediscoveryreviewsetquery-export.md
  changelog/Microsoft.PrintService.json
  changelog/Microsoft.ThreatIntelligence.json
  concepts/whats-new-overview.md
Labels: do not merge, internal

#22136 Refresh what's new topic with the remaining items in June.
  api-reference/beta/api/security-ediscoveryreviewsetquery-export.md
  api-reference/v1.0/api/security-ediscoveryreviewsetquery-export.md
  changelog/Microsoft.PrintService.json
  changelog/Microsoft.ThreatIntelligence.json
  concepts/whats-new-overview.md
Labels: internal

#22132 Edits in PR 21730
  api-reference/beta/resources/security-kubernetesclusterevidence.md
  api-reference/v1.0/resources/security-kubernetesclusterevidence.md
Labels: external

#22157 Update Microsoft.Security.Ediscovery.json
  changelog/Microsoft.Security.Ediscovery.json
Labels: ready to merge, internal

#22141 Add July items to what's new topic.
  api-reference/beta/api/sitepage-create-webpart.md
  api-reference/beta/toc.yml
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: do not merge, internal

#22133 Edits in PR 21642
  api-reference/beta/resources/devicemanagement-alertrecord.md
  api-reference/beta/resources/devicemanagement-alertrule.md
  changelog/Microsoft.DeviceManagement.Monitoring.json
Labels: external

#22173 Fix syntax error in beta TOC
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
Labels: do not merge, internal

#22178 TOC Cleanup
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
Labels: internal

#22168 Refresh what's new topic with a few July items.
  api-reference/beta/api/sitepage-create-webpart.md
  api-reference/beta/toc.yml
  api-reference/v1.0/toc.yml
  changelog/Microsoft.Security.Ediscovery.json
  concepts/whats-new-earlier.md
  concepts/whats-new-overview.md
Labels: do not merge, internal

#22224 Extract non-TOC file updates from PR #22203 so to update what's new topic and isolate TOC display problem on staging site.
  api-reference/beta/api/user-delete-sponsors.md
  api-reference/beta/api/user-post-sponsors.md
  api-reference/beta/resources/companysubscription.md
  api-reference/beta/resources/message.md
  api-reference/beta/resources/subscribedsku.md
  api-reference/v1.0/resources/subscribedsku.md
  changelog/Microsoft.People.json
  concepts/whats-new-overview.md
Labels: do not merge, internal

#22226 Refresh what's new topic with remaining July updates as of 7/22.
  api-reference/beta/api/user-delete-sponsors.md
  api-reference/beta/api/user-post-sponsors.md
  api-reference/beta/resources/companysubscription.md
  api-reference/beta/resources/message.md
  api-reference/beta/resources/subscribedsku.md
  api-reference/v1.0/resources/subscribedsku.md
  changelog/Microsoft.People.json
  concepts/whats-new-overview.md
Labels: internal

#22188 Edits in PR 21988
  api-reference/beta/resources/enums-windowsupdates.md
  api-reference/beta/resources/windowsupdates-knowledgebasearticle.md
  api-reference/beta/resources/windowsupdates-qualityupdatecveseverityinformation.md
  changelog/Microsoft.WindowsUpdates.json
Labels: external

#21995 Fix typo approleassignment.md
  api-reference/v1.0/resources/approleassignment.md
Labels: external

#22093 Update Microsoft.SubscriptionServices.json
  changelog/Microsoft.SubscriptionServices.json
  concepts/teams-changenotifications-callrecording-and-calltranscript.md
Labels: external

#22114 Update calltranscript.md
  api-reference/beta/resources/calltranscript.md
Labels: external

#22115 Update externalmeetingregistration.md
  api-reference/beta/resources/externalmeetingregistration.md
Labels: external

#22169 Update basesitepage-delete.md
  api-reference/beta/api/basesitepage-delete.md
Labels: external

#22170 Update basesitepage.md
  api-reference/beta/resources/basesitepage.md
Labels: external

#22210 Update opentypeextension-delete.md
  api-reference/beta/api/opentypeextension-delete.md
Labels: external

#22211 Update opentypeextension-delete.md
  api-reference/v1.0/api/opentypeextension-delete.md
Labels: external

#22212 Update outlookcategory-delete.md
  api-reference/beta/api/outlookcategory-delete.md
Labels: external

#22213 Update outlookcategory-delete.md
  api-reference/v1.0/api/outlookcategory-delete.md
Labels: external

#22214 Update devicemanagement-alertimpact.md
  api-reference/beta/resources/devicemanagement-alertimpact.md
Labels: external

#22230 Add "Manager" as a valid value for `accessReviewSettings.reviewType`
  api-reference/beta/resources/assignmentreviewsettings.md
Labels: external

#22143 Minor doc fixes
  api-reference/beta/api/accessreviewinstance-update.md
  api-reference/beta/api/device-update.md
  api-reference/beta/api/directoryaudit-get.md
  api-reference/beta/api/directoryaudit-list.md
  api-reference/beta/api/invitation-post.md
  api-reference/beta/api/oauth2permissiongrant-post.md
  api-reference/beta/api/provisioningobjectsummary-list.md
  api-reference/beta/api/signin-list.md
  api-reference/beta/resources/accesspackagesubject.md
  api-reference/beta/resources/directoryaudit.md
  api-reference/beta/resources/invitation.md
  api-reference/beta/resources/invitedusermessageinfo.md
  api-reference/beta/resources/oauth2permissiongrant.md
  api-reference/beta/resources/privilegedidentitymanagementv3-overview.md
  api-reference/beta/resources/provisionedidentity.md
  api-reference/beta/resources/provisioningobjectsummary.md
  api-reference/beta/resources/provisioningstatusinfo.md
  api-reference/beta/resources/provisioningsystem.md
  api-reference/beta/resources/signin.md
  api-reference/beta/resources/statusbase.md
  api-reference/beta/resources/subscription.md
  api-reference/beta/resources/unifiedrolemanagementalert.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/accessreviewinstance-update.md
  api-reference/v1.0/api/device-update.md
  api-reference/v1.0/api/directoryaudit-get.md
  api-reference/v1.0/api/directoryaudit-list.md
  api-reference/v1.0/api/invitation-post.md
  api-reference/v1.0/api/oauth2permissiongrant-post.md
  api-reference/v1.0/api/provisioningobjectsummary-list.md
  api-reference/v1.0/api/signin-list.md
  api-reference/v1.0/resources/directoryaudit.md
  api-reference/v1.0/resources/invitation.md
  api-reference/v1.0/resources/invitedusermessageinfo.md
  api-reference/v1.0/resources/oauth2permissiongrant.md
  api-reference/v1.0/resources/provisionedidentity.md
  api-reference/v1.0/resources/provisioningobjectsummary.md
  api-reference/v1.0/resources/signin.md
  api-reference/v1.0/resources/subscription.md
  api-reference/v1.0/toc.yml
  changelog/Microsoft.AAD.Reporting.json
  concepts/auth-v2-service.md
  concepts/auth-v2-user.md
  concepts/auth/auth-concepts.md
  concepts/extensibility-overview.md
  concepts/json-batching.md
  concepts/permissions-grant-via-msgraph.md
  concepts/use-the-api.md
  concepts/webhooks.md
Labels: area: Entra, ready to merge, internal

#22181 Reporting TOC fix
  api-reference/v1.0/resources/identitygovernance-lifecycleworkflows-reporting-overview.md
  api-reference/v1.0/toc.yml
Labels: ready to merge, internal

#22200 Fixing wrong HTTP method in externalItem-Update
  api-reference/beta/api/externalconnectors-externalitem-update.md
  api-reference/v1.0/api/externalconnectors-externalitem-update.md
Labels: ready to merge, internal

#22007 [Doc Improvement][Response code update][3140616]
  api-reference/beta/api/schedule-share.md
  api-reference/v1.0/api/schedule-share.md
Labels: ready to merge, internal, content review complete

#22108 Incorporated review comments
  api-reference/beta/api/synchronization-synchronizationjob-post-bulkupload.md
  api-reference/beta/resources/synchronization-bulkupload.md
Labels: area: Entra, ready to merge, internal, content review complete

#22179 Fixing examples in uploadSession
  api-reference/beta/api/driveitem-createuploadsession.md
  api-reference/v1.0/api/driveitem-createuploadsession.md
Labels: do not merge, ready to merge, internal

#22180 fixing delete example in Edu
  api-reference/v1.0/api/educationschool-delete-users.md
Labels: do not merge, ready to merge, internal

#22184 teams-app-update examples
  api-reference/beta/api/teamsapp-update.md
  api-reference/v1.0/api/teamsapp-update.md
Labels: do not merge, ready to merge, internal

#21058 [CloudPC] Add cloudPcInGracePeriodScenario in public alert doc
  api-reference/beta/api/devicemanagement-alertrule-post.md
  api-reference/beta/resources/devicemanagement-alertrecord.md
  api-reference/beta/resources/devicemanagement-alertrule.md
  api-reference/beta/resources/devicemanagement-portalnotification.md
  changelog/Microsoft.DeviceManagement.Monitoring.json
Labels: ready to merge, internal, content review complete

#21979 Adding examples for getAllSites API usage
  api-reference/beta/api/site-getallsites.md
  api-reference/beta/resources/site.md
  api-reference/beta/toc.yml
  api-reference/v1.0/api/site-getallsites.md
  api-reference/v1.0/resources/site.md
  api-reference/v1.0/toc.yml
Labels: ready to merge, internal, content review complete

#22236 Update directoryrole-list.md
  api-reference/v1.0/api/directoryrole-list.md
Labels: external

#22052 Made changes on the remove notes
  api-reference/beta/api/educationsubmission-reassign.md
  api-reference/beta/api/educationsubmission-submit.md
  api-reference/beta/api/educationsubmission-unsubmit.md
  api-reference/v1.0/api/educationsubmission-reassign.md
  api-reference/v1.0/api/educationsubmission-submit.md
  api-reference/v1.0/api/educationsubmission-unsubmit.md
Labels: ready to merge, internal, content review complete

#22177 Update table-post-rows.md
  api-reference/beta/api/table-post-rows.md
  api-reference/v1.0/api/table-post-rows.md
Labels: external

#22239 Edits in PR 21473
  changelog/Microsoft.SubscriptionServices.json
  concepts/teams-change-notification-in-microsoft-teams-overview.md
  concepts/toc.yml
Labels: external
